### ISSUE TITLE
cant resolve namespace member: spdlog::basic_logger_mt

### ISSUE THREAD

**Issue by Rich2020** [gabime/spdlog#1000]
Installed via Homebrew on Mac OS Mojave and get the following error: 
`Cant resolve namespace member: spdlog::basic_logger_mt`

**Comment by gabime** [comment]
you need to include basic_file_sink.h

**Comment by Rich2020** [comment]
Oh, sorry. I apologise; I did not see that in the example (it is there). Thank you for your help.

**Comment by gabime** [comment]
np. enjoy the logging
