### ISSUE TITLE
Logging an expression?

### ISSUE THREAD

**Issue by sssilver** [gabime/spdlog#1001]
It would be lovely if instead of:
```cpp
spdlog::info("powf(1.0f - damping, dt): {}", powf(1.0f - damping, dt))
```
we could just do:
```cpp
spdlog::info_expression(powf(1.0f - damping, dt))
```
And that would log both the expression and what value it evaluates to.

(obviously the interface for doing that could be better)

**Comment by gabime** [comment]
How can this be achieved without some kind of macro magic?

**Comment by sssilver** [comment]
I wouldn't mind if this were a macro, as long as that felt more like an implementation detail and was somewhat unobtrusive.

**Comment by DanielChabrowski** [comment]
Such logs wouldn't be very informative without looking to the source code. One would probably want to log "Distance between closest player: {}" rather than "math::distance(currentPos, otherPlayer.getPosition())" and not have to rely on line numbers that frequently change.

**Comment by ArnCarveris** [comment]
@DanielChabrowski Well, better replace `info` by `trace` that will results `spdlog::trace_expression`, but anyway the self-descriptive log is a lot better.

**Comment by sssilver** [comment]
@DanielChabrowski To your point about usefulness of such logs -- I suppose it largely depends on what the logs are being used for.

If they're being used to capture an ordinary log of operations on something like a production service running on some server, then you're definitely right.

In our case, we're primarily using it as an aid in debugging a video game while we're programming it. The vast majority of our logs have "debug" severity. Most of our logs will be deleted out once the game is packaged and shipped. We use them extensively to quickly generate text output to validate our calculations, make sure events get triggered, etc, while working on the project.

Perhaps it could be argued that the "right tool" for something like that are breakpoints and a debugger instead, but since the project is being developed on multiple platforms and with different compilers and IDEs at the same time, logs are quite a convenient, quick, and uniform mechanism for peeking at data while programming the game.

In the end, we end up defining such a macro for ourselves, and it has proven to be extremely useful. I imagine that if _spdlog_ were to offer such functionality out of the box, many programmers would have taken advantage of it.

**Comment by gabime** [comment]
> we end up defining such a macro for ourselves

Can you share it here?

**Comment by sssilver** [comment]
Sure --

**Comment by sssilver** [comment]
Sure -- we did a quick & dirty:

```cpp
#define LOG_VAR(var) LogD(#var ": {}", var);
```

Where `LogD()` is ultimately:

```cpp
void Logger::LogD(std::string&& str) const
{
    spdLogger->debug(str);
}
```

**Comment by gabime** [comment]
I could imagine adding a single macro to spdlg called SPDLG_DEBUG_EXPR(..) .
Just for debug level .. I guess thats the main usecase for this.

**Comment by tmarkovich** [comment]
We've done something similar internally to log a variable number of arguments at once:

```
#ifdef NDEBUG
#   define TRACER(...) (void)0
#   define STRTRACER(...) (void)0
#   define SPDDUMP(...) (void)0
#else
#   define TRACER(os, ...) trace_printer(os, std::begin(split_fn_names(NAMES(__VA_ARGS__))), __VA_ARGS__)
#   define STRTRACER(...) to_string(std::begin(split_fn_names(NAMES(__VA_ARGS__))), __VA_ARGS__)
#   define SPDDUMP(name, ...) SPDLOG_LOGGER_TRACE(spdlog::spdlog(name), to_string(std::begin(split_fn_names(NAMES(__VA_ARGS__))), __VA_ARGS__))
#   define NAMES(...) #__VA_ARGS__
#endif

inline void trace_printer(std::ostream& out, std::vector<std::string>::const_iterator name);

template <typename T1, typename T2>
std::ostream& operator<<(std::ostream& os, const std::pair<T1, T2>& p){
    os << "{" << p.first << ", " << p.second << "}";
    return os;
}

template <typename T>
std::ostream& operator<<(std::ostream& os, const std::vector<T>& container){
    for(const T& t: container)
        os << t << "\n";
    return os;
}

template <typename T>
std::ostream& operator<<(std::ostream& os, const std::set<T>& container){
    for(const T& t: container)
        os << t << "\n";
    return os;
}

template <typename T>
void trace_printer(std::ostream& out, std::vector<std::string>::const_iterator name, T t) {
    out << *name << ": " << t;
}

template <typename T, typename... Args>
void trace_printer(std::ostream& out, std::vector<std::string>::const_iterator name, T t, Args... args)
{
    out << *name << ": " << t << ", ";
    trace_printer(out, ++name, args...);
}

template <typename... Args>
std::string to_string(std::vector<std::string>::const_iterator name, Args... args){
    std::ostringstream os{};
    trace_printer(os, name, args...);
    return os.str();
}

std::vector<std::string> split_fn_names(const std::string& f){
    std::vector<std::string> out{};
    boost::split(out, f, [](char c){return std::isspace(c);});
    for(std::string& o: out) if(std::ispunct(o.back())) o.pop_back();
    return out;
}

std::string to_string(std::vector<std::string>::const_iterator name){
    std::ostringstream os;
    trace_printer(os, name);
    return os.str();
}

```

which ultimately means that we can call:
```
void func(stuff){
...
SPDDUMP("logger_name", a, b, c, d);
...
}
```

and it prints something like this to the terminal
```
[handler.cpp:858] a: 1, b: -1, c: 2, d: 0
```

I've sprinkled trace level statements throughout my code at places where I'd commonly set break points so that I can just change the log level and run with the problematic input as a nice first step in the debugging chain.

**Comment by gabime** [comment]
@tmarkovich Nicely done.

**Comment by tmarkovich** [comment]
thanks! I considered PRing it back to spdlog but I didn't want to introduce a boost dependency, and writing my own `split` method seemed less than fun.

**Comment by gabime** [comment]
I might borrow some of this code if thats ok with you.

**Comment by tmarkovich** [comment]
Please do

**Comment by sssilver** [comment]
Would it be possible to make this look a little less like a macro and a little more like a normal part of the spdlog interface? Or do you believe that would be misleading and not idiomatic?

**Comment by gabime** [comment]
you mean to name the macro with lower cases? would be misleading indeed

**Comment by tmarkovich** [comment]
I personally prefer macros to be all upper case as an indication that this "function" is dangerous, not type checked, and could involve significant unexpected magic.
