### ISSUE TITLE
Show full filepaths from log macros

### ISSUE THREAD

**Issue by dapirian** [gabime/spdlog#1002]
remove `SPDLOG_FILE_BASENAME` & usage from `spdlog.h`, if a user wants only `filename:line` they can achieve that in their formatter right? I work in a big repo and having just a filename is ambiguous versus the whole path.

**Comment by gabime** [comment]
Probably need to an option in tweakme.h to override this macro with something else.

**Comment by gabime** [comment]
Implemented as a new "%g" flag to the pattern formatter (full path name).
