### ISSUE TITLE
ERROR_SHARING_VIOLATION when stress testing logging on multiple threads

### ISSUE THREAD

**Issue by vshcherbyna** [gabime/spdlog#1003]
Hello,

I am using spdlog 1.1.0 and in my project I have multiple threads that are logging different log messages. The max file size is set to 32 Mb and after short time I see that the file rotation stops working because in rename method spdlog library experiences an error ERROR_SHARING_VIOLATION. Please see below screenshot:

![clipboard - february 22 2019 6-23 pm](https://user-images.githubusercontent.com/337059/53304744-1ff72680-3879-11e9-83fd-7c992e4899b8.png)

Is it a well-known issue? I am able to reproduce the problem each time I am doing some stress logging from multiple threads. My environment is VS 2017, spdlog 1.1.0, Windows 10 1809 Enterprise x64

**Comment by gabime** [comment]
please provide code to reproduce.
