### ISSUE TITLE
Is there a way to detect if a sink supports colors?

### ISSUE THREAD

**Issue by floouuu** [gabime/spdlog#1004]
Hey there,

I am trying to put context information (usually the class name) into the log output. I did this by prefixing the message with a "<Context>: " and it works as expected. However, now I tried to make the context information bold to enhance readability of the log outputs. My first attempt was to use console color codes like:
```c++
console_->log(logSeverityMapping_[r.severity], "\033[1m" + r.context.name() + ":\033[0m " + r.message);
```
where `r` is the log record of our framework that I want to log with spdlog. So, I just surrounded the context with escape chars to print it in bold. This works fine.

However, as soon as I pipe the output into a file, the escape chars get logged as well (no surprise here). So it would really nice to have a method in a sink that tells me if the sink supports colored output or not.

I saw that `ansicolor_sink` has a private member `should_do_colors_`. Would it make sense to provide this information to the outer world? So I could for example

```c++
auto console_sink = dynamic_cast<spdlog::sinks::stdout_color_sink_mt *>(console_->sinks().back().get());
```

and then check if the sink supports colors and modify the message accordingly.

Or is there a simpler method (other than re-writing spdlog source) to format the log message itself?

Sorry for the long text and thank you for your help!

Kind regards, Florian

**Comment by gabime** [comment]
I don’t mind to add a public function for this, but you could just copy the line that checks it:
 ```c++
should_ color = details::os::in_terminal(stdout) && details::os::is_color_terminal();
```

**Comment by floouuu** [comment]
Hi!

Thank you for your response. Yeah, that works too. I just felt a little bit uncomfortable to invoke things from the `details` namespace from outside.
But I can live with this :wink: 

Kind regards, Florian

**Comment by gabime** [comment]
You might want to open pr to expose this variable as public function (e.g. bool should_color())
