### ISSUE TITLE
spdlog can't write log files on android?

### ISSUE THREAD

**Issue by 1976277169** [gabime/spdlog#1006]
I use sinks to write log files, version is 1.3.1, code is: 
```c++
#include "spdlog/sinks/stdout_sinks.h"
#include "spdlog/sinks/rotating_file_sink.h"
#ifdef BUILD_ANDROID
#include "spdlog/sinks/android_sink.h"
#endif
    spd::logger* my_logger;
    std::vector<spd::sink_ptr> sinks;
    #ifdef __ANDROID__
    sinks.push_back(std::make_shared<spd::sinks::android_sink_mt>());
    #else
    sinks.push_back(std::make_shared<spd::sinks::stdout_sink_mt>());
    #endif
    sinks.push_back(std::make_shared<spd::sinks::rotating_file_sink_mt>(log_rotate_file.c_str(), 1024 * 1024 * 5, 5));

    my_logger = new spdlog::logger("gv", sinks.begin(), sinks.end());

    my_logger->set_level(spd::level::trace);
    sinks[0]->set_level(spd::level::trace); // console. Allow everything.  Default value
    sinks[1]->set_level(spd::level::trace); //  regular file. Allow everything.  Default value
```

   it can print log information, but the log files is empty.
![default](https://user-images.githubusercontent.com/18477929/53390048-d9b2dc00-39cc-11e9-8910-7972c91a30e7.png)
![default](https://user-images.githubusercontent.com/18477929/53390065-ea635200-39cc-11e9-9c9f-79d418f24837.png)
can you help me ? thx~@gabime

**Comment by gabime** [comment]
Try setting the flush level to trace too.

**Comment by 1976277169** [comment]
>  flush

can you tell me how to set flush level? thx a lot~

**Comment by gabime** [comment]
see the docs please

**Comment by 1976277169** [comment]
ok, thank you ~

**Comment by luqihua** [comment]
Have you solved this problem？I call "logger->flush_on(spdlog::level::trace);"  but it does’t work
