### ISSUE TITLE
No color when use spdlog::stderr_color_mt since 0.17.0

### ISSUE THREAD

**Issue by xyz1001** [gabime/spdlog#1007]
Today I update spdlog from v0.16.3 to lastest version. When I use spdlog v0.16.3, the log in terminal is color but lastest version  not.
![spdlog v1.3.1](https://user-images.githubusercontent.com/14332136/53396333-27384480-39df-11e9-868b-558bcaacbc5d.png)
![spdlog v0.16.3](https://user-images.githubusercontent.com/14332136/53396363-3a4b1480-39df-11e9-9b0d-ffc64cfc3241.png)
Then I tried other version (v0.17.0, v1.0.0, v1.2.1), but only v0.16.3 is colored.

Here is my environment

| | |
|--|--|
|os| manjaro deepin 18.0.2|
|terminal| deepin-terminal with tmux|
|shell| zsh|
|g++| 8.2.1|

**Comment by gabime** [comment]
You need to specify the color range in the log pattern see the wiki.

**Comment by xyz1001** [comment]
My problem is resolved. Thank you.
