### ISSUE TITLE
Get Exception stacktrace  as part of one log

### ISSUE THREAD

**Issue by PuneetPatwari** [gabime/spdlog#1008]
Hi

I am using execinfo.h to get the backtrace for any exception. The "backtrace_symbols()" method return a char** , an array of string. I was thinking if we can do something like 

`  SPDLOG_ERROR("Exception { }",backtrace_symbols(array, size));
`

so that the exception stack-trace can be logged as a part of the logging message. 

Is this possible?

**Comment by nbrachet** [comment]
You can also define your own formatting for `std::exception`. For example:
```
FMT_BEGIN_NAMESPACE

    // Extend fmt lib to support std::exception
    // see http://fmtlib.net/latest/api.html#formatting-user-defined-types
    //
    // Logs the exception message (`what()`) followed by the stack trace
    // (in DEBUG build).
    //
    // @usage:
    //   try { ... }
    //   catch (const std::exception& ex) {
    //     logger->error("exception caught: {}", ex);
    //   }

    template<>
    struct formatter<std::exception> {
        template<typename ParseContext>
        constexpr auto parse(ParseContext& ctx) { return ctx.begin(); }

        template<typename FormatContext>
        auto format(const std::exception& ex, FormatContext& ctx) {
            auto it = format_to(ctx.begin(), "{}", ex.what());
#ifndef NDEBUG
            boost::stacktrace::stacktrace st{12, static_cast<std::size_t>(-1)};
            if (st)
            {
                for (unsigned i = 0; i < st.size(); ++i)
                    it = format_to(it, "\n\t{:2d}# {}", i, boost::stacktrace::to_string(st[i]));
            }
#endif
            return it;
        }
    };

    template<>
    struct formatter<std::logic_error> : public formatter<std::exception> {};

    template<>
    struct formatter<std::runtime_error> : public formatter<std::exception> {};

    template<>
    struct formatter<std::bad_alloc> : public formatter<std::exception> {};

FMT_END_NAMESPACE
```

This code uses `boost::stacktrace` but you should be able to easily accommodate it to `backtrace_symbols`.

Unfortunately, you have to specialize each derived exception type you want to log.

**Comment by PuneetPatwari** [comment]
Hi @nbrachet , I like the approach you are suggesting. However, I do not want to take the risk of modifying the formatting of standard library as it will be fatal in my use case. It will be desirable if spdlog out-of-box provides support to log stack traces in 1 log message like in Java/Scala. Well, this being C++ we are talking about, I realise that this can be tedious activity for @gabime 😃 

What can be possible with the existing APIs?

**Comment by gabime** [comment]
@PuneetPatwari You can also try to use the [ostream api](https://github.com/gabime/spdlog/wiki/1.-QuickStart#log-user-defined-objects) for this.

**Comment by PuneetPatwari** [comment]
Hi @gabime , Do you mean that I need to first store the exception stack-trace as 1 string and pass it as ostream? I am not particularly clear about this. Can you explain?

**Comment by gabime** [comment]
No, The idea is convert it to some object represnting the stack trace and that implements ```operator<< ```
