### ISSUE TITLE
Formatting of null-pointers (char*)?

### ISSUE THREAD

**Issue by tomszilagyi** [gabime/spdlog#1009]
Hi,

I am using spdlog 1.3.1 with bundled fmt on MacOS X.

Not sure if this is a bug or a feature. If I have a char* (C-string) that is sometimes a nullptr, and in that case I get this when attempting to log it (nothing fancy, just `spdlog::debug("ptr={}\n", ptr);`):

```
[*** LOG ERROR ***] [2019-02-27 12:43:18] [] string pointer is null
```

Naturally, I get the correct log output when `ptr` is non-null and points to a valid C-string.

What I would prefer is if, instead of the above error message, I would get an indication that the passed value is null, with the rest of the format string rendered, perhaps like plain old printf in glibc:

```
[...] ptr=(null)
```

Is this achievable somehow? I would prefer not to add if-checks for such logging entries. 

N.B.: After some digging around, I see that fmtlib has a fix for this, see https://github.com/fmtlib/fmt/issues/226
However, the check is only included when using `fmt::printf`.

Thanks!

**Comment by gabime** [comment]
@tomszilagyi  Thanks for the update. Closing it.

**Comment by watho** [comment]
Hello,

i still see the error on windows with spdlog 1.3.1. I don't understand the fmt-fix or what to do with that.

Simple test case:
```c++
const char* emtpy = nullptr;
SPDLOG_INFO("{}", empty);
```

**Comment by gabime** [comment]
try casting to void* before passing it

**Comment by watho** [comment]
Thanks for the quick answer.

Casting it prints 0x0 for a null pointer (OK) but breaks printing the real value for non-null values. (not OK)

**Comment by gabime** [comment]
oh, so you can try cast to string view instead: https://stackoverflow.com/a/47240730

**Comment by watho** [comment]
I'm pre c++17 and don't have std::string_view. I tried the bundled fmt::string_view but this gives an exception with a nullptr.

**Comment by tt4g** [comment]
`char* empty_chars = nullptr` is not an empty characters. If accessed as a pointer, a segmentation fault will occur: https://wandbox.org/permlink/Uly1DGGrgQwVf30k

```cpp
    char* nullptr_char = nullptr;

    std::cout << *nullptr_char << std::endl; // Segmentation fault
```

The empty characters is '\n': https://wandbox.org/permlink/cGF3hn330ARw8b5x

```cpp
    char empty[] = { '\0' };

    char* empty_char = empty;
    std::cout << *empty_char << std::endl;
```

**Comment by watho** [comment]
I know this, but it does not matter. I am getting the null pointer from an external library. My request is the same like the original poster had:

> What I would prefer is if, instead of the above error message, I would get an indication that the passed value is null, with the rest of the format string rendered, perhaps like plain old printf in glibc:
> [...] ptr=(null)
> Is this achievable somehow? I would prefer not to add if-checks for such logging entries.

My main problem is, that the error message does not include the original maybe unformatted message or filename and linenumber like my normal logs. So it is impossible to say where this error occurs.

My current workaround is to wrap all possible null pointer in something like `SPDLOG_INFO({}, s ? s : "null");` and that is time-consuming and seems to be something the logging library should do.
