### ISSUE TITLE
use spdlog instance globally

### ISSUE THREAD

**Issue by kerry999** [gabime/spdlog#1010]
it's convinient to define a logger as global var so that each class/files can use. e.g:
spdlog::logger global_logger;

but there is no empty constructor for spdlog and a function to set the name and sinks later. so a logger instance , for example: spdlog::logger logger("multi_sink", {console_sink, file_sink});
have to be local inside a function. but it will be destroyed outside of the function and other class instance cannot access it anymore.

**Comment by gabime** [comment]
You should store shared pointer for the logger. This will enable having same instance for all
