### ISSUE TITLE
Compiling with cygwin gives errors "'fileno' was not declared in this scope" in os.h

### ISSUE THREAD

**Issue by N00TN00T** [gabime/spdlog#1011]
Hi,

When I try to compile my project, which includes spdlog, I get the same error on line 139, 228 and 416 in os.h, saying "'fileno' was not declared in this scope".

**Comment by gabime** [comment]
Please provide more info. (spdlog version, os, compiler)

**Comment by jhnwnd** [comment]
The _fileno_() function is a POSIX extension.
One way to resolve this is by removing the `set(CMAKE_CXX_EXTENSIONS OFF)` in the CMakeLists.txt file (or changing OFF to ON here, which is the default).
