### ISSUE TITLE
no basic_file_sink.h in ubuntu libspdlog-dev

### ISSUE THREAD

**Issue by moqingyan** [gabime/spdlog#1012]
I have wrote a Dockerfile to setup an environment for a project:
 `FROM ubuntu:latest
WORKDIR .
COPY . /
RUN apt-get update && apt-get install -y \
  libclang-dev llvm-dev cmake libspdlog-dev libmlpack-dev`
However, basic_file_sink.h is not among the files that are installed according to `dpkg -L libspdlog-dev`. 

 I also tried manually clone the directory, but I am not sure which is the build directory in the project I am working on. 

I also tried cmake the directory. When I used `make -j` at the last step, it seems to be stucked on `[ 82%] Building CXX object tests/CMakeFiles/spdlog-utests.dir/main.cpp.o`

**Comment by gabime** [comment]
Which version of spdlog get installed  (see in version.h) ?
