### ISSUE TITLE
Question: error with linking spdlog (which is git submodule) to another header-only lib

### ISSUE THREAD

**Issue by GillianGrayson** [gabime/spdlog#1013]
Dear all,

I apologize if my question is stupid. I am new in CMAKE and C++.

In my project (hello-world header-only lib) I want to use spdlog as git submodule.
But I don't know how to correctly link spdlog to my header-only lib.
In this repository: https://github.com/GillianGrayson/header_only_lib I create very simple header-only lib (main cmake file copied from spdlog and slightly adapted).
In order for my library to be displayed correctly in the IDE, I use the add_custom_target with all .h files as SOURCE arguments.
But the problem is that in this case the headers from spdlog are not found: cannot open source file (error file is header_only_lib/include/header_only_lib/logger.h)
But headers from spdlog are explicitly included:
include_directories(${THIRD_PARTY_INCLUDE_PATH}).
How to include correctly headers from spdlog (which is git submodule) to my header-only lib?

Thanks for help!

**Comment by Alexander-Degtyar** [comment]
@GillianGrayson,

To link spdlog as submodule:
1. Add the submodule to your repo: `git submodule add https://github.com/gabime/spdlog.git`
2. Optionally, select version: `cd spdlog; git checkout v1.9.2`
3. Do not forget to add spdlog directory to parent CMakeLists.txt: `add_subdirectory(spdlog)`
4. In the target you build just link the spdlog library: `target_link_libraries(your-target spdlog)`
