### ISSUE TITLE
Basic usage example fails

### ISSUE THREAD

**Issue by kingaj12** [gabime/spdlog#1015]
I copied the following lines into my code: 

    #include "spdlog/spdlog.h"
    int main() 
    {
        spdlog::info("Welcome to spdlog!");
        spdlog::error("Some error message with arg: {}", 1);

Code fails to compile since `info` and `error` are not in the spdlog namespace.  And indeed, they are not.

**Comment by kingaj12** [comment]
And in the file 

        spdlog/tests/test_file_logging.cpp

one finds the correct invocations.  Would be good to fix the basic example.

**Comment by gabime** [comment]
This should work . You probably use old version.

**Comment by kingaj12** [comment]
OK - I figured it out.  I installed using `sudo apt install libspdlog-dev`.  This is probably the old version.  When I downloaded the `include/spdlog` directory it worked just fine.  

Thanks!  It looks like a very nice package.

**Comment by gabime** [comment]
@kingaj12  You're welcome.  The ubuntu package is old indeed . It's best to use that latest from github  (v1.3.1)
