### ISSUE TITLE
Question: can i create a callback function for when something is logged?

### ISSUE THREAD

**Issue by GeestWagen** [gabime/spdlog#1016]
basically i am trying to get something like this
`
void callbackFunction(string message)
{
/*code*/
}
` 
and that function should be called when i do this: `spdlog::info("message");`

i haven't figured a way to do this since quite unfamiliar with this library. thanks in advance

**Comment by gabime** [comment]
There is no obvious way for this. You could imlement a custom sink that do this but I doubt it will worth the effort.
