### ISSUE TITLE
I need to be able to delete my application log file, when it runs. How to do this?

### ISSUE THREAD

**Issue by a-d-gordienko** [gabime/spdlog#1018]

**Comment by gabime** [comment]
it depens on the sink you use.

**Comment by a-d-gordienko** [comment]
Does the library have such or need to write?

**Comment by gabime** [comment]
The lib can truncate the file before starting to write to it

**Comment by a-d-gordienko** [comment]
I implemented my sink, released_file_sink on based base_sink. Show it?

**Comment by gabime** [comment]
sure

**Comment by a-d-gordienko** [comment]
`#pragma once
//released_file_sink.h
#ifndef SPDLOG_H
#include "spdlog/spdlog.h"
#endif

#include "spdlog/details/file_helper.h"
#include "spdlog/details/null_mutex.h"
#include "spdlog/sinks/base_sink.h"

#include <mutex>
#include <string>
#include <list>

namespace spdlog {
	namespace sinks {
		/*
		 * Released file sink:
		 * Algorithm write: wrtite to messages list 
		 * Algorithm flush: open file, bypass message list and write to file, flush and close file
		 */
		template<typename Mutex>
		class released_file_sink final : public base_sink<Mutex>
		{
		public:
			explicit released_file_sink(const filename_t &filename, bool truncate = false) : _filename(filename), _truncate(truncate){	}

			~released_file_sink() {
				flush_();
			}
			
			const filename_t &filename() const {
				return _filename;
			}

		protected:
			void sink_it_(const details::log_msg &msg) override	{
				std::unique_ptr<fmt::memory_buffer> formatted(new fmt::memory_buffer);
				sink::formatter_->format(msg, *formatted);
				line_drive.push_back(std::move(formatted));
			}

			void flush_() override
			{				
				if (!line_drive.empty()) {
					try{
						file_helper_.open(_filename, _truncate);
					}catch (spdlog_ex &e) {}
					for (std::unique_ptr<fmt::memory_buffer> &pbuf : line_drive) {
						try {
							file_helper_.write(*pbuf.get());
						}catch (spdlog_ex &e) {}
					}
					line_drive.clear();
					file_helper_.flush();
					file_helper_.close();
				}
			}

		private:
			details::file_helper file_helper_;
			filename_t _filename;
			bool _truncate;
			std::list<std::unique_ptr<fmt::memory_buffer> > line_drive;
		};

		using released_file_sink_mt = released_file_sink<std::mutex>;
		using released_file_sink_st = released_file_sink<details::null_mutex>;

	} // namespace sinks

	//
	// factory functions
	//
	template<typename Factory = default_factory>
	inline std::shared_ptr<logger> released_logger_mt(const std::string &logger_name, const filename_t &filename, bool truncate = false)
	{
		return Factory::template create<sinks::released_file_sink_mt>(logger_name, filename, truncate);
	}

	template<typename Factory = default_factory>
	inline std::shared_ptr<logger> released_logger_st(const std::string &logger_name, const filename_t &filename, bool truncate = false)
	{
		return Factory::template create<sinks::released_file_sink_st>(logger_name, filename, truncate);
	}

} // namespace spdlog`

**Comment by Xydez** [comment]
^^^ Formatted code above ^^^

```c++
#pragma once

//released_file_sink.h

#ifndef SPDLOG_H
#include "spdlog/spdlog.h"
#endif

#include "spdlog/details/file_helper.h"
#include "spdlog/details/null_mutex.h"
#include "spdlog/sinks/base_sink.h"

#include
#include
#include

namespace spdlog
{
	namespace sinks
	{
		/*
		 * Released file sink:
		 * Algorithm write: wrtite to messages list
		 * Algorithm flush: open file, bypass message list and write to file, flush and close file
		 */
		template class released_file_sink final : public base_sink
		{
		public:
			explicit released_file_sink(const filename_t &filename, bool truncate = false) : _filename(filename), _truncate(truncate){	}

			~released_file_sink()
			{
				flush_();
			}
		
			const filename_t &filename() const
			{
				return _filename;
			}

		protected:
			void sink_it_(const details::log_msg &msg) override
			{
				std::unique_ptr<fmt::memory_buffer> formatted(new fmt::memory_buffer);
				sink::formatter_->format(msg, *formatted);
				line_drive.push_back(std::move(formatted));
			}

			void flush_() override
			{				
				if (!line_drive.empty())
				{
					try
					{
						file_helper_.open(_filename, _truncate);
					}
					catch (spdlog_ex &e) {}
					
					for (std::unique_ptr<fmt::memory_buffer> &pbuf : line_drive)
					{
						try
						{
							file_helper_.write(*pbuf.get());
						}
						catch (spdlog_ex &e) {}
					}

					line_drive.clear();
					file_helper_.flush();
					file_helper_.close();
				}
			}

		private:
			details::file_helper file_helper_;
			filename_t _filename;
			bool _truncate;
			std::list<std::unique_ptr<fmt::memory_buffer> > line_drive;
		};

		using released_file_sink_mt = released_file_sink<std::mutex>;
		using released_file_sink_st = released_file_sink<details::null_mutex>;

	} // namespace sinks

	//
	// factory functions
	//
	template<typename Factory = default_factory>
	inline std::shared_ptr<logger> released_logger_mt(const std::string& logger_name, const filename_t& filename, bool truncate = false)
	{
		return Factory::template create<sinks::released_file_sink_mt>(logger_name, filename, truncate);
	}
	
	template<typename Factory = default_factory>
	inline std::shared_ptr<logger> released_logger_st(const std::string& logger_name, const filename_t& filename, bool truncate = false)
	{
		return Factory::template create<sinks::released_file_sink_st>(logger_name, filename, truncate);
	}
} // namespace spdlog
```

**Comment by gabime** [comment]
whats the purpose?

**Comment by a-d-gordienko** [comment]
While the application is running, you can delete the log file.
