### ISSUE TITLE
How to change precision of double by using SPDLOG_INFO?

### ISSUE THREAD

**Issue by larvavral** [gabime/spdlog#1019]
It seems that default precision for double in spdlog is 6 or 7. Is there anyway to change it when using SPDLOG_INFO?
```
int main(int argc, char* argv[]) {
  double x = 4.1234567890;
  SPDLOG_INFO("Test: {}", x);
  return 0;
}
```
Output: [2019-03-08 17:11:45.813] [info] [test.cc:81] Test: 4.12346

**Comment by larvavral** [comment]
I found that we can use python format style:
```
SPDLOG_INFO("Test: {0:.8f}", y);
```
Output: [2019-03-08 17:28:15.921] [info] [test.cc:75] Test: 4.12345679

But is there anyway to just set precision 1 time so we no need to put "0:.8f" every time logging double?

**Comment by gabime** [comment]
No such way
