### ISSUE TITLE
Logging from library

### ISSUE THREAD

**Issue by AlexandrePTJ** [gabime/spdlog#102]
Hi,

I am trying to use spdlog in a project involving a library under windows.
I create two loggers. One for the app using the library, one for the library itself.
The library's logger is created from the app but when the library want to add a message, it crash.

Following is an simplified example.

**The library**

*libclass.h*

```cpp
#ifndef LIBCLASS_H
#define LIBCLASS_H

#include <spdlog/spdlog.h>

#ifdef WIN32
#  ifdef BUILD_APPLIB_SHARED
#    define APPLIB_EXPORT __declspec(dllexport)
#  else
#    define APPLIB_EXPORT
#  endif //BUILD_APPLIB_SHARED
#else
#  define APPLIB_EXPORT
#endif // WIN32

class APPLIB_EXPORT LibClass
{
public:
    LibClass();
    ~LibClass();

    static std::string loggerName();

    void testLog();

private:
    std::shared_ptr<spdlog::logger> m_logger;
};

#endif //LIBCLASS_H
```

*libclass.cpp*

```cpp
#include "libclass.h"

const std::string myLoggerName = "lib_logger";

LibClass::LibClass()
{
    m_logger = spdlog::get(myLoggerName);
}

LibClass::~LibClass()
{ }

std::string LibClass::loggerName()
{
    return myLoggerName;
}

void LibClass::testLog()
{
    m_logger->info("Log from library");
}
```

**The application**

*main.cpp*

```cpp
#include <spdlog/spdlog.h>
#include <applib/libclass.h>

void logtest()
{
    auto logger = spdlog::get("app_logger");
    logger->info("Log from application");
}

int main(int argc, char *argv[])
{
    // create loggers
    auto appLogger = spdlog::stdout_logger_mt("app_logger");
    auto libLogger = spdlog::stdout_logger_mt(LibClass::loggerName());

    // log from app
    logtest();

    // log from lib
    LibClass lc;
    lc.testLog();

    return 0;
}
```

**Comment by gabime** [comment]
Could you debug and see what might be the cause?

**Comment by AlexandrePTJ** [comment]
From what I see, the `_loggers` map from `registry.h` is empty when calling `spdlog::get(myLoggerName);` from the library. Then `m_logger` is null.

**Comment by gabime** [comment]
Seems there are 2 registry objects in this case. You could workaround with passing the logger shared ptr to the lib ctor and then registering it using spdlog::register(from the lib)..

**Comment by AlexandrePTJ** [comment]
This can solve the problem for the small example, I don't think it is suitable for a bigger project.
I created a PR #103 to discuss about another solution.
