### ISSUE TITLE
Logging N variables 

### ISSUE THREAD

**Issue by L4ZZA** [gabime/spdlog#1021]
I'm trying to log more than 1 variable through my assert macro that at the moment looks like this: 
`#define ASSERT(x, ...) { if(!x) {LOG_ERROR("Assertion failed: {0}", __VA_ARGS__); __debugbreak();}}`
and the LOG_ERROR macro is defined like so: `Logger::ClientLogger()->error(__VA_ARGS__)`
How can I log more than one variable like I'm trying to do here?
`ASSERT(b.x, "X components not equals {0} != {1}", var1, var2);`

**Comment by boimart1** [comment]
I would suggest the following:
```
#define ASSERT(x, fmt, ...) { if (!(x)) { LOG_ERROR(std::string("Assertion failed: ") + fmt, __VA_ARGS__); __debugbreak(); }}
```

**Comment by L4ZZA** [comment]
I agree this would be a possible solution, but I consider this more like a work around than and actual fix. 
I wanted to know if there's a specific alternative to these brackets `{}` or `{0}` but with the power to concatenate all the variables passed to the main message or if it will be implemented.

**Comment by boimart1** [comment]
Spdlog's formatting is done by [fmt](https://github.com/fmtlib/fmt) ([doc here](http://fmtlib.net/latest/index.html)), so you might have better luck with such a question over there.
