### ISSUE TITLE
spdlog version in Ubuntu repository

### ISSUE THREAD

**Issue by keith-bennett-gbg** [gabime/spdlog#1023]
Hi,

I'm not sure if this is an issue with spdlog or Ubuntu. I noticed the spdlog README.md states that I should be able to install `libspdlog-dev`, so I was curious what version it would install. I checked to ensure the package name was correct using `apt-cache search spdlog`, which showed `libspdlog-dev - Very fast, header only, C++ logging library`. Good so far.

I then checked what version it is using `apt-cache show libspdlog-dev`, which reveals it's version 1.6-1:
```
Package: libspdlog-dev
Priority: optional
Section: universe/libdevel
Installed-Size: 376
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Med Packaging Team <debian-med-packaging@lists.alioth.debian.org>
Architecture: amd64
Source: spdlog
Version: 1.6-1
Filename: pool/universe/s/spdlog/libspdlog-dev_1.6-1_amd64.deb
Size: 116970
MD5sum: 1efbeb313383f99fd65a3559799cd494
SHA1: 6f8e9d96d1d886cd85bea4b86b6e2bdd90d68ac5
SHA256: 62110559e2dd6106410eb6a6e0bfb3a0010d0691a58367a67da003e28a3e86a5
Description-en: Very fast, header only, C++ logging library
 Features: Very fast - performance is the primary goal; Headers only; No
 dependencies - just copy and use; call style using the excellent cppformat
 library; ostream call style is supported too; Optional extremely fast
 asynchronous mode - using lockfree queues and other tricks to reach millions
 of calls/sec; Custom formatting; Multi/Single threaded loggers; Easily
 extendable with custom log targets (just implement a single function in the
 sink interface). Severity based filtering - threshold levels can be modified
 in runtime as well as in compile time.
 .
 Various log targets:
 Rotating log files, Daily log files, Console logging, Linux syslog.
Description-md5: 97412f713972fcd601eccc1757ddcca4
Homepage: https://github.com/COMBINE-lab/spdlog
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
```

But when looking at the repository here, I don't see any tagged version 1.6. The highest I see is 1.3. Is this a mistake on my part?

I am using Ubuntu 16.04; you can reproduce my issue using Docker:
`docker run --rm ubuntu:16.04 bash -c 'apt-get update > /dev/null && apt-cache show libspdlog-dev | grep Version'`
-> `Version: 1.6-1`

It looks like the `libspdlog-dev` package in Ubuntu actually points to a different repository, https://github.com/COMBINE-lab/spdlog. It looks like that repository hasn't been updated for about a year, and the 1.6 tag is four years old.

I'm really confused about this. Can you help to clarify some of this information?

**Comment by gabime** [comment]
The ubuntu package is old. Please use the latest github version.

**Comment by keith-bennett-gbg** [comment]
Thanks for the quick reply!

**Comment by BassantArboud** [comment]
> Hi,
> 
> I'm not sure if this is an issue with spdlog or Ubuntu. I noticed the spdlog README.md states that I should be able to install `libspdlog-dev`, so I was curious what version it would install. I checked to ensure the package name was correct using `apt-cache search spdlog`, which showed `libspdlog-dev - Very fast, header only, C++ logging library`. Good so far.
> 
> I then checked what version it is using `apt-cache show libspdlog-dev`, which reveals it's version 1.6-1:
> 
> ```
> Package: libspdlog-dev
> Priority: optional
> Section: universe/libdevel
> Installed-Size: 376
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Original-Maintainer: Debian Med Packaging Team <debian-med-packaging@lists.alioth.debian.org>
> Architecture: amd64
> Source: spdlog
> Version: 1.6-1
> Filename: pool/universe/s/spdlog/libspdlog-dev_1.6-1_amd64.deb
> Size: 116970
> MD5sum: 1efbeb313383f99fd65a3559799cd494
> SHA1: 6f8e9d96d1d886cd85bea4b86b6e2bdd90d68ac5
> SHA256: 62110559e2dd6106410eb6a6e0bfb3a0010d0691a58367a67da003e28a3e86a5
> Description-en: Very fast, header only, C++ logging library
>  Features: Very fast - performance is the primary goal; Headers only; No
>  dependencies - just copy and use; call style using the excellent cppformat
>  library; ostream call style is supported too; Optional extremely fast
>  asynchronous mode - using lockfree queues and other tricks to reach millions
>  of calls/sec; Custom formatting; Multi/Single threaded loggers; Easily
>  extendable with custom log targets (just implement a single function in the
>  sink interface). Severity based filtering - threshold levels can be modified
>  in runtime as well as in compile time.
>  .
>  Various log targets:
>  Rotating log files, Daily log files, Console logging, Linux syslog.
> Description-md5: 97412f713972fcd601eccc1757ddcca4
> Homepage: https://github.com/COMBINE-lab/spdlog
> Bugs: https://bugs.launchpad.net/ubuntu/+filebug
> Origin: Ubuntu
> ```
> 
> But when looking at the repository here, I don't see any tagged version 1.6. The highest I see is 1.3. Is this a mistake on my part?
> 
> I am using Ubuntu 16.04; you can reproduce my issue using Docker:
> `docker run --rm ubuntu:16.04 bash -c 'apt-get update > /dev/null && apt-cache show libspdlog-dev | grep Version'`
> -> `Version: 1.6-1`
> 
> It looks like the `libspdlog-dev` package in Ubuntu actually points to a different repository, https://github.com/COMBINE-lab/spdlog. It looks like that repository hasn't been updated for about a year, and the 1.6 tag is four years old.
> 
> I'm really confused about this. Can you help to clarify some of this information?

could you please tell me what do you use at docker file in ubuntu ? clone spdlog or install libspdlog-dev ?

**Comment by balu-B07** [comment]
can you confirm me!  spdlog's will work in centos 7 version server.
i can't install in these server..
