### ISSUE TITLE
cmake configuration failed for XCode

### ISSUE THREAD

**Issue by awkv** [gabime/spdlog#1026]
spdlog is included as subfolder like this:
```
add_subdirectory(spdlog EXCLUDE_FROM_ALL)

find_package(spdlog CONFIG REQUIRED)
```
spdlog/example was taken as a root and spdlog was inserted as a subfolder. `cmake -GXcode` configuration fails with the following error (paths are cut a little):
```
CMake Error at .../spdlog/spdlogConfig.cmake:26 (include):
  include could not find load file:

    .../spdlog/spdlogTargets.cmake

```

macos version: Darwin Kernel Version 18.2.0 (macos Mojave 10.14.3)
cmake version 1.13.1
spdlog version 1.3.1 (reproducible on earlier versions too)
Exactly the same project is configured for VS (on Windows) w/o any errors.

**Comment by kerry999** [comment]
fyi. no need to make spdlog, i only add -I to make cmake know where to find the header files. and i works for both ios and android, windows

**Comment by gabime** [comment]
@awkv CMakeLists.txt was re-written recently. Please try latest commit and seen if it solves

**Comment by tetsuhaut** [comment]
Dear gabime,
I got the exact same error trying to link with static library form of spdlog, be it version 1.4.2 or master:

```CMake Error at C:/prog/lib/spdlog/spdlog-1.x-vs2019-64bits-static/spdlogConfig.cmake:15 `(include):`

  include could not find load file:

    C:/prog/lib/spdlog/spdlog-1.x-vs2019-64bits-static/spdlogConfigTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:123 (find_package)```

Here is the part of my project's CMakeList.txt that links with spdlog:
```
find_package(spdlog)
include_directories(${SPDLOG_INCLUDEDIR})
target_link_libraries(main_lib spdlog::spdlog)

```

**Comment by awkv** [comment]
@tetsuhaut try delete your 'find_package(spdlog)' but preserve 'add_subdirectory(spdlog)'. It works for me to link statically with spdlog.

**Comment by tetsuhaut** [comment]
Thanks for your answer @awkv but I did not added spdlog as a subdirectory. In fact, I am trying to use spdlog as an external library, as described in the readme: "Static lib version (recommended - much faster compile times)".
