### ISSUE TITLE
set_async_mode no a member of 'spdlog'

### ISSUE THREAD

**Issue by wcwang07** [gabime/spdlog#1028]
spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block_retry);
   ^~~~~~
spdlogger_ = spdlog::stdout_color_mt(LOGGER_NAME);
                ^~~~~~
 spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block_retry);
                                        ^~~~~~~~~~~~~~~~~~~~~

**Comment by gabime** [comment]
pleas use version 1.x

**Comment by wcwang07** [comment]
i was trying to compile from the following file from: 

https://github.com/ucbrise/clipper/blob/develop/src/libclipper/src/logging.cpp#L20

https://github.com/ucbrise/clipper/blob/develop/src/libclipper/src/logging.cpp#L13

https://github.com/ucbrise/clipper/blob/develop/src/libclipper/src/logging.cpp#L12

I think I need these functions
