### ISSUE TITLE
why spd::set_pattern("***[%@]***") don't print file name function and line number 

### ISSUE THREAD

**Issue by Eric-Sunjian** [gabime/spdlog#1031]

**Comment by tt4g** [comment]
should use macro `SPDLOG_TRACE`, `SPDLOG_INFO` ...

Details are written on the wiki.

**Comment by smrititripathi027** [comment]
If I am creating two loggers in same c++ file then how to print file name, line number in file becausee if I am using SPDLOG_TRACE , it is supporting to only one logger.
