### ISSUE TITLE
add __LINE__ to macro function

### ISSUE THREAD

**Issue by MacroGu** [gabime/spdlog#1032]
I want to add __LINE__ info when log something, and I add a macro function to do that, here is my code: 
`#define LOG_INFO(fmt, ...) ServerLog::GetInstance().GetInstance().GetRotatingLogger()->info("{0}: {1}  "##fmt    , __FUNCTION__, __LINE__, ##__VA_ARGS__)`
and it works under vs2017, but cause a compile error under gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1), and the error say:
`error: pasting ""{0}: {1}  "" and ""current status: {} , not accept new connect"" does not give a valid preprocessing token
 #define LOG_INFO(fmt, ...) ServerLog::GetInstance().GetInstance().GetRotatingLogger()->info("{0}: {1}  "##fmt, __FUNCTION__, __LINE__, ##__VA_ARGS__)`

please help me fix that ,thanks!

**Comment by tt4g** [comment]
`SPDLOG_TRACE` macro and` %# `format are available.

see Wiki: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

**Comment by MacroGu** [comment]
could you please give me an example code of how to use SPDLOG_TRACE ? thanks

**Comment by tt4g** [comment]
simple snippet:
```cpp
// Enable SPDLOG_TRACE macro, see: spdlog/tweakme.h
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#define SPDLOG_DEBUG_ON
#define SPDLOG_TRACE_ON

#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>

int main(int, char**)
{
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");

    auto console = spdlog::stdout_logger_mt("console");
    spdlog::set_default_logger(console);

    SPDLOG_TRACE("global output with arg {}", 1); // [source main.cpp] [function main] [line 16] global output with arg 1
    SPDLOG_LOGGER_TRACE(console, "logger output with arg {}", 2); // [source main.cpp] [function main] [line 17] logger output with arg 2
    console->info("invoke member function"); // [source ] [function ] [line ] invoke member function

    return 0;
}
```

**Comment by baby-care** [comment]
> simple snippet:
> 
> ```c++
> // Enable SPDLOG_TRACE macro, see: spdlog/tweakme.h
> #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
> #define SPDLOG_DEBUG_ON
> #define SPDLOG_TRACE_ON
> 
> #include <spdlog/spdlog.h>
> #include <spdlog/sinks/stdout_sinks.h>
> 
> int main(int, char**)
> {
>     spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
> 
>     auto console = spdlog::stdout_logger_mt("console");
>     spdlog::set_default_logger(console);
> 
>     SPDLOG_TRACE("global output with arg {}", 1); // [source main.cpp] [function main] [line 16] global output with arg 1
>     SPDLOG_LOGGER_TRACE(console, "logger output with arg {}", 2); // [source main.cpp] [function main] [line 17] logger output with arg 2
>     console->info("invoke member function"); // [source ] [function ] [line ] invoke member function
> 
>     return 0;
> }
> ```
Please help. I am new to c++
I install spdlog in system,  copy this code, and compiled success. but not function and line output.

output only:
[source ] [function ] [line ] invoke member function

thanks.

**Comment by gabime** [comment]
it works only when using the macros.

**Comment by baby-care** [comment]
> It works only when using the macros. Also, no need to define SPDLOG_TRACE_ON nor SPDLOG_DEBUG_ON

Thanks.

I find the format(show source, func name, line number) not works with SPDLOG_TRACE & SPDLOG_DEBUG, but SPDLOG_INFO/SPDLOG_ERROR/SPDLOG_CRITICAL works well. 

Here's my code, I didn't find some doc metion this,  or something wrong with me.  

#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>

int main(int, char**)
{
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
    spdlog::set_level(spdlog::level::trace);

    SPDLOG_TRACE("This trace"); 
    SPDLOG_DEBUG("This is debug..");
    SPDLOG_INFO("This is info..");
    SPDLOG_ERROR("This is error..");
    SPDLOG_CRITICAL("This is critical..");

    return 0;
}

**Comment by gabime** [comment]
you must
```c++
 #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
```
before including spdlog.h

**Comment by tesla1060** [comment]
> you must
> 
> ```c++
>  #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
> ```
> 
> before including spdlog.h

Hi as what baby-care said, it seems to be the case that even we do,
```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>

int main(int, char**)
{

spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
spdlog::set_level(spdlog::level::trace);

SPDLOG_TRACE("This trace"); 
SPDLOG_DEBUG("This is debug..");
SPDLOG_INFO("This is info..");
SPDLOG_ERROR("This is error..");
SPDLOG_CRITICAL("This is critical..");

return 0;
}
```

I am only getting starting from `info` showing, `trace` and `debug` are missing. wondering why?

**Comment by tt4g** [comment]
@tesla1060 What your spdlog version?
If using spdlog version before v1.3.0, shoud you define `SPDLOG_DEBUG_ON` and `SPDLOG_TRACE_ON`.

https://github.com/gabime/spdlog/blob/10e809cf644d55e5bd7d66d02e2604e2ddd7fb48/include/spdlog/spdlog.h#L129-L132

**Comment by tesla1060** [comment]
> @tesla1060 What your spdlog version?
> If using spdlog version before v1.3.0, shoud you define `SPDLOG_DEBUG_ON` and `SPDLOG_TRACE_ON`.
> 
> https://github.com/gabime/spdlog/blob/10e809cf644d55e5bd7d66d02e2604e2ddd7fb48/include/spdlog/spdlog.h#L129-L132

I am using straight from the master, 1.x, and tried 1.7.0 latest release, both not working, even with 

```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#define SPDLOG_DEBUG_ON
#define SPDLOG_TRACE_ON
```

I am using vs2019 compiler on windows 10.
But I just tried on my linux box, this actually works. A bug on windows?

**Comment by tt4g** [comment]
@tesla1060 Can you output `SPDLOG_ACTIVE_LEVEL` ?

```diff
+#ifndef SPDLOG_ACTIVE_LEVEL
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
+#endif
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>

int main(int, char**)
{
+ std::cout << "SPDLOG_ACTIVE_LEVEL: " << SPDLOG_ACTIVE_LEVEL << "\n";
spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
spdlog::set_level(spdlog::level::trace);

SPDLOG_TRACE("This trace"); 
SPDLOG_DEBUG("This is debug..");
SPDLOG_INFO("This is info..");
SPDLOG_ERROR("This is error..");
SPDLOG_CRITICAL("This is critical..");

return 0;
}
```

**Comment by tesla1060** [comment]
@tt4g this is what I am getting,

> D:\code_test\cmake-build-debug\test_spdlog.exe
> SPDLOG_ACTIVE_LEVEL: 0
> [source spdlog_test.cpp] [function main] [line 16] This trace
> [source spdlog_test.cpp] [function main] [line 17] This is debug..
> [source spdlog_test.cpp] [function main] [line 18] This is info..
> [source spdlog_test.cpp] [function main] [line 19] This is error..
> [source spdlog_test.cpp] [function main] [line 20] This is critical..


So I should put this on?

> spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
> spdlog::set_level(spdlog::level::trace);

**Comment by tesla1060** [comment]
> @tesla1060 Can you output `SPDLOG_ACTIVE_LEVEL` ?
> 
> ```diff
> +#ifndef SPDLOG_ACTIVE_LEVEL
> #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
> +#endif
> #include <spdlog/spdlog.h>
> #include <spdlog/sinks/stdout_sinks.h>
> 
> int main(int, char**)
> {
> + std::cout << "SPDLOG_ACTIVE_LEVEL: " << SPDLOG_ACTIVE_LEVEL << "\n";
> spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
> spdlog::set_level(spdlog::level::trace);
> 
> SPDLOG_TRACE("This trace"); 
> SPDLOG_DEBUG("This is debug..");
> SPDLOG_INFO("This is info..");
> SPDLOG_ERROR("This is error..");
> SPDLOG_CRITICAL("This is critical..");
> 
> return 0;
> }
> ```

apology, I think I have mixed up some testing code,
this actually works,

```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>

int main(int, char**)
{

    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
    spdlog::set_level(spdlog::level::trace);

    SPDLOG_TRACE("This trace");
    SPDLOG_DEBUG("This is debug..");
    SPDLOG_INFO("This is info..");
    SPDLOG_ERROR("This is error..");
    SPDLOG_CRITICAL("This is critical..");

    return 0;
}
```

**Comment by tt4g** [comment]
@tesla1060 That's good to hear
