### ISSUE TITLE
Separate formatting for log levels

### ISSUE THREAD

**Issue by Xydez** [gabime/spdlog#1033]
It would be nice if you could set different formatting for different log levels.

    0.    int main(void)
    1.    {
    2.        SPDLOG_TRACE("Hello, world!");
    3.    }
would result in (all gray): `Hello, world!` while

    0.    int main(void)
    1.    {
    2.        SPDLOG_WARN("Hello, world!");
    3.    }
would result in (warning and function = yellow, message = white, "at main:cpp:2" = gray):

    0.    WARNING:  test_function: Hello, world! 
    1.            at main.cpp:2

Is this already possible in spdlog?

**Comment by gabime** [comment]
No. Thats not possible in spdlog
