### ISSUE TITLE
Default logger is NOT thread safe

### ISSUE THREAD

**Issue by tnie** [gabime/spdlog#1036]

**Comment by gabime** [comment]
Please provide info

**Comment by tnie** [comment]
if you call `spdlog::info("xxx")` after `spdlog::shutdown()` (maybe in another thread), it will crash.

**Comment by gabime** [comment]
you can call it,  ut it should be the last usage of spdlog. you cannot call spdlog afterwards..
Anyway, this is not mandatory, to call shutdown.
