### ISSUE TITLE
Question: How do I log to a file and the console with one call?

### ISSUE THREAD

**Issue by Hampfh** [gabime/spdlog#1037]
Hey, I was wondering whether it is possible to create a logger which when is called writes to the console and to a file. Is this possible?

Alternatively is it possible to have have the logger name be the same for both loggers. This way you don't need to see `[date] mylogger_file` and `[date] mylogger_console` but instead` [date] mylogger` for both

Right now I have two loggers, one for writing to a log file and one for console:
```cpp 
// File logger
mylogger_file = spdlog::rotating_logger_mt("mylogger_file", "logs/rotating.txt", 1048576 * 5, 3);
// Console logger
mylogger_console = spdlog::stdout_color_mt("mylogger_console");
```

This feels very weird and I'm sure there is a better way...

**Comment by tt4g** [comment]
see https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#creating-loggers-with-multiple-sinks

**Comment by Hampfh** [comment]
That was exactly what I was looking for, thanks

**Comment by degloff** [comment]
According to the above link and remarks this should log to console AND file but it doesn't. 

```
include <filesystem>

#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"

namespace utils {

    std::shared_ptr<spdlog::logger> create_logger() {
        auto cwd = std::filesystem::current_path().string();
        auto logger_name = "combined";
        auto logger_file = "my_log_file.log";
        auto log_level = spdlog::level::debug;

        std::vector<spdlog::sink_ptr> sinks{
            std::make_shared<spdlog::sinks::stdout_color_sink_mt>(),
            std::make_shared<spdlog::sinks::basic_file_sink_mt>(logger_file),
        };
        auto spd_logger = std::make_shared<spdlog::logger>(logger_name, begin(sinks), end(sinks));
        spdlog::register_logger(spd_logger);
        spdlog::set_level(log_level);
        spdlog::flush_every(std::chrono::seconds(1));

        spdlog::debug("Logging started, logger_name={}, level={}, cwd={}", logger_name, (int)spd_logger->level(), cwd);

        return spd_logger;
    }

}
```

The log file created but it is always empty, although I see the log on the screen. 

What is wrong here or is it a (new) bug?

I use the latest version 1.14.1.

Thanks for helping out.

**Comment by tt4g** [comment]
@degloff You forgot to call `set_default_logger(spd_logger)`, so `spdlog::debug()` does not use `spd_logger`.
Please add `set_default_logger(spd_logger)`.

```diff
         auto spd_logger = std::make_shared<spdlog::logger>(logger_name, begin(sinks), end(sinks));
         spdlog::register_logger(spd_logger);
+       spdlog::set_default_logger(spd_logger);
         spdlog::set_level(log_level);
```

**Comment by degloff** [comment]
ah that make sense - thanks a lot.
