### ISSUE TITLE
android multisink: some infomation lost during fast logging

### ISSUE THREAD

**Issue by kerry999** [gabime/spdlog#1039]
i create multi-sink logger for android: one log to file and one log to logcat.
several (some 10) lines printed every 10ms. but the log file lost some of them.
the issue may not link to multi-sink because during run , instead of debug, the logcat dosen't work at all.

dose the issue relates to performance or buffer size?

below is init code:

// ----------------------------------------------------------------------
auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(filename, true);
file_sink->set_level(spdlog::level::trace);
sinks.push_back(file_sink);

 auto android_logcat_sink = std::make_shared<spdlog::sinks::android_sink_mt>("MC", false);
 android_logcat_sink->set_level(spdlog::level::trace);
 sinks.push_back(android_logcat_sink);

auto local_logger = std::make_shared<spdlog::logger>("mc", sinks.begin(), sinks.end());
local_logger->set_level(spdlog::level::debug);
local_logger->flush_on(spdlog::level::err);
spdlog::flush_every(std::chrono::seconds(5));

**Comment by tt4g** [comment]
I think the application has exited before the logs are flushed, Please execute `spdlog:: shutdown()` before exit.

In your case, the log that was left is flushed in destructor of `spdlog::details::registry::periodic_flusher_`:
https://github.com/gabime/spdlog/blob/9b5b4cd505143202fd785af6a077c409327f0683/include/spdlog/details/registry.h#L206

**Comment by kerry999** [comment]
it's not the text on the end lost, some text lost from time to time. is flush every 5 seconds too slow in my case ( log every 10ms?)

**Comment by gabime** [comment]
you need to call spdlog::register_logger(local_lgger) for perdioc flush.

**Comment by kerry999** [comment]
thank your comments. i has spdlog::register_logger and i just added spdlog:: shutdown() . will logger auto flush when buffer full (but has not reach 5sec period and no error triggered) please?

**Comment by gabime** [comment]
yes

**Comment by kerry999** [comment]
sorry, i just found i coded by mistake. there is no log lost after fixed bug.
