### ISSUE TITLE
Question: Compatibility with stdin

### ISSUE THREAD

**Issue by mastergberry** [gabime/spdlog#1042]
Hi.

I have a question about this library. I have been using it for months on a project to output data to the console or a log file without any issues. I have recently tried to build a simple console command handler system using getline, but the stdout from this library (and regular stdout as well) causes issues. I have used other programming languages where I have seen things like interactive consoles where you have a special "line" at the bottom of the terminal that is allowing you to freely input commands while output is still appearing above without them overlapping/interfering.

e.g.

```
[00:00:01] A line
[00:00:02] A line
[00:00:03] A line
... continuing to appear
prompt> I can freely type in here with the above lines still printing out
```

This might not be the right place to ask, but I would appreciate if there is a push in the right direction that you can shove me to. Is this possible in C++? I was looking at the GNU Readline library but I couldn't seem to figure out how to support behavior like this

Thanks

**Comment by tt4g** [comment]
I didn't really understand what I was looking for, but would you like something like this?

```cpp
#include <iostream>
#include <string>

int main(int, char**) {
    std::cout << "Hello!\n"
                 "Please enter your name:"
                 << std::flush;

    std::string line;
    std::cin >> line;

    std::cout << "Hello!, " << line << std::endl;

    return 0;
}

```

**Comment by mastergberry** [comment]
I have a quick test program below to show what I am looking for utilizing the readline GNU lib:

```cpp
#include <stdlib.h>
#include <readline/readline.h>
#include <readline/history.h>
#include <thread>
#include <iostream>
#include <chrono>

int main()
{
    // Configure readline to auto-complete paths when the tab key is hit.
    rl_bind_key('\t', rl_complete);

    std::thread foo([]() {
        for (;;) {
            std::cout << "hello world " << std::endl;
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
    });

    for(;;) {
        // Display prompt and read input
        char* input = readline("prompt> ");

        // Check for EOF.
        if (!input)
            break;

        // Add input to readline history.
        add_history(input);

        // Do stuff...

        // Free buffer that was allocated by readline
        free(input);
    }
    return 0;
}
```
My desired output would be

```
hello world
hello world
hello world
... keeps printing every second
prompt> I have some text sitting here not being disturbed by the above "hello world" output printing out every second
```

I am not sure if something like this is possible with standard cin/cout.

**Comment by tt4g** [comment]
I will tell you everything I know.

In most cases `std::cout` is tied to standard output, which is the console.

Since the console is not under C ++ control, the order of the output contents can not be controlled.

Although you can control the order by buffering the output contents and outputting them collectively, it may be difficult to partially change the output contents.

If you really want to operate the console from C ++, you need to use the OS API.
see https://stackoverflow.com/questions/6486289/how-can-i-clear-console

**Comment by mastergberry** [comment]
Ok, I had another person point me to ncurses as well but I just wanted to verify this was the only true way to do this.

Thanks for the further explanation :)
