### ISSUE TITLE
easy way to toggle the behaviour of a logger from sync to async and vice versa

### ISSUE THREAD

**Issue by nj2901** [gabime/spdlog#1043]
My use case requires me to read from a config file the details of the logger so that my code should not be compiled each time some specification change in logger. 
I want to set logger mode in my config file. 
And my code to handle if the string was sync then make a sync logger else make a async logger.
Is there any already present method for this in spdlog v1.3.1 ?

Also , how to create a global object of my logger below so that this logger reference can be used anywhere in my code : 

```
auto logger = std::make_shared<spdlog::async_logger>("loggername", sinks.begin(), sinks.end(), spdlog::thread_pool(), spdlog::async_overflow_policy::overrun_oldest);
    
```

**Comment by gabime** [comment]
You might want to try https://github.com/guangie88/spdlog_setup to handle spdlog config file.

Use spdlog::register_logger(logger) to have it globaly available using spdlog::get(“loggername”)

**Comment by nj2901** [comment]
Thanks @gabime  It helps.
