### ISSUE TITLE
same question in framework on mac

### ISSUE THREAD

**Issue by AsteriskZuo** [gabime/spdlog#1044]
I did not compile successfully. Compile through the twists and turns and find some problems to share with you.
Question:
1. Name conflict between file time.h and system file.
2. The member function format_float body implementation of file format-inl.h was not found
3.File bin_to_hex.h uses macro variables but does not find SPDLOG_CONSTEXPR definition
4.File android_sink.h does not use conditional compilation, just like file msvc_sink.h.

Above, I have done the test, please see here.
git@github.com:AsteriskZuo/test_spdlog_framework.git

**Comment by AsteriskZuo** [comment]
https://github.com/AsteriskZuo/test_spdlog_framework

**Comment by gabime** [comment]
spdlog build regulary on mac. try compiling the tests using cmake
