### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by PeachBlossomIsland** [gabime/spdlog#1046]
![捕获](https://user-images.githubusercontent.com/29038514/55315388-d369c100-549e-11e9-8f19-ece90fdd2b39.PNG)
I use vs2017 and download branch v1.x in github.
Always show that “namespace spdlog and no member basic_logger_mt”et
why?thank you!

**Comment by tt4g** [comment]
You need to add `#include "spdlog/sinks/basic_file_sink.h"` first,, and include `spdlog/spdlog.h` before `spdlog/async.h`.

example:

```cpp
#include <iostream>
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/async.h"
```

**Comment by PeachBlossomIsland** [comment]
> You need to add `#include "spdlog/sinks/basic_file_sink.h"` first,, and include `spdlog/spdlog.h` before `spdlog/async.h`.
> 
> example:
> 
> ```c++
> #include <iostream>
> #include "spdlog/spdlog.h"
> #include "spdlog/sinks/basic_file_sink.h"
> #include "spdlog/async.h"
> ```

thank you!It is ok!

**Comment by PeachBlossomIsland** [comment]
> You need to add `#include "spdlog/sinks/basic_file_sink.h"` first,, and include `spdlog/spdlog.h` before `spdlog/async.h`.
> 
> example:
> 
> ```c++
> #include <iostream>
> #include "spdlog/spdlog.h"
> #include "spdlog/sinks/basic_file_sink.h"
> #include "spdlog/async.h"
> ```

Why do header files have to be included in this order?Thank you!

**Comment by tt4g** [comment]
This is because `spdlog/spdlog.h` define core features.

It does not always have to be in this order. However, changing the order sometimes causes problems.

**Comment by PeachBlossomIsland** [comment]
> This is because `spdlog/spdlog.h` define core functions.
> 
> It does not always have to be in this order. However, changing the order sometimes causes problems.

thank you!
