### ISSUE TITLE
docs bug

### ISSUE THREAD

**Issue by ranjan-ranjan** [gabime/spdlog#1048]
There are some links in docs that redirect to `v1.x` branch. It should redirect to `master` branch.

Eg
![change branch to master](https://user-images.githubusercontent.com/16834561/55472618-2e7bef00-562a-11e9-8fb4-624cbb7b1431.png)
:

**Comment by gabime** [comment]
the v1.x is the main branch. master points to old version v0.x

**Comment by ranjan-ranjan** [comment]
should this `v1.x` branch merged with `master` branch?
