### ISSUE TITLE
Logger giving segmentation fault while logging

### ISSUE THREAD

**Issue by nj2901** [gabime/spdlog#1050]
I have created a logger and trying to log in it : 
```
logger->log(spd::log::info , "check data");

```

I am getting below error : 
```

***** SIGNAL SIGSEGV(11)

[2019-04-04 04:10:44.898] [critical]    stack dump [1]  /home/cubical/Downloads/LoggerProject/Logger+0x3d157 [0x564686c1f157]
        stack dump [2]  /lib/x86_64-linux-gnu/libpthread.so.0+0x12890 [0x7f1713e2c890]
        stack dump [3]  /home/cubical/Downloads/LoggerProject/Logger+0x39e0a [0x564686c1be0a]
        stack dump [4]  /home/cubical/Downloads/LoggerProject/Logger+0x399b0 [0x564686c1b9b0]
        stack dump [5]  /home/cubical/Downloads/LoggerProject/Logger+0x39c1e [0x564686c1bc1e]
        stack dump [6]  /home/cubical/Downloads/LoggerProject/Logger+0x43b9b [0x564686c25b9b]
        stack dump [7]  /home/cubical/Downloads/LoggerProject/Logger+0x3296d [0x564686c1496d]
        stack dump [8]  /home/cubical/Downloads/LoggerProject/Logger+0x29fbe [0x564686c0bfbe]
        stack dump [9]  /home/cubical/Downloads/LoggerProject/Logger+0xcb0e [0x564686beeb0e]
        stack dump [10]  /home/cubical/Downloads/LoggerProject/Logger+0x909f [0x564686beb09f]
        stack dump [11]  /lib/x86_64-linux-gnu/libc.so.6__libc_start_main+0xe7 [0x7f1713a4ab97]
        stack dump [12]  /home/cubical/Downloads/LoggerProject/Logger+0x897a [0x564686bea97a]

[2019-04-04 04:10:44.898] [critical] Received fatal signal: SIGSEGV(11) PID: 4691

***** SIGNAL SIGSEGV(11)



exitWithDefaultSignalHandler:205. Exiting due to signal , 11   


```

Though, specifically i have used signal_handler.h by @rxdu  and using that this error message is printing in my rotating file sink which means that logger is created and file is created successfully and data is logging in to it.

But i am not getting the reason why logger->log is giving error.

**Comment by tt4g** [comment]
There is too little information in the invoke `spdlog::logger::log()`.

Could you write your code such as `logger` initialization to solve the problem?

Better if it's a minimal snippet that can reproduce the problem.

**Comment by tt4g** [comment]
I found issue #486 that seems to be related to `signal_handler.h`.

@nj2901 You need to be careful in investigating the cause of this problem.

That's because `SIGSEGV` may occur somewhere unrelated to spdlog.

spdlog outputs to the log the `SIGSEGV` information notified to the process.
You should first check if you have problems even if you comment out `logger->log(...)`.
If you still have problems after commenting out `logger->log(...)`, please write a snippet.

**Comment by nj2901** [comment]
Yes, when i commented it out the problem doesn't reproduce. Even ``` logger->info() ``` is giving same type of segmentation fault.

my code snippet below : 

```
        std::cout<<"Creating asynchronous logger\n"<<std::flush;
        spdlog::init_thread_pool(8192, 1);
        auto logger = std::make_shared<spdlog::async_logger>(logger_name , sinks.begin(), sinks.end(), spdlog::thread_pool(), spdlog::async_overflow_policy::overrun_oldest);
        logger->set_level(getLogLevel(as_integer(globalLevel)));
        logger->flush_on(getLogLevel(3));
            std::cout<<"before logger log\n"<<std::flush;
//        logger->info("check with data \n");
//        logger->log(getLogLevel(3)," just check sme tect\n");
            std::cout<<"after logger log\n"<<std::flush;
        spdlog::register_logger(logger);
```
If i execute this, it works fine. But as soon as i uncomment logger->info() , it gives me segmentation fault.

**Comment by tt4g** [comment]
I have confirmed that the problem is reproduced in your snippet but I get error even if I commentout `logger->log(...)`.

I get an error in the `spdlog::init_thread_pool(8192, 1)`, there may be a difference that I'm building with MSVC 2017.

@nj2901 I would like to clarify if the error occurred differently.
Are you outputting `"before logger log"` to the console?

**Comment by tt4g** [comment]
In the case of MSVC, an error occurred inside the following call to `std::vector::emplace_back`:

https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/details/thread_pool.h#L134-L137

**Comment by nj2901** [comment]
Yes, before logger log is getting printed to console if just fine. 
Can you suggest in more  simple terms about this MSVC , emplace_back as i am not able to get your point.

**Comment by gabime** [comment]
signal handlers do work well with threads. see https://stackoverflow.com/questions/12952262/signal-handler-function-in-multithreaded-environment

**Comment by tt4g** [comment]
I'm compile and execute your snippet (I'm in a situation where only the MSVC 2017 compiler is currently available due to my own problems).
Then an error was encountered before getting output `"before logger log"` to console.

As a result of investigating where the error occurred using the `cdb` debugger, the result of `spdlog::init_thread_pool(8192, 1)` is called internally when the `spdlog::details::thread_pool` constructor is called. I found out that was happening.

Specifically, an error occurs when a new log writing thread is added by call `std::vector::emplace_back` on `std::vector<std::thread>` where the thread pool is managed.

**Comment by gabime** [comment]
@tt4g Does https://github.com/tt4g/spdlog-issue-1050/blob/master/main.cpp crash for you?

**Comment by tt4g** [comment]
> @tt4g Does https://github.com/tt4g/spdlog-issue-1050/blob/master/main.cpp crash for you?

Yes, crash this line: https://github.com/tt4g/spdlog-issue-1050/blob/0c5aad2d7bd10509e12f0675d76f66a879705198/main.cpp#L13

**Comment by gabime** [comment]
Please put  ```spdlog::shutdown();``` before end of main. This is a known msvc issue

**Comment by tt4g** [comment]
@gabime I'm updated source: https://github.com/tt4g/spdlog-issue-1050/blob/master/main.cpp#L36
However, happen 'Access violation reading location 0x0000000000000010` with MSVC 2017 in `std::vector::emplace_back`.

This error is different issue. 

I would like to execute the code in `gcc`, but it is currently not possible to use `gcc`.

**Comment by nj2901** [comment]
Now, it did work fine @gabime  @tt4g . But i want to ask that i want to use this logger in my always running code, then spdlog::Shutdown() should be called only in my destructor of the logger object right ?

**Comment by nj2901** [comment]
Also, i take my words back : 

```
https://github.com/tt4g/spdlog-issue-1050/blob/master/main.cpp
```
this is working fine for me.

But my actual use case is something like this : 
```
void createLogger(){
    std::cout << "Creating asynchronous logger" << std::endl;

    spdlog::init_thread_pool(8192, 1);

    std::vector<spdlog::sink_ptr> sinks({
            std::make_shared<spdlog::sinks::null_sink_mt>(),
            std::make_shared<spdlog::sinks::stdout_sink_mt>()
    });

    auto logger =
            std::make_shared<spdlog::async_logger>(
                    "async_logger" , sinks.begin(), sinks.end(),
                    spdlog::thread_pool(),
                    spdlog::async_overflow_policy::overrun_oldest);
    logger->set_level(spdlog::level::info);
    logger->flush_on(spdlog::level::info);

    spdlog::register_logger(logger);
    std::cout << "before logger log" << std::flush;

    logger->info("check with data \n"); // this works fine
    logger->log(spdlog::level::info, " just check sme tect\n");  //this works fine
    std::cout << "after logger log" << std::endl;

}

MyClassConstructor() {

    spdlog::installCrashHandlerOnce();
    
    createSinks();
    createLogger();
    std::cout<<"Before get\n"<<std::flush;
    logger = spdlog::get("logger"); // getting logger object in private member of the class
    std::cout<<"after get\n"<<std::flush;
   logger->info("check \n"); // this line is giving segmentation fault
    std::cout<<"after logger log\n"<<std::flush;
    consoleLogging = false;
}

```
Why so ? I have registered my logger then also i am getting Segmentation fault

**Comment by gabime** [comment]
you dont call get() with the right looger name "async_logger״

**Comment by nj2901** [comment]
Oh thanks, I thought that we need to call get() with the same name as we register .

Thanks @gabime , this works now. 
Also, spdlog::shutdown() should be called at extreme end or say in the destructor of my class right ? If i don't call spdlog::shutdown() what possible behaviour can be expected from spdlog ?

**Comment by gabime** [comment]
No, just call it once at the very end of main(). under msvc there are sometimes problems at end of main if shutdown not called.

**Comment by tt4g** [comment]
just for the record.

MSVC error was a problem of my environment.

Today, I installed MSVC 2019, which caused the tool to reference the MSVC 2019 toolset.
An error occurred when using the `cdb` debugger in this situation.

Without the `cdb` debugger, MSVC was also successful.

I apologize for causing confusion.

**Comment by gabime** [comment]
np. thanks for the update
