### ISSUE TITLE
warning when using spdlog

### ISSUE THREAD

**Issue by ranjan-ranjan** [gabime/spdlog#1051]
I am using spdlog with VS 2019. I have copy pasted the [spdlog folder](https://github.com/gabime/spdlog/tree/v1.x/include/spdlog) as given in the docs.
I got the following warnings:

1. spdlog\fmt\bundled\format-inl.h(722): warning C4244: 'argument': conversion from 'const unsigned __int64' to 'int', possible loss of data
2. spdlog\fmt\bundled\format-inl.h(722): note: This diagnostic occurred in the compiler generated function 'std::enable_if<sizeof(Double)==,bool>::type fmt::v5::internal::grisu2_format(Double,fmt::v5::internal::buffer &,fmt::v5::core_format_specs)'
3. spdlog\fmt\bundled\format-inl.h(722): warning C4244: 'argument': conversion from 'const unsigned __int64' to 'int', possible loss of data
4. spdlog\fmt\bundled\format-inl.h(722): note: This diagnostic occurred in the compiler generated function 'std::enable_if<sizeof(Double)==,bool>::type fmt::v5::internal::grisu2_format(Double,fmt::v5::internal::buffer &,fmt::v5::core_format_specs)'

**Comment by gabime** [comment]
That's fmtlib issue. Please reopen in the fmt repo instead
