### ISSUE TITLE
Only a part of large string written to file

### ISSUE THREAD

**Issue by yuanhuihe** [gabime/spdlog#1063]
Hi, I want to send a config text by socket and write it to a log file after the client received. But I found that only a part of config text was written to file.
>  ClientsManager::GetLogger()->debug("[request_config] config len:{}\n{}", len, data);
The length of string is 34366. Really a huge text. But in the log file, it only a 29918 length. Why?

**Comment by gabime** [comment]
try calling logger-> flush()
