### ISSUE TITLE
Using printf-style in v.1.3.1

### ISSUE THREAD

**Issue by ylaskin** [gabime/spdlog#1066]
Hi,
I'm understanding that you are removed printf-style support that was used by SPDLOG_FMT_PRINTF define. 

It's any simple way to add it to current version?
Thanks.

**Comment by tt4g** [comment]
It is not exactly the same `SPDLOG_FMT_PRINTF` function, spdlog v1.3.1 provides python like formatting API using fmt  (https://github.com/fmtlib/fmt),

fmt is also a header-only OSS, spdlog bundles the sources (you can use it `#include "spdlog/fmt/bundled/format.h"`).

If you are using the original fmt library, you can use the external source fmt for spdlog with the　`SPDLOG_FMT_EXTERNAL` macro.

**Comment by ylaskin** [comment]
I'm trying to use spdlog v1.3.1 without fmt external library so i tried to include spdlog/fmt/bundled/format.h to fmt/fmt.h after bundled/format.h but it's didn't work.

Could you please point to right place to include spdlog/fmt/bundled/format.h

Thanks.


> It is not exactly the same `SPDLOG_FMT_PRINTF` function, spdlog v1.3.1 provides python like formatting API using fmt (https://github.com/fmtlib/fmt),
> 
> fmt is also a header-only OSS, spdlog bundles the sources (you can use it `#include "spdlog/fmt/bundled/format.h"`).
> 
> If you are using the original fmt library, you can use the external source fmt for spdlog with the　`SPDLOG_FMT_EXTERNAL` macro.

**Comment by tt4g** [comment]
@ylaskin Sorry. I was conveying the wrong information, don't need additional includes when using builtin fmt.

You don't have to do anything. Just add the arguments when output log.

```cpp
logger->info("Hello! {} with artuments", "World"); // Hello! World with artuments
logger->info("format {:x}", 16); // format 10
```

**Comment by ylaskin** [comment]
I mean printf-style
logger->info("Hello! %s with artuments", "World");

> ```c++
> logger->info("Hello! {} with artuments", "World");
> ```

**Comment by tt4g** [comment]
printf-style does not seem to be already supported: https://github.com/gabime/spdlog/issues/976#issuecomment-456383439

I think the easiest way to format is to use fmt but You can use print-style API provided fmt if you don't care about performance.

http://fmtlib.net/latest/api.html#printf-api

```cpp
std::string message = fmt::sprintf("Hello! %s with artuments", "World");
logger->info(message);
```

**Comment by ylaskin** [comment]
Are any bench test for using {} style with printf-style

Thanks 

> printf-style does not seem to be already supported: [#976 (comment)](https://github.com/gabime/spdlog/issues/976#issuecomment-456383439)
> 
> I think the easiest way to format is to use fmt but you can use print-style API provided fmt if you don't care about performance.
> 
> http://fmtlib.net/latest/api.html#printf-api
> 
> ```c++
> #include <spdlog/spdlog.h>
> #include <spdlog/sinks/stdout_sinks.h>
> #include <spdlog/fmt/bundled/printf.h> // If using external fmt, #include fmt/printf.h
> 
> int main(int, char**) {
>     auto logger = spdlog::stdout_logger_mt("console-logger");
> 
>     std::string message = fmt::sprintf("Hello! %s with artuments", "World"); // Hello! World with artuments
>     logger->info(message);
> 
>     return 0;
> }
> ```
> 
> However, `fmt::sprintf` does not know how long support will continue with bundled fmt.

**Comment by gabime** [comment]
As @tt4g mentioned, printf is not supported in latest versions. 
An easy workaround would be wrapping in a macro that 
 calls snprintf into some temp buffer and then pass it to spdlog.

**Comment by tt4g** [comment]
@ylaskin I don't have benchmark and test.
However, since messages are always generated by fmt without log_level filtering, it can be imagined that memory and speed will be sacrificed for useless message construction.

**Comment by ylaskin** [comment]
so why don't using fmt::sprintf like @tt4g said?


> As @tt4g mentioned, printf is not supported in latest versions.
> An easy workaround would be wrapping in a macro that
> calls snprintf into some temp buffer and then pass it to spdlog.

**Comment by gabime** [comment]
Because you won't  need to include fmt's printf features, so compilation would be much faster (no templated call, no additional include). 

This will come on the cost of less secure code, since sprintf is not type safe but fmt is.

**Comment by ylaskin** [comment]
@gabime @tt4g 

I found that while I using spdlog instead my old logger the **compile time increase by twice**. (from 1.5 min. to 3 min.). I wrapped spdlog to singletone:

```
#pragma once
#ifndef LOGGER_H
#define LOGGER_H

#include <mutex>
#include <memory>
#include <spdlog/spdlog.h>
#include <spdlog/fmt/bundled/printf.h> // support for printf-style

namespace my {
    namespace Logger {
        class Log
        {
            public:
                Log();
                template <typename... Args> void info(const char* message, const Args&... args)     { logger_->info(fmt::sprintf(message, args...)); }
                ...
                static Log* getInstance();
            private:
                static Log* instance_;
                static std::once_flag initFlag_;
                static std::shared_ptr<spdlog::logger> logger_;
        };

        template <typename... Args> void Info(const char* message, const Args&... args)     { Log::getInstance()->info(message, args...); }
		...
    }
}

#define LOG_INFO(MESSAGE, ...)							innovi::Logger::Info(MESSAGE, ##__VA_ARGS__)
...

#endif /* LOGGER_H */
```

**Comment by gabime** [comment]
@ylaskin  Thanks.You can checkout the static-lib branch. It implements a statically compiled lib of spdlog(cmake -DSPDLOG_STATIC_LIB=ON), which reduce the compile time by 40-50%.

Will be merged to master soon ,but it is still wip.

**Comment by ylaskin** [comment]
I see that I should define SPDLOG_STATIC_LIB before include spdlog/spdlog.h.
It seem like you should add config.h to spdlog.h with default defines while use: make install


> @ylaskin Thanks.You can checkout the static-lib branch. It implements a statically compiled lib of spdlog(cmake -DSPDLOG_STATIC_LIB=ON), which reduce the compile time by 40-50%.
> 
> Will be merged to master soon, but it is still wip.

**Comment by gabime** [comment]
Maybe.. whats the common practice with cmake install?
