### ISSUE TITLE
libfmt OSX error

### ISSUE THREAD

**Issue by ladoramkershner** [gabime/spdlog#1067]
I'm finding an error similar to this

https://github.com/fmtlib/fmt/issues/1115

The issue has been fixed and merged, but the bundled fmt needs to updated to fix this in spdlog.

**Comment by gabime** [comment]
this will have to wait for formal fmt to release, since spdlog use only fmt formal releases.

**Comment by vedranmiletic** [comment]
Also affects GCC 7.4 on Debian. I have asked if there are any plans for a release with this patch on the fmt issue.

**Comment by vedranmiletic** [comment]
@gabime As you might already know, fmt 6.0.0 with the fix included has been released: https://github.com/fmtlib/fmt/releases/tag/6.0.0

**Comment by gabime** [comment]
Fixed
