### ISSUE TITLE
Thread ID in formatter ignores child thread id

### ISSUE THREAD

**Issue by dyoungworth** [gabime/spdlog#1069]
I would expect the formatter to grab the thread ID of the current child thread, but it only prints the parent thread in which the logger was created.

```
auto trace = spdlog::rotating_logger_mt("tr", trace.json", 1000000, 10);
 trace->set_pattern("ThreadID:'%t', Output:'%v'");
trace->info("start");

pid_t pid = fork();

if (pid == 0) {
trace->info("child thread");
return 0;
}

trace->info("parent thread created child thread {}", pid);
```
All lines get the same thread ID:
```
ThreadID:61386, start
ThreadID:61386, child thread
ThreadID:61386, parent thread created child thread 61389
```

**Comment by gabime** [comment]
duplicate of https://github.com/gabime/spdlog/issues/385

**Comment by dyoungworth** [comment]
That works!  Note it is `#define SPDLOG_DISABLE_TID_CACHING` in master branch.

Thank you gabime!
