### ISSUE TITLE
Clear/truncate log content

### ISSUE THREAD

**Issue by meraj321** [gabime/spdlog#1070]
HI,

I am using pretty old version of spdlog (ver: 0.12.0). Does it has support for cleaning the log content? I am using rotating file mt sync.

**Comment by tt4g** [comment]
When do you want to truncate the log contents?

When did you generate a sink? Or is it time to call function?

**Comment by meraj321** [comment]
I want to truncate the log file based on time say after 15 minutes.

so here is my requirement:
1: Application starts  -> sync generated
2: user presses start logging button on application's UI.
3: application starts logging default for 10 minutes.
4: or user presses stop logging button on application's UI, application
stops logging.

In both cases either user presses stop button or default after 10 minutes,
logging should stop and all previous logged content should be deleted.
Either log file should be deleted or file content should be deleted, I am
fine any of these two.

Thanks,
Meraj03

**Comment by tt4g** [comment]
Do you want to delete the log file after rotation?
If so, I think you can use the `max_files=1` option.

https://github.com/gabime/spdlog/blob/93d84e5d594b15be0abef4998cdd1a5be72db476/include/spdlog/sinks/file_sinks.h#L67-L68

If you only need one log file at all times, you can use `simple_file_sink`, and set `truncate=true`.

https://github.com/gabime/spdlog/blob/93d84e5d594b15be0abef4998cdd1a5be72db476/include/spdlog/sinks/file_sinks.h#L32-L35

**Comment by meraj321** [comment]
Thanks,

so basically in my case say i use simple_file_sink then I should set
truncate = true and after 10 minutes again open the sync so that all
previous content will be deleted?
Also do I need to call drop() also just before reopening the sync?

Please assist.

**Comment by tt4g** [comment]
> Also do I need to call drop() also just before reopening the sync?

Yes. If you want to clear the log contents every time it is better to drop the sink (or logger)

**Comment by meraj321** [comment]
Thanks,

Last question: so which function() call exactly deletes the content? sync
drop() or opening the sync again?

Thanks,
Meraj

**Comment by tt4g** [comment]
`simple_file_sink` does not seem to delete log file.
You need to manually remove it when application exit.
