### ISSUE TITLE
Spdlog giving below errors for the first time

### ISSUE THREAD

**Issue by nj2901** [gabime/spdlog#1071]
In file included from /usr/local/include/spdlog/formatter.h:9:
/usr/local/include/spdlog/spdlog/details/log_msg.h:16:8: error: redefinition of 'log_msg'
struct log_msg
       ^
/usr/local/include/spdlog/details/log_msg.h:16:8: note: previous definition is here
struct log_msg
       ^
In file included from /home/pi/loggerpoc/main.cpp:2:
In file included from /home/pi/loggerpoc/Logger.h:13:
In file included from /home/pi/loggerpoc/spdlog/spdlog.h:13:
In file included from /usr/local/include/spdlog/details/registry.h:15:
In file included from /usr/local/include/spdlog/logger.h:23:
In file included from /usr/local/include/spdlog/spdlog/sinks/sink.h:9:
In file included from /usr/local/include/spdlog/details/pattern_formatter.h:12:
/usr/local/include/spdlog/formatter.h:13:7: error: redefinition of 'formatter'
class formatter
      ^
/usr/local/include/spdlog/spdlog/formatter.h:13:7: note: previous definition is here
class formatter
      ^
In file included from /home/pi/loggerpoc/main.cpp:2:
In file included from /home/pi/loggerpoc/Logger.h:13:
In file included from /home/pi/loggerpoc/spdlog/spdlog.h:13:
In file included from /usr/local/include/spdlog/details/registry.h:15:
In file included from /usr/local/include/spdlog/logger.h:23:
In file included from /usr/local/include/spdlog/spdlog/sinks/sink.h:9:
/usr/local/include/spdlog/details/pattern_formatter.h:1036:31: error: no matching function for call to 'make_unique'
        formatters_.push_back(details::make_unique<details::full_formatter>(details::padding_info{}));
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/spdlog/spdlog/common.h:236:20: note: candidate template ignored: substitution failure [with T =
      spdlog::details::full_formatter, Args = <spdlog::details::padding_info>]
std::unique_ptr<T> make_unique(Args &&... args)
                   ^

**Comment by gabime** [comment]
which compiler version and os are you using?

**Comment by nj2901** [comment]
pi@raspberrypi:~ $ clang --version
clang version 3.8.1-24+rpi1 (tags/RELEASE_381/final)
Target: armv6--linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin

**Comment by nj2901** [comment]
Hi gabime,
its resolved.
I mistakenly had spdlog/ folder inside my original spdlog/ folder. When i removed it , it worked fine. 
Thanks for always replying.
