### ISSUE TITLE
Message not sent to syslog on OSX

### ISSUE THREAD

**Issue by terrisgit** [gabime/spdlog#1072]
spdlog-1.3.1 
OSX 10.13.6 High Sierra due to old hardware MacBook Pro (17-inch, Late 2011)

The following code works on Linux but not OSX. 

Two lines are sent to stdout but nothing is written to OSX's syslog. I am looking for messages via the 'console' app and in /var/log/system.log

```
#include "spdlog/sinks/dist_sink.h"
#include "spdlog/sinks/syslog_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#include <memory>

int main (int argc, const char** argv) {
  auto syslog_sink = std::make_shared<spdlog::sinks::syslog_sink_mt>("please.help.me");
  auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();

  auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_st>();
  dist_sink->add_sink(syslog_sink);
  dist_sink->add_sink(console_sink);

  auto logger = std::make_shared<spdlog::logger>("my_logger", dist_sink);
  logger->set_level(spdlog::level::info);
  logger->error("error");
  logger->info("info");
  logger->debug("debug");
}
```

**Comment by tt4g** [comment]
I do not have MacOS and I do not have details.
However, I will keep a record of what I found out.

Recent Mac OS seems to be forwarding syslog to Apple System Log.

It seems necessary to check both `/etc/syslog.conf` and `/etc/asl.conf` carefully to check the log output destination.

By default, ASL discards logs less important than syslog level `LOG_NOTICE`.

**Comment by terrisgit** [comment]
Thank you!
