### ISSUE TITLE
spdlog in debug mode can't init for singleton

### ISSUE THREAD

**Issue by jamesmasika** [gabime/spdlog#1073]
Monitor_Spdlog::Monitor_Spdlog()
{
	std::string path = "../logs2";
	if (ACCESS(path.c_str(), 0))
	{
		MKDIR(path.c_str());
	}
	std::string fileName = path + "/syslog.log";
	try {
		m_logger = spdlog::daily_logger_st("SpdMonitor", fileName.c_str(), 2, 30);
		//m_logger->set_level(spdlog::level::info);
		m_logger->warn("create {}", __FUNCTION__);
		Monitor_Spdlog::IsReady = true;
	}
	catch (const std::exception &e)
	{
		printf("%s\n",e.what());
		Monitor_Spdlog::IsReady = false;
	}
}

it showed "argument index out of range" ???

**Comment by jamesmasika** [comment]
i found the exception was throwed by the below function.

struct daily_filename_calculator
{
    // Create filename for the form basename.YYYY-MM-DD
    static filename_t calc_filename(const filename_t &filename, const tm &now_tm)
    {
        filename_t basename, ext;
        std::tie(basename, ext) = details::file_helper::split_by_extension(filename);
        std::conditional<std::is_same<filename_t::value_type, char>::value, fmt::memory_buffer, fmt::wmemory_buffer>::type w;
        #fmt::format_to(
            w, SPDLOG_FILENAME_T("{}_{:04d}-{:02d}-{:02d}{}"), basename, now_tm.tm_year + 1900, now_tm.tm_mon + 1, now_tm.tm_mday, ext);
        return fmt::to_string(w);
    }
};

**Comment by gabime** [comment]
When does the singleton get created?
Please provide a fully reproducible example code.

**Comment by jamesmasika** [comment]
it only worked with release mode in my project,  my predefined macros were same to the demo, thanks.

#ifndef Monitor_Spdlog_H_
#define Monitor_Spdlog_H
#include "spdlog/spdlog.h"
#include "spdlog/sinks/daily_file_sink.h"
#define SPDLOGGER Monitor_Spdlog::GetInstance()
#define SPDLOG(functionName, fmt, ...) SPDLOGGER.m_logger->##functionName(fmt,##__VA_ARGS__);

class Monitor_Spdlog {
public:
	virtual ~Monitor_Spdlog();
	void SetLogLevel(int level);
private:
	Monitor_Spdlog();
	
	Monitor_Spdlog(const Monitor_Spdlog& rhs){};
	Monitor_Spdlog& operator =(const Monitor_Spdlog& rhs){};
public:
	std::shared_ptr<spdlog::logger> m_logger;
	static Monitor_Spdlog& GetInstance(){
		return m_instance;
	}
private:
	static Monitor_Spdlog m_instance;
};

#endif

///////////////////////////////////////////////////////////////////////////////////////////////////
#include "monitor_Spdlog.h"
Monitor_Spdlog Monitor_Spdlog::m_instance;

Monitor_Spdlog::~Monitor_Spdlog()
{
}

Monitor_Spdlog::Monitor_Spdlog()
{
	std::string path = "../logs";
	if (ACCESS(path.c_str(), 0))
	{
		MKDIR(path.c_str());
	}
	std::string fileName = path + "/syslog.log";
	try {
		m_logger = spdlog::daily_logger_st("SpdMonitor", fileName.c_str(), 2, 30);
		m_logger->warn("create {}", __FUNCTION__);
	}
	catch (const std::exception &e)
	{
		printf("%s\n",e.what());
	}
}

**Comment by tt4g** [comment]
For your record.

I executed the sample code as follows with Visual Studio 2017 (Debug mode) but could not reproduce it (argument index out of range):

`monitor_Spdlog.hpp.hpp`

```cpp
#ifndef Monitor_Spdlog_H_
#define Monitor_Spdlog_H

#include "spdlog/spdlog.h"
#include "spdlog/sinks/daily_file_sink.h"

#define SPDLOGGER Monitor_Spdlog::GetInstance()
// #define SPDLOG(functionName, fmt, ...) SPDLOGGER.m_logger->##functionName(fmt,##VA_ARGS);
#define SPDLOG(functionName, fmt, ...) SPDLOGGER.m_logger->##functionName(fmt,__VA_ARGS__);

class Monitor_Spdlog
{
public:

    virtual ~Monitor_Spdlog();
    // void SetLogLevel(int level);

private:

    Monitor_Spdlog();

    Monitor_Spdlog(const Monitor_Spdlog& rhs){};

    Monitor_Spdlog& operator =(const Monitor_Spdlog& rhs){};

public:
    std::shared_ptr<spdlog::logger> m_logger;

    static Monitor_Spdlog& GetInstance(){

        return m_instance;
    }

private:

    static Monitor_Spdlog m_instance;
};

#endif

```

`monitor_Spdlog.cpp`

```cpp
#include "monitor_Spdlog.hpp"

Monitor_Spdlog Monitor_Spdlog::m_instance;

Monitor_Spdlog::~Monitor_Spdlog()
{
}

Monitor_Spdlog::Monitor_Spdlog()
{
    std::string fileName = "syslog.log";
    try {
        m_logger = spdlog::daily_logger_st("SpdMonitor", fileName.c_str(), 2, 30);
        m_logger->warn("create {}", "Monitor_Spdlog()");
    } catch (const std::exception &e) {
        printf("%s\n",e.what());
    }
}

```
`main.cpp`

```cpp
#include <iostream>
#include <memory>
#include <vector>

#include "monitor_Spdlog.hpp"

int main(int, char**) 
{

    SPDLOG(info, "Hello!, World! {} {}", 1, 2);

    return 0;
}
```

However, when `main.cpp` is changed as follows, the message `"[*** LOG ERROR ***] [2019-04-30 22:12:49] [SpdMonitor] argument index out of range"` is output to the console (it seems to `_default_err_handler` of spdlog is output to the console).

```cpp
#include <iostream>
#include <memory>
#include <vector>

#include "monitor_Spdlog.hpp"

int main(int, char**) 
{
//    SPDLOG(info, "Hello!, World {} {}", 1, 2);
    SPDLOG(info, "Hello!, World {} {} {}", 1, 2); // 
Braces more than the number of arguments..

    return 0;
}

```

If the error message you are looking for has a similar format, it is possible that the argument specification method of fmt library is wrong.
