### ISSUE TITLE
Add option to force color output without TTY

### ISSUE THREAD

**Issue by psalz** [gabime/spdlog#1074]
Currently the `ansicolor_sink` [checks for a TTY with color support](https://github.com/gabime/spdlog/blob/366935142780e3754b358542f0fd5ed83793b263/include/spdlog/sinks/ansicolor_sink.h#L41) in order to decide whether it should actually output any color codes. That is fine, however in some situations it is desirable to force color output anyway - for example when piping outputs through another executable.

Many applications thus typically provide a flag to force color output regardless of the destination, for example Clang's `-fcolor-diagnostic`. As far as I can tell there is currently no way (other than providing a custom sink) to enable such a flag using spdlog.

I thus propose adding an optional parameter to the color sink factory functions, i.e., ```stdout_color_mt(const std::string &logger_name, bool force_color = false)``` which will then be passed into the constructor of `ansicolor_sink` (not sure how the behavior for wincolor is or what the conventions are).

Alternatively / additionally a member function could be added to the sink, e.g. `ansicolor_sink::force_color_output(bool value)`.

**Comment by gabime** [comment]
Agreed. I think ansicolor_sink::force_color_output is preferable to change to the ctor.

**Comment by psalz** [comment]
What do you think about adding the option to the factory functions though? They could then call `force_color_output` internally before returning the pointer. My concern is that having it only on the sink requires care in user code because the sink returned by `stdout_color_mt` is platform dependent.

**Comment by gabime** [comment]
Yea, sounds good.

**Comment by gabime** [comment]
Closed. Thanks @psalz for fixing.
