### ISSUE TITLE
Compiler warning with gcc-9 shipped with Fedora 30

### ISSUE THREAD

**Issue by bsergean** [gabime/spdlog#1077]
Here is the error.

```
/tmp/cmake/ws/../third_party/spdlog/include/spdlog/fmt/bundled/format.h:3475:55: warning: ISO C++ did not adopt string literal operator templates taking an argument pack of characters [-Wpedantic]
 3475 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
      |                                                       ^~~~~~~~
```

If someone has an idea I can help to validate the fix.

**Comment by gabime** [comment]
This is part of the fmtlib code. Seems it has already been  reported [here](https://github.com/fmtlib/fmt/issues/1148).

**Comment by bsergean** [comment]
Ah thanks for the link. It looks like they have fixed the problem so whenever you guys update fmtlib this should be fixed.

**Comment by DennisOSRM** [comment]
> Ah thanks for the link. It looks like they have fixed the problem so whenever you guys update fmtlib this should be fixed.
> […](#)

@gabime Would it be possible to cut a new release s.t. other projects depending on it can upgrade?

**Comment by gabime** [comment]
This will have to wait for official fmt release (some time after june 21 ( https://github.com/fmtlib/fmt/issues/1160#issuecomment-492449920 )

**Comment by limitedAtonement** [comment]
Please update when that fmt release is ready and spdlog compiles again. In the meantime, I did:

<pre>diff --git a/include/spdlog/fmt/bundled/format.h b/include/spdlog/fmt/bundled/format.h
index 1bb24a5..a4dc1e1 100644
--- a/include/spdlog/fmt/bundled/format.h
+++ b/include/spdlog/fmt/bundled/format.h
@@ -126,7 +126,7 @@ FMT_END_NAMESPACE
       FMT_GCC_VERSION >= 407 || FMT_MSC_VER >= 1900) && \
       (!(FMT_ICC_VERSION || FMT_CUDA_VERSION) || \
        FMT_ICC_VERSION >= 1500 || FMT_CUDA_VERSION >= 700)
-#  define FMT_USE_USER_DEFINED_LITERALS 1
+#  define FMT_USE_USER_DEFINED_LITERALS 0
 # else
 #  define FMT_USE_USER_DEFINED_LITERALS 0
 # endif
</pre>I couldn't figure out a way to do this by setting `#define`s.
