### ISSUE TITLE
Crash while trying to use a logger after shutdown

### ISSUE THREAD

**Issue by boschpsirt** [gabime/spdlog#1078]
While fuzzing the library with libfuzzer we encountered a bug that leads to a segmentation fault.
The crash occurs while trying to use a logger after calling the shutdown function.

Tested versions: 1.3.0 and 1.3.1 (361dab82 resp. 20174aaa)

Minimal Example:
```c
#include <cstdio>

#include "spdlog/spdlog.h"

int main(int, char *[])
{
    spdlog::shutdown();
    spdlog::info("Welcome to spdlog version {}.{}.{} !", SPDLOG_VER_MAJOR, SPDLOG_VER_MINOR, SPDLOG_VER_PATCH); // BUG: try to use a logger ater shutdown

}
```

**Comment by tt4g** [comment]
`spdlog::shutdown()` releases all `std::shared_ptr` of loggers and default_logger.

You can't call `spdlog::info(...)` after `spdlog::shutdown()` because it's using default_logger.

**Comment by gabime** [comment]
right. this is by design.. shutdown is the last function call to spdlog.
