### ISSUE TITLE
file logger in the example not write to file

### ISSUE THREAD

**Issue by xzwang2005** [gabime/spdlog#108]
When I compile and run the example.cpp in Visual Studio 2013, the program hang in the end, leaving the console window open. And the log files created were empty.  Looks like the logs were not flushed in time.   As soon as I comment out the async logging part, everything works fine.  I've tried to set a flush timer for async logger but didn't work.

**Comment by kesinger** [comment]
I'm getting the hangs as well, but it appears to work fine on osx.

**Comment by gabime** [comment]
Thats a known issue of the visual studio compiler regarding joining threads.

**Comment by xzwang2005** [comment]
could you give more details? like how to work around the issue?

**Comment by gregoire-astruc** [comment]
Maybe using the native API for VS < 2015?

Something along those lines:

```cpp
// 1800 is msvc version in VS2013
#if defined(_MSC_VER) && _MSC_VER <= 1800
WaitForSingleObject(the_thread.native_handle(), INFINITE);
#else
the_thread.join();
#endif
```

**Comment by gabime** [comment]
Thanks I will try this.

**Comment by gabime** [comment]
@xzwang2005 see https://connect.microsoft.com/VisualStudio/feedback/details/747145 for details

**Comment by gabime** [comment]
@xzwang2005 Doesn't happen under VS 2013 update 5 (do you call ```spdlog::drop_all()```  at the end of main? you need too)
