### ISSUE TITLE
Crash while trying to retrieve uninitialized logger from a global registry

### ISSUE THREAD

**Issue by boschpsirt** [gabime/spdlog#1080]
While fuzzing the library with libfuzzer we encountered a bug that leads to a segmentation fault.

The crash occurs while trying to retrieve uninitialized logger from a global registry.

Tested versions: 0.16.3 (915ebcf9)

Minimal Example:

```c
#include "spdlog/spdlog.h"

// #include <iostream>
// #include <memory>

namespace spd = spdlog;

int main(int, char*[])
{
    try
    {
        spd::get("console")->info("try to retrieve uninitialized logger from a global registry ");
    }
    // catch thrown std::string or int or any other unrelated type
    catch (...) {
        return 1;
    }
    return 0;
}
```

**Comment by gabime** [comment]
it returns nullptr so it is expected. one must check the return value if there is a doublf
