### ISSUE TITLE
Configuration files misplaced if used as submodule

### ISSUE THREAD

**Issue by peanutfun** [gabime/spdlog#1081]
### Description
`spdlog` places the CMake version file and the `pkg-config` version file into directories relative to `${CMAKE_BINARY_DIR}`. We include `spdlog` as Git Submodule into our source tree. The `${CMAKE_BINARY_DIR}` therefore is not the top-level binary dir of `spdlog`, but of the entire project. I figure it is undesireable that the config files end up out of the actual `spdlog` build tree. Files affected:
* `spdlog.pc`
* `spdlogConfigVersion.cmake`

### How to fix this
Favor `${PROJECT_BINARY_DIR}` over `${CMAKE_BINARY_DIR}`. This will make sure that the files always end up in the binary dir of `spdlog`, even if it is used as sub-project in a larger source tree.

**Comment by peanutfun** [comment]
Sorry, I'm still on an old version. I just realized issue was fixed in 90a299f42489a49122d13e14edba0a0da9466123

Anyway, this just shows how well maintained this library is. Keep up the good work! 😊

**Comment by gabime** [comment]
@peanutfun Thanks for the feedback
