### ISSUE TITLE
Lazy log file creation

### ISSUE THREAD

**Issue by gexclaude** [gabime/spdlog#1083]
I wonder whether it is or would be possible that spdlog only creates a log file when it is required (lazily). 

My use case is, that I have an executable which outputs no log if there is no error or warning. In those majority of cases the log file is just not needed and would be nice if it wasn't created at all. Is there any way to achieve this?

**Comment by gabime** [comment]
Not directly, but you can postpone the creation of the logger until needed.

**Comment by gexclaude** [comment]
I see, so I would have to wrap the actual spdlog-calls to do so.
Would impact my code more than I'd like to.

**Comment by gabime** [comment]
Another option would be to start with empty logger with no sinks, and add the file sink on first error

**Comment by gexclaude** [comment]
I assume log statements get discarded as long as sink is null and not queue up until sink is provided?

**Comment by gabime** [comment]
right.

**Comment by gexclaude** [comment]
@gabime when I have a look at https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/basic_file_sink-inl.h I wonder if it wouldn't be possible to lazily create the log file? Calling file_helper_.open just once before any other method like sink_it_ or flush_ is being called. What do you think? Do you see any issues with such an approach? We could think of a separate, "lazy-basic-file-sink" though...

I'd be more than happy to get your opinion on that.

**Comment by gabime** [comment]
The main motivation for eagerly opening the file is to fail fast in case of error and notify about this asap using an exception..
Otherwise failing to open might happen too late todo something about it. 
Also spdlog never throws while logging so even an exception wont happen (by default errors curing logging are printed to console).

**Comment by gexclaude** [comment]
I expected this being a design decision. In my case it would have been okay if an error occurs but no exception is thrown during logging (no fail fast). I use logging only for in error situations which are reproducible, therefore this would not have been an issue.

**Comment by gabime** [comment]
His about creating the logger/sink lazily on first error?

**Comment by gexclaude** [comment]
Lazily on first log event that makes it to the sink. Usually "warning" level is set, so there are no log events if processing goes normal. In case of issues, we set "trace" log level and get all in depth log statements.

**Comment by gabime** [comment]
Then the easiest would be just a copy/paste your custom `lazy-basic-file-sink.

Should take 10 minutes.

**Comment by gexclaude** [comment]
Yes, that is what I'd do if a lazy file sink is not of interest for spdlog itself.

**Comment by gabime** [comment]
>  is not of interest for spdlog itself

Not at the moment, but it would be cool if you could post the code here for refernce.

**Comment by gexclaude** [comment]
Sure, when I implement it, I will post the code for sure. You do a great job with this library!

**Comment by gabime** [comment]
Thanks @gexclaude

**Comment by gexclaude** [comment]
So, this is pretty much what I'm doing

`//
// spdlog Copyright(c) 2015-2018 Gabi Melman, see https://github.com/gabime/spdlog
// this is a simple lazy variant of https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/basic_file_sink.h
//

#pragma once

#ifndef SPDLOG_H
#include "spdlog/spdlog.h"
#endif

#include "spdlog/details/file_helper.h"
#include "spdlog/details/null_mutex.h"
#include "spdlog/sinks/base_sink.h"

#include <mutex>
#include <string>

namespace spdlog {
    namespace sinks {
        /*
         * Trivial lazy initialized file sink with single file as target
         */
        template<typename Mutex>
        class basic_lazy_file_sink final : public base_sink<Mutex>
        {
        public:
            explicit basic_lazy_file_sink(const filename_t &filename, bool truncate = false)
            {
                filename_ = filename;
                truncate_ = truncate;
            }

        protected:
            void sink_it_(const details::log_msg &msg) override
            {
                if(file_helper_.filename().empty())
                {
                    // not yet initialized, do it now
                    try
                    {
                        file_helper_.open(filename_, truncate_);
                    }
                    catch (const spdlog_ex&)
                    {
                        // file open failed, try fallback log file once
                        if(filename_ != "spdlog_fallback.txt")
                        {
                            filename_ = "spdlog_fallback.txt";
                            try
                            {
                                file_helper_.open(filename_, truncate_);
                            }
                            catch (const spdlog_ex&)
                            {
                                // trade off of a lazy initialized file logger -> we don't want to throw the exception during sink, therefore swallow it
                            }
                        }
                    }
                }

                if(!file_helper_.filename().empty())
                {
                    fmt::memory_buffer formatted;
                    sink::formatter_->format(msg, formatted);
                    file_helper_.write(formatted);
                }
            }

            void flush_() override
            {
                file_helper_.flush();
            }

        private:
            filename_t filename_;
            bool truncate_;
            details::file_helper file_helper_;
        };

        using basic_lazy_file_sink_mt = basic_lazy_file_sink<std::mutex>;
        using basic_lazy_file_sink_st = basic_lazy_file_sink<details::null_mutex>;

    } // namespace sinks

    //
    // factory functions
    //
    template<typename Factory = default_factory>
    inline std::shared_ptr<logger> basic_lazy_logger_mt(const std::string &logger_name, const filename_t &filename, bool truncate = false)
    {
        return Factory::template create<sinks::basic_lazy_file_sink_mt>(logger_name, filename, truncate);
    }

    template<typename Factory = default_factory>
    inline std::shared_ptr<logger> basic_lazy_logger_st(const std::string &logger_name, const filename_t &filename, bool truncate = false)
    {
        return Factory::template create<sinks::basic_lazy_file_sink_st>(logger_name, filename, truncate);
    }

} // namespace spdlog
`

**Comment by gabime** [comment]
Thanks. Note that spdlog already swallows exceptions from sinks so there is no need to do it here.

**Comment by gexclaude** [comment]
> Thanks. Note that spdlog already swallows exceptions from sinks so there is no need to do it here.

thanks for the hint, therefore I do not need the most inner try-catch then?

**Comment by gabime** [comment]
Right

**Comment by gexclaude** [comment]
Okay: https://gist.github.com/gexclaude/4f867c4b288c4f1c1426a2ce654ee3e6

**Comment by jamesvanvurensafesend** [comment]
Thanks to gexclaude for posting his code. We needed it for our Adobe Acrobat plugin. When Acrobat is configured to run in protected mode, if an Acrobat plugin tries to write to a log file while the plugin is being loaded by Acrobat, even if only to create an empty log file, Acrobat itself will fail to start. We were able to work around this by using gexclaude's gist, along with overriding the spd logging level to "off" when Acrobat is in protected mode.
