### ISSUE TITLE
Rotating file sink: reopen deleted log file

### ISSUE THREAD

**Issue by kevintjen** [gabime/spdlog#1085]
Hello, I'm trying out spdlog's rotating file logger, and I'm discovering that when I delete a log file while it should be open and in use, the deleted file is not automatically recreated (unless the file name rotates back around).  Is this expected behavior, and if so, are there any plans to mitigate it?

As an experiment, I added a simple check to `spdlog::sinks::rotating_file_sink::sink_it_()` on whether the filename in the file helper exists and to `reopen()` the file if necessary, but I haven't tried looking at the overhead that would add, or how to address the possible overhead.

**Comment by gabime** [comment]
yes this is expected. don't delete files while they are open.
