### ISSUE TITLE
"Identifier not found" on Windows

### ISSUE THREAD

**Issue by Omegastick** [gabime/spdlog#1086]
I'm trying to port a program using spdlog over to Windows, but I'm getting the following build errors from Spdlog:
```
C:\Users\Omega\prog\bots\lib\spdlog\include\spdlog/details/os.h(134): error C3861: '_get_osfhandle': identifier not found [C:\Users\Omega\prog\bots\build\Graphics.vcxproj]
C:\Users\Omega\prog\bots\lib\spdlog\include\spdlog/details/os.h(220): error C3861: '_filelength': identifier not found [C:\Users\Omega\prog\bots\build\Graphics.vcxproj]
C:\Users\Omega\prog\bots\lib\spdlog\include\spdlog/details/os.h(414): error C3861: '_isatty': identifier not found [C:\Users\Omega\prog\bots\build\Graphics.vcxproj]
```

Compiling with VS2017, CMake build system.

Any ideas?

**Comment by tt4g** [comment]
It may be that the header which is not `io.h` of Windows system is included.

Could you confirm that the file `io.h` does not exist under include paths in your project?

The post of Stackoverflow may be helpful: https://stackoverflow.com/questions/2526659/header-correct-but-identifier-not-found/2527074

**Comment by Omegastick** [comment]
Ah yes, I have an io.h in my project. I'll check in the morning.
