### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by acajic** [gabime/spdlog#1087]
I use revision #2d8737

I am seeing this line in stdout.

[*** LOG ERROR ***] [logger] [std::bad_alloc] [2019-05-24 12:19:56]

Logger is initialized like this:

		logger = spdlog::rotating_logger_mt(LOGGER_NAME, "log", 1048576 * 15, 10); // three rotating log files of 15mb
		logger->set_level(spdlog::level::info);
		logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e %z] [%L] [%t] %v");
		spdlog::set_async_mode(65536, spdlog::async_overflow_policy::discard_log_msg);

I understand you will probably advise to first update to the latest version. But what can be the cause of this?

**Comment by tt4g** [comment]
This problem seems to be related: #458

In previous versions it seems that async logger and sync logger could not exist simultaneously.

**Comment by acajic** [comment]
Sorry, my bad. Some of the strings I was passing to the logger were deallocated.
