### ISSUE TITLE
no stdout_color_sinks.h in libspdlog-dev 1:0.11.0-2 package on debian:stretch

### ISSUE THREAD

**Issue by kgbook** [gabime/spdlog#1088]
Built [ failed on debian](https://circleci.com/gh/kgbook/RTSPServer/25).

I even installed `spdlog` on my pc with the command `apt-get install -y libspdlog-dev`, and found no such file using `find /usr -name stdout_color_sinks.h`.

Then I ran `ls /usr/include/spdlog/sinks/*stdout*`, 
```shell
(base) alpha@debian:~$ ls /usr/include/spdlog/sinks/*stdout*
/usr/include/spdlog/sinks/stdout_sinks.h
```

As a result, no `stdout_color_sinks.h`.

Also no such file in the [file list of packages libspdlog-dev in stretch of architecture amd64](https://packages.debian.org/stretch/amd64/libspdlog-dev/filelist)

## Related information

libspdlog-dev **version 1:0.11.0-2**

If detailed log needed, see [CircleCI](https://circleci.com/gh/kgbook/RTSPServer/25) please.

### Install log:
```shell
#!/bin/bash -eo pipefail
apt-get install -y libspdlog-dev

Reading package lists... Done


Building dependency tree       


Reading state information... Done

The following NEW packages will be installed:
  libspdlog-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 132 kB of archives.
After this operation, 434 kB of additional disk space will be used.

Get:1 http://deb.debian.org/debian stretch/main amd64 libspdlog-dev amd64 1:0.11.0-2 [132 kB]

Fetched 132 kB in 0s (8334 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libspdlog-dev.
(Reading database ... 36879 files and directories currently installed.)
Preparing to unpack .../libspdlog-dev_1%3a0.11.0-2_amd64.deb ...
Unpacking libspdlog-dev (1:0.11.0-2) ...
Setting up libspdlog-dev (1:0.11.0-2) ...

```

### Build log:
```shell
/root/project/common/skeleton/../utils/include/log.h:11:45: fatal error: spdlog/sinks/stdout_color_sinks.h: No such file or directory
 #include <spdlog/sinks/stdout_color_sinks.h>
```

**Comment by gabime** [comment]
I pretty sure that libspdlog-dev is just old and obsolete package.

**Comment by kgbook** [comment]
> I pretty sure that libspdlog-dev is just old and obsolete package.

@gabime  I used debian:buster instead of debian:stretch to upgrade 1:1.3.1-1 version. Now it built well.
The latest stable version of libspdlog-dev on debian is 1:0.11.0-2.

Thanks.

**Comment by kgbook** [comment]
Hope someone upgrade to 1:1.3.1-1 version on  debian:stretch.
