### ISSUE TITLE
Specify different patterns for different log levels

### ISSUE THREAD

**Issue by mrzv** [gabime/spdlog#109]
It would be nice if it was possible to specify different patterns for different log levels. I'm specifically interested in setting colors for warnings and critical messages that are printed on the console.

This should probably be a feature in sinks, in conjunction with specifying different log levels per sink (#79), since color codes make sense on the console, but not so much in a file.

**Comment by gabime** [comment]
Colored console could be implemented as a sink class  Should be pretty easy i think

**Comment by mrzv** [comment]
But the sink doesn't know the log level of the message, does it? That's the whole point: I want to highlight warning and critical (maybe with different colors), but not debug or trace.

**Comment by mrzv** [comment]
Oh, I see. `details::log_msg` does store the level. Ok, problem solved. Thanks.

**Comment by gabime** [comment]
If you will develop something colofeul I would appreciate a pull :)

**Comment by petke** [comment]
Did something colorful happen?

**Comment by gabime** [comment]
nope

**Comment by aaost** [comment]
In case anyone is still interested, I got this working in Linux by modifying ostream_sink.h (you could also create a custom sink). I took the idea from g3log. It's not super-clean and it's not cross-platform, but it works for me.

```
protected:
    // Linux xterm color
    // http://stackoverflow.com/questions/2616906/how-do-i-output-coloured-text-to-a-linux-terminal
    enum FG_Color {YELLOW = 33,
                   RED    = 31,
                   GREEN  = 32,
                   BLUE   = 34,
                   WHITE  = 97};

    FG_Color GetColor(const level::level_enum l) const
    {
      if (l == level::level_enum::warn) { return YELLOW; }
      if (l == level::level_enum::debug) { return GREEN; }
      if (l == level::level_enum::critical) { return RED; }
      return WHITE;
    }

    void _sink_it(const details::log_msg& msg) override
    {
      auto color = GetColor(msg.level);
      _ostream << "\033[" << color << "m";
      _ostream.write(msg.formatted.data(), msg.formatted.size());
      _ostream << "\033[m";

      if (_force_flush)
        _ostream.flush();
    }
```

Windows would require #ifdefs and something like this:
```
#include <windows.h>
    enum Colors {
      Black = 0,
      Blue = 1,
      Green = 2,
      Red = 4,
      Yellow = 6,
      White = 7
      //0 = Black	8 = Gray
      //1 = Blue	9 = Light Blue
      //2 = Green a = Light Green
      //3 = Aqua	b = Light Aqua
      //4 = Red	c = Light Red
      //5 = Purple	d = Light Purple
      //6 = Yellow	e = Light Yellow
      //7 = White	f = Bright White
    };
HANDLE consoleHandle_;
consoleHandle_ = GetStdHandle(STD_OUTPUT_HANDLE);
SetConsoleTextAttribute(consoleHandle_, Red);
_ostream.write(...)
SetConsoleTextAttribute(consoleHandle_, White);
```

**Comment by gabime** [comment]
Yes. this is interesting. I got numerous requests for supporting colors. Please post pull request (or send me by mailo anything you can share)  and I'll take it from there

**Comment by godbyk** [comment]
I wrote an [ANSI-color wrapper sink](https://github.com/OSVR/spdlog/blob/ansi-color-sink-decorator/include/spdlog/sinks/ansicolor_sink.h) for adding color to Linux and OS X output, but haven't had a chance to sort out the equivalent for the native Windows console.

**Comment by godbyk** [comment]
@gabime See PR #191.  Feel free to modify things to your liking.
