### ISSUE TITLE
Add uppercase pointer format option

### ISSUE THREAD

**Issue by miniwa** [gabime/spdlog#1090]
Small feature request.

{:p} gives you the address of a pointer as a lowercase hexadecimal string, would be great if there was one for uppercase hexadecimal as well.

Yes, you can do this with {:X} already but its an extra step.

**Comment by tt4g** [comment]
Message processing of spdlog is performed by fmt (https://github.com/fmtlib/fmt).

I think it is better to propose in the issue of fmt.

**Comment by gabime** [comment]
right. please open in fmt repo
