### ISSUE TITLE
Including filename and line # when using logger object

### ISSUE THREAD

**Issue by 4sfaloth** [gabime/spdlog#1091]
Hi,

first of all thank you for all your hard work and making it available to anyone, it is really amazing!

I am trying to automatically include source filename and line number in my log messages. I've seen that I can do it with the SPDLOG_TRACE etc... macros, but as far as I understand these will always use the default logger. In our project we are creating several different logger objects, and so would really like to use the logger->Trace() etc... methods for this. Is there any way to achieve this?

Thanks in advance

**Comment by tt4g** [comment]
You can use `SPDLOG_LOGGER_TRACE`.

https://github.com/gabime/spdlog/blob/5709cb10d1691bf7779a6500a6930d335cbe4b0a/include/spdlog/spdlog.h#L285-L291

**Comment by 4sfaloth** [comment]
worked like a charm, thanks a lot from your fast response!
I'm sorry if I missed it, but I do think this functionality is not mentioned in the docs

**Comment by kakyoism** [comment]
@tt4g On Windows with Visual Studio 2017, the example code you cited gives me empty names for source, function, and empty line number as well. What am I missing here?

**Comment by kakyoism** [comment]
@tt4g Calling `spdlog::set_level(spdlog::level::debug);` before the sample code will disable the display. Is this normal?
