### ISSUE TITLE
Logging filename and line # using wrapper

### ISSUE THREAD

**Issue by 4sfaloth** [gabime/spdlog#1092]
Hi,

I am including filename and code line in my log entries by using %a in the log pattern and SPDLOG_LOGGER_INFO etc... macros in the code. My issue is, I have a wrapper class around spdlog and so all log call are like WrapperClass.log which then internally calls spdlog macro. I though that by using 'inline' keyword in my WrapperClass methods the filename and code line would be respective to the called (instead of always seeing 'WrapperClass.h:xxx'), but that does not seem to the case. Anyone knows how I can achieve this?

Thanks in advance

**Comment by gabime** [comment]
You can pass the source location directly using the ```log(..)`` method. 
For example, to log info message:
```c++
logger->log(spdlog::source_loc{__FILE__, __LINE__, __FUNCTION__}, spdlog::level::info, "Some message {}", 123);
```

**Comment by 4sfaloth** [comment]
ah nice, I'll go with that. Thanks for the quick answer
