### ISSUE TITLE
Share sink, different logging levels

### ISSUE THREAD

**Issue by 4sfaloth** [gabime/spdlog#1093]
Hi,

I have several different logger instances, each writing to a a separate file. Now, I would also like **all** loggers to write (some) messages to std::out as well. If I understood correctly, for this to work I need to create a single console sink instance and use it in all my loggers. But in that case, that sink would have the same logging level for all loggers. 

In short, what I am trying to achieve is:
- have N loggers, each writing to a separate file
- all N loggers writing to console
- each logger should have a separate log level for the file and the console sink

Thanks in advance

**Comment by tt4g** [comment]
You can set an individual log level for each logger with `logger::set_level()`.

Note that calling `spdlog::set_level()` will change the level of all registered loggers.

example code:

```cpp
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_sinks.h>

#include <memory>
#include <vector>

int main()
{
    auto console = std::make_shared<spdlog::sinks::stdout_sink_mt>();
    auto file_1 = std::make_shared<spdlog::sinks::basic_file_sink_mt>("file_1.txt");
    auto file_2 = std::make_shared<spdlog::sinks::basic_file_sink_mt>("file_2.txt");

    std::vector<spdlog::sink_ptr> sinks_1;
    sinks_1.push_back(console);
    sinks_1.push_back(file_1);
    auto logger_1 = std::make_shared<spdlog::logger>("logger_1", sinks_1.begin(), sinks_1.end());

    std::vector<spdlog::sink_ptr> sinks_2;
    sinks_2.push_back(console);
    sinks_2.push_back(file_2);
    auto logger_2 = std::make_shared<spdlog::logger>("logger_2", sinks_2.begin(), sinks_2.end());

    // Register globally, operations such as `spdlog::shutdown()`,
    // `spdlog::set_level()`, etc... will be propagated.
    // It's unnecessary if you don't need it.
    spdlog::register_logger(logger_1);
    spdlog::register_logger(logger_2);

    logger_1->set_level(spdlog::level::info);
    logger_2->set_level(spdlog::level::warn);

    // Output console ans file_1.txt
    logger_1->info("Hello! logger_1");
     // Suppress output.
    logger_2->info("Hello! logger_2");

    // Change log level of logger_1 and logger_2.
    spdlog::set_level(spdlog::level::debug);

    // Both logs are output.
    logger_1->debug("debug level logger_1");
    logger_2->debug("debug level logger_2");

    // Shutdown all registered loggers.
    spdlog::shutdown();

    return 0;
}
```

**Comment by 4sfaloth** [comment]
thanks for another fast response @tt4g 
I am aware of the logger::set_level method, but that will set both sinks on that logger to the same level, correct? I was hoping to have different levels per logger per sink. For instance consider this (absurd I know) example:

Logger1: outputing to console at info level and to file at debug level
Logger2: outputing to console at warn level and to file at error level

**Comment by gabime** [comment]
Each sink can get its own log level too. 

```c++
sink->set_level(...);
```

**Comment by tt4g** [comment]
I'm sorry. I did not read correctly about the sink log level.

Sink also has `sink::set_level()`.

**Comment by 4sfaloth** [comment]
> Each sink can get its own log level too.
> 
> ```c++
> sink->set_level(...);
> ```

I'm sorry if I'm missing something. I realize the sinks can have their level too, but both loggers are sharing the console sink (I believe I cannot have two different console sinks?). 
So if I change the console sink log level, won't it change for both loggers?

**Comment by gabime** [comment]
> I believe I cannot have two different console sinks?

of course you can.

**Comment by 4sfaloth** [comment]
> > I believe I cannot have two different console sinks?
> 
> of course you can.

hum... my bad then. I thought I'd seen in another thread that you could not have two different sinks writing to same destination, and that you had to share a single sink through the different loggers in that case. 
That should do it then, thanks
