### ISSUE TITLE
Variadic params not work with set_pattern

### ISSUE THREAD

**Issue by aj3423** [gabime/spdlog#1094]
I tried to modify the pattern:

	log->set_pattern("[%H:%M:%S] [%l] %v");
	log->error("err %d", 123);

I expected it to log something like:

    [01:02:03] [error] err 123

But actually it logs:
    
    [01:02:03] [error] err %d

How to modify the pattern to make the variadic parameters work ?
Thanks.

**Comment by gabime** [comment]
use {}
