### ISSUE TITLE
Could not make it work,

### ISSUE THREAD

**Issue by diwakar09** [gabime/spdlog#1096]
```c++
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#define SPDLOG_DEBUG_ON
#define SPDLOG_TRACE_ON
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"

int main()
{
      		auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
		console_sink->set_level(spdlog::level::trace);
		console_sink->set_pattern("[%Y-%m-%d %H:%M:%S:%e] - [%n] - [%^%l%$] - [thread %t]- [source %s] [function %!] [line %#] %v");
		

		auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("logs/multisink.txt", true);
		file_sink->set_level(spdlog::level::trace);
		file_sink->set_pattern("[%Y-%m-%d %H:%M:%S:%e] - [%n] - [%^%l%$] - [thread %t]- [source %s] [function %!] [line %#] %v");

		spdlog::logger logger("multi_sink", { console_sink, file_sink });

		
		spdlog::set_default_logger(spdlog::get("multi_sink"));
		spdlog::register_logger(spdlog::get("multi_sink"));

		std::shared_ptr<spdlog::logger> log = spdlog::get("multi_sink");

		

		log->warn("Some Warning");
		log->info("Some Info Message");
		log->trace("Trace Log");
		SPDLOG_TRACE("Using Macro", 1);
		SPDLOG_LOGGER_TRACE(log, "Using Macro with logger", 1);
}
```

Experts, Please have a look, I need to log on stdout as well as on file with line number and file name,

**Comment by tt4g** [comment]
Are you unable to output the log and the program crashes at runtime? In that case, please check and correct the following contents.

1. Create a logger with `std::make_shared` and pass it to `spdlog::register_logger()`.

    Only loggers created with `spdlog::create()` or passed to `spdlog::register_logger()` can be obtained with `spdlog::get()`.


2. `spdlog::sinks::basic_file_sink_mt` will generate an error if there is a nonexistent directory in the middle path.

    see #423 

3. Need to invoke `spdlog::shutdown()` before the application exit.

snippet:

```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#define SPDLOG_DEBUG_ON
#define SPDLOG_TRACE_ON

#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"

#include <memory>
#include <vector>

int main()
{
    auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    console_sink->set_level(spdlog::level::trace);
    console_sink->set_pattern("[%Y-%m-%d %H:%M:%S:%e] - [%n] - [%^%l%$] - [thread %t]- [source %s] [function %!] [line %#] %v");

    /* Abort: directory logs is not exist. */
    // auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("logs/multisink.txt", true);
    auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("multisink.txt", true);
    file_sink->set_level(spdlog::level::trace);
    file_sink->set_pattern("[%Y-%m-%d %H:%M:%S:%e] - [%n] - [%^%l%$] - [thread %t]- [source %s] [function %!] [line %#] %v");

    std::vector<spdlog::sink_ptr> sinks({ console_sink, file_sink });
    auto logger = std::make_shared<spdlog::logger>("multi_sink", sinks.begin(), sinks.end());

    /* Register a logger named "multi_sink" in spdlog globally. */
    spdlog::register_logger(logger);
    spdlog::set_default_logger(spdlog::get("multi_sink"));

    logger->warn("Some Warning");
    logger->info("Some Info Message");
    logger->trace("Trace Log");
    SPDLOG_TRACE("Using Macro");
    SPDLOG_LOGGER_TRACE(spdlog::get("multi_sink"), "Using Macro with logger");

    spdlog::shutdown();

    return 0;
}

```

**Comment by diwakar09** [comment]
Thanks It worked,
However, multisink.txt doesnot append, looks like for every run it creates new file.
Is there a way to append to the existing log?

**Comment by tt4g** [comment]
Change the second argument of the `basic_file_synk_mt` constructor to` false`.

This variable is a `truncate` variable, clear the contents of the log file each time if set `true`.

```diff
- auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("multisink.txt", true);
+ auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("multisink.txt", false);
```

**Comment by diwakar09** [comment]
Thanks,
However I ran into other issue,
`
auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
console_sink->set_level(spdlog::level::trace);
console_sink->set_pattern("[%Y-%m-%d %H:%M:%S:%e] - [%n] - [%^%l%$] - [thread %t]- %v");


auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(log_file, false);
file_sink->set_level(spdlog::level::trace);
file_sink->set_pattern("[%Y-%m-%d %H:%M:%S:%e] - [%n] - [%^%l%$] - [thread %t]- %v");

std::vector<spdlog::sink_ptr> sinks({ console_sink, file_sink });
auto logger = std::make_shared<spdlog::logger>("multi_sink", sinks.begin(), sinks.end());

/* Register a logger named "multi_sink" in spdlog globally. */
spdlog::register_logger(logger);
spdlog::set_default_logger(spdlog::get("multi_sink"));


auto trace_logger = spdlog::get("multi_sink")->clone("trace_logger");
trace_logger->set_pattern("[%Y-%m-%d %H:%M:%S:%e] - [%n] - [%^%l%$] - [thread %t]- [source %s] [function %!] [line %#] %v");

spdlog::register_logger(trace_logger);


logger->warn("Some Warning");
logger->info("Some Info Message");
logger->trace("Trace Log");

SPDLOG_TRACE("Using Macro");
SPDLOG_LOGGER_TRACE(trace_logger, "Using Macro with logger");
SPDLOG_DEBUG("Using Macro Debug");
logger->info("Info log);
`
I am trying to set different pattern for logger and trace_logger,
But I think the last one overrides all of them.
Any suggestions?

**Comment by tt4g** [comment]
`logger::set_pattern()` is a shortcut function of `logger::set_formatter()`.

As described in the source documentation, the format is a property of the sink, and `logger::set_formatter()` changes the format of all sinks configured in the logger.

https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/logger.h#L144-L147

Since `logger::clone()` shares the same sink, changing the format of `trace_logger` also changes `logger`.

Therefore, you can not specify an individual log format for each logger.

**Comment by diwakar09** [comment]
Thanks,
