### ISSUE TITLE
Question: container sink

### ISSUE THREAD

**Issue by leonsal** [gabime/spdlog#1097]
Hi,

In my application, threads generates logs (low frequency) that should be shown in a window
in a GUI. So I think I need to to log to a container like std::vector<string> or std::list<string>.
The main program will periodically access the container, remove the logs and show them in a window. What should be the best approach to develop such a sink ? Derive from sink.h or
base_sink.h ? In the factory function should I pass the container and a mutex ?
I am using the static lib version of spdlog.
Any hints will be appreciated. Thanks.

**Comment by gabime** [comment]
If you use async logger, you will get most of the functionality already(log to a queue, have worker thread that consumes it and calls your sink).
So what is left is to develop a simple sink to update the gui (should not even be mutex protected if using the  default thread pool of 1 thread).

**Comment by leonsal** [comment]
Thanks. I would look into that, but as my application is OpenGL based it already has
a main loop which runs at 60 fps to update the UI, so it would not be a problem to access the container
periodically in the loop and without creating a new threads.

**Comment by gabime** [comment]
ok . sounds good.
