### ISSUE TITLE
Compiler errors on HEAD on OSX High Sierra

### ISSUE THREAD

**Issue by terrisgit** [gabime/spdlog#1098]
I guess this is a fmt issue. I am building with gcc and -std=c++11

```
In file included from /usr/include/wchar.h:91:
In file included from spdlog/include/spdlog/fmt/bundled/time.h:13:
In file included from spdlog/include/spdlog/fmt/bundled/format.h:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:756:27: error: unknown type name 'char_traits'
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
```

**Comment by gabime** [comment]
yes. please report in the fmt repo

**Comment by terrisgit** [comment]
Do you recall which release of fmt you included? Was it from HEAD or from an official release?

**Comment by gabime** [comment]
official release 5.3

**Comment by terrisgit** [comment]
I tried using that version of fmt ("https://github.com/fmtlib/fmt/archive/5.3.0.tar.gz") with 1.3.1 of spdlog and got all kinds of errors on ubuntu and osx. Perhaps you ran it through configure/cmake. I tried this because the HEAD version of fmt is even worse and its API changed, breaking spdlog 1.3.1 and HEAD. Just a heads up.
