### ISSUE TITLE
the class or struct pointer compile failed.

### ISSUE THREAD

**Issue by taniey** [gabime/spdlog#1101]
for example, the compile will failed.

#include <spdlog/logger.h>
#include <spdlog/sinks/basic_file_sink.h>

class MyTest{};

int main()
{
spdlog::set_level(spdlog::level::trace); // Set global log level to debug
auto file_logger = spdlog::basic_logger_mt("basic_file_logger", "~/test.log");
spdlog::set_default_logger(rotating_logger);

MyTest *onlyfortest_log_error = new MyTest ();
spdlog::debug("{0}", onlyfortest_log_error);

delete onlyfortest_log_error ;
return 0;
}

**Comment by gabime** [comment]
do you try to print address pointer or a struct?

**Comment by taniey** [comment]
yes,cast to void* while sucess. but why user need care for  the type of the pointer.

**Comment by gabime** [comment]
thats the way it is.
