### ISSUE TITLE
 In Version 1.3.1 Create an asynchronous logger and change thread pool settings 

### ISSUE THREAD

**Issue by huluBrother** [gabime/spdlog#1102]
```
#include "spdlog/async.h" //support for async logging.
#include "spdlog/sinks/basic_file_sink.h"

int main(int, char* [])
{
    try
    {        
        auto async_file = spdlog::basic_logger_mt<spdlog::async_factory>("async_file_logger", "logs/async_log.txt");
       for (int i = 1; i < 101; ++i)
      {
         async_file->info("Async message #{}", i);
      }
       // Under VisualStudio, this must be called before main finishes to workaround a known VS issue
        spdlog::drop_all(); 
    }
    catch (const spdlog::spdlog_ex& ex)
    {
        std::cout << "Log initialization failed: " << ex.what() << std::endl;
    }
}
```
When I was watching the tutorial on the wiki，I use the code above，It prompts the following error `The namespace spdlog::sinks has no member daily_file_sink_mt`  
I have copied the full `include` directory
why?

**Comment by zhanghxsmzycc** [comment]
I already know the reason, the header file reference error on the wiki file, you should use #include "spdlog/sinks/daily_file_sink.h"

**Comment by huluBrother** [comment]
I already know the reason, the header file reference error on the wiki file, you should use #include "spdlog/sinks/daily_file_sink.h"
