### ISSUE TITLE
Help : spdlog API

### ISSUE THREAD

**Issue by huluBrother** [gabime/spdlog#1103]
Does the `spdlog` project have an API for function descriptions? Where can I find it? I tried to find it through google, but I got nothing.

**Comment by gabime** [comment]
I m not sure what do you mean?

**Comment by zhanghxsmzycc** [comment]
![image](https://user-images.githubusercontent.com/42665235/59891083-564b4980-9406-11e9-80d7-23062e90f32f.png)

I would like to ask if there is an API description similar to the one above.

**Comment by gabime** [comment]
No. No such thing.
