### ISSUE TITLE
gcc 4.8.2  compilation error

### ISSUE THREAD

**Issue by ashishmittal85** [gabime/spdlog#1110]
I cloned the repo and tried to build it without any changes for Linux. This is the error I see:

Scanning dependencies of target spdlog
[ 16%] Building CXX object CMakeFiles/spdlog.dir/src/spdlog.cpp.o
In file included from /palscratch/ash.mittal/spdlog-1.x/include/spdlog/sinks/basic_file_sink-inl.h:7:0,
                 from /palscratch/ash.mittal/spdlog-1.x/src/spdlog.cpp:28:
/palscratch/ash.mittal/spdlog-1.x/include/spdlog/sinks/basic_file_sink.h: In instantiation of ‘class spdlog::sinks::basic_file_sink<std::mutex>’:
/palscratch/ash.mittal/spdlog-1.x/src/spdlog.cpp:29:31:   required from here
/palscratch/ash.mittal/spdlog-1.x/include/spdlog/sinks/basic_file_sink.h:20:7: error: looser throw specifier for ‘virtual spdlog::sinks::basic_file_sink<std::mutex>::~basic_file_sink()’
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/spdlog.dir/src/spdlog.cpp.o] Error 1
make[1]: *** [CMakeFiles/spdlog.dir/all] Error 2
make: *** [all] Error 2

My compiler is: linux/x64/gcc/4.8.2/bin/g++
and CMake version is 3.15

I tried to add a destructor with "throw()" but then I see similar errors for other classes.

**Comment by gabime** [comment]
Try a newer compiler maybe. Never saw thus one..

**Comment by Ensteinjun** [comment]
I have encountered the same issue. I found that fmt requires c++ 14, so when I try to compile with -std = c++14, the issue disappears.
