### ISSUE TITLE
log into a file with color

### ISSUE THREAD

**Issue by SnowfallDan** [gabime/spdlog#1111]
hello，
I use spdlog to log my server.here is my code:
`auto file_sink = std::make_shared<spdlog::sinks::daily_file_sink_st>(log_file_path, 0, 1);`
`file_sink->set_pattern("%^[%Y-%m-%d %H:%M:%S %f][Thread: %t] %v %$");`
`logger_ = std::make_shared<spdlog::logger>("both", begin(sink_list), end(sink_list));
    spdlog::register_logger(logger_);`
`logger_->set_pattern("%^[%Y-%m-%d %H:%M:%S %f][Thread: %t] %v %$");`

i log to the file which path is the input parm `log_file_path`. 
how i can make this file with color when i use `vim` open it.
bad english, sorry
Thx!

**Comment by tt4g** [comment]
Do you want to colorize log files when opened with `vim`?
If so, that is the job of `vim`.

You can change the color scheme with `:colorscheme` or add vim plugins to make the log easier to read.

**Comment by SnowfallDan** [comment]
> Do you want to colorize log files when opened with `vim`?
> If so, that is the job of `vim`.
> 
> You can change the color scheme with `:colorscheme` or add vim plugins to make the log easier to read.

Thx for reply.
u mean the file is already colorized with the code i write above? i need to find a vim plugin to make the file colorful?
Thx

**Comment by tt4g** [comment]
> u mean the file is already colorized with the code i write above?

No, color is not included because `spdlog::sinks::daily_file_sink_st` writes to files as plain text.

> i need to find a vim plugin to make the file colorful?

Yes, if you want to color the content written by `spdlog::sinks::daily_file_sink_st`.

`vim` can do syntax highlighting by adding a plugin.
For example, https://github.com/andreshazard/vim-logreview is a plugin that color-displays the characters `DEBUG`, `INFO`, `WARN`, etc.

**Comment by SnowfallDan** [comment]
> > u mean the file is already colorized with the code i write above?
> 
> No, color is not included because `spdlog::sinks::daily_file_sink_st` writes to files as plain text.
> 
> > i need to find a vim plugin to make the file colorful?
> 
> Yes, if you want to color the content written by `spdlog::sinks::daily_file_sink_st`.
> 
> `vim` can do syntax highlighting by adding a plugin.
> For example, https://github.com/andreshazard/vim-logreview is a plugin that color-displays the characters `DEBUG`, `INFO`, `WARN`, etc.

Thx for reply! very useful!
