### ISSUE TITLE
spdlog::set_async_mode removed?

### ISSUE THREAD

**Issue by life-engineer** [gabime/spdlog#1113]
Hi,

I noticed that spdlog::set_async_mode has been recently removed. We are relying on this method to modify the thread priority and set the pthreads thread name, and in the latest version we can no longer accomplish this. Is there a specific reason why this functionality has been removed?

**Comment by gabime** [comment]
It was removed few months ago in version 1.x

How do you rely on it for thread name ? Can you give an example?

**Comment by life-engineer** [comment]
> It was removed few months ago in version 1.x
> 
> How do you rely on it for thread name ? Can you give an example?

For example I can pass in a lambda to spdlog::set_async_mode:

[]() {

// set thread affinity using internal api

// set thread affinity using internal api
}

The internal api gets the current thread id, and applies the attributes to it. In the old version, the lambda gets called before the main loop of the thread which works find for us.

**Comment by gabime** [comment]
I never knew anyone actually used this feature..
It can be added to the new API if important.

**Comment by life-engineer** [comment]
Yes please. That would be most convenient for us. A 'startup callback' that allows the caller to modify the thread properties as they like before the main thread is what we are really after. Many thanks in advance.

**Comment by gabime** [comment]
Implemented.  One can now pass a callback function to the thread pool constructor or to the "init_thread_pool" function.

**Comment by batilak** [comment]
I did "git clone" today and it is not finding it :

`error:` ‘set_async_mode’ is not a member of ‘spdlog’
