### ISSUE TITLE
wide char support on Windows

### ISSUE THREAD

**Issue by mfouad** [gabime/spdlog#112]
I get this error whenever I pass a wide character array `wchar_t*` or a `wstring` 
it seems to be treating these pointers as user defined types

``` cpp
error C2248: 'fmt::internal::MakeValue<Char>::MakeValue' : cannot access private member declared in class 'fmt::internal::MakeValue<Char>'	
.\spdlog\include\spdlog\details\format.h	1771	1	
```

I beleive cppFormat supports widechar. Is there a way around this in spdlog?

**Comment by vitaut** [comment]
Just to clarify that this error is generated when trying to format a wide string into a narrow string which is explicitly forbidden as in:

```
  fmt::format("{}", L"test"); // forbidden
  fmt::format(L"{}", L"test"); // allowed
```

**Comment by Kentzo** [comment]
This issue is indirectly related to https://github.com/gabime/spdlog/pull/111 which is probably part of making spdlog to support unicode on Windows.
