### ISSUE TITLE
windwos platform doesn't work with release version

### ISSUE THREAD

**Issue by Curchan** [gabime/spdlog#1123]
it only output log with debug environment, and release environment just create file but doesn't write text.

here is my code
------------------Init
logdir.append("/").append(filename).append("_daily.txt");

		loggerPtr = spdlog::get(filename);
		if ( !loggerPtr ) {

			#ifdef _CONSOLE
			loggercontainer.push_back(std::make_shared<spdlog::sinks::stderr_color_sink_mt>());
			#endif
			loggercontainer.push_back(std::make_shared<spdlog::sinks::daily_file_sink_mt>(logdir.c_str(), 23, 59));

			loggername = filename;
			loggerPtr = std::make_shared<spdlog::logger>(filename, std::begin(loggercontainer), std::end(loggercontainer));
			spdlog::register_logger(loggerPtr);
		}

		spdlog::set_pattern("%^[%H:%M:%S:%e][%l] %v%$");

		spdlog::set_level(spdlog::level::trace);

		spdlog::flush_on(spdlog::level::warn);
--------------------output

template <typename... Args>
void CLog::WriteLog(spdlog::level::level_enum lev, const char * fmt, Args... ag)
{
	char *pszStr = nullptr;
	if ( nullptr != fmt ) {

		if ( loggerPtr ) {
			switch ( lev ) {
				case spdlog::level::trace:
					loggerPtr->trace(fmt, ag...);
					break;
				case spdlog::level::debug:
					loggerPtr->debug(fmt, ag...);
					break;
				case spdlog::level::info:
					loggerPtr->info(fmt, ag...);
					break;
				case spdlog::level::warn:
					loggerPtr->warn(fmt, ag...);
					break;
				case spdlog::level::err:
					loggerPtr->error(fmt, ag...);
					break;
				default:
					break;
			}
		}

	}
}

**Comment by tt4g** [comment]
More source code samples are needed to identify the cause.

If it is a Debug build, is the log output to a file?

By the way, the sample does not seem to call `spdlog::shutdown()`,
If you do not call it before the application exits, log data may remain in the buffer.

**Comment by Curchan** [comment]
> More source code samples are needed to identify the cause.
> 
> If it is a Debug build, is the log output to a file?
> 
> By the way, the sample does not seem to call `spdlog::shutdown()`,
> If you do not call it before the application exits, log data may remain in the buffer.

thanks
it is output to a file when debug build, but release build doesn't.
i will try calling std::log::shutdown() in sample to observing it.
