### ISSUE TITLE
rotating_file_sink: failed renaming and Permission Denied when running the multiple executable instances of project

### ISSUE THREAD

**Issue by vaibhav0210** [gabime/spdlog#1124]
Hello!
I run the 2 instances of my project and both executable instance trying to log into the same file and both have their separate loggers but when the maximum limit of a file is reached and trying to rename the file both executable instance gives me error as- 

Error by exe1-
[*** LOG ERROR ***] [2019-06-29 11:38:48] [file_logger1] rotating_file_sink: failed renaming G:\TempLogs\mylogs.txt to G:\TempLogs\mylogs.1.txt: Permission denied

Error by exe2-
[*** LOG ERROR ***] [2019-06-29 11:38:48] [file_logger2] rotating_file_sink: failed renaming G:\TempLogs\mylogs.txt to G:\TempLogs\mylogs.1.txt: Permission denied

I created the logger by -

auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("mylogs.txt", 1024* 100, 10);
spdlog::logger mylog(argv[1], file_sink);

Here name of the logger is passed as the command line argument. Also the file sink is shared.

**Comment by gabime** [comment]
There is no support for multi process logging to same file, so it is expected.
