### ISSUE TITLE
Native wide character support

### ISSUE THREAD

**Issue by sylveon** [gabime/spdlog#1125]
Currently, output of wide character strings in Windows is done by converting them to UTF-8 internally using WideCharToMultiByte. This behavior is undesirable because:
 - It cripples performance, due to having to call the API twice.
 - It doesn't handles all characters correctly. In my use-case, I sometimes end up logging strings with particular characters like U+202D (left to right override). WideCharToMultiByte converts this character to some junk: 
![image](https://user-images.githubusercontent.com/6440374/60391928-bd809200-9ac7-11e9-9622-88b0e166a334.png)
Emojis are also obliterated:
![image](https://user-images.githubusercontent.com/6440374/60391975-6929e200-9ac8-11e9-9849-ac9b3e48c7d9.png)
- Memory usage while logging is increased threefold due to having to hold a char and wchar_t version of the string at the same time.

My app does not uses normal characters at all, everything is wide characters.

There should be a way so that spdlog supports wchar_t, inside and out, without ever having to convert between encodings because it is fragile. I can provide my own sinks if required.

**Comment by gabime** [comment]
which version are you using? last time i checked the  wchar_t converting performance was not  bad.
> There should be a way so that spdlog supports wchar_t, inside and out,

It is doable, but there is no easy way without re writing big portion of spdlog.

**Comment by sylveon** [comment]
I'm using 1.3.1

```cpp
#define SPDLOG_NO_THREAD_ID

#include <spdlog/spdlog.h>
#include <spdlog/sinks/null_sink.h>

#include <chrono>
#include <iostream>

void test(std::shared_ptr<spdlog::logger> logger)
{
	const auto begin = std::chrono::steady_clock::now();

	for (size_t i = 0; i < 1000000; i++)
	{
		logger->info("Hello world");
	}

	const auto end = std::chrono::steady_clock::now();

	std::cout << std::chrono::duration_cast<std::chrono::nanoseconds>(end - begin).count() << std::endl;
}
```

The following code (when giving it a null logger to avoid I/O overhead) took 8098311 nanoseconds over an average of 9 runs. The same code, when using wide characters instead, takes 10071744 nanoseconds. That's a 24% performance hit.

**Comment by gabime** [comment]
Maybe an easy improvement would be to avoid the double call to WideCharToMultiByte.

**Comment by gabime** [comment]
for example i guess the max size is already known (the length of the inout string * 2 or 3?)

**Comment by sylveon** [comment]
That's a possible optimization, but doesn't resolves bad conversions unfortunately.

**Comment by gabime** [comment]
Are we sure Microsoft’s WideCharToMultiByte has such severe issues? Worth double checking..

**Comment by sylveon** [comment]
What I've shown earlier is output directly from WideCharToMultiByte.

![image](https://user-images.githubusercontent.com/6440374/60402055-fbc59200-9b57-11e9-8635-53c69608c00c.png)

**Comment by gabime** [comment]
isnt t just the debugger display that is broken? have you checked that the actual value in not the expected utf?

**Comment by sylveon** [comment]
Actually, you are correct and the value is in the expected UTF. Should have taken more attention, my mistake.

**Comment by gabime** [comment]
NP. Anyway there is room for optimizing the double call to WideCharToMultiByte

**Comment by sylveon** [comment]
Possibly, but then this can result into excessive allocation.
Microsoft [recommends](https://docs.microsoft.com/en-us/windows/desktop/Intl/using-functions-that-have-no-unicode-equivalents) `2 * (wstr.size() + 1)` but you may end up using only half of that.

**Comment by gabime** [comment]
spdlog use stack buffer of size 500 bytes anyway. So as long as wstr.size()  is less than 250 , no allocations will be made. 
Only If it is bigger, it would need to allocate. 

So a possible  approach is 

```c++

auto wbuf_size = static_cast<int>(wbuf.size());
int required_out_size;
if(wbuf_size >= 249)
{
   required_out_size = ::WideCharToMultiByte(CP_UTF8, 0, wbuf.data(), wbuf_size, NULL, 0, NULL, NULL);
   target.resize(result_size);
}
else 
{
    required_out_size = 500
}


 ::WideCharToMultiByte(CP_UTF8, 0, wbuf.data(), wbuf_size, &target.data()[0], required_out_size, NULL, NULL);

```

**Comment by XMuli** [comment]
> ```c++
> #define SPDLOG_NO_THREAD_ID
> 
> #include <spdlog/spdlog.h>
> #include <spdlog/sinks/null_sink.h>
> ```

SPDLOG_NO_THREAD_ID needs to be defined before the header file, this helped me, thanks!
