### ISSUE TITLE
add support for pattern_time_type in sink set_pattern

### ISSUE THREAD

**Issue by karoberts** [gabime/spdlog#1132]
#215 added support for UTC timestamps in patterns
#421 added support for patterns at the sink level

however, you cannot pass a pattern_time_type to a sink set_pattern

e.g.

logger has this
 `void set_pattern(std::string pattern, pattern_time_type time_type = pattern_time_type::local);`

but sink only has
`virtual void set_pattern(const std::string &pattern)`

I have 1 logger logging to 2 sinks, each with a different pattern, and I cannot enable utc logging for those sinks.

**Comment by gabime** [comment]
An easy workaround is to use the set_formatter instead:

```c++
auto f=std::make_unique<spdlog::pattern_formatter>(pattern, pattern_time_type::utc);
sink->set->formatter(std::move(f));
```

**Comment by karoberts** [comment]
Thanks, that works nicely.  I think for API consistency it would be nice to have the overload available on the sink, but this works for me.

**Comment by gabime** [comment]
Agreed. However, I try to keep the sink interface as minimal as possible.
