### ISSUE TITLE
error C2039: 'error': is not a member of 'spdlog'

### ISSUE THREAD

**Issue by Omegastick** [gabime/spdlog#1135]
When compiling with MSVC VS2017 (build system created with CMake) I get the following errors:

```
C:\Users\Omega\prog\bots\src\graphics\window.cpp(88): error C3861: 'error': identifier not found
C:\Users\Omega\prog\bots\src\graphics\window.cpp(91): error C2039: 'warn': is not a member of 'spdlog'
  c:\users\omega\prog\bots\lib\spdlog\include\spdlog\details\../sinks/wincolor_sink.h(17): note: see declaration of 'spdlog'
C:\Users\Omega\prog\bots\src\graphics\window.cpp(91): error C3861: 'warn': identifier not found
C:\Users\Omega\prog\bots\src\graphics\window.cpp(94): error C2039: 'info': is not a member of 'spdlog'
  c:\users\omega\prog\bots\lib\spdlog\include\spdlog\details\../sinks/wincolor_sink.h(17): note: see declaration of 'spdlog'
C:\Users\Omega\prog\bots\src\graphics\window.cpp(94): error C3861: 'info': identifier not found
C:\Users\Omega\prog\bots\src\graphics\window.cpp(101): error C2039: 'debug': is not a member of 'spdlog'
```
The above repeats ad nauseum for every call to spdlog's logging functions in the library.

This only occurs on MSVC on Windows, not on G++ on Ubuntu.

Seems to be related to #1014, but you didn't say how you fixed the problem in the end so I'm not sure what to do.

**Comment by tt4g** [comment]
What is the version?

If spdlog 1.3.1, it may be because you did not include "spdlog/spdlog.h" first: https://github.com/gabime/spdlog/issues/1014#issuecomment-480444135

Please refer to the following code. It is a sample code written in anticipation of using `spdlog::stdout_color_mt()` from the error message you wrote:

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"

#include <memory>

int main(int, char**) {

    std::shared_ptr<spdlog::logger> stdout_logger = spdlog::stdout_color_mt("stdout");
    spdlog::set_default_logger(stdout_logger);

    spdlog::info("Hello, World!");

    spdlog::shutdown();

    return 0;
}
```

If you need further assistance, you will need to provide the spdlog version and source code that reproduces the problem.

**Comment by Omegastick** [comment]
@tt4g Ah, I was on the master branch, not the `v1.x` branch. Thanks.

**Comment by gabime** [comment]
It have been fixed few commits ago.  Please try latest code from trunk
