### ISSUE TITLE
Async logger scaling with number of threads

### ISSUE THREAD

**Issue by nickaleks** [gabime/spdlog#1137]
While benchmarking the logger, I've noticed that the performance does not improve as the thread pool size is increased. For the overrun policy performace stays more or less flat, while blocking policy shows significant performance degradation when the thread pool size is increased beyond 1 thread.

As I understand this happens due to the design, where both the queue and the sink is protected by the mutex, so number of threads does not matter, since their operations get serialized anyway. The only exception is the formatting of the message, which is done in parallel, but it is hardly the heaviest part of the logging.

Below are the results of the async_bench for the different number of threads. Other configuration properties are kept as in the readme. Blocking benchmarks are a bit jittery, which may be caused by OS scheduling playing a big role, however the performance decrease when jumping from 1 to 2 threads is consistently replicated for me.

![image](https://user-images.githubusercontent.com/14168731/60757940-ad156d80-a019-11e9-93da-2e909153ee45.png)
![image](https://user-images.githubusercontent.com/14168731/60757945-c4ecf180-a019-11e9-89a3-2d91736bcde5.png)

Am I missing something, or is there really no benefit from using several worker threads with the current logger design?

**Comment by gabime** [comment]
> where both the queue and the sink is protected by the mutex
They not share the same mutex.  There is a separate dedicated mutex protecting pushing/popping to/from the queue.

If there are multiple threads in the pool, all trying to access the same sink instance, then no wonder performance doesn't improve as they all compete for same sink mutex and the work is in effect serialized..

A use case where  more threads would improve performance  would be for example using multiple  sink objects, from different loggers. Other then that I do not see how increasing the amount of tp threads help in anyway.
