### ISSUE TITLE
Parameter name shadow warning (includes patch)

### ISSUE THREAD

**Issue by rpopescu** [gabime/spdlog#114]
Hi Gabi,

I get a warning in details/format.h where in the ctor of NamedArg the parameter "name" shadows member "name".
This happens with:
```
$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
```

Although the warning does not appear with GCC 4.8.3, it is genuine in my opinion, this simple patch fixes it (changes parameter "name" to "argname"):

```
Index: include/spdlog/details/format.h
===================================================================
--- include/spdlog/details/format.h	(revision 754)
+++ include/spdlog/details/format.h	(working copy)
@@ -1127,8 +1127,8 @@
     BasicStringRef<Char> name;
 
     template <typename T>
-    NamedArg(BasicStringRef<Char> name, const T &value)
-        : name(name), Arg(MakeValue<Char>(value)) {
+    NamedArg(BasicStringRef<Char> argname, const T &value)
+        : name(argname), Arg(MakeValue<Char>(value)) {
         type = static_cast<internal::Arg::Type>(MakeValue<Char>::type(value));
     }
 };
```

**Comment by gabime** [comment]
Thanks. Please submit pull request to cppformat(https://github.com/cppformat/cppformat) repository. Format.h and format.cc is part of the cppformat and spdlog just use it.

**Comment by rpopescu** [comment]
Unfortunately that's not as simple as I thought; the code you're using seems a bit older than the current master of cppformat.
Can you update your local copy?

**Comment by rpopescu** [comment]
cppformat pull is https://github.com/cppformat/cppformat/pull/191
