### ISSUE TITLE
complice error

### ISSUE THREAD

**Issue by cangyuegui** [gabime/spdlog#1141]
use only head file
fmt::v5::print

**Comment by gabime** [comment]
Please provide more details

**Comment by cangyuegui** [comment]
use : vs 2013
file: copy head file
when include spdlog/logger.h
it will tell me that:
Overload function calls ambiguous

**Comment by cangyuegui** [comment]
the error function locate at fmt::v5::print

**Comment by tt4g** [comment]
In MSVC 2013, there is a problem with the use of the fmt library, because the compiler does not properly support the C++11 features.

I think it is necessary to find out the problem with fmt and MSVC2013.

Could you provide reproduce snippet and write build error message?
Also, what version of spdlog do you use (master branch)?

**Comment by cangyuegui** [comment]
version is 1.x 
i do not wrote any code.
the file is logger-inl.h
the line is 231
click this function , it will jump to fmt/bundled/core.h line 1477

**Comment by cangyuegui** [comment]
can i be solved ?
or must i give up this library?
:-(

**Comment by cangyuegui** [comment]
also,
if i use the fmt like this print<char*, char*, const std::string, const std::string>(...)
 the error will be same as https://github.com/fmtlib/fmt/issues/987

**Comment by tt4g** [comment]
As long as I read https://github.com/fmtlib/fmt/issues/987#issuecomment-448645027, it seems that fmt is working with MSVC 2013 (Update 5 18.0.40629.0).

Check your MSVC version macro `_MSC_FULL_VER`.
If your MSVC 2013 version is 18.0.40629.0, `_MSC_FULL_VER` is equal to `180040629`.

Another way is to run `cl.ext /?` at the MSVC developr command prompt.

The following is the result of running on my machine (MSVC 2017 Pro):

```bash
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional>cl.exe /?
Microsoft(R) C/C++ Optimizing Compiler Version 19.16.27032.1 for x64 # 19.16.27032.1 is MSVC full version.
Copyright (C) Microsoft Corporation.  All rights reserved.

                         C/C++ COMPILER OPTIONS

...

```

**Comment by cangyuegui** [comment]
i'd tried it
it seems the value is eque to 180021005
because my work pc is 【Intranet net only】.
i think i have to abandon it.
thx!
