### ISSUE TITLE
android compile error!!

### ISSUE THREAD

**Issue by nkari82** [gabime/spdlog#1143]
branch v1.x 
spdlog/sinks/android_sink.h(50,19): error : no member named 'formatter_' in 'spdlog::sinks::sink'

 `
 if (use_raw_msg_)
        {
            details::fmt_helper::append_string_view(msg.payload, formatted);
        }
        else
        {
            sink::formatter_->format(msg, formatted);  <--- base_sink<Mutex>::formatter_ ??
        }
`

**Comment by gabime** [comment]
Fixed. Thanks for reporting

**Comment by lutherling12** [comment]
Applied a similar fix to the Sinks documentation.

**Comment by lutherling12** [comment]
Had to apply a similar fix to the example in the sinks documentation.

**Comment by lutherling12** [comment]
Had to apply a similar fix in the sinks documentation.

```c++
