### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [gabime/spdlog#1144]
Greetings spdlog developers and contributors,

We’re reaching out (again) because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

To help you getting started, we can provide our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://github.com/google/oss-fuzz/blob/master/docs/faq.md ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by gabime** [comment]
> To help you getting started, we can provide our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

Please do. I don't have any spare time for this, but at least lets get started

**Comment by Google-Autofuzz** [comment]
> > To help you getting started, we can provide our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.
> 
> Please do. I don't have any spare time for this, but at least lets get started

Sure, this is our internal fuzz target (log_fuzzer.cc), shown below. It uses a library called [FuzzedDataProvider](https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/fuzzer/utils/FuzzedDataProvider.h) that we wrote. Please take a look and we are happy that you do consider to use [OSS-Fuzz](https://github.com/google/oss-fuzz). 

```
#include <cstddef>

#include "FuzzedDataProvider.h"
#include "spdlog.h"

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
  if (size == 0) {
    return 0;
  }
  FuzzedDataProvider stream(data, size);

  const size_t size_arg = stream.ConsumeIntegral<size_t>();
  const int int_arg = stream.ConsumeIntegral<int>();
  const string string_arg = stream.ConsumeRandomLengthString(size);
  const string format_string = stream.ConsumeRemainingBytesAsString();
  spdlog::info(format_string.c_str(), size_arg, int_arg, string_arg);

  return 0;
}
```

**Comment by Google-Autofuzz** [comment]
Hi,

I am upstreaming spdlog to [OSS-FUZZ](https://github.com/google/oss-fuzz) dynamically to start. We can change it later and add more fuzzers as you like. Can I get a primary contact email address so that the OSS-FUZZ team can contact after finding bugs-related issues? 

Thanks,
Tommy

**Comment by gabime** [comment]
Mail of @gabime

**Comment by Google-Autofuzz** [comment]
spdlog has been upstreamed to OSS-Fuzz with the log_fuzzer fuzzer. You can make changes on [here](https://github.com/google/oss-fuzz/tree/master/projects/spdlog) and I suggest you to add more fuzzers, dictionaries, seed corpuses. We are happy that you are consider to use OSS-Fuzz :) 

If you think this issue can be closed, you can close it.
