### ISSUE TITLE
spdlog::stderr_color_mt on windows breaks when stderr is not console.

### ISSUE THREAD

**Issue by scudette** [gabime/spdlog#1147]
Our application selects `spdlog::stderr_color_mt` which works when the program is run in the windows console but if a user redirects stderr then spdlog loses all messages. I think we still creates the wincolor sink and this calls WriteConsoleA on the (non console) handle. Note also that the wincolor sink ignores the error status of WriteConsole (It probably should repeat the logging with WriteFile) 

This should fallback gracefully to simply writing to the handle as recommended in the MSDN article:

https://docs.microsoft.com/en-us/windows/console/writeconsole

WriteConsole fails if it is used with a standard handle that is redirected to a file. If an application processes multilingual output that can be redirected, determine whether the output handle is a console handle (one method is to call the GetConsoleMode function and check whether it succeeds). If the handle is a console handle, call WriteConsole. If the handle is not a console handle, the output is redirected and you should call WriteFile to perform the I/O.

**Comment by gabime** [comment]
Thanks for reporting. Will be fixed - broken logging if redirected is not good indeed.

**Comment by gabime** [comment]
Fixed in c138685364f8a7124e4b90f4a9bf9b3dd99f3b7a
