### ISSUE TITLE
No Nuget package published since version 1.0.0

### ISSUE THREAD

**Issue by sbacquet** [gabime/spdlog#1149]
Would be good to publish every new version as a Nuget package.
Thanks in advance !

**Comment by gabime** [comment]
Thats not part of spdlog’s scope. Please open this issue to the relevant nuget maintainers

**Comment by sbacquet** [comment]
OK fair enough.
The Nuget maintainer is supposed to be Denis Brachet Barbuse, but I don't know how to reach him.
Any hint please?
