### ISSUE TITLE
Add -fno-exceptions support

### ISSUE THREAD

**Issue by brycearden** [gabime/spdlog#1152]
It seems like the discussion about providing a version of spdlog that does not throw exceptions hasn't surfaced in about [18 months](https://github.com/gabime/spdlog/issues/598), but is the plan to not support `-fno-exceptions` anytime in the near future? I'd really like to use this logging framework in some of my experimental code around tensorflow (which compiles with -fno-exceptions by default.)

**Comment by gabime** [comment]
What would be the "standard" way to replace the ```throw``` in the code ? abort? what does std does ?

**Comment by brycearden** [comment]
The way I see it there are kind of two approaches.

1) follow the steps of fmtlib and create a `SPDLOG_THROW` macro that works similar to this:
https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L69-L93
https://github.com/fmtlib/fmt/blob/master/include/fmt/format-inl.h#L39-L45
https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L82-L90

This would allow `spdlog` to match the current behavior of `fmtlib` (which might be desired because `fmtlib` is a true dependency). However, `fmtlib`'s approach may change in the process of moving format into the stdlib.

2) Support `error_code` modes for environments that do not support exceptions. This appears to be the approach that the stdlib takes in most scenarios and is used all over the place in Google open source code (since the [Google C++ style guide disallows exceptions](https://google.github.io/styleguide/cppguide.html#Exceptions). For example, something similar to [GRPC status codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) where we indicate the failure scenario and except the caller to handle the status code. 

Google currently defines their status codes in their `googleapis` repo using protobuf. Here's the status code definitions for GRPC as an example.

https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto

**Comment by gabime** [comment]
option 2 is overkill and would require too many changes.
The way i see it, it all comes to 2 oprions: 
1. abort() instead of throw
2. Ignore instead of throw and pray

**Comment by brycearden** [comment]
The abort() instead of throw approach would match `fmtlib` since the `FMT_THROW` macro basically just turns all exceptions into `assert(false)` anyways. 
https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L90

**Comment by gabime** [comment]
But what happens in std? For example what std::vector does at oob access or failed alloc?

**Comment by brycearden** [comment]
In std, `std::nothrow` is used as a way to distinguish between `operator new[]` overloads (one that throws the std::bad_alloc exception, and another that returns nullptr.
https://en.cppreference.com/w/cpp/memory/new/nothrow

Its probably worth noting thought that if there is an failed alloc then you are probably out of memory and the program should exit anyways...

**Comment by gabime** [comment]
> My guess is that the stl defaults to the std::nothrow

ok, But then what ? lets suppose std::vector  uses no-throw and gets null ? now what it does?

There are also other exceptions that std might throw.. I just feel un comfortable supporting   fno-exceptions without understanding the implications,,

**Comment by gabime** [comment]
Found this about gcc:

https://arobenko.gitbooks.io/bare_metal_cpp/content/compiler_output/exceptions.html

**Comment by gabime** [comment]
spdlog not supports -fno-exceptions. It will issue std::abort() instead of throwing.

Enable with ```cmake -DSPDLOG_NO_EXCEPTIONS=ON```

or ```#define SDPLOG_NO_EXCEPTIONS``` before building

**Comment by platisd** [comment]
> spdlog not supports -fno-exceptions. It will issue std::abort() instead of throwing.
> 
> Enable with `cmake -DSPDLOG_NO_EXCEPTIONS=ON`
> 
> or `#define SDPLOG_NO_EXCEPTIONS` before building

@gabime When was this introduced? I cannot find any reference to `SDPLOG_NO_EXCEPTIONS` in the latest `master`.

**Comment by gabime** [comment]
It in the v1.x branch. “master” is legacy.

**Comment by platisd** [comment]
Oh right now I found it, thanks!
I was still on `master` and hadn't checked out the `v1.x` branch correctly. :+1:
