### ISSUE TITLE
Safely copy files with logs while working rotating_file_sink.

### ISSUE THREAD

**Issue by Rivand** [gabime/spdlog#1153]
Hello. I started using spdlog to build my embedded system. I read the source code and saw one potential problem for myself in `rotating_file_sink`. I correctly understand that if during the copying of logs (via SSH for example) the `rotating_file_sink <...> :: rotate_ ()` method will be called, trouble will happen (due to the fact that this method renames all files)? I want to say that when the application is running with `rotating_file_sink`, we are not guaranteed to safely read or copy files with logs. I can’t stop the application at the time of uploading logs because it synchronizes a lot of important equipment in real-time.

**Comment by gabime** [comment]
Right. I don't think it is safe to copy them during rotation. 
Maybe consider using different sink like `daily_file_sink`, with predictable renaming times.

**Comment by Rivand** [comment]
`daily_file_sink` doesn't suit me because logs will be downloaded when something is wrong with the equipment (this happens quite often). Perhaps, in rotating_file_sink it is worth adding some rotation control mechanisms (add `pause_logging` / `resume_logging` methods for example)?

**Comment by gabime** [comment]
you can always write a custom sink for your specific needs. It is quite easy.

 Another option would be prevent rotating by passing 0 to the sink ctor’s max_files. This would make it just to truncate the file when it reach  max size.
