### ISSUE TITLE
rotating file on the basis of size only

### ISSUE THREAD

**Issue by smrititripathi027** [gabime/spdlog#1157]
Hi ,

I want to rotate file only on the basis of size, but i don't wanna pass any maximum number of files. Is there any option ?

Thanks in advance.

**Comment by tt4g** [comment]
You can use `spdlog::sinks::rotating_file_sink_mt`:

```cpp
#include <spdlog/spdlog.h>
#include <spdlog/sinks/rotating_file_sink.h>

#include <memory>
#include <string>
#include <vector>

int main(int, char**) {
    // Rotate when file size exceeds 10MB.
    // The rotated file remains for 3 generations (log.txt, log.txt.1, log.txt.2, log.txt.3).
    std::string log_filename = "log.txt";
    std::size_t max_size = 10 * 1024 * 1024;
    std::size_t max_files = 3;
    auto rotate_file_sink =
            std::make_shared<spdlog::sinks::rotating_file_sink_mt>(
                    log_filename, max_size, max_files);

    // Create logger, it use rotate_file_sink.
    std::vector<spdlog::sink_ptr> sinks;
    sinks.emplace_back(std::move(rotate_file_sink));
    auto root_logger =
            std::make_shared<spdlog::logger>(
                    "root_logger", sinks.begin(), sinks.end());

    root_logger->set_level(spdlog::level::info);
    root_logger->flush_on(spdlog::level::info);

    spdlog::register_logger(root_logger);

    root_logger->info("first.");

    // Set default logger.
    spdlog::set_default_logger(root_logger);
    spdlog::warn("second.");

    spdlog::shutdown();

    return 0;
}

```

**Comment by smrititripathi027** [comment]
In this code we are passing max_files = 3, this means code can generate max 3 files.

But I don't want to restrict my code only for n numbers of file generation.

**Comment by smrititripathi027** [comment]
In this code we are passing max_files = 3, this means code can generate max 3 files.

But I don't want to restrict my code only for n numbers of file generation. It should generate any number of files according to need.

**Comment by tt4g** [comment]
You can specify `max_files` up to the maximum value of `std :: size_t`.
It will be quite large in most environments, but still not enough?

**Comment by gabime** [comment]
won’t work - the rotating code will try to rotate max_files files..

**Comment by smrititripathi027** [comment]
You are right @tt4g , but there is one problem like if I am running one software on production , I will not restart this software for so many days or months , that time this max_files will become bottleneck for me.

**Comment by tt4g** [comment]
The easy solution I came up with is to give UUID or date and index (e.g. {filename}.YYYY-MM-DD.{index}) to the file name prefix when rotating.


However, UUID can not determine which file is new from the filename, need to know the last modified date of the file as a way to identify the new file.

Date prefix doesn't have this problem, but it's awkward considering considering crossing dates during rotate.

**Comment by Omernn23** [comment]
I guess it related, 
If I want the largerst filr number for totation, 
What is the maximum size for max_size (the file size)?
and what is the maximum size for max_files (the nuber of files for rotating)?
Is there any limit?
This is the command im using- 
auto rotate_file_sink =std::make_shared<spdlog::sinks::rotating_file_sink_mt>(rotate_filename, max_size, max_files); 
In addition I was looking in the internet and didnt find what is the meaning of the variable - bool rotate_on_open=false?
@gabime @tt4g
