### ISSUE TITLE
[Build] Support for conan packages

### ISSUE THREAD

**Issue by alexandrudsc** [gabime/spdlog#1158]
Hi,
did you guys ever considered adding conan as an official package manager? I know you have a list already and conan has it's own drawbacks. but it got a lot of traction in the last year.
There is already some work done [here](https://github.com/memsharded/conan-spdlog/blob/master/conanfile.py) and [here](https://github.com/bincrafters/conan-spdlog)

Thanks,
and no worries if this request gets rejected :)

**Comment by gabime** [comment]
You mean in the readme? why not.. a PR would be great
