### ISSUE TITLE
rotating_logger_mt does not rotate properly if app restarts

### ISSUE THREAD

**Issue by ephsiung** [gabime/spdlog#116]
I instantiated a rotating_logger_mt with something like this:
auto logger = spdlog::rotating_logger_mt("file_logger", "<path>/log", 2 * 1024 * 1024, 3, true);

If I generate more than 2MB of logger content then the log file rotates fine and I get log.txt and log.1.txt, as expected.

If I generate 1.5MB of logger content, close my app, restart my app, generate 1.5MB of content, the log file never rotates, my log file is now 3MB in size. If I keep this cycle going the log file grows indefinitely.

rotating_file_sink has a _current_size member that is initialized to zero. This needs to take into account the re-open-a-log-file case and determine the correct current size. Something like this:

    rotating_file_sink(const std::string &base_filename, const std::string &extension,
                       std::size_t max_size, std::size_t max_files,
                       bool force_flush = false) :
        _base_filename(base_filename),
        _extension(extension),
        _max_size(max_size),
        _max_files(max_files),
        _current_size(0),
        _file_helper(force_flush)
    {
        _file_helper.open(calc_filename(_base_filename, 0, _extension));
        _current_size = _file_helper.size();
    }

where _file_helper.size() could be something like this:

    size_t size()
    {
        size_t size = 0;
        if (_fd)
        {
            size_t pos = ftell(_fd);
            if (fseek(_fd, 0, SEEK_END) == 0)
                size = ftell(_fd);
            fseek(_fd, pos, SEEK_SET);
        }
        return size;
    }

**Comment by gabime** [comment]
Right. Should be fixed indeed. Thanks

**Comment by gabime** [comment]
Fixed in f8b728ea8a5ea5b10148b69737f88e8c11909673
