### ISSUE TITLE
Is it possible to have multiple formatting patterns?

### ISSUE THREAD

**Issue by m-peko** [gabime/spdlog#1166]
Hi there,

I would like to be able to define two additional parameters in the logging pattern. For example, root of my application has the following pattern `[%H:%M:%S] APP_NAME [%l] [thread %t]`. Now, I am running multiple components and I would like to have additional information in that component's logging pattern (e.g. `[%H:%M:%S] APP_NAME [%l] [thread %t] COMPONENT_NAME`).
Is this possible to achieve automatically, i.e. in a way different from what I am doing right now: `logger_->info("{} ...", COMPONENT_NAME...);`

Thank you

**Comment by tt4g** [comment]
The name of the logger can be included in the message with the pattern flag `%n`.
Components must have their own loggers to achieve this goal.

**Comment by m-peko** [comment]
Thank you very much
