### ISSUE TITLE
warning: initialization of 'level_string_views' with static storage duration may throw an exception that cannot be caught [cert-err58-cpp]

### ISSUE THREAD

**Issue by ClausKlein** [gabime/spdlog#1170]
`run-clang-tidy.py ...`

26390 warnings generated.

include/spdlog/common-inl.h|12 col 22| warning: initialization of 'level_string_views' with static storage duration may throw an exception that cannot be caught [cert-err58-cpp]
static string_view_t level_string_views[] SPDLOG_LEVEL_NAMES;
                      ^

Suppressed 26389 warnings (26389 in non-user code).

include/spdlog/fmt/bundled/core.h|371 col 3| note: possibly throwing constructor declared here
   basic_string_view(const Char *s)
   ^

'clang-tidy -header-filter=include/spdlog/[^f].* -checks=-misc-definitions-in-headers,boost-*,cert-*,portability-*,readablitity-* -p=/Users/clausklein/Workspace/cpp/spdlog /Users/clausklein/Workspace/cpp/spdlog/src/spdlog.cpp`

**Comment by gabime** [comment]
closing since there is no fix without major code changes. the string_view won’t throw anyway in this case.

**Comment by ClausKlein** [comment]
You may find a lot of ways around this problem:
https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR58-CPP.+Handle+all+exceptions+thrown+before+main()+begins+executing
