### ISSUE TITLE
flush_every does not support synchronous logger?

### ISSUE THREAD

**Issue by Mrzhuzy** [gabime/spdlog#1172]
hello, Can you give me an answer?

**Comment by tt4g** [comment]
Is that for `logger::flush()` ?

**Comment by Mrzhuzy** [comment]
> Do you want to `logger::flush()` ?
 I want 
    m_hHandle = spdlog::create<spdlog::sinks::daily_file_sink_mt>(m_plogconfig.logname, m_plogconfig.filename, 11, 59);
    m_hHandle->set_level((spdlog::level::level_enum)m_plogconfig.level);
    m_hHandle->flush_on(spdlog::level::level_enum::err);
    spdlog::flush_every(std::chrono::seconds(m_plogconfig.flushtime));

**Comment by tt4g** [comment]
Does this mean that the log is not flushed by `spdlog::flush_every()` ?
If so, the synchronous logger will also output the log periodically.

there are conditions for this. The logger needs to be registered in spdlog registry.
The logger is registered in the spdlog registry by `spdlog::create<Sink>()`.

However, the log will not be flushed unless the time specified by `spdlog::flush_every()` has elapsed before the application ends.
To get around this, call `spdlog :: shutdown ()` just before the application exits (when you no longer use the logger).
