### ISSUE TITLE
[*** LOG ERROR ***] [2019-07-27 15:51:18] [log] async log: thread pool doesn't e xist anymore

### ISSUE THREAD

**Issue by Mrzhuzy** [gabime/spdlog#1173]
my code :

	auto tp = std::make_shared<spdlog::details::thread_pool>(10240, 2);
    auto daily_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>("date.log", 23, 59);
   auto  m_hHandle = std::make_shared<spdlog::async_logger>("log", daily_sink, tp, spdlog::async_overflow_policy::block);
    m_hHandle->set_level((spdlog::level::level_enum)0);
    m_hHandle->flush_on(spdlog::level::level_enum::err);
    spdlog::flush_every(std::chrono::seconds(1));
    spdlog::register_logger(m_hHandle);
	
	m_hHandle->error("11111111");
	m_hHandle->error("22222222");

why?

**Comment by tt4g** [comment]
`spdlog::async_logger` receives `thread_pool` as `std::weak_ptr`.

https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/details/async_logger_impl.h#L32-L36

If `std::shared_ptr<spdlog::detail::thread_pool` is deleted, you will get an error because there is no `thread_pool`.

https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/details/async_logger_impl.h#L39-L65

**Comment by Mrzhuzy** [comment]
> `spdlog::async_logger` receives `thread_pool` as `std::weak_ptr`.
> 
> https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/details/async_logger_impl.h#L32-L36
> 
> If `std::shared_ptr<spdlog::detail::thread_pool` is deleted, you will get an error because there is no `thread_pool`.
> 
> https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/details/async_logger_impl.h#L39-L65

thank you ! so, how can i use async_logger？

**Comment by tt4g** [comment]
The easiest way is to get `thread_pool` managed by spdlog registry.

Change the first part of the code you wrote:

```diff
- auto tp = std::make_shared<spdlog::details::thread_pool>(10240, 2);
+ spdlog::init_thread_pool(10240, 2);
+ auto tp = spdlog::thread_pool();
auto daily_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>("date.log", 23, 59);
auto m_hHandle = std :: make_sharedspdlog :: async_logger（ "log"、daily_sink、tp、spdlog :: async_overflow_policy :: block）; 
m_hHandle-> set_level（（spdlog :: level :: level_enum）0）; 
m_hHandle-> flush_on（spdlog :: level :: level_enum :: err）; 
spdlog :: flush_every（std :: chrono :: seconds（1））; 
spdlog :: register_logger（m_hHandle）;

m_hHandle->error("11111111");
m_hHandle->error("22222222");
```

The `thread_pool` generated this way is stopped by calling` spdlog::shutdown()`.

**Comment by Mrzhuzy** [comment]
> ```diff
> + spdlog::init_thread_pool(10240, 2);
> + auto tp = spdlog::thread_pool();
> ```

ok,thank you very much
