### ISSUE TITLE
Rotating loggers don't create files?

### ISSUE THREAD

**Issue by Alv3s** [gabime/spdlog#1174]
Hello,

I'm moving from EasyLogging to Spdlg and I'm having a very simple issue. Following the wiki I found that creating rotating logs would be as simple as:

```
#include "spdlog/sinks/rotating_file_sink.h"

int main()
{
    auto file_logger = spdlog::rotating_logger_mt("file_logger", "logs/mylogfile", 1048576 * 5, 3);
    file_logger->info("Hello World!!!");
    return 0;
}
```

But the above code doesn't work and gives an exception:

```
terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  Failed opening file logs/mylogfile for writing: No such file or directory
Aborted (core dumped)
```

Am I doing something wrong or is this an issue?

**Comment by tt4g** [comment]
spdlog does not create directories recursively.

Try creating a `logs` directory.

**Comment by Alv3s** [comment]
Thank you for your feedback. It makes sense but following the wiki newbies like me can get the wrong impression (as the wiki example has a folder and is not stated the I need to create it). Thanks!
