### ISSUE TITLE
wchar support not only for windows?

### ISSUE THREAD

**Issue by glani** [gabime/spdlog#1175]
Just a question.

Why it is forbidden to compile not under windows with using wchar support ?

Many libraries are able to handle this. Why spdlog does not allow it ?

P.S. The second time I have tried to integrate spdlog to the project (the first time it was compiling time issue) and finally I did git revert

**Comment by tt4g** [comment]
Does this mean that you can not build if you have enabled the `SPDLOG_WCHAR_TO_UTF8_SUPPORT` macro?
If so, please provide a reproduce snippet or error log. And what version do you use?

**Comment by tt4g** [comment]
@glani Are you using version 1.4.0 (`v1.x` branch)? If so, similar issues have been reported.
