### ISSUE TITLE
cannot ouput wide string using spdlog 1.4.0

### ISSUE THREAD

**Issue by artemyv** [gabime/spdlog#1176]
I'm trying to use spdlog version 1.4.0 Latest commit 88b4ade  with wchar_t string and got following results (Windows VS2019 ver 16.2)

```c++
`#include "spdlog/spdlog.h"

int main(int, char* [])
{
    spdlog::info("Welcome to spdlog version {}.{}.{}  !", SPDLOG_VER_MAJOR, SPDLOG_VER_MINOR, SPDLOG_VER_PATCH);
    spdlog::debug(L"{}" , L"This message should be displayed..");
}
```

With SPDLOG_WCHAR_TO_UTF8_SUPPORT results in missing output
`[2019-08-01 14:37:49.683] [info] Welcome to spdlog version 1.4.0  !

D:\dev\Samples\spdlog-1.x\Demo_issue\test_spdlog\Debug\test_spdlog.exe (process 13480) exited with code 0.`

Without SPDLOG_WCHAR_TO_UTF8_SUPPORT 

`test_spdlog.cpp(6,64): error C2664:  'void spdlog::debug<wchar_t[35]>(spdlog::string_view_t,const wchar_t (&)[35])': cannot convert argument 1 from 'const wchar_t [3]' to 'spdlog::string_view_t'`

Same code with narrow format
`#include "spdlog/spdlog.h"

int main(int, char* [])
{
    spdlog::info("Welcome to spdlog version {}.{}.{}  !", SPDLOG_VER_MAJOR, SPDLOG_VER_MINOR, SPDLOG_VER_PATCH);
    spdlog::debug("{}" , L"This message should be displayed..");
}`

With or without SPDLOG_WCHAR_TO_UTF8_SUPPORT gives a lot of errors

`include\spdlog\fmt\bundled\core.h(1069,1): error C2440:  'return': cannot convert from 'void' to 'fmt::v5::internal::value<Context>'
include\spdlog\fmt\bundled\core.h(1069,1): error C2440:         with
include\spdlog\fmt\bundled\core.h(1069,1): error C2440:         [
include\spdlog\fmt\bundled\core.h(1069,1): error C2440:             Context=fmt::v5::format_context
include\spdlog\fmt\bundled\core.h(1069,1): error C2440:         ]
include\spdlog\fmt\bundled\core.h(1069,3): message :  Expressions of type void cannot be converted to other types
include\spdlog\fmt\bundled\core.h(1179): message :  see reference to function template instantiation 'fmt::v5::internal::value<Context> fmt::v5::internal::make_arg<true,Context,wchar_t[35]>(const T (&))' being compiled
include\spdlog\fmt\bundled\core.h(1179): message :         with
include\spdlog\fmt\bundled\core.h(1179): message :         [
include\spdlog\fmt\bundled\core.h(1179): message :             Context=fmt::v5::format_context,
include\spdlog\fmt\bundled\core.h(1179): message :             T=wchar_t [35]
include\spdlog\fmt\bundled\core.h(1179): message :         ]
include\spdlog\fmt\bundled\core.h(1179): message :  while compiling class template member function 'fmt::v5::format_arg_store<context,wchar_t [35]>::format_arg_store(const wchar_t (&)[35])'
include\spdlog\fmt\bundled\format.h(3257): message :  see reference to function template instantiation 'fmt::v5::format_arg_store<context,wchar_t [35]>::format_arg_store(const wchar_t (&)[35])' being compiled
include\spdlog\fmt\bundled\format.h(3254): message :  see reference to class template instantiation 'fmt::v5::format_arg_store<context,wchar_t [35]>' being compiled
include\spdlog\logger.h(74): message :  see reference to function template instantiation 'OutputIt fmt::v5::format_to<spdlog::string_view_t,wchar_t[35],500,char>(fmt::v5::basic_memory_buffer<char,500,std::allocator<char>> &,const S &,const wchar_t (&)[35])' being compiled
include\spdlog\logger.h(74): message :         with
include\spdlog\logger.h(74): message :         [
include\spdlog\logger.h(74): message :             OutputIt=std::back_insert_iterator<fmt::v5::internal::basic_buffer<char>>,
include\spdlog\logger.h(74): message :             S=spdlog::string_view_t
include\spdlog\logger.h(74): message :         ]
include\spdlog\logger.h(87): message :  see reference to function template instantiation 'void spdlog::logger::force_log<wchar_t[35]>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t,const wchar_t (&)[35])' being compiled
include\spdlog\logger.h(96): message :  see reference to function template instantiation 'void spdlog::logger::log<wchar_t[35]>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t,const wchar_t (&)[35])' being compiled
include\spdlog\logger.h(111): message :  see reference to function template instantiation 'void spdlog::logger::log<wchar_t[35]>(spdlog::level::level_enum,spdlog::string_view_t,const wchar_t (&)[35])' being compiled
include\spdlog\spdlog.h(137): message :  see reference to function template instantiation 'void spdlog::logger::debug<wchar_t[35]>(spdlog::string_view_t,const wchar_t (&)[35])' being compiled
Demo_issue\test_spdlog\test_spdlog.cpp(6): message :  see reference to function template instantiation 'void spdlog::debug<wchar_t[35]>(spdlog::string_view_t,const wchar_t (&)[35])' being compiled
`

Is it possible somehow to output the wide strings still?

**Comment by gabime** [comment]
its missing because debug level is not enabled by default. use spdlog::set_level(..)

**Comment by artemyv** [comment]
Thanks it is really was the cause.
But the problem persists when using SPDLOG_INFO
All these macros skip calling logger::log and go directly to spdlog::force_log member
And it looks like the force_log does not have the wide string overload

**Comment by gabime** [comment]
Right. Nerd to be fixed.

**Comment by artemyv** [comment]
How about adding possibility to log mix of wide and narrow string arguments using narrow format when SPDLOG_WCHAR_TO_UTF8_SUPPORT is on?

Basic idea would be to convert all wide strings to narrow before passing to force_log instead of current approach of the whole buffer only. Will this require to much overhead?

`
	#include "spdlog/spdlog.h"

	#define SPDLOG_LOGGER_CALL_W(logger, level, ...)    logline(logger,spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, level, __VA_ARGS__)

	template<class T>
	auto convert(T&& arg)
	{
		return std::forward<T>(arg); // Forward as lvalue or as rvalue, depending on T
	}

	auto convert(const wchar_t* arg)
	{
		auto result_size = ::WideCharToMultiByte(CP_UTF8, 0, arg, -1, NULL, 0, NULL, NULL);

		if (result_size > 0)
		{
			std::string target;
			target.resize(result_size);
			result_size = ::WideCharToMultiByte(CP_UTF8, 0, arg, -1, target.data(), result_size, NULL, NULL);

			if (result_size > 0)
			{
				target.resize(result_size);
				return target;
			}
		}
		throw std::exception("Could not convert string");
	}

	template<typename LoggerPtr, typename... Ts>
	void logline(LoggerPtr logger, spdlog::source_loc loc, spdlog::level::level_enum level, const char* fmt, Ts... args)
	{
		if (logger->should_log(level))                                                                                                     
			logger->force_log(loc, level, fmt, convert(args)...);
	}

	int main(int, char*[])
	{
		spdlog::info("Welcome to spdlog version {}.{}.{}  !", SPDLOG_VER_MAJOR, SPDLOG_VER_MINOR, SPDLOG_VER_PATCH);
		spdlog::info(L"{}", L"This message should be displayed..");
		SPDLOG_LOGGER_CALL_W(spdlog::default_logger_raw(),spdlog::level::info,"{} is {}", L"This message should be displayed..", "This message should be displayed..");
	}
`

I did not try to utilize details::os::wstr_to_utf8buf as is to to provide sample for all possible string representations just a general idea.

**Comment by gabime** [comment]
Interesting approach. I think in your example, convert need to be variadic. Will check, however I am not sure it would worth the extra compile times and complexity..

**Comment by artemyv** [comment]
No convert receives each parameter one by one
for example for Ts... args being int i, char c, const char* str, const wchar_t* wstr
the convert(args)... expands to
convert(i), convert(c), convert(str), convert(wstr)

**Comment by artemyv** [comment]
Why on line 217 parameter is string_view_t and not wstring_view_t? I just got a notification did not try to compile it...

**Comment by gabime** [comment]
oops.. Fixed again.

**Comment by artemyv** [comment]
tried to compile - another 2 errors
spdlog\include\spdlog\logger.h(228): error C3861: 'source': identifier not found
spdlog\include\spdlog\logger.h(239): error C3861: 'loc': identifier not found

**Comment by StevenSavold** [comment]
I am currently using spdlog 1.8.2 and experiencing this issue with SPDLOG_INFO macro on Windows. 
I am attempting to log a wide string like this, am I missing something?
```cpp
std::wstring myString = L"my wide string";
SPDLOG_INFO(L"This is {}", myString.c_str());
```

I have used set_level to set my logging level to trace.
