### ISSUE TITLE
win10: failed to compile for Android x86_64

### ISSUE THREAD

**Issue by fasiondog** [gabime/spdlog#1178]
> failed compile for android x86_64, error info:
> \spdlog/details/os-inl.h:215:9: error: no matching function for call to 'fstat64'
>     if (fstat64(fd, &st) == 0)
>         ^~~~~~~
> \AppData\Local\Android\Sdk\ndk-bundle\sysroot/usr/include\sys/stat.h:159:5: note: candidate function not viable: no known conversion from 'struct stat *' to 'struct stat64 *' for 2nd argument
> int fstat64(int __fd, struct stat64* __buf) __RENAME_STAT64(fstat, 3, 21);
>     ^
> 1 error generated.

i remove “defined(__x86_64__)” as shown below, now it works, but i don'tn know reason:

> //#if !defined(__FreeBSD__) && !defined(__APPLE__) && (defined(__x86_64__) || defined(__ppc64__)) && !defined(__CYGWIN__)
> #if !defined(__FreeBSD__) && !defined(__APPLE__) && (defined(__ppc64__)) && !defined(__CYGWIN__)

**Comment by gabime** [comment]
@fasiondog Can you check if the adding following line before line 215 fix it ? 

```c++
#if defined(__ANDROID__) && defined(__ANDROID_API__) && (__ANDROID_API__ < 21)
#define stat64 stat
#endif
```
If yes, I will issue a fix..

**Comment by fasiondog** [comment]
No，it is still failed. I only use "#if defined(__ANDROID__)" is failed also.

**Comment by gabime** [comment]
How about the if you replace line 218 with:

```c++
#if not defined(__ANDROID__) 
struct stat64 st;
#else
struct stat st;
#endif
```

**Comment by fasiondog** [comment]
Failed too. 
May be modifed like: 
#if !defined(__FreeBSD__) && !defined(__APPLE__) && (**(defined(__x86_64__) && !defined(__ANDROID__))** || defined(__ppc64__)) && !defined(__CYGWIN__)

**Comment by gabime** [comment]
It compiles fine in Linux.

**Comment by fasiondog** [comment]
checking for the NDK directory ... C:\Users\AOC\AppData\Local\Android\Sdk\ndk-bundle
checking for the SDK version of NDK ... 28
checking for the toolchains version of NDK ... 4.9
checking for the Android SDK directory ... C:\Users\AOC/AppData/Local/Android/Sdk
checking for the Build Tools Version of Android SDK ... 29.0.0

**Comment by fasiondog** [comment]
I use xmake project, not in android studio. The complete compilation information is as follows :

[  5%]: compiling.release cpp\yihua\data_driver\sqlite\SQLiteDataDriver.cpp
C:\\Users\\AOC\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++ -c -Wall -Werror -O3 -msse -msse2 -msse3 -mmmx -std=c++17 -ID:\\\\src\\\\boost_1_69_0 -ID:\\\\workspace\\\\yhfacedetect\\\\3rdparty -ID:\\\\workspace\\\\yhfacedetect\\\\cpp -DBOOST_ALL_DYN_LINK -DDLIB_NO_GUI_SUPPORT -DDLIB_PNG_SUPPORT -DDLIB_JPEG_SUPPORT -DDLIB_JPEG_STATIC -Ipkg\\\\facedetect.pkg\\\\android\\\\x86_64\\\\include -Ipkg\\\\dlib.pkg\\\\android\\\\x86_64\\\\include -Ipkg\\\\sqlite3.pkg\\\\android\\\\x86_64\\\\include -frtti -fexceptions -fopenmp --sysroot=C:\\Users\\AOC\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\sysroot -isystem C:\\Users\\AOC\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\sysroot\\usr\\include\\x86_64-linux-android -IC:\\Users\\AOC\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\sources\\cxx-stl\\llvm-libc++/include -IC:\\Users\\AOC\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\sources\\cxx-stl\\llvm-libc++/libs/x86_64/include -IC:\\Users\\AOC\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\sources\\cxx-stl\\llvm-libc++abi\\include -Qunused-arguments -target x86_64-none-linux-android -gcc-toolchain C:\\Users\\AOC\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\x86_64-4.9\\prebuilt\\windows-x86_64 -D__ANDROID_API__=28 -fPIC -o build\\release\\android\\x86_64\\.objs\\android\\x86_64\\release\\cpp\\yihua\\data_driver\\sqlite\\SQLiteDataDriver.cpp.o cpp\\yihua\\data_driver\\sqlite\\SQLiteDataDriver.cpp
error: C:\Program Files (x86)\xmake/core/base/os.lua:715: C:\Program Files (x86)\xmake/core/base/os.lua:715: C:\Program Files (x86)\xmake/core/base/os.lua:715: C:\Program Files (x86)\xmake/core/base/os.lua:715: In file included from cpp\yihua\image_process\ImageHash.cpp:10:
In file included from cpp\yihua\image_process/ImageHash.h:18:
In file included from cpp\yihua\image_process/../DataType.h:27:
In file included from cpp\yihua\image_process/../Log.h:15:
In file included from D:\\workspace\\yhfacedetect\\3rdparty\spdlog/spdlog.h:13:
In file included from D:\\workspace\\yhfacedetect\\3rdparty\spdlog/details/registry.h:103:
In file included from D:\\workspace\\yhfacedetect\\3rdparty\spdlog/details/registry-inl.h:12:
In file included from D:\\workspace\\yhfacedetect\\3rdparty\spdlog/logger.h:19:
In file included from D:\\workspace\\yhfacedetect\\3rdparty\spdlog/details/log_msg.h:33:
In file included from D:\\workspace\\yhfacedetect\\3rdparty\spdlog/details/log_msg-inl.h:10:
In file included from D:\\workspace\\yhfacedetect\\3rdparty\spdlog/details/os.h:92:
D:\\workspace\\yhfacedetect\\3rdparty\spdlog/details/os-inl.h:215:9: error: no matching function for call to 'fstat64'
    if (fstat64(fd, &st) == 0)
        ^~~~~~~
C:\Users\AOC\AppData\Local\Android\Sdk\ndk-bundle\sysroot/usr/include\sys/stat.h:159:5: note: candidate function not viable: no known conversion from 'struct stat *' to 'struct stat64 *' for 2nd argument
int fstat64(int __fd, struct stat64* __buf) __RENAME_STAT64(fstat, 3, 21);
    ^
1 error generated.

**Comment by gabime** [comment]
It is hard for me to reproduce. Maybe you can find the right ifdef sequence to replace the `struct  stat64` with `struct stat` but **only** for this perticular setup.

**Comment by fasiondog** [comment]
OK.  I will compare android compilations on Linux and Windows later, and see if there's anything I can do

**Comment by gabime** [comment]
@fasiondog Any news about it ?

**Comment by fasiondog** [comment]
No, I can't found any macros that distinguish between android compilations on WIN or LINUX

**Comment by iansachs** [comment]
@fasiondog @gabime i know this is closed, but I stumbled across this issue and I am wondering if it is caused by the inclusion of dlib.

Specifically: `dlib/dir_nav/dir_nav_kernel_2.h` defines:
```c++
#if !defined(__USE_LARGEFILE64 ) && !defined(_LARGEFILE64_SOURCE)
#define stat64 stat
#endif
```

**Comment by fasiondog** [comment]
> 
> 
> @fasiondog @gabime i know this is closed, but I stumbled across this issue and I am wondering if it is caused by the inclusion of dlib.
> 
> Specifically: `dlib/dir_nav/dir_nav_kernel_2.h` defines:
> 
> ```c++
> #if !defined(__USE_LARGEFILE64 ) && !defined(_LARGEFILE64_SOURCE)
> #define stat64 stat
> #endif
> ```

Thanks! I think you are right, i am using dlib
