### ISSUE TITLE
S macro breaks my code because I have an struct called S

### ISSUE THREAD

**Issue by gnzlbg** [gabime/spdlog#118]
I just updated the library and now there is a macro called `S` defined in `common.hpp` that is exported and breaks any code in which there is a class, function, variable, or template parameter called `S`. 

If the macro is used internally it should be undefined before any code external to `spdlog` sees it. 
If the macro is to be exported by the library it should be called `SPDLOG_S_` at least to avoid name clashes. 

From the usage of the macro it looks that it is only intended for internal usage within the library and thus should be undefined.

**Comment by gabime** [comment]
I reverted the problematic change..
