### ISSUE TITLE
CMake Refactoring breaks compilation with CMake version 3.1

### ISSUE THREAD

**Issue by felixfrank** [gabime/spdlog#1180]
Commit 68a0193d952eb0b39ccb54e3a8c60b72c3f189a9 changes the way the CMake build systems extracts the spdlog version. Instead of using the matched substrings directly, the `CMAKE_MATCH_COUNT` is used. This variable does not exist prior to CMake 3.2, at least that's the first time it appears in the documentation, and it definitely breaks compilation with CMake 3.1.

I guess you should increase the minimum required version to 3.2.

**Comment by gabime** [comment]
Fixed. Thanks for reporting.
