### ISSUE TITLE
add compression to rotating file sink

### ISSUE THREAD

**Issue by m4ce** [gabime/spdlog#1181]
This is not an issue but more of a feature request. It would be really nice if the rotating file sink would optionally compress the rotated log file, let's say to gzip?

log4j2 has a similar feature in its RotatingFile appender: 

```    <RollingFile name="RollingFile" fileName="logs/app.log"
                 filePattern="logs/$${date:yyyy-MM}/app-%d{MM-dd-yyyy}-%i.log.gz">
```

when the `filePattern` ends with `gz`, it will automatically compress it for you.

**Comment by artemyv** [comment]
On windows I'd like to have zip possibility

**Comment by gabime** [comment]
Depending on a zip/gzip/tar/your favourite compression is pretty big. 

A better way would be to provide the option to prodie a function what would be called after each rotation (along with the rotated filenames). 

something like 
```c++
void on_rotated(std::vector<std::string> rotated_filenames);
```

This way, everyone is happy and can use its own favourite cleaning mechanism.

**Comment by m4ce** [comment]
@gabime, that would work well! Would we pass that as a std::function when instantiating the rotating file sink?

**Comment by gabime** [comment]
something like that, yes

**Comment by m4ce** [comment]
@gabime - that would be really useful. Any chance to get this feature in one of the next releases? :)

**Comment by gabime** [comment]
I hope so

**Comment by m4ce** [comment]
@gabime, by the way, I was thinking about this and I was wondering how to go about a possible scenario.

Assume that we rotate the files and then we call `on_rotated`. Also assume that the user will go through the rotated files and gzip them, they will be renamed to `<log>.gz`. When the next rotation runs, the files will be rotated using the old index without taking into consideration the compressed ones.

I guess one way to solve this is to also optionally provide the user with a function to determine the new file name? Open to ideas..

**Comment by m4ce** [comment]
@gabime, in the `rotating_file_sink<Mutex>::rotate_()`, there's a loop that takes care of rotating the files. However, the `calc_filename` will not take into consideration the `.gz` extension when building the `filename.<index>log`..

**Comment by gabime** [comment]
I don't think there is an issue If I understand correctly.

For example:

After the callback only the following files exist: 
```
log.txt (active file, cannot be zipped)
log.1.zip, 
log.2.zip
```

After on the next rotate spdlog will only file "log.txt" and will rotate it to "log1.txt", so the callback will get only "log.1.txt" to zip and after this procedure we get:

```
log.txt,
log1.zip (new)
log2.zip(old)
log3.zip(old)
```

**Comment by m4ce** [comment]
Yep, never mind, I think it's actually fine at the end as the callback that takes care of compressing the rotated file could add something extra in the filename like the date and time to make it unique, or simply an extra counter. If the rotated file gets compressed after the each rotation runs, spdlog will always rotate one file at most ..

**Comment by gabime** [comment]
> rotated file could add something extra in the filename like the date and time to make it unique

Right, but note that in this case there is no much point in the rotating operation at all.  The callback will have to take care of cleaning/rotating in each round. Confusing stuff..

**Comment by pancpp** [comment]
@gabime Since this issue is closed, does the latest release of spdlog support compression after rotation as of now? Thanks.
