### ISSUE TITLE
Question on daily_file_sink_st and  rotating_logger_mt

### ISSUE THREAD

**Issue by SnowfallDan** [gabime/spdlog#1182]
I want to combine rotating strategy with rotating_sink and daily_sink.
 I want to combine rotating with size. if size up to my setting size, then rotated. if day is changed, then write to next day log file, for now I cannot find how to do.
I find #707 . But not fit me.

Looking forward your reply, thanks.

**Comment by tt4g** [comment]
So far no sink implementation has been provided that combines the characteristics of both `daily_file_sink` and `rotating_file_sink`.

Since the sink is a virtual class, a custom sink can be created and used if necessary.

**Comment by SnowfallDan** [comment]
i thought a another soulution. Monitor file size using a shell script. If the file size reaches a certain size, copy and delete the daily_file_sink_st file. But deleted files will not be regenerated by daily_file_sink_st.
if there is a solution?

Looking forward your reply, thanks.

**Comment by tt4g** [comment]
If the application that uses spdlog is a type that runs periodically, there will be no problem. 

It will not work for resident applications. If the log file is deleted, the spdlog file descriptor will be corrupted and an error will occur.
If you want to avoid the error, you need to regenerate the spdlog sink.

**Comment by SnowfallDan** [comment]
thx!
