### ISSUE TITLE
spdlog deadlocks on thread_pool destructor when using inside a DLL.

### ISSUE THREAD

**Issue by KevinW1998** [gabime/spdlog#1183]
I am using spdlog inside a DLL that uses threads. Now my problem is that when the DLL unloads and threads are still active, then windows just kills it without notification. Basically when the thread_pool gets destructed then it deadlocks when it tries to post a blocking terminate message.

I temporary "fixed" is by calling `spdlog::details::registry::instance().set_tp(nullptr);` early (before threads are killed) though I don't see it as a permanent solution.

**Comment by tt4g** [comment]
If you do not release all resources by calling `spdlog::shutdown()` before exiting the application, the logger may not exit correctly.

**Comment by KevinW1998** [comment]
Thank you, this fixed the issue.

**Comment by polesapart** [comment]
Is this documented on the wiki (or elsewhere)?
