### ISSUE TITLE
Cannot configure different patterns on loggers sharing sink

### ISSUE THREAD

**Issue by Tmplt** [gabime/spdlog#1184]
```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"

int main() {
  auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
  auto a = std::make_shared<spdlog::logger>("a", stdout_sink);
  auto b = std::make_shared<spdlog::logger>("b", stdout_sink);

  a->set_pattern("%v");
  b->set_pattern("debug %v");

  a->info("a");
  b->info("b");
}
```
When above example executes the output is
```
debug a
debug b
```
instead of the expected
```
a
debug b
```
[From the wiki entry](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#customizing-format-using-set_pattern) I figure I should be able to configure different patterns for loggers, even though they share a sink. Or is the actual output above expected behavior?

Tested on 8cc0997f796d2295b0ccc9caaf0abcca25d89525, currently latest HEAD of `v1.x`.

**Comment by tt4g** [comment]
The format is always set to sink. The logger sets the format to its own sink.

See source document:
https://github.com/gabime/spdlog/blob/8cc0997f796d2295b0ccc9caaf0abcca25d89525/include/spdlog/logger.h#L317-L319

and wiki: [3. Custom formatting](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting)

> Each logger's sink have a formatter which formats the messages to its destination.

**Comment by Tmplt** [comment]
I see, thank you.
