### ISSUE TITLE
Separate sink log levels within multilogger don't work

### ISSUE THREAD

**Issue by sktpin** [gabime/spdlog#1187]
I have 1 console sink, and 1 rotating sink.
I set the console to level=warn, the file one to trace.
I add them both to a multilogger.
I set: multiLogger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%l] %v").
I globally register: spdlog::register_logger( multiLogger );
And: spdlog::flush_every(std::chrono::seconds( 3 ));

Now when calling the different logging functions on the multilogger:
Trace, Debug and Info messages don't get through to the log file.
I then, for debugging, set also the console sink to Trace. They also don't get through to the console.
Then I changed the code to, after everything else was set up, setting the level on the multilogger itself, to Trace: NOW trace/debug/info messages get through to both file and console.
But, I want them only in the file, and only severe stuff on the console, and my impression was that it is supposed to work like that because you can assign levels to sinks within a logger.
Am I wrong?
Or is this a bug?
___
As a side note: I am using a stdout_color_sink_mt for the console, to be precise.
It does not color the labels there on my console. On the same console, a direct call to spdlog::info(...) does give a green colored "[info]" tag, though. I wonder why that is.
___
**EDIT**: Hrm, there is a certain overriding behavior I wasn't aware of. It seems that the multilogger needs to have the least severe level (trace), and then if I set the sinks to console=warn, rotating=trace, then I get the intended behavior of the file logging everything, while the conssole shows only more severe messages. (save for the missing coloring on the console - should I make an own issue out of it?)

**Comment by gabime** [comment]
That's the intended behavior although I agree it can be confusing. Both logger and sink their own dedicated log level. The default level loggers is "Info" - that's why you didn't see the trace stuff.
