### ISSUE TITLE
Static lib have to be compiled with -fpic

### ISSUE THREAD

**Issue by yesint** [gabime/spdlog#1190]
The static library built with CMake is compiled with no -fpic and thus can't be linked afterwards. Passing -DCMAKE_CXX_FLAGS="-fpic" manually solves the problem but this should be added to build system.

**Comment by gabime** [comment]
>  can't be linked afterwards

How can this reproduced? I had never any problems leven without this flag.

**Comment by tt4g** [comment]
We should be able to control `-fpic` by defining `CMAKE_POSITION_INDEPENDENT_CODE`.

https://stackoverflow.com/questions/38296756/what-is-the-idiomatic-way-in-cmake-to-add-the-fpic-compiler-option

**Comment by gabime** [comment]
Afaik CMake already does the right thing automatically - add “-fpic״ to dynamic lib builds.

**Comment by marcizhu** [comment]
CMake does add the `-fpic` flag to dynamic libraries, but does NOT add it to static libs, which makes it impossible to link spdlog as a static lib against a dynamic one.

To reproduce this, build a small DLL that uses spdlog, compile it as a dynamic lib and link against spdlog as a static lib. You will see it generates a linker error and it even suggests to add the `-fpic` flag when compiling.

**Comment by yesint** [comment]
> How can this reproduced? I had never any problems leven without this flag.

I just naively installed spdlog using cmake with default options:
```

cmake ../spdlog -DCMAKE_INSTALL_PREFIX=whatever
make 
make install
```

When linking with installed lib I've got an error about missed fpic.
If configured as 
`cmake ../spdlog -DCMAKE_INSTALL_PREFIX=... -DCMAKE_CXX_FLAGS="-fpic"`
this problem vanishes.

**Comment by gabime** [comment]
So there are 2 workaround fixes to this:
1. use  -DCMAKE_CXX_FLAGS="-fpic"
2. Link to the dynamic lib version of spdlog

I might add a a dedicated "SPDLOG_BUILD_FPIC" CMake option if it still proves to be confusing.

**Comment by chrisdembia** [comment]
I just ran into this issue. It would be great to smooth out this process.

**Comment by Otacon5555** [comment]
> 
> 
> I just ran into this issue. It would be great to smooth out this process.

Same here, maybe building it as a shared lib could be the default. However, I'm loving this library, thank you!

**Comment by chrisdembia** [comment]
> Same here, maybe building it as a shared lib could be the default. 

This can usually be controlled with the global CMake variable [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html). I think it would still be good to fix the issue by adding the line `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` in the root `CMakeLists.txt`. 

> However, I'm loving this library, thank you!

Yes, it's wonderful!

**Comment by m-chichikalov** [comment]
I just run into exact issue (below my solution, maybe would helpful to someone)

if your project fetch spdlog as a sub_project it's just simple as add `POSITION_INDEPENDENT_CODE` property...

```cmake
FetchContent_Declare(
    spdlog
    GIT_REPOSITORY https://github.com/gabime/spdlog.git
    GIT_TAG        v1.6.1
)

FetchContent_GetProperties(spdlog)
string(TOLOWER "spdlog" lcName)
if(NOT ${lcName}_POPULATED)
  FetchContent_Populate(spdlog)
  add_subdirectory(${${lcName}_SOURCE_DIR} ${${lcName}_BINARY_DIR})
  set_target_properties( spdlog
    PROPERTIES
        POSITION_INDEPENDENT_CODE ON
  )
endif()
```
