### ISSUE TITLE
Windows: spdlog does not output to stdout?

### ISSUE THREAD

**Issue by alanhdu** [gabime/spdlog#1191]
Hi! I have a possibly very naive bug. Right now, I have the following program:

```cpp
#include <iostream>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>

int main() {
  auto logger = spdlog::stdout_color_mt("console");
  for (int i = 0; i < 10; i ++) {
    logger->info("Hello world");
    logger->flush();
  }
  std::cout << "Hello" << std::endl;
  std::cout << "Good bye!" << std::endl;
  return 0;
}
```

when I run compile and run it in the powershell, everything works as expected. But when I try to programmatically intercept the output using Python:

```python
import subprocess
process = subprocess.Popen(
    "test.exe", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = process.communicate()
print((stdout, stderr))
```

Python only ever outputs the things we printed to `std::cout`, and none of the things output by the logger! (i.e. this prints `(b'Hello\r\nGood bye!\r\n', b'')`).

This is with spdlog 1.2.1 compiled for Windows 10 on Visual Studio C++ 17 (and Python 3.6, if that's relevant).

Do you know what's going on here, and why I'm unable to programmatically grab the output of this small program?

**Comment by alanhdu** [comment]
Poking around the docs a little more, it seems like I should be using `msvc_sink` here. Is that correct? If so, feel free to close!

(Sorry if this is just noise -- I'm pretty clueless about Windows C++ development -- I've worked almost exclusively on Linux)

**Comment by gabime** [comment]
It is a bug (#1147) that have been solved lately.
Please try latest commit.

**Comment by alanhdu** [comment]
> It is a bug (#1147) that have been solved lately.

Thanks! I've confirmed that this code works as expected against the latest version of master!

> I don't think so .

Yup -- I was just being dumb.
