### ISSUE TITLE
No feature to replace the clone() API

### ISSUE THREAD

**Issue by vstojkovic** [gabime/spdlog#1197]
Removing the `clone()` method from the `logger` class leaves no way for existing code to do the same thing. If I use the copy constructor, I can't rename the new logger. If I use the constructor that takes the name and the sinks, I can't make the new logger use the source logger's custom error handler, because it's write-only.

**Comment by gabime** [comment]
Yes. I realized this too after removing this.. We be fixed

**Comment by gabime** [comment]
Fixed.

**Comment by vstojkovic** [comment]
Thanks for the quick turnaround.
