### ISSUE TITLE
add ""crash safe"

### ISSUE THREAD

**Issue by ryhzd** [gabime/spdlog#1198]
I like spdlog, thanks for you great works! but, when soft crashed, the spdlog can't save log, can you add "crash safe" function like g3log, thanks!

**Comment by gabime** [comment]
related #1197 

You can try to setup a signal handler to flush like in the example in #1197 - but there is a good chance it won't work (signal handlers + threading/mutexes don't play together well).

I suggest setting the logger's flush level or using the "automatic_flush()" function.
