### ISSUE TITLE
Still no wchar support?

### ISSUE THREAD

**Issue by kakyoism** [gabime/spdlog#1199]
The API design of this project is beautiful. But this wchar problem is just a deal breaker for me right now.

```
1>g:\me\app.cpp(72): error C2664: 'void spdlog::info<LPWSTR,LPWSTR>(const char *,const LPWSTR &,const LPWSTR &)': cannot convert argument 1 from 'const wchar_t [22]' to 'const char *'
```

... Or am I missing anything obvious?

**Comment by gabime** [comment]
There is support for windows (define SPDLOG_WCHAR_TO_UTF8_SUPPORT).

**Comment by kakyoism** [comment]
Thanks! IMHO, this could turn down Windows users from the get-go. It'd better be in the `README.md`, e.g., somewhere around the Basic Usage. Or could it be more transparent with a locale detection during build? I don't know. Anyways, I'm all good now.

**Comment by kakyoism** [comment]
hmm, still not wirte

**Comment by tt4g** [comment]
> hmm, still not right. The output is not correct wchars but converted to UTF8? Is this by design?

Yes.
`wchar_t` is converted to UTF-8 encoding`char`, if `SPDLOG_WCHAR_TO_UTF8_SUPPORT` is defined.

**Comment by kakyoism** [comment]
@tt4g duh... So is there a roadmap towards a true wchar support? [plog](https://github.com/SergiusTheBest/plog) supports wchar out of the box. If spdlog could add the feature,  then it'd be a clear winner, but right now `plog` seems to have an upper hand.

**Comment by tt4g** [comment]
As far as I know, `wchar_t` support is only `SPDLOG_WCHAR_TO_UTF8_SUPPORT`.

I have never used plog. I don't know exactly what feature you want, but do you want to output `wchar_t` as it is?

As far as I look at the plog source code, it seems that `std::wostream` outputs `wchar_t` when the `_WIN32` macro exists.

Since spdlog uses an API that outputs `char` in many places, it will not be easy to add support to output` wchar_t` as it is.

**Comment by tt4g** [comment]
The big problem is that C ++ `char` and `wchar_t` don't have character encoding information. Both strings are treated as just bytes in the computer.

Fortunately, the `wchar_t` generated by the MSVC compiler is determined to be in UTF-16 encoding. If you can determine the character encoding in the file, you may be able to avoid garbled characters by converting `wchar_t` to `char` with `WideCharToMultiByte`: https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte

**Comment by gabime** [comment]
>  then it'd be a clear winner to me, but right now `plog` seems to have an upper hand.

@kakyoism Its not a contest, please use plog if you find it more suitable.

**Comment by kakyoism** [comment]
@tt4g Thanks for the info. I do know about charset conversion and I fully admire the work behind spdlog. It's still my first choice when I work with char 100%. Despite the fact that client-side workaround exists, it'd be really great that a usability-oriented third-party cross-platform wrapper could hide platform details.

**Comment by kakyoism** [comment]
@gabime Please don't take my playful words too seriously. I fully admire your work and there is really no offense.
