### ISSUE TITLE
Ubuntu: strange characters in output

### ISSUE THREAD

**Issue by boxerab** [gabime/spdlog#1204]
First of all, thanks for this make this great library available!

I tried some lines from the sample code in my project:

```
spdlog::info("Welcome to spdlog!");
spdlog::error("Some error message with arg: {}", 1);
````
And this is the output:

```
[2019-09-01 17:08:29.372] [[32minfo[m] Welcome to spdlog!
[2019-09-01 17:08:29.372] [[31m[1merror[m] Some error message with arg: 1
```

**Comment by gabime** [comment]
which terminal is it? if fails to display ansi color codes..

**Comment by boxerab** [comment]
Thanks, this is on Eclipse CDT, in the console.

**Comment by boxerab** [comment]
Ahhh! I installed a plugin for ANSII color and it works fine now. Thanks!!!
