### ISSUE TITLE
Is it really necessary for the registry to be a singleton?

### ISSUE THREAD

**Issue by caiazza** [gabime/spdlog#1207]
Hi gabime,
I'm trying to use your library in a pretty large project involving multiple library and plugins. As you already noted in other issues an important problem is the uniqueness of the registry in the different libraries. This can be mitigated using the compiled version of spdlog but I think it could be mitigated further by separating the definition of the registry with the definition of its global instance. I would suggest to define the registry as a normal class of which one can have multiple instances with a free function or a static method which declares the global instance which is used for convenience in the factory functions. You will still have a unique global instance which is the one referred to by the internal functions but now you also allow the user to simply embed the registry in a convenient place in their code in case they want to use a managed instance rather than a global one.

What do you think?

**Comment by gabime** [comment]
The functions under the```spdlog::``` namespace are using the singleton instance..

Do you want to create another instance and use it in other places ? or do you want to point the ```spdlog::``` functions to your new instance ?

**Comment by caiazza** [comment]
I want to be able to create local instances of the registry.
The point is that you don't need that instance to be unique. You can have a single global object of a class without that class being a singleton. The typical example is ```std::cout```. That is a global object of the ```iostream``` class but the ```iostream``` class is not a singleton.
You can have a very minimal change by having the constructors back in the public section which allows a user to have their local registries which they can manage by themselves, possibly embedding them deep in their libraries without ever exposing them to their own users. This shouldn't break anything because the ```instance()``` function will still refer to a static object created at the first call, at least within each library boundary. To make things more clear, you could replace the ```instance()``` method with free function returning a ```registry&``` called something like ```GetGlobalRegistry()``` but that would be a breaking change unless you keep also the instance() function and from there you call this free function and you could label the instance function deprecated to give a clear indication to your users.

**Comment by gabime** [comment]
ok, Lets keep it simple and just make the constructor and destructor public.  Pr is welcome

**Comment by caiazza** [comment]
I'll try to do something within a couple of days.
