### ISSUE TITLE
Output raw string data

### ISSUE THREAD

**Issue by matt77hias** [gabime/spdlog#1208]
I like `spdlog`'s way of switching between sinks and like to redirect all my text outputting (not only logging) to `spdlog`. Is it possible to output raw string data (without the logging related information) as well?

**Comment by gabime** [comment]
Not sure i understand. Could you provide an example?

**Comment by matt77hias** [comment]
Just normal text (potentially containing '\n' and '\r' characters) without the prefix of the _pattern_ (e.g., `[21:18:34] [T] [thread 18516]`) (without having to toggle it on and off using `set_pattern`).

```
Engine version 1.0.0 of Sep  1 2019 at 11:02:17
Copyright (c) 2016-2019 Matthias Moulin.

[21:18:34] [T] [thread 18516] This is a trace message.
[21:18:34] [D] [thread 18516] This is a debug message.
[21:18:34] [I] [thread 18516] This is an info message.
[21:18:34] [W] [thread 18516] This is a warning message.
[21:18:34] [E] [thread 18516] This is an error message.
[21:18:34] [C] [thread 18516] This is a fatal message.

Task 1: [++++++++++++++++++++++++++++++++++++++++]  (0.3s)
Task 2: [+++++++++++++++++++++++++++             ]  (0.3s | 0.5s)
```

**Comment by gabime** [comment]
> without having to toggle it on and off using set_pattern

No, I don't think there is a way
