### ISSUE TITLE
Build failed on raspberry PI 3

### ISSUE THREAD

**Issue by andre237** [gabime/spdlog#1209]
I've followed the steps to build the library using cmake. Everything went fine throughout the build process, however, when I tried to add the necessary headers to my project, it kept saying the files could not be found. Here's the CMakeLists for my project:

cmake_minimum_required(VERSION 3.13)
project(LoggerTests CXX)

set(CMAKE_CXX_STANDARD 17)

add_executable(LoggerTests main.cpp)

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
target_link_libraries(${PROJECT_NAME} Threads::Threads)

find_package(spdlog REQUIRED)
target_link_libraries(${PROJECT_NAME} spdlog::spdlog)

Note: I've done the exact same thing in my local computer (Ubuntu 18.04) and it works great. Guess my problem resides on the raspberry

Any help would be appreciated!

**Comment by tt4g** [comment]
Is spdlog installed with CMake?
If you don't, you won't be able to find header files with `find_package(spdlog REQUIRED)`.

**Comment by andre237** [comment]
Yes, I built it just as the README says

**Comment by tt4g** [comment]
Can you provide an error log because I don't know why CMake failed?

**Comment by andre237** [comment]
Actually, I can't. I'll point some more details about my project's environment. I'm using CLion IDE with a toolchain for cross-compilation to my raspberry. When I reload the CMake , it goes fine and prints the usual cmake success message. However, when I include <spdlog/spdlog.h> at main.cpp, the IDE marks it as not found. I even tried to compile (thought it might be some IDE issue) but it keeps saying the header could not be found. I guess the static lib version is not actually installed in the raspberry, that's way I can't find it.

**Comment by tt4g** [comment]
Try adding the following debug code to `CMakeLists.txt`.

```diff
find_package(spdlog REQUIRED)
target_link_libraries(${PROJECT_NAME} spdlog::spdlog)

+ get_target_property(DEBUG_SPDLOG_INCLUDE_DIR spdlog::spdlog INTERFACE_INCLUDE_DIRECTORIES)
+ message("DEBUG_SPDLOG_INCLUDE_DIR: ${DEBUG_SPDLOG_INCLUDE_DIR}")
```

The include directory of `spdlog :: spdlog` is output to the message.

Is that path as you expected?

**Comment by andre237** [comment]
It printed: /usr/include. Guess that's what I expected. Mysteriously, I compiled my project, ignoring the fact the IDE kept saying it could not find the header, and it WORKED. Don't know what could it be, maybe the whole issue is within the toolchain, but can't affirm that

**Comment by tt4g** [comment]
I think it is an IDE problem.
Maybe CMake and IDE are not working well.

**Comment by andre237** [comment]
Fixed. It really was an IDE issue. After a bit of a search, I found that the IDE must be explicitly resynced with the remote host. Thanks for your help anyway
