### ISSUE TITLE
Match runtime log level of default logger with the compile time SPDLOG_ACTIVE_LEVEL

### ISSUE THREAD

**Issue by Jerry-Ma** [gabime/spdlog#1211]
Hi,

I was wondering if it makes sense to set the default log level to SPDLOG_ACTIVE_LEVEL. Currently, the default runtime log level is always `info`, which surprised me when I was changing around SPDLOG_ACTIVE_LEVEL from cmake target definitions but saw no effect. (I later realized that the runtime level was always info and I was setting SPDLOG_ACTIVE_LEVEL from TRACE to DEBUG).

**Comment by gabime** [comment]
It only affects the macros (SPDLOG_DEBUG(), SPDLOG_INFO() etc.).

**Comment by Jerry-Ma** [comment]
I was only using these default loggers in my current project right now, so I am doing this at the beginning of main:

```
spdlog::set_level(
        static_cast<spdlog::level::level_enum>(SPDLOG_ACTIVE_LEVEL));
```

The issue is not a big deal, but I guess it would make sense to make this the default.

**Comment by gabime** [comment]
In previous versions of spdlog it did this, but since spdlog now compiles to a library, it can be confusing to have closed binary lib with un expected default log level.

**Comment by Jerry-Ma** [comment]
I see. Thanks for the explanation.
