### ISSUE TITLE
Having 2 stdout loggers?

### ISSUE THREAD

**Issue by maxdymond** [gabime/spdlog#1212]
I'm currently migrating from the 0.16 spdlog to the 1.3.1 spdlog, and my code broke because I'm basically doing this:

```
    auto stdout_sink = std::make_shared<spdlog::sinks::stdout_sink_mt>();

    auto logger = std::make_shared<spdlog::logger>(LOGGER1, stdout_sink);

    logger->set_formatter(make_my_custom_formatter());
    logger->set_level(spdlog::level::debug);
    spdlog::register_logger(logger);

    // Create a logger which just logs out the logged message
    auto logger2 =
                 std::make_shared<spdlog::logger>(LOGGER2, stdout_sink);
    logger2->set_pattern("%v");
    spdlog::register_logger(logger2);
```
As far as I can tell, between 0.16 and 1.3.1 the formatter is now set on the sink, which means that the `set_pattern` on the second logger overrides the first logger's set_formatter.

Does this mean that sinks cannot be shared now? It seems weird to have 2 stdout sinks - the whole point about having one is that it's guarded with a mutex, so you don't get interleaved output.

**Comment by gabime** [comment]
> - the whole point about having one is that it's guarded with a mutex, so you don't get interleaved output.

Its fine- all stdout/stderr/color sinks share same global console mutex

**Comment by maxdymond** [comment]
Ok, thanks!
