### ISSUE TITLE
Please release 1.3.2 before changing fmt version

### ISSUE THREAD

**Issue by LuisAyuso** [gabime/spdlog#1217]
We have a large development that uses fmt and spdlog. Unfortunately, the CMake flag to use external fmtlib with imported targets is only available in branch 1.x. 
I would really like to bind my development to a release instead of a branch, but the feature as not yet been released and latest fmtlib changes have created quite a hullabaloo over here.

**Comment by gabime** [comment]
When 1.4.0 releases, the external fmt option will be included so you can specify a different fmt version.
