### ISSUE TITLE
How can I change the default logger .txt encoding ? (Windows)

### ISSUE THREAD

**Issue by vajos** [gabime/spdlog#1218]
Im not sure if questions like this are allowed at github but i saw the label question so i guess its fine if not remove this post.

For example This Logger or any other logger.

    //Create Logger
		try
		{
			auto daily_logger = spdlog::daily_logger_mt("logger", "C:\\Log\\ErrorHands.txt", 12, 00);
			daily_logger->set_pattern("%v");
		}
		catch (const spdlog::spdlog_ex& ex)
		{
			fmt::print("Error:  {0}\n", ex.what());
		}

Saves the txt file as ANSI under windows I want to change the default to UTF-8. Is there an option for this?

**Comment by tt4g** [comment]
The first thing to know is that computers represent characters with character codes and character encodings.
The character code is just a byte. Character encoding is information that links characters that humans read and write with character codes.

Unfortunately, C ++ defines `char` and` wchar_t` corresponding to character codes, but does not define a type that represents character encoding (there is a plan to add `char8_t` that represents UTF-8 character code in C ++ 20.).

In other words, even if you save `char` or` wchar_t` in C ++ as a text file, only the character code is saved. The character encoding is not saved in the file.

However, methods other than C ++ (e.g. `vi`) do not store information about character encoding in text files.
Most systems display characters by inferring the character encoding from the character code.

Perhaps only the ANSI code is stored in the file you opened.
In that state, the character code in the file is assumed to be ANSI by the system.
UTF-8 is compatible with ANSI code, so it is no mistake.

**Comment by vajos** [comment]
Hmmm okay I assume this is a no as an answer regarding spdlog.
For the rest the more i read about encoding the more confused I became, all I know is changing my .txt file to UTF-8 fixes encoding problems for libpqxx library where the database is also set to UTF-8, thats why I was asking. 


Thanks anyways!

**Comment by gabime** [comment]
@vajos actually spdlog supports utf8. you need to define SPDLOG_WCHAR_TO_UTF8_SUPPORT before including/compiling spdlog and use L””(wchar) when logging.
