### ISSUE TITLE
Formatter "%i" outputs huge numbers

### ISSUE THREAD

**Issue by josefschroettle** [gabime/spdlog#1219]
When using formatter "%i" (time to last message) the output are sometimes huge numbers.
Please see the following output with formatter "%i;%Y.%m.%d %H:%M:%S.%f;%v"
**18446744073709551604**;2019.09.10 14:05:10.653383;...
000056;2019.09.10 14:05:10.653439;...
000001;2019.09.10 14:05:10.653445;...
**18446744073709551612**;2019.09.10 14:05:10.653441;...
000007;2019.09.10 14:05:10.653448;...
The time delta is sometimes negative and then printed as a very large integer
The lines
    void format(const details::log_msg &msg, const std::tm &, memory_buf_t &dest) override
    {
        auto delta = msg.time - last_message_time_;
#ifdef FIX_FOR_NEGATIVE_TIME
        if (delta < decltype(delta)::zero())
            delta = decltype(delta)::zero();
#endif
        auto delta_units = std::chrono::duration_cast<DurationUnits>(delta);
        last_message_time_ = msg.time;
       ...
    }
in 'elapsed_formatter' in pattern_formatter-inl.h fix that.

**Comment by gabime** [comment]
Fixed. Thanks For reporting!
