### ISSUE TITLE
Consider reader/writer locks for the registry

### ISSUE THREAD

**Issue by gregoire-astruc** [gabime/spdlog#122]
R/W locks allow readers not to block each other.
If you're looking at performance, this should help.

I don't know if there are other places where this would be applicable.

**Comment by rpopescu** [comment]
Considering the discussion in #87 and the very good point you brought up, I think it's hardly worth the extra complexity of a rw lock, don't you?
Just look it up and keep it around.
Performance would be improved only if one had a tight loop where the logger would be retrieved by name, but that's a silly thing to do to begin with.

**Comment by gabime** [comment]
I agree with @rpopescu . I am not sure it worth the effort and complexity.

**Comment by gregoire-astruc** [comment]
Yeah, I thought there might be other places too but it appears not :)

**Comment by rpopescu** [comment]
This should probably be closed, right @gregoire-astruc ?
