### ISSUE TITLE
SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE Build fails

### ISSUE THREAD

**Issue by LinaSchad** [gabime/spdlog#1220]
When the SPDLOG_ACTIVE_LEVEL is set to debug, or any other level to be specific, the build runs without a problem. Is it set to SPDLOG_LEVEL_TRACE though the build fails. The occurring error is:
C2338: Mismatch between char-types of context and argument in core.h line 763

The build failure happens when using spdlog as header-only and compiled with Visual Studio 16.2.4.

[spdlog error.txt](https://github.com/gabime/spdlog/files/3595577/spdlog.error.txt)

**Comment by gabime** [comment]
Are you trying to log wchar strings ? Please provide an example to reproduce the problem
