### ISSUE TITLE
macro to log to a custom logger?

### ISSUE THREAD

**Issue by mike239x** [gabime/spdlog#1222]
Hi, if I understand correctly, to log with `file:line` reference one has to use `SPDLOG_INFO` macro (or a similar one with `_ERROR` etc). This however logs to the default logger. How do I log with `file:line` to a custom logger?

I looked through the code and found `SPDLOG_LOGGER_INFO` macro, which I think does exactly what I want, but I found no mention of it in the Wiki...

**Comment by gabime** [comment]
> I looked through the code and found SPDLOG_LOGGER_INFO macro, which I think does exactly what I want, but I found no mention of it in the Wiki...

Yes. This is the way to achieve that. Wiki should be updated..
