### ISSUE TITLE
Enhancement suggestion: output of UTF-8 BOM into rotating_file_sink file to make logs natively supporting Unicode viewing

### ISSUE THREAD

**Issue by martinjansa** [gabime/spdlog#1225]
Hi,

Firstly, thank you for a great library! :-)

We are using it for storing the logging information using the UTF-8 format, but sometimes the tools we are using (on Windows) for viewing the logs don't show the specific characters correctly, when the UTF-8 encoding is not recognized or manually set. It would be very helpfull, if the log file could contain a 3-byte UTF-8 identifier (BOM), that would suggest the tools the encoding of the content.

@gabime, would this be something you could be willing to include into your repo? If so, I would be willing to contribute in getting it done.

So far, I've made a fork of your repo and implemented this functionality into a branch and verified everything works fine. As you can see at https://github.com/martinjansa/spdlog/commit/ff5495ee2bc2d925c4907f951db2472b95c2fc9c, the interface is fully backwards compatible. 

Is it going the right way? If so, how shall we proceed further?

Thank you,

Martin

**Comment by gabime** [comment]
Hi, 
Thanks for the nice feedback :+1: 

There are numerous requests regarding adding something automatically at the start of each file (e.g.  adding speacial header line on start of each new file).

This is why I try to come up with an API or some config struct for all file sinks.

Something like:

```c++
sink->after_open(std::funcion<void (FILE* fd)> callback_fun);

//And maybe
sink->before_close(std::funcion<void (FILE* fd)> callback_fun);

// And even maybe
sink->after_close(std::funcion<void (std::string& filename)> callback_fun);
```

Of course, any help on formalizing such API would be appreciated

**Comment by martinjansa** [comment]
Perfect, sounds great. I'll then wait for the <config> support to come out and use it for this purpose. Please, let me know, if there's anything I could help in that.

**Comment by m4ce** [comment]
@gabime, I think the API spec you put down works really well. The `after_rotate` is exactly what I am looking for in #1181.

**Comment by gabime** [comment]
spdlog now provides an option to get callbacks before/after a log file is created/closed.

```cpp
    // pass the spdlog::file_event_handlers to file sinks for open/close log file notifications
    spdlog::file_event_handlers handlers;
    handlers.before_open = [](spdlog::filename_t filename) { spdlog::info("Before opening {}", filename); };
    handlers.after_open = [](spdlog::filename_t filename, std::FILE *fstream) {
        spdlog::info("After opening {}", filename);
        fputs("After opening\n", fstream);
    };
    handlers.before_close = [](spdlog::filename_t filename, std::FILE *fstream) {
        spdlog::info("Before closing {}", filename);
        fputs("Before closing\n", fstream);
    };
    handlers.after_close = [](spdlog::filename_t filename) { spdlog::info("After closing {}", filename); };
    auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("logs/events-sample.txt", true, handlers);
    spdlog::logger my_logger("some_logger", file_sink);
    my_logger.info("Some log line");
```
