### ISSUE TITLE
Misusing spdlog

### ISSUE THREAD

**Issue by julio77it** [gabime/spdlog#1226]
Hi,

I've included in projects spdlog from this repo : spdlog/1.3.1@bincrafters/stable

I've written below a sample of the "problem" I have.
Does macro SPDLOG_LOGGER_* not rely on spdlog::set_level for their log level ?
Are there another way to automatic inclusion of __FILE__, __LINE__ on  every log line ?

Thanks for the attention,
Regards
Giulio

// Without the line below, SPDLOG_LOGGER_DEBUG macros don't log
//#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
#include <spdlog/spdlog.h>
#include "spdlog/sinks/stdout_color_sinks.h"

int main()
{
    spdlog::set_level(spdlog::level::debug);
    spdlog::debug("Some debug message 0");

    std::shared_ptr<spdlog::logger> stdout_logger = spdlog::stdout_color_mt("stdout_logger");
    stdout_logger->set_pattern("%Y/%m/%d %T.%e | %l | %t | %n | %s:%# | %v");
    stdout_logger->debug("Some debug message 1");
    spdlog::set_default_logger(stdout_logger);      
    spdlog::set_level(spdlog::level::debug);

    spdlog::debug("Some debug message 2");

    SPDLOG_DEBUG("Some debug message {}", 3);
    SPDLOG_LOGGER_DEBUG(stdout_logger, "Some debug message {}", 4);
    SPDLOG_LOGGER_INFO(stdout_logger, "Some info message {}", 1);
    SPDLOG_INFO("Some info message {}", 2);
}

**Comment by gabime** [comment]
> Does macro SPDLOG_LOGGER_* not rely on spdlog::set_level for their log level ?

No, this is defined at compile time. 

> Are there another way to automatic inclusion of FILE, LINE on every log line ?

Using macros is the recommended way to include FILE LINE conveniently.

If you insist not using macros you can try:

```c++
logger->log(spdlog::source_loc{__FILE__, __LINE__, __FUNCTION__, spdlog::level::info,  "Some log message {}", 1234);
```

**Comment by julio77it** [comment]
I've used macro everywhere in my project but I usually need to dinamically change level

**Comment by gabime** [comment]
Then you can  #define the active level to SPDLOG_LEVEL_TRACE at compile time, and change dynamically at runtime using set_level().

**Comment by julio77it** [comment]
Ok, I got it, now I've fixed everything.

Thanks for the patience and for spdlog.

Giulio
