### ISSUE TITLE
The serial number is in the wrong order

### ISSUE THREAD

**Issue by 13272438611** [gabime/spdlog#1230]
hi,
  I Changed the async_example() code as follows：
  spdlog::init_thread_pool(32768, 1);  ->  spdlog::init_thread_pool(32768, 4)；
  and found that "Async message" of i is in the wrong order.

**Comment by gabime** [comment]
That's expected. There are multiple threads writing to same destiniy

**Comment by 13272438611** [comment]
Thank you for your response, but is there any way to fix it?

**Comment by 13272438611** [comment]
Is there any way to use multiple threads and make sure the serial number is in the wrong order?

**Comment by 13272438611** [comment]
> That's expected. There are multiple threads writing to same target

Thank you for your response, but is there any way to use multiple threads and make sure the serial number is in the right order?
