### ISSUE TITLE
[*** LOG ERROR ***] string pointer is null

### ISSUE THREAD

**Issue by sfindeisen** [gabime/spdlog#1232]
This occurs every 70 minutes in our busy log:

```
[*** LOG ERROR ***] [2019-07-22 21:33:26] [app-xxx] string pointer is null
```

(The timestamps do differ, of course.) Have you seen this before?

**Comment by gabime** [comment]
seems you pass null pointer instead of valid const char* in one of the logging statements

**Comment by sfindeisen** [comment]
Well, that would be simple. Are you sure? We have examined all of our log statements, but couldn't spot it. Will search again...

**Comment by gabime** [comment]
pretty much. it comes straight from fmt then it encounters a null pointer - https://github.com/gabime/spdlog/blob/31020f9eea1fd212b354546cf8c703a0176a300b/include/spdlog/fmt/bundled/format.h#L1750

**Comment by gabime** [comment]
@sfindeisen Any news about it?

**Comment by sfindeisen** [comment]
Yep it was a NP on our side.
