### ISSUE TITLE
Enhancement suggestion : Add category logger.

### ISSUE THREAD

**Issue by tsubasakusaka** [gabime/spdlog#1235]
Thank you for such a great logger.

Could you consider to add capability to add a categorical logging feature like log4j ?
I think It will be helpful for many people maybe.

For example, I want to add two additional logger bellow,
- class category_logger : public logger
- class category_async_logger : public async_logger

both logger have two additional property simply.

```
std::share_ptr<logger> parent_ : 
bool isAdditive_;
```

And we override sink_it_(), flush_() and clone().

But some issues are there to implement :
- We cannot inherit async_logger because that is final class.
- In sink_it_() implementation, the timestamp is slightly changed to pass to parent logger because log() method recreate timestamp. That is not same to original.

```
void sink_it_(spdlog::details::log_msg& msg) override
{
	// sink to local sinks;
	logger::sink_it_(msg); // or async_logger::sink_it_();

	// delegate to parent.
	if (isAdditive_ && parent_ != nullptr) {
		/*
		* Issue: timestamp is changed in parent.
		* Suggestion: we can call: Logger_->log(msg);
		*/
		parent_->log(msg.level, msg.payload);
	}
}
```
Summary:
- Could you consider async_logger can be inherit.
  -  Remove final directive from async_logger .
  -  Add virtual directive to clone() , sink_it_() and flush_().
  -  Change visibility of  thread_pool_ and overflow_policy_ from private to protected

- Could you consider to add  public:  void log(details::log_msg &msg) method to logger and async_logger.

Best regards.

**Comment by gabime** [comment]
Thanks for the suggestions. However I deliberately avoid this feature for simplicity reasons. It can be easily worked around without doing complex logger hierarchies

**Comment by tsubasakusaka** [comment]
Dear Gabime,
Thank you for your reply.
I understand your intention. 
However If possible, could you consider just to add inherit capability to async_logger ?
I think it does not destroy simplicity.
Best regards.
