### ISSUE TITLE
Please add a pkgconfig file.

### ISSUE THREAD

**Issue by orbea** [gabime/spdlog#1237]
In the update from `1.3.1` to `1.4.0` spdlog lost its pkgconfig file and this breaks the configure process for some programs that use spdlog as a dependency. It would be great if it could get added back.

For example with `libixion-0.15.0`.
```
checking for SPDLOG... no
configure: error: Package requirements (spdlog >= 0.16.0) were not met:

Package 'spdlog', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SPDLOG_CFLAGS
and SPDLOG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by gabime** [comment]
I just didn't have time to deal with this. PRs are welcome

**Comment by orbea** [comment]
@gabime I'll give it a try, but what is the correct linking flag for the spdlog library?
