### ISSUE TITLE
 Overwriting log

### ISSUE THREAD

**Issue by galek** [gabime/spdlog#124]
For overwriting log-file do replace in constructor of rotating_file_sink (for rotating_logger_mt)
_file_helper.open(calc_filename(_base_filename, 0, _extension),);
On:
_file_helper.open(calc_filename(_base_filename, 0, _extension), true);

**Comment by gabime** [comment]
This is by design in rotating files

**Comment by galek** [comment]
Is possible implement flag for disable appending to end of file? - It's not best solution for me( I have own log-backup system).

Or how implement logging without appending?

**Comment by gabime** [comment]
I will consider but you can always implement your own sink pretty essily
