### ISSUE TITLE
wstring_view_t not defined with SPDLOG_WCHAR_FILENAMES

### ISSUE THREAD

**Issue by isanae** [gabime/spdlog#1249]
Commit 3bcd3cef2f4a7bfd2faab88f9871560f1e73f690 changed [the `#if` in `os.h`](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/details/os.h#L88) to include `SPDLOG_WCHAR_FILENAMES`, but [`wstring_view_t` in `common.h`](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/common.h#L106) is only defined for `SPDLOG_WCHAR_TO_UTF8_SUPPORT`.

**Comment by gabime** [comment]
Fixed. Thanks for reporting
