### ISSUE TITLE
stderr_color_sink_mt throws without a console

### ISSUE THREAD

**Issue by isanae** [gabime/spdlog#1250]
Commit c138685364f8a7124e4b90f4a9bf9b3dd99f3b7a introduced a workaround for redirected handles by using `WriteFile()` instead of `WriteConsole()`. The [new code in `wincolor_sink-inl.h`](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/wincolor_sink-inl.h#L152) _throws_ if `WriteFile()` fails, although the old `WriteConsole()` still doesn't.

This broke our logging because we don't usually start a console, except in rare cases. Console logs used to be discarded silently, but now they throw. It's even worse because we're actually using a `dist_sink` and the console sink is the first one. Since `dist_sink` doesn't catch anything, _all_ logging now fails.

The main problem is that if `GetConsoleMode()` returns false, spdlog assumes that `out_handle_` is a valid file handle. I would add a check for a null handle in `write_to_file_()` (and possibly `print_range_()`) to avoid throwing or even trying to write to it.

I'm also wondering whether `dist_sink` should catch exceptions to allow the other sinks to do their work, but I'm not sure about that.

**Comment by gabime** [comment]
Fixed. Thanks for reporting
