### ISSUE TITLE
Cannot compile using VS2013

### ISSUE THREAD

**Issue by rusvid** [gabime/spdlog#1255]
I used spdlog 1.0.0 and it was compiled without problems. Updated spdlog to 1.4.2 and got many errors:

> Error	50	error C1903: unable to recover from previous error(s); stopping compilation	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	769
> Error	63	error C1903: unable to recover from previous error(s); stopping compilation	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	422
> Error	10	error C2039: 'type' : is not a member of '`global namespace''	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	417
> Error	60	error C2039: 'type' : is not a member of '`global namespace''	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	417
> Error	29	error C2059: syntax error : ','	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	660
> Error	15	error C2061: syntax error : identifier 'basic_parse_context'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	474
> Error	16	error C2061: syntax error : identifier 'basic_parse_context'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	475
> Error	34	error C2061: syntax error : identifier 'basic_parse_context'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	679
> Error	38	error C2061: syntax error : identifier 'basic_parse_context'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	736
> Error	37	error C2061: syntax error : identifier 'basic_string_view'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	713
> Error	9	error C2061: syntax error : identifier 'char_t_impl'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	417
> Error	59	error C2061: syntax error : identifier 'char_t_impl'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	417
> Error	39	error C2061: syntax error : identifier 'conditional_t'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	750
> Error	40	error C2061: syntax error : identifier 'conditional_t'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	751
> Error	49	error C2061: syntax error : identifier 'enable_if_t'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	769
> Error	36	error C2061: syntax error : identifier 'parse_context'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	681
> Error	20	error C2062: type 'char' unexpected	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	477
> Error	24	error C2062: type 'wchar_t' unexpected	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	478
> Error	19	error C2065: 'basic_parse_context' : undeclared identifier	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	477
> Error	23	error C2065: 'basic_parse_context' : undeclared identifier	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	478
> Error	26	error C2065: 'basic_string_view' : undeclared identifier	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	660
> Error	5	error C2079: 'fmt::v6::to_string_view' uses undefined class 'fmt::v6::basic_string_view<S::char_type>'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	388
> Error	55	error C2079: 'fmt::v6::to_string_view' uses undefined class 'fmt::v6::basic_string_view<S::char_type>'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	388
> Error	4	error C2143: syntax error : missing ',' before '&'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	386
> Error	54	error C2143: syntax error : missing ',' before '&'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	386
> Error	25	error C2143: syntax error : missing ',' before '<'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	492
> Error	28	error C2143: syntax error : missing ';' before ','	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	660
> Error	13	error C2143: syntax error : missing ';' before '{'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	422
> Error	31	error C2143: syntax error : missing ';' before '{'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	660
> Error	2	error C2143: syntax error : missing ';' before '<template-id>'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	386
> Error	52	error C2143: syntax error : missing ';' before '<template-id>'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	386
> Error	17	error C2144: syntax error : 'int' should be preceded by ';'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	477
> Error	21	error C2144: syntax error : 'int' should be preceded by ';'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	478
> Error	41	error C2146: syntax error : missing ';' before identifier 'map'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	763
> Error	45	error C2146: syntax error : missing ';' before identifier 'map'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	764
> Error	30	error C2226: syntax error : unexpected type 'std::integral_constant<fmt::internal::type,string_type>'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	660
> Error	35	error C2238: unexpected token(s) preceding ';'	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	679
> Error	42	error C2433: 'fmt::internal::arg_mapper<Context>::long_type' : 'inline' not permitted on data declarations	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	763
> Error	46	error C2433: 'fmt::internal::arg_mapper<Context>::ulong_type' : 'inline' not permitted on data declarations	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	764
> Error	7	error C2447: '{' : missing function header (old-style formal list?)	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	409
> Error	14	error C2447: '{' : missing function header (old-style formal list?)	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	422
> Error	32	error C2447: '{' : missing function header (old-style formal list?)	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	660
> Error	57	error C2447: '{' : missing function header (old-style formal list?)	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	409
> Error	12	error C2631: 'basic_parse_context' : a class or enum cannot be defined in an alias template	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	422
> Error	62	error C2631: 'basic_parse_context' : a class or enum cannot be defined in an alias template	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	422
> Error	8	error C2653: 'internal' : is not a class or namespace name	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	417
> Error	11	error C2653: 'internal' : is not a class or namespace name	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	421
> Error	58	error C2653: 'internal' : is not a class or namespace name	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	417
> Error	61	error C2653: 'internal' : is not a class or namespace name	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	421
> Error	18	error C2873: 'parse_context' : symbol cannot be used in a using-declaration	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	477
> Error	22	error C2873: 'wparse_context' : symbol cannot be used in a using-declaration	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	478
> Error	27	error C2976: 'fmt::internal::type_constant' : too few template arguments	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	660
> Error	33	error C2976: 'fmt::internal::type_constant' : too few template arguments	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	661
> Error	3	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	386
> Error	43	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	763
> Error	47	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	764
> Error	53	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	e:\projects\egrlib\src\egrlib\spdlog\fmt\bundled\core.h	386
> 	65	IntelliSense: expected a ';'	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\core.h	477
> 	67	IntelliSense: expected a ';'	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\core.h	478
> 	69	IntelliSense: expected a ';'	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\format.h	2599
> 	71	IntelliSense: expected a ';'	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\format.h	2600
> 	64	IntelliSense: identifier "parse_context" is undefined	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\core.h	477
> 	66	IntelliSense: identifier "wparse_context" is undefined	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\core.h	478
> 	68	IntelliSense: identifier "writer" is undefined	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\format.h	2599
> 	70	IntelliSense: identifier "wwriter" is undefined	e:\projects\egrlib\SRC\egrlib\spdlog\fmt\bundled\format.h	2600
>

**Comment by tt4g** [comment]
It seems that the fmt library has not been compiled.
As far as I know, fmt requires the latest version of MSVC 2013 (Update 5 18.0.40629.0).

Check your MSVC version macro `_MSC_FULL_VER`. and please check this issue: #1141

**Comment by rusvid** [comment]
I have the latest MSVS 2013.
From about:

> Microsoft Visual Studio Professional 2013
> Version 12.0.40629.00 Update 5

From cmd:

> C:\Program Files (x86)\Microsoft Visual Studio 12.0>cl.exe /?
> Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86

**Comment by tt4g** [comment]
It may be the effect that the version has bumped fmt to version 6.0.0.

All compilation error messages indicate the source of fmt, so it is better to create an issue with the fmt project.

Another solution is define `SPDLOG_FMT_EXTERNAL`. Next, use a version of fmt that can be compiled with MSVC 2013.
