### ISSUE TITLE
Make _log_if_enabled public.

### ISSUE THREAD

**Issue by Kentzo** [gabime/spdlog#126]
Often in CLI verbosity is specified via some option. It would be convenient if spdlog had a method to specify level directly.

**Comment by gabime** [comment]
Not sure i understand. Could you give an example?

**Comment by Kentzo** [comment]
Right now I'm writing a wrapper function that does some extract actions in addition to logging. Among other arguments it accepts level of the log (which is `spdlog::level::level_enum`). Right now I have to use switch and get line_logger by name (debug, info, error etc). If I'd have a function to get appropriate line_logger by level, it would make my life easier.

**Comment by gabime** [comment]
Why not must copy paste the implemtation of log_if_enabled ? It is just 3 lines

**Comment by Kentzo** [comment]
@gabime That's an option for sure, but it breaks encapsulation, doesn't it?

**Comment by gabime** [comment]
Maybe, but making the function public breaks it as well :)

**Comment by Kentzo** [comment]
Why is it private in the first place? Most libraries I've seen has such function public. E.g. [glib](https://developer.gnome.org/glib/stable/glib-Message-Logging.html#g-log)

**Comment by gabime** [comment]
It just factory for the internal line logger. I didnt think anyone would use it directly. How do you use it anyway?
