### ISSUE TITLE
Documentation: Incorrect spdlog version claimed

### ISSUE THREAD

**Issue by vchekan** [gabime/spdlog#1260]
`README.md` clains that minimal spdlog version is 0.11.0, but code depends on `#include "spdlog/sinks/basic_file_sink.h"` which appears in spdlog `1.0.0` for the first time.

Should minimal spdlog version be corrected in README to be 1.0.0.?

**Comment by gabime** [comment]
where does it say that? cant find

**Comment by vchekan** [comment]
Oh, this comment was intended for Decave/JCoz which use spdlog. Wrong window :)
