### ISSUE TITLE
Generate tweakme.h from CMake

### ISSUE THREAD

**Issue by chulup** [gabime/spdlog#1263]
I install spdlog as static library through Conan with several options like SPDLOG_WCHAR_FILENAMES. In the end, I have static lib compiled with SPDLOG_WCHAR_FILENAMES but I have to define it again for my code to know that fact.

Is there a way to modify already existing tweakme.h when options put there were already provided to CMake during initial install? That way any code using the same Spdlog installation will be using the same set of compiler definitions automatically.

**Comment by tt4g** [comment]
> I install spdlog as static library through Conan with several options like SPDLOG_WCHAR_FILENAMES. In the end, I have static lib compiled with SPDLOG_WCHAR_FILENAMES but I have to define it again for my code to know that fact.

[conan-io/cmake-conan](https://github.com/conan-io/cmake-conan) will help if you use CMake and conan.

When you link the CMake target provided using conan's CMake generator to your application, the macros added by conan to spdlog are automatically added to your build options: https://github.com/bincrafters/conan-spdlog/blob/stable/1.4.1/conanfile.py#L88-L101

It is recommended that you also read the following documents:

* [cmake generator — conan 1\.19\.1 documentation](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html)
* [cmake — conan 1\.19\.1 documentation](https://docs.conan.io/en/latest/reference/generators/cmake.html#cmake-generator)
> Is there a way to modify already existing tweakme.h when options put there were already provided to CMake during initial install? That way any code using the same Spdlog installation will be using the same set of compiler definitions automatically.

Installed libraries are used by multiple projects.
If tweakme.h is changed, installation will be required for each project, so I cannot answer whether tweakme.h should be changed.

**Comment by chulup** [comment]
> [conan-io/cmake-conan](https://github.com/conan-io/cmake-conan) will help if you use CMake and conan.
> 
> When you link the CMake target provided using conan's CMake generator to your application, the macros added by conan to spdlog are automatically added to your build options: https://github.com/bincrafters/conan-spdlog/blob/stable/1.4.1/conanfile.py#L88-L101
> 
> It is recommended that you also read the following documents:
> 
>     * [cmake generator — conan 1.19.1 documentation](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html)
> 
>     * [cmake — conan 1.19.1 documentation](https://docs.conan.io/en/latest/reference/generators/cmake.html#cmake-generator)

Thanks, I know it.
I tried to explain something else: all the info about defines is lost right after static library compilation.

The problem is gone if I use  header_only option - no static library is compiled, I just provide some set of defines and everything's good.

Conan tries to use install scripts provided by the projects, and if CMake for spdlog provides option to compile static lib with some defines and does not save those defines somewhere, that information is lost for spdlog users.

> > Is there a way to modify already existing tweakme.h when options put there were already provided to CMake during initial install? That way any code using the same Spdlog installation will be using the same set of compiler definitions automatically.
> 
> Installed libraries are used by multiple projects.
> If tweakme.h is changed, installation will be required for each project, so I cannot answer whether tweakme.h should be changed.

Conan installs the library in such a way every set of settings and options generates a separate installation. New package will be created when some project needs specific options for spdlog. 

That means all projects requiring the same defines could set options in their conanfile.py to use the same package. And if CMake install script saves defines it knows about into tweakme.h then projects won't need to repeat the same defines in their own build scripts: it's all in tweakme.h already.


Sorry if my initial question was not properly explained.

**Comment by tt4g** [comment]
Is it a suggestion for Conan's spdlog recipe?

If so, it is managed by [bincrafters/conan\-spdlog](https://github.com/bincrafters/conan-spdlog). And suggestions for improvements are accepted in [bincrafters/community](https://github.com/bincrafters/community).

Please know that English is not my native language, and I may have misread your comment.

**Comment by tt4g** [comment]
I may have understood what you need.

Is it a suggestion for a macro definition that exists in tweakme.h and the CMake variable of the same name is not defined in CMakeLists.txt, but is referenced in the source file?

For example, the `SPDLOG_NO_DATETIME` macro is not defined in CMakeLists.txt, but it is certainly used for static builds.
This macro is not recorded anywhere if the user specifies `cmake -G" ... "-DSPDLOG_NO_DATETIME`.

If this information is lost, there may be problems with binary compatibility.

Sorry, I may have been distracted by Conan and CMake and took time to realize the meaning of your proposal.

**Comment by gabime** [comment]
The most important defines from tweakme are already supported. what define are you missing?

**Comment by chulup** [comment]
@gabime 
That's not a question of missing defines. My use case look like that:

1. I install spdlog using Conan. "wchar_filenames=True" and "header_only=False" are specified, which force CMake to build spdlog into static library with SPDLOG_WCHAR_FILENAMES defined

2 now. I use installed previously spdlog in my project. Now no one but me as a programmer knows that static library for spdlog was built using SPDLOG_WCHAR_FILENAMES, so I have to define it in my build system again.

2 as I want it. CMake on step 1 saved SPDLOG_WCHAR_FILENAMES into "tweakme.h" and now it's enough for me to include <spdlog/spdlog.h> into my code, the define is already there.

**Comment by gabime** [comment]
sounds like a problem of the conan pakckage, not spdlog’s.
if you skip conan and install spdlog directly it works as expected:

```console
cmake ..
make install
 ```
And then in your project’s CMakeLists.txt ``` find_package(spdlog REQUIRED)``` will set the right defines. 
Also, since version 1.4.2, you can use pkg- config to find the right cflags

**Comment by chulup** [comment]
Here's the thing, I do not use CMake right now so I can't use CMake-only options in my projects. 
Why would there be "tweakme.h" then if one is supposed to use CMake build system for defines?

Conan is just another layer of abstraction here. I can directly install spdlog using CMake but include/link everything manually and the build would be broken just the same.

**Comment by gabime** [comment]
tweakme is not the recommended when using cmake/ conan.
Please open an issue in conan so the fix the missing flags.

**Comment by chulup** [comment]
At the end that was found to be local issue as usual. Conan package for spdlog already saves those defines in .props file generated for MS VS project.

Thanks for a great library!
