### ISSUE TITLE
Setting SPDLOG_ACTIVE_LEVEL to SPDLOG_LEVEL_DEBUG or SPDLOG_LEVEL_TRACE has no effect

### ISSUE THREAD

**Issue by Jesse-Bakker** [gabime/spdlog#1267]
The program

    #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
    #include <spdlog/spdlog.h>
    
    int main() {
        SPDLOG_DEBUG("Test");
        return 0;
    }

will not log anything.
Setting the level to a value higher than the default (INFO) will restrict the log level, but setting it to a lower value will not loosen it.

Tested with clang++ 9.0.0 and g++ 9.2.0, spdlog version 1.4.2 and HEAD

**Comment by gabime** [comment]
SPDLOG_ACTIVE_LEVEL does not change the global log level. It just replaces the relevant macros with empty/real statements at compile time.

The default level is info. Call ```spdlog::set_level(spdlog::level::debug)`` to fix.
