### ISSUE TITLE
Wiki about setting SPDLOG_ACTIVE_LEVEL should be updated. 

### ISSUE THREAD

**Issue by cyang-kth** [gabime/spdlog#1268]
Also reported in this issue #1267 

The latest wiki (https://github.com/gabime/spdlog/wiki/1.-QuickStart#logging-macros) about setting the macro of SPDLOG_ACTIVE_LEVEL is not correct:

The current version is:

-------------
You can define SPDLOG_ACTIVE_LEVEL to the desired log level *before * including "spdlog.h".
This will turn on/off logging statements at compile time
```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG

SPDLOG_LOGGER_TRACE(file_logger , "Some trace message that will not be evaluated.{} ,{}", 1, 3.23);
SPDLOG_LOGGER_DEBUG(file_logger , "Some Debug message that will be evaluated.. {} ,{}", 1, 3.23);
SPDLOG_DEBUG("Some debug message to default logger that will be evaluated");
```
---------------

That is not correct. To print debug level information, the addition setting is required
```
spdlog::set_level(spdlog::level::debug); 
```

The new code like below
```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
#include "spdlog/spdlog.h"
int main(int argc, char* argv[])
{
    spdlog::set_level(spdlog::level::debug); // This setting is missed in the wiki
    SPDLOG_DEBUG("SPDLOG test debug");
}
```
The wiki should be updated with this information. I have spent hours to figure out the problem.

**Comment by gabime** [comment]
Close by updating the wiki.

**Comment by wkingnet** [comment]
it's still confused now. Macro `#define SPDLOG_ACTIVE_LEVEL` MUST be defined, otherwise SPDLOG_LOGGER_??? macro won't work.

log level is controlled by both macro `SPDLOG_ACTIVE_LEVEL` and `logger.set_level()`. 

This is so weird, I suggest removing the Macro `#define SPDLOG_ACTIVE_LEVEL`

**Comment by gabime** [comment]
The point is to remove at compile time log statements if the are below SPDLOG_ACTIVE_LEVEL. logger.set_level()  sets the log level 
 on runtime/
