### ISSUE TITLE
how to print file name and line no

### ISSUE THREAD

**Issue by yuimo** [gabime/spdlog#1269]
hi everybody, when i call spdlog::info, how to print file name and line no to the log file?
is there any switch to do this?
thx

**Comment by tt4g** [comment]
You can use logging macros `SPDLOG_TRACE("message")`, `SPDLOG_LOGGER_TRACE(logger, "message")` to output line numbers and file names.

Should define `SPDLOG_ACTIVE_LEVEL` macro that enables this feature.

https://github.com/gabime/spdlog/blob/v1.4.2/include/spdlog/spdlog.h#L275-L285

And set custom format %@.

Check the wiki for details.

* https://github.com/gabime/spdlog/wiki/3.-Custom-formatting
