### ISSUE TITLE
Exception: Failed opening file

### ISSUE THREAD

**Issue by nyckmaia** [gabime/spdlog#1271]
Hi, I downloaded and compiled the **static lib** version of spdlog (using Visual Studio) and added the headers and *lib file to my C++ Qt Project.

So I copy and paste the Wiki example:
```
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"

int main() 
{
    spdlog::info("Welcome to spdlog!");
    spdlog::error("Some error message with arg: {}", 1);
    
    spdlog::warn("Easy padding in numbers like {:08d}", 12);
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
    spdlog::info("Support for floats {:03.2f}", 1.23456);
    spdlog::info("Positional args are {1} {0}..", "too", "supported");
    spdlog::info("{:<30}", "left aligned");
    
    spdlog::set_level(spdlog::level::debug); // Set global log level to debug
    spdlog::debug("This message should be displayed..");    
    
    // change log pattern
    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");
    
    // Compile time log levels
    // define SPDLOG_ACTIVE_LEVEL to desired level
    SPDLOG_TRACE("Some trace message with param {}", {});
    SPDLOG_DEBUG("Some debug message");
    
    // Set the default logger to file logger
    auto file_logger = spdlog::basic_logger_mt("basic_logger", "logs/basic.txt");
    spdlog::set_default_logger(file_logger);            
}
```
**It compiles ok. No errors.**

But when the debugger hits the line:
```
auto file_logger = spdlog::basic_logger_mt("basic_logger", "logs/basic.txt");
```
I got a exception saying: `Failed opening file`
![image](https://user-images.githubusercontent.com/4555404/67118873-3feaaa00-f1bc-11e9-8364-88c988796bf2.png)

**Why is this happening?**

**My system:**

- Windows 10 x64
- Qt Creator IDE 4.10.1
- Visual Studio 2019 Enterprise

**Comment by nyckmaia** [comment]
**Solved!**
I'm using Windows...so the path to the file must be with backslash `\`

**Comment by syaifulnizamyahya** [comment]
Im on Visual studio 2019 and have exactly the same problem. Anybody have the sam eproblem?

Failed opening file for writing.

**Comment by tt4g** [comment]
@syaifulnizamyahya You have to replace the path separator slash with a backslash on Windows OS.

e.g. `"logs/basic.txt"` to `"logs\basic.txt"`.

Another solution: using `std::filesystem::path::make_preferred()`.
