### ISSUE TITLE
fmt.o should not be compiled when using external fmt library

### ISSUE THREAD

**Issue by dvhwgumby** [gabime/spdlog#1273]
`SPDLOG_SRCS` should not include `src/fmt.cpp` unless `SPDLOG_FMT_EXTERNAL=OFF` .  Its contents *are* correctly protected from compilation via preprocessor in this case, but compiling that file causes ranlib to complain `ranlib: file: libspdlog.a(fmt.cpp.o) has no symbols`.

Seems like this is a small oversight as installation already takes care not to include include `fmt/bundled`

**Comment by gabime** [comment]
Agreed. Thanks for reporting.

**Comment by gabime** [comment]
Fixed.
