### ISSUE TITLE
location of CMake config info

### ISSUE THREAD

**Issue by dvhwgumby** [gabime/spdlog#1274]
It's fantastic that you include both .pc files and .cmake files in the install tree!  I wish more people did since not every package uses CMake.

Although `${CMAKE_INSTALL_LIBDIR}/spdlog/cmake` will be searched by CMake, I believe the canonical location is `${CMAKE_INSTALL_LIBDIR}/cmake/spdlog` (looking at the docs it is searched first, and all my other third party packages install there.  This is also parallel that all the `.pc` files go into `pkgconfig/`: all the cmake details go into cmake/pkgname.

(N.B. #1253)

**Comment by gabime** [comment]
Fixed.
