### ISSUE TITLE
premature file rotating in version 1.3.1 under VM suspension

### ISSUE THREAD

**Issue by artemyv** [gabime/spdlog#1277]
I got a report that rotating logger configured to rotate on 20M file size actually produced files of following sizes
1 - 192.KB
2 - 1152KB
3 - 128KB
4 - 2752KB
5 - 20480KB

So only last one looks correct.
I could not find any issue reporting similar problem being fixed in the version 1.4

Could there be a problem with fmt::memory_buffer reporting wrong formatted size in case of failed formatting inside sink_it_ function?

I see that last log before rotating is always the same, but not all such lines are followed by rotation.

I suppose that if the problem is with wrong format - I will not see the problematic line in the log immediately after rotation - so I'm not sure I will be able to generate the sample code reproducing the issue.

**Comment by gabime** [comment]
I don't think wrong format could cause this. Perhaps the program just crashes now and then and doesn’t  reach 20 megs?

**Comment by artemyv** [comment]
There is no indication of crashes in the application itself - since the log is not opened after rotation and no aplication start-up sequence - it just continues to work. But there is a jump in timestamps after rotation for several minutes, and then adjusting it for 2-4 hours more (probably when clock was adjusted by time server). Looks like VM has been suspended and the restored which caused the log rotation. But no power management events found.

Is there a way to prevent log rotation in such a scenario?

**Comment by gabime** [comment]
which vm is it? can you provide an exact scenario to reproduce?

**Comment by artemyv** [comment]
The VM is vmware installed on ESX. Guest OS Microsoft Windows 10 Enterprise Build 18363
It occurs that at the time of log rotation/time gaps ESX has suspended the VM due to insufficient memory.

Other logs - that do  not use spdlog library have time gaps/broken lines during suspend but continue to write to the same file after resume

**Comment by gabime** [comment]
> ESX has suspended the VM due to insufficient memory.

Well, no wonder it happens. 
I think setting higher flush level would force flush before the memory runs out (at the cost of much lower performance of course). 
Another option is to flush automatically every few seconds. see https://github.com/gabime/spdlog/wiki/7.-Flush-policy#interval-based-flush

**Comment by artemyv** [comment]
Periodic flush was set for 1 sec
Out-of-memory condition was not on the guest VM but on the host.
The problem is not a missing logs but sudden log rotation caused by VM  suspend/resume
As a result instead of getting 5*20M logs in total - I got only ~24M logs in total. Which is not what being expected from rotating logger.
So I cannot consider the issue closed.
