### ISSUE TITLE
pattern %@ %! got nothing

### ISSUE THREAD

**Issue by magicsupery** [gabime/spdlog#1280]
`spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] %n [%^%l%$] [%@(%!)] %v"); `
`spdlog::info("this is a test")`

will output this :

[2019-10-23 11:57:45.003]  [info] [()] this is a test

==============
version is master

**Comment by gabime** [comment]
You need to use the macros in order to get the source file name

**Comment by magicsupery** [comment]
> You need to use the macros in order to get the source file name

the macro means the __FILE__ __FUNCTION__ __LINE__  in every spdlog::info(xxxx)  or you mean i can build source with some macro open that can make it show?

**Comment by gabime** [comment]
Please see https://github.com/gabime/spdlog/wiki/1.-QuickStart#logging-macros on how to use spdlog’s macros

**Comment by magicsupery** [comment]
> Please see https://github.com/gabime/spdlog/wiki/1.-QuickStart#logging-macros on how to use spdlog’s macros

thanks a lot !

**Comment by magicsupery** [comment]
> Please see https://github.com/gabime/spdlog/wiki/1.-QuickStart#logging-macros on how to use spdlog’s macros

spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] %n [%^%l%$] [%@(%!)] %v");
spdlog::info("this is a test")

will output this :

[2019-10-23 11:57:45.003] [info] [()] this is a test

=============
i'm confused the SPDLOG_ACTIVE_LEVEL can solve this?

**Comment by gabime** [comment]
Thisand using the SPDLOG_xxx macros (e.g SPDLOG_INFO(..), SPDLOG_DEBUG(..), etc.)
