### ISSUE TITLE
how can i print a {} in the log??

### ISSUE THREAD

**Issue by alpaca2333** [gabime/spdlog#1281]
i was trying to make all log messages in the json format.
how ever, due to spdlog use {} as placeholders, i cannot put them in the format string.
such as " {  \"traceid\": \"blabla\"  }"
a "{invalid format string}" is always what i got.

**Comment by tt4g** [comment]
The format processing of spdlog depends on fmt: https://github.com/fmtlib/fmt
You can escape with a double curly braces.

* [Format String Syntax — fmt 6\.0\.0 documentation](https://fmt.dev/6.0.0/syntax.html)

> Format strings contain “replacement fields” surrounded by curly braces {}. Anything that is not contained in braces is considered literal text, which is copied unchanged to the output. If you need to include a brace character in the literal text, it can be escaped by doubling: {{ and }}.

**Comment by alpaca2333** [comment]
thx a lot. that works.
