### ISSUE TITLE
Error trying to use the spdlog static library with cmake

### ISSUE THREAD

**Issue by tetsuhaut** [gabime/spdlog#1286]
Dear gabime,
I got an error trying to link with static library form of spdlog, be it version 1.4.2 or master:

>CMake Error at C:/prog/lib/spdlog/spdlog-1.x-vs2019-64bits-static/spdlogConfig.cmake:15 (include):
>
>  include could not find load file:
>
>    C:/prog/lib/spdlog/spdlog-1.x-vs2019-64bits-static/spdlogConfigTargets.cmake
>Call Stack (most recent call first):
>  CMakeLists.txt:123 (find_package)

Here is the part of my project's CMakeList.txt that links with spdlog:

>find_package(spdlog)
>include_directories(${SPDLOG_INCLUDEDIR})
>target_link_libraries(main_lib spdlog::spdlog)

Note that  I obtained the same error when generating for the Visual Studio 2019 or Mingw Makefile build systems.

**Comment by tt4g** [comment]
Is spdlog installed on the system?
`spdlogConfigTargets.cmake` is generated by CMake when it is installed.

https://github.com/gabime/spdlog/blob/b848ff8db9039ec630451c06f9078e61a5ec9166/CMakeLists.txt#L219-L230

And refer: https://cmake.org/cmake/help/latest/command/install.html#installing-exports

**Comment by tt4g** [comment]
If you are using `add_subdirectory()`, do not use `find_package(spdlog): #1026

**Comment by tetsuhaut** [comment]
Thanks for your answer @tt4g. I did not add spdlog as a subdirectory. In fact, I am trying to use spdlog as an external library, as described in https://github.com/gabime/spdlog/blob/v1.x/README.md: "Static lib version (recommended - much faster compile times)".
I took https://github.com/gabime/spdlog/blob/v1.x/example/CMakeLists.txt as an example.

I have compiled spdlog using cmake, and `spdlogConfigTargets.cmake` was indeed generated, in 
`<spdlog build dir>\CMakeFiles\Export\lib\cmake\spdlog`.
The problem is that when trying to link my program with the spdlog static lib, cmake says that the file `<spdlog build dir>\spdlogConfig.cmake` tries to include `spdlogConfigTargets.cmake` but can't find it.

**Comment by tt4g** [comment]
CMake installation is defined so that `spdlogConfig.cmake` and `spdlogConfigTargets.cmake` are output to the same installation directory.

Is there `spdlogConfig.cmake` in `<spdlog build dir>\CMakeFiles\Export\lib\cmake\spdlog`?
If so, you need to change the search path for `find_package()`.

In CMake version 3.12 and later, add `set(SPDLOG_ROOT <spdlog build dir>\CMakeFiles\Export\lib\cmake\spdlog)` before `find_package ()`: https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

**Comment by tetsuhaut** [comment]
> CMake installation is defined so that spdlogConfig.cmake and spdlogConfigTargets.cmake are output to the same installation directory.

When running the command
`cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Debug -D SPDLOG_BUILD_SHARED=OFF -D SPDLOG_BUILD_EXAMPLE=OFF -D SPDLOG_BUILD_TESTS=OFF -D SPDLOG_BUILD_BENCH=OFF -D SPDLOG_FMT_EXTERNAL=ON ..\spdlog-1.4.2`
There is a `spdlogConfig.cmake` file created, and a `CMakeFiles\Export\lib\cmake\spdlog\spdlogConfigTargets.cmake`.
In other words, `spdlogConfig.cmake` and `spdlogConfigTargets.cmake` are *not* output to the same installation directory.

**Comment by tetsuhaut** [comment]
Here is what I do:
```
C:\prog\lib\spdlog\spdlog-1.4.2-build-mingw64
\>cmake -G "MinGW Makefiles" ..\spdlog-1.4.2
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: C:/softs/cpp/gcc_mcf_lhmouse_com/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/softs/cpp/gcc_mcf_lhmouse_com/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.4.2
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Build type: Release
-- Generating examples
-- Generating tests
-- Found PkgConfig: C:/softs/cpp/gcc_mcf_lhmouse_com/mingw64/bin/pkg-config.exe (found version "0.29.2")
-- Checking for module 'libsystemd'
--   No package 'libsystemd' found
-- Generating install
-- Configuring done
-- Generating done
-- Build files have been written to: C:/prog/lib/spdlog/spdlog-1.4.2-build-mingw64

C:\prog\lib\spdlog\spdlog-1.4.2-build-mingw64
\>dir
 Le volume dans le lecteur C s’appelle System
 Le numéro de série du volume est E65F-9F26

 Répertoire de C:\prog\lib\spdlog\spdlog-1.4.2-build-mingw64

28/10/2019  10:46    <DIR>          .
28/10/2019  10:46    <DIR>          ..
28/10/2019  10:46            20 835 CMakeCache.txt
28/10/2019  10:46    <DIR>          CMakeFiles
28/10/2019  10:46             4 613 cmake_install.cmake
28/10/2019  10:46             4 182 CPackConfig.cmake
28/10/2019  10:46             4 634 CPackSourceConfig.cmake
28/10/2019  10:46               351 CTestTestfile.cmake
28/10/2019  10:46    <DIR>          example
28/10/2019  10:46            13 900 Makefile
28/10/2019  10:46               330 spdlog.pc
28/10/2019  10:46               401 spdlogConfig.cmake
28/10/2019  10:46             1 773 spdlogConfigVersion.cmake
28/10/2019  10:46    <DIR>          tests
               9 fichier(s)           51 019 octets
               5 Rép(s)  170 679 926 784 octets libres
```

**Comment by tt4g** [comment]
Looks like it is not installed.
The `cmake` command only creates a project and does not build and install it.
This is because `cmake` is a command that only creates a project. This is almost the same as `./configure`: https://cmake.org/cmake/help/latest/manual/cmake.1.html

You need to run `make && make install` or `cmake --build . && cmake --instal .`.

**Comment by tetsuhaut** [comment]
ok, I will try make && make install. However, this is not something I found in the readme where it explains how to build, and I never did 'install' for any other lib ???
Here is the result:
```
C:\prog\lib\spdlog\spdlog-1.4.2-build-mingw64
>mingw32-make -j 4
Scanning dependencies of target spdlog
[  3%] Building CXX object CMakeFiles/spdlog.dir/src/spdlog.cpp.obj
[  7%] Building CXX object CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.obj
[ 11%] Building CXX object CMakeFiles/spdlog.dir/src/color_sinks.cpp.obj
[... everything builds correctly...]
[ 92%] Building CXX object tests/CMakeFiles/spdlog-utests.dir/test_backtrace.cpp.obj
[ 96%] Building CXX object tests/CMakeFiles/spdlog-utests.dir/test_errors.cpp.obj
[100%] Linking CXX executable spdlog-utests.exe
[100%] Built target spdlog-utests

C:\sjoucrea\prog\lib\spdlog\spdlog-1.4.2-build-mingw64
>mingw32-make install
[ 26%] Built target spdlog
[ 34%] Built target example
[100%] Built target spdlog-utests
Install the project...
-- Install configuration: "Release"
-- Installing: C:/Program Files (x86)/spdlog/include
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot make directory "C:/Program Files (x86)/spdlog/include":
  No such file or directory


mingw32-make: *** [Makefile:138: install] Error 1
```

**Comment by tetsuhaut** [comment]
It seems that I need to have write permission to C:\Program Files (x86). If this is required for the 'install' command, then this is not possible for me. It feels a bit strange to have to install a lib to make find_package find it... Some other libs, such as fmt or others, do not require it. 
Are you sure it is needed? There might be other steps you do for it to work, that I am not aware of.

**Comment by tt4g** [comment]
> It seems that I need to have write permission to C:\Program Files (x86). If this is required for the 'install' command, then this is not possible for me. It feels a bit strange to have to install a lib to make find_package find it... Some other libs, such as fmt or others, do not require it.
> Are you sure it is needed? There might be other steps you do for it to work, that I am not aware of.

As far as I confirmed, `example/CMakeLists.txt` uses `find_package()` and will not work unless it is installed.
However, if you are familiar with CMake, you can use another method, such as adding `FindSpdlog.cmake`.

I have never tried it, but you can change the installation location with `CMAKE_INSTALL_PREFIX`(e.g. `cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=<path-to-install-dir> ..\spdlog-1.4.2 && make && make install`).

**Comment by tt4g** [comment]
There are several C / C ++ package managers that can work with CMake if necessary.

* [conan](https://conan.io/)
* [meson](https://mesonbuild.com/)

You will get a comfortable build. Instead, you will need knowledge about the package manager.

**Comment by gabime** [comment]
@tetsuhaut Please refer to https://stackoverflow.com/a/49816516/192001 on how to use find_package with custom paths.

**Comment by tetsuhaut** [comment]
dear @tt4g and @gabime, I followed https://stackoverflow.com/a/49816516/192001 to use find_package with custom paths, but still got the error:
```
CMake Error at C:/prog/lib/spdlog/spdlog-1.4.2-build-mingw64/spdlogConfig.cmake:15 (include):
  include could not find load file:

    C:/prog/lib/spdlog/spdlog-1.4.2-build-mingw64/spdlogConfigTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:119 (find_package)
```
I understand that the ` find_package` in my project requires that spdlog is installed in my C:\Program Files (x86), and nowhere else.
I will try it and see if it works, and then try to understand why I have to install spdlog in that particular place, and how to do other way.
Thank you for your help anyway.

**Comment by tetsuhaut** [comment]
So, for the record (and a potentially future updated readme file...)
I managed to build spdlog correctly, i.e. in a way that makes CMake able to find it through `find_package` in my project that depends on spdlog.

First, build spdlog and install it. For debug, you'll have to keep both the build dir and the install dir, as the build dir contains the *pdb files (at least when compiling with msvc). The build and install dir must be different. The command I used was
>cmake -G "MinGW Makefiles" ^
> -D CMAKE_BUILD_TYPE=Debug ^
> -D SPDLOG_BUILD_SHARED=OFF ^
> -D SPDLOG_FMT_EXTERNAL=ON ^
> -D SPDLOG_BUILD_EXAMPLE=OFF ^
> -D SPDLOG_BUILD_TESTS=OFF ^
> -D CMAKE_INSTALL_PREFIX=%BUILD_DIR%/install ^
> %SRC_DIR%
>mingw32-make -j 4 install

Adapt as needed.

Then, define an environment variable `SPDLOG_DIR` pointing to your install dir. It'll be used by the CMake `find_package` directive to find spdlog.

Finally, put in your project the following:
> find_package(spdlog 1.4.2 REQUIRED)
> target_link_libraries(myProject spdlog::spdlog)

Here, 1.4.2 is the version of spdlog my project requires to link with, and myProject is the target, i.e. library or executable, my project generates.

Dear @tt4g and @gabime, thanks for your help and support! It would be great if you could update the usage indications of the spdlog project so that next users do not need such CMake "expertise" in the future...
Or maybe should I send you a merge request for this?

**Comment by tt4g** [comment]
Thank you for your record.

However, I think it is difficult to present the best procedure for CMake configuration.

CMake is cross-platform and supports a combination of multiple compilers, IDEs and build tools. I guess it would be impossible to give a good hint for all these combinations.

I believe this issue will help other users.
