### ISSUE TITLE
\fmt/format.h(2780): warning C4189: 'options': local variable is initialized but not referenced 

### ISSUE THREAD

**Issue by dan-42** [gabime/spdlog#1287]
Hi I'm using:
* fmt v6.0.0
  * USE_GRISU is undefined
* Microsoft Visual C++ 2015

during compilation I see: 
```
[...]fmt/format.h(2780): warning C4189: 'options': local variable is initialized but not referenced (compiling source file  [...].cpp)
1>  [...]fmt/format.h(1790): note: see reference to function template instantiation 'void fmt::v6::internal::basic_writer<fmt::v6::internal::buffer_range<char>>::write_double<T,false>(T,const fmt::v6::basic_format_specs<char> &)' being compiled
1>          with
1>          [
1>              T=double
1>          ] (compiling source file [...].cpp)
```

The warning makes sens, as ``` USE_GRISU  ``` is not defined, the variable is never used.
This breaks my build if ``` Treat warnings as errors ``` is enables

**Comment by gabime** [comment]
This was fixed in fmt a while ago. try getting latest version or use the bundled fmt

**Comment by tt4g** [comment]
fmt is other project,  Better to ask thre: https://github.com/fmtlib/fmt/

I think already fixed master branch: https://github.com/fmtlib/fmt/blob/b7a157401e54895b491d0189045f27ca5cf100f6/include/fmt/format.h#L2810-L2818

**Comment by dan-42** [comment]
Thank you for the quick reply and sorry for the noise
