### ISSUE TITLE
systemd-journald sink does not log logger name

### ISSUE THREAD

**Issue by jktjkt** [gabime/spdlog#1289]
My application uses several loggers. When I use an `spdlog::sinks::ansicolor_stderr_sink_mt`, the output contains (among other things) the logger's name. When I switch to using `spdlog::sinks::systemd_sink_mt`, the logger name is not available anymore.

I think that this is because the systemd/journald sink does not use `spdlog::base_sink::formatter_` at all even though it inherits from `base_sink`. I suspect that this might have been due to the fact that the default formatter outputs stuff such as date/time/priority which is available via other means with journald. The logger name, however, is effectively lost this way.

**Comment by gabime** [comment]
This is very similar to a syslog issue we had (#1107).
I guess it can be solved in a similar way.

**Comment by jktjkt** [comment]
I looked into this a bit more. `journald` supports structured logging (essentially, it's feeding a stream of [key-value pairs, one of these keys is `MESSAGE`](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html) which corresponds to the human-readable string that's shown). So there are two possible approaches looking from `journald`'s perspective:
- Reuse the formatter and put the logger name into the `MESSAGE` string. Advantage: the logger name gets shown with no extra work. Disadvantage: it cannot be extracted in a machine-readable way.
- Put in an extra field just for the logger name. Advantage: allows for filtering, etc. Disadvantage: `journalctl` default output does not support showing arbitrary extra fields. But on a second thought, there's the `SYSLOG_IDENTIFIER` which looks exactly like that part that could be useful.
