### ISSUE TITLE
backtrace support produces confusing results with multiple loggers

### ISSUE THREAD

**Issue by jktjkt** [gabime/spdlog#1290]
This might be an A/B question. Here's the A-part:

I'm currently using several loggers, all of them sharing one sink, to provide something like "categories". I have one category for `io`, one for `interface-to-an-external-lib`, another one for `processing`, etc. Parts of my code which perform IO log to the `io` logger, etc.

I would like to use the backtrace subsystem to show additional details when an error has happened. During the course of normal operation, nobody cares about a hardcopy of the actual IO (it can be about 200 kB/s for me), but when the code logs an error about a malformed communication, then the IO details become important. The problem with backtraces is that they work per-logger. When I dump the messages, I get all IO messages together, followed by the "processing" messages, etc. I would like to have all messages across all loggers in order. I think that this could be solved by a "proxy logger" which just feeds all messages to some other logger, and the other logger preserves the original logger's name.

Here's the B-part:

What I'm really after is not necessarily multiple loggers. I just want different parts of my code to "tag" the messages as they are produced. If there's a better way then multiple loggers, I'll be happy to do that. I think I still need to set the log levels "per component", though, just because of the volume of the trace messages...

**Comment by gabime** [comment]
>  I think that this could be solved by a "proxy logger" which just feeds all messages to some other logger, and the other logger preserves the original logger's name.

In current implementation,I don't see a clear solution for this (perhaps define a dedicated custom “backtrace” sink that forwards all its messages to a dedicated backtrace logger?).

> What I'm really after is not necessarily multiple loggers. I just want different parts of my code to "tag" the messages as they are produced. If there's a better way..

That’s the recommended way - To have a logger per component/subsytem (they all can share the same set of sinks of course).
