### ISSUE TITLE
Please add clipping alignment

### ISSUE THREAD

**Issue by eudoxos** [gabime/spdlog#1297]
Alignment specifiers in patterns allow one to align left, right or centered. However, if the string being aligned is longer than alignment, it will stick out. Would it be possible to request clipping of the resulting string, e.g. via `%!12` or some modifier other than `-` and `=` already in use? This would be useful to e.g show only first 12 characters of base filename or logger name (so that messages stay aligned). Up to consideration whether the clipped variant should also have left/centered/right versions, I'd be fine with left-aligned (right-padded or right-clipped) only.

**Comment by gabime** [comment]
sounds good

**Comment by eudoxos** [comment]
Current idea for the mini-syntax:
* `[nothing]`, `-`. `=` retain their function;
* `>` for clip-right (or pad-right, if shorter), `<` for clip-left (or pad-left, if shorter);
* `|` for ellipsize-middle (insert `…` or `_` – configurable globally?), `/` for ellipsize-right (like clip-right, only put ellipsis instead of the last char if longer), `\` for ellipsize-left (like clip-left, with ellipsis instead of the first char)

**Comment by gabime** [comment]
To much syntax for such small feature :)
I suggest to keep it simple with a single flag that  truncates the right side if longer than the specified size.
 This would cover 99% of the needs.

**Comment by gabime** [comment]
@eudoxos Implemeted in cee35f7d246f7afb5fa6cc9d1509bacbea9201e7.

Use the optional ```!``` flag. It would truncate the right side if needed (see also the [updated wiki](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#aligning)) :
```
set_pattern("[%8!] %v");
set_pattern("[%-8!] %v");
set_pattern("[%=8!] %v");
```

Feedback is welcome

**Comment by FreeYourSoul** [comment]
This feature is awesome, just saying

**Comment by gabime** [comment]
@FreeYourSoul Thanks!

**Comment by amurzeau** [comment]
Hi,
Thanks for this feature too :) 

Truncating on the left would have been intersting when truncating function name, as when using C++, namespace and class names are less discriminating than the method name:

For example with `%30!!` with method `spdlog::details::scoped_padder::count_digits`:
- Truncating on the right (as done currently): `spdlog::details::scoped_padder`
- Truncating on the left: `s::scoped_padder::count_digits`

This is the same for filenames if we get absolute path, the beginning of the path is less likely interesting the the end.

I've looked on the existing code, it does not look easy to implement a left truncation with a small change:
```cpp
void format(const details::log_msg &msg, const std::tm &, memory_buf_t &dest) override              
{                                                                                                   
    if (msg.source.empty())                                                                         
    {                                                                                               
        return;                                                                                     
    }                                                                                               
    size_t text_size = padinfo_.enabled() ? std::char_traits<char>::length(msg.source.filename) : 0;
    ScopedPadder p(text_size, padinfo_, dest);                                                      
    fmt_helper::append_string_view(msg.source.filename, dest);                                      
}                                                                                                   
```

`fmt_helper::append_string_view` is called and will copy the non-truncated string no matter what `ScopedPadder` wants.
Then, when exiting scope, `ScopedPadder` can only do a resize on `dest` as done currently, but that's a truncation on the right.

**Comment by amurzeau** [comment]
Actually, I have successfuly implemented a right truncation, but that seems to me more like a workaround:

```diff
@@ -40,10 +40,18 @@ public:
         , dest_(dest)
     {
         remaining_pad_ = static_cast<long>(padinfo.width_) - static_cast<long>(wrapped_size);
         if (remaining_pad_ <= 0)
         {
+            if (remaining_pad_ < 0 && padinfo.truncate_ && padinfo_.side_ == padding_info::left)
+            {
+                // If we need to truncate the right of the field, save the current buffer to original_dest_
+                // dest_ is cleared and will only contain the field data when ~scoped_padder() will be called
+                // allowing us to add only the wanted part of the field.
+                original_dest_ = std::move(dest_);
+                dest_.clear();
+            }
             return;
         }
 
         if (padinfo_.side_ == padding_info::left)
         {
@@ -69,10 +77,19 @@ public:
     {
         if (remaining_pad_ >= 0)
         {
             pad_it(remaining_pad_);
         }
+        else if (padinfo_.truncate_ && padinfo_.side_ == padding_info::left)
+        {
+            size_t truncated_size = dest_.size() - padinfo_.width_;
+            // At this time, dest_ only contains the field data as it was moved to original_dest_ in the constructor
+            // So append only the padinfo.width_ last bytes of the field data to original_dest_
+            // and the move it back to dest_.
+            original_dest_.append(dest_.data() + truncated_size, dest_.data() + dest_.size());
+            dest_ = std::move(original_dest_);
+        }
         else if (padinfo_.truncate_)
         {
             long new_size = static_cast<long>(dest_.size()) + remaining_pad_;
             dest_.resize(static_cast<size_t>(new_size));
         }
@@ -86,10 +103,11 @@ private:
 
     const padding_info &padinfo_;
     memory_buf_t &dest_;
     long remaining_pad_;
     string_view_t spaces_{"                                                                ", 64};
+    memory_buf_t original_dest_;
 };
 
 struct null_scoped_padder
 {
     null_scoped_padder(size_t /*wrapped_size*/, const padding_info & /*padinfo*/, memory_buf_t & /*dest*/) {}
```

**Comment by gabime** [comment]
Thanks for the info. 
Might be useful indeed if/when right truncate would be implemented.
