### ISSUE TITLE
Logs not beeing printed to the log file

### ISSUE THREAD

**Issue by dbots94** [gabime/spdlog#1301]
Hello,

First of all, thank you very much for this library. It has been really usefull.
Second, I have this piece code:

`auto Sink = spdlog::basic_logger_mt("Sink", "LALA.log");`
`Sink->set_level(spdlog::level::trace);`
`Sink->set_pattern("[%H:%M:%S %z] [%^%L%$] [thread %t] %v");`
`SPDLOG_LOGGER_DEBUG(Sink, "BLA BEL ILB OBL LBU");`

For some reason, nothing is beeing printed inside the LALA.log, and I can't figure out why. Is there any initialization that should be done prior to the log?

I'm working on Linux, and in a multi-class multi-thread environment.

**Comment by tt4g** [comment]
You need to call `spdlog::shutdown()` before application exit.

**Comment by gabime** [comment]
Probably due to flush level. Please see the [flush policy](https://github.com/gabime/spdlog/wiki/7.-Flush-policy) on wiki.

**Comment by dbots94** [comment]
Thank you very much for both comments.
I managed to solve the issue by adding `spdlog::flush_every(std::chrono::seconds(10))` in the main(). 
Still the sollution given by @tt4g works just fine, but when the program is terminated by a keyboard interrupt, the error remains. Using the `atexit()` can correct that.
Best regards
