### ISSUE TITLE
Compiler error in os-inl.h min/max on Windows

### ISSUE THREAD

**Issue by mmakhalaf** [gabime/spdlog#1302]
This looks similar to #1251 and #902

This issue also manifests itself when using `std::numeric_limits<>::max / min()` . This is causing an issue in `details/os-inl.h` for us, but I can see that it's in `sinks/syslog_sink.h` and `sinks/systemd_sink.h` as well as a few other `fmt` files.

**Comment by gabime** [comment]
please provide the full error log from the compiler

**Comment by mmakhalaf** [comment]
```
1>d:\dev.10.0\externallibs\spdlog\include\spdlog\details\os-inl.h(429): warning C4003: not enough actual parameters for macro 'max'
1>d:\dev.10.0\externallibs\spdlog\include\spdlog\details\os-inl.h(429): error C2589: '(': illegal token on right side of '::'
1>d:\dev.10.0\externallibs\spdlog\include\spdlog\details\os-inl.h(429): error C2059: syntax error: '::'
1>d:\dev.10.0\externallibs\spdlog\include\spdlog\details\os-inl.h(429): error C2143: syntax error: missing '(' before '::'
1>d:\dev.10.0\externallibs\spdlog\include\spdlog\details\os-inl.h(430): error C2143: syntax error: missing ';' before '{'
```

We have min / max defined as macros by Windows (and enforced by us). We have the SPDLOG_WCHAR_TO_UTF8_SUPPORT flag also.

**Comment by gabime** [comment]
Fixed. (I hope, please verify)

The systemd/syslog sinks are not available under Winows anyway.
