### ISSUE TITLE
Segmentation Fault when using multi-sink

### ISSUE THREAD

**Issue by dbots94** [gabime/spdlog#1303]
Hello,

I'm using your library to achieve a multi-sink logger. In the code bellow, my objective is to print the log message to both console and file, with different output formats.
Here's my code:

Here I initialize the class specific sink, to print logs into a rotating file:
> auto asusXtionSink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("asusXtion.log", 1048576 * 5, 3);
> asusXtionSink->set_level(spdlog::level::info);
> asusXtionSink->set_pattern("%Y-%m-%d %H:%M:%S:%F [thread:%t] %l - %v");

Here I initialize the console sink:
> 
> auto consoleSink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
> consoleSink->set_level(spdlog::level::trace);
> consoleSink->set_pattern("%H:%M:%S:%F [thread:%t] %l - %v");
> 

Finally I construct the logger:
> 
> auto asusXtionLogger = spdlog::logger("asusXtionLogger", { asusXtionSink,consoleSink });
> asusXtionLogger.set_level(spdlog::level::trace);
>spdlog::get("asusXtionLogger")->debug("New AsusXtion object created");
>
For some reason the last line gives me a segmentation fault error. Can you help? 
Best regards

PS: Sorry for using quotes instead of code, but I wasn't able to make it "look good"

**Comment by tt4g** [comment]
You have to call `spdlog::register_logger()` before `spdlog::get()`.
This is because `spdlog::get()` finds the logger from the spdlog global registry.
`spdlog::register_logger()` registers a logger in the spdlog global registry.

The factory function (e.g. `spdlog::basic_logger_mt()`) calls `spdlog::register_logger()`. When using a custom sink, you must do it manually.

See also: https://github.com/gabime/spdlog/wiki/5.-Logger-registry

**Comment by dbots94** [comment]
Sorry for bothering again, but I'm still having troubles achiving a multi-sink logger.
As you can see from my code above, I create a consoleSink and a fileSink(asusXtionSink). 

To register I tried this way:
`spdlog::register_logger(asusXtionSink.clone("asusXtionLogger");`

But now It doesn't log anything anywhere.
How should one get the _std::shared_ptr < spdlog:logger >_ parameter to registry my logger.

**Comment by tt4g** [comment]
Try the following code:

```cpp
int main(int, char**) {
    auto asusXtionSink = 
            std::make_shared<spdlog::sinks::rotating_file_sink_mt>("asusXtion.log", 1048576 * 5, 3);
    asusXtionSink->set_level(spdlog::level::info);
    asusXtionSink->set_pattern("%Y-%m-%d %H:%M:%S:%F [thread:%t] %l - %v");

    auto consoleSink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    consoleSink->set_level(spdlog::level::trace);
    consoleSink->set_pattern("%H:%M:%S:%F [thread:%t] %l - %v");

    std::vector<spdlog::sink_ptr> sinks({ asusXtionSink, consoleSink });

    auto asusXtionLogger = 
            std::make_shared<spdlog::logger>("asusXtionLogger", sinks.begin(), sinks.end());
    asusXtionLogger.set_level(spdlog::level::trace);
    spdlog::register_logger(asusXtionLogger);

    spdlog::get("asusXtionLogger")->debug("New AsusXtion object created");

   spdlog::shutdown();

   return 0;
}
```

**Comment by dbots94** [comment]
Thank you very much for the reply.
It worked as supposed!!

Best regards
