### ISSUE TITLE
Can not print filename and line in windows(msvc2017)

### ISSUE THREAD

**Issue by 1011875777** [gabime/spdlog#1309]
![image](https://user-images.githubusercontent.com/13702789/68546805-8e831100-0415-11ea-9576-fa387c238d34.png)

**Comment by tt4g** [comment]
Patterns `%@`, `%s` `%g`, `%#`, and `%!` are not printed unless a macro is used: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

**Comment by 1011875777** [comment]
ok,I got it, thank you very much. @tt4g
