### ISSUE TITLE
Would like to be able to get a const view of all registered loggers

### ISSUE THREAD

**Issue by igfraga** [gabime/spdlog#1313]
Mostly for diagnostics, I'd like to see what loggers are currently registered and at what level they are logging.

Something like this would be perfect:
```c++
SPDLOG_INLINE std::unordered_map<std::string, std::shared_ptr<logger>> registry::get_loggers()
{
    std::lock_guard<std::mutex> lock(logger_map_mutex_);
    return loggers_;
}
```
Would be happy to make a PR.

**Comment by tt4g** [comment]
FYI.

There is a similar function `spdlog::apply_all()` exists.

https://github.com/gabime/spdlog/blob/1f5f17622ed2c01831337cef72e17c0d8985993d/include/spdlog/spdlog.h#L88-L91

**Comment by igfraga** [comment]
Thanks, that works!
