### ISSUE TITLE
Disable Windows GDI definitions

### ISSUE THREAD

**Issue by miikka75** [gabime/spdlog#1315]
I have defined Rectangle in my code base (inside my own namespace) but still I get a compile error in Windows with MSVC 2019 toolset:

error C2872: 'Rectangle': ambiguous symbol
[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\wingdi.h(4515): note: could be 'BOOL Rectangle(HDC,int,int,int,int)'

To fix the issue, following change is needed:

```cpp
diff --git a/include/spdlog/common.h b/include/spdlog/common.h
index 830220e..01c5c73 100644
--- a/include/spdlog/common.h
+++ b/include/spdlog/common.h
@@ -19,6 +19,9 @@
 #ifndef NOMINMAX
 #define NOMINMAX // prevent windows redefining min/max
 #endif
+#ifndef NOGDI
+#define NOGDI
+#endif

 #ifndef WIN32_LEAN_AND_MEAN
 #define WIN32_LEAN_AND_MEAN
```

**Comment by gabime** [comment]
How come there is a collision if  yours in its own namespace?

**Comment by miikka75** [comment]
Here's a simplified example of case that gives error:
```cpp
namespace myspace { struct Rectangle { int left; int top; int right; int bottom; }; }
#include "windows.h"
using namespace myspace;
int main() {
    Rectangle my_rect = {0,0,10,10};
    return 0;
}
```
compiler outputs:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\wingdi.h(4515): note: could be 'BOOL Rectangle(HDC,int,int,int,int)'
[build] ..\test.cpp(1): note: or       'myspace::Rectangle'
[build] ..\test.cpp(9): error C2872: 'Rectangle': ambiguous symbol
```

I'd like to use ```myspace::Rectangle``` without needing to define namespace ```myspace```. I guess ```windows.h``` pollutes global namespace with its own ```Rectangle``` and IMO it would be best to avoid defining anything unnecessary in global scope. What exactly spdlog is using from ```windows.h```?

**Comment by gabime** [comment]
You can include windows.h before spdlog.h and define NOGDI. spdlog should not decide for everyone not to use GDI.
