### ISSUE TITLE
Getting results from ostream_sink_mt with std::ostringstream

### ISSUE THREAD

**Issue by chulup** [gabime/spdlog#1316]
This issue is more of a discussion request with two possible solutions presented.

I need to write logs to memory and fetch them from time to time so I decided to use `ostream_sink_mt` with `std::ostringstream`.

The usual way of calling `auto results = stream.str(); stream.str("")` to get collected string is not possible here due to multiple writing threads in my app and the fact that all spdlog locks are in `spdlog::sinks::base_sink`. My short tests show that in about 3 seconds of simultaneous logging and withdrawing results from `std::ostringstream` object memory corruption occurs.

In my case I copied ostream_sink (why is it `final`?) and implemented the following method:

```cpp
std::string getResults() {
    std::lock_guard<Mutex> lock(spdlog::sinks::base_sink<Mutex>::mutex_);
    // throws std::bad_cast when `ostream` is not std::ostringstream
    auto& ostringstream_ = dynamic_cast<std::ostringstream&>(ostream_);
    auto ret = ostringstream_.str();
    ostringstream_.str("");
    return ret;
  }
```

It works for me but that shows that `spdlog::sinks::ostream_sink` class is incomplete. 
The `getResults` method is specific to my case and won't work for other cases.

There could be another solution which would allow me to sidestep the problem entirely: add something like following to `base_sink`:

```cpp
template<typename Mutex>
void SPDLOG_INLINE spdlog::sinks::base_sink<Mutex>::executeLocked(std::function<void(void)> &&lambda) {
    std::lock_guard<Mutex> lock(mutex_);
    lambda();
}
```

Caller would be able to do access resources used by `base_sink` like that:

```cpp
void a() {
  std::ostringstream out;
  auto sink = std::make_shared<spdlog::sinks::ostream_sink_mt>(out);
  auto sync_logger = std::make_shared<spdlog::logger>("stream_sync", sink);

  std::atomic_bool running = true;
  auto t1 = std::thread([&running, log = sync_logger]() {
    uint64_t i = 0;
    while (running) {
      log->warn("ostream log: {:>10}", i++);
    }
  });

  std::this_thread::sleep_for(std::chrono::milliseconds(300));
  std::string results;
  sink->executeLocked([&results]() {
    results = out.str();
    out.str("");
  });

  // process results here
}
```

Of course this opens another host of problems like calling `base_sink` methods while `mutex_` is locked by the same thread but in my opinion that's what documentaion is for.

**Comment by gabime** [comment]
I think your first approach is fine. Just get the pointer to the sink and call getResults() without extra abstractions.

You might want to use the recently added [rigbbuffer_sink_mt](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/ringbuffer_sink.h) by @eudoxos  that does exactly what you need!

**Comment by chulup** [comment]
We use Conan for deps so it'll have to be my first option until you release next version.

Funny how I asked that a week after new sink was added!
