### ISSUE TITLE
Trace and Debug messages dont appear when using logging macros

### ISSUE THREAD

**Issue by ROTARTSI82** [gabime/spdlog#1318]
I initialize the logger with
```
spdlog::set_level(spdlog::level::trace);
auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
console_sink->set_level(spdlog::level::trace);

std::shared_ptr<spdlog::sinks::basic_file_sink_mt> file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("latest.log", true);
file_sink->set_level(spdlog::level::trace);

std::shared_ptr<spdlog::logger> logger = std::make_shared<spdlog::logger>("root", spdlog::sinks_init_list({console_sink, file_sink}));
logger->set_level(spdlog::level::trace);

spdlog::register_logger(logger);
spdlog::set_default_logger(logger);
```

and then when I use `SPDLOG_TRACE` or `SPDLOG_DEBUG` nothing is logged to the console or the file. However, `SPDLOG_INFO` and above work perfectly fine.

EDIT: I just tried the functions `spdlog::trace` and `spdlog::debug` and they work as intended... Is there a seperate setting for macros? Am I doing anything wrong?

Code:
```
// Insert same code above

spdlog::set_pattern("%^[%Y.%m.%d] [%H:%M:%S.%F] [%n:%l] [%s:%#]: %v%$");
spdlog::trace("Testing trace");
spdlog::debug("Testing debug");
spdlog::info("Testing inf");
spdlog::warn("Testing warn");
spdlog::critical("Testing crit");
SPDLOG_TRACE("Testing trace macro");
SPDLOG_DEBUG("Testing debug macro");
SPDLOG_INFO("Testing inf macro");
SPDLOG_WARN("Testing warn macro");
SPDLOG_CRITICAL("Testing crit macro");
```

Output:

```
[2019.11.17] [10:20:21.492722000] [root:trace] [:]: Testing trace
[2019.11.17] [10:20:21.492740000] [root:debug] [:]: Testing debug
[2019.11.17] [10:20:21.492758000] [root:info] [:]: Testing inf
[2019.11.17] [10:20:21.492776000] [root:warning] [:]: Testing warn
[2019.11.17] [10:20:21.492793000] [root:critical] [:]: Testing crit
[2019.11.17] [10:20:21.492810000] [root:info] [logging.cpp:68]: Testing inf macro
[2019.11.17] [10:20:21.492829000] [root:warning] [logging.cpp:69]: Testing warn macro
[2019.11.17] [10:20:21.492849000] [root:critical] [logging.cpp:70]: Testing crit macro
```

**Comment by ROTARTSI82** [comment]
Realized the problem: I forgot to
`#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE`

**Comment by k-sheridan** [comment]
I have the same problem, but I verified that SPDLOG_ACTIVE_LEVEL is actually set to SPDLOG_LEVEL_TRACE. When I change to WARN or higher, it works.

**Comment by gabime** [comment]
You also need to use set_level(trace)

**Comment by k-sheridan** [comment]
Why is that required for trace and debug, but not info and higher?

**Comment by gabime** [comment]
Because the default level is always info for each logger instance. The SPDLOG_LEVEL_TRACE doesn't change this.

**Comment by shazni** [comment]
I can't get this to work. I defined the macro and still the trace and debug is not getting printed. I want to use the %@, %s patterns in the set_pattern method. Is there any other way I can the functionality of %@ without using the macro versions?

**Comment by gabime** [comment]
Please provide the problematic code

**Comment by shazni** [comment]
Figured out the issue. Actually I had to define the macro before including the spdlog header file. However, I have related questions.
1) The %@ prints the full path - but the wiki says otherwise. 
2) Let's say I have defined SPDLOG_LEVEL_TRACE and now wants to restrict the log level to DEBUG, do I need to unset the #define and use set_level(trace)?

**Comment by tt4g** [comment]
> The %@ prints the full path - but the wiki says otherwise.

spdlog gets the path of a source file from `__FILE__` macro.

https://github.com/gabime/spdlog/blob/4a9ccf7e38e257feecce0c579a782741254eaeef/include/spdlog/spdlog.h#L241

The `__FILE__` macro is replaced with the path to the source file by the preprocessor, but the result is either an absolute or relative path, depending on the compiler.

gcc compiler, replace `__FILE__` to absolute path: https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html

MSVC, replace `__FILE__` to relative path (can override behavior `/FC` option): https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019

NOTE if using CMake with Ninja generator, always render relative path: https://gitlab.kitware.com/cmake/cmake/-/issues/13894

> Let's say I have defined SPDLOG_LEVEL_TRACE and now wants to restrict the log level to DEBUG, do I need to unset the #define and use set_level(trace)?

Replace `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE` with `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG`.

**Comment by shazni** [comment]
Thanks for the details. 

Understood the behavior of the %@.

For changing TRACE to DEBUG, I suppose what you are suggesting is a compile time way of changing the level. I'm looking at changing the level in the runtime when using the macros to log.

**Comment by tt4g** [comment]
> For changing TRACE to DEBUG, I suppose what you are suggesting is a compile time way of changing the level. I'm looking at changing the level in the runtime when using the macros to log.

@shazni The preprocessor will replace `SPDLOG_TRACE` to `(void) 0` if defined `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG`.

https://github.com/gabime/spdlog/blob/4a9ccf7e38e257feecce0c579a782741254eaeef/include/spdlog/spdlog.h#L243-L257

Should call `spdlog::logger::set_level(spdlog::level)` with `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE` to change the level at runtime.

**Comment by shazni** [comment]
Thanks I will try this out.

**Comment by anhns** [comment]
> Realized the problem: I forgot to `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE`
> 
> I _really_ think this should be documented better

It works for me.
Thank you so much

**Comment by everdrone** [comment]
```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>
```

```cpp
SPDLOG_TRACE("not working");
```

does not work for me. The `SPDLOG_ACTIVE_LEVEL` definition is set but spdlog does not print anything below `info`

**Comment by tt4g** [comment]
@everdrone https://github.com/gabime/spdlog/issues/1318#issuecomment-602248684

> You also need to use ` set_level(trace)`

**Comment by everdrone** [comment]
@tt4g so there is no way of setting it without calling a function that calls `spdlog::set_level()`?

I was hoping for a way of setting `SPDLOG_LEVEL_TRACE` using macros for use in a library.

**Comment by tt4g** [comment]
@everdrone The `SPDLOG_LEVEL_TRACE` macro is intended to allow removal of unnecessary logging statements at compile time.
Log messages will be discarded by the logger unless `spdlog::set_level(spdlog::level::trace)` is called to change the log level from the default of `spdlog::level::info`.

https://github.com/gabime/spdlog/blob/4c5ee9bb108e7c0e141f95913360b228569fa568/include/spdlog/logger.h#L353-L354

**Comment by BhaskarRamanna** [comment]
spdlog::set_level(spdlog::level::level_enum::trace) with spdlog::trace(msg) works well 
but with SPDLOG_TRACE(msg) its not!
