### ISSUE TITLE
Shared from this for standard loggers

### ISSUE THREAD

**Issue by caiazza** [gabime/spdlog#1323]
Hi gabime,
Working with the async loggers I noticed that that class is derived from enable_shared_from_this. Wouldn't be better to allow the default logger to have the same feature by moving that inheritance at the base level?

**Comment by gabime** [comment]
why?

**Comment by caiazza** [comment]
Because I assumed that if you had a good reason to have it in the derived, a similar reason may apply to the base. I may be wrong but the idea to use that class is to be able to get a properly shared shared_ptr from a reference of an object and that can apply to async_logger as well as to a normal logger, can it not?

**Comment by gabime** [comment]
It is needed for the async logger impl only.  So i don't see the point moving it to the base class.

**Comment by caiazza** [comment]
Ok, considering you pass the loggers around by shared_ptr, I thought it was also a facility for the user, not just for the implementation.
If it's just an implementation detail I would suggest to use private inheritance, rather than public, so your intention is clear. It's just a minor detail, though, just got me a bit confused when I was looking at it

**Comment by gabime** [comment]
I dont think it is even possible https://stackoverflow.com/questions/39937112/stdenable-shared-from-this-public-vs-private

**Comment by caiazza** [comment]
Yes, you're right.
