### ISSUE TITLE
Info needed

### ISSUE THREAD

**Issue by rakeshsv** [gabime/spdlog#1324]
In : spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v"); I want to change it like spdlog::set_pattern("[%H:%M:%S %z] [%ModuleName] [%^---%L---%$] [thread %t] %v"); . Module Name is defined as a string. Also what is z

**Comment by tt4g** [comment]
You can use the same logger in a module. This logger name is the module name.

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"

void foo()
{
    auto module_logger = spdlog::get("ModuleName");

    module_logger ->info("foo");
}

void bar()
{
    auto module_logger = spdlog::get("ModuleName");

    module_logger ->info("bar");
}

int main(int, char**)
{
    // Register "ModuleName" logger.
    spdlog::basic_logger_mt("ModuleName", "log.txt");

    foo();
    bar();

    return 0;
}
```

**Comment by rakeshsv** [comment]
Thanks, few more questions please.
- Can I turn off logging easily? 
- Can I control levels ( Critical/ Info / warning) easily

**Comment by tt4g** [comment]
> * Can I turn off logging easily?
> * Can I control levels ( Critical/ Info / warning) easily

You can pass `spdlog::level_enum::off` to `spdlog::set_level()`, `spdlog::logger::set_level()`, `spdlog::sinks::sink::set_level()`.

`spdlog::set_level()`: Change the log level of all registered loggers.

`spdlog::logger::set_level()`: The logger changes the log level.

`spdlog::sinks::sink::set_level()`: The sink changes log level.

The above function is thread-safe.

**Comment by rakeshsv** [comment]
Just a thought, may be an export variable that can be used at the shell prompt instead of compiling the source again, would be helpful

**Comment by gabime** [comment]
see this branch https://github.com/gabime/spdlog/tree/env_config 

Its only wip nut you can try it and fedback.
