### ISSUE TITLE
[Enhancement] Option to use fmt::fmt-header-only when SPDLOG_FMT_EXTERNAL==true

### ISSUE THREAD

**Issue by steffenb7333** [gabime/spdlog#1325]
When SPDLOG_FMT_EXTERNAL evaluates to true, the spdlog-target is hardwired to use fmt::fmt. Please add an option to use fmt::fmt-header-only instead.

**Comment by gabime** [comment]
Implemented by adding ```SPDLOG_FMT_EXTERNAL_HO``` option to CMake (mutual exclusive to ```SPDLOG_FMT_EXTERNAL``
