### ISSUE TITLE
set_level vcpkg

### ISSUE THREAD

**Issue by coderc264** [gabime/spdlog#1326]
Hi all, i tried to change log level to trace, but unfortunately doesn't work for me.
I've installed the library with vcpkg in windows. and i have this code:

`void inline configureLogger()
{
	auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
	console_sink->set_pattern("%D-%e %@ [%^%l%$] %v");

	auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("../logs/units.log", true);
	file_sink->set_pattern("%D-%e %@ [%^%l%$] %v");
    
    std::vector<spdlog::sink_ptr> sinks;
    sinks.emplace_back(console_sink);
    sinks.emplace_back(file_sink);

    auto combined_logger = std::make_shared<spdlog::logger>("multi_sink", begin(sinks), end(sinks));
    
	spdlog::register_logger(combined_logger);
    
    spdlog::set_default_logger(combined_logger);
	
	combined_logger->set_level(spdlog::level::trace);
	spdlog::set_level(spdlog::level::trace);
}`

**Comment by tt4g** [comment]
Should you call `spdlog::logger::flush()` or `spdlog::shutdown()` before application exit.

**Comment by coderc264** [comment]
Soryy, but doesn't work

**Comment by gabime** [comment]
Please provide the code to reproduce.

**Comment by coderc264** [comment]
This is my code:

`spdlog::set_level(spdlog::level::trace);
	auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
	console_sink->set_pattern("%D-%e %s:%# [%^%l%$] %v");

	auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("../logs/units.log", true);
	file_sink->set_pattern("%D-%e %s:%# [%^%l%$] %v");

	std::vector<spdlog::sink_ptr> sinks;
	sinks.emplace_back(console_sink);
	sinks.emplace_back(file_sink);

	auto combined_logger = std::make_shared<spdlog::logger>("multi_sink", begin(sinks), end(sinks));

	spdlog::register_logger(combined_logger);
	spdlog::set_default_logger(combined_logger);
	
	combined_logger->set_level(spdlog::level::trace);
	//configureLogger();

	SPDLOG_TRACE("Units running {0}", (string)Date::getCurrentDate());`

**Comment by tt4g** [comment]
Try the following changes:

```diff
- spdlog::set_level(spdlog::level::trace); // tried this
auto console_sink = std::make_sharedspdlog::sinks::stdout_color_sink_mt();
console_sink->set_pattern("%D-%e %s:%# [%^%l%$] %v");

auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("../logs/units.log", true);
file_sink->set_pattern("%D-%e %s:%# [%^%l%$] %v");

std::vector<spdlog::sink_ptr> sinks;
sinks.emplace_back(console_sink);
sinks.emplace_back(file_sink);

auto combined_logger = std::make_shared<spdlog::logger>("multi_sink", begin(sinks), end(sinks));

spdlog::register_logger(combined_logger);
spdlog::set_default_logger(combined_logger);

combined_logger->set_level(spdlog::level::trace); // tried this
+ combined_logger->flush_on(spdlog::level::trace);

SPDLOG_TRACE("Units running ");`
```

And if use `spdlog::flush_on()`, change `spdlog::register_logger(combined_logger);` to `spdlog::initialize_logger(combined_logger);`.

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/spdlog.h#L39-L49

**Comment by coderc264** [comment]
i tried but ddin't work for me. i installed the library with vcpkg, could this be the problem?

**Comment by gabime** [comment]
@coderc264  This is very strange. What exactly doesn't work ? And also could you please provide full example(after all the changes) here to reproduce

**Comment by coderc264** [comment]
simply the trace level doesn't work

**Comment by gabime** [comment]
You mean when you call ```SPDLOG_TRACE("Units running ");``` ?

**Comment by coderc264** [comment]
here the full code:

`#include <iostream>
#include <chrono>

#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/rotating_file_sink.h>
#include <spdlog/sinks/stdout_sinks.h>
#include <spdlog/sinks/stdout_color_sinks.h>

using namespace std;

int main(int argc, char* argv[])
{
	//spdlog::set_level(spdlog::level::trace);
	auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
	console_sink->set_pattern("%D-%e %s:%# [%^%l%$] %v");

	auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("../logs/units.log", true);
	file_sink->set_pattern("%D-%e %s:%# [%^%l%$] %v");

	std::vector<spdlog::sink_ptr> sinks;
	sinks.emplace_back(console_sink);
	sinks.emplace_back(file_sink);

	auto combined_logger = std::make_shared<spdlog::logger>("multi_sink", begin(sinks), end(sinks));

	spdlog::register_logger(combined_logger);
	spdlog::set_default_logger(combined_logger);
	
	combined_logger->set_level(spdlog::level::trace);

	SPDLOG_TRACE("Units running");
	SPDLOG_DEBUG("Units running");
	SPDLOG_INFO("Units running");
	SPDLOG_WARN("Units running");
	SPDLOG_ERROR("Units running");
	SPDLOG_CRITICAL("Units running");
	
	exit(EXIT_SUCCESS);
}

`
 
compiled on windows 10 with Visual Studio 2019, cmake and vcpkg

**Comment by gabime** [comment]
You need to 
```c++
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
``` 

**before** including spdlog.h

**Comment by coderc264** [comment]
i tried it but stil doesn't work

**Comment by gabime** [comment]
What doesn't work exactly?

**Comment by coderc264** [comment]
If i use "combined_logger->trace("HELLO");" works, but doesn't have colored terminal outupt, function name and line number

**Comment by gabime** [comment]
function name and line number only works when using macros (SPDLOG_TRACE)

**Comment by coderc264** [comment]
But if i use macros the code doesn't print trace and debug levels

**Comment by tt4g** [comment]
@coderc264 Please see permlinks:

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/common.h#L135-L137

If you not define `SPDLOG_ACTIVE_LEVEL` that is `SPDLOG_LEVEL_INFO`.

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/spdlog.h#L288-L296

if `SPDLOG_ACTIVE_LEVEL` is not equal `SPDLOG_LEVEL_TRACE`, `SPDLOG_LOGGER_TRACE` is not working (empty macro).
And `SPDLOG_LOGGER_CALL` specifies `SPDLOG_FUNCTION` and `__LINE__`.

This is why you must define `SPDLOG_ACTIVE_LEVEL` and use `SPDLOG_LOGGER_TRACE` for printing function name and line number.

Try change your full code:

```diff
#include <iostream>
#include <chrono>

+ #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

...

```

Or change CMakeLists.txt:

```diff
add_definitions(-DWIN32_LEAN_AND_MEAN)
add_definitions(-D_CRT_SECURE_NO_WARNINGS)
add_definitions(-DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE)
add_definitions(/MP)
add_definitions(/permissive-)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4275")

set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT units)
```

**Comment by coderc264** [comment]
I tried the secondo solution (modify CMakeLists.txt) now it works, but write without colors attributes. 
I need to enable something else?

**Comment by coderc264** [comment]
Sorry i that it's ok now.
trace = white color
debug = blue color
info = green color
and so on

**Comment by tt4g** [comment]
Call `spdlog::shutdown()` before application exit.

**Comment by coderc264** [comment]
thanks alot
