### ISSUE TITLE
Callback on error level log

### ISSUE THREAD

**Issue by fourier** [gabime/spdlog#1328]
Hi,

I want to add some special behavior to my application which uses spdlog: I want to have a callback after the message of log level "error" has been written.
Most of the time I want to gracefully shutdown the application and do not want to add special lines of code all the places where the ->error could be called.
Is there an easy way to achieve this? Important is that the error entry still has to be written (and flushed) to the file.

**Comment by gabime** [comment]
You could develop a custom sink that does this when an error is logged, and add this to the end of the sinks vector used by your logger

**Comment by fourier** [comment]
Thanks! Sounds like a plan.
