### ISSUE TITLE
spdlog unconditionally enabling -Wconversion causes build break with external {fmt} lib

### ISSUE THREAD

**Issue by 0x8000-0000** [gabime/spdlog#1329]
https://github.com/gabime/spdlog/blob/79259fdb3f57283f65185a8e41840968dae4043c/cmake/utils.cmake#L31

When using {fmt} 6.0.0 with spdlog 1.4.2, the build fails when trying to compile spdlog/src/async.cpp because of sign-conversion warnings in fmt/core.h .

I think -Wall -Wextra -pedantic should be acceptable for a library, but -Wconversion is a bit too much.

For the record, we're cleaning up -Wconversion in our internal projects, but can only submit pull requests and file bug reports for upstream libraries.

**Comment by tt4g** [comment]
It is better to report this issue to fmt project.

**Comment by gabime** [comment]
spdlog is already bundled with fmt 6,  So i don't understand why it fails in your setup..

**Comment by 0x8000-0000** [comment]
Because I want to use upstream {fmt} lib instead of bundled. For instance, 6.0 has some shadow warnings (in the headers) which forced us to disable -Wshadow on the code base, which masked a bug. So I would prefer to decouple the two libraries .

**Comment by 0x8000-0000** [comment]
> If the warning occurs in the fmt header file, It is better to report this issue to fmt project.

Right - and I have done that as well. But I don't see why one library should impose flags on another. I prefer using unbundled libraries, and where I inject the flags that I want to use.
