### ISSUE TITLE
error C2220: 警告被视为错误 - 没有生成“object”文件

### ISSUE THREAD

**Issue by zh1an** [gabime/spdlog#1330]
The package installed from vcpkg cannot be compiled. The followings is error info: 
D:\git\vcpkg\installed\x86-windows\include\fmt/format.h(2780): error C2220: 警告被视为错误 - 没有生成“object”文件
D:\git\vcpkg\installed\x86-windows\include\fmt/format.h(2780): warning C4189: “options”: 局部变量已初始化但不引用
I Just searched this error, showing that warning treated as error - no object file generated.
I already upload the log.
[install-x86-windows-dbg-out.log](https://github.com/gabime/spdlog/files/3895914/install-x86-windows-dbg-out.log)

**Comment by zh1an** [comment]
Sorry.The portfile.cmake shows version is `v1.4.2`.

**Comment by gabime** [comment]
Please open this issue in the vcpkg repo
