### ISSUE TITLE
Make the `pattern_formatter` extensible.

### ISSUE THREAD

**Issue by tkausl** [gabime/spdlog#1334]
spdlog has a `formatter` interface which one can implement to create custom formatters. This is not needed however for most cases if one needs only a minor change or addition to the `pattern_formatter`. 

Currently, the `pattern_formatter` has a hardcoded `switch` in `pattern_formatter::handle_flag_` to create `flag_formatter`s by flag-character which isn't really extensible.

I propose the following changes:

1. Instead of the hardcoded switch, store character -> flag_formatter somehow (maybe a char -> "create"-function in a map or something similar)

2. Create a _public_ api to allow clients to register their own flags.

This would make it possible to implement a _minor_ change or addition without the need to write a whole new `formatter` and reimplement what's already existing in the `pattern_formatter`.

**Comment by gabime** [comment]
Implemented in 60a8c5f1c9cf039453824b439d1a40c7e76a93c4

See the example.cpp on how to use.
