### ISSUE TITLE
os-inl.h compile error on OpenBSD

### ISSUE THREAD

**Issue by weanti** [gabime/spdlog#1335]
The following errormessage is displayed when os-inl.h is compiled:
In file included from /home/weanti/programming/spdlog/include/spdlog/spdlog.h:13:
In file included from /home/weanti/programming/spdlog/include/spdlog/details/registry.h:108:
In file included from /home/weanti/programming/spdlog/include/spdlog/details/registry-inl.h:12:
In file included from /home/weanti/programming/spdlog/include/spdlog/logger.h:18:
In file included from /home/weanti/programming/spdlog/include/spdlog/details/log_msg.h:34:
In file included from /home/weanti/programming/spdlog/include/spdlog/details/log_msg-inl.h:10:
In file included from /home/weanti/programming/spdlog/include/spdlog/details/os.h:110:
/home/weanti/programming/spdlog/include/spdlog/details/os-inl.h:233:16: error: expected unqualified-id
    int fd = ::fileno(f);
               ^
/usr/include/stdio.h:406:19: note: expanded from macro 'fileno'
#define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))

As it is visible the reason of the error is that 'fileno' is a macro on OpenBSD 6.6+Clang 8.0.1 combination which does not work with '::'. The following extension makes compiling work:
`#if defined(__clang__)`
`    int fd = fileno(f);`
`#else`
`    int fd = ::fileno(f);`
`#endif`

**Comment by gabime** [comment]
Thanks for reporting.

**Comment by gabime** [comment]
Fixed

**Comment by weanti** [comment]
Thank you
