### ISSUE TITLE
Support for Message Sequence Number Removed?

### ISSUE THREAD

**Issue by alexbrinister** [gabime/spdlog#1338]
The custom formatting documentation on the wiki indicates that adding the message sequence number (`%i`) is possible but in at least version 1.4.2, nothing happens when the `%i` option is specified. Furthermore, the `SPDLOG_ENABLE_MESSAGE_COUNTER` macro is missing from `tweakme.h`.

Digging into the release history, it seems that corresponding formatter function, `i_formatter` was removed after version 1.3.1.

Is this feature deprecated? Should it be removed from the documentation?

**Comment by gabime** [comment]
Yes. It was removed. I will update the docs
