### ISSUE TITLE
spdlog scatters logs when caller do chdir

### ISSUE THREAD

**Issue by objectx** [gabime/spdlog#134]
When user pass the relative path to `spdlog::rotate_logger_??` and rotation was occured, `spdlog` simply create a log relative to current directory.

Is it intended ?

# I've created the [example](https://github.com/objectx/spdlog-rotate-test).

**Comment by gabime** [comment]
It is not intended.

(I think) it can be considered a bug. Thanks for reporting

**Comment by agauniyal** [comment]
Still a bug or should be closed?

**Comment by gabime** [comment]
It still exists but I dont think it is really an issue. Since relative path is defined as relative to current working dir spdlog behaves correctly. A full path should be used if this is not a desirable behavior
