### ISSUE TITLE
 details\pattern_formatter-inl.h & details\thread_pool-inl.h should include <cassert>

### ISSUE THREAD

**Issue by jeanga** [gabime/spdlog#1340]
Hi,

When compiling spdlog (via vcpkg, with fmt 6.1.0 with VC2019 preview), I have compilation errors for details\pattern_formatter-inl.h & details\thread_pool-inl.h.

Adding #include <cassert> fixes the error.

HTH,
Jean

**Comment by gabime** [comment]
Fixed. Thanks for reporting,
