### ISSUE TITLE
Potential leak in set_pattern() ?

### ISSUE THREAD

**Issue by MrEliptik** [gabime/spdlog#1341]
Hi, 

First thank you for your amazing work. I've been using SPDlog in my system and it works great. I'm currently using v1.4.1 and running Vlagrind under debian 8 I've seen leaks. It seems to be comming from set_pattern(). Below is the code I'm using to dynamically set levels and patterns for my sinks: 

```
m_logFile_logger->set_level(m_spdlog_levels_map[m_str_level]);
    if (m_add_details) {
        for (auto sink : m_logFile_logger->sinks())
        {
            sink->set_pattern(LOG_FILE_DETAILLED_FORMAT);
        }
    }
    else {
        for (auto sink : m_logFile_logger->sinks())
        {
            sink->set_pattern(LOG_FILE_FORMAT);
        }
    }
```

below, part of the output of valgrind: 

```
==9749== 320 bytes in 10 blocks are indirectly lost in loss record 110 of 122
==9749== at 0x4C29180: operator new(unsigned long) (vg_replace_malloc.c:324)
==9749== by 0x435D8D: std::unique_ptr<spdlog::details::aggregate_formatter, std::default_delete<spdlog::details::aggregate_formatter> > spdlog::details::make_unique<spdlog::details::aggregate_formatter>() (in /home/sot/Documents/multiZR_27_11/lib/liberror_handler/build/bin/Release/test_error_handler)
==9749== by 0x439989: spdlog::pattern_formatter::compile_pattern_(std::string const&) (in /home/sot/Documents/multiZR_27_11/lib/liberror_handler/build/bin/Release/test_error_handler)
==9749== by 0x44E56E: spdlog::sinks::ansicolor_sink<spdlog::details::console_mutex>::set_pattern(std::string const&) (in /home/sot/Documents/multiZR_27_11/lib/liberror_handler/build/bin/Release/test_error_handler)
```

Am I doing something wrong?

**Comment by gabime** [comment]
> First thank you for your amazing work..

👍 Thank you!


Do you see actual leaks or just reports from Valgrind? Sometimes there are false positives.. 

> Am I doing something wrong?

It's hard to tell. Please post a small reproducible example(including the definition of LOG_FILE_DETAILLED_FORMAT/LOG_FILE_FORMAT).

**Comment by MrEliptik** [comment]
Well.. I can't reproduce what I was seing, even with the same program.. It was detected by our automated test suit using valgrind. The thing is I wrapped your libraries with my own classes, so the leak might come from me. 

We can close this for now and I'll come to you again if I have more information. Thanks for your reactivity!
