### ISSUE TITLE
Document whether spdlog is crash-safe

### ISSUE THREAD

**Issue by JackSabbath** [gabime/spdlog#1342]
One feature that is very important for a logger is the crash-safety. That is, that all messages that are in the buffer will be written to their sinks in case the application crashes (throws an unhandled exception etc.), so no information will be lost.

So I want to ask here: Is it actually crash-safe? I couldn't find an information if spdlog is crash-safe or not in it's documentation. I suggest adding that information.
If not, I kindly suggest to implement it.

**Comment by gabime** [comment]
Its not crash safe.
Frankly I don't know of a reliable way to implement it.. If an application crashes then by definition it is in undefined, bad state, including its logging data structures and buffers.

**Comment by JackSabbath** [comment]
KjellKod (Author of G3log) explained his approach on this topic here: https://www.codeproject.com/Articles/288827/g-log-An-efficient-asynchronous-logger-using-Cplus#TOC_crashing

I also read the loguru docs and they seem to follow the same idea: https://emilk.github.io/loguru/index.html#loggingcrashes

It's not much that I can provide, but I hope it's still useful.
