### ISSUE TITLE
Build fails with fmt 6.1.0

### ISSUE THREAD

**Issue by luigino** [gabime/spdlog#1344]
spdlog 1.4.2 on openSUSE Tumbleweed, see [log](https://github.com/gabime/spdlog/files/3921623/spdlog142_fmt610.txt).

No apparent problem using fmt 6.0.0.

**Comment by gabime** [comment]
Please try latest spdlog commit. It has been fixed lately

**Comment by luigino** [comment]
Thanks, https://github.com/gabime/spdlog/commit/1aa9ea92e20142a1ce2f2e1ac40ed1fa781fac19 indeed did the trick.
