### ISSUE TITLE
daily log with rotation, the max_files didn't work as expected

### ISSUE THREAD

**Issue by link1120** [gabime/spdlog#1345]
I had tried two ways, the following are:

1. std::shared_ptr<spdlog::logger> logger = spdlog::create_async_nb<spdlog::sinks::daily_file_sink_mt>("daily_logger", filename, 0, 30, 2);

2. std::shared_ptr<spdlog::logger> logger = spdlog::daily_logger_mt("daily_logger", filename, 0, 30, 2);

Both gave the value of max_files arg 2,  but it didn't work fine. 
How could I use the daily_file_sink to implement that request daily log with rotation?

**Comment by tt4g** [comment]
Your snippet specifies `truncate` argument. `max_files` is not specified.

See the permlink (spdlog 1.4.2): https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/sinks/daily_file_sink.h#L48

**Comment by link1120** [comment]
Thanks a lot. It works fine now. @tt4g
