### ISSUE TITLE
Question: What are the differences in version v.1, master and release

### ISSUE THREAD

**Issue by perevozchikov85** [gabime/spdlog#1346]
OS: Xubuntu 18.04
I do not want to install  spdlog in the system.
1. how to connect a static library to my project?
i download release source version 1.4.2 and compile and i get file libspdlog.a.

**Comment by gabime** [comment]
The "master" branch is old and deprecated.

v1.x is the actual "master" branch that should be used.

Please see [example](https://github.com/gabime/spdlog/tree/v1.x/example) on how to use.
