### ISSUE TITLE
[question] Log line after new daily log is created? 

### ISSUE THREAD

**Issue by elvisoric** [gabime/spdlog#1349]
Hello, 
Is it possible to write information in a log file, using a daily logger, whenever a new file is created? 
Basically, I want to log the same first line to all daily log files.

Is there a way to be notified when a new file is created or to register some kind of callback whenever that happens?

**Comment by gabime** [comment]
Currently, There is no way to do it.  See https://github.com/gabime/spdlog/issues/1225 for discussion about providing such a way in future versions.
