### ISSUE TITLE
tests fail if you set SPDLOG_SHORT_LEVEL_NAMES in tweakme.h (after library was built).

### ISSUE THREAD

**Issue by pavard** [gabime/spdlog#1352]
subj. lot of messages like:
: FAILED:                                                                                                                             │~
  REQUIRE( log_to_str("Some message", "[%-3L] %v", spdlog::pattern_time_type::local, "\n") == "[I  ] Some message\n" ).
proposal for decision: build tests using the headers_only and specifying the expected -DSPDLOG_SHORT_LEVEL_NAMES=... as compile definition.

**Comment by gabime** [comment]
Do the header only tests fail? (cmake -DSPDLOG_BUILD_TESTS_HO=ON ..)

**Comment by pavard** [comment]
(after library was built) - wrong edition. tweakme.h patched before build. the problem applies to both the library and the version with header files. you were misled by my proposal to collect tests with headers_only and specifying SPDLOG_SHORT_LEVEL_NAMES, - this is necessary in order for the tests to fix the values for which they are written.
