### ISSUE TITLE
Warning: #pragma GCC diagnostic

### ISSUE THREAD

**Issue by perevozchikov85** [gabime/spdlog#1354]
Hello, please help me solve problem with this warning:
```
warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
```

**Comment by tt4g** [comment]
@gabime It seems that it was added with 31fc1aca5316ea864c4d78fe11c2180dd2e6e667.

 `-Wimplicit-fallthrough` is supported gcc 7 or above.


I think it can be solved by using `FMT_HAS_CPP_ATTRIBUTE(fallthrough)` or `__has_cpp_attribute(fallthrough)`.

However, I don't have time to set up a gcc environment right now and see if the warning is suppressed.

**Comment by perevozchikov85** [comment]
Sorry all ok, these were my mistakes.
