### ISSUE TITLE
Header order dependency for spdlog/fmt/ostr.h

### ISSUE THREAD

**Issue by gegles** [gabime/spdlog#1356]
My clang-format automatically re-orders my headers alphabetically...

so:
```c++
#include <spdlog/spdlog.h>
#include <spdlog/fmt/ostr.h>
```

Automatically changes it to:
```c++
#include <spdlog/fmt/ostr.h>
#include <spdlog/spdlog.h>
```

Which then seems to generate the following issues:

```
Undefined symbols for architecture x86_64:
  "fmt::v6::format_error::~format_error()", referenced from:
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<int, fmt::v6::basic_format_specs<char> >::on_error() in fasp_io_socket_service_tests.cpp.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned int, fmt::v6::basic_format_specs<char> >::on_error() in fasp_io_socket_service_tests.cpp.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<long long, fmt::v6::basic_format_specs<char> >::on_error() in fasp_io_socket_service_tests.cpp.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned long long, fmt::v6::basic_format_specs<char> >::on_error() in fasp_io_socket_service_tests.cpp.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<__int128, fmt::v6::basic_format_specs<char> >::on_error() in fasp_io_socket_service_tests.cpp.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned __int128, fmt::v6::basic_format_specs<char> >::on_error() in fasp_io_socket_service_tests.cpp.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<char, fmt::v6::basic_format_specs<char> >::on_error() in fasp_io_socket_service_tests.cpp.o
      ...
```

I believe this has to do with `FMT_HEADER_ONLY` not being defined then...

**Comment by gabime** [comment]
I can't reproduce. Can you reproduce  using the latest commit  ? There were some changes regarding this lately.

**Comment by rayferric** [comment]
I was able to reproduce by configuring with `-DBUILD_SHARED_LIBS=ON` and `spdlog_header_only` interface.
Appearently **{fmt}** doesn't cause issues in header-only, static builds with wrong order of includes.
Simple solution is to define `SPDLOG_HEADER_ONLY` yourself or make sure to always include `spdlog.h` before 'ostr.h'.

**Comment by gabime** [comment]
Thanks @rayferric . Useful for anyone who might encounter this.

**Comment by gegles** [comment]
> I was able to reproduce by configuring with `-DBUILD_SHARED_LIBS=ON` and `spdlog_header_only` interface.
> Appearently **{fmt}** doesn't cause issues in header-only, static builds with wrong order of includes.
> Simple solution is to define `SPDLOG_HEADER_ONLY` yourself or make sure to always include `spdlog.h` before `ostr.h`.

Thanks, good to know I was not crazy ;-)
