### ISSUE TITLE
Multiple loggers, sharing the same output sinks but using individual log levels for each sink

### ISSUE THREAD

**Issue by jonasvb** [gabime/spdlog#1357]
Is it possible to create different loggers, sharing the same sinks, but use different log levels for each sink?
For example, I'd like to create a logger in different classes. All theses loggers shall be connected to the same file sink and the same console sink. In addition, each logger should be able to set individual levels for the different sinks.
`
auto shared_console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
auto shared_file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("fileName.txt", true);
spdlog::sinks_init_list sink_list = {sharedFileSink, console_sink};

auto firstLogger = std::make_shared<spdlog::logger>("firstLoggerName", sink_list);
auto secondLogger = std::make_unique<spdlog::logger>("secondLoggerName", sink_list);

/* Now I'd like to set different log levels for different thinks, for example like this. */
// firstLogger and secondLogger are using different logging levels for each sink, but I can not
// seperate the file log level from the console log level for each logger.
firstLogger->set_level(spdlog::level::err);            
secondLogger->set_level(spdlog::level::critical);

// Understandably, only the last levels ("warn" and "info") are adopted here and applied to all loggers
firstLogger->sinks()[0]->set_level(spdlog::level::critical);      // set file log level to critical
firstLogger->sinks()[1]->set_level(spdlog::level::err);           // set console log level to error
secondLogger->sinks()[0]->set_level(spdlog::level::warn);   // set file log level to warn
secondLogger->sinks()[1]->set_level(spdlog::level::info);     // set console log level to info
`
Is there a way to create multiple loggers, sharing all the same sinks, but use individual log levels for each sink? Thank you very much.

**Comment by tt4g** [comment]
You can use `spdlog::sinks::dist_sink` that provide proxy pattern.

```cpp
shared_console_sink->set_level(spdlog::level::trace);

auto console_link_proxy = std::make_shared<spdlog::sinks::dist_sink_mt>();
console_link_proxy->add_sink(shared_console_sink);
console_link_proxy->set_level(spdlog::level::info);

auto firstLogger = std::make_sharedspdlog::logger("firstLoggerName", console_link_proxy);
```

**Comment by jonasvb** [comment]
Thank you very much for your fast answer and your help. But can I use this sink to create loggers with multiple sinks, using different log levels for each sink? I couldn't figure out yet, how this works.
Let's say, I have a console sink and a file sink and I have two different loggers, which are connected to both sinks.

```
using proxy_dist_sink_mt = proxy_dist_sink<std::mutex>;

// init console logging
shared_console_sink->set_level(spdlog::level::trace);
auto console_link_proxy = std::make_shared<spdlog::sinks::proxy_dist_sink_mt>();
console_link_proxy->add_sink(shared_console_sink);
console_link_proxy->set_level(spdlog::level::info);

// init file logging
shared_file_sink->set_level(spdlog::level::trace);
auto file_link_proxy = std::make_shared<spdlog::sinks::proxy_dist_sink_mt>();
file_link_proxy ->add_sink(shared_file_sink);
file_link_proxy ->set_level(spdlog::level::info)

spdlog::sinks_init_list sink_list = {sharedFileSink, file_link_proxy };

auto firstLogger = std::make_sharedspdlog::logger("firstLoggerName", sink_list );
auto secondLogger = std::make_sharedspdlog::logger("secondLoggerName", sink_list );
```


And now I'd like to set individual log levels for each logger and each sink, e.g. like in the table below.

|| firstLogger  | secondLogger |
| ------------- | ------------- | ------------- |
| **FileSink** | critical  | err |
|**ConsoleSink**| warn | info |

I only can configure different log levels for each sink, but than they have to be identical for each logger (e.g. see next table):

|| firstLogger  | secondLogger |
| ------------- | ------------- | ------------- |
| **FileSink** | err| err |
|**ConsoleSink**| warn | warn|

Or a logger with the same log level for each sink  (e.g. next table):

|| firstLogger  | secondLogger |
| ------------- | ------------- | ------------- |
| **FileSink** | err| warn|
|**ConsoleSink**| err| warn|

Is there a way to set individual log levels? Thank you very much.

**Comment by tt4g** [comment]
It is possible to filter by log level with just the sink.

First of all, please understand that logger and sink each perform `level_` filtering with` should_log()`.
Log filtering is performed by logger and sink.
In other words, logger and sink can set different `lebel_`.

* logger

    https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/logger.h#L77-L83

    https://github.com/gabime/spdlog/blob/d52e825bbc7c25566f822d9aef6ff2ba3a3d603b/include/spdlog/logger-inl.h#L67-L70

* sink

    https://github.com/gabime/spdlog/blob/d52e825bbc7c25566f822d9aef6ff2ba3a3d603b/include/spdlog/sinks/sink-inl.h#L12-L20

After understanding this mechanism, consider how to filter at different log levels for each combination of logger and sink.
Probably the best is to have an additional filtering layer between logger and sink.

`proxy_dist_sink` can be added between logger and sink, so it can act as a filtering layer.

Prepare `proxy_dist_sink` for each logger and sink, and specify `spdlog::log_level::trace` for logger, `console_link_proxy`, and `shared_console_sink`.

This should allow you to filter at different log levels for each logger and sink combination.

```cpp
// Set log level.
shared_console_sink->set_level(spdlog::level::trace);
shared_file_sink->set_level(spdlog::level::trace);

// Create proxy_dist_sink for firstLogger.
auto console_link_proxy_for_first = std::make_shared<spdlog::sinks::proxy_dist_sink_mt>();
console_link_proxy_for_first->add_sink(shared_console_sink);
console_link_proxy_for_first->set_level(spdlog::level::warn);

auto file_link_proxy_for_first = std::make_shared<spdlog::sinks::proxy_dist_sink_mt>();
file_link_proxy_for_first->add_sink(shared_file_sink);
file_link_proxy_for_first->set_level(spdlog::level::critical)

spdlog::sinks_init_list sink_list_for_first = {console_link_proxy_for_first, file_link_proxy_for_first};
auto firstLogger = std::make_sharedspdlog::logger("firstLoggerName", sink_list_for_first);
firstLogger->set_level(spdlog::level::trace);


auto console_link_proxy_for_second = std::make_shared<spdlog::sinks::proxy_dist_sink_mt>();
console_link_proxy_for_second->add_sink(shared_console_sink);
console_link_proxy_for_second->set_level(spdlog::level::warn);

auto file_link_proxy_for_second = std::make_shared<spdlog::sinks::proxy_dist_sink_mt>();
file_link_proxy_for_second->add_sink(shared_file_sink);
file_link_proxy_for_second->set_level(spdlog::level::critical)

spdlog::sinks_init_list sink_list_for_first = {console_link_proxy_for_second, file_link_proxy_for_second};
auto secondLogger = std::make_sharedspdlog::logger("secondLoggerName", sink_list_for_first);
secondLogger->set_level(spdlog::level::trace);
```

**Comment by jonasvb** [comment]
Thank you very much. You have helped me a lot!
