### ISSUE TITLE
Get current log level

### ISSUE THREAD

**Issue by caiazza** [gabime/spdlog#1358]
The registry currently allows to set a global log level to be applied to all registered loggers. This level is even stored within the register but there is no way in the API to retrieve it. Is there a reason why that is not done or can it be added?

**Comment by tt4g** [comment]
I think you should create pull request.

**Comment by caiazza** [comment]
I will, as soon as the owner of the projects tells me it is a desirable feature.

**Comment by gabime** [comment]
go for it @
