### ISSUE TITLE
Default shared sinks

### ISSUE THREAD

**Issue by caiazza** [gabime/spdlog#1359]
When creating a new logger and using the registry initialization of that logger, the system currently adds the formatter, error handler and level settings. It may be useful to define a list of default sinks which may be added to the logger in that phase.

**Comment by gabime** [comment]
thats the job of the default logger already

**Comment by caiazza** [comment]
What I mean it's a different thing. The default logger is a single logger with its own set of parameters, among which the sinks. I'm using different loggers for different components, with different logging levels, for example, but I want to share the same sinks, for example the same log file. 

At the moment one can create different loggers, each with its own set of sinks, pass it to the registry Initialize function and the registry will set those other parameters, that is levels, formatter etc.

What I want is to create a logger with a default set of everything, including the sinks, and then change something like the formatter or the log level which, in my case at least, are options the user wants to customize much more than the set of sinks. I'm already doing it using an overlay on top of spdlog, but I think it would be an useful addition to the general project

**Comment by gabime** [comment]
logger->clone() is good for this. it returns a copy with same sinks and can be customized.

**Comment by caiazza** [comment]
Sure, you can do that, but my point is that the Initialize logger function, imho, performs just half a job in this sense. It needs a partially initialized logger in the first place and it only updates some of the logger functionalities to some default value.
From our conversations I realize that we have slightly differing views of the role of the registry in your project. It seems you view your system as a collection of standalone loggers with the registry on top of it to provide some ad-hoc functionality while I see the registry with a more central role.
