### ISSUE TITLE
Truncation breaks with macros

### ISSUE THREAD

**Issue by geiseri** [gabime/spdlog#1360]
It looks like #1297 doesn't work for the macros since `%!` is used for the function name.

**Comment by gabime** [comment]
Are you sure? Not according to [this](https://github.com/gabime/spdlog/blob/v1.x/tests/test_pattern_formatter.cpp#L234) test

**Comment by gabime** [comment]
it works with e.g.```%10!!``` or just with ```%!```

**Comment by geiseri** [comment]
Sorry for the late reply.  I have the following code:

```
spdlog::set_pattern("[%H:%M:%S][%L][%P:%t][%-15!s:%-3#] %v");
```

My goal is to have the file name printed but truncated at 15 characters.  

My logline is:

```
SPDLOG_INFO("Start reading");
```
With `%-15!s` I see the following output:

```
[12:19:30][I][172618:172618][TestBody       s:203] Start reading
```

Without the `%-15s` I see:

```
[08:09:49][I][165683:165683][identity_tests.cpp:203] Start reading
```

What I am looking for is it to output:

```
[08:09:49][I][165683:165683][identity_tests.:203] Start reading
```

It seems that it interprets `%-15!s` as `%-15!` or am I confused about something?

**Comment by gabime** [comment]
> With %-15!s I see the following output:
[12:19:30][I][172618:172618][TestBody       s:203] Start reading

Do you use latest version ? Here is my output:
```c++
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include "spdlog/spdlog.h"

int main(int, char *[]) {
    spdlog::set_pattern("[%H:%M:%S][%L][%P:%t][%-15!s:%-3#] %v");
    spdlog::set_level(spdlog::level::trace);
    SPDLOG_INFO("Start reading");
}
```

```console
[20:59:41][I][22543:22543][example.cpp    :9  ] Start reading
```

**Comment by geiseri** [comment]
I am using 1.4.2 from vcpkg.

**Comment by gabime** [comment]
Please try latest commit. Truncation was added after 1.4.2

**Comment by geiseri** [comment]
Ah, okay.  Are you in a position to have an official release?
