### ISSUE TITLE
Multiple file loggers with the same output file but different patterns 

### ISSUE THREAD

**Issue by jacknsly** [gabime/spdlog#1361]
Hello, I'd like to know, if it's possibe to create mutiple loggers with the same output file, but different patterns. For example:

```cpp
 auto sharedFileSink =
      std::make_shared<spdlog::sinks::basic_file_sink_mt>("fileName.txt");
 auto firstLogger = std::make_shared<spdlog::logger>("firstLoggerName", sharedFileSink);
 firstLogger->set_pattern(">Custom Text 1<: %v");
 auto secondLogger = std::make_shared<spdlog::logger>("secondLoggerName", sharedFileSink);
 secondLogger->set_pattern(">Custom Text 2<: %v");

 SPDLOG_LOGGER_ERROR(firstLogger, "Message 1");
 SPDLOG_LOGGER_ERROR(secondLogger, "Message 2");
```

As expected, I get this output:
```
>Custom Text 2<: Message 1
>Custom Text 2<: Message 2
```
but I'd like to see something like this:
```
>Custom Text 1<: Message 1
>Custom Text 2<: Message 2
```
Are there any ways to get the results I'd like to have?

**Comment by tt4g** [comment]
`spdlog::logger::set_pattern` is shorthand for 'spdlog::logger::set_formatter'

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/logger.h#L330-L334

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/logger-inl.h#L105-L109

> As expected, I get this output:

I think it is not supported yet.
You need to create a custom sink.

**Comment by gabime** [comment]
Right, there can be only format per sink.
