### ISSUE TITLE
Your suggestion needed

### ISSUE THREAD

**Issue by chengm349** [gabime/spdlog#1364]
[FtSpdlogStream.txt](https://github.com/gabime/spdlog/files/3982737/FtSpdlogStream.txt)
Following this ticket's (https://github.com/gabime/spdlog/issues/1362) discussion, I need to re-compile spdlog. Take this opportunity I downloaded the latest spdlog code. However my wrapper failed to pass:

FtSpdlogStream.h:38:69: error: invalid use of void expression
             spdlog::default_logger()->trace(to_string_view(os.m_buf));
                                                                     ^
FtSpdlogStream.h: In function ‘FtSpdlogDebugStream& endl(FtSpdlogDebugStream&)’:
FtSpdlogStream.h:58:68: error: use of deleted function ‘fmt::v6::basic_memory_buffer<char>::basic_memory_buffer(const fmt::v6::basic_memory_buffer<char>&)’
             spdlog::default_logger()->debug(to_string_view(os.m_buf));

3 months' ago spdlog src was ok for my wrapper.

By checking its definition, seems no change:
template<typename... Args>
inline void debug(string_view_t fmt, const Args &... args)
{
    default_logger_raw()->debug(fmt, args...);
}

I don't know fmt. Should I change fmt::memory_buffer m_buf  defined in FtSpdlogStream.h?

**Comment by chengm349** [comment]
If I want to get 3 months ago src, how to do it?

**Comment by tt4g** [comment]
> If I want to get 3 months ago src, how to do it?

Try `git checkout v4.4.2`.

Other ways:

1. Visit this project GitHub page.
2. Change "Branch" combo box to "Tags" -> "v1.4.2".
3. "Clone or download" -> "Download ZIP"

**Comment by chengm349** [comment]
could be 1.4.0. thanks.

BTW, by that time there was only spdlog.cpp and if static usage way, user is supposed to copy the cpp to his project folder. Now there are several cpp files. All should be copied?
