### ISSUE TITLE
output to ostream, variable eta...

### ISSUE THREAD

**Issue by ElonH** [gabime/spdlog#1365]
Spdlog can output log message to stdout, file, syslog...
Is it a way to build a logger based on general ostream (rather than std::cout ) or buffer that the log message can be get from ostream or buffer ?
than I can show the message via dialog or do other thing.

**Comment by tt4g** [comment]
You can create custom sink that is buffering log message.
And use `splog::sinks::dist_sink` to combine another sink and your custom sink.

See this comment before create custom sink:

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/sinks/base_sink.h#L5-L10

I think `splog::sinks::dist_sink` is custom sink reference implementation will help you:  https://github.com/gabime/spdlog/blob/v1.4.2/include/spdlog/sinks/dist_sink.h

**Comment by tt4g** [comment]
I'm forget `spdlog::details::backtracer` that is like for buffer.
It is will help you for buffer sink implementation.

**Comment by gabime** [comment]
The new (and recommended) way is to use the [ringbuffer sink] and use its ‘ last_formatted(N)’
 to get the last N messages.
