### ISSUE TITLE
static usage

### ISSUE THREAD

**Issue by chengm349** [gabime/spdlog#1366]
There was only spdlog.cpp in older src and if static usage way, user is supposed to copy the cpp to his project folder. Now there are several cpp files. All should be copied?

**Comment by chengm349** [comment]
seems the version I need is earlier than 1.4.0 bcos my spdlog.cpp size is

-rw-r--r--  1 mcheng flexusr  7533 Dec 20 09:14 spdlog.cpp

Wondering whether there is anyway to get that version.

**Comment by tt4g** [comment]
If you need static library, It is recommended that you do not copy the spdlog source to the project, only build and install spdlog project.

The following command is builds spdlog with CMake (https://github.com/gabime/spdlog/blob/v1.4.2/README.md#static-lib-version-recommended---much-faster-compile-times):

```bash
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j
```

Then, run `make install` to install spdlog your system.

Example of using the installed spdlog in a CMake project: https://github.com/gabime/spdlog/blob/v1.4.2/example/CMakeLists.txt

**Comment by chengm349** [comment]
seems the version I need is earlier than 1.4.0 bcos my spdlog.cpp size is
-rw-r--r-- 1 mcheng flexusr 7533 Dec 20 09:14 spdlog.cpp
Wondering whether there is anyway to get that version.

ver 1.4.0/+ give me the same problem:

FtSpdlogStream.h:38:69: error: invalid use of void expression
             spdlog::default_logger()->trace(to_string_view(os.m_buf));
                                                                     ^
FtSpdlogStream.h: In function ‘FtSpdlogDebugStream& endl(FtSpdlogDebugStream&)’:
/fs02/home/thirdparty/spdlog2/include/FtSpdlogStream.h:58:68: error: use of deleted function ‘fmt::v6::basic_memory_buffer<char>::basic_memory_buffer(const fmt::v6::basic_memory_buffer<char>&)’
             spdlog::default_logger()->debug(to_string_view(os.m_buf));

I need to solve my crash issue asap. Solving the above compilation issue is my last choice.

**Comment by tt4g** [comment]
Maybe the template parameter `SIZE` of `fmt::basic_memory_buffer` is different.

it is 250 that spdlog internal using size but `fmt::memory_buffer` is 500 as default.

https://github.com/gabime/spdlog/blob/4f66313440fe4d307b1d1e0a2550a9c12af75a95/include/spdlog/common.h#L105

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/fmt/bundled/format.h#L532-L534

You are using `fmt::memory_buffer m_buf` in `FtSpdlogStream`: https://github.com/gabime/spdlog/issues/1362#issuecomment-566824493

**Comment by chengm349** [comment]
you are right. I changed to sdplog::memory_buf_t. compilation is ok at least.
