### ISSUE TITLE
Can't display source file name and line number

### ISSUE THREAD

**Issue by ScottYang1982** [gabime/spdlog#1368]
when try to set pattern like this:
`spdlog::set_pattern("[%D %H:%M:%S %e] [%^%l%$] [thread %t]  %@ %v");`
Even "%@" flag included, no source file name and line number printed, could anyone tell me why?
And how to correctly print out file name and line number? thank you!

**Comment by tt4g** [comment]
Should you use logging macros such as `SPDLOG_TRACE`, `SPDLOG_LOGGER_TRACE`, etc.

See wiki: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

And see permlink: 

https://github.com/gabime/spdlog/blob/1f5f17622ed2c01831337cef72e17c0d8985993d/include/spdlog/spdlog.h#L276-L336

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/tweakme.h#L122-L127

https://github.com/gabime/spdlog/blob/1549ff12f1aa61ffc4d9a8727c519034724392a0/include/spdlog/common.h#L127-L133
