### ISSUE TITLE
spdlog::create const reference

### ISSUE THREAD

**Issue by smessmer** [gabime/spdlog#137]
Line 111 in spdlog_impl.h is

    inline std::shared_ptr<spdlog::logger> spdlog::create(const std::string& logger_name, const Args&... args)

This prevents using it with ostream_sink, because the ostream_sink constructor needs a non-const reference to a std::ostream as parameter but this line in spdlog_impl.h casts it to a const reference.

**Comment by gabime** [comment]
Fixed in b85662c536a8b347c3528f3df59c42fce151add4
