### ISSUE TITLE
Can spdlog create folders?

### ISSUE THREAD

**Issue by MuFatty** [gabime/spdlog#1374]
I read the following passage in the wiki(https://github.com/gabime/spdlog/wiki/4.-Sinks):
"It is the user's responsibility to create any log folder they need. Spdlog will not attempt to create any folders, only files."
But when I used the following code, I found that spdlog could create folders:

```c++
auto basic_log = spdlog::basic_logger_st("BasicLog", "logs/basic_log.txt");
basic_log->set_level(spdlog::level::debug);
basic_log->info("log contents {0} {1} {2}", 1, 2.1, "ele3");
spdlog::drop_all(); 
```

Is there something wrong with that?

**Comment by gabime** [comment]
spdlog do create folders. This is a new feature that wasn't yet officially released.

**Comment by MuFatty** [comment]
> spdlog do create folders. This is a new feature that wasn't yet officially released.

thank you

**Comment by rupak-d** [comment]
can I get it to create a new folder in the /var/log directory?
