### ISSUE TITLE
Unable to compile inside Docker container

### ISSUE THREAD

**Issue by zoonman** [gabime/spdlog#1379]
```
In file included from /usr/include/spdlog/common.h:38,
                 from /usr/include/spdlog/spdlog.h:12,
                 from /app/src/main.cpp:8:
/usr/include/spdlog/fmt/fmt.h:22:10: fatal error: bundled/core.h: No such file or directory
   22 | #include "bundled/core.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

I use in CMakeLists.txt:
```
find_package(spdlog)
```

And have in Dockerfile:
```
RUN apk update \
    && apk upgrade \
    && apk add --update  --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
        --virtual .build-deps \
        alpine-sdk \
        cmake \
        pkgconf \
        doxygen \
        build-base \
        openssl-dev \
        python3 \
        rabbitmq-c \
        rabbitmq-c-dev \
        libbson \
        libbson-dev \
        libbsoncxx \
        libbsoncxx-dev \
        snappy-dev \
        boost-dev \
        libgcc \
        libstdc++ \
        musl \
        fmt-dev \
        spdlog \
        spdlog-dev
```

**Comment by zoonman** [comment]
Also MacPorts are really outdated.

**Comment by tt4g** [comment]
As far as I look at the package information of alpine, "spdlog/bundled/core.h" should not be used because `SPDLOG_FMT_EXTERNAL` is defined by CMake: https://pkgs.alpinelinux.org/package/edge/community/x86_64/spdlog

My guess is that you need to add `target_link_libraries` to your `CMakeLists.txt` as follows (replace `your_target` with the executable target for your project):

```diff
- find_package(spdlog)
+ find_package(spdlog REQUIRED)

+ target_link_libraries(your_target PRIVATE spdlog::spdlog)
```

**Comment by tt4g** [comment]
This repository does not manage alpine package.
I recommend creating an issue in the alpine project: https://pkgs.alpinelinux.org/packages

**Comment by zoonman** [comment]
Thank you! I had to add your spdlog as git submodule and compile during Docker image build.
Is there a way to skip the tests building?

**Comment by tt4g** [comment]
> Is there a way to skip the tests building?

Define `SPDLOG_BUILD_TESTS` and `SPDLOG_BUILD_TESTS_HO`.
e.g. `cmake -DSPDLOG_BUILD_TESTS=OFF -DSPDLOG_BUILD_TESTS_HO=OFF (other options)`.

**Comment by zoonman** [comment]
Thank you for the help. Closing the issue.

**Comment by sudoLife** [comment]
This exact problem is happening in the [Arch community package](https://archlinux.org/packages/community/x86_64/spdlog/)

`In file included from /usr/include/spdlog/common.h:36,
                 from /usr/include/spdlog/spdlog.h:12,
                 from spdlog_test.cpp:1:
/usr/include/spdlog/fmt/fmt.h:22:10: fatal error: spdlog/fmt/bundled/core.h: No such file or directory
   22 | #include <spdlog/fmt/bundled/core.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by tt4g** [comment]
@sudoLife It seems that `spdlog/fmt/bundled/core.h` is not included in the package.
I can't give advice because I don't know what the options are when building the package. Please check with the Arch Community for usage.
