### ISSUE TITLE
Getting multiple definition errors when trying to build

### ISSUE THREAD

**Issue by Dislousius** [gabime/spdlog#1380]
Hello.
I've been trying to make spdlog work on my build setup but can't get it to work 100% of the time.
What I mean with this is that when I try to do something as simple as SPDLOG_INFO("test {}", 1), compiling fails. However, this is not always the case. It only happens when I try to print logging from within two different projects (which are linked) AND when I provide extra args such as "1" in the given example.
If I would just print SPDLOG_INFO("test") everywhere in my project then this problem doesn't even arise.  The build errors I get are listed below:

[ 17%] Built target spdlog
[ 57%] Built target glfw
[ 62%] Built target glad
[ 75%] Built target Tools
Scanning dependencies of target Application
[ 77%] Building CXX object Application/CMakeFiles/Application.dir/src/Main.cpp.obj
[ 80%] Linking CXX executable ..\Debug\bin\Application.exe
../Debug/lib/libspdlogd.a(fmt.cpp.obj): In function `fmt::v6::format_error::~format_error()':
D:/Development/git/uilibrarysandbox/third_party/spdlog/include/spdlog/fmt/bundled/format-inl.h:229: multiple definition of `fmt::v6::format_error::~format_error()'
../Debug/lib/libTools.dll.a(d000160.o):(.text+0x0): first defined here
../Debug/lib/libspdlogd.a(fmt.cpp.obj): In function `fmt::v6::internal::error_handler::on_error(char const*)':
D:/Development/git/uilibrarysandbox/third_party/spdlog/include/spdlog/fmt/bundled/format-inl.h:954: multiple definition of `fmt::v6::internal::error_handler::on_error(char const*)'
../Debug/lib/libTools.dll.a(d000638.o):(.text+0x0): first defined here
../Debug/lib/libspdlogd.a(fmt.cpp.obj): In function `char fmt::v6::internal::thousands_sep_impl<char>(fmt::v6::internal::locale_ref)':
D:/Development/git/uilibrarysandbox/third_party/spdlog/include/spdlog/fmt/bundled/format-inl.h:209: multiple definition of `char fmt::v6::internal::thousands_sep_impl<char>(fmt::v6::internal::locale_ref)'
../Debug/lib/libTools.dll.a(d000864.o):(.text+0x0): first defined here
../Debug/lib/libspdlogd.a(fmt.cpp.obj): In function `char fmt::v6::internal::decimal_point_impl<char>(fmt::v6::internal::locale_ref)':
D:/Development/git/uilibrarysandbox/third_party/spdlog/include/spdlog/fmt/bundled/format-inl.h:213: multiple definition of `char fmt::v6::internal::decimal_point_impl<char>(fmt::v6::internal::locale_ref)'
../Debug/lib/libTools.dll.a(d000860.o):(.text+0x0): first defined here
../Debug/lib/libspdlogd.a(fmt.cpp.obj): In function `char* fmt::v6::internal::sprintf_format<double>(double, fmt::v6::internal::buffer<char>&, fmt::v6::internal::sprintf_specs)':
D:/Development/git/uilibrarysandbox/third_party/spdlog/include/spdlog/fmt/bundled/format-inl.h:756: multiple definition of `char* fmt::v6::internal::sprintf_format<double>(double, fmt::v6::internal::buffer<char>&, fmt::v6::internal::sprintf_specs)'
../Debug/lib/libTools.dll.a(d000762.o):(.text+0x0): first defined here
../Debug/lib/libspdlogd.a(fmt.cpp.obj): In function `char* fmt::v6::internal::sprintf_format<long double>(long double, fmt::v6::internal::buffer<char>&, fmt::v6::internal::sprintf_specs)':
D:/Development/git/uilibrarysandbox/third_party/spdlog/include/spdlog/fmt/bundled/format-inl.h:756: multiple definition of `char* fmt::v6::internal::sprintf_format<long double>(long double, fmt::v6::internal::buffer<char>&, fmt::v6::internal::sprintf_specs)'
../Debug/lib/libTools.dll.a(d000763.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [Application\CMakeFiles\Application.dir\build.make:218: Debug/bin/Application.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:207: Application/CMakeFiles/Application.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2

I'm not sure what I'm doing wrong exactly as I can in fact get it to build under certain circumstances as I explained earlier. Also not sure but perhaps this has something to do with my CMAKE configuration?

To simplify, I've created a new project with the bare minimum to reproduce this problem.

Application contains a file main.cpp with the following contents

    #include "Logger.h"
    #include <iostream>

    int main()
    {
	    DEBUGERROR("error in main {}", 1);
	    getchar();
	    return 0;
    }

Tools includes the following:

**Logger.cpp**

    #pragma once
    #include <string>
    #include <iostream>
    #include <spdlog/spdlog.h>
    
    #define DEBUGERROR(userFormat,...) spdlog::error("[{}] [{}:{}] " userFormat, __COMPONENT__, __func__, __LINE__, ##__VA_ARGS__);
    #define DEBUGINFO(userFormat,...) spdlog::info("[{}] [{}:{}] " userFormat, __COMPONENT__, __func__, __LINE__, ##__VA_ARGS__);;
    #define DEBUGWARNING(userFormat,...) spdlog::warn("[{}] [{}:{}] " userFormat, __COMPONENT__, __func__, __LINE__, ##__VA_ARGS__);
    #define DEBUGCRITICAL(userFormat,...) spdlog::critical("[{}] [{}:{}] " userFormat, __COMPONENT__, __func__, __LINE__, ##__VA_ARGS__);
    
    namespace Tools
    {
        class Logger
        {
        public:
            void Logger::init()
            {
                spdlog::set_pattern("%^[thread %t] [%H:%M:%S] [%l] [%s:%#] %v%$");
            }
        };
    } 

**Printer.h**

    #pragma once
    
    class Printer
    {
    public:
        Printer();
        virtual ~Printer();
        static void printError();
    private:
    }; 

**Printer.cpp**

    #include "printer.h"
    #include "Logger.h"
    
    Printer::Printer()
    {
    
    }
    Printer::~Printer()
    {
    
    }
    
    void Printer::printError()
    {
        DEBUGERROR("printing an error {}", 1);
    } 

To build this, I've created 3 cmake files.

**Root CMakeLists.txt**

    cmake_minimum_required(VERSION 3.15.3)
    project(AllProjects LANGUAGES CXX C)
    
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/lib)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/lib)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/bin)
    
    add_subdirectory("third_party/spdlog")
    add_subdirectory("Tools")
    add_subdirectory("Application") 

**Application CMakeLists.txt**

    cmake_minimum_required(VERSION 3.15.3)
    project(Application LANGUAGES CXX C)
    add_definitions( /D__COMPONENT__="app" )
    
    file(GLOB_RECURSE SOURCES src/*.cpp)
    
    set(INCLUDEDIR ${PROJECT_SOURCE_DIR}/include
                   ${CMAKE_SOURCE_DIR}/Tools/include
    )
    
    include_directories(${INCLUDEDIR})
    add_executable(Application ${SOURCES})
    target_link_libraries (Application Tools) 

**Tools CMakeLists.txt**

    cmake_minimum_required(VERSION 3.15.3)
    project(Tools LANGUAGES CXX C)
    
    add_definitions( /D__COMPONENT__="tools" )
    
    file(GLOB_RECURSE SOURCES src/*.cpp
    )
    
    set(INCLUDEDIR ${PROJECT_SOURCE_DIR}/include
        ${CMAKE_SOURCE_DIR}/third_party/spdlog/include
    )
    
    include_directories(${INCLUDEDIR})
    
    add_library(Tools SHARED ${SOURCES})
    target_link_libraries (Tools spdlog) 

Finally, I'm using the following set of commands to get everything to build:

    cd build
    cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "MinGW Makefiles" ..
    mingw32-make
    cd .. 

So in the end, the structure of the project is as follows:

Project

 - Application
     - include
     - src
     - CMakeLists.txt
 - Tools
     - include
     - src
     - CMakeLists.txt
 - third_party
     - spdlog repository as git submodule
 - CMakeLists.txt

So yea, I'm not sure if this is something I'm doing wrong or not.
Thank you for your time.

**Comment by tt4g** [comment]
My guess is that the Application `CMakeLists.txt` is missing the spdlog include directory.

```diff
cmake_minimum_required(VERSION 3.15.3)
project(Application LANGUAGES CXX C)
add_definitions( /D__TEST__="app" )

file(GLOB_RECURSE SOURCES src/*.cpp)
file(GLOB_RECURSE INCLUDES include/*.h)

set(INCLUDEDIR ${PROJECT_SOURCE_DIR}/include
			   ${CMAKE_SOURCE_DIR}/Tools/include
			   ${CMAKE_SOURCE_DIR}/third_party/glm/glm
			   ${CMAKE_SOURCE_DIR}/third_party/glfw/include
			   ${PROJECT_SOURCE_DIR}/third_party/glad/include
+                          ${CMAKE_SOURCE_DIR}/third_party/spdlog/include
)

include_directories(${INCLUDEDIR})

set(GLAD "${PROJECT_SOURCE_DIR}/third_party/glad/include/glad"
         "${PROJECT_SOURCE_DIR}/third_party/glad/src/glad.c")

add_executable(Application ${SOURCES})
add_library(glad STATIC ${PROJECT_SOURCE_DIR}/third_party/glad/src/glad.c)
target_link_libraries (Application Tools)
target_link_libraries (Application glad "${CMAKE_DL_LIBS}")
target_link_libraries (Application glfw ${GLFW_LIBRARIES})

add_custom_command(TARGET Application POST_BUILD
                   COMMAND ${CMAKE_COMMAND} -E copy_directory
                       ${PROJECT_SOURCE_DIR}/resources ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/resources)
```

**Comment by Dislousius** [comment]
Including "${CMAKE_SOURCE_DIR}/third_party/spdlog/include" in application's cmakelists unfortunately doesn't work.

**Comment by tt4g** [comment]
Try the following changes:

```diff
cmake_minimum_required(VERSION 3.15.3)
project(Application LANGUAGES CXX C)
add_definitions( /D__TEST__="app" )

file(GLOB_RECURSE SOURCES src/*.cpp)
file(GLOB_RECURSE INCLUDES include/*.h)

set(INCLUDEDIR ${PROJECT_SOURCE_DIR}/include
			   ${CMAKE_SOURCE_DIR}/Tools/include
			   ${CMAKE_SOURCE_DIR}/third_party/glm/glm
			   ${CMAKE_SOURCE_DIR}/third_party/glfw/include
			   ${PROJECT_SOURCE_DIR}/third_party/glad/include
-                          ${CMAKE_SOURCE_DIR}/third_party/spdlog/include
)

include_directories(${INCLUDEDIR})

set(GLAD "${PROJECT_SOURCE_DIR}/third_party/glad/include/glad"
         "${PROJECT_SOURCE_DIR}/third_party/glad/src/glad.c")

add_executable(Application ${SOURCES})
add_library(glad STATIC ${PROJECT_SOURCE_DIR}/third_party/glad/src/glad.c)
target_link_libraries (Application Tools)
target_link_libraries (Application glad "${CMAKE_DL_LIBS}")
target_link_libraries (Application glfw ${GLFW_LIBRARIES})
+ target_link_libraries (Application spdlog)

add_custom_command(TARGET Application POST_BUILD
                   COMMAND ${CMAKE_COMMAND} -E copy_directory
                       ${PROJECT_SOURCE_DIR}/resources ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/resources)
```

spdlog as target is provided by `add_subdirectory("third_party/spdlog")` in Root `CMakeLists.txt`

**Comment by Dislousius** [comment]
Not working either. But from the output given while building, it seems that something in my Tools library is conflicting with something in the spdlog library for some reason.

**Comment by tt4g** [comment]
There may be a header name conflict or a problem with the configuration of the CMake project.

The result of `file (GLOB_RESOURCE ...)` may include spdlog files.

**Comment by Dislousius** [comment]
It may not be a problem with my CMAKE configuration after all.
I have created a new project that only contains the bare minimum to reproduce this problem.
However, this time I have compiled it using visual studio's compiler whereas I normally would build using mingw64. It compiles just fine with the MVCM.
However, I remember my project building succesfully in the past on my previous PC, which was also using MinGW64 although it was a custom build that I got from somewhere. The current MinGW64 I'm using comes from the official website this time. I'm now trying to see what the official MinGW32 does with this.

**Comment by Dislousius** [comment]
Unfortunately couldn't get it to work in other versions either. MinGW32 can't compile std::recursive_mutex even if I've installed pthreading support. MinGW64 with a way older gcc compiler results in the same redefinition errors.

**Comment by Dislousius** [comment]
Unfortunately couldn't get it to work in other versions either. MinGW32 can't compile std::recursive_mutex even if I've installed pthreading support. MinGW64 with a way older gcc compiler results in the same redefinition errors.

**Comment by tt4g** [comment]
You may have installed the spdlog static library on your system.

`find_package` finds the installed spdlog. And the spdlog found is linked to your application by `target_link_library`.

In this situation, it is possible that the header file of spdlog added to the project by `add_subdirectory("third_party/spdlog")` and `include_directories(${CMAKE_SOURCE_DIR}/third_party/spdlog/include)` has a conflict.

Try removing `add_subdirectory` and building.

**Comment by Dislousius** [comment]
I've tried your suggestion but then I just get:
C:/PROGRA~1/MINGW-~1/X86_64~1.4-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.4/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lspdlog

I've now also created a new project, only including the bare minimum needed to reproduce this problem. I'l edit my main post to include this more concrete example.

**Comment by Dislousius** [comment]
Okey, I have finally found the solution although I'm not exactly sure why this fixes it.
In my application's CMakeLists.txt, I had to add "${CMAKE_SOURCE_DIR}/third_party/spdlog/include" to the includes as tt4g suggested. But at the same time, I needed to change target_link_libraries (Tools spdlog) in Tools' CMakeLists.txt to target_link_libraries (Tools PRIVATE spdlog). 
Now everything compiles just fine. 
So yea, not sure why I need the private part. Since the intention is/was to have tools contain spdlog so that I wouldn't need to include spdlog itself in all other projects that will eventually link with tools.
So for now, I'd need to make sure every project also includes spdlog seperately, even though my tools lib should have it.
Thanks for the help tt4g. I'll close this soon. Perhaps someone could still shed some light as to why I still need to include spdlog seperately and make it private to tools.

**Comment by tt4g** [comment]
If you specify `PRIVATE` for `target_link_library`, the library will not be linked to another object that depends on that CMake target.

* https://cmake.org/cmake/help/v3.16/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents

Now the difference is that it is only linked to Tools.
Previously, your configuration linked spdlog to Tools and Application.
The duplicate definition may have been caused by this.

I've developed a project with an executable application with a main function and a library just like you.
Both depended on spdlog with `target_link_library (target PUBLIC spdlog ...)`, but this project could be built with MSVC.

I don't know why it doesn't work with MinGW.

**Comment by tt4g** [comment]
My guess.

Tools is shared library (`add_library(Tools SHARED ${SOURCES})`) and `tools.so` have spdlog symbols from `spdlog.a`.
And application link targets include `tools.so` and `spdlog.a`.

The compiler detects the spdlog symbols twice in `tools.so` and `spdlog.a` and assumes that a link error has occurred.
