### ISSUE TITLE
Shared sinks across multiple files with multiple classes.

### ISSUE THREAD

**Issue by ericwomer** [gabime/spdlog#1381]
I know you can register loggers for accessing loggers via spdlog::get() but is there an equivalent for sinks, I want a category system with options based on severity of the level of message to either report it to the console and file, or just the file. I want to be able for every class to set its own separate category, but I only found methods for registering loggers for global access and not sinks.

**Comment by tt4g** [comment]
spdlog 1.4.2 and earlier does not directly manage sink.
Access via logger.

One solution is to manage the sink yourself with `std::unordered_map` or `std::unordered_set`.
If you want the sink to have additional features, create a custom sink.

The easiest way to get all the sinks of a registered logger is to call `spdlog::apply_all()`.

Example:

```cpp
#include "spdlog/spdlog.h"

#include <unordered_set>

std::unordered_set<std::shared_ptr<spdlog::sinks::sink>> colloct_all_sinks()
{
    std::unordered_set<std::shared_ptr<spdlog::sinks::sink>> allSinks;

    spdlog::apply_all([&allSinks](std::shared_ptr<spdlog::logger> logger)
    {
        for (auto sink : logger->sinks()) {
            allSinks.insert(sink);
        }
    });

    return allSinks;
}
```

However, this example cannot access nested sink in a proxy sink such as `spdlog::sinks::dist_sink`, `spdlog::sinks::dup_filter_sink`.
