### ISSUE TITLE
spdlog/details/pattern_formatter.h:100:9: error: ‘assert’ was not declared in this scope

### ISSUE THREAD

**Issue by zenfey** [gabime/spdlog#1382]
when defined SPDLOG_FMT_EXTERNAL with fmt::v6, pattern_formatter.h missed <cassert> header.

spdlog/details/pattern_formatter.h: 100 : 9: error: ‘assert’ was not declared in this scope
[build]          assert(count <= spaces_.size());
[build]          ^~~~~~

**Comment by gabime** [comment]
Please try latest spdlog commit. It has been fixed lately
