### ISSUE TITLE
Question Clone to another DLL

### ISSUE THREAD

**Issue by Athesis** [gabime/spdlog#1383]
Hi,

I Try using spdlog across multiple dll's (They all work together). It works fine for the first initialized dll, but as soon I try to clone it over to the other dll's it won't work anymore. Is there a good method of copying spdlog over so every dll uses the same sinks?

**Comment by tt4g** [comment]
NOTE The global registry of spdlog 1.4.2 or earlier is not share between dll's.

This wiki page for your helpful: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

**Comment by Athesis** [comment]
Thanks @tt4g for your time. I'm aware of the Wiki-Article, but this does create new sinks and I would have to create them for every dll, including routines to select what sinks should be used. I like to use the same sinks. 

I've seen the "clone" function in "logger.h", it's described as exactly what I would need but it seems that it has not been further documented besides the description line inside the source code.

**Comment by tt4g** [comment]
This project has several undocumented features that do not belong to namespace `spdlog::details`.

I think you can use `spdlog::logger::close()`, it has tests:

https://github.com/gabime/spdlog/blob/feefb7e7e2eff57ea7bf7fa7397826ede6aaffe5/tests/test_misc.cpp#L96-L102
