### ISSUE TITLE
unable to get dist_sink example (from wiki page) to compile

### ISSUE THREAD

**Issue by djernst** [gabime/spdlog#1386]
I have tried to get dist_sink to compile.  Is there complete example of how this works?

I attempted to compile the following straight from the wiki example...

auto dist_sink = make_shared<spdlog::sinks::dist_sink_st>();
auto sink1 = make_shared<spdlog::sinks::stdout_sink_st>();
auto sink2 = make_shared<spdlog::sinks::simple_file_sink_st>("mylog.log");

Compiler complains that simple_file_sink_st is not a member of spdlog::sinks

**Comment by gabime** [comment]
The wiki is lacking the include

You need to 
```c++
#include spdlog/sinks/dist_sink.h
```
