### ISSUE TITLE
async logger is slower than the sync logger.

### ISSUE THREAD

**Issue by chloro-pn** [gabime/spdlog#1391]
Did I make mistake in using async logger?

this is sync result:
source code:
```
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/async.h"
#include <iostream>
#include <thread>
#include <chrono>

int main()
{
    //auto file = spdlog::basic_logger_st<spdlog::async_factory>("async_file_logger","basic.txt");
    auto file = spdlog::basic_logger_st("basic_logger","basic.txt");
    using namespace std::chrono;
    time_point<system_clock, milliseconds> start = time_point_cast<milliseconds>(system_clock::now());
    std::vector<std::thread> ths;
    for(int i = 0;i<1;++i) {
        ths.emplace_back([&]()->void {
            for(int i = 0;i<1000000;++i) {
                file->info("Youth is not a time of life; it is a state of mind. It is not a matter of rosy cheeks. {}",i);
            }
       });
    }
    for(auto& each : ths) {
        each.join();
    }
    time_point<system_clock,milliseconds> end = time_point_cast<milliseconds>(system_clock::now());
    std::cout << "use : " << (end - start).count() << " milliseconds." << std::endl;
    return 0;
}
```
output : use : 593 milliseconds.
***
async result:
source code:
```#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/async.h"
#include <iostream>
#include <thread>
#include <chrono>

int main()
{
    auto file = spdlog::basic_logger_st<spdlog::async_factory>("async_file_logger","basic.txt");
    //auto file = spdlog::basic_logger_st("basic_logger","basic.txt");
    using namespace std::chrono;
    time_point<system_clock, milliseconds> start = time_point_cast<milliseconds>(system_clock::now());
    std::vector<std::thread> ths;
    for(int i = 0;i<1;++i) {
        ths.emplace_back([&]()->void {
            for(int i = 0;i<1000000;++i) {
                file->info("Youth is not a time of life; it is a state of mind. It is not a matter of rosy cheeks. {}",i);
            }
       });
    }
    for(auto& each : ths) {
        each.join();
    }
    time_point<system_clock,milliseconds> end = time_point_cast<milliseconds>(system_clock::now());
    std::cout << "use : " << (end - start).count() << " milliseconds." << std::endl;
    return 0;
}
```
output :use : 1707 milliseconds.
***
environment : macOS 10.14.4 1.8GHz i5

**Comment by chloro-pn** [comment]
Thank you for answering my question.but I also have a question. : )
In my understanding, sync logger means that you append a log to logfile without memory buffer, and async logger need memory buffer to cache the logs and append to logfile  together.So async logger calls fewer system api and gets more throughput, which makes async logger faster, isn’t it?

**Comment by gabime** [comment]
No. because there is extra cost of copying the message to the queue and popping it later. Also there is a cost in synchronizing the queue access which can be high if you push from multiple threads in an infinite loop like in your test. 
Add to this the fact that in OSX ```std::mutex``` are known to be much [slower].(https://stackoverflow.com/questions/22899053/why-is-stdmutex-so-slow-on-osx)

**Comment by chloro-pn** [comment]
Get it! thanks a lot.

**Comment by randomizedthinking** [comment]
> No, because there is extra cost of copying the message to the queue and popping it later. Also there is a cost in synchronizing the queue access which can be high under heavy contention if you push from multiple threads in a tight loop like in your test. Add to this the fact that in OSX `std::mutex` are known to be much [slower](https://stackoverflow.com/questions/22899053/why-is-stdmutex-so-slow-on-osx).

@gabime I am late to the discussion, but one question. Is it possible to use `unique_ptr` to avoid one extra copy for the async logger? The `unique_ptr` might be introduced to all loggers to ensure a unified interface.

**Comment by gabime** [comment]
What do you mean? Please provide example.
