### ISSUE TITLE
how to create daily log with rotating feature and log file size is more than 1GB?

### ISSUE THREAD

**Issue by ruoshui1314** [gabime/spdlog#1393]
hi
   thank you for your library.I would like to create a log file that could be created everyday and rotated with 30 days.The size may be more than 1GB but I hope it could be recorded to one file in each day.In other words, the file is only one in everyday.
Is there any suggestion or solution that could help me to solve it?

**Comment by ruoshui1314** [comment]
The reason is that the max size is less than 1GB using rotating_logger_mt method which could create only 512MB size of file.

**Comment by ruoshui1314** [comment]
sorry,I find the interface.
I check it out in preview branch in my local repository.

**Comment by Edassap** [comment]
which interface, can you point out? I have same question!

**Comment by ruoshui1314** [comment]
> which interface, can you point out? I have same question!

``` shell

template<typename Factory = spdlog::synchronous_factory>
inline std::shared_ptr<logger> daily_logger_mt(
    const std::string &logger_name, const filename_t &filename, int hour = 0, int minute = 0, bool truncate = false, uint16_t max_files = 0)
{
    return Factory::template create<sinks::daily_file_sink_mt>(logger_name, filename, hour, minute, truncate, max_files);
}

```

It is ok to set parameter truncate to true.

**Comment by danielabutbul01** [comment]
@ruoshui1314, how "truncate" arg is related to the rotating feature? From what I saw in the code, it just overwrites the file content. How is that described as limiting the log file?
