### ISSUE TITLE
In-Memory Caching / Logging

### ISSUE THREAD

**Issue by kumaryashwanth07** [gabime/spdlog#1396]
does this logging library support in-memory caching/buffer/logging in any way ? if so can anyone specify how to enable it programatically...

**Comment by gabime** [comment]
what exactly do you need? there are several features..

**Comment by kumaryashwanth07** [comment]
I need to know whether the logging library will cache/buffer the log events/records in memory ?

**Comment by tt4g** [comment]
You can use an async logger: https://github.com/gabime/spdlog/blob/v1.5.0/README.md#asynchronous-logging

The async logger buffers log messages in memory, and output log to file with worker thread.
