### ISSUE TITLE
Comiler error to_hex

### ISSUE THREAD

**Issue by slay-er** [gabime/spdlog#1397]
I get a compiler error for **to_hex**, if I include fmt/range.h header.

Code example:

#include <vector>
#include <spdlog/spdlog.h>
#include <spdlog/fmt/bin_to_hex.h>  
#include <fmt/ranges.h>

int main()
{
    std::vector<char> buf(80);

    spdlog::info("{}", spdlog::to_hex(buf));

    return 0;
}

The error message looks like this:

error C2752: 'fmt::v6::formatter<Arg,Char,void>': more than one partial specialization matches the template argument list
        with
        [
            Arg=spdlog::details::bytes_range<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<char>>>>,
            Char=char
        ]
...\include\spdlog\fmt\bin_to_hex.h(71,8): message : could be 'fmt::v6::formatter<spdlog::details::bytes_range<It>,char,void>'
...\include\fmt\ranges.h(254,8): message : or       'fmt::v6::formatter<RangeT,Char,std::enable_if<fmt::v6::is_range<T,Char>::value,void>::type>'
...\include\fmt\core.h(938): message : see reference to class template instantiation 'std::is_constructible<fmt::v6::formatter<Arg,Char,void>>' being compiled
        with
        [
            Arg=spdlog::details::bytes_range<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<char>>>>,
            Char=char
        ]

Can we get a fix for this?

**Comment by gabime** [comment]
Look like an fmt issue. Please open in its repo
