### ISSUE TITLE
fmt Lib Not Declared in LICENSE File

### ISSUE THREAD

**Issue by joernschellhaas** [gabime/spdlog#1398]
I'm using spdlog in a closed source project. We are quite aware that we have to adhere to the licenses of our libraries.

fmt is somewhat hidden from the user of the spdlog library. This introduces the danger that it is not noticed by them and the license is violated (though, yes, the exception in its license makes such a violation quite difficult to achieve).

I therefore recommend to add some notice about the fmt library to the LICENSE file.

**Comment by gabime** [comment]
The fmt license file It is already included in bundled fmt copy. 
But lets ask the author of fmt.. @vitaut how do you recommend placing the fmt license by spdlog?

**Comment by vitaut** [comment]
I'm fine with the way it's done right now, but you could mention {fmt}'s license in the top-level LICENSE if you want to make it slightly more clear. Note that {fmt}'s license is also MIT which I guess makes things easier.

**Comment by gabime** [comment]
Thanks. will do

**Comment by gabime** [comment]
Added a note in the License file to make it more clear.
