### ISSUE TITLE
Color sink improvements.

### ISSUE THREAD

**Issue by qis** [gabime/spdlog#1400]
I have noticed a few color sink things that could be improved, in particular on Windows:

1. `SetConsoleTextAttribute` has no effect in the VS Code "DEBUG&nbsp;CONSOLE" window.<br/>Colors are always disabled, even in `spdlog::color_mode::always` mode..

2. The VS Code "DEBUG&nbsp;CONSOLE" and "TERMINAL" windows, as well as the new Windows 10 [Terminal](https://github.com/microsoft/terminal) support ANSI color codes. They should be optional on all platforms.

3. The spdlog ANSI color sink uses a reset color code that does not work in VS Code "DEBUG&nbsp;CONSOLE" window, but works in the "TERMINAL" window and in [Terminal](https://github.com/microsoft/terminal).

4. The spdlog ANSI color sink could use text styles from `<fmt/color.h>`.<br/>This fixes the VS Code "DEBUG&nbsp;CONSOLE" window issue.

5. It looks like there is no need to use `unordered_map` for colors.<br/>`std::array<string_view_t, spdlog::level::off>` should be faster.

6. `log_msg` is in the `details` namespace and `pattern_formatter` is in `details/pattern_formatter.h`. This discourages users from creating their own sinks.<br/>Is this intentional?

7. Theoretically, there could be a single sink for Windows and POSIX systems.

I'm currently using [this](https://gist.github.com/qis/dfac1730bbed717bf90f89de6f2cfa68) sink. It's very simplistic, but supports all use cases we need.

**Comment by gabime** [comment]
Thanks for the comments.
This sink is not specific to VS Code, so not particular effort was made to accomedate to VS ocde quirks..

>  looks like there is no need to use unordered_map for colors.
std::array<string_view_t, spdlog::level::off> should be faster.
 
Not sure, have you measured ?

> log_msg is in the details namespace and pattern_formatter is in details/pattern_formatter.h. This discourages users from creating their own sinks.
Is this intentional? 

No - creating your own sinks is encourged. log_msg is in details for historic reasons more than anything.

**Comment by gabime** [comment]
fyi. I replace the map with array

**Comment by qis** [comment]
@gabime Thanks! Sorry I couldn't find time to properly benchmark it.
