### ISSUE TITLE
Support for logging binary data (i.e pass char* / unsigned char *)

### ISSUE THREAD

**Issue by kumaryashwanth07** [gabime/spdlog#1401]
This library support logging string type in each of the logging methods that are available, If possible can anyone implement a method or logging sink so that developers can efficiently log raw binary data passed as char* / unsigned char* pointers as method arguments thereby increasing performance. passing string type as pass by value that directly invokes copy constructor multiple times degrades performance.

**Comment by tt4g** [comment]
Do you want to logging `char*` or `unsigned char*` as binary data?
The following code works for me (spdlog v1.4.2 and C++17):

```cpp
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>

#include <spdlog/fmt/bundled/format.h>
#include <spdlog/fmt/bundled/ranges.h>

#include <string_view>

int main(int, char**) {
    auto consoleSink = std::make_shared<spdlog::sinks::stdout_sink_mt>();

    auto logger = std::make_shared<spdlog::logger>("console", consoleSink);

    spdlog::register_logger(logger);

    char* binary = u8"foo";
    std::string_view container(binary);
    logger->info("{0:b}", fmt::join(container, ""));

    spdlog::shutdown();

    return 0;
}
```

I get console outputs:

```bash
$ spdlog_issue_1401
[2020-01-30 10:06:49.324] [console] [info] 110011011011111101111
```

**Comment by gabime** [comment]
See [this](https://github.com/gabime/spdlog#log-binary-data-in-hex) example on how to log binary data as hex.

**Comment by WorstCodeWay** [comment]
@tt4g @gabime 
Hi, please help me.

> See [this](https://github.com/gabime/spdlog#log-binary-data-in-hex) example on how to log binary data as hex.

I have read that tutorial, but I still don't know how to log data in memory with type, suchlike `std::uint16_t *`, it's not a `stl` container data type.  If there is a way, please kindly show me some codes, thanks very much.

**Comment by tt4g** [comment]
@WorstCodeWay If iterator is provided, the tutorial code will work. In the sample code, `std::array<T>` is used, but C arrays will also work.

**Comment by WorstCodeWay** [comment]
> @WorstCodeWay If iterator is provided, the tutorial code will work. In the sample code, `std::array<T>` is used, but C arrays will also work.

So, I understand your answer like If I have a buffer(`std::uint16_t *` created by `malloc`), then I should convert it into `std::array` then I can use this `spdlog` trick, right? But this will make codes ugly:

```c++
// std::uint16_t *data received from tcp/ip with given size
if(spdlog::level == debug)
{
  std::vector<std::uint16_t> container;
  ConvertDataToStdVector(data, container);
  logger->info("{0:#x}", fmt::join(container, " "));
}
```

1. first I should check the log level whether should I convert c-like pointer into some container which have a iterator

**Comment by tt4g** [comment]
@WorstCodeWay If you want to use `fmt::join()`, include `include/spdlog/fmt/bundled/ranges.h` (`include/spdlog/fmt/ranges.h` is available in v1.x branch).

`fmt::join()` is provided by the fmt project. Please check there for details.
For example, a test for the C array exists: https://github.com/fmtlib/fmt/blob/d141cdbeb0fb422a3fb7173b285fd38e0d1772dc/test/ranges-test.cc#L30-L43

**Comment by gabime** [comment]
@WorstCodeWay Have you tried passing the pointers as is?
e.g.

```cpp
std::uint16_t *start = malloc(…);

std::uint16_t *end = start + N;

logger->info("Some buffer {:X}", spdlog::to_hex(start, end));
```

**Comment by WorstCodeWay** [comment]
> @WorstCodeWay If you want to use `fmt::join()`, include `include/spdlog/fmt/bundled/ranges.h` (`include/spdlog/fmt/ranges.h` is available in v1.x branch).
> 
> `fmt::join()` is provided by the fmt project. Please check there for details. For example, a test for the C array exists: https://github.com/fmtlib/fmt/blob/d141cdbeb0fb422a3fb7173b285fd38e0d1772dc/test/ranges-test.cc#L30-L43

@tt4g thanks, I'll try and back soon.

**Comment by WorstCodeWay** [comment]
@gabime 

> @WorstCodeWay Have you tried passing the pointers as is? e.g.
> 
> ```c++
> std::uint16_t *start = malloc(…);
> 
> std::uint16_t *end = start + N;
> 
> logger->info("Some buffer {:X}", spdlog::to_hex(start, end));
> ```

Tried just now, works for me. Perfectly.

@tt4g thanks, any way.

**Comment by gabime** [comment]
Thats great. This is also very efficient, passing the buffer as is without any conversions
