### ISSUE TITLE
Creating multiple file loggers with the same output file leads to an error 109/126

### ISSUE THREAD

**Issue by DmAC4D7** [gabime/spdlog#1403]
Hello,

I'm using the mechanism I pointed in the title. The spdlog is integrated as a log-system into existing DLL. I'm doing the logging from the different threads. Depending on the thread I'm receiving the following error message:
 - [24-01-2020 17:29:16.743] [ID 11120] [ERROR] [error] Api::ReadRegister line 218 is failed with an error 109: The pipe has been ended.
- [24-01-2020 17:29:20.052] [ID 9140] [ERROR] [error] Api::ReadRegister line 218 is failed with an error 126: The specified module could not be found.

Below you can see the spdlog initialization part:

auto sharedFileSink = std::make_shared<spdlog::sinks::simple_file_sink_mt>("KernelApi.log");

auto tadxi_logger = std::make_shared<spdlog::logger>("MAIN", sharedFileSink);
auto error_logger = std::make_shared<spdlog::logger>("ERROR", sharedFileSink);
auto misc_stuff_logger = std::make_shared<spdlog::logger>("MISC", sharedFileSink);
auto hdlc_logger = std::make_shared<spdlog::logger>("HDLC", sharedFileSink);
auto hdlc_rx_logger = std::make_shared<spdlog::logger>("->RX", sharedFileSink);
			
spdlog::register_logger(main_logger);
spdlog::register_logger(error_logger);
spdlog::register_logger(misc_stuff_logger);
spdlog::register_logger(hdlc_logger);
spdlog::register_logger(hdlc_rx_logger);

The above code has inserted in the dllmain.cpp, at the DLL_PROCESS_ATTACH section of DLL.
I didn't get from the Wiki (https://github.com/gabime/spdlog/wiki/2.-Creating-loggers) how properly to use std::make_unique<>. Because the giving example includes the only two loggers, in my case I have 5.

Couldn't you clarify what can be wrong here?

Best Regards,
Dzmitry Altukhou

**Comment by gabime** [comment]
Your code is fine. These errors don't seem not to originate from spdlog
