### ISSUE TITLE
Async logging: log statements in wrong order with a thread pool

### ISSUE THREAD

**Issue by andrea1bergamini** [gabime/spdlog#1404]
I have a multithread application that outputs on a rotating log file and console:

```
static std::shared_ptr<spdlog::details::thread_pool> _tp = std::make_shared<spdlog::details::thread_pool>(51200, 4);

try
	{		
		spdlog::drop(m_logID.toStdString().c_str());

		auto logFilePath = m_logFilePath + m_logFileName;

		auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_mt>();

#if defined _MSC_VER && defined QT_DEBUG
		dist_sink->add_sink(std::make_shared<spdlog::sinks::msvc_sink_mt>());
#endif // _MSC_VER

#ifdef Q_OS_ANDROID
        dist_sink->add_sink(std::make_shared<spdlog::sinks::android_sink_mt>());
#endif // Q_OS_ANDROID

		dist_sink->add_sink(std::make_shared<spdlog::sinks::stdout_color_sink_mt>());
		dist_sink->add_sink(std::make_shared<spdlog::sinks::rotating_file_sink_mt>(logFilePath.toStdString().c_str(), m_maxLogFileSize, m_maxNLogFile));
		
		auto logger = std::make_shared<spdlog::async_logger>(m_logID.toStdString().c_str(), dist_sink, _tp, spdlog::async_overflow_policy::overrun_oldest);
		spdlog::register_logger(logger);

		spdlog::set_level(spdlog::level::trace);
		spdlog::set_pattern("%^[%Y-%m-%d %H:%M:%S.%e] [%L] %v%$");
	}
	catch (const spdlog::spdlog_ex &ex)
	{
		qDebug() << "Log init failed: " << ex.what();
		return false;
	}
	return true;
```

Even if log statements come from a single thread, they're not sorted in the way they're supposed to be.
I can confirm by prepending a counter for each log operation.

The only workaround I've found is to create a custom thread pool and reduce the pool to 1 thread instead of 4 as the code above. So, my thinking is that the thread pool pick the messages from the queue without taking care of the order. 
I can understand the case when log messages come from multiple threads, but I can confirm they come from a single thread, so even if output it's async, the order should be kept (with any thread pool).

**Comment by tt4g** [comment]
As far as I know, `spdlog::details::thread_pool` does not guarantee the order of log messages, 
the only workaround is to have one worker thread in the pool.

**Comment by andrea1bergamini** [comment]
It's exactly what I did. But in my personal opinion, order must be guaranteed even if the thread pool is made of more worker threads. Logging order is very important.
Anyway, if it's a choice instead of side effect, must be written in the wiki

**Comment by tt4g** [comment]
Added "Message ordering" section: https://github.com/gabime/spdlog/wiki/6.-Asynchronous-logging
