### ISSUE TITLE
"relocation R_X86_64_TPOFF32 against ..."  Issue when compiling

### ISSUE THREAD

**Issue by fedqx** [gabime/spdlog#1405]
Hi, I am compiling a Shared library (.so) in Ubuntu 18.04. 

My `g++ -v` output is : `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)`. 
I am getting this error when compiling: 

`libspdlog.a(spdlog.cpp.o): relocation R_X86_64_TPOFF32 against _ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC`.

 My shared library has `-fPIC` flag but I think it may be the `spdlog.a` that requires this option. I am not experienced enough to mess with makefiles etc. even if that is the problem.
Edit: I can provide more info when needed.

**Comment by tt4g** [comment]
CMake does not set the `-fpic` option when building static libraries.

You can define `CMAKE_POSITION_INDEPENDENT_CODE=ON` to force this option : `cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && make -j`

CMake documents:

* [CMAKE\_POSITION\_INDEPENDENT\_CODE — CMake 3\.16\.3 Documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html)
* [POSITION\_INDEPENDENT\_CODE — CMake 3\.16\.3 Documentation](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html#prop_tgt:POSITION_INDEPENDENT_CODE)

**Comment by fedqx** [comment]
Thanks, @tt4g ! That solved the issue

**Comment by abrzozowski** [comment]
Thanks @tt4g

**Comment by Abdelrahman350** [comment]
Hello @tt4g, I have the same problem. Can you tell me what to do?

**Comment by tt4g** [comment]
@Abdelrahman350  the procedure remains unchanged.
Set CMake variable `CMAKE_POSITION_INDEPENDENT_CODE` to `ON`.

Example: 

```bash
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON (other option) ..
$ make -j
```

**Comment by Abdelrahman350** [comment]
Thank you @tt4g  this helped me alot

**Comment by cyrillicw** [comment]
But if we build spdlog as a shared library, do we still need to use -fpic in order to avoid relocation problem?

**Comment by tt4g** [comment]
@cyrillicw Yes. However, the default compiler option generated by CMake may specify `-fpic` (or `-fPIC`).
