### ISSUE TITLE
Dreaded duplicate fmt symbols are back

### ISSUE THREAD

**Issue by geiseri** [gabime/spdlog#1406]
I have `spdlog` inside of my DLL. In some places, I am using inline templates that contain log lines, but for some reason no matter how I order the includes I can only move these duplicates around.  In fact in the build error below there are no logging calls made in that file, but it does come in via a header.

![image](https://user-images.githubusercontent.com/2265693/73397506-ad28d380-42b1-11ea-83f2-d93bf6454911.png)
(Sorry for the PNG)

I am using `vcpkg` that in fact has the `SPDLOG_FMT_EXTERNAL` hardcoded so that it is always external.  I am not sure if this is a `fmt` bug or a `spdlog` bug.  It seems that it comes and goes, but always disappears for no apparent reason :\

**Comment by gabime** [comment]
> It seems that it comes and goes, but always disappears for no apparent reason :\

Seems like an issue with your environment, or its interaction with vcpkg

**Comment by geiseri** [comment]
I am sure it is, but the question is what could cause it.  I will try including it locally vs using vcpkg and report back.

**Comment by gabime** [comment]
@geiseri Any news about it?
