### ISSUE TITLE
Using `spdlog::details::log_msg` in `spdlog::sinks::sink` interface.

### ISSUE THREAD

**Issue by ngrodzitski** [gabime/spdlog#1408]
Given that `log_msg` lives in `details` namespace I assume it is a part of implementation and cannot be considered a thing one should be relied on when using spdlog. But in the same time it appears in a method `void sinks::sink::log(const details::log_msg &msg)`: https://github.com/gabime/spdlog/blob/v1.5.0/include/spdlog/sinks/sink.h#L16 

So if I want to introduce a custom sink (implementing its interface), or reuse existing sinks there is a doubt can I do it reliably as `spdlog::details::log_msg` can be altered in any "next" version?

Can you, please, elabarate on this (specifically on reusing sinks and custom sinks implementation)?

**Comment by gabime** [comment]
Although ```log_msg``` is ```details``` namespace, its interface will not break without a **big** notice in the release notes, as it is an important interface to the library users and implementation.

Custom sinks implementation are encourged.

**Comment by ngrodzitski** [comment]
Ok, thanks for clarification.
