### ISSUE TITLE
Double precision significantly increases upgrading from 1.4.2 to 1.5.0

### ISSUE THREAD

**Issue by renkun-ken** [gabime/spdlog#1410]
With spdlog 1.4.2 (using fmtlib 6.0.0), `info("{}", x)` produces `-0.000422091` while with spdlog 1.5.0 (using fmtlib 6.1.2) it produces `-0.0004220898603249235`. This makes the produced log file significantly larger than before, e.g. from 30GB to 60GB.

**Comment by tt4g** [comment]
This is a change of  fmt 6.1.0; https://github.com/fmtlib/fmt/releases/tag/6.1.0

**Comment by renkun-ken** [comment]
Thanks!

Is the following change that causes this:

>{fmt} now formats IEEE 754 float and double using the shortest decimal representation with correct rounding by default

Therefore, to restore the previous behavior, the only way is to specify format like `{:.8g}`?

**Comment by tt4g** [comment]
I think so.

**Comment by renkun-ken** [comment]
Thanks!
