### ISSUE TITLE
Can spdlog be use to generate serilog-like logs

### ISSUE THREAD

**Issue by jprobichaud** [gabime/spdlog#1411]
We are happy with spdlog, but recently we have a new requirement push on us: serilog.  Basically, to ease ingestion of logs and instrumentation (dashboarding, alerts, etc..) we need to start supporting [serilog](https://github.com/serilog/serilog) kind of formatting, which is basically a json format where one has the "template" message and the named args outputted as fields in a json document.

In C#, one write the serilog log function like:
```
Log.Warning("Disk quota {Quota} MB exceeded by {User}", quota, user);
```

As you can see, this uses named parameters, but doing the magical assignment of a "named parameter" with the position at which `quota` or `user` appear.

Is this a known/shared problem with others?  I couldn't see how to do that easily with spdlog.

I can imagine customizing the log function to do that, but with fmt, we need to explicitly call the `fmt::arg` function:
```
 spdlog::info("testing {abc} {def} !",fmt::arg("abc", 1),fmt::arg("def", 2));
```

Would there be a better way so that I don't have to put down the fmt::arg all the time?

**Comment by tt4g** [comment]
spdlog delegates expansion of log arguments to fmt, and not provide any other way than using `fmt::arg()` for using named arguments.

If you want to use name arguments in other ways, you will have to create a custom formatter.
