### ISSUE TITLE
Changing tweakme.h breaks tests, should this be improved upon?

### ISSUE THREAD

**Issue by emmenlau** [gabime/spdlog#1413]
First, thanks for the awesome work! I like spdlog a lot.

For our needs, we do not need most of the formatting, so we disable a number of features before building spdlog. We enable in `tweakme.h` the following:
 * `SPDLOG_CLOCK_COARSE`
 * `SPDLOG_NO_THREAD_ID`
 * `SPDLOG_NO_NAME`
 * `SPDLOG_NO_ATOMIC_LEVELS`
 * `SPDLOG_EOL`

When I run the tests afterwards, I get:
```
test cases: 118 | 106 passed | 12 failed
assertions: 421 | 409 passed | 12 failed
The following tests FAILED:
 	  1 - spdlog-utests (Failed)
```
This is pretty impressive, and I guess it means that I can trust the resulting library. But for my good nights sleep I want to look into the tests and see exactly which ones failed and why. And for our CI it would be great if I could get a green light from the test, so a 100% success.

Now my question: If I can provide a merge request that adapts some of the tests to support also the defines from `tweakme.h`, would that be acceptable for merging? I guess I can not cover all possible cases, but hopefully a number of relevant ones. For example, supporting an empty `SPDLOG_EOL` would be a relatively straightforward case in `TEST_CASE("rotating_file_logger1", "[rotating_logger]]")` where the number of expected lines would be `1` instead of `10`:
```
...
    for (int i = 0; i < 10; ++i)
    {
        logger->info("Test message {}", i);
    }

    logger->flush();
    auto filename = basename;
    if (strlen(spdlog::details::os::default_eol)) == 0) {
        REQUIRE(count_lines(filename) == 1);
    } else {
        REQUIRE(count_lines(filename) == 10);
    }
}
```

**Comment by gabime** [comment]
You are welcome to open PR for the tests. Try to keep it simple though ;)

**Comment by emmenlau** [comment]
I've created a showcase PR for this in #1414 . Can you take a look and tell me what you think?
