### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by qianqians** [gabime/spdlog#1415]
![image](https://user-images.githubusercontent.com/1223332/73937552-42fed700-4920-11ea-9cf7-36cf017a2549.png)
open log file then memory usage reduced

**Comment by qianqians** [comment]
after open log file
![image](https://user-images.githubusercontent.com/1223332/73937763-c0c2e280-4920-11ea-9145-9f6bc30d4370.png)

**Comment by tt4g** [comment]
File size is too large.
I recommend to using `spdlog::sinks::rotating_file_sink`.

**Comment by qianqians** [comment]
![image](https://user-images.githubusercontent.com/1223332/73939092-a9d1bf80-4923-11ea-8b77-9f3f2c1b618a.png)
i used rotating_logger_mt

**Comment by tt4g** [comment]
Are you calling `spdlog::logger::flush()`?
If not, log data may continue to accumulate in memory.

**Comment by qianqians** [comment]
i use
file_logger = spdlog::rotating_logger_mt("basic_logger", file_path, 64*1024*1024, 5);
file_logger->flush();

**Comment by gabime** [comment]
Whats the exact scenario to reproduce? Even better, please post code to reproduce

**Comment by gabime** [comment]
> If not, log data may continue to accumulate in memory.

it is upto to libc to decide when to flush (using the BUFSIZ macro which is 256 KB, 512 KB or 4096 KB ). In anyway it will not grow too big.

**Comment by tt4g** [comment]
@gabime Right. This memory usage is too much.

@qianqians `spdlog::logger::flush()` must be called periodically: https://github.com/gabime/spdlog/wiki/7.-Flush-policy

**Comment by gabime** [comment]
> spdlog::logger::flush() must be called periodically

 I don't think there is such need, and I don't think it is related to the issue

**Comment by tt4g** [comment]
> I don't think there is such need, and I don't think it is related to the issue

That's right. It should not be directly related to this issue. I wrote this because flush usage may be wrong.

I shouldn't have written this now. Sorry for the confusion.

**Comment by tt4g** [comment]
@qianqians I created the following snippet from the code in the image you provided.
I built this code with Visual Studio 2017 and ran it on Windows 10 OS, but the program did not use much memory.

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/rotating_file_sink.h"

#include <iostream>
#include <memory>

int main(int, char**) {
    spdlog::set_level(spdlog::level::trace);
    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");

    std::shared_ptr<spdlog::logger> file_logger =
            spdlog::rotating_logger_mt(
                    "basic_logger", "log/battle.txt", 64 * 1024 * 1024, 5);
    spdlog::set_default_logger(file_logger);

    for (int i = 0; i < 102400; ++i) {
        file_logger->info("fooooooooooo");
    }

    std::cout << "Press Enter..." << std::endl;

    std::cin.get();

    spdlog::shutdown();

    return 0;
}
```

For details, when the "Press Enter ..." message was displayed on the console, the log file size was 7,100KB, but the application memory usage was about 8MB.
