### ISSUE TITLE
Should spdlog add more information to the exception error handler.

### ISSUE THREAD

**Issue by haquocviet** [gabime/spdlog#1416]
Hello everyone,

To catch the error exception of the spdlog, I handle like this:
```
void CustomLogErrHandler(const std::string& msg)
{	
}

spdlog::set_error_handler(CustomLogErrHandler);

```
I ever expected that from the exception handler I could track back to the place which causes the exception. But the fact turns out that argument 'msg' pass to the handler is too general, often it is like "argument not found", "invalid type specifier". 

It would be better if spdlog could give the error-handler more information such as the original arguments that were passed to spdlog::log().

**Comment by gabime** [comment]
The messages about bad fmt arguments originate from the fmt lib. I suggest you open a ticket in its repo instead.
