### ISSUE TITLE
>16 arguments?

### ISSUE THREAD

**Issue by divaykin** [gabime/spdlog#142]
Hi @gabime 

the following code
	log->info("0: {}; 1: {}; 2: {}; 3: {}; 4: {}; 5: {}; 6: {}; 7: {}; 8: {}; 9: {}; 10: {}; 11: {}; 12: {}; 13: {}; 14: {}; 15: {}; 16: {}",
		0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);

fails with assert "argument index out of range".

what's the best way to print >16 arguments? thx

**Comment by gabime** [comment]
its a limitation of cppformat lib. if you need more than 16 please use the << operator instead

**Comment by divaykin** [comment]
thx

**Comment by vitaut** [comment]
@divaykin cppformat can handle more than 16 arguments provided that compiler supports variadic templates (a C++11 feature).

**Comment by divaykin** [comment]
@vitaut apparently it does not
```cpp
#include <spdlog/spdlog.h>
#include <cstdlib>

using namespace std;

int main(int argc, char** argv) {
	auto log = spdlog::stdout_logger_mt("log");
	log->info("std: {}; gcc: {}", __cplusplus, (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__));
	log->info("0: {}; 1: {}; 2: {}; 3: {}; 4: {}; 5: {}; 6: {}; 7: {}; 8: {}; 9: {}; 10: {}; 11: {}; 12: {}; 13: {}; 14: {}; 15: {}; 16: {}",
		0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);
	return 0;
}
```

```
[2015-11-06 10:40:42.857] [info] std: 201103; gcc: 50101
qtest: /usr/local/include/spdlog/sinks/./../details/./format.h:1035: Result fmt::internal::ArgVisitor<Impl, Result>::visit(const fmt::internal::Arg&) [with Impl = fmt::internal::ArgFormatter<char>; Result = void]: Assertion `false' failed.

RUN FINISHED; Aborted; core dumped; real time: 60ms; user: 0ms; system: 0ms
```

**Comment by vitaut** [comment]
@divaykin Looks like you are using an old version of spdlog, because there is no assert at line 1035 of format.h in recent ones. Here's what I get on cbc8ba72035a3828f3a03e425e7f0d91da6c2ba3:

```
[2015-11-06 07:20:55.618] [log] [info] std: 201103; gcc: 40804
[2015-11-06 07:20:55.618] [log] [info] 0: 0; 1: 1; 2: 2; 3: 3; 4: 4; 5: 5; 6: 6; 7: 7; 8: 8; 9: 9; 10: 10; 11: 11; 12: 12; 13: 13; 14: 14; 15: 15; 16: 16
```

**Comment by divaykin** [comment]
thanks @vitaut
