### ISSUE TITLE
Formatting Pattern to print numeric log levels mapped to systemd/syslog

### ISSUE THREAD

**Issue by berhoeckner** [gabime/spdlog#1443]
Hi, is there a way to have a formatting pattern which prints the log level as number mapped to the syslog levels?

something like in: https://github.com/gabime/spdlog/issues/873#issuecomment-441056572

This would allow to use a console_sink and when a program is intended to be started via systemd the log output pattern can be adjusted to incorporate the log level as <log_level_number>.

**Comment by gabime** [comment]
spdlog’s systemd sink already use “sd_journal_send(..)” and the “PRIORITY” flag to set the level. why is it not enough?

**Comment by berhoeckner** [comment]
i'm happily using the systemd_sink. thanks for that!

as far as i understood: if a log message is prefixed with <syslog_level_number> journald treats the log message with the prefixed piority.

this would allow to use the same sink for console output and logging to journald when run as service via systemd.

one could alter the pattern of the console sink depending on being a service or not.

**Comment by gabime** [comment]
Right, but what I don't understand is why is it needed since the the sink already use the needed api flags to set the priority when calling [sd_journal_send](https://manpages.debian.org/testing/libsystemd-dev/sd_journal_send.3.en.html)

**Comment by berhoeckner** [comment]
i guess i have no "hard" argument.

i found it a bit strange to directly depend on systemd/journald for the logging, and not use the stdout/err redirection of systemd.

so to allow systemd/journald logs and console logs, i should add two sinks, one systemd_sink and a console_sink?

**Comment by gabime** [comment]
> so to allow systemd/journald logs and console logs, i should add two sinks, one systemd_sink and a console_sink?

Yes. Thats the recommended way in spdlog.

**Comment by berhoeckner** [comment]
ok thanks!
