### ISSUE TITLE
Blocking flush in multithreaded logger

### ISSUE THREAD

**Issue by rob-p** [gabime/spdlog#145]
Hi,

  First, thanks for spdlog.  It's a fantastic library and has become my go-to tool for logging in all of my projects.  It's lightweight header only nature, fast speed, and rich feature set make it a near-perfect choice!  I have a situation in which I'm using a multi-threaded logger, and I want to report a certain error condition to the user before the program exits.  The problem that I'm encountering is that *sometimes* the message appears and *sometimes* it does not (the program terminates before the message is written).  I'm making the call to flush the logger before I call `std::exit()`.  In the multithreaded logger, is there any way to *block* until the log has been flushed?  Right now, I'm reduced to the very inelegant solution of using `cerr` in the cases where I want to report an error right before program termination.

**Comment by gabime** [comment]
Thanks for the feedback, I appriciate it.
Regarding the question, I assume you are using the sync mode with cerr logger?
I am not sure why flush doesnt help, but please try calling spdlog::drop_all() before exiting.

**Comment by rob-p** [comment]
I'm not quite sure what you mean by the `sync` mode with cerr logger.  I create the logger in the following manner:

```
auto fileSink = std::make_shared<spdlog::sinks::ostream_sink_mt>(logFile);
auto consoleSink = std::make_shared<spdlog::sinks::stderr_sink_mt>();
auto consoleLog = spdlog::create("stderrLog", {consoleSink});
auto fileLog = spdlog::create("fileLog", {fileSink});
auto jointLog = spdlog::create("jointLog", {fileSink, consoleSink});
```

I then write to `jointLog`, and call `jointLog->flush_all()` before exiting.  I also tried additionally calling `spdlog::drop_all()` before exiting, but it doesn't seem to help.  I *think* that the issue may have something to do with the semantics of logging directly before `std::exit()`.  If I place the call in a separate function and force the function to return directly before a call to `exit()`, the message seems to be written to the log.  However, this solution is clearly not always possible.  Is there something specific about the way that the compiler handles `std::exit()` that may cause the logger to not be appropriately flushed?

**Comment by gabime** [comment]
This is very strange indeed.. which os/compiler do you use?

**Comment by rob-p** [comment]
I'm on ubuntu 14.10.  The result of `uname -a` is:

```
Linux feynman 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
and I'm using gcc 4.9.1.  The result of `c++ -v` is:

```
c++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.1-16ubuntu6' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.1 (Ubuntu 4.9.1-16ubuntu6)
```

**Comment by rob-p** [comment]
Ahhh --- I see now.  This is the same behavior as is being seen in #147.  I didn't know that using the logger in async mode would demonstrate different behavior with respect to flush_all, but this is with an async logger.  I agree with @oconnore; it would be great to have some way to force all of the pending messages to be processed before quitting (I'm using this for efficient output in my [RapMap](https://github.com/COMBINE-lab/RapMap)) project, and I'm guessing that this behavior could cause the program to fail to output a few alignments at the end.

**Comment by gabime** [comment]
Yes. I intend to fixe teh ```flush()``` function in async mode as to wait for the queue to empty and only then flush the sinks.
