### ISSUE TITLE
Why ‘formatter_’ is not a member of ‘spdlog::sinks::sink’ ?

### ISSUE THREAD

**Issue by LazyPlanet** [gabime/spdlog#1456]
struct min_file_name_calculator {

		static filename_t calc_filename(const filename_t &filename) {
			std::tm tm = spdlog::details::os::localtime();
			filename_t basename, ext;
			std::tie(basename, ext) = details::file_helper::split_by_extension(filename);
			std::conditional<std::is_same<filename_t::value_type, char>::value, fmt::memory_buffer, fmt::wmemory_buffer>::type w;
			fmt::format_to(w, SPDLOG_FILENAME_T("{}_{:04d}_{:02d}_{:02d}_{:02d}_{:02d}.log"), basename, tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min);
			return fmt::to_string(w);
		}

	};

	struct hour_file_name_calculator {

		static filename_t calc_filename(const filename_t &filename) {
			std::tm tm = spdlog::details::os::localtime();
			filename_t basename, ext;
			std::tie(basename, ext) = details::file_helper::split_by_extension(filename);
			std::conditional<std::is_same<filename_t::value_type, char>::value, fmt::memory_buffer, fmt::wmemory_buffer>::type w;
			fmt::format_to(w, SPDLOG_FILENAME_T("{}_{:04d}_{:02d}_{:02d}_{:02d}.log"), basename, tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour);
			return fmt::to_string(w);
		}

	};

	template<class Mutex, class FileNameCalc>
	class hour_file_sink : public base_sink<Mutex> {

	public:

		hour_file_sink(filename_t base_filename, int rotation_hour, int rotation_minute)
			: base_filename_(std::move(base_filename))
			, rotation_h_(rotation_hour)
			, rotation_m_(rotation_minute) {
			if (rotation_hour < 0 || rotation_hour > 23 || rotation_minute < 0 || rotation_minute > 59) {
				throw spdlog_ex("daily_file_sink: Invalid rotation time in ctor");
			}
			rotation_tp_ = next_rotation_tp_();
			### **file_helper_.open(FileNameCalc::calc_filename(base_filename_));**
		}

	protected:

		void sink_it_(const details::log_msg &msg) override {
			fmt::memory_buffer formatted;
			**sink::formatter_->format(msg, formatted);**
			if (std::chrono::system_clock::now() >= rotation_tp_) {
				file_helper_.open(FileNameCalc::calc_filename(base_filename_));
				rotation_tp_ = next_rotation_tp_();
			}
			file_helper_.write(formatted);
		}

		void flush_() override {
			file_helper_.flush();
		}

	private:

		std::chrono::system_clock::time_point next_rotation_tp_() {
			auto now = std::chrono::system_clock::now();
			time_t tnow = std::chrono::system_clock::to_time_t(now);
			tm date = spdlog::details::os::localtime(tnow);
			date.tm_hour += rotation_h_;
			date.tm_min += rotation_m_;
			date.tm_sec = 0;
			auto rotation_time = std::chrono::system_clock::from_time_t(std::mktime(&date));
			if (rotation_time > now) {
				return rotation_time;
			}
			return { rotation_time + std::chrono::minutes(1) };
		}

		filename_t base_filename_;
		int rotation_h_;
		int rotation_m_;
		std::chrono::system_clock::time_point rotation_tp_;
		details::file_helper file_helper_;

	};		

while buiding on centos, it shows:

![image](https://user-images.githubusercontent.com/15156350/75514930-ab2e6d80-5a33-11ea-91d0-2e77fefa9e04.png)
Log.cpp: In member function ‘void spdlog::sinks::hour_file_sink<Mutex, FileNameCalc>::sink_it_(const spdlog::details::log_msg&)’:
Log.cpp:60:10: error: ‘formatter_’ is not a member of ‘spdlog::sinks::sink’
    sink::formatter_->format(msg, formatted);
          ^~~~~~~~~~
Log.cpp:65:32: error: no matching function for call to ‘spdlog::details::file_helper::write(fmt::v6::memory_buffer&)’
    file_helper_.write(formatted);
                                ^
In file included from ../ThirdParty/spdlog/include/spdlog/details/file_helper.h:58,
                 from ../ThirdParty/spdlog/include/spdlog/sinks/daily_file_sink.h:7,
                 from Log.cpp:6:
../ThirdParty/spdlog/include/spdlog/details/file_helper-inl.h:72:20: note: candidate: ‘void spdlog::details::file_helper::write(const memory_buf_t&)’
 SPDLOG_INLINE void file_helper::write(const memory_buf_t &buf)
                    ^~~~~~~~~~~
../ThirdParty/spdlog/include/spdlog/details/file_helper-inl.h:72:20: note:   no known conversion for argument 1 from ‘fmt::v6::memory_buffer’ {aka ‘fmt::v6::basic_memory_buffer<char>’} to ‘const memory_buf_t&’ {aka ‘const fmt::v6::basic_memory_buffer<char, 250>&’}

**Comment by tt4g** [comment]
I don't know the answer to the issue subject, but I know how to fix compilation errors.

Replace `sink::formatter_->format(msg, formatted);` with `base_sink<Mutex>::formatter_->format(msg, formatted);` because `formatter_` is member variable of `spdlog::sinks::base_sink<Mutex>`.

Reference implementation:

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/sinks/dist_sink.h#L82-L89

**Comment by LazyPlanet** [comment]
@tt4g 
thank you for reply, i just upgrade spdlog from v1.3.1 to spdlog-1.x, and error occurs.
