### ISSUE TITLE
Log "seconds.milliseconds" since program start

### ISSUE THREAD

**Issue by dpacbach** [gabime/spdlog#1458]
In my logging output I'd like it to look something like this:
```
0.000   some logging output line 1...
0.357   some logging output line 2...
2.530   some logging output line 3...
```
where the numbers are seconds.milliseconds since program start.  Is there any feature that would allow doing that?  I am familiar with the existing format specifiers but could not find one that suits this purpose.  Thanks

**Comment by gabime** [comment]
There is no such feature.
