### ISSUE TITLE
Logging from shared library

### ISSUE THREAD

**Issue by madCoder24** [gabime/spdlog#146]
I am currently trying to use spdlog from a shared library. Then this library will be pulled in to use for other custom shared libraries. The shared libraries could either be a .so or .dll. However, the code I currently have does not seem to write to the file.

Header:

```C++
#include <spdlog.h>
#include <string>

namespace spd = spdlog;

class MadLink_Logger
{
public:
    MadLink_Logger();
    MadLink_Logger(std::string name);

    void log(std::string message = "");
    void log(std::string name, std::string message);

private:
    std::shared_ptr<spdlog::logger> file_logger;
};
```
Implementation:

```C++
#include "MadLink_Logger.h"

MadLink_Logger::MadLink_Logger()
{
    spd::set_level(spd::level::debug);
    spd::set_async_mode(1048576, spd::async_overflow_policy::discard_log_msg);
    file_logger = spd::rotating_logger_mt("file_logger", "log", 1048576 * 5, 3);
    //file_logger->debug("creating logger");
}

MadLink_Logger::MadLink_Logger(std::string name)
{
    spd::set_level(spd::level::debug);
    spd::set_async_mode(1048576, spd::async_overflow_policy::discard_log_msg);
    spd::rotating_logger_mt(name, "log", 1048576 * 5, 3);
}

void MadLink_Logger::log(std::string message)
{
    file_logger->debug(message);
}

void MadLink_Logger::log(std::string name, std::string message)
{
    file_logger = spd::get(name);
    file_logger->debug(message);
}
```

Now according to the wiki, I can just have a private variable then create it in the constructor. Is it out of scope in my methods? If I try to write to the file inside the constructor that works perfectly.

I appreciate any advice given.

Thanks

**Comment by gogdizzy** [comment]
I don't know if you miss assignment in the 2nd CTOR.
file_logger is not assigned.

**Comment by paulsapps** [comment]
If you have it in a shared object and static lib then the static lib will have another copy of the vars so it won't work.
