### ISSUE TITLE
Question - Lock Mechanism Design for Multi Thread  

### ISSUE THREAD

**Issue by mohsenomidi** [gabime/spdlog#1460]
Dear @gabime 

Hope you are doing well, currently i am working on a C++ application and it works Multi Thread, after long study on Multi Thread lock mechanism and design i just found two different methods to handle the locking one method using the mutex and another one using the atomic operation and variables, and also there is an implementation safe_ptr, in some articles about comparison of std::mutex and std::atomic, says the std::atomic is 10 to 42 times faster than the std::mutex and also the safe_ptr, [object_threadsafe](https://github.com/AlexeyAB/object_threadsafe) says this is the very fast 

> 10 times faster to achieve the speed of lock-free algorithms on >85% reads

i just want to know do you have any research about this, i think you also use the std::mutex for threads, and performance for loging is very critical, what do you think about it ?

**Comment by gabime** [comment]
I think implementing  locking correctly is very very hard, and using mutex is the way to go.

**Comment by mohsenomidi** [comment]
Thanks :)
