### ISSUE TITLE
spdlog is not clang-cl / cross-compilation aware

### ISSUE THREAD

**Issue by robinchrist** [gabime/spdlog#1462]
When using clang-cl to crosscompile for Windows, the compilation fails, because an unknown flag is added:

`clang: fatal error: unknown argument ignored in clang-cl: '-pedantic' [-Wunknown-argument]`

`clang-cl` does support the `-W<warning>` but not `-pedantic`

The flags are added here (`utils.cmake`)
```
function(spdlog_enable_warnings target_name)
    target_compile_options(${target_name} PRIVATE
        $<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>,$<CXX_COMPILER_ID:GNU>>:
            -Wall -Wextra -Wconversion -pedantic -Wfatal-errors>
        $<$<CXX_COMPILER_ID:MSVC>:/W4>)
		if(MSVC_VERSION GREATER  1900)  #Allow non fatal security wanrnings for msvc 2015
			target_compile_options(${target_name} PRIVATE /WX)
		endif()
endfunction()
```

**Comment by gabime** [comment]
How can this reproduced? what ate the steps to cross compile this?
