### ISSUE TITLE
Fails to build with SPDLOG_BUILD_SHARED=yes

### ISSUE THREAD

**Issue by yurivict** [gabime/spdlog#1468]
With SPDLOG_BUILD_SHARED=yes it fails on FreeBSD:
```
/usr/ports/devel/spdlog/work/spdlog-1.4.2/include/spdlog/fmt/fmt.h:22:10: fatal error: 'bundled/core.h' file not found
#include "bundled/core.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

Choosing to build shared libraries instead of static libraries should not change how the fmt dependency is handled.

Please also enable shared libraries by default on linux/BSD. Shared libaries are generally better because they lead to smaller executables.

**Comment by gabime** [comment]
This is an not the latest version. Is it reproducible in latest version or commit?

**Comment by yurivict** [comment]
This is reproducible in the latest version ```1.5.0```.

**Comment by tt4g** [comment]
Did you get error "fatal error: 'bundled/core.h' file not found" because you did not define `SPDLOG_FMT_EXTERNAL=ON`?

**Comment by yurivict** [comment]
```SPDLOG_FMT_EXTERNAL=ON``` helped, but it shouldn't be related to the shared library option.

**Comment by gabime** [comment]
@yurivict  Could you try latest commit ? There were some fixes regarding this lately

**Comment by yurivict** [comment]
The latest rev. f78bca4a still looks for bundled files when shared library is requested.

**Comment by gabime** [comment]
> still looks for bundled files when shared library is requested.

It should look for the bundled files actually. The question is why it doesn't find them.

**Comment by yurivict** [comment]
Bundled files are removed by the port, because it works fine with standard packages.

**Comment by gabime** [comment]
well that explains it..
whoever removed the bundle should take care of defining SPDLOG_FMT_EXTERNAL=ON

**Comment by yurivict** [comment]
It doesn't explain why static lib doesn't need a bundle, but shared does.

**Comment by gabime** [comment]
I dont know,but it is clearly not in the scope of the lib. I suggest taking this to the port maintainer.
