### ISSUE TITLE
Using spdlog in VS2013

### ISSUE THREAD

**Issue by fresh-ji** [gabime/spdlog#1469]
Dear whom it may concern,

i am using spdlog in my personal program currently. But the lastest version needs c++11 and my VS2013 can not support c++11's full features (i.e. constexpr). So i tried an older version, but some errors still exist.
the error is shown below:
![捕获1](https://user-images.githubusercontent.com/25540984/76481403-58e64700-644c-11ea-96b8-cafc9d20e025.PNG)

"msg_id" is not the member of "spdlog::details::async_msg"

could you please help me to solve this error or provide a better way to use spdlog in my VS2013 project?

Thank you very much.
Sincerely,
Ji.

**Comment by tt4g** [comment]
As far as I look git tag v1.0.0...v1.3.1, `spdlog::details::async_msg` has `msg_id` member variable.
What version are you using?

**Comment by tt4g** [comment]
Similar issue: #894 
You may be able to use v1.4.1 if update MSVC toolset.

**Comment by fresh-ji** [comment]
Thank you so much for your reply. I tried spdlog 1.3.0 and encountered the problem mentioned in issue894. I have installed vc141, but currently i am asked to use vc120 only.

![捕获2](https://user-images.githubusercontent.com/25540984/76490376-f9953080-6465-11ea-978e-26e264f02d69.PNG)

In a word, if i want to use spdlog with vc120, i can not use the versions later than v1.2.1. Is that right?

Thanks again!

**Comment by tt4g** [comment]
> In a word, if i want to use spdlog with vc120, i can not use the versions later than v1.2.1. Is that right?

I don't think so,
If `msg_id` is declared in `spdlog::details::async_msg`, it should compile, and t is declared in v1.2.1.

https://github.com/gabime/spdlog/blob/10e809cf644d55e5bd7d66d02e2604e2ddd7fb48/include/spdlog/details/thread_pool.h#L26-L35

Check the source at hand.

**Comment by fresh-ji** [comment]
Apologize for my expressions. the v1.2.1 is running well in my program. but i want to use "spdlog::source_loc", which is not inlcuded untill v1.3.0.

v1.3.0 with vc120 leads to this error: < function-style-cast > : cannot convert from 'initializer-list' to 'fmt::v5::internal::id_adapter<Handler,Char>', which is mentioned in issue#894. Unfortunatly i am not allowed to update my MSVC toolset.

Is there a substitute method for "spdlog::source_loc" in v1.2.1 OR a solution to make v1.3.0 and vc120 work together.

Thanks!

**Comment by tt4g** [comment]
You can use `SPDLOG_TRACE()` and `SPDLOG_DEBUG()` in spdlog v1.2.1 (these were removed in spdlog v1.3.0):

https://github.com/gabime/spdlog/blob/10e809cf644d55e5bd7d66d02e2604e2ddd7fb48/include/spdlog/spdlog.h#L127-L139

NOTE should define `SPDLOG_TRACE_ON` and `SPDLOG_DEBUG_ON` macro before `#include "spdlog/spdlog.h"`.

**Comment by fresh-ji** [comment]
Thanks for your answers. helps a lot!
