### ISSUE TITLE
Project compiling speed so slow when using spdlog

### ISSUE THREAD

**Issue by xiaodian2234** [gabime/spdlog#1470]
My operation is : 
  Compiled spdlog
       1.Set SPDLOG_BUILD_SHARED = ON
       2.make  && make install
       3.spdlog generates .so and can find in /usr/local/lib
  My project's cmakelist
       1.find_package(spdlog REQUIRED)
       2.target_link_libraries(my_project_name, spdlog::spdlog)
  Use ldd shows 
        libspdlog.so.1 => /usr/local/lib/libspdlog.so.1 

The problem is that the compiling time is long. Method of directly including the header files  costs the same time.

My platform is TX2, and the compiling costs about 10 minutes.

**Comment by gabime** [comment]
How much compiling the example/example.cpp takes? It should take about 3 seconds. If more there is something wrong with the setup.

**Comment by tt4g** [comment]
Using an external fmt library can reduce the build time.

**Comment by gamelaster** [comment]
Sadly, I'm experiencing same issue as @xiaodian2234 . I'm using spdlog on ARM CPU, installed from Debian apt.

**Comment by tt4g** [comment]
@gamelaster Does Debian apt provide a static spdlog library?
The CMake target name of the static library is `spdlog::spdlog`.

Using a header-only spdlog will result in longer compilation times.

**Comment by gamelaster** [comment]
@tt4g Yes, Debian have it, I'm linking it via CMake as you describing upper.

**Comment by tt4g** [comment]
@gamelaster Try adding forward declarations of `spdlog::logger` and `spdlog::sinks:: sink` forward declarations in your header files.
If the spdlog header is included in many places, it might improve compile time.
In version 1.6.0 or later, you can use `#include "spdlog/fwd.h"`.

**Comment by xerxes95** [comment]
Is it possible to forward-declare functions too? For example, if I want to use `spdlog::stdout_color_mt`

**Comment by Omernn23** [comment]
@gabime how to define SPDLOG_COMPILED_LIB with cmake?

**Comment by tt4g** [comment]
Use [`target_compile_definitions()`](https://cmake.org/cmake/help/v3.25/command/target_compile_definitions.html).

```cmake
`target_compile_definitions(<your_target> SPDLOG_COMPILED_LIB)
```

EDIT: If you are using CMake, then linking the spdlog target will automatically define `SPDLOG_COMPILED_LIB`.

https://github.com/gabime/spdlog/blob/50e8b2d982e40266f61b9a0d023c008322c650cb/CMakeLists.txt#L173
