### ISSUE TITLE
Can't use find_package

### ISSUE THREAD

**Issue by lerivi** [gabime/spdlog#1471]
`find_package` call don't work. All attempts to write `Findspdlog.cmake` weren't successfull: script executes with `couldn't find path spdlog_INCLUDE_DIR`.
Repository didn't export targets.
The only way i can use spdlog in my build is to `add_subdirectory(vendor/spdlog)`.

I have read all related issues and, unfortunately, didn't find the answer. Thanks.

**Comment by tt4g** [comment]
`find_package` will not work without spdlog installed.

You can use `spdlog::spdlog` CMake target after `add_subdirectory(vendor/spdlog)`.

Example:

```cmake
project(foo)

set(SPDLOG_BUILD_SHARED OFF)
set(SPDLOG_BUILD_EXAMPLE OFF)
set(SPDLOG_BUILD_EXAMPLE_HO OFF)
set(SPDLOG_BUILD_TESTS OFF)
set(SPDLOG_BUILD_TESTS_HO OFF)
set(SPDLOG_BUILD_BENCH OFF)
set(SPDLOG_SANITIZE_ADDRESS OFF)
set(SPDLOG_INSTALL OFF)
set(SPDLOG_FMT_EXTERNAL OFF)
set(SPDLOG_FMT_EXTERNAL_HO OFF)
set(SPDLOG_NO_EXCEPTIONS OFF)
add_subdirectory(vendor/spdlog)

add_executable(foo ${YOUR_SOURCE_FILES})
target_link_libraries(spdlog_issue_973
  PUBLIC
    spdlog::spdlog)
```

**Comment by lerivi** [comment]
Thanks. I'll use this way.
