### ISSUE TITLE
How to not evaluate loggers args when log level is high enough

### ISSUE THREAD

**Issue by SylvainCecchetto** [gabime/spdlog#1476]
Hi,

I have this case:

```c++
auto core_logger = spdlog::stdout_color_st("core");
core_logger->set_level(spdlog::level::debug);

// Later in another file
std::shared_ptr<spdlog::logger> log = spdlog::get("core");

log->info("Test 1: {}", myObject.toString());
log->debug("Test 2: {}", myObject.toString());
log->trace("Test 3: {}", myObject.toString());
```

My problem is that even with level set to `spdlog::level::debug`, `myObject.toString()` on `Test 3` line is evaluate.

In my program, a lot of `log->trace` lines use arguments that have a high cost in time. I would like to not evaluate `log->trace` arguments when I set a log level higher than 0.

Is there a way to do that easily?

Thank you!

**Comment by gabime** [comment]
You can use SPDLOG_TRACE MACRO. Please see the faq for details.
