### ISSUE TITLE
Can we remove #include <windows.h> from spdlog/common.h:

### ISSUE THREAD

**Issue by sharpe5** [gabime/spdlog#1477]
This code is in `spdlog/common.h`:

```
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX // prevent windows redefining min/max
#endif

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>
#endif //_WIN32
```

There are some problems with including `<windows.h>`:

- Using #include <windows.h> adds #defines that may break an existing codebase, especially if that existing codebase is designed to be cross platform.
- ~~The library defines WIN32_LEAN_AND_MEAN. What if we do not want that defined? We are then stuck.~~
- ~~I'm not sure why <windows.h> is necessary, I commented it out and all of the functionality seemed to work just fine for a reasonably complicated program that targets MSVC and gcc.~~
- `spdlog.h` is pervasive, usually it gets included in all files using something like `stdafx.h` or `pch.h`. This means that if there are any clashes between <windows.h> or spdlog, we have to choose between logging or including a 3rd party library. This is an difficult choice, as logging is so important.
- If we attempt to wrap up `spdlog.h` inside a `.cpp` file, we have to add manual `template` commands for every single combination of template parameters, which is a huge amount of work and a big maintenance burden. So that's not really an option.

**Comment by sharpe5** [comment]
Also, I *love* spdlog, it really is a fantastic library. Keep up the great work!

**Comment by sharpe5** [comment]
On further investigation:

* There is a #include <windows.h> in `os-inl.h` as well, so removing it from one place did not change the include.
* It may be unrealistic to ask for this to be removed, as spdlog needs this to function.

I also tried this:

```
#define SPDLOG_COMPILED_LIB
```

... but this did not work (perhaps as I am using spdlog from vcpkg).

**Comment by gabime** [comment]
I merged a [PR](https://github.com/gabime/spdlog/pull/1453) lately to at least refactor this  to a single file (details/windows_include.h).

I guess we can try to remove it from common.h and see how it goes. 

> The library defines WIN32_LEAN_AND_MEAN. What if we do not want that defined? We are then stuck.

Afaik defining `WIN32_LEAN_AND_MEAN` is recommended and common practice. So if we won't define it we loss as well.

> There is a #include <windows.h> in os-inl.h as well, so removing it from one place did not change the include.

Should be fine if used as compiled lib i(not sure what vpkg do exactly). Using the compiled lib is the recommended way anyhow.

> Also, I love spdlog, it really is a fantastic library. Keep up the great work!

Thanks! You made my day!

**Comment by sharpe5** [comment]
> Afaik defining WIN32_LEAN_AND_MEAN is recommended and common practice. So if we won't define it we loss as well.

Absolutely agree, one can always include them manually.

> I guess we can try to remove it from common.h and see how it goes.

I think this is worth trying. If I compile from source, then it will work (I think vcpkg defaults to header-only, no matter what is configured).

Thank you again for the great work on the library. As an aside, I am writing some cross-platform code, and the library internals are a fascinating read.

**Comment by horenmar** [comment]
+1 on removing the include from common inclusion path -- even with the reduction macros, `windows.h` is fairly heavyweight and brings in _ton_ of symbols.

What exactly do you need from it in the header?

**Comment by gabime** [comment]
Closed. windows.h is not part of common.h anymore
