### ISSUE TITLE
Provide a forward declaration headers

### ISSUE THREAD

**Issue by horenmar** [gabime/spdlog#1481]
I have multiple places where I want to only deal with pointer to `spdlog::logger`, without having to include spdlog headers.

I can (and currently do) forward declare the class myself, but forward declaring names from thirdparty namespaces is generally considered poor form and I would like to avoid it.

**Comment by gabime** [comment]
you can include only logger.h. It is is not fwd, but close enough..

**Comment by horenmar** [comment]
`logger.h` includes at least 10 stdlib headers within 1 level of transitivity: 
* `<atomic>`
* `<chrono>`
* `<functional>`
* `<initializer_list>`
* `<memory>`
* `<mutex>`
* `<exception>`
* `<string>`
* `<type_traits>`
* `<vector>`

**Comment by gabime** [comment]
Fair enough. However I am not sure what meaningful fwd head is possible since a major part of the logger are templates.

**Comment by horenmar** [comment]
The important part is that with a forward declaration, you can make (smart) pointers/references to a `spdlog::logger` without having to include `spdlog/logger.h`. Given the relative weight of that header, this can be quite beneficial.

To use this pointer/reference, you then _do_ need to include the logger header, but that can be done in the `.cpp` file. The main use is that if a class caches logger lookup, I do not force all users of that class to also include all of the logger headers.

**Comment by horenmar** [comment]
This is a utility header for measuring time taken by a blck of code we have in our codebase:

```cpp
#include <memory>
#include <string>

namespace spdlog {
    class logger;
}

struct Timer {
    // Keeps track of how long it was running
};

struct TimerMeasureRAII {
    TimerMeasureRAII(std::string id, std::shared_ptr<spdlog::logger> const &logger)
        : m_id(std::move(id))
        , m_logger(logger)
    {}

    //! Initializes m_logger to `spdlog::get("main-logger")`.
    explicit TimerMeasureRAII(std::string id);

    //! Log the time elapsed since calling the constructor
    ~TimerMeasureRAII();
private:
    Timer m_timer;
    std::shared_ptr<spdlog::logger> m_logger;
    const std::string m_id;
    static thread_local std::size_t s_measure_nesting;
};

template <typename F>
auto Timer::measure(std::string id, F &&f) -> decltype(f()) {
    TimerMeasureRAII timer(std::move(id));
    return f();
}

template <typename F>
auto Timer::measure(std::string id, std::shared_ptr<spdlog::logger> const &logger, F &&f) -> decltype(f()) {
    TimerMeasureRAII timer(std::move(id), logger);
    return f();
}
```

Notice that it doesn't need to include `spdlog/logger.h`, so users of this header do not need to include it either.

**Comment by gabime** [comment]
Not sure that those 3 lines really worth a new header file (on the other hand its mere existence might remind developers to use it which is good).

**Comment by horenmar** [comment]
You should probably also provide fwd decls for other classes/types your users might want to customize, e.g. sinks.

But even if you provide just the logger, you should provide it because it is generally a bad practice to create forward declarations for 3rd namespaces.

**Comment by gabime** [comment]
Fixed by adding `spdlog/fwd.h` file
