### ISSUE TITLE
[CMake/C++] Use precompiled header to speed up compilation time by 2 for static spdlog

### ISSUE THREAD

**Issue by OlivierLDff** [gabime/spdlog#1482]
# Use precompiled header to speed up compilation time by 2 for static library

Precompiled headers can speed up compilation time by a lot. Why isn't spdlog supporting it?

Since CMake `3.16` there is a new function `target_precompile_headers` that handle precompiled header for every compilers. It's really easy to set up in the project, and doesn't required more step from final user.

## Motivation

I'm building `spdlog` as part of my CMake project, and since there are lots of target in the build, i'm trying to earn so time by using precompiled header for some target that are still not supporting it.

## Benchmark

I did an implementation on my [fork](https://github.com/OlivierLDff/spdlog), branch is `pch-support`. And made some basic benchmark. 

My processor is `i7-9750H @ 2.60 Ghz` with msvc.

| Target | Without Precompiled Headers | With Precompiled Headers |
| :----: | :-------------------------: | :----------------------: |
| spdlog |        5.5-6 seconds        |      3-3.5 seconds       |

As you can see when building compilation time is almost decreased by 2.

## Proposed Changed

For the benchmark I just created a new file `pch.h` in `include/spdlog/details`.

I included stl headers that were included around the project and also `commin.h` that isn't supposed to changed.

So this is `pch.h`:

```c++
#pragma once

// c
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <climits>
#include <cwchar>
#include <cmath>
#include <cstdarg>
#include <cerrno>
#include <cassert>

// string
#include <string>
#include <sstream>
#include <ostream>

// containers
#include <unordered_map>
#include <list>
#include <vector>
#include <array>
#include <tuple>

// utilities
#include <limits>
#include <atomic>
#include <locale>
#include <initializer_list>
#include <exception>
#include <type_traits>
#include <utility>
#include <memory>
#include <functional>
#include <condition_variable>
#include <algorithm>

// thread
#include <chrono>
#include <thread>
#include <mutex>

// spdlog
#include <spdlog/common.h>
```

Then to use it i modified `CMakelists.txt` to add:

```cmake
# After creating target spdlog
if(COMMAND target_precompile_headers)
    target_precompile_headers(spdlog PRIVATE include/spdlog/details/pch.h)
endif()
```

As you can see if `target_precompile_headers` doesn't exist no compilation time reduction will happen.

And that's all.

## Possible improvement

In my fork precompiled header is the default way to go. If the user have CMake v3.16 or greater, he will benefit from shorter compilation time. 

But maybe we should add an option to disable this behavior if required?

Maybe we should add an option `SPDLOG_DISABLE_PCH` ?

## Opinion

So what's your opinion about this? Could this be considered as a PR?
What should i improve?

Thanks a lot for reading.

Olivier Le Doeuff.

## Reference

* https://cmake.org/cmake/help/git-stage/command/target_precompile_headers.html

**Comment by gabime** [comment]
Sounds good. Which compiler did you try? Did you try under msvc as well? 

SPDLOG_DISABLE_PCH seems like also good idea as well in case there are problems.
PR would be most welcome.

**Comment by OlivierLDff** [comment]
Yes i used MSVC, i will try under linux and mac to have other benchmark with gcc and clang.
I do the PR tomorrow with SPDLOG_DISABLE_PCH.

**Comment by OlivierLDff** [comment]
https://github.com/gabime/spdlog/pull/1484

**Comment by energygreek** [comment]
hello,  why not merge this pr to master branch?  i think head-only spdlog more need to be precompiled much than library headers , isn't it?
