### ISSUE TITLE
Consider outlining throws

### ISSUE THREAD

**Issue by horenmar** [gabime/spdlog#1483]
Moving throws into their own outlined functions is an often-used trick that can improve both compile-time and runtime-performance.

The reason for this is that `throw X` generates quite a lot of support code on each throw site, which has negative effects on inlining. Quarantining exceptions to specific .cpp files can also reduce the number of headers included in common locations.

**Comment by gabime** [comment]
Interesting. spdlog already defines 
```c++
#define SPDLOG_THROW(ex) throw(ex)
```

Do you suggest something like:

```c++

void spdlog_throw(const spdlog_ex @ex) { throw ex;} 

#define SPDLOG_THROW(ex) spdlog_throw(ex)

```

**Comment by horenmar** [comment]
That is one possibility, but the usual usage is more like this

```cpp
[[nothrow]]
void throw_spdlog_exception(const char* msg);
```

and then in different file:
```cpp
[[nothrow]]
void throw_spdlog_exception(const char* msg) {
    SPDLOG_THROW(spdlog::spdlog_ex(msg));
}
```

The problem with having `void spdlog_throw(const spdlog_ex& ex) { throw ex; }` is that if you add another derived exception, it will still be thrown as `spdlog_ex`, because throwing is not polymorphic.

[This is an example of the difference it can make](https://godbolt.org/z/g5Wjxx), note that `bar2` is significantly bigger, which would limit further inlining. The `bar1` also does not require including `<exception>`.

**Comment by gabime** [comment]
I didn't notice any performance difference. Regarding the size, libspdlog.a size was reduced by 2000 bytes.
However I merged this since this gets rid of the ugly ```SPDLOG_THROW(..)``` with more elegent ```throw_spdlog_ex(..)```
