### ISSUE TITLE
SPDLOG_NO_NAME documentation in tweakme.h is unclear

### ISSUE THREAD

**Issue by horenmar** [gabime/spdlog#1485]
The documentation says
```cpp
///////////////////////////////////////////////////////////////////////////////
// Uncomment if logger name logging is not needed.
// This will prevent spdlog from copying the logger name on each log call.
//
// #define SPDLOG_NO_NAME
///////////////////////////////////////////////////////////////////////////////
```

From this I would expect defining this to avoid an allocation per log call, and potentially weird things happening if I ask for logging the logger's name while this is defined.

As far as I can tell from reading the code, what actually happens is that the default logging format no longer includes logger's name (and logger's name never causes an allocation, because it is taken as a string view).

**Comment by gabime** [comment]
Right. It has much less significance after spdlog switched to string views. Now that I look at it I think this option should be removed entirely from the code.

**Comment by gabime** [comment]
Fixed by removing this option altogether.
