### ISSUE TITLE
SPDLOG_NO_THREAD_ID documentation in tweakme.h is wrong(ish)

### ISSUE THREAD

**Issue by horenmar** [gabime/spdlog#1486]
The documentaton for `SPDLOG_NO_THREAD_ID` in `tweakme.h` says

```cpp
///////////////////////////////////////////////////////////////////////////////
// Uncomment if thread id logging is not needed (i.e. no %t in the log pattern).
// This will prevent spdlog from querying the thread id on each log call.
//
// WARNING: If the log pattern contains thread id (i.e, %t) while this flag is
// on, the result is undefined.
```

However, as currently implemented, it will always have well-defined result, the thread-id will be written as 0. This is because the flag only removes code initializing the `log_msg::thread_id`  variable to specific value, which means that it will always be initialized to `0`, which is its in-class initializer.

**Comment by gabime** [comment]
Thanks. Fixed.
