### ISSUE TITLE
Build warnings (-Wsign-conversion) under Clang

### ISSUE THREAD

**Issue by Karsten1987** [gabime/spdlog#1488]
Originally reported in here: https://github.com/ros2/spdlog_vendor/issues/4

There is a quite a few warnings under clang which ideally should be addressed. Pretty much all in the style of converting `int` to `size_t`:
```
In file included from /opt/ros/master/build/spdlog_vendor/spdlog-1.5.0-prefix/src/spdlog-1.5.0/src/fmt.cpp:10:
/opt/ros/master/build/spdlog_vendor/spdlog-1.5.0-prefix/src/spdlog-1.5.0/include/spdlog/fmt/bundled/format-inl.h:484:48: warning: implicit conversion changes signedness: 'int' to 'unsigned long long' [-Wsign-conversion]
          (min_exponent + fp::significand_size - 1) * one_over_log2_10 +`
```

**Comment by tt4g** [comment]
This is fmt library problem.
I recommend opening issue in the fmt repo.

**Comment by Karsten1987** [comment]
sorry for the noise. Opened a ticket in the fmt repo: https://github.com/fmtlib/fmt/issues/1604
