### ISSUE TITLE
Ability to log file and line from where log entry was produced

### ISSUE THREAD

**Issue by tapika** [gabime/spdlog#1490]
Question.

Sometimes when I debug it's quite good to know from which source code and line `info()` function call came from. In Visual Studio - if you format trace in special way, you can double click on line and it will get you to place where log was made from. Typically it involves `__FILE__` & `__LINE__` macros, but what I have checked `__FILE__` in linux can produce complete or incomplete path, depending on how project was configured. In windows however `__FILE__` works always in same manner.

If I recall correctly format is something like:

    info("{} ({}): {}", __FILE__, __LINE__, logLine)

Is it possible to have built-in mechanism of activating this trace with file / line number, or is it possible to easily override spdlog behavior from this logging logic perspective ?

Feature could be activated using some define macro.

I know also that theoretically you can use call stack for that purpose to determine who called you, resolve symbol information and trace it out - but suspect it's not trivial thing to do at the moment.

(Relates to https://github.com/dotnet/runtime/issues/12405 , talking only about native C++, but theoretically I could see that C# could also call spdlog, but would require some C#-C++ wrappers, also call stack resolution for managed code )

**Comment by tt4g** [comment]
You can use custom format such as `%@`, `%s`, `%g`, `%#`, `%!` with logging macro such as `SPDLOG_LOGGER_TRACE`, `SPDLOG_LOGGER_DEBUG`.

Example: 

```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // Must: define SPDLOG_ACTIVE_LEVEL before `#include "spdlog/spdlog.h"`
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"

void source_info_example()
{
    auto console = spdlog::stdout_logger_mt("console");
    spdlog::set_default_logger(console);
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");

    SPDLOG_LOGGER_INFO(console, "log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 10] log with source info"
    SPDLOG_INFO("global log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 11] global logger with source info"

    console->info("source info is not printed"); // Console: "[source ] [function ] [line ] source info is not printed"
}
```

See wiki for more details:

* https://github.com/gabime/spdlog/wiki/3.-Custom-formatting
* https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

**Comment by tapika** [comment]
Tried that one, and it's indeed works, but `'%s'` uses only filename of source code, and `'%g'` uses relative path (from cmake perspective). 

    drop_all();
    sink_ptr sink = make_shared<spdlog::sinks::windebug_sink_mt>();
    auto stdoutlogger = std::make_shared<spdlog::logger>("name", sink);
    stdoutlogger->set_pattern("%s(%#): %v");
    register_logger(stdoutlogger);
    set_default_logger(stdoutlogger);

    SPDLOG_LOGGER_INFO(stdoutlogger, "test trace");

With `%s` it produces:

    test_spdlog.cpp(54): test trace

With `%g` it produces:

    ..\..\..\test_spdlog\test_spdlog.cpp(54): test trace

Is it possible to get full path, not relative.


But suspect this problem is applicable only to cmake/ninja generator, with MSVC it would work correctly.

**Comment by tapika** [comment]
Btw, it's possible to use simpler log macro, 

    SPDLOG_INFO("test trace");

**Comment by tapika** [comment]
So this code indeed works for Visual studio:

    drop_all();
    sink_ptr sink = make_shared<spdlog::sinks::windebug_sink_mt>();
    auto stdoutlogger = std::make_shared<spdlog::logger>("name", sink);
    stdoutlogger->set_pattern("%g(%#): %v");
    register_logger(stdoutlogger);
    set_default_logger(stdoutlogger);

    // Logs filepath and line to each log entry - but this will work only from VSVC project built by cmake,
    // spdlog> cmake -DCMAKE_GENERATOR_PLATFORM=x64 -Bproj -S.
    SPDLOG_INFO("test trace");

**Comment by tt4g** [comment]
> But suspect this problem is applicable only to cmake/ninja generator, with MSVC it would work correctly.

Maybe differences in compiler options between CMake and MSVC. try to set `/FC` compiler option.

https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019:

> __FILE__ The name of the current source file. __FILE__ expands to a character string literal. To ensure that the full path to the file is displayed, use /FC (Full Path of Source Code File in Diagnostics). This macro is always defined.

**Comment by tapika** [comment]
You're right, 

    if (MSVC)
        # Full Path of Source Code File in Diagnostics
        target_compile_options(test_spdlog PRIVATE  /FC)
    endif()


fixed the issue. I think you can close the ticket. Not sure if needs to be added into some readme, as additional instruction, as it's maybe not so obvious all these steps. Or just add link to this ticket.

**Comment by tapika** [comment]
Btw, does similar command line switch exists for gcc / clang, as there is similar problem with `__FILE__` macro expansion on linux side.

**Comment by tt4g** [comment]
> Btw, does similar command line switch exists for gcc / clang, as there is similar problem with __FILE__ macro expansion on linux side.

Apparently, as you guessed, this is a problem with CMake and Ninja.

GCC expands `__FILE__` to input filename at preprocessing.

https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html:

> This macro expands to the name of the current input file, in the form of a C string constant. This is the path by which the preprocessor opened the file, not the short name specified in ‘#include’ or as the input file name argument. For example, "/usr/local/include/myheader.h" is a possible expansion of this macro.

However, Input filename  is relative path when using CMake and Ninja.
I found related issues:

* https://developercommunity.visualstudio.com/content/problem/189962/cmake-outputs-broken-source-file-paths-in-build-lo.html
* https://gitlab.kitware.com/cmake/cmake/issues/13894

`/FC` is workaround on MSVC but GCC and Clang workaround not found.

**Comment by Grave18** [comment]
``` cpp 
// logSetup.hpp
#pragma once
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // must include this
#include "spdlog/spdlog.h"

void setupLog()
{
    // Use macro for print this format: [Game.hpp:23] [info] Lol 1
    // %s -source
    // %! -function
    // %# -line
    // (%^ %$) -color fore log level
    // %l -log level
    // %v -actual text
    spdlog::set_pattern("[%s:%#] [%^%l%$] %v"); // Some IDE knows format of FileName.hpp:10 and give you reference to file
 }

// some .cpp
#include "logSetup.hpp"
//...
setupLog();
SPDLOG_INFO("Lol {}", 1); // Use macro for proper functioning
//...
```
