### ISSUE TITLE
How to output Pointer

### ISSUE THREAD

**Issue by dai-2584** [gabime/spdlog#1492]
int nP = 3;
 SPDLOG_LOGGER_INFO(g_pLogger, "&nP={}", &nP);

core.h:902:5: error: static assertion failed: formatting of non-void pointers is disallowed
     static_assert(!sizeof(T), "formatting of non-void pointers is disallowed");

How to output a Pointer?

**Comment by tt4g** [comment]
spdlog use fmt library to format argument at runtime.
You can use `fmt::ptr()`:

```cpp
int nP = 3;
SPDLOG_LOGGER_INFO(g_pLogger, "&nP={}", fmt::ptr(&nP));
```

**Comment by dai-2584** [comment]
OK , thank you!

**Comment by tt4g** [comment]
@caibf Set pointer syntax `p`.
https://fmt.dev/8.0.0/syntax.html

```diff
 HWND hwnd_child = viewer->GetWindowId();
- KL_LOGGER_DEBUG("Create the visualizer viewer({}).", fmt::ptr(hwnd_child));
+ KL_LOGGER_DEBUG("Create the visualizer viewer({:p}).", fmt::ptr(hwnd_child));
```

And it is recommended that this question be asked in the fmt repository.

**Comment by caibf** [comment]
I have tried this, still the same result. Maybe the fmt version(I use spdlog 1.5.0, depends on fmt 6.1.2) problem.

But make a simple demo, result it's ok.
```
double elapsed_time = 0;
HWND hwnd_child = (HWND)&elapsed_time;
KL_LOGGER_DEBUG("Create the visualizer viewer({}).", fmt::ptr(hwnd_child));
KL_LOGGER_DEBUG("Create the visualizer viewer({:p}).", fmt::ptr(hwnd_child));
```
Output:
Create the visualizer viewer(0xef372ff6e8).
Create the visualizer viewer(0xef372ff6e8).

> And it is recommended that this question be asked in the fmt repository.

OK. I will move this question to its repository.
