### ISSUE TITLE
Unknown type name 'locale' mac xcode 

### ISSUE THREAD

**Issue by henrytien** [gabime/spdlog#1493]
I got the error, anyone knows about it.
![image](https://user-images.githubusercontent.com/7891852/77642815-3b12f900-6f99-11ea-9534-2d36733f1026.png)

![image](https://user-images.githubusercontent.com/7891852/77642759-23d40b80-6f99-11ea-8483-da9e4b97ada9.png)

**Comment by tt4g** [comment]
This is your development environment problem because `std::locale` is system header.

Check your compiler include path.

**Comment by henrytien** [comment]
I fixed it. thanks. c++ Language Dialect should be std=c++11, and I use $(SRCROOT)/xxx  in  Hear Search Paths.
