### ISSUE TITLE
%g expands to relative path depending on how compiler is invoked

### ISSUE THREAD

**Issue by eudoxos** [gabime/spdlog#1496]
I am aware this is an issue of the build system (CMake & Ninja), in which case it is a documentation issue: https://github.com/ninja-build/ninja/issues/1251

[Custom formatting](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags) says `%g` expands to *Full path of the source file (use `SPDLOG_TRACE(..)`, `SPDLOG_INFO(...) etc.)`* e.g. `/some/dir/my_file.cpp`.

In my case, I see expansion to path relative to the build directory `../src/foo.cpp`, when I use source dir relative to the build directory (`cmake ..`). When I use `cmake /abs/path/to/sources`, it works normally.

I don't think there is anything spdlog can do to absolutize `__FILE__` (but maybe I'm wrong).

**Comment by gabime** [comment]
Thanks. fixed the doc for %g
