### ISSUE TITLE
Windows MinGW: Will 'recursive_mutex' not a part of std

### ISSUE THREAD

**Issue by aadit-n3rdy** [gabime/spdlog#1498]
I did these commands in windows powershell:
`git clone http://github.com/gabime/spdlog
cd spdlog
mkdir build
cd build
cmake .. -G "MinGW Makefiles"
mingw32-make`
The cmake command works, but the make command fails with:
`/spdlog/details/registry.h:79:10: error: 'recursive_mutex' in namespace 'std' does not name a type
     std::recursive_mutex &tp_mutex();
          ^~~~~~~~~~~~~~~`

**Comment by tt4g** [comment]
Did your MinGW install what you distribute on mingw.com?
If that's case. that is not support all C++11 features.
Should use MinGW-w64 of MSYS2.

https://stackoverflow.com/questions/24009821/mingw-4-8-1-c11-thread-support
