### ISSUE TITLE
Why is spdlog_enable_warnings recommended everywhere?

### ISSUE THREAD

**Issue by loics2** [gabime/spdlog#1499]
I just spent an hour trying to find where was the `\WX` MSVC flag in my CMake configuration, and I finally found it in `spdlog_enable_warnings`.

Granted, I never actually check what this function was doing, but since it's mentioned in the [example `CMakeLists.txt`](https://github.com/gabime/spdlog/blob/v1.x/example/CMakeLists.txt) and in some answers to the Github issues, I assumed it was some kind of additional configuration.

Why do you keep recommending its use? A library shouldn't car about my compilation flags!

**Comment by gabime** [comment]
This is certainty not recommenced. Need to find a better way to clarify the example cmake.

**Comment by gabime** [comment]
Fixed. Thanks for reporting.

**Comment by loics2** [comment]
Nice ! Thanks a lot
