### ISSUE TITLE
Overloaded std::ostream operators for enum types are not being used by spdlog

### ISSUE THREAD

**Issue by RazorX1989** [gabime/spdlog#150]
If someone tries to implement output operators for enum types (for much more informative output) then spdlog just implicitly casts the enum to int and gives the operator no chance. This can be fixed by changing the IsConvertibleToInt type trait.

enum { value = !std::is_enum<T>::value && (sizeof(convert(get())) == sizeof(yes)) };

**Comment by vitaut** [comment]
This is a [C++ Format](https://github.com/cppformat/cppformat) issue so I opened an issue there: https://github.com/cppformat/cppformat/issues/232.

**Comment by vitaut** [comment]
The issue has been fixed in C++ Format (https://github.com/cppformat/cppformat/commit/6cff6d81374fef37bedc3f82eefb9a01ee48e60b), but the spdlog's copy has to be updated for this to have effect.

**Comment by gabime** [comment]
Updated.. Thanks @vitaut

**Comment by RazorX1989** [comment]
Updated version works fine. Thanks

**Comment by aCuria** [comment]
So how do i get this to work as the user?
cout << enum works but 
spdlog::error("{}" My_ENUM} does not work
