### ISSUE TITLE
How to change log file directory during run

### ISSUE THREAD

**Issue by spdlog** [gabime/spdlog#1501]
Currently I can't change the log file directory after initializing the spd log instance,
I have tried many ideas, but the only thing that works is by creating a new instance with the same parameters but different log file directory.
the spd log creation makes the logging slower.
Is there any other way to set a new log file directory without creating new instance...

**Comment by tt4g** [comment]
Simple solution: use `spdlog::sinks::dist_sink`.

The following code works for me:

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/dist_sink.h"

#include <memory>
#include <string>
#include <utility>
#include <vector>

static std::shared_ptr<spdlog::sinks::basic_file_sink_mt>
create_file_sink(std::string out)
{
    bool truncate = false;
    return std::make_shared<spdlog::sinks::basic_file_sink_mt>(
            std::move(out), truncate);
}

int main(int, char**)
{
    auto foo_file_sink = create_file_sink("foo/log.txt");
    std::vector<spdlog::sink_ptr> initial_sinks({foo_file_sink});
    // dist_sink has foo_file_sink.
    auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_mt>(initial_sinks);

    auto file_logger = std::make_shared<spdlog::logger>("file", dist_sink);
    spdlog::initialize_logger(file_logger);
    spdlog::set_default_logger(file_logger);

    spdlog::info("first log."); // foo/log.txt: "first log."
    spdlog::info("second log."); // foo/log.txt: "second log."

    auto bar_file_sink = create_file_sink("bar/log.txt");
    std::vector<spdlog::sink_ptr> next_sinks({bar_file_sink});
    // dist_sink has bar_file_sink, then drop foo_file_sink.
    dist_sink->set_sinks(next_sinks);

    spdlog::info("third log."); // bar/log.txt: "third log."

    spdlog::shutdown();

    return 0;
}

```

**Comment by spdlog** [comment]
thanks for the quick response,
could you guide me through my implementation because I can't use basic_file_sink,
because I must use rotating_file_sink_mt mode.
This is how I'm initializing my first instance logger:
`	LoggersContainerImpl::m_IsOldFormat = isOldFormat;
		if (logToStdout==true)
		{
			//In case we want to lwrite to file and console 
			std::vector<spdlog::sink_ptr> sinks;
			sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_st>());
			sinks.push_back(std::make_shared<spdlog::sinks::rotating_file_sink_mt>(path, maxFileSize, numOfFiles));
			auto mutiple_logger = std::make_shared<spdlog::logger>(source, begin(sinks), end(sinks));
			_actualLogger = mutiple_logger;
		}`
And I want to change the directory of the log file (path parameter) during the process.

**Comment by tt4g** [comment]
Both `spdlog::sinks::rotating_file_sink_mt ` and `spdlog::sinks::basic_file_sink` should be able to achieve the goal with the same procedure.
How do you want to change directories?

**Comment by spdlog** [comment]
After creating the first logger (how I described above) i will start logging into the log file that i defined,
After that somewhere in the code I want to change the dirictory that I defined before for the same logger instance( _actualLogger).
How I can do this according the code that I attached?

**Comment by tt4g** [comment]
I think it will be solved if you manage `std::shared_ptr<spdlog::sinks::dist_sink>`.
There is no need to recreate the logger.

Example:

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/daily_file_sink.h"
#include "spdlog/sinks/dist_sink.h"
#include "spdlog/sinks/stdout_sinks.h"

#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace spdlog_issue_1501
{

class LoggerFactory
{
public:

    explicit LoggerFactory(
            const std::string &logDirectory, std::string logName)
            : logName_(logName),
              dist_sink_(
                    std::make_shared<spdlog::sinks::dist_sink_mt>(
                            create_sinks_(logDirectory, logName)))
    {

    }

    std::shared_ptr<spdlog::logger> createLogger(std::string logger_name)
    {
        auto logger =
                std::make_shared<spdlog::logger>(
                        std::move(logger_name), this->dist_sink_);

        spdlog::initialize_logger(logger);

        return logger;
    }

    void swapLogDirectory(const std::string &logDirectory)
    {
        this->dist_sink_->set_sinks(create_sinks_(logDirectory, this->logName_));
    }

private:

    std::string logName_;

    std::shared_ptr<spdlog::sinks::dist_sink_mt> dist_sink_;

    std::vector<spdlog::sink_ptr>
    static create_sinks_(const std::string &logDirectory, const std::string &logName)
    {
        auto stdout_sink = std::make_shared<spdlog::sinks::stdout_sink_mt>();

        std::string logFile = logDirectory + "/" + logName;
        int rotation_hour = 0;
        int rotation_minute = 0;
        bool truncate = false;
        uint16_t max_files = 0;
        auto daily_file_sink =
                std::make_shared<spdlog::sinks::daily_file_sink_mt>(
                        std::move(logFile),
                        rotation_hour,
                        rotation_minute,
                        truncate,
                        max_files);

        std::vector<spdlog::sink_ptr> sinks({stdout_sink, daily_file_sink});

        return sinks;
    }

};

} // namespace spdlog_issue_1501

int main(int, char**)
{
    auto loggerFactory =
            std::make_shared<spdlog_issue_1501::LoggerFactory>("foo", "log.txt");
    auto logger = loggerFactory->createLogger("swap_directory_logger");
    spdlog::set_default_logger(logger);

    spdlog::info("first log."); // foo/log.txt: "first log."
    spdlog::info("second log."); // foo/log.txt: "second log."

    loggerFactory->swapLogDirectory("bar");

    spdlog::info("third log."); // bar/log.txt: "third log."

    spdlog::shutdown();

    return 0;
}
```

**Comment by spdlog** [comment]
Sorry because I'm asking a lot of questions but it is very important.

I wrote this some of lines :
`			auto foo_stdout_sink = std::make_shared<spdlog::sinks::stdout_sink_st>();
`
`auto foo_file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(path, maxFileSize, numOfFiles);`
`std::vector<spdlog::sink_ptr> sinks({ foo_stdout_sink, foo_file_sink });`
`std::shared_ptr<spdlog::sinks::dist_sink_mt> dist_sink_(std::make_shared<spdlog::sinks::dist_sink_mt>(sinks));`
`auto mutiple_logger = std::make_shared<spdlog::logger>(source, dist_sink_);`
`_actualLogger = mutiple_logger;`

in compiling time I'm getting this Error :
Severity	Code	Description	Project	File	Line
Error	C2664	'spdlog::sinks::dist_sink<std::mutex>::dist_sink(const spdlog::sinks::dist_sink<std::mutex> &)': cannot convert argument 1 from 'std::vector<spdlog::sink_ptr,std::allocator<_Ty>>' to 'const spdlog::sinks::dist_sink<std::mutex> &'	

THANKS.

**Comment by tt4g** [comment]
You have probably assigned `std::shared_ptr<spdlog::sinks::dist_sink_mt>` to a different type variable. However, I did not find the offending code in your snippet.

Read the error message carefully.
The line number that caused the error is displayed.
