### ISSUE TITLE
Flush policy for async logger with a segfault

### ISSUE THREAD

**Issue by Zephilinox** [gabime/spdlog#1502]
Hey :)

Reading the flush policy page on the wiki, it wasn't clear if a segfault would force the queue to flush. If not, is there any way to implement this manually, such as via a signal handler or at exit?

Assuming I understood it right and that setting a logger to flush for any messages when it's async doesn't guarantee it'll actually be written to disk.

**Comment by tt4g** [comment]
AFAIK, spdlog does not working in signal handler function.
See this issue comment: https://github.com/gabime/spdlog/issues/1461#issuecomment-597027416

**Comment by Zephilinox** [comment]
Thanks :) as we're using ASIOs signal handling I don't think that's a problem generally, though I'm unsure how it interacts (if it works at all) with SIGSERV.

Does that mean I'm correct in thinking the queue isn't guaranteed to be flushed?

**Comment by tt4g** [comment]
Right. I/O operations when flushing the queue in the signal handler function is not guaranteed by the C++ standard.
Also, `std::mutex` used by spdlog may not work.

When the signal handler function is called, you may be able to use the condition variable to flush the queue.
`std::atomic` can be used safely in signal handler function.
I think this is a good example: https://stackoverflow.com/a/52424515

**Comment by Zephilinox** [comment]
Thanks :) I'm automatically flushing on every message. My concern is that according to the flush policy wiki page the async loggers use a queue, and it's not clear if that means every message will be written to disk in the case of a segfault if there are messages in that queue when it happens.

**Comment by gabime** [comment]
In case of crash, messages can be lost. There is no guarantee, even if flush is called on each message. Moreover, in async loggers, flush is an async operation and does not happen immediately, so it won't prevent message loss on crash.

**Comment by Zephilinox** [comment]
I see, thanks :) does that means this is also the case with a synchronous logger? i.e. if I write a message with a flush_on level that would make it flush, and then in the next line I segfault.

**Comment by gabime** [comment]
The chances of losing messages this way are much smaller but it can still happen. Nothing is guaranteed  in case of a crash.

**Comment by Zephilinox** [comment]
Thanks, I appreciate the help. It's good to know :)
