### ISSUE TITLE
Library fails to build when compiler warnings are emitted

### ISSUE THREAD

**Issue by peanutfun** [gabime/spdlog#1504]
### Description
Spdlog currently sets the compiler option `-Wfatal-errors` unconditionally to its library target via the [`spdlog_enable_warnings` ](https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L159) CMake function. This makes it difficult to locally build the library from source, especially when used as Git Submodule. For example, when building the latest version v1.5.0, Clang-6.0 (available on Ubuntu 18.04 LTS) issues the warning reported in #1488 that produces a fatal error. The warnings are not enabled for the header-only CMake target, but the [`README.md`](https://github.com/gabime/spdlog#static-lib-version-recommended---much-faster-compile-times) specifically recommends using the library target for faster compile times:

> #### Static lib version (recommended - much faster compile times)

While building a library without warnings is an important goal for developers, this information is not really useful for downstream users. And with `-Wfatal-errors`, it can actually cause trouble. Could all warning flags be conditionally set, e.g., via a CMake option?

### Suggestions
* Add CMake option `SPDLOG_ENABLE_WARNINGS` (default: `OFF`) for controlling the warnings on the `spdlog` library target.
* Remove `-Wfatal-errors` from the "regular warnings" flag list.
* Recommend linking to header-only target if spdlog is used as submodule (if previous suggestions are not feasible for some reason)

**Comment by gabime** [comment]
PR#1503 addresses exactly this. The only thing i am not sure yet is wether to enable warnings by default  or not..

**Comment by peanutfun** [comment]
Great! I only had a look at the issues 🙈 

I think the default settings should consider that the person who builds the project has little to no idea about the project internals. If enabling the warnings means that the build might fail although it would succeed without `-Wfatal-errors`, I think the default setting should be `OFF`.

**Comment by gabime** [comment]
Fixed. Warning are OFF by default

**Comment by peanutfun** [comment]
Great! Thank you! 👍
