### ISSUE TITLE
Why no compile-time error for fmt::format(FMT_STRING("{}"), 1, 2);?

### ISSUE THREAD

**Issue by yaoxinliu** [gabime/spdlog#1510]
```
fmt::format(FMT_STRING("{}{}"), 1); // trigger a compile-time error
fmt::format(FMT_STRING("{}"), 1, 2); // no compile-time error
```

The first statement would trigger a compile-time error as expected.

**Why does the second not?**

**Comment by tt4g** [comment]
This is fmt library feature. I recommend asking questions in [fmt project](https://github.com/fmtlib/fmt).

**Comment by hak8or** [comment]
Actually, I bet this is related to  #1369 which was and sadly still remains closed. So I guess we won't ever be getting that perk of using fmt (compile time safety).

**Comment by gabime** [comment]
@hak8or It turned out to be not very simple without breaking the existing API, and without degrading performance of existing API. Help is wanted.
