### ISSUE TITLE
a way to set the time of the message

### ISSUE THREAD

**Issue by ron003** [gabime/spdlog#1512]
This is a feature request...
I have a logging utility that does memory logging (like traceback) but to a
memory-mapped file. I call this "fast-path logging". I've designed this utility to be able to wrap around an additional logging facility to do what I call slow-path logging.
I can configure this utility so that any given log statement can either, both, or none of the slow-path and/or the fast-path. But if both are selected, they will both have the same micro/nano-second resolution timestamp.
Can you add a log function that takes a log_clock::time_point argument? For example:

> void log(log_clock::time_point &log_time, source_loc loc, level::level_enum lvl, string_view_t msg)
{
	bool log_enabled = should_log(lvl);
	bool traceback_enabled = tracer_.enabled();
	if (!log_enabled && !traceback_enabled)
	{
		return;
	}
	details::log_msg log_msg(log_time, loc, name_, lvl, msg);
	log_it_(log_msg, log_enabled, traceback_enabled);
}

or, is there a different way that can be used to set the time of the log message?
I think I can make a pull request if you think that would be worthwhile. Do you?
Thanks

**Comment by tt4g** [comment]
FYI: There are custom formats that already exist `%e` (milliseconds), `%f` (microseconds), `%F` (nanoseconds).
These print the creation time of `spdlog::details::log_msg`.

**Comment by ron003** [comment]
Yes, I am/was aware and I would make use of these extended precision formats to more easily and precisely correlate the message(s) logged via spdlog with the message logged in my high-speed memory-mapped file buffer.
In my logging system, I will have already done the equivalent of an os::now() call before the call to spdlog::logger::log, so I'm looking for a way to use the time_point I already have to set the creation time of spdlog::details::log_msg, making sure the time of the spdlog message is identical to my message, and avoid having spdlog do another os::now() call (which would/should result in a time_point that is a few microseconds different).
Thanks for your work on spdlog.

**Comment by tt4g** [comment]
It seems that the API you need doesn't exist. I think you should make a pull request.

**Comment by ron003** [comment]
OK, will do. Should I branch off of branch v1.x, or off of master or  one of the other branches?

**Comment by tt4g** [comment]
v1.x branch is current.

**Comment by ron003** [comment]
Thanks! I think I've made the pull request correctly... there was an issue was CI, but it seemed to be an issue with clang-7 install, not an issue with the preposed code.
