### ISSUE TITLE
Syslog sink: ‘default_factory’ does not name a type

### ISSUE THREAD

**Issue by pbardosi** [gabime/spdlog#1513]
Hy,
I tried to use syslog_sink but run the above error.
I included the "<spdlog/details/synchronous_factory.h>" header, and added the "using default_factory = synchronous_factory;" line to syslog_sink.h, to fix the problem.

Best regards,
Peter

**Comment by tt4g** [comment]
Add `#include "spdlog/spdlog.h"` above `#include "spdlog/sinks/syslog_sink.h"`.

**Comment by pbardosi** [comment]
Thanks! My clang-format always reorders my includes. :(

**Comment by gabime** [comment]
Fixed in 854abdf5e653aef4907160f0a08ecc8855c05fed.
