### ISSUE TITLE
stdout_color_mt is no member

### ISSUE THREAD

**Issue by Nickyhub** [gabime/spdlog#1514]
I am trying to compile the following code:
#include "Log.h"

namespace Blox {

	std::shared_ptr<spdlog::logger> Log::s_CoreLogger;
	std::shared_ptr<spdlog::logger> Log::s_ClientLogger;

	void Log::Init() {
		spdlog::set_pattern("%^[%T] %n: %v%$");
		s_CoreLogger = spdlog::stdout_color_mt("Example");
	}
}

However I get the error that stdout_color_mt is not a member of spdlog.

I have included the "spdlog/spdlog.h" in the Log.h file and I made sure to use the branch v1.x so that I have the latest version. I have seen this issue here multiple times but none of the answers helped me to solve my specific problem. I am using Microsoft Visual Studio 2019

**Comment by tt4g** [comment]
Add `#include "spdlog/sinks/stdout_color_sinks.h"` below `#include "spdlog/spdlog.h"`.

**Comment by Nickyhub** [comment]
Thank you very much. I looked into the spdlog.h file but I couldnt find something in their. Only something commented out. Is this because of a different Version that the definition for this is now in a different Header file?

**Comment by tt4g** [comment]
It seems that the header file was split after version 1.0.0.

**Comment by RadishMouse926** [comment]
> Thank you very much. I looked into the spdlog.h file but I couldnt find something in their. Only something commented out. Is this because of a different Version that the definition for this is now in a different Header file?

It seems you are following the Cherno's game engine tutorial. I ran into this issue too. Thanks for the answer @Nickyhub

**Comment by NAYOlxy** [comment]
Thanks for the answer.I am also following Cherno's video and confused about this.

**Comment by awa-A** [comment]
same, faced this while studying from cherno's game engine series. thanks for the comments guys

**Comment by Brandaldino** [comment]
Thanks, I will catch up with you.
