### ISSUE TITLE
How to print source file name and line number with spdlog::default_logger_raw()

### ISSUE THREAD

**Issue by rafieshamsaasef** [gabime/spdlog#1515]
I have a wrapper around spdlog::default_logger_raw() but I need to print file name and line number with the debug log. Can you show an example?

**Comment by tt4g** [comment]
You can use custom format such as `%@`, `%s`, `%g`, `%#`, `%!` with logging macro such as `SPDLOG_LOGGER_TRACE`, `SPDLOG_LOGGER_DEBUG`.
Don't forget to define `SPDLOG_ACTIVE_LEVEL` macro to enable these macros.

Example:

```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // Must: define SPDLOG_ACTIVE_LEVEL before `#include "spdlog/spdlog.h"`
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"

void source_info_example()
{
    auto console = spdlog::stdout_logger_mt("console");
    spdlog::set_default_logger(console);
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");

    SPDLOG_LOGGER_INFO(console, "log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 10] log with source info"
    SPDLOG_INFO("global log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 11] global logger with source info"

    console->info("source info is not printed"); // Console: "[source ] [function ] [line ] source info is not printed"
}
```

See also: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/spdlog.h#L278-L285

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/common.h#L127-L137

**Comment by rafieshamsaasef** [comment]
Thanks for the help. The code you sent works but I need to get access to currently configured logger not creating a new console logger. I create spdlog with all patterns and settings at the application start up code but use the log macro all over the code to log. So how do I get access to my already setup logger pointer? So I can pass it to spdlog::set_default_logger(console);

**Comment by tt4g** [comment]
Look `spdlog/spdlog.h` and example.
There are macros that accept loggers such as `SPDLOG_LOGGER_TRACE`, `SPDLOG_LOGGER_DEBUG`, `SPDLOG_LOGGER_INFO`.

```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // Must: define SPDLOG_ACTIVE_LEVEL before `#include "spdlog/spdlog.h"`
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"

void source_info_example()
{
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
    auto console = spdlog::stdout_logger_mt("console");

    SPDLOG_LOGGER_INFO(console, "log with source info"); // Use console.
    SPDLOG_INFO("global log with source info"); // Use spdlog::default_logger()

    console->info("source info is not printed"); // Console: "[source ] [function ] [line ] source info is not printed"
}
```

**Comment by rafieshamsaasef** [comment]
Got it. Thanks.
