### ISSUE TITLE
how to print a default line at the start of each rotation sink file

### ISSUE THREAD

**Issue by haddad123123** [gabime/spdlog#1518]
m_Logger = spdlog::rotating_logger_mt("logger", m_Path, 1048576 * 10 , 3);

i want the line "Haddad" to be printed at the start of each rotated file.
so when my program finish and i open the logs, i will see :
first file : 
Haddad
(some log)
(some log)
(some log)

second file : 
Haddad
(some log)
(some log)
(some log)

third file : 
Haddad
(some log)
(some log)
(some log)

so it doesn't matter how much rotated files i would have
the line : Haddad" 
will be showed in every file that created by the rotation sink.

**Comment by gabime** [comment]
There is no such way. There is related pending issue #1225
