### ISSUE TITLE
how to print uint8_t buffer in spdLogger

### ISSUE THREAD

**Issue by haddad123123** [gabime/spdlog#1519]
Hi,
is there a way using the spdLogger ,to print byte buffer as string ?
example :
buffer {A,3,0,F8} = > 0A0300F8

or is there any way to move the byte buffer to str without using any loop?
to be printed as explained.

**Comment by tt4g** [comment]
If buffer is iterable then `#include "spdlog/fmt/bin_to_hex.h"` and use `spdlog::to_hex()`.

Example:

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/example/example.cpp#L151-L156

**Comment by haddad123123** [comment]
thank you very much i will try this ASAP 
and return an answer if this works for me

**Comment by haddad123123** [comment]
hi @tt4g 
it looks it worked for me really well
but still it prints it in new line
how can i print in in same line?

example :

i am printing : 
 m_Logger->info("{},{},{},{},{},,,{:Xp}"......

output : 
2,122102399,121613792,32,1,,,
20 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

its not printing the buffer at the same line 
and i got two lines of the buffer 
i always get a second line of the buffer all with zeros

**Comment by tt4g** [comment]
Use `n` option. e.g: `{Xps}`

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/fmt/bin_to_hex.h#L11-L14

**Comment by haddad123123** [comment]
thanks you it works great

**Comment by haddad123123** [comment]
you can close the issue
very helpful thanks.

**Comment by tt4g** [comment]
I cannot close this issue.
