### ISSUE TITLE
CMakeLists.txt: include(GNUInstallDirs) should be after project statement

### ISSUE THREAD

**Issue by jenisys** [gabime/spdlog#1523]
Newer CMake versions (example: 3.17.1) indicate the problem that "include(GNUInstallDirs)" statement should be moved after the "project(...)" statement.

```sh
$ mkdir build && cd build && cmake ..
CMake Warning (dev) at /xxx/cmake/3.17.1/share/cmake/Modules/GNUInstallDirs.cmake:225 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:9 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
...
```

HINT:
Newer cmake versions can be installed via "pip install -U cmake" if the local package manager has  a more conservative package update policy (and has not newer cmake versions).

**Comment by tt4g** [comment]
Already fixed in v1.x branch:  #1407
