### ISSUE TITLE
Suggestion for SPDLOG_ERRNO macro

### ISSUE THREAD

**Issue by ltaurines** [gabime/spdlog#1524]
Hi,

Thanks for this great library.

Would he be relevant to have a SPDLOG_ERRNO (log level == err) MACRO that would had std::strerror(errno) to the message, may be even in the source location.

The idea is to obtained something as:
2020-04-20 09:38:14.279 [error] [tid 13078] [ltlab.cpp:58:No such file or directory] Could not open "/MyPath/MyFile"

To get it so far i added the following code. 

#if SPDLOG_ACTIVE_LEVEL <= SPDLOG_LEVEL_ERROR
#define SPDLOG_ERRNO_CALL(logger, level, ...) (logger)->log(spdlog::source_loc{__FILE__, __LINE__, std::strerror(errno)}, level, __VA_ARGS__)
#define SPDLOG_ERRNO_ERROR(logger, ...) SPDLOG_ERRNO_CALL(logger, spdlog::level::err, __VA_ARGS__)
#define SPDLOG_ERRNO(...) SPDLOG_ERRNO_ERROR(spdlog::default_logger_raw(), __VA_ARGS__)
#endif

Thank you

Laurent.

**Comment by gabime** [comment]
Thanks for the suggestion! I am not sure is should be part of the API though. This data can be  passed by the user easily

**Comment by ltaurines** [comment]
Almost all data are quite easy to pass. The point is more on the number of data to pass. For the middleware type of code I write it would have been one less. 
But ok it is fair. 

I sometimes need the source location information but not within the spdlog default pattern. So with my own pattern something as 
"%m-%d %H:%M:%S.%e [%^%4!l%$] [tid %5t] [%s:%!:%#] %v" 
I end up with 2 colon in a pair of square bracket "[::] when I call functions and not macros like,
"04-21 19:02:45.443 [error] [tid  4305] [::] The final error message"

Is there a way to avoid this useless "[::]" without using 2 different loggers nor overriding the SPDLOG_MACRO?

Thanks,

Laurent.


----- Mail original -----
De: "Gabi Melman" <notifications@github.com>
À: "gabime/spdlog" <spdlog@noreply.github.com>
Cc: "ltaurines" <ltaurines@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 21 Avril 2020 14:59:01
Objet: Re: [gabime/spdlog] Suggestion for SPDLOG_ERRNO macro (#1524)





Thanks for the suggestion! I am not sure is should be part of the API though. This data can be passed by the user easily

**Comment by gabime** [comment]
There is a new feature that you can try for this. Specify a custom flag handler that prints `[:filename:]` only when the filename is not empty.
