### ISSUE TITLE
Set pattern %s specifier not working as expected on windows build

### ISSUE THREAD

**Issue by dempo93** [gabime/spdlog#1526]
In my program I set the following pattern
```
spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%L] [%s:%#] %^%v%$");
```
and I expect something like this as an output
```
[2020-04-21 17:56:31.360] [warning] [machineIdentification.cpp:34] Message
```
Which is what I get when building on linux
However what I get on windows is the following
```
[2020-04-21 17:56:31.360] [warning] [C:/path/to/machineIdentification.cpp:34] Message 
```

I narrowed it down to the `__FILE__` macro being expanded to `C:/path/to/machineIdentification.cpp` with **forward** slashes instead of `C:\path\to\machineIdentification.cpp` . 

My workaround at the moment is forcing the folder separator in https://github.com/gabime/spdlog/blob/2b326e90b82f74492229b8d2b27d66d088386e74/include/spdlog/details/os.h#L36 to be `/` both under windows and linux

I am using Visual Studio 19 with Windows SDK version 10.0.18362.0 and Microsoft Build Engine version 16.4.0+e901037fe

**Comment by gabime** [comment]
> with forward slashes instead of

How can this reproduced?

**Comment by Tradias** [comment]
Turns out it is not related to spdlog.

To reproduce:
```
// file.h
std::string file() {
  return __FILE__;
}


// main.cpp
#include <iostream>
#include "absolute/path/to/file.h"

int main() {
  std::cout << file();
}
```
This outputs: `absolute/path/to/file.h` exactly how it is spelled in the include statement (tested with Visual Studio 19).

**Comment by gabime** [comment]
ok. thanks
