### ISSUE TITLE
Error on Android compilation

### ISSUE THREAD

**Issue by Bizyroth** [gabime/spdlog#1527]
Hello
I'm trying to compile spdlog for Android but i'm facing multiple error:

- `spdlog/include/spdlog/pattern_formatter.h:83:95: error: converting to 'spdlog::pattern_formatter::custom_flags {aka std::unordered_map<char, std::unique_ptr<spdlog::custom_flag_formatter> >}' from initializer list would use explicit constructor 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = char; _Tp = std::unique_ptr<spdlog::custom_flag_formatter>; _Hash = std::hash<char>; _Pred = std::equal_to<char>; _Alloc = std::allocator<std::pair<const char, std::unique_ptr<spdlog::custom_flag_formatter> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<char>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<char>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const char, std::unique_ptr<spdlog::custom_flag_formatter> > >]'
         std::string eol = spdlog::details::os::default_eol, custom_flags custom_user_flags = {});`

- `include/spdlog/common.h:238:65: error: converting to 'spdlog::pattern_formatter::custom_flags {aka std::unordered_map<char, std::unique_ptr<spdlog::custom_flag_formatter> >}' from initializer list would use explicit constructor 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = char; _Tp = std::unique_ptr<spdlog::custom_flag_formatter>; _Hash = std::hash<char>; _Pred = std::equal_to<char>; _Alloc = std::allocator<std::pair<const char, std::unique_ptr<spdlog::custom_flag_formatter> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<char>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<char>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const char, std::unique_ptr<spdlog::custom_flag_formatter> > >]'
     return std::unique_ptr<T>(new T(std::forward<Args>(args)...));`

- `include/spdlog/sinks/ansicolor_sink-inl.h:79:16: error: converting to 'spdlog::pattern_formatter::custom_flags {aka std::unordered_map<char, std::unique_ptr<spdlog::custom_flag_formatter> >}' from initializer list would use explicit constructor 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = char; _Tp = std::unique_ptr<spdlog::custom_flag_formatter>; _Hash = std::hash<char>; _Pred = std::equal_to<char>; _Alloc = std::allocator<std::pair<const char, std::unique_ptr<spdlog::custom_flag_formatter> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<char>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<char>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const char, std::unique_ptr<spdlog::custom_flag_formatter> > >]'
     formatter_ = std::unique_ptr<spdlog::formatter>(new pattern_formatter(pattern));
`

The same code compiles well on linux

**Comment by gabime** [comment]
How do you compile and which ndk version are you using?

 I can't reproduce with ndk 21.1.6352462
