### ISSUE TITLE
dup_filter_sink_mt problem with syslog logging

### ISSUE THREAD

**Issue by jafar75** [gabime/spdlog#1528]
According to [https://github.com/gabime/spdlog/issues/696](url), one can define dup_filter_sink to remove identical consecutive log messages. I wnat to use it with syslog sink. 

    #include <chrono>

    #include <spdlog/spdlog.h>
    #include <spdlog/sinks/syslog_sink.h>
    #include <spdlog/sinks/dup_filter_sink.h>
    #include <spdlog/sinks/stdout_color_sinks.h>

    int main() {
        auto dup_filter = std::make_shared<spdlog::sinks::dup_filter_sink_mt>(std::chrono::seconds(5));
        dup_filter->add_sink(std::make_shared<spdlog::sinks::syslog_sink_mt> ("filtered_syslog_sink_mt"));
        spdlog::logger l("logger", dup_filter);
        l.info("Hello");
        l.info("Hello");
        l.info("Hello");
        l.info("Different Hello");
    }

it has an error:

> /mnt/g/spdlog-logger/src/tmp_file.cpp:10:99:   required from here
/usr/include/c++/7/ext/new_allocator.h:136:4: error: no matching function for call to ‘spdlog::sinks::syslog_sink<std::mutex>::syslog_sink(const char [24])’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }

**Comment by jafar75** [comment]
> According to [https://github.com/gabime/spdlog/issues/696](url), one can define dup_filter_sink to remove identical consecutive log messages. I wnat to use it with syslog sink.
> 
> `#include
> 
> #include <spdlog/spdlog.h>
> #include <spdlog/sinks/syslog_sink.h>
> #include <spdlog/sinks/dup_filter_sink.h>
> #include <spdlog/sinks/stdout_color_sinks.h>
> 
> int main() {
> auto dup_filter = std::make_sharedspdlog::sinks::dup_filter_sink_mt(std::chrono::seconds(5));
> dup_filter->add_sink(std::make_sharedspdlog::sinks::syslog_sink_mt("filtered_syslog_sink_mt"));
> spdlog::logger l("logger", dup_filter);
> l.info("Hello");
> l.info("Hello");
> l.info("Hello");
> l.info("Different Hello");
> }`
> 
> it has an error:
> 
> > /mnt/g/spdlog-logger/src/tmp_file.cpp:10:99:   required from here
> > /usr/include/c++/7/ext/new_allocator.h:136:4: error: no matching function for call to ‘spdlog::sinks::syslog_sinkstd::mutex::syslog_sink(const char [24])’
> > { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }

**Comment by gabime** [comment]
syslog_sink_mt doesn't have a ctor that gets only a string..You need to pass 4 args.

**Comment by jafar75** [comment]
Could you please give an example for the ctor?
i tested with 

    dup_filter->add_sink(std::make_shared<spdlog::sinks::syslog_sink_mt>("filtered_syslog_sink_mt", 
                                  "some_indent", 0, 0, false));

but it does not work.

**Comment by jafar75** [comment]
thanks. it is working.
