### ISSUE TITLE
Modify log level name (e.g. "info" --> ℹ️)

### ISSUE THREAD

**Issue by SylvainCecchetto** [gabime/spdlog#1529]
Hi,

I know that we can modify a logger pattern with `set_pattern` but is It possible to change a existing `spdlog::level::level_enum` name?

My goal is:

```
info --> ℹ️
warn --> ⚠️
...
```

Before:
`[09:47:13.678] [  boa_disas  ] [I] Modified BasicBlock at address 0x10011d7`

After:
`[09:47:13.678] [  boa_disas  ] [ℹ️] Modified BasicBlock at address 0x10011d7`

Thank you!

**Comment by tt4g** [comment]
You can define `SPDLOG_LEVEL_NAMES` or `SPDLOG_SHORT_LEVEL_NAMES` to replace log level name.

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/tweakme.h#L88-L100

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/common-inl.h#L12-L14

**Comment by SylvainCecchetto** [comment]
This is exactly what I was looking for! Thank you so much!
