### ISSUE TITLE
Automatically delete old file logs when spdlog is initialised.

### ISSUE THREAD

**Issue by IIFE** [gabime/spdlog#1531]
Hi,

Is it possible to automatically delete old file logs when spdlog is initialised? For example if I want to delete logs if spdlog detect that a log file is older than 7 days, is this possible?

**Comment by gabime** [comment]
see daily_sink ctor for this https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/daily_file_sink.h#L49

**Comment by IIFE** [comment]
Thanks. So for my purposes I need to set `rotation_hour` to 24, and `max_files` to 7, correct?

**Comment by gabime** [comment]
you mean rotation hour 0..

**Comment by IIFE** [comment]
Sorry I may not be fully understanding the ctor. How is 0 hours going to create a new files every day, and delete the oldest file on the 7th day? Doesn't 0 hours mean no creation of new files?

**Comment by gabime** [comment]
0 means create new file each midnight.

**Comment by IIFE** [comment]
Aah gotcha. Thought the parameter meant an interval rather than the actual time.

That explains it. Thanks.
