### ISSUE TITLE
how to print std::map with spdlog

### ISSUE THREAD

**Issue by chenpengfei** [gabime/spdlog#1532]
```
int main()
{
    std::map<std::string, std::string> o;
    o["foo"] = "foo value";
    spdlog::info(o);
    return 0;
}
```
Got error: static_assert failed due to requirement 'formattable' "Cannot format argument. To make type T formattable provide a formatter specialization: https://fmt.dev/latest/api.html#formatting-user-defined-types"

**Comment by tt4g** [comment]
Should `#include "spdlog/fmt/bundled/ranges.h"` or `#include "fmt/ranges.h"`, and first argument of `spdlog::info()` is characters.

Example:

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/fmt/bundled/ranges.h

int main()
{
    std::map<std::string, std::string> o;
    o["foo"] = "foo value";
    spdlog::info("{}", o);
    return 0;
}
```

See also fmt API document: https://fmt.dev/latest/api.html#ranges-api

**Comment by chenpengfei** [comment]
@tt4g  thanks very much

**Comment by chenpengfei** [comment]
when I add `#include "spdlog/fmt/bundled/ranges.h"`

I got a new issue: custom struct will not work, eg:
template<typename OStream>
        friend OStream &operator<<(OStream &os, const Person& v) {
            return os << v.age ;
        }

error info:
cannot pass object of non-trivial type 'const sb::scuttlebutt_accept' through variadic method; call will abort at runtime
