### ISSUE TITLE
"mutex destroyed while busy" message from application with asynchronnous logger

### ISSUE THREAD

**Issue by nayz-git** [gabime/spdlog#1533]
To reproduce (I tested it on Windows 10 using VS2017):

```cpp
#include "spdlog.h"
#include "sinks/stdout_color_sinks.h"
#include "async.h"
#include "async_logger.h"
#include <memory>

void main()
{
	spdlog::init_thread_pool(8192, 1);
	auto sink {std::make_shared<typename spdlog::sinks::stdout_color_sink_mt>()};
	auto logger {std::make_shared<spdlog::async_logger>(
		"MyLogger",
		sink,
		spdlog::thread_pool(),
		spdlog::async_overflow_policy::overrun_oldest)};
	logger->log(spdlog::level::level_enum::err, "Test message...");
}
```

### Problem description

The static function `static mutex_t &mutex()` defined in `console_mutex` class (spdlog/details/console_globals.h) defines static local variable `s_mutex` (of type std::mutex). This mutex is constructed at the moment a console sink is created.

After the main function exits the statically allocated objects are destroyed including this mutex. But at the same time the worker thread is processing the message and thus the mutex can still be locked by the `wincolor_sink<ConsoleMutex>::log(...)` function.

This behaviour can be surely reproduced by adding some delay to an appropriate place inside this function (it is not necessary in my case), e.g.:

```cpp
template<typename ConsoleMutex>
void SPDLOG_INLINE wincolor_sink<ConsoleMutex>::log(const details::log_msg &msg)
{
	std::lock_guard<mutex_t> lock(mutex_);
	std::this_thread::sleep_for(std::chrono::seconds(1));
	...
```

As far as I can see the problem is that the mutex is allocated statically and thus there is no way to control its life time. Maybe better would be to not allocate the mutex statically but dynamically and reference it using shared pointers (from the `wincolor_sink` objects).

### Possible workaround

As a workaround `spdlog::shutdown()` can be called at the very end of the `main` function. This ensures that the worker thread ends (and the message is written to the console) before end of the main function and therefore before the statically allocated mutex is destructed.

But sometimes it can be difficult to do so, e.g. when using an application framework that offers no direct access to `main()` function.

**Comment by gabime** [comment]
Thanks for the report. This is known issue with msvc that was reported many times.
 One must call shutdown() under windows before end of main or dll.

**Comment by nayz-git** [comment]
Thank you for your answer.
