### ISSUE TITLE
Log in shared_ptr holded instance deconstructor will throw exception

### ISSUE THREAD

**Issue by lanrobin** [gabime/spdlog#1538]
`
// exception will throw in ~A().
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"

using namespace std;

struct A;

static shared_ptr<A> STATIC_A = nullptr;

struct A {
	A() {
		spdlog::info("A Constructor");
	}

	int printLog() {
		spdlog::info("A:printLog");
		return 0;
	}

	~A() {
		spdlog::info("A Destructor");
	}

	static void initInstance() {
		assert(STATIC_A == nullptr);
		STATIC_A = make_shared<A>();
		spdlog::info("STATIC_A use_count:{}", STATIC_A.use_count());
	}

	static shared_ptr<A> getIntance() {
		return STATIC_A;
	}
};

int main()
{
	spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");
	spdlog::info("Welcome to spdlog!");
	spdlog::error("Some error message with arg: {}", 1);
	spdlog::info("Hello CMake.");
	A::initInstance();
	auto a = A::getIntance();
	auto result = a->printLog();
	spdlog::info("STATIC_A use_count:{}", a.use_count());
	spdlog::info("printLog returns:{}", result); 
	return 0;
}
`

**Comment by gabime** [comment]
spdlog get destroyed after main exit, but you try to use it  in your  
~A() destructor(static destruction is called in undefined order after main)

**Comment by lanrobin** [comment]
Thanks, got resolved.
