### ISSUE TITLE
log category feature

### ISSUE THREAD

**Issue by azadkuh** [gabime/spdlog#154]
it would be nice to have `Logging Category` like: [Qt5](http://doc.qt.io/qt-5/qloggingcategory.html) / [Qt weekly #1](http://blog.qt.io/blog/2014/03/11/qt-weekly-1-categorized-logging)

by category, one can *optionally* control and manage different logs of application (as db, net, hardware, math, ...) into a single log file. even a basic implementation of category would be great.

at the moment, is there any way to attach different logs (as category name) to a single file?!

**Comment by gabime** [comment]
If I understood your question then logging category is already supported by using logger names.

You just need to share a sink between different loggers

For example:

```c++
auto rotating_sink = make_shared<spdlog::sinks::rotating_file_sink_mt> ("log_filename", "log", 1024*1024, 5, false);
auto net_logger = make_shared<spdlog::logger>("net", rotating_sink);
auto hw_logger = make_shared<spdlog::logger>("hw", rotating_sink);
auto db_logger = make_shared<spdlog::logger>("db", rotating_sink);
```
And then anywere in the program:

```c++
spdlog::get("net")->info("....");
spdlog::get("db")->debug("....");

//Or the the preferred way (avoiding too much spd::get("..") calls which are slower
auto hw_logger = spd::get("hw");
hw_logger->info("...");
hw_logger->info("...");
hw_logger->info("...");
```

**Comment by azadkuh** [comment]
thanks. that's gr8! 
i had not noticed:
```cpp
logger::logger(const std::string& logger_name, sink_ptr single_sink);
```
IMHO it's so important that it should be explicitly mentioned in *Quick Start*!

**Comment by gabime** [comment]
**Edit** : I forgot to mention in the example that if you create loggers this way you also need to register in order to use the spdlog::get(..) method:
```c++
spdlog::register_logger(hw_logger);
spdlog::register_logger(net_logger);
spdlog::register_logger(db_logger);
```
```
