### ISSUE TITLE
Need to test if pattern_formatter.h exists

### ISSUE THREAD

**Issue by ncihnegn** [gabime/spdlog#1543]
To build for both 1.5 and 1.6, we need a way to skip pattern_formatter.h.
I wish I can write code like this:
```
#include <spdlog/spdlog.h>

#if SPDLOG_HAS_PATTERN_FORMATTER
#include <spdlog/pattern_formatter.h>
class my_formatter_flag : public spdlog::custom_flag_formatter 
...
#endif
```

**Comment by gabime** [comment]
In 1.5 it exists too, in spdlog/details.

**Comment by ncihnegn** [comment]
> In 1.5 it exists too, in spdlog/details.

The include path changes. How to detect that?

**Comment by gabime** [comment]
you can check the SPDLOG_VERSION or the other macros on spdlog/version.h
