### ISSUE TITLE
Logging after every minute

### ISSUE THREAD

**Issue by hamzakhalidsc** [gabime/spdlog#1544]
I want to start the logging when the application starts. This log will be shared among multiple threads. The problem is the I want to add a new log after every one minute. I donot wish to delete the previous logs. Should I make use of the sink interface and write my own class or does tweaking the configurations in the current functionality will help me do it ?

**Comment by gabime** [comment]
There is no such sink, so you should develop it. See #222 for a reference(old pr).

**Comment by hamzakhalidsc** [comment]
@gabime thanks.
