### ISSUE TITLE
Compile error on implementing custom sink

### ISSUE THREAD

**Issue by andre237** [gabime/spdlog#1545]
I'm creating a file sink that can reopen the file in case of external deletion. I followed the steps in wiki and used the `basic_file_sink` as example. 
The error issued by the compiler is the following:

`/usr/include/c++/8/ext/new_allocator.h:136:4: error: no matching function for call to ‘spdlog::logger::logger(std::__cxx11::basic_string<char>, std::shared_ptr<reloadable_file_sink<std::mutex> >)’`

I see that one of the logger constructors expects its name and a `std::shared_ptr<sinks::sink>`, so I guess the sink i created is not of type `sinks::sink`. 

Here's my sink code:

```
#include <spdlog/sinks/base_sink.h>
#include <spdlog/details/file_helper.h>
#include <spdlog/details/synchronous_factory.h>

template<typename Mutex>
class reloadable_file_sink : spdlog::sinks::base_sink<Mutex> {
private:
    spdlog::details::file_helper file_helper_;

public:
    explicit reloadable_file_sink(const std::string& filename);

protected:
    void sink_it_(const spdlog::details::log_msg &msg) override;
    void flush_() override;
};

using reloadable_file_sink_mt = reloadable_file_sink<std::mutex>;

template<typename Factory = spdlog::synchronous_factory>
inline std::shared_ptr<spdlog::logger> reloadable_logger_mt(const std::string& logger_name, const std::string& filename) {
    return Factory::template create<reloadable_file_sink_mt>(logger_name, filename);
}
```

Any help???

**Comment by gabime** [comment]
Maybe try to include logger.h?

**Comment by tt4g** [comment]
Missing `public` keyword.

```diff
template<typename Mutex>
- class reloadable_file_sink : spdlog::sinks::base_sink<Mutex> {
+ class reloadable_file_sink : public spdlog::sinks::base_sink<Mutex> {
private:
    spdlog::details::file_helper file_helper_;

public:
    explicit reloadable_file_sink(const std::string& filename);

protected:
    void sink_it_(const spdlog::details::log_msg &msg) override;
    void flush_() override;
};
```

**Comment by andre237** [comment]
So, the public key word did the trick with the compiler error, but now I'm getting a linking error on the constructor and the base class functions:

`undefined reference to spdlog::sinks::reloadable_file_sink<std::mutex>::reloadable_file_sink(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`

`spdlog::sinks::reloadable_file_sink<std::mutex>::sink_it_(spdlog::details::log_msg const&)`

`spdlog::sinks::reloadable_file_sink<std::mutex>::flush_()`

My application is built with cmake, is there something else to be added to CMakeLists?

**Comment by tt4g** [comment]
Issue snippet does not have function implementation.
Where is `reloadable_file_sink` implementation?

**Comment by andre237** [comment]
Yeah, I have a .cpp file, I just ommited its code, but it is set to my cmake compilation target. Now i deleted it and made the implementation inline and it is working. Thanks for the help anyway!
