### ISSUE TITLE
Trace messages not being printed

### ISSUE THREAD

**Issue by brukted** [gabime/spdlog#1548]
I have created a single stdout colored sink for multiple loggers and set the level for the sink to trace.
assigned the sink to all the loggers i created.But trace messages are not being printed.I am using the latest gcc from mingw with vs code and cmake;
Thanks.

**Comment by gabime** [comment]
You need to set the loggers level to trace as well.

**Comment by brukted** [comment]
Thanks.

**Comment by brukted** [comment]
Thank  you. Sent from Mail for Windows 10 From: Gabi MelmanSent: Monday, May 11, 2020 8:18 PMTo: gabime/spdlogCc: brukted; AuthorSubject: Re: [gabime/spdlog] Trace messages not being printed (#1548) You need to set the loggers level to trace as well.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
