### ISSUE TITLE
Combined logger pattern - adding new sinks uses default format

### ISSUE THREAD

**Issue by eliasdaler** [gabime/spdlog#1549]
I make a logger with several sinks like this:

```c++
std::vector<spdlog::sink_ptr> sinks;
sinks.push_back(std::make_shared<spdlog::sinks::stdout_color_sink_st>());
...
combined_logger = std::make_shared<spdlog::logger>("logger", begin(sinks), end(sinks));
combined_logger->set_pattern("%v");
```

then, I add a new sink to the same logger:

```c++
auto& sinks = combined_logger->sinks();
sinks.push_back(std::make_shared<ImGuiConsoleSink>(devState->getConsole()));
```

The problem is - the default pattern is used for that sink, not the custom one. Is this an expected behaviour?

Even if I do this, the default pattern (with logger name, source file, etc.) is used for newly added sinks:

```c++
spdlog::register_logger(combined_logger);
spdlog::set_default_logger(combined_logger);
spdlog::set_pattern("%v");
```

**Comment by gabime** [comment]
It is expected (though it can be confusing I agree). 
All that `logger->set_pattern(..)` is doing is to set the pattern in each sink in this logger. 

So if you need to add a sink later, you should set the format directly on the sink(`sink->set_pattern(..)`) or call again  `logger- set_pattern(..)` after the sink was added.

**Comment by tt4g** [comment]
NOTE: `spdlog::logger::sinks()` is not thread safety.
If a sink is added during a call to `spdlog::logger::sink_it_()`, the iterator may be disabled (of course, as long as it's single-threaded, there's no problem.).

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/logger-inl.h#L145-L148

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/logger-inl.h#L177-L195

It is recommended to manage multiple sinks with `spdlog::sinks::dist_sink`.
You can safely add a sink with `spdlog::sinks::dist_sink::add_sink()`.

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/sinks/dist_sink.h#L34-L38

**Comment by eliasdaler** [comment]
Thanks a lot, everyone! This solves my issue.

I think it would be great to mention `dist_sink` as the alternative to `sinks()` in the end of [this page](https://github.com/gabime/spdlog/wiki/4.-Sinks).
