### ISSUE TITLE
rotating notification / user's callback

### ISSUE THREAD

**Issue by azadkuh** [gabime/spdlog#155]
it would be great if `spdlog::rotating_file_sink` constructor accepts an optional callback which will be called when `rotating_file_sink::_rotate()` finishes (similar to `spdlog::set_async_mode` warmup_cb)

by this callback, one can do:
- compress the older logs with his/her favorite algorithm
- move, backup, send, ... the rotating files
- notify a node or an admin user 
- process the latest rotate file and make a report
- handle errors by clean up, ...
- ...

at the right time.

**Comment by bakinat** [comment]
If I may add another related enhancement to also be able to access the new created file (maybe in a separate callback) to do such thing as writing a common header line.
Thanks, Barak

**Comment by asit-dhal** [comment]
Hi @gabime ,

Should that callback  be supplied with any arguments ?

**Comment by gabime** [comment]
which arguments for example?

**Comment by asit-dhal** [comment]
file name or simply a notifcation should be made ?

**Comment by gabime** [comment]
Good idea. I think the both new and old filenames shoud be passed (and maybe also the open fd of the new file if the user wants to write stuff to it at this point)

**Comment by asit-dhal** [comment]
ok thanks

I will add those and send you a pull reuqest.
Please ignore the PR https://github.com/gabime/spdlog/pull/487
