### ISSUE TITLE
1.6.0 on MSVC pulls in min/max macros by default

### ISSUE THREAD

**Issue by norbertwenzel** [gabime/spdlog#1553]
I just switched to 1.6.0 and my project would not build any more on MSVC. It seems something has changed between 1.5.0 and 1.6.0 that requires me to define `NOMINMAX` to disable these WinAPI macros.

I'm still searching the actual change. I'll post an update when I found it.

**Comment by gabime** [comment]
Probably because spdlog doesn't include window.h in its public header (and hence doesn't define NOMINMAX for your code).

**Comment by norbertwenzel** [comment]
Thank you for the swift reply. I think the include comes from the bundled fmt library, as referenced above, and has been introduced in 7698bb0ae1029ffa0b97b7924adba50e2f9bac43.

Would you consider this an issue in spdlog (as it copies fmt's upstream source) or should I close this ticket?

**Comment by gabime** [comment]
yes, seems like you are right. closing.

**Comment by norbertwenzel** [comment]
Just for documentation purposes: It seems fmt intentionally removed their elaborate macro guards before including `windows.h` as discussed in https://github.com/fmtlib/fmt/issues/1508.
So the solution is to define `NOMINMAX` for yourself, if one wants to use the header-only version or use fmt (and maybe also/only spdlog, I did not investigate that) as a compiled library, so the WinAPI include stays an implementation detail.

**Comment by gabime** [comment]
@norbertwenzel Maybe it is worthwhile to add this inti the [FAQ](https://github.com/gabime/spdlog/wiki/0.-FAQ)

**Comment by norbertwenzel** [comment]
Sorry, I didn't find time for that this evening. Will do tomorrow.
Are there any conventions I should follow in the wiki?

**Comment by gabime** [comment]
No. knock yourself out.

**Comment by norbertwenzel** [comment]
@gabime Added to [FAQ](https://github.com/gabime/spdlog/wiki/0.-FAQ#winapi-minmax-macro-definitions). HTH.

**Comment by gabime** [comment]
Thanks! I modified it a little
