### ISSUE TITLE
Enhancement: Use configuration variables to rename the spdlog environment variables

### ISSUE THREAD

**Issue by jeanga** [gabime/spdlog#1554]
Hi,

With the recent release of spdlog, it is possible to use environment variable to modify loggers behavior.
While this is a great new features, I miss the ability to configure the name of the environment variables. 

If I have multiple binaries and/or binaries creating children processes, I do not have an easy way to configure logging for a specific binary.

If A launches B and both A&B use spdlog, I have no way to configure logging only for A or B.

CMake configuration would be a great way to make sure each binary has it's own environment variable to configure logging.

Thank you for spdlog, it's a great library!

**Comment by tt4g** [comment]
You should be able to change the log level on a per-process basis with `spdlog::cfg::load_argv_levels`.

https://github.com/gabime/spdlog/blob/83b9149930f392d7797b54fe97a66ab3f2120671/example/example.cpp#L134-L136

You can also generate arguments to pass to `spdlog::cfg::load_argv_levels` from your own environment variables.
Take a look at the following test:

https://github.com/gabime/spdlog/blob/d09e03606cd4ca0c0dde835f1b26d0311bec37ff/tests/test_cfg.cpp#L28-L30

Example (I haven't tested it):

```cpp
const char *log_level = std::getenv("MY_SPDLOG_LEVEL");

if (log_level) {
    std::string log_level_str = "SPDLOG_LEVEL=";
	log_level_str.append(log_level);

    const char *argv[] = {"ignore", log_level_str._c_str()};

    spdlog::cfg::load_argv_levels(2, argv);
}
```

**Comment by jeanga** [comment]
Thank you for this workaround :-)
