### ISSUE TITLE
FILE* support went away in v1.4.0?

### ISSUE THREAD

**Issue by abrownsword** [gabime/spdlog#1555]
I just tried updating to 1.6.0 from 1.3.0, and have discovered that support for logging to C-style FILE* appears to have been removed (silently, as far as I can tell from the release notes).  Unfortunately I was depending upon this functionality as my code receives Linux file descriptors from a C library I am using, which I had converted to FILE* objects in order to interface to spdlog.  With this support removed, however, I cannot update the library without significant code changes.  What is the recommended approach now to support an ansi color sink that goes to an fd or a FILE*?

**Comment by gabime** [comment]
Not sure which exact interfaces you refer to.. 
The [ansicolor_sink](https://github.com/gabime/spdlog/blob/83b9149930f392d7797b54fe97a66ab3f2120671/include/spdlog/sinks/ansicolor_sink.h#L29) constructor sink expects FILE* in its first param, so you can create it and pass to your logger.

**Comment by abrownsword** [comment]
There used to be 2 template parameters which provided a mutex type and another type... this is changed...?

**Comment by gabime** [comment]
Yes. Now, it is much simpler.  You can just pass FILE* to the constructor .

**Comment by abrownsword** [comment]
Ah, okay, thanks.  Wasn't immediately obvious from the errors produced.
