### ISSUE TITLE
uselss-cast warning in gcc 10 

### ISSUE THREAD

**Issue by madeso** [gabime/spdlog#1557]
With this code:
```cpp
#include "spdlog/spdlog.h"

int
main(int, char* [])
{
    return 0;
}
```
Running `g++ -I. -std=c++17 -Wuseless-cast main.cc` with g++ 10.1.0 on arch linux using spdlog [1.6.0](https://github.com/gabime/spdlog/releases/tag/v1.6.0) I get the following useless-cast warning:

```
In file included from ./spdlog/details/os.h:110,
                 from ./spdlog/details/log_msg-inl.h:10,
                 from ./spdlog/details/log_msg.h:35,
                 from ./spdlog/logger.h:18,
                 from ./spdlog/details/registry-inl.h:12,
                 from ./spdlog/details/registry.h:111,
                 from spdlog/spdlog.h:13,
                 from main.cc:1:
./spdlog/details/os-inl.h: In function ‘int spdlog::details::os::pid()’:
./spdlog/details/os-inl.h:389:12: warning: useless cast to type ‘int’ [-Wuseless-cast]
  389 |     return static_cast<int>(::getpid());
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Removing the static_cast removes the warning, but I'm not sure what the repercussions are for other compilers

**Comment by gabime** [comment]
The problem is that `getpid()` officialy defined as returning a pid_t .There is no guarantee that pid_t is exactly an  int(even though it is very likely).
If you know a trick to avoid the cast if typeof (pid)== int i will happy to fix

**Comment by madeso** [comment]
I was thinking perhaps of something along the lines of function overloading, template specializations or sfinae and started tinkering, but apparently just storing it in a temporary variable removes the warning.

Unless I'm thinking about it the wrong way or missing something this shouldn't remove the useless cast, since it's still there, and it's either a invalid warning (since it's a pid_t) or the "fix" shouldn't remove the warning (and it's a spotty useless-cast detection).

I might have to consider dropping the useless-cast warning.

```cpp
// warning
    return static_cast<int>(::getpid());

// no warning
    const auto p = ::getpid();
    return static_cast<int>(p);
```

**Comment by gabime** [comment]
Strange indeed. compiler bug? or yet another cpp corner case? 

Anyway, recommended usage is the compiled lib. This will save you ton of time compiling and dealing with strange warnings.
