### ISSUE TITLE
Multiple loggers, single sink file: Wrong log statement order

### ISSUE THREAD

**Issue by peza8** [gabime/spdlog#1558]
I use the paradigm of creating a separate logger in each major class with the name of the class. All these loggers share a single sink file. 

**The issue**: The produced text file has '*sections*', where each logger writes, rather then ordering log statements sequentially/chronologically. 

**Code to create loggers:** 
```
    std::vector<spdlog::sink_ptr> sinks;
    sinks.push_back(std::make_shared<spdlog::sinks::stdout_color_sink_mt>());
    sinks.push_back(std::make_shared<spdlog::sinks::basic_file_sink_mt>(sink_filepath));
    auto logger = std::make_shared<spdlog::logger>(logger_name_unique, begin(sinks), end(sinks));
```

**Typical output:**
```
[2020-05-19 12:02:11.848004] [th 37616] [debug] [MissionController] Creating new logger with 2 sinks
[2020-05-19 12:02:11.848036] [th 37616] [info] [MissionController] Initialising mission manager
[2020-05-19 12:02:11.848049] [th 37616] [info] [MissionController] Started state machine
[2020-05-19 12:03:04.705216] [th 37616] [debug] [MissionController] Releasing mission controller
[2020-05-19 12:02:08.691114] [th 37616] [debug] [KinematicTelemetry] Creating new logger with 2 sinks
[2020-05-19 12:02:10.257207] [th 37616] [debug] [KinematicTelemetry] Started package subscription
[2020-05-19 12:03:04.710092] [th 37724] [debug] [KinematicTelemetry] Removing active subscription with package ID = 1
[2020-05-19 12:03:04.971286] [th 37724] [debug] [KinematicTelemetry] Successfully stopped reading telemetry data correctly
[2020-05-19 12:02:10.257731] [th 37616] [debug] [RcTelemetry] Creating new logger with 2 sinks
[2020-05-19 12:02:11.847041] [th 37616] [debug] [RcTelemetry] Started package subscription
[2020-05-19 12:03:05.017615] [th 37733] [debug] [RcTelemetry] Removing active subscription with package ID = 2
[2020-05-19 12:03:05.270080] [th 37733] [debug] [RcTelemetry] Successfully stopped reading telemetry data correctly
[2020-05-19 12:02:01.592009] [th 37616] [debug] [MAIN] Creating new logger with 2 sinks
[2020-05-19 12:02:01.592068] [th 37616] [info] [MAIN] Starting program version 0.3.0
[2020-05-19 12:02:11.847411] [th 37616] [info] [MAIN] Initialised vehicle
[2020-05-19 12:03:04.705540] [th 37616] [info] [MAIN] Exiting program
```

As can be seen from the timestamps, the ordering isn't performed by chronology but rather by the logger names. 

Is this intentional? (I imagine it is, seems harder than chronology). 
Is there an option to order log statements chronologically? 

===============================
Thanks for this library though, it's amazing.

**Comment by tt4g** [comment]
I'll tell you what I know.
This is probably an implementation-dependent specification.
There is no complete guarantee of log order in multithreading.

The timestamp of the log records the time when `spdlog::details::log_msg` was built.
It is created in the `spdlog::logger::log()` function.

After that, `spdlog::logger::log_it_()` is called and log messages are sent to `spdlog::sinks::sink`.

Importantly, at this time, the `spdlog::logger` does not gain a lock by `std::mutex`.
`std::mutex` locking takes place when the sink receives `spdlog::details::log_msg` and when the `spdlog::sinks::sink` outputs `spdlog::details::log_msg`.

When outputting logs in multi-threading, there is a time lag between the generation of `spdlog::details::log_msg` and `spdlog::sinks::sink` acquisition of the `std::mutex` lock.

There is currently no ability to control the order in which the log outputs during this time lag.

TIP: while one logger sends `spdlog::details::log_msg` to `spdlog::sinks::sink`, the other loggers can't send `spdlog::details::log_msg` until `spdlog::sinks::sink` has won a `std::mutex` lock acquisition.
Depending on the acquisition priority of the `std::mutex`, one would expect to see a strange phenomenon of continuous log output from a single thread.

**Comment by tt4g** [comment]
Maybe you need your own custom `spdlog::sinks::sink` to control the output order of the logs.
That sink will have to sort the messages by timestamp, while storing the messages like a queue.
In addition, a lock-free implementation may be required to guarantee write speeds from multithreading.

This sink needs to send the contents of the message queue to the sink it is holding at a particular time (`spdlog::sinks::dist_sink` does something similar).

However, even if you add such a custom sink, the order of messages will swap depending on when `spdlog::details::log_msg` is generated and then added or retrieved in the queue.
After all, there's a time lag between message generation and the `spdlog::details::log_msg` being added to the queue, and in multithreading, the order of messages is swapped.
We cannot rule out the possibility that a message with a new timestamp will be sent from the queue to custom sink before a message with an older timestamp reaches the queue.

This problem exists in log services that aggregate logs from multiple services.
And many of them solve the problem by storing them in the database and then reordering the log messages in timestamp order.

If you want to enforce the order of all log messages in timestamp order, you need the ability for all loggers to acquire locks in a shared `std::mutex`.

**Comment by peza8** [comment]
Thank you so much for your answer @tt4g , but I'm not sure we're on the same page. I completely agree with you on the variability of log message order in a multithreaded environment for log calls that occur close together in time. However, that is not what's happening here. 

I have attached is an [example log file](https://github.com/gabime/spdlog/files/4667820/program_logs.txt) in which there is about **120s** difference in some of the log statements, and they are clearly grouped by specific logger object, not chronologically. 

Let me create a hypothetical example illustrating the point: 

```
    // Create 2 loggers, called A and B
    auto logger_A = std::make_shared<spdlog::logger>("A", "logfile.txt");
    auto logger_B = std::make_shared<spdlog::logger>("B", "logfile.txt");

    // Log 5 messages from each, 1s apart
    std::thread th_A = std::thread([]{
      for (int i = 1; i < 6; ++i) {
        logger_A->info("A msg {}", i);
      }
    });
    std::thread th_B = std::thread([]{
      for (int i = 1; i < 6; ++i) {
        logger_B->info("B msg {}", i);
      }
    });
```

I would expect the output of this in **logfile.txt** to be: 
```
[A] A msg 1
[B] B msg 1
[B] B msg 2   // change in order because of thread race + locking
[A] A msg 2
[A] A msg 3
[B] B msg 3
[A] A msg 4
[B] B msg 4
[A] A msg 5
[B] B msg 5
```

But what I'm seeing is: 
```
[B] B msg 1    // Order of log statement groupings is by most recently created logger
[B] B msg 2
[B] B msg 3
[B] B msg 4
[B] B msg 5
[A] A msg 1
[A] A msg 2
[A] A msg 3
[A] A msg 4
[A] A msg 5
```

I would really like logfile.txt to contain the log messages chronologically, millisecond
 accuracy is not necessary, hence I don't think it's a mutex locking issue.

**Comment by gabime** [comment]
Seems the cause is flushing. Note that file loggers buffer to memory until flushed for better performance . see the flush api on how to control this behaviour.

**Comment by gabime** [comment]
Also having to sinks to same file is not supported. .The 2 loggers should share the same sink.

**Comment by tt4g** [comment]
I've created a project based on your snippet: https://github.com/tt4g/spdlog-issue-1558.git
When I built the following code with Windows OS and VIsual Studio 2019, the logs were alternately logged.

Try to build this project and see how it works.

<details>
<summary>main.cpp</summary>

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"

#include <chrono>
#include <memory>
#include <thread>

static void run_example(
        std::shared_ptr<spdlog::logger> left,
        std::shared_ptr<spdlog::logger> right)
{
    static constexpr auto sleep_count = std::chrono::milliseconds(1);

    std::thread left_thread([left]()
    {
        for (int i = 1; i < 6; ++i) {
            left->info("left msg {}", i);

            std::this_thread::sleep_for(sleep_count);
        }
    });
    std::thread right_thread([right]() {
        for (int i = 1; i < 6; ++i) {
            right->info("right msg {}", i);

            std::this_thread::sleep_for(sleep_count);
        }
    });

    left_thread.join();
    right_thread.join();

    left->flush();
    right->flush();
}

int main(int argc, char** argv)
{
    auto file_sink =
            std::make_shared<spdlog::sinks::basic_file_sink_mt>("log.txt", true);
    auto left_logger = std::make_shared<spdlog::logger>("L", file_sink);
    auto right_logger = std::make_shared<spdlog::logger>("R", file_sink);
    spdlog::register_logger(left_logger);
    spdlog::register_logger(right_logger);

    spdlog::set_level(spdlog::level::trace);

    left_logger->debug("start run_example() with spdlog::level::off");
    left_logger->flush();

    spdlog::flush_on(spdlog::level::off); // spdlog::level::off by default in spdlog 1.6.0.
    run_example(left_logger, right_logger);

    right_logger->debug("start run_example() with spdlog::level::trace");
    right_logger->flush();

    spdlog::flush_on(spdlog::level::trace); // flush every.
    run_example(left_logger, right_logger);

    return 0;
}
```
</details>

<details>
<summary>log.txt</summary>

```plaintext
[2020-05-22 21:41:44.807] [L] [debug] start run_example() with spdlog::level::off
[2020-05-22 21:41:44.808] [L] [info] left msg 1
[2020-05-22 21:41:44.808] [R] [info] right msg 1
[2020-05-22 21:41:44.810] [L] [info] left msg 2
[2020-05-22 21:41:44.810] [R] [info] right msg 2
[2020-05-22 21:41:44.812] [R] [info] right msg 3
[2020-05-22 21:41:44.812] [L] [info] left msg 3
[2020-05-22 21:41:44.814] [L] [info] left msg 4
[2020-05-22 21:41:44.814] [R] [info] right msg 4
[2020-05-22 21:41:44.816] [R] [info] right msg 5
[2020-05-22 21:41:44.816] [L] [info] left msg 5
[2020-05-22 21:41:44.818] [R] [debug] start run_example() with spdlog::level::trace
[2020-05-22 21:41:44.818] [R] [info] right msg 1
[2020-05-22 21:41:44.818] [L] [info] left msg 1
[2020-05-22 21:41:44.820] [L] [info] left msg 2
[2020-05-22 21:41:44.820] [R] [info] right msg 2
[2020-05-22 21:41:44.822] [R] [info] right msg 3
[2020-05-22 21:41:44.822] [L] [info] left msg 3
[2020-05-22 21:41:44.824] [L] [info] left msg 4
[2020-05-22 21:41:44.824] [R] [info] right msg 4
[2020-05-22 21:41:44.826] [R] [info] right msg 5
[2020-05-22 21:41:44.826] [L] [info] left msg 5
```
</details>

**Comment by peza8** [comment]
Thanks for the attention on this issue. The problem was exactly as @gabime stated in the second comment - We were creating a unique sink file object for every logger, non the wiser that this was not correct practise. 

> Also having two sinks with same file is not recommended. .The 2 loggers should share the same sink object. This would also solve the flushing issue - gabime

In @tt4g 's example program a single file sink is use, that's why the chronology is correct. It seems the sink object logs to a specific section of the file when contending with others. 

Issue correctly closed 👍
