### ISSUE TITLE
Can't flush synchronously

### ISSUE THREAD

**Issue by koreus7** [gabime/spdlog#1560]
When my program hits a fatal error I want to flush all the logs immediately and delay exiting until that is done.

This is the code I have at the moment:
```cpp
...
auto file_logger = spdlog::basic_logger_mt("myLogger", filename);
file_logger->flush_on(spdlog::level::critical);
spdlog::set_default_logger(file_logger);
...
spdlog::critical("Some fatal error");
spdlog::default_logger()->flush();
spdlog::shutdown();
// Program exit
```

When I check the log file there is nothing there. If I just log normal debug messages and wait long enough then the log file shows up but if the program crashes then I get nothing.

Is there a way to synchronously ensure that spd log has written out the log and cleaned up?

Thanks.

**Comment by gabime** [comment]
Unless you are using the async logger, flush() should work exactly as you described. 

> if the program crashes

Do you call shutdown from a signal handler?

**Comment by koreus7** [comment]
I looked at it again this morning and it was my mistake.

The critical error logging was happening in the constructor of an object that was declared before the logger was set up.
