### ISSUE TITLE
performance issue for syslog (_st, _mt)

### ISSUE THREAD

**Issue by jafar75** [gabime/spdlog#1564]
Hello there,
I added `spdlog::syslog_logger_st` and `spdlog::syslog_logger_mt` to `bench.cpp`. 
But it gained slightly low performance (about 65k/s). I also tested with some other opensource libs like boost.log and all had the same rate. 
I wonder it is related to implementation or system specs and configs?
Is there any ways to optimize it?

    // Both with 250k messages, about 65k/s
    // Inside bench_single_threaded()
    spdlog::info("");
    auto syslog_st = spdlog::syslog_logger_st("syslog_st");
    bench(iters, std::move(syslog_st));

    // Inside bench_threaded_logging()
    spdlog::info("");
    auto syslog_mt = spdlog::syslog_logger_mt("syslog_mt");
    bench_mt(iters, std::move(syslog_mt), threads);

**Comment by gabime** [comment]
seems syslog is slow see https://stackoverflow.com/questions/208098/can-syslog-performance-be-improved
