### ISSUE TITLE
Question: how to set log file for global logger like SPDLOG_ERROR? 

### ISSUE THREAD

**Issue by junxstudio** [gabime/spdlog#1565]
Hi, 

I'd like to use global logger like SPDLOG_ERROR to output code file and line number (seems this is the only way to do it), but I couldn't figure out how to set the output log file. By default, I didn't see a log file in the folder where app was executed.

**Comment by tt4g** [comment]
You can create file logger and call `spdlog::set_default_logger()` to set to global logger.

Another way. you can use `SPDLOG_LOGGER_<LOGLEVEL>` marco to output file name and line number to local logger.

https://github.com/gabime/spdlog/blob/83b9149930f392d7797b54fe97a66ab3f2120671/include/spdlog/spdlog.h#L320-L326

Example:

```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // define SPDLOG_ACTIVE_LEVEL before `#include "spdlog/spdlog.h"`
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"

void source_info_example()
{
    auto file_logger = spdlog::basic_logger_mt("file_logger", "log.txt");
    spdlog::set_default_logger(file_logger);
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");

    SPDLOG_LOGGER_INFO(file_logger, "log with source info"); // file_logger: "[source example.cpp] [function source_info_example] [line 10] log with source info"
    SPDLOG_INFO("global log with source info"); // file_logger: "[source example.cpp] [function source_info_example] [line 11] global logger with source info"

    file_logger->info("source info is not printed"); // file_logger: "[source ] [function ] [line ] source info is not printed"
}
```
