### ISSUE TITLE
is it legal to use async mode with single threaded sink 

### ISSUE THREAD

**Issue by xwangg** [gabime/spdlog#157]
Thanks very much for providing the awesome log tool, it helps a lot;

I'm wondering that if it is legal to use async mode with single threaded sink while keeping thread safety , like this:

spdlog::set_async_mode(queueSlots);
pGlobalLogger.swap(spdlog::rotating_logger_st("TheLog",
	GetApplicationDirPath() + R"(\logs\)" + prefix + "log", 1048576, 1000)); / * Is it legal to use _st rather than _mt */

I guess the worker thread is the only thread actually writing logs, so it might be OK even if pGloableLogger is used by multithread simultaneously?

**Comment by gabime** [comment]
yes. you are right it is ok since only one thread actually use it in the background. it might be even faster

**Comment by xwangg** [comment]
thanks a lot and happy new year
