### ISSUE TITLE
daily_file_sink has deadlock bug

### ISSUE THREAD

**Issue by IIFE** [gabime/spdlog#1570]
The `sink_it` function of `daily_file_sink` runs under a lock, however it can call `delete_old_`, which internally calls `filename()`. `filename()` tries to acquire the lock, which is already held open. This leads to deadlock.

Happy to fix.

**Comment by gabime** [comment]
Right. Good catch. Strange that nobody encountered this so far..
Fix is welcome

**Comment by IIFE** [comment]
I think some exception handling is swallowing the issue.

**Comment by gabime** [comment]
Imdont exception would happen. just a deadlock after few days when its time to clean old.

**Comment by IIFE** [comment]
What I meant is that when the deadlock occurs, an exception occurs and gets swallowed. This is the behaviour I'm seeing when delete_old_ gets called. Could just be undefined behaviour.

**Comment by gabime** [comment]
This us a critical bug actually. I will release new version 1.6.1 as soon as you do the fix (and maybe upgrade the bundled  fmt as well)
