### ISSUE TITLE
support custom print

### ISSUE THREAD

**Issue by magicsupery** [gabime/spdlog#1572]
i build a unity plugin with spdlog
is there a function to hook the print function to my own function call which i can use it to send the string to the unity function pointer

**Comment by magicsupery** [comment]
`auto loggerC = spdlog::custom_logger_mt("xxx", myown_print_function);
	spdlog::set_default_logger(loggerC);`

sth like this

**Comment by tt4g** [comment]
You can create custom sink yourself.

Example:

```cpp
#include "spdlog/sinks/base_sink.h"
#include "spdlog/details/log_msg.h"
#include "spdlog/details/null_mutex.h"
#include "spdlog/pattern_formatter.h"

#include <memory>
#include <mutex>

template<typename Mutex>
class callback_sink : public spdlog::sinks::base_sink<Mutex>
{
    using BaseSink = spdlog::sinks::base_sink<Mutex>;

public:

    using CallbackFunctor = // Define your callback type.

    callback_sink(CallbackFunctor callback)
            : callback_(callback)
    {
    }

    virtual ~callback_sink() override {}

    callback_sink(const callback_sink&) = delete;
    callback_sink(callback_sink&&) = delete;
    callback_sink& operator=(const callback&) = delete;
    callback_sink& operator=(callback&&) = delete;

protected:

    virtual void sink_it_(const spdlog::details::log_msg &msg) override
    {
        // Format log message.
        spdlog::memory_buf_t formatted;
        BaseSink::formatter_->format(msg, formatted);

        // formatted.data() returns `char *`.
        std::string formatted_string(formatted.data());
        // Invoke callback.
        this->callback(std::move(formatterd_string));
    }

    virtual void flush_() override
    {
        // N/A
    }

private:

    CallbackFunctor callback_;

};

using callback_sink_mt = callback_sink<std::mutex>;
using callback_sink_st = callback_sink<spdlog::details::null_mutex>;

```

Reference for implementation:

* https://github.com/gabime/spdlog/blob/v1.6.1/include/spdlog/sinks/dist_sink.h

https://github.com/gabime/spdlog/blob/22a169bc319ac06948e7ee0be6b9b0ac81386604/include/spdlog/sinks/basic_file_sink-inl.h#L28-L34

**Comment by gabime** [comment]
> std::string formatted_string(formatted.data());

will break. data() does not return  c_str

**Comment by tt4g** [comment]
> will break. data() does not return c_str, so need to pass the size as well.

Oh!, My bad!
Thank you for review.

Edit my example: replace `std::string formatted_string(formatted.data())` with `std::string formatted_string(formatted.data(), formatted.size());`.

**Comment by gabime** [comment]
Maybe its better to avoid the allocation and use string_view instead.
