### ISSUE TITLE
avoid absolute prefix path in .pc file

### ISSUE THREAD

**Issue by dirk-thomas** [gabime/spdlog#1575]
The generated `.pc` file contains the absolute path of the install prefix in the `prefix` fields which makes that artifact not relocatable.

Instead of embedding the absolute install prefix the `.pc` can use the variable `${pcfiledir}` which points to the path of the `.pc` file at runtime. Depending on how many subdirectories the `.pc` is being installed under the install prefix the hard coded install prefix can be emulated by e.g. `${pcfiledir}/../..` (the number of `..` depends on the used `libdir`.

**Comment by dirk-thomas** [comment]
An example how the absolute path can be avoided: ros2/urdfdom#20.

**Comment by gabime** [comment]
@dirk-thomas I tried it. Seem to work, however I don't fully understand how does this make it "relocatable". One still need to install correctly spdlog.pc in the new environment.

**Comment by dirk-thomas** [comment]
Without a patch the generated `.pc` file contains an absolute path of the location it is being installed in (e.g. `/install-prefix`). If you take all files from the install prefix and move them somewhere else (e.g. create an archive of it, distribute it to other users, they unpack them in a different location) then the `.pc` file still references a directory under `/install_prefix` which doesn't exist.

With a change as in the referenced patch the actual location of the `.pc` is used to replace the absolute part of the prefix path. So when being moved to a different prefix the `.pc` file continue to provide the correct information.

**Comment by gabime** [comment]
> So when being moved to a different prefix the .pc file continue to provide the correct information.

Provided that the relative path is still valid in the new env..

Seems to me that .pc  is not meant to be copied around, but installed vie the package manger or CMake.

**Comment by dirk-thomas** [comment]
> Provided that the relative path is still valid in the new env..

Obviously the assumption is that the whole content of the install prefix is being moved around - not individual files.

> Seems to me that .pc is not meant to be copied around, but installed vie the package manger or CMake.

A package manager implies that there are binary packages available for a platform which might not be the case. And CMake implies that the user builds the package from source which is often not desired on less powerful devices.

**Comment by gabime** [comment]
Thanks for clarifying.
It still feels a bit weird though, to get output like this from pkg-config:

```console
gabi@gabi-ubuntu:~$ pkg-config spdlog --libs
-L/usr/local/lib/pkgconfig/../../lib -lspdlog -pthread
```

instead of the regular `-L/usr/local/lib`, so I think I will wait with this change until I'm certain about it.
