### ISSUE TITLE
min/max errors on Windows

### ISSUE THREAD

**Issue by adriendelsalle** [gabime/spdlog#1576]
Hi!
Thanks for this great lib, it's very usefull!
Don't hesistate if you need more detailed information.

Thanks

---

### Description
v1.6.0 and v1.6.1 generate compilation errors on Windows using `std::numeric_limits::max()` or just `std::max`. I get errors like `syntax error : '::'` or  `'(' : illegal token on right side of '::'`.
 It seems related with macros defined in a `windows` specific header.

v1.5.0 works fine.

I noticed this [PR](https://github.com/gabime/spdlog/pull/1453), maybe related to this issue.

### Environment

O/S : Windows 10 pro 1607
spdlog: >=1.6.0 installed using conda

**Comment by gabime** [comment]
Thanks for the great feedback!

This is a known issue (#1553) that can be easily overcome. Please see https://github.com/gabime/spdlog/wiki/0.-FAQ#winapi-minmax-macro-definitions on how to fix.

**Comment by adriendelsalle** [comment]
Sorry for the duplicate! I should have searched a bit more.
Thanks again!
