### ISSUE TITLE
Option to prevent setting of global cmake variables

### ISSUE THREAD

**Issue by sunnlok** [gabime/spdlog#1578]
Currently, when spdlog is added to a build, it is setting some global cmake variables if they are not present.
These being :
`
CMAKE_BUILD_TYPE
CMAKE_CXX_STANDARD
CMAKE_CXX_EXTENSIONS
`
In a multi configuration build setting these can have unforseen consequences, as they can affect compilation, which for me caused my application to behave erraticaly and crash when sdplog is linked against via cmake.
(Specifically when loading a dll that isnt included in the build process)

Furthermore it would be great to have a configuration option to set the debug postfix since some project setups already create folder structures based on build settings.
This makes using it easier for multi configuration projects that allow switching between debug, release or other arbitrary configurations.

**Comment by gabime** [comment]
Those are the most standard variables set used in thr most standard way. Seems like the multi configuration build should be fixed.

**Comment by sunnlok** [comment]
Force-setting it to Release/Debug seems to override settings used by the other configurations though.
Meaning if you have something like an in-between profile type it can mess up the build slightly making it impossible to use with dlls that are built against it in a specific configuration and to which the user might not have source access.
I was surprised this caused any issues at all, but i if i dont suppress the setting of CMAKE_BUILD_TYPE things will break.

That setting potentially affects output folders, compile settings, link library lookup folders and overriding anything that has been configured per target. 
My work around was to simply add a cmake variable that disables this.

In my opinion it would be nice if a library had at least the option to suppress the creation of global settings that might leak out into the overall project configuration and interact with things in unexpected ways.

**Comment by gabime** [comment]
Ok. Thanks for your input. Will revisit this if similar issues are reported.
