### ISSUE TITLE
spdlog::logger::dump_backtrace() does not ignore sink log levels

### ISSUE THREAD

**Issue by TrevorMuraro** [gabime/spdlog#1579]
My spdlog setup consists of one logger per application component, all set to trace level and with backtrace enabled, and two file sinks: one for trace level, one for error level.  I added dump_backtrace() to my error handling with the intent of putting error-relevant low-level messages into the error file.  However, the backtraces only appear in the trace log.

Is this intended behavior?

**Comment by tt4g** [comment]
Do you have a problem with error-level file sinks not outputting trace-level logs?
If so, the level set for the sink is the level that filters the logs. This setting is not intended to override the level of the log messages.

In other words, it works like this:

```cpp
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

#include <memory>
#include <vector>

void example()
{
    // trace_sink: outputs all log messages.
    auto trace_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("trace.log");
    trace_sink->set_level(spdlog::level::trace);

    // error_sink: outputs messages that log level greater than spdlog::level::err.
    auto error_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("error.log");
    error_sink->set_level(spdlog::level::err);

    std::vector<spdlog::sink_ptr> sinks;
    sinks.push_back(trace_sink );
    sinks.push_back(error_sink);

    auto files_logger = std::make_shared<spdlog::logger>("files_logger", sinks.begin(), sinks.end());
    // files_logger: pass all log messages to trace_sink and error_sink.
    files_logger->set_level(spdlog::level::trace);
    files_logger->enable_backtrace(10);

    // This log message that trace_sink outputs, but error_sink do not output.
    files_logger->trace("trace message");
    // trace_sink and error_sink outputs this log message.
    files_logger->error("trace message");

    // Outputs the log message again, still at the same log level.
    files_logger->dump_backtrace();
}
```

**Comment by TrevorMuraro** [comment]
I had read [here](https://github.com/gabime/spdlog/issues/1465#issuecomment-596211279) that dump_backtrace() ignores the log level of a logger, so e.g. an error-level logger will still output trace-level messages during a backtrace dump.  I was hoping that the same applied to sinks, so I could have trace messages in the trace log at all times, and trace messages in the error log only as part of error backtraces.

**Comment by tt4g** [comment]
Do you expect it to work like this?

You always output a log below the `spdlog::level::err` so that the error sink doesn't usually output a log.
However, only when the backtrace is performed, the error sink will ignore the log level and also output the log below `spdlog::level::err`.

If so, then unfortunately `spdlog::sinks::sink` will also filter by log level when backtracing.

When dumping backtrace, `spdlog::logger::sink_it_()` is called through `spdlog::logger::dump_backtrace_()`, but here, sink does filtering by log level:

https://github.com/gabime/spdlog/blob/22a169bc319ac06948e7ee0be6b9b0ac81386604/include/spdlog/logger-inl.h#L213-L218

https://github.com/gabime/spdlog/blob/22a169bc319ac06948e7ee0be6b9b0ac81386604/include/spdlog/logger-inl.h#L178-L190

**Comment by TrevorMuraro** [comment]
Essentially, yes - I also output error messages, but I had hoped I could put lower-level backtraces in the error log so I didn't have to sift through the trace log to find the relevant trace messages.

Thanks for letting me know it isn't the case.

**Comment by gabime** [comment]
@TrevorMuraro You can set the sink level temporarily to trace before calling  `dump_bactrace()` and back to error level right afterwards.

**Comment by TrevorMuraro** [comment]
Oh, I hadn't thought of that - thanks!
