### ISSUE TITLE
Is there any way to set log file to share mode?

### ISSUE THREAD

**Issue by tianmingyao** [gabime/spdlog#1583]
For example, my application uses spdlog and write to the log file. In the meantime, some other process wants to read the log file. Is there any option to do that?

**Comment by tianmingyao** [comment]
I looked up the source code and found that:
`    *fp = _fsopen((filename.c_str()), mode.c_str(), _SH_DENYNO);`
_SH_DENYNO means 'Permits read and write access.' 
I  write another program to read the log when spdlog works, and it succeeds.
But if i use a zip tool to zip the log file, it will fail and report file is currently occupied.
Is anything wrong here ?

**Comment by tt4g** [comment]
The zip tool may be trying to acquire the file lock.

**Comment by tianmingyao** [comment]
> The zip tool may be trying to acquire the file lock.

ok, thanks.
