### ISSUE TITLE
Is there a any log method feature?

### ISSUE THREAD

**Issue by navarrothiago** [gabime/spdlog#1588]
I would like to know if there is a feature `spdlog::func()` like the example below:

```
void my_method(){
  spdlog::func();
  // user output
}
```

Output:
```
[bgn] my_method
// user output
[end] my_method
```

The idea is to put it in every method/scope and the result is like a call stack.
We shall create a log level in order to disable/enable. 

Thank you in advance!

**Comment by gabime** [comment]
There is no such feature is spdlog.

**Comment by mguidry-glodon** [comment]
If you can use macros, these could be reasonable:

```
#define debug_func_begin() spdlog::debug("[bgn] " __func__)

#define debug_func_end() spdlog::debug("[end]" __func__)
```
 And just put it at the beginning and end of your functions.

**Comment by navarrothiago** [comment]
Thanks @gabime and @mguidry-glodon for your prompt response!
 @mguidry-glodon, I was thinking to create a class like:
```
#if defined(ENABLE_SPDLOG_FUNC)
      #define SPDLOG_FUNC()  \
      Logger __log(__func__)
#else
      #define SPDLOG_FUNC()
#endif

class Logger{
  public:
  Logger(const std::string& funcName)
    : mfuncName(funcName)
  {
    spdlog::debug("[bgn] {}" mFuncName.c_str());
  }
  virtual ~Logger(){
    spdlog::debug("[end] {}" mFuncName.c_str());
  }

  private:
    const string mFuncName;
} 
```

Usage:
```
void test(){
  SPDLOG_FUNC()
  // code
}
```

So, you do not need to log in the end of the function.

**Comment by navarrothiago** [comment]
Thank you for the answers. I have closed it.
