### ISSUE TITLE
Macro redefinition when using winsock2

### ISSUE THREAD

**Issue by samcragg** [gabime/spdlog#1589]
I just upgraded from 1.4.2 to 1.6.1 and, unfortunately, my project failed to compile on Windows, with lots of warnings about macro redefinitions from the `winsock2.h` header (seems to be [this issue](https://stackoverflow.com/q/1372480/312325)).

It looks like it's caused by the bundled `fmt` library, as that includes `windows.h`. I fixed it by changing [this line](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/fmt/bundled/format-inl.h#L26) to use the spdlog windows include file instead (i.e. from `<windows.h>` to `<spdlog/details/windows_include.h>`) and everything seems to be working again.

Happy to submit a PR, however, as it's a bundled library I'm not sure if when the library gets updated the change would be lost?

Thanks

**Comment by tt4g** [comment]
This issue is similar to #1553.

See also: https://github.com/gabime/spdlog/wiki/0.-FAQ#winapi-minmax-macro-definitions
