### ISSUE TITLE
format.cc compiling errors?

### ISSUE THREAD

**Issue by Max-Stern** [gabime/spdlog#159]
Hello.
I use spdlog in my .DLL project but I can't compile it because compiler (Visual Studio 2015) keeps saying that functions in format.cc already have bodies. I get many C2084, C2995 and C2264 errors but I really don't know what is wrong here =\
I include only spdlog.h as stated in manual, what am I doing wrong?

**Comment by gabime** [comment]
Maybe you are already using cppformat lib elsewhere in your project?

**Comment by Max-Stern** [comment]
Surely now.
I removed spdlog from my project (it's completely new, nothing is here except of main.cpp and one class which doesn't include anything) and then I added C++ Format header to test only this library.
Everything compiled and C++ Format worked without any error.

Then I remove C++ Format, added back spdlog but I've replaced format.cc and format.h in spdlog/details with original files from C++ Format archive.
Project compiled and spdlog works now...

**Comment by Max-Stern** [comment]
Okay, I found the problem, if remove FMT_HEADER_ONLY define then everything compiles.

**Comment by Max-Stern** [comment]
Oh... Sorry, it was my fault.
Just realized that I need to exclude format.cc from my project if FMT_HEADER_ONLY is defined.

No problems now, thank you for your awesome library!

**Comment by gabime** [comment]
Sure, enjoy the lib

**Comment by sukeshchand** [comment]
> Oh... Sorry, it was my fault.
> Just realized that I've included spdlog into my project so Visual Studio tries to build everything there but I don't need to do this obviously.
> 
What files we need to include? How we will use the library without installing it. Just by using source code?
