### ISSUE TITLE
Continuous logging in file 

### ISSUE THREAD

**Issue by Ahmunna** [gabime/spdlog#1590]
I have a server running that needs continuous logging in a file.
Currently, my log file stays empty until i stop the server.
I can't find a solution
Here is my code

```
            //set Logger for core server
            coreLogger = std::make_shared<spdlog::sinks::basic_file_sink_mt>("logs/aiservicesdk.log", true);
            coreLogger->set_level(spdlog::level::trace);
            //set logger for clients
            clientLogger = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
            clientLogger->set_level(spdlog::level::warn);
            //set Server logger
            logger = new spdlog::logger("aiservicesdk",{coreLogger,clientLogger});
            logger->set_level(spdlog::level::debug);
```

**Comment by tt4g** [comment]
Call `spdlog::logger::flush_on()` or `spdlog::flush_every()` to flush log message.
You can flush manually by calling `spdlog::logger::flush()`.

See also: https://github.com/gabime/spdlog/wiki/7.-Flush-policy

**Comment by Ahmunna** [comment]
@tt4g  Thank you so much, that's what i needed
