### ISSUE TITLE
core.h line# 272 is giving compilation error on line# 388 using Visual Studio 2019 16.6.2

### ISSUE THREAD

**Issue by yongchoo** [gabime/spdlog#1593]
When compiling using the above mentioned Visual Studio 2019 16.6.2 version, I am getting compilation error on core.h line 388. Tracing back, line #272 defines FMT_ENABLE_IF. Reading the few lines above, the comment lines indicated that " Extra parentheses are needed to workaround a bug in MSVC 2019 (see #1140 and #1186).". 
Need to look into this for us since we can no longer use this wonderful sw in the latest MSVS 2019 16.6.2 released on 6/14/2020. Ty!

**Comment by gabime** [comment]
core.h is part of fmt lib. Please open the issue there(https://github.com/fmtlib/fmt)
