### ISSUE TITLE
Backtrace support for all registered loggers

### ISSUE THREAD

**Issue by matthesoundman** [gabime/spdlog#1599]
Feature Request
- add ability to dump backtrace for all registered loggers

As of right now, it seems backtrace buffer is only for a given logger and there is no global buffer for a backtrace dump of all messages regardless of the logger.

**Comment by gabime** [comment]
You can call spdlog::apply_all() for this:

```c++
spdlog::apply_all([&](std::shared_ptr<spdlog::logger> l) { l->dump_backtrace(); });
```
