### ISSUE TITLE
Configure output names of log levels

### ISSUE THREAD

**Issue by tkolomiets** [gabime/spdlog#1600]
Hi.
Sometime it's need to configure output names of log levels (%l pattern param). E.g., we have production centralized logs monitoring system (as zabbix, e.g.), which is configured with some filter patterns for log levels names: error = ERR, debug = DEB and etc.
I,ve found in common.h definition of SPDLOG_LEVEL_NAMES and reached my purpose due to editing names and recompilation of project (spdlog used as header only lib im my case). But may be some native spdlog means exist for this purpose?
In future spdlog library will be enhance, and it is no comfortable to change SPDLOG_LEVEL_NAMES every time when new version will be use.

**Comment by tt4g** [comment]
You can create custom message formatter that inheriting `spdlog::custom_flag_formatter` and register it with `spdlog::pattern_formatter::add_flag()` member function.

Reference implementation appear `README.md` and the following test:

https://github.com/gabime/spdlog/blob/39150eb8c7673f37d740d957acfcbff8c48ef9a6/tests/test_pattern_formatter.cpp#L308-L353

Your custom formatter will get log level from `spdlog::details::log_msg::level` member variable.

https://github.com/gabime/spdlog/blob/22a169bc319ac06948e7ee0be6b9b0ac81386604/include/spdlog/details/log_msg.h#L20

Although `spdlog::details::log_msg::level` is the internal object, but project plan to announce it when there are API changes.

See: https://github.com/gabime/spdlog/issues/1408#issuecomment-581131101

**Comment by tkolomiets** [comment]
Ok, thanks )

**Comment by TrueWodzu** [comment]
@gabime since this question is three years old, is @tt4g answer still the correct way of changing logging level output names?
