### ISSUE TITLE
enhancement: Default log-level for a logger with multiple sinks

### ISSUE THREAD

**Issue by dsxmachina** [gabime/spdlog#1609]
Hi,
i dont know how to formulate this well, so sorry for bad english:
When i have a logger with multiple sinks for example: 
```    
      auto console_sink = make_shared<spdlog::sinks::stdout_sink_mt>();
      console_sink->set_level(spdlog::level::trace);

      auto file_sink    = make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/logfile", 1024 * 1024 * 1, 2);
      file_sink->set_level(spdlog::level::debug);

      spdlog::set_default_logger(
         make_shared<spdlog::logger>("multi_logger",
                                     spdlog::sinks_init_list({console_sink, file_sink})));
```
I also have to set

`spdlog::set_level(spdlog::level::trace);`
Manually, or otherwise the trace and debug messages are lost.

Wouldn't it be possible, to set the logger's default log level to the "lowest" level of it's attached sinks ? 

Thanks

**Comment by tt4g** [comment]
`spdlog::set_level()` changes the level of all the registered loggers.
You have to register the logger in the spdlog registry if you do not use the factory function such as `spdlog::stdout_color_mt()`and `spdlog::basic_logger_mt()`.

You can register logger to spdlog registry with `spdlog::register_logger()`.
NOTE: Before changing the log level with `spdlog::set_level()`, you must register the logger with `spdlog::register_logger()`.

Example:

```cpp
auto console_sink = make_shared<spdlog::sinks::stdout_sink_mt>();
console_sink->set_level(spdlog::level::trace);

auto file_sink    = make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/logfile", 1024 * 1024 * 1, 2);
file_sink->set_level(spdlog::level::debug);

auto logger = make_shared<spdlog::logger>("multi_logger", spdlog::sinks_init_list({console_sink, file_sink}))

spdlog::register_logger(logger); // Register logger.
spdlog::set_level(spdlog::level::trace); // Change the log level of each registered logger.
spdlog::set_default_logger(logger);
```

If you need register logger after `spdlog::set_level()`, you can use `spdlog::initialize_logger()`.
However, `spdlog::initialize_logger()` registers the logger and at the same time overwrites settings other than the log level.

**Comment by dsxmachina** [comment]
Thanks for your fast answer!
My tests show no difference if i register the logger or just set it to default. 
The crucial thing is, if i do not do:
```
spdlog::set_level(spdlog::level::debug)
```
The log level i gave each sink is not applied.
Although i did:
```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
```
Before including spdlog.h.
I read in some issue, that you have to set the log level via spdlog::set_level, after you defined the macro above.
But it feels weird, that i have to set this in three places to be working:
- the macro (i get why this is important)
- the sinks
- and then in the logger
As far as i understand, this is due to the fact, that "info" is the default logging level if not said otherwise.
So the "logger" object, has logging level "info", even if it's associated sinks have "debug" or "trace".
Maybe a simple warning or something would be sufficient,
but i was rather confused, that my logs did not contain any debug statements, altough i explicitly set it in the options of the sink.

**Comment by tt4g** [comment]
This is a design.

Rendering of the log messages requires a lot of memory.
To avoid this, the logger avoids rendering unwanted log messages at the log level.

Multiple sinks can be registered to a logger and sink is shared by multiple loggers.
The logger log level does not always match the sink log level.

For example, if the logger is registered with a sink that outputs only error messages to STDERR and a file sink that outputs all messages, STDERR sink can suppress all log messages below the error level by its own log level filtering.

**Comment by dsxmachina** [comment]
> For example, if the logger is registered with a sink that outputs only error messages to STDERR and a file sink that outputs all messages, STDERR sink can suppress all log messages below the error level by its own log level filtering.

Yes, in that case it makes total sense. What I was talking about was just the other way around:
For example, you have a logger with two sinks, one with logger level 'error' and one with logger level 'debug'. 
If the logger's log-level is at 'info' - which seems to be the default - the second sink will drop all debug messages (although you explicitly told it to log on debug level).
If I as a user override the loggers level, fair enough. But if I create a logger, it's default log-level get set for me, without me knowing about it or seeing it. 
I was just thinking about some kind of warning message, if this happens.
Or maybe a little hint in the example from the wiki would be sufficient also.
Because in the multi-sink example here (https://github.com/gabime/spdlog/wiki/1.-QuickStart), you have exactly this case I was talking about,
the first sinks log level is trace, while the loggers log level is debug. When you see this, you would not expect, that the sink will drop all trace messages.

**Comment by tt4g** [comment]
Is Section [Logger with multi sinks - each with different format and log level](https://github.com/gabime/spdlog/blob/22a169bc319ac06948e7ee0be6b9b0ac81386604/README.md#L200) of README.md not enough to explain it?

**Comment by dsxmachina** [comment]
Ok, let's take a look at this:
```
// create logger with 2 targets with different log levels and formats.
// the console will show only warnings or errors, while the file will log all.
void multi_sink_example()
{
    auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    console_sink->set_level(spdlog::level::warn);
    console_sink->set_pattern("[multi_sink_example] [%^%l%$] %v");

    auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("logs/multisink.txt", true);
    file_sink->set_level(spdlog::level::trace);

    spdlog::logger logger("multi_sink", {console_sink, file_sink});
    logger.set_level(spdlog::level::debug);
    logger.warn("this should appear in both console and file");
    logger.info("this message should not appear in the console, only in the file");
}
```
The 'info' and 'warn' messages indeed show the expected behaviour, but if i do:
```
logger.trace("This message should appear in file-log as a trace message!")
```
It is not logged in the file, although the file sink has log-level 'trace' . 
I do get now why that is (because the logger's log-level overrides the sink's log-level - please correct me if I am wrong here! ),
but in your comment it says
```
// ... while the file will log all.
```
And that is a little confusing at the beginning, since this "hierarchy" is not pointed out for noobs like me ;)
As far as I understand it is:
log_level_sink < log_level_logger < log_level_macro
(with macro i mean the SPDLOG_ACTIVE_LEVEL thing you have to define).
Am I correct with this ?

**Comment by tt4g** [comment]
> As far as I understand it is:
> log_level_sink < log_level_logger < log_level_macro
> (with macro i mean the SPDLOG_ACTIVE_LEVEL thing you have to define).
> Am I correct with this ?

Right.
