### ISSUE TITLE
include issue in spdlog/details/tcp_client-windows.h

### ISSUE THREAD

**Issue by yjhustc** [gabime/spdlog#1614]
When #include "spdlog/sinks/tcp_sink.h" and build on on windows VisualStidio ,VS report warning C4005: “AF_IPX” re defined and series errors causes by that. It seems that, in file "spdlog/details/tcp_client-windows.h", the order of #include <windows.h> and #include <winsock2.h> lead this problem.

**Comment by gabime** [comment]
Fixed (https://github.com/gabime/spdlog/commit/58875bdcd790dd2f5cb8d95ef1da7970de0a4530)

Thanks @yjhustc
