### ISSUE TITLE
Cannot create std::unique_ptr of async_logger

### ISSUE THREAD

**Issue by sourcedelica** [gabime/spdlog#1615]
If I try to create a `std::unique_ptr` of an `async_logger` then a `bad_weak_ptr` exception is thrown from `shared_from_this()` in `spdlog::async_logger::sink_it_()`.  For example:
```
auto spdLogger = 
    std::make_unique<spdlog::async_logger>(loggerName, sinks.begin(), sinks.end(), spdlog::thread_pool(),
                                           spdlog::async_overflow_policy::overrun_oldest);
```
It seems like this should be supported.  It is supported for the non-async loggers.

Thanks,

**Comment by gabime** [comment]
This is by design. The async logger must be shared ptr because it is shared with the logging thread.
