### ISSUE TITLE
Is there a dynamic library version of spdlog?

### ISSUE THREAD

**Issue by kleirama** [gabime/spdlog#1618]
Hei,

I am wondering if there is any dynamic version of library (like spdlog.so). If there is such thing how can I get that dynamic version of the library?

**Comment by tt4g** [comment]
`SPDLOG_VERSION` macro is defined in https://github.com/gabime/spdlog/blob/v1.7.0/include/spdlog/version.h

**Comment by kleirama** [comment]
But how can I build spdlog in order to get the dynamic library? Anytime I build it, I get a static version of the library

**Comment by tt4g** [comment]
Sorry, I misread it.

You can build shared library by specifying the CMake variable `SPDLOG_BUILD_SHARED=ON` on CMake configuration command.

https://github.com/gabime/spdlog/blob/616caa5d30172b65cc3a06800894c575d70cb8e6/CMakeLists.txt#L61-L62

Example:

```bash
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. -DSPDLOG_BUILD_SHARED=ON (other options here)
$ make -j
```

You can found another build option from https://github.com/gabime/spdlog/blob/616caa5d30172b65cc3a06800894c575d70cb8e6/CMakeLists.txt

**Comment by kleirama** [comment]
That worked :). Thanks for your help!
