### ISSUE TITLE
CMake variable name is wrong in release note v1.4.0.

### ISSUE THREAD

**Issue by tt4g** [gabime/spdlog#1619]
The following example command to build a shared library is available in https://github.com/gabime/spdlog/releases/tag/v1.4.0.

```
$ cd spdlog && mkdir build && cd build
# Build is static lib (pass -DCMAKE_BUILD_TYPE=shared for building as shared lib)
$ cmake .. && make -j
```

But `-DCMAKE_BUILD_TYPE=shared` is wrong and `-DSPDLOG_BUILD_SHARED=ON` is correct.

**Comment by gabime** [comment]
Fixed.
Thanks for reporting @tt4g
