### ISSUE TITLE
Setting custom logging colors?

### ISSUE THREAD

**Issue by slackjaw** [gabime/spdlog#1620]
I could not find an answer in the wiki - for color sinks, is it possible to programmatically change the default log color (which currently default to info=green, debug=cyan, etc) to something else, preferably to any fmt-legal color string?

**Comment by gabime** [comment]
See `set_color(..)` https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/ansicolor_sink.h#L38

**Comment by slackjaw** [comment]
OK - thanks, missed that.  So are any ANSI codes acceptable (assuming the terminal supports it)?

**Comment by gabime** [comment]
I believe so, yes.
