### ISSUE TITLE
Enable customization of backtrace start/end banners

### ISSUE THREAD

**Issue by dandee** [gabime/spdlog#1623]
I'd like to set my own backtrace start/end banners or silence them completely. So instead of seeing this for example:

```
[2020-07-16 22:31:16.718] [info] ****************** Backtrace Start ******************
[2020-07-16 22:31:16.719] [info] Some log
[2020-07-16 22:31:16.721] [info] ****************** Backtrace End ********************
[2020-07-16 22:31:16.723] [info] App is doing well
```

I'd like to see this:

```
[2020-07-16 22:31:16.719] [info] Some log
[2020-07-16 22:31:16.723] [info] App is doing well
```

or this:

```
[2020-07-16 22:31:16.718] [info] Hello world!
[2020-07-16 22:31:16.719] [info] Some log
[2020-07-16 22:31:16.721] [info] and after the intermission now this:
[2020-07-16 22:31:16.723] [info] App is doing well
```

**Comment by gabime** [comment]
There is no such option in spdlog

**Comment by Indra5196** [comment]
Is it okay to keep the banners in a text file? You can edit the file whenever you want to change the banners. Or are you looking for some other way?

**Comment by dandee** [comment]
Text file should be fine but isn't it a bit of overkill? Would a method or two to override the defaults be a better solution? Like:

`
spdlog::backtrace_banners("Start", "End");
`

**Comment by gabime** [comment]
Interesting to know that someone is actually using the backtrace feature. I am planning to remove it in v2.x due to lack of interest..

**Comment by Indra5196** [comment]
That should be fine but I just wanted to avoid recompilation everytime we change banners.

**Comment by dandee** [comment]
> Interesting to know that someone is actually using the backtrace feature. I am planning to remove it in v2.x due to lack of interest..

I think it'd be a step back in offered functionality. Not everything is a direct console application. You can have embedded system with sink configured to output through serial link which could mean that you'd lose traces emitted before client console connects to that link, etc.

**Comment by gabime** [comment]
@dandee I think the [ring buffer sink](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/ringbuffer_sink.h) would be a good alternative to achieve this.

**Comment by dandee** [comment]
> @dandee I think the [ring buffer sink](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/ringbuffer_sink.h) would be a good alternative to achieve this.

Fair enough! Thanks!
