### ISSUE TITLE
Pure virtual method called Error

### ISSUE THREAD

**Issue by mdlui** [gabime/spdlog#163]
I have one class that buffers actions. Those actions flush messages via spdlog. During the destructor of that class, I run through the last of the buffered actions, flushing the rest of the messages to a log. There is an error on the first info log that I make, during the destructor.

The log I create:
```c++
spdlog::set_async_mode(4096);
spdlog::create<spdlog::sinks::simple_file_sink_st>(name, name);
spdlog::get(name)->set_pattern("%v");
```
Messages are logged with:
```c++
spdlog::get(name)->info(sstr.str());
```

Flushing after every call still provides me with the error. The error I get during the functions that are called during the destructor, compiled with gcc-5.3.0:
`pure virtual method called`
`terminate called without an active exception`

My theories about what's happening haven't gotten me anywhere so far, but I'm assuming it's a resource releasing issue; the error definitely occurs during the info logging. I've seen this from the standard:
**Because of this difference in behavior, it is recommended that you never invoke an object's virtual function while it is being constructed or destroyed.**

But I'm not calling that object's virtual function, it's something from spdlog. Any help or advice is appreciated

**Edit:** I traced it to the details::line_logger destructor:
```c++
 _callback_logger->_log_msg(_log_msg); 
```
and then  in spdlog::logger::_log_msg
```c++
_formatter->format(msg)
```
The error happens when dereferencing _formatter->format

**Comment by gabime** [comment]
it would help if you provided the complete code. even a small main that reproduce it

**Comment by mdlui** [comment]
While I was making a reproducible, simpler example, I realized the issue occurs due to a singleton I have. Although all spdlog related pointers/data exists outside my singleton, I do a log when the static instance in the singleton is destroyed at the end of the program. 

Is it still worth pursuing reproducible code, or is it *expected* that spdlog has *undefined behavior* during destruction of static member variables after main?

Relevant link: http://stackoverflow.com/questions/2204608/does-c-call-destructors-for-global-and-class-static-variables

**Comment by gabime** [comment]
Yes it is expected. after main finishes, spdlogs own destructors are called(global registey singleton) so bad things happen if use try to call spdlog after main..

**Comment by mdlui** [comment]
Yea I see how that's obvious now. Only done some minor work with threads in C++ before. Thanks
