### ISSUE TITLE
Option to auto-indent lines for alignment with the log entry prefix

### ISSUE THREAD

**Issue by eyalroz** [gabime/spdlog#1630]
Let me illustrate this missing feature with an example.

What spdlog produces now (for some hypothetical program using it):
```
[2020-07-23 16:19:59.944] [trace] Got filename for buffer B
[2020-07-23 16:19:59.944] [trace] Read buffer A
[2020-07-23 16:19:59.947] [trace] Buffer A contents:
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
```
But it should be configurable so as to produce:
```
[2020-07-23 16:19:59.944] [trace] Got filename for buffer B
[2020-07-23 16:19:59.944] [trace] Read buffer A
[2020-07-23 16:19:59.947] [trace] Buffer A contents:
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                          ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation  
                          ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
                          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
                          occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
```
given the same longer string.

Of course there's some room for tweaking of this proposed feature:

* Indent to align with the start of other messages?
* Indent to align with the log-level indicator?
* Indent by a fixed amount?
* Detect terminal width?
* Allow capping terminal width artificially for wrapping?

etc.

**Comment by gabime** [comment]
I believe this can be already achieved with fmt. Its syntax supports left or right alignment. See https://fmt.dev/latest/syntax.html

**Comment by eyalroz** [comment]
@gabime : I meant, without the user having to format individual message. I want to say:
```
spdlog::trace("Buffer A contents:\n{}", buffer_A_string);
```
and have it appear like in the second case above.

**Comment by gabime** [comment]
How would it know when to place newlines? Seems out of the  scope of spdlog anyway.

**Comment by eyalroz** [comment]
@gabime : Several options:

1. Don't add newlines anywhere; just indent the lines you've been handed.
2. Check the output terminal's width and use that (it's [not terribly hard](https://stackoverflow.com/questions/1022957/getting-terminal-width-in-c)) - if it's at all a terminal.
3. The user gives you a maximum line width (this is also a fallback for option (2.)

Option(1.) is the easiest to implement and to justify (pun not intended) IMO.

**Comment by gabime** [comment]
> Don't add newlines anywhere; just indent the lines you've been handed.

which means scannjmg for newlines in each every logged character. would considerably slow thing down.

**Comment by eyalroz** [comment]
1 It's not slow relative to I/O to a file or a terminal. You're already copying the string into a buffer, so the thing is in the cache anyway. And vectorization speeds up the scan.
2. I suggested it as a preference. If it's preffed-off, you don't need to perform the scan.
3. It's slower to scan logs with your eye when the content is not uniformly indented. Plus you can't use `cut -cNN-` for an appropriate NN to get just the entries themselves.
