### ISSUE TITLE
service cannot accept

### ISSUE THREAD

**Issue by FHBGH** [gabime/spdlog#1633]
The main function is like this，Then other source files are added with header files:#include "spdlog/spdlog.h"，Then such a server program cannot accpet, and other client connet will return -1. The same is true for telnet testing. It can work after removing the spdlog related. What might be the problem?

#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"

int main(){
    
    auto logger = spdlog::basic_logger_mt("basic_logger", "logs/basic.txt");
    pdlog::set_default_logger(logger);
    spdlog::flush_on(spdlog::level::info);
    spdlog::flush_on(spdlog::level::err);

}

**Comment by gabime** [comment]
“spdlog::flush_on(spdlog::level::err);” should be removed. “spdlog::flush_on(spdlog::level::info);“ already includes all levels above “info” like “error”.

**Comment by FHBGH** [comment]
Then such a server program cannot accpet, and other client connet will return -1. The same is true for telnet testing. It can work after removing the spdlog related. What might be the problem?
