### ISSUE TITLE
message dedup

### ISSUE THREAD

**Issue by pm100** [gabime/spdlog#1635]
I am using spdlog in a project that is v noisy when tracing and sends lots of dup messages. I quickly hacked a dedup mechanism into spdlog so that it says 'last message repeated nn times' and it seems like this would be a useful feature. I have probably done it very poorly (code in the wrong place, blows up yr performance,...) and there are no control knob (enabled /disable, threshold for min dups,...) so any pull req would be bounced

[2020-07-24 17:59:19.379] [log] [trace] [Bus.cpp:98] device readb RK05 : 177404 = 10
[2020-07-24 17:59:19.397] [log] [trace] [Bus.cpp:98] device readb RK05 : 177404 = 10
[2020-07-24 17:59:19.397] [log] [debug] [TimerQueue.cpp:47] last message repeated 225 times

So maybe you could add it as a vanilla feature

**Comment by gabime** [comment]
Thanks. seems you can use the dup filter sink (https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/dup_filter_sink.h).

**Comment by pm100** [comment]
you highlight an issue with your excellent library - no docs :-(

**Comment by tt4g** [comment]
@pm100 Sink docs is here: https://github.com/gabime/spdlog/wiki/4.-Sinks
