### ISSUE TITLE
using add_subdirecory() to add spdlog results in cmake error

### ISSUE THREAD

**Issue by akulkarncadence** [gabime/spdlog#1636]
Hi!

I have a project A that depends on spdlog. Here is the structure:

|--- dir A
...|---src
......|---CMakeLists.txt
...|---include
...|---CMakeLists.txt
|---external/3rd_party/spdlog

I am trying to access spdlog in project A by adding a subdirectory. Here is how my A/CMakeLists.txt looks like:

```# Version of CMAKE (https://cmake.org/cmake/help/v3.9/manual/cmake.1.html)  
cmake_minimum_required(VERSION 3.9.3 FATAL_ERROR)
project(GLOBAL CXX)
add_subdirectory(${PATH}/external/3rd_party/spdlog   ${CMAKE_BINARY_DIR}/spdlog  EXCLUDE_FROM_ALL)
add_subdirectory(src)
```

Here is how my A/src/CMakeLists.txt looks like:

```
cmake_minimum_required(VERSION 3.9.3 FATAL_ERROR)
project(Alib CXX)

if(NOT TARGET spdlog)
   # Stand-alone build
   # find_package(spdlog_header_only REQUIRED)
endif()
add_librray(A A.cpp)
target_link_libraries(A PUBLIC spdlog_header_only)

install(TARGETS A
   EXPORT ATargets
   LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
   ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)
install(EXPORT ATargets
    NAMESPACE A::
    FILE ATargets.cmake
    DESTINATION ${INSTALL_CONFIGDIR})

install(FILES AConfig.cmake DESTINATION ${INSTALL_CONFIGDIR})
```

When I try to build this, I get the following error:
`CMake Error: install(EXPORT "ATargets" ...) includes target "A" which requires target "spdlog_header_only" that is not in the export set.`

Please can you suggest me how to fix it?

**Comment by gabime** [comment]
https://stackoverflow.com/questions/63175618/accessing-an-external-project-with-add-subdirectory-results-in-cmake-error-relat
