### ISSUE TITLE
custom sinks still supported or needed?

### ISSUE THREAD

**Issue by VikingExplorer** [gabime/spdlog#1637]
```
class DebugTraceSink : public spdlog::sinks::base_sink< std::mutex >
{
      protected:
              void sink_it_( const spdlog::details::log_msg& msg ) override;
	      void flush_() override;
};
```
just updated spdlog link with vcpkg.  Getting compiler errors.  I have code that creates a custom sink.  Is there a new way to do this?

**Comment by tt4g** [comment]
What your getting error message?

**Comment by tt4g** [comment]
Are you using spdlog v1.6.1 and compile errors related to the keyword "min" or "max"?
If so, this problem from fmt 6.2.1 (spdlog v1.6.1 bundled fmt v6.2.1) and this is known issue #1576. 

The workaround is to define `NOMINMAX` macro before `#include "spdlog/*"` and `#include "fmt/*"` header.

**Comment by VikingExplorer** [comment]
error C2259: 'spdlog::sinks::sink': cannot instantiate abstract class 
trying to figure out which version just came down from vcpkg

**Comment by tt4g** [comment]
Are there any unimplemented virtual functions reported by the compiler?

My guess is that the addition of `~base_sink() override = default;` in spdlog v1.6.0 has prevented the compiler generate an implicit destructor.

Try this change:

```diff
class DebugTraceSink : public spdlog::sinks::base_sink< std::mutex >
{
+      public:
+
+              DebugTraceSink() = default;
+
+              ~DebugTraceSink() override = default;
+
+              DebugTraceSink(const DebugTraceSink&) = delete;
+
+              DebugTraceSink(DebugTraceSink&&) = delete;
+
+              DebugTraceSink& operator=(const DebugTraceSink&) = delete;
+
+              DebugTraceSink& operator=(DebugTraceSink&&) = delete;
+
      protected:
              void sink_it_( const spdlog::details::log_msg& msg ) override;
	      void flush_() override;
};
```

**Comment by VikingExplorer** [comment]
class DebugTraceSink : public spdlog::sinks::base_sink< std::mutex >
	{
		public:
			DebugTraceSink() = default;
			~DebugTraceSink() override = default;
			DebugTraceSink(const DebugTraceSink&) = delete;
			DebugTraceSink(DebugTraceSink&&) = delete;
			DebugTraceSink & operator=(const DebugTraceSink&) = delete;
			DebugTraceSink & operator=(DebugTraceSink&&) = delete;
	
		protected:
         void sink_it_( const spdlog::details::log_msg& msg ) override;
	      void flush_() override;
	};

2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(1971,9): error C2259: 'spdlog::sinks::sink': cannot instantiate abstract class (compiling source file Log.cpp)
2>C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog\sinks\sink.h(12): message : see declaration of 'spdlog::sinks::sink' (compiling source file Log.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(1971,9): message : due to following members: (compiling source file Log.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(1971,9): message : 'void spdlog::sinks::sink::log(const spdlog::details::log_msg &)': is abstract (compiling source file Log.cpp)
2>C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog\sinks\sink.h(16): message : see declaration of 'spdlog::sinks::sink::log' (compiling source file Log.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(1971,9): message : 'void spdlog::sinks::sink::flush(void)': is abstract (compiling source file Log.cpp)
2>C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog\sinks\sink.h(17): message : see declaration of 'spdlog::sinks::sink::flush' (compiling source file Log.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(1971,9): message : 'void spdlog::sinks::sink::set_pattern(const std::string &)': is abstract (compiling source file Log.cpp)
2>C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog\sinks\sink.h(18): message : see declaration of 'spdlog::sinks::sink::set_pattern' (compiling source file Log.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(1971,9): message : 'void spdlog::sinks::sink::set_formatter(std::unique_ptr<spdlog::formatter,std::default_delete<spdlog::formatter>>)': is abstract (compiling source file Log.cpp)
2>C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog\sinks\sink.h(19): message : see declaration of 'spdlog::sinks::sink::set_formatter' (compiling source file Log.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1498): message : see reference to class template instantiation 'std::_Wrap<_Ty>' being compiled
2>        with
2>        [
2>            _Ty=spdlog::sinks::sink
2>        ] (compiling source file Log.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1587): message : see reference to class template instantiation 'std::_Ref_count_obj2<_Ty>' being compiled
2>        with
2>        [
2>            _Ty=spdlog::sinks::sink
2>        ] (compiling source file Log.cpp)
2>C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Log.cpp(48): message : see reference to function template instantiation 'std::shared_ptr<spdlog::sinks::sink> std::make_shared<spdlog::sinks::sink,const std::wstring&,int,int>(const std::wstring &,int &&,int &&)' being compiled

**Comment by tt4g** [comment]
It seems that `std::make_shared<spdlog::sinks::sink>` is wrong.
Can you provide `Log.cpp` snipped?

**Comment by VikingExplorer** [comment]
sinks.push_back( make_shared<spdlog::sinks::sink>( FileName.value(), 1024 * 1024, 5 ) );

**Comment by tt4g** [comment]
Can not call `std::make_shared<spdlog::sinks::sink>`.
The template parameter of `std::make_shared<T>` must be of an implemented type.

Looking at the constructor parameters, did you try to generate `spdlog::sinks::basic_file_sink_mt`?

**Comment by VikingExplorer** [comment]
rotating is what I wanted.  I've got
`            sinks.push_back( std::make_shared<spdlog::sinks::rotating_file_sink>( FileName.narrow().c_str(), 1024 * 1024, 5 ) );
`which matches the example at https://github.com/gabime/spdlog#asynchronous-logger-with-multi-sinks

But my errors are:
1>C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Log.cpp(49,35): error C2672: 'std::make_shared': no matching overloaded function found
1>C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Log.cpp(49,125): error C3206: 'std::make_shared': invalid template argument for '_Ty', missing template argument list on class template 'spdlog::sinks::rotating_file_sink'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1587): message : see declaration of 'std::make_shared'
1>C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Log.cpp(55,30): error C2672: 'std::make_shared': no matching overloaded function found
1>C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Log.cpp(55,120): error C3206: 'std::make_shared': invalid template argument for '_Ty', missing template argument list on class template 'spdlog::sinks::rotating_file_sink'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1587): message : see declaration of 'std::make_shared'

**Comment by VikingExplorer** [comment]
`            sinks.push_back( make_shared<spdlog::sinks::rotating_file_sink_st>( FileName.narrow().c_str(), 1024 * 1024, 5 ) );
`
Looking at pdlog/sinks/rotating_file_sink.h & avoiding having to specify a mutex, but I still get the following.  Don't see where the ambiguity is coming from:

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(204,12): error C2664: 'spdlog::sinks::rotating_file_sink<spdlog::details::null_mutex>::rotating_file_sink(const spdlog::sinks::rotating_file_sink<spdlog::details::null_mutex> &)': cannot convert argument 1 from '_Ty' to 'spdlog::filename_t'
1>        with
1>        [
1>            _Ty=const char *
1>        ] (compiling source file Log.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory(202,109): message : No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file Log.cpp)
1>C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog\sinks\rotating_file_sink.h(25,5): message : see declaration of 'spdlog::sinks::rotating_file_sink<spdlog::details::null_mutex>::rotating_file_sink' (compiling source file Log.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1489): message : see reference to function template instantiation 'void std::_Construct_in_place<_Ty,const char*,int,int>(_Ty &,const char *&&,int &&,int &&) noexcept(false)' being compiled
1>        with
1>        [
1>            _Ty=spdlog::sinks::rotating_file_sink_st
1>        ] (compiling source file Log.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1587): message : see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<const char*,int,int>(const char *&&,int &&,int &&)' being compiled
1>        with
1>        [
1>            _Ty=spdlog::sinks::rotating_file_sink_st
1>        ] (compiling source file Log.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\memory(1588): message : see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<const char*,int,int>(const char *&&,int &&,int &&)' being compiled
1>        with
1>        [
1>            _Ty=spdlog::sinks::rotating_file_sink_st
1>        ] (compiling source file Log.cpp)
1>C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Log.cpp(49): message : see reference to function template instantiation 'std::shared_ptr<spdlog::sinks::rotating_file_sink_st> std::make_shared<spdlog::sinks::rotating_file_sink_st,const _Elem*,int,int>(const _Elem *&&,int &&,int &&)' being compiled
1>        with
1>        [
1>            _Elem=char
1>        ]

**Comment by VikingExplorer** [comment]
```
            sinks.push_back( make_shared<spdlog::sinks::rotating_file_sink_mt>("mylog.txt", MaxFileSize, MaxFiles) );
            sinks.push_back( make_shared<spdlog::sinks::rotating_file_sink_mt>( FileName.narrow().c_str(), MaxFileSize, MaxFiles) );  

```

1st line ok, 2nd line is the error above.

c_str() returns a **const char***

Weird.  This didn't happen w/ a previous version of this library.

**Comment by tt4g** [comment]
What is the type of `Filename`? and what version of spdlog are you planning to use?

**Comment by VikingExplorer** [comment]
my pre-processor definitions:
FMT_EXPORT;SPDLOG_WCHAR_FILENAMES;PUGIXML_WCHAR_MODE;PUGIXML_NO_EXCEPTIONS;BOOST_LIB_DIAGNOSTIC;_BCGCBPRO_STATIC_;_BCGCBPRO_;_UNICODE;UNICODE;_AFXDLL;_LIB;WIN_D;_DEBUG;

**Comment by VikingExplorer** [comment]
![Capture](https://user-images.githubusercontent.com/15109208/89346382-f39f2680-d676-11ea-9e6c-960edd7b2c6a.PNG)

**Comment by tt4g** [comment]
Remove `SPDLOG_WCHAR_FILENAMES` if use `char *` for filename.

**Comment by VikingExplorer** [comment]
Now it builds.  Compared to the previous version, the only change is:
`#include <spdlog/sinks/rotating_file_sink.h>
`
I jumped to the conclusion that something in the API had changed.  Sorry, much ado about nothing.

Thank you for the great support.
