### ISSUE TITLE
[macOS] tcp_sink.h not compileable in macOS

### ISSUE THREAD

**Issue by dkruempe** [gabime/spdlog#1639]
I just tested the excellent library in linux and macOS. Actually nearly all is working. Except the tcp_sink.h in macOS. Currently I got every time the message that SOCK_CLOEXEC is an undefined identifier. 

As far as I see is the mentioned part in tcp_client.h.

```
int const flags = SOCK_CLOEXEC;
socket_ = ::socket(rp->ai_family, rp->ai_socktype | flags, rp->ai_protocol);
```

Actually the SOCK_CLOEXEC doesn't exists in sys/socket.h. So, it won't compile in macOS currently.

To make the part compilable again I have used the following workaround 

```
int flags = 0;
#ifdef SOCK_CLOEXEC
            flags = SOCK_CLOEXEC;
#endif
socket_ = ::socket(rp->ai_family, rp->ai_socktype | flags, rp->ai_protocol);
```

Actually I am not completely sure if it works 100%.

**Comment by gabime** [comment]
Thanks for reporting. If this works for you a PR would be welcome.
