### ISSUE TITLE
Conversion and old-style cast warnings

### ISSUE THREAD

**Issue by dtoma** [gabime/spdlog#164]
Hello,

I'm using this library in a project that compiles using the following warning flags:

`-Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Weffc++ -Wconversion`

I'm getting a lot of warnings from `-Wconversion` and `-Wold-style-cast`, for example:

```
./deps/spdlog/sinks/../details/./format.h:946:57: warning: implicit conversion changes signedness: 'int' to 'unsigned int' [-Wsign-conversion]
    unsigned t = (64 - FMT_BUILTIN_CLZLL(n | 1)) * 1233 >> 12;
             ~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
```

```
./deps/spdlog/sinks/../details/format.h:2927:34: warning: implicit conversion changes signedness: 'const int' to 'std::size_t' (aka 'unsigned long') [-Wsign-conversion]
    std::size_t precision = spec.precision_;
                ~~~~~~~~~   ~~~~~^~~~~~~~~~
```

```
./deps/spdlog/sinks/../details/./mpmc_bounded_q.h:88:28: warning: use of old-style cast [-Wold-style-cast]
            intptr_t dif = (intptr_t)seq - (intptr_t)pos;
                           ^         ~~~
```

Is this something you would consider fixing or accepting a pull request for?

Cheers,
Damien

**Comment by gabime** [comment]
try taking the latest version.i think it was fixed in the past.

anyway, format.h is an external lib called cppformat.
please open issue there.

**Comment by dtoma** [comment]
Ok, I'll head over to the cppformat repo.

Cheers,
Damien
