### ISSUE TITLE
Sink set level is thread safe?

### ISSUE THREAD

**Issue by XNerv** [gabime/spdlog#1647]
Sink set level is thread safe?

auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path, truncate);
sink.sink->**set_level**(spdlog::level::level_enum::critical);

**Comment by tt4g** [comment]
`spdlog::sinks::sink::set_level(spdlog::level::level_enum` is thread safe (atomic access), if `SPDLOG_NO_ATOMIC_LEVELS` is not defined.

https://github.com/gabime/spdlog/blob/616caa5d30172b65cc3a06800894c575d70cb8e6/include/spdlog/common.h#L119-L123

https://github.com/gabime/spdlog/blob/616caa5d30172b65cc3a06800894c575d70cb8e6/include/spdlog/sinks/sink.h#L27
