### ISSUE TITLE
Arithmetic overflow and other warning

### ISSUE THREAD

**Issue by RadiantMin3** [gabime/spdlog#1655]
I just cloned spdlog and added it to my solution and I'm getting 22 warnings and don't know how to fix them. I don't think they are really effecting it but it's just annoying to have it there.

i'm using the latest version of spdlog and visual studio 2019.

`Severity	Code	Description	Project	File	Line	Suppression State
Warning	C26812	The enum type 'spdlog::level::level_enum' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\common-inl.h	16	
Warning	C26495	Variable 'fmt::v6::internal::buffer<char>::ptr_' is uninitialized. Always initialize a member variable (type.6).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\core.h	653	
Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format-inl.h	404	
Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format-inl.h	414	
Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format-inl.h	418	
Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format-inl.h	466	
Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format-inl.h	466	
Warning	C26812	The enum type 'fmt::v6::internal::digits::result' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format-inl.h	879	
Warning	C26812	The enum type 'fmt::v6::internal::char8_type' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	516	
Warning	C26812	The enum type 'fmt::v6::align::type' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1050	
Warning	C26812	The enum type 'fmt::v6::sign::type' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1051	
Warning	C26451	Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1090	
Warning	C26451	Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1095	
Warning	C26495	Variable 'fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<__int64,fmt::v6::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1492	
Warning	C26495	Variable 'fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<char,fmt::v6::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1492	
Warning	C26495	Variable 'fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<int,fmt::v6::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1492	
Warning	C26495	Variable 'fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned __int64,fmt::v6::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1492	
Warning	C26495	Variable 'fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned int,fmt::v6::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1492	
Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1658	
Warning	C6385	Reading invalid data from 'signs':  the readable size is '4' bytes, but 'fspecs.sign' bytes may be read.	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1743	
Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\fmt\bundled\format.h	1823	
Warning	C26812	The enum type 'spdlog::details::padding_info::pad_side' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	RadiantEngine	F:\VS\RadiantEngineGithub\RadiantEngine\RadiantEngine\vendor\spdlog\include\spdlog\pattern_formatter.h	33	
`

**Comment by valkyrienyanko** [comment]
I am getting the exact same warnings and doing the above does not disable them. I even tried this 
```cpp
#pragma warning (push, 0)
#include <spdlog/spdlog.h>
#pragma warning (pop)
```
