### ISSUE TITLE
Static Library with make

### ISSUE THREAD

**Issue by mla-pt** [gabime/spdlog#1664]
Hello,
I have the usual problem that including spdlog headers slows down the compilation time (a lot!).
I am using MAKE to compile my code which resides in a folder different from the one where I have compiled spdlog.
It seems to me that I do not manage to use the static library. Indeed, when I include the library in the compilation rules, I observed no speed improvement.
This is the rule I use to compile:
`c++ -c -Wall -O3 -fpic -o obj/ZenithResolution.o src/ZenithResolution.cc -pthread -std=c++11 -m64 -I/astro/group/root_versions/SL7_v6.20.04/include -fPIC -Iinclude -I /astro/users/mperrint/KM3NeT/Analysis/paramNMH2/OscProb -I /astro/users/mperrint/Tools/spdlog-git/include/ -l/astro/users/mperrint/Tools/spdlog-git/build/libspdlog.a`

How should I modify it?
Thanks in advance for your help

**Comment by gabime** [comment]
You need to define SPDLOG_COMPILED_LIB bas well

**Comment by mla-pt** [comment]
indeed having (order matters):
#define SPDLOG_COMPILED_LIB
#include "spdlog/fwd.h"
#include "spdlog/spdlog.h"

solved the pb! Thanks a lot
