### ISSUE TITLE
Is it possible to use spdlog without std::mutex

### ISSUE THREAD

**Issue by syntroniks** [gabime/spdlog#1665]
We would like to use spdlog on an embedded system without any C++ support for threading & concurrency.

In this case, `std::mutex` and other threading constructs are generally unavailable.

Will it be possible to configure spdlog without these features?

I have noticed one of the first places a `mutex` appears is in the registry. Can we operate without a registry?

Another issue is the lack of `std::thread` for a thread id in `os-inl.h`

**Comment by gabime** [comment]
I don't think there is a way without modifying spdlogs code.
