### ISSUE TITLE
msvc_sink pulls in windows.h even with SPDLOG_COMPILED_LIB defined

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [gabime/spdlog#1667]
Is this intentional? I know `msvc_sink` is a template, but it could defer to a function declaration with an implementation in a cpp file with `SPDLOG_COMPILED_LIB` defined.

**Comment by gabime** [comment]
It could, but since it is header only sink, it is intentional.

**Comment by gabime** [comment]
I wonder though if including debugapi.h instead is better.

**Comment by terraKote** [comment]
Can we omit using windows.h anyhow?

**Comment by gabime** [comment]
Fixed using a trick found in SO (https://stackoverflow.com/a/30741042)
