### ISSUE TITLE
Async logger exception when used from dll

### ISSUE THREAD

**Issue by NIKEA-SOFT** [gabime/spdlog#1669]
Hello, thanks for the spdlog.
I have runtime problems.
I am working on a framework that is based on a module system (dll / so).
It works like this: .exe loads modules and then initializes them.
By the word "module" I mean the the dynamic library (dll / so)

I needed a module to work with logs and decided to use spdlog. but I'm in trouble. If I use log module for asynchronously output logs from other modules, the pointer to "filename" sometimes throws a "Read Access Violation" exception.
The strange thing is that it does not always happen, it's randomly. That is, if I display only one message in asynchronous mode, then everything works. And if I try to display 2 or more messages at the same time, then in one of the calls to "log" an exception occurs at the "filename" pointer in spdlog::source_loc

In addition, if I call the log output from the same module where the log system is implemented, then everything works fine.

I read the wiki and that before asking this question, but it didn't help me fix the problem.
What am I doing wrong? 

My repos, see in brach Develop:
[Framework Modules](https://github.com/NIKEA-SOFT/HelenaFramework/tree/develop/Helena/Module)
All you need is in the files: "IPluginLog.hpp", "PluginLog.hpp", "PluginLog.cpp", "PluginTestA.cpp"
A log system is implemented in the "ModuleLog", in the Interface folder there is an abstract class that was created so that the "PluginLog" class could be used in another "ModuleTestA" module.
In "IPluginLog" along the path "ModuleLog/Interface" a function is implemented that creates "spdlog::source_loc", given that the exception occurs in the "filename" pointer, I assume that you need to look there.

The screenshot below demonstrates the exception
![image](https://user-images.githubusercontent.com/57288440/92440821-c255d100-f1b5-11ea-9568-d80e8230fb46.png)
![image](https://user-images.githubusercontent.com/57288440/92438382-60936800-f1b1-11ea-97ff-692c253282e1.png)

**Comment by tt4g** [comment]
The `filename` is a characters literal resulting from the preprocessing of the `__FILE__` macro.
And the characters literal is almost always placed in a static segment (code segment) in memory.

Refer: https://stackoverflow.com/questions/14468697/where-is-memory-allocated-with-a-const-char-pointer/14468729

The `filename` is declared with `const char *` to avoid unnecessary memory allocation.
If the library is unloaded, the reference memory is an invalid address.

Your project seems to be dynamically loading libraries, but the library with the memory that `filename` was referring to is not being unloaded at the time of the log output?

**Comment by NIKEA-SOFT** [comment]
> The `filename` is a characters literal resulting from the preprocessing of the `__FILE__` macro.
> And the characters literal is almost always placed in a static segment (code segment) in memory.
> 
> Refer: https://stackoverflow.com/questions/14468697/where-is-memory-allocated-with-a-const-char-pointer/14468729
> 
> The `filename` is declared with `const char *` to avoid unnecessary memory allocation.
> If the library is unloaded, the reference memory is an invalid address.
> 
> Your project seems to be dynamically loading libraries, but the library with the memory that `filename` was referring to is not being unloaded at the time of the log output?

Thanks for the quick response
Indeed, you are right. Modules are unloaded after a return occurs inside the Initialize method. Since `GetPlugin<>` was called earlier, it returned `nullptr` and notified the framework of an error, which leads to unloading of all modules.

And this is indeed the reason why exception happen. I added `while (true) {}` and the program began to work correctly, which confirmed your assumption. Is there a way to solve this problem? My framework architecture does not provide for waiting for the completion of async logic in modules. I mean the module itself has to shutdown its threads internally, but how do I do that using spdlog?

As I understand it, calls to `spdlog::drop_all()` and `spdlog::shutdown()` do not solve this problem. I think that it would be more correct to interrupt logging and terminate the work of threads if the `PluginLog` destructor was called, however, this does not help.
What is the best way to proceed in this case?
[Link on destructor](https://github.com/NIKEA-SOFT/HelenaFramework/blob/develop/Helena/Module/ModuleLog/PluginLog.cpp#L34)

**Comment by tt4g** [comment]
Add a callback to be called just before the plugin unloads.
The relevant callback will perform a cleanup operation that should be performed before unloading the plugin.

Call `spdlog::shutdown()` with this callback.
And don't output a log during the plugin unloading process (spdlog doesn't work).

**Comment by NIKEA-SOFT** [comment]
> Add a callback to be called just before the plugin unloads.
> The relevant callback will perform a cleanup operation that should be performed before unloading the plugin.
> 
> Call `spdlog::shutdown()` with this callback.
> And don't output a log during the plugin unloading process (spdlog doesn't work).

I think I discovered what the problem was, I just forgot to call .reset on shared_ptr inside PluginLog, so my streams dedicated to spdlog kept working. Thank you for your help, you really helped me in finding a solution to the problem.
You will probably be laughing, but I just forgot to call .reset on shared_ptr objects :)
