### ISSUE TITLE
Enabling Debug output for multiple files?

### ISSUE THREAD

**Issue by seanngpack** [gabime/spdlog#1670]
Hi, I can't seem to figure out how to get debug logging working in different files.

I CAN make it work if I use the runtime command

```
spdlog::set_level(spdlog::level::debug);
spdlog::debug("some text");
```

But I can to call set_level() in every single file, seems like there is a better way to do this.

So then I tried using the processor command

```
main.cpp

#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
#include "spdlog/spdlog.h"

spdlog::debug("some text");
```

But there is no debug output at all. What is the best approach for enable debug output for multiple files?

Thanks!

**Comment by tt4g** [comment]
`spdlog::debug()` to be use default logger.
You can change default logger.
Also, should you create logger that use multiple file sinks.

See Wiki:

* https://github.com/gabime/spdlog/wiki/Default-logger
* https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#creating-multiple-file-loggers-with-the-same-output-file

**Comment by seanngpack** [comment]
Hi @tt4g 

Thanks for the response! In retrospect, I think my title and body text was confusing--I want to use the spdlogger IN multiple files, such as A.h, B.h, and just log to console rather than logging TO multiple files. So to clarify my questions, should I manually call the runtime ```spdlog::set_level(spdlog::level::debug);``` in each of my files to achieve debugging logging? If I don't, it defaults to info level logging

Thanks!

**Comment by tt4g** [comment]
`spdlog::set_level(spdlog::level::debug);` will change log level of all loggers in spdlog global registry.
Since the default logger is already in spdlog global registry, it is sufficient to call `spdlog::set_level(spdlog::level::debug);` just once (e.g. `main()`).

If you use spdlog in more than one application, you will have to call `spdlog::set_level(spdlog::level::debug);` in each application.

**Comment by seanngpack** [comment]
@tt4g thank you for the info! calling ```spdlog::set_level(spdlog::level::debug);``` in the main seems like it does not have an effect on the global registry because I must call it again in any other file I want debug level logging. I have two builds of spdlog, one from brew and one using the header-only library and they show the same behavior. Perhaps this may be a bug on macOS?

**Comment by tt4g** [comment]
> I am compiling my projects as libraries so that must be doing something weird to spdlog. Perhaps it's because my library has an instance of spdlog, 

Right. spdlog global registry is declared `static`.

https://github.com/gabime/spdlog/blob/4a9ccf7e38e257feecce0c579a782741254eaeef/include/spdlog/details/registry-inl.h#L277-L281

Variables declared `static` are global in memory space. Note that they are not global in all applications.

Most compilers place the `static` variable in a static location in memory.
Variables placed in a static location in a shared library refer to the same memory across all applications that use it.

The same rules apply if your library was a shared library (the spdlog global registry is placed in a static location in your shared library's memory space).

When you link spdlog to a header-only library or a static library directly to an application, spdlog global registry will be created in each linked application.

**Comment by seanngpack** [comment]
thanks again for additional insight!

I solved my issue with a modified version of this resource: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs
