### ISSUE TITLE
time problem about Log printing 

### ISSUE THREAD

**Issue by Biaoshi** [gabime/spdlog#1673]
When I use
 `
auto logger = spdlog::daily_logger_mt("my_logger", "logs/myServer.log");

#define INFOLOG(...) SPDLOG_LOGGER_INFO(spdlog::default_logger_raw(), __VA_ARGS__);SPDLOG_LOGGER_INFO(spdlog::get("my_logger"), __VA_ARGS__)` 

to print log in console and wirte them in log file.
I found that the recorded logs are out of order about the recorded time.
![image](https://user-images.githubusercontent.com/31428174/93458775-57be3700-f913-11ea-9604-4488b3e3d417.png)

How can I make the time at a right order? Thanks a lot.

**Comment by tt4g** [comment]
Do you share loggers with multiple threads?

**Comment by Biaoshi** [comment]
> Do you share loggers with multiple threads?

Nope, the logs in the picture are log the heartbeat. all of them are in the same thread.

**Comment by tt4g** [comment]
It's odd how the time shifts in a single thread.
Do you have an `SPDLOG_CLOCK_COARSE` macro defined?

https://github.com/gabime/spdlog/blob/4a9ccf7e38e257feecce0c579a782741254eaeef/include/spdlog/tweakme.h#L13-L20

Even if you don't define `SPDLOG_CLOCK_COARSE` macro, the time may go back in time if the ntp client is running in step mode.

**Comment by tt4g** [comment]
I noticed.
The seconds part of the log in your image is in three digits.
Seconds should never be a three-digit string.

Can you provide a format for the logger?
