### ISSUE TITLE
stdout sink produces extra carriage returns on Windows

### ISSUE THREAD

**Issue by chris-t-w** [gabime/spdlog#1675]
Given the following example:

```
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"
#include "spdlog/sinks/stdout_color_sinks.h"

int main()
{
    std::shared_ptr<spdlog::logger> logger1 = spdlog::stdout_logger_st("one");
    logger1->set_pattern("%v");
    logger1->info("hello");

    std::shared_ptr<spdlog::logger> logger2 = spdlog::stdout_color_st("two");
    logger2->set_pattern("%v");
    logger2->info("world");

    return 0;
}
```

If we run this program on Windows and redirect the output to a file (`example.exe > output.txt`) and have a look at this output in a hex editor, we see the following:

```
68 65 6C 6C 6F 0D 0D 0A 77 6F 72 6C 64 0D 0A
h  e  l  l  o  \r \r \n w  o  r  l  d  \r \n
```

i.e. `"hello\r\r\nworld\r\n"` - notice the additional carriage return after "hello".

I believe the first example can be explained because:

1. `stdout_logger_st` uses `fwrite` to write to the `stdout` handle
2. The formatter automatically appends `\r\n` by default
3. `stdout` is opened in text mode according to: https://docs.microsoft.com/en-us/cpp/c-runtime-library/text-and-binary-mode-file-i-o ("_The stdin, stdout, and stderr streams always open in text mode by default_")
4. Streams opened in text mode will automatically replace `\n` with `\r\n` according to: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fwrite ("_If stream is opened in text mode, each line feed is replaced with a carriage return-line feed pair_")

This is a problem because some programs interpret the `\r\r\n` as two lines, resulting in all of the logs appearing with extra blank lines between them.

The only thing I can't explain is why the problem doesn't seem to happen with the color sink, which you can see from the output above produces the correct `"world\r\n"`.

**Comment by gabime** [comment]
Thanks for the detailed analysis. Good to know.

> The only thing I can't explain is why the problem doesn't seem to happen with the color sink..

That't because it the windows color sink uses ```::WriteConsoleA``` instead of fwrite ([see here](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/wincolor_sink-inl.h#L138)).

I guess the way to fix this is to use ```WriteFile``` instead under Windows in this sink..

**Comment by chris-t-w** [comment]
Thanks. As a work-around, I've just been using the `stdout_color_st` as there doesn't seem to be any down-side to doing so. For anybody else with this issue, I believe you can use the `stdout_color_st` sink and just remove the color range flags (`%^` and `%$`) from the pattern if you really don't want them.

**Comment by dgehri** [comment]
With this fix, creating a `stdout_sink` in an GUI (non-console) application now throws an exception, because the call `::_get_osfhandle(::_fileno(file_));` now fails, whereas the previous version would allow the sink to be created.
