### ISSUE TITLE
Stopwatch should use `steady_clock`

### ISSUE THREAD

**Issue by SuperWig** [gabime/spdlog#1676]
In Microsoft's implementation and libc++ `high_resolution_clock` is just a type alias for `steady_clock`. In libstdc++ however, it is a type alias for `system_clock`.

If you want a stop watch you want `steady_clock`.

See Howard explain it here
http://www.youtube.com/watch?v=P32hvk8b13M&t=48m44s

**Comment by gabime** [comment]
Fixed. Thanks for reporting!
