### ISSUE TITLE
Windows: clang-cl -fno-exceptions clashes with bundled fmtlib

### ISSUE THREAD

**Issue by photex** [gabime/spdlog#1677]
Howdy!

When building with MSVC things appear to be just fine. However, there seems to be an issue when using clang-cl (llvm 10, installed via scoop) whereby spdlog builds using -fno-exceptions but fmtlib detects exceptions as being available and so enables try, throw, and catch in it's configuration.

I'm currently not sure how to get around this.

**Comment by tt4g** [comment]
fmt provide `FMT_EXCEPTIONS` and `FMT_THROW` option.

https://github.com/fmtlib/fmt/blob/cd4af11efc9c622896a3e4cb599fa28668ca3d05/include/fmt/format.h#L96-L128
