### ISSUE TITLE
Filter Option

### ISSUE THREAD

**Issue by paulhazen** [gabime/spdlog#1678]
I apologize if this request belies my understanding of SPDLog, but I'm searching for the right logging system to use in a game engine. There are a lot of disparate areas of the game engine in which logs are being generated, and we want to be able to 'filter' the messages not just based on the loglevel, but based on a custom defined tag like "physics" or "graphics" that way the graphics dev won't be flooded with physics log messages and the physics dev won't be flooded with graphics log messages.

What is SPDLog's response to this scenario? Is it best to use one logger for physics, one logger for graphics, etc? Or is there a filter-esque feature that I'm not seeing?

I apologize if this is the wrong forum to be asking such a question / requesting such a feature. If it is, please let me know where the appropriate place is.

EDIT: It seems upon further inspection the ability to add custom flags may be the intended solution for this use case. Can someone confirm that for me?

**Comment by tt4g** [comment]
I think you can add filtering yourself by creating a custom logger or custom sink.

Since there is already an `spdlog::sinks::dup_filter_sink` that filters the same message, you can use this as a reference implementation: https://github.com/gabime/spdlog/blob/v1.8.0/include/spdlog/sinks/dup_filter_sink.h

**Comment by gabime** [comment]
> What is SPDLog's response to this scenario? Is it best to use one logger for physics, one logger for graphics, etc?

Yes. This is the recommended way - multiple loggers, all share same sink objects. One can use ```logger->clone("new_name")``` for this.

For example :

```c++
auto main_logger = spdlog::basic_logger_mt("main", "logs/basic-log.txt");
auto physics_logger = main_logger->clone("physics");
auto graphics_logger = main_logger->clone("graphics");
```

**Comment by jiudianren** [comment]
will spdlog add filter option like boost log ? tks.
