### ISSUE TITLE
[Question][Bug] How come load_env_levels() overrides levels to default of info when SPDLOG_LEVEL env var doesn't exist?

### ISSUE THREAD

**Issue by Tridacnid** [gabime/spdlog#1680]
It looks like calling load_env_levels() when SPDLOG_LEVEL doesn't exist overwrites every registered logger's level to a default of "info". Additionally, when SPDLOG_LEVEL does exist but only specifies a couple logger's levels, the others have their levels overwritten to the default of info.

pseduo-code example:
```
// export SPDLOG_LEVEL=logger2=off

// create "logger1" and set level to trace
auto logger1{spdlog::stdout_color_mt("logger1");
logger1->set_level(trace);
spdlog::register_logger(logger1);

// create "logger2" and set level to debug
auto logger2{spdlog::stderr_color_mt("logger2");
logger2->set_level(debug);
spdlog::register_logger(logger2);

spdlog:;cfg::load_env_levels();

// logger2 is set to off level as expected, but logger1 is now set to info even though it wasn't specified in SPDLOG_LEVEL
// if SPDLOG_LEVEL doesn't exist in the environment, both logger1 and logger2 would be set to info
```

Is this by design? It's certainly annoying that a missing env var will reset the logger levels I have specified in my source code. I wouldn't expect a logger's level to change if it wasn't present in the env var.

As a side note, it looks like the argv processing suffers from this same behavior.

**Comment by gabime** [comment]
It is not by design. This is indeed an annoying bug

**Comment by Tridacnid** [comment]
I have a fix I'll try to submit as a patch this weekend for the empty env var + unit tests for that case. 

Is the `SPDLOG_LEVEL=logger2=off` affecting `logger1`'s level also a bug or is that intentional? I took a look and changing that might be more involved.

**Comment by gabime** [comment]
> I have a fix I'll try to submit as a patch this weekend f
Don't bother. My fix is almost ready.

>Is the SPDLOG_LEVEL=logger2=off affecting logger1's level also a bug or is that intentional? 

Also a bug.

**Comment by gabime** [comment]
@Tridacnid Fixed. Please verify works for you as well

**Comment by Tridacnid** [comment]
Ran some quick tests and everything looks like it's behaving nicely now, thanks!
