### ISSUE TITLE
gRPC logging? 

### ISSUE THREAD

**Issue by LiorBanai** [gabime/spdlog#1681]
Hi,
I was wondering if this library has gRPC support to stream logs? The reason I'm asking it that I have gRPC server and viewer at https://github.com/Analogy-LogViewer/Real-Time-Log-Server and wanted to know if I can use this library with my proto file.

**Comment by tt4g** [comment]
Not supported yet but you can create custom sink yourself.

**Comment by LiorBanai** [comment]
Thanks I'll check this out.
I have c# and c++ applications and it will be very useful to see both logs in real time for debugging and troubleshooting.

Maybe it will also help others if I see it working well..
