### ISSUE TITLE
Is spdlog possibly slower than simple ofstream with simple locking?

### ISSUE THREAD

**Issue by emmenlau** [gabime/spdlog#1682]
I've been using spdlog for a long time and I'm quite happy with it. But recently I needed to implement a simple file based logger based on ofstream and a mutex lock with std::mutex. For the sake of curiosity I benchmarked both, and it turns out that the simple logger is always faster than spdlog - usually between 5% and 20% faster.

This question is admittedly a bit naiive, but I hope someone can shed some light: under which use-case can spdlog show its potential?

My assumptions are:
 - My simple comparison was not using very many threads, only a few threads logged most messages
 - My simple comparison was not using any extra formatting, only plain ready-made std::strings where logged

Did anyone ever compare the speed of spdlog to such a simple logger, and in which cases is spdlog on par or faster?

**Comment by gabime** [comment]
spdlog does quite a bit under the hood except for writing to file(log levels, fmt formatting, sinks, pattern formatting, flush management, datetime formatting, error handling etc.) so no wonder that just writing to a file is faster.
