### ISSUE TITLE
Compile time checking not working

### ISSUE THREAD

**Issue by chris-t-w** [gabime/spdlog#1683]
I saw that in `spdlog v1.7` one of the features included was compile-time checking of format strings, however I can't get this to work.

**What I expect**:

As I understand it, any invalid format strings should result in a compile error using `spdlog v1.7` without having to do anything extra.

**What I see**:

Invalid format strings successfully compile and result in a runtime error.

Manually adding the `FMT_STRING` macro around a format string _does_ produce a compile error.

**Reproduction case**:

```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.10)
project(spdlog_example CXX)
find_package(spdlog CONFIG REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example PRIVATE spdlog::spdlog)
```

```
// example.cpp
#include "spdlog/spdlog.h"
#include "fmt/format.h"

//#define ENABLE_CHECK

void correct() {
    spdlog::info("{}", 123);
    spdlog::info(FMT_STRING("{}"), 123);
}

void incorrect() {
    spdlog::info("{} {}", 123);
#if defined(ENABLE_CHECK)
    spdlog::info(FMT_STRING("{} {}"), 123);
#endif
}

int main(int, char *[]) {
    spdlog::info("spdlog version {}.{}.{}", SPDLOG_VER_MAJOR, SPDLOG_VER_MINOR, SPDLOG_VER_PATCH);
    correct(); incorrect();
}
```

As-is, this compiles but fails to run just as would be expected with a previous version of `spdlog`:

```
$ cmake --build build --config Release && build\Release\example.exe
...
[2020-09-25 12:32:36.319] [info] spdlog version 1.7.0
[2020-09-25 12:32:36.323] [info] 123
[2020-09-25 12:32:36.324] [info] 123
[*** LOG ERROR #0001 ***] [2020-09-25 12:32:36] [] {argument not found}
```

With `ENABLE_CHECK` defined, it fails to compile due to the compile-time check forced by the `FMT_STRING` macro:

```
$ cmake --build build --config Release && build\Release\example.exe
...
format.h(2874,42): error C3615: constexpr function 'fmt::v7::basic_format_parse_context<char,fmt::v7::detail::error_handler>::on_error' cannot result  in a constant expression
```

----

Note: I'm using `vcpkg` to install `spdlog`, which seems to automatically define `SPDLOG_FMT_EXTERNAL` and link against the `fmt` library provided by `vcpkg` (which at the moment seems to be vesion 7.0.2). I don't know if that perhaps has something to do with it?

**Comment by gabime** [comment]
This only works if your code compiled with c++14 or later flag.

**Comment by gabime** [comment]
> Manually adding the FMT_STRING macro around a format string does produce a compile error

Thats the way to use it. FMT_STRING is a must

**Comment by chris-t-w** [comment]
So to enable compile-time checking of format strings, must we place the `FMT_STRING` macro on every single logging call, like this?

```
spdlog::info(FMT_STRING("foo {}"),1);
spdlog::info(FMT_STRING("bar {}"), s);
spdlog::debug(FMT_STRING("baz {:x}"), a);
spdlog::error(FMT_STRING("err: {}"), msg);
// etc.
```

If so, is there any way I could write some kind of wrapper that does it automatically, something like this?

```
template <typename Fmt, typename... Args>
void log_error(Fmt&& fmt, Args&&... args)
{
    spdlog::log(spdlog::level::err, FMT_STRING(std::forward<Fmt>(fmt)), std::forward<Args>(args)...);
}
```

(though this doesn't seem to compile: `error: ... function cannot access 'fmt'`)

**Comment by gabime** [comment]
AFAIK it is not possible the way fmt currently implemented.

**Comment by chris-t-w** [comment]
I got it to somewhat work using a preprocessor macro, but it's a bit hacky:

```
#define info(lvl, fmt, ...) info(lvl, FMT_STRING(fmt), __VA_ARGS__)
```

That way:

```
spdlog::info("hello {}", "world");
// expands to:
spdlog::info(FMT_STRING("hello {}"), "world");
```

But unfortunately it will expand _every_ instance of `info`, not just `spdlog::info` and I can't think of a way around that.
