### ISSUE TITLE
Nothing logs because of intentional late segfault 

### ISSUE THREAD

**Issue by sinaaghli** [gabime/spdlog#1684]
Hi, 
I'm new to spdlog and have been playing with examples to create a logger for my application, However whenever a segfault happens later in the program I see nothing has been logged. Here is an example program I created to demonstrate the problem.

I have two sinks where one is logging to a file and the other is logging to the terminal. 

```
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/rotating_file_sink.h>
#include <memory>
#include <signal.h>

using namespace std;

int main(){

    spdlog::sink_ptr console_sink_(make_shared<spdlog::sinks::stdout_color_sink_mt>());
    spdlog::sink_ptr file_sink_(make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/slog.txt", 1048576*100, 2));
    shared_ptr<spdlog::async_logger> logger_;
    
    spdlog::init_thread_pool(8192, 1);
    std::vector<spdlog::sink_ptr> sinks{console_sink_, file_sink_};
    logger_ = make_shared<spdlog::async_logger>("mocapserver", sinks.begin(), sinks.end(), spdlog::thread_pool(), spdlog::async_overflow_policy::overrun_oldest);
    spdlog::register_logger(logger_);
    
    console_sink_->set_level(spdlog::level::debug);
    file_sink_->set_level(spdlog::level::debug);
    logger_->set_level(spdlog::level::debug);
    logger_->debug("Text-debug.");
    logger_->info("Text-info.");
    logger_->error("Text-error.");
    // raise(SIGSEGV);
    return 0;
}
```
when the last line of code is commented out the output is 
```
[2020-09-28 03:03:11.345] [mocapserver] [debug] Text-debug.
[2020-09-28 03:03:11.345] [mocapserver] [info] Text-info.
[2020-09-28 03:03:11.345] [mocapserver] [error] Text-error.
```
and the log file is created correctly.
however, if I raise the segfault in the last line I get 
`Segmentation fault: 11`
So no log messages are printed and the log file is empty even though the segmentation fault was raised after log instants.
The whole purpose of logger for me is to catch what was happening before a segfault, am I missing something in my example code? or maybe I'm expecting a feature which is not there?

**Comment by tt4g** [comment]
The feature to output the log after a segmentation fault occurs is not supported yet.
See #1607

If you call `spdlog::flush_on(spdlog::level::trace)`, you can expect to see most of the log output until a segmentation fault occurs.

**Comment by gabime** [comment]
Try to you use the synchronous (default) logger instead of the async - then you can expect to see almost all log statements that were flushed.

**Comment by sinaaghli** [comment]
I ended up creating a [signal handler](https://stackoverflow.com/questions/2350489/how-to-catch-segmentation-fault-in-linux) and call spdlog::flush_on inside the handler which seems to work. Thank you guys.

**Comment by gabime** [comment]
> I ended up creating a signal handler and call spdlog::flush_on inside the handler which seems to work

Be warned it might not work reliably. see #1607
