### ISSUE TITLE
Does spdlog supports stacktrace in critical level

### ISSUE THREAD

**Issue by ashione** [gabime/spdlog#1686]
I noticed that glog FATAL can show more detail stacktraces, even including source code line when check failed. I wonder whether spdlog will be able to display them as well, which is a significant feature to us.

**Comment by gabime** [comment]
There is no stack trace support in spdlog

**Comment by muse117** [comment]
> There is no stack trace support in spdlog

What doesn't support Stacktraces, which is useful for analyzing Coredump？
