### ISSUE TITLE
Apple Clang: -Wshadow causes warning in bundled fmt

### ISSUE THREAD

**Issue by tadmn** [gabime/spdlog#1687]
`spdlog` `v1.8.1`

In file included from /usr/local/include/spdlog/spdlog.h:12:
In file included from /usr/local/include/spdlog/common.h:36:
In file included from /usr/local/include/spdlog/fmt/fmt.h:23:
/usr/local/include/spdlog/fmt/bundled/format.h:1601:11: error: declaration shadows a type alias in 'int_writer<OutputIt, Char, UInt>' [-Werror,-Wshadow]
    using iterator = remove_reference_t<decltype(reserve(out, 0))>;
          ^
/usr/local/include/spdlog/fmt/bundled/format.h:1490:9: note: previous declaration is here
  using iterator =

Compiled with `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++`
```
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by tadmn** [comment]
Note if I checkout `v1.7.0`, build + install, the warning goes away.

**Comment by gabime** [comment]
This is an fmt 7.x issue. I suggest open an issue in the fmt repo
