### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by petke** [gabime/spdlog#169]
I have a application (using boost log) with thousands of log messages with this syntax:

LOG(error) << "error level msg";
LOG(debug) << "debug level msg";

Id like to switch to using spdlog without changing all the client code. Unfortunately spdlog doesnt have such a interface. 

So I added the following common interface function to logger_impl.h

inline spdlog::details::line_logger spdlog::logger::common(level::level_enum lvl)
{
	return _log_if_enabled(lvl);
}

Now I can use the syntax

spdlog::get("console")->common(spdlog::level::debug) << "test debug";

spdlog::get("console")->common(spdlog::level::error) << "test error";

and with a bit of MACRO hacking I can get it so the client syntax doesnt change at all.

I think other users might find such a common interface logging function useful also. 

Thanks /Petke

**Comment by gabime** [comment]
I am not sure how this helps. 
Can you provide an example of a macro that cannot be implemented with the current API and must use  this new function?

**Comment by petke** [comment]
Good point. 

The name of the logger functions are the same as the name of the level enums (except for  logger::error() vs level::err). So for example with a LOG(info) macro call, I can expand the "info" text to either the enum name level::info or the function name logger::info(). Both work.

You can close this issue. No need to change anything.

Thanks /Petke
