### ISSUE TITLE
Header only resulting in large binary size

### ISSUE THREAD

**Issue by heavyweight87** [gabime/spdlog#1694]
Hi,

This library is great but im using it on an embedded system where space is scarse. 

When using the static lib my binary size is around 12MB
However when using the header only version it gets to about 35MB. 
I would expect some increase to file size but nearly tribble the size does not sound right

Any idea how I can reduce this? I'm using it on my yocto system which currently has issues with the static lib so header only would make it alot easier for me

Thanks

**Comment by gabime** [comment]
Maybe try to strip it?
