### ISSUE TITLE
Remote syslog support

### ISSUE THREAD

**Issue by pananton** [gabime/spdlog#1699]
Hello, can you please tell me whether there is a way to configure remote syslog server address for the library?

**Comment by pananton** [comment]
I have a remote syslog server running. Earlier Boost.Log was used for writing logs to it. It allows to directly set remote address of syslog server. Is there a way to do the same thing in spdlog? I've looked thourgh earlier issues and did not find the answer (sorry if missed it).

**Comment by gabime** [comment]
No such option exists (PRs are welcome).
