### ISSUE TITLE
Not Compatible with Visual Studio CppUnitTest?

### ISSUE THREAD

**Issue by seven-qi** [gabime/spdlog#170]
Hi, I'm using VS2013 to run its self-contained CppUnitTest. If I enable the logger in function, all test cases will fail, complaining C00000005, any thought? Thanks! The logger works perfect on normal use.

**Comment by gabime** [comment]
please post the code

**Comment by seven-qi** [comment]
Please check it at https://github.com/seven-qi/ThreadedMessengerCpp Thanks!

**Comment by gabime** [comment]
I tried few tests and they works fine in my visual studio env (2013)
Probably something specific to your tests
