### ISSUE TITLE
Support %s, %# for non-SPDLOG_ loggers

### ISSUE THREAD

**Issue by jackyjia** [gabime/spdlog#1700]
See some flags here (https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags) are only supported in SPDLOG macros, would be great to also support them in other types of loggers.

**Comment by gabime** [comment]
It is supported. Use

```c++
logger->log(spdlog::source_loc{__FILE__, __LINE__, __FUNCTION__}, level, “my message {}, 123);
```
