### ISSUE TITLE
Support log rotation for SPDLOG macros

### ISSUE THREAD

**Issue by jackyjia** [gabime/spdlog#1701]
as the title

**Comment by gabime** [comment]
It is supported using SPDLOG_LOGGER_... macros

**Comment by jackyjia** [comment]
is there any example of enabling rotation using SPDLOG_LOGGER_... macros? Didn't find it in the wiki: https://github.com/gabime/spdlog/wiki. Thanks. @gabime

**Comment by jackyjia** [comment]
> is there any example of enabling rotation using SPDLOG_LOGGER_... macros? Didn't find it in the wiki: https://github.com/gabime/spdlog/wiki. Thanks. @gabime

found it in the example. Thanks.

**Comment by jackyjia** [comment]
> > is there any example of enabling rotation using SPDLOG_LOGGER_... macros? Didn't find it in the wiki: https://github.com/gabime/spdlog/wiki. Thanks. @gabime
> 
> found it in the example. Thanks.

with SPDLOG_LOGGER_... macros can i still use flags here (https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags) that are only supported in SPDLOG macros?

**Comment by jackyjia** [comment]
> > > is there any example of enabling rotation using SPDLOG_LOGGER_... macros? Didn't find it in the wiki: https://github.com/gabime/spdlog/wiki. Thanks. @gabime
> > 
> > 
> > found it in the example. Thanks.
> 
> with SPDLOG_LOGGER_... macros can i still use flags here (https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags) that are only supported in SPDLOG macros?

verified that it's supported
