### ISSUE TITLE
influence libfmt when include spdlog/spdlog.h

### ISSUE THREAD

**Issue by Kidsunbo** [gabime/spdlog#1702]
## Environment:
- System: docker (ubuntu:latest).
- g++: gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
- cmake: 3.16.3

## Dependency:
- spdlog: **master branch**  https://github.com/gabime/spdlog.git
- libfmt: **master branch**  https://github.com/fmtlib/fmt.git

## Directory Structure:
```
app
   |-fmt/
   |-spdlog/
   |-main.cpp
   |-wrapper.cpp
```

## Code:
**CMakeList.txt**
```
cmake_minimum_required(VERSION 3.16)
project(app)

set(CMAKE_CXX_STANDARD 20)

add_subdirectory(fmt)

add_executable(app main.cpp wrapper.cpp)
target_include_directories(app PUBLIC spdlog/include)
target_link_libraries(app PUBLIC fmt)
```

**main.cpp**
The `#include <spdlog/spdlog.h>` is the key to influence here.
```
#include <spdlog/spdlog.h>

void hey();

int main() {

    hey();

    return 0;
}
```

**wrapper.cpp**
```
#include <fmt/format.h>
#include <iostream>


void hey(){
    std::cout<<fmt::format("value={}", 1000)<<std::endl;
}

```

## Result
With `Debug` mode, the output is `value=1000` which is normal. But with `Release` mode, the output is `value1000`, which the charactor before `{}` is missing.
If I comment out `#include <spdlog/spdlog.h>` in the `main.cpp`, the result is right.
 I am curious why this happens.

**Comment by gabime** [comment]
spdlog master branch is old. Please use v1.x branch

**Comment by Kidsunbo** [comment]
> spdlog master branch is old. Please use v1.x branch
> Also you need to set SPDLOG_FMT_EXTERNAL=ON if you are using fmt from the system instead of the bundled

My mistake. I didn't set SPDLOG_FMT_EXTERNAL. The result is right when SPDLOG_FMT_EXTERNAL is set. 
But why doesn't this happen on MacOS with Clang?
