### ISSUE TITLE
Test failure on OSX (async periodic flush)

### ISSUE THREAD

**Issue by bluescarni** [gabime/spdlog#1705]
Hello,

I am trying to modify the conda package for spdlog to use a shared library build and external fmt (whereas the current version of the package uses the default spdlog build configuration). When doing so, I am seeing a test failure when the conda CI pipeline tries to build the package on OSX:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=225598&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1116

The failing line is here:

https://github.com/gabime/spdlog/blob/v1.x/tests/test_async.cpp#L91

I have not been able to check so far if ``test_sink->flush_counter()`` returns 0 or a number > 1. But after taking a look at the current bug list for spdlog (which features a variety of reports stemming from buggy stdlib implementations of chrono functions), my feeling is that the issue might be connected to some clock problem.

Would you like me to investigate more?

**Comment by gabime** [comment]
Thanks for reporting. seems that increasing the sleep time in line 90 might fix this test. Please confirm if it helps

**Comment by bluescarni** [comment]
@gabime I bumped up the sleep time from 1100ms to 1700ms and now the test passes, at least on the one build I tried:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=244643&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b

It seems thought it might still potentially fail erratically in unfortunate circumstances?

In any case, thanks a lot for the help! Shall I close this report? Or would you like a PR?

**Comment by gabime** [comment]
PR would be great. Thanks !

**Comment by bluescarni** [comment]
PR up at #1749.

**Comment by bluescarni** [comment]
Cheers for merging, I'll close this report.
