### ISSUE TITLE
Suggestion: Provide an include_headers() method in Python when installed with pip

### ISSUE THREAD

**Issue by ashyantony7** [gabime/spdlog#1707]
For projects involving python wrappers to C++ libraries, it is useful to have the include header locations. 

Currently, when spdlog is installed with pip, the headers are located in the root (spdlog.h, null_mutex.h etc..)
It would be really useful to have these headers organized in the way they are intended and a method is available in Python to get the include location.

For instance, Pybind11 provides a method (pybind11.get_include()). This is especially useful for having a setup.py for compilation.

**Comment by gabime** [comment]
Do you refer to https://github.com/bodgergely/spdlog-python ?  This probably should be openend there.

**Comment by ashyantony7** [comment]
Thank you. I will do it there
