### ISSUE TITLE
Fail to build version 1.8.1 with msvc14

### ISSUE THREAD

**Issue by deleoDev91** [gabime/spdlog#1713]
Hi,
Im trying to use the last version of spdlog in my project but this fails to build because in spdlog\fmt\bundled\format.h(1751) uses std copy without using (the pain in the ass) checked iterator utilities from stdext. This is only necessary when building with msvc (Im using msvc14). In error notification say that this can be solved disabling certain warnings but i dont to do this unless its totally necessary

**Comment by gabime** [comment]
fmt warnings are out of the scope of spdlog repo, it belongs to fmt repo

**Comment by deleoDev91** [comment]
Thanks for your support, @gabime . 
For now I solved the problem downloading an older version of fmt(6.0.0) and disabling the spdlog version through macro SPDLOG_FMT_EXTERNAL. I left an issue in fmt git repporting the problem. Leaving link for people who has same problem:
https://github.com/fmtlib/fmt/issues/1947
