### ISSUE TITLE
Multiple loggers, using same console sink, using different message patterns

### ISSUE THREAD

**Issue by B1ackDrag0n** [gabime/spdlog#1715]
Good morning

I have a micro service, with it's own logger, and it uses a rules engine, also with it's own logger.  Both of these loggers write to console and file, but they use different message patterns, to allow for easily identifying where the log entry came from.

My formats are set up as follows:
- Service : %Y/%m/%d %T.%e | Service | %l | %^%v%$
- Engine : %Y/%m/%d %T.%e | Engine | %l | %^%v%$

I found, however, that, as soon as the rules engine starts logging, both loggers use the rules engine's message pattern so all log entries, from that point onward, use the "%Y/%m/%d %T.%e | Engine | %l | %^%v%$" pattern.

How can I resolve this problem?

I have not confirmed, yet, but should I expect a similar problem with the file logging as well, if they are using the same type of file sink - both for the logging filename and message format?

**Comment by gabime** [comment]
Please provide some sample code to reproduce,or have better understanding.

**Comment by B1ackDrag0n** [comment]
I created a wrapper class that sets up my logging sinks:

      void base_logger::add_console_sink(bool colour, level::level_enum log_from_level, string message_pattern)
      {
        if (colour)
        {
          auto colour_sink = make_shared<spdlog::sinks::stdout_color_sink_mt>(spdlog::color_mode::always);

          colour_sink->set_level((spdlog::level::level_enum)log_from_level);
          colour_sink->set_pattern(message_pattern);

          spdlog::default_logger_raw()->sinks().push_back(colour_sink);
        }
        else
        {
          auto normal_sink = make_shared<spdlog::sinks::stdout_sink_mt>();

          normal_sink->set_level((spdlog::level::level_enum)log_from_level);
          normal_sink->set_pattern(message_pattern);

          spdlog::default_logger_raw()->sinks().push_back(normal_sink);
        }
      }
      ...
      void base_logger::log_trace(string message)
      {
        spdlog::trace(message);
      }

When I set up my classes' individual loggers, I do the following:

        if (console_logging_active)
        {
          logger.add_console_sink(console_logging_colour, logger.log_level_from_string(console_logging_level), console_logging_pattern);
        }

When I do the logging:

        logger.log_trace("Rules directory = " + rules_directory);

I hope this helps.

**Comment by B1ackDrag0n** [comment]
I have confirmed that the file logging is doing the same thing.  Both end up logging to the same file as well, even though they started off with the own respective log file names.

**Comment by gabime** [comment]
Your code add sinks to the default logger, so after add_console_sink() is called the default logger will contain multiple sinks.

**Comment by B1ackDrag0n** [comment]
OK.  How can I change that?

**Comment by gabime** [comment]
Don't use the default logger. You can create  2 different logger instances.
