### ISSUE TITLE
std::unique_lock shadow bug

### ISSUE THREAD

**Issue by chunheguo** [gabime/spdlog#1718]
https://github.com/gabime/spdlog/blob/408a2229d69010155e6704866ebd8dad1c5dd794/include/spdlog/details/mpmc_blocking_q.h#L35

https://github.com/gabime/spdlog/blob/408a2229d69010155e6704866ebd8dad1c5dd794/include/spdlog/details/mpmc_blocking_q.h#L46

https://github.com/gabime/spdlog/blob/408a2229d69010155e6704866ebd8dad1c5dd794/include/spdlog/details/periodic_worker-inl.h#L24

Hi,
you have a shadow bug in the link above. 
It is caused by the default constructor of std::unique_lock. You are not locking your code.

See this video on why it is a bug: https://youtu.be/lkgszkPnV8g?t=2068.

Solution to the bug: Just name it.

Best regards,
Jack

**Comment by gabime** [comment]
There are all actually named “lock” . Whats is the problem?

**Comment by chunheguo** [comment]
ahh ok ... then i was missreading it xD
