### ISSUE TITLE
Is there any way to clear log file during program running

### ISSUE THREAD

**Issue by warren-lei** [gabime/spdlog#1722]
I want to clear the log file when the program is running. And rewrite log message to cover the log file.
Is there any way to do this?

**Comment by gabime** [comment]
You can destruct the logger, and then create a new one. Use a basic file sink with the truncate flag.

**Comment by warren-lei** [comment]
> You can destruct the logger, and then create a new one. Use a basic file sink with the truncate flag.

Thanks.
