### ISSUE TITLE
Is there any way to get fmt (format) of a details::log_msg.payload (formatted string)?

### ISSUE THREAD

**Issue by MykolaLebid** [gabime/spdlog#1723]
I want to create a "clever" sink based on fmt of log_msg aka extension of dup_filter_sink. Could you give me a hint about this possibility or give me suggestion how to get it without adding additional member variable to details::log_msg and init it in 

spdlog/include/spdlog/logger.h:
    template<typename FormatString, typename... Args>
    void log_(source_loc loc, level::level_enum lvl, const FormatString &fmt, const Args &...args) .

Thanks a lot for your wonderful library!

**Comment by gabime** [comment]
The message already  payload contains the message after the fmt formatting

**Comment by MykolaLebid** [comment]
Sorry for misunderstanding. I mean, I need to have access to a pre-format (FormatString &fmt) after formatting and before the pattern format formatting.

**Comment by gabime** [comment]
It makes sense, however I dont want to add another field to this important struct, for such a rare case..
