### ISSUE TITLE
Adding header to CSV file when running spdlog::daily_logger_mt

### ISSUE THREAD

**Issue by eddietseng1129** [gabime/spdlog#1724]
Hi,

I'm trying to record my device's data every day by running "spdlog::daily_logger_mt("daily_logger", "logs/PLC_daily.csv", 0, 0)"
The file should be like this:
![Screenshot from 2020-10-30 14-02-20](https://user-images.githubusercontent.com/35317612/97756693-8bff4880-1ab8-11eb-9e16-7a754379e4de.png)

However, when the program created another file, the header wasn't added to the new CSV file. The rest of the information is created successfully.

Here's my code for adding header:
![Screenshot from 2020-10-30 14-11-48](https://user-images.githubusercontent.com/35317612/97757419-e6e56f80-1ab9-11eb-9409-1ee6042c7f80.png)

**Comment by gabime** [comment]
I suggest to implement a custom sink for this, based on the daily sink code.

**Comment by tamanrasset** [comment]
In case you've stumbled upon the same issue, it is now possible to use [Log file open/close event handlers](https://github.com/gabime/spdlog#log-file-openclose-event-handlers) for this.
Create an `after_open` callback, which writes header to the file: 
```
spdlog::file_event_handlers handlers;
handlers.after_open = [](spdlog::filename_t, std::FILE* fstream) {
    fputs("Date,Time,TimeZone,Thread,etc.\n", fstream);
};
```
And then pass it as the last argument to the factory:
```
auto csv_logger = spdlog::daily_logger_mt("daily_logger", "logs/PLC_daily.csv", 0, 0,  false, 0, handlers);
```
This way the header is written to the beginning of every file created by the logger.

Another advantage over writing header as as regular log entry is that now you can use spdlog built-in fields such as date, time, thread and such. In the example above pattern could be set to something like `"%Y-%m-%d,%H:%M:%S.%e,%z,%t,%v"` so you'd only need to log two comma-separated temperatures

**Comment by yalov** [comment]
Are handlers available in the `spdlog::sinks::base_sink`, for been able to implement the csv header only in the inherited custom_sink, but not the logger (bc logger could log also to other sinks) ?

UPD. found, the member of `spdlog::details::file_helper`, which is the member of a sink
