### ISSUE TITLE
does spdlog rotating_file_sink_mt flush upon destruction?

### ISSUE THREAD

**Issue by tesla1060** [gabime/spdlog#1727]
Hi, 
I have to sink one being `daily_file_sink_mt` another being `rotating_file_sink_mt` in my program. I found when I press `ctrl+c`, the logger to  `rotating_file_sink_mt` doesnt flush, while `daily_file_sink_mt` does. I wonder if spdlog flush all logs upon destruction?

**Comment by tt4g** [comment]
If the application finishes in the regular procedure, the flush will be called in the destructor.
However, `Ctrl + C` will terminate the application by a signal, so a destructor call is not guaranteed.

**Comment by tesla1060** [comment]
@gabime but for a normal `fstream`, an `ctrl +c` will flush the buffer, why `spdlog` seems not be flushing upon `ctrl + c`?
