### ISSUE TITLE
Compile error when using fmt::to_wstring

### ISSUE THREAD

**Issue by m0rtalis** [gabime/spdlog#1728]
I am getting the compile error `error: use of deleted function 'fmt::v7::basic_memory_buffer<char, 250>::basic_memory_buffer(const fmt::v7::basic_memory_buffer<char, 250>&)`
when compiling my custom sink

	template<typename Mutex>
	class xwf_logger : public spdlog::sinks::base_sink<Mutex>
	{
		protected:
			void sink_it_(const spdlog::details::log_msg& msg) override
			{
				spdlog::memory_buf_t formatted;
				spdlog::sinks::base_sink<Mutex>::formatter_->format(msg, formatted);
				std::wstring log_message = fmt::to_wstring(formatted); // Compile error
				XWF_OutputMessage(log_message.c_str(), 0);
			}
			void flush_() override {}
	};

	using xwf_logger_mt = xwf::xwf_logger<std::mutex>;
	using xwf_logger_st = xwf::xwf_logger<spdlog::details::null_mutex>;

the full stacktrace is

	In file included from external/spdlog/fmt/fmt.h:22,
					 from external/spdlog/common.h:36,
					 from external/spdlog/spdlog.h:12,
					 from src/lib/xtension.cpp:9:
	external/spdlog/fmt/bundled/core.h: In instantiation of 'fmt::v7::detail::value<Context> fmt::v7::detail::make_arg(const T&) [with bool IS_PACKED = true; Context = fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<wchar_t> >, wchar_t>; fmt::v7::detail::type <anonymous> = fmt::v7::detail::type::int_type; T = fmt::v7::basic_memory_buffer<char, 250>; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]':
	external/spdlog/fmt/bundled/core.h:1410:64:   required from 'fmt::v7::format_arg_store<Context, Args>::format_arg_store(const Args& ...) [with Context = fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<wchar_t> >, wchar_t>; Args = {const fmt::v7::basic_memory_buffer<char, 250, std::allocator<char> >}]'
	external/spdlog/fmt/bundled/core.h:1764:18:   required from 'fmt::v7::format_arg_store<fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<Char> >, Char>, fmt::v7::remove_reference_t<Args>...> fmt::v7::detail::make_args_checked(const S&, fmt::v7::remove_reference_t<Args>& ...) [with Args = {const fmt::v7::basic_memory_buffer<char, 250, std::allocator<char> >&}; S = wchar_t [3]; Char = wchar_t]'
	external/spdlog/fmt/bundled/core.h:1835:57:   required from 'std::__cxx11::basic_string<_CharT> fmt::v7::format(const S&, Args&& ...) [with S = wchar_t [3]; Args = {const fmt::v7::basic_memory_buffer<char, 250, std::allocator<char> >&}; Char = wchar_t]'
	external/spdlog/fmt/bundled/format.h:3449:16:   required from 'std::wstring fmt::v7::to_wstring(const T&) [with T = fmt::v7::basic_memory_buffer<char, 250>; std::wstring = std::__cxx11::basic_string<wchar_t>]'
	external/xwf/logger.h:20:47:   required from 'void xwf::xwf_logger<Mutex>::sink_it_(const spdlog::details::log_msg&) [with Mutex = std::mutex]'
	external/xwf/logger.h:16:9:   required from here
	external/spdlog/fmt/bundled/core.h:1259:35: error: use of deleted function 'fmt::v7::basic_memory_buffer<char, 250>::basic_memory_buffer(const fmt::v7::basic_memory_buffer<char, 250>&)'
	 1259 |   return arg_mapper<Context>().map(val);
		  |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
	In file included from external/spdlog/fmt/fmt.h:23,
					 from external/spdlog/common.h:36,
					 from external/spdlog/spdlog.h:12,
					 from src/lib/xtension.cpp:9:
	external/spdlog/fmt/bundled/format.h:613:7: note: 'fmt::v7::basic_memory_buffer<char, 250>::basic_memory_buffer(const fmt::v7::basic_memory_buffer<char, 250>&)' is implicitly declared as deleted because 'fmt::v7::basic_memory_buffer<char, 250>' declares a move constructor or move assignment operator
	  613 | class basic_memory_buffer : public detail::buffer<T> {
		  |       ^~~~~~~~~~~~~~~~~~~

`XWF_OutputMessage` takes `const wchar_t *` as first argument.

**Comment by tt4g** [comment]
`spdlog::details::log_msg‘ has `char *`.
You can use `MultiByteToWideChar()`: https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar

**Comment by m0rtalis** [comment]
Ok thanks
