### ISSUE TITLE
timezone as output by %z option has a double negative sign

### ISSUE THREAD

**Issue by guyd** [gabime/spdlog#173]
When trying to output a date in 8601 format, I noticed that the timezone is outputted with two negative signs 
```
[2016-02-01T14:20:15.788--5:00]
```
Since the sign of a negative number is a negative number there is not need to add the sign [here](https://github.com/gabime/spdlog/blob/master/include/spdlog/details/pattern_formatter_impl.h#L320).

**Comment by gabime** [comment]
Thanks for reporting. Fixed in 0c7beb2e36008598cf80d0e8eb8635ac403febb9

**Comment by guyd** [comment]
Thanks for the speedy fix!
