### ISSUE TITLE
logger_name returns logger's name and the message

### ISSUE THREAD

**Issue by maxlein** [gabime/spdlog#1730]
I am a bit clueless here.  
I have a custom sink and inside the `sink_it_()` method, I want to get loggers name:  

```cpp
void sink_it_(const spdlog::details::log_msg& msg) override
{
  memory_buf_t formatted;
  ros_sink<Mutex>::formatter_->format(msg, formatted);
  printf("formatted: %s", fmt::to_string(formatted).c_str());
  printf("logger_name: %s\n", msg.logger_name.data());
  printf("data: %s\n", fmt::to_string(msg.payload).c_str());
}
```  

And as you see, the formatter returns a nice log message but retrieving the logger name directly is erronous:  

```
formatted: [2020-11-09 14:29:28.064] [default] [info] Set logger level: return val: 0
logger_name: defaultSet logger level: return val: 0
data: Set logger level: return val: 0
```  

Has someone an idea on what could be wrong here?

**Comment by gabime** [comment]
The logger_name filed is string_view, so the null value at the end  is not guaranteed. 
see https://stackoverflow.com/questions/48081436/how-you-convert-a-stdstring-view-to-a-const-char/48081509

**Comment by maxlein** [comment]
Oh, didn't look into string_view's yet.  
Thanks.  

So if others look here, I convert string_view to char * like that now:  

`fmt::format(msg.logger_name).c_str()
`

**Comment by gabime** [comment]
Note that fmt::to_string allocates new string, so consider optimizing with something like:

```c++

printf("%.*s", static_cast<int>(formatted.size()), payload.data())
printf("%.*s", static_cast<int>(msg.logger_name.data().size()), msg.logger_name.data().data())
```

**Comment by maxlein** [comment]
Sorry, I don't get your hint.  Could you describe this a little further?  
I only see the string length and the payload which I would then pass to a string constructor which also allocates.  

I need to pass the log msg to this function:  

```
void rcutils_log(
  const rcutils_log_location_t * location,
  int severity,
  const char * name,
  const char * format,
  ...)
```

**Comment by gabime** [comment]
The point is to pass the data and length to printf without converting to c string  like this: "%.*s"
