### ISSUE TITLE
Unable to compile using Visual C++ 2013 (v120 - Update 5) 

### ISSUE THREAD

**Issue by andybaish** [gabime/spdlog#1731]
Hoping that this toolset is still supported for an aging codebase.

Using Visual C++ 2013 v120 toolset, Version 18.00.40629

Adding `#include "spdlog/spdlog.h" ` to my project results in a large amount of errors, most of which appear to stem from the 'fmt' library:

![image](https://user-images.githubusercontent.com/8977654/98605501-791d1d00-22dd-11eb-9138-2c171bbec228.png)

I've reverted through various versions of spdlog back to 1.2.0, none of which I'm able to compile.

I'm unable to compile using an external fmt install, of which I've tried various versions back to ~4.0.

Thoughts here would be much appreciated.

**Comment by tt4g** [comment]
C++ 11 support enabled?

**Comment by andybaish** [comment]
My understanding is that C++ 11 support is somewhat 'out-the-box' with the v120 toolset:

https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)?redirectedfrom=MSDN

I'm aware there's no support for `constexpr` with the v120 toolset, but that doesn't appear to be one of the issues in my compilation (although with 208 errors it may well be...).

**Comment by tt4g** [comment]
IMO. From the fmt source code, it looks like the `constexpr` keyword is the reason for the parsing failure.

https://github.com/gabime/spdlog/blob/cbe9448650176797739dbab13961ef4c07f4290f/include/spdlog/fmt/bundled/core.h#L274

However,`FMT_CONSTEXPR` line does not appear to be a parse error:

https://github.com/gabime/spdlog/blob/cbe9448650176797739dbab13961ef4c07f4290f/include/spdlog/fmt/bundled/core.h#L383

Can you remove `constexpr`(or replace `constexpr` with `FMT_CONSTEXPR `)?
