### ISSUE TITLE
Cannot find any examples of how to color individual log callsites

### ISSUE THREAD

**Issue by Qix-** [gabime/spdlog#1733]
I remember seeing some code _somewhere_ that added color to certain parts of _single logging callsites_ (_not_ the overall sink's pattern) but cannot find any official examples here. I see swaths of color-related enumerations but even the tests seem to be lacking such examples.

Can an example be added to the readme for this?

**Comment by gabime** [comment]
I don’t think there is an “official” way to achieve this..Maybe using some hack..

**Comment by Qix-** [comment]
I could have sworn I saw a way to do this - to accent logs with color within color sinks.

But okay, nevermind then 🙃
