### ISSUE TITLE
issues whit spdlog.lib

### ISSUE THREAD

**Issue by seeyuo** [gabime/spdlog#1734]
platform: vs2015
how to use the spdlog.lib ?
The linker's additional dependency library has included spdlog.lib
but in spdlog.h ,it prompts  errors like "Unable to open source file"
do i need to add the path of other header files in the include directory?
![error](https://user-images.githubusercontent.com/40467934/99056671-9bf94b00-25d5-11eb-92a5-7b08a8a7ce2a.png)
thanks

**Comment by tt4g** [comment]
Yes.
You have to add spdlog to the project's include directory.
See https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=msvc-140#directory-and-path-values

**Comment by seeyuo** [comment]
> Yes.
> You have to add spdlog to the project's include directory.
> See https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=msvc-140#directory-and-path-values

These are two ways to use this library .
1. included the path "include" of "VC_IncludePath".  This method compiles the code without problems
2. use the "spdlog.lib",  I compiled the static library. added the static library path to LibPath. But the above problem still occurs
What confuses me is that if I need to include all header file folder paths when I use a static library, is there any point in using a static library?

**Comment by tt4g** [comment]
The difference between static and dynamic libraries is not an issue specific to spdlog, so I'd like to avoid mentioning it.
I recommend finding and understanding sites like the following link: https://stackoverflow.com/questions/140061/when-to-use-dynamic-vs-static-libraries

Also, if you use spdlog as a static library, you have to define an `SPDLOG_COMPILED_LIB` macro.

**Comment by seeyuo** [comment]
> The difference between static and dynamic libraries is not an issue specific to spdlog, so I'd like to avoid mentioning it.
> I recommend finding and understanding sites like the following link: https://stackoverflow.com/questions/140061/when-to-use-dynamic-vs-static-libraries
> 
> Also, if you use spdlog as a static library, you have to define an `SPDLOG_COMPILED_LIB` macro.

Thanks for your reply, I will try again

**Comment by VanishedDust** [comment]
I meet the same problem. If you want solve it in a simple way, just download spdlog1.3.1.  The reason is that after 1.3.1, the head file in "spdlog.h" changed,  "spdlog/common.h"  -> <spdlog/common.h>  ,  so you have to put  the include folder under your visual studio path.

**Comment by seeyuo** [comment]
> I meet the same problem. If you want solve it in a simple way, just download spdlog1.3.1. The reason is that after 1.3.1, the head file in "spdlog.h" changed, "spdlog/common.h" -> <spdlog/common.h> , so you have to put the include folder under your visual studio path.

In fact, my question is, when using the generated "spdlib.lib" library file, do I still need the following two steps:
1>The project file should include all header files in the "include" folder.
2>Add the "include" path to the include-path of the project property page.
If 1 and 2 conditions are required, what is the difference between using it directly without generating the lib library file?

**Comment by tt4g** [comment]
Static library support was added because it was reported that using spdlog as a header-only library in a project could take a long time to build.

**Comment by seeyuo** [comment]
> Static library support was added because it was reported that using spdlog as a header-only library in a project could take a long time to build.

Can you give an example of using static libraries on the visual studio platform, thank you!

**Comment by tt4g** [comment]
I don't usually use Visual Studio IDE, but if you set the include path and library directory, you should be able to use it.
How to build and install spdlog static library is provided by CMake: https://github.com/gabime/spdlog#static-lib-version-recommended---much-faster-compile-times

In addition, Microsoft vcpkg provides spdlog.

**Comment by seeyuo** [comment]
> I don't usually use Visual Studio IDE, but if you set the include path and library directory, you should be able to use it.
> How to build and install spdlog static library is provided by CMake: https://github.com/gabime/spdlog#static-lib-version-recommended---much-faster-compile-times
> 
> In addition, Microsoft vcpkg provides spdlog.

I get it, thank you.
