### ISSUE TITLE
wchar_t support on Linux

### ISSUE THREAD

**Issue by dungcules** [gabime/spdlog#1739]
I am try to use spdlog on my project which build on Linux. I am able to install and add the library but when I build it, I got following error:

`1>/usr/include/spdlog/fmt/bundled/core.h(1069,10): error : no viable conversion from returned value of type 'typename std::enable_if<!std::is_same<wchar_t, typename basic_format_context<back_insert_iterator<basic_buffer<char> >, char>::char_type>::value>::type' (aka 'void') to function return type 'typename std::enable_if<true, value<basic_format_context<back_insert_iterator<basic_buffer<char> >, char> > >::type' (aka 'fmt::v5::internal::value<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >')
1>/usr/include/spdlog/fmt/bundled/core.h(1069,10): error :   return make_value<Context>(value);
1>/usr/include/spdlog/fmt/bundled/core.h(1069,10): error :  

1>/usr/include/spdlog/fmt/bundled/core.h(721,3): error : static_assert failed due to requirement '!sizeof(wchar_t)' "formatting of non-void pointers is disallowed"
1>/usr/include/spdlog/fmt/bundled/core.h(721,3): error :   static_assert(!sizeof(T), "formatting of non-void pointers is disallowed");
1>/usr/include/spdlog/fmt/bundled/core.h(721,3): error :   ^  `

My code is really simple as following: 
`#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

#define SPDLOG_WCHAR_TO_UTF8_SUPPORT

int main() {
	auto spdlogger_obj = spdlog::basic_logger_mt("logger", "/DATA/test_log.txt");
	spdlogger_obj->info(L"Hello");
	return 0;
}`

I wonder if the library supports wide character on Linux or not

**Comment by gabime** [comment]
No, There is only support for windows for this.
