### ISSUE TITLE
Valrind - helgrind and DRD gives errors

### ISSUE THREAD

**Issue by JamesH65** [gabime/spdlog#174]
Getting the following log from Helgrind (similar from DRD) when running the example code below.  Using gcc (gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4).

Any ideas if I am doing something wrong?

`==9840== Possible data race during write of size 8 at 0x6841048 by thread #1
==9840== Locks held: none
==9840==    at 0x4A4D2B: std::__atomic_base<unsigned long>::store(unsigned long, std::memory_order) (atomic_base.h:474)
==9840==    by 0x49EB64: spdlog::details::mpmc_bounded_queue<spdlog::details::async_log_helper::async_msg>::enqueue(spdlog::details::async_log_helper::async_msg&&) (mpmc_bounded_q.h:104)
==9840==    by 0x49A568: spdlog::details::async_log_helper::push_msg(spdlog::details::async_log_helper::async_msg&&) (async_log_helper.h:225)
==9840==    by 0x49A4F0: spdlog::details::async_log_helper::log(spdlog::details::log_msg const&) (async_log_helper.h:216)
==9840==    by 0x49B3A6: spdlog::async_logger::_log_msg(spdlog::details::log_msg&) (async_logger_impl.h:68)
==9840==    by 0x4997CF: spdlog::details::line_logger::~line_logger() (line_logger.h:55)
==9840==    by 0x4923EB: ____C_A_T_C_H____T_E_S_T____881() (testcases.cpp:945)
==9840==    by 0x44A625: Catch::FreeFunctionTestCase::invoke() const (catch.hpp:5818)
==9840==    by 0x437058: Catch::TestCase::invoke() const (catch.hpp:6723)
==9840==    by 0x44855E: Catch::RunContext::invokeActiveTestCase() (catch.hpp:5417)
==9840==    by 0x448208: Catch::RunContext::runCurrentTest(std::string&, std::string&) (catch.hpp:5389)
==9840==    by 0x446BFC: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:5228)
==9840== 
==9840== This conflicts with a previous read of size 8 by thread #53
==9840== Locks held: none
==9840==    at 0x4A5031: std::__atomic_base<unsigned long>::load(std::memory_order) const (atomic_base.h:496)
==9840==    by 0x49ED8D: spdlog::details::mpmc_bounded_queue<spdlog::details::async_log_helper::async_msg>::dequeue(spdlog::details::async_log_helper::async_msg&) (mpmc_bounded_q.h:116)
==9840==    by 0x49A9B2: spdlog::details::async_log_helper::process_next_msg(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&, std::chrono::time_point<std::chrono::_V2::sy
stem_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&) (async_log_helper.h:271)
==9840==    by 0x49A6A0: spdlog::details::async_log_helper::worker_loop() (async_log_helper.h:251)
==9840==    by 0x4CEA04: void std::_Mem_fn<void (spdlog::details::async_log_helper::*)()>::operator()<, void>(spdlog::details::async_log_helper*) const (in /build/jamesh/workspace/framework/test/framework_test)
==9840==    by 0x4CE69A: void std::_Bind_simple<std::_Mem_fn<void (spdlog::details::async_log_helper::*)()> (spdlog::details::async_log_helper*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (functional:1732)
==9840==    by 0x4CDF6E: std::_Bind_simple<std::_Mem_fn<void (spdlog::details::async_log_helper::*)()> (spdlog::details::async_log_helper*)>::operator()() (functional:1720)
==9840==    by 0x4CD3FB: std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (spdlog::details::async_log_helper::*)()> (spdlog::details::async_log_helper*)> >::_M_run() (thread:115)
==9840==  Address 0x6841048 is 8 bytes inside a block of size 58,720,264 alloc'd
==9840==    at 0x4C2CC20: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==9840==    by 0x49E613: spdlog::details::mpmc_bounded_queue<spdlog::details::async_log_helper::async_msg>::mpmc_bounded_queue(unsigned long) (mpmc_bounded_q.h:62)
==9840==    by 0x49A287: spdlog::details::async_log_helper::async_log_helper(std::shared_ptr<spdlog::formatter>, std::vector<std::shared_ptr<spdlog::sinks::sink>, std::allocator<std::shared_ptr<spdlog::sinks::sink> > > const&, unsigned lon
g, spdlog::async_overflow_policy, std::function<void ()> const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&) (async_log_helper.h:196)
==9840==    by 0x49F229: spdlog::async_logger::async_logger<std::shared_ptr<spdlog::sinks::sink> const*>(std::string const&, std::shared_ptr<spdlog::sinks::sink> const* const&, std::shared_ptr<spdlog::sinks::sink> const* const&, unsigned l
ong, spdlog::async_overflow_policy, std::function<void ()> const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&) (async_logger_impl.h:23)
==9840==    by 0x4C9A09: _ZN9__gnu_cxx13new_allocatorIN6spdlog12async_loggerEE9constructIS2_IRKSsRKPKSt10shared_ptrINS1_5sinks4sinkEESE_RmRNS1_21async_overflow_policyERSt8functionIFvvEERNSt6chrono8durationIlSt5ratioILl1ELl1000EEEEEEEvPT_Dp
OT0_ (in /build/jamesh/workspace/framework/test/framework_test)
==9840==    by 0x4C905E: _ZNSt16allocator_traitsISaIN6spdlog12async_loggerEEE12_S_constructIS1_IRKSsRKPKSt10shared_ptrINS0_5sinks4sinkEESE_RmRNS0_21async_overflow_policyERSt8functionIFvvEERNSt6chrono8durationIlSt5ratioILl1ELl1000EEEEEEENSt
9enable_ifIXsrNS3_18__construct_helperIT_IDpT0_EEE5valueEvE4typeERS2_PSU_DpOSV_ (alloc_traits.h:254)
==9840==    by 0x4C86EF: _ZNSt16allocator_traitsISaIN6spdlog12async_loggerEEE9constructIS1_IRKSsRKPKSt10shared_ptrINS0_5sinks4sinkEESE_RmRNS0_21async_overflow_policyERSt8functionIFvvEERNSt6chrono8durationIlSt5ratioILl1ELl1000EEEEEEEDTcl12_
S_constructfp_fp0_spcl7forwardIT0_Efp1_EEERS2_PT_DpOSS_ (alloc_traits.h:393)
==9840==    by 0x4C7E8D: std::_Sp_counted_ptr_inplace<spdlog::async_logger, std::allocator<spdlog::async_logger>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::string const&, std::shared_ptr<spdlog::sinks::sink> const* const&, 
std::shared_ptr<spdlog::sinks::sink> const* const&, unsigned long&, spdlog::async_overflow_policy&, std::function<void ()>&, std::chrono::duration<long, std::ratio<1l, 1000l> >&>(std::allocator<spdlog::async_logger>, std::string const&, st
d::shared_ptr<spdlog::sinks::sink> const* const&, std::shared_ptr<spdlog::sinks::sink> const* const&, unsigned long&, spdlog::async_overflow_policy&, std::function<void ()>&, std::chrono::duration<long, std::ratio<1l, 1000l> >&) (shared_pt
r_base.h:399)
==9840==    by 0x4C73AE: _ZN9__gnu_cxx13new_allocatorISt23_Sp_counted_ptr_inplaceIN6spdlog12async_loggerESaIS3_ELNS_12_Lock_policyE2EEE9constructIS6_IKS4_RKSsRKPKSt10shared_ptrINS2_5sinks4sinkEESJ_RmRNS2_21async_overflow_policyERSt8functio
nIFvvEERNSt6chrono8durationIlSt5ratioILl1ELl1000EEEEEEEvPT_DpOT0_ (in /build/jamesh/workspace/framework/test/framework_test)
==9840==    by 0x4C6144: _ZNSt16allocator_traitsISaISt23_Sp_counted_ptr_inplaceIN6spdlog12async_loggerESaIS2_ELN9__gnu_cxx12_Lock_policyE2EEEE12_S_constructIS6_IKS3_RKSsRKPKSt10shared_ptrINS1_5sinks4sinkEESK_RmRNS1_21async_overflow_policyE
RSt8functionIFvvEERNSt6chrono8durationIlSt5ratioILl1ELl1000EEEEEEENSt9enable_ifIXsrNS8_18__construct_helperIT_IDpT0_EEE5valueEvE4typeERS7_PS10_DpOS11_ (alloc_traits.h:254)
==9840==    by 0x4C40F5: _ZNSt16allocator_traitsISaISt23_Sp_counted_ptr_inplaceIN6spdlog12async_loggerESaIS2_ELN9__gnu_cxx12_Lock_policyE2EEEE9constructIS6_IKS3_RKSsRKPKSt10shared_ptrINS1_5sinks4sinkEESK_RmRNS1_21async_overflow_policyERSt8
functionIFvvEERNSt6chrono8durationIlSt5ratioILl1ELl1000EEEEEEEDTcl12_S_constructfp_fp0_spcl7forwardIT0_Efp1_EEERS7_PT_DpOSY_ (alloc_traits.h:393)
==9840==    by 0x4C19A3: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<spdlog::async_logger, std::allocator<spdlog::async_logger>, std::string const&, std::shared_ptr<spdlog::sinks::sink> const* const&, std::shared_ptr<sp
dlog::sinks::sink> const* const&, unsigned long&, spdlog::async_overflow_policy&, std::function<void ()>&, std::chrono::duration<long, std::ratio<1l, 1000l> >&>(std::_Sp_make_shared_tag, spdlog::async_logger*, std::allocator<spdlog::async_
logger> const&, std::string const&, std::shared_ptr<spdlog::sinks::sink> const* const&, std::shared_ptr<spdlog::sinks::sink> const* const&, unsigned long&, spdlog::async_overflow_policy&, std::function<void ()>&, std::chrono::duration<long, std::ratio<1l, 1000l> >&) (shared_ptr_base.h:502)
==9840==  Block was alloc'd by thread #1'

Exmaple code

`TEST_CASE("Testing spdlog logging library", "[SPDLOG]")
{
    namespace spd = spdlog;

    //Create console, multithreaded logger
    auto console = spd::stdout_logger_mt("console");
    console->info("Welcome to spdlog!");
    console->info("An info message example {}..", 1);
    console->info() << "Streams are supported too  " << 1;

    //Formatting examples
    console->info("Easy padding in numbers like {:08d}", 12);
    console->info("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
    console->info("Support for floats {:03.2f}", 1.23456);
    console->info("Positional args are {1} {0}..", "too", "supported");

    console->info("{:<30}", "left aligned");
    console->info("{:>30}", "right aligned");
    console->info("{:^30}", "centered");

    //
    // Runtime log levels
    //
    spd::set_level(spd::level::info); //Set global log level to info
    console->debug("This message shold not be displayed!");
    console->set_level(spd::level::debug); // Set specific logger's log level
    console->debug("Now it should..");

    //
    // Create a file rotating logger with 5mb size max and 3 rotated files
    //
    auto file_logger = spd::rotating_logger_mt("file_logger", "mylogfile.log", 1048576 * 5, 3);
    for (int i = 0; i < 10; ++i)
        file_logger->info("{} * {} equals {:>10}", i, i, i*i);

    //
    // Create a daily logger - a new file is created every day on 2:30am
    //
    auto daily_logger = spd::daily_logger_mt("daily_logger", "daily.log", 2, 30);

    //
    // Customize msg format for all messages
    //
    spd::set_pattern("*** [%H:%M:%S %z] [thread %t] %v ***");
    file_logger->info("This is another message with custom format");

    spd::get("console")->info("loggers can be retrieved from a global registry using the spdlog::get(logger_name) function");

    //
    // Compile time debug or trace macros.
    // Enabled #ifdef SPDLOG_DEBUG_ON or #ifdef SPDLOG_TRACE_ON
    //
    SPDLOG_TRACE(console, "Enabled only #ifdef SPDLOG_TRACE_ON..{} ,{}", 1, 3.23);
    SPDLOG_DEBUG(console, "Enabled only #ifdef SPDLOG_DEBUG_ON.. {} ,{}", 1, 3.23);

    //
    // Asynchronous logging is very fast..
    // Just call spdlog::set_async_mode(q_size) and all created loggers from now on will be asynchronous..
    //
    size_t q_size = 1048576; //queue size must be power of 2
    spdlog::set_async_mode(q_size);
    auto async_file = spd::daily_logger_st("async_file_logger", "async_log.txt");
    for (int i = 0; i < 100; ++i)
        async_file->info("Async message #{}", i);

    std::string ident = "spdlog-example";
    auto syslog_logger = spd::syslog_logger("syslog", ident, LOG_PID);
    syslog_logger->warn("This is warning that will end up in syslog. This is Linux only!");

    //
    //Release and close all loggers
    //
    spdlog::drop_all();
}
`

**Comment by gabime** [comment]
i am not sure. sorry
