### ISSUE TITLE
Logging to multiple sinks from global context

### ISSUE THREAD

**Issue by angrdtsk** [gabime/spdlog#1741]
In a program that I am writing, I'd like to have a logging system that would be able to write to both console and files (independent log files and syslog) and to be easily (singleton-ishly) accessible from any class in the program.

The multi-sink example seems to be what is needed for writing console and files and that works. The problem seems to be in making it singleton-ish.

I am creating the logger with this line from the example:
`spdlog::logger logger("multi_sink", {console_sink, file_sink});`

I then tried to access it from another class with this line:
`spdlog::get("multi_sink")->info("Some log message");`

That, however, gives segmentation fault. The documentation says that spdlog::get() returns nullptr if the names logger does not exist. Is that what is happening?

Next, I tried to make that logger the default logger with this code:
`auto logger = std::make_shared<spdlog::logger>("multi_sink", {console_sink, file_sink});`
`spdlog::set_default_logger(logger);`

That, however, won't compile. The compiler says
`error: too many arguments to function ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = spdlog::logger; _Args = {}]’`
`auto logger = std::make_shared<spdlog::logger>("", {console_sink, file_sink});`

The problem seems to be in providing multiple sinks i.e. a list of sinks instead of just one when using std::make_shared().

What am I doing wrong with my code, or is there some better way to do what I am after?

**Comment by tt4g** [comment]
> I am creating the logger with this line from the example:
> `spdlog::logger logger("multi_sink", {console_sink, file_sink});`
>
> I then tried to access it from another class with this line:
> `spdlog::get("multi_sink")->info("Some log message");`

spdlog::get()` returns `nullptr` if you do not register the logger in the spdlog global registry by calling `spdlog::register_logger()`.

> The problem seems to be in providing multiple sinks i.e. a list of sinks instead of just one when using std::make_shared().
>
> What am I doing wrong with my code, or is there some better way to do what I am after?

Perhaps the types of console sink and file sink are different (My guess is `std::shared_ptr<spdlog::sinks::stdout_sink_mt> and `std::shared_ptr<spdlog::sinks::basic_file_sink_mt>`).
Declare two common ancestor classes.
See https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#creating-loggers-with-multiple-sinks

**Comment by angrdtsk** [comment]
The code example behind the link solved problem. I just replaced the calls to the constructors of the sinks inside the calls to vector's push_back() with references to sinks instantiated separately.

Thanks!

**Comment by angrdtsk** [comment]
Am I supposed to close this issue myself now that the problem got solved? How does this work?

**Comment by tt4g** [comment]
If you've solved the problem, then the issue can be closed yourself.
