### ISSUE TITLE
Explicit #include <algorithm> is required in helpers-inl.h

### ISSUE THREAD

**Issue by makkarpov** [gabime/spdlog#1743]
Today I faced an issue where implicit inclusion of `<algorithm>` header was absent in `helpers-inl.h` file, resulting in a error when trying to do `std::transform`:

https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/cfg/helpers-inl.h#L23

Specifically, spdlog was included as CMake subproject, and `SPDLOG_FMT_EXTERNAL` was set to `ON`, while fmt was included as separate subproject. But I don't know whether this is sufficient conditions to reproduce.

**Comment by gabime** [comment]
Fixed today by @jwitt in https://github.com/gabime/spdlog/pull/1742
