### ISSUE TITLE
Can I turn a logger on and off during runtime?

### ISSUE THREAD

**Issue by winduptoy** [gabime/spdlog#175]
I want to make multiple loggers for different subsystems within my application and have them all log to stdout. Is there a way to toggle specific loggers on and off during runtime, so that I can focus on the logs for a specific subsystem?

Also, is it possible to remove loggers during compilation for performance?

**Comment by gabime** [comment]
sure. logging level can be changed on runtime.

 to turn off completly you can do 'my_logger.set_level(spdlog::level::off)'

**Comment by winduptoy** [comment]
Awesome, thank you.

I don't see in the documentation if spdlog supports removing all logging during compilation (i.e. with preprocessor macros). Is this possible?
