### ISSUE TITLE
Custom formatting on windows:  `[%s:%#]` does much more than the filename:line_nb

### ISSUE THREAD

**Issue by Milerius** [gabime/spdlog#1750]
Compiler: clang-11
OS: Windows 10

Screenshot of the output:

![image](https://user-images.githubusercontent.com/21139416/100449078-990d5880-30b3-11eb-8a1c-a42a7d661c44.png)

was expecting the same output as osx/linux:

<img width="830" alt="Capture d’écran 2020-11-27 à 13 17 54" src="https://user-images.githubusercontent.com/21139416/100448679-f8b73400-30b2-11eb-9780-bdf5a6a3ba64.png">

According to https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags:

I should just have the filename, not the full path or indirect path

My set_pattern:

```cpp
spdlog::set_pattern("[%T] [%^%l%$] [%s:%#]: %v");
```

https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/details/os.h#L36 ///< This line seems wrong too, according to my screenshot my separator is `/` not `\\`

(spdlog 1.8.1)

**Comment by gabime** [comment]
I think pr #1787 fixed this. Could you try @Milerius ?

**Comment by Milerius** [comment]
I will check as soon as possible tyvm

**Comment by Milerius** [comment]
> I think pr #1787 fixed this. Could you try @Milerius ?

It's working thanks a lot !
