### ISSUE TITLE
Gibberish stdout of UTF-8 characters in non-unicode codepage

### ISSUE THREAD

**Issue by yetanothercheer** [gabime/spdlog#1751]
https://github.com/gabime/spdlog/blob/233e97c5e46d8f8e83a6ea06b2dc8db804a4aed4/include/spdlog/sinks/wincolor_sink-inl.h#L138

AFAIK, this line will not work as expected on UTF-8 string in locale codepage. A workaround is
```
 SetConsoleOutputCP(65001);
```

So, is this a bug or a feature?

**Comment by tt4g** [comment]
IMO.

There is no specification for character encoding in C++.
Therefore, it is the responsibility of the programmer to coordinate the character encoding inside C++ with the console encoding.

**Comment by yetanothercheer** [comment]
Thanks for your reply!

BTW, I notice fmt use 
https://github.com/gabime/spdlog/blob/233e97c5e46d8f8e83a6ea06b2dc8db804a4aed4/include/spdlog/fmt/bundled/core.h#L321-L326
to determine the encoding of source files (I am not quite sure, though), and use this 
https://github.com/gabime/spdlog/blob/cd701761f9ad9919b9409e519237fb4c90f6375d/include/spdlog/fmt/bundled/format-inl.h#L1419-L1425
to print correctly in a locale codepage.

Can we do the same thing to make programmer's life easier?

**Comment by tt4g** [comment]
For now there is only support for converting UTF-16 (`wchar_t`) to UTF-8 (`char`).

If you need that feature right now, you might want to create a custom sync.
A helpful implementation is `spdlog::sinks::wincolor_sink`. This is the only one that uses the `WriteConsoleA()` API.

https://github.com/gabime/spdlog/blob/cbe9448650176797739dbab13961ef4c07f4290f/include/spdlog/sinks/wincolor_sink-inl.h#L134-L139
