### ISSUE TITLE
Need the rotating log part number in ascend sequence

### ISSUE THREAD

**Issue by tashaxing** [gabime/spdlog#1755]
Current rotating log part number is in a reverse sequence, the bigger number log stands for the early log, thas is not convinient
for example
18:04:06 my.1.log  
18:03:05 my.2.log
18:02:01 my.3.log 

Can this be in a normal sequence, the bigger number log stands for the older log, that is fine
for example
18:02:01 my.1.log  
18:03:05 my.2.log
18:04:06 my.3.log

**Comment by gabime** [comment]
Thats standard practice in numerous log libs.
