### ISSUE TITLE
Please can basic example show switching to stderr

### ISSUE THREAD

**Issue by tonyelewis** [gabime/spdlog#1759]
Thanks very much for this library and for having helpful examples in the docs.

I'm trying to figure out the simplest way to switch to `stderr` so that `spdlog::warn()` etc will go to `stderr`. It occurs to me that I think this would be a really useful thing to include in the [Basic-example](https://github.com/gabime/spdlog/wiki/1.-QuickStart#basic-example).

Also, please may I ask: what's the answer? I haven't been able to figure it out.

Thanks very much.

**Comment by tonyelewis** [comment]
Is the following the simplest way to switch to `stderr`?

~~~cpp
spdlog::set_default_logger( spdlog::stderr_color_st( "some_arbitrary_name" ) );
~~~

**Comment by tt4g** [comment]
> Is the following the simplest way to switch to stderr?

Right.

**Comment by tony-triller** [comment]
> Right.

Thanks very much. I think it would be really useful for us to put something like this in the [Basic-example](https://github.com/gabime/spdlog/wiki/1.-QuickStart#basic-example).

But first, one problem with the above code is that it causes `[some_arbitrary_name]` to be inserted into the log messages:

```
[2020-12-16 09:34:50.033] [some_arbitrary_name] [warning] Message
```

&hellip;whereas the original unmodified log has no such field:

```
[2020-12-16 09:35:19.577] [warning] Message
```

`spdlog::stderr_color_st()` doesn't compile and `spdlog::stderr_color_st( "" )` causes a `spdlog::spdlog_ex` to be thrown with a `.what()` message of : `logger with name '' already exists`.

What's the simplest way to switch from `stdout` to `stderr` without changing anything else?

**Comment by tony-triller** [comment]
~~~cpp
spdlog::set_default_logger( spdlog::stderr_color_st( "some_arbitrary_name" ) );
spdlog::set_default_logger( spdlog::stderr_color_st( "" ) );
~~~

&hellip;appears to work. Is there a better way?

**Comment by tonyelewis** [comment]
<sup>(replacing comment mistakenly posted from different account - sorry for the muddle)</sup>

> Right.

Thanks very much. I think it would be really useful for us to put something like this in the [Basic-example](https://github.com/gabime/spdlog/wiki/1.-QuickStart#basic-example).

But first, one problem with the above code is that it causes `[some_arbitrary_name]` to be inserted into the log messages:

```
[2020-12-16 09:34:50.033] [some_arbitrary_name] [warning] Message
```

&hellip;whereas the original unmodified log has no such field:

```
[2020-12-16 09:35:19.577] [warning] Message
```

`spdlog::stderr_color_st()` doesn't compile and `spdlog::stderr_color_st( "" )` causes a `spdlog::spdlog_ex` to be thrown with a `.what()` message of : `logger with name '' already exists`.

This appears to work:

~~~cpp
spdlog::set_default_logger( spdlog::stderr_color_st( "some_arbitrary_name" ) );
spdlog::set_default_logger( spdlog::stderr_color_st( "" ) );
~~~

Is this valid? Is there a simpler way to switch from `stdout` to `stderr` without changing anything else?

**Comment by tt4g** [comment]
> spdlog::stderr_color_st() doesn't compile and spdlog::stderr_color_st( "" ) causes a spdlog::spdlog_ex to be thrown with a .what() message of : logger with name '' already exists.

The first argument of `spdlog::stderr_color_st()` is used for the logger name.
spdlog manages loggers internally and uses the logger name to identify the logger.
If the logger name is duplicated, it cannot be managed, so `throw` exception.

**Comment by tt4g** [comment]
> But first, one problem with the above code is that it causes [some_arbitrary_name] to be inserted into the log messages:

It is metadata that is added by the formatter.
By setting up a formatter, you can remove extra metadata from the log.
See: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

> Is this valid? Is there a simpler way to switch from stdout to stderr without changing anything else?

You can override default format.

Example:
```cpp
spdlog::set_pattern("%Y-%m-%d %H:%M:%S.%e [%l] %v");
spdlog::set_default_logger(spdlog::stderr_color_mt("some_arbitrary_name"));

// Output: [2020-12-16 09:35:19.577] [warning] Message
spdlog::warn("Message");
```

**Comment by tonyelewis** [comment]
Thanks.

It feels wrong to be changing the format to some complex, specific string to to just switch to `stderr`. I think I'll go for:

~~~cpp
spdlog::set_default_logger( spdlog::stderr_color_st( "some_arbitrary_name" ) );
spdlog::set_default_logger( spdlog::stderr_color_st( "" ) );
~~~

&hellip;for now.

Are you open to your recommended approach to `stderr`-switching being added to the docs? I'm guessing that that's a pretty common first thing that many users will want to do.

**Comment by tt4g** [comment]
Updates and PR for the Wiki FAQ page are welcome.

**Comment by tonyelewis** [comment]
Thanks.

How can I PR for the wiki? Or are you happy for me to make direct edits there?

**Comment by gabime** [comment]
You can make direct edits in the wiki.

**Comment by tonyelewis** [comment]
Thanks. I've added this &sect; : https://github.com/gabime/spdlog/wiki/0.-FAQ#how-can-output-be-switched-to-stderr

**Comment by gabime** [comment]
Thanks @tonyelewis
