### ISSUE TITLE
SPDLOG_DISABLE_DEFAULT_LOGGER is not a cmake option

### ISSUE THREAD

**Issue by shimaowo** [gabime/spdlog#1765]
Is there a reason that SPDLOG_DISABLE_DEFAULT_LOGGER is omitted from cmake options?  The other tweakme variables have cmake options as well, which makes things slightly nicer, or at least more uniform, when using spdlog as a dependency.

Without it being a proper option, you instead have to do something like this:
```
option(SPDLOG_NO_ATOMIC_LEVELS "" ON)
add_subdirectory(vendor/spdlog)
# no cmake option for this for some reason
target_compile_definitions(spdlog PRIVATE
    SPDLOG_DISABLE_DEFAULT_LOGGER
)
``` 

or, when building from the command line, it's perhaps even more annoying:
`CXXFLAGS="-DSPDLOG_DISABLE_DEFAULT_LOGGER" cmake -S. -Bbuild -G "Unix Makefiles" -DSPDLOG_NO_ATOMIC_LEVELS -DCMAKE_BUILD_TYPE=Release`

(CXXFLAGS here must be specified as an env var, rather than using the CMAKE_ version, or it will overwrite and not append.  This is sort of unintuitive and messy)

It seems like this could just be added to the existing compiler flag foreach in CMakeLists.txt (as well as adding the option itself, of course) https://github.com/gabime/spdlog/blob/17c6e6ee3fe720f78bafb5c0d5ce03155cb903cf/CMakeLists.txt#L195-L209

Was there a reason for this to be omitted?

**Comment by gabime** [comment]
You are right. This should be a cmake option. PR is welcome.
