### ISSUE TITLE
daily_file_sink don't create a new log file at the correct time

### ISSUE THREAD

**Issue by f1msch** [gabime/spdlog#1769]
HI,I am going to create a new log file after an appointed time.
For example,I am going to log a file naming filename_2020-12-23.log before 2020-12-23 1:00 am; and create a new one just after 2020-12-23 1:00 as filename_2020-12-24.log.The code is like below:
#include "spdlog/spdlog.h"
#include "spdlog/sinks/daily_file_sink.h"
#include  < chrono > 
using namespace std;
int main()
{
	int hours = 1;
	int minutes = 0; 
	auto logger = spdlog::daily_logger_mt("logger_name", "filename.log", hours, minutes);
	spdlog::flush_every(std::chrono::seconds(1));
	while(1)
	{
		logger->info("logging");
		sleep(10);
	}
}
But it turns out when I start the program before 2020-12-23 0:00(date changed when the program running), it will work correctly; but when I start it after 2020-12-23 0:00(date not changed when the program running),it will not create a new log.
Could it have a solution to achieve my purpose?

**Comment by tt4g** [comment]
> But it turns out when I start the program before 2020-12-23 0:00(date changed when the program running), it will work correctly; but when I start it after 2020-12-23 0:00(date not changed when the program running),it will not create a new log.
Could it have a solution to achieve my purpose?

Daily rotation contains only the date and time in the file name, so if the date does not change after the rotation time, it will be logged in the previous file.

If the date changes from 2020-12-22 to 2020-12-23, the log file will be changed from `{filename}_2020-12-22.{ext}` to `{filename}_2020-12-23.{ext}`.
However, on 2020-12-23 00:00 and 2020-12-23 01:00, the date has not changed, so the log file remains the same.

The file name is generated by `daily_filename_calculator`.
I think you can achieve your goal by replacing the template argument with your own implementation that includes the minutes in the filename.

https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/sinks/daily_file_sink.h#L24-L45

**Comment by tt4g** [comment]
I noticed that `hourly_file_sink` is exists in v1.x branch (see #1763).
You can use it after next release.
