### ISSUE TITLE
Benchmarks use bundled fmt even if SPDLOG_FMT_EXTERNAL is defined

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [gabime/spdlog#1772]
This should be a trivial fix, I can make a pr for it if you would like.

https://github.com/gabime/spdlog/blob/a5f413910268ab6dad5dd7a48161d2e57b256fa4/bench/bench.cpp#L14
https://github.com/gabime/spdlog/blob/a5f413910268ab6dad5dd7a48161d2e57b256fa4/bench/async_bench.cpp#L12

**Comment by gabime** [comment]
Right, pr is welocme
