### ISSUE TITLE
Outputting different log levels to different files and questions about using the library

### ISSUE THREAD

**Issue by IanQS** [gabime/spdlog#1776]
Hello! 

I've got a few questions about how to use the library. As far as I know, the docs don't answer my questions so I thought I'd post this here.

Say I've got a module:

```
project
  - src 
    - file1.h
    - file1.cpp
  - third_party
  - main.cpp
```

1) How would I output the different logs to different files? In Python, I specify that I want to output different log levels to different files but I'm not sure how to do that here. Would I create a sink list as in [example](https://spdlog.docsforge.com/v1.x/1.quickstart/#create-a-logger-with-multiple-sinks-each-sink-with-its-own-formatting-and-log-level)? 

2) I notice that in the examples there is no distinction between logging levels (they all get pushed to 1 file). Is this the preferred way to use this library? 

3) Say I want logging in `file1.cpp`. Should I import the logging library in the header or in the implementation? I've been scanning through projects on GitHub that use spdlog and it seems to be a mixed bag.

4) Related to ^. Should I create a logger for `file1.X` within main.cpp, register it, then use the getter from inside `file1` to get the logger? E.g in [docs](https://spdlog.docsforge.com/v1.x/1.quickstart/#create-a-logger-with-multiple-sinks-each-sink-with-its-own-formatting-and-log-level)

```
// globally register the loggers so so the can be accessed using spdlog::get(logger_name)
spdlog::register_logger(net_logger);
```

Or should I create a logger inside `file1` ? I'm assuming it's the first but I just want to make sure

**Comment by tt4g** [comment]
> 1. How would I output the different logs to different files? In Python, I specify that I want to output different log levels to different files but I'm not sure how to do that here. Would I create a sink list as in example?

Yes.

> 2. I notice that in the examples there is no distinction between logging levels (they all get pushed to 1 file). Is this the preferred way to use this library?

Do you mean you want to change the output file for each log level, like a Python logger?
If so, spdlog does not provide such a feature.
You can achieve your goal by preparing your own class that wraps other sinks such as `spdlog::sinks::dist_sink`.

**Comment by tt4g** [comment]
> 3. Say I want logging in file1.cpp. Should I import the logging library in the header or in the implementation? I've been scanning through projects on GitHub that use spdlog and it seems to be a mixed bag.

You must include the spdlog header file with sources and headers that use classes that exist in the spdlog namespace.
This is a restriction imposed by the C++ specification.

> 4. Related to ^. Should I create a logger for file1.X within main.cpp, register it, then use the getter from inside file1 to get the logger? E.g in docs

You can use either `main.cpp` or `file1.X` to create logger.
Loggers registered with `spdlog::register_logger()` can be get with `spdlog::get()`.
