### ISSUE TITLE
My code was working but now it's failing---

### ISSUE THREAD

**Issue by sbrothy** [gabime/spdlog#1777]
Basicalli I am setting up more than one sink. On rotating file sink and (optionally) aconsole color logger, like this:

`
[...]
	std::vector<spdlog::sink_ptr>						m_sinks;
	std::shared_ptr<spdlog::logger>					m_log;
[...}

		try { 
			// set up spdlog
			m_sinks.push_back(
				std::make_shared<spdlog::sinks::rotating_file_sink_mt>(
					get_log_file_name(),			// returns "server.log"
					get_log_file_size(), 			// returns 4096
					get_log_max_num_files(), 		// returns 5
					log_rotate_on_open()			// returns true
				)
			);
		} catch(const std::out_of_range &e) {
			std::cerr << "Exceptioh caught trying std::vector::psuh_back(): " << e.what() << std::endl;
			throw;
		}
[...]
`

This used to work mind but suddenly I get the out_of_range exception. What m I doing wrong?

Regards

**Comment by sbrothy** [comment]
That would be:

`
std::vector<spdlog::sink_ptr> m_sinks;
std::shared_ptr<spdlog::logger> m_log;`
`

**Comment by sbrothy** [comment]
Ah, as usual the problem was elsewhere. Specifically with the "log_rotate_on_open()" function. Nevermind.

**Comment by sbrothy** [comment]
BTW, I really like spdlog. You people did a good job there. Thumbs up. :)

**Comment by gabime** [comment]
Thanks @sbrothy !
