### ISSUE TITLE
Obsolete version in Ubuntu repository

### ISSUE THREAD

**Issue by colesnicov** [gabime/spdlog#1778]
I just want to point out that there is only one very obsolete version of 'spdlog' in the ubuntu repositories. It is in version '**1: 0.16.3-1**' and in addition only '_DEV_' build is available. '_RELEASE_' is missing .. You can close this ISSUE after reading. Thank you for your attention.

**Comment by gabime** [comment]
Thanks for the heads up.

**Comment by Samahu** [comment]
I just found out that the 'spdlog' version on Ubuntu 18 is very old. What is the recommendation on this? Any advice?

**Comment by tt4g** [comment]
@Samahu Ubuntu repositories are not maintained here. you can ask questions in the Ubuntu Community.
