### ISSUE TITLE
How to log a self-defined structure 

### ISSUE THREAD

**Issue by f1msch** [gabime/spdlog#1779]
hi，
If there is a struct like
struct st
{
    int a;
}
I can log by using "operator<<" just like what's in examples,and I'v already achieve that.
But
My question is if there is a struct like
struct st1
{
    int a1;
    map<int, int> m1;
}
How to log just simply using "log->info(...)" too?
Even if there is a struct like
struct st2
{
    int a2;
    map<int, st> m2;
}
How to log then?

**Comment by colesnicov** [comment]
**why don't you use tags for the code? it would be formatted...**

[https://github.com/gabime/spdlog/wiki/1.-QuickStart](https://github.com/gabime/spdlog/wiki/1.-QuickStart) - at the end of page!

**Comment by colesnicov** [comment]
Override operator for structure? :)
