### ISSUE TITLE
Quite a complication, for a novice.

### ISSUE THREAD

**Issue by colesnicov** [gabime/spdlog#1780]
I don't know if it's complicated enough, I can't compile it in the Eclipse IDE: "Please define **SPDLOG_COMPILED_LIB** to compile this file." Of course, it's okay now.

I tried these procedures:

- I tried to define in _Project > Properties > C / C ++ Build > Environment_ and _BUILD_VARIABLES_, it didn't help.

- I tried to remove the '_test_' folder from the build (I had to disable its compilation) because it tried to compile everything possible. It didn't help

I also had to omit the '_bench_' folder from the compilation, I don't have a benchmark installed on the system ...

It helped with this:
_Project> Properties> C / C ++ Build> GCC [C | C ++] Compiler> Preprocessor> ADD Symbol (-D ...)_ - add the symbol '**SPDLOG_COMPILED_LIB**' here.

To be sure, I also disabled the compilation of the '_examples_' folder, and the report also reported errors.

It can be complicated for a novice, and rather than use it, he would rather use something easier to assemble. Just so you know.

**Comment by gabime** [comment]
It is very simple actually if using cmake (the recommended usage).

**Comment by colesnicov** [comment]
_I forgot to state in the first post that it is not an **ISSUE**, it is only an observation._ 

**Yes, if you know what you are doing**. But I, for example, and many others, we know cmake just from the discussion .. Of course, it can all be put into operation. But if there was a **simple WIKI page that explained the configuration of the compilation in the IDE**, it would be even better, at least for those newcomers .. :)

Otherwise, good work.

**Comment by gabime** [comment]
@colesnicov Feel free to add a wiki section about it.

**Comment by colesnicov** [comment]
My English is very bad, I mostly use a translator. But can I write a simple tutorial (a few lines of text), how to run it under the Eclipse IDE and give it to you to moderate?

**Comment by gabime** [comment]
Sure

**Comment by colesnicov** [comment]
Go on https://github.com/gabime/spdlog/wiki/Integrating-into-Eclipse-IDE
In the future, I will add a couple of pictures, now you do not, I make a screenshot, Exhibit one:

**Comment by gabime** [comment]
Thanks!

**Comment by colesnicov** [comment]
A little problem, I can't upload a picture to **WIKI**, I would have to upload to `imgur.com`, for example, and then throw a link here. Which is not good, if I accidentally delete the image on `imgur.com`, it will also disappear here...
