### ISSUE TITLE
Custom TAGS/LABELS?

### ISSUE THREAD

**Issue by colesnicov** [gabime/spdlog#1781]
Can I use ''Labels" or "TAGS"

  Something like:

```
char * TAG = "MUJ_TAG";
logger-> setTag (MUJ_TAG) -> info ("incredible");
```

Or do I have to **change the pattern every time?** For example, as follows:

```
logger-> set_pattern ("MUJ_TAG %H:%m:%i %v");
logger-> info ("boring");
```

I ask, because I have a fairly large program, based on my own SDK and modules to it.

So far, I use my own implementation of the logger (quite primitive) but I would like to replace it.

At the same time, I want to have only one instance of Logger in the SDK in the whole application, and the other modules must access it. At the same time, each module **has its own TAG for easy identification**.

**Comment by colesnicov** [comment]
If this is not possible, then perhaps such a possibility will appear in the future?

**Comment by gabime** [comment]
Something like this: https://github.com/gabime/spdlog/pull/1740 ?

**Comment by colesnicov** [comment]
No. It is not.

Now I look at the code and see that the class logger in the **spdlog.h** file has three constructors. The first one accepts as its argument only the 'string'

Eventually, you probably somehow must pass the object '`Sink`' into? I do not see a suitable method for this. Perhaps '`register_logger(std::shared_ptr<logger> logger)`'? This could be the answer to the ISSUE mentioned above? If I understand correctly, Sink is context?

But now that I've seen something from the source, I can see it's probably useless.

Just call `log->info("{} {}", MUJ_TAG, "Hello");`

But the problem is in the statement:
`I 02.01.2021 13:55:57 +01: 00 [ecoSDK] Hello`

But I need this:
`I [ecoSDK] 02.01.2021 14:13:25 +01: 00: Hello`

[ecoSDK] is TAG ..

But I also see the '`get(const std::string &name)`' method
which returns me a `Logger` with a preset `Sink`? And the sink will already have its specific formatter and other presets set.

As so, with the help of methods that are already available, I can put together what I need, but it seems to me like an unnecessarily inflated...

Let's say I have 30 modules and everyone has to have their own Sink for one chain only: TAG.

It's all just formatting the output.

I like this output:

`I [ecoSDK] 02.01.2021 14:13:25 +01: 00: Hello`

I = Log level
[ecoSDK] = TAG
02 ... 25 +01: 00 the date and time
Hello = message

TAG is in second place in this show and that's exactly what I need!

I don't need the whole context, just one extra string is enough.

I hope that I wrote some nonsense, and it's understandable.

**Comment by gabime** [comment]
Take a look at https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#extending-spdlog-with-your-own-flags

**Comment by colesnicov** [comment]
It's impressive.  I will probably need some time to study WIKI.  I think we can close this ISSUE for now.
