### ISSUE TITLE
How to wait for spdlog's threadpool to be idle before calling std::abort()

### ISSUE THREAD

**Issue by IAmNotHanni** [gabime/spdlog#1782]
Hello there!
First of all thank you for spdlog, it's an awesome logging lib and we enjoy using it.
How can we tell spdlog that we want to call `std::abort()` next, but we want to wait until spdlog's threadpool has finished all console/file output? So we want to wait in our thread until spdlog is idle so we can call `std::abort`.
**edit**: If we don't wait before calling std::abort, visual studio debugger will halt all threads and some spdlog output is not yet written in the console.

**Comment by gabime** [comment]
> First of all thank you for spdlog, it's an awesome logging lib and we enjoy using it.

Thanks ! 

Seems like ```spdlog:shutdown()``` is what you need.

**Comment by IAmNotHanni** [comment]
Yes that worked. Thank you very much!
