### ISSUE TITLE
Dedicated handling of std::filesystem::path objects with several new type specifiers

### ISSUE THREAD

**Issue by sebastianzander** [gabime/spdlog#1783]
Please see and label the following as a feature request _and_ a question for how to implement it myself (see below).

I am looking for a way to comfortably log ``std::filesystem::path`` objects in different ways. For example like so:

```
// working directory: /home/projects/bin/
// actual file path: /home/projects/images/cat.png
std::filesystem::path imagePath("../images/cat.png");

// regarding std::filesystem::path::string()
spdlog::info("Loading image from \"{}\"", imagePath);  // Loading image from "../images/cat.png"

// regarding std::filesystem::path::root_path()
spdlog::info("Loading image from \"{:/}\"", imagePath);  // Loading image from "/home/projects/bin/../images/cat.png"

// regarding std::filesystem::path::relative_path()
spdlog::info("Loading image from \"{:~}\"", imagePath);  // Loading image from "../images/cat.png"

// regarding std::filesystem::weakly_canonical(const std::filesystem::path&)
spdlog::info("Loading image from \"{:c}\"", imagePath);  // Loading image from "/home/projects/images/cat.png"

// regarding std::filesystem::path::filename()
spdlog::info("Loading image from \"{:f}\"", imagePath);  // Loading image from "cat.png"

// regarding std::filesystem::path::stem()
spdlog::info("Loading image from \"{:s}\"", imagePath);  // Loading image from "cat"

// regarding std::filesystem::path::parent_path()
spdlog::info("Loading from directory \"{:p}\"", imagePath);  // Loading from directory "/home/projects/images"
```

These are some type specifiers that I came up with. I am sure they would be _niche_ specifiers but effectively it saves the user either the extra `.string()` or the improper automatic string cast (with the added double quotes and escaped path separators) otherwise. The actual specifier chars are of course subject for debate.

I don't know if this functionality would be something that users may take notice of since they are probably used to accessing the respective ``std::string`` returning methods in ``std::filesystem::path``. But there are already some exotic and seldomly used type specifiers and if my proposed ones will get documented I am sure that people will use them.

If this doesn't seem like a useful addition to this library, could someone at least guide me towards the the source files where I could implement it under my own fork of spdlog? I could then offer it/create a pull request anyway.

Kind regards, 
Sebastian Zander

**Comment by gabime** [comment]
Since spdlog use fmtlib under the hood for formatting, I think this question better suited to https://github.com/fmtlib/fmt

**Comment by sebastianzander** [comment]
Thanks for the reply. I didn't know that there were third party libraries. I must have looked for git submodules only. I will have a look and post my feature request in fmtlib.

Something tangential: I just had a look into fmtlib and saw that `std::literals::chrono_literals` are supported there. I tried to compile something analogous to the following:

```
spdlog::info("{} ms", 13ms);
```

but I got this compile error:

```
Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
```

So even if fmtlib would support formatting of `std::filesystem::path` it seems that spdlog would have to separately support and implement it. Is my assumption correct?

**Comment by gabime** [comment]
> So even if fmtlib would support formatting of std::filesystem::path it seems that spdlog would have to separately support and implement it. Is my assumption correct?

Hard to say. Hopefully  not.

**Comment by tt4g** [comment]
> but I got this compile error:

I guess that your code missing `#include "spdlog/fmt/chrono.h"`.

**Comment by sebastianzander** [comment]
You are absolutely right. Silly me. I am still new to this library.
With the help of Victor Zverovich from fmtlib I was able to implement the `std::filesystem::path` type specifiers and dedicated formatting. It works flawlessly with spdlog. I really do like what spdlog has to offer.

Thank you very much for your help.

**Comment by sebastianzander** [comment]
If someone is interested in how I solved it for my project, here is a source code snippet that should be self-contained:

```
#include <spdlog/fmt/bundled/format.h>

template <>
struct fmt::formatter<std::filesystem::path>
{
    char presentation = 's';

    constexpr auto parse(format_parse_context& ctx)
    {
        auto it = ctx.begin(), end = ctx.end();
        if(it != end &&  (*it == '/' || *it == '.' || *it == 'c' || *it == 'f' || 
            *it == 's' || *it == 'n' || *it == 'p' || *it == 'e')) presentation = *it++;

        if(it != end && *it != '}')
            throw format_error("invalid format");

        return it;
    }

    template <typename FormatContext>
    auto format(const std::filesystem::path& p, FormatContext& ctx)
    {
        switch(presentation) {
        case '/': return format_to(ctx.out(), "{}", p.root_path().string());
        case '.': return format_to(ctx.out(), "{}", p.has_root_path() ? p.relative_path().string() : p.string());
        case 's': return format_to(ctx.out(), "{}", p.string());
        case 'n': return format_to(ctx.out(), "{}", p.stem().string());
        case 'f': return format_to(ctx.out(), "{}", p.filename().string());
        case 'e': return format_to(ctx.out(), "{}", p.extension().string());
        case 'c': return format_to(ctx.out(), "{}", std::filesystem::weakly_canonical(p).string());
        default:  return format_to(ctx.out(), "{}", p.string());
        }
    }
};
```

It does however not catch `std::filesystem::filesystem_error` exceptions. Whoever uses this code would have to deal with it him or herself.
