### ISSUE TITLE
Combining color settings and pattern doesn't appear to work

### ISSUE THREAD

**Issue by twarg1** [gabime/spdlog#1784]
Sorry, this is my first post so hopefully this will formatted correctly .
Running on Windows environment.  Can't output both the pattern and the colors together correctly.
If the pattern is set as default prior to creating the color_sink and log (shown in code) ...   I get the colors but **not** the full pattern.
If the pattern is set in the color_sink or log (commented out in code) ...   I get full pattern but **not** the colors.

Code as follows:

#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/fmt/bundled/color.h>

int main()
{
    const std::string pattern = "[%H:%M:%S.%f %z] [%n:%l] [%s:%#:%!] [%t] %v";
    spdlog::set_pattern(pattern);

    auto color_sink = std::make_shared < spdlog::sinks::wincolor_stdout_sink_mt >();
    // color_sink->set_pattern(pattern);
    color_sink->set_color_mode(spdlog::color_mode::always);
    color_sink->set_color(spdlog::level::trace, color_sink->WHITE);
    color_sink->set_color(spdlog::level::info, color_sink->GREEN);
    color_sink->set_color(spdlog::level::debug, color_sink->YELLOW);
    color_sink->set_color(spdlog::level::warn, color_sink->YELLOW);
    color_sink->set_color(spdlog::level::err, color_sink->RED);
    color_sink->set_color(spdlog::level::critical, color_sink->RED);

    auto log = std::make_shared<spdlog::logger>("console", color_sink);
    log->set_level(spdlog::level::trace);
    spdlog::register_logger(log);
    spdlog::set_default_logger(log);

    SPDLOG_TRACE("HELLO!");
    SPDLOG_INFO("HELLO!");
    SPDLOG_DEBUG("HELLO!");
    SPDLOG_WARN("HELLO!");
    SPDLOG_ERROR("HELLO!");
    SPDLOG_CRITICAL("HELLO!");

    return 0;
}

Thanks for your help!

**Comment by gabime** [comment]
Please see https://github.com/gabime/spdlog/wiki/0.-FAQ#colors-do-not-appear-when-using-custom-format

**Comment by twarg1** [comment]
Perfect!   Thanks so much!
