### ISSUE TITLE
spdlog 1.8.2-1 include bitset exception

### ISSUE THREAD

**Issue by huwentao** [gabime/spdlog#1789]
[Running] cd "/home/work/code/cdemo/src/" && g++ zzmj_test.cpp -o zzmj_test && "/home/work/code/cdemo/src/"zzmj_test
In file included from /usr/local/include/spdlog/fmt/fmt.h:22,
                 from /usr/local/include/spdlog/common.h:36,
                 from /usr/local/include/spdlog/spdlog.h:12,
                 from zzmj_test.cpp:14:
/usr/local/include/spdlog/fmt/bundled/core.h: In instantiation of ‘int fmt::v7::detail::check(fmt::v7::detail::unformattable) [with T = std::bitset<27>]’:
/usr/local/include/spdlog/fmt/bundled/core.h:1438:18:   required from ‘fmt::v7::detail::value<Context> fmt::v7::detail::make_arg(const T&) [with bool IS_PACKED = true; Context = fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>; fmt::v7::detail::type <anonymous> = fmt::v7::detail::type::custom_type; T = std::bitset<27>; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’
/usr/local/include/spdlog/fmt/bundled/core.h:1589:64:   required from ‘fmt::v7::format_arg_store<Context, Args>::format_arg_store(const Args& ...) [with Context = fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>; Args = {std::bitset<27>}]’
/usr/local/include/spdlog/fmt/bundled/core.h:1626:18:   required from ‘fmt::v7::format_arg_store<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<Char>, Char>, fmt::v7::remove_reference_t<Args>...> fmt::v7::make_args_checked(const S&, fmt::v7::remove_reference_t<Args>& ...) [with Args = {std::bitset<27>}; S = fmt::v7::basic_string_view<char>; Char = char]’
/usr/local/include/spdlog/fmt/bundled/format.h:3820:54:   required from ‘typename fmt::v7::buffer_context<Char>::iterator fmt::v7::format_to(fmt::v7::basic_memory_buffer<Char, SIZE>&, const S&, Args&& ...) [with S = fmt::v7::basic_string_view<char>; Args = {std::bitset<27>}; long unsigned int SIZE = 250; Char = char; typename fmt::v7::buffer_context<Char>::iterator = fmt::v7::detail::buffer_appender<char>]’
/usr/local/include/spdlog/logger.h:340:27:   required from ‘void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, const FormatString&, Args&& ...) [with FormatString = fmt::v7::basic_string_view<char>; Args = {std::bitset<27>}]’
/usr/local/include/spdlog/logger.h:87:13:   required from ‘void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {std::bitset<27>}; spdlog::string_view_t = fmt::v7::basic_string_view<char>]’
zzmj_test.cpp:207:5:   required from here
/usr/local/include/spdlog/fmt/bundled/core.h:1423:7: 错误：static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1423 |       formattable<T>(),
      |       ^~~~~~~~~~~~~~~~

[Done] exited with code=1 in 2.839 seconds

**Comment by tt4g** [comment]
As far as the error message is concerned, you have specified `std::bitset` as the argument of the log message.
spdlog uses [fmt](https://github.com/fmtlib/fmt) to format log messages, but it cannot be compiled because fmt does not support converting `std::bitset` to a string.

Go to https://fmt.dev/latest/api.html#udt provided in the error message and add `std::bitset` formatter.

Another way is to add `#include "spdlog/fmt/ostr.h"` and format it with the `std::bitset` output operator (`operator<<(std::basic_ostream&, const std::bistset&)`).
