### ISSUE TITLE
Cmake build failed with v140_xp, v141_xp toolset flags

### ISSUE THREAD

**Issue by wwriter** [gabime/spdlog#1790]
First of all, thank you for providing and maintaining this nice library.
I am posting this to ask if there's some way to build spdlog with `_xp` toolset flag.

When I use this script to build spdlog
``` sh
cmake -T v141_xp (or v140_xp) ... (other flags) ..
cmake --build . --config Debug (or Release)
```

I got this error message.
```
stdout_sink-inl.h (18) fileapi.h : no such file or directory
```
So I opened the inl file and found these lines.
``` cpp
#ifdef _WIN32
// under windows using fwrite to non-binary stream results in \r\r\n (see issue #1675)
// so instead we use ::FileWrite
#include <spdlog/details/windows_include.h>
#include <fileapi.h> // WriteFile (..) //< ******this seemed to cause the error*******
#include <io.h>      // _get_osfhandle(..)
#include <stdio.h>   // _fileno(..)
#endif               // WIN32
```
After doing some tests, I figured out that one cannot include `fileapi.h` when the version of Windows SDK for the project is set to 7.
Then I changed the code somewhat like this and was able to get the lib file.
``` cpp
#ifdef _WIN32
// ... 
#ifndef _USING_V110_SDK71_
#include <fileapi.h> // WriteFile (..) //< ******this seemed to cause the error*******
#endif
// ...
#endif               // WIN32
```

My question is, is there any flag or option that I can set to build a lib for Windows xp?

**Comment by gabime** [comment]
No, WinXP is not supported.

**Comment by wwriter** [comment]
I thought it might support windows xp because earlier today, I found some questions about crashes on windows xp or whatnot.
Anyway, thanks for your quick response !

**Comment by swex** [comment]
@wwriter If you just remove `#include fileapi.h` it would compile and work just ok.
btw @gabime why windows xp is not supported anyway?

**Comment by gabime** [comment]
It didn't compile cleanly and I have no time to support it.
Prs are welcome to make it work.
