### ISSUE TITLE
static initialization order for level_string_views

### ISSUE THREAD

**Issue by gv-me** [gabime/spdlog#1791]
In file common-inl.h level names are defined as `string_view`s. The declarations can be made `constexpr` so they are always initialized at start of the program.

Currently, any logs created before entering `main()` or even any operations dealing with level names like loading levels from env variables cannot be performed reliably before entering `main()` function of the program. Depending on the static initialization order, sometimes level names might not be present at the time.

For `constexpr` declaration of `level_string_views` only minor changes are needed. I can submit a PR if that is preferred.

**Comment by gabime** [comment]
Sounds good. Thanks. 

Keep in mind this should still compile in c++11

**Comment by gcerretani** [comment]
Are there reliable solutions for C++14? I'm developing a shared library using spdlog, and I would like to reliably invoke `spdlog::cfg::load_env_levels()` from a function marked as `__attribute__((constructor))`. The constexpr solution has no impact on C++14, right?

**Comment by gcerretani** [comment]
Seems that the problem is solved also with C++14 using the x1.x branch since commit 68aed6a5ebf55aecc67351513ad4aea3e38dc7d9, but I can't find any workdaround for 1.8.5.
