### ISSUE TITLE
How to create async logger manually?

### ISSUE THREAD

**Issue by repu1sion** [gabime/spdlog#1792]
I need to create async logger manually, but from docs or API just don't see the way to do it.
Things like these don't work:
`auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(pathname);`
` auto logger = std::make_shared<spdlog::create_async>(str, sink);		//<-- error: no matching function for call`

Also it doesn't work in another way:
`auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(pathname);`	
`auto logger = std::make_shared<spdlog::async_logger>(str, sink);            //<-- error: no matching function for call to` `‘spdlog::async_logger::async_logger`

Any correct way to do so?

**Comment by tt4g** [comment]
Try it (https://github.com/gabime/spdlog/wiki/6.-Asynchronous-logging#construct-directly-and-use-the-global-thread-pool):

```diff
auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(pathname);
- auto logger = std::make_shared<spdlog::create_async>(str, sink);
+ spdlog::init_thread_pool(1024, 1);
+ auto logger = std::make_shared<spdlog::create_async>(str, sink, spdlog::thread_pool(), async_overflow_policy::block); 
```

**Comment by repu1sion** [comment]
```
error: no matching function for call to ‘make_shared<spdlog::create_async>(std::__cxx11::string&, std::shared_ptr<spdlog::sinks::basic_file_sink<std::mutex> >&, std::shared_ptr<spdlog::details::thread_pool>, spdlog::async_overflow_policy)’
    auto logger = std::make_shared<spdlog::create_async>(str, sink, spdlog::thread_pool(), spdlog::async_overflow_policy::block);
```

**Comment by tt4g** [comment]
I'm sorry. `std::make_shared<spdlog::async_logger>()` is correct.

```diff
auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(pathname);
- auto logger = std::make_shared<spdlog::create_async>(str, sink);
+ spdlog::init_thread_pool(1024, 1);
+ auto logger = std::make_shared<spdlog::async_logger>(str, sink, spdlog::thread_pool(), async_overflow_policy::block); 
```

**Comment by repu1sion** [comment]
thanks, I also figured out this way by myself after lots of bad tries. it really helps.
