### ISSUE TITLE
getting a list of currently registered loggers and their currently set log level

### ISSUE THREAD

**Issue by p0fi** [gabime/spdlog#180]
Is it somehow possible to get a list of all registered loggers and their current log level?

**Comment by gabime** [comment]
no. the map is a private member in the registry class

**Comment by MartinThoma** [comment]
`logging.Logger.manager.loggerDict`

**Comment by WarShoe** [comment]
I have a similar need. To get the list of all loggers I tried to use 
```
spdlog::details::registry::instance().apply_all( [] (auto x) {
		fmt::print("{}\n",x.name());
	});
```

but of course "name()" does not exist and "_name" is protected. Now I need to write my own loggers registry code...

**Comment by ianragudo** [comment]
I believe the current code already allows to get the logger name https://github.com/gabime/spdlog/blob/1f5f17622ed2c01831337cef72e17c0d8985993d/include/spdlog/logger.h#L317

**Comment by mfinean** [comment]
> if you change x.name() to x->name() then it will work because x is a shared pointer.
