### ISSUE TITLE
log output from multiple executable skew the format

### ISSUE THREAD

**Issue by danieleTrimarchi** [gabime/spdlog#1801]
I have a simple test executable (attached) that I launch twice from the same terminal (for instance, I use python as a launcher). Of course this is only a simplified example of my framework. 

As soon as the two logger start concurrently writing to the cmd window, the format is skewed (in the screen shot below, the whole log ends up green, but depending on the output concurrency we can end up with funny colors all over the place).
 
Can you suggest a way to improve this situation ? 

![image](https://user-images.githubusercontent.com/24756418/104456138-88a03700-55a8-11eb-9a1c-29be9e4d8106.png)
[spdLoggerTest.cpp.txt](https://github.com/gabime/spdlog/files/5808737/spdLoggerTest.cpp.txt)
[launchMultiple.py.txt](https://github.com/gabime/spdlog/files/5808740/launchMultiple.py.txt)

**Comment by gabime** [comment]
Not sure there is an easy way to synchronize ouput from different executables. There is no support for this in spdlog anyway

**Comment by danieleTrimarchi** [comment]
ok thanks. 
Please reject this issue if this is not intended to be in spdlog in any foreseeable future. 
Thanks

**Comment by gabime** [comment]
Ok. But feel free to update if you find a solution for this.
