### ISSUE TITLE
Macro expansion which converts Google Logger print format(i.e. <<) to spdlog print format

### ISSUE THREAD

**Issue by MaximAxelrod** [gabime/spdlog#1804]
I have tons of code which uses Google Logger style of log printing: 
`LOG(ERROR) << "AAAA" <<< 123;`

And currently I need to replace Google logger by spdlog logger, which supports python like format: 
`logger->error("{} {}", "param1", 123);`

Of course I don't want to change each log line in the code. What I am trying to do, is to rewrite LOG(severity) macro definition. The original macro implementation is: 
`#define LOG(severity) COMPACT_GOOGLE_LOG_ ## severity.stream()`

Can you please recommend me how should I implement the macro? My idea was that the original arguments that were passed to LOG(ERROR) (i.e. << "AAAA" <<< 123) should be printed to a string buffer(str_buffer), and the string buffer will be printed to the destination spdlog logger instance like this: `logger->error("{}", str_buffer.c_str());`

What is the best idea for doing this? Thanks so much!!!

**Comment by artemyv** [comment]
I did it like this
#define SPDLOG_LOGGER_STREAM(log, lvl)                                                                   \
    log && log->should_log(lvl) &&                                                                       \
        LogStream(log, lvl, spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}) == \
            LogLine()

LogLine class implements operator<< and stores everything on the right into internal stringstream bugger
LogStream class implements operator==(const LogLine& line) which retrieves the content of LogLine internal buffer and outputs it to logger

**Comment by artemyv** [comment]
Here is the very basic demo of the approach https://github.com/artemyv/cmake_spdlog_example/tree/main/src

**Comment by MaximAxelrod** [comment]
Than you very much

**Comment by tangm421** [comment]
> Here is the very basic demo of the approach https://github.com/artemyv/cmake_spdlog_example/tree/main/src

👍 excellent way. Unfortunately, streaming output like `std::endl` cannot be supported

**Comment by gabime** [comment]
Also, I would replace the [shared_ptr](https://github.com/artemyv/cmake_spdlog_example/blob/231f58104c231d6932ff7d25ec5a65b4587a864e/src/logger.h#L19)  with regular pointer to logger for better performance since it get copied/destroyed in macro each call.

**Comment by tangm421** [comment]
> Here is the very basic demo of the approach https://github.com/artemyv/cmake_spdlog_example/tree/main/src

Not sure if this way is thread safe

**Comment by artemyv** [comment]
LogStream variable instance is created locally inside the function - so you should not have any threading issues with it

**Comment by gabime** [comment]
I thinks the line

```cpp
 m_log->log(m_loc, m_lvl, "{}", line.str());  
```
can be optimized to

```cpp
  m_log->log(m_loc, m_lvl, line.str());  // skip formatting by logging the string directly
```

**Comment by BullyWiiPlaza** [comment]
It seems like the provided code only compiles using gcc and not on MSVC. The following code is more straight-forward for providing streaming functionality and it compiles on both compilers:

```
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/spdlog.h>
#include <sstream>

class streamable_logger_t {
    spdlog::level::level_enum log_level_;
    std::ostringstream log_stream_;

public:
    explicit streamable_logger_t(const spdlog::level::level_enum log_level)
        : log_level_(log_level) {
	    
    }

    template <typename T>
    streamable_logger_t& operator<<(const T& value) {
        log_stream_ << value;
        return *this;
    }

    ~streamable_logger_t() {
        spdlog::log(log_level_, "{}", log_stream_.str());
    }
};

/* Might cause macro redefinition errors, you can comment them out if needed */
// #define INFO info
// #define WARNING warn
// #define ERROR err

// loguru
#define LOG_S(log_level) streamable_logger_t(spdlog::level::log_level)

// glog
#define LOG(log_level) LOG_S(log_level)

int main() {
    set_default_logger(spdlog::stdout_color_mt("console"));

    LOG_S(info) << "This is an info message: " << 42;
    LOG_S(err) << "This is an error message.";

    LOG(info) << "This is an info message: " << 42;
    LOG(err) << "This is an error message.";

    return EXIT_SUCCESS;
}
```
Maybe someone will find it useful.

**Comment by gabime** [comment]
Thanks @BullyWiiPlaza. This is indeed useful.
