### ISSUE TITLE
There is an error running on winxp

### ISSUE THREAD

**Issue by munitioner** [gabime/spdlog#1808]
After my win32 program is compiled and run on winxp, it prompts an error, the check is because of the spdlog error
![微信截图_20210121140534](https://user-images.githubusercontent.com/14157458/105286729-d8f34680-5bf1-11eb-83b1-81c4f33beda0.png)

**Comment by tt4g** [comment]
There is a solution that has been provided: https://github.com/gabime/spdlog/issues/404#issuecomment-289755761

**Comment by munitioner** [comment]
thank you for your reply，this solved my question. but will this affect the function of spdlog?

**Comment by munitioner** [comment]
> There is a solution that has been provided: [#404 (comment)](https://github.com/gabime/spdlog/issues/404#issuecomment-289755761)
> 
> https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/details/os-inl.h#L256-L263

thank you for your reply，this solved my question. but will this affect the function of spdlog?

**Comment by tt4g** [comment]
The function is for getting the time zone offset. may cause a shift in the log time and rotation time.
