### ISSUE TITLE
spdlog crashed on drop_all()

### ISSUE THREAD

**Issue by yzhgu** [gabime/spdlog#1809]
I have a spdlog wrapper (win10+vs2015) to write log to different file by each thread. Part of the code is as follows:
```
//.h
#pragma once
namespace MyLog
{
enum LogLevel
{
  trace, debug, info, warn, error, critic, off, nLevel
};
}
#define LOG_TRACE(fmt, ...)  cSLog::GetInstance().stdlogfmt(MyLog::trace,  fmt, ##__VA_ARGS__)
#define LOG_DEBUG(fmt, ...)  cSLog::GetInstance().stdlogfmt(MyLog::debug,  fmt, ##__VA_ARGS__)
#define LOG_INFO(fmt, ...)   cSLog::GetInstance().stdlogfmt(MyLog::info,   fmt, ##__VA_ARGS__)
#define LOG_WARN(fmt, ...)   cSLog::GetInstance().stdlogfmt(MyLog::warn,   fmt, ##__VA_ARGS__)
#define LOG_ERROR(fmt, ...)  cSLog::GetInstance().stdlogfmt(MyLog::error,  fmt, ##__VA_ARGS__)
#define LOG_CRITIC(fmt, ...) cSLog::GetInstance().stdlogfmt(MyLog::critic, fmt, ##__VA_ARGS__)

class cSLog
{
public:
  static cSLog& GetInstance()
  {
    static cSLog m_instance;
    return m_instance;
  }
  void setLogger(const std::string& FullFileName,  const int TraceLevelFile=0);
  bool stdlogfmt(const MyLog::LogLevel severity, const char *fmt, ...);

  void setMinLogLevel(const MyLog::LogLevel loglevelF, const MyLog::LogLevel loglevelC = MyLog::warn);

private:
  cSLog();
  ~cSLog();

  void setTrace(const bool bTrace) { m_bTrace = bTrace; };
  void setMaxFileSize(const int sizeMB) { m_MaxFileSize = sizeMB; };
  void setMaxFileNum(const int fileNum) { m_MaxFileNum = fileNum; };

  cSLog(const cSLog&) = delete;            // Delete the copy constructor 
  cSLog& operator=(const cSLog&) = delete; // Delete the copy assignment operator 

private:
  std::map<std::string, int> m_MapTraceLevelFile;
  std::map<std::string, std::string> m_MapStdFileName;

  int  m_MaxFileSize;
  int  m_MaxFileNum;
  std::mutex mtx;
};

//cpp
cSLog::cSLog()
  :m_MaxFileSize(2),  //2 mb
   m_MaxFileNum(100){}

cSLog::~cSLog(){
  m_MapTraceLevelFile.clear();
  spd::shutdown();
}

void cSLog::setLogger(const std::string& FullFileName, const int TraceLevelFile)
{
  std::lock_guard<std::mutex> lck(mtx);
  std::string strPID = StringUtil::getPidString();

  m_MapTraceLevelFile[strPID]    = TraceLevelFile;
  m_MapStdFileName[strPID]       = FullFileName;

  std::string filePath = DirFileUtil::getPath(FullFileName);
  if (!DirFileUtil::isDirExists(filePath))
    DirFileUtil::createDir(filePath);

  try
  {
    std::string strFileLogger = stdLoggerName + strPID;
    if (nullptr == spd::get(strFileLogger))
    {
      auto stdfileLogger = spdlog::create<dateonly_daily_file_sink_mt>(strFileLogger, FullFileName, 0, 0);
      stdfileLogger->set_level(spd::level::level_enum(m_MapTraceLevelFile[strPID]));
      stdfileLogger->set_pattern(defaultPattern);
    }
    return;
  }
  catch (const spd::spdlog_ex& ex) {
    std::cerr << "setLogger failed: " << ex.what() << std::endl;
  }
}

bool cSLog::stdlogfmt(const MyLog::LogLevel severity, const char *fmt, .../*const std::string msg*/)
{
try
  {
    std::string strPID = StringUtil::getPidString();
    auto stdlogger     = spd::get(stdLoggerName + strPID);

    if(stdlogger == nullptr) return false;
 
    char sprint_buf[2048] = { 0 };
    va_list args;
    int n;
    va_start(args, fmt);
    n = vsprintf(sprint_buf, fmt, args);
    va_end(args);

    std::string msgloc(sprint_buf);
    switch (severity)
    {
    case MyLog::trace:
        stdlogger->trace(msgloc);
        break;
    case MyLog::debug:
        stdlogger->debug(msgloc);
        break;
    case MyLog::info:
        stdlogger->info(msgloc);
        break;
    case MyLog::warn:
        stdlogger->warn(msgloc);
       break;
    case MyLog::error:
        stdlogger->error(msgloc);
        break;
    case MyLog::critic:
        stdlogger->critical(msgloc);
        break;
    default:
      break;
    }

    stdlogger->flush();
    return true;
  }
catch (const spd::spdlog_ex& ex) {
  std::cerr << "stdlog failed: " << ex.what() << std::endl;
}
  return false;
}

```
To use the logger, I just call cSLog::GetInstance().setLogger(...) once, and call LOG_TRACE/DEBUG/INFO/WARN...
The logger works fine, the crash happens at **loggers_.clear()** in funtion **registry::drop_all()** on exit:
**Unhandled exception at 0x004B92E7 in ThreadTest.exe: 0xC0000005: Access violation reading location 0xDDDDDDDD.**
and I can see the vector loggers_ is empty actually.

Why could this be? **Should I explicit call spd::shutdown() or drop_all() in deconstructor?**

**Comment by tt4g** [comment]
In my experience, Windows will cause an access violation if do not call `spdlog::shutdown()` before exiting the `main()`.

**Comment by yzhgu** [comment]
In my case the situation is just the opposite. Why the access violation happens on calling spdlog::shutdown()?

**Comment by tt4g** [comment]
No, I think `spdlog::shutdown()` is called after `main()`.
This is because `cSLog` is declared as a `static` local variable.

Quotes from the [Destructors \- cppreference\.com](https://en.cppreference.com/w/cpp/language/destructor):

> The destructor is called whenever an object's lifetime ends, which includes
> * program termination, for objects with static storage duration

Therefore, the Visual Studio compiler calls `~cSLog()` at the timing when the program is terminated after `main()`.

To work around the problem, change it to `static std::unique_ptr<sClog> m_instance = std::make_unique<sClog>();` and add a cleanup function that calls `m_instance.clear()`.
The cleanup function should be called just before the end of `main()`.

**Comment by yzhgu** [comment]
> 
> 
> No, I think `spdlog::shutdown()` is called after `main()`.
> This is because `cSLog` is declared as a `static` local variable.
> 
> Quotes from the [Destructors - cppreference.com](https://en.cppreference.com/w/cpp/language/destructor):
> 
> > The destructor is called whenever an object's lifetime ends, which includes
> > 
> > * program termination, for objects with static storage duration
> 
> Therefore, the Visual Studio compiler calls `~cSLog()` at the timing when the program is terminated after `main()`.
> 
> To work around the problem, change it to `static std::unique_ptr<sClog> m_instance = std::make_unique<sClog>();` and add a cleanup function that calls `m_instance.clear()`.
> The cleanup function should be called just before the end of `main()`.

Thx a lot, it works.

**Comment by hwangwenchao** [comment]
After my testing, I found that creating a logger (setLogger) in the constructor (cSlog) and calling drop in the destructor (~cSlog) will not cause a crash. What is the reason for this please？

**Comment by pgj007** [comment]
> After my testing, I found that creating a logger (setLogger) in the constructor (cSlog) and calling drop in the destructor (~cSlog) will not cause a crash. What is the reason for this please？



> After my testing, I found that creating a logger (setLogger) in the constructor (cSlog) and calling drop in the destructor (~cSlog) will not cause a crash. What is the reason for this please？

I don't know why no one answered this question, this problem I also encountered, I studied for a long time, I should be the details of the memory destructor sequence caused. In fact, without asynchrony, the "shutdown" call is unnecessary, and the "RAII" feature frees up all memory resources.

**Comment by pgj007** [comment]
> After my testing, I found that creating a logger (setLogger) in the constructor (cSlog) and calling drop in the destructor (~cSlog) will not cause a crash. What is the reason for this please？

I don't know why no one answered this question, this problem I also encountered, I studied for a long time, I should be the details of the memory destructor sequence caused. In fact, without asynchrony, the "shutdown" call is unnecessary, and the "RAII" feature frees up all memory resources.
