### ISSUE TITLE
Multi-thread logging performance improvement by avoiding formatter lock

### ISSUE THREAD

**Issue by WenbinHou** [gabime/spdlog#1810]
I noticed the performance is relatively low when multiple threads write to the same sink. 

After some inspection, I found the threads contended on mutex_ in base_sink, and pattern_formatter does the formatting inside critical section.

I simply tried to move the formatting outside the lock, and the performance doubled. 

Is there any plan to improve this?

**Comment by gabime** [comment]
Thanks for the suggestion. Since pattern formatter needs a lock(has internal state) I doubt we can just remove it outside the lock.
