### ISSUE TITLE
call to non-constexpr function

### ISSUE THREAD

**Issue by 854768750** [gabime/spdlog#1811]
After I pull the latest spdlog and recompile it, my code cannot compile.
`/opt/spdlog/include/spdlog/common-inl.h:16:43: error: call to non-constexpr function 'fmt::v7::basic_string_view<Char>::basic_string_view(const Char*) [with Char = char]' static string_view_t level_string_views[] SPDLOG_LEVEL_NAMES;`

And I checkout to the commit before #1798, there is no error. Does this pull request cause the problem? @gv-me 
Even something like `logger->info("{0}",idx);` connot pass the compilation where `idx` is an int.

**Comment by gv-me** [comment]
are you using C++11 or older? And are you using compiled or header only version or spdlog? Please give the full error output.

**Comment by 854768750** [comment]
change the #if __cplusplus >= 201402L at line 13 in common-inl.h to #if __cplusplus >= 201703L works. Thank you.

**Comment by 854768750** [comment]
change the `#if __cplusplus >= 201402L` at line 13 in common-inl.h to `#if __cplusplus >= 201703L` works.
