### ISSUE TITLE
widechar usage question

### ISSUE THREAD

**Issue by vpopescu** [gabime/spdlog#1812]
New user, I'm stuck at this little issue. Hoping someone can shed some light:

```
std::wstring w = L"HI";
logger->warn(w);

or..

logger->warn(L"HI");
```

results in:
```
...\spdlog\include\spdlog\fmt\bundled\core.h(1159,55): error C2338: mixing character types is disallowed
```

of course, this works fine:

```
std::string w = "HI";
logger->warn(w);
```

Can someone clarify what that message is telling me? I'm not mixing any types. Do i need to do something specific when I create the logger instance, maybe? I'd be happy to log widechar only. Appologies if I'm missing something basic, but I did try to find the information in the logs or in old issues.

(Windows, vs 2019, C++17 enabled)

**Comment by tt4g** [comment]
Define `SPDLOG_WCHAR_FILENAMES` macro for enable `wchar_t` support.

https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/tweakme.h#L49-L53

**Comment by vpopescu** [comment]
Thank you. Will close.

**Comment by vpopescu** [comment]
Actually that is for file names (I'm just using the console logger). But I will go through the tweakme.h and see what else is appropriate to fix the issue.

**Comment by vpopescu** [comment]
OK, i turned that on, and also:

``
///////////////////////////////////////////////////////////////////////////////
// Uncomment to enable wchar_t support (convert to utf8)
//
#define SPDLOG_WCHAR_TO_UTF8_SUPPORT
///////////////////////////////////////////////////////////////////////////////
```
