### ISSUE TITLE
Install cmake project which uses spdlog, misses fmt.dll

### ISSUE THREAD

**Issue by Luke-Filewalker** [gabime/spdlog#1814]
When I try to install a cmake project which depends on spdlog, the fmt.dll is not copied to the install dir. What can I do do solve this?

btw using vcpkg spdlog

**Comment by gabime** [comment]
It is probably a vcpkg issue. Please open the issue there.

**Comment by Luke-Filewalker** [comment]
But when building with visual studio it works, it copies the fmt.dll to the bin directory

**Comment by tt4g** [comment]
The CMake script of spdlog does not generate `fmt.dll`.
I guess that Visual Studio (or vcpkg) generates `fmt.dll`.
