### ISSUE TITLE
spdlog::flush_every in multi-thread, and log level issue

### ISSUE THREAD

**Issue by yzhgu** [gabime/spdlog#1815]
Question 1:
I made a spdlog wrapper, which contains two loggers, each logger has file_sink and console_sink:
```
      auto file_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>(FullFileName, 0, 0, false, 0);
      file_sink->set_level(spdlog::level::level_enum(LevelF));
      file_sink->set_pattern(defaultPattern);
      std::vector<spdlog::sink_ptr> sinks{ file_sink };
      if(bLogToConsole)
      {
        auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        console_sink->set_level(spdlog::level::level_enum(LevelC));
        console_sink->set_pattern(defaultPattern);
        sinks.push_back(console_sink);
        if(LevelC < LevelF)
          iloglevel = LevelC;
      }
      auto logger = std::make_shared<spdlog::logger>(strFileLogger, sinks.begin(), sinks.end());
      logger->set_level(spdlog::level::level_enum(iloglevel));
      spdlog::register_logger(logger);

// here create another logger and register it, the same as the first logger created above

      spdlog::flush_every(std::chrono::seconds(3));
```
It works fine in single thread mode. How ever in mt mode, the log file only has log message during startup and rundown (I guess because spdlog::apply_all([&](std::shared_ptr<spdlog::logger> l) {l->flush(); }) is called in rundown ).
Am I missing any steps？

Question 2:
Is it right to set the logger level as the minimum log level of the sinks? I tested a lot, and found only in this case I got the result as what I want.

**Comment by tt4g** [comment]
> Question 1

`spdlog::flush_every()` performs flush operations periodically, but does not flush the log that was left before the application exits.

You should call `spdlog::shutdown()` before the application exits.

> Question 2:

Loggers and sinks are filtered by log level in that order.
If you want to pass all messages from the logger to the sink, set the logger to a lower log level than the sink.

**Comment by yzhgu** [comment]
Many thx!
