### ISSUE TITLE
After the program ends abnormally, start again, spdlog cannot write logs

### ISSUE THREAD

**Issue by munitioner** [gabime/spdlog#1816]
When my program is running, I restart the computer and the program runs again, but spdlog can no longer write logs. When my program is closed normally, open the program again, spdlog can write logs normally.

**Comment by tt4g** [comment]
Are there any processes remaining from before the reboot?
Use Process Explorer to check the status after the reboot.

**Comment by munitioner** [comment]
> 重新启动之前还有剩余的进程吗？
> 重新启动后，使用Process Explorer检查状态。

My program starts automatically after booting, and the program will start automatically after the computer restarts

**Comment by tt4g** [comment]
Are you writing logs to a file?
If so, do you specify the log file as an absolute path?

**Comment by munitioner** [comment]
> Are you writing logs to a file?
> If so, do you specify the log file as an absolute path?
系统重启的时候不确定是否正在将日志写入文件，日志文件是绝对路径，和程序在一个目录下

**Comment by tt4g** [comment]
If the logs are written to a file when you run the application manually, then Windows is probably the cause.
See if there is a difference between running it manually and starting it automatically.
For example, who is the owner of the process when it is run automatically?

By the way.
If your application writes files other than spdlog, are those files being written successfully?

**Comment by munitioner** [comment]
> 如果在手动运行应用程序时将日志写入文件，则可能是Windows。
> 查看手动运行和自动启动之间是否有区别。
> 例如，当进程自动运行时，谁是该进程的所有者？
> 
> 顺便说说。
> 如果您的应用程序写了spdlog以外的文件，这些文件是否被成功写了？

![微信截图_20210208104720](https://user-images.githubusercontent.com/14157458/107170417-3a415500-69fb-11eb-8f17-4a90200e3ff3.png)
当我的程序正在运行，我重启电脑后，会报这样的错误。但是当我的程序正常关闭，再次启动后则不会报这样的错误。

**Comment by tt4g** [comment]
It looks like you are trying to open a log file with a relative path.
When it is a relative path, the file will be created in the working directory.
In most cases, the working directory for processes started by Windows automatically starts is the system directory (e.g. `C:\Windows\System32`).

Please specify an absolute path.

**Comment by munitioner** [comment]
> It looks like you are trying to open a log file with a relative path.
> When it is a relative path, the file will be created in the working directory.
> In most cases, the working directory for processes started by Windows automatically starts is the system directory (e.g. `C:\Windows\System32`).
> 
> Please specify an absolute path.
![微信截图_20210208113604](https://user-images.githubusercontent.com/14157458/107173054-dec69580-6a01-11eb-9729-76cb462592aa.png)
是将spdlog::daily_logger_mt中的路径设置为绝对路径？

**Comment by munitioner** [comment]
> > It looks like you are trying to open a log file with a relative path.
> > When it is a relative path, the file will be created in the working directory.
> > In most cases, the working directory for processes started by Windows automatically starts is the system directory (e.g. `C:\Windows\System32`).
> > Please specify an absolute path.
> > ![微信截图_20210208113604](https://user-images.githubusercontent.com/14157458/107173054-dec69580-6a01-11eb-9729-76cb462592aa.png)
> > 是将spdlog::daily_logger_mt中的路径设置为绝对路径？

感谢你的回复，我已经解决了这个问题，就是应该将路径设置为绝对路径，再次感谢！
