### ISSUE TITLE
Debug logs not being displayed even after calling set_level(level::debug)

### ISSUE THREAD

**Issue by Iscle** [gabime/spdlog#1820]
As the title says, I can't get debug logs to show on the command line.

Info logs are displayed correctly, but debug logs are not. The library is build with CMake as a static lib.

The following is the log output:
```
[2021-02-05 22:01:11.094] [info] librespot_cpp.cpp:16 - Welcome to librespot-c++!
[2021-02-05 22:01:11.095] [info] zeroconf.cpp:38 - Starting zeroconf server at port 10374
[2021-02-05 22:01:12.256] [info] zeroconf.cpp:43 - getInfo requested from 192.168.1.58:65135
```

The first log entry is being made right after the set_debug function call. Then, just after that one, a debug log should be printed, but it's not. The code can be found here: https://github.com/Iscle/librespot-cpp/blob/ae7955067a682db5cf01951268613a80d2e5ffe5/src/librespot_cpp.cpp#L18

Also, the last log line is printed right after a call to SPDLOG_DEBUG and right before another call to SPDLOG_DEBUG. As you can see, neither debug calls take any effect. The code for the last entry is here: https://github.com/Iscle/librespot-cpp/blob/ae7955067a682db5cf01951268613a80d2e5ffe5/src/network/zeroconf.cpp#L42

I have read through the documentation and nothing else is mentioned about switching to debug mode. It's a really strange issue.

Any clue as to what might be happening?

Thanks!

EDIT: I have tried it with spdlog::debug and it does work, but not with SPDLOG_DEBUG. In my code I'm using the macro as I need to print the file name and line number.

**Comment by tt4g** [comment]
Missing define `SPDLOG_ACTIVE_LEVEL` macro.
Add `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG` in your code.

Wiki: https://github.com/gabime/spdlog/wiki/1.-QuickStart#logging-macros

https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/tweakme.h#L102-L107

**Comment by Iscle** [comment]
Oops! I missed that one...

Thanks, it works perfectly now!
