### ISSUE TITLE
Infinite loop in rotating_file_sink_mt?

### ISSUE THREAD

**Issue by vpopescu** [gabime/spdlog#1821]
Not sure if I'm doing something wrong.. I managed to create a logic loop in my program, or ran into a bug.  It comes down to this piece of code in rotating_file_sink-inl.h:

```
    for (auto i = max_files_; i > 0; --i)
    {
        filename_t src = calc_filename(base_filename_, i - 1);
        if (!path_exists(src))
        {
            continue;
        }
        filename_t target = calc_filename(base_filename_, i);
```

I think this is trying to find the next available number?

In my case, the directory is empty. Since the 'path_exists(src) == false', it 'continues'.  Should it actually be continuing if the loop is "path_exists(src) == true" ? I'm sitting in the debugger and my 'i' value is ever decreasing and rolling over.

Also since the 'auto' ends up being a size_t, it's forever positive, so the "i > 0" check is always true.

**Comment by gabime** [comment]
> Also since the 'auto' ends up being a size_t, it's forever positive

Not sure I understand. size_t will reach zero at some point.

**Comment by vpopescu** [comment]
You are correct, sorry, I misread the line. 

I think I found my issue, I had the two parameters (size and number of files) reversed. Compiler wasn't much help in catching me on that one! :)   Rookie mistake, I know. I will close this. I am not sure why that caused an infinite loop, it may have just been a slow finite loop.
