### ISSUE TITLE
std::format compatible version of spdlog

### ISSUE THREAD

**Issue by skannan89** [gabime/spdlog#1822]
Hello! Love using your library. spdlog bundles fmt library in it's source code, right? Are there any plans for a C++ 20 std::format only version of spdlog? 

Thank you.

**Comment by gabime** [comment]
Good idea  however splog uses some fmt functions and classes that are not in the standard(e.g. fmt::basic_memory_buffer).

**Comment by skannan89** [comment]
> Good idea however splog uses some fmt functions and classes that are not in the standard(e.g. fmt::basic_memory_buffer).

Thanks for your quick response. I understand, created this issue to see if it would be worthwhile to have a separate std::format version of spdlog. Please feel free to close this issue.
