### ISSUE TITLE
Warning flags are getting propagated

### ISSUE THREAD

**Issue by prateek9623** [gabime/spdlog#1825]
The shared library of spdlog is propagating MSVC warning flags, which is creating issues while compiling my CUDA based application as NVCC don't play well with MSVC warning flags.

So, can we make this PRIVATE

https://github.com/gabime/spdlog/blob/ff6e3c95f2dc038c19e220afce1d045137b1cb24/CMakeLists.txt#L134-L136

Environment
OS: Windows
Compiler: MSVC(14.28.29333), NVCC 11.2

To Reproduce
link with CUDA based application using vcpkg

Expected behavior
the warning should not propagate from spdlog

**Comment by gabime** [comment]
I think making it private would cause warnings for users of spdlog through include, but not sure.

**Comment by prateek9623** [comment]
@gabime  I didn't understand, are you saying about spdlog_header_only?

**Comment by gabime** [comment]
No. About users getting the warnings after including spdlog.h if the warning suppression is made private

**Comment by prateek9623** [comment]
ya, it will, but it also prevents in their codebase also. Which is a risk for them. As this warning suppression is not just for spdlog if it is public.

**Comment by gabime** [comment]
I dont see an easy solution for this. If the made private there will be complains about new warnings that suddenly appear.

**Comment by prateek9623** [comment]
If not private can we do something like this:
`
set(PROJECT_WARNINGS /wd4251 /wd4275)
 target_compile_options(${project_name} INTERFACE 
    $<$<COMPILE_LANGUAGE:C>:${PROJECT_WARNINGS}> 
    $<$<COMPILE_LANGUAGE:CXX>:${PROJECT_WARNINGS}>
  )
`

**Comment by tt4g** [comment]
I think we can add an option when the "compiler is MSVC, not CUDA".

```cmake
target_compile_options(${project_name} INTERFACE
  $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<NOT:$<CXX_COMPILER_ID:NVIDIA>>>:/wd4251 /wd4275>)
```

**Comment by prateek9623** [comment]
> I think we can add an option when the "compiler is MSVC, not CUDA".
> 
> ```cmake
> target_compile_options(${project_name} INTERFACE
>   $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<NOT:$<CXX_COMPILER_ID:NVIDIA>>>:/wd4251 /wd4275>)
> ```
> 
> `CMAKE_ <LANG> _COMPILER_ID` list: https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html

I think this would also work

**Comment by prateek9623** [comment]
> I think we can add an option when the "compiler is MSVC, not CUDA".
> 
> ```cmake
> target_compile_options(${project_name} INTERFACE
>   $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<NOT:$<CXX_COMPILER_ID:NVIDIA>>>:/wd4251 /wd4275>)
> ```
> 
> `CMAKE_ <LANG> _COMPILER_ID` list: https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html

this wouldn't work I think as CMAKE_ <LANG> _COMPILER_ID cant be multiple values

**Comment by prateek9623** [comment]
```cmake
set(PROJECT_WARNINGS /wd4251 /wd4275)
target_compile_options(spdlog PUBLIC $<AND:$<CXX_COMPILER_ID:MSVC>, 
$<NOT:$<COMPILE_LANGUAGE:CUDA>>>:${PROJECT_WARNINGS}> )
```
I think this is a more elegant solution, "compiler is MSVC and language is not CUDA"

**Comment by prateek9623** [comment]
@gabime any comment on this?

**Comment by gabime** [comment]
If this fixes your problem, please issue a pr.

**Comment by prateek9623** [comment]
@gabime when should i expect this fix to reflect in vcpkg

**Comment by tt4g** [comment]
We do not maintain vcpkg.
Please wait for the vcpkg maintainer's response (microsoft/vcpkg#16153) or send a pull request.
