### ISSUE TITLE
Give access the whole range of syslog log levels

### ISSUE THREAD

**Issue by ambre-m** [gabime/spdlog#1826]
Syslog uses a few more log levels that can't be emitted in spdlog: notice (between info and warning), alert and emergency (both after critical).

I see two possible evolutions: either augment spdlog levels list, or allow configuration of level_enum from tweakme.

**Comment by gabime** [comment]
I domt see good reason to augment or add tweakme just to fit syslog levels

**Comment by ambre-m** [comment]
So my current project using both syslog and android logs could use this otherwise very powerfull solution.

I will be making my own solution, somewhat similar.

**Comment by gabime** [comment]
Sounds good. Thanks for reporting.
