### ISSUE TITLE
Integration with SFML (updated)

### ISSUE THREAD

**Issue by colesnicov** [gabime/spdlog#1827]
Hello. Can you advise me if it works: [Redirect SFML Errors to Custom Logger](https://github.com/SFML/SFML/wiki/Source%3A-Redirect-SFML-Errors-to-Custom-Logger) ? It could be added to WIKI.

**Comment by gabime** [comment]
Might work. I don't think it belongs to the wiki since this is not to really related to,spdlog. It is a  general way to redirect sfml to an external logger.
