### ISSUE TITLE
EXC_BAD_ACCESS (code: 1, addr: 0x0)

### ISSUE THREAD

**Issue by HerbertKoelman** [gabime/spdlog#183]
First of all I'm quite impressed by SPDLOG. It's doing a very good job. 

I had initially wrapped another implementation with my `pmu::logger` class, but I decided to adapt my wrapper so that it now uses SPDLOG instead.

To give access to the logger instance created by `pmu::logger`constructor, I overloaded the *operator->()*. 

Everything is running fine, but from time to time my code ends up with this runtime exception.

It seems that when this happens it is handling some SPDLOG formatting operation, so I wondered if it was possible that something was going wrong in SPDLOG.

## description

When using spdlog in multi-threaded application, I frequently end up with EXC_BAD_ACCESS runtime error.

Any idea of what is going wrong ? Why do we end up with a null pointer ?

According to the stack trace destructor is called twice (item 4 et 5).

## stack trace Xcode

1. ` _LIBCPP_INLINE_VISIBILITY pointer operator->() const _NOEXCEPT {return __ptr_.first();}`: **this** is null.
2. `inline void spdlog::pattern_formatter::format(details::log_msg& msg)` at  `f-> format(msg, tm_time);`: 
3. `spdlog::logger::_log_msg(details::log_msg& msg)` at `_formatter->format(msg);`
4. `spdlog::details::line_logger::~line_logger()`at `_callback_logger->_log_msg(_log_msg);`
5. `spdlog::details::line_logger::~line_logger()`
6. `void consumer( pmu::sync_queue<message> *queue, const string fname )`at `logger->warn( err.what() );`

## plateform

* Mac OS X: 10.11.3 (15D21)
* Xcode: 7.2.1 (7C1002)
* C++11

### my thread function

This incriminated thread code fragment that fails:
```
void consumer( pmu::sync_queue<message> *queue, const string flamme )
  try {
    pmu::logger logger("consumer");
    logger->set_level(pmu::logger_levels::notice);
    logger->notice("starting.");

    std::chrono::seconds wait_time{1};
    ofstream out ;
    out.exceptions(std::ifstream::failbit | std::ifstream::badbit);
    
    try {
      out.open( name );{
      while( running ){
        message msg;
        
        logger->debug("before get message.");
        try{
          queue->get(msg,wait_time);
          
          logger->debug("popped a message off, header: [{}], content: [{}]", msg.get_header(), msg.get_content());
          
          out << msg.get_header() << ";" << msg.get_content() << ends;
        }catch(pmu::sync_queue_timeout &err){
          this is were the error is detected in my code (a c++ thread) >>>>>> logger->warn( err.what() );
        }
      }
      
      out.close();
      
    } catch (std::ofstream::failure &err) {
      logger->critical("file error, going down. {}, {}",err.what(), strerror( err.code().value()));
    }
  } catch ( pmu::logger_exception &err){
    printf("consumer logger setup failed, going down. %s.\n", err.what());
  } catch ( ... ){
    printf("unhandled exception was thrown in consumer thread, going down.\n");
  }
}
```

### splog wrapper header code:

```
#include "spdlog/spdlog.h"

namespace peu {
  
  using namespace std ;
  using logger_exception = spdlog::spdlog_ex ;  
  using logger_levels = spdlog::level::level_enum ;
  
  void set_level( logger_levels level);
  
  class logger {
  public:
    
    logger( const string name );
    
    inline void set_level( logger_levels level );
    inline logger_levels level() const ;
    
    std::shared_ptr<spdlog::logger> operator->();
    
  private:
    std::shared_ptr<spdlog::logger> log ;
    std::mutex mix;
    string name ;
  };
}
```

### splog wrapper body code:

```
#include "logger.hp"

namespace peu {
  
  void set_level( logger_levels level){
    
    spdlog::set_level(level);
  }
  
  logger::logger( const string n ): name{n}{
    
    std::lock_guard<std::mutex> lck(max);
    
    try {
      log = spdlog::stdout_logger_mt(name);
      log->set_pattern("%d/%m/%Y %T.%e %z, [%t] %n.%l: %v");
      
    } catch( logger_exception &err){
      log = spdlog::get(name);
      log->set_pattern("%d/%m/%Y %T.%e %z, [%t] %n.%l: %v");
    }
    
  }
  
  void logger::set_level( logger_levels level ){
    log->set_level(level);
  }
  
  logger_levels logger::level() const {
    return log->level() ;
  }

  std::shared_ptr<spdlog::logger> logger::operator->(){
    
    if (log == nullptr ) {
      throw logger_exception("null pointer logger for logger name: " + name);
    }
    return log ;
  }
  
}
```

**Comment by gabime** [comment]
I am note sure why the crash,, but I noticed there is 
```

   try {
      log = spdlog::stdout_logger_mt(name);
      log->set_pattern("%d/%m/%Y %T.%e %z, [%t] %n.%l: %v");

    } catch( logger_exception &err){
      log = spdlog::get(name);
      log->set_pattern("%d/%m/%Y %T.%e %z, [%t] %n.%l: %v");
    }

```
So if spdlog throws, the code forces the logger to some format? This doesn't make sense to me. The logger is invalid after such exception.
 Better to not catch  at all and report the error at higher level of the call stack.

As a side not this ctor could be much shorter (not need to locking for example)

```
  logger::logger( const string n ): name{n}{ 
      log = spdlog::stdout_logger_mt(name);
      log->set_pattern("%d/%m/%Y %T.%e %z, [%t] %n.%l: %v"); 
  }
```

**Comment by HerbertKoelman** [comment]
Hey that was mighty quick :-) 

So if I understand this well, the exception is not thrown only if the logger named _name_ was previously registered. 

I'm correct with this assumption ?

If so my code is indeed wrong.

My intention was:

1. check if a registered logger named _name_ exists
2. if so wrap a reference in logger class and that's it
3. if not found, then create and register a new one. wrap the new one in logger class

I tried to check if 'spdlog::get()' returned a nullptr but it throws an exception. Hence the use of a try catch structure.

How about declaring a "sub exception" that would make it possible to check the existence of a registered  logger instance.

Something like:
```
class spdlog::not_registered : spdlog::spdlog_ex{
  public:
    spdlog::not_regsitered( ... );
  ...
}
```

Or simpler, if one instantiate a logger that was already registered with this `spdlog::stdout_logger_mt(name);` the factory returns the existing one instead of creating a new instance.

**Comment by gabime** [comment]
get() it should return nullptr  if such logger doesnt exist. if an exception was thrown instead, then something went very wrong..

**Comment by HerbertKoelman** [comment]
Ok thanks I'll check this point.

Is there an online code documentation that I can consult ?

Something like doxigen would generate.

**Comment by gabime** [comment]
we have [wiki docs](https://github.com/gabime/spdlog/wiki/1.-QuickStart)

**Comment by HerbertKoelman** [comment]
Close but no cigar !

I refactored the logger wrapper's constructor
```
 log = spdlog::get(name);
 if ( log == nullptr ){
   log = spdlog::stdout_logger_mt(name);
 }
```

Still not working.

I'm correct to use ```spdlog::stdout_logger_mt``` ? I assumed it was a thread safe version.

**Comment by gabime** [comment]
yes. it is the thread safe version. 

I suggest to try and use spdlog directly without the wrapper to see if this is thecause of the problem

**Comment by HerbertKoelman** [comment]
I did start that way, but the number of threads that are using spdlog are quite a few. That's why I wanted to use registered loggers instead of instantiating one for each thread.

After a bit of looking into it deeper, I think it might be the set_pattern method that is not thread safe and causing the issue.

Is there a function to set the pattern once and for all loggers ? Like the function spdlog::set_level.

**Comment by gabime** [comment]
spdlog::set_pattern(..)

**Comment by HerbertKoelman** [comment]
I understand that this would help. But it's not very easy to do, we are working as a team of 5 persons. How the he...l can I know when one of my fellows is in need of a new logger category :-)

I'm setting up Xcode's instruments (Apple's profiler) and see if I can detect what and when things are going wrong I'll see if I can fix it...

More soon

**Comment by HerbertKoelman** [comment]
Hi there ! What's up ?

Some feedback on this issue. The code is apparently failing in this code (registry.h) when multithreading is used:
```
void register_logger_impl(std::shared_ptr<logger> logger)
    {
        auto logger_name = logger->name();
        if (_loggers.find(logger_name) != std::end(_loggers))
            throw spdlog_ex("logger with name " + logger_name + " already exists");
        _loggers[logger->name()] = logger;
    }

```

Is this code thread safe ? It seems that two threads are calling this registry method at the same time.

I expected the use of a mutex to secure this critical code section, something like this
```
void register_logger_impl(std::shared_ptr<logger> logger)
    {
        auto logger_name = logger->name();

        std::unique_lock<std::mutex> lck(mtx); // acquire lock
        if (_loggers.find(logger_name) != std::end(_loggers))
            throw spdlog_ex("logger with name " + logger_name + " already exists");
        _loggers[logger->name()] = logger;
    }
```

**Comment by gabime** [comment]
I don't think this is he problem.

The private methods are without locks, but the public methods that call them, use mutexes (like the public registey::register_logger(..))

**Comment by HerbertKoelman** [comment]
Hello, it's me again, I've changed the registry method like this:
```
    void register_logger_impl(std::shared_ptr<logger> logger)
    {
      auto logger_name = logger->name();
      
      if ( _loggers.count(logger_name) != 1 ){ // count returns 1 if an element with a key equivalent to k is found, or zero otherwise.
        _loggers[logger->name()] = logger;
        std::cout << "registrered " << logger_name << "." << std::endl ;
      }
    }
```

And this is apparently doing much better.

**Comment by gabime** [comment]
maybe it is because of the std::cout line. it make things slower and avoids some race condition.

 i dont think there is a difference from the orig code that would explain the difference

**Comment by HerbertKoelman** [comment]
The std::cout should not be there, I used it to debug 8-)

The code is looking for an entry with find wich return an iterator. This iterator was compared to std::end(_loggers). I have a feeling that this std::end is not exactly doing what it's expected to do...

According to my readings one should use _loggers.end() instead of std::end(_loggers).

The count method is supposed to be faster, so I replaced find with count.

The intention was to avoid to register twice a logger. And the code is doing just that.

**Comment by gabime** [comment]
According to [stackoverflow](http://stackoverflow.com/questions/8452130/when-to-use-stdbegin-and-stdend-instead-of-container-specific-versions) there shoul dnot be difference between std::end(_logger) and _logger.end

Why is the count method is supposed to be faster ?

**Comment by gabime** [comment]
Try taking the [latest](2f8e22d828bc48c41aaf2d5836b3dc9088a27284) version. In this version spdlog creates the logger only if it doesn't exist and might help your case

**Comment by HerbertKoelman** [comment]
Ok, I sure that this will fix my issue. My proposed changes did exactly that (creates the logger only if it doesn't exist)

:-)

**Comment by gabime** [comment]
well? did it help?

**Comment by HerbertKoelman** [comment]
Shame on me. Didn't have time to upgrade yet. I'll do this tomorrow. Promised 😊 


Cordialement 

Herbert Koelman

**Comment by gabime** [comment]
@HerbertKoelman Can I close this issue ?

**Comment by HerbertKoelman** [comment]
Sorry for this late feed back (I was quite busy).

Every seems to run fine with the latest code I found in the master branch.

Cool
