### ISSUE TITLE
Synchronous logger content is written only after logger.flush()

### ISSUE THREAD

**Issue by MaximAxelrod** [gabime/spdlog#1830]
Hi All, 
we compile and run the following snippet but we don't get anything printed into the file. The appropriate file is created and owned by the corresponding process, but it remains empty even several seconds after this code was finished (the program continues to run). The only log that is printed is "SPD DEFAULT LOGGER" to the stdout, but no other log is printed at all to the file, it's size remains 0. We had added logger->flush() at the end of the program and saw that all logs were printed. 

The question is why it happens? Do we really need to flush synchronous logger output? Thank you so much for your help! 

```
  try {

    // create a simple file thread safe sink which will create a new log file
    auto shared_file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(
        "/tmp/logfile.txt");

    auto logger =
          std::make_shared<spdlog::logger>("tgcad", shared_file_sink);

    logger->set_level(spdlog::level::info);

    spdlog::register_logger(logger);
	
	// try print using logger instance
    logger->error("1");
    logger->info("2");
    logger->debug("3");

	spdlog::info("SPD DEFAULT LOGGER");
  
	// try print using get()
    spdlog::get("tgcad")->error("4");
    spdlog::get("tgcad")->info("5");
    spdlog::get("tgcad")->debug("6");

  } catch (const spdlog::spdlog_ex &ex) {
    std::cout << "Log initialization failed: " << ex.what() << std::endl;
  }
```

**Comment by MaximAxelrod** [comment]
Thank you so much!

**Comment by gabime** [comment]
You welcome
