### ISSUE TITLE
Add spdlog to export targets

### ISSUE THREAD

**Issue by Febbe** [gabime/spdlog#1836]
spdlog is in an installation set when `SPDLOG_INSTALL` is defined, but this does not define an export set for it.
This results in not being able to build libraries that depend on spdlog. Especially if spdlog is built as a subdirectory.

**Comment by gabime** [comment]
Not sure I understand. Could you provide concrete example to reproduce?

**Comment by Febbe** [comment]
I need to check that out on my workstation. But maybe it's caused by our lib, using the [`export`](https://cmake.org/cmake/help/latest/command/export.html).
