### ISSUE TITLE
Add color support on file sinks

### ISSUE THREAD

**Issue by patrick-rotsaert** [gabime/spdlog#1838]
I'd like to have a rotating file sink with ansi coloring. Colored log files are a lot easier to read (e.g. with less -R) than plain text.
Colored logging to a file is possible using an `ansicolor_sink` with the `FILE *` c'tor, but then there is no rotation.
Any chance this may be added?

**Comment by alex-176** [comment]
@gabime this issue is closed as completed. but there is no color_rotating_sink in the codebase (or i missed it?). i can add a PR

**Comment by gabime** [comment]
It was closed because this can be achieved using custom formatter (or perhaps adding this functionality to the current pattern_formatter)

Also, there are many tools that display file contents with color.

**Comment by alex-176** [comment]
thanks

**Comment by patrick-rotsaert** [comment]
Please see this [PR](https://github.com/gabime/spdlog/pull/3112).
