### ISSUE TITLE
Question: how do I change the log info field?

### ISSUE THREAD

**Issue by VikingExplorer** [gabime/spdlog#184]
I haven't been able to figure out how to change the [info] field in log text.  For example:
```
[2016-03-03 12:58:53.054] [debug] [debug] EventHandler: processing event startup-dialog
```
According to the wiki: [info] [my_loggername] some text

So, "debug" is my logger name.  How do I change the info field?

**Comment by gabime** [comment]
please see the wiki docs

**Comment by VikingExplorer** [comment]
as I said, I can't find it.  Which section?

**Comment by gabime** [comment]
yes. this is the level name

**Comment by VikingExplorer** [comment]
Ok, sorry I misunderstand.  The wiki should say  [level] [my_loggername] some text.
