### ISSUE TITLE
how can i speed up compiling after building a static library?

### ISSUE THREAD

**Issue by nickhuangxinyu** [gabime/spdlog#1841]
I built out a libsqdlog.a

but i think i still need to include the header file directory.

how can i use to speed up complie?

just link the libsqdlog.a in compile command, without other operation?

(I am not familiar with compiler, so i think i still include all the source file)

**Comment by tt4g** [comment]
Even if you have a static library, you have to `include` the header.
This is a restriction due to the C++ build system, not the library.

**Comment by gabime** [comment]
You need to define SPDLOG_COMPILED_LIB before including spdlog in your code or use -DSPDLOG_COMPILED_LIB compiler flag when compiling your program.
Otherwise you would use the header only.

**Comment by nickhuangxinyu** [comment]
@gabime  if i use cmake, I just need to add SET(DSPDLOG_COMPILED_LIB my_lib_path), then the complie will speed up?

**Comment by tt4g** [comment]
`SPDLOG_COMPILED_LIB` is C/C++ macro, you have to use `target_compile_definitions()` in CMake.

```cmake
target_compile_definitions(my_lib_path PUBLIC SPDLOG_COMPILED_LIB)`
```

**Comment by tt4g** [comment]
> then the complie will speed up?

Compilation time will be faster than header only.

**Comment by nickhuangxinyu** [comment]
@tt4g sorry, i am a newbie in c++ and cmake.
So, if i compile spdlog, and get a static library in /home/nick/spdlog/lib/libspdlog.a

then my code include spdlog.

the concrete solution is:
i add target_compile_definitions(/home/nick/spdlog/lib/libspdlog.a PUBLIC SPDLOG_COMPILED_LIB)

then i cmake, make.
the compile process will be faster, right?

**Comment by tt4g** [comment]
> the concrete solution is:
> i add target_compile_definitions(/home/nick/spdlog/lib/libspdlog.a PUBLIC SPDLOG_COMPILED_LIB)

No, the first argument of `target_compile_definitions()` is your application or library.

`CMakeLists.txt` Example:

```cmake
# Define your application. If you want to build the library, replace it with `add_library(your_library ...)`.
add_executable(your_application <source file list here>)

# Link libspdlog.a.
target_link_libraries(your_application PUBLIC /home/nick/spdlog/lib/libspdlog.a)

# Define the `SPDLOG_COMPILED_LIB` macro when building your_application .
target_compile_definitions(your_application PUBLIC SPDLOG_COMPILED_LIB)
```

**Comment by nickhuangxinyu** [comment]
@tt4g great, much thanks!!!

**Comment by mandy-yan** [comment]
if my project don`t use cmake, it means i need use -DSPDLOG_COMPILED_LIB with gcc， is it right?

**Comment by tt4g** [comment]
Right.
