### ISSUE TITLE
%@ format does not work?

### ISSUE THREAD

**Issue by nickhuangxinyu** [gabime/spdlog#1842]
spdlog is a great tool!

but one more question:
i want to add source file line in my format.
i read fmt setting in set_pattern. it tells me `%@ `will be source file line adder.

so, i do like this:

```
#include "spdlog/spdlog.h"
int main() 
{
    spdlog::set_pattern("[%H:%M:%S] %@ %v");
    spdlog::info("Welcome to spdlog!");
}
```

but i didnt see the source file line info, can you help on this?

**Comment by tt4g** [comment]
Look wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

Example:

```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // Don't forget define SPDLOG_ACTIVE_LEVEL macro.

#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"

void source_info_example()
{
    auto console = spdlog::stdout_logger_mt("console");
    spdlog::set_default_logger(console);
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");

    SPDLOG_LOGGER_INFO(console, "log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 10] log with source info"
    SPDLOG_INFO("global log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 11] global logger with source info"

    console->info("source info is not printed"); // Console: "[source ] [function ] [line ] source info is not printed"
}
```

**Comment by ForwardXu** [comment]
> Look wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format
> 
> Example:
> 
> ```c++
> #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // Don't forget define SPDLOG_ACTIVE_LEVEL macro.
> 
> #include "spdlog/spdlog.h"
> #include "spdlog/sinks/stdout_sinks.h"
> 
> void source_info_example()
> {
>     auto console = spdlog::stdout_logger_mt("console");
>     spdlog::set_default_logger(console);
>     spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
> 
>     SPDLOG_LOGGER_INFO(console, "log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 10] log with source info"
>     SPDLOG_INFO("global log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 11] global logger with source info"
> 
>     console->info("source info is not printed"); // Console: "[source ] [function ] [line ] source info is not printed"
> }
> ```

Thanks. It solved my problem.
