### ISSUE TITLE
why spdlog doesnt support printf style?

### ISSUE THREAD

**Issue by nickhuangxinyu** [gabime/spdlog#1843]
can i use `spdlog::info("do as printf,%s", "format")`?

if this can work, i can use spdlog to replace all the printf function without modify one by one.

Thanks

**Comment by tt4g** [comment]
The spdlog argument is formatted by [fmt](https://github.com/fmtlib/fmt).
The fmt syntax works.
Look https://fmt.dev/latest/syntax.html

Example:

```cpp
spdlog::info("string syntax {:s}", "format");
spdlog::info("numeric syntax {:d}", 100);
```

**Comment by artemyv** [comment]
you can use fmt::sprintf
```
template <class loggerPtr, class... Args>
void loglineprintf(loggerPtr                 logger,
                   spdlog::level::level_enum level,
                   spdlog::source_loc        loc,
                   const char*               fmt,
                   const Args&... args) noexcept
{
    if(logger && logger->should_log(level))
	{
		logger->log(loc, level, "{}", fmt::sprintf(fmt, args...));
	}
}

#define SPDLOG_LOGGER_PRINTF(logger, level, ...) \
    loglineprintf(logger, level, spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, __VA_ARGS__)
```

and then define macro for each level and use it

**Comment by nickhuangxinyu** [comment]
> you can use fmt::sprintf
> 
> ```
> template <class loggerPtr, class... Args>
> void loglineprintf(loggerPtr                 logger,
>                    spdlog::level::level_enum level,
>                    spdlog::source_loc        loc,
>                    const char*               fmt,
>                    const Args&... args) noexcept
> {
>     if(logger && logger->should_log(level))
> 	{
> 		logger->log(loc, level, "{}", fmt::sprintf(fmt, args...));
> 	}
> }
> 
> #define SPDLOG_LOGGER_PRINTF(logger, level, ...) \
>     loglineprintf(logger, level, spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, __VA_ARGS__)
> ```
> 
> and then define macro for each level and use it

can you give me a tiny runnable example.

sorry, i am a newbie in c++. and i think this code may be used for logger?

I just need to make spdlog::info / spdlog::trace to support printf style.

much thanks

**Comment by artemyv** [comment]
Example https://github.com/artemyv/cmake_spdlog_example/tree/printf_like/src
Usage not directly but through MACROS
```
    LOG_ERROR("do as printf,%s", "format");
    LOG_INFO("do as printf,%d", 125);
```
Output
```
[2021-02-23 18:23:48.941] [error] [main.cpp:7] do as printf,format
[2021-02-23 18:23:48.942] [info] [main.cpp:8] do as printf,125
```

**Comment by nickhuangxinyu** [comment]
too muchhhhh thanks!!!!!!!!!!!!!!!!!!!!!

**Comment by 474914041** [comment]
> Example https://github.com/artemyv/cmake_spdlog_example/tree/printf_like/src Usage not directly but through MACROS
> 
> ```
>     LOG_ERROR("do as printf,%s", "format");
>     LOG_INFO("do as printf,%d", 125);
> ```
> 
> Output
> 
> ```
> [2021-02-23 18:23:48.941] [error] [main.cpp:7] do as printf,format
> [2021-02-23 18:23:48.942] [info] [main.cpp:8] do as printf,125
> ```

Thank you so much!

**Comment by 474914041** [comment]
> Example https://github.com/artemyv/cmake_spdlog_example/tree/printf_like/src Usage not directly but through MACROS
> 
> ```
>     LOG_ERROR("do as printf,%s", "format");
>     LOG_INFO("do as printf,%d", 125);
> ```
> 
> Output
> 
> ```
> [2021-02-23 18:23:48.941] [error] [main.cpp:7] do as printf,format
> [2021-02-23 18:23:48.942] [info] [main.cpp:8] do as printf,125
> ```

I found this way cannot support %p poniter, and %d enum has lots of warning.
So I used vsnprintf directly.
```C++
void log_printf_style(LoggerPtr& logger, spdlog::level::level_enum level, spdlog::source_loc loc,
                      const char* fmt, ...) noexcept {
    va_list args;
    va_start(args, fmt);
    int size = vsnprintf(nullptr, 0, fmt, args); // 获取格式化后的字符串长度
    va_end(args);

    char *tmp = nullptr;
    const int tmp_buff_len = 512;
    char buff[tmp_buff_len] = {0};
    bool mallco_mem = false;

    if (strstr(fmt, "%") == nullptr) {
        tmp = (char*)fmt;
    } else {
        if (size < tmp_buff_len) {  // 避免频繁申请小内存
            tmp = buff;
        } else {
            tmp = (char*)calloc(1, size + 1);
            if (!tmp) return;
            mallco_mem = true;
        }

        va_start(args, fmt);
        vsnprintf(tmp, size + 1, fmt, args);
        va_end(args);
    }

    logger->log(loc, level, "{}", tmp);

    if (mallco_mem)
        free(tmp);
}
```

**Comment by pzy2253999075** [comment]
```
#define SPDLOG_LOGGER_PRINTF(logger, level, m_fmt, ...) \
    SPDLOG_LOGGER_CALL(logger, level, "{}", fmt::sprintf(m_fmt __VA_OPT__(,) __VA_ARGS__))

#define LOG_NAME "async_logger"

#define LOG_FATAL(...)                                               \
  SPDLOG_LOGGER_PRINTF(spdlog::get(LOG_NAME), spdlog::level::critical, \
                     __VA_ARGS__)
#define LOG_ERROR(...) \
  SPDLOG_LOGGER_PRINTF(spdlog::get(LOG_NAME), spdlog::level::err, __VA_ARGS__)
#define LOG_WARN(...) \
  SPDLOG_LOGGER_PRINTF(spdlog::get(LOG_NAME), spdlog::level::warn, __VA_ARGS__)
#define LOG_INFO(...) \
  SPDLOG_LOGGER_PRINTF(spdlog::get(LOG_NAME), spdlog::level::info, __VA_ARGS__)
#define LOG_DEBUG(...) \
  SPDLOG_LOGGER_PRINTF(spdlog::get(LOG_NAME), spdlog::level::debug, __VA_ARGS__)
#define LOG_TRACE(...) \
  SPDLOG_LOGGER_PRINTF(spdlog::get(LOG_NAME), spdlog::level::trace, __VA_ARGS__)
```
