### ISSUE TITLE
Version 1.8.2 the {fmt} complie by VS2015 error: C2784 and C2893

### ISSUE THREAD

**Issue by yume2017** [gabime/spdlog#1844]

**Comment by yume2017** [comment]
I using visual studio 2015 to complie "example.cpp", will complie error. Then I try to change {fmt} to older version from version 1.8.1. Then work well. I a newer programmer, and don't know why will complie error when using fmt is 7.1.3.

**Comment by tt4g** [comment]
Please provide a detailed error message.
The cause cannot be determined from the error code alone.

**Comment by yume2017** [comment]
> Please provide a detailed error message.
> The cause cannot be determined from the error code alone.

1>  example.cpp
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(148): error C2784: “basic_format_context<fmt::v7::detail::buffer_appender<Char>,Char>::iterator fmt::v7::format_to(fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &,const S &,Args &&...)”: 未能从“fmt::v7::detail::buffer_appender<char>”为“fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &”推导 模板 参数
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(148): error C2893: 未能使函数模板“std::enable_if<enable,OutputIt>::type fmt::v7::format_to(OutputIt,const S &,Args &&...)”专用化
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(148): note: 用下列模板参数:
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(148): note: “OutputIt=fmt::v7::detail::buffer_appender<char>”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(148): note: “S=char [5]”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(148): note: “Args={fmt::v7::string_view &, const char (&)[3]}”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(148): note: “enable=false”
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(149): error C2784: “basic_format_context<fmt::v7::detail::buffer_appender<Char>,Char>::iterator fmt::v7::format_to(fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &,const S &,Args &&...)”: 未能从“fmt::v7::detail::buffer_appender<char>”为“fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &”推导 模板 参数
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(149): error C2893: 未能使函数模板“std::enable_if<enable,OutputIt>::type fmt::v7::format_to(OutputIt,const S &,Args &&...)”专用化
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(149): note: 用下列模板参数:
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(149): note: “OutputIt=fmt::v7::detail::buffer_appender<char>”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(149): note: “S=char [5]”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(149): note: “Args={const char (&)[7], int &}”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(149): note: “enable=false”
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(147): warning C4390: “;”: 找到空的受控语句；这是否是有意的?
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2670): error C2784: “basic_format_context<fmt::v7::detail::buffer_appender<Char>,Char>::iterator fmt::v7::format_to(fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &,const S &,Args &&...)”: 未能从“fmt::v7::detail::buffer_appender<char>”为“fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &”推导 模板 参数
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2670): error C2893: 未能使函数模板“std::enable_if<enable,OutputIt>::type fmt::v7::format_to(OutputIt,const S &,Args &&...)”专用化
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2670): note: 用下列模板参数:
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2670): note: “OutputIt=fmt::v7::detail::buffer_appender<char>”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2670): note: “S=char [5]”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2670): note: “Args={fmt::v7::detail::bigint::bigit &}”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2670): note: “enable=false”
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2674): error C2784: “basic_format_context<fmt::v7::detail::buffer_appender<Char>,Char>::iterator fmt::v7::format_to(fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &,const S &,Args &&...)”: 未能从“fmt::v7::detail::buffer_appender<char>”为“fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &”推导 模板 参数
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2674): error C2893: 未能使函数模板“std::enable_if<enable,OutputIt>::type fmt::v7::format_to(OutputIt,const S &,Args &&...)”专用化
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2674): note: 用下列模板参数:
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2674): note: “OutputIt=fmt::v7::detail::buffer_appender<char>”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2674): note: “S=char [7]”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2674): note: “Args={fmt::v7::detail::bigint::bigit &}”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2674): note: “enable=false”
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2677): error C2784: “basic_format_context<fmt::v7::detail::buffer_appender<Char>,Char>::iterator fmt::v7::format_to(fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &,const S &,Args &&...)”: 未能从“fmt::v7::detail::buffer_appender<char>”为“fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &”推导 模板 参数
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2677): error C2893: 未能使函数模板“std::enable_if<enable,OutputIt>::type fmt::v7::format_to(OutputIt,const S &,Args &&...)”专用化
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2677): note: 用下列模板参数:
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2677): note: “OutputIt=fmt::v7::detail::buffer_appender<char>”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2677): note: “S=char [4]”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2677): note: “Args={int}”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2677): note: “enable=false”
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2676): warning C4390: “;”: 找到空的受控语句；这是否是有意的?
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2724): error C2784: “basic_format_context<fmt::v7::detail::buffer_appender<Char>,Char>::iterator fmt::v7::format_to(fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &,const S &,Args &&...)”: 未能从“fmt::v7::detail::buffer_appender<char>”为“fmt::v7::basic_memory_buffer<Char,SIZE,std::allocator<Char>> &”推导 模板 参数
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>  d:\...\include\spdlog\fmt\bundled\format.h(3818): note: 参见“fmt::v7::format_to”的声明
1>d:\...\include\spdlog\fmt\bundled\format-inl.h(2724): error C2893: 未能使函数模板“std::enable_if<enable,OutputIt>::type fmt::v7::format_to(OutputIt,const S &,Args &&...)”专用化
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2724): note: 用下列模板参数:
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2724): note: “OutputIt=fmt::v7::detail::buffer_appender<char>”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2724): note: “S=char [7]”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2724): note: “Args={fmt::v7::string_view &, char *&}”
1>  d:\...\include\spdlog\fmt\bundled\format-inl.h(2724): note: “enable=false”

**Comment by tt4g** [comment]
> d:...\include\spdlog\fmt\bundled\format-inl.h(2676): warning C4390: “;”: 找到空的受控语句；这是否是有意的?

This warning is reporting an empty statement, but if you look at the source code, you will see that there is a function call there.

https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/fmt/bundled/format-inl.h#L2676-L2677

Probably, the source code of spdlog has been modified.
Please make sure that the source code is correct.

**Comment by yume2017** [comment]
> Probably, the source code of spdlog has been modified.
> Please make sure that the source code is correct.

Thanks first. I have check the code. The spdlog didn't change {fmt} source code. And this warning is a little strange...

**Comment by tt4g** [comment]
The error message indicates a bundled {fmt}. You seem to have changed the {fmt} version, are you using an external {fmt}?

**Comment by yume2017** [comment]
> The error message indicates a bundled {fmt}. You seem to have changed the {fmt} version, are you using an external {fmt}?

No, I didn't using external {fmt}. I change {fmt} to FMT_VERSION 70003(7.0.3), and it work well. Then i also try  other version {fmt} , like 7.1.3, 7.1.2, 7.1.1 and 7.1.0 through replace inside "bunble" files, they all compile errors. Maybe after {fmt} 7.1.0 don't support VC14.0(Visual Studio 2015)?

**Comment by tt4g** [comment]
I don't know, I couldn't find the issue in the {fmt} project.
However, there have been some API changes in version 7.1.0.

It might be a good idea to report the code that cannot be built with MSVC 2015 to the {fmt} project.
