### ISSUE TITLE
High CPU load while invoke spdlog::flush_every(std::chrono::seconds(60));

### ISSUE THREAD

**Issue by duanliquan** [gabime/spdlog#1845]
`
auto file_logger = spdlog::rotating_logger_mt("log", "local.log", 1024 * 1024 * 3, 3);
spdlog::set_default_logger(file_logger);
spdlog::flush_every(std::chrono::seconds(60));
`
The application's CPU load increase to 98~99% while invoking flush_every function in the embedded system environment( NXP i.MX6D ).
How to fix this issue if i want to use flush interval function?

**Comment by gabime** [comment]
I can only guess that https://github.com/gabime/spdlog/blob/de89c4fd016cf7d81562c4fbba9bfee4c3fceb35/include/spdlog/details/periodic_worker-inl.h#L25 in this embedded system is implemented with bust wait or similar.

Try to insert a sleep of 1 or 2 seconds inside the for(;;) loop (before the  ״std::unique_lock״ line)

**Comment by duanliquan** [comment]
> ```c++
> while(_active)
> {
>     std::this_thread::sleep_for(std::chrono::milliseconds{1000});
>    callback_fun();
> }
> ```
> 
> This will flush every second but might fix the busy loop. Then, if needed, you can add the logic here to flush only every 60 seconds
Hi gabime, thank you for reply! 
It really works that using while replace for(;;) . Also , I can write a separate logic with using the logger->flush() function to implement the similar feature.
I wonder that why it doesn't work while I try to insert a sleep before "std::unique_lock" line or after.  Are the semaphore's usages effect the result? Is there a good way to improve the problem while maintaining existing interfaces?

**Comment by duanliquan** [comment]
`f (this->cv_.wait_for(lock, interval, [this] {
                std::this_thread::sleep_for(std::chrono::milliseconds(10));
                return !this->active_; }))`
I think I have got a kind of solution that insert a sleep before return !this->active, [this]{} is a busy loop while waiting condition_variable.

**Comment by gabime** [comment]
Yes, that would work too,  but I dont see the point of using ```cv_.wait_for``` if it just busy waits for the mutex.
What os/compiler/c runtime are you using? 

Also, 10ms seems a bit small. Consider increasing it to 100 or 200 to avoid calling sleep() hundreds times a second.

**Comment by duanliquan** [comment]
> Yes, that would work too, but I dont see the point of using `cv_.wait_for` if it just busy waits for the mutex.
> What os/compiler/c runtime are you using?
> 
> Also, 10ms seems a bit small. Consider increasing it to 100 or 200 to avoid calling sleep() hundreds times a second.

Thank you very much!
Here are some info about my environment:
OS: linux 4.1.15
Compiler: arm-poky-linux-gnueabi-gcc (GCC) 5.3.0
C runtime:
`
# /lib/libc.so.6
GNU C Library (GNU libc) stable release version 2.23, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 5.3.0.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
`
