### ISSUE TITLE
Rename SPDLOG_BUILD_SHARED to BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by concatime** [gabime/spdlog#1848]
I recommend the use of the [documented](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) `BUILD_SHARED_LIBS` (like [LibreSSL](//github.com/libressl-portable/portable/tree/v3.2.4#cmake---additional-options) and [{fmt}](//github.com/fmtlib/fmt/blob/7.1.3/CMakeLists.txt#L234) do) instead of using a custom variable.
We can then refactor this:
```cmake
if(SPDLOG_BUILD_SHARED)
    if(WIN32)
        configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cmake/version.rc.in ${CMAKE_CURRENT_BINARY_DIR}/version.rc @ONLY)
        list(APPEND SPDLOG_SRCS ${CMAKE_CURRENT_BINARY_DIR}/version.rc)
    endif()
    add_library(spdlog SHARED ${SPDLOG_SRCS} ${SPDLOG_ALL_HEADERS})
    target_compile_definitions(spdlog PUBLIC SPDLOG_SHARED_LIB)
    if(MSVC)
        target_compile_options(spdlog PUBLIC 
            $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<NOT:$<COMPILE_LANGUAGE:CUDA>>>:/wd4251 /wd4275>)
    endif()
    if(NOT SPDLOG_FMT_EXTERNAL AND NOT SPDLOG_FMT_EXTERNAL_HO)
        target_compile_definitions(spdlog PRIVATE FMT_EXPORT PUBLIC FMT_SHARED)
    endif()
else()
    add_library(spdlog STATIC ${SPDLOG_SRCS} ${SPDLOG_ALL_HEADERS})
endif()
```

to something like this:

```cmake
if(BUILD_SHARED_LIBS AND WIN32)
    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cmake/version.rc.in ${CMAKE_CURRENT_BINARY_DIR}/version.rc @ONLY)
    list(APPEND SPDLOG_SRCS ${CMAKE_CURRENT_BINARY_DIR}/version.rc)
endif()
add_library(spdlog ${SPDLOG_SRCS} ${SPDLOG_ALL_HEADERS})
if (BUILD_SHARED_LIBS)
    target_compile_definitions(spdlog PUBLIC SPDLOG_SHARED_LIB)
    if(MSVC)
        target_compile_options(spdlog PUBLIC 
            $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<NOT:$<COMPILE_LANGUAGE:CUDA>>>:/wd4251 /wd4275>)
    endif()
    if(NOT SPDLOG_FMT_EXTERNAL AND NOT SPDLOG_FMT_EXTERNAL_HO)
        target_compile_definitions(spdlog PRIVATE FMT_EXPORT PUBLIC FMT_SHARED)
    endif()
endif()
```

WDYT?

**Comment by gabime** [comment]
Sounds ok.  What is the main benefit? This would break backward compatibility.

**Comment by concatime** [comment]
> What is the main benefit?

Well, because it’s the standard 😅.
More seriously, it ease the library usage because people (developers and maintainers) don’t _need_ nor _should_ dig into the cmake config for each library just to check how to tell it to build itself as a static or dynamic library.
They would expect `BUILD_SHARED_LIBS` to do this, just like how we expect `CMAKE_BUILD_TYPE` to control whether or not `-g` is passed to the compiler.

**Comment by gabime** [comment]
Good points. I think its best add it in addition to the SPDLOG_BUILD_SHARED to retain backward compatibility.
