### ISSUE TITLE
Daily file sink does not clean old files of previous program executions

### ISSUE THREAD

**Issue by rubenpraets** [gabime/spdlog#1850]
As far as I can see, the daily file sink will only work as intended under some specific circumstances. I'll try to explain what I think is wrong with it, but I don't have a lot of time now so feel free to ask for more info. 

The problem seems to be that this logger doesn't take into account that the process using spdlog is not guaranteed to be running continuously. Some problems this entails:
- Deleting old files only ever happens if the process is active when the rotation time point comes around. If not, spdlog will never detect this and old files will pile up.
- If the process is stopped and then started the next day, a new log file is created no matter the intended rotation time. When the rotation time point rolls around, it is assumed that a new file will be created and an old one is removed. Instead, the current file name is entered a second time into the filenames_q_ and not the oldest but second oldest log file is deleted, leaving the oldest one there for eternity.

My description is probably not complete, but if you reason about it a bit you might see what I mean, or otherwise prove me wrong. In any case, I also have a slightly simplified version of your daily file sink that I'm willing to share. It always rotates at midnight, and that deals with some of the problems I describe above.
Thanks anyway for the great logging library you gave us ;)

**Comment by gabime** [comment]
Thanks for reporting. Both of the problems are due to the fact that spdlog, for performance reasons avoids to accessing the disk to search existing files,  but uses in memory q jnstead.

It might be a good idea to replace with something more robust even at the expense of accessing the disk. PRs are welcome.

**Comment by rubenpraets** [comment]
I'll make a PR for my adaptations when I'm sure they are correct, but in the meantime I can also recommend you to look at this Python class: [TimedRotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler) (source code available [here](https://github.com/python/cpython/blob/3.9/Lib/logging/handlers.py))
It offers the same basic functionality as your daily file sink but also some extra stuff, and might be a good source of inspiration.
