### ISSUE TITLE
Can't redirect std::cout (within google test framework)

### ISSUE THREAD

**Issue by vulkan101** [gabime/spdlog#1859]
Hi, I'm cross posting from S/O as it looks like this might be an issue with spdlog.
I'm on master and up to date. I'm trying to capture my output from std::cout within google tests, previously when directly writing to std::cout this works:
```
class MyTest : public testing::Test
{
protected:
        void SetUp() override
        {            
            sbuf = std::cout.rdbuf();
            std::cout.rdbuf(buffer.rdbuf());        
        }
        void TearDown() override
        {
            std::cout.rdbuf(sbuf);         
        }
        std::stringstream buffer;
        std::streambuf* sbuf;
}
// buffer is then read within a test body like so:
doSomethingThatWritesToStdOut();
std::string teststr = buffer.str();
EXPECT_TRUE(teststr.find("Some output string") != std::string::npos);
```
Now when I switch from outputting to std::cout to using either a specific spdlog instance or the default spdlog::debug(), I can no longer capture the output. 
By specific spdlog instance I mean:
```
auto console = spdlog::stdout_color_mt("console");
console->debug("log");
```

S/O link is [here ](https://stackoverflow.com/q/66473052/822830) in case any more detail pops up

**Comment by gabime** [comment]
> I'm on master and up to date

Main branch is v1.x, not master which obsolete.

spdlog does not use cout so no wonder capturing cout doesnt work.

**Comment by vulkan101** [comment]
Fair enough, I assumed the latest branch was master - I'm on v1.x.
Can you suggest a way to capture the output of spdlog in a test? The reaction to issue 1147 made me think that being able to redirect stdout was a thing that should work.

**Comment by gabime** [comment]
Why not try one of the answers in so https://stackoverflow.com/questions/3803465/how-to-capture-stdout-stderr-with-googletest ?

**Comment by vulkan101** [comment]
Most of those answers are actually about std::cout, which I have no trouble capturing. 
It looks like maybe I can use the  ostream sink to get spdlog to write to a buffer I can then read, does that sound feasible?

**Comment by gabime** [comment]
https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/ringbuffer_sink.h is even better choice

**Comment by vulkan101** [comment]
Thanks, will give it a shot!

**Comment by artemyv** [comment]
why not to use ostream sync?
```
    std::ostringstream oss;
    auto ostream_sink = std::make_shared<spdlog::sinks::ostream_sink_st>(oss);
    auto test_logger = std::make_shared<spdlog::logger>("root", ostream_sink);

    test_logger->set_pattern(">%v<");
	//Do your code using test_logger

    ASSERT_TRUE(oss.str() == ">Your expected output<\r\n");
```

**Comment by vulkan101** [comment]
@artemyv that's what I was thinking - but for some reason I never see anything written to the `std::ostringstream`?

**Comment by artemyv** [comment]
I posted a snippet from the code that is actually working in my unittests
So maybe you have not configured level that is actually used. By default only critical-info messages will be shown. So debug and trace needs to be explicitly configured

**Comment by vulkan101** [comment]
@artemyv  Thanks for your snippet - yes, you can see I worked it out above, I hadn't set the level correctly, most of my log output is debug or trace, so I needed to set to that level. Works lovely now :-D
