### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by mdinacci** [gabime/spdlog#186]
`format.cc` and `format.h` are not licensed under an Open Source license.

    Copyright (c) 2012 - 2015, Victor Zverovich
    All rights reserved.

I don't think **spdlog** can be released under a MIT license with these files but I'm not a license lawyer so don't take my word for it. In any case it makes the library unusable in any context where proprietary code cannot be used.

**Comment by LogicalKnight** [comment]
Actually, C++ Format is released under a [2-Clause BSD License](https://opensource.org/licenses/BSD-2-Clause). See [C++ Format's license](https://github.com/cppformat/cppformat/blob/master/LICENSE.rst).

**Comment by vitaut** [comment]
As @LogicalKnight wrote, C++ Format is licensed under an open-source BSD license which is copied in `format.{h,cc}`: https://github.com/gabime/spdlog/blob/master/include/spdlog/details/format.h#L4-L25, so all is good. Note that this license only covers that 2 files, the rest of spdlog library can be released under any combination of compatible licenses.

**Comment by mdinacci** [comment]
Thanks for the very quick response ! 
The "All Rights Reserved" line put me off but that's exactly what the template of the BSD license says.
