### ISSUE TITLE
Stdout sink enhancement

### ISSUE THREAD

**Issue by Eddie-cz** [gabime/spdlog#1864]
Hi,
 current stdout sink initializes in constructor and if it fails, it's done. 
 There is hovewer one situation, where it could behave differently, and it is GUI Win32 app with not yet created stdout redirections  (_fileno returns -2 in that case). It would help us to have possibility to set for this sink such behaviour, that it would try to init itself on every log entry in this specific case (stdout console is created manually later during our app initialization).
Petr

**Comment by gabime** [comment]
Why not create the  sink only when needed(after the stdout redirections are ready)?

**Comment by Eddie-cz** [comment]
As we support both linux and win, have to have custom stdout sink initialization in code which creates win stdout console and same stdout sink initialization elsewhere in code for linux platform where i don't have to wait for console redirection. Otherwise I would create this sink directly with logger, which I cannot atm.

**Comment by gabime** [comment]
This is very specific need. You can define custom sink for this sink easily.

**Comment by Eddie-cz** [comment]
You are the author;-) Don't think reimplementing color stdout sink can be done easily, but I will figure something out.

**Comment by gabime** [comment]
Another option would be re create the color sink after the console creation code and register it with same name to replace previous one.
