### ISSUE TITLE
std::bad_alloc while running simple application without sync/async things

### ISSUE THREAD

**Issue by m4infr4m3** [gabime/spdlog#1865]
When i run this code : 

#include "spdlog/spdlog.h"

int main()
{
	spdlog::info("Hello!");

	return 0;
}	

I'm getting a `[*** LOG ERROR #0001 ***] [2021-03-07 12:43:55] [] {std::bad_alloc}` 
As you see, i don't use sync or async, only header file and code from example

**Comment by tt4g** [comment]
Similar issue: #1720

**Comment by m4infr4m3** [comment]
Many thanks!

**Comment by maingoh** [comment]
Sorry I am not sure to understand the solution, I get the exact same error log with the main above and don't manage to just print a normal info log. 
It should work the same way than doing `std::cout << "Hello!" << std::endl;` no ?

**Comment by tt4g** [comment]
Register an error handler as shown in the Example code in [this comment](https://github.com/gabime/spdlog/issues/1720#issuecomment-720517067).

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"

#include <iostream>
#include <memory>

int main(int, char**) {

    spdlog::set_error_handler([](const std::string &msg) { std::cerr << "error handler: " << msg.c_str() << "\n"; });

    auto stdout_logger =
        std::make_shared<spdlog::logger>("stdout_logger", std::make_shared<spdlog::sinks::stdout_sink_mt>());
    spdlog::initialize_logger(stdout_logger);

    const char *terminated_chars = "Hello, World!";
    stdout_logger->info("terminated: {0}", terminated_chars);

    // Hello, World!
    const char non_terminated_chars[] =
        {'H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!'};

    stdout_logger->info("no terminated: {0}", non_terminated_chars);

    return 0;
}
```

It is assumed that the printed message is not null-terminated.

On a machine with not enough memory, an error will occur with `new` and the message will not be printed.
In that case, please add more memory.

**Comment by maingoh** [comment]
Literal strings are always null terminated and I have enough RAM. 
I realized my issue might come from the fact that I was installing spdlog from conan. There might be a issue with the prebuilt library. When I compile it myself it works.

**Comment by tt4g** [comment]
You may be using an incompatible library, or the build flags may be different.

**Comment by maingoh** [comment]
Found the issue: I needed to set conan to use the new ABI `conan profile update settings.compiler.libcxx=libstdc++11 default`. Sorry for the inconvenience :)
