### ISSUE TITLE
use uvw::spawn start child process, rotate_file_sink appears "Permission denied" when rename_file_()

### ISSUE THREAD

**Issue by LeeYearJ** [gabime/spdlog#1867]
file size: 1 * 1024 
even file size is 10 * 1024 * 1024 and close all av(windows10 defender and others), still cant avoid.

**Comment by tt4g** [comment]
What is `uvw::spawn`?
Have you checked the executor of the child process?

**Comment by tt4g** [comment]
Write down all the causes that come to mind.

1. The executor of the child process does not have permissions on the previously created log file.
2. The parent process has opened the log file to be rotated, so the child process cannot rename it.
3. Failed to delete the file. 
  https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/sinks/rotating_file_sink-inl.h#L122-L126

**Comment by LeeYearJ** [comment]
Thank you for your reply and suggestions. 
I go back to verify these conjectures

uvw used to create child processes.

**Comment by LeeYearJ** [comment]
Debug with breakpoints, after the CreateProcessW() method is executed, the file rorate failed and shows "Permission denied"
