### ISSUE TITLE
spdlog type streaming is fragile

### ISSUE THREAD

**Issue by skelly-energid** [gabime/spdlog#1868]
Whether streaming works with spdlog seems to depend on include order and which compiler is used.

Consider this simulation:

```
// #define WORKING_INCLUDE_ORDER

#ifndef WORKING_INCLUDE_ORDER
#    include <spdlog/spdlog.h>

#    include <spdlog/fmt/ostr.h>
#endif

#include <iostream>

namespace ns
{
    struct Aaa
    {
    };
} // namespace ns

std::ostream& operator<<(std::ostream& os, ns::Aaa const& vec);

#ifdef WORKING_INCLUDE_ORDER

#    include <spdlog/spdlog.h>

#    include <spdlog/fmt/ostr.h>

#endif

void foo()
{
    ns::Aaa aa;
    spdlog::info("none", "Aaa : {}", aa);
}
```

Compiling with gcc works:
```
/usr/bin/g++ -isystem spdlog/include -c test.cpp
```
Compiling with clang fails:
```
/usr/bin/clang++ -isystem spdlog/include -c test.cpp
spdlog/include/spdlog/fmt/bundled/core.h:1016:5: error: static_assert failed due to requirement 'formattable' "Cannot format argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#formatting-user-defined-types"
```

Clang also "works" if `WORKING_INCLUDE_ORDER` is defined.

We encountered this while trying to stream a `osg::Vec3` using a `operator<<` which we define.

**Comment by tt4g** [comment]
Since the error message is reported by the fmt library, it is recommended that you open the issue in the [fmt project](https://github.com/fmtlib/fmt).

**Comment by skelly-energid** [comment]
This seems to be related: https://github.com/fmtlib/fmt/issues/2130 At least, this issue can be closed in favor of dealing with it in the context of fmt.
