### ISSUE TITLE
Custom sink for SQlite3

### ISSUE THREAD

**Issue by PedroRod** [gabime/spdlog#187]
Hey Guys, I have made a custom sink for SQlite3.

let me know if anyone is interested and I will make a pull request for you guys to review possibly add it as another built-in sink.

Bellow is the ss of the sql table for the logs!
![image](https://cloud.githubusercontent.com/assets/15665242/13902194/a8a158d6-ee15-11e5-85aa-142dbbd2f314.png)

Thanks for such nice logging API guys! Happy coding!

**Comment by gabime** [comment]
Thanks. Looking good.. 

Please submit the pull request.

**Comment by PedroRod** [comment]
Pull request was created.

I also made a small repo for it with a simple doc on how to implement.
[https://github.com/PedroRod/sqlite3_database_sink](url)
