### ISSUE TITLE
Provide logger for each loaded plugin

### ISSUE THREAD

**Issue by Tectu** [gabime/spdlog#1871]
Imagine a simple application which can load zero or more plugins during runtime. The core application is already using `spdlog`. I would now like to pass an instance of `spdlog` to each plugin upon loading it. The idea would be that each plugin gets it's own logger which will reflect the plugin's name in the resulting log next to the severity level.

However, the application adds multiple sinks already: One to console, one to file and a simple in-memory sink. I would like to implement this in a way that if the plugins issues a log call that it will appear on all sinks - just prefixed with the plugin's name.

What is the proper way of achieving this?

**Comment by Tectu** [comment]
That appears to work well. Thank you!

**Comment by Tectu** [comment]
While this works as expected I'd like to revisit the issue.

For the use case outlined in the original post it would be much better to add a second level of brackets containing a second name.
This might sound like non-sense as I might not be familiar with the proper terminology. Let me explain:

Currently we have this format (out of the box):
```none
[date] [name] [severity] content
```
What I'd like is something like this:
```none
[date] [name1] [name2] [severity] content
```
Ideally this would allow to create more deeply nested hierarchies such as:
```none
[date] [app name] [plugin name] [sub-system name] [severity] content
```
I am basically looking for something that works exactly like `logger::clone()` but instead of changing the name it would extend it.
For the sake of argument it could also look like this:
```none
[date] [name1 | name2 | name3 ] [severity] content
```
How can I achieve this?

**Comment by gabime** [comment]
A simple solution would be give it whatever extended name needed depending on cloned logger name:

```c++
logger1->clone(logger.name() + " name1");
logger2->clone(logger1.name() + " name2");
```

**Comment by Tectu** [comment]
How does the non-simple solution look like? I take it that this can be achieved with a custom format?

**Comment by gabime** [comment]
Not sure. But why would you want non simple solution ? simple is best you know

**Comment by Tectu** [comment]
Can't argue with that. It's certainly sufficient for my current needs.
I was just hoping to gather some more information in case the needs change in the future ;-)

But let's cross that bridge when we get there.

Thanks for your help (and this library, of course)!
