### ISSUE TITLE
Logging a std::vector

### ISSUE THREAD

**Issue by AjGodara** [gabime/spdlog#1874]
Hi,

I am trying to log the contents of a std::vector using spdlog. I initially tried by defining the << operator for std::vector<T>, then instead tried defining the << operator for a specific type(std::vector\<int> ), none of which were sufficient to get the formatting working. 
What i really wanted to do is : 
```C++
std::vector<int> vec{2, 3, 5};
spdlog::info("This is some vector {}", vec); 
```
So i tried defining these 
```C++
std::ostream& operator << (std::ostream& os, const std::vector<int>& vec);
```
OR 
```C++
template<typename T>
std::ostream& operator << (std::ostream& os, const std::vector<T>& vec);
```
Which does not work.
The following, however, does:
```C++
class toyClass {};

std::ostream& operator << (std::ostream& os, const toyClass& c){
    os << "Printing a toyClass instance " << "\n";
    return os;
}
```

Is the formatting not supported for templated types ? Or should i be doing it differently? 

Thanks for your attention.

**Comment by gabime** [comment]
fmt has support for for this in the ranges.h header.

```c++
#include “spdlog/fmt/bundled/ranges.h”
logger->info ("{}", fmt::join(vec, ", ")); 
```

**Comment by AjGodara** [comment]
Thanks very much. this is better and more generic than i expected. :+1:
