### ISSUE TITLE
how many times can spdlong be faster than printf?

### ISSUE THREAD

**Issue by nickhuangxinyu** [gabime/spdlog#1875]
i think printf is slow, can i speed up if i use spdlog::info to replace printf?

i read someone's blog, it told me one time printf will cost about 10us, is there any numbers about one time of spdlog print?

**Comment by tt4g** [comment]
[Here](https://github.com/fmtlib/fmt#benchmarks) is a benchmark of the fmt library that spdlog uses to format log messages.

**Comment by tt4g** [comment]
The purpose of spdlog is logging. There are costs other than formatting for this purpose.

If you just want to replace `printf`, it is better to use the fmt library.
`fmt::printf` supports the `printf` format.
https://fmt.dev/latest/api.html#printf-formatting
