### ISSUE TITLE
VS2019 W4 cast warning

### ISSUE THREAD

**Issue by flriancu** [gabime/spdlog#1876]
Hi @gabime ,

[This particular line](https://github.com/gabime/spdlog/blob/1305663d991d37607964cbc6b7c08954677992e3/include/spdlog/sinks/wincolor_sink-inl.h#L137) generates a level 4 warning with VS2019:

```
[...]\spdlog\sinks\wincolor_sink-inl.h(137,80): warning C4244: 'argument': conversion
from 'int' to 'WORD', possible loss of data
```

It can be solved with `static_cast<WORD>(new_attribs)`.

**Comment by gabime** [comment]
Fixed. Thanks @flriancu
