### ISSUE TITLE
1.8.3 release date

### ISSUE THREAD

**Issue by davinci26** [gabime/spdlog#1887]
Hey folks, awesome project!

Do you have an approximate timeline for 1.8.3 release?

Thanks,
Sotiris

**Comment by gabime** [comment]
No timeline. But should be soon. Why ?

**Comment by davinci26** [comment]
I wanted to pick a change that is available in main but not in the latest release and I prefer pulling "stable" version rather than master. So I am trying to see if it is worth for me to wait for 1.8.3 or just work based on main.

**Comment by gabime** [comment]
which change in particular?

**Comment by davinci26** [comment]
This one https://github.com/gabime/spdlog/pull/1760

Also as an FYI you do not mention Windows Event logger as part of the features on the README. I found out that you support only because I was searching the code. It is a pretty cool feature that you support.

**Comment by gabime** [comment]
Updated.. Thanks!

**Comment by pwuertz** [comment]
Also interested in a 1.8.3 release because of the stdout_sink regression Windows #1828

**Comment by gabime** [comment]
Version 1.8.3 released.
