### ISSUE TITLE
When I use spdlog in my project, I compired ,As follow error

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [gabime/spdlog#1892]
![image](https://user-images.githubusercontent.com/28779327/112625518-01a1f180-8e6a-11eb-8415-d890def98c52.png)

**Comment by tt4g** [comment]
Enable C++11 standard.

**Comment by wangwenqiangGitHub** [comment]
> Enable C++11 standard.
![Uploading image.png…]()

**Comment by tt4g** [comment]
The image is failing to upload.

It doesn't look like `std::tuple` is being used on line 153 in the v1.8.5 source code.
Try to get the latest source from the release page. or `git checkout v1.8.5`.

**Comment by wangwenqiangGitHub** [comment]
> The image is failing to upload.
> 
> It doesn't look like `std::tuple` is being used on line 153 in the v1.8.5 source code.
> Try to get the latest source from the release page. or `git checkout v1.8.5`.

We project used old version, the CmakeLists.txt As follow
 set(CMAKE_CXX_FLAGS "-std=c++11 -pthread  -fPIC -Wall -fmessage-length=0")
set(CMAKE_C_FLAGS "-std=c99 -Wall -fmessage-length=0")

**Comment by wangwenqiangGitHub** [comment]
> > The image is failing to upload.
> > It doesn't look like `std::tuple` is being used on line 153 in the v1.8.5 source code.
> > Try to get the latest source from the release page. or `git checkout v1.8.5`.
> 
> We project used old version, the CmakeLists.txt As follow
> set(CMAKE_CXX_FLAGS "-std=c++11 -pthread -fPIC -Wall -fmessage-length=0")
> set(CMAKE_C_FLAGS "-std=c99 -Wall -fmessage-length=0")

ours project has quoto source code of spdlog

**Comment by tt4g** [comment]
> ours project has quoto source code of spdlog

If the "quote" source code has been modified, then the compilation error is not a spdlog issue.

If yours is only a copy, please let me know the version so I can investigate the cause of the build error.

**Comment by wangwenqiangGitHub** [comment]
> > ours project has quoto source code of spdlog
> 
> If the "quote" source code has been modified, then the compilation error is not a spdlog issue.
> 
> If yours is only a copy, please let me know the version so I can investigate the cause of the build error.

When I use g++ -std=c++0x  -O0 -g3 -Wall -c -fmessage-length=0 -fPIC in EClipse IDE， it could be successfull,but I use CMakeList.txt is erro

**Comment by tt4g** [comment]
> When I use g++ -std=c++0x -O0 -g3 -Wall -c -fmessage-length=0 -fPIC in EClipse IDE， it could be successfull,but I use CMakeList.txt is erro

Please provide a `CMakeLists.txt` that can reproduce the problem.

**Comment by wangwenqiangGitHub** [comment]
> > When I use g++ -std=c++0x -O0 -g3 -Wall -c -fmessage-length=0 -fPIC in EClipse IDE， it could be successfull,but I use CMakeList.txt is erro
> 
> Please provide a `CMakeLists.txt` that can reproduce the problem.

cmake_minimum_required(VERSION 3.8)
set(CMAKE_CXX_FLAGS "-std=c++11 -pthread  -fPIC -Wall -fmessage-length=0")
set(CMAKE_C_FLAGS "-std=c99 -Wall -fmessage-length=0")
set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_NO_SYSTEM_FROM_IMPORTED ON)


PROJECT(libom)
include_directories(./internal)
include_directories(./internal/crypto)
include_directories(./internal/spdlog)
include_directories(./internal/spdlog/details)
include_directories(./internal/spdlog/fmt)
include_directories(./internal/spdlog/fmt/bundled)
include_directories(./internal/spdlog/sinks)
include_directories(./message)
include_directories(../libssl/openssl)
include_directories(./)

aux_source_directory(internal DIR_OM_INTERNAL)
aux_source_directory(internal/crypto DIR_OM_INTERNAL_CRYPTO)
aux_source_directory(internal/spdlog DIR_OM_INTERNAL_SPDLOG)
aux_source_directory(internal/spdlog/details DIR_OM_INTERNAL_SPDLOG_DETAILS)
aux_source_directory(internal/spdlog/fmt DIR_OM_INTERNAL_SPDLOG_FMT)
aux_source_directory(internal/spdlog/fmt/bundled DIR_OM_INTERNAL_SPDLOG_FMT_BUNDLED)
aux_source_directory(internal/spdlog/sinks DIR_OM_INTERNAL_SPDLOG_SINKS)


aux_source_directory(message DIR_OM_MESSAGE)
#

##########################################################
add_library(om SHARED
        ${DIR_OM_INTERNAL}
        ${DIR_OM_INTERNAL_CRYPTO}

        ${DIR_OM_INTERNAL_SPDLOG}
        ${DIR_OM_INTERNAL_SPDLOG_DETAILS}
        ${DIR_OM_INTERNAL_SPDLOG_FMT}
        ${DIR_OM_INTERNAL_SPDLOG_SINKS}

        ${DIR_OM_MESSAGE}
        main.cpp
        logger.cpp
        )

target_link_libraries(
    om
    /mnt/d/code/LTE—V2X/libssl/Debug/libcrypto.so
    /mnt/d/code/LTE—V2X/libssl/Debug/libssl.so
    )

**Comment by wangwenqiangGitHub** [comment]
> > When I use g++ -std=c++0x -O0 -g3 -Wall -c -fmessage-length=0 -fPIC in EClipse IDE， it could be successfull,but I use CMakeList.txt is erro
> 
> Please provide a `CMakeLists.txt` that can reproduce the problem.
in version.h as follow
#define SPDLOG_VER_MAJOR 1
#define SPDLOG_VER_MINOR 3
#define SPDLOG_VER_PATCH 1

**Comment by tt4g** [comment]
Remove `-std=c++11` from `CMAKE_CXX_FLAGS` and set `CMAKE_CXX_STANDARD` to `11`.

```diff
cmake_minimum_required(VERSION 3.8)
-set(CMAKE_CXX_FLAGS "-std=c++11 -pthread -fPIC -Wall -fmessage-length=0")
-set(CMAKE_C_FLAGS "-std=c99 -Wall -fmessage-length=0")
set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_NO_SYSTEM_FROM_IMPORTED ON)

PROJECT(libom)
+set(CMAKE_CXX_FLAGS "-pthread -fPIC -Wall -fmessage-length=0")
+set(CMAKE_C_FLAGS "-std=c99 -Wall -fmessage-length=0")
+set(CMAKE_CXX_STANDARD 11)
+set(CMAKE_CXX_STANDARD_REQUIRED on)
include_directories(./internal)
include_directories(./internal/crypto)
include_directories(./internal/spdlog)
include_directories(./internal/spdlog/details)
include_directories(./internal/spdlog/fmt)
include_directories(./internal/spdlog/fmt/bundled)
include_directories(./internal/spdlog/sinks)
include_directories(./message)
include_directories(../libssl/openssl)
include_directories(./)

aux_source_directory(internal DIR_OM_INTERNAL)
aux_source_directory(internal/crypto DIR_OM_INTERNAL_CRYPTO)
aux_source_directory(internal/spdlog DIR_OM_INTERNAL_SPDLOG)
aux_source_directory(internal/spdlog/details DIR_OM_INTERNAL_SPDLOG_DETAILS)
aux_source_directory(internal/spdlog/fmt DIR_OM_INTERNAL_SPDLOG_FMT)
aux_source_directory(internal/spdlog/fmt/bundled DIR_OM_INTERNAL_SPDLOG_FMT_BUNDLED)
aux_source_directory(internal/spdlog/sinks DIR_OM_INTERNAL_SPDLOG_SINKS)

aux_source_directory(message DIR_OM_MESSAGE)

##########################################################
add_library(om SHARED
${DIR_OM_INTERNAL}
${DIR_OM_INTERNAL_CRYPTO}

    ${DIR_OM_INTERNAL_SPDLOG}
    ${DIR_OM_INTERNAL_SPDLOG_DETAILS}
    ${DIR_OM_INTERNAL_SPDLOG_FMT}
    ${DIR_OM_INTERNAL_SPDLOG_SINKS}

    ${DIR_OM_MESSAGE}
    main.cpp
    logger.cpp
    )
target_link_libraries(
om
/mnt/d/code/LTE—V2X/libssl/Debug/libcrypto.so
/mnt/d/code/LTE—V2X/libssl/Debug/libssl.so
)
```

See: https://stackoverflow.com/a/46330404
     https://cliutils.gitlab.io/modern-cmake/chapters/features/cpp11.html

**Comment by wangwenqiangGitHub** [comment]
> Remove `-std=c++11` from `CMAKE_CXX_FLAGS` and set `CMAKE_CXX_STANDARD` to `11`.
> 
> ```diff
> cmake_minimum_required(VERSION 3.8)
> -set(CMAKE_CXX_FLAGS "-std=c++11 -pthread -fPIC -Wall -fmessage-length=0")
> -set(CMAKE_C_FLAGS "-std=c99 -Wall -fmessage-length=0")
> set(CMAKE_SYSTEM_NAME Linux)
> 
> set(CMAKE_NO_SYSTEM_FROM_IMPORTED ON)
> 
> PROJECT(libom)
> +set(CMAKE_CXX_FLAGS "-pthread -fPIC -Wall -fmessage-length=0")
> +set(CMAKE_C_FLAGS "-std=c99 -Wall -fmessage-length=0")
> +set(CMAKE_CXX_STANDARD 11)
> +set(CMAKE_CXX_STANDARD_REQUIRED on)
> include_directories(./internal)
> include_directories(./internal/crypto)
> include_directories(./internal/spdlog)
> include_directories(./internal/spdlog/details)
> include_directories(./internal/spdlog/fmt)
> include_directories(./internal/spdlog/fmt/bundled)
> include_directories(./internal/spdlog/sinks)
> include_directories(./message)
> include_directories(../libssl/openssl)
> include_directories(./)
> 
> aux_source_directory(internal DIR_OM_INTERNAL)
> aux_source_directory(internal/crypto DIR_OM_INTERNAL_CRYPTO)
> aux_source_directory(internal/spdlog DIR_OM_INTERNAL_SPDLOG)
> aux_source_directory(internal/spdlog/details DIR_OM_INTERNAL_SPDLOG_DETAILS)
> aux_source_directory(internal/spdlog/fmt DIR_OM_INTERNAL_SPDLOG_FMT)
> aux_source_directory(internal/spdlog/fmt/bundled DIR_OM_INTERNAL_SPDLOG_FMT_BUNDLED)
> aux_source_directory(internal/spdlog/sinks DIR_OM_INTERNAL_SPDLOG_SINKS)
> 
> aux_source_directory(message DIR_OM_MESSAGE)
> 
> ##########################################################
> add_library(om SHARED
> ${DIR_OM_INTERNAL}
> ${DIR_OM_INTERNAL_CRYPTO}
> 
>     ${DIR_OM_INTERNAL_SPDLOG}
>     ${DIR_OM_INTERNAL_SPDLOG_DETAILS}
>     ${DIR_OM_INTERNAL_SPDLOG_FMT}
>     ${DIR_OM_INTERNAL_SPDLOG_SINKS}
> 
>     ${DIR_OM_MESSAGE}
>     main.cpp
>     logger.cpp
>     )
> target_link_libraries(
> om
> /mnt/d/code/LTE—V2X/libssl/Debug/libcrypto.so
> /mnt/d/code/LTE—V2X/libssl/Debug/libssl.so
> )
> ```
> 
> See: https://stackoverflow.com/a/46330404
> https://cliutils.gitlab.io/modern-cmake/chapters/features/cpp11.html

still erro

**Comment by tt4g** [comment]
If you can build it on the command line, then it is a problem with your CMake project.
Can you provide commands for CMake to build your project?

**Comment by tt4g** [comment]
I investigated the old spdlog source and found the code to generate periodic_worker at line 153 in v1.3.1.

https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/details/registry.h#L149-L154

The definition of `spdlog::details::make_unique` can be found here:

https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/common.h#L229-L241

The error you provided shows `std::get<0>`, so the source and error messages do not match.

Are you guys modifying the spdlog source?
If so, please provide the modified source so that we can find the cause of the error.

**Comment by wangwenqiangGitHub** [comment]
> I investigated the old spdlog source and found the code to generate periodic_worker at line 153 in v1.3.1.
> 
> https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/details/registry.h#L149-L154
> 
> The definition of `spdlog::details::make_unique` can be found here:
> 
> https://github.com/gabime/spdlog/blob/a7148b718ea2fabb8387cb90aee9bf448da63e65/include/spdlog/common.h#L229-L241
> 
> The error you provided shows `std::get<0>`, so the source and error messages do not match.
> 
> Are you guys modifying the spdlog source?
> If so, please provide the modified source so that we can find the cause of the error.

yes, we writed a class inherit spdlog::formatte and base_sink<Mutex>

**Comment by tt4g** [comment]
The problem with the modified source code is not clear to me.

To help you solve problem, please provide the following

* Full compile error log
* Compile command with options

**Comment by wangwenqiangGitHub** [comment]
> The problem with the modified source code is not clear to me.
> 
> To help you solve problem, please provide the following
> 
> * Full compile error log
> * Compile command with options

I have sovle this problem , thanks suport, it's file include in CMakeLits.txt problem
