### ISSUE TITLE
Release 1.8.5 failing tests in Build2 CI

### ISSUE THREAD

**Issue by Wmbat** [gabime/spdlog#1896]
Hi, I'm the maintainer of the **build2** package of [spdlog](https://github.com/build2-packaging/spdlog) and while running our CI, I noticed some errors in the unit tests. The errors where not present when I ran the CI for 1.8.2 or 1.8.3, but appeared in 1.8.5. 

Here is all the CI builds for version [1.8.3](https://ci.cppget.org/@9a574958-b43c-4f7c-be62-ec0d00d10f63). apart from a few warnings in some windows builds. It all worked fine.

Once we reach version [1.8.5](https://ci.cppget.org/@a8840e0a-52b8-45ad-8bd3-80c16a2b062e). A sizeable proportion of our CI seem to [fail](https://ci.cppget.org/@a8840e0a-52b8-45ad-8bd3-80c16a2b062e?builds=&pv=&tc=*&cf=&mn=&tg=&rs=error), despite 1.8.5 bringing only minor changes. I believe some of the CI errors can be traced back to this [commit](https://github.com/gabime/spdlog/commit/7b2776fdc78300323d65f9994e09e31815a709d8)

I would also like to point out that both CIs had warnings in some Windows builds relating to DLL exportation on classes inheriting from standard library classes.

**Comment by gabime** [comment]
strange.. how come it passes the travis/appveyor tests? different compile flags?

**Comment by Wmbat** [comment]
Well, It's not all build configs that are currently failing. But all of the errors seem related to this [test case](https://github.com/gabime/spdlog/commit/7b2776fdc78300323d65f9994e09e31815a709d8#diff-60ebf3f4061f0ec2c457416973042bc39f8d9bb73733ad8b121411e466e773a0R60) with this specific function being the error. `spdlog::level::set_string_view(spdlog::level::info, "INF");` 
You can see that it's not actually setting the underlying string value, 
`REQUIRE( spdlog::level::to_string_view(spdlog::level::info) == "INF" ) with expansion: { 'i', 'n', 'f', 'o' } == "INF"`. I doubt compilation flags would cause an error like that. 

I'm a bit busy at the moment, but I will try to investigate more on why the function doesn't work when I have more time
