### ISSUE TITLE
Using external fmt results in missing header `spdlog/fmt/bundled/core.h`

### ISSUE THREAD

**Issue by doronbehar** [gabime/spdlog#1897]
I'm trying to use spdlog as a dependency to build a certain package on NixOS and I stumbled upon this error when building that package:

```
/nix/store/x5q48dl920xmrxyjwjgnmcjgxg1706hs-spdlog-1.8.5-dev/include/spdlog/fmt/fmt.h:22:10: fatal error: spdlog/fmt/bundled/core.h: No such file or directory
    22 | #include <spdlog/fmt/bundled/core.h>
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It makes sense because NixOS sets:

https://github.com/NixOS/nixpkgs/blob/1ca0f5bafef272b50b5b8764fa0aa77201e2dc11/pkgs/development/libraries/spdlog/default.nix#L20-L27 :

```nix
      cmakeFlags = [
        "-DSPDLOG_BUILD_SHARED=${if stdenv.hostPlatform.isStatic then "OFF" else "ON"}"
        "-DSPDLOG_BUILD_STATIC=${if stdenv.hostPlatform.isStatic then "ON" else "OFF"}"
        "-DSPDLOG_BUILD_EXAMPLE=OFF"
        "-DSPDLOG_BUILD_BENCH=OFF"
        "-DSPDLOG_BUILD_TESTS=ON"
        "-DSPDLOG_FMT_EXTERNAL=ON"
      ];
```

I read spdlog's `CMakeLists.txt` and I noticed:

https://github.com/gabime/spdlog/blob/be14e60d9e8be31735dd9d2d132d8a4cd3482165/CMakeLists.txt#L87-L89

And that these files are not installed unless both `SPDLOG_FMT_EXTERNAL` flags are off:

https://github.com/gabime/spdlog/blob/be14e60d9e8be31735dd9d2d132d8a4cd3482165/CMakeLists.txt#L278-L281

Why are these flags mutually exclusive? Perhaps there should be only 1 flag that if set, will make also `spdlog/fmt/fmt.h` not include `fmt` in that path, but in the path where it was found during build?

OTH I notice that `spdlog/fmt/fmt.h` has:

```
#else // SPDLOG_FMT_EXTERNAL is defined - use external fmtlib
#include <fmt/core.h>
#include <fmt/format.h>
#endif
```

So using external fmt really works if I set directly in cflags `-DSPDLOG_FMT_EXTERNAL`. Perhaps I'm doing something wrong when I add spdlog to my project:

```cmake
  find_package(spdlog)
  target_link_libraries(mytarget spdlog)
```

Regards.

**Comment by tt4g** [comment]
`SPDLOG_FMT_EXTERNAL` macro should be added to the compiler options in `target_compile_definitions()`.

https://github.com/gabime/spdlog/blob/be14e60d9e8be31735dd9d2d132d8a4cd3482165/CMakeLists.txt#L183-L184

Can you check the compilation flags generated by CMake?

**Comment by doronbehar** [comment]
> Can you check the compilation flags generated by CMake?

I'm sorry but I'm not sure how to do that, I'm probably a big noob with cmake, I'm just trying to package a certain project for NixOS that requires spdlog and some modifications to it's `CMakeLists.txt`. I will probably have to learn cmake better at some point but it will take time.

**Comment by breakds** [comment]
@doronbehar I stumbled this issue as well while building something for NixOS. After a bit researching I found that

The line ` #include <spdlog/fmt/bundled/core.h>` is guarded by `#if !defined(SPDLOG_FMT_EXTERNAL)`, which means that as long as `SPDLOG_FMT_EXTERNAL` is defined (VERY IMPORTANT, it should be defined for your compilation target), that offending `#include` line will be NOOP.

Although in the `.nix` file that packages `spdlog` we have `-DSPDLOG_FMT_EXTERNAL=ON`, but that does not propagate to your project that depends on `spdlog`. This means that in your project, assuming you have a target called `A`:

``` cmake
add_library(A OBJECT)
target_link_libraries(A
    PRIVATE spdlog:;spdlog)
```

You should add that definition too with

``` cmake
target _compile_definitioins(A PRIVATE SPDLOG_FMT_EXTERNAL)
```

Or, if you have a lot of targets depending on `spdlog` and would like to have this definition for all targets by default, you probably want to add this to your **TOP-LEVEL** `CMakeLists.txt`:

``` cmake
add_compile_definitions(SPDLOG_FMT_EXTERNAL)
```

Hope this helps anyone who find this issue.
