### ISSUE TITLE
Incorrect path or missing files when #include'ing spdlog via vcpkg

### ISSUE THREAD

**Issue by ifexception** [gabime/spdlog#1910]
Hi all

I've installed spdlog via vcpkg and the recent update to 1.8.5 has yielded a problem with a `#include` file:

> C:\Microsoft\vcpkg\installed\x64-windows\include\spdlog\fmt\chrono.h(17,10): fatal error C1083: Cannot open include file: 'spdlog/fmt/bundled/chrono.h': No such file or directory

This didn't happen on the previous versions...

The file in question: `chrono.h`
![image](https://user-images.githubusercontent.com/17222073/113893620-7d376300-97c7-11eb-9d51-e34726a8b9bd.png)

vcpkg directory:
![image](https://user-images.githubusercontent.com/17222073/113893817-a952e400-97c7-11eb-87a6-7c7348a803c8.png)

**Comment by gabime** [comment]
Seems like a vcpkg problem. Please open the issue in the vcpkg repo
