### ISSUE TITLE
CMake build error when building for Android

### ISSUE THREAD

**Issue by vladimir-voinea** [gabime/spdlog#1915]
Hi,

I am using spdlog as a submodule in my project. I include it via add_subdirectory and the build works fine when building via MSVC, however if I build it as part of an Android studio C++ project, via CMake, I get the following error:

```
C:\Users\Vladimir\Documents\GitHub\ndk-samples\gles3jni\app\src\main\cpp\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at C:\Users\Vladimir\Documents\GitHub\ndk-samples\gles3jni\app\src\main\cpp\vr\dependencies\spdlog\CMakeLists.txt:212 (target_link_libraries):
  Cannot specify link libraries for target "spdlog_header_only" which is not
  built by this project.
```
Coming from this line in spdlog/CMakeLists.txt (212):
`
 target_link_libraries(spdlog_header_only INTERFACE log)
`

If I comment the above line of code, the build succeeds. Also I am not defining any extra CMake variables for spdlog, just building it out of the box. Using branch v2.x

**Comment by gabime** [comment]
Branch v2.x is not supported. Please use v1.x branch
