### ISSUE TITLE
std::pair not formattable despite custom operator definition

### ISSUE THREAD

**Issue by zonradkuse** [gabime/spdlog#1917]
Hi!

I am using `std::pair` in my code and cannot get it logged. My header file in `utils/ostream_operators.h` looks like the following

```C++
#include <utility>
#include "spdlog/fmt/ostr.h"
#include "spdlog/spdlog.h"

// excluded a few more custom operators for map and vector

template<typename T1, typename T2>
std::ostream &operator<<(std::ostream &os, const std::pair<T1, T2> &v) {
    return os << "(" << v.first << ", " << v.second << ")";
}
```

Minimal failing gtest in the project
```C++
#include "utils/ostream_operators.h"

#include <gtest/gtest.h>


TEST(TestPlayground, Ostream) {
    // FAILS
    auto pair = std::make_pair(true, false);
    spdlog::info("{}", pair);

    // WORKS
    std::stringstream s;
    s << pair;
    spdlog::info("{}", s.str());
}
```

Interesting is that some other operators like vector and map seem to compile within the project but don't when trying to reproduce the issue in a small setting. Unfortunately, I can't share to code, yet. However, there are shared libraries. The most high-level library is the only one using spdlog besides the main application.

Could you maybe point me to what I've been doing wrong? Let me know how I can support you. Thank you!

Best,
Johannes

**Comment by gabime** [comment]
Maybe try fmt ranges.h instead? see https://github.com/gabime/spdlog/issues/1874

**Comment by zonradkuse** [comment]
Thank you! I was hoping to avoid any additional code in the log call and could stick with operator overloading. However, I will give it a shot. Do you maybe have a clue what the issue could be or a theory what the cause could be?

**Comment by gabime** [comment]
Not sure. See the end of the thread in https://github.com/gabime/spdlog/issues/1227 for possible solution

**Comment by zonradkuse** [comment]
That helped thank you very much! For anyone encountering a similar issue. For standard containers wrapping the operator definitions into `namespace std` did the trick for me. #1227 has a really neat in-depth explanation at the very end.
