### ISSUE TITLE
cross compile error

### ISSUE THREAD

**Issue by Handy-xing** [gabime/spdlog#1934]
Hello,
 when I use cross compiler to compil spdlog,there are some errors:
arm-linux-gnueabi-g++ -std=c++11 main.cpp 
main.cpp:2:45: fatal error: spdlog/sinks/stdout_color_sinks.h: No such file or directory
 #include "spdlog/sinks/stdout_color_sinks.h"
                                             ^
compilation terminated.

but when I use normal g++,it's OK
g++ -std=c++11 main.cpp

I don't know why, if you know how, please let me know,
Thanks!

**Comment by tt4g** [comment]
Perhaps the default include directory is different.
`g++` includes the user include directory such as `/usr/local/include` and `/usr/include` in the default include path.
But `arm-linux-gnueabi-g++` does not seem to include these.

Try adding include path with `-I` option, e.g. `-I/usr/local/include`.

Helpful Links:
* https://stackoverflow.com/questions/4980819/what-are-the-gcc-default-include-directories/19839946
* https://askubuntu.com/questions/947954/wrong-default-include-directories-for-clang-cross-compile

**Comment by Handy-xing** [comment]
> Perhaps the default include directory is different.
> `g++` includes the user include directory such as `/usr/local/include` and `/usr/include` in the default include path.
> But `arm-linux-gnueabi-g++` does not seem to include these.
> 
> Try adding include path with `-I` option, e.g. `-I/usr/local/include`.
> 
> Helpful Links:
> 
> * https://stackoverflow.com/questions/4980819/what-are-the-gcc-default-include-directories/19839946
> * https://askubuntu.com/questions/947954/wrong-default-include-directories-for-clang-cross-compile

thanks for your help，I solved the problem after using arm-linux-gnueabi-g++ -I/spdlog/include method, thanks again
