### ISSUE TITLE
cmake error when include <spdlog/spdlog.h> in multiple files

### ISSUE THREAD

**Issue by dlc1994** [gabime/spdlog#1935]
here is my dirs:
- project 
- -dir1
- --a.h
- -dir2
- --b.h
when a.h include <spdlog/spdlog.h> there is no error
but when b.h include <spdlog/spdlog.h> there generates many error, the first is

.../spdlog/fmt/bundled/format.h:89:30: error: missing binary operator before token "("
 #  if FMT_HAS_CPP17_ATTRIBUTE(maybe_unused)

**Comment by dlc1994** [comment]
I found out that it was caused by external usage of fmt, so the question becomes how to use external fmt package and header-only spdlog simultaneously

**Comment by tt4g** [comment]
Must define `SPDLOG_FMT_EXTERNAL` macro if using external fmt.

https://github.com/gabime/spdlog/blob/100f30043f33277122e0991c83845a2617172ffd/include/spdlog/fmt/fmt.h#L13-L27

https://github.com/gabime/spdlog/blob/100f30043f33277122e0991c83845a2617172ffd/CMakeLists.txt#L176-L196
