### ISSUE TITLE
Custom Type Printing not working after spdlog upgrade

### ISSUE THREAD

**Issue by KerstinKeller** [gabime/spdlog#1936]
I am porting code from an ancient spdlog version to the newest 1.8.5.
However logging custom types, I now get the error:
```
error C2338: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt (compiling source file algorithm.cpp)
```

I have implemented a `operator<<` for that type, and the code also has a `#include <spdlog/fmt/ostr.h>`.
Is it expected to work or do I need to implement a special formatter now?
According to the [sample](https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/example/example.cpp#L189-L190) it should work.

In another issues I also found information about including `#include "spdlog/fmt/bundled/ranges.h`? The type which I am trying to print is a `std::vector` of a custom type. 

Thanks for the clarification.

**Comment by gabime** [comment]
For vectors it is recommended to use fmt’s ranges.h.
If this won’t help I think recommended fmt way these days is to implement `formatter<T>`  and implement parse and format methods. see https://fmt.dev/latest/api.html#format-api .
