### ISSUE TITLE
Using spdlog with FreeRTOS or RTEMS

### ISSUE THREAD

**Issue by robamu** [gabime/spdlog#1939]
I'm interested in using this library for a project which might be run on an embedded system using real-time operating systems like the ones mentioned above. Would it in principle be possible to use the logger with those RTOSes in some way? There is no std::mutex and regular std::thread support when using those RTOSes, but console printout generally works if the lower level syscalls forward the stdout and stderr output via something like a UART, and this is often times the cause for larger MCUs like the STM32H7. Is it possible to implement a sink which uses the FreeRTOS or RTEMS Mutex API instead of a std::mutex (single-threaded would be okay for now) ? Has anyone attempted this yet or was able to make spdlog work with thoses RTOSes?

Thanks a lot in advance!

**Comment by gabime** [comment]
The _st sinks are using a null mutex, so perhaps it would be possible.

**Comment by rmspacefish** [comment]
I tried compiling our project where spdlog works in the hosted versions for FreeRTOS, and it failed because the Threads package was not found. At the very least, this would required disabling this in `CMake` optionally.. Is it even possible to compile without Threads?

**Comment by gabime** [comment]
Not sure. You can try and see

**Comment by minhleGremsy** [comment]
Hi, I'm using spdlog in my embedded project with STM32 and FreeRTOS. But I cannot build successfully because spdlog requires std::thread and std::mutex but they are not available in arm-none-eabi-gcc. Has any one integrate spdlog to embedded project successfully? How to build spdlog without thread and mutex? Thanks.

**Comment by gabime** [comment]
This would require changes in the spdlog code. PR is welcome.

**Comment by mincequi** [comment]
I tried to use spdlog on a Raspberry Pi Pico and started a fork without using Threads and mutexes, but concluded that this change exceeds my resources in terms of available time.

However, https://github.com/SergiusTheBest/plog is an alternative that works very will with RTEMS.
