### ISSUE TITLE
Build failure with current fmt head branch

### ISSUE THREAD

**Issue by jcelerier** [gabime/spdlog#1941]
Hello,
since fmt at commit fmtlib/fmt@16f2ef91ab4218004d0f034f0b7cd6400bef955f

spdlog does not build, with the following error on win32 (latest MSVC):
```
spdlog\include\spdlog\common-inl.h(61,53): 
error C2664: 
'void fmt::v7::format_system_error(fmt::v7::detail::buffer<T> &,int,const char *) noexcept': 
cannot convert argument 3 from 'const std::string' to 'const char *'
          with
          [
              T=char
          ]
```

Not critical, but a heads-up :)

**Comment by jcelerier** [comment]
(small heads-up to @vitaut also in case the issue is in fmt instead of spdlog?)

**Comment by FreezePhoenix** [comment]
Believe it's because of the fact that FMT changed a handful of things, and Spdlog's local copy of the FMT API isn't synced.

**Comment by vitaut** [comment]
This is one of the `system_error`-related changes made in preparation for the major release. The (obvious) fix is to add `.c_str()`.

**Comment by FreezePhoenix** [comment]
Side note that using the latest releases of both libspdlog and libfmt results in some unresolved symbols when trying to use them.

**Comment by lgbaldoni** [comment]
fmt 1.8.0 released and build failing.

**Comment by gabime** [comment]
Fixed in latest commit
