### ISSUE TITLE
default registry and custom logger not working properly (Qt)

### ISSUE THREAD

**Issue by LeKristapino** [gabime/spdlog#1943]
It seems that when using spdlog in Qt, default registry doesn't work properly. It seems that custom made logger is applied quite randomly. We use stdoutput and daily file sinks but in stdouput you can see that logger sometimes does not apply custom formatting.

example log output:

```
[2021-05-15 11:08:50.721] [info] MainWindow::serviceConnected - true
|05/15/21|11:08:50|info    |        MainWindow::checkAllDevicesConnected - false         
```

MainWindow.cpp relevant code:
```cpp
void MainWindow::serviceConnected(bool connected) {
        if (connected) {
            ui->servicesStatus->setDeviceReady(connected);
            spdlog::info("MainWindow::serviceConnected - true");
        } 
    }
....

bool MainWindow::checkAllDevicesConnected() {
    bool allConnected = true;
    ...
    spdlog::info("MainWindow::checkAllDevicesConnected - {}", allConnected)
    return allConnected;
}
```

Our spdlog setup in main.cpp

```cpp
std::vector<spdlog::sink_ptr> sinks;
    //create a sink for terminal output and log output
    sinks.push_back(std::make_shared<spdlog::sinks::stdout_color_sink_mt>());
    sinks.push_back(std::make_shared<spdlog::sinks::daily_file_sink_mt>("log/my_logs", 0, 0, false, 10));

    //combine sinks, register new, combined sink and make it default logger
    std::shared_ptr<spdlog::logger> combined_logger = std::make_shared<spdlog::logger>("logger", begin(sinks), end(sinks));
    spdlog::register_logger(combined_logger);
    spdlog::set_default_logger(combined_logger);

    //set log level and formatting pattern
    //"trace", "debug", "info", "warning", "error", "critical", "off"
    spdlog::set_level(spdlog::level::from_str(settings->logSeverity().toStdString()));
    spdlog::flush_on(spdlog::level::level_enum::trace);
    spdlog::set_pattern("%^|%-10D|%-2H:%-2M:%-2S|%-8l|%-64v|%$");
    spdlog::info("Application started. Version: {}", QCoreApplication::applicationVersion().toStdString());
```

Also in some cases if I try to use `spdlog::get("logger")->info("whatever")` the App will crash because nothing is returned from the registry. It seems quite weird since we can't find a clear pattern for when the custom logger is ignored and when it is used. Even within one file.

**Comment by tt4g** [comment]
Is `MainWindow` created after the initialization of spdlog is completed?
Once the Qt object is created and the event loop starts, the Qt object will access spdlog before it is initialized, so you should not create the Qt object before the spdlog is initialized.

**Comment by LeKristapino** [comment]
@tt4g Yes, spdlog is initialized before MainWindow is created. But I managed to fix this issue by using this solution: 

https://spdlog.docsforge.com/v1.x/how-to-use-spdlog-in-dlls/

**Comment by tt4g** [comment]
Right. It is necessary to devise a way to initialize spdlog in the library.
