### ISSUE TITLE
Chinese support bug

### ISSUE THREAD

**Issue by Hisos** [gabime/spdlog#1944]
// in qt

#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/stdout_sinks.h"
#include <QApplication>

int main(int argc, char *argv[])
{
    auto logger = spdlog::basic_logger_mt("basic_logger", "logs/basic-log.txt");
    SPDLOG_LOGGER_INFO(logger, "hello hisos 你");
}

// "hello hisos 你" can't build, error: C2001: 常量中有换行符, error: C1057: 宏扩展中遇到意外的文件结束
// "hello hisos 你好" build succeed
// "hello hisos 你好你" can't build, error: C2001: 常量中有换行符, error: C1057: 宏扩展中遇到意外的文件结束
// "hello hisos 你好你好" build succeed
// conclusion: If the second param of SPDLOG_LOGGER_INFO ends in even chinese, build succeed. Otherwise, failed!

**Comment by keefo** [comment]
I can compile and output Chinese without a problem. 
I suspect it is your source code encoding issue.  Please confirm that your source code is utf8 encoding.

**Comment by Hisos** [comment]
Ok, I have a try.
