### ISSUE TITLE
Update cmake_minimum_requrired to 3.13

### ISSUE THREAD

**Issue by jafj** [gabime/spdlog#1945]
I am using spdlog as CMake subdirectory (through ```add_subdirectory```), and am unable to set configuration options (such as ```SPDLOG_FMT_EXTERNAL```) in my parent CMakeLists.txt file. This is because ```cmake_minimum_required(VERSION 3.10)``` unsets CMake policy ```CMP0077```.

```CMP0077``` unsets normal variables (i.e. a parent-project required setting for ```SPDLOG_FMT_EXTERNAL``` etc), and forces the default option. I can not force the policy to be set as the current ```cmake_minimum_required(VERSION 3.10)``` overrides my own policy / version settings.

The new (more intuitive) behaviour was introduced in cmake 3.13: https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077

**Comment by jafj** [comment]
An alternative, which is what Google's Abseil library does in order to maintain compatability with earlier cmake versions, is to add the following in their CMake file:

```
if (POLICY CMP0077)
  cmake_policy(SET CMP0077 NEW)
endif (POLICY CMP0077)
```

**Comment by gabime** [comment]
> if (POLICY CMP0077)
  cmake_policy(SET CMP0077 NEW)
endif (POLICY CMP0077)

Agreed. PR is welcome

**Comment by jafj** [comment]
Done: #1946
