### ISSUE TITLE
[MSVC][Windows] binskim security check error due to `__declspec(safebuffers)`

### ISSUE THREAD

**Issue by LoSealL** [gabime/spdlog#1947]
Hi

[binskim](https://github.com/microsoft/binskim) is a Microsoft security check tool for binary files.
In [format.h](https://github.com/gabime/spdlog/blob/be14e60d9e8be31735dd9d2d132d8a4cd3482165/include/spdlog/fmt/bundled/format.h#L982) there is a macro that disables the `/GS` by declaring `__declspec(safebuffers)`, which raised the error in the check report.

We could delete the macro ourselves directly, the only thing we wonder is that how much performance it will impact? Any idea that introduces this macro?

**Comment by gabime** [comment]
This file belongs to the {fmt} library used by spdlog. Please reopen this issue in the fmt [repo](https://github.com/fmtlib/fmt).

**Comment by LoSealL** [comment]
Thanks. I saw fmt has removed this part of codes in the master branch.
