### ISSUE TITLE
can't use %+, %n for dll

### ISSUE THREAD

**Issue by hands133** [gabime/spdlog#1950]
Good evening, I've encountered a problem with dlls.
Well I want to use spdlog in a class with static variables in "log.h", with VS2019, Win10:
```cpp
#pragma once

#include <memory>

#include "core.h"
#include "spdlog/spdlog.h"

namespace hazel {

	class HAZEL_API Log
	{
	public:
		static void Init();

		static std::shared_ptr<spdlog::logger>& GetCoreLogger() { return s_CoreLogger; }
		static std::shared_ptr<spdlog::logger>& GetClientLogger() { return s_ClientLogger; }

	private:
		static std::shared_ptr<spdlog::logger> s_CoreLogger;
		static std::shared_ptr<spdlog::logger> s_ClientLogger;
	};

}
```
and then initialize variables in "log.cpp"
```cpp
#include "log.h"

#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/async.h"

namespace hazel {

	std::shared_ptr<spdlog::logger> Log::s_CoreLogger;
	std::shared_ptr<spdlog::logger> Log::s_ClientLogger;

	void Log::Init()
	{
		//https://hub.fastgit.org/gabime/spdlog/wiki/3.-Custom-formatting
		spdlog::set_pattern("%^[%c] [%l] : %v%$");
		
		s_CoreLogger = spdlog::stdout_color_mt("HAZEL");
		s_CoreLogger->set_level(spdlog::level::level_enum::trace);

		s_ClientLogger = spdlog::stdout_color_mt("APP");
		s_ClientLogger->set_level(spdlog::level::level_enum::trace);
	}
}
```
Then I export the code as dll file for function `main()`:
```cpp
int main(int argc, char* argv[])
{
	std::cout << "Hazel Engine Start!" << std::endl;

        hazel::Log::Init();
	hazel::Log::GetCoreLogger()->warn("Initialized Log!");
	hazel::Log::GetClientLogger()->info("Hello!");

	spdlog::shutdown();


	auto app = hazel::CreateApplication();
	app->Run();
	delete app;
	
	return 0;
}
```
But something wrong happened if I use %n, %+, the VS would report runtime error in file <xutility>:4382 :0xC0000005, access 0xFFFFFFFFFFFFFFFF.
Then I tried with %s,output nothing in the position of %s. %v and %T works well.
I've read the [article](https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs), it seems not working.
In [https://hub.fastgit.org/gabime/spdlog/issues/1562](https://hub.fastgit.org/gabime/spdlog/issues/1562), said that I should use function to access variable, or `extern` variable, but how?
Thanks a lot for helping!

**Comment by tt4g** [comment]
Don't use global variable `std::shared_ptr<spdlog::logger>`, Libraries and applications manage objects with different memory storage.
( below C++17), `static` variables declared in a class are placed at different addresses in the application and the library.

And you must not use `std::shared_ptr&` either.

See https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

**Comment by hands133** [comment]
> Don't use global variable `std::shared_ptr<spdlog::logger>`, Libraries and applications manage objects with different memory storage.
> ( below C++17), `static` variables declared in a class are placed at different addresses in the application and the library.
> 
> And you must not use `std::shared_ptr&` either.
> 
> See https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

Thanks for replying,  surprisingly it works good now without any changes, and I don't know why. Maybe I would launch an issue next time for any similar problems, thanks a lot.
