### ISSUE TITLE
Add FMT_ENFORCE_COMPILE_STRING support

### ISSUE THREAD

**Issue by mrbald** [gabime/spdlog#1953]
Would be nice to have FMT_ENFORCE_COMPILE_STRING working.
It's pretty much a matter of wrapping format strings in calls to fmt::format into FMT_STRING() and using fmt::vstring for non-constexpr cases.

**Comment by gabime** [comment]
Latest version supports this under c++20

**Comment by mrbald** [comment]
Thanks!
