### ISSUE TITLE
async logger flush policy

### ISSUE THREAD

**Issue by 7starsea** [gabime/spdlog#1957]
Currently I am using async logger (spdlog-1.8.2) with the following logic
```
logger->set_pattern("%v");
logger->info("some comment");
logger->flush();

logger->set_pattern("%T,%v");
```
I notice that the info `some comment` used the new pattern `%T,%v`. 
After reading the `flush policy` doc, `flush` operation will return immediately. I am wondering is there any may to make sure that the info `some comment` uses the older pattern `%v`.

Thanks.

**Comment by gabime** [comment]
Indeed, flush is async in async logger. I don't see any easy way to  achieve this, except maybe custom sink.
