### ISSUE TITLE
Suggestion: add intermediate class for sinks logging to a file.

### ISSUE THREAD

**Issue by bartgol** [gabime/spdlog#1960]
I have a piece of code that creates a file sink (either basic or rotating), stored in a `base_sink` pointer. When we have to query the name of the file, we need to perform a cast to `basic_file_sink` to get the filename, and if the cast fails, cast to `rotating_file_sink`. It might be convenient to have an intermediate class `file_sink` that simply adds the virtual method `filename()`. Then, one can store a file sink as a ptr to `file_sink`, and directly query for the filename. Or, if this sink is stored among other kind of sinks, dyn cast _once_ to `file_sink` to get the file name.

**Comment by gabime** [comment]
Thanks. Need to consider this also for other common file operations(e.g. callbaks on file open closed, see #1225)
