### ISSUE TITLE
Suggestion: Update outdated wiki page on logging custom types

### ISSUE THREAD

**Issue by mdorier** [gabime/spdlog#1962]
The wiki page [here](https://github.com/gabime/spdlog/wiki/1.-QuickStart#log-user-defined-objects) provides a way of enabling logging custom types that no longer works (at least as of spdlog 1.8.4 and 1.8.5. It worked with 1.8.0. I don't know which version dropped this support). Googling for how to format custom types with spdlog only points back to this wiki page. I had to dig a closed issue on this repository to actually find out that now the right way of enabling custom type formatting is to specialize a `formatter<T>`, with a link pointing to [this documentation](https://fmt.dev/latest/api.html#format-api) for the `fmt` library. This documentation is not great, though, it would be good for the spdlog wiki to be updated.

Another suggestion would be for spdlog to re-enable the old way of formatting custom types (via ostream), in particular for the following reasons:
- Many projects that use the ostream approach now break because of the change;
- The ostream approach is arguably much simpler.

**Comment by gabime** [comment]
The wiki page is open for everyone to edit. You are welcome to edit it.

> Another suggestion would be for spdlog to re-enable the old way of formatting custom types (via ostream),

Ths old way is supported. see the official [example](https://github.com/gabime/spdlog/blob/a530b87fd0fcca818c4504f834340c5c263b3049/example/example.cpp#L223).  Perhaps (i am just guessing here) recent changes in fmt lib prevent some types to work.

**Comment by mdorier** [comment]
I will have to check: my code uses `std::ostream` directly, like in the first link I posted. The example you pointed out uses a template. Maybe that's what has changed in the fmt library?

**Comment by gabime** [comment]
Not sure. Please update if you find the cause.
