### ISSUE TITLE
about print "code file name" and "line number"

### ISSUE THREAD

**Issue by hctym1995** [gabime/spdlog#1963]
i already know how to print "file name" and " line number" separately by using MACRO

i want to konw how to print them use "multi-sink"

or it is impossible?

this is my test code In VS2019:

`#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // Must: define SPDLOG_ACTIVE_LEVEL before `#include "spdlog/spdlog.h"`

#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/sinks/rotating_file_sink.h"
#include "spdlog/sinks/basic_file_sink.h"

int main()
{
    auto console = spdlog::stdout_logger_mt("console");
    spdlog::set_default_logger(console);
    spdlog::set_pattern("%m-%d %H:%M:%S.%e [%^%4!l%$] [tid %5t] [%s:%!:%#] %v");

    SPDLOG_LOGGER_INFO(console, "log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 10] log with source info"
    SPDLOG_INFO("global log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 11] global logger with source info"

    console->info("source info is not printed"); // Console: "[source ] [function ] [line ] source info is not printed"
    
    auto file = spdlog::rotating_logger_mt("some_logger_name", "logs/rotating.txt", 1234, 1234);
    SPDLOG_LOGGER_INFO(file, "log with source info {}", 123);

    auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    console_sink->set_level(spdlog::level::warn);
    console_sink->set_pattern("[multi_sink_example] [%^%l%$] %v");

    auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("logs/multisink.txt", true);
    file_sink->set_level(spdlog::level::trace);

    //spdlog::logger logger("multi_sink", { console_sink, file_sink });
    auto logger = spdlog::logger("multi_sink", { console_sink, file_sink });
    logger.set_level(spdlog::level::debug);
    logger.set_pattern("%m-%d %H:%M:%S.%e [%^%4!l%$] [tid %5t] [%s:%!:%#] %v");
    logger.warn("this should appear in both console and file");
    logger.info("this message should not appear in the console, only in the file");
    SPDLOG_LOGGER_INFO(logger, "log with source info {}", 123);   //compile error:C2819
    
    return 0;
}`

**Comment by gabime** [comment]
The macro expects a pointer to logger. 

This should work:

```cpp
SPDLOG_LOGGER_INFO(&logger, "log with source info {}", 123);
```

**Comment by hctym1995** [comment]
it's useful. thank u so much!
