### ISSUE TITLE
spdlog header file conflicts with glm header file

### ISSUE THREAD

**Issue by HODAKdev** [gabime/spdlog#1966]
If I add spdlog.h into main so i get glm errors, why? Thanks for help :)
![wefwefwfe](https://user-images.githubusercontent.com/82084934/120836909-66628200-c566-11eb-839c-e02406ff62b7.PNG)

**Comment by gabime** [comment]
please post the full error messages.not the intellisense.

**Comment by HODAKdev** [comment]
> please post the full error messages.not the intellisense.


what exactly do you mean?

**Comment by HODAKdev** [comment]
![awdawdawd](https://user-images.githubusercontent.com/82084934/120894441-ac781e00-c618-11eb-9341-8eb67314b2c9.PNG)
![ewfwegreger](https://user-images.githubusercontent.com/82084934/120894442-ad10b480-c618-11eb-97e2-479b34f6568d.PNG)
![wefwefwef](https://user-images.githubusercontent.com/82084934/120894443-ad10b480-c618-11eb-86ae-3619f9018b14.PNG)

**Comment by HODAKdev** [comment]
okey i managed to fix it by deleting those floats :)
