### ISSUE TITLE
是否可以在同一个sink同时支持 async, rotating,daily

### ISSUE THREAD

**Issue by yzw88** [gabime/spdlog#1968]
你好，请教一个问题，如果日志  同时支持 异步输出，文件按照日期切割，文件到达指定大小切割呢？

**Comment by tt4g** [comment]
我不懂中文，所以我用翻译工具来翻译。

不幸的是，不支持同时支持日期和文件大小的旋转。
有实现每个旋转条件的sink。

* `spdlog::sinks::daily_file_sink`将按日期进行轮换。
* `spdlog::sinks::rotating_file_sink`按文件大小旋转。

任何带有后缀`*_mt`的sink，如`spdlog::sinks::daily_file_sink_mt`和`spdlog::sinks::rotating_file_sink_mt`都可以安全地与async logger一起使用。

---
I don't know Chinese, so I use a translation tool.

Unfortunately, rotations that support both date and file size are not supported.
There are sinks that implement each of the rotation conditions.

* `spdlog::sinks::daily_file_sink`. rotates by date.
* `spdlog::sinks::rotating_file_sink` rotates by file size.

Any `sink` with the suffix `*_mt` such as `spdlog::sinks::daily_file_sink_mt` and `spdlog::sinks::rotating_file_sink_mt` can be safely used with async logger.

**Comment by yzw88** [comment]
thanks
