### ISSUE TITLE
Elision of logging function call if not needed in Release mode

### ISSUE THREAD

**Issue by prittjam** [gabime/spdlog#1969]
Is there a way to set a compile flag such that the logging functions are elided from the generated code? This feature would be useful for performance critical code.

**Comment by tt4g** [comment]
You can use logging macro such as `SPDLOG_DEBUG`, `SPDLOG_LOGGER_DEBUG` `SPDLOG_TRACE`, SPDLOG_LOGGER_TRACE` and etc.
Look FAQ: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

These are declared here:

https://github.com/gabime/spdlog/blob/100f30043f33277122e0991c83845a2617172ffd/include/spdlog/spdlog.h#L241-L257

**Comment by prittjam** [comment]
Thanks for the response! Nice library and very useful...
