### ISSUE TITLE
Changed to CRLF format?

### ISSUE THREAD

**Issue by ichizok** [gabime/spdlog#197]
Out of curiosity, why did you change file-format LF to CRLF at https://github.com/gabime/spdlog/commit/495ecaeaee527c5e1468b0479d0d546346fe7665?
[astyle.sh](https://github.com/gabime/spdlog/blob/master/astyle.sh#L2) calls `dos2unix`, or this script isn't used anymore?

**Comment by gabime** [comment]
Good question.. Maybe the dos2unix command failed for some reason.. 
I will re format again

**Comment by ichizok** [comment]
I understand. Thank you 😃

**Comment by gabime** [comment]
Fixed in 0d26359856303d534d10d919c22d7441611b8a05
