### ISSUE TITLE
Faile logging vector<bool>

### ISSUE THREAD

**Issue by shipleyxie** [gabime/spdlog#1977]
```C++
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/fmt/bundled/ranges.h"
#include <vector>
using namespace std;
auto logger = spdlog::basic_logger_st("416", "416.txt");

int main(){
vector<bool> dp(5);
logger->info("{}", dp);
return 0;
}
```
And got following error:

>  error: static assertion failed: Cannot format an argument. To make type T formattable prov

change` vector<bool> dp(5);` to `vector<int> dp(5);` will fix this.
I use spdlog v1.x,  could you give me some suggestion how to log` vector<bool>` ?

**Comment by tt4g** [comment]
Use `fmt::join()` https://fmt.dev/latest/api.html#_CPPv2N3fmt4joinERR5Range11string_view

**Comment by shipleyxie** [comment]
Thanks! Now it works.
