### ISSUE TITLE
GetFileAttributesW not found WinU

### ISSUE THREAD

**Issue by VikingExplorer** [gabime/spdlog#198]
I'm building a Windows Universal project and I'm getting this error:

os.h(179): error C3861: 'GetFileAttributesW': identifier not found (compiling source file CouloirApplication.cpp)

Anyone come across this?

**Comment by VikingExplorer** [comment]
I think some more detail would be helpful:
1>  Log.cpp
1>c:\dev\couloir\3plibs\include\spdlog\details\os.h(179): error C3861: 'GetFileAttributesW': identifier not found
1>c:\dev\couloir\3plibs\include\spdlog\details\os.h(212): error C2679: binary '+': no operator found which takes a right-hand operand of type 'DWORD' (or there is no acceptable conversion)
1>  c:\dev\couloir\3plibs\include\spdlog\details\os.h(212): note: could be 'built-in C++ operator+(volatile const Platform::String ^, volatile const Platform::String ^)'
1>  c:\dev\couloir\3plibs\include\spdlog\details\os.h(212): note: or       'built-in C++ operator+(volatile const Platform::String ^, volatile const Platform::Object ^)'
1>  c:\dev\couloir\3plibs\include\spdlog\details\os.h(212): note: or       'built-in C++ operator+(volatile const Platform::Object ^, volatile const Platform::String ^)'
1>  c:\dev\couloir\3plibs\include\spdlog\details\os.h(212): note: while trying to match the argument list '(Platform::String ^, DWORD)'
1>c:\dev\couloir\3plibs\include\spdlog\details\os.h(212): error C2512: 'spdlog::spdlog_ex': no appropriate default constructor available
1>  c:\dev\couloir\3plibs\include\spdlog\details\os.h(212): note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by VikingExplorer** [comment]
It's interpreting a string constant as Platform::String

**Comment by Armagetron** [comment]
@VikingExplorer : I think your problem here is that the function [GetFileAttributes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364944%28v=vs.85%29.aspx) is only available with Win32 "desktop" apps and not on the Universal platform.

**Comment by VikingExplorer** [comment]
@Armagetron right, thanks!  I did figure that out, sorry I didn't update this. I also updated the code with the equivalent WinU code. I'm planning on pushing it and initiating a pull request at some point.

**Comment by gabime** [comment]
@VikingExplorer yes, a pull request with a fix will be most welcome

**Comment by VikingExplorer** [comment]
If anyone is waiting, sorry it's taking me a while to get back to WinU. I've been pulled onto several other priorities, but I'm definitely heading back to WinU, and will do a PR at that time.

**Comment by gabime** [comment]
great, thanks

**Comment by gabime** [comment]
@VikingExplorer any news?
