### ISSUE TITLE
Multi process basic logger "basic_logger_mt" is giving multiple log according to child for main process 

### ISSUE THREAD

**Issue by akash2826** [gabime/spdlog#1985]
Hi Gabime,

I am trying to setup multi proccess logging but i am facing issue for generation of multiple log for single line written in main process. below is the program I am executing and I am expecting only one line output in my log file.

[..]
#include <unistd.h>
#include <stdio.h>
#include <iostream>
#include "spdlog/spdlog.h"
#include <spdlog_setup/conf.h>
#include "spdlog/sinks/basic_file_sink.h"

int main()
{

    auto my_logger = spdlog::basic_logger_mt("basic_logger", "basic.txt");
    my_logger->info("Test File Logger {}", "test");
    // Creating first child
    int n1 = fork();

    // Creating second child. First child
    // also executes this line and creates
    // grandchild.
    int n2 = fork();

    if (n1 > 0 && n2 > 0) {
        printf("parent\n");
        printf("%d %d \n", n1, n2);
        printf(" my id is %d \n", getpid());
    }
    else if (n1 == 0 && n2 > 0)
    {
        printf("First child\n");
        printf("%d %d \n", n1, n2);
        printf("my id is %d  \n", getpid());
    }
    else if (n1 > 0 && n2 == 0)
    {
        printf("Second child\n");
        printf("%d %d \n", n1, n2);
        printf("my id is %d  \n", getpid());
    }
    else {
        printf("third child\n");
        printf("%d %d \n", n1, n2);
        printf(" my id is %d \n", getpid());
    }
    return 0;
}
 ========================
Output:
[..]
[2021-06-28 19:53:07.839] [basic_logger] [info] Test File Logger test
[2021-06-28 19:53:07.839] [basic_logger] [info] Test File Logger test
[2021-06-28 19:53:07.839] [basic_logger] [info] Test File Logger test
[2021-06-28 19:53:07.839] [basic_logger] [info] Test File Logger test
[..]

I am expecting it to show only one log.

Please Help on this and also please share any example for setting multiprocess logging.

Thanks 
Akash Mishra

**Comment by gabime** [comment]
It is not supported by spdlog. See https://github.com/gabime/spdlog/issues/937 for possible ways to make it work

**Comment by akash2826** [comment]
But how to stop it for creating it logs for child process also which current program is showing in which log is written in main process only but it is printing as many time child is created.

**Comment by gabime** [comment]
maybe try  SPDLOG_PREVENT_CHILD_FD macro

**Comment by akash2826** [comment]
Hi gabime,

It is not working I tried below option while building spdlog
"cmake -DSPDLOG_BUILD_EXAMPLE=ON -DSPDLOG_PREVENT_CHILD_FD=ON .."

kindly confirm if this option is correct or if there is any other method.

**Comment by gabime** [comment]
Yes. You can try this
