### ISSUE TITLE
Close a log file and start a new one at runtime without affecting logging efficiency

### ISSUE THREAD

**Issue by qiao-tw** [gabime/spdlog#1987]
Hi, thanks for the great library. I used it on an embedded Linux C++ project. Now we're interfacing some performance issues and I'm wondering whether I'm using this library correctly. Followings are the requirements of our logger:
1. Only 1 log file at a time. All threads write the log message to the same log file.
2. The logger should close the current log file and create a new one when 
  a) file size reaches a given maximum (e.g. 9999 lines)
  b) system date/time changed (logfile name should be changed accordingly)

In order to switch to the new log file at runtime and keep it thread-safe, I use mutex protection "every log" to prevent accessing to null pointer during the logfile switch.

Part of my implementation are as follows:
```c++
// this is the function called by differents threads, should be thread-safe
void Logger::DoLog(std::string message, int level)
{
    std::lock_guard<std::mutex> lock(mtx_file_logger); // mutex protection for all DoLog() call to make sure g_file_logger is not null
    if (!g_file_logger)
    {
        StartNewLog();
    }

    // if date/time changed, start a new log
    if (g_is_datetime_set && g_file_logger)
    {
        g_file_logger->info("system time updated, let's update file name");
        StartNewLog();
    }

    if (g_file_logger)
    {
        switch (level)
        {
        case INFO:
            g_file_logger->info(message.c_str());
            break;
        case WARN:
            g_file_logger->warn(message.c_str());
            break;
        case ERROR:
            g_file_logger->error(message.c_str());
            break;
        case FATAL:
            g_file_logger->critical(message.c_str());
            exit(1);
            break;
        default:
            g_file_logger->info(message.c_str());
            break;
        }
        ++line_count_;
        if (line_count_ == log_max_lines_)
        {
            StartNewLog();
        }
    } else
    {
        std::cerr << "g_file_logger is not initialized";
    }
}

bool Logger::StartNewLog()
{
    std::string full_path_file = /* function to get current system time and convert to string */
    std::cout << filename << std::endl;

    if (g_file_logger) {
        std::stringstream message;
        message << "Starting new log file: ";
        message << full_path_file;
        message << std::endl;
        g_file_logger->info(message.str().c_str());
    }

    if (g_file_logger) {
        g_file_logger->flush();
    }

    spdlog::drop("my_logger"); // Here g_file_logger is set to empty, right?
    g_file_logger = spdlog::basic_logger_mt("my_logger", full_path_file);
    spdlog::set_default_logger(g_file_logger);
    g_file_logger->set_pattern(LOG_FORMAT);
    spdlog::flush_every(std::chrono::seconds(1));

    line_count_ = 0;
    return true;
}

```

I'm wandering am I wrapping the loggger the right way? Should I use ```spdlog::basic_logger_mt``` or other? Is there any other thread-safe way to switch to another log file at runtime?

Thanks.

**Comment by hctym1995** [comment]
I think you can use "rotating_logger_mt" to instead of  "basic_logger_mt"
The "rotating_logger_mt" supports setting ths max_size of every logfile and the number of files,you can set ths max_fize is 1.
`#include "spdlog/sinks/rotating_file_sink.h"
void rotating_example()
{
    // Create a file rotating logger with 5mb size max and 3 rotated files
    auto max_size = 1048576 * 5;
    auto max_files = 3;
    auto logger = spdlog::rotating_logger_mt("some_logger_name", "logs/rotating.txt", max_size, max_files);
}`

**Comment by qiao-tw** [comment]
Thank you, @hctym1995. However, as my understanding, the rotating_logger_mt maintains only 1 file and keep log into it from the start when reaching the maximum. What I need is save the file and create a new one instead of erasing the previous log message within the same file.

**Comment by hctym1995** [comment]
Well, i got it wrong, maybe the author can answer your questions

**Comment by tt4g** [comment]
@qiao-tw `spdlog::flush_every()` should only be called once if the arguments remain the same, as it acquires the lock and creates a new thread, which has a significant impact on performance.

**Comment by qiao-tw** [comment]
@tt4g Thanks! It's very helpful!
