### ISSUE TITLE
Alignment flags inconsistent with Wiki (are swapped?)

### ISSUE THREAD

**Issue by WalkerWilliams741** [gabime/spdlog#1991]
I was creating my own format flag and decided to use padinfo_.side_ to get some dynamic padding (using a switch) and was surprised to find out that the left and right were swapped. This is inconsistent with what I read on the wiki:

https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#aligning

Is the wiki wrong? Or is the code wrong? Or am I just crazy?

The below code is from "pattern_formatter-inl.h"

```c++
padding_info::pad_side side;
switch (*it)
{
case '-':
    side = padding_info::pad_side::right; // shouldn't this be left?
    ++it;
    break;
case '=':
    side = padding_info::pad_side::center;
    ++it;
    break;
default:
    side = details::padding_info::pad_side::left; // shouldn't this be right?
    break;
}
```

**Comment by gabime** [comment]
You are not crazy, it is just the ```details::padding_info::pad_side``` means where to add space (which is the opposite of the alignment).

```padding_info::pad_side::right``` means add  spaces to the right - so is left aligned.
``` padding_info::pad_side::left``` means add  spaces to the left- so is right aligned.
