### ISSUE TITLE
"Log once" functionality?

### ISSUE THREAD

**Issue by willat343** [gabime/spdlog#1992]
I've been using spdlog for a while and like it much more than other loggers i've used. However one feature that I've seen in other logging software that I can't seem to find in spdlog's documentation is the ability to log a message once (or once/period) through the default logger.

Does this functionality exist and i've missed it? In particular i'm thinking of an equivalent to what ROS's logger does (`ROS_INFO_ONCE`) in a spdlog macro like `SPDLOG_INFO_ONCE`? They also supply macros with _THROTTLE for msgs at a max frequency and _COND for logging if a condition is true, which cuts a 2-3 line if+log statement to a 1 line log statement. These would also be convenient. (http://wiki.ros.org/roscpp/Overview/Logging)

In particular, i need to use spdlog's macros because in my application i need to be able to compile them out.

If this functionality does not exist, would this be a worthwhile feature request?

In terms of implementation of _ONCE, each log line has a unique identifier in it's source file and line number, which could be used to check if this log has been called before. I don't know the internal workings of spdlog though.

**Comment by gabime** [comment]
There is the [dup_filter_sink](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/dup_filter_sink.h ) which you might find useful. It filters duplicate messages up to the given  "max_skip_duration".

**Comment by willat343** [comment]
thanks @gabime, that does look useful and might be applicable to one of my usecases, however if i wanted to log a message that could be unique like the following made-up example: `SPDLOG_INFO("System time: {}", current_time());` then this sink would print all messages (if I understand it correctly)

**Comment by gabime** [comment]
> ; then this sink would print all messages (if I understand it correctly)

Right. In this case I recommend implementing custom sink to answer your specific requirements .
