### ISSUE TITLE
daily_file_sink behavior when no logs for more than 24 hours

### ISSUE THREAD

**Issue by joshreed13** [gabime/spdlog#1993]
I'm experiencing issues with the `daily_file_sink`, specifically when the application goes more than 24 hours without writing a log.

For example, if it's supposed to keep 2 days of logs and logs on Monday, does nothing on Tuesday, and then logs on Wednesday, Monday's file is not removed, even though it should only keep logs for two days.

I think this is illustrated by the following (failing) unit test:
```
TEST_CASE("daily_logger rotate skip day", "[daily_file_sink]")
{
    using spdlog::log_clock;
    using spdlog::details::log_msg;
    using spdlog::sinks::daily_file_sink_st;

    prepare_logdir();

    spdlog::filename_t basename = SPDLOG_FILENAME_T("test_logs/daily_rotate.txt");
    daily_file_sink_st sink{basename, 2, 30, true, 10};

    // simulate messages each day, skipping day 2
    for (int i = 0; i < 12; i++)
    {
        if (i == 2)
        {
            continue;
        }
        auto offset = std::chrono::seconds{24 * 3600 * i};
        sink.log(create_msg(offset));
    }

    REQUIRE(count_files("test_logs") == static_cast<size_t>(9));
}
```

This issue seems similar to #1566 and #1850, but in my case, the application is running the entire time.

I've also seen related issues where spdlog leaves files behind after the application restarts (and repopulates the `filenames_q_`) when some of the previous days had no logs.

I'd be interested in taking a stab at fixing this. It looks like the code in `daily_file_sink::init_filenames_q_` and `daily_file_sink::delete_old_` would need to be updated to not assume the number of files should always be the max allowed, but instead leave space when a file is missing.

Thanks!

**Comment by gabime** [comment]
Sure. PR is welcome.
