### ISSUE TITLE
aync log sinks without file outputs

### ISSUE THREAD

**Issue by helldragonx** [gabime/spdlog#1995]
Environments: Win10
Develop Tools: Visual Stdio 2019
Issue: The output log files is empty !?

Code:
`#include "../_MyLog.h"
#include <string>
#include <ctime>
#include <stdio.h>

#include "../libs/spdlog/spdlog.h"
#include "../libs/spdlog/sinks/stdout_color_sinks.h"
#include "../libs/spdlog/sinks/basic_file_sink.h"
#include "spdlog/async.h"
#include "../libs/spdlog/sinks/rotating_file_sink.h"

//init the spdlog with async, file/console out put.

bool init_log(short level, const char * directory, const char * module_name)
{
    time_t now = time(0);
    tm ltm;
    localtime_s(&ltm,&now);
    char tm_str[1024];
    snprintf(tm_str, sizeof(tm_str), "%s/%s_%04d%02d%02d_%02d%02d%02d.log", directory, module_name, ltm.tm_year + 1900
        , ltm.tm_mon, ltm.tm_mday, ltm.tm_hour, ltm.tm_min, ltm.tm_sec);

    spdlog::init_thread_pool(8192, 1);
    auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt >();
    stdout_sink->set_level( (spdlog::level::level_enum)level);

    auto rotating_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(tm_str, 1024 * 1024 * 10, 3);
    rotating_sink->set_level((spdlog::level::level_enum)level);

    std::vector<spdlog::sink_ptr> sinks{ stdout_sink, rotating_sink };
    auto logger = std::make_shared<spdlog::async_logger>(module_name, sinks.begin(), sinks.end(), spdlog::thread_pool(), spdlog::async_overflow_policy::block);
    spdlog::register_logger(logger);

    spdlog::flush_on(spdlog::level::err);
    spdlog::flush_every(std::chrono::seconds(1));

    return true;
}`

in the calling:
`    init_log(spdlog::level::info,"E:/tmp/", "FtpApiXXX");

    spd::error("System started !!!");
    spd::error("System started !!!");
    spd::error("System started !!!");
    spd::error("System started !!!");
    spd::error("System started !!!");
    spd::error("System started !!!");
    spd::error("System started !!!");`

**Comment by helldragonx** [comment]
sorry for this question, but I really try so many times, including using sync file , it also seems not work!
--code -->>
`bool init_log(short level, const char* directory, const char* module_name)
{
    time_t now = time(0);
    tm ltm;
    localtime_s(&ltm, &now);
    static char tm_str[1024];
    snprintf(tm_str, sizeof(tm_str), "%s/%s_%04d%02d%02d_%02d%02d%02d.log", directory, module_name, ltm.tm_year + 1900
        , ltm.tm_mon, ltm.tm_mday, ltm.tm_hour, ltm.tm_min, ltm.tm_sec);

    //spdlog::init_thread_pool(8192, 1);
    auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt >();
    stdout_sink->set_level((spdlog::level::level_enum)level);

    auto rotating_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(tm_str);
    rotating_sink->set_level((spdlog::level::level_enum)level);

    std::vector<spdlog::sink_ptr> sinks{ stdout_sink, rotating_sink };
    //auto logger = std::make_shared<spdlog::async_logger>(module_name, sinks.begin(), sinks.end(), spdlog::thread_pool(), spdlog::async_overflow_policy::block);
    auto logger = std::make_shared<spdlog::logger>(module_name, begin(sinks), end(sinks) );
    spdlog::register_logger(logger);

    spdlog::flush_on(spdlog::level::err);
    spdlog::flush_every(std::chrono::seconds(1));

    return true;
}`

**Comment by tt4g** [comment]
How do you output log?
Should call `spdlog::set_default_logger(logger)` If you call `spdlog::info(...)` for logging.

And since Windows does not flush file I/O when a program exits, call `spdlog::shutdown()` before exiting the application.
