### ISSUE TITLE
Add standard spdlog::spdlog alias?

### ISSUE THREAD

**Issue by dvhwgumby** [gabime/spdlog#1996]
Most CMake packages have a developer::pkg label but spdlog remains solitary.

The simple patch is to add `add_library(spdlog::spdlog ALIAS spdlog)` right after the line `add_library(spdlog INTERFACE)`

Here's a diff you could add via `patch`, or simply cut/paste

    diff CMakeLists.txt.orig CMakeLists.txt
    25a26
    > add_library(spdlog::spdlog ALIAS spdlog)

**Comment by gabime** [comment]
Not sure I understand: https://github.com/gabime/spdlog/blob/6491abb519a6a15792c1c6717270ce6c9ba4d72e/CMakeLists.txt#L162

**Comment by dvhwgumby** [comment]
Sorry, that must have been quite confusing, given that you seem to have added that line two years ago!  I must have fumbled fingered my grep pattern `-ie alias` doesn't seem so hard but... So my apologies

This is actually a consequence of a different bug relating to building with FetchContent.  I'm making a small test case and debating whether it'sa CMake issue or a spdlog issue (or me).

**Comment by gabime** [comment]
No worries. All is good.
