### ISSUE TITLE
msvc_sink usage with SPDLOG_X macros

### ISSUE THREAD

**Issue by zcream** [gabime/spdlog#1999]
I am unable to find an example of usage of SPDLOG_X macros with msvc_sink.
Thus far, I defined,
```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>
```

and in the main entry, 

    spdlog::set_level(spdlog::level::trace); // Set global log level to trace

Obviously, all the SPDLOG_TRACE and SPDLOG_DEBUG are not working and no output is seen in the Visual Studio debug window.

As an example,
```
#include "spdlog/sinks/msvc_sink.h"
auto sink = std::make_shared<spdlog::sinks::msvc_sink_mt>();
auto logger = std::make_shared<spdlog::logger>("msvc_logger", sink);
```

However, with this, I have to log using the logger->method. All the code insertions using macros will still not work. 
Is there a way to define msvc_sink as logger, and still be able to log using the macros ?

**Comment by gabime** [comment]
You need to use SPDLOG_LOGGER_(LEVEL) macros and pass them the logger shared ptr:
for example

```c++
SPDLOG_TRACE_LOGGER(logger, "some log {}", 5);
```

**Comment by zcream** [comment]
Will it work if I define logger as static and set the sink and logger during entry ? Also, what would be the sink and logger setup for XCode ? The defaults worked really well from XCode.

**Comment by zcream** [comment]
For usage, in header define
```
#include <spdlog/spdlog.h>
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)
#include <spdlog/sinks/msvc_sink.h>
#endif
```

In cpp file define
`static std::shared_ptr <spdlog::logger> S_logger;`

In class constructor, define
```
		auto sink = std::make_shared<spdlog::sinks::msvc_sink_mt>();
		S_logger = std::make_shared<spdlog::logger>("msvc_logger", sink);
```

**Comment by zcream** [comment]
Now, all I don't understand is, how do I convert the S_logger back to the default using 

```
auto sink = std::make_shared<spdlog::sinks::msvc_sink_mt>();
S_logger = std::make_shared<spdlog::logger>("msvc_logger", sink);
```
