### ISSUE TITLE
error C2039: 'remove': is not a member of 'spdlog::details::os' 

### ISSUE THREAD

**Issue by VikingExplorer** [gabime/spdlog#200]
I'm upgraded to the latest version of SpdLog, building for Windows Desktop, and I'm getting:

1>C:\Dev\Couloir\3pLibs\Include\spdlog/sinks/file_sinks.h(119): error C2039: 'remove': is not a member of 'spdlog::details::os'
1>  C:\Dev\Couloir\3pLibs\Include\spdlog/details/os.h(36): note: see declaration of 'spdlog::details::os'
1>  C:\Dev\Couloir\3pLibs\Include\spdlog/sinks/file_sinks.h(110): note: while compiling class template member function 'void spdlog::sinks::rotating_file_sink<std::mutex>::_rotate(void)'
1>  C:\Dev\Couloir\3pLibs\Include\spdlog/sinks/file_sinks.h(86): note: see reference to function template instantiation 'void spdlog::sinks::rotating_file_sink<std::mutex>::_rotate(void)' being compiled

Any ideas?

**Comment by gabime** [comment]
maybe you didnt take the last version of os.h file? please make sure you upgraded all the file

**Comment by VikingExplorer** [comment]
Yea, not sure how that could have happened. Oh well, thanks.
