### ISSUE TITLE
Can I just create an object in Android and then dynamically change the tag? 

### ISSUE THREAD

**Issue by lilinxiong** [gabime/spdlog#2000]
I saw that the Android sample passed in the tag directly when creating the instance. That is:
```c++
#include "spdlog/sinks/android_sink.h"
void android_example()
{
    std::string tag = "spdlog-android";
    auto android_logger = spdlog::android_logger_mt("android", tag);
    android_logger->critical("Use \"adb shell logcat\" to view this message.");
}
```
But every time you have to create an android_sink_mt, I don't want to do this. It is not very easy to manage. Can I just create an android_sink_mt and then dynamically modify the tag inside? 
I checked the documentation and looked at the code, and found that ``tag_`` is **private**. No relevant code can be found to modify it. 
Is there a function similar to android_logger->set_tag("new_tag"), that I can call? 
This log library is very good. I used it when I was developing under Linux. Now I want to use it under Android. Can you give me some suggestions? 
We are expecting a reply.

**Comment by gabime** [comment]
I dint think there is such way.

**Comment by lilinxiong** [comment]
@gabime Thank you for your reply. Can you tell me related documents or specific functions? Maybe I missed some details, because indeed I did not find set_tag and similar functions in the code, thank you very much.

**Comment by lilinxiong** [comment]
Let me add my doubts.
In [android_sink class](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/android_sink.h), Through android_logger_mt create android_sink ptr, and then pass in the tag, but in the android_sink class, tag_ is private, and in the final __android_log_write, the tag_ value is used. code is:
```c++
  // std::string tag = "spdlog-android";
  // auto android_logger = spdlog::android_logger_mt("android", tag);
template<typename Factory = spdlog::synchronous_factory>
inline std::shared_ptr<logger> android_logger_mt(const std::string &logger_name, const std::string &tag = "spdlog")
{
    return Factory::template create<sinks::android_sink_mt>(logger_name, tag);
}
template<typename Mutex>
class android_sink final : public base_sink<Mutex>
{
public:
    explicit android_sink(std::string tag = "spdlog", bool use_raw_msg = false)
        : tag_(std::move(tag))
        , use_raw_msg_(use_raw_msg)
    {}
protected:
int ret = __android_log_write(priority, tag_.c_str(), msg_output);
private:
    std::string tag_;
    bool use_raw_msg_;
}
```
1. There is no function to reset tag_ in the android_sink class.
2. What android_logger_mt returns is the logger object, and there is no set_tag_ function in the logger, but in the end, when we use it, the useful function is the function provided in the logger. So is it necessary to recreate android_sink to print a log with different tag values?
3. [implementing-your-own-sink?](https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink)

**Comment by gabime** [comment]
You can add a set_tag() function to this sink. PR is welcome.

**Comment by lilinxiong** [comment]
@gabime  Ok, I will try it. I just read the code from the beginning. I already know how to do it. I have implemented an interface, but the changes are relatively large. But I think it is a reasonable modification. This is the current effect:
![image](https://user-images.githubusercontent.com/24367027/125919043-a5c14a9d-c312-4606-b8c6-bad3bf24f9b9.png)
I believe you know how I did it and the scope of the changes...

**Comment by lilinxiong** [comment]
@gabime Hello,Recently, I changed it a bit and didn't change ```sink_it_```, but added a variable ```string_view_t msg_tag``` in ```details::log_msg```. Then I modified ```logger.h``` and ```spdlog.h``` and ```spdlog-inl.h```. I don't think the changes are very big. Is this kind of change acceptable? If possible, I will mention PR.
