### ISSUE TITLE
custom_flag_formatter with custom user data

### ISSUE THREAD

**Issue by MJBGO** [gabime/spdlog#2001]
Hello !

Sorry if the question was already answered, I couln't find any solution to my problem :)

I'm using the pattern system to format logs to a JSON format, read by filebeat processes. This works fine.
I can add static info via the custom_flag_formatter (adding a new flag), this works fine.

But how can I use this custom_flag_formatter to set custom data that is passed along the logger ?

For example, when I do : 

`spdlog::get("console")->info("My message")`

I need to pass extra data that will not be added to the message field but in a separate one (printed by a custom flag, for example let's say conversationId). How can I achieve that ?

Thanks for your work

**Comment by gabime** [comment]
There is no built in way for passing separate extra data. You should implement the mechanism yourself.

**Comment by lp35** [comment]
Hi,

I'm looking for the exact same thing. This would be awesome feature for extending the capabilities of log system.
