### ISSUE TITLE
Need suppress -Wsuggest-attribute=format

### ISSUE THREAD

**Issue by rsy56640** [gabime/spdlog#2003]
https://github.com/gabime/spdlog/blob/70d2832c0de306abc86ca06b751a7ed5ac0e525d/include/spdlog/fmt/bundled/format-inl.h#L2437
cannot compile with "-Wsuggest-attribute=format", and
https://github.com/gabime/spdlog/blob/70d2832c0de306abc86ca06b751a7ed5ac0e525d/include/spdlog/fmt/bundled/chrono.h#L459-L462
compiles in a pattern that suppress the warning.

**Comment by gabime** [comment]
Please open in the fmt lib  repo instead
