### ISSUE TITLE
Deadlock Issue -  Logger with 2 multi-threaded sinks

### ISSUE THREAD

**Issue by rocketcyberdev** [gabime/spdlog#2009]
Have an issue where 5 threads were blocked waiting on the sink mutex in our application.
The app runs as a windows service. This issue was observed on Windows 10.

All affected threads were blocked on the lock_guard statement in base_sink-inl.h

```
template<typename Mutex>
void SPDLOG_INLINE spdlog::sinks::base_sink<Mutex>::log(const details::log_msg &msg)
{
    std::lock_guard<Mutex> lock(mutex_);
    sink_it_(msg);
}
```

The following code is used to initialize the logger which was pretty much borrowed from the multi sink logger example.

```
auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();

int max_size = 1048576 * 2; // 2mb  max
int max_files = 3;
bool rotate_on_start = false;
auto roti_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(log_file_name, max_size,max_files,rotate_on_start);

spdlog::sinks_init_list sink_list = { roti_sink, console_sink };
logger = std::make_shared<spdlog::logger>(log_name, sink_list.begin(), sink_list.end());
logger->set_level(spdlog::level::info);
logger->set_pattern("%v");
spdlog::register_logger(logger);
spdlog::set_default_logger(logger);

```
Is this a known issue? Are there recommendations for multi-threaded/multi-sink apps beyond whats in the example?

Thanks in advance.

**Comment by gabime** [comment]
This is not known issue. Do you run the init code from dll main?

**Comment by rocketcyberdev** [comment]
Its initialized in the main() function of the service executable through a static library linked at compiled time with the .exe and the .dll.

The goal being to have a shared logger function between the main app and the dll.

As a work around we've just switched over to async log type. Not sure if that will prove any different?

**Comment by zhy755788055** [comment]
ldd <your program>,is pthread lib linked?If you not linked the pthread lib,the program work properly.I meet this problem,but I don't know why.
