### ISSUE TITLE
Multiply loggers using same file crashes on windows

### ISSUE THREAD

**Issue by a-teammate** [gabime/spdlog#201]
If multiply loggers on windows use the same file it crashes, since only the first is allowed to open that file (for write mode).

Possible fix:

Replace `_SH_DENYRW` (Deny any subsequent write calls) with `_SH_DENYRD` (deny any subsequent read calls)
in fopen_s() in io.h

**Comment by gabime** [comment]
Does it really crash? or just throws an exception (which wasn't caught) ?

**Comment by a-teammate** [comment]
Oh yes sure, it throws an exception (in file_helper::open()). Sry, for confusion

**Comment by gabime** [comment]
in this case it is not an issue. spdlog does not support multi loggers/processes to same file

**Comment by a-teammate** [comment]
while multiple processes to the same file seems invalid indeed whats the purpose of forbidding multiply loggers writing to the same file?

(we got a lot of loggers and sometimes even use different ones for closely related parts, like "frag_involved" and "frag_not_involved" which preferably should go to the same file, since their distinction is only for the purpose of enabling them seperately in the UI-sink)
