### ISSUE TITLE
MSVC sink will output wrong result when string contain non-ASCII character

### ISSUE THREAD

**Issue by Demonese** [gabime/spdlog#2012]
Some project detail:
* all source files using utf8 encoding and compiled with /utf-8 option
* some string contain Chinese or Japenese character
* spdlog disable wchar support (because all in utf8)
In VS2019 debugger output window, Chinese or Japenese character will display in wrong way. I found a OutputDebugStringA calling in msvc_sink.h but this method seems doesn't support unicode encoding (instead, we should using OutputDebugStringW, but it recive wchar string, converting might be expensive?).

**Comment by tt4g** [comment]
I think the reason is that the character encoding of the debugger console is not UTF-8 (or does not support it).
It should not be garbled in a console that supports UTF-8.

> but it recive wchar string, converting might be expensive?

Probably yes.

**Comment by tt4g** [comment]
Do you have the compile option "/utf8" set (can use `/source-charset:utf-8` and `/execution-charset:utf-8` instead)?
If these options are not set, the Visual Studio compiler will not print UTF-8 characters.

https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-160

As described on the `/execution-charset` option page, the Visual Studio compiler will not detect character codes other than UTF-16 and UTF-8 with BOM in the source code.

https://docs.microsoft.com/en-us/cpp/build/reference/execution-charset-set-execution-character-set?view=msvc-160

**Comment by Demonese** [comment]
> I think the reason is that the character encoding of the debugger console is not UTF-8 (or does not support it).
> It should not be garbled in a console that supports UTF-8.

Yeah, VS2019 debug output window only support OutputDebugStringW (UTF16-LE).

![image](https://user-images.githubusercontent.com/57629614/126889832-fd4567d0-1311-4256-b921-ff8f8759aa81.png)
![image](https://user-images.githubusercontent.com/57629614/126889849-2cdf9567-578f-44c0-aca4-5ddd4fbb86bc.png)
![image](https://user-images.githubusercontent.com/57629614/126889844-8847cbb8-48b0-45c4-8482-bb964a32d3a6.png)

**Comment by tt4g** [comment]
`OutputDebugStringW` converts the UTF-16 string to the encoding of the system locale, and then passes it to `OutputDebugStringA`.

https://docs.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringa

> OutputDebugStringW converts the specified string based on the current system locale information and passes it to OutputDebugStringA to be displayed. As a result, some Unicode characters may not be displayed correctly.

If you call `OutputDebugStringW` directly and it is not garbled, then your debugger console is in the mode to display the characters of the system locale.

Change the character encoding of the debug console.
