### ISSUE TITLE
Ways to incorporate spdlog to my project?

### ISSUE THREAD

**Issue by glassxer1** [gabime/spdlog#2014]
Hi, I am trying to use Spdlog in my c++ project and found that the nuget package available on nuget.org was from 2018. So I try to create a nuget package myself but fail due to the lack of documentation on the Internet. I wonder what is the proper way to create a current version Spdlog of nuget or incorporate Spdlog into my project?

Thanks

**Comment by sjanel** [comment]
Hello,

If you use a recent version of cmake, I suggest using FetchContent, like this:
```
FetchContent_Declare(
  spdlog
  GIT_REPOSITORY https://github.com/gabime/spdlog.git
  GIT_TAG        v1.x
)

FetchContent_MakeAvailable(spdlog)
```

Then, you simply link it like this:
```
target_link_libraries(MyLib PRIVATE spdlog)
```

**Comment by glassxer1** [comment]
I managed to build a workable nuget package using CoApp, but I will try using cmake as well. Thanks!
