### ISSUE TITLE
Cannot format an argument. To make type T formattable provide a formatter<T> specialization

### ISSUE THREAD

**Issue by sunrongyi** [gabime/spdlog#2021]
When i include spdlog file into my project. Always prompt “Cannot format an argument. To make type T formattable provide a formatter<T> specialization”,How to solve this problem？

**Comment by tt4g** [comment]
spdlog uses [{fmt}](https://github.com/fmtlib/fmt) library to format the log arguments.
You can format `T` by `fmt::formatter<T>` specification.
See: https://fmt.dev/8.0.0/api.html#formatting-user-defined-types

**Comment by xinsuinizhuan** [comment]
I meet the same problem, i think it change, it this!
