### ISSUE TITLE
Macro  SPDLOG_LEVEL_NAME_xxxx is namespace when outside of spdlog

### ISSUE THREAD

**Issue by ashley-b** [gabime/spdlog#2022]
When I use the log level names in user code it can not be found. I get the following error.
```
error: use of undeclared identifier 'string_view_t' 
```
This use to work in older version's.
Looks like string_view_t should be spdlog::string_view_t

https://github.com/gabime/spdlog/blob/bee3e63e1bae8b4cd5e3ebd69fbf75f68e47996a/include/spdlog/common.h#L176-L182

**Comment by gabime** [comment]
Fixed. Thanks for reporting.
