### ISSUE TITLE
Documentation for supported format strings.

### ISSUE THREAD

**Issue by CiaranWelsh** [gabime/spdlog#2031]
Hello, I'm trying out this library in my project - all seems to be working nicely so far. Do you have any documentation for the range of supported format strings? 

The example shows `    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");` but what do all of these symbols mean? Thanks.

**Comment by gabime** [comment]
https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags

**Comment by CiaranWelsh** [comment]
Thanks!
