### ISSUE TITLE
[question] hi, I am new to cpp, i have an question when run example in wiki.

### ISSUE THREAD

**Issue by hbwang15** [gabime/spdlog#2032]
since i have an spdlog registry in dynamic lib, why the example say it wan't shared the registry? but the registry is an Singleton. and the example i run would get double register exception because of registry twice. 

Links: [https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs]

**Comment by hbwang15** [comment]
> Because spdlog is header-only, building shared libraries and using it in a main program will not share the registry between them. This means that calls to functions like spdlog::set_level(spdlog::level::level_enum::info) will not change loggers in DLLs.

why not shared registry between main and shared library???

**Comment by tt4g** [comment]
Duplicate #2033
