### ISSUE TITLE
comma formatting

### ISSUE THREAD

**Issue by jfritz64** [gabime/spdlog#2052]
Is comma formatting supported similar to the python format string "{:,}"?

**Comment by tt4g** [comment]
The format of the argument is {fmt}, and the comma format does not seem to be supported.
However, formatting according to locale is supported.

```c++
#include <fmt/locale.h>

auto s = fmt::format(std::locale("en_US.UTF-8"), "{:L}", 1234567890);
// s == "1,234,567,890"
```

Please refer to the API documentation for {fmt}: https://fmt.dev/8.0.0/syntax.html

**Comment by jfritz64** [comment]
thank you!
