### ISSUE TITLE
Multi thread use multi log file support

### ISSUE THREAD

**Issue by IshNar** [gabime/spdlog#2053]
![image](https://user-images.githubusercontent.com/88694288/129686664-f6127905-156d-421a-a984-63b31ae76ccf.png)
![image](https://user-images.githubusercontent.com/88694288/129686720-d24c71a1-2ef2-4f9f-b5d2-08021b49f6b6.png)
I usually create and use log files and folders for each thread like this.
I found a better log program and tried to use spdlog, so I applied it. This is what the content looks like this.
![image](https://user-images.githubusercontent.com/88694288/129686967-95cefc77-0919-4410-bf09-048b01e4a87b.png)
![image](https://user-images.githubusercontent.com/88694288/129687034-9ac87c83-a81e-4197-85cd-90578ba2eb91.png)

This is how it is assigned within a class called CLogger, and each time you add a Log, the CPU is allocated about 13%. That's why spdlog is unavailable.
Is there any way?

**Comment by tt4g** [comment]
Does not using spdlog reduce CPU usage?
I developed a GUI application that writes to a log file from multiple threads, but the log writes had no impact on performance.

Have you investigated to see if there are other problems besides spdlog, such as threads?
For example, WSL2 has a problem with very slow file writing.

NOTE use `spdlog::basic_logger_mt` instead of `spdlog::basic_logger_st` for sinks used from multiple threads.

**Comment by IshNar** [comment]
> NOTE use `spdlog::basic_logger_mt` instead of `spdlog::basic_logger_st` for sinks used from multiple threads.

-> The same CPU Usage issue occurs when tested with spdlog::basic_logger_mt.

**Comment by tt4g** [comment]
> -> The same CPU Usage issue occurs when tested with spdlog::basic_logger_mt.

This comment is meant to convey a general note on using sink in multithreading.
I don't think it has much to do with issue.

The code you provided is fragmented, so I don't know that spdlog is causing the CPU usage to increase.
Please check CPU usage will decrease after removing the logger creation code.

**Comment by IshNar** [comment]
> > -> The same CPU Usage issue occurs when tested with spdlog::basic_logger_mt.
> 
> This comment is meant to convey a general note on using sink in multithreading.
> I don't think it has much to do with issue.
> 
> The code you provided is fragmented, so I don't know that spdlog is causing the CPU usage to increase.
> Please check CPU usage will decrease after removing the logger creation code.

If I remove the logger generation code, how do I save it to a different file?
I have to use a format that I save to multiple log files.
Could you teach me about that?

**Comment by tt4g** [comment]
The purpose of temporarily removing the code is to find out if spdlog is causing the problem.
You can restore the code after the investigation is finished.

**Comment by IshNar** [comment]
> The purpose of temporarily removing the code is to find out if spdlog is causing the problem.
> You can restore the code after the investigation is finished.

I already said test basic_logger_mt. that cause problem too.

**Comment by tt4g** [comment]
I'll write again, the difference between `basic_logger_st` and `basic_logger_mt` shouldn't have a significant effect on CPU usage.

To investigate whether the creation of loggers with file writes is affecting CPU usage, try removing the code that creates the loggers.

**Comment by IshNar** [comment]
> The difference between `basic_logger_st` and `basic_logger_mt` shouldn't have a significant effect on CPU usage.
> 
> To investigate whether the creation of loggers with file writes is affecting CPU usage, try removing the code that creates the loggers.

I don't think the conversation is going well right now. I'm sorry.
I've already confirmed that I occupy one cpu per file write, and I've already said it's a problem.
What I want is that I need to write several log files. By the way, if you say, "Then why don't we use multiple log files?" I can't solve the problem.

I don't want to know the difference between basic_logger_st and basic_logger_mt. They want a way to write a lot of log files and not take over the CPU. My existing log that I write does not occupy 13% of the CPU per file write, or 1/8.

**Comment by tt4g** [comment]
You are right, there seems to be a difference in our perceptions.
Let me ask you a few questions.

I recognize from the issue title that the problem occurs when using spdlog in multithreading.
However, does the same problem actually occur in single thread?

I am aware that `CLogger` (in the first image) is a wrapper for spdlog.
Are you saying that using a logger implementation other than spdlog with `CLogger` will not cause problems?

I can't understand the code you wrote from the image.
Can you provide the code to reproduce the problem?

**Comment by IshNar** [comment]
> You are right, there seems to be a difference in our perceptions.
> Let me ask you a few questions.
> 
> I recognize from the issue title that the problem occurs when using spdlog in multithreading.
> However, does the same problem actually occur in single thread?
> 
> I am aware that `CLogger` (in the second image) is a wrapper for spdlog.
> Are you saying that using a logger implementation other than spdlog with `CLogger` will not cause problems?
> 
> I can't understand the code you wrote from the image.
> Can you provide the code to reproduce the problem?

![log Error Capture](https://user-images.githubusercontent.com/88694288/130006816-4c59520f-4239-4475-afe0-334def9f8742.JPG)



No CPU problems occur in a single thread. However, it still has a large cpu share (13%)
In the shared image, the Logger class is assigned in part 1 and there are two inside each class in number 1. After allocating multiple log file stores, the problem is that CPU share = 13% * number of allocation classes.

**Comment by tt4g** [comment]
Are all log file names in `CLogger` unique?
If you try to write logs to the same file at the same time, `spdlog::spdlog_ex` will be thrown and performance will deteriorate.
`spdlog::spdlog_ex` is `catch` inside spdlog and notified to the error handler, which may not be aware of it since the application is not stopped.

**Comment by IshNar** [comment]
> Are all log file names in `CLogger` unique?
> If you try to write logs to the same file at the same time, `spdlog::spdlog_ex` will be thrown and performance will deteriorate.
> `spdlog::spdlog_ex` is `catch` inside spdlog and notified to the error handler, which may not be aware of it since the application is not stopped.

Ok, I will try and feedback

**Comment by tt4g** [comment]
What is the compiler you are using?
MinGW is known to have very poor performance.

**Comment by IshNar** [comment]
> What is the compiler you are using?
> MinGW is known to have very poor performance.

MY OS : Window 10
compiler : visual studio 2015 c++

**Comment by tt4g** [comment]
Hmmm, I can't guess the cause any more than I already have.
Please wait for someone else's answer.

**Comment by IshNar** [comment]
> Hmmm, I can't guess the cause any more than I already have.
> Please wait for someone else's answer.

Thanks for your reply
