### ISSUE TITLE
Question about qt_sink class constructor

### ISSUE THREAD

**Issue by ashley-b** [gabime/spdlog#2055]
When I was directly constructing a qt_sink in a multi sink arrangement with a file logger. I found It was displaying nothing till I released I was missing **meta_method** since it defaults to an empty string. I think the arguments **qt_object** and **meta_method** should not have default as it does make sense, since there are no setters to change theses values after construction.
 
https://github.com/gabime/spdlog/blob/243c4beac7b271e451c7d1ae9f8a0370e9b95355/include/spdlog/sinks/qt_sinks.h#L26

**Comment by gabime** [comment]
agreed. pr would. pr would be most welcome
