### ISSUE TITLE
how to make a logger log every day,and limit every day's log file size?(like Integrate 'rotating_file_sink_mt' and 'daily_file_format_sink_mt')

### ISSUE THREAD

**Issue by huygens-cheng** [gabime/spdlog#2059]
I want to build a log system to record the logs of the last 30 days, and limit the daily log file size to 20m. If the log file of the day is greater than 20m, the earliest record of the day will be overwritten, just like combining 'rotating_file_sink_mt' and 'daily_file_format_sink_mt '.

**Comment by tt4g** [comment]
The feature to overwrite old records when the log file size exceeds the threshold is not supported.
But you can create custom sink yourself.
