### ISSUE TITLE
Exit program is suspended in Win7, but Win10 will not

### ISSUE THREAD

**Issue by RonxBulld** [gabime/spdlog#2072]
I use the code ```spdlog::rotating_logger_mt<spdlog::async_factory_nonblock>```  to create a logger, but after main returned, the process not terminal. I try to use ```spdlog::drop_all``` and ```spdlog::shutdown```, but it has no effect, until used the Windows API ```TerminalProcess```.
In the end, the debugger showed that the problem was caused by the hang of TerminalThread.

OS: Windows 7 SP1
Build: Visual Studio 2017 Win64

**Comment by tt4g** [comment]
What's `TerminalProcess` and TerminalThread?

**Comment by sbwtw** [comment]
![image](https://user-images.githubusercontent.com/3384652/173548336-870758a5-1588-469b-bb75-9d5fbbb4310c.png)

https://stackoverflow.com/questions/60452341/stdconditional-variable-notify-problem-on-windows-7-called-from-destructor-o
