### ISSUE TITLE
FreeBSD package is broken: include/spdlog/fmt/fmt.h includes spdlog/fmt/bundled/core.h which isn't installed 

### ISSUE THREAD

**Issue by yurivict** [gabime/spdlog#2076]
On FreeBSD spdlog-1.9.2 installs ```include/spdlog/fmt/fmt.h``` with this line:
> #    include <spdlog/fmt/bundled/core.h>
but it doesn't install ```spdlog/fmt/bundled/core.h``` so other project fails to find ```spdlog```.

Is it important to have a bundled ```fmt```? FreeBSD does have a functional ```fmt``` package.

Is this something that is left by mistake?

Downstream bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258073

**Comment by tt4g** [comment]
if `SPDLOG_FMT_EXTERNAL` macro not defined, will include `spdlog/fmt/bundled/core.h`.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/fmt/fmt.h#L13-L27

`CMake` will automatically add the `SPDLOG_FMT_EXTERNAL` macro to the project (if don't use `CMake`, please add it manually).

**Comment by yurivict** [comment]
But what is the purpose to bundle ```fmt``` when ```fmt``` package is installed?

**Comment by tt4g** [comment]
If the CMake variable `SPDLOG_FMT_EXTERNAL` is true, it will not be installed bundled fmt.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/CMakeLists.txt#L290-L293

I don't know why it is installed on FreeBSD.

**Comment by yurivict** [comment]
FreeBSD builds spdlog with ```-DSPDLOG_FMT_EXTERNAL=ON``` but the code with ```#include <spdlog/fmt/bundled/core.h>``` is still installed conditional on a further compile-time switch.

Shouldn't ```#include <spdlog/fmt/bundled/core.h>``` be entirely removed when built with ```-DSPDLOG_FMT_EXTERNAL=ON```?

**Comment by tt4g** [comment]
Since sdlog is a header-only library (the feature to build it as a library was added later), I think it uses a macro to switch the include target in order to be able to switch between bundled fmt and external fmt for each project.
If `#include <spdlog/fmt/bundled/core.h>` is removed at CMake build time, it will lose its feature as a header-only library.

However, I am not the main maintainer of this repository.
So opening a PR that removes `#include <spdlog/fmt/bundled/core.h>` at CMake build time might merge it.

**Comment by gabime** [comment]
@yurivict If you want the freebsd pkg not to `#include` the bundled fmt, then it should define somewhere `SPDLOG_FMT_EXTERNAL` for the pkg users. Otherwise they should define it themselves.

**Comment by yurivict** [comment]
> [...] it should define somewhere SPDLOG_FMT_EXTERNAL for all pkg users 

Random packages just try to compile and fail.

There is no way to make them all use ```SPDLOG_FMT_EXTERNAL```.

**Comment by gabime** [comment]
In this case don't remove the bundled fmt and let the users decide for themselves using the SPDLOG_FMT_EXTERNAL macro/flag. This is the intended way anyway.
