### ISSUE TITLE
Using a *static lib* that imports spdlog, inside app already using  spdlog - our logger stop working.

### ISSUE THREAD

**Issue by kurtguenther** [gabime/spdlog#2077]
I just need a sanity check that this scenario is supported.

Our app is importing a new vendor static lib that uses spdlog (header only).
We also have our own static lib that use spdlog (header only) that we import into our app.
Both versions are the exact same v1.2.1.

Our logs work fine until we import the vendor static lib and instantiate any of their classes. 
From then on all our logs simply fail to print.

This is _before_ the vendor lib even creates any loggers.

Is this scenario supported?

**Comment by tt4g** [comment]
Theoretically, it will work if there is no problem with the ABI (application binary compatibility) of the functions contained in all static libraries.
The fact that it doesn't work means that the ABI is broken and is causing undefined behavior.

When the application links to the static library, it will use the first symbol it finds.
Perhaps your project's library symbols are embedded in the application, and the vendor's library symbols are ignored when linking.

See: https://stackoverflow.com/questions/29079742/same-symbols-in-different-libraries-and-linking-order

It is not expected to work unless spdlog generates the same binary for all libraries.
It is possible to use header-only spdlog in multiple static libraries, but it is difficult and should be avoided.

**Comment by gabime** [comment]
Thanks @tt4g for the explenation
