### ISSUE TITLE
spdlog::flush_every that takes std::chrono::milliseconds

### ISSUE THREAD

**Issue by apartridge** [gabime/spdlog#2080]
The spdlog::flush_every() function takes as input seconds.

```
SPDLOG_INLINE void flush_every(std::chrono::seconds interval)
{
    details::registry::instance().flush_every(interval);
}
```

It would be great if there was a `flush_every` that takes milliseconds. To debug issues it can sometimes be useful to set the flushing interval low (lower than 1 second) to more regularly update the file on disk. std::chrono::seconds will correctly convert to a std::chrono::milliseconds, so the code above could just be changed to milliseconds and existing user code should still work, however some customer may hit problems due to having more than 1 user-defined implicit conversion. So the safest would probably be a second overload that takes milliseconds.

**Comment by gabime** [comment]
I agree that an overload would be safer. 
However for those kind of resolutions, using ```flush_on(debug)``` is way better for debugging.

**Comment by apartridge** [comment]
I agree that `flush_on(debug)` could be more useful in the example I mention. In our case we have this logger flush-interval exposed as an "expert configuration" to our users.  I think since spdlog contains a `flush_every` function, it would be nice if it provided finer granularity than seconds. Milliseconds was available in earlier versions of spdlog, in `spdlog::set_async_mode`. However  it seems when it was changed to `spdlog::flush_every()` it only supported seconds.
