### ISSUE TITLE
How to change the sinks on an existing logger?

### ISSUE THREAD

**Issue by tkocmathla** [gabime/spdlog#2085]
Given an existing logger, I want to change its sinks. Or more specifically, I'd like to have a function that wraps a logger's existing sink(s) in a `dup_filter_sink_mt`. Is this possible?

I know I can get the logger with:
```
auto logger = spdlog::get(logger_name);
```

And I can get its sinks with:
```
auto sinks = logger->sinks();
```

But how would I take those sinks and move them into a `dup_filter_sink_mt`?

**Comment by tt4g** [comment]
`spdlog::sinks::dup_filter_sink<Mutex>` inherits `spdlog::sinks::dist_sink<Mutex>`.
You can call `spdlog::sinks::dup_filter_sink<Mutex>::add_sink(std::shared_ptr<sink> sink)` to move sink.

**Comment by tkocmathla** [comment]
Cool, but how do I then replace the logger's existing sinks with the new `dup_filter_sink` that wraps them? I don't see an API for something like `logger->set_sinks(...)`.

**Comment by tt4g** [comment]
The API to replace sink of `spdlog::logger` is not supported.

First, pass `dup_filter_sink` (or `dist_sink`) to sink of `spdlog::logger::logger()` constructor.
You should assign `dup_filter_sink` to a variable, and add and remove sinks via `dup_filter_sink`.

**Comment by gabime** [comment]
One can use the logger->sinks() https://github.com/gabime/spdlog/blob/a1d9f501e3863611824685426e3682cab1c8e016/include/spdlog/logger.h#L310 to access and modify the sinks (in a non thread safe way though..i.e.  do it only if no other thread is using this sink/logger in the same time)

**Comment by tkocmathla** [comment]
ok, i have something working and am curious if it seems sane or evil:

create the logger in one context:
```
auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_mt>();
dist_sink->set_sinks({stdout_sink});

auto logger = std::make_shared<spdlog::logger>("", dist_sink);
spdlog::register_logger(logger);
```

then modify it to add the deduplication in a later context:
```
for (auto sink_ptr : logger->sinks()) {
    if (auto dist_sink = dynamic_cast<spdlog::sinks::dist_sink_mt *>(sink_ptr.get())) {
        auto dup_filter = std::make_shared<spdlog::sinks::dup_filter_sink_mt>(std::chrono::seconds(3));
        // move the dist sink's sinks into the dedupe sink
        dup_filter->set_sinks(dist_sink->sinks());
        dist_sink->set_sinks({dup_filter});
        break;
    }
}
```

**Comment by tt4g** [comment]
It appears to work. However, it is not thread-safe because it uses `spdlog::logger::sinks()`.
