### ISSUE TITLE
spdlog fails to link with gold linker (static build)

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [gabime/spdlog#2086]
gcc 9.2.1 for arm-v7a:

`arm-v7a-linux-gnueabihf-g++ -o <target> -pthread -fuse-ld=gold -static -static-libgcc -static-libstdc++ -Wl,--whole-archive -lpthread -Wl,--no-whole-archive <objects and libs>`

```
ld.gold: error: undefined or discarded symbol _ZZN6spdlog7details2os9thread_idEvE3tid in GOT
ld.gold: error: undefined or discarded symbol _ZGVZN6spdlog7details2os9thread_idEvE3tid in GOT
```

With the gcc linker it links without a problem:
`arm-v7a-linux-gnueabihf-g++ -o <target> -pthread -static -static-libgcc -static-libstdc++ -Wl,--whole-archive -lpthread -Wl,--no-whole-archive <objects and libs>`

**Comment by gabime** [comment]
seems like linker issue or wrong flags
