### ISSUE TITLE
comment about thread safety in logger.h is not correct?

### ISSUE THREAD

**Issue by alek314** [gabime/spdlog#209]
it writes "Thread safe logger" in logger.h.
but if you use a rotating_logger_st, it's not thread safe, because base_sink::log use a null_mutex.
i think logger is thread safe under some conditions, and it would be nice if they are documented explicitly.

**Comment by gabime** [comment]
technically it is correct, because the logger object itself is always thread safe. (the sinks that it use might be not), but I agree it is confusing. please open a pull with better comment.
