### ISSUE TITLE
How to add customized suffix append to daily file? Like "20210905.mylog"

### ISSUE THREAD

**Issue by WorstCodeWay** [gabime/spdlog#2091]
The tile describes my demand. Thanks

**Comment by tt4g** [comment]
You can use `spdlog::sinks::daily_file_format_sink_mt`.
e.g. `std::shared_ptr<spdlog::logger> logger = spdlog::daily_logger_format_mt("daily_logger", "%Y%m%d.mylog");`
See this PR #1847.

**Comment by WorstCodeWay** [comment]
> #1847

Thanks，I believe this can solve my title question, but can I further add sinks(say, qtwidget sink) into this "format daily logger")?

**Comment by tt4g** [comment]
`spdlog::sinks::dist_sink_mt` can combine multiple sinks into a single sink.

```cpp
auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_mt>();

dist_sink->add_sink(
    std::make_shared<spdlog::sinks::daily_file_format_sink_mt>(
        "%Y%m%d.mylog", ...(other args) ));

// Add other sinks.
dist_sink->add_sink( ... );

auto dist_logger = std::make_shared<spdlog::logger>("dist_logger", dist_sink);
spdlog::register_logger(dist_logger);
```

**Comment by WorstCodeWay** [comment]
> `spdlog::sinks::dist_sink_mt` can combine multiple sinks into a single sink.
> 
> ```c++
> auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_mt>();
> 
> dist_sink->add_sink(
>     std::make_shared<spdlog::sinks::daily_file_format_sink_mt>(
>         "%Y%m%d.mylog", ...(other args) ));
> 
> // Add other sinks.
> dist_sink->add_sink( ... );
> 
> auto dist_logger = std::make_shared<spdlog::logger>("dist_logger", dist_sink);
> spdlog::register_logger(dist_logger);
> ```

Nice！I will try it.

**Comment by WorstCodeWay** [comment]
> `spdlog::sinks::dist_sink_mt` can combine multiple sinks into a single sink.
> 
> ```c++
> auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_mt>();
> 
> dist_sink->add_sink(
>     std::make_shared<spdlog::sinks::daily_file_format_sink_mt>(
>         "%Y%m%d.mylog", ...(other args) ));
> 
> // Add other sinks.
> dist_sink->add_sink( ... );
> 
> auto dist_logger = std::make_shared<spdlog::logger>("dist_logger", dist_sink);
> spdlog::register_logger(dist_logger);
> ```

I have tried, and just `daily_file_format_sink_mt` satisfies my demand: add a daily file sink with custom suffix append onto log file, like ".mylog", and add this sink into logger which will add further sinks, so codes is:

```c++
auto formatfilesink = std::make_shared<spdlog::sinks::daily_file_format_sink_mt>("Log_%Y-%m-%d.log", 23, 59);
auto logger = std::make_shared<spdlog::logger>("LogName",  _sysFileSink);

logger->sinks().push_back(/*some other sink*/);
``` 

That works just fine.

Thank you again, @tt4g.
