### ISSUE TITLE
Unresolved External Symbol on First Build

### ISSUE THREAD

**Issue by CaptainLupa** [gabime/spdlog#2099]
I'm just trying to use this library at all and I just get these errors every time.
![image](https://user-images.githubusercontent.com/31449649/132773618-f24d97a3-2acf-436a-82d5-e39e0fdd27f7.png)
This is all the code I have there's basically nothing to mess up I don't know what's happening.
![image](https://user-images.githubusercontent.com/31449649/132773682-34ab7269-dce3-4a3b-a1a9-5e8b6f102b47.png)

**Comment by Iamgoofball** [comment]
So how exactly did you fix this?
