### ISSUE TITLE
ARM cross compilation with older CMake

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [gabime/spdlog#2100]
Hi,

I am trying to cross compile spdlog for ARM, so I need to source the provided toolchain before building.
When I issue the cmake command, I get:

`CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.10...3.21 or higher is required.  You are running version 3.8.2

-- Configuring incomplete, errors occurred!
`

Is there an easy way to cross compile your library using an older CMake version?

Thank you in advance

**Comment by tt4g** [comment]
CMake stops building because the version is less than the version specified by `cmake_minimum_required(VERSION 3.10...3.21)` in some `CMakeLists.txt`.

If you change it to `cmake_minimum_required(VERSION 3.8)`, CMake will try to build, but it is not sure whether the build will complete or not.

**Comment by gianmarcoodorizzi** [comment]
It works!!!
Thank you
