### ISSUE TITLE
Isn't std::fwrite thread-safe ?

### ISSUE THREAD

**Issue by jackeykong** [gabime/spdlog#2104]
std::write is thread-safe on Windows. Why std::mutex locks? For example:
using basic_file_sink_mt = basic_file_sink<std::mutex>;

Refer to the content:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fwrite?view=msvc-160

I found a description "Because this function locks the calling thread, it is thread-safe. For a non-locking version, see _fwrite_nolock."

**Comment by gabime** [comment]
Maybe,  but the ```base_sink<Mutex>::formatter_->format(msg, formatted);``` still need to be protected from multiple threads.

**Comment by jackeykong** [comment]
> Maybe, but the `base_sink<Mutex>::formatter_->format(msg, formatted);` still need to be protected from multiple threads.

So, if i only want to write files, there is no need to lock with std::mutex, right?

**Comment by gabime** [comment]
you must lock if you use spdlog sink

**Comment by jackeykong** [comment]
> you must lock if you use spdlog sink

In other words, even if I use the same "spdlog::basic_file_sink_st" object, as long as I make sure that no other threads call "spdlog::Logger::set_pattern" while I'm logging, it's also safe, right? 
Thanks for your reply.

**Comment by gabime** [comment]
No, this is wrong.. like i said the mutex is also used for protecting this line https://github.com/gabime/spdlog/blob/8826011c81b69e1f8427be520b357c19c74ea480/include/spdlog/sinks/basic_file_sink-inl.h#L32

**Comment by jackeykong** [comment]
> > .. while I'm logging, it's also safe, right
> 
> No, this is wrong.. like i said the mutex is also used for protecting this line
> 
> https://github.com/gabime/spdlog/blob/8826011c81b69e1f8427be520b357c19c74ea480/include/spdlog/sinks/basic_file_sink-inl.h#L32

Is "format" on line 32 unsafe? Can you tell me why?
Thanks for your reply.

**Comment by gabime** [comment]
Because the formatter stores some state that might change (e.g. date/time caching).

**Comment by jackeykong** [comment]
> Because the formatter stores some state that might change (e.g. date/time caching).

I see!! But why store date/time? Is it because the "get_time_" function on line 1055 is inefficient?
[https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/pattern_formatter-inl.h#L1055]

**Comment by jackeykong** [comment]
> Because the formatter stores some state that might change (e.g. date/time caching).

I see!! But why store date/time? Is it because the "get_time_" function on line 1055 is inefficient?
[https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/pattern_formatter-inl.h](url)#L1055

**Comment by jackeykong** [comment]
> Because the formatter stores some state that might change (e.g. date/time caching).

I see!! But why store date/time? Is it because the "get_time_" function on line 1055 of the "pattern_formatter-inl.h" file is inefficient?
`SPDLOG_INLINE void pattern_formatter::format(const details::log_msg &msg, memory_buf_t &dest)
{
    auto secs = std::chrono::duration_cast<std::chrono::seconds>(msg.time.time_since_epoch());
    if (secs != last_log_secs_)
    {
        cached_tm_ = get_time_(msg);
        last_log_secs_ = secs;
    }

    for (auto &f : formatters_)
    {
        f->format(msg, cached_tm_, dest);
    }
    // write eol
    details::fmt_helper::append_string_view(eol_, dest);
}`

**Comment by jackeykong** [comment]
> Because the formatter stores some state that might change (e.g. date/time caching).

I see!! But why store date/time? Is it because the "get_time_" function on line 1055 of the "pattern_formatter-inl.h" file is inefficient?
`
SPDLOG_INLINE void pattern_formatter::format(const details::log_msg &msg, memory_buf_t &dest)
{
    auto secs = std::chrono::duration_cast<std::chrono::seconds>(msg.time.time_since_epoch());
    if (secs != last_log_secs_)
    {
        cached_tm_ = get_time_(msg);
        last_log_secs_ = secs;
    }

    for (auto &f : formatters_)
    {
        f->format(msg, cached_tm_, dest);
    }
    // write eol
    details::fmt_helper::append_string_view(eol_, dest);
}
`

**Comment by jackeykong** [comment]
> Because the formatter stores some state that might change (e.g. date/time caching).

I see!! But why store date/time? Is it because the "get_time_" function on line 1055 of the "pattern_formatter-inl.h" file is inefficient?
