### ISSUE TITLE
how to use spdlog in a deamon process

### ISSUE THREAD

**Issue by zhoutotong** [gabime/spdlog#2105]
I have a deamon process, and I try to log some info to log file, it 
work well with common process, and can not log to file with deamon.

daemon(0, 1);

**Comment by tt4g** [comment]
I can't guess what is going on because of the little information provided.

spdlog will report errors by error handler (default print message to `STDERR') when it fails to work.
Please check the message printed by the error handler.
Wiki: https://github.com/gabime/spdlog/wiki/Error-handling

**Comment by zhoutotong** [comment]
think you very much for your respones. I can offer you a test program code:

`#include <stdlib.h>
#include <signal.h>
#include <sys/time.h>
#include <unistd.h>

#include <spdlog/cfg/env.h>
#include <spdlog/async.h>
#include <spdlog/async_logger.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/rotating_file_sink.h>


const std::string path_to_log_file = "./";

int main(int argc, char **argv)
{

   const std::string module = "spdlog_test";
   spdlog::init_thread_pool(8192, 1);
   auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
   console_sink->set_level(spdlog::level::trace);

   std::size_t max_size = 1024 * 1024 * 5;
   std::size_t max_files = 1024;

   std::string logFile = module + ".log";

   auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(path_to_log_file + "/" + logFile, max_size, max_files);
   file_sink->set_level(spdlog::level::info);

   std::vector<spdlog::sink_ptr> sinks{console_sink, file_sink};

   auto logger = std::make_shared<spdlog::async_logger>(module, sinks.begin(), sinks.end(),\
                                                         spdlog::thread_pool(), spdlog::async_overflow_policy::block);

   spdlog::register_logger(logger);
   daemon(0, 1);


   logger->info("this is a test info msg.");

   // while (true)
   // {
   //    /* code */
   // }
   

   return 0;
}`

spdlog version: 
#define SPDLOG_VER_MAJOR 1
#define SPDLOG_VER_MINOR 8
#define SPDLOG_VER_PATCH 0

after run this program, it can only create log file(spdlog_test.log), and the log file is empty.

**Comment by tt4g** [comment]
`daemon()` calls `fork()` internally.
`fork()` shares memory with the parent process.
And since the parent process that called `daemon()` exits, it is expected that the files that the parent process had opened will be closed.

I think that if you create the sink and logger after calling `daemon()` (i.e. after the daemon process starts), the log will be written.

**Comment by zhoutotong** [comment]
thank you very much, you are right, my problem had fixed.
