### ISSUE TITLE
Cannot find spdlog functions via Conan/Cmake

### ISSUE THREAD

**Issue by howardjp** [gabime/spdlog#2108]
I am trying to use spdlog with Conan/CMake and am having some difficulty.  I am not sure if the problem might be in either Conan or CMake, or somewhere else, but I am hoping someone here has seen the problem.

I have an application that pulls in spdlog 1.8.0 via Conan, finds it, then links against it.  This all works perfectly on my Mac development machine and has all along.  I am trying to get a CI process up and running with GitHub Actions and the process is breaking down in the link phase with linker errors with undefined [references to various spdlog objects (link to action history)](https://github.com/k3jph/kami/runs/3625512076).  I connected to a Codespace and encountered similar problems.  It appears to be an issue specific to the Linux platform.

I have tried different versions of spdlog, both g++ and clang++, and many other attempts to correct this, with no effective solution available.  Has anyone else seen this and do you know what the solution may be?

Thanks! James

**Comment by tt4g** [comment]
The library built by Conan seems to be linked with libstdc++.
Isn't it due to the incompatibility of the C++ library that CI is trying to link to?
See: https://stackoverflow.com/a/62005571

Or use `--build` policy that `conan install` option: https://docs.conan.io/en/latest/mastering/policies.html

**Comment by howardjp** [comment]
Thanks, that was the hint I needed.  I added this:

    conan config init
    conan profile update settings.compiler.libcxx=libstdc++11 default

And, just for fun:

   conan frogarian

To the build.yml and everything is much better.  Well, I crashing out later, but now it's in Sphinx.

Thakn you, J~
