### ISSUE TITLE
‘error’ is not a member of ‘spdlog’

### ISSUE THREAD

**Issue by jin-111** [gabime/spdlog#2109]
I compile with code `spdlog::error("ensureValid(Point)>> {},{},{} value out of range", x, y, z);` on ubuntu 18. Tips :
```
error: ‘error’ is not a member of ‘spdlog’
       spdlog::error("ensureValid(Point)>> {},{},{} value out of range", x, y, z);
```

**Comment by tt4g** [comment]
You are forget `#include "spdlog/spdlog.h"`.

**Comment by jin-111** [comment]
> You are forget `#include "spdlog/spdlog.h"`.

Sorry, but I have added it. The following code will have an error “spdlog has no member info”, as does the above code.
```
#include "spdlog/spdlog.h"

int main(){
    spdlog::info("Starting");
}
```

**Comment by tt4g** [comment]
How did you get spdlog source?
If you are using `master` branch, it is not current branch (`v1.x` is current).

**Comment by jin-111** [comment]
> How did you get spdlog source?
> If you are using `master` branch, it is not current branch (`v1.x` is current).

I download by zip with the version v1.x and v1.9.2

**Comment by tt4g** [comment]
It's strange. Those functions are present in the current spdlog.

Make sure you don't have the old spdlog installed on your machine.

**Comment by jin-111** [comment]
> It's strange. Those functions are present in the current spdlog.
> 
> Make sure you don't have the old spdlog installed on your machine.

Thank you. I will check it.
