### ISSUE TITLE
Way of setting global macro logging level at compile time

### ISSUE THREAD

**Issue by LukerMaster** [gabime/spdlog#2110]
Hi, I've tried to create a small macro-type logging wrapper using spdlog and various other logging methods but I ran into an issue when I wanted to include DEBUG and TRACE messages.

The idea is that I wanted to create a system that allows you to choose what logging library/method to use by simply setting
`#define MYWRAPPER_LOGGER_TYPE SPDLOG` for example.

I'm trying to make it work in a way so if you set `#define MYWRAPPER_LOG_LEVEL NONE` every logging call gets replaced with `(void)0` to effectively add 0 performance penalty for logging.

The main issue is that spdlog requires you to call `spdlog::set_level(spdlog::level::trace)` to include DEBUG and TRACE messages **alongside** with `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE`. I cannot call `set_level` using preprocessor only.

It would be fine if only the `SPDLOG_ACTIVE_LEVEL` macro would need to be set, but apparently I need both.

Is there a way around it? Any way to use just preprocessor to set logging level?

**Comment by tt4g** [comment]
There is no macro to set the log level at runtime.
Use the `SPDLOG_ACTIVE_LEVEL` macro in your project code to set it.

```c++
#if SPDLOG_ACTIVE_LEVEL == SPDLOG_LEVEL_TRACE
spdlog::set_level(spdlog::level::trace);
#elif SPDLOG_ACTIVE_LEVEL == SPDLOG_LEVEL_DEBUG
spdlog::set_level(spdlog::level::debug);
#elif SPDLOG_ACTIVE_LEVEL == SPDLOG_LEVEL_INFO
spdlog::set_level(spdlog::level::info);
#elif SPDLOG_ACTIVE_LEVEL == SPDLOG_LEVEL_WARN
spdlog::set_level(spdlog::level::warn);
#elif SPDLOG_ACTIVE_LEVEL == SPDLOG_LEVEL_ERROR
spdlog::set_level(spdlog::level::err);
#elif SPDLOG_ACTIVE_LEVEL == SPDLOG_LEVEL_CRITICAL
spdlog::set_level(spdlog::level::critical);
#endif
```

**Comment by LukerMaster** [comment]
That does not really answer my question. I know there is no way of using macros to switch levels at runtime. I just need a way to set the global level at compile time.

That means when I'm debugging I can set `#define DEBUG 1` and all my **macro-type** logs are in the code. When I'm releasing a public version of a program I can set `#define DEBUG 0` and that would cut out all the logging from the program before it is even compiled.

The problem is that I kinda cannot use anything other than just preprocessor statements, which complicates things as spdlog requires you to set the global level using an actual function call. This wouldn't be an issue if the default out-of-the-box level was set to TRACE (and I'm talking about the `set_level()` setting, not the `SPDLOD_ACTIVE_LEVEL` setting).
This also wouldn't be an issue if you could set only `SPDLOG_ACTIVE_LEVEL` to `TRACE`, but you need to set both the `SPD_ACTIVE_LEVEL` and the `spdlog::setlevel()` for the **macro-type** logging to work.

Why cannot I use anything other that preprocessor? Since I'm choosing logging method using a preprocessor statement like `#define LOGGING_LIB SPDLOG` for example. I cannot add any actual logging function calls to the main program, everything about the logging needs to be fully macro-ized for 0 performance penalty when the actual program is released.

**Comment by tt4g** [comment]
You mean you want the default logger level to be something other than `spdlog::level::info`? (The following code).

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/logger.h#L314-L315

The reason you can't change the default logger level is probably because no one has ever needed it before.
Pull request is welcome.
