### ISSUE TITLE
Ability to log perror

### ISSUE THREAD

**Issue by fabiomanz** [gabime/spdlog#2115]
Hi,

I am converting my project to use spdlog as my logging library. In that project I use a lot of perror() calls.

Do you think it would make sense to add a function **perror** to the logger class? You could have one parameter for an additional message and then append `strerror(errno)` to that message.

Do you think you could implement something like that?

Thank you very much,
Fabio

**Comment by gabime** [comment]
You can create a custom format flag for this.
