### ISSUE TITLE
Can't display source file name and line number

### ISSUE THREAD

**Issue by sayedmomeen** [gabime/spdlog#2127]
Logging level is set depending on configuration. on debug level i need to display src file name, functions and line number. I tried a sample and its not working as expected.
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>

int main(int argc, char *argv[])
{
    std::shared_ptr<spdlog::logger> logIt = nullptr;
    logIt = spdlog::basic_logger_st("Mytest","LogTestMe.txt",true);
    logIt->set_pattern("[%D %H:%M:%S.%f][%L][src %s][fn %!][ln %#] %v");
    spdlog::set_pattern("[%D %H:%M:%S.%f][%L][src %s][fn %!][ln %#] %v");
    logIt->set_level(spdlog::level::debug);
    spdlog::set_level(spdlog::level::debug);
    logIt->flush_on(spdlog::level::debug);
    logIt->debug("flush this shit.");
    spdlog::debug("flush out shit.");
}

**Comment by gabime** [comment]
see faq https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format
