### ISSUE TITLE
Structured logging?

### ISSUE THREAD

**Issue by Falmarri** [gabime/spdlog#2134]
Are there any plans to add support for structured logging? I found this library that's built off of spdlog https://github.com/takeshibaconsuzuki/structlog/ but it's brand new and my team would much prefer going with a "standard" library with a history of releases and development.

**Comment by pravic** [comment]
@gabime This was closed as completed, but no references to the PR or a commit to where exactly this was completed. Any links?

**Comment by gabime** [comment]
@pravic Sorry for the confusion. There is no plan to support this at the moment

**Comment by gabime** [comment]
Closed again.
