### ISSUE TITLE
throwing exceptions at line_logger destructor

### ISSUE THREAD

**Issue by icexile** [gabime/spdlog#214]
Hi, when I using spdlog on android with android sink, I found spdlog may throwing exceptions in line_logger's destructor, and cannot be catched by my outer functions, which cause crashes.

spdlog::details::line_logger::~line_logger()
   -> _callback_logger->_log_msg(_log_msg)
       -> sink->log(msg)
             -> base_android_sink::_sink_it()
                  ->throwing spdlog_ex
                       -> crash

**Comment by gabime** [comment]
related to #136

**Comment by gabime** [comment]
Fixed. line_logger removed after (removing streaming API)
