### ISSUE TITLE
Better documentation support for compiled lib

### ISSUE THREAD

**Issue by ZackOfAllTrades** [gabime/spdlog#2155]
For context Im new to spdlog, I eventually stumbled upon the magic macro to save the day SPDLOG_COMPILED_LIB, I'm using a giant external library that uses spdlog,I knew it was a header only lib but they went the route of static lib. I wish this magic macro would have been mentioned under the Install section in the readme to save a couple of hours of frustration. Here's hoping we we save the next dev. Thanks!

**Comment by gabime** [comment]
Thanks. PR is welcome. Also the wiki docs are open for all to edit.
