### ISSUE TITLE
Perfect forwarding for arguments spdlog change

### ISSUE THREAD

**Issue by matt77hias** [gabime/spdlog#2158]
What is the purpose of 23572369fced02f41cc1cfef061540192df56986: "Perfect forwarding for arguments"?

I get the perfect forwarding for `make_unique` (e.g., `add_flag`). But what is the benefit of perfect forwarding the formatting arguments? This is unnecessary; both `<format>` and `{fmt}` pass arguments as lvalue references. Furthermore, this unnecessarily increases the number of template instantiations (_and potentially the binary size_).

cc @dkavolis

**Comment by dkavolis** [comment]
This is needed by `fmt` to work with views as it doesn't allow passing them by lvalue. Forwarding the arguments is probably no longer needed with `fmt::basic_format_string` as the validation happens at the call site.

https://github.com/fmtlib/fmt/blob/3b6e409cd8573f63e4acad7717d9082bd898ec87/include/fmt/core.h#L3009-L3013

**Comment by matt77hias** [comment]
Thanks for the info 👍

**Comment by gabime** [comment]
@matt77hias  Out of curiosity, why does it increases the number of template instantiations ?

**Comment by matt77hias** [comment]
`const Foo&` and `Foo&&` are different types.

Before they would both be passed as `const Foo&`.
Now they are passed as `const Foo&` and `Foo&&`, respectively.
