### ISSUE TITLE
How to shutdown and restart in the same program?

### ISSUE THREAD

**Issue by KevinLucidyne** [gabime/spdlog#216]
I'm using spdlog to run logs for both managed and unmanaged code in Visual Studio. For that reason I've written shell classes that use spdlog under the hood.

However, I'm running into problems with my unit tests.  My unit tests run in a single executable and so need to stop and restart spdlog loggers and logfiles multiple times.

How do I do this?  I'm using this code in a class to currently start instances of spdlog in a Windows DLL:

                 private:
			API static std::mutex _mutex;
			API static std::shared_ptr<spdlog::logger> _instance;

			static std::shared_ptr<spdlog::logger> Instance()
			{
				std::unique_lock<std::mutex> lck(_mutex, std::defer_lock);
				lck.lock();
				if (_instance == nullptr)
				{
					_instance = spdlog::rotating_logger_mt("Logger", "EXO", 1024 * 1024 * 5, 4, true);
				}
				lck.unlock();
				return _instance;
			}

**Comment by gabime** [comment]
you should release it using spdlog::drop("Logger") and then you can just destruct it

**Comment by KevinLucidyne** [comment]
Thanks!  I was trying spdlog::dropall() but that didn't work.

On Fri, May 20, 2016 at 3:30 PM, Gabi Melman <notifications@github.com>
wrote:

> you should release it using spdlog::drop("Logger") and then you can just
> destruct it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gabime/spdlog/issues/216#issuecomment-220733703>
>



-- 
Kevin Johnsrude
Senior Software Engineer
Lucidyne Technologies, Inc.
155 SW Madison Ave.
Corvallis, Oregon 97330
541 753 5111
www.Lucidyne.com

**Comment by gabime** [comment]
don't forget to delete the object itself too
