### ISSUE TITLE
How to print file and line numbers with custom formatting?

### ISSUE THREAD

**Issue by apoorv569** [gabime/spdlog#2160]
I have created this custom format for logging messages,,

```cpp
        spdlog::set_pattern("%^[%-T] [%-n] [%l]: %v %@%$");
```

as you can see I have `%@` for the `file:line_num` but it doesn't get printed if I use,

```cpp
        s_Logger = spdlog::stdout_color_mt(logger);
        s_Logger->set_level(spdlog::level::trace);

        s_Logger->info("some message here..");
```

However if I use,

```cpp
        SPDLOG_INFO("some message here..");
```

It does print file and line number but doesn't print things like the logger name.

```
[14:24:58] [SampleHive] [info]: some message here..
[14:24:58] [] [info]: some message here.. ../src/Utility/Log.cpp:19
```

 I want the logger name as well. How do I solve this problem?

**Comment by gabime** [comment]
```SPDLOG_LOGGER_INFO(s_logger, "some message here..");```

**Comment by apoorv569** [comment]
> ```c++
> SPDLOG_LOGGER_INFO(s_logger, "some message here..");
> ```

Nice, thanks these `macros` seem to work, however the `SPDLOG_LOGGER_DEBUG` and `SPDLOG_LOGGER_TRACE` doesn't seem to print anything.

```cpp
        SPDLOG_LOGGER_TRACE(s_Logger, "Some message here..");
        SPDLOG_LOGGER_INFO(s_Logger, "Some message here..");
        SPDLOG_LOGGER_WARN(s_Logger, "Some message here..");
        SPDLOG_LOGGER_DEBUG(s_Logger, "Some message here..");
        SPDLOG_LOGGER_ERROR(s_Logger, "Some message here..");
        SPDLOG_LOGGER_CRITICAL(s_Logger, "Some message here..");
```

This only prints these one's,

```
[17:01:07] [SampleHive] [info]: Some message here.. ../src/Utility/Log.cpp:17
[17:01:07] [SampleHive] [warning]: Some message here.. ../src/Utility/Log.cpp:18
[17:01:07] [SampleHive] [error]: Some message here.. ../src/Utility/Log.cpp:20
[17:01:07] [SampleHive] [critical]: Some message here.. ../src/Utility/Log.cpp:21
```

**Comment by gabime** [comment]
Thats because the default log level is info.

**Comment by apoorv569** [comment]
> Thats because the default log level is info.

But I have set the log level to trace,

```cpp
            s_Logger = spdlog::stdout_color_mt(logger);
            s_Logger->set_level(spdlog::level::trace);

            SPDLOG_LOGGER_TRACE(s_Logger, "Some message here..");
            SPDLOG_LOGGER_INFO(s_Logger, "Some message here..");
            SPDLOG_LOGGER_WARN(s_Logger, "Some message here..");
            SPDLOG_LOGGER_DEBUG(s_Logger, "Some message here..");
            SPDLOG_LOGGER_ERROR(s_Logger, "Some message here..");
            SPDLOG_LOGGER_CRITICAL(s_Logger, "Some message here..");
```

Or should I use,

```cpp
            SPDLOG_LOGGER_CALL(s_Logger, spdlog::level::trace, "Some message here");
```
and specify log level for all `CALL` macros?

**Comment by tt4g** [comment]
Don't forget to set `SPDLOG_ACTIVE_LEVEL` macro.

```cpp
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE

#include "spdlog/spdlog.h"

...

            s_Logger = spdlog::stdout_color_mt(logger);
            s_Logger->set_level(spdlog::level::trace);

            SPDLOG_LOGGER_TRACE(s_Logger, "Some message here..");
            SPDLOG_LOGGER_INFO(s_Logger, "Some message here..");
            SPDLOG_LOGGER_WARN(s_Logger, "Some message here..");
            SPDLOG_LOGGER_DEBUG(s_Logger, "Some message here..");
            SPDLOG_LOGGER_ERROR(s_Logger, "Some message here..");
            SPDLOG_LOGGER_CRITICAL(s_Logger, "Some message here..");
```

Read Wiki; https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

**Comment by apoorv569** [comment]
> Don't forget to set `SPDLOG_ACTIVE_LEVEL` macro.
> 
> ```c++
> #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
> 
> #include "spdlog/spdlog.h"
> 
> ...
> 
>             s_Logger = spdlog::stdout_color_mt(logger);
>             s_Logger->set_level(spdlog::level::trace);
> 
>             SPDLOG_LOGGER_TRACE(s_Logger, "Some message here..");
>             SPDLOG_LOGGER_INFO(s_Logger, "Some message here..");
>             SPDLOG_LOGGER_WARN(s_Logger, "Some message here..");
>             SPDLOG_LOGGER_DEBUG(s_Logger, "Some message here..");
>             SPDLOG_LOGGER_ERROR(s_Logger, "Some message here..");
>             SPDLOG_LOGGER_CRITICAL(s_Logger, "Some message here..");
> ```
> 
> Read Wiki; https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

Okay, it works now . Needed to define that macro. Thanks :D
