### ISSUE TITLE
Add root cause context of spdlog errors

### ISSUE THREAD

**Issue by chill1n** [gabime/spdlog#2161]
To handle a spdlog error, I define spdlog::set_error_handler() like this:

   spdlog::set_error_handler( [](const std::string& msg) {
      fmt::print(stderr, "[*** LOG ERROR ***] [{:%H:%M:%S}] {}\n",
            std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()), msg); 
   });

It gives a more precise hint as to where the logging issue might be located in the code (using millisecond accuracy). But in the case of a complex code base with multiple threads and a lot of logging lines, it's still quite painful to find the root cause of a logging error.

If only the error handler would be given the function name (__func__) and line number (__LINE__) of the log line that causes the error handler to be called, it would be directly clear what the problematic line is.

**Comment by chill1n** [comment]
I checked out the branch. Indeed that would be good enough for me.
However the hard-coded string message containing the file name and line number is relatively restrictive. For instance, a user cannot only print the base name of the file name. On the other hand, it's not needed to fix the logging problem. But perhaps in a customer environment it might show too many (perhaps proprietary) implementation details. It is more generic to pass source_loc to the error_handler function. For backwards compatibility both error_handler function signatures could be supported.

**Comment by chill1n** [comment]
I pulled the latest 1.x code to check out the functionality, but couldn't see any difference; no file name or line numbers. How is this functionality enabled (so that source_loc is filled and passed to the log call)? The use model is not clear to me.

**Comment by tt4g** [comment]
Since source_loc is information for debugging purposes, it will always be empty unless you are using a logging macro.

See Wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

**Comment by chill1n** [comment]
Thanks. It's clear now.  
However, I think that the current use model is less flexible than the one I proposed. Is the reason for this choice that with macros it's easy to get the required preprocessor data?

**Comment by gabime** [comment]
How can you get the source location of the caller without macros and without c++20 ?

**Comment by tt4g** [comment]
The purpose of the logging macro is to remove unnecessary logging statements at compile time.
And it also provides information for debugging (source file name, line number).

**Comment by chill1n** [comment]
Without C++20 and macros it is indeed not possible to get the proper function name and line number in a logger line.  
I'll write my own macros to realize my goal. It's time for some refactoring anyway. Thanks for the help and the short discussion. I'll close this issue.
