### ISSUE TITLE
spdlog design and crash issues

### ISSUE THREAD

**Issue by scottzhang** [gabime/spdlog#217]
I am in charge of a middle size(100-1000 clients normally) network server, we were using log4cpp but it looks has some memory-leak which crash our server so we abondan it. 
As I was searching for an replacement, I found boost.log(we tried, it is not human friendly to use), easylogging and spdlog, by read the readme looks spdlog is the fatest so I start with this firstly. 
I have finished my integration of spdlog, but the result is not good. We notice following issues:
We server application is based on boost.asio+threadpool(10 threads) so with 100 clients, the normal memory consumption is 60M+ and 10 threads total, CPU usage is about 30% of single core on 4 cores server.  
1. async mode
As all our code is using boost.asio, all  async running, so async mode is prefer. By copy the example code, first problem is the memory consumption goes up to 4G. At first, after use valgrid, we track to spdlog, and by 
test, we found the qsize can't be 1M, we change it to 4K. now the program take about 90M memory which is acceptabel. 
size_t q_size = 4096;
	spdlog::set_async_mode(q_size, spdlog::async_overflow_policy::block_retry,
                       nullptr,
                       std::chrono::seconds(5));

Then the problem with spdlog async, as we have 100+ clients, we want each clients writes its own log, so give each client its own spdlog object. Looks cpu usage goes up but don't know why until we use gdb to debug a coredump, we found there are many many threads in program. As  we only use 10 threads pool and spdlog is the only newly added library. so we have to turn async off. As async off, looks cpu usage is 2-4x higher than our normal use .

2. throw exceptions
Throw exception is driving me crazy. Don't know why it throws.
We have spdlog in four type classes:
1. Database
2. Threshold
3. Client Sessions
4. Server object
I have to use 
try
	{
		spdloger_ = spdlog::rotating_logger_mt ("threshold", "logs/threshold", 1048576 * 50, 1);
		spdloger_->set_level (spdlog::level::trace);
	}catch(spdlog::spdlog_ex ex)
	{
		std::cout<<"OpenLog threshold Exception:"<<ex.what()<<std::endl;
	}
to open and try catch.
	template <typename... Args>
	void InfoLog(const char* fmt, const Args&... args)
	{
		boost::mutex::scoped_lock lLock(logMutex);
		if(spdloger_ != nullptr)
		{
			try
			{
				spdloger_->info(fmt, args...);
			}catch(spdlog::spdlog_ex ex)
			{
				std::cout<<"InfoLog Exception:"<<ex.what()<<std::endl;
			}
		}			
	}
to log, all use with try-catch but can't stop it throw 
can't open log/threshold.txt" for writing 
exception which immediately crash my server.
After read "https://github.com/gabime/spdlog/issues/136"
I define
// Check if exceptions are disabled.
#if defined(__GNUC__) && !defined(__EXCEPTIONS)
# define FMT_EXCEPTIONS 0
#endif
#if defined(_MSC_VER) && !_HAS_EXCEPTIONS
# define FMT_EXCEPTIONS 0
#endif
#ifndef FMT_EXCEPTIONS
# define FMT_EXCEPTIONS 0  //Make it 0 defaultly
#endif

Now FMT_EXCEPTIONS is 0 but it throws exception all same. 
And the wierd thing is Database and Threshold use same code, why only threshold class throw exception all the time but database not. From application logic , threshold runs about 100x faster than database object, because each client needs to run data agaist rules to check, which means it has 100x log request than other, is this the reason it throw exception each time? So I guess spdlog is not ready for 100x  thread call on single object log. you can see i used lock&mutex to prevent thread race.
Then I have to disable spdlog in threshold object and program stop throw exception. 

So what I think spdlog need to improve in following points:
1. async mode, use thread pool, use at most, eg 2-5 threads. We are running code on server with 4 cores, we have use at most 2.4x 10 threads pool. 
2. sync mode, looks sync mode take too much steps to write single line into log, comparing with log4cpp, which looks it consume more cpu(unconfirmed, only view by eye compare). Should make it very simple, just write line into file, no more line object construction&deconstruciton,
3. throw exception, as another friends say in #136, we don't need throw exception, log for us is not an critical problem, I don't want to log crash our program. especially uncatchable exception. 
4. for over 100+ client-session-object calling same spdlog object to write log, as I use lock to prevent this, I don't know why it still throw exceptions. So need to fix this.

**Comment by scottzhang** [comment]
for "can't open log/threshold.txt" for writing"
I am pretty sure it has openned threshold for writing and has written many lines of code in. Just during the logging process, it suddenly give the exception. Don't know what trigger this.

**Comment by gabime** [comment]
I think he problem is that you have multiple loggers writing to the same log file. spdlog doesnt support this. each logger should write to its own file. also, no locking should be done. spdlog is thread safe..

**Comment by scottzhang** [comment]
ThresholdController is a singleton, which only has one instance. So there is no possibility for multiple logger writing to same log file. 

using namespace Loki;
typedef SingletonHolder<ThresholdController, CreateUsingNew, PhoenixSingleton> ThresholdControllerInstance;

And one thing I think may interfere with spdlog is I used "posix_spawn", but according to doc, I let newly created process not inherent  the open file descriptor. 

		posix_spawnattr_t attr;
		posix_spawn_file_actions_t fact;
		posix_spawnattr_init(&attr);
		posix_spawn_file_actions_init(&fact);
		status = posix_spawn(&pid, "/usr/bin/node", &fact, &attr, argv, environ);


usually, before spawn, it doesn't throw threshold.txt exception, after spawn, and usually runs for another 60+seconds, I get this exception.

**Comment by gabime** [comment]
This probably explains it. you have multiple processes writing to the same log file, each trying to rotate it when it gets full, and bad things happen..

**Comment by gabime** [comment]
try using latest version. There is big cleanup in regarding of exceptions ( no more exception from dtor ' no more line_logger)

**Comment by scottzhang** [comment]
Once again, I come back. Now the problem is not with the fork log.
First, our server design with 10 threads pool in total whatever how many clients connected. 
1. performance  - not good
Now our server handles 400+ network clients, each clients with a spdlog object, which gives me extra 400+ spdlog threads. The cpu usually without spdlog is about 25%, with spdlog log added in goes up to 80%. Memory consumption goes from 200M+ to 600M+ and still climbing before crash.

2. Unknown heep corruption introduced
Our server code programmed with c++ heavily with smart pointer, there are no new/malloc in code.  And when handle with memory buffer directly , we add heavily barrier to prevent memory overflow or underflow.  But there are still unknown crash , which usually crashed on string/stringstream construction. 
After remove spdlog, the crash issue disappear.  
The problem I guess is with "formating", some things wrong. but I don't have time to debug this library so have to remove this.

So I conclude spdlog is not good for the multiple-clients scenario. too many threads introduced, and crash issue. For small project, desktop or small server, may be good.

**Comment by gabime** [comment]
Sorry, but this is **not** how spdlog should be used (hundreds of independent async log objects) . 
The right design would be using one (or several) loggers shared bewteen all the clients.

**Comment by scottzhang** [comment]
So if I only use single instance of spdlog, could it be configured to different log files for different clients?
I don't see use case in example. the construct function need a file name so how to separate different log files? 
If the CPU usage can down and crash issue resolved, I still like the template log function with is easy to use than old printf like log functions.

**Comment by gabime** [comment]
If you need hundreds of log files, then I suggest you try the regular synchronous logger. It is still very fast (can reach millions logs/sec, see the bench) ,and you can create hundreds of those..

If each logger is not accessed by different threads, you could create  single-threaded loggers  for even better results (```spdlog::rotating_logger_st(...)```.

The recommended way to create them would be (without the overhead of registering them in spdlog internal registry):
```c++
auto sink = std::make_shared<spdlog::sinks::rotating_rotating_file_sink_st>("unique_filename_per_client", ".txt", maxsize, max_files, force_flush));
auto my_logger= std::make_shared<spdlog::logger>("mylogger", sink);
```

Otherwise, If you want to use the regular factory methods (```spdlog::rotating_logger_st("some_name"```)  make sure to give unique name for each logger and **most importantly call spdlog::drop(rotating_logger->name())** when closing the looger to force destructing the logger and closing the file..

**Comment by scottzhang** [comment]
As I run only 10 threads pool to handle all the clients, async operation is preferred, which make the main process operation no waiting for anything, write to file is a thing. No matter how fast sync-logger is, it still need to write to disk, which make no difference but only worse because introduced high abstruction  comparing to a simple c++ write to file, which introduce delay. 
So best solution will be async logger with thread pool, I think I could do a wrapper around spdlog, wrapper class is async, and the read write is sync-log.  But I don't know yet a method about  how to pass variable arguments to templated log function  then pass to async callback

**Comment by gabime** [comment]
no need for wrappers. I am open to the idea of modifying spdlog to use global thread pool.

i will be happy to get a pull and maybe the integrate in main branch

**Comment by IshNar** [comment]
can you teach me how to use correctly?
