### ISSUE TITLE
Basic spd coloring unsupported on different linux terminal emulators [SOLVED]

### ISSUE THREAD

**Issue by rfmineguy** [gabime/spdlog#2177]
I have come across an issue where the coloring you are supposed to get from **spdlog::stdout_color_mt(...)** doesn't work in the Alacrity terminal emulator. However when i tested it through the default bash shell, the coloring worked just fine. I;m not sure if this is a problem with how Alacrity is set up or not though.

Using the latest released version of spdlog in Alacrity version **alacritty 0.9.0 (fed349aa)**

**Comment by rfmineguy** [comment]
I did some more digging, and found that **spdlog::details::os::is_color_terminal()** is false in alacrity even though it clearly does support color.

**Comment by rfmineguy** [comment]
Solved. Turns out that the way the library determines whether a terminal has color support is just a hard coded array of strings. So in **details/os.h** i just added "alacritty" to the list. Not sure if this is the best/correct way, but it is a way. I'll mak this as solved.

**Comment by rfmineguy** [comment]
Note: I must've had an old version. The changes i made are in the new version I cloned.

**Comment by gabime** [comment]
@rfmineguy which change fixed it?

**Comment by rfmineguy** [comment]
The first fix was adding "alacritty" to the accepted color terminals (in os.h), but then I switched to an updated version. I went to look at what I changed earlier and the fix was the same.
