### ISSUE TITLE
Source location in output string

### ISSUE THREAD

**Issue by romka0017** [gabime/spdlog#2178]
Hello
I use spglog, and for Trace level it prints information about file and line. But for another logging levels i don't see this info. Where can i find setting of this feature?

**Comment by tt4g** [comment]
Logging macros less than the `SPDLOG_ACTIVE_LEVEL` macro level will be removed.

See Wiki:

* https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-
* https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

**Comment by romka0017** [comment]
Hello, tt4g
In my situation I see information from all levels, but source location only for Trace.
From you description about SPDLOG_ACTIVE_LEVEL it looks like full removing from code for several levels.

**Comment by gabime** [comment]
Please provide sample code to demonstrate the problem

**Comment by romka0017** [comment]
I can't provide our wrapper over spdlog now. But we use clear spdlog under our wrapper.
I only want to understand, is it correct behavior that we have information about source location only in Trace mode?
Can we change it and have for another levels of logging?

**Comment by tt4g** [comment]
If you are using logging macros, spdlog will print the source location regardless of the log level.
