### ISSUE TITLE
Change sinks at runtime (global logger)

### ISSUE THREAD

**Issue by Nooby4Ever** [gabime/spdlog#218]
Is it possible to change the sinks of a global logger at run time without having to "get" the logger again?

**Usecase:** having a global logger (`simple_file_sink`, no auto flush), during run time i want to add a second `simple_file_sink` and later remove it again. This while not have to do a "get" again everywhere i log. (i do a `spdlog::get` for the global logger in the constructor of my class, once)

Flow, file1 logs everything file2 and 3 only parts:
```
File1 - File2 - File3
1
2
3        3
4        4
5        5
6        6
7
8                  8
9                  9
10
```
(in reality the file names, `File2` and `File3`,  are dynamic at runtime, so i can not register them at the start)
***

My attempt was to use
```
_logger->flush(); // _logger = spdlog::get("logger"); in constuctor
std::vector<spdlog::sink_ptr> sinks;
sinks.push_back(std::make_shared<spdlog::sinks::simple_file_sink_st>("File1.log", false));
... // and other simple_file_sink(s)
auto newLogger = std::make_shared<spdlog::logger>("logger", begin(sinks), end(sinks));
spdlog::get("logger").swap(newLogger);
```
every time i want to add/remove a file. So the `"logger"` always has `File1` and optionally `File2` or `File3`. 
This approach will make the `file2` and `file3` files but they are empty. `File1` will contain the full log.

Single threaded environment.

*** 
Is this possible and how?

**Comment by jiudianren** [comment]
how to implment your require?

**Comment by tt4g** [comment]
Try it.

```cpp
auto default_logger = spdlog::default_logger();
std::vector<spdlog::sink_ptr> &sinks = default_logger->sinks();

// Change `sinks` elements.
```

NOTE `spdlog::logger::sinks()` will returns `std::vector<spdlog::sink_ptr>&`, it is not thread-safe.
