### ISSUE TITLE
Is there a qt_sinks working mode with a recycling garbage collection?

### ISSUE THREAD

**Issue by cocomeow** [gabime/spdlog#2184]
- Pass through the `textDocument` property and `append` method of `TextEdit` QML component to qt_sink. 
- `clear()` method can only clean the display text content, but the logs are still occupied and run out of my memory.
-  Turn off qt_sink and use stdout instead, there will be no excessive memory usage.

https://github.com/ArkToria/ACross/blob/d396ba7e1dc33067988e9d63c4345dd126fe797c/src/view_models/logview.cpp#L42

- The memory usage of the application (`ACross`) when there are about 5,000 logs:
![image](https://user-images.githubusercontent.com/89690129/142732662-5880ec7d-adac-4002-a1d3-2daa15e5596c.png)

- Logging on TextEdit Preview
![image](https://user-images.githubusercontent.com/89690129/142732734-e8a6157d-2274-4507-8ea0-0ae6ce31a062.png)

**Comment by gabime** [comment]
This is a question to qt rather than spdlog. spdlog only appends the text.

**Comment by cocomeow** [comment]
> This is a question to qt rather than spdlog. spdlog only appends the text.

Thanks for your reminder, I should disable the `undoAndRedoStacks`
