### ISSUE TITLE
Compilation error in format.h: error: invalid use of non-lvalue array with gcc 6

### ISSUE THREAD

**Issue by WilliamTambellini** [gabime/spdlog#2185]
Compilation error with gcc6 on such a line:

https://github.com/gabime/spdlog/blob/2ab86a46d086da8a381be98ec9e50f36b9059c50/include/spdlog/fmt/bundled/format.h#L1096

```
release/extern/spdlog-src/include/spdlog/fmt/bundled/format.h: In function ‘Char* fmt::v7::detail::format_uint(Char*, UInt, int, bool)’:
extern/spdlog-src/include/spdlog/fmt/bundled/format.h:1087:68: error: invalid use of non-lvalue array
     const char* digits = upper ? "0123456789ABCDEF" : data::hex_digits;
```
data::hex_digits is indeed a char array, not a char pointer, and gcc6 was not that flexible.
A simple cast resolves the issue:
```
    const char* digits = upper ? "0123456789ABCDEF" : (const char*)data::hex_digits;
```
Same issue on data::left_padding_shifts:
```
spdlog/fmt/bundled/format.h:1501:100: error: invalid use of non-lvalue array
   auto* shifts = align == align::left ? data::left_padding_shifts
```

**Comment by tt4g** [comment]
This is fmt library problem and already fixed (fmtlib/fmt@3a044814857ea3a2734abc0df815b13731baa10a and fmtlib/fmt@e3ebf366a6612b23d64a21e0a1e788aac947be4b).
