### ISSUE TITLE
error C2280: 'std::share d_ptr<cpptoml::value<double>> std::dynamic_pointer_cast<cpptoml::value<double>,cpptoml::base>(const std::shared_ptr<cpptoml::base> &) noexcept': 

### ISSUE THREAD

**Issue by gpravada** [gabime/spdlog#2188]
When i tried to build spdlog in windows for creating .node file along with c++ sources. I got following error

unwind semantics are not enabled. Specify /EHsc [D:\Open_source_latest_build\nov-decoder-develop\node-test\build\convertaddon.vcxproj]
d:\open_source_latest_build\nov-decoder-develop\node-test\lib\includelib\spdlog_setup\details\third_party\cpptoml.h(577): error C2280: 'std::share
d_ptr<cpptoml::value<double>> std::dynamic_pointer_cast<cpptoml::value<double>,cpptoml::base>(const std::shared_ptr<cpptoml::base> &) noexcept': a
ttempting to reference a deleted function [D:\Open_source_latest_build\nov-decoder-develop\node-test\build\convertaddon.vcxproj]

**Comment by tt4g** [comment]
The cause of the error is the spdlog_setup library.
It is recommended to move this issue to https://github.com/guangie88/spdlog_setup.
