### ISSUE TITLE
%@ includes relative path to build directory

### ISSUE THREAD

**Issue by razaqq** [gabime/spdlog#2191]
Clang 13.0
Windows x64
spdlog 1.9.2
latest microsoft STL

The docs say for `%@` `Source file and line` with example `my_file.cpp:123`. This is however not the case for me.

```c++
set_pattern("%@");
```

causes `..\..\..\Client\Serializer.cpp:54` instead of `Client\Serializer.cpp:54` or just `Serializer.cpp:54`
This is caused because `__FILE__` expands to that.

On clang there exists `__FILE_NAME__`, which is just the file name without a path.
Otherwise some sort of `String::ReplaceAll(msg.source.filename, "..\\", "")` could make sense too.
Otherwise it would be nice if there was a way to set the base path for all these patterns.

**Comment by tt4g** [comment]
The format flag `％@` will print `__FILE__` and `__LINE__` macro but the format of `__FILE__` depends on the compiler (relative path, absolute path, basename).

You can use the format flag `%s:%#` that will print basename and line.

**Comment by tt4g** [comment]
Similar problem #1490 and workaround https://github.com/gabime/spdlog/issues/1490#issuecomment-603715769 on MSVC with CMake.

**Comment by razaqq** [comment]
Yes but most people dont use msvc

**Comment by tt4g** [comment]
The format flag `%s:%#` works for non MSVC.

**Comment by razaqq** [comment]
Correct but then you are not able to set a combined width of it.
Whatever i just created my own custom flag

**Comment by tt4g** [comment]
> Correct but then you are not able to set a combined width of it.
> Whatever i just created my own custom flag

This is a different issue, so I recommend to open a new issue.
