### ISSUE TITLE
How to limit file size when use daily file sink?

### ISSUE THREAD

**Issue by gzliudan** [gabime/spdlog#220]
As rotating logger can limit the file size, can daily file sink limit the file size? When the file reaches the limit, the daily logger will create a new file.

**Comment by gabime** [comment]
The daily logger does not support this.. you can write a custom sink to fit your needs.

**Comment by jeremy-bitbridge** [comment]
Is this still unsupported? It would be cool if we could add traits to a logger to combine features.

**Comment by fenglc** [comment]
Is this still unsupported?

**Comment by danielabutbul01** [comment]
Is this still unsupported?
