### ISSUE TITLE
Async loggers working on the same main thread?

### ISSUE THREAD

**Issue by lucho1** [gabime/spdlog#2202]
I'm trying to have 3 multithreaded loggers so I tried to create the 3 loggers as asynchronous loggers, however when I make them print the thread ID with the [%T] pattern, they all print the same thread which is actually the main one, shouldn't they be working in different threads?

I know this question is similar to [#385](https://github.com/gabime/spdlog/issues/385) and [#1069](https://github.com/gabime/spdlog/issues/1069), but I still don't understand why it's happening and I tried with quite a few options shown in the documentation. Maybe I'm assuming something it isn't or I'm jumping any step?

As I said, I have 2 loggers initialized as:

`logger1 = std::make_shared<spdlog::async_logger>("Logger1", _some_sink_, spdlog::thread_pool(), async_overflow_policy::block);`

`logger2 = std::make_shared<spdlog::async_logger>("Logger2", _some_sink_, spdlog::thread_pool(), async_overflow_policy::block);`

`async_file = spdlog::create_async<spdlog::sinks::basic_file_sink_mt>("async_file_logger", "../aslog.txt", true);`

As mentioned in the linked issues I also defined `#define SPDLOG_NO_TLS` right before including spdlog in the header (and also tried with uncommenting that line in _tweakme.h_), and when I use them to log, I have the next result:

![image](https://user-images.githubusercontent.com/11302677/145102625-80936ba0-961e-41f7-a517-24d047706e1c.png)

**Comment by gabime** [comment]
Which platform are you using? 
> shouldn't they be working in different threads 

No. Unless you use them from 3 different threads. How do you use those loggers? The thread id is the thread id of the calling thread.

>  I also defined #define SPDLOG_NO_TLS right before including spdlog

If you use the  compiled version you need to recompile spdlog with this flag set.

**Comment by lucho1** [comment]
I'm on Windows 10, working with Visual Studio 2019.

> No. Unless you use them from 3 different threads. How do you use those loggers? The thread id is the thread id of the calling thread.

Ah okay so I'm using it wrongly, I have to call the logger from a created thread, I wrongly assumed the logging MT was handled internally

> If you use the compiled version you need to recompile spdlog with this flag set.

I'm actually using it as a submodule, so I have it included in the project, that should compile it each time, don't?

Also, thanks for the quick response and forgot to say: it's a very good library to work with :)

**Comment by gabime** [comment]
> Also, thanks for the quick response and forgot to say: it's a very good library to work with :

Thanks :)

**Comment by lucho1** [comment]
> Ah okay so I'm using it wrongly, I have to call the logger from a created thread, I wrongly assumed the logging MT was handled internally

So just for clarification, I guess for the logging to be MT we need to create ourselves a thread and make the log there?

**Comment by gabime** [comment]
Not sure I understand. What are you trying to achieve?

**Comment by lucho1** [comment]
I'm trying to make the logging to be multithreaded, for some reason I assumed it was done internally, but it seems it doesn't, so I guess I'll have to create the 3 loggers in a different thread and make the logs from that thread?

**Comment by gabime** [comment]
No need. The async logger is using a thread pool. You didnt see different thread id since spdlog displays the  thread id of the calling thread, not of the worker thread from the pool .

**Comment by lucho1** [comment]
Aaah fine so then I guess my initial thought and code were right: just creating an async logger should already go MT... Okay thanks for the quick responses and for everything :)

**Comment by vantheo** [comment]
search a similiar question and got me here. 
So here is my situation, I have an single thread app that spin on a isolated core. I would like to add an async logger(text file logger) to it, but put the logger thread on non isolcated cores. 

The problem is even if I created thread pool before I created logger, it seems that async logger still try to create a new thread (maybe inside the thread pool, I dont know). So the end result is, I have one more thread than I requested in the init_thread_pool call.

In the init_thread_pool call, I can add a on_thread_start callback to move the thread onto non isolated cores, but the thread created by async logger will still be on the same core as the main thread, which is not desired. 

So my question, is this behavior(logger created its own thread even after thread pool is created) expected? and how do I move the logger thread onto other cores? also if my purpose is a single text file sink, is it enough for me to have just one thread in thread pool. 


```
spdlog::init_thread_pool(8192, 2, []() {
// move current thread to non isol cpus
});

std::string file_name = "/tmp/log.file";

std::string logger_name = "mylogger";

auto async_file_logger = spdlog::create_async<spdlog::sinks::basic_file_sink_mt>(logger_name.c_str(), file_name.c_str());


```
the sample coe above will give me three child thread under my main thread.
two of those are moved to non isol cpus and one is still there.

I am currently use the latest version v1.14.1

sorry I was meant to post under https://github.com/gabime/spdlog/issues/275

**Comment by tt4g** [comment]
@vantheo 

> The problem is even if I created thread pool before I created logger, it seems that async logger still try to create a new thread (maybe inside the thread pool, I dont know). So the end result is, I have one more thread than I requested in the init_thread_pool call.

spdlog may spawn threads not only for asynchronous loggers, but also for other purposes. For example, it also spawns threads for interval flush: https://github.com/gabime/spdlog/wiki/7.-Flush-policy#interval-based-flush

And the OS may also spawn threads for process management.
So, you mentioned one thread too many, but I cannot determine from the information you provided whether it was spawned by spdlog or not.

> So my question, is this behavior(logger created its own thread even after thread pool is created) expected? and how do I move the logger thread onto other cores? also if my purpose is a single text file sink, is it enough for me to have just one thread in thread pool.

The OS manages the CPU cores that run the threads; there is no way to control that in the C++ standard specification.

**Comment by vantheo** [comment]
> @vantheo
> 
> > The problem is even if I created thread pool before I created logger, it seems that async logger still try to create a new thread (maybe inside the thread pool, I dont know). So the end result is, I have one more thread than I requested in the init_thread_pool call.
> 
> spdlog may spawn threads not only for asynchronous loggers, but also for other purposes. For example, it also spawns threads for interval flush: https://github.com/gabime/spdlog/wiki/7.-Flush-policy#interval-based-flush
> 
> And the OS may also spawn threads for process management. So, you mentioned one thread too many, but I cannot determine from the information you provided whether it was spawned by spdlog or not.
> 
> > So my question, is this behavior(logger created its own thread even after thread pool is created) expected? and how do I move the logger thread onto other cores? also if my purpose is a single text file sink, is it enough for me to have just one thread in thread pool.
> 
> The OS manages the CPU cores that run the threads; there is no way to control that in the C++ standard specification.

Flush could be a place to look at, I will double check, I did setup flush_every() in my code. 
I am pretty sure the thread comes from spdlog, because if I disable spdlog part, the app runs on single thread(This is a single thread app and I am very sure about it)

**Comment by vantheo** [comment]
Yes, verified. After I commented out flush_every(), the behavior is just as expected. 
So now the question becomes is it possible to reuse the thread pool for perodic flush? or can I assign a on_thread_start callback for it as well.

**Comment by tt4g** [comment]
> So now the question becomes is it possible to reuse the thread pool for perodic flush? or can I assign a on_thread_start callback for it as well.

Interval flush runs in the single dedicated thread. Thread pools and `on_thread_start()` are not supported.

**Comment by vantheo** [comment]
> > So now the question becomes is it possible to reuse the thread pool for perodic flush? or can I assign a on_thread_start callback for it as well.
> 
> Interval flush runs in the single dedicated thread. Thread pools and `on_thread_start()` are not supported.

Thanks, problem solved! I am gonna issue flush call from my main thread.
