### ISSUE TITLE
set_level not a member function

### ISSUE THREAD

**Issue by TheFern2** [gabime/spdlog#2208]
Latest on main is giving this error when trying to set_level. I rolled back a few commits, and it works. 

This commit works
https://github.com/gabime/spdlog/tree/1f35621d720c8740234b564cb452ca4f738619df

**Comment by gabime** [comment]
In branch v1.x? which commit doesn’t compile?

**Comment by TheFern2** [comment]
@gabime I just pulled latest on default branch today. Usually I use spdlog as a submodule, but today I got that error. Everything else works fine as far as I can tell, except set_level. Does it work for you?

**Comment by gabime** [comment]
It works, otherwise the ci would fail. What is the code to reproduce ? and in which platform?

**Comment by TheFern2** [comment]
```cpp
#include <SFML/Graphics.hpp>
#include <spdlog/spdlog.h>
#include "spdlog/sinks/stdout_color_sinks.h"
#include <iostream>
#include "Config.h"
#include "Game.h"

int main()
{
    config::load_config("conf.json");
    auto clogger = spdlog::stdout_color_mt("console");
    spdlog::set_default_logger(clogger);
    spdlog::set_level(spdlog::level::debug);
    spdlog::info("{} {} started", config::app_name, config::version);

    Game game;
    game.run();

    return 0;
}

#if defined(_WIN32)
#include <windows.h>
int APIENTRY WinMain(HINSTANCE, HINSTANCE, PSTR, int)
{
    return main();
}
#endif
```

This is on visual studio 2019. Win64. If I comment out set level, application including logging runs fine. I don't have this problem with the commit mentioned in my previous comment.

**Comment by tt4g** [comment]
@gabime It looks like `include/spdlog/spdlog.h` has been updated to the contents of v2.x branch in the most recent commit (f0fa6779d289be4f0985e873118e048674c6c565 7ba5eec16ab71af40187e6953dcc02d0e9d34352).

**Comment by gabime** [comment]
Right. Seems like bad merges.

**Comment by gabime** [comment]
I cleaned up the mess I hope. 
Please verify if it indeed fixed @TheFern2  and @tt4g

**Comment by TheFern2** [comment]
@gabime thank you, all good on commit fe782edc534bed26d0f9844ff4dc525b692ad251
