### ISSUE TITLE
output error message only

### ISSUE THREAD

**Issue by xjsxujingsong** [gabime/spdlog#2209]
Hi I followed the tutorials and it can generate logs when I set kLogger->flush_on(spdlog::level::info); I can see both info and err messages are logged. But when I changed it to kLogger->flush_on(spdlog::level::err), the info message still is generated. Any suggestion? Here is the code:

spdlog::set_pattern("%Y-%m-%d %H:%M:%S:%e [%l] [%t] - <%s>|<%#>|<%!>,%v");//set output pattern

typedef spdlog::sinks::daily_file_sink<std::mutex, spdlog::sinks::daily_filename_calculator> dateonly_daily_file_sink_mt;
kLogger = spdlog::create<dateonly_daily_file_sink_mt>("kLogger", "daily_result/logs/log.log", 0, 0);
kLogger->flush_on(spdlog::level::err);

**Comment by tt4g** [comment]
Should use `spdlog::logger::set_level(spdlog::level::level_enum)` to limit output log message.

**Comment by xjsxujingsong** [comment]
@tt4g  Thanks. It works.
