### ISSUE TITLE
How to manually clear a file with basic_file_sink_mt?

### ISSUE THREAD

**Issue by HA6Bots** [gabime/spdlog#2210]
Spdlog appears to have a trancute upon construction of basic_file_sink_mt, but other then that there appears to be no method that can be called to clear the file. My current workaround is to reconstruct the basic_file_sink_mt object so that trancute is called but this is not ideal as I have to reset the level of it too. Is there any other way supported by the library to clear a file a logger is writing to that I have missed?

Thanks

**Comment by gabime** [comment]
In linux, you can try  https://linux.die.net/man/2/ftruncate 

You can get the file descriptor using the after_open event and then 

```cpp
ftruncate(fileno(fstream))
```

I am not sure it would work but worth trying..
