### ISSUE TITLE
C++20 crashes Apple-Clang 13.0.0 compiler on macos-11 (from Github Actions)

### ISSUE THREAD

**Issue by Adnn** [gabime/spdlog#2219]
I am building my repositories in Github actions for several environments. We are switching to C++20, and it triggered a compiler crash when compiling spdlog (via Conan center package `spdlog/1.9.2`) on `macos-11`.

### Minimal example

I made a repository triggering the issue: https://github.com/Adnn/spdlog192_appleclang_crash/actions/runs/1606462938

### Steps to reproduce

Running this command:

    conan install --build=missing -s compiler.cppstd=20 spdlog/1.9.2@

Results in a compiler crash on `macos-11`:

> [ 71%] Building CXX object source_subfolder/CMakeFiles/spdlog.dir/src/async.cpp.o
> clang: error: unable to execute command: Segmentation fault: 11
> clang: error: clang frontend command failed due to signal (use -v to see invocation)
> Apple clang version 13.0.0 (clang-1300.0.29.3)
> Target: x86_64-apple-darwin20.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode_13.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> clang: note: diagnostic msg: 
> 
> PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
> Preprocessed source(s) and associated run script(s) are located at:
> clang: note: diagnostic msg: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/file_sinks-937046.cpp
> clang: note: diagnostic msg: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/file_sinks-937046.sh
> clang: note: diagnostic msg: Crash backtrace is located in
> clang: note: diagnostic msg: /Users/runner/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
> clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
> clang: note: diagnostic msg: 
> 

---

I also posted on [conan-center issue tracker](https://github.com/conan-io/conan-center-index/issues/8480).

**Comment by timblechmann** [comment]
afaict fmt is the culprit here: https://github.com/fmtlib/fmt/issues/2455

**Comment by yangruihan** [comment]
I had the same problem, is this issue fixed now?

**Comment by gabime** [comment]
Should be fixed after upgrading to fmt 8.1.1

**Comment by gabime** [comment]
Yes. No release date yet.

**Comment by timblechmann** [comment]
haven't been able to test, yet, but apparently fixed it in xcode13.3
