### ISSUE TITLE
Failure at Include in Shared Library

### ISSUE THREAD

**Issue by christopher-besch** [gabime/spdlog#2226]
Hello smart people!

I'm getting a linking error when attempting to use spdlog in a shared library:
```
[100%] Linking CXX shared library libtest.so
/usr/bin/ld: spdlog/libspdlog.a(spdlog.cpp.o): relocation R_X86_64_TPOFF32 against `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: spdlog/libspdlog.a(color_sinks.cpp.o): warning: relocation against `_ZTVSt23_Sp_counted_ptr_inplaceIN6spdlog5sinks21ansicolor_stderr_sinkINS0_7details17console_nullmutexEEESaIS5_ELN9__gnu_cxx12_Lock_policyE2EE' in read-only section `.text._ZN6spdlog18async_factory_implILNS_21async_overflow_policyE0EE6createINS_5sinks21ansicolor_stderr_sinkINS_7details17console_nullmutexEEEJRNS_10color_modeEEEESt10shared_ptrINS_12async_loggerEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEDpOT0_[_ZN6spdlog18async_factory_implILNS_21async_overflow_policyE0EE6createINS_5sinks21ansicolor_stderr_sinkINS_7details17console_nullmutexEEEJRNS_10color_modeEEEESt10shared_ptrINS_12async_loggerEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEDpOT0_]'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test.dir/build.make:98: libtest.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

This is my `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.10)

project(cmake_test)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

# set(SPDLOG_BUILD_SHARED ON)
add_subdirectory("${CMAKE_SOURCE_DIR}/spdlog")

file(GLOB_RECURSE SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
# add_library(test STATIC ${SOURCES})
add_library(test SHARED ${SOURCES})
target_include_directories(test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")

target_link_libraries(test PRIVATE spdlog::spdlog)
```

When I create a static library instead (`add_library(test STATIC ${SOURCES})`), I don't get any problem at all.

You can find a minimal working example [here](https://github.com/christopher-besch/cmake_test). Make sure to clone with `--recurse`.

**Comment by tt4g** [comment]
> can not be used when making a shared object; recompile with -fPIC

The `fPIC` option needs to be added.

Try this change:

```diff
 cmake_minimum_required(VERSION 3.10)

 project(cmake_test)

 set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
+set(CMAKE_POSITION_INDEPENDENT_CODE TRUE)
```

See: https://stackoverflow.com/questions/38296756/what-is-the-idiomatic-way-in-cmake-to-add-the-fpic-compiler-option

**Comment by christopher-besch** [comment]
I've already tried `CMAKE_POSITION_INDEPENDENT_CODE` but didn't set it before including the spdlog CMake.

But this works. Thank you very much, @tt4g!


Could this maybe be added to spdlog's `CMakeLists.txt` or at least to it's documentation?

**Comment by tt4g** [comment]
`CMAKE_POSITION_INDEPENDENT_CODE` is the option that can also be enabled with the `cmake` command.

Example: `cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON (other arguments)`

When this option is specified from the command line, the `-fPIC` option will be added to all build targets, so there is no need to add this option to the spdlog project.

**Comment by christopher-besch** [comment]
> When this option is specified from the command line, the -fPIC option will be added to all build targets, so there is no need to add this option to the spdlog project.

Makes sense. Then what about a heads-up in the documentation?

**Comment by tt4g** [comment]
PR and Wiki edits are welcome.

**Comment by christopher-besch** [comment]
[done](https://github.com/gabime/spdlog/wiki/9.-CMake#using-spdlog-in-a-shared-library)
