### ISSUE TITLE
Unexpected signal handling

### ISSUE THREAD

**Issue by simone-gaia** [gabime/spdlog#2242]
Hi Gambie,

First of all, `spdlog` is great, thanks for making it available to all of us.

I tried integrating `spdlog` within a program that has its own signal handler. Now, if I send a signal to the process (`pkill -SIGHUP process`), `spdlog` seems to handle it and crashes the process:

```
[Inlined] __pthread_cond_clockwait 0x00007f6ce426cc80
__pthread_cond_clockwait 0x00007f6ce426cbe0
std::condition_variable::__do_timed_wait(std::unique_lock<…> &, std::chrono::time_point<…>) __mutex_base:506
std::condition_variable::wait_until<…>(std::unique_lock<…> &, const std::chrono::time_point<…> &) __mutex_base:421
std::condition_variable::wait_until<…>(std::unique_lock<…> &, const std::chrono::time_point<…> &, <lambda>) __mutex_base:433
std::condition_variable::wait_for<…>(std::unique_lock<…> &, const std::chrono::duration<…> &, <lambda>) __mutex_base:477
gaia_spdlog::details::mpmc_blocking_queue::dequeue_for(gaia_spdlog::details::async_msg &, std::chrono::duration<…>) mpmc_blocking_q.h:58
gaia_spdlog::details::thread_pool::process_next_msg_() thread_pool-inl.h:99
gaia_spdlog::details::thread_pool::worker_loop_() thread_pool-inl.h:90
<lambda>::operator()() const thread_pool-inl.h:28
decltype(static_cast<gaia_spdlog::details::thread_pool::thread_pool(unsigned long, unsigned long, std::__1::function<void ()>)::'lambda'()>(fp)()) std::__1::__invoke<gaia_spdlog::details::thread_pool::thread_pool(unsigned long, unsigned long, std::__1::function<void ()>)::'lambda'()>(gaia_spdlog::details::thread_pool::thread_pool(unsigned long, unsigned long, std::__1::function<void ()>)::'lambda'()&&) type_traits:3918
std::__thread_execute<…>(std::tuple<…> &, std::__tuple_indices<…>) thread:280
std::__thread_proxy<…>(void *) thread:291
start_thread 0x00007f6ce4265609
__clone 0x00007f6ce4166293
```

If I move the `spdlog` initialization after my own signal handler the problem seems to disappear, though this is not really an option since I need logging earlier than that.

I wonder if this is something expected or it is a bug (maybe with my own software). 

I tried looking for signal handling calls in the spdlog but I didn't find anything. It seems there used to be something like that `installCrashHandlerOnce()` but it is not present in the version I'm currently using `1.8.5`.

**Comment by gabime** [comment]
> spdlog is great, thanks for making it available to all of us

Thanks   :)

Regarding signal handling, spdlog indeed dosn’t support it yet. see #1607 for a workarojnd.

**Comment by simone-gaia** [comment]
I will close the issue for now, and update it if I find something useful.

Thanks!
