### ISSUE TITLE
Random crash using async_create and single threaded sinks

### ISSUE THREAD

**Issue by gcerretani** [gabime/spdlog#2244]
I have this example code, compiled on VS2019, based on shared sinks generated with singletons and async loggers.

``` c++
#include <string>

#include <spdlog/spdlog.h>
#include <spdlog/cfg/env.h>
#include <spdlog/async.h>
#include <spdlog/sinks/dist_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/rotating_file_sink.h>

using namespace std::literals;

namespace logger {

namespace {

// sink singleton
template<typename T, typename... Args>
std::shared_ptr<spdlog::sinks::sink> sink(Args&& ...args) {
	static_assert(std::is_base_of_v<spdlog::sinks::sink, T>);
	static auto sink_instance = std::make_shared<T>(std::forward<Args>(args)...);
	return sink_instance;
}

std::shared_ptr<spdlog::sinks::sink> stdout_sink() {
	using sink_type = spdlog::sinks::stdout_color_sink_st;
	static constexpr spdlog::color_mode color_mode{ spdlog::color_mode::automatic };
	return sink<sink_type>(color_mode);
}

std::shared_ptr<spdlog::sinks::sink> rotating_file_sink() {
	using sink_type = spdlog::sinks::rotating_file_sink_st;
	const auto filename = SPDLOG_FILENAME_T("test.log");
	static constexpr std::size_t max_size{ 1 << 24 };
	static constexpr std::size_t max_files{ 4 };
	static constexpr bool rotate_on_open{ true };
	return sink<sink_type>(filename, max_size, max_files, rotate_on_open);
}

} // unnamed namespace

std::shared_ptr<spdlog::logger> create_logger(const std::string& name) {
	spdlog::sinks_init_list sink_list{
		rotating_file_sink(),
		stdout_sink(),
	};
	return spdlog::create_async<spdlog::sinks::dist_sink_st>(name, std::move(sink_list));
}

void init() {

	static constexpr std::size_t queue_size{ 8192 };
	static constexpr std::size_t thread_count{ 1 };
	spdlog::init_thread_pool(queue_size, thread_count);

	spdlog::set_automatic_registration(false);
	spdlog::set_level(static_cast<spdlog::level::level_enum>(SPDLOG_ACTIVE_LEVEL));

	spdlog::cfg::load_env_levels();

	spdlog::flush_on(spdlog::level::err);
	spdlog::set_default_logger(create_logger("default"s));

}

} // namespace logger

int main() {

	logger::init();

	auto l1 = logger::create_logger("test1"s);
	l1->info("test1 foo");

	auto l2 = logger::create_logger("test2"s);
	l2->info("test2 foo");

	spdlog::shutdown();

}
```

This almost always fails due to a failed assertions generated by a corrupted `pattern_formatter` object when invoking `pattern_formatter::format` on the logger thread. As far as I've read in the documentation and on some old issues, it should be safe to use `_st` sinks in this case even if I am sharing sinks between more loggers, because there is only a thread in my pool.

In [this thread](https://github.com/gabime/spdlog/discussions/1852) @gabime writes this about thread safety:

> Right. As long as all loggers with the shared sinks use async logging.

The code above works perfectly if i replace `_st` with `_mt`.

May you help me?

**Comment by gcerretani** [comment]
If i replace, on my code,

```c++
return spdlog::create_async<spdlog::sinks::dist_sink_st>(name, std::move(sink_list));
```
with

```c++
auto sink = std::make_shared<spdlog::sinks::dist_sink_st>(std::move(sink_list));
auto logger = std::make_shared<spdlog::async_logger>(name, std::move(sink), spdlog::thread_pool());
spdlog::initialize_logger(logger);
return logger;
```

I get the same error, as expeced because it is the same. But if I remove the call to `spdlog::initialize_logger` the problem seems to disappear. So, the problem arises with something that happens in that function. I guess it is related to the `set_formatter` call at https://github.com/gabime/spdlog/blob/4cfdc8c5c84f696774cb9acde2f95c9e87c11a5e/include/spdlog/details/registry-inl.h#L63

**Comment by gcerretani** [comment]
Ok, replacing `spdlog::initialize_logger(logger);` with

```c++
logger->set_formatter(std::make_unique<spdlog::pattern_formatter>()->clone());
```

produces the same effect: that assertion fails.

**Comment by gcerretani** [comment]
I've identified the problem, and it is not a bug but a common race condition.

1. I'm sharing not thread safe sinks betweek loggers
2. `spdlog::initialize_logger` invokes `set_formatter` to the sinks: when intializing a new logger, it changes the formatter also to the previously defined loggers
3. The problem happens while the thread pool is logging using the same formatter that is going to be replaced by another thread, if it is not protected by a mutex.

This is why I need multi thread is the right solution in this case: there is only a thread in the pool that invokes `spdlog::sinks::sink::log`, but sinks are being managed also by another thread that continues to create loggers and to modify the same sinks. Race conditions are inevitable.

**Comment by gabime** [comment]
Thanks for the analysis @gcerretani
