### ISSUE TITLE
Circular buffer in memory/file sink

### ISSUE THREAD

**Issue by Felicheat** [gabime/spdlog#2247]
Would it be possible to create a circular buffer sink (in memory or file) to replace the backtrace buffer? 

Our current implementation includes multiple loggers which all have enabled_backtrace. Issue is when an exception or error occurs, I iterate through all named loggers and dump their backtrace, causing an unorganized dump and many unnecessary Backtrace messages.

My current theorized solution is a rotating file that has 1 max_files and dumping the last n trace messages on our main log sink. I havent implemented this yet, but I would think this could work although it is not pretty or practical.

Thanks in advance.

**Comment by tt4g** [comment]
`spdlog::sinks::ringbuffer_sink` already exists.

**Comment by Felicheat** [comment]
> `spdlog::sinks::ringbuffer_sink` already exists (declared in `include/spdlog/sinks/ringbuffer_sink.h`).

Crazy how I missed that. Many thanks
