### ISSUE TITLE
flush policy is not working

### ISSUE THREAD

**Issue by gzliudan** [gabime/spdlog#225]
Hi:
    When I set flush police to flash every 1 second, if the log size is less than 4096, it is not write to disk file after many seconds, until I close my program. Below is my code:

    void CombinedLogger::Init(const std::string &app_name, const std::string &log_path) {
        const std::string pattern(GetPattern(app_name));

        m_std_err = spdlog::stderr_logger_mt("std_err");
        m_std_err->set_level(spdlog::level::warn);
        m_std_err->set_pattern(pattern);

        std::string logger_name("file_");
        uint file_no = m_file_no.fetch_add(1);
        logger_name += std::to_string(file_no);
        // std::cout << "logger name=" << logger_name << std::endl;

        std::string file_name(log_path);
        if (log_path.empty()) {
            file_name = "/var/log/cgcz/";
        } else {
            if (log_path[log_path.size() - 1] != '/') {
                file_name += '/';
            }
        }
        file_name += GetFileBaseName(app_name);

        spdlog::set_async_mode(1048576 * 4,
                               spdlog::async_overflow_policy::block_retry,
                               nullptr,
                               std::chrono::seconds(1));
        auto rotate_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(file_name,
                                                                                  "log",
                                                                                  m_max_file_size,
                                                                                  m_max_file_count,
                                                                                  false);
        m_file_logger = std::make_shared<spdlog::logger>(logger_name, rotate_sink);
        m_file_logger->set_level(m_log_level);
        m_file_logger->set_pattern(pattern);
    }

**Comment by gabime** [comment]
I think the problem is that the logger is created manually instead of using one of the spdlog:: factories. 
try to use ```auto m_file_logger=spdlog::rotating_sink(...)```

**Comment by gzliudan** [comment]
Thanks, now it works after change code as you said:
        spdlog::set_async_mode(1048576 * 4,
                               spdlog::async_overflow_policy::block_retry,
                               nullptr,
                               std::chrono::seconds(1));
        m_file_logger = spdlog::create<spdlog::sinks::rotating_file_sink_mt>(logger_name,
                                                                     file_name,
                                                                     SPDLOG_FILENAME_T("log"),
                                                                     m_max_file_size,
                                                                     m_max_file_count,
                                                                     false);

**Comment by rayrapetyan** [comment]
I have the same issue, but I can't use a factory methods as I need a single logger sharing multiple sinks. Is there a way to make async flush policy to work properly for a manually created sinks\loggers?

**Comment by gabime** [comment]
yes, just pass the timeout param to the constructor

**Comment by rayrapetyan** [comment]
Sorry, which constructor you mean? Here is my code:

``
try {
        spdlog::set_async_mode(65536, spdlog::async_overflow_policy::block_retry, nullptr, std::chrono::seconds(2));
        std::vector<spdlog::sink_ptr> sinks;

        sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_st>());

        auto sink_dbg = std::make_shared<spdlog::sinks::rotating_file_sink_st>(
                '/tmp/aaa',
                "log", conf.log.max_size, conf.log.count);
        sink_dbg->set_level(spdlog::level::debug);
        sinks.push_back(sink_dbg);

        auto sink_err = std::make_shared<spdlog::sinks::rotating_file_sink_st>(
                '/tmp/bbb',
                "log", conf.log.max_size, conf.log.count);
        sink_err->set_level(spdlog::level::err);
        sinks.push_back(sink_err);

        auto logger = std::make_shared<spdlog::logger>("root", sinks.begin(), sinks.end());
        spdlog::register_logger(logger);

        logger->set_level(spdlog::level::debug);
        logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%l] %v");
    } catch (const spdlog::spdlog_ex &ex) {
        std::cout << "Log init failed: " << ex.what() << std::endl;
        exit(1);
    }

It flushes only when queue is full and\or program exits...

**Comment by gabime** [comment]
you need to create async_logger instance, not the regular one (see https://github.com/gabime/spdlog/blob/master/include/spdlog/async_logger.h)

**Comment by rayrapetyan** [comment]
Yes it works this way, thanks! However, I think "registry", when used, should "pass-through" all options to the newly registered loggers.
