### ISSUE TITLE
SPDLOG_ACTIVE_LEVEL appears not to work

### ISSUE THREAD

**Issue by tenspd137** [gabime/spdlog#2252]
Hi - I am using v1.9.2 with external fmt lib.  It appears that SPDLOG_ACTIVE_LEVEL is not recognized:

```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG

#include <spdlog/spdlog.h>

int main()
{
    SPDLOG_DEBUG("Log level is at least debug");
    SPDLOG_TRACE("Log level is at least trace");
    SPDLOG_INFO("Log level is at least info");

    return 0;
}
```
```
└┌(%:~/projects/jrpg_ecs/apps)┌- g++ -std=c++17 test_app.cpp -o test -lfmt 
┌┌(dayd@dagon)┌(1261/pts/4)┌(09:33pm:01/20/22)┌-
└┌(%:~/projects/jrpg_ecs/apps)┌- ./test                                   
[2022-01-20 21:33:11.549] [info] [test_app.cpp:9] Log level is at least info
```
I would expect the debug message to be printed?  Am I missing something?  Thanks!

**Comment by tt4g** [comment]
The default logger log level is `info` (https://github.com/gabime/spdlog/blob/v1.9.2/include/spdlog/logger.h#L314). If you want all logs to be output, set the log level to `trace`.

```diff
 #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG

 #include <spdlog/spdlog.h>

 int main()
 {
+   spdlog::set_level(spdlog::level::trace);
     SPDLOG_DEBUG("Log level is at least debug");
     SPDLOG_TRACE("Log level is at least trace");
     SPDLOG_INFO("Log level is at least info");

     return 0;
 }
```

TIP: the default log level of sink is `trace` (https://github.com/gabime/spdlog/blob/v1.9.2/include/spdlog/sinks/sink.h#L27), so there is no need to change it.

**Comment by tenspd137** [comment]
Ohhh - user error - that is what I figured.  Thanks for the tip!
