### ISSUE TITLE
Custom Configuration - Filenames, Filesize Rotation, New File on Process Crash

### ISSUE THREAD

**Issue by twarg1** [gabime/spdlog#2254]
Hi Folks,

Any updates to the issues?:

1) allow file syncs to customize file names (e.g. add process name, add timestamp, etc.) - although it was stated that the daily file sink allows filename customization, I see no example of this?    Can this be done via config file (spdlog-setup). the daily file sink appends the year/month/day to the file name automatically ... it is not customizable from a config file from what we can tell?   ! what are we missing? how is this done through config file?
2) rotate file based on filesize - is this working?    If so, can this be done through config file?
3) create new log on process crash - is this a current capability?   if so, can this be done through config file?
Thanks!

**Comment by gabime** [comment]
> - although it was stated that the daily file sink allows filename customization, I see no example of this

1. Here is an example 

```c++
auto sink =  std::make_shared<spdlog::sinks::daily_file_format_sink_mt>("myapp-%Y-%m-%d:%H:%M:%S.log", hour, minute);"
auto logger = spdlog::daily_logger_format_mt("loggername, "myapp-%Y-%m-%d:%X.log", hour,  minute)"
```

2. Yes
3. No such feaure
