### ISSUE TITLE
Daily File level does not change setting env variable

### ISSUE THREAD

**Issue by massimiliano96** [gabime/spdlog#2257]
Hi,

I'm not able to change the log level into my daily log file, setting the env varible. My code is the following:

```
spdlog::cfg::load_env_levels();
boost::filesystem::path log_file_path("/var/log/test/");
if(!boost::filesystem::exists(log_file_path))
boost::filesystem::create_directory(log_file_path);
auto logger = spdlog::daily_logger_st("daily_logger", "/var/log/test/prova.txt", 23, 59);

for(unsigned i = 0; i<10; i++)
logger -> debug("i = {}", i);
```
Then I export the variables:
`export SPDLOG_LEVEL=debug, daily_logger=debug`

Finally I run the code, but nothing is written into the file. On the other hand if I try using **info** level everything works. Which is my fault?

**Comment by tt4g** [comment]
Doesn't it work if environment variables are quoted?

`export SPDLOG_LEVEL="debug, daily_logger=debug"`

**Comment by massimiliano96** [comment]
Solved. It was my fault, in order to write in /var/log/ I was running my code in this way: `sudo ./Test` 
but the environment variable were exported from my user and not from root.
