### ISSUE TITLE
Change Runtime Log level using macros

### ISSUE THREAD

**Issue by massimiliano96** [gabime/spdlog#2259]
I'm trying to use macros since I want to print the file path in my log, however now exporting environmental variables I'm not able to change the log level at runtime. Here's my code:
```
spdlog::cfg::load_env_levels();
boost::filesystem::path log_file_path("/var/log/test/");
if(!boost::filesystem::exists(log_file_path))
	boost::filesystem::create_directory(log_file_path);
auto logger = spdlog::daily_logger_st("daily_logger", "/var/log/test/prova.txt", 23, 59);
spdlog::set_default_logger(logger);

std::string id = this -> instanceUuid;
logger -> set_pattern("[%@] [%!] [%c] [%l] ["+id+"] : %v");

SPDLOG_INFO("Test INFO level");
SPDLOG_DEBUG("Test DEBUG level");
```

Then I export the variables: `export SPDLOG_LEVEL=debug, daily_logger=debug`
Finally I run the code `./Test`

The Debug message is never printed on my daily file. How can I fix?

**Comment by tt4g** [comment]
Logging macros lower than the level specified by the ` SPDLOG_ACTIVE_LEVEL` macro (by default `SPDLOG_LEVEL_INFO`) will be removed.

Wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

If you don't want to remove the logging macro, set `SPDLOG_ACTIVE_LEVEL` macro to `SPDLOG_LEVEL_TRACE`.

**Comment by massimiliano96** [comment]
Solved. Thanks a lot!
