### ISSUE TITLE
File name bug

### ISSUE THREAD

**Issue by LukeMauldin** [gabime/spdlog#226]
When using Visual Studio 2015 with Clang C2 May compiler toolset, the code to calculate the file name does not work correctly. For example, using Visual Studio 2015 with the default VS140 toolset, this code works:
```
std::vector<spdlog::sink_ptr> sinks;
	sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_st>());
	sinks.push_back(std::make_shared<spdlog::sinks::daily_file_sink_st>(logFilePath, "txt", 23, 59));
	defaultLogger = std::make_shared<spdlog::logger>(processName, begin(sinks), end(sinks));
```
A file is created with the name: appname.exe_3936_2016-06-14_09-30.txt 
However, when I use the Clang C2 toolset, the file name is truncated like: appname.exe_17888_

I have debugged through the code to file_sinks.h default_daily_file_name_calculator::calc_filename  I have verified that the tm variable is correct but the result of the w.write(...) call is what does not perform as expected.

I have updated to the latest version of spdlog and fmtlib.

**Comment by gabime** [comment]
thanks for the detailed report. 

which write call in the source is the suspect? which line # ?

**Comment by LukeMauldin** [comment]
```
struct default_daily_file_name_calculator
{
    //Create filename for the form basename.YYYY-MM-DD_hh-mm.extension
    static filename_t calc_filename(const filename_t& basename, const filename_t& extension)
    {
        std::tm tm = spdlog::details::os::localtime();
        std::conditional<std::is_same<filename_t::value_type, char>::value, fmt::MemoryWriter, fmt::WMemoryWriter>::type w;
        w.write(SPDLOG_FILENAME_T("{}_{:04d}-{:02d}-{:02d}_{:02d}-{:02d}.{}"), basename, tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, extension);
        return w.str();
    }
}
```
The w.write line

**Comment by gabime** [comment]
do you use wchar filenames?

**Comment by LukeMauldin** [comment]
No

**Comment by gabime** [comment]
clang on VisualStudio  is not supporetd
