### ISSUE TITLE
"invalid numeric argument" when building on Windows 10

### ISSUE THREAD

**Issue by benpm** [gabime/spdlog#2260]
Because of [this](https://github.com/gabime/spdlog/blob/8fb112158a64afe1bd58c82c06bf6a142c9b3823/CMakeLists.txt#L155) line in CMakeLists.txt, building on Windows causes the following error:
```
cl : command line error D8021: invalid numeric argument '/wd4275>'
```

This is fixed by placing /w4275 outside of the generator expression, and placing it all on one line:
```CMake
    if(MSVC)
        target_compile_options(spdlog PUBLIC $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<NOT:$<COMPILE_LANGUAGE:CUDA>>>:/wd4251> /wd4275)
    endif()
```

**Comment by gabime** [comment]
It does compile on windows. How to reproduce?
