### ISSUE TITLE
When disk is full log rotation resulted zero size log files.

### ISSUE THREAD

**Issue by kishorekrd** [gabime/spdlog#2261]
I set log rotation configuration with file size as 10Mb and up to 10 files. But when the disk is full, I ended up having 10 files all with zero size. How can I avoid this situation? I am expecting that when the write fails because of disk full situation, spdlog should not overwrite the old log files and should exit gracefully.

**Comment by gabime** [comment]
Thanks for reporting. Which platform are you using?

**Comment by kishorekrd** [comment]
ubuntu 18.04

**Comment by kishorekrd** [comment]
Hi @gabime , Any fix or workaround for this issue?

**Comment by gabime** [comment]
Not sure. I need to find time to check this out.  PRs are welcome.

**Comment by gabime** [comment]
@kishorekrd I can't reproduce
I filled the disk and the logger behaved as expected.

```c++

#include "spdlog/spdlog.h"
#include "spdlog/sinks/rotating_file_sink.h"

int main(int, char *[]) {

    // Create a file rotating logger with 5mb size max and 4 rotated files.
    auto rotating_logger = spdlog::rotating_logger_mt("some_logger_name", "/mnt/loopfs/rotating.txt", 1048576 * 5, 3);
    for(int long i = 0; i < 10000000; i++)
        rotating_logger->info("HELLO              {}",i);
}
```


[*** LOG ERROR #0001 ***] [2022-02-04 13:19:19] [some_logger_name] {Failed writing to file /mnt/loopfs/rotating.txt: No space left on device}
[*** LOG ERROR #7175 ***] [2022-02-04 13:19:20] [some_logger_name] {Failed writing to file /mnt/loopfs/rotating.txt: No space left on device}
[*** LOG ERROR #9579 ***] [2022-02-04 13:19:21] [some_logger_name] {Failed writing to file /mnt/loopfs/rotating.txt: No space left on device}
[*** LOG ERROR #15589 ***] [2022-02-04 13:19:22] [some_logger_name] {Failed writing to file /mnt/loopfs/rotating.txt: No space left on device}
[*** LOG ERROR #21599 ***] [2022-02-04 13:19:24] [some_logger_name] {Failed writing to file /mnt/loopfs/rotating.txt: No space left on device}
[*** LOG ERROR #27609 ***] [2022-02-04 13:19:25] [some_logger_name] {Failed writing to file /mnt/loopfs/rotating.txt: No space left on device}

```console
ls /mnt/loopfs/ -l
total 12256
drwx------ 2 root root   16384 Feb  4 13:10 lost+found
-rw-r--r-- 1 root root 5242835 Feb  4 13:19 rotating.1.txt
-rw-r--r-- 1 root root  303104 Feb  4 13:19 rotating.2.txt
-rw-r--r-- 1 root root 5242835 Feb  4 13:19 rotating.3.txt
-rw-r--r-- 1 root root 1709718 Feb  4 13:19 rotating.txt

**Comment by kishorekrd** [comment]
@gabime , Thanks for trying. I see that file writing failed when disk is full. 
When rotation happens, it has to rename all the existing log files and create new log file. But if disk becomes full in this situation, it is failing and making all the log files with zero size. I think rotation should pause if the disk is full.

**Comment by gabime** [comment]
I couldn't reproduce. See the output of ls command above. The files are not empty. Maybe provide a code to reproduce?

**Comment by gabime** [comment]
@kishorekrd I fixed it by checking that  the file is not empty before rotating (seems to be the case when the disk is full)

Could you please verify it solves your problem?

**Comment by kishorekrd** [comment]
Thanks for the fix. it looks good.
