### ISSUE TITLE
spdlog/fmt/fmt.h triggers assert in libfmt

### ISSUE THREAD

**Issue by yurivict** [gabime/spdlog#2264]
After either spdlog or libfmt update the OpenRoad FreeBSD port now fails to build:
```
In file included from /wrkdirs/usr/ports/cad/openroad/work/OpenROAD-2.0/src/TritonRoute/src/gr/FlexGRCMap.cpp:29:
In file included from /wrkdirs/usr/ports/cad/openroad/work/OpenROAD-2.0/src/TritonRoute/src/gr/FlexGRCMap.h:37:
In file included from /wrkdirs/usr/ports/cad/openroad/work/OpenROAD-2.0/src/TritonRoute/src/frBaseTypes.h:41:
In file included from /wrkdirs/usr/ports/cad/openroad/work/OpenROAD-2.0/src/utl/include/utl/Logger.h:46:
In file included from /usr/local/include/spdlog/spdlog.h:12:
In file included from /usr/local/include/spdlog/common.h:36:
In file included from /usr/local/include/spdlog/fmt/fmt.h:25:
/usr/local/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/local/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::v8::detail::make_arg<true, fmt::v8::basic_format_context<fmt::v8::appender, char>, fmt::v8::detail::type::custom_type, const fr::frMinstepTypeEnum &, 0>' requested here
        data_{detail::make_arg<
                      ^
```

Full [log](http://beefy16.nyi.freebsd.org/data/130amd64-default/d79790970038/logs/openroad-2.0,1.log) (IPv6 URL).

It appears that the cause is a version of libfmt bundled with spdlog.

Such bundling can not work, please remove it.

Please advise how to fix the port.

FreeBSD 13

Thanks.

**Comment by gabime** [comment]
Maybe try to upgrade to latest version of fmt

**Comment by yurivict** [comment]
The latest ```libfmt-8.1.1``` is already used.

**Comment by gabime** [comment]
SoI suggest open an issue in the fmt repo

**Comment by yurivict** [comment]
I've already been there. There was a similar issue 1-2 years ago due to bundling.
Mixing ```/usr/local/include/spdlog/fmt/fmt.h``` and ```/usr/local/include/fmt/core.h``` can't work.

You should rename the bundled fmt into some other name so that there'd be no such conflicts.

The commit "devel/libfmt: Update to 8.1.1" on Jan 28th, 2022 caused the problem.

**Comment by gabime** [comment]
> You should rename the bundled fmt into some other name so that there'd be no such conflicts.

Cant do that without breaking all the that depend on those filenames. How come this not a problem in other systems? Seems to me the compiler include path is wrong. Note that spdlog supports external fmt  using SPDLOG _FMT_EXTERNAL define.

**Comment by yurivict** [comment]
Neither a cmake variable ```SPDLOG_FMT_EXTERNAL``` nor a C++ define ```SPDLOG_FMT_EXTERNAL``` helps.

**Comment by yurivict** [comment]
> How come this not a problem in other systems?

This is potentially a problem on all systems.

**Comment by tt4g** [comment]
(I haven't been able to check the logs, because I don't have access to IPv6 domain `beefy16.nyi.freebsd.org`)

I have worked on projects that use external fmt and have never encountered such a problem.

Can you provide a list of include paths?
If you are using the gcc compiler, just add the `-v` option and the list will be displayed.

**Comment by yurivict** [comment]
Here's the command line:
```
[  1% 19/771] /usr/bin/c++  -I/disk-samsung/freebsd-ports/cad/openroad/work/OpenROAD-2.0/src/OpenDB/src/lef/lef -I/disk-samsung/freebsd-ports/cad/openroad/work/.build/src/OpenDB/src/lef -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include/eigen3 -DSPDLOG_FMT_EXTERNAL -isystem /usr/local/include -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include/eigen3 -DSPDLOG_FMT_EXTERNAL -isystem /usr/local/include -fPIC -std=c++17 -MD -MT src/OpenDB/src/lef/CMakeFiles/lef.dir/lef/lefiCrossTalk.cpp.o -MF src/OpenDB/src/lef/CMakeFiles/lef.dir/lef/lefiCrossTalk.cpp.o.d -o src/OpenDB/src/lef/CMakeFiles/lef.dir/lef/lefiCrossTalk.cpp.o -c /disk-samsung/freebsd-ports/cad/openroad/work/OpenROAD-2.0/src/OpenDB/src/lef/lef/lefiCrossTalk.cpp
```

----------------------------------

> I have worked on projects that use external fmt and have never encountered such a problem.

Could you please point out what guarantees include path order, or how is it guaranteed?

**Comment by tt4g** [comment]
From the command line provided, It doesn't look like `/usr/local/include/spdlog/fmt/bundled` is added to include path.
I don't think your project is using the fmt that spdlog bundled.

I also checked the error messages in the issue comments, and here `static_assert` in line 1727 of `/usr/local/include/fmt/core.h` is failing.
However, the version of fmt bundled with the latest (v1.9.2) spdlog is v8.0.1, and its `static_assert` is at line 1567.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/fmt/bundled/core.h#L1567-L1570

Looking at fmt v8.0.1, that `static_assert` is indeed at line 1727: https://github.com/fmtlib/fmt/blob/8.1.1/include/fmt/core.h#L1727

> It appears that the cause is a version of libfmt bundled with spdlog.
>
> Such bundling can not work, please remove it.

Why do you think so?
From the information you provided, I can only assume that spdlog is using an external fmt.

**Comment by yurivict** [comment]
> Why do you think so?
> From the information you provided, I can only assume that spdlog is using an external fmt.

The original error message fails in the package-installed fmt, but it is called through the bundled fmt's header.

So the cause is mixing fmt versions.

**Comment by tt4g** [comment]
> The original error message fails in the package-installed fmt, but it is called through the bundled fmt's header.

Do you mean `In file included from /usr/local/include/spdlog/fmt/fmt.h:25:`? If so, then this file is not a bundled fmt.
This file is used to change the fmt used by spdlog to either external or bundle.

https://github.com/gabime/spdlog/blob/v1.9.2/include/spdlog/fmt/fmt.h#L13-L27

**Comment by yurivict** [comment]
```
In file included from /usr/local/include/spdlog/fmt/fmt.h:25:
/usr/local/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
```

Both versions are included in the same module.

**Comment by tt4g** [comment]
The same error was reproduced in Compiler Explorer (with fmt v7.1.2): https://godbolt.org/z/MYne43YMc

<details>
<summary>reproduce code</summary>

```cpp
#include <fmt/core.h>

namespace fr
{

class frMinstepTypeEnum {
    
};

}

int main() {
  fmt::print("The answer is {}.", fr::frMinstepTypeEnum());
}
```

</details>

> In file included from /wrkdirs/usr/ports/cad/openroad/work/OpenROAD-2.0/src/TritonRoute/src/gr/FlexGRCMap.cpp:29:

This line causes `static_assert` to fail because it formats a class that does not implement the fmt formatting method.

> /usr/local/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::v8::detail::make_arg<true, fmt::v8::basic_format_context<fmt::v8::appender, char>, fmt::v8::detail::type::custom_type, const fr::frMinstepTypeEnum &, 0>' requested here

The message is broken and not clear, but it looks like `fr::frMinstepTypeEnum` is the cause.

**Comment by tt4g** [comment]
I found the OpenLoad repository, where spdlog v1.8.1 is installed as a dependency.

https://github.com/The-OpenROAD-Project/OpenROAD/blob/v2.0/etc/DependencyInstaller.sh#L14

fmt v8.x support has been added for spdlog version v1.9.0 and above.

**Comment by yurivict** [comment]
The FreeBSD port devel/spdlog is built with -DSPDLOG_FMT_EXTERNAL=OFF but ```include/spdlog/fmt``` is still installed. This looks like a bug.

**Comment by yurivict** [comment]
Also: Is there an explanation why ```spdlib``` needs to install ```include/spdlog/fmt``` ?

**Comment by yurivict** [comment]
This problem exists from at least 2019: [FreeBSD port bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240148)

And you just have never fixed it.

**Comment by tt4g** [comment]
> The FreeBSD port devel/spdlog is built with -DSPDLOG_FMT_EXTERNAL=ON but include/spdlog/fmt is still installed. This looks like a bug.

Bundled fmt will not be installed as long as the CMake variables `SPDLOG_FMT_EXTERNAL` and `SPDLOG_FMT_EXTERNAL_HO` are defined.
Moreover, the installation path of bundled fmt is `spdlog/fmt/bundled`.

`include/spdlog/fmt` can only be considered as an exteranl fmt installed with dependencies.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/CMakeLists.txt#L282

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/CMakeLists.txt#L290-L293

**Comment by yurivict** [comment]
> Bundled fmt will not be installed as long as the CMake variables SPDLOG_FMT_EXTERNAL and SPDLOG_FMT_EXTERNAL_HO are defined.

Nope:
```
CMake Error at CMakeLists.txt:95 (message):
  SPDLOG_FMT_EXTERNAL and SPDLOG_FMT_EXTERNAL_HO are mutually exclusive
```

**Comment by yurivict** [comment]
It still installs bundled fmt with -DSPDLOG_FMT_EXTERNAL=ON.

Version 1.9.2

**Comment by yurivict** [comment]
> /usr/local/include/fmt has nothing to do with bundled fmt.

Except it conflicts with it.

**Comment by tt4g** [comment]
> Nope:

Sorry. I'm not a native speaker, so there was a mistake in the English wording.
Edited my comment.

**Comment by tt4g** [comment]
> Except that it conflicts with it.

I don't think it's a conflict.
As I mentioned in https://github.com/gabime/spdlog/issues/2264#issuecomment-1030558881, the reason for the assertion failure was that the fmt library was passed a type for which no formatting method was provided.

And OpenROAD version 2.0 depends on spdlog v1.8.1, and this version does not support fmt v8.x.

**Comment by tt4g** [comment]
> It still installs bundled fmt with -DSPDLOG_FMT_EXTERNAL=ON.

Can you provide the `install_manifest.txt` generated by CMake?

**Comment by tt4g** [comment]
> Also: Is there an explanation why spdlib needs to install include/spdlog/fmt ?

Wrappers for bundle fmt and external fmt, as per the comments: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240148#c1

> FMT_HEADER_ONLY fix is suboptimal. <spdlog/fmt/fmt.h> and <spdlog/fmt/ostr.h> appear to be wrappers to cheat on libfmt dependency.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/fmt/fmt.h#L13-L27

**Comment by gabime** [comment]
@yurivict What's the status of this issue ?

**Comment by stineje** [comment]
Fixed this error by installing a new version of spdlog from source - fyi.
