### ISSUE TITLE
Support for providing dynamic values to formatter arguments

### ISSUE THREAD

**Issue by radumotrescu** [gabime/spdlog#2270]
So, we have this need to do logging in the format of:
```%i %Y-%m-%d %v```
Where ```%i``` represents an IP address that is determined at log time, it is specified dynamically at each call. At the same time, there is the ```%v``` argument that would need to stay the same as the current spdlog implementation.

Is there such feature implemented? I could not find any reference to something like this.

**Comment by gabime** [comment]
No, there is no such feature.
