### ISSUE TITLE
Async vs Non-Async

### ISSUE THREAD

**Issue by Thomspoon** [gabime/spdlog#2282]
What is the use-case for Async logging, and should we prefer using non-async logging if looking for performance?

EDIT: This is in reference of the benchmarks section in the main README, if I was reading it correctly, it seems to suggest that synchronous logging is faster, which was unexpected.

**Comment by Thomspoon** [comment]
Thank you, Gabime, this was helpful!

**Comment by yalov** [comment]
What kind of delay should the caller expect during an "occasional flush to disk"?

Are we talking about microseconds, or could it sometimes be milliseconds?

Let's say I have 10 threads, no more than 25 messages/s on a logger/thread, a message is no more than 150 characters.

**Comment by zaphodikus** [comment]
> What kind of delay should the caller expect during an "occasional flush to disk"?
> 
> Are we talking about microseconds, or could it sometimes be milliseconds?
> 
> Let's say I have 10 threads, no more than 25 messages/s on a logger/thread, a message is no more than 150 characters.

It's impossible to say how long, basically if you are asking, then the delay is going to be too long for you is the correct answer to give someone who asks. The delay has other effects, so even if it's less than a millisecond, which is a damn long time, then it still impacts other threads and mutexes and creates synchronisation side effects. Like yourself, I'm learning how to deal with flushing, disabling it for now.
