### ISSUE TITLE
[*** LOG ERROR #0001 ***] [2022-02-20 14:40:13] [] {std::bad_alloc} in simple program

### ISSUE THREAD

**Issue by WilliamBehrens** [gabime/spdlog#2286]
code:
```c++
#include "spdlog/spdlog.h"

int main() {
    spdlog::set_level(spdlog::level::debug);
    spdlog::info("Starting RCBot");
}
```

I'm using spdlog 1.9.2 from conan center and anytime I so much as call spdlog::info(""); I get `[*** LOG ERROR #0001 ***] [2022-02-20 14:40:13] [] {std::bad_alloc}`

**Comment by tt4g** [comment]
Probably a conan problem.
Does the same problem occur if I use spdlog without conan?

**Comment by WilliamBehrens** [comment]
No, so something is wrong with how the [conan recipe](https://github.com/conan-io/conan-center-index/tree/master/recipes/spdlog) is handled. I submitted an error report there [conan-center-index #9446](https://github.com/conan-io/conan-center-index/issues/9446)
