### ISSUE TITLE
How to output all dumptrace information in async logging to an error-level sink?

### ISSUE THREAD

**Issue by YunchengLiu** [gabime/spdlog#2287]
I am new to spdlog and I have learned a lot by using this library.

I saw the [issues](https://github.com/gabime/spdlog/issues/1579) discussed in the issue and wanted to implement the same backtrace function according to this.

I also set an error sink. Generally, the filter level is warn, but when the backtrace starts, set the filter level to **trace** to record the backtrace information, and reset the **warn** level after the backtrace is over.

This works fine when logging synchronously.

but when in async logging mode, when i call below.
```
error_sink_->set_level(spdlog::level::trace); // ①
logger_->dump_backtrace(); // ②
error_sink_->set_level(spdlog::level::warn); // ③
```

Since only the log request is submitted to the queue at this time, the above method will return quickly, then ③ will make many logs ignored due to the sinking filter level when the backtrace information is actually output.

I can wait for a while and then restore the sinking filter level.
```
using namespace std::chrono_literals;
error_sink_->set_level(spdlog::level::trace);
logger_->dump_backtrace();
std::this_thread::sleep_for(1s); // just for example
error_sink_->set_level(spdlog::level::warn);
```
This does not feel like a more appropriate method.

Is there a suitable way to know the update status of the message? Or other flags that could work?

So I would like to ask how to handle this situation when logging asynchronously? Or is there any other better practice?

Thank you everyone.

**Comment by tt4g** [comment]
There is no way provided for an asynchronous logger to know that a particular log message has arrived at sink.

But you can create custom sink with `spdlog::sinks::ringbuffer_sink` instead of `dump_backtrace()` API (see #1866).

**Comment by YunchengLiu** [comment]
Thanks，i will try it.
