### ISSUE TITLE
How can I Set/Change the log rotation size and count at runtime?

### ISSUE THREAD

**Issue by talk2sohail** [gabime/spdlog#2288]
Is there any way to change the default log rotation size of an existing logger object?
I want to change the already set the log size(also rotation count) during the runtime just as we can change the log levels.
I cannot find any API for the above operation in the source code. Please point me to the code, if any or suggest some idea 
to accomplish the above idea.

**Comment by tt4g** [comment]
It is not supported. and #2281 (add `set_max_size` API) was closed.

**Comment by talk2sohail** [comment]
Thanks for mention. But I wonder why this is not supported as good argument was presented in #2281.
Is there any chance that it can be supported now?

**Comment by tt4g** [comment]
As per https://github.com/gabime/spdlog/pull/2281#issuecomment-1042548157 by the main maintainer, the feature may be added if it is discussed.

**Comment by talk2sohail** [comment]
Hi @gabime. 
You have already pointed out the reason then to not support this #2281. I request you to please consider adding support for log size change. 

I also feel it is not very common use case and but still I also believe this could help increase developer experience and also we can skip not so useful workaround of creating new sink. Please let me know if you feel if it's the correct time to add this support.

CC: @tt4g I would also like to hear your opinion on this.

**Comment by tt4g** [comment]
IMO.

In many cases, immutable variables can simplify a program.
Making a previously immutable variable mutable can have unexpected side effects and be difficult to maintain.
I respect the idea of making many variables immutable in order to make the program easier to maintain.

On the other hand, I understand the opinion that the rotation size has to be changed when the server dynamically changes the log level and so on.
The more log messages that are output, the faster the rotation cycle becomes, and you may lose logs that are necessary for system operation.

The solution I came up with is to create a custom sink that wraps the `spdlog::sinks::rotating_file_sink` (like `spdlog::sinks::dist_sink`).
I think your goal can be achieved with the following custom sink (NOTE the code has not been tested to work.)

<details>
<summary>mutable_rotating_file_sink</summary>

```cpp
// Your namespace

template<typename Mutex, typename RotatingFileSink = spdlog::sinks::rotating_file_sink<Mutex>>
class mutable_rotating_file_sink : public spdlog::sinks::base_sink<Mutex>
{
public:

    explicit mutable_rotating_file_sink (
        spdlog::level::level_enum log_level,
        // spdlog::sinks::rotating_file_sink() arguments.
        spdlog::filename_t base_filename,
        std::size_t max_size,
        std::size_t max_files,
        bool rotate_on_open = false,
        const spdlog::file_event_handlers &event_handlers = {})
        : base_filename_(std::move(base_filename)),
          rotate_on_open_(rotate_on_open),
          event_handlers_(event_handlers),
          rotating_file_sink_(std::make_unique<RotatingFileSink>(base_filename_, max_size, max_files, rotate_on_open_, event_handlers_))
    {
        rotating_file_sink_->set_level(log_level);
    }

    mutable_rotating_file_sink(const mutable_rotating_file_sink&) = delete;
    mutable_rotating_file_sink&operator=(const mutable_rotating_file_sink&) = delete;

    void update_rotating_file_sink(spdlog::level::level_enum log_level, std::size_t max_size, std::size_t max_files)
    {
        std::lock_guard<Mutex> lock(spdlog::sinks::base_sink<Mutex>::mutex_);
        // Destruct old rotating_file_sink (to close internal file descriptor).
        rotating_file_sink_ = nullptr;

        rotating_file_sink_ = std::make_unique<RotatingFileSink>(base_filename_, max_size, max_files, rotate_on_open_, event_handlers_);
        rotating_file_sink_->set_level(log_level);
    }

protected:
    void sink_it_(const spdlog::details::log_msg &msg) override
    {
        if (rotating_file_sink_->should_log(msg.level)) {
            rotating_file_sink_->log(msg);
        }
    }

    void flush_() override
    {
        rotating_file_sink_->flush();
    }

    void set_pattern_(const std::string &pattern) override
    {
        set_formatter_(std::make_unique<spdlog::pattern_formatter>(pattern));
    }

    void set_formatter_(std::unique_ptr<spdlog::formatter> sink_formatter) override
    {
        rotating_file_sink_->set_formatter(std::move(sink_formatter));
    }

    spdlog::filename_t base_filename_;
    bool rotate_on_open_:
    spdlog::file_event_handlers event_handlers_;
    std::unique_ptr<RotatingFileSink > rotating_file_sink_;
};

using mutable_rotating_file_sink_mt = mutable_rotating_file_sink<std::mutex>;
using mutable_rotating_file_sink_st = mutable_rotating_file_sink<spdlog::details::null_mutex>;

// Your namespace
```
</details>

**Comment by gabime** [comment]
As @tt4g said, Immutability is the main reason for not adding support for this.

However since there are are multiple requests for this so I will reconsider.

**Comment by talk2sohail** [comment]
Thanks @gabime for reconsidering it.
@tt4g : would you like to send the PR ? As I am still new to the codebase and picking up bits and pieces, It will take a little time to come with the changes. Please let me know If you are interested else I am happy to send the PR to **support for changing the log size dynamically**.

**Comment by tt4g** [comment]
I haven't used C++ much for a while now, and my development environment is not sufficient.
If you need this feature quickly, I recommend that you send a PR.

**Comment by talk2sohail** [comment]
@tt4g : Okay I will send the PR. Thanks.
