### ISSUE TITLE
How can I get SPDLOG_LOGGER_INFO to log more than one argument

### ISSUE THREAD

**Issue by husseinsafa98** [gabime/spdlog#2289]
auto logger = spdlog::basic_logger_mt("testFile", "logs/basic-log.txt");

logger->set_pattern("[source %s] [function %!] [line %#] %v ");

SPDLOG_LOGGER_INFO(logger , "Program Name is: %s" , argv[0])

 argv[0] is holding the name of the program i was wondering how can i display it when sending it into the file i get

[source test.cpp] [function main] [line 67] Program Name is: %s 

its not displaying the other argument where it holds the programs name, if anyone can help id appreciate it

**Comment by tt4g** [comment]
Use fmt placeholder `{}`.
See: https://fmt.dev/latest/index.html

```diff
-SPDLOG_LOGGER_INFO(logger , "Program Name is: %s" , argv[0])
+SPDLOG_LOGGER_INFO(logger , "Program Name is: {}" , argv[0])
```

**Comment by husseinsafa98** [comment]
Thank you! how about for something with a for loop

for (counter = 0; counter < argc; counter++)
			printf("argv[%d]: %s\n", counter, argv[counter])

**Comment by tt4g** [comment]
Placeholder `{}` can be used for almost any type of mold.

```cpp
for (counter = 0; counter < argc; counter++)
    SPDLOG_LOGGER_INFO("argv[{}]: {}", counter, argv[counter])
```

Use syntax like `{02:d}` only when you want to specify the number of digits.
https://fmt.dev/latest/syntax.html
