### ISSUE TITLE
"Access violation writing location 0x0000000000000050" exception whenever I initialize

### ISSUE THREAD

**Issue by ItsNovaAndCrap** [gabime/spdlog#2291]
Whenever I initialize spdlog with this function:
```cpp
std::shared_ptr<spdlog::logger> Log::s_CoreLogger;
std::shared_ptr<spdlog::logger> Log::s_ClientLogger;

void Log::Init()
{
	spdlog::set_pattern("%^[%T] %n: %v%$");
	s_CoreLogger = spdlog::stdout_color_mt("MOLAR");
	s_CoreLogger->set_level(spdlog::level::trace);

	s_CoreLogger = spdlog::stdout_color_mt("APP");
	s_ClientLogger->set_level(spdlog::level::trace);
}
```

It returns an exception:
`Exception thrown at 0x00007FFAD6CF8B67 (Molar.dll) in Sandbox.exe: 0xC0000005: Access violation writing location 0x0000000000000050.`

**Comment by ItsNovaAndCrap** [comment]
Note: The exception seems to be coming from the "atomic" header file at line 887.

**Comment by gabime** [comment]
shouldnt it be 

s_ClientLogger = spdlog::stdout_color_mt("APP") ?

**Comment by ItsNovaAndCrap** [comment]
huh, i didn't notice that. I thought I fixed that problem way before I received that exception... ty!

**Comment by ItsNovaAndCrap** [comment]
now when I print something with one of these macros:
```cpp
// Core log macros
#define ML_CORE_TRACE(...)		::Molar::Log::GetCoreLogger()->trace(__VA_ARGS__)
#define ML_CORE_INFO(...)		::Molar::Log::GetCoreLogger()->info(__VA_ARGS__)
#define ML_CORE_WARN(...)		::Molar::Log::GetCoreLogger()->warn(__VA_ARGS__)
#define ML_CORE_ERROR(...)		::Molar::Log::GetCoreLogger()->error(__VA_ARGS__)
#define ML_CORE_FATAL(...)		::Molar::Log::GetCoreLogger()->critical(__VA_ARGS__)

// Client log macros
#define ML_TRACE(...)			::Molar::Log::GetClientLogger()->trace(__VA_ARGS__)
#define ML_INFO(...)			::Molar::Log::GetClientLogger()->info(__VA_ARGS__)
#define ML_WARN(...)			::Molar::Log::GetClientLogger()->warn(__VA_ARGS__)
#define ML_ERROR(...)			::Molar::Log::GetClientLogger()->error(__VA_ARGS__)
#define ML_FATAL(...)			::Molar::Log::GetClientLogger()->critical(__VA_ARGS__)
```
I get the same exception except from the main function!
EntryPoint.h:
```cpp
#pragma once

#ifdef ML_PLATFORM_WINDOWS

extern Molar::Application* Molar::CreateApplication();

int main(int argc, char** argv)
{
	Molar::Log::Init();
	ML_CORE_WARN("Initialized Log!");
	int a = 5;
	ML_TRACE("Hello! Var={0}", a);

	auto app = Molar::CreateApplication();
	app->Run();
	delete app;
}

#endif
```

**Comment by tt4g** [comment]
I think there is a problem with the declaration of variables `Log::s_CoreLogger` and `Log::s_ClientLogger`.
Maybe reloated #1505

**Comment by ItsNovaAndCrap** [comment]
I don't see the problem with those variables, neither do I see a solution in that issue.

**Comment by tt4g** [comment]
I know from the error trace that you are using spdlog in your DLL.
Do you understand what the following link is about?

* https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs
* #1562
* #1530
* #2267

There are so many people who encounter access violation errors when they do not understand how to initialize `extern` and `static` declared variables in DLLs, and I believe this problem is caused by the same thing.
