### ISSUE TITLE
When using the supervisord  startup program，pdlog will not write logs to files

### ISSUE THREAD

**Issue by ioir123ju** [gabime/spdlog#2293]
Probability trigger, trigger conditions are unknown

**Comment by tt4g** [comment]
What is supervisord? I don't know what it is.

And, are you able to write logs without using supervisord?
If so, is it not a problem with supervisord?

**Comment by ioir123ju** [comment]
> 

supervisord is a process management tool and a watchdog program.
Without it, logs can be saved.

**Comment by tt4g** [comment]
> Without it, logs can be saved.

It is recommended to reopen issue supervisord community.

**Comment by tt4g** [comment]
Related ochinchina/supervisord#312
