### ISSUE TITLE
spdlog fails to build under gcc 11

### ISSUE THREAD

**Issue by boxerab** [gabime/spdlog#2295]
branch `v1.x`

Error:

`undefined references to `std::__throw_bad_array_new_length()'`

**Comment by tt4g** [comment]
That's sounds like gcc compatibilty problem between 10 and 11.
See: https://gcc.gnu.org/pipermail/gcc-help/2021-June/140487.html

**Comment by tt4g** [comment]
Similar issue: stan-dev/pystan#294

**Comment by boxerab** [comment]
@tt4g thanks! It turns out this is only a problem if I build my library (linked to spdlog) as a static lib. So, there is an issue with static libstdc++ versioning. Closing.
