### ISSUE TITLE
Set custom deleter for `std::shared_ptr<logger>`

### ISSUE THREAD

**Issue by davids91** [gabime/spdlog#2299]
Is it possible to set a custom deleter through the factory methods? 
The way I see [the code](https://github.com/gabime/spdlog/blob/ad08f13aacc92b5e38c4a77f9cabd24d54fd53b1/include/spdlog/details/synchronous_factory.h) it's not yet available. Despite the fact that `std::weak_ptr` can be used as a workaround,  I think it would be a great feature to add to the library.

**Comment by tt4g** [comment]
`Factory` template parameter can be specified for the sink factory function, providing an alternative implementation to `spdlog::synchronous_factory`.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/sinks/null_sink.h#L28-L42

**Comment by davids91** [comment]
I tried to implement it by extending the factory: 
```diff
diff --git a/include/spdlog/details/synchronous_factory.h b/include/spdlog/details/synchronous_factory.h
index 1f729ab9..890f6842 100644
--- a/include/spdlog/details/synchronous_factory.h
+++ b/include/spdlog/details/synchronous_factory.h
@@ -12,11 +12,11 @@ class logger;
 
 struct synchronous_factory
 {
-    template<typename Sink, typename... SinkArgs>
-    static std::shared_ptr<spdlog::logger> create(std::string logger_name, SinkArgs &&... args)
+    template<typename Sink, typename... SinkArgs, class LoggerDeleter = std::default_delete<spdlog::logger>>
+    static std::shared_ptr<spdlog::logger> create(std::string logger_name, SinkArgs &&... args, LoggerDeleter&& deleter = LoggerDeleter())
     {
         auto sink = std::make_shared<Sink>(std::forward<SinkArgs>(args)...);
-        auto new_logger = std::make_shared<spdlog::logger>(std::move(logger_name), std::move(sink));
+        auto new_logger = std::shared_ptr<spdlog::logger>(new spdlog::logger(std::move(logger_name), std::move(sink)), std::move(deleter));
         details::registry::instance().initialize_logger(new_logger);
         return new_logger;
     }

```

But unfortunately it fails, I presume because `spdlog::logger` is an abstract class, so `std::default_delete<spdlog::logger>` is not well formed; so I believe a custom class based on `spdlog::synchronous_factory` is the way too. 

Thanks!
