### ISSUE TITLE
Custom Flag Formatting using Runtime data

### ISSUE THREAD

**Issue by massimiliano96** [gabime/spdlog#2303]
Hi Guys,

I'm implementing a daily-file logger for which I would like to implement a custom flag that represents the sessionID of the process. This is the Wiki guide on custom formatting :

`
```
#include "spdlog/pattern_formatter.h"
class my_formatter_flag : public spdlog::custom_flag_formatter
{
public:
    void format(const spdlog::details::log_msg &, const std::tm &, spdlog::memory_buf_t &dest) override
    {
        std::string some_txt = "custom-flag";
        dest.append(some_txt.data(), some_txt.data() + some_txt.size());
    }

    std::unique_ptr<custom_flag_formatter> clone() const override
    {
        return spdlog::details::make_unique<my_formatter_flag>();
    }
};

void custom_flags_example()
{    
    auto formatter = std::make_unique<spdlog::pattern_formatter>();
    formatter->add_flag<my_formatter_flag>('*').set_pattern("[%n] [%*] [%^%l%$] %v");
    spdlog::set_formatter(std::move(formatter));
}
```
`
I would like to change the "custom-flag" at runtime passing to the function the string representing my sessionID. Is there any wait of implementing such king of custom flag?

**Comment by tt4g** [comment]
> I would like to change the "custom-flag" at runtime passing to the function the string representing my sessionID. Is there any wait of implementing such king of custom flag?

What is a function? Is it a logging function like `spdlog::info`?
If so, just pass it as a logging argument.

```cpp
spdlog::info("sessionID: {}", sessionID);
```

No custom formatter is needed.

**Comment by tt4g** [comment]
Perhaps what you need is a feature like logging context?
Unfortunately, that feature is not supported (#353, #532).

**Comment by maordadush** [comment]
@gabime @tt4g Do you intend to support the logging context feature?

**Comment by tt4g** [comment]
I have no such plans.
