### ISSUE TITLE
async_logger in DLL on windows is not working properly

### ISSUE THREAD

**Issue by grapehunter** [gabime/spdlog#2304]
I have read [How to use spdlog in DLLs](https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs) and [Asynchronous logging hangs under Windows dll](https://github.com/gabime/spdlog/wiki/0.-FAQ#asynchronous-logging-hangs-under-windows-dll)
And I've looked up all related contents in Issue, but I can't solve the problem.

### Here is very simple sample:

- In dynamic library(DLL):

header (framework.h):
```cpp
#include <windows.h>
#include <spdlog/spdlog.h>
#include <spdlog/async_logger.h>
#include <spdlog/async.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#ifdef DLLLOG_EXPORTS
#define DLLLOG_EXPORT __declspec(dllexport)
#else
#define DLLLOG_EXPORT __declspec(dllimport)
#endif
namespace dlllog {
	class DLLLOG_EXPORT Dlllog
	{
	public:
		static std::shared_ptr<spdlog::async_logger> SetupLogger();
		static void Log(std::string msg);
	};
}
```
cpp (dllmain.cpp):
```cpp
#include "framework.h"

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        spdlog::shutdown();
        break;
    }
    return TRUE;
}
namespace dlllog {
    std::shared_ptr<spdlog::async_logger> _logger;
    std::shared_ptr<spdlog::async_logger> Dlllog::SetupLogger() {
        auto consoleSink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        std::vector<spdlog::sink_ptr> sinks = { consoleSink };
        spdlog::init_thread_pool(8192, 1);
        _logger = std::make_shared<spdlog::async_logger>("DLLLOG", sinks.begin(), sinks.end(), spdlog::thread_pool());
        spdlog::set_default_logger(_logger);
        return _logger;
    }

     void Dlllog::Log(std::string msg) {
         SPDLOG_INFO(msg);
    }
}
```

- In executable project(exe):
```cpp
#include "framework.h"
using namespace dlllog;
int main()
{
    auto logger = Dlllog::SetupLogger();
    Dlllog::Log("Helloworld 1");
    Dlllog::Log("Helloworld 2");
    Dlllog::Log("Helloworld 3");
    Dlllog::Log("Helloworld 4");
    Dlllog::Log("Helloworld 5");
    spdlog::set_default_logger(logger->clone("main"));
    SPDLOG_INFO("Helloworld 1");
    SPDLOG_INFO("Helloworld 2");
    SPDLOG_INFO("Helloworld 3");
    SPDLOG_INFO("Helloworld 4");
    SPDLOG_INFO("Helloworld 5");
    //spdlog::shutdown();
}
```

And I created a repo using visual studio 2022 and the code is as above https://github.com/grapehunter/SpdlogWhiteboard
(If needed, I can create a cmake project)

### Problem Description

1. If I place code `spdlog::shutdown();` in DllMain of DLL (as code above), The program will crash due to memory failure.
![image](https://user-images.githubusercontent.com/3354458/157855676-5fecec73-126a-4833-9986-7b8fd9940b5b.png)

2. If I place code `spdlog::shutdown();` at the end of the main function (Instead of in DLLMain), I will encounter the `mutex destroyed while busy` Error.
![image](https://user-images.githubusercontent.com/3354458/157856120-190c7c77-1acc-42f8-9a32-f3d2ab5cb317.png)

### Other
VS2022 17.1.0
spdlog 1.9.2

**Comment by tt4g** [comment]
Don't call spdlog API in `DllMain`.
Between the calls to `DllMain` and `main`, resources used by the process are initialized and destroyed.
When `spdlog::shutdown()` is called in `DllMain`, the system resources used by `std::mutex` and `std::thread` are dangling pointers.

* https://github.com/gabime/spdlog/issues/1530#issuecomment-618949363
* https://github.com/gabime/spdlog/wiki/0.-FAQ#asynchronous-logging-hangs-under-windows-dll

**Comment by grapehunter** [comment]
> Don't call spdlog API in `DllMain`. Between the calls to `DllMain` and `main`, resources used by the process are initialized and destroyed. When `spdlog::shutdown()` is called in `DllMain`, the system resources used by `std::mutex` and `std::thread` are dangling pointers.
> 
> * [Initialising spdlog inside DLL rather than main function #1530 (comment)](https://github.com/gabime/spdlog/issues/1530#issuecomment-618949363)
> * https://github.com/gabime/spdlog/wiki/0.-FAQ#asynchronous-logging-hangs-under-windows-dll

Thank you for your reply.

I have made other attempts, like I said in the second case, instead of calling in dllmain, I put the code `spdlog::shutdown()` at the end of the main function and got an error `mutex destroyed while busy`

```cpp
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```

```cpp
int main()
{
    ...
    ...
    spdlog::shutdown();
}
```

**Comment by tt4g** [comment]
I didn't notice the `spdlog::*` API call in the `main` function.
I think the cause is that you are calling `spdlog::shutdown()` after passing the DLL created logger to `spdlog::set_default_logger()`.

```cpp
int main()
{
    ...
    spdlog::set_default_logger(logger->clone("main"));
    ...
    spdlog::shutdown();
}
```

This is because `spdlog::shutdown()` calls `drop_all()` to destroy the default logger.

https://github.com/gabime/spdlog/blob/v1.9.2/include/spdlog/details/registry-inl.h#L240

When deleting the default logger, the member variable `std::mutex` of sink is also deleted. However, since this `std::mutex` is created by the DLL, it may not be deleted successfully from the application.

Do not use `set_default_logger()` in your application to register DLL created loggers.
And add a function in the DLL that calls `spdlog::shutdown()` to delete loggers in the DLL's memory space, and the application should call that function.

**Comment by tt4g** [comment]
> Do not use `set_default_logger()` in your application to register DLL created loggers.
> And add a function in the DLL that calls `spdlog::shutdown()` to delete loggers in the DLL's memory space, and the application should call that function.

Perhaps the error is not caused by sink's `std::mutex` (my mistake).
I guess it is `std::mutex` of thread pool used by `spdlog::async_logger`.

**Comment by grapehunter** [comment]
> I didn't notice the `spdlog::*` API call in the `main` function. I think the cause is that you are calling `spdlog::shutdown()` after passing the DLL created logger to `spdlog::set_default_logger()`.
> 

Thank you very much.
> And add a function in the DLL that calls spdlog::shutdown() to delete loggers in the DLL's memory space, and the application should call that function.

**This line is the solution.**
Library header
```diff patch
	class DLLLOG_EXPORT Dlllog
	{
	public:
		static std::shared_ptr<spdlog::async_logger> SetupLogger();
		static void Log(std::string msg);
+              static void Log(std::string msg);
	};
```
Library cpp
```diff patch
+	void Dlllog::DestoryLogger() {
+		spdlog::shutdown();
+	}
```

main.cpp
```diff patch
-    spdlog::shutdown();
+    Dlllog::DestoryLogger();
}
```
> Do not use set_default_logger() in your application to register DLL created loggers.

Because I need to display the **file name** and **the line number** (pattern: `[%Y-%m-%d %H:%M:%S.%e] [%P] [%t] [%n] [%^%l%$] [%s(%#)] %v`)
As I understand it, the only way to achieve this is through the macro SPDLOG_* (like SPDLOG_INFO). And using this macro requires to `set_default_logger()`
Do I understand correctly? Is there a way to display line numbers just by calling `spdlog::register_logger`?

**Comment by tt4g** [comment]
> I understand it, the only way to achieve this is through the macro SPDLOG_* (like SPDLOG_INFO). And using this macro requires to set_default_logger()

`SPDLOG_LOGGER_<LEVEL>` macro is provided that passes logger as its first argument.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/spdlog.h#L291-L299

Therefore, `spdlog::set_default_logger()`  and the `SPDLOG_<LEVEL>` macro are options.

Example:

```cpp
int main()
{
    auto logger = Dlllog::SetupLogger();
    Dlllog::Log("Helloworld 1");
    Dlllog::Log("Helloworld 2");
    Dlllog::Log("Helloworld 3");
    Dlllog::Log("Helloworld 4");
    Dlllog::Log("Helloworld 5");

    SPDLOG_LOGGER_INFO(logger, "Helloworld 1");
    SPDLOG_LOGGER_INFO(logger, "Helloworld 2");
    SPDLOG_LOGGER_INFO(logger, "Helloworld 3");
    SPDLOG_LOGGER_INFO(logger, "Helloworld 4");
    SPDLOG_LOGGER_INFO(logger, "Helloworld 5");
}
```

> And I found that based on the above code, the program works fine even if I call set_default_logger()

Yes, it was probably the `std::mutex` in the thread pool that was causing the error as per my last comment.

**Comment by grapehunter** [comment]
@tt4g 
Got it, thanks for the help. I'll close this issue.
Thank you very much.
Have I nice day.
