### ISSUE TITLE
stdout_color_sink_mt cannot print colorful text in docker.

### ISSUE THREAD

**Issue by WorstCodeWay** [gabime/spdlog#2311]
My docker is arm64-v8 build from [l4t-base:r32.6.1](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-base/tags).

Besides, I have read #2177 by @rfmineguy, my result of environment variable `TERM` is **xterm**, so function `is_color_terminal` return true.

What am I missed?

**Comment by tt4g** [comment]
Probably related https://stackoverflow.com/a/33499558
