### ISSUE TITLE
Can't get multi sink logger working as per example

### ISSUE THREAD

**Issue by TheFern2** [gabime/spdlog#2316]
Not entirely sure what is going on, I setup a multi sink as per the example on the readme, but using a rotating file sink. Only the console sink works. The log file is created but nothing is outputted to it. Any ideas what I am doing wrong?

```cpp
// Multiple sinks
auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("./logs/log.txt", 1024 * 1024 * 5, 3); // 3 rotating logs of 5MB
spdlog::logger logger("multi_sink", {console_sink, file_sink});

// Set logging configuration
spdlog::flush_every(std::chrono::seconds(5));
if (config::logging_debug)
{
    spdlog::set_level(spdlog::level::debug);
}
else
{
    spdlog::set_level(spdlog::level::info);
}

spdlog::set_pattern("[%D %H:%M:%S.%e] [%^%l%$] %v");
```

**Comment by tt4g** [comment]
> is there a way to set default logger with multiple sinks?

Call `spdlog::set_default_logger()`.
And you must call `spdlog::register_logger()` (or `spdlog::initialize_logger()`) to register it in the global registry to be affected by the API in the `spdlog::*` namespace.

```diff
 // Multiple sinks
 auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
 auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("./logs/log.txt", 1024 * 1024 * 5, 3); // 3 rotating logs of 5MB
-spdlog::logger logger("multi_sink", {console_sink, file_sink});
+auto logger = std::make_shared<spdlog::logger>("multi_sink", {console_sink, file_sink});

+spdlog::register_logger(logger);
+spdlog::set_default_logger(logger);

 // Set logging configuration
 spdlog::flush_every(std::chrono::seconds(5));
 if (config::logging_debug)
 {
     spdlog::set_level(spdlog::level::debug);
 }
 else
 {
     spdlog::set_level(spdlog::level::info);
 }

 spdlog::set_pattern("[%D %H:%M:%S.%e] [%^%l%$] %v");
```

**Comment by TheFern2** [comment]
> > is there a way to set default logger with multiple sinks?
> 
> Call `spdlog::set_default_logger()`. And you must call `spdlog::register_logger()` (or `spdlog::initialize_logger()`) to register it in the global registry to be affected by the API in the `spdlog::*` namespace.
> 
> ```diff
>  // Multiple sinks
>  auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
>  auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("./logs/log.txt", 1024 * 1024 * 5, 3); // 3 rotating logs of 5MB
> -spdlog::logger logger("multi_sink", {console_sink, file_sink});
> +auto logger = std::make_shared<spdlog::logger>("multi_sink", {console_sink, file_sink});
> 
> +spdlog::register_logger(logger);
> +spdlog::set_default_logger(logger);
> 
>  // Set logging configuration
>  spdlog::flush_every(std::chrono::seconds(5));
>  if (config::logging_debug)
>  {
>      spdlog::set_level(spdlog::level::debug);
>  }
>  else
>  {
>      spdlog::set_level(spdlog::level::info);
>  }
> 
>  spdlog::set_pattern("[%D %H:%M:%S.%e] [%^%l%$] %v");
> ```

Thanks! is that meant for certain version, I am on 1.5.0. I get a no matching function when I tried to make the logger with make_shared. I'll try making this multiple sink a Log class instead and see if it works, although that means I'll need to replace all my spdlog::* calls, but is not a huge application yet.

**Comment by tt4g** [comment]
Oh, my example code is wrong (missing `std::initializer_list<spdlog::sink_ptr>`).

```diff
-auto logger = std::make_shared<spdlog::logger>("multi_sink", {console_sink, file_sink});
+auto logger = std::make_shared<spdlog::logger>("multi_sink", std::initializer_list<spdlog::sinks_ptr>{console_sink, file_sink});

**Comment by TheFern2** [comment]
@tt4g I appreciate it, that did the trick!
