### ISSUE TITLE
make _log_if_enabled public?

### ISSUE THREAD

**Issue by petke** [gabime/spdlog#232]
Hi.

There are many different logging functions trace(), info(), error(), etc. There is a common protected function interface called _log_if_enabled(level::level_enum lvl). I'd like to use that from user code, but cant as this function interface is not public. Could you make the interface public? (Maybe also give it a more user friendly name like: "details::line_logger log(level::level_enum lvl);"

More details:

The reason i need this is that my code base is tied to this syntax: 

    LOG(ERROR_LVL) << "whatever";
    LOG(INFO_LVL) << "whatever"; 
    //etc. 

With a bit of MACRO help I can get it all to work

    enum my_log_lvl //values corresponds to spdlog::level::level_enum
    {
	TRACE_LVL = 0,
	DEBUG_LVL = 1,
	INFO_LVL = 2,
	NOTICE_LVL = 3,
	WARNING_LVL = 4,
	ERROR_LVL = 5,
	FATAL_LVL = 6
    };

    #define LOG(my_lvl_)\
	get_my_log_inst()->_log_if_enabled(static_cast <spdlog::level::level_enum> (my_lvl_)) <<  "["     << __FUNC__ << ":" << __LINE__ <<"] "

**Comment by gabime** [comment]
Agreed, a pull request would be appriciated. 
I think it would be better  to add a new public function called ```log(spdlog::level::level_enum) ``` which wraps the ```_log_if_enabled(..)``` function instead of renaming & making it public ( it is already used in many places in the code)

**Comment by gabime** [comment]
latest version provides a log() function
