### ISSUE TITLE
stderr_logger_st flushes too much

### ISSUE THREAD

**Issue by realtime-neil** [gabime/spdlog#2321]
The `spdlog::stderr_logger_st` and the `spdlog::basic_logger_st` seem to differ in how they obey flush semantics. The basic logger seems to correctly delay flushing, but the stderr logger flushes immediately.

I have attached a reproducer in the form of a small C++ mainprog that demonstrates the difference in behavior. It calls `spdlog::flush_on(spdlog::level::err)` before emitting the same logs to each backend. This is what it prints:

```
$ ./early-flush
early-flush.basic.log:
[2022-03-25 16:10:57.699] [basic] [error] fee

early-flush.stderr.log:
[2022-03-25 16:10:57.699] [stderr] [error] fee
[2022-03-25 16:10:57.699] [stderr] [warning] fie
[2022-03-25 16:10:57.699] [stderr] [info] foe
```

Note that the basic logger correctly flushes only on `spdlog::level::err`, while the stderr logger incorrectly flushes on every level.

[early-flush.cc.txt](https://github.com/gabime/spdlog/files/8352333/early-flush.cc.txt)

**Comment by tt4g** [comment]
NOTE I/O flash operations are performed automatically by OS.
Data written to file, STDOUT, and STDERR is buffered in memory, but the buffer size is limited and OS will flush the buffer if data exceeding the buffer size is written.

The buffer size of STDOUT and STDERR will sometimes be smaller than the buffer size of the file.
See http://www.pixelbeat.org/programming/stdio_buffering/

**Comment by realtime-neil** [comment]
@tt4g okay, understood. I didn't know if the spdlog ostream sinks were buffering between the caller and the OS-managed file descriptors, but I guess they're not.

Should the documentation be changed to mention this?

Should the implementation be changed to throw an error if the caller attempts to set a flush policy on an ostream sink?

Should the implementation be changed to buffer caller writes before flushing them to `stdout` and/or `stderr`?

Should I just close this ticket as "working as intended"? :smile:

**Comment by tt4g** [comment]
> Should the documentation be changed to mention this?

It is a C/C++ language specification, not spdlog.
You can find a detailed explanation on StackOverflow: https://stackoverflow.com/a/10904459

The standard specification defines buffering as implementation-defined, and you can (maybe) change buffer size with `setbuf` or `setvbuf`.

Note that `STDERR` does not seem to be buffered on Linux (to display error messages quickly).

> Should the implementation be changed to throw an error if the caller attempts to set a flush policy on an ostream sink?

No.

> Should the implementation be changed to buffer caller writes before flushing them to stdout and/or stderr?

If buffering is needed, change the buffer size with `setvbuf`.

> Should I just close this ticket as "working as intended"? 

I think it should be closed.

**Comment by gabime** [comment]
The stdout/stderr sinks flush on each log regardless of the flush level(https://github.com/gabime/spdlog/blob/a49456f7f21fb802c1000fd79ef05911aa2101b7/include/spdlog/sinks/stdout_sinks-inl.h#L76). This is by design since normally users expect to see the screen output immediately, and also due to the fact that under windows the ```WriteConsoleA()``` flush directly to the console anyway.
