### ISSUE TITLE
Can spdlog redirect  the stdout to file which config by file sink 

### ISSUE THREAD

**Issue by Nevercomes** [gabime/spdlog#2322]
Just like the std::cout and  printf used by some third_partys in my apps,  can I redirect them like '>' symbol?

**Comment by tt4g** [comment]
There is no support.

**Comment by yalov** [comment]
@gabime Hello,

Is the feature not planned?

What would you recommend to achieve the same behavior?

I have my "main log" set up as dup_filter_sink, which sinks to stdout_color_sink and a custom file_size_time_sink. 
However, when some third-party libraries output their error messages to the console using cout, cerr, printf, etc, the messages are shown in the terminal, **but are not written to the text file by file_size_time_sink**.
