### ISSUE TITLE
fmt build fail

### ISSUE THREAD

**Issue by alicera** [gabime/spdlog#2325]
I already build fmt and its structure is
```
fmt
├── release
 │     ├── include
 │     └── lib
                 ├── fmt.lib
                 ├── cmake/fmt
                             ├── fmt-config.cmake
```
command
```
cmake -G "Visual Studio 16 2019" ^
		-DCMAKE_BUILD_TYPE=Release ^
		-DSPDLOG_FMT_EXTERNAL=True ^
		-Dfmt_DIR=..\fmt\release\
```
error
```
CMake Error at CMakeLists.txt:193 (find_package):
  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

But change Dfmt_DIR, it will success.
```
cmake -G "Visual Studio 16 2019" ^
		-DCMAKE_BUILD_TYPE=Release ^
		-DSPDLOG_FMT_EXTERNAL=True ^
		-Dfmt_DIR=..\fmt\release\lib\cmake\fmt
```

**Comment by tt4g** [comment]
This is the behavior as described in the `find_package()` documentation.

https://cmake.org/cmake/help/v3.23/command/find_package.html

> If `<PackageName>_DIR` has been set to a directory not containing a configuration file CMake will ignore it and search from scratch.

**Comment by alicera** [comment]
1.In fact, I don't use find_package() on camkelist.txt setting.
I use command cmake to set Dfmt_DIR parameter.
Do you mean find_package can be used by cmake command ? How to do that?

2.
you say 
```
If <PackageName>_DIR has been set to a directory not containing a configuration file CMake will ignore it and search from scratch
```
You mean the directory containing a configuration file.
like this
put  fmt-config.cmake, ...*.cmake to top level folder
```
fmt
├── fmt-config.cmake
├── release
 │     ├── include
 │     └── lib
                 ├── fmt.lib
                 ├── cmake/fmt
                             
```

But you also say  search from scratch.
why it dosent find the fmt\release\lib\cmake\fmt\*.cmake?

**Comment by tt4g** [comment]
> In fact, I don't use find_package() on camkelist.txt setting.

`find_package(fmt)` exists in `CMakeLists.txt` in the spdlog repository.
Look at the error message "CMake Error at CMakeLists.txt:193 (find_package)".

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/CMakeLists.txt#L191-L194


> why it dosent find the fmt\release\lib\cmake\fmt*.cmake?

This is a CMake specification. Please read the CMake documentation carefully.

https://cmake.org/cmake/help/v3.23/command/find_package.html#search-procedure

**Comment by alicera** [comment]
Thanks a lot.

But the structure is generate with the commnad.
How can I do to effectively use search-procedure
```
cd fmt
cmake -G "Visual Studio 16 2019" ^
		-S .\ ^
		-B .\build-release ^
		-DCMAKE_BUILD_TYPE=Release ^
cmake --build build-release --config Release
cmake --install build-release --config Release --prefix ..\release
```

```
fmt
├── fmt (project)
├── release
 │     ├── include
 │     └── lib
                 ├── fmt.lib
                 ├── cmake/fmt
                             ├── fmt-config.cmake
├── debug
 │     ├── include
 │     └── lib
                 ├── fmt.lib
                 ├── cmake/fmt
                             ├── fmt-config.cmake
```

**Comment by tt4g** [comment]
CMake does not know that fmt binaries are multiple. If you want to switch binaries, change `fmt_DIR` and build.
