### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by qalastar** [gabime/spdlog#233]
Hi,

I discover today your library and I try to use it but I have some trouble. 

My version of Gcc is 4.8.4 and I use ubuntu 14.04.3

When I compile my project with your files includes, I have some errors : 

17:46:13 **** Incremental Build of configuration Debug for project manage_raid ****
make all 
Building file: ../src/main.cpp
Invoking: GCC C++ Compiler
g++ -I"/home/sharebox/git/manage_raid" -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"src/main.d" -MT"src/main.o" -o "src/main.o" "../src/main.cpp"
Finished building: ../src/main.cpp
 
Building file: ../spdlog/details/format.cc
Invoking: GCC C++ Compiler
g++ -I"/home/sharebox/git/manage_raid" -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"spdlog/details/format.d" -MT"spdlog/details/format.o" -o "spdlog/details/format.o" "../spdlog/details/format.cc"
../spdlog/details/format.cc: In function ‘fmt::internal::Null<> strerror_r(int, char*, ...)’:
../spdlog/details/format.cc:80:37: error: redefinition of ‘fmt::internal::Null<> strerror_r(int, char*, ...)’
 static inline fmt::internal::Null<> strerror_r(int, char *, ...)
                                     ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:80:37: error: ‘fmt::internal::Null<> strerror_r(int, char*, ...)’ previously defined here
 static inline fmt::internal::Null<> strerror_r(int, char *, ...)
                                     ^
../spdlog/details/format.cc: In function ‘fmt::internal::Null<> strerror_s(char*, std::size_t, ...)’:
../spdlog/details/format.cc:84:37: error: redefinition of ‘fmt::internal::Null<> strerror_s(char*, std::size_t, ...)’
 static inline fmt::internal::Null<> strerror_s(char *, std::size_t, ...)
                                     ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:84:37: error: ‘fmt::internal::Null<> strerror_s(char*, std::size_t, ...)’ previously defined here
 static inline fmt::internal::Null<> strerror_s(char *, std::size_t, ...)
                                     ^
../spdlog/details/format.cc: At global scope:
../spdlog/details/format.cc:115:10: error: redefinition of ‘struct fmt::{anonymous}::IntChecker<IsSigned>’
   struct IntChecker
          ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:115:10: error: previous definition of ‘struct fmt::{anonymous}::IntChecker<IsSigned>’
   struct IntChecker
          ^
../spdlog/details/format.cc:130:10: error: redefinition of ‘struct fmt::{anonymous}::IntChecker<true>’
   struct IntChecker<true>
          ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:130:10: error: previous definition of ‘struct fmt::{anonymous}::IntChecker<true>’
   struct IntChecker<true>
          ^
../spdlog/details/format.cc:143:26: error: redefinition of ‘const char fmt::{anonymous}::RESET_COLOR []’
   const char RESET_COLOR[] = "\x1b[0m";
                          ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:143:14: error: ‘const char fmt::{anonymous}::RESET_COLOR [5]’ previously defined here
   const char RESET_COLOR[] = "\x1b[0m";
              ^
../spdlog/details/format.cc: In function ‘int fmt::{anonymous}::safe_strerror(int, char*&, std::size_t)’:
../spdlog/details/format.cc:156:7: error: redefinition of ‘int fmt::{anonymous}::safe_strerror(int, char*&, std::size_t)’
   int safe_strerror(
       ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:156:7: error: ‘int fmt::{anonymous}::safe_strerror(int, char*&, std::size_t)’ previously defined here
   int safe_strerror(
       ^
../spdlog/details/format.cc: In function ‘void fmt::{anonymous}::format_error_code(fmt::Writer&, int, fmt::StringRef)’:
../spdlog/details/format.cc:225:8: error: redefinition of ‘void fmt::{anonymous}::format_error_code(fmt::Writer&, int, fmt::StringRef)’
   void format_error_code(fmt::Writer &out, int error_code,
        ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:225:8: error: ‘void fmt::{anonymous}::format_error_code(fmt::Writer&, int, fmt::StringRef)’ previously defined here
   void format_error_code(fmt::Writer &out, int error_code,
        ^
../spdlog/details/format.cc: In function ‘void fmt::{anonymous}::report_error(fmt::{anonymous}::FormatFunc, int, fmt::StringRef)’:
../spdlog/details/format.cc:249:8: error: redefinition of ‘void fmt::{anonymous}::report_error(fmt::{anonymous}::FormatFunc, int, fmt::StringRef)’
   void report_error(FormatFunc func,
        ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:249:8: error: ‘void fmt::{anonymous}::report_error(fmt::{anonymous}::FormatFunc, int, fmt::StringRef)’ previously defined here
   void report_error(FormatFunc func,
        ^
../spdlog/details/format.cc: At global scope:
../spdlog/details/format.cc:261:9: error: redefinition of ‘class fmt::{anonymous}::IsZeroInt’
   class IsZeroInt: public fmt::internal::ArgVisitor<IsZeroInt, bool>
         ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:261:9: error: previous definition of ‘class fmt::{anonymous}::IsZeroInt’
   class IsZeroInt: public fmt::internal::ArgVisitor<IsZeroInt, bool>
         ^
../spdlog/details/format.cc:273:9: error: redefinition of ‘class fmt::{anonymous}::WidthHandler’
   class WidthHandler: public fmt::internal::ArgVisitor<WidthHandler, unsigned>
         ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:273:9: error: previous definition of ‘class fmt::{anonymous}::WidthHandler’
   class WidthHandler: public fmt::internal::ArgVisitor<WidthHandler, unsigned>
         ^
../spdlog/details/format.cc:304:9: error: redefinition of ‘class fmt::{anonymous}::PrecisionHandler’
   class PrecisionHandler:
         ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:304:9: error: previous definition of ‘class fmt::{anonymous}::PrecisionHandler’
   class PrecisionHandler:
         ^
../spdlog/details/format.cc:323:10: error: redefinition of ‘struct fmt::{anonymous}::is_same<T, U>’
   struct is_same
          ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:323:10: error: previous definition of ‘struct fmt::{anonymous}::is_same<T, U>’
   struct is_same
          ^
../spdlog/details/format.cc:332:10: error: redefinition of ‘struct fmt::{anonymous}::is_same<T, T>’
   struct is_same<T, T>
          ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:332:10: error: previous definition of ‘struct fmt::{anonymous}::is_same<T, T>’
   struct is_same<T, T>
          ^
../spdlog/details/format.cc:345:9: error: redefinition of default argument for ‘class T’
   class ArgConverter: public fmt::internal::ArgVisitor<ArgConverter<T>, void>
         ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:344:13: note: original definition appeared here
   template <typename T = void>
             ^
../spdlog/details/format.cc:401:9: error: redefinition of ‘class fmt::{anonymous}::CharConverter’
   class CharConverter: public fmt::internal::ArgVisitor<CharConverter, void>
         ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:401:9: error: previous definition of ‘class fmt::{anonymous}::CharConverter’
   class CharConverter: public fmt::internal::ArgVisitor<CharConverter, void>
         ^
../spdlog/details/format.cc: In function ‘void fmt::{anonymous}::write(std::ostream&, fmt::Writer&)’:
../spdlog/details/format.cc:421:8: error: redefinition of ‘void fmt::{anonymous}::write(std::ostream&, fmt::Writer&)’
   void write(std::ostream &os, fmt::Writer &w)
        ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:421:8: error: ‘void fmt::{anonymous}::write(std::ostream&, fmt::Writer&)’ previously defined here
   void write(std::ostream &os, fmt::Writer &w)
        ^
../spdlog/details/format.cc: At global scope:
../spdlog/details/format.cc:440:9: error: redefinition of ‘class fmt::internal::PrintfArgFormatter<Char>’
   class PrintfArgFormatter:
         ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:440:9: error: previous definition of ‘class fmt::internal::PrintfArgFormatter<Char>’
   class PrintfArgFormatter:
         ^
../spdlog/details/format.cc:520:15: error: redefinition of ‘void fmt::SystemError::init(int, fmt::CStringRef, fmt::ArgList)’
 FMT_FUNC void fmt::SystemError::init(
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:520:15: error: ‘void fmt::SystemError::init(int, fmt::CStringRef, fmt::ArgList)’ previously defined here
 FMT_FUNC void fmt::SystemError::init(
               ^
../spdlog/details/format.cc:531:5: error: redefinition of ‘static int fmt::internal::CharTraits<char>::format_float(char*, std::size_t, const char*, unsigned int, int, T)’
 int fmt::internal::CharTraits<char>::format_float(
     ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:531:5: error: ‘static int fmt::internal::CharTraits<char>::format_float(char*, std::size_t, const char*, unsigned int, int, T)’ previously declared here
 int fmt::internal::CharTraits<char>::format_float(
     ^
../spdlog/details/format.cc:546:5: error: redefinition of ‘static int fmt::internal::CharTraits<wchar_t>::format_float(wchar_t*, std::size_t, const wchar_t*, unsigned int, int, T)’
 int fmt::internal::CharTraits<wchar_t>::format_float(
     ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:546:5: error: ‘static int fmt::internal::CharTraits<wchar_t>::format_float(wchar_t*, std::size_t, const wchar_t*, unsigned int, int, T)’ previously declared here
 int fmt::internal::CharTraits<wchar_t>::format_float(
     ^
../spdlog/details/format.cc:561:48: error: redefinition of ‘const char fmt::internal::BasicData<T>::DIGITS []’
 const char fmt::internal::BasicData<T>::DIGITS[] =
                                                ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:561:12: error: ‘const char fmt::internal::BasicData<T>::DIGITS [201]’ previously declared here
 const char fmt::internal::BasicData<T>::DIGITS[] =
            ^
../spdlog/details/format.cc:580:61: error: redefinition of ‘const uint32_t fmt::internal::BasicData<T>::POWERS_OF_10_32 []’
 const uint32_t fmt::internal::BasicData<T>::POWERS_OF_10_32[] = {
                                                             ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:580:16: error: ‘const uint32_t fmt::internal::BasicData<T>::POWERS_OF_10_32 [10]’ previously declared here
 const uint32_t fmt::internal::BasicData<T>::POWERS_OF_10_32[] = {
                ^
../spdlog/details/format.cc:585:61: error: redefinition of ‘const uint64_t fmt::internal::BasicData<T>::POWERS_OF_10_64 []’
 const uint64_t fmt::internal::BasicData<T>::POWERS_OF_10_64[] = {
                                                             ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:585:16: error: ‘const uint64_t fmt::internal::BasicData<T>::POWERS_OF_10_64 [20]’ previously declared here
 const uint64_t fmt::internal::BasicData<T>::POWERS_OF_10_64[] = {
                ^
../spdlog/details/format.cc: In function ‘void fmt::internal::report_unknown_type(char, const char*)’:
../spdlog/details/format.cc:594:15: error: redefinition of ‘void fmt::internal::report_unknown_type(char, const char*)’
 FMT_FUNC void fmt::internal::report_unknown_type(char code, const char *type)
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:594:15: error: ‘void fmt::internal::report_unknown_type(char, const char*)’ previously defined here
 FMT_FUNC void fmt::internal::report_unknown_type(char code, const char *type)
               ^
../spdlog/details/format.cc: In function ‘void fmt::internal::format_system_error(fmt::Writer&, int, fmt::StringRef)’:
../spdlog/details/format.cc:692:15: error: redefinition of ‘void fmt::internal::format_system_error(fmt::Writer&, int, fmt::StringRef)’
 FMT_FUNC void fmt::internal::format_system_error(
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:692:15: error: ‘void fmt::internal::format_system_error(fmt::Writer&, int, fmt::StringRef)’ previously defined here
 FMT_FUNC void fmt::internal::format_system_error(
               ^
../spdlog/details/format.cc: At global scope:
../spdlog/details/format.cc:716:6: error: redefinition of ‘void fmt::internal::ArgMap<Char>::init(const fmt::ArgList&)’
 void fmt::internal::ArgMap<Char>::init(const ArgList &args)
      ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:716:6: error: ‘void fmt::internal::ArgMap<Char>::init(const fmt::ArgList&)’ previously declared here
 void fmt::internal::ArgMap<Char>::init(const ArgList &args)
      ^
../spdlog/details/format.cc:762:6: error: redefinition of ‘void fmt::internal::FixedBuffer<Char>::grow(std::size_t)’
 void fmt::internal::FixedBuffer<Char>::grow(std::size_t)
      ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:762:6: error: ‘void fmt::internal::FixedBuffer<Char>::grow(std::size_t)’ previously declared here
 void fmt::internal::FixedBuffer<Char>::grow(std::size_t)
      ^
../spdlog/details/format.cc:767:14: error: redefinition of ‘fmt::internal::Arg fmt::internal::FormatterBase::do_get_arg(unsigned int, const char*&)’
 FMT_FUNC Arg fmt::internal::FormatterBase::do_get_arg(
              ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:767:14: error: ‘fmt::internal::Arg fmt::internal::FormatterBase::do_get_arg(unsigned int, const char*&)’ previously defined here
 FMT_FUNC Arg fmt::internal::FormatterBase::do_get_arg(
              ^
../spdlog/details/format.cc:785:6: error: redefinition of ‘void fmt::internal::PrintfFormatter<Char>::parse_flags(fmt::FormatSpec&, const Char*&)’
 void fmt::internal::PrintfFormatter<Char>::parse_flags(
      ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:785:6: error: ‘void fmt::internal::PrintfFormatter<Char>::parse_flags(fmt::FormatSpec&, const Char*&)’ previously declared here
 void fmt::internal::PrintfFormatter<Char>::parse_flags(
      ^
../spdlog/details/format.cc:813:5: error: redefinition of ‘fmt::internal::Arg fmt::internal::PrintfFormatter<Char>::get_arg(const Char*, unsigned int)’
 Arg fmt::internal::PrintfFormatter<Char>::get_arg(
     ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:813:5: error: ‘fmt::internal::Arg fmt::internal::PrintfFormatter<Char>::get_arg(const Char*, unsigned int)’ previously declared here
 Arg fmt::internal::PrintfFormatter<Char>::get_arg(
     ^
../spdlog/details/format.cc:826:10: error: redefinition of ‘unsigned int fmt::internal::PrintfFormatter<Char>::parse_header(const Char*&, fmt::FormatSpec&)’
 unsigned fmt::internal::PrintfFormatter<Char>::parse_header(
          ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:826:10: error: ‘unsigned int fmt::internal::PrintfFormatter<Char>::parse_header(const Char*&, fmt::FormatSpec&)’ previously declared here
 unsigned fmt::internal::PrintfFormatter<Char>::parse_header(
          ^
../spdlog/details/format.cc:863:6: error: redefinition of ‘void fmt::internal::PrintfFormatter<Char>::format(fmt::BasicWriter<Char>&, fmt::BasicCStringRef<Char>)’
 void fmt::internal::PrintfFormatter<Char>::format(
      ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:863:6: error: ‘void fmt::internal::PrintfFormatter<Char>::format(fmt::BasicWriter<Char>&, fmt::BasicCStringRef<Char>)’ previously declared here
 void fmt::internal::PrintfFormatter<Char>::format(
      ^
../spdlog/details/format.cc: In function ‘void fmt::report_system_error(int, fmt::StringRef)’:
../spdlog/details/format.cc:963:15: error: redefinition of ‘void fmt::report_system_error(int, fmt::StringRef)’
 FMT_FUNC void fmt::report_system_error(
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:963:15: error: ‘void fmt::report_system_error(int, fmt::StringRef)’ previously defined here
 FMT_FUNC void fmt::report_system_error(
               ^
../spdlog/details/format.cc: In function ‘void fmt::print(FILE*, fmt::CStringRef, fmt::ArgList)’:
../spdlog/details/format.cc:979:15: error: redefinition of ‘void fmt::print(FILE*, fmt::CStringRef, fmt::ArgList)’
 FMT_FUNC void fmt::print(std::FILE *f, CStringRef format_str, ArgList args)
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:979:15: error: ‘void fmt::print(FILE*, fmt::CStringRef, fmt::ArgList)’ previously defined here
 FMT_FUNC void fmt::print(std::FILE *f, CStringRef format_str, ArgList args)
               ^
../spdlog/details/format.cc: In function ‘void fmt::print(fmt::CStringRef, fmt::ArgList)’:
../spdlog/details/format.cc:986:15: error: redefinition of ‘void fmt::print(fmt::CStringRef, fmt::ArgList)’
 FMT_FUNC void fmt::print(CStringRef format_str, ArgList args)
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:986:15: error: ‘void fmt::print(fmt::CStringRef, fmt::ArgList)’ previously defined here
 FMT_FUNC void fmt::print(CStringRef format_str, ArgList args)
               ^
../spdlog/details/format.cc: In function ‘void fmt::print(std::ostream&, fmt::CStringRef, fmt::ArgList)’:
../spdlog/details/format.cc:991:15: error: redefinition of ‘void fmt::print(std::ostream&, fmt::CStringRef, fmt::ArgList)’
 FMT_FUNC void fmt::print(std::ostream &os, CStringRef format_str,
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:991:15: error: ‘void fmt::print(std::ostream&, fmt::CStringRef, fmt::ArgList)’ previously defined here
 FMT_FUNC void fmt::print(std::ostream &os, CStringRef format_str,
               ^
../spdlog/details/format.cc: In function ‘void fmt::print_colored(fmt::Color, fmt::CStringRef, fmt::ArgList)’:
../spdlog/details/format.cc:999:15: error: redefinition of ‘void fmt::print_colored(fmt::Color, fmt::CStringRef, fmt::ArgList)’
 FMT_FUNC void fmt::print_colored(Color c, CStringRef format, ArgList args)
               ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:999:15: error: ‘void fmt::print_colored(fmt::Color, fmt::CStringRef, fmt::ArgList)’ previously defined here
 FMT_FUNC void fmt::print_colored(Color c, CStringRef format, ArgList args)
               ^
../spdlog/details/format.cc: In function ‘int fmt::fprintf(FILE*, fmt::CStringRef, fmt::ArgList)’:
../spdlog/details/format.cc:1008:14: error: redefinition of ‘int fmt::fprintf(FILE*, fmt::CStringRef, fmt::ArgList)’
 FMT_FUNC int fmt::fprintf(std::FILE *f, CStringRef format, ArgList args)
              ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:1008:14: error: ‘int fmt::fprintf(FILE*, fmt::CStringRef, fmt::ArgList)’ previously defined here
 FMT_FUNC int fmt::fprintf(std::FILE *f, CStringRef format, ArgList args)
              ^
../spdlog/details/format.cc: In function ‘int fmt::fprintf(std::ostream&, fmt::CStringRef, fmt::ArgList)’:
../spdlog/details/format.cc:1016:14: error: redefinition of ‘int fmt::fprintf(std::ostream&, fmt::CStringRef, fmt::ArgList)’
 FMT_FUNC int fmt::fprintf(std::ostream &os, CStringRef format, ArgList args)
              ^
In file included from ../spdlog/details/format.h:4496:0,
                 from ../spdlog/details/format.cc:28:
../spdlog/details/format.cc:1016:14: error: ‘int fmt::fprintf(std::ostream&, fmt::CStringRef, fmt::ArgList)’ previously defined here
 FMT_FUNC int fmt::fprintf(std::ostream &os, CStringRef format, ArgList args)
              ^
make: *** [spdlog/details/format.o] Erreur 1

17:46:31 Build Finished (took 18s.136ms)

_____________________________________________________________________

Do you know why ?

Thanks

**Comment by gabime** [comment]
maybe your build already include the fmt lib(aka cppformat)?

**Comment by vitaut** [comment]
@qalastar You shouldn't include `format.cc` in the build
```
Building file: ../spdlog/details/format.cc
```
because spdlog includes it in a header-only configuration.

**Comment by qalastar** [comment]
I exclude the file format.cc for the build and it works now. Thank you both.

But now I have some trouble with the this : 

`// log
	try
	{
		//Multithreaded console logger(with color support)
		auto console = spdlog::stdout_logger_mt("console", true /*use color*/);
		console->info("Welcome to spdlog!") ;
		console->info("An info message example {} ..", 1);
		console->info() << "Streams are supported too  " << 2;

		// Create basic file logger (not rotated)
		auto my_logger = spdlog::basic_logger_mt("basic_logger", "logs/basic.txt");
		my_logger->info("Some log message");


		// create a file rotating logger with 5mb size max and 3 rotated files
		auto file_logger = spdlog::rotating_logger_mt("file_logger", "myfilename", 1024 * 1024 * 5, 3);
		file_logger->info("Hello spdlog {} {} {}", 1, 2, "three");

	}
	catch (const spdlog::spdlog_ex& ex)
	{
		cout << "Log failed: " << ex.what() << std::endl;
	}
`

when I build, the compiler said that it didn't find the method 'info' . You know why ?

Thank you very much for your help.

**Comment by gabime** [comment]
strange.. can you post th exact message?

**Comment by qalastar** [comment]
Here is : 

```
01:13:23 **** Incremental Build of configuration Debug for project manage_raid ****
make all 
Building file: ../src/main.cpp
Invoking: GCC C++ Compiler
g++ -I"/home/maxime/git/manage_raid/lib" -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"src/main.d" -MT"src/main.o" -o "src/main.o" "../src/main.cpp"
Finished building: ../src/main.cpp
 
Building target: manage_raid
Invoking: GCC C++ Linker
g++ -L"/home/maxime/git/manage_raid/lib" -o "manage_raid"  ./src/Raid.o ./src/main.o  ./lib/configuration/configuration.o   
./src/main.o : Dans la fonction « std::thread::thread<void (spdlog::details::async_log_helper::*)(), spdlog::details::async_log_helper*>(void (spdlog::details::async_log_helper::*&&)(), spdlog::details::async_log_helper*&&) » :
makefile:46 : la recette pour la cible « manage_raid » a échouée
/usr/include/c++/5/thread:137 : référence indéfinie vers « pthread_create »
collect2: error: ld returned 1 exit status
make: *** [manage_raid] Erreur 1

01:13:26 Build Finished (took 3s.317ms)

```

**Comment by gabime** [comment]
try adding the -pthread flag to the left linker

**Comment by qalastar** [comment]
Thank you. It's work well now :)
