### ISSUE TITLE
Error: make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by SpaceView** [gabime/spdlog#2334]
in Windows10, I did exactly what is mentioned,
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j

and also for the downloaded version,
https://github.com/gabime/spdlog/archive/refs/tags/v1.10.0.tar.gz

whichever I use, the following error appears, 
E:\vOpenMM\spdlog1100\build>cmake .. && make -j
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The CXX compiler identification is MSVC 19.29.30139.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.10.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE
-- Build type: Release
-- Generating example(s)
-- Generating install
-- Configuring done
-- Generating done
-- Build files have been written to: E:/vOpenMM/spdlog1100/build
make: *** No targets specified and no makefile found.  Stop.

It seems this doesn't work under windows. how can I fix this?

**Comment by tt4g** [comment]
Use the build command `cmake --build . --target all`.

```shell
$ git clone [gabime/spdlog.git](https://github.com/gabime/spdlog.git)
$ cd spdlog && mkdir build && cd build
#$ cmake .. && make -j
$ cmake .. && cmake --build . --target all
```

**Comment by kaushal98** [comment]
I have the same issue on Ubuntu 20.4 (running as VM in MacOS Monterey) as well. I've `spdlog` added as a git submodule in another project.

This works only as described here:
```
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j
```

You do need to clone the repo. Doesn't work with git submodule
