### ISSUE TITLE
Have an empty line with each log on use stdout_logger and redirect to file on windows.

### ISSUE THREAD

**Issue by wherewindblow** [gabime/spdlog#234]
Maybe this only make me uncomfortable.

1.Use stdout_sink_st to output in console will be normal.
`#include <spdlog/spdlog.h>`
`auto g_logger = spdlog::stdout_logger_st("logger");`
`int main(int argc, const char *argv[])`
`{`
`	g_logger->info("this");`
`	g_logger->info("is");`
`	return 0;`
`}`

output:
`this`
`is`

2.But when but redirection to redirect the output to a file, output will have empty line for each line.
`D:\a.exe > logfile`
output:
`this`
`//empty line`
`is`
`//empty line`

3.Record log to file via rotating_file_sink_st also will be normal.
`#include <spdlog/spdlog.h>`
`auto g_logger = spdlog::rotating_logger_st("logger", "logfile", 3 * 1024 * 1024, 1);`
`int main(int argc, const char *argv[])`
`{`
`	g_logger->info("this");`
`	g_logger->info("is");`
`	return 0;`
`}`

output:
`this`
`is`

On 
  file: spdlog/details/pattern_formatter_impl.h
  function: void spdlog::pattern_formatter::format(details::log_msg& msg)
  line 612: msg.formatted << details::os::eol(); 
It append eol() to each log. The details on
  file: spdlog/details/os.h
  line: 115
There are it details.
`#ifdef _WIN32`
`inline const char* eol()`
`{`
`    return "\r\n";`
`}`
`#else`
`constexpr inline const char* eol()`
`{`
`    return "\n";`
`}`
`#endif`

Open the output file in case 2 on binary and output with hex.
`#include <cstdio>`
`#include <cwchar>`
`int main(int argc, const char *argv[])`
`{`
`	freopen("logfile", "rb", stdin);`
`	char ch;`
`	while ((ch = getchar()) != EOF)`
`	{`
`		printf("0x%02x\t", ch);`
`		if (ch == '\n')`
`		{`
`			putchar('\n');`
`		}`
`	}`
`	return 0;`
`}`

output:
`0x74    0x68    0x69    0x73    0x0d    0x0d    0x0a`
`0x69    0x73    0x0d    0x0d    0x0a`

There are two CR(0x0d) and one LF(0x0a) on each end of line. It testify use standard buffer to output will handling '\n' and turn into "\r\n" on windows. So spdlog add eol() to each line end will turn into "\r\r\n". But why via rotating_file_sink_st will not lead to this result.There are some trail.

On
  file: spdlog/details/file_helper.h
  functions: void open(const filename_t& fname, bool truncate = false)
  line 50: auto *mode = truncate ? SPDLOG_FILENAME_T("wb") : SPDLOG_FILENAME_T("ab");
File is open with binary mode, '\n' will no be handling in this mode. So eol will keep it orginal and output "\r\n".

Finally, how to fix it. Just set eof() to return '\n' without check the operating system. And change the file open mode without binary.

**Comment by gabime** [comment]
Thanks for the details analysis. spdlog must open with binary mode because it relies on it in several places (seek  etc).

Furthermore, I always suspected that text mode is substantially slower than binary mode (in windows)
So I took the opportunity to do little test (write 1000000 lines to the nul device):

```c++

#include <stdio.h>
#include <tchar.h>
#include <cstdio>
#include <chrono>
#include <iostream>

#define LINE_SIZE 80
#define TOTAL_LINES 1000000

void bench(const char *open_mode)
{
    using clock = std::chrono::high_resolution_clock;
    auto *f = fopen("nul", open_mode);
    if (f == nullptr) {
        std::cerr << "Failed opening nul file for writing" << std::endl;
    }

    char line[LINE_SIZE];
    memset(line, 'a', LINE_SIZE);
    line[LINE_SIZE - 1] = '\n';

    auto start = clock::now();

    for (int i = 0; i < TOTAL_LINES; ++i) {
        fwrite(line, 1, LINE_SIZE, f);
    }
    auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(clock::now() - start).count();
    fclose(f);

    std::cout << "Open_mode:\t" << open_mode << std::endl;
    std::cout << "Total lines:\t" << TOTAL_LINES << std::endl;
    std::cout << "Line size:\t" << LINE_SIZE << std::endl;
    std::cout << "Total duration:\t" << millis << " millis" << std::endl << std::endl;
}


int main(int argc, char* argv[]) {
    bench("wb");
    bench("w");
}
```

And the results (windows 10, visual studio 2013): 

```
E:\devel\bench\Release>bench.exe
Open_mode:      wb
Total lines:    1000000
Line size:      80
Total duration: 40 millis

Open_mode:      w
Total lines:    1000000
Line size:      80
Total duration: 211 millis
```

**x5  slower!**

So the problem must be resolved in different way.

**Comment by wherewindblow** [comment]
Maybe is the check that decide to turn new line character slower it. And in fact, i also not often do that way and it maybe not important for me.

**Comment by gabime** [comment]
Yes. Doesn't worth the slowdown.

**Comment by mkren** [comment]
I set:
`#define SPDLOG_EOL "\n"`
as workaround of this issue.

**Comment by gabime** [comment]
there is also an option now in the formatter ctor to change the eol

**Comment by mkren** [comment]
thank you - it is better:
`logger->set_formatter(std::make_shared<spdlog::pattern_formatter>(logFormat, spdlog::pattern_time_type::local, "\n"));`
