### ISSUE TITLE
SPDLOG_USE_STD_FORMAT not cover user defined type use case

### ISSUE THREAD

**Issue by memetea** [gabime/spdlog#2340]
The user defined type format depends on "spdlog/fmt/ostr.h". which includes fmtlib header.  So even I define SPDLOG_USE_STD_FORMAT,  the assembly also depends on fmtlib. 

// user defined types logging by implementing operator<<
#include "spdlog/fmt/ostr.h" // must be included
struct my_type
{
    int i;
    template<typename OStream>
    friend OStream &operator<<(OStream &os, const my_type &c)
    {
        return os << "[my_type i=" << c.i << "]";
    }
};

void user_defined_example()
{
    spdlog::get("console")->info("user defined type: {}", my_type{14});
}

**Comment by tt4g** [comment]
Define `std::formatter<T, CharT>` specialization to format user-defined type with `std::format`.

See: https://en.cppreference.com/w/cpp/utility/format/formatter

**Comment by memetea** [comment]
> Define `std::formatter<T, CharT>` specialization to format user-defined type with `std::format`.
> 
> See: https://stackoverflow.com/questions/59909102/stdformat-of-user-defined-types

In such case we should rewirte format code for user defined types to remove dependency on fmtlib.    
This is reasonable to rewrite format code to use std::format. 
But I suggest to add document or make some changes to the ostr.h header to expose the fact that there are still depends on fmtlib without changing your format code.   


#if 0 // !defined(SPDLOG_FMT_EXTERNAL)
#    ifdef SPDLOG_HEADER_ONLY
#        ifndef FMT_HEADER_ONLY
#            define FMT_HEADER_ONLY
#        endif
#    endif
#    include <spdlog/fmt/bundled/ostream.h>
#elif !defined(SPDLOG_USE_STD_FORMAT)
#    include <fmt/ostream.h>
#endif

**Comment by memetea** [comment]
I checked the source in github. This problem was fixed.   
I'm using code from vcpkg. that's a bit older version.
