### ISSUE TITLE
 error C2338: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: 

### ISSUE THREAD

**Issue by xinsuinizhuan** [gabime/spdlog#2345]
spdlog/fmt/bundled/core.h(1728): error C2338: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt

**Comment by SpriteOvO** [comment]
Please try this solution in README https://github.com/gabime/spdlog#user-defined-types.

**Comment by hjxu2016** [comment]
`enum ecode;
SPDLOG_LOGGER_CALL(logger, "hree {} ", ecode )`;    same error message!

`SPDLOG_LOGGER_CALL(logger, "hree {} ", int(ecode) )`   Solve this problem~
