### ISSUE TITLE
Is there any way to log an exception occured in the catch block

### ISSUE THREAD

**Issue by beemibrahim** [gabime/spdlog#2351]
I want to log an exception , by getting the line and file number of where the exception occured , the exception could occur anywhere , I don't know where it might occur

**Comment by tt4g** [comment]
There is no feature in the C++ specification to record the location of an error.
Also note that any object can be thrown as an exception with `throw`, such as `throw 1` `throw "error"`.

**Comment by USAFrenzy** [comment]
Please correct me if I'm wrong, but I believe the closest thing you could get is here is setting your logger's pattern to use any of ```%s```, ```%@```, ```%g```, ```%#```, ```%!``` (This part I'm unsure of as I haven't tested it without using the log macros).

An alternative is to make your own flag formatter by inheriting from spdlog's ```spdlog::custom_flag_formatter``` and overload the format function to format using the source type macros or C++20's ```std::source_location``` functions. You can then just create a default spdlog formatter and add your custom flag to it, and then set that new formatter to your logger. Then, in your catch block, you could log to some sort of target. 

This might be unnecessary information, but you could even enable the backtrace support spdlog has to see what has been logged up until that point of failure. As far as I'm aware though, to do what you're wanting requires you to basically add a log line and try/catch block wherever something may throw in your program which can quite obviously be super tedious (looking at what functions you use that aren't noexcept or anything that could allocate).
