### ISSUE TITLE
Argument conversion issue

### ISSUE THREAD

**Issue by bloodgain** [gabime/spdlog#2353]
I imagine this is going to point at something in fmtlib, but I thought I'd ask here, too.

I'm running into a strange argument conversion error using spdlog v1.9.2:

error C2664: 'void spdlog::logger::info<unsigned int&>(fmt::v8::basic_format_string<char,T &>,unsigned int &)': cannot convert argument 2 from 'unsigned int' to 'unsigned int &'
        with
        [
            T=fmt::v8::detail::bigint::bigit
        ]

I have the following definitions and use:

```cpp
// defined by MSVC in basetsd.h
typedef unsigned int UINT32, *PUINT32;

struct BITS {
    unsigned int bit00 : 1;
    unsigned int bit01 : 1;
    //      .
    //      .
    //      .
    // and so on until...
    unsigned int bit31 : 1;
};

// Current Time Register
struct CTR_REG {
    unsigned int current_time : 32;
};

union CTRRegisterType {
    UINT32 wholeDword;
    CTR_REG fields;
    BITS bits;
};

CTRRegisterType ctr;
ctr.wholeDword = 12345;  // assume any call that writes a 32 bit value here

const auto filelogger = spdlog::basic_logger_mt("filelog", "somefile.log");

// casting to ulong will compile
filelogger->info(" First Read Time: {}", static_cast<unsigned long>(ctr.fields.current_time));

// doing an assignment then writing to unsigned int will compile
unsigned int ctime = ctr.fields.current_time;
filelogger->info(" First Read Time: {}", ctime);

// using the value directly will NOT compile, giving the error
filelogger->info(" First Read Time: {}", ctr.fields.current_time);

// casting to uint will NOT compile either! What?
filelogger->info(" First Read Time: {}", static_cast<unsigned int>(ctr.fields.current_time));
````

As you can see, I'm doing C++ but doing a little bit of C-like low-level work. This is the first time I've run into integer conversion issues at compile time. If anything, I probably have some unsanitary implicit conversions that could bite me at run time eventually.

Sure, it works with static_cast to ulong or an extra variable assignment step, but aside from that not being quite correct, it's a hassle. I just converted us away from iostreams/fstreams and bad custom logger classes to spdlog, and I really don't want to have to deliver the news that we have to static_cast every time we want to print an integer from these unions/structs, as they are core to our project.

Both spdlog and my project were built using Using VS 2017 v15.9.42.

Any ideas what I might be doing wrong, or if this is a limitation in spdlog/fmt -- intentional or otherwise?

Thanks!

**Comment by bloodgain** [comment]
Cross-posted issue with fmt:
https://github.com/fmtlib/fmt/issues/2876

FYI, if it's something I can help fix, I _am_ willing to help!

**Comment by gabime** [comment]
Not sure how this can be solved.  a workaround would be to use https://github.com/gabime/spdlog#user-defined-types for those classes

**Comment by USAFrenzy** [comment]
I'm not sure if the user defined types already do this under the hood, but would casting with a removal of the reference help in this case? If so, to avoid always having to static cast explicitly, you could just wrap the log function and in the wrapper static cast it?
Something like:
```cpp
template<typename T> struct is_unsigned_int;
template<typename T> struct is_unsigned_int<T, unsigned int>: std::bool_constant<(std::is_same<T, unsigned int>::value>{};

bool containsTypeToCast {false};

template<typename... Args> std::tuple<bool, unsigned int, int> CheckForType(Args&&... args){
(
[ = ](auto&& arg) {
    auto isSame = is_unsigned_int<std::remove_reference_t<decltype(arg)>> {};
    std::tuple<bool, unsigned int, int> result{false, 0, 0};
    int argCounter{0};
    for(;;){      
       ++argCounter;
        if constexpr(isSame.value){
            std::get<0>(result) = true;
            std::get<1>(result) = static_cast<std::remove_reference_t<unsigned int>>(arg);
            std::get<2>(result) = argCounter; 
            containsTypeToCast = true;
            break;
         }else{
            if(containsTypeToCast) break;
         }
    }
}(args),
...);
}

template<typename... Args>
void Info(spdlog::logger& logger, std::string_view fmtStr, Args&&... args){

    std::string finalStr;
    auto copy {fmtStr};   

    auto [containsValueToCast, value, argCount] = CheckForType(std::forward<Args>(args)...);

    if(containsValueToCast){
        for(int i {0}; i < argCount; ++i){
           auto begin {copy.find_first_of('{'};
           auto end {copy.find_first_of('{'};
           if(begin != std::string_view::npos && end != std::string_view::npos){
              copy.remove_prefix(end +1);
          }
        }      
        auto replaceStart {fmtStr.find(copy)};
        auto replaceEnd {replaceStart+ copy.size()};
        copy = std::vformat(copy, value);

        auto initialPortion {fmtStr.substr(0, replaceStart);
        auto remainder {fmt.substr(replaceEnd, fmt.size());

        finalStr.append(initalPortion).append(copy).append(remainder);
        logger->info(finalStr, std::forward<Args>(args)...);
      } else{
         logger->info(fmtStr, std::forward<Args>(args)...);
     }
```

Maybe with some more logic if you're using positional argument notation. This is off the top of my head, so I can't guarantee it works as-is but hopefully this might spark a better idea if the user-defined-types doesn't work out?

**Comment by bloodgain** [comment]
So the need to cast to a full-width type is apparently a limitation of C++'s perfect forwarding, per the fmtlib devs (see referenced cross-post). However, the failure to cast to `unsigned int` here is coming from spdlog, as that works in fmtlib directly: https://godbolt.org/z/d6K73Tes4

Casting to a wider size is not the end of the world, as in most cases, I'll be casting from much narrower bit fields (1-10 bits), anyway. Any idea why casting to `unsigned int` would fail here, but `unsigned long` would work fine?

Interestingly, I tried another case where I have a bit field of width 9. It will compile if I cast it to unsigned short, int, _or_ long. However, VS 2017's Intellisense still doesn't like seeing `unsigned int` here and will complain, even though MSVC compiles it fine.

**Comment by gabime** [comment]
> However, the failure to cast to unsigned int here is coming from spdlog, as that works in fmtlib directly: https://godbolt.org/z/d6K73Tes4

Strange. Could be a compiler issue? Have you tried to reproduce in gcc?

**Comment by bloodgain** [comment]
Yeah, it looks like this might be a bug in MSVC 15.x. I don't have gcc readily available (company Windows machine), but it appears to build on Compiler Explorer:

gcc 11.x, but oddly enough, passing in the raw bit field _also_ compiles here:
https://godbolt.org/z/ebr5z5naT

Compiles on MSVC 19.x, but not the raw bit field, as expected:
https://godbolt.org/z/EMToE53f9

Clang 14.0 is also OK with the raw bit field:
https://godbolt.org/z/qTKsMhn58

Can't run any of these for output, because linking fails for either spdlog or pthread. I have clang installed locally and might be able to see what it does, and I could set up on a personal box for gcc, but it looks like the issue is MSVC 15.x here.

I certainly don't expect you to patch spdlog for a bug in an old MSVC version! If I knew a fast fix, I might patch it for internal use, but probably just easier to work around it.

I'll close the issue. Thanks for the help!
