### ISSUE TITLE
`std::filesystem::path` as `filename_t`

### ISSUE THREAD

**Issue by laudrup** [gabime/spdlog#2355]
Currently `filename_t` can either be a `std::string` or `std::wstring` (when on Windows with the appropriate `#define`) and I was wondering why spdlog doesn't support `std::filesystem::path` for file sinks?

It would seem like the obvious type to use for filesystem paths when targeting C++17. At least as an option similar to how `std::wstring` can be enabled for Windows platforms but with the added benefit that `std::filesystem::path` is platform agnostic.

I haven't looked at the code in detail to be honest, but it would seem relatively trivial to implement and unless there's a specific reason why this is *not* supported I wouldn't mind trying to come up with a PR for that if it has any interest?

Thanks a lot.

**Comment by gabime** [comment]
It is not used is since spdlog is a c++11 lib.

**Comment by laudrup** [comment]
I hadn't considered that. I guess I just assumed that various language features could be used based on which version was targeted but it's a perfectly reasonable decision to stick to C++11 features only.

Thanks a lot for you reply.
