### ISSUE TITLE
How to automatically delete expired files in 'daily_logger_mt' mode?

### ISSUE THREAD

**Issue by 474914041** [gabime/spdlog#2366]
When I use 'daily_logger_mt' to recrod log, I set 'max_file' is 10.
But when the date is 20220412, it can't  automatically delete 20220401's log file. My batch program executes every ten minutes.
How to achieve this?

**Comment by tt4g** [comment]
If the rotation time is over, it rotates and then deletes the old log file.
If the application runs only for a short time, it does not cross the rotation time, so the deletion is not performed.

Please make sure to output logs across log rotation times. Or use logrotate to delete old log files.

**Comment by 474914041** [comment]
>Thanks for you addvice. 
I think delete overdue old log file is important for Spdlog in this case. Hope to be implemented in some version!

**Comment by 474914041** [comment]
Thanks for you addvice.
I think delete overdue old log file is important for Spdlog in this case. Hope to be implemented in some version!
