### ISSUE TITLE
Unresolved symbols when moving to spdlog 1.10 without recompile - maybe full symbol

### ISSUE THREAD

**Issue by commel** [gabime/spdlog#2369]
The cryfs package uses spdlog 1.8.x. openSUSE moved to spdlog 1.10. This resulted in unresolved symbols, because of a ABI break in one of the later commits: c47ae3b15dedc35cc62cc34ec1e411b040373776

Would it be possible to include version symbols in the releases? Or somehow maintain backward compatibility?

See our bugreport: https://bugzilla.opensuse.org/show_bug.cgi?id=1199306#c0

**Comment by tt4g** [comment]
`SPDLOG_VERSION` macro is here:

https://github.com/gabime/spdlog/blob/76fb40d95455f249bd70824ecfcae7a8f0930fa3/include/spdlog/version.h#L6-L10

**Comment by Vogtinator** [comment]
What's needed is to either increase the sover on each ABI incompatible release or introduce use of symbol versioning.

**Comment by tt4g** [comment]
There is no documentation on ABI compatibility for spdlog, but I think spdlog has a policy of not guaranteeing ABI compatibility with minor version upgrades.
@gabime Is this understanding correct?

**Comment by gabime** [comment]
We try not to break the ABI however it is certainly not guaranteed nor a top priority.
