### ISSUE TITLE
Missing C++11 flags

### ISSUE THREAD

**Issue by JensMunkHansen** [gabime/spdlog#237]
Using CMake 3.0.2 and g++ 4.9.2-10, you get a bunch of errors. 

You need to add --std=c++11 to your CMAKE_CXX_FLAGS

**Comment by gabime** [comment]
works for me. Which CMakeLists.txt are you executing ?

**Comment by JensMunkHansen** [comment]
The top one. I used cmake .. -DCMAKE_CXX_FLAGS=--std=c++11 to get around
the issue

**Comment by gabime** [comment]
This is strange. It already contains ```set(CMAKE_CXX_STANDARD 11)``` in line #9

Do you use this version for CMakeLists.txt?

**Comment by JensMunkHansen** [comment]
You need cmake version 3.1 to support that. I guess. You require 2.8 and I
have 3.0.1

**Comment by JensMunkHansen** [comment]
Sorry. You require version 3.0, but 3.1 is needed to
support set(CMAKE_CXX_STANDARD 11)

The reason why I did not work for me. It is very confusing that the people
from CMake cannot decide on a final product and things constantly change.
On linux, I still use automake for this reason. Just correct

cmake_minimum_required(VERSION 3.0)

to

cmake_minimum_required(VERSION 3.1)

Cheers,
Jens

**Comment by gabime** [comment]
thanks. i fixed it to 3.1
