### ISSUE TITLE
UDP and TCP sink

### ISSUE THREAD

**Issue by computerquip-work** [gabime/spdlog#2371]
I see these two in the code but I don't see any corresponding documentation. I'm curious if these are possible to use with remote syslog?

**Comment by tt4g** [comment]
You need to create our own UDP/TCP server.

**Comment by computerquip-work** [comment]
Fair enough. What format does it use? Is there an intended purpose of those sinks for now or is that pending further implementation?

**Comment by tt4g** [comment]
There is no dedicated format for TCP/UDP sink.
spdlog logging formatted messages are sent.
See Wiki; https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

And these are the PR submitted (#1426 #2090) for sending to a log collector.
