### ISSUE TITLE
Compile error when using SPDLOG_TRACE() with param and -fno-exceptions

### ISSUE THREAD

**Issue by prncoprs** [gabime/spdlog#2373]
When I use SPDLOG_TRACE() with parameters in my program, the program will crash. But if I comment out the SPDLOG_TRACE() with parameters, the program can work. Besides, the SPDLOG_TRACE() without parameters works in my program.
My code is as follows.
```
SPDLOG_TRACE("json");
SPDLOG_TRACE("Some trace message with param {}", 42);
```
If I comment out the second line, the program works. And the program can output the `json` string in my console. If I do not comment the second line, the program will present the follows.
```
/usr/include/spdlog/logger.h: In instantiation of ‘void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {int}; spdlog::string_view_t = fmt::v8::basic_string_view<char>]’:
/usr/include/spdlog/logger.h:83:13:   required from ‘void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v8::format_string<T ...>, Args&& ...) [with Args = {int}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, int>]’
/home/klee/lib/Core/SI.cpp:441:5:   required from here
/usr/include/spdlog/logger.h:336:9: error: exception handling disabled, use ‘-fexceptions’ to enable
  336 |         SPDLOG_LOGGER_CATCH()
      |         ^~~~~~~~~~~~~~~~~~~
/usr/include/spdlog/logger.h:336:9: error: ‘...’ handler must be the last handler for its try block [-fpermissive]
```

My os is ubuntu 22.04. 
Package: libspdlog-dev
Version: 1:1.9.2+ds-0.2

**Comment by tt4g** [comment]
`try` and `catch` keywords are not allowed with the `-fno-exceptions` option enabled.

Remove `-fno-exceptions` or define CMake variable `SPDLOG_NO_EXCEPTIONS`.

**Comment by prncoprs** [comment]
> 

Could you please tell me where I should put this line `set(SPDLOG_NO_EXCEPTIONS ON)`? In my project main `CMakeLists.txt`? I did not use the header-only version. I use the `sudo apt install libspdlog-dev` to install the package.

**Comment by kslattery** [comment]
@prncoprs The libspdlog that you have installed was built with SPDLOG_NO_EXCEPTIONS == OFF. You'll have to build the libspdlog library yourself with SPDLOG_NO_EXCEPTIONS == ON, then build your project against that version.

Also, you should change the title of this issue. Your program isn't crashing, it's failing to compile. Something like "Compile error when using SPDLOG_TRACE() with param and -fno-exceptions".

**Comment by prncoprs** [comment]
> @prncoprs The libspdlog that you have installed was built with SPDLOG_NO_EXCEPTIONS == OFF. You'll have to build the libspdlog library yourself with SPDLOG_NO_EXCEPTIONS == ON, then build your project against that version.
> 
> Also, you should change the title of this issue. Your program isn't crashing, it's failing to compile. Something like "Compile error when using SPDLOG_TRACE() with param and -fno-exceptions".

Can I use header-only version without compilation?

**Comment by tt4g** [comment]
The CMake target `spdlog::spdlog_header_only` should be defined.
Replace `spdlog::spdlog` in `target_link_libraries()` with `spdlog::spdlog_header_only`.

**Comment by prncoprs** [comment]
I added the `set(SPDLOG_NO_EXCEPTIONS ON)` to the main `CMakeList.txt` file, recompiled the spdlog using source, and `sudo make install`, then the problem was fixed. Sincerely thanks! @tt4g @kslattery
