### ISSUE TITLE
[Question] Can I set newline by myself?

### ISSUE THREAD

**Issue by panzhongxian** [gabime/spdlog#2378]
I want to use spdlog as an line log dumper. I find it may use '\n' or '\r' as newline seperator depending on different platform.
Is it possible allow user choose which kind of new line seperator by themself?

**Comment by tt4g** [comment]
You can define the `SPDLOG_EOL` macro to `""` to override newline (see `tweakme.h`).

See also:

- #579
- #298

**Comment by panzhongxian** [comment]
Solved. Thank you very much! @tt4g
