### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_LIBDIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [gabime/spdlog#2380]
As per title: `cmake/spdlog.pc.in` has (since https://github.com/gabime/spdlog/pull/1238)
```
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_LIBDIR`. This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by tt4g** [comment]
Can you submit a PR to be fixed?

**Comment by alexshpilkin** [comment]
Yes, now that I’ve finished reporting all the other instances of this problem I actually can :)
