### ISSUE TITLE
conflict when using boost

### ISSUE THREAD

**Issue by memetea** [gabime/spdlog#239]
when using boost::posix_time and spdlog.  the boost::posix_time::hours and std::chrono::hours conflicts.  compiler complains.    for example:  228@file_sinks.h` return system_clock::time_point(rotation_time + hours(24));`

**Comment by gabime** [comment]
It is a a in warning or an error ? Could you please post more details of the exact message and the compiler version?

**Comment by gabime** [comment]
Can't reproduce

**Comment by memetea** [comment]
sorry.  I recheck this issue for a long latency.    if `using boost:posix_time` and `using std::chrono` in the mean time. then the symbol with same name under these two namespaces will conflict. compiler can't distigush which one to use.   so i think `return std::chrono::system_clock::time_point(rotation_time + std::chrono::hours(24));`  maybe better.

**Comment by gabime** [comment]
Never mind i fixed it anyway to use the full namespace.
