### ISSUE TITLE
Are there ways to print the vector of pointers (not the pointer value)? 

### ISSUE THREAD

**Issue by allencho1222** [gabime/spdlog#2390]
I couldn't find the solution on this issue.

```
Class A {
public:
  ...
private:
  template <typename OStream>
  friend OStream &operator<<(OStream &os, const Stat& stat) {
     fmt::format_to(std::ostream_iterator<char>(os), "{}", ...);
     return os;
  }
}

int main(void) {
  std::vector<A> v_1;
  std::vector<A*> v_2;
  logger->trace("{}", fmt::join(v_1, " "));  // 1
  logger->trace("{}", fmt::join(v_2, " ")); // 2

  return 0;
}
```

As in the above example, the logger only works for the case 1.
If class A is not abstract class, transforming A* to A by using `std::transform` can be one of possible solutions.
However, if class A is an abstract class, it is impossible to convert type A* to A. 
How to make the case 2 same as the case 1? Is it impossible?

**Comment by tt4g** [comment]
I recommend moving this issue to the fmt project because `fmt::join()` is API provided by fmt project.

**Comment by tt4g** [comment]
In fmt v8.1.1, `fmt::formatter` specification works for me.

[Compiler Explorer](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAAzGakAA6oCoRODB7evnrJqY4CQSHhLFEx8baY9vkMQgRMxASZPn5cFVXptfUEhWGR0XoKdQ1N2a2DXT3FpRIAlLaoXsTI7BzmscHI3lgA1CaxblQsBAD0aMSYAHQIe9gmGgCCaxtbmLv7hyf8xCxMBFc3d0eDyeDE2Xh2ezcADdMA4SADgQ9NkwFAptvddgB2KzAzEAET2OKB9wImBYiQMpLebhu20GxC8Dm2HxAIC%2BPwIpOIkMesWwIGZJA5XMh9OCwAA%2BlC8JgAO60kzYwHbbbHY7bRL1JTbPBo4IIaKETDoZnEVAsQXfX4i/ZioxSmXyvkXZXbUnkymvSEEACeiUYrFeADEhb8PIJMKoCAiMdsmF4iJaORAMUw06RtiGrY1ZJHo2YAGzbByqGZYokqlXnAiLBhJ63RUUEYjih1ym6s9m/CDmMyPMwJYsEUuE12Kgm4gmxImA90U35e/a0%2BmMgjMo6d0Ocxv7e4AKg79e33Ntzdb0vbfPLrrVGq1r11OoYBpbpJNVDNFq7x6bLftF6dbAXQeFU509alfX9Zg2EzLdw1JKMYxVeNE2/FM9zjdNYOzeC83MIsSzLRUK0ratayPG03DtSUAI7Nktx7Ad917DNCNHECsQnR58XY4lgjXH5gggIilQ4lVBnQVkYThE83F5bBtihCUuB7bF7mEjN1JmcdtOnV1xIISSQGkohZOYq8lLMVSLBCWV0Q07ZbPs7T8V0mcxPXAhWUSP8CEYsxiPHEwAFY3AYFjPNZbRUCEpTWl2AcErMGY3P0yKQB8/j/MCnjQvCgcMxZEBotiiVB17JKUt4oKHg4OZaE4YLeD8DgtFIVBOBpSxrDpBYli9MxYh4UgvNauq5gAaxASQNAuYLgoATgADmCzENFWzFMTMSQlv0ThJGazReA6jheAUEANBGo65jgWAYEQFBzUSOhonISg0HJF6YmALgNASGhaC5c6IAiI7SAiYJ6h9Thho%2BthBAAeQYWhobG0gsB%2BIxxDR/BzgcPAYXOtHI1hBMVja/jKjB2g8AiYgoY8LAYd4M8WGZuYqAMYAFAANUdBGoOZmRBBEMR2CkYX5CUNQwd0VoDCMFBrGsfRafO2BoPYD5SBhGIOCWrgeBS9rEmqImAFoEbOypYWqFwGHcTxmn8B3Jj6GJWlyNIBBGFokhSb2GDdkp%2BjGG38YETphid0Y2ltjohm6YJehDj3bET32BkT4Ppi4OYFD65Y9GbTAViNvaOCa0gWrak7VCWgtzYLSRtmAZBkG2X6LjMbYIC6qxLAzXBCBIBKhozDxPvoYgx7zlnrsmkBgsuhqOAO0g2eX6uwZOs6LqusabvuiAkAWAhEgTN6IGNEeW0k1p%2BBF0RxAlx%2BpZUdQ0bl0hZXpxJ2YrlXGux1OAIwTBfNcqAqDbHro3Zurd26d1mj3PuT0vqzxmPPQ%2BcwDRMCwDEDSq916b0usA9qnA96XVGloY2U1FoXEkDNKQZgFqSAHGYTEwUEir1iIdNGu8D40PqpwMwfDa4UMEeNHW0RUjOEkEAA)

Code:

```cpp
#include <fmt/core.h>
#include <fmt/format.h>

#include <vector>

class A {
};

template <> struct fmt::formatter<A>: formatter<string_view> {
  // parse is inherited from formatter<string_view>.
  template <typename FormatContext>
  auto format(A aaa, FormatContext& ctx) {
    return formatter<string_view>::format("A", ctx);
  }
};

template <> struct fmt::formatter<A*>: formatter<string_view> {
  // parse is inherited from formatter<string_view>.
  template <typename FormatContext>
  auto format(A* aaa, FormatContext& ctx) {
    return formatter<string_view>::format("A*", ctx);
  }
};

int main() {
    std::vector<A> v_1({A(), A()});
    std::vector<A*> v_2({new A(), new A()});

    fmt::print("{}\n", fmt::join(v_1, " "));
    fmt::print("{}\n", fmt::join(v_2, " "));
}

```

**Comment by allencho1222** [comment]
@tt4g

Thank you. This is what I want to achieve.
