### ISSUE TITLE
windows下VS2015编译spdlog(release x64)提示:fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“X86”冲突

### ISSUE THREAD

**Issue by Valder-Fields** [gabime/spdlog#2392]
步骤:
cd spdlog && mkdir build && cd build
cmake ..
使用VS2015打开spdlog.sln
设置release模式
新建x64模式,并选择x64
编译出现如下提示:
1>  Checking Build System
2>------ 已启动生成: 项目: spdlog, 配置: Release x64 ------
2>  Building Custom Rule D:/fjy/test/library/spdlog-1.10.0/spdlog-1.10.0/CMakeLists.txt
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>  spdlog.cpp
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>  stdout_sinks.cpp
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>  color_sinks.cpp
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>  file_sinks.cpp
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>  async.cpp
2>  cfg.cpp
2>cl : 命令行 warning D9002: 忽略未知选项“/Zc:__cplusplus”
2>  fmt.cpp
2>x64\Release\spdlog.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“X86”冲突
========== 生成: 成功 1 个，失败 1 个，最新 0 个，跳过 0 个 ==========

![image](https://user-images.githubusercontent.com/30290537/170824887-7b83e0cf-a8b2-49e7-a2e5-9c3e8404fb16.png)

**Comment by tt4g** [comment]
This is due to the fact that you are building for x64 in the CMake configuration.
Your machine is x64, so the x64 compiler is used, but the target machine is x86, so you cannot build.

Please specify x86 compiler in the CMake generator.

```shell
$ cd spdlog && mkdir build && cd build
$ cmake -G "Visual Studio 14 2015" -A Win32 ..
```

See also:
- https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2014%202015.html
- https://stackoverflow.com/questions/45226775/cmake-how-to-specify-target-platform
- https://stackoverflow.com/questions/41762898/fatal-error-lnk1112-module-machine-type-x64-conflicts-with-target-machine-typ

**Comment by Valder-Fields** [comment]
> This is due to the fact that you are building for x64 in the CMake configuration. Your machine is x64, so the x64 compiler is used, but the target machine is x86, so you cannot build.
> 
> Please specify x86 compiler in the CMake generator.
> 
> ```shell
> $ cd spdlog && mkdir build && cd build
> $ cmake -G "Visual Studio 14 2015" -A Win32 ..
> ```
> 
> See also:
> 
> * https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2014%202015.html
> * https://stackoverflow.com/questions/45226775/cmake-how-to-specify-target-platform
> * https://stackoverflow.com/questions/41762898/fatal-error-lnk1112-module-machine-type-x64-conflicts-with-target-machine-typ

我的需求是在win10下使用VS2015 release x64模式进行编译,所以我的目标计算机确实是X64的
但是不知道为什么它会提示目标计算机类型是x86?  这是问题的根本,不清楚什么地方使得工程配置识别成了x86的模式,请问还有什么解决办法吗?

**Comment by tt4g** [comment]
If you have changed the CMake configuration on your machine, the default build mode will change.
Questions related to the CMake configuration should be directed to the CMake community.

See also official document:
- [User Interaction Guide — CMake 3\.23\.2 Documentation](https://cmake.org/cmake/help/v3.23/guide/user-interaction/index.html)
- [cmake\-gui\(1\) — CMake 3\.23\.2 Documentation](https://cmake.org/cmake/help/v3.23/manual/cmake-gui.1.html)

**Comment by Valder-Fields** [comment]
没有做cmake的设置修改,我的开发环境编译其他项目没有问题,但是使用spdlog编译步骤生成的IDE的工程文件,进行win10下 release x64模式编译就产生上述问题,似乎是spdlog的cmakelist写的有问题导致的,能否帮忙尝试一下同样的环境是否你那里没有问题呢?

**Comment by Valder-Fields** [comment]
问题已解决
按照官方编译说明中的操作:
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j
生成的是默认x86编译的工程文件,即使用vs2015打开工程修改为x64也不能编译,始终会报上述错误,如需编译x64模式,需要:
使用cmake-gui.exe配置工程,选项中选择x64,再genarate,这样生成的工程文件编译没有问题
