### ISSUE TITLE
[feature] iOS support

### ISSUE THREAD

**Issue by nicola36631** [gabime/spdlog#2393]
Given that spdlog already supports all the big Operating Systems, it would be great if iOS support was added as well to achieve complete cross-platform compatibility.
Are there currently any plans for it?

**Comment by tt4g** [comment]
spdlog requires C++11. In other words, if C++11 is supported, it can be used.

Related:

- #491
- #2069

**Comment by nicola36631** [comment]
but it is not mentioned in the supported platforms list  of the README, and the last post on the first issue you linked (#491 ) mentions that they couldn't get most features to work.

**Comment by tt4g** [comment]
The maintainer says "Not officially" (#491), and I don't know why it is not working as there is no error log and crash report.
