### ISSUE TITLE
There are some errors when compiling, the development environment is vs2015(not updated).

### ISSUE THREAD

**Issue by Valder-Fields** [gabime/spdlog#2395]
There are some errors when compiling, the development environment is win10, vs2015(not updated).
The error is shawn by the picture below
 
![image](https://user-images.githubusercontent.com/30290537/171368616-d5875550-e4f9-42bb-a8ad-6c733c8b664e.png)

**Comment by tt4g** [comment]
It is an issue with the fmt library, so please move the issue in the [fmt project](https://github.com/fmtlib/fmt).
