### ISSUE TITLE
CMAKE_CXX_STANDARD should be c++20 if SPDLOG_USE_STD_FORMAT is set

### ISSUE THREAD

**Issue by mdavis199** [gabime/spdlog#2400]
By default, `spdlog`  sets `CMAKE_CXX_STANDARD 11`. However, if the option `SPDLOG_USE_STD_FORMAT` is `ON`, the required standard should be 17 or higher, because `std::string_view` is required. 

This can cause problems when using package managers such as vcpkg or conan.   To enable SPDLOG_USE_STD_FORMAT, package managers need to patch spdlog's CMakelist.txt.

I suggest that spdlog's CMakeLists.txt should specify the CMAKE_CXX_STANDARD through `target_compile_features` based on the value of `SPDLOG_USE_STD_FORMAT`.

**Comment by tt4g** [comment]
Right. PR is welcome.

Workaround. if we specify `cmake -DCMAKE_CXX_STANDARD=20 (other options...)` at build time, the problem should not appear.

**Comment by cookcocck** [comment]
@mdavis199 
What if we specify CMAKE_CXX_STANDARD by target_compile_features, but also want to pass the parameter via `cmake -DCMAKE_CXX_STANDARD`?

**Comment by cookcocck** [comment]
@tt4g  Could you please check my PR?
https://github.com/gabime/spdlog/pull/2402

**Comment by sylveon** [comment]
Seems like this can be closed
