### ISSUE TITLE
process core

### ISSUE THREAD

**Issue by paxifaer** [gabime/spdlog#2403]
when my c++ process core,does spdlog will switch old log file's name?  I cannot search some information about it.

**Comment by tt4g** [comment]
What's mean "process core"?

The sinks provided by spdlog, such as rotating_file_sink and daily_file_sink, rename rotated file names when rotating old files.

See also

- https://github.com/gabime/spdlog/wiki/4.-Sinks
- https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/rotating_file_sink.h
- https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/daily_file_sink.h

**Comment by paxifaer** [comment]
Means my program suddenly crashes for some reason

**Comment by tt4g** [comment]
Since the behavior of a crashed C++ application is undefined behavior, spdlog behavior is not guaranteed.

If the rotation conditions are met when the application is run again, spdlog will rotate (rename) the file.

**Comment by paxifaer** [comment]
Can this be done? Every time the program starts, it checks whether there is a generated log file. If the log file already exists, rename the existing log file, and then generate a new log file.

**Comment by tt4g** [comment]
spdlog does not know if the application has crashed.
You should rename the log at your own risk before calling spdlog.

**Comment by paxifaer** [comment]
Ok,I konw what you mean.Thanks a lot.
