### ISSUE TITLE
how to disable default “” logger

### ISSUE THREAD

**Issue by stan1334** [gabime/spdlog#2405]
#ifndef SPDLOG_DISABLE_DEFAULT_LOGGER

option(SPDLOG_NO_ATOMIC_LEVELS "" ON)

valied

 registry::registry()

create  default_logger_name = ""; logger

i dont need "" logger

how to disable “” logger

@gabime

**Comment by tt4g** [comment]
You can disable default_logger by defining `SPDLOG_DISABLE_DEFAULT_LOGGER`.

See Wiki: https://github.com/gabime/spdlog/wiki/8.-Tweaking
Source: https://github.com/gabime/spdlog/blob/v1.10.0/include/spdlog/details/registry-inl.h#L37-L49

**Comment by stan1334** [comment]
> SPDLOG_DISABLE_DEFAULT_LOGGER

#define SPDLOG_DISABLE_DEFAULT_LOGGER

int main()
{
    std::cout << "Hello World!\n";
    INOV_LOG(CINOLOG_LEVEL_ERROR,  "11111111111", "2222222222222 {}", 10);

defaut "" logger always exist

**Comment by gabime** [comment]
You need to define it before building the library itself.

**Comment by stan1334** [comment]
> You need to define it before building the library itself.

add_compile_options(-DSPDLOG_DISABLE_DEFAULT_LOGGER)
TK U
