### ISSUE TITLE
win7 program exit stuck

### ISSUE THREAD

**Issue by stan1334** [gabime/spdlog#2406]
windbg analyze dmp：
0:000> k
Child-SP          RetAddr           Call Site
00000000`001ac7b8 00000000`77ca5ff0 ntdll!ZwReleaseKeyedEvent+0xa
00000000`001ac7c0 00000000`77cabaf7 ntdll!RtlTryAcquireSRWLockShared+0x1a0
00000000`001ac800 000007fe`edeb26bb ntdll!RtlWakeConditionVariable+0x47
00000000`001ac830 000007fe`edeb2979 MSVCP140D!std::_Winerror_message+0x36b
00000000`001ac860 000007fe`ee24b1bc MSVCP140D!Cnd_signal+0x39
00000000`001ac8a0 000007fe`ee230331 Commons!std::condition_variable::notify_one+0x1c [C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\mutex @ 587]
00000000`001ac8d0 000007fe`ee236d48 Commons!spdlog::details::periodic_worker::~periodic_worker+0x71 [E:\-Commit\\3rdparty\spdlog\include\spdlog\details\periodic_worker-inl.h @ 44]
00000000`001ac920 000007fe`ee234a20 Commons!spdlog::details::periodic_worker::`scalar deleting destructor'+0x18
00000000`001ac950 000007fe`ee22fa92 Commons!std::default_delete<spdlog::details::periodic_worker>::operator()+0x30 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\memory @ 3090]
00000000`001ac990 000007fe`ee230470 Commons!std::unique_ptr<spdlog::details::periodic_worker,std::default_delete<spdlog::details::periodic_worker> >::~unique_ptr<spdlog::details::periodic_worker,std::default_delete<spdlog::details::periodic_worker> >+0x32 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\memory @ 3200]
00000000`001ac9c0 000007fe`ee2c82c2 Commons!spdlog::details::registry::~registry+0x30 [E:\-Commit\\3rdparty\spdlog\include\spdlog\details\registry-inl.h @ 52]
00000000`001ac9f0 000007fe`edd04957 Commons!`spdlog::details::registry::instance'::`2'::`dynamic atexit destructor for 's_instance''+0x12
00000000`001aca20 000007fe`edd04365 ucrtbased!initterm_e+0x6a7
00000000`001acab0 000007fe`edd0449a ucrtbased!initterm_e+0xb5
00000000`001acaf0 000007fe`edd04b01 ucrtbased!initterm_e+0x1ea
00000000`001acb40 000007fe`ee29ce69 ucrtbased!execute_onexit_table+0x31
00000000`001acb80 000007fe`ee29e88c Commons!__scrt_dllmain_uninitialize_c+0x19 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\utility\utility.cpp @ 399]
00000000`001acbb0 000007fe`ee29e667 Commons!dllmain_crt_process_detach+0x4c [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\dll_dllmain.cpp @ 182]
00000000`001acbf0 000007fe`ee29e9fe Commons!dllmain_crt_dispatch+0x67 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\dll_dllmain.cpp @ 220]
00000000`001acc30 000007fe`ee29eb71 Commons!dllmain_dispatch+0xfe [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\dll_dllmain.cpp @ 293]

build on win10 64 ，running win10 ok
build on win10 64 ，running win7 stuck

spdlog version  1.9.2

#define SPDLOG_VER_MAJOR 1
#define SPDLOG_VER_MINOR 9
#define SPDLOG_VER_PATCH 2

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

@gabime 
@Gabi120

**Comment by tt4g** [comment]
Seems to be a known issue.

Don't use spdlog inside Windows `DllMain()` function.

- #1530
- #2304
- https://github.com/gabime/spdlog/wiki/0.-FAQ#asynchronous-logging-hangs-under-windows-dll

Or, don't forget call `spdlog::shutdown()` before exiting the `main()` on Windows.

- #1809

**Comment by stan1334** [comment]
> Seems to be a known issue.
> 
> Don't use spdlog inside Windows `DllMain()` function.
> 
> * [Initialising spdlog inside DLL rather than main function #1530](https://github.com/gabime/spdlog/issues/1530)
> * [async_logger in DLL on windows is not working properly #2304](https://github.com/gabime/spdlog/issues/2304)
> * https://github.com/gabime/spdlog/wiki/0.-FAQ#asynchronous-logging-hangs-under-windows-dll
> 
> Or, don't forget call `spdlog::shutdown()` before exiting the `main()` on Windows.
> 
> * [spdlog crashed on drop_all() #1809](https://github.com/gabime/spdlog/issues/1809)

void Dlllog::DestoryLogger() {
+		spdlog::shutdown();
+	}


if use dllmain

main process 
int main(){
Dlllog::Log("Helloworld 1");
    Dlllog::Log("Helloworld 2");
    Dlllog::Log("Helloworld 3");
    Dlllog::Log("Helloworld 4");
    Dlllog::Log("Helloworld 5");
 Dlllog::DestoryLogger()
}

**Comment by tt4g** [comment]
Is the source code you provided accurate code? At least `__declspec(dllexport)` is missing in `Dlllog::DestoryLogger()`.
And if the function body of `Dlllog::DestoryLogger()` is written in a header file, then the application inlines the function and calls `spdlog::shutdown()` in the application memory space. Therefore, `spdlog::shutdown()` is not called in the memory space of the library.

See:
  - https://github.com/gabime/spdlog/issues/2304#issuecomment-1065137959
  - https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

**Comment by stan1334** [comment]
https://github.com/gabime/spdlog/wiki/7.-Flush-policy
i see three mode for flush datas from cache 2 disk。

I also refreshed the log without using these three methods, I want to know where the default refresh mechanism is in the code

please guide me。
@tt4g

**Comment by tt4g** [comment]
spdlog provides only those three flash APIs.

The question has changed, does that mean the issue (application crash) has been resolved?

**Comment by stan1334** [comment]
i set period refresh in my dll
//spdlog::flush_every(std::chrono::seconds(3));

not use any refres mode，normal exit on win7.
so  i check source code，when lgger-log will be write datas 2 disk，so default refesh mode is record log is refresh？

**Comment by tt4g** [comment]
If flush policy is not set, spdlog will not flush actively. Basically, the OS will flush the memory buffer automatically.

And if you crash with `spdlog::flush_every()`, you are not shutting down spdlog in the DLL with `spdlog::shutdown()`.
You need to read the issue links I have presented so far and fix your own code.

**Comment by stan1334** [comment]
automatically will be wast io，period flush is good，bug i need modify on test environment。
I'll get back to you with the results later

**Comment by stan1334** [comment]
> automatically will be wast io，period flush is good，bug i need modify on test environment。 I'll get back to you with the results later

https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

my dllmain is not same the official example
//commons.dll
//commonDef.h

COMMONFUN_EXPORT void recordLog(int level, string logRecord, spdlog::source_loc loc);
COMMONFUN_EXPORT void initLogger(std::string loggerName);
COMMONFUN_EXPORT void flushLog();

template<class Formatter, class ... Args>
inline void strFormatter(spdlog::source_loc loc, int level, string strModlueName, const Formatter& fmt, Args &&...args) {
	//日志内容拼接
	string logContext;
	try {
		logContext = fmt::format(fmt, args...);
	}
	catch (exception& ec) {
		logContext += ec.what();
	}

	string logRecord;
	logRecord = fmt::format(LOG_FMT_STR, strModlueName, logContext);
	//发送日志loc记录文件行号、函数名等信息
	recordLog(level, logRecord, loc);
}

#define LOG(level, modluename, formatter, ...) strFormatter(spdlog::source_loc{ FILE, LINE, FUNCTION}, level, modluename, FMT_STRING(formatter), VA_ARGS)
#define LOG_T(modluename, formatter, ...) LOG(SPDLOG_LEVEL_TRACE, modluename, formatter, VA_ARGS)
#define LOG_E(modluename, formatter, ...) LOG(SPDLOG_LEVEL_ERROR, modluename, formatter, VA_ARGS)
#define FLUSH_LOG flushLog()

class TestSpdLog
{
public:
	//防止外部构造
	TestSpdLog();
	//拷贝构造禁用
	TestSpdLog(TestSpdLog const&) = delete;
	//赋值拷贝禁用
	TestSpdLog& operator=(TestSpdLog const&) = delete;
	~TestSpdLog();
	static TestSpdLog* getInstance();

public:
	void close();
	void recordLog(int nLogLevel, string strLogContext, spdlog::source_loc loc);
	string getlogPath();
	//设置logerNamer
	void setLoggerName(const std::string loogerName);
	//初始化looger
	int initLogger(string serviceName);
	//立即刷新
	void flush();

private:
	//自动清理
	void autoClearCacheData();
	//更新定时器：刷新日志目录 每天
	void startUpdateDirTimer(UInt64 id = -1, UInt64 interval = -1);
	//获取写日志全路径
	void getWriteLogDir(string serviceName, string& filePath);

private:
	//日志配置文件信息
	LogConfigInfo m_LogConfigInfo;
	//日志记录器
	vector<string> m_loggersName;
	//定时器24小时更新日志目录
	std::shared_ptr<Timer<asio::steady_timer>> m_pTimer;
	std::string m_loggerName;
};
//commonDef.cpp
void TestSpdLog::close() {
	spdlog::shutdown();
}

void recordLog(int level, string logRecord, spdlog::source_loc loc) {
	//发送日志loc记录文件行号、函数名等信息
	TestSpdLog::getInstance()->recordLog(level, logRecord, loc);
}

void initLogger(std::string loggerName) {
	TestSpdLog::getInstance()->setLoggerName(loggerName);
	TestSpdLog::getInstance()->initLogger(loggerName);
}

void flushLog() {
	TestSpdLog::getInstance()->flush();
	TestSpdLog::getInstance()->close();
}

// In the main program

#include commonDef.h
int main() {
	LOG_E("moudleA", "main start {}", 111);
	LOG_T("moudleA", "main start {}", 111);

	//FLUSH_LOG  just to it?
}


so，open FLUSH_LOG will normal exit on win7?

**Comment by tt4g** [comment]
> so，open FLUSH_LOG will normal exit on win7?

In theory, yes, but it is not clear since there is no function body for `TestSpdLog::getInstance()`.

Please, can you format the source code? It is very difficult to read.
The source code is formatted by enclosing it in ` ```cpp ` and ` ``` `.

Example:

````
```cpp
class Foo
{
};
```
`````

Result:

```cpp
class Foo
{
};
```

**Comment by stan1334** [comment]
> 

already update ，TestSpdLog.cpp code not very convenient。

**Comment by stan1334** [comment]
> > so，open FLUSH_LOG will normal exit on win7?
> 
> In theory, yes, but it is not clear since there is no function body for `TestSpdLog::getInstance()`.
> 
> Please, can you format the source code? It is very difficult to read. The source code is formatted by enclosing it in `` ```cpp `` and `` ``` ``.
> 
> Example:
> 
> ```
> ```cpp
> class Foo
> {
> };
> ```
> ```
> 
> Result:
> 
> ```c++
> class Foo
> {
> };
> ```

already update ，TestSpdLog.cpp code not very convenient。

**Comment by stan1334** [comment]
> > so，open FLUSH_LOG will normal exit on win7?
> 
> In theory, yes, but it is not clear since there is no function body for `TestSpdLog::getInstance()`.
> 
> Please, can you format the source code? It is very difficult to read. The source code is formatted by enclosing it in `` ```cpp `` and `` ``` ``.
> 
> Example:
> 
> ```
> ```cpp
> class Foo
> {
> };
> ```
> ```
> 
> Result:
> 
> ```c++
> class Foo
> {
> };
> ```

// clean all resources and threads started by the registry
SPDLOG_INLINE void registry::shutdown()
{
    {
        std::lock_guard<std::mutex> lock(flusher_mutex_);
        periodic_flusher_.reset();
    }

}


i think i know why call shutdown on main ,TKU,

**Comment by tt4g** [comment]
The reason is simple: the resources present in the DLL's memory space must be released.

The application can then call the exported functions of the DLL.
At this time, DLL functions are executed using the application stack.
However, threads and mutexes created in the DLL are placed in the DLL's dedicated memory space, not the application's memory.
Threads and mutexes are automatically released by the OS when the application exits. However, DLL threads and mutexes are not automatically released when the application exits because DLLs may be loaded by multiple applications.
The threads and mutexes of the DLL must be released by calling the DLL's exported functions because the OS does not automatically release them.

So you have to call the exported function of the DLL that calls `spdlog::shutdown()` before `main()` exits.
Forgetting to do so will result in a crash during DLL unloading because resources associated with threads and mutexes have not been freed.

**Comment by stan1334** [comment]
> The reason is simple: the resources present in the DLL's memory space must be released.
> 
> The application can then call the exported functions of the DLL. At this time, DLL functions are executed using the application stack. However, threads and mutexes created in the DLL are placed in the DLL's dedicated memory space, not the application's memory. Threads and mutexes are automatically released by the OS when the application exits. However, DLL threads and mutexes are not automatically released when the application exits because DLLs may be loaded by multiple applications. The threads and mutexes of the DLL must be released by calling the DLL's exported functions because the OS does not automatically release them.
> 
> So you have to call the exported function of the DLL that calls `spdlog::shutdown()` before `main()` exits. Forgetting to do so will result in a crash during DLL unloading because resources associated with threads and mutexes have not been freed.

i know it，bug win10 is ok，process normal exit。I think, win7 and win10 have some differences in the process of program exit

**Comment by artemyv** [comment]
> i know it，bug win10 is ok，process normal exit。I think, win7 and win10 have some differences in the process of program exit

On Win7 std::condition_variable::notify_one has a bug - it does not exits if the thread that has to be notified has already terminated. On Win10 this does not happening.

So WA for Win7 - if you want to log after exiting WinMain and want to delay the calling of shutdown - make sure you stop all spdog threads before exiting WinMain.

For example in our apps we do not use the async loggers - so only thread that is created by spdlog is one doing periodic flush.
We disable periodic flush before exiting WinMain - as a result shutdown (called later) does not find any working threads to be stopped - so notify_one is skipped and application does not stuck on exit

**Comment by stan1334** [comment]
> On Win7 std::condition_variable::notify_one has a bug - it does not exits if the thread that has to be notified has already terminated. On Win10 this does not happening.

The core principle of the exit of win7 and win10 is probably difficult to explain, very turbid.
