### ISSUE TITLE
Using the __FILE__ and __FUNCTION__ and __LINE__ Macro

### ISSUE THREAD

**Issue by hjclub123** [gabime/spdlog#241]
We are using spdlog and like spdlog.

By the way,

is not compile In 139 line of spdlog/spdlog.h
→  #define SPDLOG_TRACE(logger, ...)  logger->trace(__FILE__ ## " line " ## SPDLOG_STR(__LINE__) ## ": " ## __VA_ARGS__);

Using c++ example is as follows:
------------------------------------------------------------
#define SPDLOG_TRACE_ON
#include "spdlog/spdlog.h"

int main(int, char* [])
{
    spdlog::set_level(spdlog::level::trace);
    auto console = spdlog::stdout_logger_mt("console", true);
    console->info("Welcome to spdlog!");

    SPDLOG_TRACE(console, "Some debug message {} {}", 1, 3.2);

    return 0;
}
------------------------------------------------------------
spdlog/spdlog.h:139:50: error: pasting "__FILE__" and "" line "" does not give a valid preprocessing token
 #define SPDLOG_TRACE(logger, ...)  logger->trace(__FILE__ ## " line " ## SPDLOG_STR(__LINE__) ## ": " ## __VA_ARGS__);
------------------------------------------------------------

The development environment:

CentOS 7
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
c++11

I also want to use the __FUNTION__ Macro
How should I do?

**Comment by gabime** [comment]
where are the underscores around them ? (should be __FILE__ not FILE)

**Comment by gabime** [comment]
Fixed in https://github.com/gabime/spdlog/commit/e5032c8db53debb669243a01e8f267f3e390650a

**Comment by hjclub123** [comment]
Thank you!

Can use a __FUNCTION__ Macro?

**Comment by gabime** [comment]
Maybe. Try it
