### ISSUE TITLE
Timezone out of sync

### ISSUE THREAD

**Issue by paxifaer** [gabime/spdlog#2410]
my code is `LOGGER->set_pattern("[%H:%M:%S:%e%z %[%L%$ %t] %v");`
the result is 
![image](https://user-images.githubusercontent.com/51481718/174542780-de65ff24-696f-483b-96a8-c12f231e35dc.png)
Actually,now my time is 14:53:28:509.The time in my region is eight hours ahead of the log.
What can I do?

**Comment by tt4g** [comment]
If the application is run before the time zone is reflected in the system, the log time will not reflect the time zone.
If you are on a Linux OS, make sure the `TZ` environment variable is set when the application is started.

**Comment by paxifaer** [comment]
What you said inspired me, the program is running in docker. So the time zone setting is wrong. I added the command to set the time zone in the DockerFile, and the log time corresponds to it. Thanks!
