### ISSUE TITLE
enabling throwing exception for  crtitical error only

### ISSUE THREAD

**Issue by Jaberh** [gabime/spdlog#2412]
I would like  the logger only throw exception for the crtitical part. 
Can you please take a look; Here is the snippet of the code 

   auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
   std::vector<spdlog::sink_ptr> sinks{console_sink};
   auto log = std::make_shared<spdlog::logger>("mylog", sinks.begin(), sinks.end());
   log->set_level(spdlog::level::trace);
   log->flush_on(spdlog::level::trace);
  // this is suggested by the manual 
   log->set_error_handler([](const std::string& msg) { throw std::runtime_error(msg); });
   spdlog::register_logger(log);
   spdlog::get("mylog")->critical("fatal error");

   however, when I run this no exception is thrown and the code runs to completion!  
    
 Thanks for your help

**Comment by tt4g** [comment]
I think that the error is reported with `spdlog::logger::critical()` when an error occurred.

If you want to make the operation work the way you want it to, create a custom sink that throw error from inside `spdlog`.
See: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

Example:

```cpp
#include "spdlog/sinks/base_sink.h"
#include "spdlog/details/null_mutex.h"
#include <mutex>
#include <stdexcept>

template<typename Mutex>
class report_critical_sink: public spdlog::sinks::base_sink <Mutex>
{

// Initialization code here ...

protected:
    void sink_it_(const spdlog::details::log_msg& msg) override
    {
        if (msg.level!= spdlog::level::critical) {
            return;
        }

        spdlog::memory_buf_t formatted;
        spdlog::sinks::base_sink<Mutex>::formatter_->format(msg, formatted);
        throw std::runtime_error(fmt::to_string(formatted));
    }

    void flush_() override 
    {
    }

    void set_pattern_(const std::string &pattern) override
    {
    }

    void set_formatter_(std::unique_ptr<spdlog::formatter> sink_formatter) override
    {
    }

};

using report_critical_sink_mt = report_critical_sink<std::mutex>;
using report_critical_sink_st = report_critical_sink<spdlog::details::null_mutex>;
```

**Comment by Jaberh** [comment]
Thanks for the info, that is the base sink and hence does lose all the colors when I use it that way, 
I think a simpler approach is just to wrap the spdlog::get(mylogger)->critical call 
in a class method and call throw after that for now.

**Comment by tt4g** [comment]
> throw after that for now.

That is the simplest way.
It is easier to use a macro that executes `spdlog::get(mylogger)->critical()` and `throw` together than to `throw` from inside spdlog.

**Comment by Jaberh** [comment]
yes, agree, thanks for the help,
