### ISSUE TITLE
What are the default rules of outputting doubles?

### ISSUE THREAD

**Issue by sashagsr** [gabime/spdlog#2413]
The output is confusing and looks inconsistent. Code snippet:
````
const double d = 32567.17;
const double d1 = 123.4354;
const double d2 = 1234.123;
const double d3 = 32567.12345678901234;
const double d4 = 12.235;
const double d5 = 12.236;
const double d6 = 123456.123456;
const double d7 = 12345678.12345678;
spdlog::info("{} {} {} {} {} {} {} {}", d, d1, d2, d3, d4, d5, d6, d7);
````
Produces the following output:
````
[2022-06-22 15:03:48.777] [info] 32567.2 123.435 1234.12 32567.1 12.235 12.236 123456. 1.23457e+07
````
The first value is rounded, the second is truncated, the second from the end has no decimals outputted.
Version is: SPDLOG_VERSION 1.4.2 with internal fmt

**Comment by tt4g** [comment]
This is fmt library specification. If it is a spec question, please move the issue to the fmt project.

Looking at the fmt test code, floating point is processed in the `g` format when there is no format specifier.

https://github.com/fmtlib/fmt/blob/b6f4ceaed0a0a24ccf575fab6c56dd50ccf6f1a9/test/format-test.cc#L1236-L1240

See fmt API documentation: https://fmt.dev/latest/syntax.html#format-specification-mini-language
