### ISSUE TITLE
Calling from plain C

### ISSUE THREAD

**Issue by mcondarelli** [gabime/spdlog#2414]
Hi,
I have a large project in C++ i want to convert to use `spdlog`.
Problem is I have a few Plain-C functions that need to log errors (if and when, of course).
I would hate to use a different solution for a handful of printouts.
I can live with severely crippled `spdlog` (i.e.: no formatting and just a couple of levels) for those.
What can I do?

**Comment by gabime** [comment]
The easiest would be to develop a simple  C layer that accepts const char*


Something like

`spdlog_4c.h:`

``` cpp

#ifdef __cplusplus
extern "C" {
#endif

void spdlog_init(); 
void spdlog_trace(const char* message);
void spdlog_debug(const char* message);
void spdlog_info(const char* message);
void spdlog_error(const char* message);
void spdlog_critical(const char* message);

#ifdef __cplusplus
}
#endif

```

`spdlog_4c.cpp`:

```c++
void spdlog_init()
{
   /* init spdlog default logger if required (e.g. to file instead stdout)
    * for example
    *   auto file_logger = spdlog::basic_logger_mt("file_logger", "log.txt");
    *   spdlog::set_default_logger(file_logger);
    */
 
}

void spdlog_info(const char* message)
{
   spdlog::info(message);
}

void spdlog_warn(const char* message)
{
   spdlog::warn(message);
}
...
```

**Comment by mcondarelli** [comment]
Thanks.
I don't think `spdlog_init()` is needed as I already do something like that in C++and I only use `default_logger` afterwards.
Calling a C layer makes good sense,
Many Thanks!
