### ISSUE TITLE
Encoding Assumptions

### ISSUE THREAD

**Issue by igoloe** [gabime/spdlog#2416]
Hi,
I'd like to clarify assumptions spdlog makes about encoding and what the future of charN_t Support.

I know spdlog currently targets C++11, but its 2022 and C++20 is getting more and more common.

fmt
As far as i can deduce the choice of fmt implies encoding agnostic behavior at the frontend. Writing to sinks from a memory buffer means holistic encoding from the frontend in the backend sinks.

This is what couples client encoding at the frontend to the backend. You need to know your sink or you produce mojibake.

Motivation
What may not be of importance in new modern c++ linux based systems, is a mess in windows systems with legacy parts.

Question
1. Are there any plans to transcode to utf8 before forwarding to sinks. Or provide a transcoding customization point .. 
2. This would also allow to unify all charN_t to utf8 an interpret char* like on windows as acp and under linux as utf8.

A customization point may "easily" be provided, including charN_t overloads for log adaption to fmt.

Note: wchar_t is not an option. Its just another mess.

Regards. Ilo

**Comment by tt4g** [comment]
IMO.

As far as I know, there is no standard feature specified in C/C++ to do character encoding conversion and the character encoding of `char *` is also not specified (historically, many C/C++ APIs assume that `char *` is a string compatible with ASCII code.). Therefore, spdlog does not provide the ability to guarantee output character encoding.

So, if the `char *` passed to spdlog is compatible with ASCII codes, spdlog should work.
And If you want to convert the character encoding of the log messages output by spdlog, you can create a custom sink at your own risk (wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink).

**Comment by igoloe** [comment]
Thanks for your answer.

Maybe the motivation is not defined unambious:
I am currently evaluating different logging frameworks for their capability to deal with unicode in a portable and safe way, especially mixing all char types. The goal is to draft and move to such a logging framework as a prerequisite to support unicode along all included processes of a system.

Encoding Guarantees
At least guaranteed is the execution-charset, which is under windows without explicitliy specifying it the active codepage acp and depends on the region.

We nail that to be long assumed ansi/latin1, so unspecified behavior gets specified and is compatible to legacy apis. Therfore char* is well known.

Under linux char* defaults to utf8 ... if not specified different. But I am not an expert for linux intrinsics.

wchar_t* under windows to utf16, and the new charN_t* to utf8, 16 and 32 for any os.

So encoding is well known and can be determined from the format string char type passed to fmt or its string result type produced.

Customization
Thus after applying fmt it is easily possible to plugin transcoding before passing to sinks.

This would be the customization point. By default nothing happens and spdlog holistic behavior is preserved. If overload the client code can do whatever it likes to, especially transcoding.

Sinks should be completly unaware of the encoding - as currently. Ofc it would not make sense for all sinks to consume utf8, but the situation is not different to now.

Regards. Ilo.

**Comment by gabime** [comment]
Under windows only, you can define `SPDLOG_WCHAR_TO_UTF8_SUPPORT`.
This will make spdlog convert wchar inputs to utf8 before forwarding to the sinks.

**Comment by igoloe** [comment]
Thx.

Would a PR be appreciated to add support for charN_t and transcoding to utf8 depending on feature test macros and/or spdlog specific defines?

Same question for char* under windows.

Something like
```cpp
// if enabled transcodes any char seq to utf8
// before forwarding to sinks. 
// Transcoding is done in respect to active codepage.
SPDLOG_CHAR_TO_UTF8_SUPPORT
```

```cpp
Transcodes any charN_t to utf8 before forwarding to sinks.
SPDLOG_CHAR16T_TO_UTF8_SUPPORT
SPDLOG_CHAR32T_TO_UTF8_SUPPORT
```

Simplification: Policy driven
1. Leave as is
2. Transcode to charN_t

Its just a more convenient but less flexible way than to use customization via overloads.

**Comment by gabime** [comment]
Thanks for the suggestion. However, the current SPDLOG_WCHAR_TO_UTF8_SUPPORT feature is already complicating codebase significantly. I would rather not to add even more char conversions.
