### ISSUE TITLE
Is this possible to write log with multithreaded environment ?

### ISSUE THREAD

**Issue by kevinemk** [gabime/spdlog#242]
```
auto logger = spd::rotating_logger_mt(((const char*)program), (const char*)fileName, 1048576 * 4, 100000);	
logger->log(spdlog::level::info, (const char*)asc);
spdlog::drop_all();	
```
I created function including above code and try to run:
```
thread t(Do);
t.join();
thread x(Do);
t.join();
```
I'll try this code with multi thread environment and then get error.

> Unhandled exception at 0x750EDAE8 in LogTester.exe: Microsoft C++ exception: std::system_error at memory location 0x0088FBB0.

**Comment by gabime** [comment]
You have a bug -  you call ```t.join()``` twice (instead of calling ```x.join()``` in the last line )
