### ISSUE TITLE
Include Error: function "Chord" is not the name of a C/C++ type (757)

### ISSUE THREAD

**Issue by nyckmaia** [gabime/spdlog#2423]
Hi, I have a include problem between `spdlog` and my current project files.

My install steps were: 

1- Downloaded and included the `spdlog` folder into my `CMakeLists.txt`
2- Opened a source code file and added `#include <spdlog/spdlog.h>`

I'm using `VS Code`, and when I `CTRL+click` in the `#include <spdlog/spdlog.h>` I checked that it was correctly installed in my project.

The Problem
---------------
Just with these 2 steps above, both `VS Code` and `g++` are saying that I have a problem with my custom type `Chord`

When I added the line `#include <spdlog/spdlog.h>`, the `VS Code` shows:
```
function "Chord" is not the name of a C/C++ type (757)
```
![image](https://user-images.githubusercontent.com/4555404/177220638-5a878929-52be-46b7-925d-2455fe23ac5f.png)

If I just comment the line `#include <spdlog/spdlog.h>` **this error do not appear and my project compiles without any warning or error.**

This type-error generates another errors on my fuctions/methods that uses the type `Chord`.
Error example:
```
score.cpp:2493:28: note:   expected a type, got 'Chord'
score.cpp:2493:33: error: template argument 1 is invalid
 2493 | std::vector<std::pair<int, Chord>> Score::getChords(nlohmann::json config)
```

Questions
-----------
1- What is the relation between the `spdlog` and my custom type `Chord`?
2- How can I fix it?

Thank you

**Comment by tt4g** [comment]
> 1- What is the relation between the spdlog and my custom type Chord?
> 2- How can I fix it?

spdlog does not define `Chord`.

In my experience, when I encounter problems with header file inclusion, the cause is often not the header file.

For example.
If there is a statement in the spdlog header file that your compiler does not recognize, it may interpret the rest of the statement unexpectedly without a statement error.
In this case, the compiler reports a warning message, and often the warning is simply missed.

I recommend that you carefully check the compile-time messages and your own source code once.

**Comment by nyckmaia** [comment]
Thank you @tt4g ,

UPDATE 01
=======

I tested my code on 2 environments: `Windows` and `Linux`
In the `Linux` OS all works great without any warnings or erros even with `#include <spdlog/spdlog.h>` line.
So my `Chord` type problem is only on `Windows` environment, ok?

On Windows Environment
------------------------------

On Windows, if I just comment the single `#include <spdlog/spdlog.h>` line, my code compiles without any errors or warnings, even with `-Wall -Wextra`. No warnings at all!

When I add the `#include <spdlog/spdlog.h>` line in a single file, the `VS Code` "internal reference" of my type `Chord` changes and go to another file, outside my project, that defines `Chord` as a function.

The 2 different behaviors on Windows System
---------------------------------------------------

**Behravior 01:**

My current code (correct reference to the `Chord` type) is:
![image](https://user-images.githubusercontent.com/4555404/177343688-9702b36d-b38b-44bb-8a05-39c462d581e7.png)
![image](https://user-images.githubusercontent.com/4555404/177343975-f2391c3b-f853-4afd-b7ff-38b6466de874.png)

**Behravior 02:**
If I add the `#include <spdlog/spdlog.h>`, the `VS Code` "internal reference" point to this external Windows file:
![image](https://user-images.githubusercontent.com/4555404/177343031-a2a64dc2-95b3-4026-9794-18f79e4aca59.png)

![image](https://user-images.githubusercontent.com/4555404/177342948-e035aa66-aa52-4695-ad5c-8282f2444f18.png)

**Question:**
Is there a way to fix this wrong behravior on Windows environment?

Thanks,

**My Linux System**
- OS: Ubuntu 20.04 LTS (Running on WSL 2)
- g++ 9.3.0

**My Windows System**
- OS: Windows 10
- g++ 10.3.0 (MSYS 2)

**Comment by tt4g** [comment]
Ah, unfortunately it seems that `Chord` function is defined in the Windows API (spdlog includes OS API with `#include <windows.h>` on Windows).
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-chord

Basically, when there is a name conflict with the OS API in C, the only way is to change the function name.

> **TIP**
> Many libraries add a library name prefix to function names to avoid conflicts.

In C++, the `namespace` feature is used to avoid name conflicts with the C/C++ API.

**Comment by nyckmaia** [comment]
Ok! Thank you!
