### ISSUE TITLE
How to cross-compile on Linux using the ARM compiler？

### ISSUE THREAD

**Issue by jianjianliu0918** [gabime/spdlog#2425]
HI，
 I want to use the ARM compiler to cross-compile to generate static lib on Ubuntu 20.04.
I tried to add the following statement to the CMAKELIST.

set(CMAKE_C_COMPILER "/opt/Sourcery_CodeBench_Lite_for_Xilinx_GNU_Linux/bin/arm-xilinx-linux-gnueabi-gcc")
set(CMAKE_CXX_COMPILER "/opt/Sourcery_CodeBench_Lite_for_Xilinx_GNU_Linux/bin/arm-xilinx-linux-gnueabi-g++")

But the following error occurred:

-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 2.0.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Build type: Release
-- Generating example(s)
-- Generating install
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++

How should I use ARM compiler to generate static lib?
Thanks!!

**Comment by tt4g** [comment]
What is the error?
The CMake configuration step appears to have completed successfully.

**Comment by jianjianliu0918** [comment]
> What is the error? The CMake configuration step appears to have completed successfully.

Thank you for your reply, the error is that the compilation process enters an infinite loop. 
The more detailed output 
ljj@ljj-gnu:~/workarea/spdlog-2.x/build$ cmake ..
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 2.0.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Build type: Release
-- Generating example(s)
-- Generating install
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++

-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 2.0.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Build type: Release
-- Generating example(s)
-- Generating install
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++

... and enters an infinite loop.

**Comment by tt4g** [comment]
This is the CMake problem.
See same issue
- https://stackoverflow.com/questions/18347726/why-does-cmake-refuse-to-use-a-non-default-compiler
- https://stackoverflow.com/questions/32306648/changing-compiler-with-cmake-creates-infinite-loop

**Comment by tt4g** [comment]
See also: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html

**Comment by jianjianliu0918** [comment]
> This is the CMake problem. See same issue
> 
> * https://stackoverflow.com/questions/18347726/why-does-cmake-refuse-to-use-a-non-default-compiler
> * https://stackoverflow.com/questions/32306648/changing-compiler-with-cmake-creates-infinite-loop

I modified CMakelist and add the following

set(tools /opt/Sourcery_CodeBench_Lite_for_Xilinx_GNU_Linux)
set(CMAKE_C_COMPILER ${tools}/bin/arm-xilinx-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/arm-xilinx-linux-gnueabi-g++)

"cmake " is done, but some errors occurs with "make -j"

cmake ..
-- The CXX compiler identification is GNU 4.7.2
-- Check for working CXX compiler: /opt/Sourcery_CodeBench_Lite_for_Xilinx_GNU_Linux/bin/arm-xilinx-linux-gnueabi-g++
-- Check for working CXX compiler: /opt/Sourcery_CodeBench_Lite_for_Xilinx_GNU_Linux/bin/arm-xilinx-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.10.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Build type: Release
-- Generating example(s)
-- Generating install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ljj/workarea/spdlog/build
ljj@ljj-gnu:~/workarea/spdlog/build$ make -j
Scanning dependencies of target spdlog
[ 20%] Building CXX object CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
[ 40%] Building CXX object CMakeFiles/spdlog.dir/src/color_sinks.cpp.o
[ 20%] Building CXX object CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
[ 40%] Building CXX object CMakeFiles/spdlog.dir/src/spdlog.cpp.o
[ 70%] Building CXX object CMakeFiles/spdlog.dir/src/fmt.cpp.o
[ 70%] Building CXX object CMakeFiles/spdlog.dir/src/async.cpp.o
[ 70%] Building CXX object CMakeFiles/spdlog.dir/src/cfg.cpp.o
In file included from /home/ljj/workarea/spdlog/include/spdlog/fmt/fmt.h:24:0,
                 from /home/ljj/workarea/spdlog/include/spdlog/common.h:45,
                 from /home/ljj/workarea/spdlog/include/spdlog/logger.h:17,
                 from /home/ljj/workarea/spdlog/include/spdlog/async_logger.h:17,
                 from /home/ljj/workarea/spdlog/include/spdlog/async.h:17,
                 from /home/ljj/workarea/spdlog/src/color_sinks.cpp:11:
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h:1515:58: error: 'std::back_insert_iterator<fmt::v8::detail::buffer<char> >::back_insert_iterator' names constructor
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h:2739:25: error: bit-field 'format' with non-integral type
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h: In function 'fmt::v8::detail::float_specs fmt::v8::detail::parse_float_type_spec(const fmt::v8::basic_format_specs<Char>&, ErrorHandler&&)':
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h:2757:12: error: 'struct fmt::v8::detail::float_specs' has no member named 'format'
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h:2763:12: error: 'struct fmt::v8::detail::float_specs' has no member named 'format'
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h:2769:12: error: 'struct fmt::v8::detail::float_specs' has no member named 'format'
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h:2776:12: error: 'struct fmt::v8::detail::float_specs' has no member named 'format'
/home/ljj/workarea/spdlog/include/spdlog/fmt/bundled/core.h:2783:12: error: 'struct fmt::v8::detail::float_specs' has no member named 'format'
In file included from /home/ljj/workarea/spdlog/include/spdlog/fmt/fmt.h:25:0,
                 from /home/ljj/workarea/spdlog/include/spdlog/common.h:45,
                 from /home/ljj/workarea/spdlog/include/spdlog/logger.h:17,
                 from /home/ljj/workarea/spdlog/include/spdlog/async_logger.h:17,
                 from /home/ljj/workarea/spdlog/include/spdlog/async.h:17,


I checked the compiler version:
ljj@ljj-gnu:~$ /opt/Sourcery_CodeBench_Lite_for_Xilinx_GNU_Linux/bin/arm-xilinx-linux-gnueabi-gcc --version
arm-xilinx-linux-gnueabi-gcc (Sourcery CodeBench Lite 2012.09-104) 4.7.2

Is it possible that the compiler version is too old to cause these error?

Thanks again!

**Comment by tt4g** [comment]
This is gcc 4.7.x bug.

See:
- https://stackoverflow.com/questions/44295575/names-the-constructor-not-the-type-in-g-4-4-7
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=11764

**Comment by jianjianliu0918** [comment]
> This is gcc 4.7.x bug.
> 
> See:
> 
> * https://stackoverflow.com/questions/44295575/names-the-constructor-not-the-type-in-g-4-4-7
> * https://gcc.gnu.org/bugzilla/show_bug.cgi?id=11764

I changed the compiler version and have compiled it.  Version details:

ljj@ljj-gnu:/opt/arm_xilinx_linux_gnueabi-master/bin$ ./arm-xilinx-linux-gnueabi-gcc --version
arm-xilinx-linux-gnueabi-gcc (Sourcery CodeBench Lite 2015.05-17) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
