### ISSUE TITLE
Question: Multiple sinks with the same output file - order

### ISSUE THREAD

**Issue by macszur-mob** [gabime/spdlog#243]
Hi all !
First of all -> spdlog is just awsome tool ! @gabime huge thanks for doing it ;)

During development I'm creating multiple file loggers(based on simple_file_sink_mt) but all of them have the same output file. I've noticed that logs order is really weird after my app ends. If I enable force flushing everything is fine. After a bit of digging and experimenting situation became quite obvious to me -> all of them opens the same file getting different file descriptors, each logger has a bit different time of calling destructor thus moment of closing each file descriptors is slightly different (and in fact, later I've noticed that these logs are always in the same "weird" order). So my question is there any other way of ensuring logs order between multiple loggers sharing the same file then force flush? Or should I implement my own sink with one of these options : 

- shared among all sinks logs queue which will do final write in destructor 
- use setvbuf in some tricky way
- share one file descriptor

For now force flush is enough but I'm wondering is there better/more performant solution embedded into spdlog ;)

p.s. My os is OS X 10.11.5, clang version 
```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
```

**Comment by gabime** [comment]
@macszur-mob Thanks for the nice feedback :+1: 

If you want multiple loggers to share the same file, they **must** share the same sink. Otherwise, bad things will happen as you have noticed.

Example:
```c++

auto file_sink = std::make_shared<spdlog::sinks::simple_file_sink_mt>("filename.log");
auto logger1 = std::make_shared<spdlog::logger>("somename1", file_sink );
auto logger2 = std::make_shared<spdlog::logger>("somename2", sfile_sink nk);
auto logger3 = std::make_shared<spdlog::logger>("somename3", file_sink );

``` 
Please refer to the [wiki docs](https://github.com/gabime/spdlog/wiki/4.-Sinksl) for more info

>

**Comment by macszur-mob** [comment]
Ahhh, yes, your solution is much simpler and better ;) thanks !

btw. maybe this info could be useful to somebody else, what about putting it into wiki docs ?

**Comment by gabime** [comment]
I will be happy to get contributions to the wiki. could you please add a section that clarifies this?

**Comment by macszur-mob** [comment]
yes, sure 👍 I'll prepare it tomorrow :)
