### ISSUE TITLE
"the value of 'm' is not usable in a constant expression" When Invoking Logging Function

### ISSUE THREAD

**Issue by limitedAtonement** [gabime/spdlog#2430]
This looks something like #2142. The reproduction instructions are nearly identical (with only the version of spdlog being different):

main.cpp:

```cpp
#include "spdlog/spdlog.h"
std::shared_ptr<spdlog::logger> logger;
int main(int, char const **)
{
    std::string m{"{:06d}"};
    logger->info(m, 1);
    return 0;
}
```

build:

```bash
#!/bin/bash

set -ex;
g++ --version;
if [[ ! -d obj ]]; then mkdir obj; fi;
g++ -c -Wall -Wextra -pedantic -std=c++20 -O3 -DNDEBUG -MMD -Ispdlog/include main.cpp -o obj/main.o;
```

and of course a recent tag of spdlog retrieved by doing:

```bash
git clone https://github.com/gabime/spdlog;
cd spdlog;
git co v1.10.0;
cd ..;
```

The output is:

```
+ g++ --version
g++ (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ [[ ! -d obj ]]
+ g++ -c -Wall -Wextra -pedantic -std=c++20 -O3 -DNDEBUG -MMD -Ispdlog/include main.cpp -o obj/main.o
main.cpp: In function 'int main(int, const char**)':
main.cpp:6:17:   in 'constexpr' expansion of 'fmt::v8::basic_format_string<char, int>(m)'
spdlog/include/spdlog/fmt/bundled/core.h:3057:62:   in 'constexpr' expansion of '((fmt::v8::basic_format_string<char, int>*)this)->fmt::v8::basic_format_string<char, int>::str_.fmt::v8::basic_string_view<char>::basic_string_view<std::char_traits<char>, std::allocator<char> >((* & s))'
spdlog/include/spdlog/fmt/bundled/core.h:483:21:   in 'constexpr' expansion of '(& s)->std::__cxx11::basic_string<char>::data()'
/usr/include/c++/12.1.0/bits/basic_string.h:2568:23:   in 'constexpr' expansion of '((const std::__cxx11::basic_string<char>*)this)->std::__cxx11::basic_string<char>::_M_data()'
main.cpp:6:17: error: the value of 'm' is not usable in a constant expression
    6 |     logger->info(m, 1);
      |     ~~~~~~~~~~~~^~~~~~
main.cpp:5:17: note: 'm' was not declared 'constexpr'
    5 |     std::string m{"{:06d}"};
      |                 ^

**Comment by tt4g** [comment]
It appears to be a problem with the fmt library or the clang compiler (fmtlib/fmt#2455).
Does this workaround fmtlib/fmt#2438 not work?

**Comment by limitedAtonement** [comment]
> It appears to be a problem with the fmt library or the clang compiler

As a reminder, I'm using gcc. 

> Does this workaround fmtlib/fmt#2438 not work?

I spent a while looking at fmtlib/fmt#2455 accidentally and found that downgrading to std c++17 and removing all C++20 features from my code does work around the issue.

Adding `fmt::runtime` does work. So changing my example to `logger->info(fmt::runtime(m), 1);` doesn't show the error.

Googling the issue, at https://fmt.dev/dev/api.html, I see

> fmt is a format string that contains literal text and replacement fields surrounded by braces {}. The fields are replaced with formatted arguments in the resulting string. format_string is a format string which can be implicitly constructed from a string literal or a constexpr string and is checked at compile time in C++20. To pass a runtime format string wrap it in `fmt::runtime()`.

So it looks like what I was doing (passing a non-`constexpr` `std::string`) is explicitly not supported by the fmt library, and thus by spdlog. Maybe spdlog could carefully construct overloads for non-`constexpr` and do the `fmt::runtime()` wrapping there. Thank you for your help!
