### ISSUE TITLE
shadows if internal variables

### ISSUE THREAD

**Issue by MohammadKanan** [gabime/spdlog#2431]
When I #include "spdlog/sinks/dist_sink.h"
I get compilation error
spdlog/include/spdlog/sinks/dist_sink.h:58: error: declaration of ‘sink’ shadows a member of ‘spdlog::sinks::dist_sink<std::mutex>’ [-Werror=shadow]
In file included from 
nclude/spdlog/sinks/dist_sink.h: In instantiation of ‘void spdlog::sinks::dist_sink<Mutex>::sink_it_(const spdlog::details::log_msg&) [with Mutex = std::mutex]’:
spdlog/include/spdlog/sinks/dist_sink.h:58:10:   required from here
spdlog/sinks/dist_sink.h:60:9: error: declaration of ‘sink’ shadows a member of ‘spdlog::sinks::dist_sink<std::mutex>’ [-Werror=shadow]
   60 |         for (auto &sink : sinks_)
      |         ^~~

**Comment by tt4g** [comment]
PR is welcome.

**Comment by MohammadKanan** [comment]
> PR is welcome.
Shortly ..
