### ISSUE TITLE
error: call of overloaded ‘make_shared<spdlog::sinks::rotating_file_sink_mt>(const char [12], std::string&, int, int, bool)’ is ambiguous

### ISSUE THREAD

**Issue by IaroslavS** [gabime/spdlog#2432]
Hi !
Cannot compile when creating sink for rotating file logger:

`auto file_logger = spdlog::rotating_logger_mt("file_logger", "logs/mylogfile", 1048576 * 5, 3);`

```
error: call of overloaded ‘make_shared<spdlog::sinks::rotating_file_sink_mt>(const char [12], std::string&, int, int, bool)’ is ambiguous 
auto file_sink = make_shared<spdlog::sinks::rotating_file_sink_mt> ("file_logger", log_filename, 1024*1024*50, 1, false);
```

What's wrong ? Thanks in advance

**Comment by tt4g** [comment]
I don't know anything about it due to the little information provided.
And furthermore, the code in the comment is different from the code that appears in the error message. Which is the code at issue?

**Comment by tt4g** [comment]
Ah, a common cause of ambiguity in symbol resolution is situations where you are declaring `using namespace std` or `using namespace boost`.
If this is the cause, try to specify the full namespace, like `std::make_shared`.

**Comment by IaroslavS** [comment]
Sorry, The provided code really doesn't correspond to the provided error. I'm closing this issue and maybe open a new one with correct code and error if there will be any.
