### ISSUE TITLE
stopwatch.h problem since updating v1.10.0

### ISSUE THREAD

**Issue by fabianbuettner** [gabime/spdlog#2434]
Hi,

after updating the spdlog module in my project to v1.10.0 I noticed the following compilation error:
`
spdlog/include/spdlog/stopwatch.h:30:24: error: ‘chrono’ in namespace ‘std’ does not name a type
   30 |     using clock = std::chrono::steady_clock;
`

I can workaround that by including chrono before including stopwatch.h, but I am not sure if this is the expected behavior.

best regards,
Fabian

**Comment by gabime** [comment]
Thanks for reporting. Indeed seems the include for chrono is missing in stopwatch.h

**Comment by fabianbuettner** [comment]
No problem. do you want me to create a pull request for it?

**Comment by gabime** [comment]
Sure. Please do.
