### ISSUE TITLE
segmentation fault in `spdlog::details::registry::~registry()` when linking a library that links spdlog statically.

### ISSUE THREAD

**Issue by rob-p** [gabime/spdlog#2436]
First; thanks for the awesome library! We use it in several different projects.  Currently, I'm attempting to do something I've not done before, which is to use `rust` to call out to a C API to do some processing.  Everything there works fine and the results are as expected.  However, I noticed that when I change the default log level to `warn` (i.e. a "quiet" mode of execution for the program), the process segfaults as the main function returns.  The stack trace isn't particularly informative:

```
0x00005555558d46fc in spdlog::details::registry::~registry() ()
(gdb) bt
#0  0x00005555558d46fc in spdlog::details::registry::~registry() ()
#1  0x00007ffff7a4a8a7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7a4aa60 in exit () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff7a2808a in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00005555555ab72e in _start ()
(gdb)
```

but it does suggest that the segfault is coming from the spdlog registry destructor.  I imagine this may have something to do with he static storage (is that still used?) for the registry and the way that interacts with static linking, perhaps across extern function call boundaries?  Regardless, the strange part to me is that this works fine with the default log levels.  Well, perhaps I shouldn't say works fine, because this is C++ and who knows what might be happening without an visible segfault, but the logs are printed properly and everything seems to be working correctly.  So, it's only when I set the default log level differently that this behavior manifests.  Any idea what might be going on or how to fix it?

Thanks!
Rob

**Comment by gabime** [comment]
Thanks for the nice feedback! I am glad you find it useful.

I guess that when you set the log level a new registry instance is created in a different  static storage. This [link](https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs#problem) might help.

**Comment by rob-p** [comment]
Thanks!  So what I ended up doing was replacing the default logger (since that was also giving me issues) with a standard stdout, color, mt logger.  As long as I set the level on the created logger *before* I register this as the new default logger, the segfault seems to go away.  Thanks for the explanation!  Since this seems resolved by this solution, I'll close this for the time being.
