### ISSUE TITLE
Incompatible with libfmt 9.0

### ISSUE THREAD

**Issue by smessmer** [gabime/spdlog#2437]
It seems spdlog doesn't build on debian systems with libfmt 9.0.

see https://github.com/cryfs/cryfs/issues/432
and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014684

**Comment by tt4g** [comment]
From reading the error message, it looks like the `boost::filesystem::path` formatter is not provided. I don't think spdlog is the cause.
fmt issue: fmtlib/fmt#2778

**Comment by smessmer** [comment]
Oh, interesting. I had missed this. Thanks.
