### ISSUE TITLE
Request: support VS2012

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [gabime/spdlog#244]
initializer lists and variadic templates were shipped with VS2012 ctp compiler, but are not part of the std library. Any possibility, you'd support VS 2012 ?

**Comment by gabime** [comment]
what would it take to support variadic tpls?

**Comment by AbsolutelyFreeWeb** [comment]
I'm not that familiar with c++11 but at least simple variadic templates compile fine. Below is an example using both variadic templates as well as initializer list which compiles after having installed the CTP com
[vserrors.txt](https://github.com/gabime/spdlog/files/368016/vserrors.txt)
piler and run  

```
"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat" x86
set PATH=C:\Program Files (x86)\Microsoft Visual C++ Compiler Nov 2012 CTP\bin;%PATH%
set INCLUDE=C:\Program Files (x86)\Microsoft Visual C++ Compiler Nov 2012 CTP\include;%INCLUDE%
```

the example
```
template<typename T>
T adder(T v) {
	return v;
}

template<typename T, typename... Args>
T adder(T first, Args... args) {
	return first + adder(args...);
}

int _tmain(int argc, _TCHAR* argv[])
{
	auto a = { 0 };
	long sum = adder(1, 2, 3, 8, 7);
	std::cout << sum << std::endl;
	return 0;
}
```
However, you get a long list of errors trying to compile spdlog, I'm attaching a file with all the errors your project gives. I see same a lot of recurring errors, default functions, "using" aliases..

**Comment by gabime** [comment]
sorry. too much changes would be needed
