### ISSUE TITLE
Is it possible to rename the spdlog worker threads?

### ISSUE THREAD

**Issue by lbckmnn** [gabime/spdlog#2451]
Hi,
First of all: Thanks for the awesome logging library. 
I am using async logging and would like to know if it is possible to give the worker threads a custom name (on linux).

Thanks in advance!

**Comment by tt4g** [comment]
spdlog does not provide API to set thread names.
However, you can add API from this PR #2417.

**Comment by lbckmnn** [comment]
Thanks, 
Yes that should work for me.
