### ISSUE TITLE
linker error when trying to use vcpkg on a aarch64 dynamic library

### ISSUE THREAD

**Issue by eladmaimoni** [gabime/spdlog#2452]
**Host Environment**
- OS: linux x64
- Compiler: gcc 8

I am building a dynamic library using gcc 8, targeting aarch64.
The dynamic library links spdlog as a static library. configured via a vcpkg manifest file.

When building, I get many linker errors that emanate from spdlog:

```
relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN6spdlog5sinks14ansicolor_sinkINS_7details13console_mutexEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
```

I tried solving this by using a custom vcpkg triplet file in addition to my custom toolchain file.
The triplet file is supposed to add the -fPic compiler option to all vcpkg libraries I use.

Here they are for reference.

triplet file - arm64-linux-static.cmake
```
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
string(APPEND CMAKE_C_FLAGS_INIT " -fPIC ${VCPKG_C_FLAGS} ")
string(APPEND CMAKE_CXX_FLAGS_INIT " -fPIC ${VCPKG_CXX_FLAGS}")

if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
    execute_process(COMMAND "uname" "-m" OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_PROCESSOR OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/arm64_linux_toolchain_gcc8.cmake")
```

toolchain file

```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_SYSROOT /media/tlv/usr)

set(tools /usr/bin)
set(CMAKE_C_COMPILER ${tools}/aarch64-linux-gnu-gcc-8)
set(CMAKE_CXX_COMPILER ${tools}/aarch64-linux-gnu-g++-8)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

Is this a bug in the spdlog port? Is there a known workaround?

**Comment by tt4g** [comment]
spdlog does not change the `-fPIC` option.
It is usually set by the developer via the CMake variable `CMAKE_CXX_FLAGS`.

You might want to ask about support for the `-fPIC` option in [vcpkg project](https://github.com/microsoft/vcpkg).

**Comment by tt4g** [comment]
See also #1190.

**Comment by eladmaimoni** [comment]
@tt4g I opened a vcpkg issue as well. but no help so far.

https://github.com/microsoft/vcpkg/issues/25994

I think the problem is the way vcpkg is configured when compiling spdlog for the target triplet.
As far as I know, cmake has the -fPic option on by default when compiling shared libraries. It is also what I see in the compiler output. I also tried to set it manually but it didn't help.
