### ISSUE TITLE
Exception thrown when registering logger On Windows With Visual Studio 2022

### ISSUE THREAD

**Issue by hamzaahmedzia1** [gabime/spdlog#2453]
Host OS 
Windows 11 x64 Professional
IDE 
Visual Studio 2022 Community x64
Package Manager 
vcpkg
Used command `vcpkg install spdlog:x86-windows-static`

Using sdplog in a C++ Win32 dll project 

Setup sink and logger in the following manner

```
std::shared_ptr<spdlog::sinks::basic_file_sink_st> file_sink = std::make_shared<spdlog::sinks::basic_file_sink_st>("filesink.txt",true);
file_sink->set_level(spdlog::level::trace);
file_sink->set_pattern("%^[%Y-%m-%d %H:%M:%S.%e] %v%$");

std::vector<spdlog::sink_ptr> sinks = {file_sink};
std::shared_ptr<spdlog::logger> logger = std::make_shared<spdlog::logger>("default_logger", sinks.begin(),sinks.end());
logger->set_level(spdlog::level::trace);
logger->flush_on(spdlog::level::trace);
spdlog::register_logger(logger);

```

F11 into files led me to this function in spdlog registry-inl.h file thowing exception on  `auto logger_name = new_logger->name();`
**E:\vcpkg\installed\x86-windows-static\include\spdlog\details\registry-inl.h** 
```
SPDLOG_INLINE void registry::register_logger_(std::shared_ptr<logger> new_logger)
{
    auto logger_name = new_logger->name();
    throw_if_exists_(logger_name);
    loggers_[logger_name] = std::move(new_logger);
}

```

The page that opens up is 

**C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\crt\src\i386\memcpy.asm**
with message _Access violation reading location 0x023CC000._

in the following code at   `rep     movsd                           ; move all of our dwords`

```
Dword_align_Ok:
        mov     edx, ecx
        cmp     ecx, 32
        jb      CopyUpDwordMov
        shr     ecx,2
        rep     movsd                           ; move all of our dwords
        and     edx,11b                         ; trailing byte count
        jmp     dword ptr TrailingUpVec[edx*4]  ; process trailing bytes
```

**Comment by tt4g** [comment]
Can you reproduce the problem without using vcpkg? If not reproduce, please move the issue to the [vpckg project](https://github.com/microsoft/vcpkg).

**Comment by hamzaahmedzia1** [comment]
How do I use spdlog on windows with visual studio without vcpkg?

**Comment by hamzaahmedzia1** [comment]
> Can you reproduce the problem without using vcpkg? If not reproduce, please move the issue to the [vpckg project](https://github.com/microsoft/vcpkg).

How do I use spdlog on windows with visual studio without vcpkg?

**Comment by tt4g** [comment]
Just copy the source code from the repository and add `<SPDLOG_SOURCE_ROOT>/include` to the include path, as described in `README.md`.

**Comment by tt4g** [comment]
As a fundamental question, are you using a 32bit library `spdlog:x86-windows-static` in your 64bit project?
It will not work, use 64bit libraries.
See also: https://stackoverflow.com/questions/27956415/mixing-x86-and-x64-static-libs-during-c-compilation

**Comment by hamzaahmedzia1** [comment]
> As a fundamental question, are you using a 32bit library `spdlog:x86-windows-static` in your 64bit project? It will not work, use 64bit libraries. See also: https://stackoverflow.com/questions/27956415/mixing-x86-and-x64-static-libs-during-c-compilation

I am using the x86-windows-static library in a Win32 Dll project. Inside visual studio architecture is set to Win32.

**Comment by hamzaahmedzia1** [comment]
@tt4g I removed vcpkg and added `E:\cpp-libraries\spdlog\include` . 

Sometimes 

1. I get the exact same logger initialization error as described above.

And sometimes

logger is being registered however when I try to write a trace message I have a different exception 

Sequence of files
First in file **E:\cpp-libraries\spdlog\include\spdlog\logger-inl.h** _log_enabled_ is false while _traceback_enabled_ is true so it goes to _tracer_.push_back(log_msg);_ (why is this so). When I initialize a logger shouldn't _log_enabled_ be true?
```

SPDLOG_INLINE void logger::log_it_(const spdlog::details::log_msg &log_msg, bool log_enabled, bool traceback_enabled)
{
    if (log_enabled)
    {
        sink_it_(log_msg);
    }
    if (traceback_enabled)
    {
        tracer_.push_back(log_msg);
    }
}
```

Then In file **E:\cpp-libraries\spdlog\include\spdlog\details\backtracer-inl.h** on _ std::lock_guard<std::mutex> lock{mutex_};_ an exception is thrown 
```
SPDLOG_INLINE void backtracer::push_back(const log_msg &msg)
{
    std::lock_guard<std::mutex> lock{mutex_};
    messages_.push_back(log_msg_buffer{msg});
}
```
Exception in file **C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\crt\src\stl\mutex.cpp**

```
Exception thrown: read access violation.
_Mtx_internal_imp_t::_get_cs(...)-> was nullptr.
```
Function Exception is thrown

```

static int mtx_do_lock(_Mtx_t mtx, const xtime* target) { // lock mutex
    if ((mtx->type & ~_Mtx_recursive) == _Mtx_plain) { // set the lock
        if (mtx->thread_id != static_cast<long>(GetCurrentThreadId())) { // not current thread, do lock
            mtx->_get_cs()->lock();
            mtx->thread_id = static_cast<long>(GetCurrentThreadId());
        }
        ++mtx->count;

        return _Thrd_success;
    } else { // handle timed or recursive mutex
        int res = WAIT_TIMEOUT;
        if (target == nullptr) { // no target --> plain wait (i.e. infinite timeout)
            if (mtx->thread_id != static_cast<long>(GetCurrentThreadId())) {
                mtx->_get_cs()->lock();
            }

            res = WAIT_OBJECT_0;

        } else if (target->sec < 0 || target->sec == 0 && target->nsec <= 0) {
            // target time <= 0 --> plain trylock or timed wait for time that has passed; try to lock with 0 timeout
            if (mtx->thread_id != static_cast<long>(GetCurrentThreadId())) { // not this thread, lock it
                if (mtx->_get_cs()->try_lock()) {
                    res = WAIT_OBJECT_0;
                } else {
                    res = WAIT_TIMEOUT;
                }
            } else {
                res = WAIT_OBJECT_0;
            }

        } else { // check timeout
            xtime now;
            xtime_get(&now, TIME_UTC);
            while (now.sec < target->sec || now.sec == target->sec && now.nsec < target->nsec) { // time has not expired
                if (mtx->thread_id == static_cast<long>(GetCurrentThreadId())
                    || mtx->_get_cs()->try_lock_for(_Xtime_diff_to_millis2(target, &now))) { // stop waiting
                    res = WAIT_OBJECT_0;
                    break;
                } else {
                    res = WAIT_TIMEOUT;
                }

                xtime_get(&now, TIME_UTC);
            }
        }
        if (res == WAIT_OBJECT_0 || res == WAIT_ABANDONED) {
            if (1 < ++mtx->count) { // check count
                if ((mtx->type & _Mtx_recursive) != _Mtx_recursive) { // not recursive, fixup count
                    --mtx->count;
                    res = WAIT_TIMEOUT;
                }
            } else {
                mtx->thread_id = static_cast<long>(GetCurrentThreadId());
            }
        }

        switch (res) {
        case WAIT_OBJECT_0:
        case WAIT_ABANDONED:
            return _Thrd_success;

        case WAIT_TIMEOUT:
            if (target == nullptr || (target->sec == 0 && target->nsec == 0)) {
                return _Thrd_busy;
            } else {
                return _Thrd_timedout;
            }

        default:
            return _Thrd_error;
        }
    }
}
```

Line Exception is thrown on line `mtx->_get_cs()->lock();`

```
if (target == nullptr) { // no target --> plain wait (i.e. infinite timeout)
            if (mtx->thread_id != static_cast<long>(GetCurrentThreadId())) {
                mtx->_get_cs()->lock();
            }
```

**Comment by tt4g** [comment]
In all cases, the access violation is occurring in the standard library. I can only assume that the cause of the glitch is something other than spdlog.

I think the access violation is caused by a memory leak that is happening elsewhere, such as MSVC extensions that cannot coexist with C++ being enabled.
Try disabling the MSVC extension or commentout the code before calling spdlog to see if it stops the problem from occurring.

**Comment by tt4g** [comment]
A possible cause of Access Violation is the mixing of different CRT (such as `/MT` and `/MD`).
If you have changed the CRT of your project or are using a library that you did not build yourself, the difference in CRT settings may be the cause.

- https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=msvc-170
- https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170

In any case, unless the problem is reproduced in a small project that directly uses spdlog by adding it to the include path, then the cause of the problem is not in spdlog.
