### ISSUE TITLE
Implicit signal handling

### ISSUE THREAD

**Issue by GreenFatGuy** [gabime/spdlog#2456]
Hello!

First of all I would like to thank you for the great library! Your work is amazing and I appreciate that you allow everyone to use it.

We've been using `spdlog` in one of the projects for a very long time. The version of `spdlog` in my project was very old, it was dated ~2015.
Recently I've decided to update it and faced quite not obvious behavior. The thing is that my program should be able to shutdown gracefully, and this  feature is a must. In order to do so we handle some signals in a special way with custom handlers, for example `SIGINT` and `SIGTERM`.

What we faced that after updating `spdlog` to the newer version signal handlers got replaced by some handlers from `spdlog`.  Thus our program does not have graceful shutdown anymore, which is a crucial. Thus we have to switch back to the older version. 

I was able to find two related issues and it seems that current behavior some how connected to this one: 

- First one about flushing logs on signal https://github.com/gabime/spdlog/issues/1607 . I think that current `spdlog` handlers are might be inspired by the very this issue.

- Second one about unexpected signal handling: https://github.com/gabime/spdlog/issues/2242 . However, this one seems to be closed without any result. I got similar stacktrace as in the issue: I see `wait` on some `std::condition_variable`. Me assumption that with this cond vars `spdlog` tries to flush logs on signal.

Thus I have following few questions:

1. Could you please document this feature or please tell me if I missed it somehow? I think that this is an important thing to know for anyone going to use `spdlog`.

2. Is there a legit way to use custom signal handlers and `async` `spdlog` at the same time?

3. If the answer to `2` is no, are there any plans to somehow implement this feature? In my particular case it is way much more important to have a graceful shutdown, than to have a log flush on exit

I don't have a ton of experience, so I apologize in advance if I am wrong at any point. However I think that this behavior at least should be to mentioned in documentation as a big warning. 
Signal handlers may not be used very often, but when someone decides to do so - it might be something crucial. When some library silently replace handlers it may cause some serious damage.

**Comment by gabime** [comment]
> First of all I would like to thank you for the great library! Your work is amazing and I appreciate that you allow everyone to use it.

Thanks. Much appreciated.

spdlog doesn't replace nor install any signal handlers. I guess it worked for you in the old version by chance only. 
There is a todo to provide some kind of support for this but not sure when.
 In the meanwhile I suggest look at @tt4g workaround suggestion https://github.com/gabime/spdlog/issues/1607#issuecomment-654722474

**Comment by GreenFatGuy** [comment]
Thanks a lot for your answer. I think I've found the cause of the problem in my code. Sorry for disturbance!
