### ISSUE TITLE
Combine text and flags to be aligned together

### ISSUE THREAD

**Issue by benjibst** [gabime/spdlog#2458]
For example:
I have different loggers with different names, and i want to log messages including the loggers name surrounded by square braces. 
![image](https://user-images.githubusercontent.com/76067254/182549953-4875e55f-39d4-46a6-b76e-f41490d3c87a.png)

Currently its only possible to align a flag such as %n, but I cant align the name of the logger including the surrounding braces. This is how i would want my log to look like:
![image](https://user-images.githubusercontent.com/76067254/182550030-27bbee4b-96e0-4845-a88a-33a1025c95e3.png)

It looks like this if i align just the name:
![image](https://user-images.githubusercontent.com/76067254/182550088-5bb59618-9ab3-44c0-9894-80eb0184252b.png)

Please add syntax to combine literal text with logger flags for alignment or if a feature like this already exists, share it please.

**Comment by tt4g** [comment]
You can use align flag option.
e.g. `[%-10n]` (if need to truncate, use `!` option: `[%-10!n]`)

See wiki; https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#aligning

**Comment by benjibst** [comment]
If i do like you said, this happens:
![image](https://user-images.githubusercontent.com/76067254/182568504-3b957f35-e583-4eec-a3c3-cc9ded00f1ab.png)

It is kind of what im looking for but it would look better if the closing bracket was at the end of the name

**Comment by tt4g** [comment]
Align width is always fixed. If appearance is a priority, remove the brackets (use `%-10n`).

**Comment by benjibst** [comment]
This doesnt quite solve my problem since i think brackets would be more consistent. Maybe you could add syntax for this alignment?
i think this is something which would be used a lot

**Comment by tt4g** [comment]
What spdlog provides is a simple fixed-width alignment. Brackets are not considered when the formatter calculates the width, since they are not passed on.

Add brackets to the logger name so that the bracket width is taken into consideration in the alignment calculation.

Another way. You can add new formatters of your own creation.
See: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#extending-spdlog-with-your-own-flags

**Comment by benjibst** [comment]
thanks, the idea of adding the brackets to the logger name didnt cross my mind.
i think this solves the issue for me
