### ISSUE TITLE
Information loss

### ISSUE THREAD

**Issue by MingbaiLiu** [gabime/spdlog#2459]
when i use `spdlog::apply_all([&](std::shared_ptr<spdlog::logger> l) { l->info("End of example."); });`, it seems lost info, but `std::cout` seems good.

![image](https://user-images.githubusercontent.com/107988636/182819334-d5e90e1f-c7c9-4a40-9307-970e95f68aeb.png)

**Comment by tt4g** [comment]
Was the stack trace generated with a fatal error?
If so, spdlog will not work properly.
This is because the C++ standard specification does not guarantee that a program will work correctly after a fatal error.

**Comment by MingbaiLiu** [comment]
yes, it happens a fatal error. this callstack is solved as `char*`, I just pass `char*` to `spdlog::apply_all([&](std::shared_ptr<spdlog::logger> l) { l->info("this is my char*"); });`. now I have fix it. it may cause by the difference between `char* callstack` and `char[] callstack`. When I pass `char*` into spdlog, it seems spdlog will modify the context inside.  now following code works.
![image](https://user-images.githubusercontent.com/107988636/182886803-8b6ba02a-f820-48c9-91a8-0bb05ff7ad03.png)
