### ISSUE TITLE
Is there a way to add custom variable in SPDLOG_API log_msg

### ISSUE THREAD

**Issue by gooker** [gabime/spdlog#2464]
I'm new to spdlog and I add a sink, and want to write msg to  db.

myvariable is what I want it to be ...

in my sink  sink_it_  i want to change msg to sql :
        std::string sql = fmt::format("INSERT INTO `LOG` (`funcname`,`dev_id`, `task_id`, `err_code`,`level`,`content`) VALUES "
            "(\"{}\",'{}','{}','{}','{}',\"{}\");",
            msg.source.funcname,
            msg.myvariable.dev_id,
            msg.myvariable.task_id,
            msg.myvariable.err_code,
            msg.level,
            std::string(msg.payload.begin(), msg.payload.end()));

Is there any way to achieve it or other methods?

> logger->log(spdlog::source_loc{__FILE__,` __LINE__, SPDLOG_FUNCTION}, level, __VA_ARGS__)
maybe  add myvariable  to  logger->log?

tks;

**Comment by tt4g** [comment]
There is no ability to add custom attributes to log messages.

**Comment by gooker** [comment]
> There is no ability to add custom attributes to log messages.


Is there a method to transfer custom variables to sink?

**Comment by tt4g** [comment]
Not provided. Since spdlog is the logging library, only the variables necessary to generate log messages are passed to sink.

**Comment by tt4g** [comment]
I believe many logging libraries do not have a way to transfer application-specific variables. If you want to record application variables in the database, you should consider methods that do not force the use of logging libraries.
For example, [Boost.Signals2](https://www.boost.org/doc/libs/1_80_0/doc/html/signals2.html) can easily transfer variables.

**Comment by gooker** [comment]
thks
