### ISSUE TITLE
Fail to use CMake find_package add spdlog(header not found)

### ISSUE THREAD

**Issue by SnorlaxGengar** [gabime/spdlog#2466]
Question:
I install spdlog:
```shell
git clone https://github.com/gabime/spdlog/
cd spdlog
# Windows: -DCMAKE_INSTALL_PREFIX=D:\lib
cmake -B build
cmake --build build
cmake --install
```
then I use `find_package` to add library, cmake is ok, but it occupt error: spdlog.h is not found when compiled.
`${spdlog_FOUND}` is set, but `${spdlog_INCLUDE_DIRS}` is empty.
I test this in Win10 with MSVC2015 and CentOS7.5(gcc 4.8.5).
It compile pass without error in Linux, I think it's because Linux headers search path included the install path(/usr/local/include).
I also test GTest library, GTest behave the same.
I don't familiar with CMake, is any effective/right practive to add spdlog with CMakeLists?
Thanks.

My CMakeLists:
```CMake
cmake_minimum_required(VERSION 3.23.3)
project(spdlog_test)

add_executable(spdlog_test main.cpp)

message("spdlog...")
find_package(spdlog CONFIG REQUIRED)
message("${spdlog_FOUND}")
message("${spdlog_DIR}")
message("${spdlog_INCLUDE_DIRS}")
message("spdlog...")
```

OUTPUT:
```shell
# Windows: -DCMAKE_INSTALL_PREFIX=D:\lib
$ cmake -B build
spdlog...
1

spdlog...
/usr/local/lib/cmake/spdlog
```

**Comment by tt4g** [comment]
`find_package()` only finds the package. CMake does not know that the `spdlog_test` target uses spdlog, so it does not add a compile option to use spdlog.

Please add `target_link_libraries(spdlog_test PRIVATE spdlog::spdlog)`.

```diff
 cmake_minimum_required(VERSION 3.23.3)
 project(spdlog_test)

 add_executable(spdlog_test main.cpp)

 find_package(spdlog CONFIG REQUIRED)
+target_link_libraries(spdlog_test PRIVATE spdlog::spdlog)
```

**Comment by SnorlaxGengar** [comment]
@tt4g verified, thank for your flash reply. Thanks!
