### ISSUE TITLE
Interface for notifying that spdlog drops a log?

### ISSUE THREAD

**Issue by mudream4869** [gabime/spdlog#2469]
Blocking mode is dangerous for services, but when selecting overrun mode, there is a risk of losing logs.

Not sure if there is an interface (ex: pass a callback function?) when spdlog is dropping a log.

Example callback interface?:

```cpp
void func(const Log& log) noexcept {
}
```

**Comment by tt4g** [comment]
There is no API to notify asynchronous log drops.
However, `spdlog::details::thread_pool::overrun_counter()` lets you know how many logs were dropped due to overruns.

https://github.com/gabime/spdlog/blob/f44fa31f5110331af196d0ed7f00ae1c7b8ef3cc/include/spdlog/details/thread_pool.h#L99-L100

**Comment by dawagner** [comment]
@tt4g : I found out about `overrun_counter` and I'm using it but I'm wondering, since it is in a `details` namespace, whether I can rely on the existence of this API? Would it make sense to make it part of the "official" public API and advertise it as such?

**Comment by tt4g** [comment]
@dawagner I am not the maintainer of this repository, so I cannot give an official answer.
You need to ask @gabime for the answer.

**Comment by gabime** [comment]
@dawagner I don’t think it worth it to add “official” api for this, but there are no plans on changing this in version 1.x.

**Comment by dawagner** [comment]
ok, thanks for the answer!
