### ISSUE TITLE
error C4996: 'fmt::v9::detail::arg_mapper<context>::map': was declared deprecated

### ISSUE THREAD

**Issue by Ou7law007** [gabime/spdlog#2470]
fmt v: 9.0.0 (latest)
spdlog v: 1.10.0 (latest)

The errors only started showing after updating both libraries. I don't remember the previous versions.

Every log that included an enum type produces this error.

Casting to the enum's actual type (e.g. int) solves the problem but it's really difficult to find where these are since all the errors point to the same line of code in `core.h` inside of `fmt` itself

**Comment by tt4g** [comment]
Discussion #2455 

spdlog does not support fmt v9.0.0.
