### ISSUE TITLE
Fail to log into driver

### ISSUE THREAD

**Issue by AndyWatterman** [gabime/spdlog#2472]
Spdlog failed to write logs to the driver object like this:
```
\\\\.\\Driver
```
This happens on Windows because it uses the following function to open a file:
```
*fp = ::_fsopen((filename.c_str()), mode.c_str(), _SH_DENYNO);
```
It would seem that the problem is that it cannot open the device. However, if we look inside the implementation of this function in the standard library, we see that "CreateFileW" returns "ERROR_SUCCESS".  So, no error here. Further investigation shows that the problem is in the call to "GetFileType":

![image](https://user-images.githubusercontent.com/61488512/187254354-5e0e6c47-36b4-4411-9a5f-9021fe3d71a8.png)

Calling this function using driver's handle returns FILE_TYPE_UNKNOWN. In this case Microsoft tells us:
```
If the function worked properly and FILE_TYPE_UNKNOWN was returned, a call to GetLastError will return NO_ERROR.
```
Thus, we need to check return value from the "GetLastError()" call. Indeed, the standard library receives the result of the GetLastError call, not to check that everything went well, but simply to set the error code:

![image](https://user-images.githubusercontent.com/61488512/187255630-aba8b4cf-23c9-4bb7-a133-f1ad43fea328.png)

It can be seen above that if the result is FILE_TYPE_UNKNOWN, the device handle will be closed. Simply changing FILE_TYPE_UNKNOWN to FILE_TYPE_DISK using debugger, spdlog starts working as expected.

Probably, better to use CreateFile API directly instead of CRT.

**Comment by gabime** [comment]
Thanks for the detailed analysis. 
Strange that a standard crt contains such a bug. 
Which  crt version are you using?

**Comment by AndyWatterman** [comment]
Actually, I don't think it depends on CRT version, cuz I tried on Windows 7 and Windows 10. Only need to bypass GetFileType, then Spdlog is going to work perfect.
