### ISSUE TITLE
%g, %#, %s, %!, %@ flags not working with set_pattern

### ISSUE THREAD

**Issue by byrdman** [gabime/spdlog#2477]
Using the following code to create a logger and set it's pattern.  It's not logging the source file or function.

```
auto console = spdlog::stdout_color_mt("console");
console->set_pattern("%Y%m%d-%H:%M:%S.%e,%s,%@,%!,%v");
console->trace("Test output");
```
This results in:
```
20220903-22:19:26.545,,,,Test output
```

Am I doing something wrong or is there a bug?

**Comment by tt4g** [comment]
Duplicate #1818, #2160

**Comment by byrdman** [comment]
After reading the others it makes sense, gotta use the macros since __FILE__ and __FUNCTION__ are only available at compile time.  Closing this issue.
