### ISSUE TITLE
Log level from commandline/env for "lazy created logger"

### ISSUE THREAD

**Issue by FredM67** [gabime/spdlog#2478]
Hi,
First, great job, great logging-lib ! and the code+doc are awesome ! Thx !

I've the situation that a couple of my loggers are created later on.
Is there a way to keep track of the settings given passed via command-line or env variable, so that when I create these loggers, I can set the appropriate level?
Here a sample: I've an application (logger called "app") which loads a shared library (logger called "mylib") and then a couple of "plugins" (logger called "plugin[n]").

- if I set "`SPDLOG_LEVEL=info,mylib=off`" or whatever cfg, it works almost fine (loggers from the plugins have "info" level).

- if I set "`SPDLOG_LEVEL=info,mylib=off,plugin1=trace,plugin2=debug`", it does not take effect since, at the point I'm calling "`spdlog::cfg::load_env_levels();`", none of the plugin-loggers is created.

I took a look at the code, it looks like I've to store myself the cfg somewhere and then apply it. I didn't find anything already build-in spdlog.

**Comment by tt4g** [comment]
`spdlog::cfg::load_env_levels()` only changes the log levels of already created loggers. And this API stores the log level set for each logger name in spdlog global registry.

To apply the log level stored in the spdlog global registry to a logger, create the `spdlog::logger` with the logger factory function, or pass the created logger to `spdlog::initialize_logger()`.

https://github.com/gabime/spdlog/blob/f44fa31f5110331af196d0ed7f00ae1c7b8ef3cc/include/spdlog/details/registry-inl.h#L70-L73

**Comment by FredM67** [comment]
Thx a lot for the quick and useful answer... Could it be, this point is missing in the doc? At least, it's not clear that the settings are stored global and can be used afterwards...
Indeed, great job !

**Comment by tt4g** [comment]
> this point is missing in the doc?

Probably yes.

It is by historical design that changes made in spdlog's global API are managed in spdlog global registry.
The fact is that the settings managed there are not applied unless using the spdlog factory function or `spdlog::initialize_logger()`.
