### ISSUE TITLE
多个进程输出日志到同一个目录文件，为什么会同时写多个spd文件

### ISSUE THREAD

**Issue by huangyong-170207** [gabime/spdlog#2482]
问题1：同时启动8个进程，每个进程的日志输出路径都是相同路径下的spd.log文件，每400M一个文件切割，最多50个文件，但是发现目录下8个进程在同时写多个文件，并没有全部输出到spd.log
<img width="670" alt="image" src="https://user-images.githubusercontent.com/113108834/189116779-e9d2c0b7-2140-4b4b-8815-2ce74d05a293.png">

问题2：如果问题1是存在的，按照现在的日志滚动逻辑，是把spd.{n-1}.log覆盖spd.{n}.log，这样是否会存在spd.1.log覆盖spd.2.log而导致正在输出日志的spd.2.log日志丢失的问题
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/113108834/189116135-e831589c-e9bd-4e6d-b53b-8a84e6415bf6.png">

问题3：目前这种日志覆盖的方式会导致采集日志的时候误判日志文件发生了变化，从而重复采集，spd有没有不覆盖文件的切割方式，比如每个新文件生成时是一个带时间戳的文件名，不需要发生文件轮转覆盖旧文件

**Comment by tt4g** [comment]
Duplicate #937, #2092

spdlog does not support writing log to the same file.

**Comment by sandy0024** [comment]
我使用到了主子进程写日志的场景，rotating_file_sink中稍加修改在仅允许主进程进行rotating就可以解决你的困惑。此时文件大小需要用到对file探测size，不能使用rotating_file_sink中的std::size_t max_size_;
但另外会引出新的问题，高频下串行，解决方案也只有信号量锁，会大量降低性能。
