### ISSUE TITLE
Logging to custom source?

### ISSUE THREAD

**Issue by guruprasadah** [gabime/spdlog#2486]
I've got a simple gui logger, what matters is that I can push strings to it. Is there any way of redirecting spdlog output to it? Thanks

**Comment by tt4g** [comment]
You can create custom sink.
Wiki; https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

As an example, `spdlog::sinks::qt_sink` is a sink connected to Qt.
