### ISSUE TITLE
source_loc not display function

### ISSUE THREAD

**Issue by L-Super** [gabime/spdlog#2487]
When I use 
```
SPDLOG_INFO("info message to default logger");
```
I hope get this log
```
[2022-09-11 22:00:12.965] [info] [QSpdlogTest.cpp QSpdlogTest::TestFunc():56] info message to default logger
```
but it's output
```
[2022-09-11 22:00:12.965] [info] [QSpdlogTest.cpp:56] info message to default logger
```
I think this macro definition can print file,line and function.
```cpp
#define SPDLOG_LOGGER_CALL(logger, level, ...) (logger)->log(spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, level, __VA_ARGS__)
```
But in fact, it didn't print out the function name.Was it my mistake this definition? or was it a bug

**Comment by tt4g** [comment]
What did you set to pattern flags?
Wiki: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags

**Comment by L-Super** [comment]
I used the default  pattern. I think the default should output the function name

**Comment by tt4g** [comment]
> I used the default pattern. I think the default should output the function name

Disagree.
We should use the logging macro (such as `SPDLOG_INFO`, `SPDLOG_LOGGER_INFO`) to print function names, but the logging macro is optional.
So the default pattern (`%+`) does not print function names.

If you want to output function names, change default pattern.

**Comment by L-Super** [comment]
I mean, I used the default `SPDLOG_INFO` , but it doesn't print out the function name, just the file name and line number.

`#define SPDLOG_LOGGER_CALL(logger, level, ...) (logger)->log(spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, level, __VA_ARGS__)`
 It has `__FILE__`, `__LINE__` and `SPDLOG_FUNCTION`, I think it could print function name, but it doesn't.
So, the `SPDLOG_FUNCTION` doesn't print out the function name?

**Comment by tt4g** [comment]
> So, the `SPDLOG_FUNCTION` doesn't print out the function name?

That macro is mapped to the `__FUNCTION__` macro.

https://github.com/gabime/spdlog/blob/d546201f127c306ec8a0082d57562a05a049af77/include/spdlog/common.h#L88-L90

If the `__FUNCTION__` macro is expanded to a function name, the logging formatter will print the function name.
However, if there is no flag `%!` in the logging formatter's format pattern, the function name will not be included in the log message.

Did you call `spdlog::set_pattern()` with print function pattern flag `%!`?

**Comment by L-Super** [comment]
I see. I have to use `spdlog::set_pattern()` to print the function name, even if it contains the `__FUNCTION__` macro definition, right?

**Comment by tt4g** [comment]
Right.

**Comment by L-Super** [comment]
Thank you very much!
