### ISSUE TITLE
Custom types fail on mac since c5c6baa

### ISSUE THREAD

**Issue by mdavezac** [gabime/spdlog#249]
The following does not compile:

```
#include <complex>
#include <iostream>
#include "spdlog/spdlog.h"

int main(int, char* [])
{
    namespace spd = spdlog;
    try
    {
        // console logger (multithreaded and with color)
        auto console = spd::stdout_logger_mt("console", true);
        console->info("An info message example {}..", std::complex<double>(0, 0));
    }
    catch (const spd::spdlog_ex& ex)
    {
        std::cout << "Log failed: " << ex.what() << std::endl;
    }
}
```

It seems to come from include/spdlog/details/os.h:274

The man page for strerror_r shows a signature compatible with include/spdlog/details/os.h:267.

line-numbers are for c5c6baa

I'll try and get a pull-request that detects darwin.

Verified with clang, gcc, intel.

**Comment by gabime** [comment]
It was already fixed in 1ac68e399a8d4812481be5cd007ee44675ce9a83
