### ISSUE TITLE
the speed of cross compilation is extremely slow

### ISSUE THREAD

**Issue by mandy-yan** [gabime/spdlog#2494]
Before i use spdlog in project, the speed of compilation is ok and normal.  But after use spdlog in project , the speed becomes extremely slow.  
I want to know why, and how i can solve it?   pls.

**Comment by gabime** [comment]
You need to compile spdlog and use the  compiled version instead of header-only version. 
 Also make sure that `SPDLOG_COMPILED_LIB` is defined before including spdlog.h.

**Comment by mandy-yan** [comment]
i can`t understand what the the compiled version and header-only version mean?   is there some docs told how to do.

**Comment by gabime** [comment]
see #1841
