### ISSUE TITLE
Unable to flush log in milliseconds

### ISSUE THREAD

**Issue by craigalix** [gabime/spdlog#2496]
Hi, i am having issues flushing the logs more frequently, is it possible to flush it in milliseconds rather than in seconds? Thank you, appreciate your help.

**Comment by tt4g** [comment]
Call manually `spdlog::logger::flush()` via `spdlog::apply_all()`.

Alternatively, you can call `spdlog::flush_on(spdlog::level::trace)` (or spdlog::logger::flush_on(spdlog::level::trace)`) to always flush automatically.

Wiki: https://github.com/gabime/spdlog/wiki/7.-Flush-policy

**Comment by tt4g** [comment]
Related #2080

**Comment by gabime** [comment]
Since pr #2439 it is possible to use millis or any other chrono duration type.

**Comment by craigalix** [comment]
Sorry may i ask if this will be in the new commit tag, as for the current version it seems like the latest tag is v1.10.0 on the apr 4th but i saw that the changes are made in July 2022.

**Comment by tt4g** [comment]
#2439 has not yet been tagged (released).
