### ISSUE TITLE
hourly file sink do not  engender new file when modifying system time manual

### ISSUE THREAD

**Issue by leirenjieyi** [gabime/spdlog#2497]
hi
I use hourly file sink, current log is log_2022-09-29_14. when I modify system time by command 'date -s "17:00:00"' , the log is still log_2022-09-29_14.

**Comment by tt4g** [comment]
I don't think `date -s "17:00:00"` command is successful.

`date "17:00:00"` is invalid date format:

```shell
# Invalid.
$ date "17:00:00"
date: invalid date '17:00:00'

# Valid.
$ date '+%F 17:00:00'
2022-09-29 17:00:00
```

**Comment by leirenjieyi** [comment]
I suggest:
hourly_file_sink.h:void sink_it_
bool should_rotate = time >= rotation_tp_
==>
bool should_rotate = (time >= rotation_tp_) || (rotation_tp_ - time >= std::chrono::hours(1));

**Comment by tt4g** [comment]
The time set in `rotation_tp_` is one hour after `next_rotation_tp_()` is called.

https://github.com/gabime/spdlog/blob/7130676697b10d1704b057371e9d2493a01503d9/include/spdlog/sinks/hourly_file_sink.h#L138-L150

The expression `rotation_tp_ - time >= std::chrono::hours(1)` is rarely `true` evaluated.
