### ISSUE TITLE
Compatibility break: removed log level

### ISSUE THREAD

**Issue by xaqq** [gabime/spdlog#250]
Hello,

I updated my `spdlog` dependency (`git pull` the submodule) and my build broke. It turns out some log level have been removed.

It's quite possible that the removal was unintended as the commit doesn't point out removal of log level: https://github.com/gabime/spdlog/commit/7ddfb2b877a0c431c647001d6b1db6fff3426628

My question: were those removal intentional, or is it a mistake and a pull request to re-add those would be accepted?

Thanks

**Comment by gabime** [comment]
Hi,

Yes it was intentional. sorry for not explicitly stating it in the commit message

**Comment by xaqq** [comment]
Hello,

Okay. While I agree that `emerg`, `alert`, and `critical` can be considered redundant, I'd argue for bringing back `notice`.

It feels like a good level between an purely informational message and a formal `warn` message. Ie, "hey its not too important, but consider taking a look".

However, I can also understand not wanting it back at all. Let me know.

**Comment by gabime** [comment]
i am not sure. It still seems redundant with warning. On the other hand if it is important to you please issue a pr and i will bring it back
