### ISSUE TITLE
Logs in file are incomplete

### ISSUE THREAD

**Issue by L0wperformer** [gabime/spdlog#2502]
Hello. 
Astonishing how incredibly fast spdlog is able to write to files. 
Sadly, the logs are incomplete. 
I am currently running benchmarks with simple time measurements. My code looks something like this: 

```c++
#include <iostream>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

bool logXTimes(int x, std::shared_ptr<spdlog::logger> logger){  
        for (int i = 0; i<x;i++){  
            //LoggingCommandHere  
           SPDLOG_LOGGER_INFO(logger,"Logmessage Nummer {}",i);  
        }  
}  

int main(int argc, char *argv[])
{
    spdlog::set_pattern("%T:%e [%s:%#] [%l] || %v");
    auto logger = spdlog::basic_logger_st("st_logger","log_st1.log");
    logger->set_level(spdlog::level::info);

    logXTimes(100,logger);

    std::cout<<"Time for 1.000.000 iterations in single Thread: "<<stopTime<<" ms"<<std::endl;
}
```

The file starts correctly but then abrubtly ends:
```
(...Above this all good...)
19:29:12:940 [main.cpp:62] [info] || Logmessage Nummer 66
19:29:12:940 [main.cpp:62] [info] || Logmessage Nummer 67
19:29:12:940 [main.cpp:62] [info] || Logmessage Nummer 68
19:29:12:940 [main.cpp:62] [info] |

```

Why does this happen? Is it a bug or is my code garbage?
Thank you in advance.

**Comment by tt4g** [comment]
Call `spdlog::shutdown()` before exiting the application.
Because the OS buffers writes to files, some logs may not be written to files unless `spdlog::logger::flush()` is called through `spdlog::shutdown()`.

**Comment by L0wperformer** [comment]
Thank you for the answer. 
Sadly `spdlog::shutdown()` did not resolve the issue. 

As it turns out, I made my minimal working example too minimal since the problem seems to be caused by the Qt-Framework I'm using. 

The truth looks more like this:

```c++
#include <iostream>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

#include <QCoreApplication>

bool logXTimes(int x, std::shared_ptr<spdlog::logger> logger){  
        for (int i = 0; i<x;i++){  
            //LoggingCommandHere  
           SPDLOG_LOGGER_INFO(logger,"Logmessage Nummer {}",i);  
        }  
}  

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    spdlog::set_pattern("%T:%e [%s:%#] [%l] || %v");
    auto logger = spdlog::basic_logger_st("st_logger","log_st1.log");
    logger->set_level(spdlog::level::info);

    logXTimes(100,logger);

    std::cout<<"Time for 1.000.000 iterations in single Thread: "<<stopTime<<" ms"<<std::endl;

    return a.exec();
}

```

Changing `return a.exec();` to `return 0;` fixed the problem. Still, I dont think this is desired behaviour.

**Comment by gabime** [comment]
Jusr call once `logger->flush()` after the call to `logXTimes(100,logger)`

**Comment by L0wperformer** [comment]
Thank you, that worked.

**Comment by tt4g** [comment]
> Sadly `spdlog::shutdown()` did not resolve the issue.

Hmm, I don't know why `spdlog::shutdown()` didn't work.

As written above, we can call `logger->flush()` to force the log to be output to a file.
This operation calls `sink->flush()` on the sink owned by the `logger`.

The `sink->flush()` is also called inside the destructor of sink. 
So once all loggers are deleted, the sink destructor is called.

Since spdlog manages the logger in its internal registry, I was going to call `spdlog::shutdown()` to have the logger deleted, but I don't know why it didn't work as I expected.

In any case I am glad your problem is solved.

**Comment by L0wperformer** [comment]
Is this worth reopening? 
I feel like the behaviour is not intuitive to say the least.

**Comment by tt4g** [comment]
I don't think it is enough to reopen.

The code provided is a simple C++ program, but the application will not exit until the call to `QCoreApplication::exec()` is completed.
Qt uses some tricks and I think that is why the sink was not deleted.

**Comment by L0wperformer** [comment]
Nevertheless, the logs should be written to the file completly. Even when ending the Programm the missing logs were not appended, so the data is just gone.  
How do I know when to call flush when I want my logs instantly in the file e.g. to be safe in events of a crash?

**Comment by tt4g** [comment]
To always flush, call `logger->flush_on(spdlog::level::trace)`.
Wiki: https://github.com/gabime/spdlog/wiki/7.-Flush-policy

However, after the application crashes, it is not guaranteed to be flushed reliably because of undefined behavior in the C++ specification.

**Comment by L0wperformer** [comment]
So this is where the perfomance compared to other framworks comes from. With `logger->flush_on(spdlog::level::xyz)` the time for one million logs grows by more than factor 10 (600ms --> 7600ms). 

I actually tested crashing of the apllication by raising a `SIGSEGV` in my logging loop and the logs were always complete, so it is even more weird to me that unless I `return 0` my logger decides to just not log until the end. 

The perfomance benefit to all other logging libs I tested is so huge though, it might be worth taking the risk and "just flushing" now and then. 

Edit: The framework even supports automatic flushes every x seconds or on specific level, so this is definetly worth the perfomance.

**Comment by tt4g** [comment]
I think `spdlog::flush_every(std::chrono::seconds(1))` is sufficient in most cases.
If the design has a specific log level that you do not want to lose, you can combine `logger->flush_on(spdlog::level::*)` as well.

**Comment by L0wperformer** [comment]
I will run some more tests but if done correctly, flushin on error or fatal (indicating a soon or definite crash) should be enough. 
Thank you very much for your time. I'm just starting working as a dev and I already learnt a lot just here :)
