### ISSUE TITLE
SPDLOG_LEVEL environment variable is not honored for future loggers

### ISSUE THREAD

**Issue by phamelin** [gabime/spdlog#2508]
When using the `SPDLOG_LEVEL` environment variable to configure loggers through `spdlog::cfg::load_env_levels()`, a call is made to `spdlog::details::registry::set_levels`. According to the documentation,
https://github.com/gabime/spdlog/blob/936697e5b1944bf1630cfbb9e82144f8bdc32815/include/spdlog/details/registry.h#L89-L90
it should set the log level for future loggers. However, it doesn't because in the implementation it only sets the level for existing loggers https://github.com/gabime/spdlog/blob/936697e5b1944bf1630cfbb9e82144f8bdc32815/include/spdlog/details/registry-inl.h#L263-L282
What is supposed to be the expected behavior?

**Comment by tt4g** [comment]
> it should set the log level for future loggers. However, it doesn't because in the implementation it only sets the level for existing loggers

No. The logger passed to `spdlog::details::registry::initialize_logger()`  will have its log level set.

https://github.com/gabime/spdlog/blob/936697e5b1944bf1630cfbb9e82144f8bdc32815/include/spdlog/details/registry-inl.h#L60-L86

**Comment by phamelin** [comment]
@tt4g You're right, I missed the global variable `log_levels_`. I was using `register_logger` instead of `initialize_logger` so I was bypassing the initialization routine. Thanks!
