### ISSUE TITLE
Compile-time switch for disabling the global registry?

### ISSUE THREAD

**Issue by bjadamson** [gabime/spdlog#251]
Hi,

I'm a new user of your (awesome) library and have a request / inquiry. I'm trying to write my application using as many functional paradigms as I can, as such the global registry is a feature I (please correct me if I am wrong) that I won't be using. I'll be passing the instances of the logger through the application, thus I don't need the "name" argument for the factory fns (again, please let me know if I am wrong) or the ability to query for sinks at runtime.

So far, I've been able to initialize my logger like this (I adapted these from the official documentation to cut down on the dynamic allocations) and I believe since everything is a unique_ptr, that I wouldn't be able to register them to the registry (without giving up my handle, perhaps using std::move, if this is even supported).

    template<typename ...Params>
    static decltype(auto)
    make_logger(Params &&...p)
    {
      // TODO: pass in a boost::filesystem::path as the directory.
      auto constexpr debug_filename = "debug.log";

      // std::array instead of std::vector
      std::array<spdlog::sink_ptr, 2> const sinks = {

        // std::make_unique instead of std::make_shared
        std::make_unique<spdlog::sinks::stdout_sink_st>(),
        std::make_unique<spdlog::sinks::daily_file_sink_st>(debug_filename, "txt", 23, 59)
      };

      auto log_impl_pointer = std::make_unique<spdlog::logger>("name", begin(sinks), end(sinks));
      // This function just returns a log-wrapper I wrote, unimportant.
      return create_logger(std::move(log_impl_pointer));
    }

I was looking through this file (what a great idea BTW)
https://github.com/gabime/spdlog/blob/master/include/spdlog/tweakme.h

and noticed there wasn't a switch for this. Has anyone approached you thus far with such a request? Do you think it would be possible (I may look into submitting a pull-request depending on what you think) to enable/disable the global registry at compile-time?

I did notice the factory functions by-default automatically register a sink as you create it, if that's it, maybe it's not so bad. Looking forward to your thoughts :+1: 

Thanks for writing such a good library BTW!

edit:
I found this, it's almost exactly what I want (I must of been reading too quickly before!)
https://github.com/gabime/spdlog/blob/master/include/spdlog/tweakme.h#L65

**Comment by gabime** [comment]
Hi, Thanks for the nice feedback👍

You do not have to use the registry. In fact if you create loggers the way you shown, the registry is not involved at all.

The registry keeps track of logger pointers (not sinks) only if they were created using the factory functions(spdlog::daily_logger_mt(..) etc.)

So to summarize, even though loggers have names, they wont be registered if constructed directly.

**Comment by bjadamson** [comment]
Great to hear, is there any runtime overhead involved at all? Is any per-thread data or global data allocated if I avoid the factory functions entirely?

If so, I think this would be a great FAQ entry! :+1:

**Comment by gabime** [comment]
No overhead afaik
