### ISSUE TITLE
compile error on Windows with external fmtlib and MSVC 17.3.6

### ISSUE THREAD

**Issue by YunchengLiu** [gabime/spdlog#2512]
Thanks a lot for this excellent library, helped me a lot.
But I encountered a sudden problem. 
On Windows platform, after enabling wchar_t and external fmtlib support in spdlog, when compiling with C++20 option in MSVC 17.3.6, fmt throws a compilation error. 

spdlog ( 1.10.0#1) and fmtlib (9.1.0) are all installed via vcpkg(x64-windows) with lasted port comfigurations.

Message as follows:

```
Error C7595: "fmt:: v9:: basic_format_string<wchar_t, const tm&>:: basic_format_string": The call to an instant function is not a constant expression.
```
The wrong location is:
https://github.com/gabime/spdlog/blob/d011332616464bd0c84817d6255bf5910b7803e9/include/spdlog/sinks/daily_file_sink.h#L81

I saw the comments here, but I still tried to modify it to `fmt::runtime` , it compiles successfully at this time, it seems that the comments here are a bit outdated? Has the new version of MSVC resolved the contradiction between wchar_t and fmt?

I tried to reproduce the above problem externally with the following minimal code. On my local PC, the following code using MSVC 17.3.6 will throw the same error (not modified to `fmt::runtime` ).

```c++

#define SPDLOG_WCHAR_FILENAMES
#define SPDLOG_FMT_EXTERNAL
#include <fmt/format.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/daily_file_sink.h>

int main(){

    auto logger = spdlog::daily_logger_mt("daily_logger", L"logs/daily.txt", 2, 30);

    logger->info("{} world", "hello");

}

```

Since I don't know about other platforms and the specific requirements for compiler versions, I would like to ask if it is possible to modify this to `fmt::runtime` to solve the problem?

**Comment by tt4g** [comment]
fmt recently added support for `wcart_t *` compilation time checks (https://github.com/fmtlib/fmt/issues/3107#issuecomment-1252716537).

The fmt bundled with spdlog is version 8.x, so it does not take into account the compile check feature of the latest version.

Can you add the `SPDLOG_FMT_RUNTIME` macro to avoid the problem?
Also, if it works, could you please create a PR?

https://github.com/gabime/spdlog/blob/d011332616464bd0c84817d6255bf5910b7803e9/include/spdlog/sinks/daily_file_sink.h#L80-L84
