### ISSUE TITLE
Feature Request: Per-Level Log Counter

### ISSUE THREAD

**Issue by jake-arkinstall** [gabime/spdlog#2521]
Consider you have some code that is required to log a warning in certain circumstances, and consider that you wish to enforce this behaviour through tests. Logs aren't often considered part of the interface that you'd test against - but when they are, they are. You don't care about the content or formatting, and interpreting stringstream contents is too hacky - your requirement is that you issue a warning, and your test simply needs to verify that this happens.

I looked around for other kinds of sink, and couldn't find one to my liking. So I wrote following sink. It's not pretty nor complete (designed for single threads), but it serves as a good enough example.

```cpp
struct event_count_sink : public spdlog::sinks::sink{
    std::size_t trace_count = 0;
    std::size_t debug_count = 0;
    std::size_t info_count = 0;
    std::size_t warn_count = 0;
    std::size_t error_count = 0;
    std::size_t critical_count = 0;
    void log(spdlog::details::log_msg const& msg) override{
        switch(msg.level){
            case SPDLOG_LEVEL_TRACE:
                ++trace_count;
                break;
            case SPDLOG_LEVEL_DEBUG:
                ++debug_count;
                break;
            case SPDLOG_LEVEL_INFO:
                ++info_count;
                break;
            case SPDLOG_LEVEL_WARN:
                ++warn_count;
                break;
            case SPDLOG_LEVEL_ERROR:
                ++error_count;
                break;
            case SPDLOG_LEVEL_CRITICAL:
                ++critical_count;
                break;
            default:
                break;
        }
    }
    void flush() override{}
    void set_pattern(const std::string&) override{}
    void set_formatter(std::unique_ptr<spdlog::formatter>) override{}
};
```

This allows me to incorporate logging checks into tests, e.g ([godbolt example](https://godbolt.org/z/xrdb3xT34)):

```cpp
TEST_CASE("Bar warns when foo", "[logging]"){
    auto sink = std::make_shared<event_count_sink>();
    auto logger = std::make_shared<spdlog::logger>("", sink);
    
    Bar b{.logger = logger};
    REQUIRE(sink->warn_count == 0);
    b.do_the_thing(false);
    REQUIRE(sink->warn_count == 0);
    b.do_the_thing(true);
    REQUIRE(sink->warn_count > 0);
}
```

This kind of sink would be useful for a variety of purposes, including tests and log monitoring (one may wish to print the number of warnings generated by a set of components before returning from main, without explicitly incrementing global integers, for example).

**Comment by gabime** [comment]
Each test env would have its requirements, so one should  implement their own test sink for their specific test env.

For example there is already a [test_sink](https://github.com/gabime/spdlog/blob/v1.x/tests/test_sink.h) in _tests_/ that counts messages (and can be used as reference).

**Comment by jake-arkinstall** [comment]
Indeed. My request is, I guess, more of a feeler - if a sink that would act as a passive counter for various types of log would be occasionally useful to some, then I'd be more than happy to implement it properly and submit a PR. If not, then the issue can be closed.

**Comment by gabime** [comment]
Thanks @jake-arkinstall. I will keep this in mind in case there is more demand for this.
