### ISSUE TITLE
Clarification request

### ISSUE THREAD

**Issue by mcondarelli** [gabime/spdlog#2522]
Hi, I am currently using `spdlog` in a small project using just one default logger using logging macros (`SPDLOG_INFO()` and friends).
As project grows, however, this strategy won't suffice.

I will need to have multiple loggers (possibly insisting on the same set of sinks), most likely one fore each file/class.
I will also need possibility to switch log level of each logger independently at runtime as debugging needs arise.

I thought about implementing a wrapper class providing services "for everyone" but, before I plunge in unknown sea, I would like to know if something similar is already available and if there are "best practices" to follow.

Many Thanks in Adevance

**Comment by tt4g** [comment]
There is no such thing as best practices as far as I know.
For example, a web server could create the separate sink and logger for each request to allow tracking of requests.
There are projects like yours that want to create the logger for each class and share the sink.

I think many people would prepare a wrapper class like logger factory that could meet the requirements of such a project.

**Comment by gabime** [comment]
A possible approach is to create at startup a “root” logger with its sinks and then, in each class that needs its own logger do

```c++
this.classLogger = spdlog.get(“root”)->clone(“myClassName”);
```

Which would create a new logger named “myClassName” with sinks (and other settings) inherited from the root logger.

**Comment by artemyv** [comment]
When project becomes really big - using logger per class/file - is unmanageable approach in my experience - we had such configuration for a long time - nobody uses per class level settings even when it is available.
So I recommend select a bigger components - like dlls to share same logger. Adding separate loggers only for very active classes - spamming with a lot of noise - so they could be silenced separately when main dll logger is set to debug or trace.

I would think 10-20 loggers for big app is reasonable

And configure your pattern to show class/function name - in this case you just filter your logs when analyzing based on class name.

**Comment by mcondarelli** [comment]
I'm unsure if reopening is the right policy, but things are closely related.
I am following @gabime advice and I am creating a bunch of partitioned loggers (of course @artemyv is right, I am not creating one-logger-per-class, I am logically grouping classes under same logger, but that is beyond the point).
Problem is I would like to be able to add/remove a sink to all defined loggers, how can I do that?

Reason for request is:
- I am logging to console and syslog, normally.
- I have a "monitoring/debugging tool" which can optionally attach to program from remote (TCP socket).
- if and when tool is connected I would like to activate remote logging, probably using an udp_sink.
- when tool is disconnected I would like to avoid sink overhead/errors.

What is the right way to achieve this?

**Comment by tt4g** [comment]
Create a custom sink that wraps udp_sink.
Custom sinks can achieve your goal by sending data from udp_sink based on the connection status of the debugging tools.
You can ignore errors by `try`-`catch` the udp_sink API in your custom sink.

Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by gabime** [comment]
> Problem is I would like to be able to add/remove a sink to all defined loggers,

It would be much easier to just change the sink level at runtime on and off. Adding/removing sinks is not a thread safe operation and also means you have iterate all loggers to remove/add the sink, instead of changing its level once.

**Comment by mcondarelli** [comment]
Thanks @gabime !
That is indeed easier and less error-prone.
Regards.
