### ISSUE TITLE
Printing C array

### ISSUE THREAD

**Issue by mcondarelli** [gabime/spdlog#2525]
Hi, I am aware of `spdlog::to_hex()` to print using iterators.
In my case I have a `function(int len, uint32_t *ptr)` and I would like to print a (hopefully not very long) `(2)[01234567, 89abcdef]`.
Is this possible directly  or should I convert manually to `std::array<uint32_t>` first?

**Comment by gabime** [comment]
If I recall correctly, It expects single byte per item, so you would need to convert to any container of chars.

I think  `spdlog::to_hex(std::begin(char*)ptr), std::begin((char*)ptr+len*sizeof(uint32_t)` might work as well

**Comment by mcondarelli** [comment]
For whoever is interested: I had to define a wrapper class for the above to work:
```
template<typename T>
class range_view {
    T* m_data;
    std::size_t m_size;
public:
    range_view(T* data, std::size_t size) : m_data { data }, m_size { size } { }

    const T* begin() const { return m_data; }
    const T* end() const { return m_data + m_size; }

    T* begin() { return m_data; }
    T* end() { return m_data + m_size; }
};
```
and use it like:
```
        auto q = range_view<uint32_t>(reinterpret_cast<uint32_t*>(p), ret);
        logger->trace("LRM::grab(): returning {}: {}", ret, spdlog::to_hex(q.begin(), q.end()));
```
