### ISSUE TITLE
how to use the Compiled version with cmake and subdirectory

### ISSUE THREAD

**Issue by Omernn23** [gabime/spdlog#2528]
Hi, I'm trying to use spdlog.
I'm getting a lot of error when I try to build:
"
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.
"

my project tree build like this:
-- project:
------ 3rd_party
-------------- spdlog
-------------- date
------ src
-------------- control
---------------------- control.cpp
---------------------- control.hpp
---------------------- CMakeLists.txt
-------------- motor (file same like control directory)
-------------- another sub directories which not relevant .. 
------ CMakeLists.txt

In control dir the CMakeLists.txt looks like this:
![image](https://user-images.githubusercontent.com/98874628/199488756-41f971a2-e51c-4a96-9040-cfc313728314.png)

In the main CMakeLists.txt:
![image](https://user-images.githubusercontent.com/98874628/199488315-8cbec150-cdd9-428e-93c5-a411745e6378.png)

What am I doing wrong ?

I just want to use the Compiled version (the recommended 1)
If I put #include "spdlog/spdlog.h" it tells me there is an error.
In addition in the readme there is explanation for the package manager and usage example - I didn't understand if I needed this in case I am using the compiled version.

Thanks

**Comment by tt4g** [comment]
If you have not installed spdlog with CMake, then `find_package()` will not find spdlog.

> **TIP**
> `spdlogConfig.cmake` is generated by the CMake-install step.
>
> - https://github.com/gabime/spdlog/blob/6a9d5616712eae9e03570a3efe80dcecba1e3cd0/CMakeLists.txt#L286-L287
> - https://github.com/gabime/spdlog/blob/6a9d5616712eae9e03570a3efe80dcecba1e3cd0/CMakeLists.txt#L338-L343

Install spdlog on your machine.
Or download the source code of spdlog to your project and import spdlog into your project with [`add_subdirectory()`](https://cmake.org/cmake/help/v3.25/command/add_subdirectory.html).

BTW: `PATH` in `find_package()` is wrong, `PATHS` is correct: https://cmake.org/cmake/help/v3.25/command/find_package.html

**Comment by Omernn23** [comment]
First, thanks for your response.
I Opened in the 3-rd_party directory in my project a directory called spdlog and did as followed:
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j
So I dont understand why find_package doesnt work olso with PATHS
any ideas?
Just want to use the API
@tt4g

**Comment by tt4g** [comment]
Missing `make install` command.

```diff
 $ git clone [gabime/spdlog.git](https://github.com/gabime/spdlog.git)
 $ cd spdlog && mkdir build && cd build
 $ cmake .. && make -j
+$ make install
```

**Comment by Omernn23** [comment]
I added subdirectory like this - 
```
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../3rd_party/spdlog ${CMAKE_CURRENT_BINARY_DIR}/spdlog)
```
and also ```make install ``` command and it is finally compiled,
Thank you very much
@tt4g
