### ISSUE TITLE
Compiler Error C2248 (not support for Chinese?)

### ISSUE THREAD

**Issue by 1eim0** [gabime/spdlog#253]
I did it this way:
1. #define SPDLOG_WCHAR_FILENAMES
2. auto my_logger = spd::basic_logger_mt("basic_logger", "logs/basic.txt");
3. my_logger->info(_T("中文"));

error:
"fmt::BasicWriter<char>::operator <<": cannot access private member(declared in class "fmt::BasicWriter<char>"

**Comment by gabime** [comment]
wchars not supported in log messages. Only in filenames

**Comment by jasonjei** [comment]
If you're using ATL, you could always use the nice CW2A macros into UTF-8.  That's what we've been doing with WCHARs. UTF-8 is more standard anyway...
