### ISSUE TITLE
Fail to create logger using daily_logger_format_mt()

### ISSUE THREAD

**Issue by fortunely** [gabime/spdlog#2533]
I try to create a logger with daily_logger_format_mt(), referencing to daily_filename_format_calculator's annotation in sinks/daily_file_sink.h. But I failed, and error happens when daily_file_sink::file_helper_.open() invoked, which errno = 22.

My question is: Is it the annotation wrong or my creating method wrong, when using daily_logger_format_mt()?

My environment：
* OS Win10x64
* IDE VS2022 Community

daily_filename_format_calculator's annotation(from [daily_file_sink L44](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/daily_file_sink.h#L44) ): 
```c++
/*
 * Generator of daily log file names with strftime format.
 * Usages:
 *    auto sink =  std::make_shared<spdlog::sinks::daily_file_format_sink_mt>("myapp-%Y-%m-%d:%H:%M:%S.log", hour, minute);"
 *    auto logger = spdlog::daily_logger_format_mt("loggername, "myapp-%Y-%m-%d:%X.log", hour,  minute)"
 *
 */
struct daily_filename_format_calculator
{...}
```

My creating case: 
add this line to  daily_example() of example.cpp
```c++
auto logger = spdlog::daily_logger_format_mt("loggername", "logs/myapp-%Y-%m-%d:%X.log", 2, 30);
````
Console output result (error message):
```
...
Log initialization failed: Failed opening file myapp-2022-11-04:16:25:57.log for writing: invalid argument
```

I guess pattern flag "%X" means "%H:%M:%S". But colon(":") is not a valid character for a filename under Window10x64. After I using 
"%H_%M" instead of ":" , no error happens.

**Comment by tt4g** [comment]
Windows OS does not allow the use of `:` in the file path.

Some characters may not be used in the path depending on the platform.
It is the developer's responsibility to ensure that these characters do not appear in the file path.

**Comment by fortunely** [comment]
@tt4g Thanks for reply. I get your point. User, that is , I should ensure the validity of a file path under specific OS.
