### ISSUE TITLE
problem with std::filesystem::path

### ISSUE THREAD

**Issue by RScherzer** [gabime/spdlog#2536]
Hi,

up to the latest update I've used my own implementation of supporting std::filesystem::path

template <>
struct fmt::formatter<std::filesystem::path> : formatter<std::string_view> ...snip.....
.... and it worked fine.

however updating to the latest release caused conflicts. I was under the impression that std::filesystem::path is now supported, so I removed my code but I get the following compile (MSVC) errors when doing something like

spdlog::error("can't access: {}", archiveName_) where archiveName_ is a std::filesystem::path

The errors I get are:

\3rdParty\spdlog\include\spdlog\fmt\bundled\core.h(2746,12): error C2039: 'parse': is not a member of 'fmt::v9::detail::fallback_formatter<std::filesystem::path,Char,void>' with [ Char=char ]
\3rdParty\spdlog\include\spdlog\fmt\bundled\core.h(1123): message : see declaration of 'fmt::v9::detail::fallback_formatter<std::filesystem::path,Char,void>' with [ Char=char ]
\3rdParty\spdlog\include\spdlog\fmt\bundled\core.h(2951): message : see reference to function template instantiation 'const char *fmt::v9::detail::parse_format_specs<std::filesystem::path,fmt::v9::detail::compile_parse_context<Char,ErrorHandler>>(ParseContext &)' being compiled with [ Char=char, ErrorHandler=fmt::v9::detail::error_handler, ParseContext=fmt::v9::detail::compile_parse_context<char,fmt::v9::detail::error_handler>]
\3rdParty\spdlog\include\spdlog\fmt\bundled\core.h(2951): message : while compiling class template member function 'fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,std::filesystem::path>::format_string_checker(fmt::v9::basic_string_view<Char>,ErrorHandler)' with [ Char=char, ErrorHandler=fmt::v9::detail::error_handler ]
\3rdParty\spdlog\include\spdlog\fmt\bundled\core.h(3148): message : see reference to class template instantiation 'fmt::v9::detail::format_string_checker<Char,fmt::v9::detail::error_handler,std::filesystem::path>' being compiled with [ Char=char ]
message : see reference to function template instantiation 'fmt::v9::basic_format_string<char,std::filesystem::path &>::basic_format_string<char[17],0>(const S (&))' being compiled with [ S=char [17] ]

Any idea?

**Comment by tt4g** [comment]
As the error message says: the fmt library does not know how to format `std::filesystem::path`.

See fmt document:
	- https://fmt.dev/9.0.0/api.html#standard-library-types-formatting
	- https://fmt.dev/9.0.0/api.html#formatting-user-defined-types

**Comment by RScherzer** [comment]
yes, I had my own

template <>
struct fmt::formatterstd::filesystem::path : formatterstd::string_view

in before and it caused a clash during compilation with the new version....so I was falsely under the impression, that std::filesystem::path is now supported by default. So I removed it and ran into the upper issues.

My fault....the clash was caused by something else which I've fixed now...all good now...thanks anyhow

**Comment by eli-b** [comment]
Looking at the fmt documentation, it does look like it supports formatting std::filesystem::path. You need to include fmt/std.h to get the formatter.

**Comment by RScherzer** [comment]
Yes, but std.h is not included in the standard spdlog fmt package....

however, yes, adding it from the fmt package (plus ostream, plus format) works....Thanks

**Comment by eli-b** [comment]
There should probably be a convenience header file similar to spdlog/fmt/ostr.h and spdlog/fmt/chrono.h that would include either fmt/std.h or the bundled fmt/std.h depending on SPDLOG_FMT_EXTERNAL.

I might open a pull request myself...

**Comment by lkesteloot** [comment]
For future readers, the header is now available:

```cpp
#include <spdlog/fmt/std.h>
```
