### ISSUE TITLE
log file per program execution

### ISSUE THREAD

**Issue by Omernn23** [gabime/spdlog#2537]
Hi I need help in how to write to a rotating multi-threaded log file , but I want a log file per execution of the program.
currently I wrote:

```
  auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("logs/multisink.txt", true);
  auto rotate_file_sink =std::make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/rotate_file_sink.txt", max_size, max_files);

  std::vector<spdlog::sink_ptr> sinks {file_sink, rotate_file_sink};
  auto logger = std::make_shared<spdlog::logger>(DEFAULT_LOGER_NAME, sinks.begin(), sinks.end());
  logger->set_level(spdlog::level::trace); 
```
 but the problem im dealing with:
1 - file_sink is not rotating so what is its file limit size?
2 - file_sink is override when stating a new execution
2 - rotate_file_sink is until its arrive its limit but I want it to be saved per execution, 
    meaning - when Im running the program a new log file is open (with the time of execution as name)
    and when done it's saved.
   than the next execution open another log file (someting like daily basis , but instead per execution)

**Comment by tt4g** [comment]
spdlog generates a log file name based on the filename passed.
If you want the log file to be unique for each execution, you can add your own timestamp, PID, or other elements to the file name to generate a unique file name for each process.

fmt example (see https://fmt.dev/9.0.0/api.html#chrono-api):

```cpp
#include "spdlog/fmt/chrono.h";

...

int main()
{
  std::time_t t = std::time(nullptr);
  std::string filename = fmt::format("logs/multisink.txt.{:%Y%m%d}", fmt::localtime(t));

  auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(filename, true);

  auto logger = std::make_shared<spdlog::logger>(DEFAULT_LOGER_NAME, file_sink);
}
```

**Comment by Omernn23** [comment]
Thanks for the response -
I did as you wrote, but its still write to the same file even though the time stamp is different
and its new execution of the program.
attach log content:
![image](https://user-images.githubusercontent.com/98874628/200311249-46e096ff-3d6c-468d-a3a2-c776f652670e.png)

also I would like to use a sink which can be multi threaded and rotating so I thing this is better for me -   
auto rotate_file_sink =std::make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/rotate_file_sink.txt", max_size, max_files);

but it still does not do what I intended.
I want that each execution has its own log file

**Comment by tt4g** [comment]
It says "new execution," but I assume you mean process start, right?
I don't know the interval at which a process is started, so I have provided an example code that includes only the date in the filename, taking a cue from the first comment, "something like daily basis".

If the "new execution" interval is in seconds, specify the appropriate format (https://fmt.dev/9.0.0/syntax.html#chrono-specs).

```diff
   std::time_t t = std::time(nullptr);
-  std::string filename = fmt::format("logs/multisink.txt.{:%Y%m%d}", fmt::localtime(t));
+  std::string filename = fmt::format("logs/multisink.txt.{:%Y%m%d_%H:%M:%S}", fmt::localtime(t));
```
