### ISSUE TITLE
Build error using spdlog as a sub-directory

### ISSUE THREAD

**Issue by Omernn23** [gabime/spdlog#2542]
Hello,
Introduction to the problem:
I downloaded & extracted spdlog code to a sub directory in my project.
I did that because Im not interested to get a copy of the history and it's functional git repo.
So I removed all the .git* related files (.github/ .gitConfig .gitAttributes) and pushed the changes to the git.
Than in my computer I built the spdlog build and the build created successfully.
than in the project's main directory I use my cmake to build the whole project and the build also was successfully created.

The problem:
In a remote system I did pull, in 3party/ dir, spdlog dir was succesfully pulled with all the files.
I did the same as I did im my local:
```
cd 3party/spdlog && mkdir build && cd build
cmake .. && make -j
sudo make install
```
and the spdlog build created successfully:
![image](https://user-images.githubusercontent.com/98874628/200834216-7da086d0-a976-4e11-a314-b49c2971cce6.png)
But when I built the whole project - got mant spdlog related errors:
 
![image](https://user-images.githubusercontent.com/98874628/200834536-45914fe8-9818-4d12-b97e-d0785260bc45.png)
 some of the error I get:
```
/3rd_party/spdlog/include/spdlog/spdlog.h:94:1: error: ‘SPDLOG_API’ does not name a type; did you mean ‘SPDLOG_WARN’?
 SPDLOG_API void register_logger(std::shared_ptr<logger> logger);
/3rd_party/spdlog/include/spdlog/spdlog.h:135:17: error: variable or field ‘log’ declared void
 inline void log(source_loc source, level::level_enum lvl, format_string_t<Args...> fmt, Args &&... args)
error: ‘source_loc’ was not declared in this scope
error: ‘format_string_t’ has not been declared
 inline void log(level::level_enum lvl, format_string_t<Args...> fmt, Args &&... args)
 error: there are no arguments to ‘default_logger_raw’ that depend on a template parameter, so a declaration of ‘default_logger_raw’ must be available [-fpermissive]
error: ‘get’ is not a member of ‘spdlog’
 #define CONSOLE_LOG_INFO(...)       if(spdlog::get(DEFAULT_LOGER_NAME) != nullptr) {spdlog::get(DEFAULT_LOGER_NAME)->info(__VA_ARGS__);}
```
Any Ideas what's wrong??
Im doing same operation, I understand that the build is per computer but its weird

**Comment by tt4g** [comment]
The `SPDLOG_API` macro is defined in `include/spdlog/common.h`.
You have `spdlog/spdlog.h` which fails to compile because the `SPDLOG_API` macro is undefined. However, `spdlog/spdlog.h` first includes `spdlog/common.h` and this inclusion seems to succeed.

https://github.com/gabime/spdlog/blob/d7de159455d0d9bafc999f78139eafddb3935c36/include/spdlog/spdlog.h#L12

In this case, you should assume that `include/spdlog/common.h` is hidden because of the existence of a file named `spdlog/common.h` in the include path of your project.
In this case, rename `spdlog/common.h` in your project.

Or, because another version of spdlog is installed on that machine, `#include <spdlog/common.h>` is not the spdlog of your project, but a header file of the old spdlog installed on your system.
In this case, adjust the include path so that the project's spdlog is loaded in priority to the header files installed on the system.

**Comment by Omernn23** [comment]
@tt4g 
Thanks for your response, but I don't have another version of spdlog, as I didn't install the libspdlog-dev Ubuntu package.
I just downloaded the latest version from the git to my local and than from the remote I use git pull to bring all the spdlog's files.
In the remote I dont have another file called  ```spdlog/common.h```.
This are the files appear - 
![image](https://user-images.githubusercontent.com/98874628/200856525-aaa093ce-8869-40ae-a065-53ccfbe62555.png)
It's looks like it supposed to be, so still stuck.
If it matter so in the remote (where the build failed) I use cmake version 3.24.1
In my local (where the build succeed) I use cmake version 3.24.1 
other than that Its the same code and same CMakefiles
any other suggestion?

**Comment by tt4g** [comment]
You have spdlog installed on your machine (#2528).
Maybe your project can only be built on a machine with spdlog installed.

**Comment by Omernn23** [comment]
I dont have spdlog installed, because I choose the second option from what you suggest - 
1 -Install spdlog on your machine. (I did not install the ubuntu backage)
2 -Or download the source code of spdlog to your project and import spdlog into your project with [add_subdirectory()]
@tt4g

**Comment by tt4g** [comment]
Frankly, I don't have any more tips.
If there is a problem, it is a machine-dependent problem.

**Comment by tt4g** [comment]
BTW, does your project import spdlog with `add_subdirectory(/path/to/spdlog)` and then call `target_link_libraries(<your_target> spdlog)` in `CMakeLists.txt` of your project?

**Comment by Omernn23** [comment]
@tt4g 
yes , I did as we discussed here - https://github.com/gabime/spdlog/issues/2528#issuecomment-1300450934
My CMakeLists contains :
```
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../3rd_party/spdlog ${CMAKE_CURRENT_BINARY_DIR}/spdlog)

if(NOT TARGET spdlog)
  #Stand-alone build
 find_package(spdlog REQUIRED)
endif()

target_link_libraries(${PROJECT_NAME} spdlog::spdlog)
```
I just want to disconnect spdlog repo from it's git . so it will be indipendant.
The wired thing is that when I do clone on the remote and handly remove the .git/, .gitIgnore , .gitAttributes
this works just fine, but this is only for check.
Because I want all the systems will be aligned with the same code. Im writing on my local and from the remote I only do git pull.
So I did  almost the same on my local ( instead of clonning , I download & extract the code & handly remove the.gitIgnore , .gitAttributes files).
But when I do pull this is where I get all the errors

**Comment by tt4g** [comment]
Do you specify a branch or tag when you `git clone`?
The current branch of spdlog is `v1.x`.

```shell
# Clone current branch.
$ git clone -b v1.x https://github.com/gabime/spdlog.git
# Clone latest release.
$ git clone -b v1.11.0 https://github.com/gabime/spdlog.git
```

Occasionally people encounter errors using the `master` branch.
