### ISSUE TITLE
Adding variable to log pattern

### ISSUE THREAD

**Issue by Omernn23** [gabime/spdlog#2546]
Hi I want to add a variable to the log pattern, I want that when I write the log message I also give the variable (lets say - id) , 
and it will print it.
I saw the example of - ```class my_formatter_flag : public spdlog::custom_flag_formatter ```
im not sure it does what I want , I added this class to one of my header files but got the compilation errors:
![image](https://user-images.githubusercontent.com/98874628/201913539-eac6dd1e-0a40-4eaf-bdfe-df946394ce4f.png)
anyway - this what I have:
```
auto max_size = 10 * 1024 * 1024;   
auto max_files = 200;
log_file_name = fmt::format("../logs/log_file_all.txt.{:%Y%m%d_%H:%M:%S}", fmt::localtime(t));
auto log_file_all =std::make_shared<spdlog::sinks::rotating_file_sink_mt>(log_file_name, max_size, max_files);
log_file_all->set_pattern("%^ [%=14n]  [%=8l] [source: %s]    %v%$"); 
     ........
auto logger = std::make_shared<spdlog::logger>(name, sinks.begin(), sinks.end());
logger->set_level(spdlog::level::trace); 
spdlog::register_logger(logger);
```
I would like to write something like this:
```
log_file_all->set_pattern("%^ [%=14n]     **[%id]**     [%=8l] [source: %s]    %v%$"); 
```
and than when I use it in my src file I will do :
```
SPDLOG_LOGGER_INFO(spdlog::get(logger), **id** ,msg);
```
Is there a way to to so?

**Comment by tt4g** [comment]
Linker error reported "multiple definitions of `custom_flags_motor_id()`".
This error is not related to spdlog.

**Comment by gabime** [comment]
Try adding “inline” before the definition of the “custom_flags_motor_id()”

**Comment by Omernn23** [comment]
I overcome the compilation error , but it still doesnt answer my question 
I want to add custom format that each time will use different id.
I use some code from the example:
```
using namespace std;
class my_formatter_flag : public spdlog::custom_flag_formatter
{
public:
    void format(const spdlog::details::log_msg &, const std::tm &, spdlog::memory_buf_t &dest) override
      {std::string some_txt = "custom-flag";
          dest.append(some_txt.data(), some_txt.data() + some_txt.size());
      }
    std::unique_ptr<custom_flag_formatter> clone() const override
        {return spdlog::details::make_unique<my_formatter_flag>();}
};
```
And my current implementation is:
```
log_file_name = fmt::format("../logs/log_file_all.txt.{:%Y%m%d_%H:%M:%S}", fmt::localtime(t));
auto log_file_all =std::make_shared<spdlog::sinks::rotating_file_sink_mt>(log_file_name, max_size, max_files);  
auto formatter = std::make_unique<spdlog::pattern_formatter>();
formatter->add_flag<my_formatter_flag>('*').set_pattern("%^ [%Y-%m-%d %T.%e] [%*] [%=8l] [source: %s]    %v%$");
log_file_all->set_formatter(std::move(formatter));
```

but I get :
![image](https://user-images.githubusercontent.com/98874628/201932063-13ca6f7a-c99e-4bd2-8e88-682671a399e1.png)

and I want to get like I describe above:
when I will use it in my src files I will do :
```
SPDLOG_LOGGER_INFO(spdlog::get(logger), __id__ ,"some message");
```
and I want to see in the log file - 
instead of ``` [custom-flag]```  will be shown ``` [2022-11-15 15:27:14.554] [id] [ trace  ] [source: ...]```

**Comment by tt4g** [comment]
I don`t think you understand how `spdlog::custom_flag_formatter` works.

spdlog calls `format()` when it finds the format pattern `%*` (the following code you wrote).

```cpp
    void format(const spdlog::details::log_msg &, const std::tm &, spdlog::memory_buf_t &dest) override
      {std::string some_txt = "custom-flag";
          dest.append(some_txt.data(), some_txt.data() + some_txt.size());
      }
```

Since this code adds `some_text` to the log message, you will always see `custom-flag` in your log output.
If you want to change this to `__id__`, think of your own way and add `__id__` instead of `some_text` in the `format()` function to the log message.

**Comment by Omernn23** [comment]
I understand how this function works.
My question is if I can transfer this function a variable , than  when spdlog will find the format pattern: ``` %* ```, it will change it within the variable.
I saw example use global variable ' something like:
```
auto str = std::to_string(my_variable);
dest.append(...);
```
but this example taking into account it's a global variable, and I want each time differnt local variable

**Comment by tt4g** [comment]
The formatter never receives more data than the arguments of the function.
Passing of variables other than arguments must be implemented by the developer.

**Comment by Omernn23** [comment]
Ok.
So I tried to get what I want in other way.
I set different pattern to few different sinks (2 files with same pattern and 1 console sink with different pattern)
for the console I set:
```
consoleSink->set_pattern("%^ [%Y-%m-%d %T%e] [%=11n] [%=5l] %v%$");
```
for both of the file I set:
```
log_file_all->set_pattern("%^ [%Y-%m-%d %T.%e] [%=11n] [%=5l] [source: %-26s] %v%$"); 
error_file->set_pattern("%^ [%Y-%m-%d %T.%e] [%=11n] [%=5l] [source: %-26s] %v%$"); 
```
In the console I dont what to see the source file, but I get it anyway. why?

In addition, I have also few loggers that can write to all sinks.
1 of the loggers I tried to changed his pattern - remove the logger name when this logger write:
```
motor_logger->set_pattern("%^ [%Y-%m-%d %T.%e] [%=11n] [%=5l] [%-26s] %v%$");
```
but it apparently remove the logger name from all loggers. why this is happen?
 
@tt4g

**Comment by tt4g** [comment]
> but it apparently remove the logger name from all loggers. why this is happen?

Duplicate this question #2419.

As written in the source code, `spdlog::logger::set_pattern(std::string, pattern_time_type)` changes the pattern of all sinks.

https://github.com/gabime/spdlog/blob/4f800773393d3ebac13c1fcd946a315d4d72bcd9/include/spdlog/logger.h#L318-L326

**Comment by Omernn23** [comment]
but as I wrote above, I didnt wrote ```spdlog::logger::set_pattern```
I set pattern per each sink.

**Comment by tt4g** [comment]
So you are saying that this code is not a logger?

```cpp
motor_logger->set_pattern("%^ [%Y-%m-%d %T.%e] [%=11n] [%=5l] [%-26s] %v%$");
```

In any case, remove `%n` from the pattern if you do not need the logger name.
See Wiki: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

**Comment by Omernn23** [comment]
Yes this is a logger , sorry , 
If I do like you suggest, 
```
auto formatter = std::make_unique<spdlog::pattern_formatter>();
formatter->set_pattern("%^ [%Y-%m-%d %T.%e] [%=8l] [source: %-27s]    %v%$");
motor_logger->set_formatter(std::move(formatter));
```
it removes the name also from the other loggers that writing to the same sink and I dont want this behavior

**Comment by tt4g** [comment]
If you want to use sinks with different formats, create a different sink instance for each logger.

**Comment by Omernn23** [comment]
I want to use the same sink for all the loggers.
Is there a way to costomize the sink , that when he gets logs from specified logger it's format will be different from the rest of the loggers writing to the same sink?

**Comment by tt4g** [comment]
Example implementation of a custom sink: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

You can change the formatting method with `sink_it_(const spdlog::details::log_msg&)`.
Logger names can be accessed with `msg.logger_name`.

However, as I repeatedly tell you, if you want to change the format, you should separate instances of sink.
