### ISSUE TITLE
How to abort the program when outputting error information

### ISSUE THREAD

**Issue by zhoupengwei** [gabime/spdlog#2547]
I thought that when some error messages in the program are detected, the program should stop running at the same time, but the default spdlog output error log, the program will continue to run. for example:
`spdlog::error("Something doesn't exist");`
// Terminate the program while outputting the above error

**Comment by tt4g** [comment]
A simple solution is to use macros.

Example:

```cpp

#define LOG_ERROR(...) { \
    spdlog::error(__VA_ARGS__); \
    std::abort(); \
}

LOG_ERROR("Something doesn't exist");
```

If you are using an asynchronous logger and want to wait for the sink process to finish, use custom sink.
See Wiki:
  - https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink
  - https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#creating-loggers-with-multiple-sinks

```cpp
#include "spdlog/sinks/base_sink.h"

template<typename Mutex>
class on_error_abort : public spdlog::sinks::base_sink<Mutex>
{
...
protected:
    void sink_it_(const spdlog::details::log_msg& msg) override
    {
        if (msg.level >= spdlog::level_enum::err && msg.level < spdlog::level_enum::off) {
            std::abort();
        }
    }

    void flush_() override 
    {

    }
};

#include "spdlog/details/null_mutex.h"
#include <mutex>
using on_error_abort_mt = on_error_abort<std::mutex>;
using on_error_abort_st = on_error_abort<spdlog::details::null_mutex>;
```

Usage:

```cpp
std::vector<spdlog::sink_ptr> sinks;
sinks.push_back(<your_sink>);
sinks.push_back(std::make_shared<on_error_abort_mt>());

auto logger = std::make_shared<spdlog::logger>("name", sinks.begin(), sinks.end());
```

**Comment by zhoupengwei** [comment]
Thank you for your nice reply @tt4g
