### ISSUE TITLE
How to Compile .so instead of .a library

### ISSUE THREAD

**Issue by defencedog** [gabime/spdlog#2548]
I am able to compile static library `.a` but how do I compile (any cmake flags?) shared library `.so`

**Comment by kforeverisback** [comment]
Use CMake flag/option `SPDLOG_BUILD_SHARED=ON` (see [CMakeLIsts.txt@L59](https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L59))

Example shared lib build:
```bash
# Create and cd into $REPO_ROOT/build dir
cmake -DSPDLOG_BUILD_SHARED=ON -DCMAKE_BUILD_TYPE=Release ../
make -j4
```

**Comment by defencedog** [comment]
@kforeverisback can u explain what is `-fPIC` flag? 
https://github.com/thermohub/thermofun/issues/39#issuecomment-1320903633
