### ISSUE TITLE
Too many backtrace start/end logs

### ISSUE THREAD

**Issue by koldi** [gabime/spdlog#2550]
I'm not sure I use this as it should be but right now I'm using a "global" logger which is cloned in every class so every class has an own logger, all sinks are the same and also has different names in different classes. However when I want to use the backtrace feature and no logs added in the specific logger it only logs out the following lines:
1: ****************** Backtrace Start ******************
2: ****************** Backtrace End ********************

I think there should be a check before this that the tracer has any log in it or it is empty. In the latter case I think we should skip this logger and move to the next one. 
My recommendations for this could be any of these:
1: check if tracer has any log in it and if its empty then skip that logger
2: Make tracer public or maybe better to create a getsize function for tracer in the logger or something like this
3: To log these 2 lines should be optional

Can I create a PR for one of these changes? Or do you have any better idea for this or I'm using it wrong?

**Comment by gabime** [comment]
Hi @koldi 

Please create a PR for options #1. It seems to be the simplest

**Comment by koldi** [comment]
> Hi @koldi
> 
> Please create a PR for options #1. It seems to be the simplest

Hi. I've created the PR but it seems there is a failed unit test or something but only on one config? Can it be flaky? Can I restart these builds? I dont see any related changes which indicates a failed test in there.

**Comment by gabime** [comment]
Fixed in pr #2568
