### ISSUE TITLE
Show multiline messages with proper indents?

### ISSUE THREAD

**Issue by zax-ftw** [gabime/spdlog#2552]
The `fmt` output looks correctly but once `spdlog` format is added it looks like this:
``` 
[00:32:48][trace] ┌────────────────────┐
│   Hello, world!    │
└────────────────────┘
[00:32:48][trace]
```
Desired result:
```
[00:32:48][trace] ┌────────────────────┐
                  │   Hello, world!    │
                  └────────────────────┘
[00:32:48][trace]
```

**Comment by tt4g** [comment]
No such feature is available.
However, it may be possible to do it with a custom formatter.

See Wiki: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#extending-spdlog-with-your-own-flags

```cpp
#include "spdlog/pattern_formatter.h"
class my_formatter_flag : public spdlog::custom_flag_formatter
{
public:
    void format(const spdlog::details::log_msg &, const std::tm &, spdlog::memory_buf_t &dest) override
    {
        std::string some_txt = "custom-flag";
        dest.append(some_txt.data(), some_txt.data() + some_txt.size());
    }

    std::unique_ptr<custom_flag_formatter> clone() const override
    {
        return spdlog::details::make_unique<my_formatter_flag>();
    }
};

void custom_flags_example()
{    
    auto formatter = std::make_unique<spdlog::pattern_formatter>();
    formatter->add_flag<my_formatter_flag>('*').set_pattern("[%n] [%*] [%^%l%$] %v");
    spdlog::set_formatter(std::move(formatter));
}
```

Assuming you have specified `%*` as a custom formatter flag, as in the Wiki example, specify this format flag at the end of the format pattern (e.g. `"[%H:%M:%S] [%l] %*"`). Then the `dest` variable should contain the characters except the message and `dest.size()` will be the indent size.

The message is set in `spdlog::details::log_msg.payload`, so split it at the newline character and call `dest.append()` while adding indentation.

**Comment by zax-ftw** [comment]
Using this approach I'm effectively replacing the functionality of `%v` with my custom flag, right?

This is what I've tried so far:
```cpp
void format(const spdlog::details::log_msg& msg, const std::tm&, spdlog::memory_buf_t& dest) override
{
	// characters before the message
	auto indent = dest.size();

	// message
	auto message = msg.payload;

	constexpr std::string_view delim{ "\n" };

	for (const auto word : std::views::split(message, delim)) {
		dest.append(word.data(), word.data() + word.size());
	}
}
```
Gives me this result in log:
```
[01:16:45][trace] ┌────────────────────┐│   Hello, world!    │└────────────────────┘
```
I'm not sure if (and how) I should erase `dest` after first iteration? because if `dest` contains `[01:16:45][trace]` characters 
then I would probably want to call it once then add indent for 2nd and further iterations?

Indent would be `dest.size()` multiplied by `" "` space or its filled automatically be appending more `size`?

**Comment by tt4g** [comment]
It looks like you can declare a variable to determine if iteration is the first, and write the indent to `dest.append()` only after the second iteration.

Maybe just modify it like this:

```diff
    std::string indnet_str = std::string(indent, ' ');
    boolean add_indent = false;
    for (const auto word : std::views::split(message, delim)) {
        if (add_indent) {
            dest.append(indnet_str .data(), indnet_str.data() + indent);
        }
        add_indent = true;

        dest.append(word.data(), word.data() + word.size());
        dest.append(delim.data(), delim.data() + delim.size());
    }
```
