### ISSUE TITLE
Failed to make a spdlog example with vcpkg+cmake+msvc

### ISSUE THREAD

**Issue by KRJackLee** [gabime/spdlog#2554]
I am using vcpkg to manage 3rd-party packages for C++. MSVC, win10. I pulled the latest vcpkg repo and downloaded spdlog 1.11.0. I am using CMakeLists as such to build the basic example in README:
 
```
cmake_minimum_required(VERSION 3.22)
project(main)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_PREFIX_PATH "C:/Program Files/vcpkg/installed/x86-windows/share")

include_directories("C:/Program Files/vcpkg/installed/x86-windows/include")
link_directories("C:/Program Files/vcpkg/installed/x86-windows/lib")

add_executable(${PROJECT_NAME} main.cpp)

find_package(spdlog CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog)
```

Such CMake used to successfully work in linking other packages downloaded with vcpkg. But now it seems to fail in linking `fmt` and maybe other dependencies. I tried to debug it and it returned as such, which seems to be "fail to link a dependencies":

```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'D:\...\C++\cpp\build\main.exe'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ntdll.dll'. 
Loaded 'C:\Windows\SysWOW64\kernel32.dll'. 
Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. 
Loaded 'C:\Windows\SysWOW64\vcruntime140d.dll'. 
Loaded 'C:\Windows\SysWOW64\msvcp140d.dll'. 
Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. 
The program '[16016] main.exe' has exited with code -1073741515 (0xc0000135).
```

Can anybody, especially the ones using MSVC+vcpkg help me on that? Thx.

**Comment by tt4g** [comment]
Is this a vcpkg issue?
If so, I suggest you ask the [vcpkg project](https://github.com/microsoft/vcpkg).

**Comment by KRJackLee** [comment]
> Is this a vcpkg issue? If so, I suggest you ask the [vcpkg project](https://github.com/microsoft/vcpkg).
I tried a clean build from source and it works the example just fine. It should be the issue from vcpkg.

**Comment by KRJackLee** [comment]
> Is this a vcpkg issue? If so, I suggest you ask the [vcpkg project](https://github.com/microsoft/vcpkg).

Is there a chance that my cmake misses some components? I digged into the cmake at root. are there more `.cmake` to include?

**Comment by KRJackLee** [comment]
> Is this a vcpkg issue? If so, I suggest you ask the [vcpkg project](https://github.com/microsoft/vcpkg).

Is there a chance that my cmake misses some components? I digged into the cmake at root. are there more `.cmake` to include?

**Comment by tt4g** [comment]
I don't know how to integrate vcpkg and CMake so I don't have the answer.

**Comment by KRJackLee** [comment]
> I don't know how to integrate vcpkg and CMake so I don't have the answer.

Let's forget the `vcpkg` for now. I think my problem lies at CMake, for which I am completely a noob. In order to `find_package(spdlog)`, does it require include of headers and linkage from both `.lib` and `.dll`? If so, I missed the linkage for DLL in my CMake.

Anyway, I have built spdlog from source with cmake. what should I write, `include_directories`, or `link_directories` or the like, to make `find_package(spdlog)` works? 

```
# Copyright(c) 2019 spdlog authors Distributed under the MIT License (http://opensource.org/licenses/MIT)

cmake_minimum_required(VERSION 3.10)
project(spdlog_examples CXX)

if(NOT TARGET spdlog)
    # Stand-alone build
    find_package(spdlog REQUIRED)
endif()

# ---------------------------------------------------------------------------------------
# Example of using pre-compiled library
# ---------------------------------------------------------------------------------------
add_executable(example example.cpp)
target_link_libraries(example PRIVATE spdlog::spdlog)
```

**Comment by tt4g** [comment]
If you built and installed spdlog with CMake, `find_package(spdlog REQUIRED)` will automatically find spdlog installed on your system.

> **TIP**
> If spdlog is not installed on your system, there is a way to import spdlog projects with `add_subdirectory(/path/to/spdlog-project)`
> See: https://cmake.org/cmake/help/v3.25/command/add_subdirectory.html

The `include_directories()` and `link_directories()` are not required. This is because the include path and linker options are set by `target_link_libraries(example PRIVATE spdlog::spdlog)`.
