### ISSUE TITLE
[Question] Does this library construct any global static resources?

### ISSUE THREAD

**Issue by VelocityRa** [gabime/spdlog#2556]
I want to run my logging initialization function [on program startup](https://stackoverflow.com/a/10897578/3548976) so that my library's users don't have to do it themselves, but this relies on the fact that spdlog doesn't itself do any static construction. Is this the case?
Specifically I'm creating a sink, a logger, set properties on the logger (formatter, level, flush_on, error_handler) and then set the default logger to it.
It _seems_ to work on MSVC but there's no guarantee that I'd be safe from static order initialization fiasco on ie. other compilers.

**Comment by tt4g** [comment]
There is a registry where spdlog manages loggers and thread pools.
This is static variable in method.

https://github.com/gabime/spdlog/blob/50e8b2d982e40266f61b9a0d023c008322c650cb/include/spdlog/details/registry-inl.h#L284-L288

**Comment by VelocityRa** [comment]
@tt4g Hi, yeah I'm aware, but this is a non-global static, it's initialized lazily upon first use, there is no order fiasco like with globals, which are inited before `main()` in an indeterminate order.

**Comment by tt4g** [comment]
Yes, there are no global variables that do not have a scope.
However, under certain conditions, static variables can also cause problems (#2113).

**Comment by VelocityRa** [comment]
Right, I see.
I don't use spdlog (or free spdlog resources) on static destructors so I think the workaround should be fine in my case right? At least not worse than whatever spdlog itself currently does internally.

**Comment by tt4g** [comment]
If it is not used in the destructor, local static variables are unlikely to cause problems.

**Comment by VelocityRa** [comment]
Thank you!
