### ISSUE TITLE
assert: - identifier not found(quaternion.inl)

### ISSUE THREAD

**Issue by fgsoftware1** [gabime/spdlog#2557]
lib compiled without errors.
when i compile my project i'm receiving this error.

includes:
```cpp
#include "include/spdlog/sinks/stdout_color_sinks.h"
#include "include/spdlog/sinks/basic_file_sink.h"
```

platform: windows
IDE: visual studio
P.S: lib compiled with vscode

**Comment by tt4g** [comment]
Try `#include <cassert>` before spdlog headers.

```diff
+#include <cassert>
 #include "include/spdlog/sinks/stdout_color_sinks.h"
 #include "include/spdlog/sinks/basic_file_sink.h"
```

**Comment by fgsoftware1** [comment]
> Try `#include <cassert>` before spdlog headers.
> 
> ```diff
> +#include <cassert>
>  #include "include/spdlog/sinks/stdout_color_sinks.h"
>  #include "include/spdlog/sinks/basic_file_sink.h"
> ```

i had done this before but no success. I've done again and still same

**Comment by tt4g** [comment]
I don't know any more, because if the spdlog library is built, then it is not a spdlog issue.

**Comment by fgsoftware1** [comment]
> I don't know any more, because if the spdlog library is built, then it is not a spdlog issue.

i've built lib and i'm linking on my proj. the probs is on headers not on lib

**Comment by tt4g** [comment]
Remove `#include "spdlog/*` from the project and add `assert(true)`. If you get the same error, then it is not a spdlog problem.

**Comment by fgsoftware1** [comment]
> Remove `#include "spdlog/*` from the project and add `assert(true)`. If you get the same error, then it is not a spdlog problem.

i'm not including this file specified on error. this file is included in some spdlog headers

**Comment by tt4g** [comment]
By "this file" do you mean `quaternion.inl`?
If so, such a file does not exist in spdlog.

In any case, spdlog also uses `assert`, but if you are able to build, it is unlikely to be a spdlog problem.

If you need help, please provide the full error message and the minimal code that can reproduce the error.

**Comment by fgsoftware1** [comment]
> By "this file" do you mean `quaternion.inl`? If so, such a file does not exist in spdlog.
> 
> In any case, spdlog also uses `assert`, but if you are able to build, it is unlikely to be a spdlog problem.
> 
> If you need help, please provide the full error message and the minimal code that can reproduce the error.

oh! i figured out, it's a GLM file not spdlog.
