### ISSUE TITLE
'fmt::v9::detail::arg_mapper<context>::map': deprecated		

### ISSUE THREAD

**Issue by ilyachastikov** [gabime/spdlog#2560]
Hello. After updating on spdlog v 1.11.0 I had the error C4996 in VS2022 'fmt::v9::detail::arg_mapper<context>::map': deprecate in line 1735 of core.h header. After remove FMT_DEPRECATED macro in line 1470 this problem had gone. I've used C++20 in settings.

**Comment by tt4g** [comment]
`fmt::v9::detail::arg_mapper<context>` is from the fmt library.
This warning is due to a change in the way custom formatters are defined in fmt version 9 (fmtlib/fmt#3183).

**Comment by icegull** [comment]
> After remove FMT_DEPRECATED macro in line 1470 this problem had gone.

Nice. This solution is useful for me. Today the enum can't be compiled in the spdlog, I can't cast all enum to int to log, it's so stupid..
