### ISSUE TITLE
`sink::should_log` can be virtual?

### ISSUE THREAD

**Issue by YunchengLiu** [gabime/spdlog#2561]
I want to use the library to construct a simple async message queue, all provided facilities seems to be customizable. But I want to know how to make a sink only accepts specific level's messages?

I can inhert from `base_sink` class, and write my sink class, but `should_log` method is not virtual.

As a simple message queue sink , i just want to integrate it into my global logger(also constructed from this library).

And only the INFO and WARN messages are sinked by this message queue sink (they may be displayed in a QTextBrowser etc..), other global logger's sinks are work as same. 

At present, the method I adopt is to maintain a separate logger and several sinks independently of the global logger But in many places, I may need to record the same information twice to distribute them to different loggers.

So, the [sink::should_log](https://github.com/gabime/spdlog/blob/50e8b2d982e40266f61b9a0d023c008322c650cb/include/spdlog/sinks/sink.h#L23) can be virtual? or there is another solution?

**Comment by tt4g** [comment]
Another solution is to use `spdlog::base_sink::sink_it_()` to accept only a specific log level.

The logger calls `[A](spdlog::sink::log())` after `spdlog::sink::should_log()`, but there is no rule that `spdlog::sink::log()` must accept the log.

https://github.com/gabime/spdlog/blob/50e8b2d982e40266f61b9a0d023c008322c650cb/include/spdlog/logger-inl.h#L178-L196

https://github.com/gabime/spdlog/blob/50e8b2d982e40266f61b9a0d023c008322c650cb/include/spdlog/sinks/base_sink-inl.h#L25-L30

**Comment by gabime** [comment]
`should_log()` is not virtual by design, since it is in the hottest path.

**Comment by YunchengLiu** [comment]
Thanks @gabime @tt4g , i will try
