### ISSUE TITLE
get data from ostream_sink_mt

### ISSUE THREAD

**Issue by Omernn23** [gabime/spdlog#2564]
Im tring to get ostringstream data in the file it is first declared but somehow I cannot get it, something Im missing??
I have file called log.h that contains a few macros somting like:
```
#define LOG_TRACE(logger_name, msg, ...)      {SPDLOG_LOGGER_TRACE(spdlog::get(logger_name), msg, ##__VA_ARGS__);}
```
and in all the files within the project  that I want to use the logs, I just include ```log.h``` header and use the macros.

Now I want that once I use the macro in the code, it also send the logs through mqtt, so I decided to use ```ostream_sink_mt```
I have file called logger.cpp which includes ```log.h``` header and contains the functions :
```
std::ostringstream oss;
void Logger::logInit(){
    auto ostream_sink = std::make_shared<spdlog::sinks::ostream_sink_mt> (oss);
    ostream_sink->set_pattern("%^ [%Y-%m-%d %T%e] [%=5l] [%=11n] %v%$");
    ....
    sinks.push_back(ostream_sink);
    ....
    auto logger = std::make_shared<spdlog::logger>(name, sinks.begin(), sinks.end());
}

int Logger::sendToConsole() {
	std::string result = oss.str();
       cout << "result "   << result << endl;  // just for checking - return nothing ; (result= "")
        ..... some code that publish result within mqtt to a topic
	oss.str("");
	result = oss.str();	
	return 1;
}
```
The problem I have is that - ```result``` is an empty string in ```Logger::sendToConsole()``` function but when I do same function in another file that include  ```logger.hpp``` header, the ```result``` var is not empty.
so my question are:
1- How can I get ostringstream data in logger.cpp file ?
2- How can I use the macro such that in addition to call the logger, it will also call ```Logger::sendToConsole() ```?

B.T.W - I was looking in older issues such : https://github.com/gabime/spdlog/issues/1316 - it didnt help me

**Comment by tt4g** [comment]
Could you please organize your questions better?
 The name `logger.hpp` suddenly appeared, what is it? I don't understand what the problem is.

**Comment by tt4g** [comment]
Answer the question without understanding the question correctly. The answer may be wrong.

First of all `#include` is just copy and paste. Think of it as simply copying the specified header file to that location.
Every time `#include "log.h";` is written, `std::ostringstream oss;` will be copied into that source code.

The `oss` variable is newly declared in that source code and is not shared with other source code.
If your project is a separate executable application, the `oss` variable will not be shared since it is an independent variable declared for each application.

If you want the `oss` variable to be shared by multiple applications, declare it in the `.cpp` file, not in a header file.

---

> 2- How can I use the macro such that in addition to call the logger, it will also call `Logger::sendToConsole()` ?

Do you mean you want to write a macro that calls multiple functions?
By writing `\` at the end, the next line is also recognized as a macro.

https://stackoverflow.com/questions/10419530/multi-line-preprocessor-macros

**Comment by Omernn23** [comment]
@tt4g First of all thanks for the response
I will try to explain bettter:
I have in ```logger.hpp``` declaration of ```std::ostringstream oss;``` 
and in ```logger.cpp``` I have:
```
void Logger::init(){
    auto ostream_sink = std::make_shared<spdlog::sinks::ostream_sink_mt> (oss);
    ostream_sink->set_pattern("%^ [%Y-%m-%d %T%e] [%=8l] [%=11n] %v%$");
    ostream_sink->set_level(spdlog::level::debug);
    ....
    sinks.push_back(ostream_sink);
    ....
    spdlog::flush_every (std::chrono::seconds(5));
}

int Logger::sendToConsole() {
    std::string result = oss.str();
    const char* pubmsg = result.c_str();
    if (strlen(pubmsg) != 0){
    MQTTClient_publish(log_client, LOGGER_TOPIC, strlen(pubmsg) ,pubmsg, 1, false, NULL;
    oss.str("");
    result = oss.str();	
    return 1;
}
```
I'm using mqtt to send logs to another process, and each time a log msg is sent, I want the ```oss``` buffer will be cleaned (so that msg that already sent, will not be sent again.
Now I was able to get it to work with the condition ```if (strlen(pubmsg) != 0)```  and result variable.
and im asking:
Is there anothere way to clean the buffer? so that I will not use the condition and result variable??
When I was debugging I saw that without the condition, the oss buffer keep getting empty msgs and the project does not respond correctly.
I was tring to use also in flush but couldn't make it work with this. (I have also another sinks )

**Comment by tt4g** [comment]
The first thing to understand is that `spdlog::sinks::ostream_sink` is API for working with streams, but it is the developer responsibility to manage the streams (`oss` variables) correctly.
The access control requirements for the `oss` variable depend on your project requirements. Since you have not provided your project requirements, I cannot responsibly answer your question.

Still, I dare to answer you that the idea of using a buffer like `oss` is wrong. Unless buffering is a requirement, it is much easier to create a custom sink and send messages directly to MQTT (if you are encountering a bug because you used a buffer when it was not required, you should consider removing it.).

Example (It will not work, you will need to develop your own implementation.):

```cpp
#include "spdlog/sinks/base_sink.h"
#include "spdlog/details/null_mutex.h"
#include <mutex>

template<typename Mutex>
class mqtt_sink : public spdlog::sinks::base_sink <Mutex>
{
public:

     mqtt_sink(...) : {
        // Initialize MQTT client.
     }

protected:
    void sink_it_(const spdlog::details::log_msg& msg) override
    {
    spdlog::memory_buf_t formatted;
    spdlog::sinks::base_sink<Mutex>::formatter_->format(msg, formatted);

    MQTTClient_publish(log_client, LOGGER_TOPIC, formatted.size(), formatted.data(), 1, false, NULL);
    }

    void flush_() override 
    {

    }
};

using mqtt_mt = mqtt_sink<std::mutex>;
using mqtt_st = mqtt_sink<spdlog::details::null_mutex>;
```

See Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by Omernn23** [comment]
@tt4g 
Buffering is not a requirement.
The requirement is that every log msg will be save in a file and will be published through mqtt to another proccess.
fot this I declare 2 sinks :
1 from kind ```spdlog::sinks::rotating_file_sink_mt```
and 1 from kind ```spdlog::sinks::ostream_sink```

**Comment by tt4g** [comment]
> Buffering is not a requirement.

So, please create a custom sink and replace it with `spdlog::sinks::ostream_sink` as per the previous comment.

**Comment by Omernn23** [comment]
I followed your advice.
In ```logger.hpp``` I wrote another class:
```
template<typename Mutex>
class mqtt_sink : public spdlog::sinks::base_sink <Mutex>
{
public:
    void mqtt_sink()
    { 
       ....
       MQTTClient_create(...)
       MQTTClient_connect(...)
    }
    mqtt_sink(const &mqtt_sink) = delete;
    mqtt_sink(mqtt_sink&&) = delete;
    mqtt_sink& operator=(const mqtt_sink&) = delete;
    mqtt_sink& operator=(mqtt_sink&&) = delete;

protected:
    void sink_it_(const spdlog::details::log_msg &msg) override
    {
        spdlog::memory_buf_t formatted;
        spdlog::sinks::base_sink<Mutex>::formatter_->format(msg, formatted); 
        MQTTClient_publish(log_client, LOGGER_TOPIC, formatted.size(), formatted.data(), 1, false, NULL)
        
    }

    void flush_() override 
    {
          // ????
    }
    using mqtt_sink_mt = mqtt_sink<std::mutex>;
    using mqtt_sink_st = mqtt_sink<spdlog::details::null_mutex>;
};
```
I have 3 question :
1- I want to use it, in ```logger.cpp``` in function ```void Logger::init()``` as I wrote above https://github.com/gabime/spdlog/issues/2564#issuecomment-1346249233
I added:
```
auto log_file =std::make_shared<spdlog::sinks::rotating_file_sink_mt>(log_file_name, max_size, max_files);
auto sink_mqtt = std::make_shared<spdlog::sinks::mqtt_sink_mt>();
sinks.push_back(log_file);
sinks.push_back(sink_mqtt);
auto my_logger = std::make_shared<spdlog::logger>(name, sinks.begin(), sinks.end());
```
but I get the error - ```namespace "spdlog::sinks" has no member "mqtt_sink_mt"```
what am I doing wrong?
2 - what should I write in the flush function if in  ```void Logger::init()```  function I write 
```spdlog::flush_every (std::chrono::seconds(5));``` ?
Is the flush fuction still relevant in ```class mqtt_sink```
3 - I want the same format of log msg both in the file and the msg sent via mqtt so is the line ```spdlog::sinks::base_sink<Mutex>::formatter_->format(msg, formatted); ``` answer this?
@tt4g

**Comment by tt4g** [comment]
The error message `namespace "spdlog::sinks" has no member "mqtt_sink_mt"` says it all.

Why do you specify the namespace `spdlog::sinks`? The `mqtt_sink` belongs to your project's namespace.

**Comment by tt4g** [comment]
> 2 - what should I write in the flush function if in void Logger::init() function I write
spdlog::flush_every (std::chrono::seconds(5)); ?
> Is the flush fuction still relevant in class mqtt_sink

Do you mean what to write in `mqtt_sink::flush()`? If so, move `MQTTClient_publish(log_client, LOGGER_TOPIC, formatted.size(), formatted.data(), 1, false, NULL)` to the flush operation only if you want to delay sending messages to MQTT until the flush is called. The message to be sent should be buffered in `std::vector<std::string>`.

> 3 - I want the same format of log msg both in the file and the msg sent via mqtt so is the line spdlog::sinks::base_sink<Mutex>::formatter_->format(msg, formatted); answer this?

Right.

**Comment by Omernn23** [comment]
First of all thank you very much, you helped a lot !!!

I dont want to delay the messages sending  to MQTT , so I left the ```MQTTClient_publish``` in ```mqtt_sink::sink_it_()``` function. And the ```mqtt_sink::flush()``` I left empty.

thanks
@tt4g
