### ISSUE TITLE
Can spdlog support uart output

### ISSUE THREAD

**Issue by npulrj** [gabime/spdlog#2566]
I want create a multiple log, and hope it can mix output from console, file and a 422 serial uart port.
So I wonder can spdlog support uart output. If support, is there any samples? If not support, is there any advices on how to improve spdlog to support it, such as Secondary development on spdlog.
Thanks a lot!

**Comment by tt4g** [comment]
UART support is not available.

It is possible to create a custom sink.
Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by npulrj** [comment]
OK，thanks！
