### ISSUE TITLE
No output in log file when msg is less

### ISSUE THREAD

**Issue by npulrj** [gabime/spdlog#2567]
I am using a mt rotating log file, and set period flush, as belowing code:

`
    
    
    auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    console_sink->set_level(spdlog::level::warn);
    console_sink->set_pattern("[%Y-%m-%d %H:%M:%S.%e %^%l%$] %v");

    auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/Log.txt", 1048576 * 10, 10);
    file_sink->set_level(spdlog::level::trace);
    file_sink->set_pattern("[%Y-%m-%d %H:%M:%S.%e %L] %v");

    spdlog::logger * pLogger = new spdlog::logger("multi_sink", {console_sink, file_sink});
    pLogger->set_level(spdlog::level::debug);

    // Flush all *registered* loggers using a worker thread every 3 seconds.
    // note: registered loggers *must* be thread safe for this to work correctly!
    spdlog::flush_every(std::chrono::seconds(3));

`

but I find when the output log msg is less, not output to log file, and when many log msgs arrived, it can output.
so is there any setting missed or any problem with it?
thanks a lot?

**Comment by tt4g** [comment]
The OS buffers I/O in memory, so writing to a file may not complete if data is low.
A flush operation can force a write, but any data buffered before the flush is called is discarded at the exit of the process.

Call `spdlog::shutdown()` just before the process exits (at the end of `main()`).

**Comment by tt4g** [comment]
I notice that you have not registered your logger with the spdlog registry.
Call `spdlog::register_logger()` to register the logger. Otherwise, it will not be subject to flush operation by `spdlog::flush_every()`.

**Comment by npulrj** [comment]
> I notice that you have not registered your logger with the spdlog registry. Call `spdlog::register_logger()` to register the logger. Otherwise, it will not be subject to flush operation by `spdlog::flush_every()`.

OK，I will try it
