### ISSUE TITLE
crash if log file in special path

### ISSUE THREAD

**Issue by jezzhu** [gabime/spdlog#2571]
https://user-images.githubusercontent.com/13492095/206466728-02c9cc8b-4fa7-40ce-85b0-b0d4d5b13e83.png

program start, and crash。 no log files be generated.

**Comment by jezzhu** [comment]
路径有 “雷神加速器体验版” 程序启动就会崩， 如果是  “雷神” 不会。 

比如  d:\雷神加速器体验版\xxxxxx\main.exe 会崩，  d:\雷神\xxxxxx\main.exe  不会崩

**Comment by tt4g** [comment]
The log file path must be a string that the system can accept.
It is the developer's responsibility to pass the correct path.

**Comment by tt4g** [comment]
Similar issue #2510.

**Comment by jezzhu** [comment]
ok, 3q, I resolve it， use  define  SPDLOG_WCHAR_FILENAMES  and log path use  wstring....  Or  use relativepath simplely.
