### ISSUE TITLE
Fix project details on comparison websites

### ISSUE THREAD

**Issue by pietrom16** [gabime/spdlog#2581]
Some comparison website have incorrect details about the spdlog project.
E.g., the [https://cpp.libhunt.com/spdlog-alternatives](https://cpp.libhunt.com/spdlog-alternatives) site has wrong licence details (GPL instead of MIT) and no references to the repository. I fixed this, waiting for the fix to be approved. 

I would suggest to check other comparison websites.

**Comment by gabime** [comment]
Thanks! Seems they fixed it.
