### ISSUE TITLE
Spdlog LNK4006 when trying to link staticly

### ISSUE THREAD

**Issue by DrMondGnu** [gabime/spdlog#2583]
I downloaded the package with vcpkg( spdlog:x64-windows-static ) and im including the header files aswell as linking the lib file.

**My question**
Is it normal to get those LNK4006 redefinition warnings due to spdlog actually being a header only library?

**Comment by tt4g** [comment]
The `SPDLOG_COMPILED_LIB` macro must be defined when using the compiled library.

And this sounds like a vcpkg issue and should be asked in [vcpkg repository](https://github.com/microsoft/vcpkg).

**Comment by DrMondGnu** [comment]
Seems to be the solution. Thank You!
