### ISSUE TITLE
Unable to enumerate active loggers

### ISSUE THREAD

**Issue by ekmett** [gabime/spdlog#259]
I'd like to be able to enumerate all of the loggers in the registry to do things like force them all to flush, right now, before doing something dangerous.

However, `registry_t` hides away `_loggers`.

**Comment by godbyk** [comment]
See also https://github.com/gabime/spdlog/issues/180.

**Comment by gabime** [comment]
Implemented in 3af247fbd3b23b393197b3ac0afbd3f9ac0781f3

**Comment by ekmett** [comment]
Awesome, thanks!
