### ISSUE TITLE
Is the spdlog::set_formatter method multi-thread safe?

### ISSUE THREAD

**Issue by trzeciak** [gabime/spdlog#2591]
I'm using spdlog in a multi-threaded application.
At runtime, I want to update the formatter (`spdlog::set_formatter`).

Recently I was using version 0.14.0 and there this `spdlog::set_formatter` method was not thread safe.

The workaround I used was to replace the `shared_ptr<spdlog::pattern_formatter>` destructor and dealloc `spdlog::pattern_formatter` asynchronously one second later (ugly but it worked).
In the current version 1.11.0 the `spdlog::set_formatter` api has been changed to require `unique_ptr`.
And now I can't pass `std::unique_ptr` to `spdlog::set_formatter` with custom destructor.

### Is the `spdlog::set_formatter` method multi-thread safe in the current version?

The crash happened when I set new one formatter in one thread and another thread using the older formatter to print some logs.

**Comment by gabime** [comment]
As long as you use thread safe sinks, and not changing the loggers’ sinks vector concurrently, it should be thread safe.

**Comment by trzeciak** [comment]
Hm.. I will try to prepare a simple example to clearly show what exactly I mean.

**Comment by trzeciak** [comment]
Okay, everything seems to be working, great 👍 sorry for the confusion

----

BTW: The code crashes in previous version:

```cpp
//
//  main.cpp
//  spdlog-0.14.0
//

#include <iostream>
#include <thread>
#include <chrono>
#include <mutex>

#include <spdlog/spdlog.h>

std::mutex g_display_mutex;

void adjuster() {

    auto logger = spdlog::stdout_color_mt("adjuster");

    for (int i = 0; i < 1000; ++i) {

        if (i % 2) {
            spdlog::set_formatter(std::make_shared<spdlog::pattern_formatter>("[%t] %H:%M.%e %n / %v"));
        }
        else {
            spdlog::set_formatter(std::make_shared<spdlog::pattern_formatter>("[%t] %H:%M.%e %n \\ %v"));
        }
    }
}

void talker() {

    static int no = 1;

    g_display_mutex.lock();
    auto logger = spdlog::stdout_color_mt("talker(" + std::to_string(no++) + ")");
    g_display_mutex.unlock();

    for (int i = 0; i < 1000; ++i) {

        logger->info("Welcome to spdlog!");
        logger->error("Some error message with arg{}..", 1);
    }
}

int main(int argc, const char * argv[]) {

    auto logger = spdlog::stdout_color_mt("main");

    logger->info("Hello, World!");

    spdlog::set_pattern("[%t] %H:%M.%e %n | %v");

    std::thread t1(talker);
    std::thread t2(talker);
    std::thread t3(talker);
    std::thread t4(talker);

    std::thread a0(adjuster);

    a0.join();

    t1.join();
    t2.join();
    t3.join();
    t4.join();

    logger->info("Bye.");

    return 0;
}
```

**Comment by gabime** [comment]
> BTW: The code crashes in previous version

Using the old 0.x branch. Thats expected.
