### ISSUE TITLE
sometimes，export json has bug

### ISSUE THREAD

**Issue by zxz970104** [gabime/spdlog#2592]
string s = "{\"nlu\":{\"input\":\"suzhou\",\"res\":\"aicar.0.8.16\",\"semantics\":{\"request\":{\"slotcount\":3,\"slots\":[{\"name\":\"intent\",\"value\":\"daohang\"},{\"name\":\"start\",\"pos\":[1,2],\"rawpinyin\":\"su zhou\",\"rawvalue\":\"number\",\"value\":\"suzhou\"},{\"name\":\"destination\",\"pos\":[3,5],\"rawpinyin\":\"bei jing\",\"rawvalue\":\"beijing\",\"value\":\"beijing\"}],\"task\":\"daohang\"}},\"skill\":\"SK_1\",\"skillId\":\"10000000289\",\"systime\":17.782958984375,\"version\":\"2017.2.13.16:38:28\"}}";
    cout << s << endl;
    
    mylog.Logger->info(s);

the cout can print right but logger ：
[*** LOG ERROR #0001 ***] [2023-01-03 19:21:49] [cdmserver] {unmatched '}' in format string}

**Comment by tt4g** [comment]
Curly braces (`{`, `}`) are considered the format syntax of the [fmt library](https://github.com/fmtlib/fmt).

Do not pass a dynamic string to a logger method.
The dynamic string must be part of the format string.

```diff
 string s = "{\"nlu\":{\"input\":\"suzhou\",\"res\":\"aicar.0.8.16\",\"semantics\":{\"request\":{\"slotcount\":3,\"slots\":[{\"name\":\"intent\",\"value\":\"daohang\"},{\"name\":\"start\",\"pos\":[1,2],\"rawpinyin\":\"su zhou\",\"rawvalue\":\"number\",\"value\":\"suzhou\"},{\"name\":\"destination\",\"pos\":[3,5],\"rawpinyin\":\"bei jing\",\"rawvalue\":\"beijing\",\"value\":\"beijing\"}],\"task\":\"daohang\"}},\"skill\":\"SK_1\",\"skillId\":\"10000000289\",\"systime\":17.782958984375,\"version\":\"2017.2.13.16:38:28\"}}";
 cout << s << endl;

-mylog.Logger->info(s);
+mylog.Logger->info("{}", s);
```

**Comment by zxz970104** [comment]
origin code is：
mylog.Logger->info("input last = {} ", input_obj->input_data->dump());
but it has [*** LOG ERROR https://github.com/gabime/spdlog/issues/1 ***] [2023-01-03 19:21:49] [cdmserver] {unmatched '}' in format string}

so I change it to  ： mylog.Logger->info(s);
but it doesn't work

**Comment by zxz970104** [comment]
if I flush it:
    mylog.Logger->info("input last = {} ", input_obj->input_data->dump());
    mylog.Logger->flush();
the data can be export right, but the fault is exist too.

**Comment by tt4g** [comment]
It is simply that the same error occurs because the same mistake is made elsewhere in the source code.
Check all the places in the source code where the logger is used.

**Comment by zxz970104** [comment]
**mylog is defined as follow:**

class myLog
{
	public:
		myLog(){
		
	            Logger = spdlog::daily_logger_mt("cdmserver", "logs/cdmserver.txt", 2, 30);
		    Logger->set_level(spdlog::level::debug);

                };
	public:
		std::shared_ptr<spdlog::logger> Logger = nullptr;
};

extern myLog mylog;

#endif




**if I write like this:**
mylog.Logger->debug("input last = {0} ", input_obj->input_data->dump());
mylog.Logger->debug("proc_select_intent");

**the output is:**
[2023-01-03 22:34:35.549] [cdmserver] [debug] input last = {"nlu":{"input":"从苏州导航去北京","res":"aicar.0.8.16","semantics":{"request":{"slotcount":3,"slots":[{"name":"intent","value":"导航"},{"name":"起点名称","pos":[1,2],"rawpinyin":"su zhou","rawvalue":"苏州","value":"苏州"},{"name":"终点名称","pos":[3,5],"rawpinyin":"bei jing","rawvalue":"北京","value":"北京"}],"task":"�

**the "proc_select_intent" has not be writed to the file;** 
and before  **mylog.Logger->debug("input last = {0} ", input_obj->input_data->dump())**   ,some json-string have been logged right.


**I have checked all my source code.(it only has 30+ log)**

**Comment by tt4g** [comment]
Has this changed to a new question about messages not outputting to the file? If so, please open a new issue or first let me know that the question has changed. It confuses our respondents.

There have been a several questions about log messages not being written to a file (#2502, #2567).
And the Wiki also has a Flash Policy page: https://github.com/gabime/spdlog/wiki/7.-Flush-policy

Call `spdlog::shutdown()` or `spdlog::logger::flush()` just before your application exits.

**Comment by zxz970104** [comment]
if  I call spdlog::shutdown() or spdlog::logger::flush(), the log can be writed, but after the flush coommand, all the remainning log can not be writed. it seems like that the buffer was filled。

if I delete the log of input last : 
more logs has been writed,and end later
[2023-01-04 14:45:46.918] [cdmserver] [debug] same_name_table = null
[2023-01-04 14:45:46.918] [cdmserver] [debug] commplete pro_select_intent
[2023-01-04 14:45:46.918] [cdmserver] [debug] norm impleted
[2023-01-04 14:45:46.919] [cdmserver] [debug] get_count, count is not exist
[2023-01-04 14:45:46.919] [cdmserver] [debug] nlu feed task name: 导航, intent: 导航, state_ret: 
[2023-01-04 14:45:46.919] [cdmserver] [debug] Policy cus_output: {"api":"http://172.16.20.

**Comment by tt4g** [comment]
There is no guarantee that log messages will be written to a file after calling `spdlog::shutdown()`.

**Comment by zxz970104** [comment]
But I can't unserstand why the log ended at  **mylog.Logger->debug("input last = {0} ", input_obj->input_data->dump())**, is that caused by the buffer?

**Comment by tt4g** [comment]
Right.
The OS tries to reduce the number of I/O by buffering writes to files. And this buffering is the cause.
The Linux OS flushes all buffers to a file when the process exits. However, Windows OS seems to discard the buffer data.

**Comment by zxz970104** [comment]
Thanks very much for your answer! ><

**Comment by roxroxroxrox** [comment]
> 
try validate your buffer data first, you can wrapper a validator class.
IMO, arch of spdlog seperates the file IO from internal buffer handler to archieve higher performance,

you bug looks like your raw buffer contains misformat data, which cause logger cannot seperate valid date segment to sinks.

BTW:
navi apps should use some time-sequence DB to store theses kind of info, not spdlog : )
