### ISSUE TITLE
Win eventlog sink event ID type in constructor is incorrect.

### ISSUE THREAD

**Issue by Tagl** [gabime/spdlog#2596]
In the constructor of win_eventlog_sink the type for `event_id` is WORD but should be DWORD according to the eventlog API.

https://github.com/gabime/spdlog/blob/287a00d364990edbb621fe5e392aeb550135fb96/include/spdlog/sinks/win_eventlog_sink.h#L261

**Comment by tt4g** [comment]
PR is welcome.
