### ISSUE TITLE
pattern formatting bug when using padding

### ISSUE THREAD

**Issue by bachittle** [gabime/spdlog#2601]
I have been tinkering with spdlog, and I found an interesting bug related to padding in pattern formatting.

refer to https://github.com/gabime/spdlog/compare/v1.x...bachittle:spdlog:pattern_formatting_bug. Test cases fail when the pattern is changed from "%v [%10!]" to "%v [%10!v" since it prints the message via v flag at the end, even though the format string should be like this to have that functionality: "%v [%10!%v". 

potential fixes include going back to the beginning after padding code has been executed.

**Comment by tt4g** [comment]
The fix for #1617 seems to be the current behavior.

The following comments suggest that this is an intentional behavior (934a9bb23ea2bf24d29a23e5f89fe013fa674c85):

```c++
         // fix issue https://github.com/gabime/spdlog/issues/1617 (prev char was '!' and should have been treated as funcname flag instead of truncating flag)
        // spdlog::set_pattern("[%10!] %v") => "[      main] some message"
        // spdlog::set_pattern("[%3!!] %v") => "[mai] some message"
```

**Comment by bachittle** [comment]
ok, so it just seems to be due to a flawed design choice where the truncate flag and the function flag are the same. I don't know if it is possible to change this to something else without breaking legacy code. It just limited my ability to add custom pattern flags, since the flag that I used ']' matched when it wasn't supposed to in this test case.

**Comment by gabime** [comment]
Right. Unfortunately it is a bug in the format specification. I don't know how this could be fixed without breaking existing code.
