### ISSUE TITLE
visit_format_arg forces formatting of 'long double'

### ISSUE THREAD

**Issue by j8asic** [gabime/spdlog#2602]
The `visit_format_arg` function in `core.h` always tries to format `long_double_type`, which creates compile errors when long double math is disabled (sometimes we have `FMT_USE_FLOAT128=0` because there are no implementations of those math functions e.g. for CUDA under libc++). So this case should be treated similar like for `int128_type` case is treated using `FMT_USE_INT128`. I.e. `FMT_USE_FLOAT128` should be checked and taken into account.

**Comment by tt4g** [comment]
The sources saved in the directory `include/spdlog/fmt/bundled/` are from the fmt library, please move the issue to the [fmt project](https://github.com/fmtlib/fmt).

**Comment by j8asic** [comment]
Thanks I completely missed. I tried reporting it previously here https://github.com/fmtlib/fmt/issues/3106 , now I added more description there
