### ISSUE TITLE
Does spdlog have the ability to call fsync?

### ISSUE THREAD

**Issue by cpp977** [gabime/spdlog#2605]
I am using spdlog on a high perfomance computing centre where the compute jobs are managed by sun grid engine.
I found that the `std::fflush()` is not sufficient to get all the contents written to the logfile. Only with `fsync(fileno(fileptr))`, the content get written. Is there any support in spdlog to call `fsync`? I saw that this was mentioned in issue #884.

**Comment by tt4g** [comment]
You cannot easily add `fsync()` calls.
In theory, it only calls `fsync()` after `file_helper::flush()`, but `basic_file_sink` is `final class`.

https://github.com/gabime/spdlog/blob/05e3a73b162705b37ed464ceb4644addfb03f25b/include/spdlog/sinks/basic_file_sink-inl.h#L37-L41

https://github.com/gabime/spdlog/blob/05e3a73b162705b37ed464ceb4644addfb03f25b/include/spdlog/sinks/basic_file_sink.h#L20

We would either have to change the spdlog code or add `fsync()` calls in a way that does not extend the existing file sinks.

If you want the spdlog code to make `fsync()` calls, I think you could open a PR like #2343 and suggest calling `fsync()` at the end of the `file_helper::flush()` function.

Another way, create a custom sink with the same implementation as `basic_file_sink`.
This custom sink can be customized to call `fsync()` after `custom_sink::flush()`.
See the Wiki for how to create a custom sink: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by cpp977** [comment]
Thanks for the tips!
Is it correct that the PR #2343 got closed only because it was not needed?
Or was there some issue with the proposed implementation?

**Comment by gabime** [comment]
As far as i remember it just added fsync support for the internal layer, with no option to use it from user code
