### ISSUE TITLE
Integer constant overflow

### ISSUE THREAD

**Issue by albert-github** [gabime/spdlog#2607]
https://github.com/gabime/spdlog/blob/f29f369a12c701db27e816c6762e914863e8e951/include/spdlog/fmt/bundled/format-inl.h#L1153-L1154

Won't this overflow, I got on Windows, 32-bit, some warnings about it:
```
...\deps\spdlog\include\spdlog\fmt\bundled\format-inl.h(1154): warning C4307: '*': integral constant overflow
...\deps\spdlog\include\spdlog\fmt\bundled\format-inl.h(1186): warning C4307: '*': integral constant overflow
..\deps\spdlog\include\spdlog\fmt\bundled\format-inl.h(1207): warning C4307: '*': integral constant overflow
```

**Comment by gabime** [comment]
This code is part of [fmtlib](https://github.com/fmtlib/fmt). Please re open the issue there

**Comment by albert-github** [comment]
Created issue for it:https://github.com/fmtlib/fmt/issues/3274

**Comment by albert-github** [comment]
The issue https://github.com/fmtlib/fmt/issues/3274 has been fixed
