### ISSUE TITLE
Rotating file sink rotate_() exception

### ISSUE THREAD

**Issue by pdx-lazer** [gabime/spdlog#2609]
Hi, I was looking at an issue with the rotating file sink `rotate_()` function throwing an exception on win due to the file being locked by another process.

Googling the issue revealed some old similar reports, and I noticed there's an attempt to fix it with the sleep in `rotate_()` but it can fail on the second rename attempt as well (an easy repro is to run two instances of a program logging frequently to the same rotating files).

It looks like copying the file instead solves it for me (requires std::filesystem, but maybe you can implement copy in os.h?):

``` c++
	// Rotate files:
	// log.2.txt -> log.3.txt (log.3.txt content lost)
	// log.1.txt -> log.2.txt
	// log.txt -> log.1.txt (log.txt now empty)
	template <typename Mutex>
        SPDLOG_INLINE void rotating_file_sink<Mutex>::rotate_()
	{
               using details::os::filename_to_str;
               using details::os::path_exists;  

		file_helper_.close();
		for ( auto i = max_files_; i > 0; --i )
		{
			filename_t src = calc_filename( base_filename_, i - 1 );
			if ( !path_exists( src ) )
			{
				continue;
			}
			filename_t target = calc_filename( base_filename_, i );

			if ( !rename_file_( src, target ) )
			{
				// Copy the file instead (src will either be moved/copied to in the next iteration or reopened below)
				std::filesystem::copy( src, target, std::filesystem::copy_options::overwrite_existing ); // "throws filesystem::filesystem_error on underlying OS API errors"
			}
		}
		file_helper_.reopen( true );
	}
```

**Comment by tt4g** [comment]
Who is locking the files?
Exclusive file lock is an operation performed to prevent another process from being allowed to modify a file.
The scene of exclusive locking on log files is a bit unpredictable.

And copying is not safe either because the Windows OS has a file lock mode that prohibits reads.
