### ISSUE TITLE
how to modify log filename on rotating_file_sink 

### ISSUE THREAD

**Issue by diandianzz** [gabime/spdlog#2612]
current the rotating_file_sink  general log file with name example.log, example.1.log,example.2.log.......
but I need the file name example_2023-01-18.log,  example_2023-01-18.1.log,  example_2023-01-18.2.log.....
Does this library support this function? What shall I do?

**Comment by tt4g** [comment]
File rotation sinks do not have such a feature.

You can implement a custom sink to add the features you want.
Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink
