### ISSUE TITLE
Add custom log rotation interval for daily log (E.g. Every 5 min)

### ISSUE THREAD

**Issue by mmanoj** [gabime/spdlog#2613]
How we can add custom log rotation time interval for daily log.Example rotate log file every 5 min.
Also file name should be:

filename.ext.<timestamp>

How can we achieve this?

**Comment by tt4g** [comment]
File rotation sinks do not have such a feature.

You can implement a custom sink to add the features you want.
Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by gabime** [comment]
There is the [hourly file sink]( https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/hourly_file_sink.h) which you might find useful.

**Comment by tt4g** [comment]
Yes, we can use `hourly_file_sink` to rotate every 5 minutes.
However, I read and interpreted the issue to mean that the current log file name is `<filename>.<ext>` (no datetime suffix) and rotated files should have a datetime suffix.
The log file name can be changed with `FileNameCalc`, but unfortunately `FileNameCalc::calc_filename()` is a static function.

https://github.com/gabime/spdlog/blob/654dbc5c3291a0981e6c473fac199409d41fcde8/include/spdlog/sinks/hourly_file_sink.h#L44-L59

https://github.com/gabime/spdlog/blob/654dbc5c3291a0981e6c473fac199409d41fcde8/include/spdlog/sinks/hourly_file_sink.h#L24-L37

You can make the log file name without the datetime suffix only once by defining a static variable in the function. However, this technique cannot be used if `hourly_file_sink` is initialized more than once.

**Comment by mmanoj** [comment]
@gabime  and @tt4g 

Thank for quick support and advice.I will check the hourly sink option. Also note i'm initializing only once at Main function. So I will do the modification as below to rotate every 5 min
```C++
log_clock::time_point next_rotation_tp_()
    {
        auto now = log_clock::now();
        tm date = now_tm(now);
        date.tm_min = 0;
        date.tm_sec = 0;
        auto rotation_time = log_clock::from_time_t(std::mktime(&date));
        if (rotation_time > now)
        {
            return rotation_time;
        }
        return {rotation_time + std::chrono::minutes(5)};
    }
```
