### ISSUE TITLE
Is spdlog supposed to work in static initializers?

### ISSUE THREAD

**Issue by mcondarelli** [gabime/spdlog#2616]
Hi,
thanks for this nice piece of code!

I am inheriting code that does substantial work in some static initializers:
I mean: there are some static class instances (created before main(), of course) 
and their constructors do not "simply initialize members" but open .xml files to read 
tings, load libraries, etc. etc.
I know it's not really "best practices", but I have little choice.

Question is: can I use spdlog (specifically SPDLOG_* macros) to emit logs in that context?
Of course that would be "default logging" as I customize spdlog at start of main(), too
late for static initializers, but apparently something is wrong because I see only ONE
SPDLOG_INFO() (probably the first one) output and then nothing else till after spdlog
initialization in main().

Could it be initialization discards pending output?
Is there any way I can flush buffers before reinitializing spdlog?

Many Thanks in Advance!

**Comment by gabime** [comment]
Have you tried calling `logger->flush() ?`

**Comment by mcondarelli** [comment]
Yes, I tried, but apparently I get printouts only for "info"  level stuff (no "error" or "critical"; not having "trace" would be understandable)

**Comment by gabime** [comment]
@mcondarelli what was the solution?

**Comment by mcondarelli** [comment]
@gabime 
Sincerely, I don't know :(
After a while, apparently without changing anything relevant, it started working as expected (with default logger, of course).
That is why I closed the Issue.
Most likely there was some mishap from my side, but I cannot understand what.
Now I'm fighting with `cmake` if I use `include_directories(${CMAKE_SOURCE_DIR}/external/spdlog/include)` I get a ton of "deprecated" warnings (probably my bad understanding of `cmake`)
