### ISSUE TITLE
How to log a root log to log files more than one with only one operation?

### ISSUE THREAD

**Issue by yucelalbar** [gabime/spdlog#2617]
Hi,

I have a root log: `Welcome`
I'd like to dispatch this root log along with different log files like `a.log`, `b.log`, `c.log`. But, the formatting of this root log will be different than other daily logs

- Root log at files won't have any file and line information as other logs have
- Root log's logger name will be `root` while other logger names are specific to log files

**Comment by tt4g** [comment]
You can create root logger with multiple sinks.
See: https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#creating-loggers-with-multiple-sinks

**Comment by yucelalbar** [comment]
Is it like:
```
    auto rotating_sink_a = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("a.log", 1024*1024*10, 3);
    auto rotating_sink_b = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("b.log", 1024*1024*10, 3);
    auto rotating_sink_c = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("c.log", 1024*1024*10, 3);
    std::vector<spdlog::sink_ptr> sinks {rotating_sink_a, rotating_sink_b, rotating_sink_c};
    auto combined_logger = std::make_shared<spdlog::logger>("root", begin(sinks), end(sinks));

    spdlog::register_logger(combined_logger);

    spdlog::get("root")->info("Welcome!");

```

**Comment by tt4g** [comment]
Right.

**Comment by yucelalbar** [comment]
Thank you @tt4g !
