### ISSUE TITLE
Dumping backtraces for registered loggers?

### ISSUE THREAD

**Issue by bachittle** [gabime/spdlog#2620]
Is there a way to combine all registered loggers into one backtrace, or do I have to call each logger backtrace manually? If the latter is the case, could this perhaps be something to implement?

**Comment by tt4g** [comment]
Duplicate #2287

`dump_backtrace()` API is not provided for all loggers, but you can use `spdlog::sinks::ringbuffer_sink` instead.

If you really want to use `spdlog::logger::dump_backtrace()`, call `spdlog::apply_all()`.

```cpp
spdlog::apply_all([](auto logger)
{
    logger->dump_backtrace();
});
```
