### ISSUE TITLE
No logging on AllocConsole() after FreeConsole()

### ISSUE THREAD

**Issue by yww999** [gabime/spdlog#2621]
The info log "Start Logging......" only can show on the first time of AllocConsole() and following logging isn't show on the console window. Here is my code.
```
VOID LoggingConsoleToggleSwitch()
{
	if (enableLogging)
	{
		AllocConsole();
		spdlog::default_logger()->flush();
		spdlog::info("Start Logging......");
	}
	else
	{
		FreeConsole();
	}
}
```

**Comment by tt4g** [comment]
spdlog does not know that the console has been detached. Please re-create the default logger with `wincolor_stdout_sink_mt` after attaching the console.

https://github.com/gabime/spdlog/blob/7d805c2231d34d71cc0fab4488fef42a307f863d/include/spdlog/details/registry-inl.h#L37-L50

**Comment by yww999** [comment]
It's fixed. Thank you tt4g~~~
