### ISSUE TITLE
Is it possible to build spdlog while RTTI compile flag is off?

### ISSUE THREAD

**Issue by T-rvw** [gabime/spdlog#2623]
In current codebase, `dynamic_cast` will be used in fmt : https://github.com/gabime/spdlog/blob/8a0b2231b17ff0c084d7319a8631a84bd89181f1/include/spdlog/fmt/bundled/ostream.h#L82

**Comment by tt4g** [comment]
fmt is maintained in another project. Please move this issue to [fmt project](https://github.com/fmtlib/fmt).

**Comment by T-rvw** [comment]
moved to fmt : https://github.com/fmtlib/fmt/issues/3291
