### ISSUE TITLE
Fail to build with NDK r16b

### ISSUE THREAD

**Issue by xyz1001** [gabime/spdlog#2624]
spdlog 1.11.0 fail to build with NDK r16b

<details>
  <summary>Compiler output</summary>
In file included from /data/conan/eslog/3.1.34/screenshare/snapshot/build/ce2b56950953d6f017405bd02f64b8f31dae9cb6/src/eslog/sink/android/sink_impl.cpp:12:

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:32:41: error: use of undeclared identifier 'log_id'

template<typename Mutex, int BufferID = log_id::LOG_ID_MAIN>

                                        ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:80:52: error: use of undeclared identifier 'log_id'

    typename std::enable_if<ID == static_cast<int>(log_id::LOG_ID_MAIN), int>::type android_log(int prio, const char *tag, const char *text)

                                                   ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:80:80: error: member 'type' declared as a template

    typename std::enable_if<ID == static_cast<int>(log_id::LOG_ID_MAIN), int>::type android_log(int prio, const char *tag, const char *text)

                                                                               ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:80:84: error: expected ';' at end of declaration list

    typename std::enable_if<ID == static_cast<int>(log_id::LOG_ID_MAIN), int>::type android_log(int prio, const char *tag, const char *text)

                                                                                   ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:37:11: error: member initializer 'tag_' does not name a non-static data member or base class

        : tag_(std::move(tag))

          ^~~~~~~~~~~~~~~~~~~~

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:44:46: error: use of undeclared identifier 'convert_to_android_'

        const android_LogPriority priority = convert_to_android_(msg.level);

                                             ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:58:41: error: use of undeclared identifier 'tag_'

        int ret = android_log(priority, tag_.c_str(), msg_output);

                                        ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:63:41: error: use of undeclared identifier 'tag_'

            ret = android_log(priority, tag_.c_str(), msg_output);

                                        ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:116:25: error: too few template arguments for class template 'android_sink'

using android_sink_mt = android_sink<std::mutex>;

                        ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:33:7: note: template is declared here

class android_sink final : public base_sink<Mutex>

      ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:117:25: error: too few template arguments for class template 'android_sink'

using android_sink_st = android_sink<details::null_mutex>;

                        ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:33:7: note: template is declared here

class android_sink final : public base_sink<Mutex>

      ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:119:25: error: use of undeclared identifier 'log_id'

template<int BufferId = log_id::LOG_ID_MAIN>

                        ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:121:25: error: use of undeclared identifier 'log_id'

template<int BufferId = log_id::LOG_ID_MAIN>

                        ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:131:44: error: no template named 'android_sink_mt' in namespace 'spdlog::sinks'; did you mean 'android_sink'?

    return Factory::template create<sinks::android_sink_mt>(logger_name, tag);

                                    ~~~~~~~^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:33:7: note: 'android_sink' declared here

class android_sink final : public base_sink<Mutex>

      ^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:137:44: error: no template named 'android_sink_st' in namespace 'spdlog::sinks'; did you mean 'android_sink'?

    return Factory::template create<sinks::android_sink_st>(logger_name, tag);

                                    ~~~~~~~^

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:33:7: note: 'android_sink' declared here

class android_sink final : public base_sink<Mutex>

      ^

/data/conan/eslog/3.1.34/screenshare/snapshot/build/ce2b56950953d6f017405bd02f64b8f31dae9cb6/src/eslog/sink/android/sink_impl.cpp:43:49: error: no template named 'android_sink_mt' in namespace 'spdlog::sinks'; did you mean 'android_sink'?

    auto sink = std::make_shared<spdlog::sinks::android_sink_mt>();

                                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~

                                                android_sink

/data/conan/spdlog/1.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/sinks/android_sink.h:33:7: note: 'android_sink' declared here

class android_sink final : public base_sink<Mutex>

      ^

/data/conan/eslog/3.1.34/screenshare/snapshot/build/ce2b56950953d6f017405bd02f64b8f31dae9cb6/src/eslog/sink/android/sink_impl.cpp:43:17: error: no matching function for call to 'make_shared'

    auto sink = std::make_shared<spdlog::sinks::android_sink_mt>();

                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/data/conan/ndk/r16b/screenshare/stable/package/4db1be536558d833e52e862fd84d64d75c2b3656/android-19-armeabi-v7a/include/c++/4.9.x/memory:4592:1: note: candidate template ignored: invalid explicitly-specified argument for template parameter '_Tp'

make_shared(_Args&& ...__args)

^

16 errors generated.
</details>

**Comment by gabime** [comment]
Help is needed for this and a PR to fix is welcome.

**Comment by gabime** [comment]
closed due to lack of activity
