### ISSUE TITLE
Source archives hash mismatch

### ISSUE THREAD

**Issue by ruslan316** [gabime/spdlog#2625]
Use Meson wrapdb packages to download spdlog
Couple hours ago got into problems:

`|Downloading spdlog source from https://github.com/gabime/spdlog/archive/v1.11.0.tar.gz
Downloading file of unknown size.
|A fallback URL could be specified using source_fallback_url key in the wrap file

subprojects/vxgcloudagent/meson.build:189:0: ERROR: Incorrect hash for source:
 ca5cae8d6cac15dae0ec63b21d6ad3530070650f68076f3a4a862ca293a858bb expected
 d12ec152ca9689e4ff9a06e56786d5301f2324acd4ab834bd1159fef5a9942d9 actual.`

The same situation with 1.9.2
`|Downloading spdlog source from https://github.com/gabime/spdlog/archive/v1.9.2.tar.gz
Downloading file of unknown size.
|A fallback URL could be specified using source_fallback_url key in the wrap file

subprojects/vxgcloudagent/meson.build:189:0: ERROR: Incorrect hash for source:
 6fff9215f5cb81760be4cc16d033526d1080427d236e86d70bb02994f85e3d38 expected
 43b0944ddc24aeb595e90e0684ba699c5b71007890440c0ab4fd5dd1c231845a actual.
`
Have you updated packages recently?

**Comment by jwnimmer-tri** [comment]
FYI The https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/ broken a ton of packages, and was reverted (/ is being reverted currently).  That's probably the root cause of your issue.

**Comment by ruslan316** [comment]
@jwnimmer-tri thanks, that explains the root cause of issue
