### ISSUE TITLE
spdlog SEFAULT

### ISSUE THREAD

**Issue by mcondarelli** [gabime/spdlog#2628]
Hi,
first of all: Many thanks for this Very nice piece of software.

Unfortunately I seem unable to use it properly :(

I have a rather large project using spdlog for all its printing needs.

I use cmake for building and I pull in spdlog using:
```cmake
  include(FetchContent)
  FetchContent_Declare(
        spdlog
        GIT_REPOSITORY https://github.com/gabime/spdlog.git
        GIT_TAG v1.10.0
  )
  FetchContent_MakeAvailable(spdlog lrm)
```

I link spdlog to my program using:
```cmake
target_link_libraries(application PUBLIC spdlog::spdlog)
```

I start my code with:
```c++
int main(int argc, char *argv[]) 
{
#define use_multiple_loggers
#ifdef use_multiple_loggers
    auto scssink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    scssink->set_level(spdlog::level::trace);

    auto udpcfg = spdlog::sinks::udp_sink_config("127.0.0.1", 30777);
    auto udpsink = std::make_shared<spdlog::sinks::udp_sink_mt>(udpcfg);
    udpsink->set_level(spdlog::level::trace);
    
    auto logger = spdlog::logger("mine", {scssink, udpsink});
    auto mylogger = std::make_shared<spdlog::logger>(logger);
    spdlog::set_default_logger(mylogger);
#endif
    spdlog::set_pattern("[%S.%e][%=8l][%22s:%-4#][%30!] %v");
    spdlog::set_level(spdlog::level::trace);

    SPDLOG_INFO("Path to this (current) executable: {}", getExePath());
    SPDLOG_INFO("Current working directory: {}", getCurrDir());
    ...
```

Problem is line `auto mylogger = std::make_shared<spdlog::logger>(logger);` bombs in `std::function::function(const std::function<…> &) std_function.h:391` rtrying to access `<unknown> 0x0000000000000002`

I attach a full capture of my IDE state hoping it's useful:

![image](https://user-images.githubusercontent.com/870849/216086614-5078413b-64de-48a0-af2a-c7801ca40b0a.png)

What can I do to debug this?

Many Thanks in Advance
Mauro

**Comment by gabime** [comment]
Strange. . What compiler/version is it?

**Comment by mcondarelli** [comment]
```
mcon@ikea:~/Work/Lucid/audioservices/src$ g++ --version
g++ (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mcondarelli** [comment]
Note this is definitely **NOT** a `spdlog` bug (at least not an explicit one), but some bad interaction with my (large and messy) program.

A simple test program with the same code works flawlessly.

Another data point is on full rebuild of my program I see the following warning:
```
====================[ Build | audio-services | Debug ]==========================
/home/mcon/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/bin/cmake/linux/x64/bin/cmake --build /home/mcon/Work/Lucid/audioservices/cmake-build-debug --target audio-services -j 25
[11/31] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/async.cpp.o
/home/mcon/Work/Lucid/audioservices/cmake-build-debug/_deps/spdlog-src/src/async.cpp:13:44: warning: type attributes ignored after type is already defined [-Wattributes]
   13 | template class SPDLOG_API spdlog::details::mpmc_blocking_queue<spdlog::details::async_msg>;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[31/31] Linking CXX executable src/AudioServices/audio-services

Build finished
```

What can I check/debug?

**Comment by gabime** [comment]
Perhaps there  another instance of spdlog lib somewhere in the program?

**Comment by mcondarelli** [comment]
Apparently not, but I will cross-check again.

Problem is: due to dual header-only/cmake-compiled nature of spdlog I fear "some piece" of my code is actually using the compiled lib but some other piece is linking to "header-only".

I am trying to check for such an issue, but it is not trivial as certain parts are built as a lib and the final link is against a few objects and several libs.

Is there some way to ENSURE I'm not doing "mixed mode"?

**Comment by gabime** [comment]
Try to define SPDLOG_COMPILED_LIB before including spdlog, or in your projects the build flags

**Comment by mcondarelli** [comment]
Thanks  for the rapid turnaround.

This is getting  stranger and stranger. (but it's 2AM here and I've better to hit the sack before I do something even more stupid)

I see the macro I added `-DSPDLOG_COMPILED_LIB=1` in command line:
```
[ 56%] Building CXX object src/AudioServices/CMakeFiles/audio-services.dir/main.cpp.o
cd /home/mcon/Work/Lucid/audioservices/build/src/AudioServices && /usr/bin/c++ -DSPDLOG_COMPILED_LIB -I/home/mcon/Work/Lucid/audioservices/INTERFACE -I/home/mcon/Work/Lucid/audioservices/build/_deps/audiofile-src -I/home/mcon/Work/Lucid/audioservices/include -I/home/mcon/Work/Lucid/audioservices/public/AWECoreOS/Include -I/home/mcon/Work/Lucid/audioservices/src/Common -I/home/mcon/Work/Lucid/audioservices/public/interfaces -I/home/mcon/Work/Lucid/audioservices/assets/XMLFiles -I/home/mcon/Work/Lucid/audioservices/../lrm/src -I/home/mcon/Work/Lucid/audioservices/src/AudioServices/lrm::header -I/home/mcon/Work/Lucid/audioservices/src/AudioServices/CM::header -I/home/mcon/Work/Lucid/audioservices/external/lrm/src -I/home/mcon/Work/Lucid/audioservices/build/_deps/spdlog-src/include -I/home/mcon/Work/Lucid/audioservices/src/AudioWeaver -I/home/mcon/Work/Lucid/audioservices/public -Wall -g  -pthread -fsanitize=undefined -fno-omit-frame-pointer -DSPDLOG_COMPILED_LIB=1 -D_GLIBCXX_DEBUG=1  -O3 -DNDEBUG -std=c++14 -MD -MT src/AudioServices/CMakeFiles/audio-services.dir/main.cpp.o -MF CMakeFiles/audio-services.dir/main.cpp.o.d -o CMakeFiles/audio-services.dir/main.cpp.o -c /home/mcon/Work/Lucid/audioservices/src/AudioServices/main.cpp
```
but  it doesn't seem to be really defined:
```c++
int main(int argc, char *argv[]) 
{
#ifndef SPDLOG_COMPILED_LIB
#error "it didn't work"
#endif

#define use_multiple_loggers
#ifdef use_multiple_loggers
    auto scssink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    scssink->set_level(spdlog::level::trace);
```
Compiles without hitting `#error`

I'll continue tomorrow
Thanks

**Comment by tt4g** [comment]
Are you calling `add_subdirectory(${spdlog_SOURCE_DIR})` after `FetchContent()`?
If not, then the spdlog project downloaded with `FetchContent()` is not imported into your project (probably using the spdlog installed on your machine).

EDIT: Since `_deps/spdlog-src` is the default download directory of `FetchContent()`, it is not necessary to use
You seem to be calling `add_subdirectory(${spdlog_SOURCE_DIR})` (as far as the `-I/home/mcon/Work/Lucid/audioservices/build/_deps/spdlog-src/include` flag path is concerned).
Another possible cause of the problem is that libraries or applications that reference spdlog do not declare their dependencies with `taget_link_libraries(<target> PUBLIC spdlog::spdlog)`, so the spdlog already installed on your machine is used instead.
