### ISSUE TITLE
Print microseconds with delimiter

### ISSUE THREAD

**Issue by raidenluikang** [gabime/spdlog#2630]
`%T.%f`  format prints  `14:48:15.362823`  for example.

It seemed be pretty, if it prints as  `14:48:15.362'823`     or  `14:48:15.362,823`   -    with some delimiter between milliseconds and microseconds part.

Could you support that feature ?

**Comment by gabime** [comment]
Everyone has its own preferred format. You can create custom formatter flag and set the format to you like.
