### ISSUE TITLE
 Compilation error with fmt: "uninitialized variable in constexpr function"

### ISSUE THREAD

**Issue by xia-chu** [gabime/spdlog#2632]
A compilation error was exposed on the gcc(6.3.0) compiler like this:
```bash
/home/work/mediaflow-workspace/bitmain/spdlog/include/spdlog/fmt/bundled/format-inl.h:1472:39:   required from here
/home/work/mediaflow-workspace/bitmain/spdlog/include/spdlog/fmt/bundled/format.h:1241:8: error: uninitialized variable ‘buffer’ in ‘constexpr’ function
   Char buffer[digits10<UInt>() + 1];
```

The code location is:

https://github.com/gabime/spdlog/blob/927cc29444a294d76e83dfb898e797dc431ce094/include/spdlog/fmt/bundled/format.h#L1241

And i saw fmt have already fix it:

https://github.com/fmtlib/fmt/blob/05e3a9233ac1dd0c2d9643e046dbb5f788c39f61/include/fmt/format.h#L1335

So can you update fmt or synchronize this modification?

Thank for your good job, spdlog is very nice!

**Comment by tt4g** [comment]
If you do not want to use the bundled fmt, define the CMake variable `SPDLOG_FMT_EXTERNAL` and build.

https://github.com/gabime/spdlog/blob/927cc29444a294d76e83dfb898e797dc431ce094/CMakeLists.txt#L88-L89

Defining the `SPDLOG_FMT_EXTERNAL` macro instead has the same effect.

https://github.com/gabime/spdlog/blob/b59b4a2b4563b3ca3cfaaf0cb62273a3d40c8b13/include/spdlog/fmt/fmt.h#L13-L33

However, the fmt bundled with spdlog (v1.11.0) is version 9.1.0. It is not guaranteed to work with newer fmt versions (fmtlib/fmt@40e414d823d8af78cf6f52f3356c4c54e02eb62f is not released yet).

**Comment by xia-chu** [comment]
Thank for your reply！
