### ISSUE TITLE
The file is overwritten when the program runs multiple times

### ISSUE THREAD

**Issue by chyczcool** [gabime/spdlog#2633]
#include <stdlib.h>
#include <iostream>
#include "spdlog/spdlog.h"
#include "spdlog/sinks/basic_file_sink.h"

int main()
{
    try
    {
        spdlog::basic_logger_mt("basic_logger", "logs/basic-log.log");
    }
    catch (const spdlog::spdlog_ex& ex)
    {
        std::cout << "Log init failed: " << ex.what() << std::endl;
    }

    auto logger = spdlog::get("basic_logger");
    if (NULL == logger)
    {
        std::cout << "get logger error." << std::endl;
    }
    
    int i = 0;
    while (i < 10)
    {

        logger->info("This is basic_logger .");
        Sleep(1000);
        i++;
    }
}
=======Dividing line=========
    The above is a log test program output to a file. After the first run, the printed content appears correctly in the log file, but it does not appear to be updated during the second run. In fact, the file generated during the first run should be overwritten during the second run. What we expect is not to overwrite the file. How can we solve this problem? Other file longers also have the same problem...

**Comment by tt4g** [comment]
Duplicate #937

spdlog does not support writing to a single file from multiple processes.
Use unique file names for each process.
