### ISSUE TITLE
'parse': is not a member of 'fmt::v9::detail::fallback_formatter<const GLubyte *,Char,void>'

### ISSUE THREAD

**Issue by P3RK4N** [gabime/spdlog#2635]
Im getting an error in VS2022 with C++20. It is in fmt library in core.h at line 2746 and I cant seem to solve it. P.S. I am building static library
![image](https://user-images.githubusercontent.com/87949029/217907812-2b7e2e14-5788-41a3-bf70-a3b0eb195c73.png)

**Comment by tt4g** [comment]
The reason the compiler cannot resolve the template is probably simply because `fmt::formatter<const GLubyte*>` is not defined.
See: https://fmt.dev/9.1.0/api.html#formatting-user-defined-types

**Comment by invi1998** [comment]
How did you solve this problem? Only older versions of C++(C++17) can be used?

**Comment by tt4g** [comment]
[This comment](https://github.com/gabime/spdlog/issues/2635#issuecomment-1424833266) says it all.

The fmt library defines `fmt::formatter` specializations only for common types.
If you can no longer actualize templates due to version upgrades, define `fmt::formatter<T>` in your project.
