### ISSUE TITLE
error: uninitialized variable 'buffer' in 'constexpr' function

### ISSUE THREAD

**Issue by jordissm** [gabime/spdlog#2637]
Hi,

I get the following error on compilation of spdlog as a dependency of another program (Doxygen): 

```
error: uninitialized variable 'buffer' in 'constexpr' function
```

due to this line -> https://github.com/gabime/spdlog/blob/927cc29444a294d76e83dfb898e797dc431ce094/include/spdlog/fmt/bundled/format.h#L1241

I'm fairly new to spdlog and Doxygen, so apologies if I'm missing something obvious.

**Comment by tt4g** [comment]
`spdlog/include/spdlog/fmt/bundled/format.h` is bundled with spdlog but is source code from the fmt library.
It should be reported to the [fmt repository}(https://github.com/fmtlib/fmt).

And this issue already fixed (not released yet): fmtlib/fmt@40e414d823d8af78cf6f52f3356c4c54e02eb62f
