### ISSUE TITLE
Option to truncate files in file loggers

### ISSUE THREAD

**Issue by sbrkopac** [gabime/spdlog#264]
Currently SPDLOG supports the rotation of log files. But currently I have some logs which should be truncated before writing to them. It would be nice to have the ability to turn truncate on instead of rotating the log.

**Comment by gabime** [comment]
I think passing zero to the max_files arg will give you what you want:

```c++
auto rotating_logger = spd::rotating_logger_mt("some_logger_name", "mylogfile", 1024*1024 , 0);
```

**Comment by sbrkopac** [comment]
Unfortunately, that didn't work. I dug a bit and found the following in line 72 of file_sinks.h

`_file_helper.open(calc_filename(_base_filename, 0, _extension));`

And it is default the truncation to false, regardless of max_files. Would you be open to modifying the API for the simple_file_sink having a truncation option in the constructor? I understand not wanting to have a lot of true / false combinations as that can get messy quickly. Thanks.

**Comment by gabime** [comment]
right, but it truncates after it reached its max size..

**Comment by sbrkopac** [comment]
Ah. I see. Sorry, I'll be more clear. We have some log files that should only last the for the life-time of the application. Once the application closes we manually review the log file (if needed) and remove it. We would like to be able to truncate the file without introducing calls to the filesystem or having the user manually delete / rotate it.

**Comment by gabime** [comment]
Since this is very specific need consider implmenting your own custom sink. it is very simple in spdlog.

**Comment by sbrkopac** [comment]
That might be the best way to go. Unfortunately changing the sinks at this point would be a very big pain so I'll have to put it on my todo list. For now I have made the following changes [https://github.com/sbrkopac/spdlog/commit/0be736c7fc6bed0733095ca2a951eb86ef1683dc]. Thanks very much for the insights!

**Comment by gabime** [comment]
please open a pr and i will merge

**Comment by gabime** [comment]
Merged in https://github.com/gabime/spdlog/commit/42dfa1975a23b246431ff3501e6cec29d946bb06

**Comment by dakiwaki** [comment]
> Ah. I see. Sorry, I'll be more clear. We have some log files that should only last the for the life-time of the application. Once the application closes we manually review the log file (if needed) and remove it. We would like to be able to truncate the file without introducing calls to the filesystem or having the user manually delete / rotate it.

Would it be possible for you to let me know how you implemented your code so that logger file will be deleted once the application closes.
