### ISSUE TITLE
Compiling code with -O2 flag causes segmentation fault

### ISSUE THREAD

**Issue by syinwu** [gabime/spdlog#2641]
![image](https://user-images.githubusercontent.com/34093828/218263063-1cc98733-1dbc-46de-b6a1-e152c6fbb4f7.png)

**Comment by tt4g** [comment]
GCC4.8 is not supported because it is not C++11 Standard complete.

https://stackoverflow.com/a/36970437

**Comment by syinwu** [comment]
> GCC4.8 is not supported because it is not C++11 Standard complete.
> 
> https://stackoverflow.com/a/36970437

Thank you so much!!!

**Comment by syinwu** [comment]
@tt4g I upgraded gcc version to 10.4, it doesn't work. I use vcpkg to manage package, and use ```target_link_libraries(spdlog::spdlog)```. The ```static registry s_instance``` crashed while running program.

**Comment by syinwu** [comment]
It works normally when the compilation flag is -O0

**Comment by tt4g** [comment]
Try without vcpkg. Possible vcpkg problem (#2452, #1910).

**Comment by syinwu** [comment]
use spdlog::spdlog_header_only to solve this problem
