### ISSUE TITLE
Failed Writing To File ... Destination Required

### ISSUE THREAD

**Issue by bjin2364** [gabime/spdlog#2647]
This is a problem that's stumped me for a while and unfortunately I can't easily reproduce the issue.

System:
- Ubuntu 20.04
- spdlog v1.5.0

Occasionally when attempting to log some data, my application will throw these backtraces:

```
[*** LOG ERROR ***] [2022-11-02T23:02:47.000Z] Failed writing to file /var/log/rtr_appliance_app/robots/rtr_1_3afeefbb-83a1-497a-98bc-1b99f6464cec.bin: Destination address required BT: [[[
bt: 0   rtr::Backtrace[abi:cxx11](int, void*) a.k.a. _ZN3rtr9BacktraceB5cxx11EiPv at ??:? from /opt/ros/foxy/lib/librtr_utils.so.2
bt: 1 _ZN3rtr6detail12log_throttleEdN6spdlog10source_locENS1_5level10level_enumERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE at ??:? from /opt/ros/foxy/lib/librtr_utils.so.2
bt: 2   spdlog::logger::err_handler_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) a.k.a. _ZN6spdlog6logger12err_handler_ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE at ??:? from /lib/x86_64-linux-gnu/libspdlog.so.1
bt: 3   from /lib/x86_64-linux-gnu/libspdlog.so.1
bt: 4   spdlog::logger::log_it_(spdlog::details::log_msg const&, bool, bool) a.k.a. _ZN6spdlog6logger7log_it_ERKNS_7details7log_msgEbb at ??:? from /lib/x86_64-linux-gnu/libspdlog.so.1
```

I have a custom error handler set which formats the above message in the following manner:
```
spdlog::set_error_handler([](const std::string& message) {                                                                                   
  const auto now_chrono = std::chrono::system_clock::now();                              
  std::time_t now_time_t = std::chrono::system_clock::to_time_t(now_chrono);             
  char time_c_str[sizeof "0000-00-00T00:00:00.000Z"];                                    
  std::strftime(time_c_str, sizeof time_c_str, "%Y-%m-%dT%H:%M:%S.000Z",                 
                std::gmtime(&now_time_t));                                               
  fmt::print(stderr, "[*** LOG ERROR ***] [{}] {} BT: [[[\n{}]]]\n", time_c_str, message,
             Backtrace());                                                          
});                                                                                      
```

Admittedly, the backtrace might be more noise than anything useful/relevant to the original error. I'll also note that after a system reboot, this error will go away.

I'm also not sure if this information is relevant, but I have a custom formatter setup for this logger instance as well. It is essentially the following:

```
class BinaryFormat final : public spdlog::formatter {                                     
 public:                                                                                          
  void format(const spdlog::details::log_msg& msg, spdlog::memory_buf_t& buffer) override {
    const std::uint16_t size = static_cast<std::uint16_t>(std::min<std::size_t>(msg.payload.size(), MAX_DATA_SIZE));
    WriteUint16(buffer, size); // writes to buffer according to endianess
    buffer.append(msg.payload.begin(), std::next(msg.payload.begin(), size));
  }

  std::unique_ptr<formatter> clone() const {
    return spdlog::details::make_unique<BinaryFormat>();
  }
};
```
The logger is of type `spdlog::rotating_logger_mt`.

I'm guessing the error is coming from a lower level library within `spdlog`, but I've had a lot of trouble finding information on what could cause a `Destination address required` error. Any help would be much appreciated!

**Comment by tt4g** [comment]
The error message "Destination address required" is reported when the socket is closed.
Are you using the socket API?

**Comment by bjin2364** [comment]
@tt4g does `spdlog` have a socket API/uses sockets under the hood? I'm having trouble finding documentation on this...

My application uses sockets for other purposes, but I don't believe there's any connection between those sockets and the way I'm logging data via `spdlog`

**Comment by tt4g** [comment]
spdlog use socket API in `tcp_sink` and `udp_sink`.

https://github.com/gabime/spdlog/blob/5a63426d1cb9d7e16dbe6b6779e041012513202e/include/spdlog/details/tcp_client.h#L130

https://github.com/gabime/spdlog/blob/5a63426d1cb9d7e16dbe6b6779e041012513202e/include/spdlog/details/udp_client.h#L87

**Comment by bjin2364** [comment]
Interesting... I am using the `spdlog::rotating_logger_mt` sink, however my application has a different thread that is logging other data via a `spdlog::sinks::syslog_sink_mt` sink, which I'm unsure if it's using the socket API under the hood.

I am confident that no part of my application is explicitly constructing a tcp/udp sink similar to this example: https://github.com/gabime/spdlog/blob/v1.x/example/example.cpp#L247

**Comment by tt4g** [comment]
If you remove `syslog_sink` and the problem does not occur, it probably means that the syslog API is reporting it.

**Comment by bjin2364** [comment]
@tt4g Thanks for the tip! Do you have any intuition on how the `syslog_sink` would have any impact on the `rotating_logger_mt` sink? Both logger instances are created in separate threads, and it looks like the `spdlog::set_error_handler(...)` function applies the error handler to individual logger instances.

I believe the backtrace "[*** LOG ERROR ***]..." message I posted earlier only happens in the thread with the `rotating_logger_mt` sink. When I stop the thread, the application stops logging those backtraces. Does this behavior make any sense to you?

**Comment by tt4g** [comment]
I have no answer because the cause is not clear to me.
It seems counterintuitive that `rotating_logger_mt` would report a "Destination address required" error.
It is necessary to isolate whether `syslog_sink` or `rotating_file_sink` (`rotating_logger_mt`) is the cause.

Unfortunately, the backtrace is unlikely to be useful since the error seems to be caused by the source code in the `.so`.

The error message suggests that `syslog_sink` is most likely reporting an error, so please try to stop using this sink once, if possible.

Also output the thread id (e.g. `std::this_thread::get_id()`) in the error handler.
This way you will know that the error is really being reported only from `rotating_logger_mt` thread.

Also, by using the logging macro such as `SPDLOG_INFO(...)` and `SPDLOG_LOGGER_INFO(logger, ...)`, the location of the logging function call that caused the error can be determined.
See: #2048
