### ISSUE TITLE
using spdlog::set_default_logger() for a logger with console and file sink missing log messages

### ISSUE THREAD

**Issue by hmutschler15** [gabime/spdlog#2650]
Hi all,

I've been trying to follow the examples for using a logger with a console sink and file sink as the default logger and have been running into issues with missing some log messages in both the console and file when using the default logger.  The application is multi-threaded and I'm trying to use the default logger to log from different threads.

```
namespace logging
{
    std::vector<spdlog::sink_ptr> sinks;
    std::shared_ptr<spdlog::logger> combined_logger;
}

void logging::InitLogger(const std::string& logfile_name, const uint8_t max_file_size, const uint8_t max_num_files)
{
    try
    {
        sinks.push_back(std::make_shared<spdlog::sinks::stdout_color_sink_mt>());
        sinks.back()->set_level(spdlog::level::info);

        sinks.push_back(std::make_shared<spdlog::sinks::rotating_file_sink_mt>(logfile_name, MB_1 * max_file_size, max_num_files));
        sinks.back()->set_level(spdlog::level::trace);

        combined_logger = std::make_shared<spdlog::logger>("multi_logger", begin(sinks), end(sinks));
        combined_logger->set_level(spdlog::level::trace);
        combined_logger->flush_on(spdlog::level::trace);

        spdlog::set_default_logger(combined_logger);
    }
    catch (const spdlog::spdlog_ex& ex)
    {
        std::cout << "Log initialization failed: " << ex.what() << std::endl;
    }
}
```

I am calling `InitLogger()` from main and when I use `spdlog::info()` or `spdlog::trace()` etc. to invoke the default logger, I have noticed that some log messages are missed in the console and in the file.  Some messages in the console print with `[multi_logger]` and others don't, but the messages that do print `[multi_logger]` are the ones that make it to the file.

Here is some of the console output that shows some messages printing with `[multi_logger]` and others not:

```
[2023-02-23 14:55:52.159] [info] Engine Version is: 2.2
[2023-02-23 14:55:52.303] [multi_logger] [info] Host Version is: 1.5
[2023-02-23 14:55:52.318] [info] System State changed to: NOT READY
```

Here is some of the file output:

```
[2023-02-23 14:55:51.459] [multi_logger] [trace] Set Reset : 0
[2023-02-23 14:55:51.659] [multi_logger] [trace] Set Reset : 1
[2023-02-23 14:55:52.303] [multi_logger] [info] Host Version is: 1.5
[2023-02-23 14:55:52.305] [multi_logger] [debug] MSG_ID_1 Response received
[2023-02-23 14:55:52.317] [multi_logger] [debug] MSG_ID_2 Response received
```

The only info level message that make it to both the console and file is the one with `[multi_logger]` printed in the console.

Everything works perfectly when using the `combined_logger` directly to create log messages, but not when using the default logger.

Any help would be much appreciated, Thanks!

**Comment by tt4g** [comment]
Is `Logger::initLogger()` defined in the shared library of your project?
If so, the default logger is not shared between the library and the application.
See: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

**Comment by hmutschler15** [comment]
That did fix the issue, thanks!
