### ISSUE TITLE
Weird run time error

### ISSUE THREAD

**Issue by Consti10** [gabime/spdlog#2652]
Hello,

I am getting the weirdest run time issue with spdlog (or,to be more exact, with fmt) when running on some old intel hardware:

```
Program received signal SIGILL, Illegal instruction.
0x00005555555dfdce in fmt::v9::detail::vformat_to<char> (buf=..., fmt=..., args=..., loc=...) at /opt/OpenHD/OpenHD/ohd_common/lib/spdlog/include/spdlog/fmt/bundled/format.h:4136
4136	  detail::parse_format_string<false>(fmt, format_handler(out, fmt, args, loc));

```

Has anybody ever encountered something similar ?

**Comment by theevilone45** [comment]
Can you give some details? Version of lib, hardware used, compiler version, operating system,minimal code that reproduces an issue would be great 😀

**Comment by Consti10** [comment]
I was able to find the reason for the crash:
We used SSSE3 intel extensions, but compiled with AVX2 flags instead.
Aparently, this resulted in the compiler generating some AVX2 only instructions inside fmt, which then crashed spdlog when running on systems with no AVX2 (but SSSE3) support.

**Comment by gabime** [comment]
Interesting. Thanks for the update !
