### ISSUE TITLE
Showing file and line info along with colors

### ISSUE THREAD

**Issue by qeroll** [gabime/spdlog#2654]
Hi,

I have been trying to set the following pattern for my logs: 
```
        m_logger = spdlog::stdout_color_mt(logger_name);
        m_logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e][%s:%!:%#][%l] %v");
```

And I encounter the following problem:
If I use `SPDLOG_LOGGER_INFO` I don't get colors in my logs. However, if I use `m_logger->info` the file and line number does not show up.

Is there any way I can solve it?

Regrads

**Comment by tt4g** [comment]
If the terminal does not support ANSI escape sequences, colors will not be output.
You can use `spdlog::color_mode::always` to force the output of ANSI escape sequences for color codes. However, if the terminal cannot interpret the escape character, it will be displayed in the terminal as it is.

```diff
-m_logger = spdlog::stdout_color_mt(logger_name);
+m_logger = spdlog::stdout_color_mt(logger_name, spdlog::color_mode::always);
```

**Comment by gabime** [comment]
> If I use SPDLOG_LOGGER_INFO I don't get colors in my logs

Please provide code to reproduce this

**Comment by qeroll** [comment]
Ok, so I double checked and the problem seems to be with my pattern. If I don't use set_pattern like below, I do see colors.

Can you tell me how to add colors to the pattern?

Here is the code:

```
std::string logger_name = name + "_logger";
m_logger = spdlog::stdout_color_mt(logger_name);
m_logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e][%s:%!:%#][%l] %v");
SPDLOG_LOGGER_INFO(m_logger, "{} created", name);
```

**Comment by qeroll** [comment]
Never mind - found it: [%^%l%$]
