### ISSUE TITLE
How can I log messages with different log levels to different files?

### ISSUE THREAD

**Issue by yo123abxd** [gabime/spdlog#2657]
Is it possible to do something like this? :
`spdlog::info("message"); // log into file: "info.log"`
`spdlog::trace("message"); // log into file: "trace.log"`

**Comment by tt4g** [comment]
Create a custom sink that passes log messages to a wrapped sink only at a specific log level.

See the Wiki for how to create a custom sink: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink
[`dist_sink`](https://github.com/gabime/spdlog/blob/v1.11.0/include/spdlog/sinks/dist_sink.h) is a hint on how to create other sink wrappers.
Answers to similar question: https://github.com/gabime/spdlog/issues/2412#issuecomment-1162599428

**Comment by yo123abxd** [comment]
> Create a custom sink that passes log messages to a wrapped sink only at a specific log level.
> 
> See the Wiki for how to create a custom sink: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink [`dist_sink`](https://github.com/gabime/spdlog/blob/v1.11.0/include/spdlog/sinks/dist_sink.h) is a hint on how to create other sink wrappers. Answers to similar question: [#2412 (comment)](https://github.com/gabime/spdlog/issues/2412#issuecomment-1162599428)

Thank you for your reply!
