### ISSUE TITLE
 error: variable or field ‘set_pattern’ declared void  & error: ‘logger’ was not declared in this scope

### ISSUE THREAD

**Issue by ZhaoHaoRu** [gabime/spdlog#2658]
I use the default branch 1.x in linux and try to set_pattern for my logger,  I got the following error report at compile time ：
```
/usr/local/include/spdlog/pattern_formatter.h:122:29: error: variable or field ‘set_pattern’ declared void
  122 | SPDLOG_API void set_pattern(logger &logger, std::string pattern);
      |                             ^~~~~~
/usr/local/include/spdlog/pattern_formatter.h:122:29: error: ‘logger’ was not declared in this scope
/usr/local/include/spdlog/pattern_formatter.h:122:37: error: ‘logger’ was not declared in this scope
  122 | SPDLOG_API void set_pattern(logger &logger, std::string pattern);
      |                                     ^~~~~~
/usr/local/include/spdlog/pattern_formatter.h:122:57: error: expected primary-expression before ‘pattern’
  122 | SPDLOG_API void set_pattern(logger &logger, std::string pattern);
```
How should I deal with this error?

**Comment by tt4g** [comment]
The declaration of `set_pattern()` in the v1.x branch is as follows:

https://github.com/gabime/spdlog/blob/8be5b41a2fe79f356c9cc20124fef6dbb050df4c/include/spdlog/pattern_formatter.h#L100

The header file path appearing in the error message indicates `/usr/local/include/spdlog/`, is it really source code on the 1.x branch?

EDIT: `/usr/local/include/spdlog/pattern_formatter.h` is the header file in which `spdlog::pattern_formatter` is defined. But from the issue comment I assume you are calling `logger->set_pattern()`. Unfortunately, the error message you provided does not indicate the cause. Please provide the minimal source code where the compilation error is occurring.

**Comment by ZhaoHaoRu** [comment]
I find I was on branch 2.x, now I switch to branch 1.x and the problem has been solved. Thanks!
