### ISSUE TITLE
Improperly-formatted ISO8601 UTC offset for negative-offset timezones

### ISSUE THREAD

**Issue by woobs** [gabime/spdlog#266]
The `z_formatter` formats negative-offset timezones incorrectly.  For example, it should format CDT as "-05:00", but instead formats it as "-5:00" because the padding function formats the integer value `-5` as "-5" and `+5` as "05".  This doesn't conform to ISO8601 and could create problems for log parsers that expect fixed-width times.  Thus, I would consider this a minor bug.

Seems the fix should be somewhere near [pattern_formatter_impl.h@325](https://github.com/gabime/spdlog/blob/master/include/spdlog/details/pattern_formatter_impl.h#L325).  Perhaps by adding a "-" to the formatted output for negative hour offsets and then sending the absolute value of the hour offset to the padding function.

**Comment by gabime** [comment]
Fixed in cb75569541bf41fed10634dc3da4024a840afc2e. 
Thanks for reporting.
