### ISSUE TITLE
ErrInfo:error: too few arguments to function ‘unsigned char fmt::v9::detail::format_as(std::byte)

### ISSUE THREAD

**Issue by VenusTrack** [gabime/spdlog#2660]
Errinfo:
`/usr/local/include/spdlog/fmt/bundled/core.h:1334:56: error: too few arguments to function ‘unsigned char fmt::v9::detail::format_as(std::byte)’
 1334 |   template <typename U, typename V = decltype(format_as(U())),`

My Question:
when I compile my projects with 【SET(CMAKE_CXX_STANDARD 17)】 in my CMakeLists.txt，getting the error befor。
“ decltype(format_as(U()))  ” changed to "decltype(format_as(std::declval<U>()()))" works good.

Do we need to consider the compatibility to c++17 standard？

**Comment by tt4g** [comment]
That is fmt library source. Please move issue to [fmt repository](https://github.com/fmtlib/fmt).
