### ISSUE TITLE
spdlog 1.11.0 fails to build with bundled fmtlib 1.9.1

### ISSUE THREAD

**Issue by Nathie1000** [gabime/spdlog#2664]
Trying to compile spdlog 1.11.0 on gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) results in an error (see attached file).

This is error is caused by a uninitialized local variable in constexpr context in file format.h on line 1241.
This issue seems to have been resolved in later version of fmtlib as of here https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L1345

[build-log.txt](https://github.com/gabime/spdlog/files/10870127/build-log.txt)

**Comment by tt4g** [comment]
Duplicate #2637

**Comment by Nathie1000** [comment]
I missed that one, my apologies.
