### ISSUE TITLE
SPDLOG_DEBUG doesn't work without setting a default logger. Undocumented?

### ISSUE THREAD

**Issue by oct15demo** [gabime/spdlog#2665]
New edit:  I seem to recall setting the default logger previously to get the SPDLOG_DEBUG to work. The thing is that I'm not sure I wasn't just tinkering with the machine until it ran, or I did actually see instructions for it somewhere. If there were instructions, I couldn't find them today when I went to look for them as I was switching my logging around. Below is my original post:

SPDLOG_DEBUG doesn't work without setting a default logger. 
Not documented? I didn't see. Did I miss something obvious?

No matter what you do, spdlog pays no attention to 
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG 
or even 
   logger.set_level(spdlog::level::debug);
has no effect unless you also set it as default logger
   spdlog::set_default_logger(logger);
and for completeness you of course first create a logger with
   logger = spdlog::get("log");

So even though there is something about set_level, not in the documentation, but here
https://github.com/gabime/spdlog/issues/1318 
and even though setting the default level for the logger appears in the example, it isn't noted that this is necessary for the level to take affect for the static compile time logging of SPDLOG_DEBUG
Not using anything but compile time logging because you want line numbers and links in your logs to the source code in your IDE? This is needed. You have to create a logger, set the level, and set as the default logger. I think I had this working before because I accidentally had a default logger set to the level I wanted for the SPDLOG_LEVEL. 

Many developers programming in Java in an IDE are used to having the logs with links to the source code. I like spdlog, but a C++ logging framework shouldn't make this facility any harder. I guess it isn't if you figure out the above. I'd add that it would be nice to have a naming convention less cumbersome than SPDLOG_DEBUG, although I understand it's partly to show it represents a macro. I tried to customize it, even hacking the spdlog.h or common.h files, and it worked with some drawbacks that needn't be present if the library was designed to configure for two alternatives modes, dynamic or static. Then my code would look like normal logging, as in logger.debug("my message").

**Comment by tt4g** [comment]
Logging macros (such as `SPDLOG_DEBUG` and `SPDLOG_INFO`) are provided to remove unnecessary logging statements at compile time: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-
Note that these macros are removed at compile time depending on the log level specified in the `SPDLOG_ACTIVE_LEVEL` macro.

And logging macros that do not contain `LOGGER` in the macro name use the default logger.
If you want to use a non-default logger, use a macro that accepts a logger as an argument.

Example:

```cpp
SPDLOG_DEBUG("debug message to default logger.");
SPDLOG_LOGGER_DEBUG(local_logger, "debug message to local_logger.");
```

https://github.com/gabime/spdlog/blob/d07e8cb576ccb5533f479dd1258e5b609ab010a6/include/spdlog/spdlog.h#L311-L325

**Comment by oct15demo** [comment]
Thank you, that's very helpful to know. But I think you're also saying that I wasn't incorrect in stating that the current examples and documentation omit the information about needing a logger and setting it to default, or as per your comment, adding a non-default logger to the logging parameters. Also, I well understand the advantage of log calls below  the level set not being compiled. But a very important consideration for me using logging, including spdlog, is the ability to log the line numbers, and have the logs in the IDE console link to the source. I repeat that point only to provide an additional reason to make the feature easy to understand and use. It's part of my plea to improve the documentation. The more developers using spdlog, the more portable my code, and easier to understand, and the more valuable my familiarity with spdlog will become. It helps me justify the choice to use spdlog over other logging libraries.

**Comment by tt4g** [comment]
Improvements are welcome as the Wiki is maintained by the community.

However, the answer to the same question as yours is in the FAQ: https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format
