### ISSUE TITLE
Support for std::complex format

### ISSUE THREAD

**Issue by CaslabUM** [gabime/spdlog#267]
Is it possible to add support for printing complex number. 
Or can someone point me to the functions/class I should look into? I am trying to figure it out. I am using it in a templated function so explicitly calling `.real()` or `.imag()` for printing is not an option.

Possible format:
`(x.real(), x.imag())`

**Comment by anandpratap** [comment]
Sorry I did not realize that the formatting is handled by another library. I will ask them.
