### ISSUE TITLE
why spdlog record repeat？

### ISSUE THREAD

**Issue by LiXuefei007** [gabime/spdlog#2671]
![image](https://user-images.githubusercontent.com/113502667/224466901-6bdf0998-4bd5-4dc8-a37d-355841609ff4.png)
![image](https://user-images.githubusercontent.com/113502667/224466983-243ace3c-10b5-4d5a-8055-2f6b3bab4ce7.png)

I set the static int ii want to locate the problem,but it puzzle me more,it record 1,2,1,2 ? ? ?
and the next line "run complete"  only once,which in the same action scope;

when i add "return true" flow the "start run" ,it record only once too,why????

I find the error info,which show the same file
![image](https://user-images.githubusercontent.com/113502667/224470682-627c86ad-9e46-4f83-85fb-3a56b98c18ee.png)
is this cause this problem?? 
__________________________________________________________________________________________________________________________________
more infomation:

package spdlog in a singleton class:

```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
#include "spdlog/spdlog.h"
#include "spdlog/async.h"
#include "spdlog/sinks/rotating_file_sink.h"

class Log{
public:
    static Log& getInstance(){
        static Log instance;
        return instance;
    }
    std::shared_ptr<spdlog::logger> getAccessLog(){
        return accessLog;
    }
private:
    ~Log(){
        spdlog::drop_all();
    }
    Log(){
        spdlog::drop_all();
        spdlog::init_thread_pool(100,1);
        accessLog = spdlog::rotating_logger_mt<spdlog::async_factory>("accessLog","log/access.log",1024*1024*3,3);
        accessLog->set_pattern("[%c][%s:%#]: %v");
    }
    std::shared_ptr<spdlog::logger> accessLog;
};

```

used in:

currentSimulate.h
```
class CurrentSimulate{
    //something unimpotant
    //.....
public:
    bool run();
};
```
currentSimulate.cpp

```
CurrentSimulate::bool run(){
      auto accessLog = Log::getInstance().getAccessLog();
      //somethin unimportant
      if(tag){

      }else{
          static int ii = 0;
          SPDLOG_LOGGER_INFO(accessLog,"start xxxxxxxxxxx,pid,pid_t,ii",ii);
          ii++;
          SPDLOG_LOGGER_INFO(accessLog,"start xxxxxxxxxxx,pid,pid_t,ii",ii);
          ii++;
          //here transfer a function which cost 5 minute
          //......
          SPDLOG_LOGGER_INFO(accessLog,"complete xxxxxxxxx");
      }
  }
```

CurrentSimulate is called at a deeper lever ,through a multiprocess_pool tool lib;
when I set Log::accessLog->flush_on(spdlog::level::trace),it record nothing at "start",when I don't set this ,it record repeat;
whether i set or not, spdlog send an error:
"LOG ERROR # 0001 : [accessLog] {arguement not fount} [the file where functionCurrentSimulate::run  implementation] [line where log start ]"

if i record "start" then return immediately(don't call  the fowllow function which cost 5 minute,it recode once.

**Comment by tt4g** [comment]
Nothing is known from a piece of source code. Please provide the minimum source code that can reproduce the problem.

**Comment by LiXuefei007** [comment]
> Nothing is known from a piece of source code. Please provide the minimum source code that can reproduce the problem.

ok ,I add some information. 
The original code is in a large project, and I cannot copy it, so I can only re-enter part of it.
thanks

**Comment by tt4g** [comment]
It is assumed that the cause is that the function body and static variables are written in the header file.
Since the logger definitions are copied into the source code that imported the header files, the variable `ii` definitions are also copied at each copied location. It will not work as expected because there are variable `ii`s generated in different memories.
This is due to the C++ specification.

Static variables should be in `.cpp`, not in header files.

**Comment by LiXuefei007** [comment]
> It is assumed that the cause is that the function body and static variables are written in the header file. Since the logger definitions are copied into the source code that imported the header files, the variable `ii` definitions are also copied at each copied location. It will not work as expected because there are variable `ii`s generated in different memories. This is due to the C++ specification.
> 
> Static variables should be in `.cpp`, not in header files.

I'm very sorry that my mistake has caused you misunderstanding. the CurrentSimulate::run()  body is not in the header file.I just wrote it together when I re-typed the code,I will modify

**Comment by tt4g** [comment]
The first image shows that log messages `start xxxxxxxxxxx,pid,pid_t,ii` is output the total of four times, but `complete xxxxxxxxx` is output only once.
If it were an spdlog problem, `complete xxxxxxxxx` would also be output twice.
So I don't think this is a spdlog problem, but simply that you have written code that outputs the log message `start xxxxxxxxxxx,pid,pid_t,ii` four times.

**Comment by LiXuefei007** [comment]
> The first image shows that log messages `start xxxxxxxxxxx,pid,pid_t,ii` is output the total of four times, but `complete xxxxxxxxx` is output only once. If it were an spdlog problem, `complete xxxxxxxxx` would also be output twice. So I don't think this is a spdlog problem, but simply that you have written code that outputs the log message `start xxxxxxxxxxx,pid,pid_t,ii` four times.

maybe,I'll check it again.
In short, thank you very much for spending so much time to help me. I am grateful for that
