### ISSUE TITLE
spdlog on linux doesn't write on ~

### ISSUE THREAD

**Issue by lucacostantinosynopsys** [gabime/spdlog#2672]
auto logger = spdlog::basic_logger_mt("basic_logger", "~/logger.txt"); does NOT work
auto logger = spdlog::basic_logger_mt("basic_logger", "/home/user/logger.txt"); works

**Comment by xvitaly** [comment]
`~` is a [bash expansion function](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html). You need to use `getenv("HOME")`.

**Comment by lucacostantinosynopsys** [comment]
I find it a bit odd, especially as no erorr/warning is raised.
Anyway, if that's the intended behavior, I won't insist...

Thanks for the quick reply!

**Comment by xvitaly** [comment]
>  Anyway, if that's the intended behavior, I won't insist...

Yes, this is intended. `~` is a bash-only expansion. It can't be used on file system level.

**Comment by gabime** [comment]
> especially as no erorr/warning is raised.

 If log file cannot be created, an exception should be thrown from the constructor. What exactly happens in this scenario?

**Comment by lucacostantinosynopsys** [comment]
Just no log file was created.
But I was doing a lot of tries to solve _another_ issue, so I may or may not have out a try/catch block...

**Comment by lucacostantinosynopsys** [comment]
> `~` is a [bash expansion function](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html). You need to use `getenv("HOME")`.

Yeah, this is what I ended up doing...
