### ISSUE TITLE
New v1.x release

### ISSUE THREAD

**Issue by LtdSauce** [gabime/spdlog#2674]
Hi,

we'd like to have access to the fmt/std.h headers but are relying on the released versions of spdlog. 
Those got introduced right after the last release (https://github.com/gabime/spdlog/pull/2539).
Could it be possible to make a new release of the v1.x branch?

Thanks in advance!

**Comment by gabime** [comment]
It will have to wait for the official fmt release. 
Note you can use external fmt version using the SPDLOG_FMT_EXTERNAL_HO or the SPDLOG_FMT_EXTERNAL cmake flags.

**Comment by LtdSauce** [comment]
Thanks for the fast reply! 

Sorry to hear it has to wait.

I'll close the issue as my question was answered. Thanks again!
