### ISSUE TITLE
Can't compile in Cu file

### ISSUE THREAD

**Issue by WanyWany88** [gabime/spdlog#2675]
when add spdlog library in cu file, the error occurs.

fmt\bundled\format.h(2501): error : too many recursive substitutions of function template signatures

detected during:  processing of template argument list for "fmt::v9::detail::has_isfinite"

and

duplicate base class name

![오류](https://user-images.githubusercontent.com/29081883/225261011-e4c9f5d8-53c2-4b85-8e39-9427d112ddda.PNG)

help me~!! thanks your best

**Comment by tt4g** [comment]
`spdlog/fmt/bundled/format.h` is copied from fmt project.
It is recommended that reopen issue in [fmt project](https://github.com/fmtlib/fmt).
