### ISSUE TITLE
syslog sink enable_formatting example

### ISSUE THREAD

**Issue by laped83** [gabime/spdlog#2676]
Do anybody have a simple example on how to use the enable_formatting option in the syslog_sink.h? What I'm looking for is a way to add source file and line number to a syslog message.

**Comment by tt4g** [comment]
Example code exists in Wiki:

syslog_sink example: https://github.com/gabime/spdlog/wiki/4.-Sinks

print source information example: https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

See also: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

**Comment by laped83** [comment]
@tt4g Thanks for the response. if I use the example from the `source-information-do-not-appear` . I'll get something like the following. The syslog sink is only printing the message in all cases.  I thought the enable_formatting option could be used in some fancy way somehow.

https://github.com/gabime/spdlog/blob/ad08f13aacc92b5e38c4a77f9cabd24d54fd53b1/include/spdlog/sinks/syslog_sink.h#L24

stdout sink
```
[source test2.cpp] [function main] [line 11] log with source info
[source test2.cpp] [function main] [line 12] global log with source info
[source ] [function ] [line ] source info is not printed
```

syslog sink
```
Mar 15 11:40:38 laped a.out[138294]: log with source info
Mar 15 11:40:38 laped a.out[138294]: global log with source info
Mar 15 11:40:38 laped a.out[138294]: source info is not printed
```

**Comment by tt4g** [comment]
Yes. You need specify `enable_formatting = true` to call spdlog formatter.

**Comment by laped83** [comment]
@tt4g Okay thanks it works with `enable_formatting = true` I just posted the code if someone else should come across this post 

```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO 
#include "spdlog/spdlog.h"
#include "spdlog/sinks/syslog_sink.h"

int main()
{
    auto console = spdlog::syslog_logger_mt( "console", "", 0, LOG_USER, true );
    spdlog::set_default_logger(console);
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");

    SPDLOG_LOGGER_INFO(console, "log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 10] log with source info"
    SPDLOG_INFO("global log with source info"); // Console: "[source example.cpp] [function source_info_example] [line 11] global logger with source info"

    console->info("source info is not printed"); // Console: "[source ] [function ] [line ] source info is not printed"
}

```
