### ISSUE TITLE
Error while trying to create library in CLI for interworking with C# using spdlog

### ISSUE THREAD

**Issue by WanyWany88** [gabime/spdlog#2677]
#error:  <condition_variable> is not supported when compiling with /clr or /clr:pure.	

It's not exactly a problem with spdlog, but it's probably a problem with threads and mutex.

I'm looking for a solution, but it's hard to find, so I'm asking here.

Is there any way to avoid this problem?

**Comment by tt4g** [comment]
C++/CLI is not compatible because it is not C++.
There is no workaround.
