### ISSUE TITLE
No color in console 

### ISSUE THREAD

**Issue by SlavaC1** [gabime/spdlog#2679]
I'm creating color console sink on windows, but for some reason I can see no colors. 

`
        auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
	console_sink->set_pattern("%X:%e - [%P][%t][%L] - %v [%s:%#]");

	auto logger = std::make_shared<spdlog::logger>("net", console_sink);

	spdlog::register_logger(logger);

	spdlog::get("net")->warn("Hello, {}!", "World");
`

There are colors when using default log but not in mine. Please advice.

**Comment by gabime** [comment]
https://github.com/gabime/spdlog/wiki/0.-FAQ#colors-do-not-appear-when-using-custom-format

**Comment by SlavaC1** [comment]
Thanks a lot! Missed that
