### ISSUE TITLE
centos gcc 编译报错

### ISSUE THREAD

**Issue by zjp8023** [gabime/spdlog#2684]
/opt/sourcecode/spdlog/example/example.cpp:278:13: 错误：在不同命名空间内对‘template<class T, class Char, class Enable> struct fmt::v9::formatter’的特例化 [-fpermissive]
 struct fmt::formatter<my_type> : fmt::formatter<std::string>
             ^
In file included from /opt/sourcecode/spdlog/include/spdlog/fmt/fmt.h:27:0,
                 from /opt/sourcecode/spdlog/include/spdlog/common.h:50,
                 from /opt/sourcecode/spdlog/include/spdlog/spdlog.h:12,
                 from /opt/sourcecode/spdlog/example/example.cpp:30:
/opt/sourcecode/spdlog/include/spdlog/fmt/bundled/core.h:791:8: 错误：  从‘template<class T, class Char, class Enable> struct fmt::v9::formatter’的定义 [-fpermissive]
 struct formatter {
        ^
make[2]: *** [example/CMakeFiles/example.dir/example.cpp.o] 错误 1
make[1]: *** [example/CMakeFiles/example.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by zjp8023** [comment]
执行  make -j4 时出错

**Comment by tt4g** [comment]
EDITED:
~~`spdlog/include/spdlog/fmt/bundled/core.h` is copied fmt library. Please reopen issue in [fmt repository](https://github.com/fmtlib/fmt).~~ See [next comment](https://github.com/gabime/spdlog/issues/2684#issuecomment-1480565717).

**Comment by tt4g** [comment]
Duplicate #2576
This is GCC problem, GCC v4.8 does not fully support the C++11 standard.

Note please include OS and compiler version information in the Issue.

**Comment by zjp8023** [comment]
> Duplicate #2576 This is GCC problem, GCC v4.8 does not fully support the C++11 standard.
> 
> Note please include OS and compiler version information in the Issue.

谢谢你，这个的确是gcc 版本上存在差异。gcc 8.5编译通过，而在gcc 11.2.1 编译失败。
[root@11:02:35 /opt/sourcecode]#gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-11/root/usr --mandir=/opt/rh/devtoolset-11/root/usr/share/man --infodir=/opt/rh/devtoolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)

**Comment by tt4g** [comment]
I can't help you because you have not provided a complete error message as stated in your previous comment.
However maybe duplicate #2637
