### ISSUE TITLE
What's happen?? with mistake

### ISSUE THREAD

**Issue by NHIKMUS** [gabime/spdlog#2689]
![image](https://user-images.githubusercontent.com/75536271/227744331-ee6dbb9d-661a-4677-a18c-8eb8268c98b0.png)

**Comment by NHIKMUS** [comment]
![image](https://user-images.githubusercontent.com/75536271/227745516-d417c08b-778a-4222-b125-6793f93eb8d8.png)

//////////////////////////////
all code here
//////////////////////////////


	#include <iostream>
	#include <thread>
	#include <chrono>
	#include <cstdlib>
	#include "spdlog/spdlog.h"
	#pragma warning(disable : 4996)
	int main()
	{
	spdlog::set_level(spdlog::level::trace); // Set global log level to debug

	spdlog::error("Some error message with arg: {}", 1);

	spdlog::trace("HelloWorld!");
	spdlog::info("Welcome to spdlog!");
	spdlog::warn("Easy padding in numbers like {:08d}", 12);
	spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
	spdlog::info("Support for floats {:03.2f}", 1.23456);
	//std::this_thread::sleep_for(0.5s);
	spdlog::info("Positional args are {1} {0}..", "too", "supported");


	spdlog::info("{:<30}", "left aligned");
	std::cout << std::getenv("path") << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	std::cout << "ssssssssssssssss" << "\n";
	//spdlog::debug("This message should be displayed..");

	// change log pattern
	///spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");

	// Compile time log levels
	// define SPDLOG_ACTIVE_LEVEL to desired level
	SPDLOG_TRACE("Some trace message with param {}", 42);
	SPDLOG_DEBUG("Some debug message");
	std::system("pause");
	}

**Comment by KMUS1997** [comment]
#include <iostream>
#include <thread>
#include <chrono>
#include <cstdlib>

**Comment by tt4g** [comment]
I have no idea what your problem is.
Please explain properly what you are having trouble with, including stating the expected results and actual facts.

**Comment by tt4g** [comment]
If you were expecting the output of `spdlog::info("Support for floats {:03.2f}", 1.23456);` to be `001.23`, the format is wrong.
The number following the `0` for zero fill is the length of the entire string after formatting.
This is the same specification as `printf()`.


```diff
-spdlog::info("Support for floats {:03.2f}", 1.23456);
+spdlog::info("Support for floats {:06.2f}", 1.23456);
```

Example: https://godbolt.org/z/f1cnsr9Tn

See also: [Format String Syntax — fmt 9.1.0 documentation](https://fmt.dev/9.1.0/syntax.html#format-specification-mini-language)

**Comment by NHIKMUS** [comment]
the result dont match the code， just in a single main function. 
 the library have a confilict with the std:cout funciton. 
 you can just copy my code ,and have a try. 
 I do not know whats happen .
 
 I do not know why they have conflict in a single thread? the log result is  either missing  ,  or repeated.

**Comment by tt4g** [comment]
Cannot reproduce. I can only assume it was not built after the source code was changed.

**Comment by NHIKMUS** [comment]
![image](https://user-images.githubusercontent.com/75536271/227770139-c1781a93-6d74-4fbd-b4d1-44fe1fb144c0.png)


In case that  start without debug , it can reproduce the secene

my compiler is msvc ,the latest one .  Visual Stuido 2022 on Win system

**Comment by NHIKMUS** [comment]
The mistakes only happen when I build and run,  but in debug mode , it is normal，and works。

![image](https://user-images.githubusercontent.com/75536271/227770377-7bed1f59-e3a9-4212-8ac8-827f106715f2.png)

**Comment by tt4g** [comment]
I keep seeing a red line on the `std::cout << "ssssssssssssssss" << "\n";` line, is it compiling successfully? Isn't that red line what you see when you are reporting an error?

**Comment by tt4g** [comment]
Comment out all lines using `std::cout` and recompile.

**Comment by NHIKMUS** [comment]
I want to issue a problem that we meeted now, 
Our log can not work with std::cout even in a single Thread, when ostream conatins a lot of contents.
It is a big issue. 
Even more , on debug mode ,no any problem , but once i build the program ,the mistakes happened.

**Comment by tt4g** [comment]
If the bug is unrelated to spdlog, please ask on StackOverflow or other question sites.

**Comment by NHIKMUS** [comment]
the spdlog, repeatedly print only the front two with mistake. the bug happen in the inner of spdlog .
so how can we get a  two repeated Msg ?

![image](https://user-images.githubusercontent.com/75536271/227771747-aa6c0c21-744b-451a-9bef-c7e2cd4775ff.png)

**Comment by tt4g** [comment]
Please provide code that reproduces the problem with all code not related to spdlog removed.
I suspect you are continuing to debug with a compile error and not compiling correctly.

**Comment by NHIKMUS** [comment]
All you said is  right, all wrongs left to me.

**Comment by NHIKMUS** [comment]
Okay ,  I Finally get the answer why the mistake  hanppened, 
win 11 terminal bugs, once I changed it to PowerShell,  no such happen.
Thank you , and std::cout << "sssssssssssssss"<<"\n";  no any mistake, just spell not meet the vs assist.
