### ISSUE TITLE
Is spdlog crash-safe?

### ISSUE THREAD

**Issue by agauniyal** [gabime/spdlog#269]
Crash-safe as advertised by several other logging libraries - https://github.com/KjellKod/g3log , https://github.com/easylogging/easyloggingpp . Will it write all pending logs before actually exiting the program in case of let's say `SIGSEGV` segmentation fault.

**Comment by agauniyal** [comment]
I also saw mention of errors here - https://github.com/gabime/spdlog/blob/451aadec97ccd6701b685cf21800872adade2181/tests/catch.hpp#L5109

**Comment by gabime** [comment]
no, there is no special handling of crashes

**Comment by agauniyal** [comment]
do you plan to support it in future? This is the only dealbreaker for me, otherwise your library is top-notch 💯

**Comment by gabime** [comment]
maybe. though I am not sure it should be the responsiblty of the lib, to handle user crashes..

**Comment by agauniyal** [comment]
I completely agree, but since it might use async logs, shouldn't saving the logs that are still in queue or something be the responsibility of lib?

**Comment by agauniyal** [comment]
Okay thanks 😄 .
