### ISSUE TITLE
spdlog fails to build with latest fmt

### ISSUE THREAD

**Issue by H1X4Dev** [gabime/spdlog#2693]
Using latest fmt, the spdlog will fail to build.

You must change the **basic_runtime** to **runtime_format_string** to fix the issue, however bundled spdlog uses **basic_runtime.** Line: https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/common.h#L181

**Comment by gabime** [comment]
PR is welcome.

**Comment by H1X4Dev** [comment]
It seems like won't really be an easy fix without hacky ways, such as definining "FMT_VERSION_MASTER" on cmake option, because their Release fmt version is the same as master fmt, but with breaking differences. If this is something allowed to add, I can make the patch for it, otherwise I don't know a valid fix that would be compatible with both versions.

**Comment by gabime** [comment]
The version in fmt head is [the unreleased) 90101, while spdlog use 90100. We can check the fmt version and apply the fix if it is >= 90101
