### ISSUE TITLE
Vulnerability detected by security scan in core.h

### ISSUE THREAD

**Issue by eugrin** [gabime/spdlog#2698]
cpp/enum-index (in thirdparty/spdlog/include/spdlog/fmt/bundled/core.h

When accessing array values_ with index id, the upper bound of an enum is used to check the upper bound of the array, but the lower bound is not checked.
2029 arg.type_ = type(id);
2030 if (arg.type_ == detail::type::none_type) return arg;
2031 arg.value_ = values_[**id**];
2032 return arg;
2033 }

**Comment by tt4g** [comment]
Please reoepn issue in [fmt project](https://github.com/fmtlib/fmt), because `include/spdlog/fmt/bundled/core.h` is fmt library source.

**Comment by tt4g** [comment]
Closed in fmt project: fmtlib/fmt#3371
