### ISSUE TITLE
Vulnerability detected in format.h

### ISSUE THREAD

**Issue by eugrin** [gabime/spdlog#2699]
cpp/infiniteloop (in thirdparty/spdlog/include/spdlog/fmt/bundled/format.h

In count_separators comparison between call to expression of type unknown and num_digits of wider type int.
1964 int count = 0;
1965 auto state = initial_state();
1966  while (**num_digits > next(state)**) ++count;
1967 return count;
1968 }

**Comment by tt4g** [comment]
Please reoepn issue in [fmt project](https://github.com/fmtlib/fmt), because `include/spdlog/fmt/bundled/format.h` is fmt library source.

**Comment by tt4g** [comment]
Closed in fmt project: fmtlib/fmt#3372
