### ISSUE TITLE
adding support for meson build system

### ISSUE THREAD

**Issue by agauniyal** [gabime/spdlog#270]
Would you mind a PR for adding a basic support for meson build system - https://github.com/mesonbuild/meson. Though I might not be able to reproduce full CMakeLists.txt build, but a simple `meson.build` file could allow meson users to import your library into their build system. It would look something like this - 

```
project('spdlog', 'cpp', version : '0.10.0',
        default_options : ['cpp_std=c++11'])

inc = include_directories('include/spdlog')
```

And other users could import by adding a git url in their subprojects directory which would make things a lot easier for us :)

**Comment by gabime** [comment]
Thanks, but I am sure there are better places for this (like central repo of mason build scripts?)

**Comment by agauniyal** [comment]
Allright they've been quite unresponsive for a bit, but I'll try again :)

**Comment by agauniyal** [comment]
@gabime - https://wrapdb.mesonbuild.com/spdlog

I'll be frequently checking for new releases and update it, however you can also ping me if required :)

**Comment by kierun** [comment]
@agauniyal Do you have an example as to how to use your wrap in the "main" `meson.build` file?

**Comment by polesapart** [comment]
Late to the party but:
`mkdir subprojects && meson wrap install spdlog`
then on "main" meson.build:
`spdlog = subproject('spdlog')
spdlog_dep = spdlog.get_variable('spdlog_dep')`

and you add spdlog_dep in dependencies of any target, e.g.
`foo = executable('foo', foo_sources, dependencies: [whatever, spdlog_dep])`
