### ISSUE TITLE
Writing logs is delayed, causing a program delay

### ISSUE THREAD

**Issue by libraqq** [gabime/spdlog#2700]
I have a problem about LOG time and I need to ask you about it. I turned over a historical issue, maybe I left out relevant issues.
I originally planned to use a single LOG log for multiple threads, but I found that there was a log delay that caused the program to lag. Later, it was changed to using one LOG per thread, but there was still a log delay when there was a continuous log write.
Here's the code I tested:

#include "../include/demo/tic_toc.h"
#include <thread>
#include "../include/spdlog/common.h"
#include "../include/spdlog/logger.h"
#include "../include/spdlog/pattern_formatter.h"
#include "../include/spdlog/sinks/basic_file_sink.h"
#include "../include/spdlog/sinks/daily_file_sink.h"
#include "../include/spdlog/sinks/rotating_file_sink.h"
#include "../include/spdlog/sinks/stdout_color_sinks.h"
#include "../include/spdlog/sinks/sink.h"
#include "../include/spdlog/spdlog.h"
#include <sys/time.h>

TicToc c_time1;

auto c_log = spdlog::rotating_logger_st("test", "/home/demoTest/test.log", 1024x1024x500, 3);

static std::string getWholeSysTime()
{
    struct timeval l_CurrTime_;
    gettimeofday(&l_CurrTime_, NULL);

    char timename[100];
    struct tm* ptm;
    long milliseconds;

    ptm = localtime(&(l_CurrTime_.tv_sec));
    strftime(timename, sizeof(timename), "%Y-%m-%d-%H-%M-%S", ptm);
    milliseconds = l_CurrTime_.tv_usec / 1000;

    sprintf(timename, "%s-%03ld", timename, milliseconds);
    return std::string(timename);
}

void threadPrintf(int p_iNum)
{
    for (int j = 0; j < p_iNum; j++)
    {
        c_time1.tic();
        std::string time = getWholeSysTime();
        c_time1.tic();
        c_log->info("{} {} 正在连续保存日志， 正在连续保存日志，正在连续保存日志，正在连续保存日志，正在连续保存日志，正在连续保存日志，正在连续保存日志，thread1", time, j);
        printf("after threadPrintf: %f - %d\n", c_time1.toc(), j);
        usleep(1000);
    }
}

int main(int argc, const char** argv)
{
    if (argc < 1)
    {
        printf("请设置参数\n");
        return 0;
    }
    int num = std::atoi(argv[1]);
    threadPrintf(num);
    return 0;
}

The question:
[2023-04-07 16:48:33.344] [test] [info] 2023-04-07-16-48-33-343 52224 正在连续保存日志，......... thread1
[2023-04-07 16:48:33.345] [test] [info] 2023-04-07-16-48-33-345 52225 正在连续保存日志，......... thread1
[2023-04-07 16:48:33.353] [test] [info] 2023-04-07-16-48-33-353 52226 正在连续保存日志，......... thread1
[2023-04-07 16:48:33.354] [test] [info] 2023-04-07-16-48-33-354 52227 正在连续保存日志，......... thread1

after threadPrintf: 0.003388 - 52223
after threadPrintf: 0.002091 - 52224
after threadPrintf: 7.122803 - 52225
after threadPrintf: 0.003483 - 52226

The execution c_log->info time increases suddenly 7.122803
There is a delay in recording data of 52225. As a result, data generation of 52226 is delayed.

Environment: Ubuntu 20.04  VS Code

**Comment by tt4g** [comment]
I don't understand why you think spdlog is slow. The time printed at the top of the log message is only a few milliseconds ahead of time.
Why do you not think that `printf()` or `c_time1.toc()` is slow?

In any case, please get benchmarks with strace command, etc. to identify really slow instructions.

**Comment by libraqq** [comment]
Thank you for your timely reply. I will go to improve my test again.
