### ISSUE TITLE
Error code C2129 static function 'errno_t localtime_s(tm *const ,const time_t *const )' declared but not defined

### ISSUE THREAD

**Issue by efgi1** [gabime/spdlog#2701]
With Visual Studio 2022 (v143) using c++20 and modules, I'm getting the error

Severity	Code	Description
Error	C2129	static function 'errno_t localtime_s(tm *const ,const time_t *const )' declared but not defined

For others with this issue, it is a known issue with modules (see https://developercommunity.visualstudio.com/t/Visual-Studio-cant-find-time-function/1126857)

The work around is to explicitly use _localtime_64_s instead at os-inl.h (line 91). I'm not sure if this should be a permanent fix and so did not submit a pull request

**Comment by gabime** [comment]
Thanks. Seems like a vc issue rather than spdlog’s.

**Comment by YanAnghelp** [comment]
I also encountered the same problem, hope VS fixed as soon as possible
