### ISSUE TITLE
wired thing happen: handle_flag_ doesn't actually run!

### ISSUE THREAD

**Issue by stayknight** [gabime/spdlog#2704]
I'm using spdlog in my project  with cmake. The project compiles ok. But when I started the compiled executalbe, I noticed that the timestamp printed by spdlog is `[1900-01-00 00:00:00.xxx]`. Then I followed the code, added some std::cout to some functions, But I can't understand the output in the console. Here's the code:
```cpp
// pattern_formatter-inl.h
template<typename Padder>
SPDLOG_INLINE void pattern_formatter::handle_flag_(char flag, details::padding_info padding)
{
    std::cout << fmt::format("handle_flag_ flag={}", flag) << std::endl;  // add a log here
    ...

SPDLOG_INLINE void pattern_formatter::compile_pattern_(const std::string &pattern)
{
    ...
            if (it != end)
            {
                if (padding.enabled())
                {
                    handle_flag_<details::scoped_padder>(*it, padding);
                }
                else
                {
                    handle_flag_<details::null_scoped_padder>(*it, padding);
                }
                std::cout << fmt::format("compile_pattern_ flag={}, need_localtime_={}", *it, need_localtime_) << std::endl;  // add a log here
            }
            else
            {
                break;
            }
    ...
```
The problem is that the log in `compile_pattern_` was printed while the log in `handle_flag_` wasn't. And the value of `need_localtime_` is always false.
 Is it some problem about c++ template?

---------
Arch: armv7l
OS: Ubuntu 20.04.5 LTS
g++: 9.4.0
spdlog: 1.11

**Comment by tt4g** [comment]
> I noticed that the timestamp printed by spdlog is [1900-01-00 00:00:00.xxx]

I don't see what's wrong with this: it's a print pattern for spdlog's default format flag `%+`.

https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/details/registry-inl.h#L33-L34

https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/pattern_formatter-inl.h#L1035-L1045

The problem with the `std::cout` not printing is considered a project problem.
If the project is divided into library and executable, then maybe the spdlog code is not shared?

**Comment by stayknight** [comment]
> > I noticed that the timestamp printed by spdlog is [1900-01-00 00:00:00.xxx]
> 
> I don't see what's wrong with this: it's a print pattern for spdlog's default format flag `%+`.
> 
> https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/details/registry-inl.h#L33-L34
> 
> https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/pattern_formatter-inl.h#L1035-L1045
> 
> The problem with the `std::cout` not printing is considered a project problem. If the project is divided into library and executable, then maybe the spdlog code is not shared?

The timestamp was not correct because the variable `need_localtime_` was false. And the variable is false because handle_flag_ is not called, which seems not possible.

**Comment by stayknight** [comment]
Update: I changed my dependency of spdlog to spdlog_header_only, then there's no problem any more. I guess it is a template problem about seperate compilation.

**Comment by tt4g** [comment]
Probably the same problem: #2681

It seems to be a mix of header-only spdlog and static/shared library spdlog.
Since you are using different symbols, the information printed by the debugger is unreliable.
