### ISSUE TITLE
 how to create a log file every few minutes

### ISSUE THREAD

**Issue by syclsp** [gabime/spdlog#2705]
May I ask how to create a log file every few minutes, I only found the missionary log file every hour-----

template <typename Factory = spdlog::synchronous_factory>
inline std::shared_ptr<logger> zcode_logger_mt(
    const std::string &logger_name, const filename_t &filename, int hour = 1, spdlog::level::level_enum consoleLevel = spdlog::level::info, spdlog::level::level_enum fileLevel = spdlog::level::info, bool truncate = false) {
    return Factory::template create<sinks::zcode_file_sink_mt>(logger_name, filename, hour, consoleLevel, fileLevel, truncate);
}

**Comment by tt4g** [comment]
Minute rolations are not supported.
It is possible to define a custom sink to rotate logs: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink
