### ISSUE TITLE
Error when running example in spdlog/example

### ISSUE THREAD

**Issue by zhang123-sys** [gabime/spdlog#2709]
![image](https://user-images.githubusercontent.com/63956071/232651112-10e18778-852d-411d-9718-376970aa535f.png)

**Comment by zhang123-sys** [comment]
cmake .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /root/cpp_project/spdlog/example/build
[ 50%] Linking CXX executable example
CMakeFiles/example.dir/example.cpp.o: In function `std::thread::thread<spdlog::details::thread_pool::thread_pool(unsigned long, unsigned long, std::function<void ()>, std::function<void ()>)::{lambda()#1}>(spdlog::details::thread_pool::thread_pool(unsigned long, unsigned long, std::function<void ()>, std::function<void ()>)::{lambda()#1}&&)':
example.cpp:(.text._ZNSt6threadC2IZN6spdlog7details11thread_poolC4EmmSt8functionIFvvEES6_EUlvE_JEEEOT_DpOT0_[_ZNSt6threadC5IZN6spdlog7details11thread_poolC4EmmSt8functionIFvvEES6_EUlvE_JEEEOT_DpOT0_]+0x2f): undefined reference to `pthread_create'
CMakeFiles/example.dir/example.cpp.o: In function `std::thread::thread<spdlog::details::periodic_worker::periodic_worker<long, std::ratio<1l, 1l> >(std::function<void ()> const&, std::chrono::duration<long, std::ratio<1l, 1l> >)::{lambda()#1}>(spdlog::details::periodic_worker::periodic_worker<long, std::ratio<1l, 1l> >(std::function<void ()> const&, std::chrono::duration<long, std::ratio<1l, 1l> >)::{lambda()#1}&&)':
example.cpp:(.text._ZNSt6threadC2IZN6spdlog7details15periodic_workerC4IlSt5ratioILl1ELl1EEEERKSt8functionIFvvEENSt6chrono8durationIT_T0_EEEUlvE_JEEEOSE_DpOT0_[_ZNSt6threadC5IZN6spdlog7details15periodic_workerC4IlSt5ratioILl1ELl1EEEERKSt8functionIFvvEENSt6chrono8durationIT_T0_EEEUlvE_JEEEOSE_DpOT0_]+0x2f): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/example.dir/build.make:94: recipe for target 'example' failed
make[2]: *** [example] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example.dir/all' failed
make[1]: *** [CMakeFiles/example.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tt4g** [comment]
> undefined reference to `pthread_create'

The error message explains it all, `pthread_create` is missing.
Please, install pthread on your machine.

If you want help, please provide the complete message of the command and information about the machine you are building on.
I don't know why `pthread` is missing since there is no complete output of `cmake ..` command.

**Comment by zhang123-sys** [comment]
ok



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 18, 2023 11:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gabime/spdlog] Error when running example in spdlog/example(Issue #2709)
