### ISSUE TITLE
Why pack fmt source inside repo?

### ISSUE THREAD

**Issue by agauniyal** [gabime/spdlog#271]
Couldn't it be managed as dependency? So that other projects are also able to use it properly.

**Comment by gabime** [comment]
it is optional. you can ```#define SPDLOG_FMT_EXTERNAL``` before including spdlog.h to use external fmt

**Comment by memsharded** [comment]
In case you could be interested, I have just added an option to the conan spdlog 0.10.0 package (https://www.conan.io/source/spdlog/0.10.0/memsharded/stable) exactly for this purpose. The code for the package recipe is here https://github.com/memsharded/conan-spdlog/blob/master/conanfile.py, is quite self explanatory.

The default option is still using ``fmt`` embedded. Using the package can be done with:

```bash
$ conan install -o spdlog:fmt_external=True
//or for the default embeded
$ conan install 
```

**Comment by gabime** [comment]
@memsharded Cool, very useful.

**Comment by agauniyal** [comment]
@gabime In case external fmt is used, should I just include fmt above where I've included spdlog library or is there something else to do?
@memsharded thankyou 😄 , but atm I'm using meson build system. However I'll look forward using conan in some future projects though.

**Comment by gabime** [comment]
no, you dont need to include fmt. spdlog  includes it (it tries  to include ```<fmt/format.h>``` so make sure the compiler knows where to find it)

**Comment by agauniyal** [comment]
That's a very good news 😄 , it would work without any change to my current conf. Thankyou for your quick support.
