### ISSUE TITLE
Using ringbuffer from default logger in other class

### ISSUE THREAD

**Issue by dressenl** [gabime/spdlog#2710]
I have a ``` logger.h``` file where I set up a logger and add a ringbuffer sink to it like so:

```
auto ringbufferSink = std::make_shared<spdlog::sinks::ringbuffer_sink_mt>(128);  
spdlog::default_logger()->sinks().push_back(ringbufferSink);
```

Now I want to read messages that are stored in the ringbuffer later in another class

I try to access the ringbuffer sink of the default logger like this:

``` auto ringBufferSink = spdlog::default_logger()->sinks()[1]; ```

My problem now is that I can't call ```ringBufferSink.lastformatted()``` because ```ringBufferSink``` is an instance of ```spdlog::sinks:sink``` and I can't seem to cast it to ```spdlog::sinks::ringbuffer_sink```.

Do I miss something or is there another way of achieving that`

Help would be appreciated!

**Comment by gabime** [comment]
What do you mean you cant cast it?

**Comment by dressenl** [comment]
Maybe it's a c++ knowledge problem for me, but all ways I tried failed.

How would you cast it?

**Comment by gabime** [comment]
auto mysink = static_cast<spdlog::sinks::ribgbuffer _sink*>(logger->sinks()[1].get())

**Comment by dressenl** [comment]
That leads to following error: ``` Use of class template 'ringbuffer_sink' requires template arguments; argument deduction not allowed here ```

**Comment by gabime** [comment]
I forgot the "_mt".

Perhaps try 
```
auto mysink = static_cast<spdlog::sinks::ribgbuffer _sink_mt*>(logger->sinks()[1].get())
```

**Comment by dressenl** [comment]
That works, thank you!
