### ISSUE TITLE
Keep first log file when using rotating file sink

### ISSUE THREAD

**Issue by dacrome** [gabime/spdlog#2711]
It would be nice to be able to config that the first log file stays when using the rotating file sink.

Use case: Startup logs can be important to find out why the app crashes later.

Or is it already possible with a specific setup of sinks?

**Comment by tt4g** [comment]
You can handle log file open/close events with `spdlog::file_event_handlers`.
Event handlers can be used to copy log files and generate hard links.

https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/sinks/rotating_file_sink.h#L25-L26

https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/common.h#L329-L342

**Comment by dacrome** [comment]
thanks @tt4g - I will try this now. looks promising for my use case!

**Comment by dacrome** [comment]
yes, with the event handler it works pefect!
