### ISSUE TITLE
SPDLOG_DEBUG not work

### ISSUE THREAD

**Issue by guojun08512** [gabime/spdlog#2712]
tag: v1.11.0
I use example code:

void replace_default_logger_example()
{
    // store the old logger so we don't break other examples.
    auto old_logger = spdlog::default_logger();

    auto new_logger = spdlog::basic_logger_mt("new_default_logger", "logs/new-default-log.txt", true);
    spdlog::set_default_logger(new_logger);
    spdlog::set_level(spdlog::level::info);
    spdlog::debug("This message should not be displayed!");
    spdlog::set_level(spdlog::level::trace);
    spdlog::debug("This message should be displayed..");
    SPDLOG_DEBUG(new_logger, "a Some debug message");
    SPDLOG_DEBUG(new_logger, "a-1 Some debug message");
    spdlog::debug("b Some debug message");
    spdlog::set_default_logger(old_logger);
}

the log file not console ("a/a-1 Some debug message")

[2023-04-20 18:08:57.582] [new_default_logger] [debug] This message should be displayed..
[2023-04-20 18:08:57.582] [new_default_logger] [debug] b Some debug message

**Comment by tt4g** [comment]
Duplicate #2665, #1820

Please define `SPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_DEBUG` macro.

See also:

- https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-
- https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

**Comment by guojun08512** [comment]
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG

int main() 
{
    auto console = spdlog::stdout_logger_mt("console");
    spdlog::set_default_logger(console);
    spdlog::info("Welcome to spdlog!");
    spdlog::error("Some error message with arg: {}", 1);
    
    spdlog::warn("Easy padding in numbers like {:08d}", 12);
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
    spdlog::info("Support for floats {:03.2f}", 1.23456);
    spdlog::info("Positional args are {1} {0}..", "too", "supported");
    spdlog::info("{:<30}", "left aligned");
    
    spdlog::set_level(spdlog::level::debug); // Set global log level to debug
    spdlog::debug("This message should be displayed..");    
    
    // change log pattern
    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");
    
    // Compile time log levels
    // define SPDLOG_ACTIVE_LEVEL to desired level
    SPDLOG_TRACE("Some trace message with param {}", 42);
    SPDLOG_DEBUG("Some debug message");
    SPDLOG_LOGGER_DEBUG(console, "log with source info"); 
}

[2023-04-20 18:31:31.829] [console] [info] Welcome to spdlog!
[2023-04-20 18:31:31.830] [console] [error] Some error message with arg: 1
[2023-04-20 18:31:31.830] [console] [warning] Easy padding in numbers like 00000012
[2023-04-20 18:31:31.830] [console] [critical] Support for int: 42;  hex: 2a;  oct: 52; bin: 101010
[2023-04-20 18:31:31.830] [console] [info] Support for floats 1.23
[2023-04-20 18:31:31.830] [console] [info] Positional args are supported too..
[2023-04-20 18:31:31.830] [console] [info] left aligned
[2023-04-20 18:31:31.830] [console] [debug] This message should be displayed..

The result is the same,
I use conan installed it.

**Comment by guojun08512** [comment]
I use conan install pkg

**Comment by tt4g** [comment]
Macros are meaningless unless defined first.

```diff
+#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
 #include "spdlog/spdlog.h"
 #include "spdlog/sinks/stdout_sinks.h"
-#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
```

**Comment by guojun08512** [comment]
thx， it's work
