### ISSUE TITLE
Logging to a file on a read-only file/location

### ISSUE THREAD

**Issue by radoslavsimeonov** [gabime/spdlog#2718]
Excuse me if duplicated, this is my first ever issue on GitHub.

The logging is working fine, I set up a  rotating file sink (rotating_file_sink_mt) to save events in a log file (the log file is in the application folder/logs), however, I ran the project from a read-only network drive and the application crashed (actually didn't start at all). So, the problem seems to occur when the logger is trying to save the file on protected media, such as a read-only network device (in my case), but also for example when the executable is on DVD-ROM, media ejected (e.g. USB unplugged) or the log file is flagged as read-only

Of course, I can check the log for RW access on every logging but that will fix only my issue and it's something that somehow I prefer not to do. If it cannot write a log, better just to continue without crashing my app

**Comment by gabime** [comment]
spdlog should not crash in such cases.  At most It would throw upon  the logger construction if it fails to create the file. 
Please provide sample code to reproduce.

**Comment by radoslavsimeonov** [comment]
Thank you for the reply.

I am using the logger from a DLL file with a bit more complex code but I made this minimal logger just for testing, It works fine, the logs are written in "rotating.txt" as should but when I make "rotating.txt" read-only (Properties->check 'Read-only'), SPDLOG throw an unhandled exception (_Unhandled exception at 0x00007FFDF3F4FDEC in LogTest.exe: Microsoft C++ exception: spdlog::spdlog_ex at memory location 0x00000019E08FE820_). Executable doesn't start at all(event logged in Windows Events). I am new to C++, writing my very first C++ application and starting from logging. I can open the file for appending to check the file permissions but I have to do that for every event.

main.cpp
```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <iostream>
#include "spdlog/spdlog.h"
#include "spdlog/sinks/rotating_file_sink.h"

int main()
{
    auto max_size = 1048576 * 5;
    auto max_files = 3;
    auto logger = spdlog::rotating_logger_mt("some_logger_name", "logs/rotating.txt", max_size, max_files);

    SPDLOG_LOGGER_CRITICAL(logger,"Write to read-only");
}
 
```

**Comment by gabime** [comment]
You need to wrap the logger creation with try/catch clause to prevent it from crashing. See the example.cpp for full example. 

```c++
try {
  …
  auto logger = spdlog::rotating_logger_mt("some_logger_name", "logs/rotating.txt", max_size, max_files);
}
catch (const spdlog::spdlog_ex &ex) {
     std::printf("Log initialization failed: %s\n", ex.what());
     return -1;
 }
