### ISSUE TITLE
Want to understand how should spdlog::shutdown() needs to be used in a multithreaded application on windows

### ISSUE THREAD

**Issue by akraturi** [gabime/spdlog#2720]
Hey folks 
We have a multithreaded win32 application(10+ threads). We are using an async logger with a custom sink that we have written to satisfy our use case.
There is a feature in the application where users can restart the application. We want to have all the logs flushed and logging cleanup(Sink destruction specifically) before we exit the process.
This is how our restart logic works
1. Spawn a new process for the current executable
2. `spdlog::shutdown()`
3. Exit the current process ` ExitProcess(EXIT_SUCCESS);`

This logic leads to invalid memory access, inside spdlog code and our hunch is this is because `spdlog::shutdown()` is not the very last call that we are doing, and after it has deallocated resources our threads are still pushing logs which are leading to this.

We don't have the option to join the threads or stop them.

Need some guidance on how should spdlog::shutdown() be used with a multi-threaded application?

Here is a minimal reproducible example of this crash. This code does not even use any custom logger or sink, but we get the same behaviour.

```c++
 // SpdlogTest.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include "spdlog/spdlog.h"

#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE

void thread1() {
    while (true) {
        SPDLOG_INFO("I am thread1");
    }
}

void thread2() {
    while (true) {
        SPDLOG_INFO("I am thread2");
    }
}

void thread3() {
    while (true) {
        SPDLOG_INFO("I am thread3");
    }
}

void thread4() {
    while (true) {
        SPDLOG_INFO("I am thread4");
    }
}

int main()
{   
    std::thread t1{ thread1 };
    std::thread t2{ thread2 };
    std::thread t3{ thread3 };
    std::thread t4{ thread4 };
    SPDLOG_INFO("I am main thread");
    Sleep(3000);
    spdlog::shutdown();
}

```

**Comment by tt4g** [comment]
spdlog does not know the user's thread status.
Design it so that it either waits for the thread to exit with `std::thread::join()` or does not call the logging API after calling `spdlog::shutdown()`.

Note, terminating the application without calling `std::thread::join()` or `std::thread::detach()` will cause undefined behavior.
