### ISSUE TITLE
[Question] Why use gold for function(spdlog_enable_sanitizer target_name)

### ISSUE THREAD

**Issue by sunflower-knight** [gabime/spdlog#2721]
I see spdlog use gold as linker in sanitizer ? But why should spdlog use gold ?
To speed up the link time in compile ...
May be gold can find other error in code?

I will appreciate it if developer can leave some comment or links .
Best wishes!

**Comment by gabime** [comment]
If I recall correctly(it was few years ago), the sanitizer required gold linker otherwise it produced link error.

**Comment by sunflower-knight** [comment]
Thanks, I will test it in my own code.
