### ISSUE TITLE
[%s:%#] not work

### ISSUE THREAD

**Issue by fayfive** [gabime/spdlog#2725]
Here is my code
```
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include "spdlog/sinks/rotating_file_sink.h"

int main(int argc, char const *argv[])
{
    // Create color console sink
    auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    console_sink->set_level(spdlog::level::trace);

    // Create rotating file sink
    auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/log", 50 * 1024 * 1024, 10);
    file_sink->set_level(spdlog::level::warn);

    // Create logger with both sinks
    std::vector<spdlog::sink_ptr> sinks {console_sink, file_sink};
    auto logger = std::make_shared<spdlog::logger>("APPLOGER", begin(sinks), end(sinks));
    logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%n] [%^%l%$] [%s:%#] %v");
    // Test logging
    logger->info("This is an info message.");
    logger->warn("This is a warn message.");
    logger->error("This is an error message.");
   
    return 0;
}
```
I want to print the name of the source file and the source line so I use `[%s:%#]`

**Comment by tt4g** [comment]
Duplicate #318

FAQ; https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

**Comment by fayfive** [comment]
Hello! I have added `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE` 
But I can't log like this `logger->info("This is an info message.");` I should log like this `SPDLOG_LOGGER_INFO(logger, "This is an info message.");` I don't know why?
Must I use `SPDLOG_LOGGER_INFO(logger, "This is an info message.");`?

**Comment by tt4g** [comment]
To print source information, you need to use logging macros such as `SPDLOG_LOGGER_INFO` and `SPDLOG_INFO`.
https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

**Comment by fayfive** [comment]
Thanks!
