### ISSUE TITLE
Including spdlog/spdlog.h breaks build and causes strange syntax errors 

### ISSUE THREAD

**Issue by yockey88** [gabime/spdlog#2726]
As the title says, my build is successful until I try to include spdlog/spdlog.h. Here is my build output

[Output-Build.txt](https://github.com/gabime/spdlog/files/11379063/Output-Build.txt)

and logs

[YE2.log](https://github.com/gabime/spdlog/files/11379065/YE2.log)

If I remove the spdlog include these all go away and the build succeeds with no errors.

I am building on Windows 11 intel x86_64 in Visual Studio 2022 v17.5.5 using Visual Studio Build Tools 2019 v16.11.26

**Comment by gabime** [comment]
please post the relevant error messages here instead of logs

**Comment by yockey88** [comment]
C:\Yock\Projects\code\YE2\YE2\include\rendering\SDL2.hpp(82,18): warning C4003: not enough arguments for function-like macro invocation 'CreateWindowW'
C:\Yock\Projects\code\YE2\YE2\include\rendering\SDL2.hpp(82,18): error C2059: syntax error: 'constant'
C:\Yock\Projects\code\YE2\YE2\src\rendering\SDL2.cpp(71,16): warning C4003: not enough arguments for function-like macro invocation 'CreateWindowW'
C:\Yock\Projects\code\YE2\YE2\src\rendering\SDL2.cpp(71,10): error C2761: 'bool YE::rendering::SDL2::CreateWindowExW(void)': redeclaration of member is not allowed
C:\Yock\Projects\code\YE2\YE2\src\rendering\SDL2.cpp(71,16): error C2065: 'config': undeclared identifier
C:\Yock\Projects\code\YE2\YE2\src\rendering\SDL2.cpp(71,16): error C2275: 'YE::rendering::SDL2_Config': expected an expression instead of a type
C:\Yock\Projects\code\YE2\YE2\src\rendering\SDL2.cpp(71,16): error C2059: syntax error: ','
C:\Yock\Projects\code\YE2\YE2\src\rendering\SDL2.cpp(71,50): error C2143: syntax error: missing ';' before '{'
C:\Yock\Projects\code\YE2\YE2\src\rendering\SDL2.cpp(71,50): error C2447: '{': missing function header (old-style formal list?)

These are them, when I remove the spdlog include (nothing implemented, just the include), these errors go away and the program builds and runs correctly with no other changes.

**Comment by tt4g** [comment]
How do you add spdlog to your project?

**Comment by yockey88** [comment]
I use a premake5 script to generate build files (currently only supporting windows Visual Studio) and I just include it with my other external libraries

``` lua
        files {
            "%{prj.name}/include/**.hpp" ,
            "%{prj.name}/src/**.cpp" ,
            "%{externals.imgui}/*.h" ,
            "%{externals.imgui}/*.cpp"
        } 

        includedirs {
            "%{prj.name}/include" 
        }

        externalincludedirs {
            "%{externals.sdl2}/include" ,
            "%{externals.imgui}" ,
            "%{externals.spdlog}/include" ,
            "%{externals.glad}/include" ,
            "%{externals.glm}" ,
            "%{externals.stb}" ,
            "%{externals.reactphysics3d}/include" ,
            "%{externals.asmjit}/src" 
        }
```

This same build system worked a few months back when I made the first iteration of this project.

**Comment by tt4g** [comment]
Oh, I understand. You didn't copy the most important compile error message into the Issue that is causing the problem.
I found the following error in `YE2.log`.

> C:\Yock\Projects\code\YE2\YE2\include\rendering\SDL2.hpp(82,18): warning C4003: not enough arguments for function-like macro invocation 'CreateWindowW'

You have defined a function in your project named `CreateWindowW`, but this name conflicts with a macro defined in the Windows system header file `windows.h`.

https://learn.microsoft.com/ja-jp/windows/win32/api/winuser/nf-winuser-createwindoww

spdlog is forced to use the system header `windows.h` to support Windows.

In C/C++, you should never define a symbol with the same name as the macro that the system header defines.
If you really do not want to change the function name, please do `#undef CreateWindowW` after including all third-party header files.

**Comment by yockey88** [comment]
I have no function in my project named CreateWindowW, as I said this error goes away when removing the spdlog include. The only function signature even remotely close is the member function 

```cpp
YE::rendering::SDL2::CreateWindow(SDL2_Config*) 
```

The project is public on my github under YE2 if you wish to see for yourself. This is why included "strange syntax errors" in the title, because the project builds successfully and runs when the only change made is commenting out the line

```cpp
#include "spdlog/spdlog.h"
```

I am slightly familiar with the Win32 API and unfortunately this was what I thought at first as well and opened the issue after double checking all my function names.

Last edit: further testing shows it is the windows header however. I will change the name , but this is really strange since they have two different names entirely even if by one letter. Have you ever seen two distinctly different names clash? Thanks for your help.

**Comment by tt4g** [comment]
Windows system functions are available with suffixes `A` (`char *` version) and `W` (`wchar_t *` version).
System macros are declared without suffixes to allow applications to switch the type of string used by the macro.

Example:

```c
HWND CreateWindowW(...);
HWND CreateWindowA(...);

#ifdef UNICODE
    #define CreateWindow CreateWindowW
#else
    #define CreateWindow CreateWindowA
#endif
```
