### ISSUE TITLE
"Log user defined objects" acc.to Wiki can't be compiled

### ISSUE THREAD

**Issue by matswebjorn** [gabime/spdlog#273]
I'm trying to test "Log user defined objects" acc.to https://github.com/gabime/spdlog/wiki/1.-QuickStart using code below (identical copy of sample code). I would deeply apprechiate some suggestions on what may be the problem

`#include "spdlog/spdlog.h"
class some_class {};
std::ostream& operator<<(std::ostream& os, const some_class& c)
{ 
    return os << "some_class"; 
}

int main()
{
    some_class c;
    auto console = spd::stdout_logger_mt("console");
    console->info("custom class with operator<<: {}..", c);
}
`
but it generates a ton of error messages like

`Building CXX object main.cpp.o
In file included from /xxx/spdlog/include/spdlog/fmt/fmt.h:21:0,
                 from /xxx/spdlog/include/spdlog/common.h:41,
                 from /xxx/spdlog/include/spdlog/spdlog.h:12,
                 from /xxx/main.cpp:1:
/xxx/spdlog/include/spdlog/fmt/bundled/format.h: In instantiation of ‘static void fmt::internal::MakeValue<Formatter>::format_custom_arg(void*, const void*, void*) [with T = TestClass; Formatter = fmt::BasicFormatter<char>]’:
/xxx/spdlog/include/spdlog/fmt/bundled/format.h:1490:23:   required from ‘fmt::internal::MakeValue<Formatter>::MakeValue(const T&, typename fmt::internal::EnableIf<fmt::internal::Not<fmt::internal::ConvertToInt<T>::value>::value, int>::type) [with T = TestClass; Formatter = fmt::BasicFormatter<char>; typename fmt::internal::EnableIf<fmt::internal::Not<fmt::internal::ConvertToInt<T>::value>::value, int>::type = int]’
/xxx/spdlog/include/spdlog/fmt/bundled/format.h:2465:38:   required from ‘static fmt::internal::Value fmt::internal::ArgArray<N, true>::make(const T&) [with Formatter = fmt::BasicFormatter<char>; T = TestClass; unsigned int N = 1u]’
/xxx/spdlog/include/spdlog/fmt/bundled/format.h:2898:5:   required from ‘void fmt::BasicWriter<Char>::write(fmt::BasicCStringRef<CharType>, const Args& ...) [with Args = {TestClass}; Char = char]’
/xxx/spdlog/include/spdlog/details/logger_impl.h:69:9:   required from ‘void spdlog::logger::log(spdlog::level::level_enum, const char*, const Args& ...) [with Args = {TestClass}]’
/xxx/spdlog/include/spdlog/details/logger_impl.h:146:5:   required from ‘void spdlog::logger::warn(const char*, const Args& ...) [with Args = {TestClass}]’
/xxx/main.cpp:32:36:   required from here
/xxx/spdlog/include/spdlog/fmt/bundled/format.h:1392:43: error: no matching function for call to ‘format(fmt::BasicFormatter<char>&, const Char*&, const TestClass&)’
                *static_cast<const T*>(arg));
`

**Comment by gabime** [comment]
You have to include ```<spdlog/fmt/ostr.h>``` for this to work. I updated the wiki

**Comment by matswebjorn** [comment]
The same problem exist on https://github.com/gabime/spdlog in the Usage Example for "// user defined types logging by implementing operator<<". And on that page name space "spd::" is used. Shouldn't it be "spdlog::" ?

**Comment by gabime** [comment]
Wiki fixed.
The example.cpp already contains this include (https://github.com/gabime/spdlog/blob/master/example/example.cpp#L133)
