### ISSUE TITLE
source_log may contain invalid attributes

### ISSUE THREAD

**Issue by lucadici** [gabime/spdlog#2738]
Preliminary:
- Version: 1.11.0
- Using void `log(source_loc loc, level::level_enum lvl, string_view_t msg) `
- Async logger

The struct `source_loc` attributes _file_ and _function_ may be no more valid when the library logs data asynchronously. 
Everything works if predefined macros are used (e.g.  `__FILENAME__` and `__FUNCTION__`) but sometimes macros are not available. A possible use case is reimplementing the Qt message handler, where _context_ remains valid only in the handler's scope.
https://doc.qt.io/qt-5/qtglobal.html#qInstallMessageHandler

This causes the logger to print weird characters. But in principle also an invalid memory location access may occur. I patched common.h this way:

```
    SPDLOG_CONSTEXPR source_loc(const char *filename_in, int line_in, const char *funcname_in)
        :line{line_in}
    {
        if(filename_in != 0){
            if(strlen(filename_in)> 0){
                strncpy(filename, filename_in, SIZE_BUF-1);
            }
        }

        if(funcname_in != 0){
            if(strlen(funcname_in)> 0){
                strncpy(funcname, funcname_in, SIZE_BUF-1);
            }
        }
    }
   ....
    char filename[SIZE_BUF]{"default-file-name"};
    int line{0};
    char funcname[SIZE_BUF]{"default-func-name"};

```

Copying buffers fixes the problem.

**Comment by gabime** [comment]
Seems like an invalid usage of spdlog, but it is hard to understand from your post. Please provide concrete example to reproduce.

**Comment by lucadici** [comment]
I'm not able to provide everything to compile from scratch, but I can point out the spdlog portions:

//logger initialization:
```
LogModule::LogModule() {
    char currentWd[512];
    if(!getWorkingDir(currentWd)){
        string err = "Failed hubFileGetWorkingDir\n";
        printf("%s", err.c_str());
        fflush(stdout);
        throw std::runtime_error(err);
    }
    _filePath 		= string(currentWd);
    _name           = "default";
    _strBuffer = (char*)malloc(STR_LEN);
    if(_strBuffer == NULL){
        string err = "Failed to alloc buffer\n";
        printf("%s", err.c_str());
        fflush(stdout);
        throw std::runtime_error(err);
    }
    if(!loggerSet){
        try{
            _consoleLogger = spdlog::stdout_logger_mt<spdlog::async_factory>(
                         _name+"-s");
        }catch(spdlog_ex & ex){
            printf("Failed to create console logger (rename it): %s", ex.what());
            fflush(stdout);
            return;
        }
        _consoleLogger->set_pattern("[%T] [%^%4!l%$] [%@] - %v");
        _consoleLogger->set_level((level::level_enum) SPDLOG_LEVEL_TRACE);
        loggerSet = true;
    }
}
```

//now the wrapper around the spdlog's log statement
```
void LogModule::loglineprintf(
        int level,
        const char *filename_in,
        int line_in,
        const char *funcname_in,
        const char *fmt,
        ...)
{
    char autoStrBuffer[STR_LEN]; //WHY? SEE NOTE (*)
    {
        __builtin_va_list arg;
        __builtin_va_start(arg, fmt);
        vsnprintf(autoStrBuffer, STR_LEN-1, fmt, arg);
        __builtin_va_end(arg);
    }
    try{
        {
            _consoleLogger->log(
                        spdlog::source_loc{filename_in, line_in, funcname_in},
                        (spdlog::level::level_enum)level,
                        autoStrBuffer);
            _consoleLogger->flush();
        }
    }catch(const std::exception &ex){
        loglineprintf(VL_ERR, filename_in, line_in, funcname_in, "Failed to log -> reason: %s", ex.what());
        return;
    }
}
```

//Now the user code and in particular the Qt message handler:
```
void qtMessageOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
{
    QByteArray localMsg = msg.toLocal8Bit();
    const char *file = context.file ? context.file : "";
    const char *function = context.function ? context.function : "";
    switch (type) {
    case QtDebugMsg:
        _qtLogger.loglineprintf(2,file, line, function, "%s", localMsg.constData());
...
}
```

The problem is the timing: 
t1)` qtMessageOutput` is called. _context_ provides _file_ and _function_ pointers
t2) `_qtLogger.loglineprintf(2,file, line, function, "%s", localMsg.constData());` is called. The method loglineprintf receives valid pointers.
t3) spd's log is called:  
```
_consoleLogger->log(
                        spdlog::source_loc{filename_in, line_in, funcname_in},
                        (spdlog::level::level_enum)level,
                        autoStrBuffer);
```

...some time passes

t4) `qtMessageOutput` completes, so `QMessageLogContext &context` is no more valid. It may have been destroyed also. The pointers passed to spdlog (  `_qtLogger.loglineprintf(2,file, **line**, **function**, "%s", localMsg.constData());`) are no more valid as well.

...some time passes...

t99) spdlog internal threads eventually send the message to console. At this point the contents of `source_loc `(_filename_ and _funcname_) may contain any value (at least different from those intendend in the qt message handler). Since the logger's pattern requires file and function, spdlog accesses those two pointers and print wrong file and function information. The message string (`autoStrBuffer`) is printed correctly since it is buffered in sdplog.

The problem is that spdlog->log does not buffer _filename_ and _funcname_ contents when `log `is called.

NOTE(*): I had to use va_list... because spdlog with printf-style formatting does not work if the message contains curly brackets "{}". Brackets are still interpreted as positional arguments (fmt-style instead of printf-style, that's maybe another issue).

I hope I described the issue better now.

**Comment by gabime** [comment]
> The pointers passed to spdlog (  _qtLogger.loglineprintf(2,file, **line**, **function**, "%s", localMsg.constData());) are no more valid as well.

Well, this is a clear invalid usage of spdlog. source_loc is just holder of the pointers passed to it, and if those pointers get invalidated, there is nothing spdlog can do about it. strcpy is not option since it would hurt performance.

**Comment by lucadici** [comment]
Okay, so let's assume I put the buffers outside the library (to move the performance penalty from the library to user code if this makes any sense). How much time should I wait before releasing the buffers? Can the library inform the user about a sync event for that line? If not then it means that I should stick with compile time log level macros (SPDLOG_INFO), but that's notfeasible if the library is hidden inside a wrapper (you would see the wrapper file and functions, not the actual user code source information)
