### ISSUE TITLE
how to flush file to disk as fast as possible

### ISSUE THREAD

**Issue by xiedeacc** [gabime/spdlog#2739]
my server use spdlog to write a lot string line to disk, about 40GB per hour, each line about 200KB, so write extremely high . so how to flush to disk as fast as possible, set spdlog::flush_every(std::chrono::seconds(1) ?

**Comment by tt4g** [comment]
`spdlog::flush_on(spdlog::level::trace)` is more better.

https://github.com/gabime/spdlog/wiki/7.-Flush-policy
