### ISSUE TITLE
backtrace with dist_sink

### ISSUE THREAD

**Issue by balaji99** [gabime/spdlog#2740]
I created a logger and a dist_sink under it. Both have log levels set to TRACE. I have a console sink as part of the dist_sink, and its log level is set to Error.
The backtrace feature was enabled, and some messages with debug level were logged. As expected, the messages were not logged immediately. But when logger->dump_backtrace() was called, no messages appeared in the console sink. I expected the messages (stored in the backtrace buffer) to reach the console sink.

How do I solve this issue? When backtrace is enabled, and logger->dump_backtrace() is called, it would be great if the backtrace buffer messages reach the sink regardless of its log level.

Note: If the console sink's level is set to debug, the log messages are logged immediately in spite of backtrace being enabled. And when logger->dump_backtrace() is called, the messages in the backtrace buffer are also sent to the sink.

**Comment by tt4g** [comment]
Duplicate #1579

The log level is never ignored by `dump_backtrace()`.
Please temporarily change the log level.

See also: #2287

**Comment by balaji99** [comment]
On a related note: is the backtrace functionality going away? 
Per https://github.com/gabime/spdlog/issues/1623#issuecomment-680282818, it will not be present in v2.x

**Comment by tt4g** [comment]
> On a related note: is the backtrace functionality going away?
> Per [#1623 (comment)](https://github.com/gabime/spdlog/issues/1623#issuecomment-680282818), it will not be present in v2.x

@gabime

**Comment by gabime** [comment]
It might be replaced with a special sink.
