### ISSUE TITLE
Automatically format user-defined types via fmt::streamed?

### ISSUE THREAD

**Issue by jdumas** [gabime/spdlog#2746]
Hi,

Since v9, fmt deprecated the implicit use of `operator <<` to format user-defined types, and support has been removed in fmt v10. `std::format` also does not support `operator <<`, and requires users to provide their own `fmt/std::formatter<>` specialization. However, until everyone catches up to the standard, the situation is we'll have a lot of libraries with custom types that have a perfectly valid `operator <<` but not `formatter<>` specialization.

One of such library is [Eigen](https://github.com/fmtlib/fmt/issues/3465) for example. It is unrealistic for me to add `fmt::streamed()` everywhere in my codebase whenever I want to log and print a Eigen type, nor can I add a `formatter<>` specialization for Eigen in my own library (it should be available upstream in Eigen).

So my question is, is there a way, in `spdlog`, that I could attach a custom formatter or create a derived logger type that would forward any argument via `fmt::streamed()` before passing it to `fmt::format()`? This would allow me to use spdlog as before, with a client-side solution to this lack for `operator <<` from `fmt`.

**Comment by gabime** [comment]
The logger calls fmt [here](https://github.com/gabime/spdlog/blob/d1eb68154f2a60c7d59e99d1504e6c6ac03fedb4/include/spdlog/logger.h#L374).

I guess you could customize spdlog source with a special ifdef until Eigen supports what you need, but it won’t be pretty(and with a considerable performance  cost i guess, since all params would be wrapped, even native ones).

I think better is just to wrap each Eigen param with streamed() when passing to the logger, even if this makes the code uglier.

**Comment by jdumas** [comment]
Thanks. Adding `fmt::streamed()` all over the place is not really an acceptable answer. I don't want to fork the spdlog source code either, but maybe I can try to write my own forwarding function that wraps the `args...` in a `fmt::streamed()` before passing it to the spdlog logger object... Either way it's a real headache and it's gonna take a me a while to find out a sensible solution.

**Comment by joanvallve** [comment]
If someone end up here with the same issue, here is my (simplified) solution so far, for implementing my Logger in case it helps:

```c++
class Logger
{
  public:
    Logger(const std::string& name);
    ~Logger();

    //  [...]

    template <typename... Args>
    void info(Args&&... args) const;
    
    //  [...]
   
  protected:
    const std::string log_name_;
    std::shared_ptr<spdlog::logger> console_;
};
template <typename... Args>
void Logger::info(Args&&... args) const
{
    console_->info(std::get<sizeof...(args) - 1>(repeated_brace), fmt::streamed(std::forward<Args>(args))...);
}
```
