### ISSUE TITLE
An error is reported about fmt compiled by vs2105 in the latest version of spdlog

### ISSUE THREAD

**Issue by Z-SmallRock** [gabime/spdlog#2747]
Why does vs2015 have an error about fmt. Is there any way to deal with it? Without changing the vs2015 version
![0c7a53ca9fd2bc8c10c83ce196f2b35](https://github.com/gabime/spdlog/assets/43021784/beff174a-415b-4b21-ab16-02b76fb87782)

**Comment by tt4g** [comment]
fmt 10 not supported yet.
And since you have not provided the source code for the cause of the error, we cannot help you.

**Comment by Z-SmallRock** [comment]
Which version of spdlog does vs2015 need to use to compile smoothly? I think this should be a common mistake. Because I use visual studio 2015 update3 with no problem！ The current version information of visualstudio is as follows
![26b087846bdd912761f9143e9936fc8](https://github.com/gabime/spdlog/assets/43021784/42753400-3d7a-4f86-9171-7f7468646ab9)

**Comment by tt4g** [comment]
Visual Studio 2015 supports C++11 so spdlog should be available.
Please provide the source code that is causing the error.

**Comment by Z-SmallRock** [comment]
The main problem is the dependency of third-party libraries in fmt
This is the problem when I use external fmt or the fmt that comes with the source code.
![image](https://github.com/gabime/spdlog/assets/43021784/777401c5-8041-44a0-b3f2-79309af60563)

**Comment by tt4g** [comment]
As I have written many times, please provide the source code that is causing the error indicated by the error code.
As far as the error trace is concerned, you are using spdlog incorrectly.

**Comment by Z-SmallRock** [comment]
thanks !   
First of all, high probability positioning is a visual studo version problem, and then I give specific steps:
1. cmake Check static lib
2. clock in visual studo 2015 compilation error was in include/fmt/format.h
It's that simple to compile staticlib, nothing else has changed
(There is no problem with compiling directly with visual studio 2015 update 3)

**Comment by tt4g** [comment]
The header file is reported in error because the C++ template specializations are failing.
Neither the Visual Studio IDE nor CMake nor the static library seem to be the cause of the error.

From the first image I can determine that you are using googletest in your project and that you are most likely using spdlog incorrectly.
No one can help you unless you provide the source code.
