### ISSUE TITLE
in pursuing the fastest log?

### ISSUE THREAD

**Issue by bethebest0622** [gabime/spdlog#2749]
I have a project which is very sensitive about speed. and i found the IO cost me a lot of time.

my IO focus on:
```
1. printf
2. std::fstream::write
```

I think the optimization part is to avoid entering linux kernel (`printf `and `fstream write` call kernel write), so the best method i think is, the main process only send printf or fstream write request, and another thread/process to handle the request.

can spdlog async mode can do this? it should open another thread to do that which need more CPU to speed up?

or is there anything i misunderstand?

if yes, considering the higheset performance, shall i use async logger only in anyplace? did it rely on my environment(how many processor)?

Thanks very much

**Comment by gabime** [comment]
see #1391
