### ISSUE TITLE
can async_logger use a thread pool instead of a single thread per logger?

### ISSUE THREAD

**Issue by facontidavide** [gabime/spdlog#275]
Hi,

apparently each async_logger has its own thread.
Since the queue used is already a lock free multi producer / multi consumer queue, it should be relatively easy to have a SINGLE queue shared by all of the async_loggers.
One or multiple dedicated worker threads can consume the elements of the queue.

Is there any technical reason that makes this hard to implement?

**Comment by gabime** [comment]
The only problem i can think of is that flush() would be way more complicated. In current version it waits until the queue is empty fefore it reurns to make sure thall the messages in it got processed.

**Comment by facontidavide** [comment]
Good point.
In that case it might sense to have a a single queue for each logger and the threads in the pool consuming those queues using something similar to a simple round robin.
I will see if I can implement a simple solution.

**Comment by gabime** [comment]
@facontidavide Please take a look at v1.x branch. There is a shared thread pool for all loggers

**Comment by vantheo** [comment]
I have a related question, but post to a less related issue.

https://github.com/gabime/spdlog/issues/2202#issuecomment-2340059291
