### ISSUE TITLE
Use signal/slot in qt_sink

### ISSUE THREAD

**Issue by Ulmo-F** [gabime/spdlog#2752]
The qt_sink class is not notified when the owned qt_object_ is destroyed.
Calling the logger/sink afterward leads to a segmentation fault.

Qt's signal/slot mechanism would detect object deletion, leading to a useless sink, but this looks like "Qt standard development pattern".
And one could argue that wasted resources are still better than a core dump.

**Comment by gabime** [comment]
So what is the solution? PR is welcome

**Comment by Ulmo-F** [comment]
Well, using signal/slot means using a Qt object.
But Qt objects work with generated .cpp files, this can't be handled by a header-only library.

Inlining the generated file will work, but only until Qt changes its internal wiring.
I wouldn't push such a solution.

So after a second look, your implementation which calls directly the target method is smart, as it cuts you from any Qt depedency.

**Comment by Ulmo-F** [comment]
But I would add some warning to the qt_sink documentation.
I propose:
```
qt_sink

qt_sink could output log messages from QTextBrowser,QTextEdit...

Note that the qt_sink won't be notified if the target object is destroyed.
If the widget's lifetime can be shorter than the logger's one, you should provide some permanent object which will be connected to the widget via standard signal/slot.

Example:
```

**Comment by gabime** [comment]
Ok. This warning should probably added directly to the sink header file(qt_sink.h). PR is welcome.

**Comment by Ulmo-F** [comment]
Proposal :
https://github.com/gabime/spdlog/pull/2753
