### ISSUE TITLE
Invalid format exception while creating "daily_file_format_sink_mt"

### ISSUE THREAD

**Issue by kkEngine** [gabime/spdlog#2756]
Hello. After update to the last version (1.11.0) i get runtime error when i want to create "daily_file_format_sink_mt".

```c++
auto file_sink = std::make_shared<spdlog::sinks::daily_file_format_sink_mt>("myApp_%Y-%m-%d_.txt", 0, 0, false, 0)
```

This code raises an "invalid format" exception.
Previous version (i don't remember which one) works without errors.
Thank you.

**Comment by kkEngine** [comment]
working with file names:
```
%Y-%m-%d.txt
%Y-%m-%d_myApp_.txt
%Y_myApp_-%m-%d.txt
```

Isn't working with:
```
logs/%Y-%m-%d_myApp_.txt
_%Y-%m-%d.txt
```

**Comment by gabime** [comment]
This was fixed in #2736. Try using latest commit.

**Comment by kkEngine** [comment]
hm, i am using vcpkg and the last release was 1.11.0 with this issue.
Is any plans to make new release?

**Comment by gabime** [comment]
No, not yet.
