### ISSUE TITLE
How to use spdlog from CMake?

### ISSUE THREAD

**Issue by worgar** [gabime/spdlog#2758]
Hi. I'm desperately trying to understand how cmake works. I inherited a project that uses cmake, and needs spdlog, but I simply cannot make cmake be able to generate the makefiles, because I cannot produce a working Findspdlog.cmake for find_package to work. 

Is there a way to use spdlog properly with FetchContent, or am I forced to install it?

**Comment by tt4g** [comment]
`find_package()` basically only finds installed libraries. It may not fit your use case.

`FetchContent()` is to import spdlog as part of your project.
When you build your project, spdlog will be built with it.

Example:

```cmake
include(FetchContent)
FetchContent_Declare(
      spdlog
      GIT_REPOSITORY https://github.com/gabime/spdlog.git
      GIT_TAG v1.11.0
)
# Download spdlog
FetchContent_MakeAvailable(spdlog)

# Import spdlog.
add_subdirectory(${spdlog_SOURCE_DIR})

target_link_libraries(<YOUR_TARGET> PUBLIC spdlog::spdlog)
```

See also: https://cmake.org/cmake/help/v3.27/module/FetchContent.html

**Comment by Richardk2n** [comment]
Is the `add_subdirectory` necessary? I never used that when using `FetchContent`.
Also, something I stumbled across when using this, that should probably be noted somewhere prominent, is, that spdlog is header only by default.
This means that if you use above example, but include a library in between that uses spdlog (see below), you will get interesting paranormal activity, because l.cpp is build with the header only version of spdlog, while main.cpp is linked as expected.
```cmake
include(FetchContent)
FetchContent_Declare(
  spdlog
  GIT_REPOSITORY "https://github.com/gabime/spdlog.git"
  GIT_TAG v1.12.0
)
FetchContent_MakeAvailable(spdlog)
include_directories("${CMAKE_CURRENT_BINARY_DIR}/_deps/spdlog-src/include")

ADD_EXECUTABLE(myExe src/main.hpp src/main.cpp)
add_library(log src/l.hpp src/l.cpp)

target_link_libraries(myExe PUBLIC log spdlog::spdlog)
```
To avoid that one either has to explicitly link spdlog in every lib used or include a line
```cmake
add_compile_options(-DSPDLOG_COMPILED_LIB)
```

**Comment by gabime** [comment]
> Is the add_subdirectory necessary?

Right, I don’t think the `add_subdirectory` is necessary.

> that spdlog is header only by default

Only if used directly without using  `target_link_libraries` (we plan to make it compiled by default in ver 2.x for all cases).

> To avoid that one either has to explicitly link spdlog in every lib used or include a line

Why not just `target_link_libraries(log PUBLIC log spdlog::spdlog)` ? seems the right to do anyway.

**Comment by Richardk2n** [comment]
Having a `target_link_libraries` for every lib (this is what I meant by “explicitly link spdlog in every lib”) would probably be the correct thing to do. However, I mostly use libs to group my code logically (whether this is bad practice I do not know) and thus have a few of them (thus adding the compile option globally is easier for me than to remember to add a `target_kink_libraries` for each one. I think this does not hurt anything?). In the end I just link them all together with a single `target_link_libraries`, which works fine with all other dependencies. Therefore, I kind of expected it to work with spdlog as well. It took me quite a while to figure out why it does not. I could see others making the same mistake, and thus I think a note is warranted.
