### ISSUE TITLE
what project used spdlog as their log module? prefer well-know project

### ISSUE THREAD

**Issue by ziyangfu** [gabime/spdlog#2760]
as we all known, spdlog is a fantastic log lib. I want to know what project used it, therefore, I can learning how to use spdlog and spdlog wrapper. 
a standard, industrial or commercial source code can let me learn more.
thanks.

**Comment by tt4g** [comment]
You can find it by searching for "spdlog" in the GitHub code search.
You will see it used in well-known projects such as Visual Studio Code (https://github.com/microsoft/vscode).
