### ISSUE TITLE
Compilation taking more than 1 minute

### ISSUE THREAD

**Issue by Hakai-Shin** [gabime/spdlog#2762]
Compiling example code using precompiled spdlog library is taking more than 1 minute. how can i reduce it

**Comment by gabime** [comment]
compiling spdlog itself or the code that include it?

**Comment by Hakai-Shin** [comment]
Hello @gabime,

I have build spdlog source code and created compiled headers and shared library. I have then included the compiled headers within an example code i have written. so during compiling the code that include spdlog, it is taking lot of time.

**Comment by Hakai-Shin** [comment]
can you explain more about this,

https://github.com/gabime/spdlog/issues/1470#issuecomment-828524830

**Comment by gabime** [comment]
The SPDLOG_COMPILED_LIB must be defined before the first include of spdlog. Otherwise it will use the header only version which slows compilation.

**Comment by Hakai-Shin** [comment]
Hi @gabime , got it. For compiling I am using g++ and while going through previous issue i found to include -DSPDLOG_COMPILED_LIB and that helped it. Thank you for your support. Also for others reference I am including example below.

`g++ -DSPDLOG_COMPILED_LIB example.cpp -o example`

where example.cpp is the code using spdlog library.
now the compilation is completed in 1 second.
