### ISSUE TITLE
any plan to upgrade the fmt 10?

### ISSUE THREAD

**Issue by aengusjiang** [gabime/spdlog#2763]
the libfmt have do a lot update, any plan to update it?

as we know, fmt v9, it is deprecated the enum formatter by default, but fmt v10 remove the limit.

https://github.com/fmtlib/fmt/releases/tag/10.0.0
Removed deprecated implicit conversions for enums and conversions to primitive types for compatibility with std::format and to prevent potential ODR violations. Use format_as instead.

**Comment by gabime** [comment]
You can use SPDLOG_FMT_EXTERNAL to use external version fmt. Not sure when we upgrade the bundled version though.
