### ISSUE TITLE
[Question] Hot to customize log level names using vcpkg?

### ISSUE THREAD

**Issue by SirPustekuchen** [gabime/spdlog#2766]
Hello,

I want to use spdlog installed by vcpkg and using CMake. Is there any way to customize the log level names?

If I compile spdlog myself, I can set these log level names in tweakme.h with #define SPDLOG_LEVEL_NAMES. This works as well. But I am looking for a way to do this when using vcpkg. Does anyone know a solution without creating custom branches of spdlog?

Thanks...

**Comment by tt4g** [comment]
I think you should ask your question in the [vcpkg repository](https://github.com/microsoft/vcpkg).

**Comment by SirPustekuchen** [comment]
Okay... https://github.com/microsoft/vcpkg/discussions/32061

Maybe in a future version of spdlog it would be possible to call a function at runtime? E.g. spdlog::set_custom_log_level_names(...)

**Comment by tt4g** [comment]
No plans in version 1.x.
See #834, #1794
