### ISSUE TITLE
Incorrect order of log messages Single thread

### ISSUE THREAD

**Issue by sk-surya** [gabime/spdlog#2768]
I'm trying to use multiple loggers within my application that need to write to the same file.
To acheive this, I have created a global function:

        typedef std::shared_ptr<spdlog::logger> TLogger;
        static auto fileSink = std::make_shared<spdlog::sinks::basic_file_sink_st>(logger::logFilenameWithDir, true);

        static TLogger CreateFileLogger(const std::string& loggerName)
        {	
        TLogger x(new spdlog::logger(loggerName, { fileSink }));
        spdlog::register_logger(x);
        return x;
        }

In one of my classes (in a header file), I have declared the logger as a static variable and defining it inside cpp file.

        logger::TLogger CCVRPInstance::m_logger(logger::CreateFileLogger("VehicleRoutingSolver.ProblemLoader"));

My main function looks like this:

        int main(int argc, char* argv[])
        {
            auto logger2 = logger::CreateFileLogger("basic_logger2");
            auto logger = logger::CreateFileLogger("basic_logger");
        
            logger->info("Welcome to spdlog!");
            logger2->info("Welcome to spdlog222!");

            CCVRPInstance problemLoader;
            
            problemLoader.LoadCVRP_TSPLIB("data\\ftv1994\\A034-02f.dat", 0);    // this logs to VehicleRoutingSolver.ProblemLoader logger
        }

My log files shows my class logger's output before displaying the logger2 and logger in main:

        [2023-06-17 19:08:23.513] [VehicleRoutingSolver.ProblemLoader] [info] Loading CVRP_TSPLIB problem from file: data\ftv1994\A034-02f.dat
        [2023-06-17 19:08:23.506] [basic_logger] [info] Welcome to spdlog!
        [2023-06-17 19:08:23.506] [basic_logger2] [info] Welcome to spdlog222!

How do I get it to display in expected order? 
PS - also, currently the messages are flushed when my program terminates. How do I make it output as soon as possible?

**Comment by sk-surya** [comment]
Console sink works correctly.
The problem appears in file sink.

**Comment by tt4g** [comment]
There is a mistake in the source code and the cause is unknown.
The variable `x` of the `TLogger` object cannot be passed to `spdlog::register_logger()`.

**Comment by sk-surya** [comment]
The behavior is the same without using 'spdlog::register_logger' too. 

Sorry, did you mean mistake in spdlog's source code or mine?

**Comment by sk-surya** [comment]
The behavior is the same without using 'spdlog::register_logger' too. 

Sorry, did you mean mistake in spdlog's source code or mine?

**Comment by tt4g** [comment]
I can't be sure, since only a partial source code is provided, but your source code doesn't look like it will compile successfully.

For example, I don't know what `logger::logFilenameWithDir` is.
And since the `static` keyword does not create a singleton object when used outside of a function body, it is possible that multiple `file_sink`s are created.

**Comment by sk-surya** [comment]
My code compiles successfully.

Here's a minimally reproduceable example:
https://gist.github.com/sk-surya/6031eecdc9e59c4fa927ddbc2b1b8e55

**Comment by sk-surya** [comment]
UPDATE - Tried moving the sink creation inside a function body (inside CreateFileLogger function) and the messages are in correct order now.

It indeed had to do with global static variable. Thanks!
