### ISSUE TITLE
Possibility to delete Backtrace Start and Backtrace End

### ISSUE THREAD

**Issue by markusmu0** [gabime/spdlog#2774]
Hi,
is there a possibility to delete Backtrace Start and End message? 

If not: Is there another possibility to buffer/store some debug messages and only dump them, when a condition is true?

**Comment by tt4g** [comment]
Duplicate #1623

Use ringbuffer_sink instead.

**Comment by markusmu0** [comment]
> Duplicate #1623
> 
> Use ringbuffer_sink instead.

I Don't think that this is a duplicate:
I am searching for a possibility
1. to dump the output on a condition and not only if the buffer is full
2. to throw away the logs if the condition is false
3. to have a complete logger with multiple sinks with this behavior 

Everything of this can be done with backtrace so the only problem is the start and end message

**Comment by tt4g** [comment]
If compatibility is not broken, please submit PR.

**Comment by markusmu0** [comment]
PR was rejected by gabime. Thus, the problem still exists. Is there another solution for this?

**Comment by tt4g** [comment]
spdlog does not provide.

Both backtracer and ringbuffer_sink use `spdlog::details::circular_q`, so create a custom sink that buffers messages using `spdlog::details::circular_q`.

https://github.com/gabime/spdlog/blob/326f8870c2746aea9b295e9b366174116f266b6e/include/spdlog/details/backtracer.h#L22

https://github.com/gabime/spdlog/blob/326f8870c2746aea9b295e9b366174116f266b6e/include/spdlog/sinks/ringbuffer_sink.h#L66

Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink
