### ISSUE TITLE
Try to use template to reconstruct the Thread pool constructor to improve performance

### ISSUE THREAD

**Issue by wjr-z** [gabime/spdlog#2783]
[https://github.com/gabime/spdlog/blob/da1e671d4285fce4b2b1603be90afc652c4f4b65/include/spdlog/details/thread_pool-inl.h#L17]()
Do not use std::function here, even if an empty lambda is passed in, it will bring unnecessary overhead.
[https://godbolt.org/z/arqjexEne]()

**Comment by gabime** [comment]
It called once so it doesn't really matter.
