### ISSUE TITLE
spdlog 1.11.0 fails to build with libfmt 10.0.0

### ISSUE THREAD

**Issue by setoye** [gabime/spdlog#2788]
in common.h line 168:
```
// clang doesn't like SFINAE disabled constructor in std::is_convertible<> so have to repeat the condition from basic_format_string here,
// in addition, fmt::basic_runtime<Char> is only convertible to basic_format_string<Char> but not basic_string_view<Char>
template<class T, class Char = char>
struct is_convertible_to_basic_format_string
    : std::integral_constant<bool,
          std::is_convertible<T, fmt::basic_string_view<Char>>::value || std::is_same<remove_cvref_t<T>, fmt::basic_runtime<Char>>::value>
{};
```
looks like `fmt::basic_runtime` has been renamed into `fmt::runtime_format_string`.

**Comment by tt4g** [comment]
spdlog v1.11.0 doesn't support fmt 10.
`v1.x` branch supported by 0ca574ae168820da0268b3ec7607ca7b33024d05, wait for next release or use `v1.x` branch.

- https://github.com/gabime/spdlog/issues/2614#issuecomment-1396348189
- https://github.com/gabime/spdlog/issues/2767#issuecomment-1595803052
