### ISSUE TITLE
The error message you encountered with ”create_async_nb“

### ISSUE THREAD

**Issue by lobmoo** [gabime/spdlog#2789]
this is   simple  demo
`#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include "spdlog/async.h"

int main()
{
    // 创建异步日志记录器
    auto logger = spdlog::create_async_nb<spdlog::sinks::stdout_color_sink_mt>("async_logger");

    // 注册日志记录器
    spdlog::register_logger(logger);

    // 使用已注册的日志记录器进行日志记录
    SPDLOG_LOGGER_INFO(logger, "Hello, spdlog!");

    // 关闭并销毁日志记录器
    spdlog::drop_all();
    
    return 0;
}`

ERROR：
terminate called after throwing an instance of 'spdlog::spdlog_ex'
 what():  logger with name 'async_logger' already exists

**Comment by tt4g** [comment]
The error message says it all.
It is because you have created multiple loggers named `"async_logger"`.

> ERROR：
> terminate called after throwing an instance of 'spdlog::spdlog_ex'
> what(): logger with name 'async_logger' already exists
