### ISSUE TITLE
Only provide format without LOG ERROR

### ISSUE THREAD

**Issue by 4kangjc** [gabime/spdlog#2791]
Hi, When I only provide format and no arguments，it will not tell me that the arguments cannot be found.
https://godbolt.org/z/bh6xK6x65
```cpp
#include <spdlog/spdlog.h>

int main(){
    auto log = spdlog::default_logger();
    log->info("Hello {}");
    log->info("Hello {} {}", "World");
}
```
output:
```bash
[*** LOG ERROR #0001 ***] [2023-06-30 16:50:36] [] {argument not found}
[2023-06-30 16:50:36.669] [info] Hello {}
```
I read the code and found that when only format is provided, it will enter this function instead of calling fmtlib, so the exception of fmtlib will not be caught. Is this the expected behavior?
https://github.com/gabime/spdlog/blob/826d8ba4b2c0cca3192f01d396fe5cdc3b1ee047/include/spdlog/logger.h#L125-L136

**Comment by gabime** [comment]
> I read the code and found that when only format is provided, it will enter this function instead of calling fmtlib, so the exception of fmtlib will not be caught. Is this the expected behavior?

Right, this is optimization to avoid calling fmt if no args passed.

**Comment by 4kangjc** [comment]
> 

Ok. I see.
