### ISSUE TITLE
Support head title for rotating_file_sink

### ISSUE THREAD

**Issue by raidenluikang** [gabime/spdlog#2792]
It would be nice, if each rotating file head writes some predefined title.
For example, title may be  git branch and commit:  ************git branch=feature/test_functionality .... commit=93434dfd *********"

Could you add that functionality:  Set a title for rotating_file_sink ?

**Comment by raidenluikang** [comment]
I) In spdlog/sinks/sinks.h
    Add `virtual void set_title(const string_view_t title) {}` to `sink` class
    
    
II) In spdlog/sinks/rotating_file_sink.h

Add   `memory_buf_t title_;`  data member  to  `rotating_file_sink` class .

Add `void set_title(const string_view_t title) override;`  method.

III) In spdlog/sinks/rotating_file_sink-inl.h 

Added this method:

```
template<typename Mutex>
SPDLOG_INLINE void rotating_file_sink<Mutex>::set_title(const string_view_t title)
{
    memory_buf_t buffer;
    details::fmt_helper::append_string_view(title, buffer);

    std::lock_guard<Mutex> lock(this->mutex_);
    title_ = std::move(buffer);
}
```
And change sink_it_ method as :

```
template<typename Mutex>
SPDLOG_INLINE void rotating_file_sink<Mutex>::sink_it_(const details::log_msg &msg)
{
    memory_buf_t formatted;
    base_sink<Mutex>::formatter_->format(msg, formatted);
    current_size_ += formatted.size();
    if (current_size_ > max_size_)
    {
        rotate_();
        current_size_ = formatted.size() + title_.size(); //1. Change: --> add title_.size()
        file_helper_.write(title_);     //2. Change: log title first right after rotating
    }
    file_helper_.write(formatted);
}

```

**Comment by tt4g** [comment]
You can already achieve your goal without adding `set_title()`.
Just pass `spdlog::file_event_handlers ` to the rotating_file_sink constructor. When the file is opened, the `spdlog::file_event_handlers::after_open(const filename_t&, std::FILE*)` callback will be called and you can write the title.

https://github.com/gabime/spdlog/blob/5ece88e5a8517fff5f6552d0e13057f38138d95a/include/spdlog/common.h#L330-L343

https://github.com/gabime/spdlog/blob/5ece88e5a8517fff5f6552d0e13057f38138d95a/include/spdlog/sinks/rotating_file_sink-inl.h#L26-L32

https://github.com/gabime/spdlog/blob/5ece88e5a8517fff5f6552d0e13057f38138d95a/include/spdlog/details/file_helper.h#L20

https://github.com/gabime/spdlog/blob/5ece88e5a8517fff5f6552d0e13057f38138d95a/include/spdlog/details/file_helper-inl.h#L61-L68

**Comment by raidenluikang** [comment]
Ouh, thanks.

I'm using spdlog 1.8.2 and there no that constructor rotating_file_sink which accept file_event_handlers. 

I'll upgrade spdlog. Thanks.
