### ISSUE TITLE
Sigfault (crash) on armeabi-v7a Android  (32 bit Android).

### ISSUE THREAD

**Issue by raidenluikang** [gabime/spdlog#2793]
armeabi-v7a Android sometimes crashed. And stacktrace shows that, it crashed in [source line](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/fmt/bundled/core.h#L2031). 

It happened  2 times, last month. First case logging  LOG_DEBUG( "{:019}", int64_t{3242} )  was crashed, after remove that logging, crash not happened. Second time,  LOG_DEBUG("some_my_class[{}]::class_method()", std::string{name_of_class});   was crashed. Both case stacktrace indicated exactly that core.h:2031 line.

There LOG_DEBUG()  is shorten of  spdlog::get("my_logger")->debug()  call.

It actually spdlog issue or I need open an issue in fmt lib ?

I'm use spdlog 1.8.2 actually, but I see that function which crashed not changed since.

**Comment by raidenluikang** [comment]
I open issue in fmt lib: https://github.com/fmtlib/fmt/issues/3518

**Comment by gabime** [comment]
Closing. Possibly a fmt/arm32 issue.
