### ISSUE TITLE
Auto divide one log into multiple lines

### ISSUE THREAD

**Issue by Doubidoubi** [gabime/spdlog#2794]
The default Spdlog will auto wrapped lines when length of log is longer than 80.
My code is 
`int main() {
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
}`
The output is 
[2023-07-02 18:13:55.788] [critical] Support for int: 42;  hex: 2a;  oct: 52; bi
n: 101010
But if i sleep 1s before spdlog::critical, the log is output in a single line.
`int main() {
    std::this_thread::sleep_for(std::chrono::seconds(1));
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
}`
The output is 
[2023-07-02 18:16:02.807] [critical] Support for int: 42;  hex: 2a;  oct: 52; bin: 101010

Environment:
I use v1.11.0 Header only version on win10

**Comment by tt4g** [comment]
spdlog has no such feature. It is thought that someone is executing an operation to flush `STDOUT`.
