### ISSUE TITLE
add a way to buffer log and output or delete it lateron

### ISSUE THREAD

**Issue by markusmu0** [gabime/spdlog#2795]
Please add a way to pause the output of all sinks of a logger and store the logs in a buffer instead. Later you should be able to output or delete the logs in the buffer.   
In the following I will try to explain why I think this is important:  
Differential equations play an important role in the natural sciences [[1](https://en.wikipedia.org/wiki/Differential_equation), [2](https://en.wikipedia.org/wiki/List_of_named_differential_equations#:~:text=Differential%20equations%20play%20a%20prominent,%2C%20medicine%2C%20economics%2C%20etc.)]. In most cases they can only be solved numerically. Adaptive stepsize methods are often used as an algorithm to solve differential equations [[3](https://en.wikipedia.org/wiki/Adaptive_step_size)]. In these methods, a function is called, the return value is evaluated and probably discarded, and the function is called again with a different set of parameters until the return value is within an error tolerance. Logs generated during the discarded function call do not contribute to the result of the simulation and therefore should not appear in the logs, in my opinion. In my current use case, the logger logs some errors (failed rootfinding) that are not important if the values are discarded.  
I hope this motivates you to implement such a feature.

**Comment by gabime** [comment]
You have 2 options already. The [ring_buffer_sink](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/ringbuffer_sink.h) or the `spdlog::enable_backtrace(..)` api

**Comment by markusmu0** [comment]
Could you please explain to me how the ring_buffer_sink for a whole logger works? How do I delete the buffer? How to force that it is applied?
enable_backtrace does exactly what I want except of the Backtrace start/end message

**Comment by gabime** [comment]
see #2118 and https://github.com/gabime/spdlog/wiki/4.-Sinks

**Comment by markusmu0** [comment]
Doesn't work for me but I don't think we'll get on the same page.
