### ISSUE TITLE
有个问题求助，希望热心的你能够帮助我

### ISSUE THREAD

**Issue by lobmoo** [gabime/spdlog#2797]
我想在我的代码里使用多个异步日志记录器，然后我想拿到他们的日志缓冲区指针，或者把这些日志输出写入到一个pipe或者fd都可以，我查了好多资料，没有能做到的

**Comment by tt4g** [comment]
> 我想在我的代码里使用多个异步日志记录器，然后我想拿到他们的日志缓冲区指针，或者把这些日志输出写入到一个pipe或者fd都可以，我查了好多资料，没有能做到的

Translate: I want to use multiple asynchronous loggers in my code, then I want to get their log buffer pointers, or write these log outputs to a pipe or fd can be, I have checked a lot of information, nothing can be done

**Comment by tt4g** [comment]
Please be more specific about what you want to tell us.
What do you expect a log buffer to look like?

Is this different from ringbuffer_sink (https://github.com/gabime/spdlog/blob/v1.11.0/include/spdlog/sinks/ringbuffer_sink.h) or backtrace (https://github.com/gabime/spdlog/blob/v1.11.0/README.md#backtrace-support). 

If you want to pipe log messages, make your own sink.
See: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by lobmoo** [comment]
我有一个c语言的日志存储器，我不想用spdlog的存储，我想创建多个异步日志记录器，然后把他们的输出都写到一个缓冲区或者命名管道，通过这个方式传给我的存储器，进行管理

**Comment by 1162431386** [comment]
`std::shared_ptr<spdlog::logger> sys_asynclogger_get(const char* logName)
{
    static std::unordered_map<std::string, std::shared_ptr<spdlog::logger>> loggers;
    static pthread_mutex_t loggersMutex = PTHREAD_MUTEX_INITIALIZER;

    pthread_mutex_lock(&loggersMutex);
    auto it = loggers.find(logName);
    if (it != loggers.end())
    {
        pthread_mutex_unlock(&loggersMutex);
        return it->second;
    }
    std::shared_ptr<spdlog::logger> logger; 
    try
    {
        logger = spdlog::create_async_nb<spdlog::sinks::stdout_color_sink_mt>(logName);
        logger->set_level(spdlog::level::info);
        logger->flush_on(spdlog::level::err);
        logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%n] [thread %t] [%s:%#] %v");
        spdlog::flush_every(std::chrono::seconds(3));
    }
    catch (const spdlog::spdlog_ex& ex)
    {
        ERR("Failed to create logger: %s\n",ex.what());
        pthread_mutex_unlock(&loggersMutex);
        return nullptr;
    }

    loggers[logName] = logger;
    pthread_mutex_unlock(&loggersMutex);
    return logger;
}`

**Comment by 1162431386** [comment]
`std::shared_ptr<spdlog::logger> sys_asynclogger_get(const char* logName)
{
    static std::unordered_map<std::string, std::shared_ptr<spdlog::logger>> loggers;
    static pthread_mutex_t loggersMutex = PTHREAD_MUTEX_INITIALIZER;

    pthread_mutex_lock(&loggersMutex);
    auto it = loggers.find(logName);
    if (it != loggers.end())
    {
        pthread_mutex_unlock(&loggersMutex);
        return it->second;
    }
    std::shared_ptr<spdlog::logger> logger; 
    try
    {
        logger = spdlog::create_async_nb<spdlog::sinks::stdout_color_sink_mt>(logName);
        logger->set_level(spdlog::level::info);
        logger->flush_on(spdlog::level::err);
        logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%n] [thread %t] [%s:%#] %v");
        spdlog::flush_every(std::chrono::seconds(3));
    }
    catch (const spdlog::spdlog_ex& ex)
    {
        ERR("Failed to create logger: %s\n",ex.what());
        pthread_mutex_unlock(&loggersMutex);
        return nullptr;
    }

    loggers[logName] = logger;
    pthread_mutex_unlock(&loggersMutex);
    return logger;
}`*
/

**Comment by lobmoo** [comment]
我写了一个方法，可以为我的每个模块单独创建日志记录器，但是我没办法拿到他们的日志缓冲区

**Comment by lobmoo** [comment]
`std::shared_ptr<spdlog::logger> sys_asynclogger_get(const char* logName)
{
    static std::unordered_map<std::string, std::shared_ptr<spdlog::logger>> loggers;
    static pthread_mutex_t loggersMutex = PTHREAD_MUTEX_INITIALIZER;

    pthread_mutex_lock(&loggersMutex);
    auto it = loggers.find(logName);
    if (it != loggers.end())
    {
        pthread_mutex_unlock(&loggersMutex);
        return it->second;
    }
    std::shared_ptr<spdlog::logger> logger; 
    try
    {
        logger = spdlog::create_async_nb<spdlog::sinks::stdout_color_sink_mt>(logName);
        logger->set_level(spdlog::level::info);
        logger->flush_on(spdlog::level::err);
        logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%n] [thread %t] [%s:%#] %v");
        spdlog::flush_every(std::chrono::seconds(3));
    }
    catch (const spdlog::spdlog_ex& ex)
    {
        ERR("Failed to create logger: %s\n",ex.what());
        pthread_mutex_unlock(&loggersMutex);
        return nullptr;
    }

    loggers[logName] = logger;
    pthread_mutex_unlock(&loggersMutex);
    return logger;
}`

**Comment by gabime** [comment]
@1162431386 This is unacceptable to write in chinese and expect us to translate. Please reopen in English.
