### ISSUE TITLE
I possess a log repository in the C language, and I prefer not to rely on spdlog for storage. Instead, I aspire to establish multiple asynchronous loggers and subsequently direct their outputs to a buffer or named pipe. This shall allow me to transmit the logs to my repository for management.

### ISSUE THREAD

**Issue by lobmoo** [gabime/spdlog#2798]
I possess a log repository in the C language, and I prefer not to rely on spdlog for storage. Instead, I aspire to establish multiple asynchronous loggers and subsequently direct their outputs to a buffer or named pipe. This shall allow me to transmit the logs to my repository for management.
`/**
 * @brief 创建一个异步日志记录器
 * @param  logName      记录器名字
 * @return std::shared_ptr<spdlog::logger> 
 * @version 1.0
 */
std::shared_ptr<spdlog::logger> sys_asynclogger_get(const char* logName)
{
    static std::unordered_map<std::string, std::shared_ptr<spdlog::logger>> loggers;
    static pthread_mutex_t loggersMutex = PTHREAD_MUTEX_INITIALIZER;

    pthread_mutex_lock(&loggersMutex);
    auto it = loggers.find(logName);
    if (it != loggers.end())
    {
        pthread_mutex_unlock(&loggersMutex);
        return it->second;
    }
    std::shared_ptr<spdlog::logger> logger; 
    try
    {
       
        logger = spdlog::create_async_nb<spdlog::sinks::stdout_color_sink_mt>(logName);
        logger->set_level(spdlog::level::info);
        logger->flush_on(spdlog::level::err);
        logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%n] [thread %t] [%s:%#] %v");
        spdlog::flush_every(std::chrono::seconds(3));
    }
    catch (const spdlog::spdlog_ex& ex)
    {
        ERR("Failed to create logger: %s\n",ex.what());
        pthread_mutex_unlock(&loggersMutex);
        return nullptr;
    }

    loggers[logName] = logger;
    pthread_mutex_unlock(&loggersMutex);
    return logger;
}
`

**Comment by tt4g** [comment]
spdlog outputs to file or STDOUT by sending log messages to sink, but does not support sink output to pipe.
You need to create your own sink for your own needs.
See: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink
