### ISSUE TITLE
Docs: Note on manually created loggers not being registered seems to be outdated

### ISSUE THREAD

**Issue by luator** [gabime/spdlog#2799]
The documentation on [creating loggers](https://github.com/gabime/spdlog/wiki/2.-Creating-loggers) says in "Note 2" that manually created loggers are not registered automatically.  However, when I try to create a logger and then register it, I get an error saying that it already exists.  So I assume that part of the documentation is outdated?

Minimal example to reproduce:
```c++
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/spdlog.h>

int main()
{
    auto logger = spdlog::stdout_color_st("foo");
    spdlog::register_logger(logger);

    return 0;
}
```
Results in this error when executing it:
```
terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  logger with name 'foo' already exists
```

**Comment by gabime** [comment]
`spdlog::stdout_color_st("foo")` is a factory , not manually a created logger.

**Comment by luator** [comment]
Oh, I see, my bad.   I just now saw further down on the page, there is actually a section with an example on how to manually create a logger.  Maybe it would make sense to move the note down there?  I think my confusion was caused by the snipped using a variable `my_logger` which is not defined anywhere above.

**Comment by gabime** [comment]
The wiki is open for edit for all. Feel free to update it.

**Comment by luator** [comment]
Thanks.  After thinking a bit, I decided to keep the note where it is but added a link to the section about manually creating loggers.  I also added `register_logger` with an explaining comment to the code snippet there.  I hope these changes make sense.

**Comment by gabime** [comment]
Thanks👍
