### ISSUE TITLE
spdlog creates a new log file per call to logger

### ISSUE THREAD

**Issue by ruipacheco** [gabime/spdlog#28]
I've setup spdlog the following way:

    shared_ptr<logger> init_logger(const Settings& settings) {
        spdlog::set_level(spdlog::level::debug);
        try {
          return rotating_logger_mt(kAppName,
                                    settings.logfile,
                                    settings.max_file_size,
                                    settings.max_files,
                                    false);
        }catch (const spdlog_ex& e) {
          throw logic_error(e.what());
        }
    }

with `settings.logfile`, `settings.max_file_size` and `settings.max_files` being

    logfile = emperor.log
    max_file_size = 10
    max_files = 10

I'm only using it in a main.cpp file and call it the following way:

```
uv_loop_t* loop = uv_default_loop();
  try {
    // Init logging.
    logging = init_logger(settings);
    logging->info() << "Init logger";

    stringstream error;
    uv_pipe_t server;
    uint16_t retrn = uv_pipe_init(loop, &server, 0);
    logging->info() << "Init pipe";
    if (retrn < 0) {
      error << "Error initializing pipe: " << uv_strerror(retrn);
      logging->error(error.str().c_str());
      throw logic_error(error.str());
    }

    retrn = uv_pipe_bind(&server, settings.socket_file.c_str());
    logging->info() << "Bind to pipe";
    if (retrn < 0) {
      error << "Error binding to socket " << settings.socket_file << ": " << uv_strerror(retrn);
      logging->error(error.str().c_str());
      throw logic_error(error.str());
    }

    retrn = uv_listen((uv_stream_t*) &server, 128, on_new_connection);
    logging->info() << "Listen on pipe";
    if (retrn < 0) {
      error << "Listen error: " << uv_strerror(retrn);
      logging->error(error.str().c_str());
      throw logic_error(error.str());
    }

  }catch(const logic_error& e) {
    logging->error() << e.what();
    return 2;
  }
```

The problem is that each call to `logging->info()` seems to generate a new log file so after my program has run I end up with several log files: `emperor.txt`, `emperor.1.txt`, `emperor.2.txt`.

**Comment by gabime** [comment]
I think that the problem is max_file_size=10. The param units are in bytes.
You need 1024*10 for 10KB or 1024*1024*10 for 10MB

**Comment by ruipacheco** [comment]
Seems to be it.
