### ISSUE TITLE
details::os::filesize() issue under WinXP(32bit)

### ISSUE THREAD

**Issue by azadkuh** [gabime/spdlog#280]
the buggy visual studio 2015 runtime causes a problem under WinXP SDK (target: v140_xp):
both `_fstat()` and `_stat()` return `EINVAL` and the `details::os::filesize()` eventually throws.

but it's ok under Windows7+ 32/64bit.

references:
- [_stat() not working under windows xp](http://stackoverflow.com/questions/32452777/visual-c-2015-express-stat-not-working-on-windows-xp)
- [_wstat64 returns -1 on XP, always](https://connect.microsoft.com/VisualStudio/feedback/details/1557168/wstat64-returns-1-on-xp-always)

this problem also affects `spdlog`

**Comment by gabime** [comment]
It only happens when **compiling** under windows XP.

**Comment by azadkuh** [comment]
@gabime 
actually I'm compiling under Windows 2008R2 (64bit) by Visual Studio 2015 update 2.

if I compile by win7+ SDK (32bit) the code will be ok (but the output app won't run under Windows XP or Windows 2003 32bit)

setting up the target to WinXP (v140_xp) will cause the damage! the code is runnable under XP but `_stat()/_fstat()/...` fails.

**Comment by gabime** [comment]
I dont have an XP machine at hand. If you can fix it easily please issue a PR. otherwise i will close i since XP is way too old to support anyway.

**Comment by azadkuh** [comment]
i made the [PR](https://github.com/gabime/spdlog/pull/285)

generally [`_filelength() / _filelengthi64()`](https://msdn.microsoft.com/en-us/library/dfbc2kec.aspx) seem to be a cleaner backend for `filesize()` under Windows.

**Comment by gabime** [comment]
@azadkuh Thanks for the fix.
