### ISSUE TITLE
How to retrieve format string from a logger

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [gabime/spdlog#2804]
Hey,
I am trying to get the format string out of a logger. I create something like
```
auto new_logger = std::make_shared<spdlog::logger>("foo", begin(sinks), end(sinks));

auto formatter_m = std::make_unique<spdlog::pattern_formatter>();
formatter_m->set_pattern(*format_str);
new_logger->set_formatter(std::move(formatter_m));

// and so on ...
```

then I would like to do something like

```
auto format = spdlog::get("foo").get_formatter().get_pattern();
```

is this this even possible?

**Comment by gabime** [comment]
No. The problem is that the pattern is per each sink, so there could be several patterns per logger.

**Comment by andrea-cassioli-maersk** [comment]
OK, I see. What about from the sinks? like `logger->sinks().front().get_formatter()`?

**Comment by gabime** [comment]
unfortunately it is not part of the sink api.
