### ISSUE TITLE
Can spdlog directly output Qt basic types, such as QString and QList?

### ISSUE THREAD

**Issue by lotuswater** [gabime/spdlog#2806]
Can spdlog directly output Qt basic types, such as QString and QList?

I want to use like this, 
```
QString text = ui->textEdit->text();
spdlog::info("text is: {}",  text);
```

**Comment by tt4g** [comment]
You can it by defining `fmt::formatter<QString>`.
See: https://fmt.dev/9.1.0/api.html#formatting-user-defined-types

**Comment by lotuswater** [comment]
> You can it by defining `fmt::formatter<QString>`. See: https://fmt.dev/9.1.0/api.html#formatting-user-defined-types

Ok, thanks!
