### ISSUE TITLE
how to stop creating spdlog - log file on disk if logging level is off

### ISSUE THREAD

**Issue by nitinbg200** [gabime/spdlog#2810]
when logging level is "off", spdlog is expected not to create file but it create. Thanks in advance for solution to this issue,

**Comment by gabime** [comment]
By design, the file is created when the sink is constructed, so you will have to create the sink only when really needed if you want to avoid it.

**Comment by nitinbg200** [comment]
Thank you very much @gabime for such quick response. 
But if we dont create sync and keep it as null pointer, then can we pass this sync to sinks_init_list
// Logger with sinks init list
    logger(std::string name, sinks_init_list sinks)

**Comment by gabime** [comment]
No, just create and add the sink when needed to the logger.

**Comment by nitinbg200** [comment]
sorry but I did not find way to add sinks on need basis. I know only way is to use- logger(std::string name, sinks_init_list sinks).
can u paste any example if you know, that would of great help.
Below is my example how I use currently 
std::make_shared<spdlog::logger>(spdlog::logger("SampleLogger", {consoleSink, fileSink}));

**Comment by gabime** [comment]
https://github.com/gabime/spdlog/wiki/4.-Sinks#adding-sinks-to-the-logger-after-creation

**Comment by nitinbg200** [comment]
> https://github.com/gabime/spdlog/wiki/4.-Sinks#adding-sinks-to-the-logger-after-creation

Great Thanks, I will check and let you know the feedback
