### ISSUE TITLE
undefined reference to `__tsan_XXX'

### ISSUE THREAD

**Issue by smessmer** [gabime/spdlog#2812]
[CryFS](https://github.com/cryfs/cryfs) has been using spdlog as a dependency for a long time. We've been using spdlog 1.8.5 so far, but now wanted to upgrade to 1.11.0. But there is a corner case where this seems to fail compilation.

We have pretty expensive CI jobs, testing everything from GCC 7 to 13 and Clang 7 to 13. Most of those builds are fine, but for some reason, clang 11 consistently fails with spdlog 1.11.0. The error message is
```
home/runner/work/cryfs/cryfs/conan-cache/.conan/data/spdlog/1.11.0/_/_/build/322beb395816afde88e8448082874923484aae43/src/include/spdlog/spdlog-inl.h:16: undefined reference to `__tsan_func_entry'
/usr/bin/ld: /home/runner/work/cryfs/cryfs/conan-cache/.conan/data/spdlog/1.11.0/_/_/package/322beb395816afde88e8448082874923484aae43/lib/libspdlogd.a(spdlog.cpp.o): in function `spdlog::details::registry::instance()':
/home/runner/work/cryfs/cryfs/conan-cache/.conan/data/spdlog/1.11.0/_/_/build/322beb395816afde88e8448082874923484aae43/src/include/spdlog/details/registry-inl.h:286: undefined reference to `__tsan_atomic8_load'
/usr/bin/ld: /home/runner/work/cryfs/cryfs/conan-cache/.conan/data/spdlog/1.11.0/_/_/package/322beb395816afde88e8448082874923484aae43/lib/libspdlogd.a(spdlog.cpp.o): in function `__shared_ptr':
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/shared_ptr_base.h:1191: undefined reference to `__tsan_read16'
/usr/bin/ld: /home/runner/work/cryfs/cryfs/conan-cache/.conan/data/spdlog/1.11.0/_/_/package/322beb395816afde88e8448082874923484aae43/lib/libspdlogd.a(spdlog.cpp.o): in function `std::__shared_count<(__gnu_cxx::_Lock_policy)2>::_M_swap(std::__shared_count<(__gnu_cxx::_Lock_policy)2>&)':
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/shared_ptr_base.h:762: undefined reference to `__tsan_write8'
/usr/bin/ld: /home/runner/work/cryfs/cryfs/conan-cache/.conan/data/spdlog/1.11.0/_/_/package/322beb395816afde88e8448082874923484aae43/lib/libspdlogd.a(spdlog.cpp.o): in function `__shared_ptr':
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/shared_ptr_base.h:1194: undefined reference to `__tsan_write8'
```
(and many more lines for other `__tsan_XXX` symbols)

Note that our build does **not** build with tsan. But for some reason, spdlog or fmt seems to enable tsan.

Full error log of the CI run: https://github.com/cryfs/cryfs/actions/runs/5511063966/jobs/10046135848
Diff that breaks it: https://github.com/cryfs/cryfs/commit/09d81386a2642805b47104780909cd4dada8f67b (the CI job works before thic ommit but breaks after this commit)

Also note that it only fails in `CMAKE_BUILD_TYPE=Debug` builds. `Release` and `RelWithDebInfo` are fine.

**Comment by tt4g** [comment]
Can you reproduce the same problem without using the package manager `conan`?
Since conan may download precompiled packages, the problem that occurs with compiled spdlog cannot be solved here.

**Comment by smessmer** [comment]
I only see it happen in this particular CI job but it could be caused by the precompiled conan package if they packaged it wrongly. I'm not too familiar with it though. Is there anything [here](https://github.com/conan-io/conan-center-index/blob/df2cef9bebe23d3684867fbd8093bf3696eec872/recipes/spdlog/all/conanfile.py#L13) that you think could cause it? I don't see any mentions of tsan.

**Comment by tt4g** [comment]
No report of ``undefined reference to `__tsan_read16'`` error found in spdlog issues.

It is set to use precompiled libraries and should be changed to build all libraries.

https://github.com/cryfs/cryfs/blob/09d81386a2642805b47104780909cd4dada8f67b/cmake-utils/DependenciesFromConan.cmake#L4-L7C26

```diff
 conan_cmake_install(
     PATH_OR_REFERENCE ${CMAKE_CURRENT_SOURCE_DIR}/conanfile.py
-    BUILD missing
+    BUILD all
     SETTINGS ${settings})
```

Reference: https://github.com/conan-io/cmake-conan#build

And please ask your conan questions in conan repository (https://github.com/conan-io/conan-center-index or https://github.com/conan-io/conan).
