### ISSUE TITLE
Is there a bug in circular_q::size()?

### ISSUE THREAD

**Issue by SaltedReed** [gabime/spdlog#2820]
Now circular_q::size() is implemented as:
```
    // Return number of elements actually stored
    size_t size() const
    {
        if (tail_ >= head_)
        {
            return tail_ - head_;
        }
        else
        {
            return max_items_ - (head_ - tail_); // is it wrong?
        }
    }
```

**At where I commented, is it supposed to be "return max_items_ *- 1* - (head_ - tail_);"?** 

An example is, when users call the following constructor to create a circular queue with `max_items`=3:
```
explicit circular_q(size_t max_items)
        : max_items_(max_items + 1) // one item is reserved as marker for full q
        , v_(max_items_)
    {}
```
`max_items_`=4. So If the circular queue looks like this:
**index:** &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0 &nbsp; 1 &nbsp; 2
**has element:** no       no     yes
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; tail_ &nbsp; &nbsp; head_
then size() is supposed to return 1. But with current implementation, the return value is 4-(2-0)=2. I think the marker for full q should be minused here, which isn't yet.

**Comment by tt4g** [comment]
It has been changed in this commit (bad728446564bc705ee5b348015a8ef0afcb7336), but maybe missed the `max_items_ = max_items + 1` in the constructor.
There is no test, so I think it is most likely a bug.

**Comment by gabime** [comment]
Good catch @SaltedReed . PR to fix is welcome. 
@tt4g You are right, we need to add some tests for it.
