### ISSUE TITLE
Two files in a row are exactly the same (0.13.0)

### ISSUE THREAD

**Issue by gutongjiang** [gabime/spdlog#2821]
I use rotating_logger_mt to rotate logs, and found that there are two consecutive files that are exactly the same, causing the server cpu to rise. The version is 0.13.0. May I ask if this is an issue with an older version and if so which version do I need to upgrade to and make minor code changes

**Comment by tt4g** [comment]
What do you mean by "two consecutive files"?

**Comment by tt4g** [comment]
In any case, please update to the latest version if possible.
[v0.13.0 was released in 2017](https://github.com/gabime/spdlog/releases/tag/v0.13.0). If another bug is found, it cannot be fixed.
