### ISSUE TITLE
epoll_wait not working with spdlog

### ISSUE THREAD

**Issue by GiridharKC** [gabime/spdlog#2822]
I am trying to use spdlog with my program main.cpp  which has epoll_wait() implmented. 

I am using below cmake to compile and link spdlog to my program in folder src.

CMakeLists.txt 
if(NOT "${CMAKE_CXX_STANDARD}")
    set(CMAKE_CXX_STANDARD 17)
endif()

cmake_minimum_required(VERSION 3.5)

add_subdirectory(src) // this folder has main.cpp
#add_subdirectory(spdlog)
------
If enable add_subdirectory(spdlog) is enabled to compile, epoll_wait() in main.cpp stops working. if I comment out add_subdirectory(spdlog) then epoll_waint() in main.cpp works.

epoll_wait() implmented to wait for timerfd. 

I am unable to understand the relationship here, though I suspected the thread lib, std thread works fine and I am able to log using spdlog. Only issue in epoll_wait() not receving any events 

Could anyone help here !

**Comment by tt4g** [comment]
Please provide minimal source code that can reproduce the issue.

**Comment by GiridharKC** [comment]
here is the code I used to recreate the issue
main.cpp

```cpp
#include <cstdlib>
#include "sys/epoll.h"
#include <sys/eventfd.h>
#include <sys/signalfd.h>
#include <sys/timerfd.h>
#include <sys/socket.h>
#include <assert.h>
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <condition_variable>
#include <mutex>
#include <chrono>
#include <thread>
#include <unistd.h>
#include <map>
#include <functional>

`const int   MAX_EVENTS = 3;
struct context {
	void (*handler)(struct context *obj);

};

struct user_context {
	void (*handler)(struct user_context *obj);
    // Any other user data can go here
    void *data;
};

typedef void sighandler(int);

int main(int argc, char* argv[])
{

    struct user_context mUserEventObj;
    struct context mObj[MAX_EVENTS] = {};
    
    int mEpollFd;
    int mTfd;
    int mEfd;
    int mSfd;
    /*
     *  Millisecond interval for periodic time loop. Change this if you  want to change the interval of timer loop
     */
    int mTickIntervalMs = 100;
    struct epoll_event mEvent[MAX_EVENTS];
    struct epoll_event mEvents[MAX_EVENTS];
    sighandler* sig_handler;

    mEpollFd = epoll_create1(0);
    assert(mEpollFd != -1);
	
    memset(mEvents, 0, sizeof(epoll_event) * MAX_EVENTS);
    memset(mEvent, 0, sizeof(epoll_event) * MAX_EVENTS);

    //setup timer

    mTfd = timerfd_create(CLOCK_MONOTONIC, TFD_NONBLOCK);
    assert(mTfd != -1);

    // start periodic timer
    struct itimerspec its;
    its.it_value.tv_sec = mTickIntervalMs/1000;
    its.it_value.tv_nsec = mTickIntervalMs * 1000000;  // 0.1 sec
    its.it_interval.tv_sec = mTickIntervalMs/1000;
    its.it_interval.tv_nsec = mTickIntervalMs * 1000000;

    assert(0 == timerfd_settime(mTfd, 0, &its, NULL));
    mEvent[0].events =  EPOLLIN | EPOLLET;
    mEvent[0].data.ptr = &mObj[0];
    assert(0 == epoll_ctl(mEpollFd, EPOLL_CTL_ADD, mTfd, &mEvent[0]));	


    //process events
 
    for (;;) {
    
        std::cout << "wait for event" <<std::endl;
        int n = epoll_wait(mEpollFd, mEvents, MAX_EVENTS, -1);
        std::cout << "event received" <<std::endl;
        assert(n >= 0);
        
        for (int i = 0; i < n; i++) {
            void * epollId = (void *)mEvents[i].data.ptr;
            if(epollId == (void *)&mObj[0]) {   
                if (mEvents[i].events & (EPOLLIN | EPOLLERR)) {   
                   std::cout << "timer event received" <<std::endl;
                   unsigned long long val;
                   read(mTfd, &val, 8);
                }
             }	
        }
 
    }
    return 0;   
 }
```
=========================================
#cmake files used to compile main.cpp

add_executable(test main.cpp)

install(TARGETS test EXPORT test
	RUNTIME DESTINATION bin
	LIBRARY DESTINATION lib
)

=========================================

#cmake file used to compile both source code and spdlog

`if(NOT "${CMAKE_CXX_STANDARD}")
    set(CMAKE_CXX_STANDARD 17)
endif()

cmake_minimum_required(VERSION 3.5)

add_subdirectory(src)
#add_subdirectory(spdlog)

======================================

ouput of disabling add_subdirectory(spdlog)

wait for event
event received
timer event received
wait for event
event received
timer event received
wait for event
event received
timer event received
wait for event
event received
timer event received
wait for event
event received
timer event received
wait for event
event received
timer event received
wait for event
event received
timer event received
wait for event

=================================
ouput of enabling add_subdirectory(spdlog)

wait for event
--stuck forever--

**Comment by GiridharKC** [comment]
<img width="1341" alt="Screenshot 2023-07-19 at 8 39 59 PM" src="https://github.com/gabime/spdlog/assets/11937861/6e4309a7-dfd9-41a6-a317-5c0cd9b304fd">
<img width="591" alt="Screenshot 2023-07-19 at 8 41 29 PM" src="https://github.com/gabime/spdlog/assets/11937861/f9846436-bece-465d-9166-fa8f82e0416e">

**Comment by tt4g** [comment]
Does the problem occur when `target_link_library(test spdlog)` is not in `CMakeLists.txt`?
If so, this is very strange. I can't find `#include <spdlog/*>` and I don't think spdlog affects your project.

**Comment by tt4g** [comment]
I am concerned that there is a branch where `read(mTfd, &val, 8)` is not called.
Interesting comments on the timer and `EPOLLET`: https://stackoverflow.com/a/63965660

See also: https://stackoverflow.com/questions/12102740/epoll-with-timerfd

**Comment by GiridharKC** [comment]
> Does the problem occur when `target_link_library(test spdlog)` is not in `CMakeLists.txt`? If so, this is very strange. I can't find `#include <spdlog/*>` and I don't think spdlog affects your project.

yes, its a strange issue. I have not even linked spdlog (`target_link_library(test spdlog)`) to executable and not included `#include <spdlog/*>`, but just build the spdlog in my project. that causing my program epoll_wait not working, if I remove spdlog build from my project, epoll_wait() in my program works fine.

**Comment by tt4g** [comment]
Can you provide the part of the compiler options changed by `add_subdirectory(spdlog)`?
If the compiler options have not changed, then spdlog is not related to the problem.

EDIT:  There are a several function calls in `assert` (e.g. `assert(0 == timerfd_settime(mTfd, 0, &its, NULL));`), but you know that `assert` is removed at compile time if the `NODEBUG` macro is defined, don't you?
In other words, the code you provided works only with Debug builds. The Release build that defines `NODEBUG` macros will not call some of the `epoll_*` functions, so it would be weird for it to work.

**Comment by GiridharKC** [comment]
> Can you provide the part of the compiler options changed by `add_subdirectory(spdlog)`? If the compiler options have not changed, then spdlog is not related to the problem.
> 
> EDIT: There are a several function calls in `assert` (e.g. `assert(0 == timerfd_settime(mTfd, 0, &its, NULL));`), but you know that `assert` is removed at compile time if the `NODEBUG` macro is defined, don't you? In other words, the code you provided works only with Debug builds. The Release build that defines `NODEBUG` macros will not call some of the `epoll_*` functions, so it would be weird for it to work.


Here is the compiler options after I build my project with spdlog 

-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.12.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Build type: Release
-- Configuring done
-- Generating done

I missed the assert part, I can see when my project built with spdlog changes compiler with "Build type: Release". This caused removal of assert as you mentioned. I fixed moving the functions outside assert(), its all working fine now. 
Thank you very much for your prompt response, I will close the ticket!
