### ISSUE TITLE
'fileno' was not declared in this scope

### ISSUE THREAD

**Issue by Purbasha-Roy** [gabime/spdlog#2824]
PS C:\Users\Purbasha Roy\OneDrive\Desktop\Project C++> make test
g++  -std=c++14   -g -O0 -pedantic -Wall -Wfatal-errors -Wextra -Wno-unused-parameter -Wno-unused-variable -MMD -MP -msse2 -c tests/part1.cpp -o .objs/tests/part1.o
g++  -std=c++14   -g -O0 -pedantic -Wall -Wfatal-errors -Wextra -Wno-unused-parameter -Wno-unused-variable -MMD -MP -msse2 -c tests/part2.cpp -o .objs/tests/part2.o
g++  -std=c++14   -g -O0 -pedantic -Wall -Wfatal-errors -Wextra -Wno-unused-parameter -Wno-unused-variable -MMD -MP -msse2 -c uiuc/catch/catchmain.cpp -o .objs/uiuc/catch/catchmain.o
In file included from uiuc/catch/catchmain.cpp:2:
uiuc/catch/catch.hpp: In constructor 'Catch::OutputRedirect::OutputRedirect(std::string&, std::string&)':
uiuc/catch/catch.hpp:8400:14: error: 'fileno' was not declared in this scope
 8400 |         dup2(fileno(m_stdoutFile.getFile()), 1);
      |              ^~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [uiuc/make/uiuc.mk:52: .objs/uiuc/catch/catchmain.o] Error 1

**Comment by tt4g** [comment]
The word "spdlog" never appears in the compile error.
