### ISSUE TITLE
Dll unloading and async logging

### ISSUE THREAD

**Issue by BoyeGuillaume** [gabime/spdlog#2826]
### Description
When using a **dll dynamically loaded/unloaded**, along **asynchronous logging** and having a single sink being shared accross all dll, it may be the case that the shared library gets unloaded while the message is not yet process by the thread pool. Because of that, the filename of the message will point into the old dll memory resulting in a segfault. 

> This "bug" is very specific and is mostly my fault. I don't expect any fix from the maintainers of spdlog. I am mostly writing this issue as a note that could be included in the documentation.
> > Mostly because the only fix I can think of is to copy all filenames into the main application memory, and this introduce for 99.9% of cases a unnecessary overhead

### How to "fix" the problem
If you have a control of when the dll's get unloaded make sure the flush the entire thread pool prior to unloading the dll !!

**Comment by gabime** [comment]
Thanks. There is the `spdlog:shutdown()` that can be used for this.
