### ISSUE TITLE
Is having multiple sinks of the same type allowed ?

### ISSUE THREAD

**Issue by Iuliean** [gabime/spdlog#2831]
```cpp
    class LoggerManager
    {
    public:
        enum class Level
        {
            DEBUG   = spdlog::level::debug,
            INFO    = spdlog::level::info,
            WARNING = spdlog::level::warn,
            ERROR   = spdlog::level::err
        };
        LoggerManager(const std::string& fileName = "");


        void SetLevel(Level level);

        std::shared_ptr<Logger> GetLogger(const std::string& name);
    private:
        std::mutex m_loggersMutex;
        std::map<std::string, std::weak_ptr<Logger>> m_loggers;
        std::vector<spdlog::sink_ptr> m_sinks;
    };
    class Logger
    {
    public:
        Logger(spdlog::logger logger);
        
        operator spdlog::logger&();

        static Logger& GetGlobalLogger();
    private:
        spdlog::logger m_logger;

        static std::unique_ptr<Logger> s_globalLogger;
        static std::mutex s_globalLoggerMutex;
    };

```
I am trying to write a way to get loggers for independent objects but also have a global logger where anything can be dumped in.

As you can see my idea is to have a logger manager that makes the objects as needed when an object requests one and also have a singleton Logger object that will do general logging from different util functions and etc (generally stuff that don't have a domain)

As my design stands i would have to make two objects of each `stdout_color_sink_mt` and `basic_file_sink_mt` one set for the LoggerManager and one set for the global Logger is this safe/allowed ? Should i just make the sinks objects into a global vector which i will use for both the global Logger and LoggerManager?

**Comment by gabime** [comment]
The `LoggerManager` seems like a duplication of spdlog’s already existing api(`spdlog::get(..), spdlog::regisger_logger(...)`, `spdlog::set_default_logger(..)`, etc.).
Why not just use it?

**Comment by Iuliean** [comment]
I had an issue with it where if you try to request a logger with a name that already exists instead of giving you the already existing logger (which is what i expected it to do) it throws an exception

Edit: And if i remember correctly i looked through the code it it seemed to be by design 
Edit2 :Sorry i looked through the code again it is the other way around if it can't find it it will return `nullptr` instead of constructing one.
But it also seems to keep them alive for the entirety of the program which i don't really want to have

**Comment by gabime** [comment]
> But it also seems to keep them alive for the entirety of the program which i don't really want to have

There is also `spdlog::drop()` …
