### ISSUE TITLE
Undefined reference on both GCC and Clang with external fmtlib 10.0.0

### ISSUE THREAD

**Issue by alex-immersive** [gabime/spdlog#2832]
I'm importing both fmtlib and spdlog using Cmake FetchContent_Declare/FetchContent_MakeAvailable. 
SPDLOG_FMT_EXTERNAL is defined. 

During linking I see the following errors:

Tested on Clang 16/GCC 13

spdlog: 1.12.0
fmtlib: 10.0.0

```
/usr/bin/ld: apps/CMakeFiles/helloworld.dir/helloworld/helloworld.cpp.o: in function `spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)':
/home/project/cmake-build-clang-debug/_deps/spdlog-src/include/spdlog/logger.h:134: undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'
/usr/bin/ld: apps/CMakeFiles/helloworld.dir/helloworld/helloworld.cpp.o: in function `void spdlog::logger::log_<char const*>(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>, char const*&&)':
/home/project/cmake-build-clang-debug/_deps/spdlog-src/include/spdlog/logger.h:377: undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'
/usr/bin/ld: apps/CMakeFiles/helloworld.dir/helloworld/helloworld.cpp.o: in function `void spdlog::logger::log_<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/home/project/cmake-build-clang-debug/_deps/spdlog-src/include/spdlog/logger.h:377: undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'
/usr/bin/ld: apps/CMakeFiles/helloworld.dir/helloworld/helloworld.cpp.o: in function `void spdlog::logger::log_<int&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>, int&)':
/home/project/cmake-build-clang-debug/_deps/spdlog-src/include/spdlog/logger.h:377: undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'
/usr/bin/ld: apps/CMakeFiles/helloworld.dir/helloworld/helloworld.cpp.o: in function `void spdlog::logger::log_<int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/home/project/cmake-build-clang-debug/_deps/spdlog-src/include/spdlog/logger.h:377: undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'
/usr/bin/ld: apps/CMakeFiles/helloworld.dir/helloworld/helloworld.cpp.o:/home/project/cmake-build-clang-debug/_deps/spdlog-src/include/spdlog/logger.h:377: more undefined references to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v10::basic_string_view<char>, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)' follow
```

**Comment by tt4g** [comment]
I think spdlog is not added to the link target, or spdlog is referring to another version of fmt.

**Comment by tt4g** [comment]
> /usr/bin/ld: apps/CMakeFiles/helloworld.dir/helloworld/helloworld.cpp.o: in function `spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)'

The error reports that it is making a call from `spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v10::basic_string_view<char>)' to another `spdlog::logger::log(...)`, but it is not implemented as such.

https://github.com/gabime/spdlog/blob/2ee8bac78e6525a8ad9a9196e65d502ce390d83a/include/spdlog/logger.h#L125-L136

**Comment by alex-immersive** [comment]
spdlog and fmt are both added to the target correctly. When I change the fmtlib version to 9.1.0, it links correctly.

I also don't think spdlog could be referring to another version of fmt, since the bundled version is v9, and my local system doesn't have fmt installed.

**Comment by tt4g** [comment]
So I guess fmt is not linked?

**Comment by alex-immersive** [comment]
I'm no expert when it comes to c++ linkage, but I'm unsure why fmt would be linked for 9.1.0 but wouldn't be for 10.0.0. I'm not changing that between switching versions.

**Comment by tt4g** [comment]
How do you add spdlog and fmt to your project?
If fmt is not installed on your machine, then you must be passing the fmt library somewhere to the linker, right?

**Comment by alex-immersive** [comment]
Not installed with an os/pkg manager. I'm using cmake's FetchContent_Declare/FetchContent_MakeAvailable to install these libs to my local cmake build dir. I then use `target_link_libraries` to configure my targets.

**Comment by tt4g** [comment]
CMake does not automatically add libraries to the link target just by importing them by `FetchContent`.
Please provide `CMakeLists.txt`.

**Comment by alex-immersive** [comment]
I don't believe this is an issue with my cmakelists. Its working correctly with 10s of other libraries including boost. It works with fmt 9.1.0, it doesn't work with fmt 10.0.0.

**Comment by tt4g** [comment]
If `CMakeLists.txt` is not provided, I can't help.
I can only assume it is a build problem as there are other users using spdlog and fmt 10.

**Comment by alex-immersive** [comment]
Thanks for the help

It was cmake after all, I needed to explicitly set the cmake variable before calling FetchContent

```
set(SPDLOG_FMT_EXTERNAL ON CACHE BOOL "SPDLOG_FMT_EXTERNAL" FORCE)
```
