### ISSUE TITLE
The problem of using macros define and customize loggers to print line numbers and file names

### ISSUE THREAD

**Issue by blueoblue** [gabime/spdlog#2837]
1. example
  (ubuntu22,gcc11,spdlog1.12.0)
  The flowwing is source code:
```c++
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"

int main()
{
    auto console=spdlog::stdout_logger_mt("console");
    console->set_pattern("[source %s][line %#] %v");

    console->info("log with console"); 
    SPDLOG_LOGGER_INFO(console, "log with macro");
    SPDLOG_INFO("log with default logger");
}
```
`console` is manual generation, and set pattern to print filename,linenumber.
macro`SPDLOG_LOGGER_INFO` using logger `console` to print.
`SPDLOG_INFO` using default logger.
  The results are as follows：
```
[source ][line ] log with console
[source lg.cpp][line 27] log with macro
[2023-07-29 14:57:13.978] [info] [lg.cpp:28] log with default logger
```

2. why
   Why does `SPDLOG_INFO` and `SPDLOG_LOGGER_INFO` output normally, but `console` not?

**Comment by tt4g** [comment]
`SPDLOG_INFO` use default logger.

```diff
 #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
 #include "spdlog/spdlog.h"
 #include "spdlog/sinks/stdout_sinks.h"

 int main()
 {
     auto console=spdlog::stdout_logger_mt("console");
     console->set_pattern("[source %s][line %#] %v");
+   spdlog::set_default_logger(console);

     console->info("log with console"); 
     SPDLOG_LOGGER_INFO(console, "log with macro");
     SPDLOG_INFO("log with default logger");
 }
```

See:
  - https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format
  - https://github.com/gabime/spdlog/wiki/Default-logger

**Comment by blueoblue** [comment]
@tt4g yes,I added this setting, but it didn't work.It still doesn't have a line number.

**Comment by tt4g** [comment]
It is a specification that `console->info("log with console");` is not output.
In the C++ language, line numbers and source file names can only be gotten at compile time.

See logging macro source: https://github.com/gabime/spdlog/blob/2ee8bac78e6525a8ad9a9196e65d502ce390d83a/include/spdlog/spdlog.h#L304-L325

**Comment by blueoblue** [comment]
@tt4g According to the first use case description in the document: "For these to work, you must use compile time log level macros.", to output information such as line numbers, I must print the information using macro definitions, not custom loggers. like this:
```c++
SPDLOG_XXX();
// or
SPDLOG_LEVEL_XXX();
// not
logerxxx->xxx()
```
Is that what it means?

**Comment by blueoblue** [comment]
@tt4g  Oh, ok thank you.

**Comment by tt4g** [comment]
Yes, but you can also use custom loggers.

```cpp
SPDLOG_LOGGER_<LEVEL>(your_logger, ...); // custom logger.
SPDLOG_<LEVEL>(...); // default logger.
```

**Comment by blueoblue** [comment]
ok
