### ISSUE TITLE
logger with name 'someName' already exists

### ISSUE THREAD

**Issue by agauniyal** [gabime/spdlog#284]
I know the cause of this error, what I'm asking is how to approach this problem. I've a class with a logger as private member. In the constructor, I initialize it like this - `logger = spdlog::rotating_logger_mt(name, "mylogfile.log", 1048576 * 5, 3);`. I don't intend to share a common logger amongst objects.

The `name` refers to another private member of my class, but currently has no restrictions over its uniqueness. Even if I had to put them, which I can do, the objects can be deleted and newer ones could be created again with same name. Or renamed as well. But `spd::logger` requires the name to be unique per logger, and I don't think it can be renamed at runtime, can it be?

So I've two problems at my hand -
 - How should I delete the logger along with the deletion of object, probably inside the destructor?
 - Can the name of logger be changed at runtime?

**Comment by gabime** [comment]
Creating loggers this way registers them and requires the unique name. 
But if the logger is not shared across the program, it can created directly without any restriction(and will be faster to create):

```c++
auto rotating_sink = make_shared<spdlog::sinks::rotating_file_sink_mt> ("log_filename", "log", 1024*1024, 5, false);
this->logger = make_shared<spdlog::logger>(name, rotating_sink);
//or for async:
this -> logger make_shared<spdlog::async_logger>("my_logger", rotating_sink, size);
```

**Comment by agauniyal** [comment]
by not shared, means I am not going to call `spd::get()` method, right? And with this manual creation, the logger gets destroyed with the object?

**Comment by gabime** [comment]
right. no get(..) and no need to uniqueness.
