### ISSUE TITLE
rotating_logger_st error in single thread class

### ISSUE THREAD

**Issue by coder0d0a** [gabime/spdlog#2841]
I'm encountered an error while create two rotating logger like this:
`
class CExecutor
{
	public:
		CExecutor()
		{
			oneLogger = spdlog::rotating_logger_mt(logname,logfile,1024,5);
			anotherLogger = spdlog::rotating_logger_mt(anotherLogName, anotherLogFile, 1024,5);
		};
		~CExecutor(){};
		void Execute()
		{
			CreateThread(NULL, 0, &CExecutor::ExecutorThread, this, 0, 0);
		}
	private:
		std::shared_ptr<spdlog::logger> oneLogger;
		std::shared_ptr<spdlog::logger> anotherLogger;
	private:
		static DWORD WINAPI ExecutorThread(LPVOID lpParam)
		{
			// some code here
		}
		
};

int main()
{
	std::vector<CExecutor*> executors;
	for(size_t index=0; index<5;index++)
	{
		CExecutor executor = new CExecutor;
		executors.push_back(executor);
	}
	
	for(auto it=executors.begin();it!=executors.end();it++)
	{
		it->Execute();
	}
	
	return 0;
}
`
The error is : 
![image](https://github.com/gabime/spdlog/assets/129766559/b29772b1-18e8-4765-8f51-339880a7b39e)

So, what's going on, and how can i avoid this error?Please Help Me.

**Comment by tt4g** [comment]
The error message explains it all.
Loggers with the same name cannot be registered in spdlog.

**Comment by coder0d0a** [comment]
> The error message explains it all. Loggers with the same name cannot be registered in spdlog.

I knew the error meanning, the key point is that how avoid this in my case?

**Comment by tt4g** [comment]
Just change `logName` and `anotherLogName` to different names.
We don't know what is set from the code provided, and no error messages are provided so we don't know what exactly to change to.

**Comment by coder0d0a** [comment]
> Just change `logName` and `anotherLogName` to different names. We don't know what is set from the code provided, and no error messages are provided so we don't know what exactly to change to.

it's my fault, the `logName`  and `anotherLogName` are already difference names. Do you have any good idea?:-)

**Comment by tt4g** [comment]
The name conflicts with a logger created elsewhere.

The name of the default_logger automatically created by spdlog is `""`.

https://github.com/gabime/spdlog/blob/2ee8bac78e6525a8ad9a9196e65d502ce390d83a/include/spdlog/details/registry-inl.h#L37-L49

If you have a conflict with any other name, we don't know what the conflicting name is, as it is a problem with your project.

**Comment by coder0d0a** [comment]
> 

1. when create the "SUCCESS" logger,the logName variable is not empty:
![image](https://github.com/gabime/spdlog/assets/129766559/16288426-b72b-4e3d-9117-10c3ce9f5611)

2. Let's step into `spdlog::rotating_logger_mt`, and the first and second parameter are valid:
![image](https://github.com/gabime/spdlog/assets/129766559/2d239e20-ccc2-429c-9125-9b197ee292cd)
![image](https://github.com/gabime/spdlog/assets/129766559/4027fa40-c194-449a-be00-540a3ff15700)

3. Go on step into `return Factory::template create<sinks::rotating_file_sink_mt>(logger_name, filename, max_file_size, max_files, rotate_on_open)`, and then, logger_name has been set to `""` after the code been executed in red rectangle:
![image](https://github.com/gabime/spdlog/assets/129766559/8982f291-de87-4240-aecc-2205f95e0515)

I'm sure that i have two differece logger names on `logName` and `anotherLogName`.

**Comment by coder0d0a** [comment]
this error is not about of spdlog, it about the class constructure function's parameter(a param should be reference of an string, but not)
