### ISSUE TITLE
Feature request: Ability to provide user-defined timepoint for logs

### ISSUE THREAD

**Issue by mc-allen-fm** [gabime/spdlog#2842]
For my use case, where I sometimes run my application within a simulation context, it would be useful to be able to provide my own timestamp for logs. I see that there is an underlying log interface that allows for a time point to be provided to populate the `log_msg` object. Could there be a public `->log()` function that would allow a timestamp to be provided?

**Comment by tt4g** [comment]
`spdlog::logger::log(log_clock::time_point log_time, source_loc loc, level::level_enum lvl, string_view_t msg)` exists.

https://github.com/gabime/spdlog/blob/811bc4c7a9a4b192c6fa59109476e214f0eb50c0/include/spdlog/logger.h#L112

**Comment by mc-allen-fm** [comment]
Right, but then I need to convert my log messages and arguments to a string view... is there another function I should use to do that?

Having a similar logger function that accepts a `log_clock::time_point` along with format string and arguments would be ideal in this case.

**Comment by tt4g** [comment]
Not provided.
PR is welcome.
