### ISSUE TITLE
vcpkg: spdlog dependency on fmt seems to have wrong minimum version specified

### ISSUE THREAD

**Issue by DanEngelbrecht** [gabime/spdlog#2844]
Consider this vcpkg.json:

```
{
  "builtin-baseline" = "44d94c2edbd44f0c01d66c2ad95eb6982a9a61bc",
  version = "1.0",
  dependencies = {
    {
      "version>=" = "1.12.0",
      platform = "linux & x64",
      "default-features" = true,
      name = "spdlog"
    }
  },
  name = "stub",
  overrides = {
    {
      name = "spdlog",
      version = "1.12.0"
    }
  }
}
```

Using this to install spdlog via vcpkg make it install fmt v 7.1.3, log:
```
The following packages will be built and installed:
  * fmt:x64-linux -> 7.1.3#4 -- /home/dan/github/microsoft/vcpkg/buildtrees/versioning_/versions/fmt/230e140a15afbb9089537e153d8b83f5b994adbe
    spdlog:x64-linux -> 1.12.0 -- /home/dan/github/microsoft/vcpkg/buildtrees/versioning_/versions/spdlog/41cf31aa350a44644863d7777489501d240f248c
  * vcpkg-cmake:x64-linux -> 2021-02-28#1 -- /home/dan/github/microsoft/vcpkg/buildtrees/versioning_/versions/vcpkg-cmake/4abdcc88bd5ec2c76e320eb2ff4db665ee9913ac
  * vcpkg-cmake-config:x64-linux -> 2021-02-26#1 -- /home/dan/github/microsoft/vcpkg/buildtrees/versioning_/versions/vcpkg-cmake-config/46d60d4dd4297bedecdcd308167ad2492b269183
```

Now this fails since spdlog can't actually be compiled with fmt version 7.1.3, it requires a newer version of the fmt library - 8.0.0 or later.

I don't know where this is specified when producing the spdlog vcpkg package.

Doing a install of spdlog where you just select "latest" makes vcpkg install the "most recent compatible version" which is 10.0.0 which is fine.

So vcpkg going with the oldest compatible version of fmt when specifying a version for spdlog could be debated, the fact that spdlog 1.12.0 does not compile with fmt v7.1.3 needs to be resolved.

**Comment by tt4g** [comment]
This repository does not maintain vcpkg.
Please reopen this issue in [microsoft/vcpkg](https://github.com/microsoft/vcpkg).

**Comment by DanEngelbrecht** [comment]
Oh, my bad, I thought spdlog specified which versions it was compatible with.

**Comment by tt4g** [comment]
Since the CMake variable `SPDLOG_FMT_EXTERNA=ON` is defined here, an external fmt library (provided by vcpkg) is used.

https://github.com/microsoft/vcpkg/blob/1e9cf6939df1d0b9c1f71505a0e54fd9f4b35d2d/ports/spdlog/portfile.cmake#L25-L34
