### ISSUE TITLE
When output to QTextEdit, Chinese garbled characters

### ISSUE THREAD

**Issue by zhjiarong** [gabime/spdlog#2847]
auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("./zhjrqt.log", true);
file_sink->set_level(spdlog::level::trace);
auto qt_sink = std::make_shared<spdlog::sinks::qt_color_sink_mt>(ui.output_textEdit, 1000);
qt_sink->set_level(spdlog::level::trace);
auto logger = std::make_shared<spdlog::logger>("zhjrQT", spdlog::sinks_init_list{file_sink, qt_sink});
logger->set_level(spdlog::level::trace);
logger->flush_on(spdlog::level::trace);

SPDLOG_LOGGER_INFO(logger, "======[核查数据]======");
![Clip_20230807_231326](https://github.com/gabime/spdlog/assets/44044519/3049200e-dfa2-4468-afe5-fe302fd78f33)

**Comment by zhjiarong** [comment]
how to solve it?

**Comment by gabime** [comment]
The color sinkIt doesnt support non ascii. see pr #2836
