### ISSUE TITLE
Error when using spdlog with gtests-parallel 

### ISSUE THREAD

**Issue by mrgalper** [gabime/spdlog#2849]
When using gtests-parallel to tests my project in a very specific case had the following stacktrace:

Stacktrace:
 0# SegmentationFaultHandler(int) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:916
 1# 0x00007FAA88ECD090 in /lib/x86_64-linux-gnu/libc.so.6
 2# cfree in /lib/x86_64-linux-gnu/libc.so.6
 3# spdlog::sinks::ansicolor_sink<spdlog::details::console_stdout, spdlog::details::console_mutex>::~ansicolor_sink() at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:191
 4# spdlog::logger::~logger() at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/atomicity.h:81
 5# std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<spdlog::logger> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<spdlog::logger> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear() at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/atomicity.h:81
 6# spdlog::details::registry::~registry() at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/hashtable.h:375
 7# __cxa_finalize in /lib/x86_64-linux-gnu/libc.so.6
 
 This was on a very specific case.

**Comment by gabime** [comment]
gtests-parallel is not supported
