### ISSUE TITLE
Passing loglevel as a parameter to logger

### ISSUE THREAD

**Issue by alex-lt-kong** [gabime/spdlog#2852]
Doc says that we can log by calling different functions, like below:

```C++
logger.warn("this should appear in both console and file");
logger.info("this message should not appear in the console, only in the file");
```

The problem is, can I switch to a different format that passes loglevel as a parameter like below?:

```C++
logger.write(warn, "this should appear in both console and file");
logger.write(info, "this message should not appear in the console, only in the file");
```

The case is that I am given a callback interface that passes loglevel as an argument:

```C++
typedef void (*logging_callback)(LoggingLevel log_level, const char *log, size_t log_size);
```

For sure I can implement the interface like below:
```C++
auto logging_cb = [](LoggingLevel level, const char *log, size_t log_size, void *) {
  if (level == LOGGING_LEVEL_INFO) {
    logger.info(log);
  }
  if (level == LOGGING_LEVEL_WARN) {
    logger.warn(log);
  }
};
```

But I am just wondering if there is a more "elegant" solution (and hopefully with fewer branching?).

(I am aware of code like below in `spdlog/spdlog.h`, but not sure if/how I should call them directly?)
```C++
template<typename T>
inline void log(source_loc source, level::level_enum lvl, const T &msg)
{
    default_logger_raw()->log(source, lvl, msg);
}

template<typename T>
inline void log(level::level_enum lvl, const T &msg)
{
    default_logger_raw()->log(lvl, msg);
}
```

**Comment by tt4g** [comment]
You can use `log()` funcsions (`spdlog::log(...)`, and `spdlog::logger::log(...)`).
Because their access limits are `public`.

If you do not want to call it directly, use the logging macro `SPDLOG_LOGGER_CALL`.

https://github.com/gabime/spdlog/blob/2312489bdc304886b4a2eebc8f7f8dc0c4de688f/include/spdlog/spdlog.h#L304-L309

**Comment by alex-lt-kong** [comment]
Ah yes it works!
