### ISSUE TITLE
Example to customize log level text

### ISSUE THREAD

**Issue by y-intercept2018** [gabime/spdlog#2854]
spdlog's log's "%l" flag by default is in lowercase, such as "debug", "info", "warning", etc. It seems to me that it is possible to convert them to "DEBUG", "INFO", "WARNING", etc per [this link](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#extending-spdlog-with-your-own-flags)

After RTFM, I come up with this class, is this the "correct" way to achieve this? (especially, would it cause any non-trivial performance degradation given the string manipulation?)

```C++
class my_formatter_flag : public spdlog::custom_flag_formatter {
public:
  void format(const spdlog::details::log_msg &msg, const std::tm &,
              spdlog::memory_buf_t &dest) override {
    char yi_log_level_text[9] = {0};
    if (msg.level == spdlog::level::level_enum::trace) {
      strcpy(yi_log_level_text, "TRACE");
    } else if (msg.level == spdlog::level::level_enum::debug) {
      strcpy(yi_log_level_text, "DEBUG");
    } else if (msg.level == spdlog::level::level_enum::warn) {
      strcpy(yi_log_level_text, "WARNING");
    } else if (msg.level == spdlog::level::level_enum::err) {
      strcpy(yi_log_level_text, "ERROR");
    } else if (msg.level == spdlog::level::level_enum::critical) {
      strcpy(yi_log_level_text, "CRITICAL");
    } else {
      strcpy(yi_log_level_text, "INFO");
    }
    dest.append(yi_log_level_text,
                yi_log_level_text + strlen(yi_log_level_text));
  }

  unique_ptr<custom_flag_formatter> clone() const override {
    return spdlog::details::make_unique<my_formatter_flag>();
  }
};
```

**Comment by gabime** [comment]
This is  not the way to achieve this. See https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#extending-spdlog-with-your-own-flags on how to customize flags.

**Comment by y-intercept2018** [comment]
> This is not the way to achieve this. See https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#extending-spdlog-with-your-own-flags on how to customize flags.

@gabime after reading the doc again, I come up with my class, does it look acceptable?

**Comment by gabime** [comment]
Should be optimized. Maybe call directly for each switch case `dest.append(“ERROR”, strlen “ERROR”)`, `dest.append(“INFO”, strlen “INFO”)`, `dest.append(“DEBUG”, strlen “DEBUG”)` ,etc.

**Comment by y-intercept2018** [comment]
Hi @gabime ,

I read through the wiki and find this:

```
///////////////////////////////////////////////////////////////////////////////
// Uncomment to customize level names (e.g. "MT TRACE")
//
// #define SPDLOG_LEVEL_NAMES { "MY TRACE", "MY DEBUG", "MY INFO", "MY WARNING",
// "MY ERROR", "MY CRITICAL", "OFF" }
///////////////////////////////////////////////////////////////////////////////
```

from https://github.com/gabime/spdlog/wiki/8.-Tweaking

Is this an even better approach?

**Comment by gabime** [comment]
Only if you are willing to compile your own version of spdlog with this setting.

**Comment by y-intercept2018** [comment]
Do you mean any changes to `tweakme.h` will only be effective if I stop using package manager's header+so files and compile the entire spdlog project myself?
