### ISSUE TITLE
Replace certain characters

### ISSUE THREAD

**Issue by hunnorth** [gabime/spdlog#2857]
Hello, 

Do you guys have any way to configure the logger to replace certain characters?
For example, I would like to configure all uses of "\n" to get interpreted as "\r". Therefore,
```
spdlog::info("Hello world\n"); 
```
gets printed as,
```
spdlog::info("Hello world\r"); 
```
Thanks

**Comment by gabime** [comment]
The pattern formatter constructor allows setting a custom eol    https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/pattern_formatter.h#L82
So you can create it and pass it to the logger using set_formatter()

**Comment by hunnorth** [comment]
Is it compatible with character's mid-string?

**Comment by gabime** [comment]
This just customizing the log line terminator.
