### ISSUE TITLE
logger->set_pattern() 格式化打印问题

### ISSUE THREAD

**Issue by 18871434218** [gabime/spdlog#2865]
m_logger = spdlog::stdout_logger_mt("logger");
m_logger->set_pattern("%Y-%m-%d %H:%M:%S.%e [%s %!:%#] %v");
为啥这样设置之后，  其他模块调用，却打印不出调用方的模块名，函数名、代码函数呢

**Comment by tt4g** [comment]
Duplicate #2725

See also #2712

**Comment by 18871434218** [comment]
只能在首行定义    #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG， 然后通过
                 SPDLOG_LOGGER_INFO(logger日志器, "message");  或者调用  SPDLOG_INFO(message) 这种方式嘛？

**Comment by tt4g** [comment]
I don't understand your question, please write it in English.

**Comment by zhin2929** [comment]
> 只能在首行定义 #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG， 然后通过 SPDLOG_LOGGER_INFO(logger日志器, "message"); 或者调用 SPDLOG_INFO(message) 这种方式嘛？

yes

**Comment by Bob2019-li** [comment]
https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#customizing-format-using-set_pattern

目前大概就是这么用吧(That's probably how it works at the moment)
