### ISSUE TITLE
How to find the definition of the test module

### ISSUE THREAD

**Issue by yirenzhi** [gabime/spdlog#2868]
test模块的定义在哪里
![image](https://github.com/gabime/spdlog/assets/8629115/8f8fb189-047d-446a-bb5c-8d8239b967be)
在vscode中如何才能正确的找到定义的地方

Where is the definition of the test module

How to find the correct definition in vscode

**Comment by tt4g** [comment]
Questions must be written in English. We cannot read it.

**Comment by yirenzhi** [comment]
ok,the last two line is my questions.

Where is the definition of the test module
![image](https://github.com/gabime/spdlog/assets/8629115/aead7b48-d6ec-4e24-9b4a-b73df48ef210)

How to find the correct definition in vscode

I just want to know where TEST_CASE  define in test module.

**Comment by tt4g** [comment]
spdlog project is managed by [CMake](https://cmake.org/) and using testing framework [Catch2](https://github.com/catchorg/Catch2).

Don't ask me here how to load a CMake project in Visual Studio Code.
[The official documentation is available](https://code.visualstudio.com/docs/cpp/cmake-linux) and there is [an extension to load CMake projects](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools), so please ask questions there.

To load Catch2, install it on your machine or save the Catch2 source code in a location that can be found with `find_package()` (https://cmake.org/cmake/help/latest/command/find_package.html).

https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/tests/CMakeLists.txt#L16

**Comment by yirenzhi** [comment]
Thanks for the reply, I got my answer Catch2.
