### ISSUE TITLE
Conflict with fmt

### ISSUE THREAD

**Issue by maths644311798** [gabime/spdlog#2872]
#include <iostream>
#include <string>
#include "spdlog/fmt/bundled/format.h"
#include "fmt/ostream.h"

int main() {
        printf("OK");
            return 0;
}

This code can not be compiled. The errors are 

/usr/local/include/fmt/ostream.h:158:1: error: 'FMT_EXPORT' does not name a type
  158 | FMT_EXPORT template <typename Char>
      | ^~~~~~~~~~
/usr/local/include/fmt/ostream.h:177:1: error: 'FMT_EXPORT' does not name a type
  177 | FMT_EXPORT template <typename... T>
      | ^~~~~~~~~~
/usr/local/include/fmt/ostream.h:186:1: error: 'FMT_EXPORT' does not name a type
  186 | FMT_EXPORT
      | ^~~~~~~~~~
/usr/local/include/fmt/ostream.h:194:1: error: 'FMT_EXPORT' does not name a type
  194 | FMT_EXPORT template <typename... T>
      | ^~~~~~~~~~
/usr/local/include/fmt/ostream.h:199:1: error: 'FMT_EXPORT' does not name a type

**Comment by tt4g** [comment]
Since it is not an fmt bundled with spdlog, spdlog appears to be irrelevant.

**Comment by tt4g** [comment]
Do not include headers from the same library in multiple locations.
That is your mistake.

```
#include "spdlog/fmt/bundled/format.h"
#include "fmt/ostream.h"
```

**Comment by maths644311798** [comment]
What if I need to use both spdlog and fmt/ostream.h?

**Comment by tt4g** [comment]
Use `#include include/spdlog/fmt/ostr.h`.
