### ISSUE TITLE
using spdlog from a dll file

### ISSUE THREAD

**Issue by 0LGL0** [gabime/spdlog#2875]
Why is it that when I try to use spdlog from my DLL, the compiler writes that it cannot find the "fmt" function?

 For example: 
" error LNK2019: "__declspec(dllimport) void __cdecl fmt::v10::detail::assert_fail(char const *,int,char const *)" (__imp_?assert_fail@detail@v10@fmt@@YAXPEBDH0@Z) в функции "struct fmt::v10::detail::format_decimal_result<char *> __cdecl fmt::v10::detail::format_decimal<char,unsigned int>(char *,unsigned int,int)" (??$format_decimal@DI@detail@v10@fmt@@YA?AU?$format_decimal_result@PEAD@012@PEADIH@Z)."

**Comment by tt4g** [comment]
This is because we are using spdlog built with a configuration that uses an external fmt. You must link the fmt referenced at build time.

**Comment by 0LGL0** [comment]
@tt4g, that is, I just need to link my program to fmt. In my case, since I use CMake, then I need to do it through it. Right?

**Comment by tt4g** [comment]
Right.
However, if `SPDLOG_FMT_EXTERNAL=ON` is not set, spdlog uses the bundled fmt.

https://github.com/gabime/spdlog/blob/3aceda041b2bfbccaf14d5c83eda16fc67bea364/CMakeLists.txt#L91-L92

In this case, external fmt is used because `SPDLOG_FMT_EXTERNAL=ON` is defined.

**Comment by 0LGL0** [comment]
@tt4g, Thanks

**Comment by 0LGL0** [comment]
@tt4g, By the way, just as I understand, the loggers for the dll file and other files (for example, exe) are not related to each other. Therefore, it will not work to call the registrar from the exe file in the dll file. But what if my functions for writing messages are wrapped in macros, and they, in turn, are in the header file, which I call from the dll, in which I want to use the same logger located in this header file? 

In short, straight to the point. Even with this method, I get an exception in the "std::atomic::load" function. Something like this: "Exception thrown: read access violation.
**_Mem** was 0x50." 

Here is the call stack:
"	GameWindow.dll!std::_Atomic_storage<int,4>::load(const std::memory_order _Order) Line 923	C++
 	GameWindow.dll!spdlog::logger::should_log(spdlog::level::level_enum msg_level) Line 303	C++
 	GameWindow.dll!spdlog::logger::log(spdlog::source_loc loc, spdlog::level::level_enum lvl, fmt::v10::basic_string_view<char> msg) Line 127	C++
 	GameWindow.dll!spdlog::logger::log<char [44]>(spdlog::level::level_enum lvl, const char[44] & msg) Line 103	C++
 	GameWindow.dll!spdlog::logger::error<char [44]>(const char[44] & msg) Line 292	C++
 	GameWindow.dll!GameWindow::init(const HKCR::WindowProps & props) Line 27	C++
 	Hyko_Engine.exe!main() Line 31	C++
 	[External Code]	
"

**Comment by gabime** [comment]
see https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

**Comment by 0LGL0** [comment]
@gabime, thanks
