### ISSUE TITLE
MSVS internal compiler error

### ISSUE THREAD

**Issue by xumepoc** [gabime/spdlog#2881]
I just update my MSVS to 17.7.4 and I get internal compiler error. 
According to MSVS the error comes from line 39 in ostream.h => (using result = decltype(test<T>(0));)

`
template <typename T, typename Char, typename Enable = void>
class is_streamable {
private:
    template <typename U>
    static auto test(int)
        -> bool_constant<sizeof(std::declval<std::basic_ostream<Char>&>()
            << std::declval<U>()) != 0>;

    template <typename> static auto test(...) -> std::false_type;

    using result = decltype(test<T>(0));

public:
    is_streamable() = default;

    static const bool value = result::value;
};
`
Has anyone seen this? I couldn't find similar report in the issues section. 

P.S. I am not sure why the formatting is wrong, i used Add code 🤷

**Comment by tt4g** [comment]
That is fmt library source. Please reopen this issue in [fmt project](https://github.com/fmtlib/fmt).
