### ISSUE TITLE
ringbuffer_sink is not working with asynchronous logger

### ISSUE THREAD

**Issue by suri-log** [gabime/spdlog#2885]
hi team,
 i am trying attach ringbuffer_sink to the existing stdoutlogger and get the messages from ring buffer sink.
 but with below code i see  some problem having ringbuffer sink where  async logger logs messages to stdout , but ringbuffer sink dont have any messages, andsame code works fine and  logger without async  logs on both stdout and ringbuffer.

i have experimented with both ringbuffer_sink_mt and ringbuffer_sink_st, . but the same works with normal logger.

 logger without async config:
       target = std::make_shared<spdlog::logger>(logger_ident, sink.begin(), sink.end());
       target->set_pattern("[%Y-%m-%d %H:%M:%S.%e]  [%l] %v");

async logger config:
  if (!spdlog::thread_pool()){
        spdlog::init_thread_pool(1024,1 );
    }
    target = std::make_shared<spdlog::async_logger>(logger_ident, sink.begin(), sink.end(), spdlog::thread_pool());
    target->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%t] %v");

void startRingbuff(){
auto ringBufferSink = std::make_sharedspdlog::sinks::ringbuffer_sink_mt(100);
logging_target->sinks().push_back(ringBufferSink);
}
getRingbuffMessages(std::vectorstd::string &kmsg,const int &ksize){
std::vectorstd::string last_messages;
auto ringbuffer_sink = std::dynamic_pointer_castspdlog::sinks::ringbuffer_sink_mt(logging_target->sinks().back());

    if (ringbuffer_sink) {
                std::cout <<"ring buff sink found" << std::endl;

            std::vector<std::string> messages;
            messages=ringbuffer_sink->last_formatted();
            for (const auto& message : messages) {
                std::cout <<"loop" <<message << std::endl;
            }

**Comment by tt4g** [comment]
The code is not formatted so I don't know what it is written.
Use code blocks for formatting: https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

`````markdown
```
int main (int argc, char *argv[])
{
    return 0;
}
```
`````

In any case, if it doesn't work with the async logger, it is probably because the ring_buffer_sink is being accessed before the message arrives.
Try `sleep(1)` to see if it works.

**Comment by suri-log** [comment]
yes it worked as expected after having sleep .. thanks
