### ISSUE TITLE
Why not prohibit the 'pop_front()' behaviour when circular queue is empty?

### ISSUE THREAD

**Issue by aiyolo** [gabime/spdlog#2886]
I think keeping queue empty when doing a pop_front() action on a empty queue is much better than making this an undefined behaviour, can you explain this design?

https://github.com/gabime/spdlog/blob/91807c2e718890ca2c0c88620326c6919ce041f4/include/spdlog/details/circular_q.h#L76C33-L85C33

**Comment by gabime** [comment]
This follows the standard std::list [behaviour](https://cplusplus.com/reference/list/list/pop_front/).  Code must check the size before using. 
If it is good enough for the standard it is good enough for spdlog.
