### ISSUE TITLE
Opinion: A better approach to categories of messages

### ISSUE THREAD

**Issue by gamagan** [gabime/spdlog#2889]
Hi,

I'm guessing that logging levels are too baked into the library for that design to change, so I'm not actually expecting for this post to be actionable.  It's just that I think logging levels is the wrong way to do logging, and I want to say something about a better design.

With the traditional log-levels, there are (at least) 3 problems:
1. The log-level categories are too coarse. They only give you a general category of the log entry.
2. Higher log-levels subsume lower log levels. Sometimes that's good, and sometimes it's not.
3. The amount of categories can be limiting.

A better approach to log categories is to allow the users to define their own, and then to
associate each log entry with 1 of those categories. To make the categories user definable 
but performant, each category is a bit in a uint32/uint64. Assuming that uint64 is chosen,
this would allow 64 different categories for log messages.

Spdlog would define an enum with generic category names, such as:
```cpp
enum class Cat : uint64_t {
    C1 = 1 << 0,
    C2 = 1 << 1,
    ...
    C64 = 1 << 63,
};
```

Then, when logging the message, a category would also be given.
The category is an int with exactly 1 of the bits on.
```cpp
auto msg = GetMyNetworkMsg();
splog::log(spdlog::Cat::C9, msg);
```

The idea being that the user would do something like this:

```cpp
constexpr auto kGuiLog          = spdlog::Cat::C3;
constexpr auto kNetPacketsLog   = spdlog::Cat::C9;
constexpr auto kNetHttpLog      = spdlog::Cat::C10;
constexpr auto kTraceNormalLog  = spdlog::Cat::21;
constexpr auto kTraceVerboseLog = spdlog::Cat::22;

#define LOG_GUI(...) spdlog::log(kGuiLog, ## __VA_ARGS__);
#define LOG_NET_PKG(...) spdlog::log(kNetPacketsLog, ## __VA_ARGS__);
#define LOG_NET_HTTP(...) spdlog::log(kNetHttpLog, ## __VA_ARGS__);
#define LOG_TRACE_NORMAL(...) spdlog::log(kTraceNormalLog, ## __VA_ARGS__);
#define LOG_TRACE_VERBOSE(...) spdlog::log(kTraceVerboseLog, ## __VA_ARGS__);
```

We could tell spdlog the specific category of messages we want to display.
If we only want to see logs related to network ip packets, we could do:

```cpp
spdlog::display(kNetPacketsLog);
```

Or, we want to see traces and gui:

```cpp
auto types = kTraceNormalLog | kTraceVerboseLog | kGuiLog;
spdlog::display(types);
```

Or, maybe we want to see everything:

```cpp
spdlog::display(~0);
```

The point is that this type of categorization would be:
1. Performant enough
2. As coarse or as granular as user wants
3. The user is in charge of their categories, as opposed to them being fixed
4. There can be lots (32/64) of categories, instead of a few.
5. Ability to chose any combination of categories to show, as opposed to getting lower categories when wanting to view higher ones.

For programs that produce lots of logging, the ability to filter the output to exactly the right category is more than just a little useful.

Regards
End of transmission

**Comment by gabime** [comment]
Thanks for the suggestion. 
I don't mixing between log severity, "error, info, etc." and log category ("http", "networking", etc) is a good idea. Those are 2 distinct concepts.
To have a category, just create a new logger with the category name, e.g  `net_logger = spdlog::logger("networking")`.

A logger is just a thin wrapper around sinks, with a name and level, so you can create as many of them as you need. 
This approach also  allows using different sinks for different categories or sharing sinks across categories if needed.
