### ISSUE TITLE
Unable to set SPDLOG_LEVEL_NAMES with `cmake` when using library build?

### ISSUE THREAD

**Issue by joshmtlau** [gabime/spdlog#2890]
Hello there. I'm having trouble setting `SPDLOG_LEVEL_NAMES` with `cmake` when using library build. 
I've tried a few different approaches but haven't had any luck.
The following doesn't work because the library build has already been compiled using the original definition of `SPDLOG_LEVEL_NAMES`:
```
// in my headers
#define SPDLOG_LEVEL_NAMES {"MY_TRACE", "MY_DEBUG, /*etc. */}
#include <spdlog/spdlog.h>
```

Also, From the discussion in #1263, it seems to be frowned upon to modify `tweakme.h` if using `cmake`.

I also tried to add the definition in `CMakeList.txt`. The problem is that `SPDLOG_LEVEL_NAMES` is an initializer list. And, to my knowledge, there isn't a way to add a definition of initializer lists in `cmake` directly.

Separately setting `SPDLOG_LEVEL_NAME_TRACE`, `SPDLOG_LEVEL_NAME_DEBUG`, etc., don't work because these level-specific `#define`s are not guarded by `#ifndef`s. 

Does anyone have any suggestions or workarounds for this issue? Thanks in advance for any help!

**Comment by tt4g** [comment]
> The following doesn't work because the library build has already been compiled using the original definition of `SPDLOG_LEVEL_NAMES`:

Since no error messages are provided, it is difficult to give proper advice.

At least it looks like the problem is not using `spdlog::string_view_t`.

https://github.com/gabime/spdlog/blob/91807c2e718890ca2c0c88620326c6919ce041f4/include/spdlog/common.h#L247-L262

And I don't understand why you can't define macros in CMake. If `"` is the problem, then you should be able to escape it with `\`.

**Comment by joshmtlau** [comment]
Thanks for the timely help! 
> And I don't understand why you can't define macros in CMake. If " is the problem, then you should be able to escape it with \.

Thanks for pointing me in the right direction. I misunderstood the syntax rules for `add_definitions` and thought I should quote the whole string since I added a definition with spaces. That has caused me to fail to add the definition. To be more specific, I used something like
```cmake
add_definitions(-DSPDLOG_LEVEL_NAMES="{\"my trace\", \"my debug\", \"my info\", \"my warn\", \"my err\", \"my critical\", \"my off\"}")
```
It turns out the outermost pair of double quotes is implicitly escaped in `cmake`, and is not treated like the double quotes in `c++` and shells.

For anyone who might be reading this in the future, I ended up using something like the following:
```cmake
add_definitions(-DSPDLOG_LEVEL_NAMES={\"my\ trace\",\"my\ debug\",\"my\ info\",\"my\ warn\",\"my\ err\",\"my\ critical\",\"my\ off\"})
```
i.e., removing the outermost pair of double quotes and escaping spaces.

Thanks again, and please feel free to close this issue if deemed appropriate.

**Comment by tt4g** [comment]
Yes, CMake considers a variable to be a list if it has spaces in it.
Spaces must also be escaped and should be used as little as possible.

**Comment by thisRedH** [comment]
For anyone stumbling over this issue, like i did: 

If you encounter an error similar to this, with the above method,
```
error: call to non-'constexpr' function 'fmt::v11::basic_string_view<Char>: basic_string_view(const Char*) [with Char = char]'
spdlog/include/spdlog/common-inl.h:19:47: note: in expansion of macro 'SPDLOG_LEVEL_NAMES'
   19 |     static string_view_t level_string_views[] SPDLOG_LEVEL_NAMES;
      |                                               ^~~~~~~~~~~~~~~~~~
```
then i would recommend something like this, which worked for me:
```cmake
add_subdirectory("path/to/spdlog")
target_link_libraries(foo PRIVATE spdlog::spdlog)

string(CONCAT SPDLOG_LEVEL_NAMES "{"
    "spdlog::string_view_t(\"TRACE\",5), spdlog::string_view_t(\"DEBUG\",5),"
    "spdlog::string_view_t(\"INFO\",4),  spdlog::string_view_t(\"WARN\",4),"
    "spdlog::string_view_t(\"ERROR\",5), spdlog::string_view_t(\"FATAL\",5),"
    "spdlog::string_view_t(\"OFF\",3)}"
)
get_target_property(SPDLOG_TARGET spdlog::spdlog ALIASED_TARGET)
target_compile_definitions(${SPDLOG_TARGET} PRIVATE SPDLOG_LEVEL_NAMES=${SPDLOG_LEVEL_NAMES})
```
