### ISSUE TITLE
Linux系统下，不安装该库，如何使用？

### ISSUE THREAD

**Issue by ghost** [gabime/spdlog#2898]
编译为静态库，不安装到系统目录下面，直接放在工程中使用，如何处理？

**Comment by tt4g** [comment]
Use English here. Contributors use English.

**Comment by tt4g** [comment]
> 编译为静态库，不安装到系统目录下面，直接放在工程中使用，如何处理？

DeepL: How to compile it as a static library and use it directly in the project without installing it under the system directory?

**Comment by tt4g** [comment]
spdlog is a header-only library and does not need to be installed.
Please import the header files into your project.

**Comment by ghost** [comment]
thanks

**Comment by gabime** [comment]
Note it is recommended to use the compiled version of spdlog instead of header only. Otherwise your compilation would be slow.
