### ISSUE TITLE
Get the log output configuration from the configuration file？

### ISSUE THREAD

**Issue by ghost** [gabime/spdlog#2903]
Is there such an interface: an interface that can get log output information from a configuration file, e.g., a configuration file configured with log levels, number of log backups, etc.? The ultimate goal is to modify the configuration file, without restarting the program, to update the status of the program output log in real time.

**Comment by tt4g** [comment]
The configuration file is not supported.
But you can use [spdlog_setup](https://github.com/guangie88/spdlog_setup)
