### ISSUE TITLE
How to achieve low latency log in async mode ?!

### ISSUE THREAD

**Issue by Hedgezzz** [gabime/spdlog#291]
I have the following test in Linux 3.10.0 , x86_64 ,  it look strange that spdlog async mode is 
much slower than  fprint  , May I ask what I do is wrong ?!

#include "/home/test/spdlog/spdlog-master/include/spdlog/spdlog.h"
namespace spd = spdlog;
std::shared_ptr<spdlog::logger> _logger ;
std::shared_ptr<spdlog::logger> console ;

Main :

    char filename[128]={0} ;
    sprintf(filename,"/home/test/priority/y.log");
    logfp = fopen(filename,"a+");
    fflush(logfp) ;

    int q_size = 2048 ;
    spdlog::set_async_mode(q_size,spdlog::async_overflow_policy::discard_log_msg);
    console = spd::stdout_logger_mt("console");

    spdlog::set_pattern("[%T][%l] %v");
    char filenm[128]={0} ;
    sprintf(filenm,"%s_%s","logs/log","x");
    auto file_logger = spd::rotating_logger_mt("file_logger",filenm , 1048576 * 5, 5);
    _logger = spdlog::get("file_logger");

    while( 1 ){
        sleep( 1 ) ;
        struct timeval  tv;
        gettimeofday(&tv, NULL);
        sem_post(&semOrder) ;
        printf("1......(%d)...(%d) \n",tv.tv_sec,tv.tv_usec) ;
    }

Thread1 : 

    char recvmsg[128]={0} ;
    strcpy( recvmsg , "hello world") ;
    std::string s(recvmsg) ;
    while( 1 ){
        sem_wait(&semOrder) ;

        for(int idx=0;idx<50;idx++){
            //fprintf(logfp,"recieve(%s)\n") ;
            _logger->info("recieve({})",recvmsg);
        }

        struct timeval  tv;
        gettimeofday(&tv, NULL);
        printf("2......(%d)...(%d) \n\n",tv.tv_sec,tv.tv_usec) ;
    } //while

The spdlog->info   do 50 times in this test cost  45 microseconds ,  fprintf  in this  test costs 6 microseconds ,  I think there should be something I do wrong ,  my compile is  4.8.3 ,

g++ --std=c++11 y.cpp   -I/home/test/spdlog/spdlog-master/include -pthread -o y.exe

What should I do to make spdlog async mode  do faster  ?!

**Comment by gabime** [comment]
* The -O2 flag should help.
* Seems you forgot to pass to  fprintf the recvmsg param.
* The fprintf test is **not** using datetime, not thread id, nor logger name, so for a better compare you need to define (before including spdlog.h):

   ```c++
 #define SPDLOG_NO_DATETIME
#define SPDLOG_NO_NAME
#define SPDLOG_NO_THREAD_ID
```
and use ``spdlog::set_pattern("%v"); ```



* Please post a full working example (I don't fully understand what is going on in this code or how it calculates the timings)

**Comment by Hedgezzz** [comment]
#include <sys/inotify.h>
    #include <limits.h>
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <math.h>
    #include <time.h>
    #include <sys/timeb.h>
    #include <unistd.h>
    #include <fcntl.h>
    #include <sys/uio.h>
    #include <sys/signal.h>
    #include <sys/types.h>
    #include <sys/file.h>
    #include <sys/socket.h>
    #include <sys/mman.h>
    #include <netinet/in.h>
    #include <arpa/inet.h>
    #include <ctype.h>
    #include <semaphore.h>
    #include <netinet/tcp.h>
    #include <sys/un.h>
    #include <pthread.h>
    #include <cstdio>
    #include <iostream>
    #include <iterator>
    #include <string>
    #include <fstream>
    #include <iostream>
    #include <unordered_map>
    #include <string>
    #include <time.h>
    #include <sys/timeb.h>
    #include <sys/time.h>
    #include <sys/stat.h>
    #include <sys/syscall.h>
    #include <sched.h>

#define SPDLOG_NO_DATETIME
#define SPDLOG_NO_NAME
#define SPDLOG_NO_THREAD_ID

#include "/home/informix/test/spdlog/spdlog-master/include/spdlog/spdlog.h"

namespace spd = spdlog;
std::shared_ptr<spdlog::logger> _logger ;

sem_t semOrder ;
FILE   *logfp ;

void *Thread1(void *param)
{

    long ithread = (long) param ;
    pthread_detach(pthread_self());
    int icnt = 0 ;
    char recvmsg[128]={0} ;
    strcpy( recvmsg , "hello world") ;
    std::string s(recvmsg) ;
    while( 1 ){
        sem_wait(&semOrder) ;

        for(int idx=0;idx<50;idx++){
            //fprintf(logfp,"recieve(%s)\n",recvmsg) ;;
            _logger->info("recieve({})",recvmsg);
        }

        struct timeval  tv;
        gettimeofday(&tv, NULL);
        printf("2......(%d)...(%d) \n\n",tv.tv_sec,tv.tv_usec) ;
    } //while
    printf("thread out \n ");
}

int main(int argc, char** argv)
{

    sem_init(&semOrder, 0, 0);
    char filename[128]={0} ;
    sprintf(filename,"/home/informix/test/priority/y.log");
    logfp = fopen(filename,"a+");
    fflush(logfp) ;

    int q_size = 2048 ;
    spdlog::set_async_mode(q_size,spdlog::async_overflow_policy::discard_log_msg);

    //spdlog::set_pattern("[%T][%l] %v");
    spdlog::set_pattern(" %v");
    char filenm[128]={0} ;
    sprintf(filenm,"%s_%s","logs/log","x");
    auto file_logger = spd::rotating_logger_mt("file_logger",filenm , 1048576 * 5, 5);
    _logger = spdlog::get("file_logger");

    pthread_t tid ;
    pthread_create(&tid , NULL, Thread1, (void*)(long)3);

    while( 1 ){
        sleep( 1 ) ;
        struct timeval  tv;
        gettimeofday(&tv, NULL);
        sem_post(&semOrder) ;
        printf("1......(%d)...(%d) \n",tv.tv_sec,tv.tv_usec) ;
    }
}

compiled by : 

g++ --std=c++11 -o2 y.cpp   -I/home/informix/test/spdlog/spdlog-master/include -pthread -o y.exe

run by  : 

sudo chrt -v -r 50 ./y.exe


with  _logger->info("recieve({})",recvmsg);   code in Thread1  , the output is  :   

1......(1475450042)...(689457) 
2......(1475450042)...(689501) 

1......(1475450043)...(689482) 
2......(1475450043)...(689521) 

1......(1475450044)...(689494) 
2......(1475450044)...(689530) 

1......(1475450045)...(689511) 
2......(1475450045)...(689549) 

1......(1475450046)...(689529) 
2......(1475450046)...(689565) 

1......(1475450047)...(689555) 
2......(1475450047)...(689593) 

1......(1475450048)...(689573) 
2......(1475450048)...(689608) 

with   fprintf(logfp,"recieve(%s)\n") ;  code in Thread1 , the output is :   

1......(1475450296)...(750824) 
2......(1475450296)...(750837) 

1......(1475450297)...(750848) 
2......(1475450297)...(750855) 

1......(1475450298)...(750860) 
2......(1475450298)...(750866) 

1......(1475450299)...(750877) 
2......(1475450299)...(750895) 

1......(1475450300)...(750895) 
2......(1475450300)...(750902) 

1......(1475450301)...(750917) 
2......(1475450301)...(750924) 

1......(1475450302)...(750936) 
2......(1475450302)...(750942)

I  like to know what  else can I do  for  spdlog to make this test case latency as close  as possible 
compare with fprintf  , spdlog async log  is excellent  job , still I need  it faster .

**Comment by Hedgezzz** [comment]
One more question :   if for some reason ,  as I know spdlog  is  a  header file library , 
is it possible that  spdlog  is  compiled as a  static library .a  or shared library .so  file ,
and then  my c++  application just link it  to run ?!

Why I ask is that currently my application compiled with -O2   will  get result not I expected , 
So I need a wrapper class of spdlog  which  compiled with -O2  and linked to my application ,
or spdlog.a  , spdlog.so  library compiled with -O2 that my application can link , 
In these 2 methods , my application will work fine  and spdlog async log works fast  as expected ,

**Comment by Hedgezzz** [comment]
in  logger_impl.h  , there is a  info function :  

    template <typename... Args>
    inline spdlog::details::line_logger spdlog::logger::info(const char* fmt, const Args&... args)
    {
        return _log_if_enabled(level::info, fmt, args...);
    }

and I try to  write my own wrapper function like  :  

    template <typename... Args>
    void doInfo(const char* fmt, const Args&... args) {
        _logger->info(fmt, args...);
    } //doTest


and  do the following cause core dump  :  

    int main(int argc, char** argv)
    {
         char recvmsg[128]={0} ;
        strcpy( recvmsg , "hello world") ;
        doInfo("recieve({})",recvmsg);
    }

May I ask  implement a  wrapper function in this way is correct ?! anything I have missed ?!

**Comment by Hedgezzz** [comment]
I have a Wrapper.cpp  :  

    #include <cstdio>
    #include <iostream>
    #include <iterator>
    #include <string>
    #include <fstream>
    #include <iostream>
    #include "Wrapper.h"

    #include "/home/informix/test/spdlog/spdlog-master/include/spdlog/spdlog.h"

    namespace spd = spdlog;
    extern std::shared_ptr<spdlog::logger> _logger ;

    template <typename... Args>
    void doInfo(const char* fmt, const Args&... args) {
        _logger->info(fmt, args...);
    } //doInfo

And a Wrapper.h :   

    #include <cstdio>
    #include <iostream>
    #include <iterator>
    #include <string>
    #include <fstream>
    #include <iostream>

    template <typename... Args>
    void doInfo(const char* fmt, const Args&... args) ;

then  compiled it in g++ 4.8.3  by 

    g++ --std=c++11 -O3  -c Wrapper.cpp

Then I have the Wrapper.o  ,  I  have the following  test.cpp    :   

    #include "Wrapper.h"

    #include "/home/informix/test/spdlog/spdlog-master/include/spdlog/spdlog.h"
    namespace spd = spdlog;
    std::shared_ptr<spdlog::logger> _logger ;
    int main(int argc, char** argv)
    {
        int q_size = 2048 ;
        spdlog::set_async_mode(q_size,spdlog::async_overflow_policy::discard_log_msg);

        spdlog::set_pattern(" %v");
        char filenm[128]={0} ;
        sprintf(filenm,"%s_%s","logs/log","x");
        auto file_logger = spd::rotating_logger_mt("file_logger",filenm , 1048576 * 5, 5);
        _logger = spdlog::get("file_logger");

        char recvmsg[128]={0} ;
        strcpy( recvmsg,"hello world" );
        doInfo("receive({})",recvmsg) ;
    }

compiled by  :   

    g++ --std=c++11  test.cpp  Wrapper.o  -I/home/informix/test/spdlog/spdlog-master/include -pthread -o test.exe

      undefined reference to `void doInfo<char [128]>(char const*, char const (&) [128])'

How should I modify my header file to make the compile/link works ?!

**Comment by gabime** [comment]
http://stackoverflow.com/q/115703 should help

**Comment by Hedgezzz** [comment]
@gabime  , thanks ,  those samples are for template class , my case is template function with 

    template <typename... Args>  

va_list  things , make it even hard to do it right  ,  I have try it  hours ,  what a chanllenge !

**Comment by gabime** [comment]
If I were you I would waste those hours to fix your original problem - not being able to use -O2 on your code

**Comment by Hedgezzz** [comment]
@gabime  , that is what I am doing ... thanks for your kindly help .
