### ISSUE TITLE
CodeQL issues

### ISSUE THREAD

**Issue by jwinarske** [gabime/spdlog#2910]
I have CodeQL enabled in my repo, and 99% of the reported issues are from spdlog.

It's free to enable.  Are you open to a PR?

99% are spdlog:
https://github.com/toyota-connected/ivi-homescreen/security/code-scanning?query=is%3Aopen+branch%3Amain

**Comment by gabime** [comment]
Not sure what you mean. Please provide details.

**Comment by jwinarske** [comment]
It's a free linter run by GitHub:  https://codeql.github.com/

My CI job:
https://github.com/toyota-connected/ivi-homescreen/blob/main/.github/workflows/oss-codeql.yml

**Comment by gabime** [comment]
Yes but where is the report? the op link is broken

**Comment by jwinarske** [comment]
I think it's an access issue.  A few screen shots

**Comment by jwinarske** [comment]
I'll post some screen shots in a bit

**Comment by jwinarske** [comment]
Three screen shots:
https://drive.google.com/drive/folders/1PdLfIIFHLuYLNj1e8Sa_yozSFY5M4rdz?usp=sharing

There are many warnings, most are benign.

**Comment by gabime** [comment]
Thanks. Note that some of those warnings belong to 3rd party fmt lib and need to be handled in the fmt repo.
Other than that, PRs are always  welcome.
