### ISSUE TITLE
sodlog Cann't support log path has emoji

### ISSUE THREAD

**Issue by zhaosky** [gabime/spdlog#2911]
configure：win11 X64
If the log path has emoji,the sodlog triggers an exception.
log path is "logs🙂/daily.log"
ex.msg_ is "Failed opening file logs??/daily_2023-10-19.log for writing: invalid argument"

**Comment by tt4g** [comment]
spdlog creates directories by the Windows API `_mkdir()` (https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mkdir-wmkdir?view=msvc-170).

https://github.com/gabime/spdlog/blob/ff205fd29a4a2f6ebcbecffd149153256d89a671/include/spdlog/details/os-inl.h#L505-L515

Can you create the directory with `mkdir("logs🙂")`?
If it fails, then this is a bug in the Windows API.

**Comment by tt4g** [comment]
On my machine the following code returns success, but the directory name that was created had broken emoji.

```c++
#include <iostream>
#include <direct.h>
#include <errno.h>

int main(void)
{
    errno = 0;
    auto result = _mkdir("logs🙂");
    auto eno = errno;

    std::cout << "result: " << result << std::endl;
    std::cout << "errno: " << eno << std::endl;

    return 0;
}
```

```bash
$ foo.exe     
result: 0
eno: 0
$ dir
2023/10/19  22:32            59,392 foo.exe
2023/10/19  22:32    <DIR>          logs凾
2023/10/19  22:32               271 main.cpp
```

Please submit a PR if you know how to create a directory containing emoji with the C/C++ API.

**Comment by tt4g** [comment]
I could not find a clear specification for this behavior.
Perhaps the Win32 `char*` API cannot process surrogate pairs.

You can define the `SPDLOG_WCHAR_FILENAMES` macro to pass `wchar_t*` to the log filename, but I am not sure if it can process emoji.

https://github.com/gabime/spdlog/blob/ff205fd29a4a2f6ebcbecffd149153256d89a671/include/spdlog/tweakme.h#L56-L60

**Comment by zhaosky** [comment]
> e `SPDLOG_WCHAR_FILENAMES` macro to pass `wchar_t*` to the log filename, but I am not sure if it can process emoji.
> 
> [spdlog/include/spdlog/tweakme.h](https://github.com/gabime/spdlog/blob/ff205fd29a4a2f6ebcbecffd149153256d89a671/include/spdlog/tweakme.h#L56-L60)

OK，thanks for your detailed reply，I will try it. I used to use log4cxx and it works well. Yesterday I try to catch the expection and create a new folder without emoji to resove the problem.

**Comment by tt4g** [comment]
log4cxx fileappender created the directory by `log4cxx::File::mkdirs()`.

https://github.com/apache/logging-log4cxx/blob/794f55ec71b9fd88fa75b4275c8fda3ac7c479b6/src/main/cpp/fileappender.cpp#L315

https://github.com/apache/logging-log4cxx/blob/794f55ec71b9fd88fa75b4275c8fda3ac7c479b6/src/main/cpp/file.cpp#L332-L337

Directory creation is realized by calling `apr_dir_make_recursive()` defined in the Apache Portable Runtime Library (https://github.com/apache/apr).

`apr_dir_make_recursive()` converted UTF-8 `char*` to UTF-16 `wchar_t*` and then called `CreateDirectoryW()`.

https://github.com/apache/apr/blob/e93513f2d270f2154d69865a25ffa5f3f465e30a/file_io/os2/dir_make_recurse.c#L63-L90
https://github.com/apache/apr/blob/e93513f2d270f2154d69865a25ffa5f3f465e30a/file_io/win32/dir.c#L200-L215

Perhaps Windows cannot create directories containing emoji without using the UNICODE API.
