### ISSUE TITLE
Building spdlog with Visual Studio 17.8 fails

### ISSUE THREAD

**Issue by jaimecbernardo** [gabime/spdlog#2912]
Hi,

Currently still on Preview 4, Visual Studio 17.8 C++ STL deprecates the use of `checked_array_iterator` with this change: https://github.com/microsoft/STL/pull/3818

spdlog uses it here: https://github.com/gabime/spdlog/blob/ff205fd29a4a2f6ebcbecffd149153256d89a671/include/spdlog/fmt/bundled/format.h#L489-L490

This causes a build error due to the deprecation if warnings are treated as errors.

On PowerToys we use spdlog and are getting around this by adding the `_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING` definition, but this `stdext::checked_array_iterator` feature is expected to be removed entirely in the future. 
https://github.com/microsoft/PowerToys/pull/29303/files#diff-db47b6c13dd626082ddffbfd3e6d5c7087bfbd39e92c99f4b28a1561a1f19593

From my understanding, this is used in spdlog to work around one warning. With the changes in STL is this still needed?
If this code just comes from the fmt liv, I believe it's been dealt with already in https://github.com/fmtlib/fmt/issues/3540 and https://github.com/microsoft/vcpkg/pull/32652 .

Thanks, in advance.

**Comment by tt4g** [comment]
Yes, `spdlog/include/spdlog/fmt/bundled/format.h` copied from fmt repository.
You can external fmt library with CMake variable `SPDLOG_FMT_EXTERNAL=ON`.

https://github.com/gabime/spdlog/blob/ff205fd29a4a2f6ebcbecffd149153256d89a671/CMakeLists.txt#L91-L92

**Comment by MiKom** [comment]
Hey.

Using the bundled `fmt` library is very useful as using the own one requires additional setup. Is there some showstopper for including newer `fmt`? Or is it more a matter of no one yet getting to it? If it's the latter I may have some time to take a look at it.

**Comment by tt4g** [comment]
@MiKom Use external fmt if you want to use new features of fmt or if another library depends on a different version of fmt than spdlog.

**Comment by gabime** [comment]
Spdlog ver 1.x cant bundle new fmt versions without breaking backward compatibility. spdlog ver 2.x will use the latest fmt version soon. As @tt4g said, you can use easily different fmt version using the right macro.

**Comment by MiKom** [comment]
> @MiKom Use external fmt if you want to use new features of fmt or if another library depends on a different version of fmt than spdlog.

Yes, I know that. My question was different though. I was wondering if there's some showstopper for inclusion of the new fmt. And as @gabime pointed out, indeed there is for spdlog 1.x.

Now I understand the situation fully and can act accordingly. Thanks @gabime

**Comment by MiKom** [comment]
@tt4g 

~Sadly spdlog 1.x is not compatible with fmt 10.1.0 where it was fixed so using custom fmt won't help here.~

~Until spdlog 2.x is out, it's necessary to use define `_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING` for recent Visual Studio MSVC.~

This comment was incorrect. spdlog is compatible with fmt 10.x, you needs to use spdlog 1.12.0 or later though.

**Comment by tt4g** [comment]
@MiKom `_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING` macro is referenced by MSVC, so I believe it can be defined regardless of the fmt and spdlog versions.

**Comment by gabime** [comment]
> Sadly spdlog 1.x is not compatible with fmt 10.1.0

@MiKom Actually it is compatible with fmt 10.x. It just doesn't bundle it.

**Comment by MiKom** [comment]
@gabime You're right of course. My mistake was using spdlog 1.11.0 whereas the fix for fmt 10.x was done in 1.12.0. Thanks!
