### ISSUE TITLE
C7595 error with Visual Studio 2019 in C++20 mode on 2.x branch

### ISSUE THREAD

**Issue by bebuch** [gabime/spdlog#2913]
This is pretty much a bug in the MSVC compiler of VS 2019. (Is Visual C++ 19.29 / VS 2019 supported on the 2.x branch?)

> C:\Temp\spdlog\include\spdlog\source_loc.h(34): error C7595: 'std::source_location::current': call to immediate function is not a constant expression

With VS 2019 in C++17 and VS 2022 in C++20 mode it works fine.

```cmd
git clone https://github.com/gabime/spdlog
cd spdlog
git checkout v2.x
cd ..
mkdir spdlog-build
cd spdlog-build
```

Change `example/example.cpp` to:

```cpp
#define SPDLOG_SOURCE_LOCATION 1
#include "spdlog/spdlog.h"

int main() {
    spdlog::info("");
}
```

VC 2019 x64 cmd:

```cmd
cmake -GNinja -DCMAKE_CXX_STANDARD=20 ../spdlog
cmake --build .
```

Build error:

```
[1/2] Building CXX object example\CMakeFiles\example.dir\example.cpp.obj
FAILED: example/CMakeFiles/example.dir/example.cpp.obj
C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP  -IC:\Temp\spdlog\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /Zc:__cplusplus /MP /MDd /Zi /Ob0 /Od /RTC1 -std:c++latest /showIncludes /Foexample\CMakeFiles\example.dir\example.cpp.obj /Fdexample\CMakeFiles\example.dir\ /FS -c C:\Temp\spdlog\example\example.cpp
C:\Temp\spdlog\include\spdlog\source_loc.h(34): error C7595: 'std::source_location::current': call to immediate function is not a constant expression
ninja: build stopped: subcommand failed.
```

Version info:

```
c:\>cmake --version
cmake version 3.20.21032501-MSVC_2

c:\>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30152 for x64
```

**Comment by gabime** [comment]
Never tried on 2019, so I guess not supported until a fix available. PR is most welcome.

**Comment by bebuch** [comment]
I'm pretty sure MS won't make any more C++ fixes for VS 2019 unless they are security related. If I find a workaround, I will make a PR.

**Comment by bebuch** [comment]
I filed a [bug report to MS](https://developercommunity.visualstudio.com/t/MSVC-2019--VC-1929-Bug:-call-to-imme/10496818). Maybe we have luck. :-)

**Comment by bebuch** [comment]
MS has unfortunately decided against a patch.

I don't think a good workaround can be implemented. So `SPDLOG_SOURCE_LOCATION` cannot be supported for VS 2019.

Unless someone has a clever idea, you can close this Issue.

The compiler bug looks like this:

```cpp
consteval int a() {
    return 5;
}

int b(int = a()) { // error if called in default argument initialization
    return 42;
}

void c(int = b()){}

void f() {
    c();
}
```

`b` here is `std::source_location` and `c` is `source_loc`. In order not to trigger the compiler bug, one would have to replace `source_loc` completely by `std::source_location`. But this would be an API break and the standard interface would not be implementable without `std::source_location`. So it is not a viable solution.

BTW I am really looking forward to using the 2.x Branch! `spdlog` is a great library! :-)

**Comment by nigels-com** [comment]
Having just finishing migrating various VS2019 builds to C++20, _now_ we realise that we're blocked updating `spdlog`.
Oh well!

**Comment by bebuch** [comment]
As long as you disable SPDLOG_SOURCE_LOCATION you can use the 2.x Branch with VS 2019.

There are a lot of such critical bugs in 2019 and MS answers are mostly along the lines, "we don't care about an old version, please update to 2022." ("This would be a behavior change, it's not worth the risk.")
