### ISSUE TITLE
No stdout logging when piped out to more?

### ISSUE THREAD

**Issue by nosati-shtakor** [gabime/spdlog#2915]
When I use my command line application like:
`my_app` then I see stdout logging, but when I pipe to more like this:
`my_app | more`, then I get no ouput.

If I use multiple sinks (file and stdout), the file logging works as expected.

Btw, tried on Windows only so far.

Any suggestions?

**Comment by tt4g** [comment]
The output to `STDOUT` is the responsibility of spdlog, and the pipe not working is a Windows problem.

**Comment by nosati-shtakor** [comment]
Ok, thanks.
