### ISSUE TITLE
there problem are macro "mkdir" passed 2 arguments, but takes just 1 etc. when i compile my project

### ISSUE THREAD

**Issue by CodeDrawing** [gabime/spdlog#2916]
part of the error message:
/spdlog/include/spdlog/fmt/bundled/format.h:2383:78: error: inconsistent types 'int' and 'bool' deduced for lambda return type

spdlog/include/spdlog/fmt/bundled/format.h:2383:78: error: inconsistent types 'int' and 'bool' deduced for lambda return type
 2383 |            output_exp >= (fspecs.precision > 0 ? fspecs.precision : exp_upper)

spdlog/include/spdlog/fmt/bundled/format.h:2383:78: error: inconsistent types 'int' and 'bool' deduced for lambda return type
/tmp/tmp.ZqiSa8XMIW/app/port/tsPacket.cpp: In member function 'int tsPacket::packet_process()':
/tmp/tmp.ZqiSa8XMIW/app/port/tsPacket.cpp:416:25: warning: 'void av_init_packet(AVPacket*)' is deprecated [-Wdeprecated-declarations]
  416 |      av_init_packet(&pkt);
etc.

i use cmake to compile my project and already include the spdlog head file in CmakeList.txt

i ran the example test has success.

spdlog -> 1.12.0
ubuntu -> 20.04.4 LTS
cpu ->RK3588
cmake ->3.16.3

**Comment by tt4g** [comment]
I assume that the macros defined in your project are breaking the library.
We do not know the cause because it is a problem with your code.
