### ISSUE TITLE
spdlog won't build in multithread, static version of the run-time library usage mode

### ISSUE THREAD

**Issue by tetsuhaut** [gabime/spdlog#2917]
Hi and thanks for this great library,
Under Windows, I use spdlog as a library statically linked to my project, using the /MT flag (see https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170).
Until the spdlog version 1.9.1, I just had to change the /MD flag in the generated CMakeCache.txt file to /MT so that cmake builds spdlog as a library ready to be statically linked. Starting with the spdlog version 1.10.0, there is no more /MD flag in CMakeCache.txt. Moreover, if I add a /MT flag manually, the following warning message appears during the execution of cmake:
"D9025 overriding '/MT' with '/MD'" and the library won't link because it was generated with the /MD flag.

How could I fix that?

**Comment by tt4g** [comment]
Microsoft does not support mixing `/MT` and `/MD`.
Please build all projects with the same build option if you want to change the CRT libraries to be linked.

See: https://stackoverflow.com/questions/3469841/mixing-code-compiled-with-mt-and-md

**Comment by tetsuhaut** [comment]
ok, what I mean is that my project compiles with /MT. How do I make spdlog compile with /MT too?

**Comment by tt4g** [comment]
I do not know how you build spdlog.
CMake 3.15 and later versions set `CMAKE_MSVC_RUNTIME_LIBRARY` or `MSVC_RUNTIME_LIBRARY` (https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html).
Earlier versions replace the build flag manually.
See: https://stackoverflow.com/questions/14172856/compile-with-mt-instead-of-md-using-cmake

**Comment by tetsuhaut** [comment]
dear tt4g,
thanks for your answer. Here is the way I build spdlog:
```
cmake -G "Ninja" ^
  -D CMAKE_BUILD_TYPE=Debug ^
  -D SPDLOG_BUILD_SHARED=OFF ^
  -D SPDLOG_FMT_EXTERNAL=OFF ^
  -D SPDLOG_BUILD_EXAMPLE=OFF ^
  -D SPDLOG_BUILD_TESTS=OFF ^
  -D CMAKE_INSTALL_PREFIX=%BUILD_DIR%/install ^
%SRC_DIR%
ninja && ninja install
```
The stackoverflow answer you pointed me to supposes there is a /MD flag that could be changed to /MT. However

- the /MD flag is nowhere to be seen in spdlog source code

- if I add the /MT flag manually, the build process warns and still uses /MD

What could I do? Is there a way to specify that /MT flag somewhere?

**Comment by tt4g** [comment]
First of all, the C++ compiler has default compilation options, and `/MT` is included there.
It is not specified by spdlog.
How to switch between `/MT` and `/MT` has already been commented (set `CMAKE_MSVC_RUNTIME_LIBRARY`).

Additionally, you seem to want to specify `/MT`, but for debug builds you should specify the `/MTd` flag.
Find out what each flag means.

```diff
 cmake -G "Ninja" ^
   -D CMAKE_BUILD_TYPE=Debug ^
   -D SPDLOG_BUILD_SHARED=OFF ^
   -D SPDLOG_FMT_EXTERNAL=OFF ^
   -D SPDLOG_BUILD_EXAMPLE=OFF ^
   -D SPDLOG_BUILD_TESTS=OFF ^
   -D CMAKE_INSTALL_PREFIX=%BUILD_DIR%/install ^
+ -D CMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"
 %SRC_DIR%
 ninja && ninja install
```

**Comment by tetsuhaut** [comment]
Thank you so much tt4g, it works.
