### ISSUE TITLE
Struct bitfield Issue

### ISSUE THREAD

**Issue by adrian-yehe** [gabime/spdlog#2921]
define struct ,
union control {
    std::uint64_t value;
    struct bit_filed {
        std::uint64_t type: 2;
        std::uint64_t dilation_conv:1;
        std::uint64_t bias_en:1;
        std::uint64_t scale_en:1;
        std::uint64_t relue_en:1;
        std::uint64_t lrelu_en:1;
        std::uint64_t inpsum_en:1;
        std::uint64_t input_format:4;
        std::uint64_t output_fromat:4;
        std::uint64_t inpsum_format:4;
        std::uint64_t ne_cmd_valid: 1;
        std::uint64_t sparse_en:1;
       }
}
Show below message 
union control ctrl;
spdlog::info("type:{}", ctrl.bit.type);
but compile code ,occers error:
error: cannot bind bitfield ‘ ctrl.bit.type" to "long unsigned int &"

**Comment by tt4g** [comment]
Cast or define `fmt::formatter<T>` (https://fmt.dev/9.1.0/api.html).
