### ISSUE TITLE
Does syslog_logger_mt not support set_pattern?

### ISSUE THREAD

**Issue by khailifz** [gabime/spdlog#2928]
I changed syslog_example in the example code. After running it, I saw that set_pattern does not take effect. Is it not natively supported? Is there an indirect method?

`void syslog_example() {

    std::string ident = "test";
    // auto syslog_logger = spdlog::syslog_logger_mt("syslog", ident, LOG_PID);
    auto syslog_logger = spdlog::syslog_logger_mt("fangz__syslog", ident, LOG_PID);
    syslog_logger->warn("This is warning that will end up in syslog.");

    spdlog::set_level(spdlog::level::info);
    syslog_logger->set_pattern("[%H:%M:%S.%f %z] [%^%l%$] [thr %t] %v");

    spdlog::set_default_logger(syslog_logger);
    spdlog::info("starting up");
}`

**Comment by tt4g** [comment]
Set `enable_formatting` to `true`.

https://github.com/gabime/spdlog/blob/ddce42155e67589a8b1534c4935242f759c07646/include/spdlog/sinks/syslog_sink.h#L22-L23

```diff
-auto syslog_logger = spdlog::syslog_logger_mt("fangz__syslog", ident, LOG_PID);
+auto syslog_logger = spdlog::syslog_logger_mt("fangz__syslog", ident, LOG_PID, true);
```
