### ISSUE TITLE
SPDLOG_DEBUG does not write the log even if the level is debug

### ISSUE THREAD

**Issue by giulianoc** [gabime/spdlog#2934]
Hi,

let's explain my issue pasting here some code:

vector<spdlog::sink_ptr> sinks;

// 1. I have a rotating_file_sink having **debug** as log level 
auto rotatingSink = make_shared<spdlog::sinks::rotating_file_sink_mt> (logPathName.c_str(), maxSizeInKBytes * 1000, maxFiles);
sinks.push_back(rotatingSink);
rotatingSink->set_level(spdlog::level::debug);

// 2. I have another rotating_file_sink for the errors having err as log level 
auto errorRotatingSink = make_shared<spdlog::sinks::rotating_file_sink_mt> (logErrorPathName.c_str(), maxSizeInKBytes * 1000, maxFiles); 
sinks.push_back(errorRotatingSink);                                                           
errorRotatingSink->set_level(spdlog::level::err);  

// 3. I have a logger containing both the above sinks
auto logger = std::make_shared<spdlog::logger>("cms-import", begin(sinks), end(sinks));               
spdlog::register_logger(logger);
spdlog::set_default_logger(logger);
logger->flush_on(spdlog::level::trace);
logger->set_level(spdlog::level::debug);

// Next statement logs correctly in sink nr. 1
logger->debug("logger->debug");

// The ISSUE is that next statement, that it is the one I usually use, DOES NOT WRITE the log in sink nr. 1
SPDLOG_DEBUG("SPDLOG_DEBUG");

Which is the problem?

Best regards

**Comment by tt4g** [comment]
Missing `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE`.

Wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

**Comment by giulianoc** [comment]
sorry should I add the above define?

**Comment by tt4g** [comment]
Yes, You should define `SPDLOG_ACTIVE_LEVEL` before `#include "spdlog/spdlog.h"`.

**Comment by giulianoc** [comment]
thank you it works.

Does it mean that the statement
logger->set_level(spdlog::level::debug);
is useless because the library will use the SPDLOG_ACTIVE_LEVEL define in anycase?

**Comment by tt4g** [comment]
No, logging macros are used to remove unnecessary logging statements at compile time.
