### ISSUE TITLE
 There is a strange problem in the QT class

### ISSUE THREAD

**Issue by zhin2929** [gabime/spdlog#2938]
In QT classes, the debug and trace levels never output. What could be the problem?

![image](https://github.com/gabime/spdlog/assets/15818471/859ce51a-7a20-47df-84f5-422fa15e291c)

```
#define SPDLOG_WCHAR_TO_UTF8_SUPPORT // VS 输出窗口支持 UTF8
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE // SPDLOG_LEVEL_TRACE
#include <spdlog/fmt/ostr.h> // 自定义类输出必须包含
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/sinks/rotating_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/msvc_sink.h>
#include <spdlog/sinks/qt_sinks.h>

void initLog() {
  constexpr auto maxSize = 1048576 * 15; // 15m
  spdlog::init_thread_pool(8192, 1);

  const auto rotatingSink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("uploadx-log.txt",
    maxSize, 1);
  rotatingSink->set_pattern("[%Y-%m-%d %H:%M:%S.%e][tid %t][%s:%!:%#][%l] : %v");
  rotatingSink->set_level(spdlog::level::trace);

  // Visual Studio sink
  const auto vsSink = std::make_shared<spdlog::sinks::msvc_sink_mt>();
  vsSink->set_pattern("%s:%!:%# [%l] [tid %t] %v");
  vsSink->set_level(spdlog::level::trace);

  std::vector<spdlog::sink_ptr> sinks{ rotatingSink, vsSink };
  const auto loggers = std::make_shared<spdlog::async_logger>("spdlog", sinks.begin(), sinks.end(),
    spdlog::thread_pool(), spdlog::async_overflow_policy::block);
  loggers->flush_on(spdlog::level::trace);
  spdlog::register_logger(loggers);
  spdlog::set_default_logger(loggers);
  spdlog::set_automatic_registration(true);
  spdlog::set_level(spdlog::level::trace); 
}


```
![image](https://github.com/gabime/spdlog/assets/15818471/ad2c5faf-d05e-4b48-8df6-2ad13fd6ef9c)

**Comment by tt4g** [comment]
Do not upload images of source code and error messages.
It takes a lot of time and effort to check.

 `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE` macro must be defined for the entire project.
If you have more than one `.cpp` file, you can define macros in the compile options.

**Comment by zhin2929** [comment]
> Do not upload images of source code and error messages. It takes a lot of time and effort to check.
> 
> `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE` macro must be defined for the entire project. If you have more than one `.cpp` file, you can define macros in the compile options.

ok, thanks
