### ISSUE TITLE
The fmt::format performance of spdlog and fmtlib

### ISSUE THREAD

**Issue by VanishedDust** [gabime/spdlog#2939]
Hello, I want to use fmt::format function for some reason. Here is my test code
```
#include <array>
#include <cstdio>
#include <random>
#include <vector>
#include <cstdlib>
#include <unordered_map>
#include <string>
//#include <fmt/core.h>
#include <spdlog/spdlog.h>
#include <iostream>

struct Data {
  double hour;
  double minute;
  double seconds;
  double ns;
};

static int64_t sys_ns() {
    struct timespec ts;
    ::clock_gettime(CLOCK_REALTIME, &ts);
    return ts.tv_sec * 1000000000 + ts.tv_nsec;
}

std::vector<Data> generate_random_data() {
  auto data = std::vector<Data>();
  for (auto i = 0; i < 1000; ++i) {
    Data d = {rand()/1e8, rand()/1e6, rand()/1e9, rand()/1e10};
    data.push_back(d);
  }
  return data;
}

auto data = generate_random_data();

void snprintf() {
  static char values[1024] = {0};
  memset(values, 0, sizeof(values));
    for (auto d : data) {
      sprintf(values, "extern_price: %lf, f1: %lf, f2: %lf, robot: sd, delay: %lf", d.hour, d.minute, d.seconds, d.ns);
      std::string result(values);
    }
}

void fformat() {
    for (auto d : data) {
      auto result = fmt::format("extern_price: {}, f1: {}, f2: {}, robot: sd, delay: {}", d.hour, d.minute, d.seconds, d.ns);
    }
}

int main(){
    int64_t t0 = sys_ns();
    snprintf();
    int64_t t1 = sys_ns();
    tformat();
    int64_t t2 = sys_ns();
    std::cout<< (t1 - t0)/1000<<", "<< (t2- t1)/1000 <<std::endl;
    return 0;
}
```
Spdlog version: v1.9.2 ,  fmtlib version: v9.1.0.
If I use spdlog, the fmt::format performance will be worse than sprintf.  But If I use fmtlib rather than spdlog, the performance will be better than sprintf. 

It seems like spdlog uses the fmt::format header only version.
So my question is :
1. Is it ture of the spdlog uses the fmtlib header only version?
2. If not, what should I do to config the spdlog?
3. If yes, could you give me a step-by-step tutorial about how to use the external fmtlib?  
```
cmake_minimum_required(VERSION 3.18)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -Wall -O2")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Wall -g -ggdb")
project(perf VERSION 0.1.0)
add_executable(${PROJECT_NAME} ftest.cpp)
target_link_libraries(${PROJECT_NAME} spdlog)
```
That's my CMakeLists.txt file, I have tried to modify tweakme.h before, seems work, but I saw your comment not suggest to do like that.  So I use the command "cmake ..  -DSPDLOG_FMT_EXTERNAL=ON", it shows: " Manually-specified variables were not used by the project: SPDLOG_FMT_EXTERNAL"

And I tried to add " #define SPDLOG_FMT_EXTERNAL" before include spdlog.h, seems to work, I am not sure if it's the correct way.

Thanks very much.
Leo

**Comment by tt4g** [comment]
You can use external header-only fmt with the CMake variable `SPDLOG_FMT_EXTERNAL_HO=ON` (`SPDLOG_FMT_EXTERNAL` uses a compiled fmt).
However, your CMake project does not add spdlog to the project using `find_package(spdlog)`, so it seems to use spdlog installed on the system.
We do not know how spdlog is installed on your machine.

If you want to download spdlog projects and import it into your project, use `FetchContent`.
Example: #2614

**Comment by tt4g** [comment]
NOTE If you want to use header-only spdlog, you must use the CMake target `spdlog::spdlog_header_only`.

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/CMakeLists.txt#L195-L199

**Comment by VanishedDust** [comment]
Yes, I install it on docker by command:
```
RUN git clone https://github.com/gabime/spdlog.git && cd spdlog && git switch -c v1.9.2 && mkdir build &&  \
    cd build && cmake .. && make -j 10  && make install && ldconfig && cd /opt/deps/ && rm -rf spdlog
```
I don't want to use header-only version, I found the test result is not good, same as header-only version.
So I have to use external fmtlib to get better performance.

The spdlog version:
```
cpp : #include <spdlog/spdlog.h>
cmake: target_link_libraries(${PROJECT_NAME} spdlog)
```
The external libfmt version:
```
cpp:  
 #define SPDLOG_FMT_EXTERNAL
#include <spdlog/spdlog.h>
cmake:  target_link_libraries(${PROJECT_NAME} spdlog fmt::fmt)
```
The external libfmt version will be better than spdlog version.

**Comment by tt4g** [comment]
You have spdlog installed on your system, but it is not recognized as a CMake project.

`find_package(spdlog)` for CMake to find spdlog installed on the system is missing.

```diff
 RUN git clone https://github.com/gabime/spdlog.git && cd spdlog && git switch -c v1.9.2 && mkdir build &&  \
-    cd build && cmake .. && make -j 10  && make install && ldconfig && cd /opt/deps/ && rm -rf spdlog
+    cd build && cmake -DSPDLOG_FMT_EXTERNAL_HO=ON .. && make -j 10  && make install && ldconfig && cd /opt/deps/ && rm -rf spdlog
```

```diff
 cmake_minimum_required(VERSION 3.18)
 set(CMAKE_CXX_STANDARD 20)
 set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -Wall -O2")
 set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Wall -g -ggdb")
 project(perf VERSION 0.1.0)
+find_pacakge(spdlog)
 add_executable(${PROJECT_NAME} ftest.cpp)
-target_link_libraries(${PROJECT_NAME} spdlog)
+target_link_libraries(${PROJECT_NAME} spdlog::spdlog_header_only)
```

**Comment by VanishedDust** [comment]
Sorry, I don't want to use spdlog_header_only version. 
I add "find_pacakge(spdlog)" and  " cmake -DSPDLOG_FMT_EXTERNAL=ON .." , the result is same if I not add libfmt.
I wanna know If I can get the same performance when I do not add external libfmt in the spdlog.

**Comment by tt4g** [comment]
I'm not sure I understand the question.
Didn't you measure performance when you called the fmt library API?
If you mean that when you print log messages from spdlog, the performance is worse than when you call the fmt library API directly, then that performance measurement is meaningless.
