### ISSUE TITLE
Support for using non-builtin format library

### ISSUE THREAD

**Issue by bschindler** [gabime/spdlog#294]
In our code base, we plan on using the format library you include in details elsewhere as well as a core depedency. The thing is, that if we add our own version, it might conflict with the one in spdlog because of using different versions. We could just include <spdlog/details/format.h> but that would be odd as well. 
Would it be possible to either: 
- Make it possible to use an external format.h header if requested (by means of a define)
- include the file into a local namespace such that it won't conflict with the other include (not so nice as it effectively duplicates the entire thing)

**Comment by gabime** [comment]
to use your own version of fmt you should just

```c++
#define SPDLOG_FMT_EXTERNAL
```
before including spdlog.h (or uncomment this in tweakme.h)

**Comment by bschindler** [comment]
Ah, our spdlog version was too old. Thanks for pointing this out
