### ISSUE TITLE
2.x branch: move `spdlog::details::log_msg` to `spdlog::log_msg`?

### ISSUE THREAD

**Issue by bebuch** [gabime/spdlog#2940]
`spdlog::details::log_msg` is used in the documented examples on the main page:

https://github.com/gabime/spdlog#user-defined-flags-in-the-log-pattern

It looks strange to me to use a type declared in the `details` namespace of the library as a user of the library.

I therefore propose to move it to the main namespace.

**Comment by gabime** [comment]
Not so strange, as it is intended for “advanced” users who should deal with details. Also, It is used in so many places that moving it to the main namespace would break lots of code
