### ISSUE TITLE
Can spdlog increase the log (time, level, details) method？

### ISSUE THREAD

**Issue by wcy168** [gabime/spdlog#2941]
I have a requirement that during the task execution process, logs will be cached. If the task execution is successful, these logs will be discarded, and if it fails, they will be recorded. Each cached log contains time, log level, and details. By traversing the log and calling spdlog:: log (time, level, details), the cached log can be recorded. However, spdlog does not have such a method, and the underlying implementation has this method: default_logger_raw()->log(log_time, source_loc{}, lvl, msg). Can this method be implemented in the upper layer to facilitate calling?

**Comment by tt4g** [comment]
It is easier to use ringbuffer_sink than to intercept function calls.

https://github.com/gabime/spdlog/blob/v1.12.0/include/spdlog/sinks/ringbuffer_sink.h

**Comment by wcy168** [comment]
> It is easier to use ringbuffer_sink than to intercept function calls.
> 
> https://github.com/gabime/spdlog/blob/v1.12.0/include/spdlog/sinks/ringbuffer_sink.h

This cannot meet my needs. In fact, it requires spdlog to add a log function with a time parameter, which already has a log (level, msg) function. Adding a log (level, time, msg) function is sufficient

**Comment by tt4g** [comment]
Oh I understand. You already have a message cache.

Instead of `log(level, time, msg)`, there is `spdlog::logger::log(time, source_location, level, msg)`.

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/logger.h#L101-L113

How about a custom macro that calls `log(time, source_location, level, msg)` of default logger with reference to the `SPDLOG_LOGGER_CALL` macro?

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/spdlog.h#L286-L292

**Comment by wcy168** [comment]
> Oh I understand. You already have a message cache.
> 
> Instead of `log(level, time, msg)`, there is `spdlog::logger::log(time, source_location, level, msg)`.
> 
> https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/logger.h#L101-L113
> 
> How about a custom macro that calls `log(time, source_location, level, msg)` of default logger with reference to the `SPDLOG_LOGGER_CALL` macro?
> 
> https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/spdlog.h#L286-L292

What I mean is that this method is not exposed to users in spdlog. h.

**Comment by tt4g** [comment]
What do you mean? This is `public` method.

EDIT:  spdlog's private API has a rule that names end with underscore.
