### ISSUE TITLE
Do not perfect forward args unnecessarily

### ISSUE THREAD

**Issue by tomilov** [gabime/spdlog#2942]
It is common (anti)pattern in the current version of sources to accept arguments via `T&&... args`, then to forward them `std::forward<Args>(args)...` to deeper levels (can be found in `spdlog/spdlog.h`, `spdlog/logger.h`).

It is not required at all and can be fixed: either `std::forward<Args>(args)...` can be changed to `args...` or both can be changed: `T&&... args` -> `const T&... args` and `std::forward<Args>(args)...` -> `args...`.

This can save some compile time and improve readability.

**Comment by tt4g** [comment]
As far as I know, if I do not use `std::forward`, the destination function will be `T&` when the argument type is `T&&`, so `std::forward<Args>(args)...` and `args... ` are different: https://stackoverflow.com/questions/7257144/when-to-use-stdforward-to-forward-arguments

```cpp
#include <utility>
#include <type_traits>

class Foo {};

template <typename T>
void require_rvalue(T &&arg)
{
    static_assert(std::is_rvalue_reference_v<decltype(arg)> == true);
}

template <typename T>
void require_lvalue(T &&arg)
{
    static_assert(std::is_lvalue_reference_v<decltype(arg)> == true);
}

template <typename T>
void use_forward(T &&arg)
{
    require_rvalue(std::forward<T>(arg));

    // assertion error.
    // require_lvalue(std::forward<T>(arg));
}

template <typename T>
void no_forward(T &&arg)
{
    // assertion error.
    // require_rvalue(arg);

    require_lvalue(arg);
}

int main(void) {
    use_forward(Foo());
    no_forward(Foo());
    return 0;
}
```

**Comment by gabime** [comment]
@tomilov Why is It is not required at all ? I think it was not compiling properly without it at some point

**Comment by tomilov** [comment]
@gabime you are right. Generators and `fmt::join` results have to be passed by rvalue reference and (sadly) to be modified. Hence it is not safe to pass something dependent twice.
