### ISSUE TITLE
Limit the number of times a message is output

### ISSUE THREAD

**Issue by colemanalan** [gabime/spdlog#2945]
Maybe this is already possible, but it would be nice to be able to limit a given error to only print out the first N times and then log how many times it has been suppressed.

**Comment by tt4g** [comment]
Duplicate #2866

This feature is not supported.

**Comment by tt4g** [comment]
For your information.

`LOG_EVERY_N` macro provided by glog uses `static` variables to keep track of the number of calls, so you should be able to provide a very similar macro yourself.

- `LOG_EVERY_N`: https://github.com/google/glog/blob/931323df212c46e3a01b743d761c6ab8dc9f0d09/src/glog/logging.h.in#L1126-L1127

- `SOME_KIND_OF_LOG_EVERY_N`: https://github.com/google/glog/blob/931323df212c46e3a01b743d761c6ab8dc9f0d09/src/glog/logging.h.in#L1072-L1081

**Comment by gabime** [comment]
There is also the  [dup filter](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/dup_filter_sink.h) sink that might help.
