### ISSUE TITLE
feature request: write empty line

### ISSUE THREAD

**Issue by wjx0912** [gabime/spdlog#2946]
```
------>empty line here!
[19:19:41.963] line1
[19:19:41.963] line2
------>empty line here!
[19:19:41.963] line3
[19:19:41.964] line4
```

can i write a empty line everywhere, thanks

**Comment by tt4g** [comment]
spdlog is a logging library that outputs formatted log messages.
It does not support the ability to output empty lines.

It is possible to print empty lines by including line breaks in the log message.
You can also create a custom formatter that prints blank lines: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#extending-spdlog-with-your-own-flags

**Comment by wjx0912** [comment]
@tt4g  thank you.
