### ISSUE TITLE
rotating_logger_mt work wrong

### ISSUE THREAD

**Issue by dzh592204** [gabime/spdlog#2949]
I use rotating_logger_mt in the following way, but sometimes it goes wrong. 
For example, it create file mss.3.log mss.log, but no mss.2.log or mss.1.log
mss.log
mss.3.log

my core code :
spdlog::set_pattern("[%D %H:%M:%S] [%n] [%^-%L-%$] [thread %t] %v");
string log_path = "./log/" + g_log_cfg.base_name;
g_logger = spdlog::rotating_logger_mt("vtcs", "./log/mss.log",30*1024*1024, 300);

g_logger->set_level((spdlog::level::level_enum)g_log_cfg.level);
g_logger->flush_on((spdlog::level::level_enum)g_log_cfg.level);

**Comment by dzh592204** [comment]
g_logger is a global variable:
std::shared_ptr<spdlog::logger> g_logger;

**Comment by tt4g** [comment]
If you are writing to the same log file from multiple processes, it will not work correctly.
The same problem would occur if the global variable `g_logger` was created more than once.

**Comment by dzh592204** [comment]
> If you are writing to the same log file from multiple processes, it will not work correctly. The same problem would occur if the global variable `g_logger` was created more than once.

@tt4g there are two different processes , but they use different log file. And the global variable `g_logger` was created just once in every process.  The two processes are in different dir.
one is:	
        g_logger = spdlog::rotating_logger_mt("mss", "./log/mss.log",3010241024, 300);

another is:
	g_logger = spdlog::rotating_logger_mt("sms", "./log/sms.log", 3010241024, 300);

**Comment by tt4g** [comment]
Do you mean that two processes are not running from the same program?
If two of the same program are launched at the same time, then it is a multiprocess.

And are you saying that the problem only occurs in `mss.log`?

**Comment by dzh592204** [comment]
@tt4g The two processes are running from diffrent program in diffrent dir. They implement different functions as independent services。
they are launched at diffrent time  but run at the same time.
the problem may occurs in any *.log.
for examle:  
one create sms.log sms.1.log sms.2.log sms.4.log and so on, but no sms.3.log;
another create mss.log mss.1.log mss.4.log and so on, but no mss.2.log and mss.3.log

**Comment by tt4g** [comment]
> The two processes are running from diffrent program in diffrent dir. They implement different functions as independent services。

How are you launching processes?
If you are using `fork()` or `daemon()` to lunch a process, it is multi process.

**Comment by dzh592204** [comment]
> daemon()

@tt4g I use NSSM to manger my process on windows server2012 R2 Standard;
eg: 
1. Corresponding log----sms.log
NSSM install StreamMediaService D:\ahjkii_media_service\stream_service\StreamMediaService.exe
NSSM set StreamMediaService AppDirectory D:\ahjkii_media_service\stream_service
NSSM start StreamMediaService

2. Corresponding log---mss.log
NSSM install JKStoreService D:\ahjkii_media_service\store_service\MediaStoreService.exe
NSSM set JKStoreService AppDirectory D:\ahjkii_media_service\store_service\
NSSM start JKStoreService

**Comment by tt4g** [comment]
Can you reproduce the problem without using NSSM?
