### ISSUE TITLE
Can't compile: sink.h:18: cannot convert argument 1 from 'spdlog::level::level_enum' to 'const std::atomic_int &'

### ISSUE THREAD

**Issue by SlavMFM** [gabime/spdlog#295]
Hello.
Sorry if I'm missing something obvious, trying to use spdlog for the first time and not being that familiar with C++11 features.
Trying to compile with MSVC 2013.
Please advice me on how can I fix it?
Thanks in advance.

**Comment by SlavMFM** [comment]
Oops, found the source of the problem: it is [Visual Studio bug](http://stackoverflow.com/questions/15750917/initializing-stdatomic-bool). Had to edit `using level_t = std::atomic_int;` to `using level_t = std::atomic<int>;` at common.h:60 and problem gone.
Sorry for being too eager trying to fix it, but examining ~50 links regarding similar problems posted this and at 51 found the solution :)

**Comment by gabime** [comment]
Thanks for reporting. I will fix this in the code
