### ISSUE TITLE
Correct way of using the same sink (file) for logging of multiple applications

### ISSUE THREAD

**Issue by simonevallifuoco** [gabime/spdlog#2951]
I would like to use spdlog in multiple different applications that will run concurrently in my QNX operating system. What is the correct way to handle that? Is it ok to define a logger in every application with the same file as sink?  
For example I would declare the following logger in every application:
auto async_file = spdlog::basic_logger_mt<spdlog::async_factory>("async_file_logger", "logs/async_log.txt");

Is this ok? Is the _mt required or it is useless in my case? Will I have any problems because of the use of the same file possibly at the same time by different applications?

**Comment by tt4g** [comment]
There is no feature to write from multiple processes to a single file: #937

For reference, many multi-process applications have one main process write logs to a file, while other processes communicate with the main process on UNIX or TCP sockets to delegate log writing.

**Comment by simonevallifuoco** [comment]
Thank you @tt4g 

I am currently working on the architecture that you suggested: I have multiple applications that delegate log writing to a logging application; to achieve that I am using mqueue for inter process communication. However I am experiencing the following issue: in the logging application I have a loop that receives messages from the queue:
```
while (true) {
  // Receive message from the queue
  ssize_t bytesReceived = mq_receive(serverQueue, buffer, MAX_MSG_SIZE,nullptr);
  if (bytesReceived == -1) {
	  perror("mq_receive");
	  break;
  }
  
  // Log received message
  buffer[bytesReceived] = '\0'; 
  logger_all->warn(buffer);
}
```

where `logger_all` has been initialized like that: 
`auto logger_all = spdlog::rotating_logger_st("logger_all","logs/logger_all.txt", 1024 * 5, 3);`

But I am debugging the application and it looks like the received messages are never written in the log file as long as the application is running inside the while loop. It's kind of having an async behavior even if it should not. If, for testing, I exit the while loop (for example by writing a `break` instruction) the log file is written at the end of the program, just like I would expect by an async logger.

Is this behavior correct? Am I making some mistake? What is the correct way of doing this?

**Comment by tt4g** [comment]
Try calling `logger_all->flush()` to see if it flushes.
See: https://github.com/gabime/spdlog/wiki/7.-Flush-policy

By the way, the source code provided may be undefined behavior.

- Is the size of `buffer` `MAX_MSG_SIZE + 1`?
- `while (true)` is undefined behavior in C++ if the compiler considers it an infinite loop, and the loop body may be removed (https://stackoverflow.com/questions/76960441/benefit-of-endless-loops-without-side-effects-in-c-being-undefined-behavior-co)

**Comment by simonevallifuoco** [comment]
Thanks @tt4g  , the flush is correctly working. 

Regarding `MAX_MSG_SIZE`, yes it is.
Regarding the `while (true)`, do you think there is a better way to implement this centralized logging program so that I don't need an infinite loop that waits for messages, or should I just check that the compiler does not ignore this loop for optimization reasons and keep this implementation?

**Comment by tt4g** [comment]
If you want to make sure that the `while(true)` loop body has not been removed, an easy way is to use `printf()` to check when the message is printed as expected.
If `printf()` prints out a message and writes it to the log file, then you can assume that the `while (true)` loop body has been removed.

**Comment by simonevallifuoco** [comment]
Yeah actually even without a printf() call, I am checking the log file and it is correctly written at each message sent, so I guess I can assume that the compiler is considering my loop, right?

**Comment by tt4g** [comment]
Right.
Perhaps the file buffer flush was blocked because the CPU was busy with `while(true)`.

**Comment by simonevallifuoco** [comment]
Yes probably. 
Thank you very much for you support @tt4g
