### ISSUE TITLE
Header-only setup for the v2.x branch seems incomplete or incorrect

### ISSUE THREAD

**Issue by Caball009** [gabime/spdlog#2956]
Even though the readme for v2.x https://github.com/gabime/spdlog/tree/v2.x#install suggests that a header-only approach would work (like it does for v1.x), this doesn't appear to be the case. I'm running into undefined symbol linking errors because the file structure changed, but the documentation has not.

Presuming the error isn't on my end, is it possible for this to be fixed?

**Comment by gabime** [comment]
There is no support for header only in v2.x. The readme hasn’t been updated yet.

**Comment by Caball009** [comment]
Thanks for the quick answer / confirmation. It probably wouldn't hurt if this was clarified in the readme file.

PS: v1.x doesn't use std::source_location but v2.x does, is that correct? That would be the reason for me to be looking at v2.x.

**Comment by gabime** [comment]
Right. It is only in 2.x
