### ISSUE TITLE
Per log level formatting

### ISSUE THREAD

**Issue by MPcoreDev** [gabime/spdlog#2958]
Per-log-level formatting is not supported. However, you can create your own custom sink and format it specifically for each log level.
Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

Use the format flags `%@` and `%! `. Note that these flags will not show anything unless you use the logging macro such as `SPDLOG_INFO` and `SPDLOG_LOGGER_INFO`.
Wiki: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

_Originally posted by @tt4g in https://github.com/gabime/spdlog/issues/2424#issuecomment-1175487114_
           

If I need two patterns, let say one colorfull and one grey (but both on console), and if each shall be used for a specific level range, let say no color from trace to info, color from warning, am I obliged to create as many sinks as levels or is there a better manner ?

**Comment by tt4g** [comment]
You can use `set_color` API.

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/sinks/ansicolor_sink-inl.h#L33-L38

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/sinks/wincolor_sink-inl.h#L42-L48

**Comment by MPcoreDev** [comment]
Thank you for the reply.
Changing color is not enough for what I want to achieve.

Basically I want the following pattern if the level is below or equal to INFO (the color is only used for the level text):
![image](https://github.com/gabime/spdlog/assets/52664431/aa0126d2-af68-48a1-9390-9d4ae8010e86)

But for other, more critical levels I want:
![image](https://github.com/gabime/spdlog/assets/52664431/36f5b889-124b-4d53-a832-55fe08ca6001)

Thus it makes two distinct patterns, with a list of applicable levels for each one.

**Comment by tt4g** [comment]
The color range format flag (start: `%^`, end `%$`) can be used to adjust the color range of the message, but the ability to set it per log level is not supported.

You may want to consider the custom formatter.

**Comment by MPcoreDev** [comment]
Yep I know how to create the pattern. My point was about how to affect pattern to level.
Any doc please about 'custom formatter' I don't manage to find it.
Thanks

**Comment by tt4g** [comment]
For now, the only documentation on custom formatters is the Wiki (the Wiki can be edited by anyone).

If the Wiki documentation lacks information, you are left to figure out how to create a custom formatter from an existing formatter implementation.
See: https://github.com/gabime/spdlog/blob/v1.12.0/include/spdlog/pattern_formatter-inl.h
