### ISSUE TITLE
how to free fd Occupancy by spdlog::sinks::rotating_file_sink_mt 

### ISSUE THREAD

**Issue by calvinhxx** [gabime/spdlog#2960]
i cant zip rotating.txt when rotating_file_sink_mt on working
shutdown() cant free file_helper_](details::file_helper file_helper_

**Comment by gabime** [comment]
Check the [spdlog::file_event_handlers](https://github.com/gabime/spdlog?tab=readme-ov-file#log-file-openclose-event-handlers) to get notified before/after a log file was closed

**Comment by calvinhxx** [comment]
Thanks for this for solving my problem.
