### ISSUE TITLE
The tags of the log are often incompletely displayed.

### ISSUE THREAD

**Issue by seulchanson** [gabime/spdlog#2966]
When an exception occurs, the program will print a log before returning directly. In this case, the tags of the log are often incompletely displayed.
I have used flush and spdlog::shutdown
 incompletely displayed:
![image](https://github.com/gabime/spdlog/assets/42291526/28ec9912-a6b9-42ba-a8e5-ff06af350fc2)
 completely displayed.
![image](https://github.com/gabime/spdlog/assets/42291526/1d918e6f-53fb-42d8-a12d-f935def63ea2)

**Comment by tt4g** [comment]
I don't think we can determine the cause of the problem unless reproducible code is provided.

> When an exception occurs

Is this exception handled by `try`-`catch`?
If not, it is an undefined behavior, and the logs are not printed correctly because of the undefined behavior.

**Comment by seulchanson** [comment]
this exception handled by try-catch

> I don't think we can determine the cause of the problem unless reproducible code is provided.
> 
> > When an exception occurs
> 
> Is this exception handled by `try`-`catch`? If not, it is an undefined behavior, and the logs are not printed correctly because of the undefined behavior.

 This exception handled by try-catch， then output the log in catch {}.

**Comment by tt4g** [comment]
@seulchanson Without the source code provided we have no idea what happened.
