### ISSUE TITLE
undefined reference to `vtable for spdlog::async_logger' when compiling

### ISSUE THREAD

**Issue by taghiloni** [gabime/spdlog#2971]
We used spdlog in extension to a vendor provided software. It was compiling and OK.
Now the vendor started to use the fmt-8.1.1 and we can not comiple the old version of the spdlog with the extensions.
We copy src/spdlog.cpp to our build tree and pass the -DSPDLOG_COMPILED_LIB to the compiler
I downloaded spdlog-1.10.0 which uses fmt-8.1.1 and try to compile. I get the following linking error:

spdlog/include/spdlog/async_logger.h:43: undefined reference to `vtable for spdlog::async_logger'
/export/gcs1/apps/deploy/packages/gcc-10.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: 
r.so.dfSPLK.ltrans1.ltrans.o: in function `spdlog::sinks::daily_file_sink<spdlog::details::null_mutex, spdlog::sinks::daily_filename_calculator>::daily_file_sink
(std::string, int, int, bool, unsigned short, spdlog::file_event_handlers const&)':
spdlog/include/spdlog/sinks/daily_file_sink.h:127: undefined reference to `spdlog::details::file_helper::file_h
elper(spdlog::file_event_handlers const&)'
/export/gcs1/apps/deploy/packages/gcc-10.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: spdlog/include/spdlog/sinks/daily_file_sink.h:136: undefined reference to `spdlog::details::file_helper::open(std::string const&, bool)'
/export/gcs1/apps/deploy/packages/gcc-10.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: spdlog/include/spdlog/sinks/daily_file_sink.h:127: undefined reference to `spdlog::details::file_helper::~file_helper()'
/export/gcs1/apps/deploy/packages/gcc-10.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: 
r.so.dfSPLK.ltrans1.ltrans.o: in function `spdlog::sinks::daily_file_sink<std::mutex, spdlog::sinks::daily_filename_calculator>::daily_file_sink(std::string, int
, int, bool, unsigned short, spdlog::file_event_handlers const&)':
spdlog/include/spdlog/sinks/daily_file_sink.h:127: undefined reference to `spdlog::details::file_helper::file_h
elper(spdlog::file_event_handlers const&)'
/export/gcs1/apps/deploy/packages/gcc-10.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: spdlog/include/spdlog/sinks/daily_file_sink.h:136: undefined reference to `spdlog::details::file_helper::open(std::string const&, bool)'
/export/gcs1/apps/deploy/packages/gcc-10.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: spdlog/include/spdlog/sinks/daily_file_sink.h:127: undefined reference to `spdlog::details::file_helper::~file_helper()'
/export/gcs1/apps/deploy/packages/gcc-10.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: 
r.so.dfSPLK.ltrans1.ltrans.o: in function `spdlog::sinks::daily_file_sink<std::mutex, spdlog::sinks::daily_filename_calculator>::~daily_file_sink()':
spdlog/include/spdlog/sinks/daily_file_sink.h:115: undefined reference to `spdlog::details::file_helper::~file_
helper()'

Any help/hint is appreciated.

**Comment by tt4g** [comment]
The link will fail if you are not using the same version of spdlog and fmt as the vendor.

EDIT: Compilation options must also match.

**Comment by tt4g** [comment]
You also need to define the `SPDLOG_FMT_EXTERNAL` macro to make spdlog use external fmt: `-DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL`

**Comment by tt4g** [comment]
Oh, I had overlooked that.
You must build all the `src/*.cpp` files, since building only `src/spdlog.cpp` will result in missing symbols.

**Comment by taghiloni** [comment]
> Oh, I had overlooked that. You must build all the `src/*.cpp` files, since building only `src/spdlog.cpp` will result in missing symbols.

But in installation file it says as one of the option to use spdlog: 
Or copy src/spdlog.cpp to your build tree and pass the -DSPDLOG_COMPILED_LIB to the compiler

& with current version of the vendor APIs  it is working.

We use the vendor APIs in our code & now we have to migrate our code to compile with vendor's new version of APIs (which use fmt, the current version of APIs do no use fmt). The vendor has provided us with fmt header files and informed us they use only fmt-8.1.1.

We tried DSPDLOG_FMT_EXTERNAL and it did not help.

**Comment by tt4g** [comment]
> But in installation file it says as one of the option to use spdlog:
> Or copy src/spdlog.cpp to your build tree and pass the -DSPDLOG_COMPILED_LIB to the compiler

Where does it say that?
As far as I know, there is no such documentation in the spdlog repository.
If the vendor is customizing the spdlog, then your question here cannot be resolved.
