### ISSUE TITLE
The macro SPDLOG_ACTIVE_LEVEL is defined as SPDLOG_LEVEL_TRACE, but SPDLOG_TRACE is not effective.

### ISSUE THREAD

**Issue by Ccccx159** [gabime/spdlog#2975]
## Summery

When I use the code in the Basic Usage section, macro `SPDLOG_TRACE` is not effective. Even if I define `SPDLOG_ACTIVE_LEVEL` as `SPDLOG_LEVEL_TRACE`.

## Reproduce

source code:

```cpp
#include "spdlog/spdlog.h"

int main() 
{
    spdlog::info("Welcome to spdlog!");
    spdlog::error("Some error message with arg: {}", 1);
    
    spdlog::warn("Easy padding in numbers like {:08d}", 12);
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
    spdlog::info("Support for floats {:03.2f}", 1.23456);
    spdlog::info("Positional args are {1} {0}..", "too", "supported");
    spdlog::info("{:<30}", "left aligned");
    
    spdlog::set_level(spdlog::level::debug); // Set global log level to debug
    spdlog::debug("This message should be displayed..");    
    
    // change log pattern
    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");
    
    // Compile time log levels
    // define SPDLOG_ACTIVE_LEVEL to desired level
    SPDLOG_TRACE("Some trace message with param {}", 42);
    SPDLOG_DEBUG("Some debug message");
}
```

compiled command:

 `g++ -I include -std=c++11 -O0 -g -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE -o spdlog-main ./spdlog-main.cc`

Here is the result of compiling and running:

```bash
code-server [13:57:01] log-example  ➜ g++ -I include -std=c++11 -O0 -g -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE -o spdlog-main ./spdlog-main.cc 
code-server [13:57:10] log-example  ➜ ./spdlog-main 
[2024-01-10 13:57:14.143] [info] Welcome to spdlog!
[2024-01-10 13:57:14.143] [error] Some error message with arg: 1
[2024-01-10 13:57:14.143] [warning] Easy padding in numbers like 00000012
[2024-01-10 13:57:14.143] [critical] Support for int: 42;  hex: 2a;  oct: 52; bin: 101010
[2024-01-10 13:57:14.143] [info] Support for floats 1.23
[2024-01-10 13:57:14.143] [info] Positional args are supported too..
[2024-01-10 13:57:14.143] [info] left aligned                  
[2024-01-10 13:57:14.143] [debug] This message should be displayed..
[13:57:14 +08:00] [] [---D---] [thread 165294] Some debug message
code-server [13:57:14] log-example  ➜ 
```

## Expected Behavior

As the comment in the code says, `SPDLOG_TRACE` should be effective while `SPDLOG_ACTIVE_LEVEL` is defined as `SPDLOG_LEVEL_TRACE`.

In [the last section of the Custom formatting in the wiki](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#source-location-flags), it also describes: 

> "If you need to use source location flags, it is necessary to define SPDLOG_ACTIVE_LEVEL to SPDLOG_LEVEL_TRACE. 
> 
> ...
> 
> And if you've set the flag to SPDLOG_LEVEL_TRACE but you don't see any trace and/or debug messages, define it directly as a compiler flag."

I did it, but it doesn't work.

## Solution

1. define `SPDLOG_ACTIVE_LEVEL` as `SPDLOG_LEVEL_TRACE`
2. call `spdlog::set_level(spdlog::level::trace)` before using `SPDLOG_TRACE`

### Step 1 check precompiled result

I have checked the precompiled result of the source file and found that the macro definition of `SPDLOG_TRACE` is expanded in the following form:

```bash
code-server [14:14:13] log-example  ➜ g++ -I include -std=c++11 -O0 -g -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE -E -o spdlog-main.i ./spdlog-main.cc
code-server [14:15:28] log-example  ➜ tail -n 11 spdlog-main.i 
    spdlog::set_level(spdlog::level::debug);
    spdlog::debug("This message should be displayed..");


    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");



    (spdlog::default_logger_raw())->log(spdlog::source_loc{"./spdlog-main.cc", 52, static_cast<const char *>(__FUNCTION__)}, spdlog::level::trace, "Some trace message with param {}", 42);
    (spdlog::default_logger_raw())->log(spdlog::source_loc{"./spdlog-main.cc", 53, static_cast<const char *>(__FUNCTION__)}, spdlog::level::debug, "Some debug message");
}
code-server [14:15:34] log-example  ➜ 
```

According to the predefinitions in the header file spdlog.h, it can be confirmed that the value of `SPDLOG_ACTIVE_LEVEL` is indeed equal to `SPDLOG_LEVEL_TRACE`, and the macro definition of `SPDLOG_TRACE` is expanded as expected.

### step 2 GDB trace

After tracing with GDB, it was found that when `SDPLOG_LEVEL_TRACE` is enabled, both "log_enabled" and "traceback_enabled" are **false** when reaching line 320 in logger.h. Therefore, the statement `SPDLOG_TRACE("Some trace message with param {}", 42);` does not output trace-level logs in the console.

After a rough reading of the source code, it appears that "traceback_enabled" being false is normal because I did not enable the backtrace feature.

The reason for "log_enabled" being false is that in the main function, the global log level is set to debug (`set_level(debug)`), and line 318 in logger.h checks if the current msg_level (trace) is less than or equal to debug.

```bash
Breakpoint 1, main () at ./spdlog-main.cc:52
52          SPDLOG_TRACE("Some trace message with param {}", 42);
(gdb) b logger.h:320
Breakpoint 2 at 0x5555555783bf: logger.h:320. (4 locations)
(gdb) c
Continuing.

Breakpoint 2, spdlog::logger::log_<int> (this=0x555555615660, loc=..., lvl=spdlog::level::trace, fmt=...)
    at include/spdlog/logger.h:320
320             if (!log_enabled && !traceback_enabled) {
(gdb) p log_enabled 
$1 = false
(gdb) p traceback_enabled 
$2 = false
(gdb) p level_
$3 = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}
(gdb) 
```

## Conclusion

Therefore, it can be concluded that in order for `SPDLOG_TRACE` to take effect, not only should `SPDLOG_ACTIVE_LEVEL` be defined as `SPDLOG_LEVEL_TRACE`, but also `spdlog::set_level(spdlog::level::trace)` should be called before using `SPDLOG_TRACE`.

new code:

```cpp
int main() 
{
    spdlog::info("Welcome to spdlog!");
    spdlog::error("Some error message with arg: {}", 1);
    
    spdlog::warn("Easy padding in numbers like {:08d}", 12);
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
    spdlog::info("Support for floats {:03.2f}", 1.23456);
    spdlog::info("Positional args are {1} {0}..", "too", "supported");
    spdlog::info("{:<30}", "left aligned");
    
    spdlog::set_level(spdlog::level::debug); // Set global log level to debug
    spdlog::debug("This message should be displayed..");    
    
    // change log pattern
    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");
    
    // Compile time log levels
    // define SPDLOG_ACTIVE_LEVEL to desired level
    spdlog::set_level(spdlog::level::trace); 
    SPDLOG_TRACE("Some trace message with param {}", 42);
    SPDLOG_DEBUG("Some debug message");
}
```

and the result:

```bash
code-server [14:56:22] log-example  ➜ g++ -I include -std=c++11 -O0 -g -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE -o spdlog-main ./spdlog-main.cc  
code-server [14:56:52] log-example  ➜ ./spdlog-main 
[2024-01-10 14:56:56.952] [info] Welcome to spdlog!
[2024-01-10 14:56:56.952] [error] Some error message with arg: 1
[2024-01-10 14:56:56.952] [warning] Easy padding in numbers like 00000012
[2024-01-10 14:56:56.952] [critical] Support for int: 42;  hex: 2a;  oct: 52; bin: 101010
[2024-01-10 14:56:56.952] [info] Support for floats 1.23
[2024-01-10 14:56:56.952] [info] Positional args are supported too..
[2024-01-10 14:56:56.952] [info] left aligned                  
[2024-01-10 14:56:56.952] [debug] This message should be displayed..
[14:56:56 +08:00] [] [---T---] [thread 177043] Some trace message with param 42
[14:56:56 +08:00] [] [---D---] [thread 177043] Some debug message
code-server [14:56:56] log-example  ➜ 
```

**Comment by tt4g** [comment]
The logging macro `SPDLOG_TRACE` is a macro to remove unnecessary logging statements by `SPDLOG_ACTIVE_LEVEL` which was defined at compile time, so the current behavior is as specified.

The examples in the `Basic usage` section of `README.md` are certainly confusing.
You can submit a PR to add a comment above `SPDLOG_TRACE` explaining that the log level is not changed.

**Comment by egaban** [comment]
I literally spent an hour trying to debug exactly the same problem. I will create a PR mentioning this. Thanks!

**Comment by egaban** [comment]
I've updated the wiki FAQ page to add a small note and created the PR #2981.

**Comment by zhuzhzh** [comment]
I am confused by this as well.

**Comment by dylanetaft** [comment]
I'm running into issues with this too.  I am still troubleshooting it.  I am passing  -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE to my compiler and it works in a test case with header-only include.

In my non test project that is static linking, it does not work, even though the flag is still being set.    I am trying to move my cmake superbuild to pull in spdlog as header only and will reply back if that makes it work. 

Oddly I see the trace messages, just the macros like %s, %i don't work.

**Comment by egaban** [comment]
> I'm running into issues with this too. I am still troubleshooting it. I am passing -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE to my compiler and it works in a test case with header-only include.
> 
> In my non test project that is static linking, it does not work, even though the flag is still being set. I am trying to move my cmake superbuild to pull in spdlog as header only and will reply back if that makes it work.
> 
> Oddly I see the trace messages, just the macros like %s, %i don't work.

But does your test case work with static linking? Does it print %s and %i?

**Comment by dylanetaft** [comment]
For the life of me I cannot isolate it.  I tried linking statically in my test case, the macros work fine.   They also work fine header only.  

It is bizarre because I still see lines printed, just the macros don't work.   I half wonder if gtest or libwebsockets is doing something with fmt.  I have not tried bringing all my third party libraries into my test case.  

My test case I am just using g++ command line.  My main project I am using cmake, a superbuild that pulls in spdlog.  I don't know if it's the same issue as OP.

**Comment by dylanetaft** [comment]
spdlog::set_level(spdlog::level::trace);
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
    SPDLOG_TRACE("Hello world from this class {}",__LINE__);
 
 Output:   
 [source ] [function ] [line ] Hello world from this class 53
[source ] [function ] [line ] P2PTaskAdapter::registerAsP2PEventListener()
[source ] [function ] [line ] P2PTaskUUIDLocator::begin()

Yeah, I am at a loss!  The preprocessor macros expand fine.  And my test cases work fine.

**Comment by dylanetaft** [comment]
I am just going to work around this with a macro in lieu of the formatter, this is working fine.  It's probably some sort of weird conflict with a library I am using in my project, which there are many libraries.  It wasn't libwebsocket causing problems.  Could be gtest...idk.  It's unlikely cmake's fault.  

``
#define C_SPDLOG_LOG(level, msg, ...) \
    spdlog::level("f:{} fn:{}:{} " msg,__FILE_NAME__,__FUNCTION__, __LINE__, ##__VA_ARGS__)
``
C_SPDLOG_LOG(TRACE,"Hello world")

**Comment by Ccccx159** [comment]
> I am just going to work around this with a macro in lieu of the formatter, this is working fine. It's probably some sort of weird conflict with a library I am using in my project, which there are many libraries. It wasn't libwebsocket causing problems. Could be gtest...idk. It's unlikely cmake's fault.
> 
> `#define C_SPDLOG_LOG(level, msg, ...) \ spdlog::level("f:{} fn:{}:{} " msg,__FILE_NAME__,__FUNCTION__, __LINE__, ##__VA_ARGS__)` C_SPDLOG_LOG(TRACE,"Hello world")C_SPDLOG_LOG(TRACE,"你好世界")

If you want to output the file name, function name, and line number in the log, you can try using the following macros.
~~~c++
SPDLOG_INFO(__VA_ARGS__)
SPDLOG_DEBUG(__VA_ARGS__)
SPDLOG_WARN(__VA_ARGS__)
SPDLOG_ERROR(__VA_ARGS__)
SPDLOG_CRITICAL(__VA_ARGS__)
~~~

Or you can also try using the following function: `spdlog::default_logger_raw()->log(spdlog::source_loc(file_name_, line_, function_name_), level_, msg_.str());` 

 I wrapped it simply to make it callable in a stream-like manner like glog, hoping it can be helpful to you.
~~~c++
#define LOG(level) \
  Logger(level, __builtin_FILE(), __builtin_FUNCTION(), __builtin_LINE())

// 兼容 glog 用法
#include <sstream>
class Logger {
 public:
  Logger(spdlog::level::level_enum level, const char *file_namem,
         const char *function_name, unsigned int line)
      : level_(level),
        file_name_(file_namem),
        function_name_(function_name),
        line_(line) {}
  ~Logger() {
    spdlog::default_logger_raw()->log(
        spdlog::source_loc(file_name_, line_, function_name_), level_,
        msg_.str());
  }
  template <typename T>
  Logger &operator<<(const T &msg) {
    msg_ << msg << ' ';
    return *this;
  }

 private:
  spdlog::level::level_enum level_;
  std::ostringstream msg_;
  const char *file_name_;
  const char *function_name_;
  unsigned int line_;
};
~~~
