### ISSUE TITLE
Option to omit default newline symbol.

### ISSUE THREAD

**Issue by SlavMFM** [gabime/spdlog#298]
Not sure if such option not available yet, but it would be awesome if there could be a way to avoid newline character being automatically printed at the end, so **'\r'** may be used.
Is there already such option available or is it possible to implement?

Thanks in advance.

**Comment by gabime** [comment]
it can be changed in tweakme.h

**Comment by gabime** [comment]
by defining  SPDLOG_EOL (found in tweakme.h)

**Comment by SlavMFM** [comment]
It worked out!
Thank you very much. Awesome design.

**Comment by gabime** [comment]
:+1

**Comment by dilawar** [comment]
Related https://github.com/gabime/spdlog/issues/579
