### ISSUE TITLE
 warning: C4459: declaration of 'uint' hides global declaration

### ISSUE THREAD

**Issue by punytroll** [gabime/spdlog#2984]
Hello,

of course, this is not really an error, but rather an annoyance. But coupled with a policy to treat all warnings as errors, it becomes a real issue.
Microsoft's compiler issues this warning:

```
<path-to-project>\subprojects\spdlog-1.11.0\include\spdlog\fmt\bundled\format.h(3251): warning C4459: declaration of 'uint' hides global declaration
C:/Qt/6.4.3/msvc2019_64/include\QtCore/qglobal.h(219): note: see declaration of 'uint'
```

I can see the same error coming from format.h:1357.

Since this is inside a templated function, the actual order of including the files doesn't matter.

I realize that this is an issue inside the bundled fmt library, but since I am not a (direct) user of fmt, I am really unsure about the correct project to report this to. Please feel free to forward the issue to the fmt library, if they need to resolve this.

Thank you very much in advance!

PS: I could post a Qt bug as well, but unfortunately, I am well aware of the speed and willingness of Qt to resolve such issues ...

**Comment by tt4g** [comment]
This warning already fixed fmtlib/fmt#3137 (fmt version 10.0.0).

However, the latest spdlog (v1.13.0) does not support fmt 10.
See this comment for more information: https://github.com/gabime/spdlog/issues/2788#issuecomment-1614068017

**Comment by gabime** [comment]
> However, the latest spdlog (v1.13.0) does not support fmt 10.

Actually spdlog does support using fmt 10 as an external lib(not bundled).

**Comment by punytroll** [comment]
There is always more to check. OK, sorry for not realizing that. Thanks!
Ah, that second comment cleans up some of my confusion. =)
Is a bundled version of fmt 10 in the pipeline or is that impossible to get? Because I really don't use fmt and it would be an additional dependency to keep track of.

**Comment by tt4g** [comment]
Bundled fmt version 10 or higher will be available after spdlog v2: https://github.com/gabime/spdlog/issues/2805#issuecomment-1626970364

**Comment by punytroll** [comment]
Thank you very much!
