### ISSUE TITLE
MSVC new version, warning MSVC(C4996).

### ISSUE THREAD

**Issue by rokgm** [gabime/spdlog#2987]
I am statically linking `spdlog` to my project. After updating MSVC (14.38.33130) , I get a warning when I include:
```
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
```

Warning only occurs when building in debug.

Warning:
'stdext::checked_array_iterator<T*>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning. MSVC(C4996)

Warning is in `format.h`:
![image](https://github.com/gabime/spdlog/assets/75335610/0ce7703e-5f66-4434-9878-e14f41af2fd4)

**Comment by tt4g** [comment]
`include/spdlog/fmt/bundled/format.h` is copied from fmt library,
Please reopen this issue in [fmt repository](https://github.com/fmtlib/fmt).

**Comment by Sonnexo** [comment]
fmt has solved the issue six month ago:
https://github.com/fmtlib/fmt/issues/3540

**Comment by gabime** [comment]
Use newest fmt version to fix this.

**Comment by NouberNou** [comment]
Is there a plan to update the bundled fmtlib to fix this issue?
