### ISSUE TITLE
error: declaration requires an exit-time destructor

### ISSUE THREAD

**Issue by Chingliu** [gabime/spdlog#2992]
In file included from ../..\third_party/spdlog/include/spdlog/spdlog.h:13:
In file included from ../../third_party/spdlog/include\spdlog/details/registry.h:121:
../../third_party/spdlog/include\spdlog/details/registry-inl.h(241,21): error: declaration requires an exit-time destructor [-Werror,-Wexit-time-destructors]
    static registry s_instance;
                    ^
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by tt4g** [comment]
Since the destructor exists, it is thought to be a compiler bug or the source code has been modified.

https://github.com/gabime/spdlog/blob/696db97f672e9082e50e50af315d0f4234c82397/include/spdlog/details/registry-inl.h#L50
