### ISSUE TITLE
Variable CHAR_WIDTH from format.h clashes with define from limits.h

### ISSUE THREAD

**Issue by th0br0** [gabime/spdlog#300]
Hey,

currently, `spdlog/fmt/bundled/format.h` uses `CHAR_WIDTH` as variable identifier.
However, this clashes with the define from `limits.h` if the file was included beforehand. 

The variable name is only used in `visit_char` here: https://github.com/gabime/spdlog/blob/master/include/spdlog/fmt/bundled/format.h#L2236

Could the variable be renamed to _CHAR_WIDTH (or similar) to avoid the conflict? I'll be happy to provide a PR if you tell me your preferred naming scheme here.

**Comment by gabime** [comment]
Hi,

format.h is part of fmt library. spdlog only bubdles it. please open an issue in the fmt lib repo and I will be happy to update to the fixed version of fmt

**Comment by vitaut** [comment]
Already fixed in https://github.com/fmtlib/fmt/commit/abbefd71666055daac9e14e78262620f9e845850 (https://github.com/fmtlib/fmt/issues/398).

**Comment by gabime** [comment]
Fixed in 6128a87da239228603758fef9dfcb9ea0ab47f3f (updated to latest version of fmtlib)
Thanks @vitaut
