### ISSUE TITLE
mirror dialog needs to revert when cancel pressed

### ISSUE THREAD

**Issue by gr5** [gabime/spdlog#3004]
when mirror dialog is visible and you change values (such as mirror diameter), there are two issues:
1) it changes it in the registry instantly
2) it changes it in the official variable visible to other code instantly

Dale may have fixed number 1 above already while working on annular polynomials (2/8/2024) but number 2 still needs fixing.

If we need to store variables like mirror diameter, even temporarily, they should go into a private variable until the Ok button is pressed and then copied to the location that all the other code accesses.

**Comment by tt4g** [comment]
Is this a spdlog issue?

**Comment by gr5** [comment]
Crap.   Sorry!  Wrong project!
