### ISSUE TITLE
spdlog not adaptable with newer versions of fmt

### ISSUE THREAD

**Issue by askraskr** [gabime/spdlog#3007]
I just installed the latest version of [fmt](https://github.com/fmtlib/fmt) library apparently `<fm/core.h>` and `<fmt/fmt.h>`  header files have been deleted or at least they're not gonna be installed after installing fmt with `make install` or `cmake --install build-dir`. So when I try to build spdlog library using external fmt (`option(SPDLOG_FMT_EXTERNAL "Use external fmt library instead of bundled" ON)`), it fails because it needs `<fmt/core.h>` and `<fmt/fmt.h>`.

**Comment by tt4g** [comment]
The `fmt/include/core.h` is still there in the last commit fmtlib/fmt@44c3fe1ebb466ab5c296e1a1a6991c7c7b51b72e .

- https://github.com/fmtlib/fmt/blob/44c3fe1ebb466ab5c296e1a1a6991c7c7b51b72e/include/fmt/core.h

The header file `fmt/fmt.h` does not exist in the fmt library as far as I know.

**Comment by tt4g** [comment]
Are you reporting the same problem with #2989?
v2.x branch is a work in progress.

**Comment by askraskr** [comment]
@tt4g  `core.h` header is in the commit, but after building the fmt library and installing it with make or cmake, it's not available in fmt folder.

![Screenshot_2024-02-10_11-05-04](https://github.com/gabime/spdlog/assets/143619332/015bfc50-dbc2-4558-8dbe-237f467d62b1)

and regarding `fmt.h`, in `spdlog/include/spdlog/common.h`, line 50 includes `#include <spdlog/fmt/fmt.h>`. But even when I'm building spdlog with external fmt, I get the following error:
```
/home/user0/spdlog/include/spdlog/common.h:50:10: fatal error: spdlog/fmt/fmt.h: No such file or directory
   50 | #include <spdlog/fmt/fmt.h>
```

**Comment by tt4g** [comment]
The problem of `/usr/local/include/fmt/core.h` not being installed is not worth discussing here.
Please report it to the fmt repository.

 `spdlog/fmt/fmt.h` is a spdlog header file, not the fmt library.
Is this header file installed?

**Comment by askraskr** [comment]
@tt4g `spdlog/fmt/fmt.h` is installed. yes. but when I'm builing spdlog with external fmt, I still the same error.

**Comment by tt4g** [comment]
If you are using the installed spdlog, then you should be building your own project.
If there are conflicting directory or file names in the header file search path when you build your project, some header files may not be found.
Output the header file search information in the compiler debug options to see from which path the compiler is looking for header files.

e.g. `VERBOSE=1 make`: https://stackoverflow.com/questions/17690414/c-make-show-where-include-is-searching-for-files
