### ISSUE TITLE
[Possible Bug] : undesired deletion of logger from registry(loggers_ map) 

### ISSUE THREAD

**Issue by raj17ce** [gabime/spdlog#3016]
Steps to produce
1. Created a shared pointer of logger class and added it to registry.
```C++
std::shared_ptr<spdlog::logger> myLogger = std::make_shared<spdlog::logger>("myLogger");
spdlog::register_logger(myLogger);
```
2. Set this logger to default logger
```C++
spdlog::set_default_logger(myLogger);
```

3. Create another shared pointer to a new logger object and set it default.
```C++
std::shared_ptr<spdlog::logger> myLogger2 = std::make_shared<spdlog::logger>("myLogger2");
spdlog::set_default_logger(myLogger2);
```

4. when trying to access the first pointer(myLogger) from registry using get("myLogger") method, it returns nullptr.
```C++
auto myLogger = spdlog::get("myLogger");
```

This is undesirable, as I registered myLogger into the registry. But changing the default logger not only changed the default logger but also deleted it from the registry map loggers_ .

I tried to track the issue, and I found that while setting another default logger, the entry for the previous logger is erased from the registry map loggers_. 

[File] : registry-inl.h
[Function]  : 

```C++
SPDLOG_INLINE void registry::set_default_logger(std::shared_ptr<logger> new_default_logger) {
    std::lock_guard<std::mutex> lock(logger_map_mutex_);
    // remove previous default logger from the map
    if (default_logger_ != nullptr) {
        loggers_.erase(default_logger_->name());
    }
    if (new_default_logger != nullptr) {
        loggers_[new_default_logger->name()] = new_default_logger;
    }
    default_logger_ = std::move(new_default_logger);
}
```

Inside the first if block, the entry is being erased.

**Comment by gabime** [comment]
I agree. Seems undesirable.Maybe the fix would be just set the `default_logger_` without touching the loggers_ at all. I can’t recall though why it was implemented like this.

**Comment by raj17ce** [comment]
Should I create a Pull Request removing the below if condition ??
```C++
if (default_logger_ != nullptr) {
        loggers_.erase(default_logger_->name());
}
```
