### ISSUE TITLE
Doesn't compile on OSX

### ISSUE THREAD

**Issue by ghost** [gabime/spdlog#303]
When using spdlog on OSX (current git head), I get:

```
include/spdlog/details/os.h:347: error: expected value in expression
      ((_POSIX_C_SOURCE >= 200112L) && ! _GNU_SOURCE) // posix version
                                                    ^
```

and

```
include/spdlog/details/os.h:355: error: no matching conversion for functional-style cast from 'int' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
    return std::string(strerror_r(err_num, buf, buf_size));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Compiling with Apple LLVM version 7.3.0 (clang-703.0.31)

**Comment by nuuman** [comment]
Seems like spdlog is very sensitive to include file ordering. Including spdlog.h first helped.

Is this really a requirement?

**Comment by gabime** [comment]
> Seems like spdlog is very sensitive to include file ordering. Including spdlog.h first helped.

Which ordering breaks the build?

**Comment by nuuman** [comment]
@gabime Well, it seems that I have to put #include "spdlog/spdlog.h" above everything else to get reliable compiles.

**Comment by gabime** [comment]
can you give concrete example so i can reproduce?

**Comment by nuuman** [comment]
My codebase is closed source  (seem to be non-trivial to create a test case, the error happens when spdlog is used  is used in large projects)

**Comment by mutantkeyboard** [comment]
@gabime It'd be nice to mention that in order to include this lib properly it needs to be copied into the include path which is by default something like: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`
At least that's how I got it to work on macOS Sierra

**Comment by gabime** [comment]
@mutantkeyboard Not sure I understand. why this specific path?

**Comment by mutantkeyboard** [comment]
@gabime Since I use a lot of console-based programs, I prefer having the most used libraries available system-wide. By copying it into the system-include path I have spdlog available in any project I work with, by simply invoking it with `#include <spdlog/spdlog.h>`

**Comment by gabime** [comment]
@mutantkeyboard 👍
