### ISSUE TITLE
payload in callback_sink getting trailing garbage

### ISSUE THREAD

**Issue by craydog61** [gabime/spdlog#3033]
The payload string from const spdlog::details::log_msg &msg is getting trailing garbage characters. Here is the logger set up:

  auto abCallbackSink =
     std::make_shared<spdlog::sinks::callback_sink_mt>([&](const spdlog::details::log_msg &msg)
  {
    std::string payloadStr(msg.payload.data());

std::cout << "payload: " << str<< std::endl;
  
  });

  LoggerSinks.push_back(abCallbackSink);
  std::shared_ptr<spdlog::logger> log =
     std::make_shared<spdlog::logger>(LOGGER, begin(LoggerSinks), end(LoggerSinks));

  spdlog::register_logger(log);

Code for sending the message:
Strings were verified as correct before calling the spdlog.

spdlog::get(LOGGER)->info(  "test msg);

   

Any idea why this would happen?

**Comment by tt4g** [comment]
The code is broken so I can't read exactly what you are doing.
Please use markdown formatting when providing your code.
See: https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by tt4g** [comment]
It appears that the reason is that the length of the string data is not passed.

```diff
 auto abCallbackSink =
 std::make_shared<spdlog::sinks::callback_sink_mt>([&](const spdlog::details::log_msg &msg)
 {
-std::string payloadStr(msg.payload.data());
+std::string payloadStr(msg.payload.data(), msg.payload.size());
 
 std::cout << "payload: " << payloadStr << std::endl;
 
 });
```

**Comment by craydog61** [comment]
tt4g that was it! Thank you!
