### ISSUE TITLE
wstr_to_utf8buf throw exception

### ISSUE THREAD

**Issue by Tomas-Zhu** [gabime/spdlog#3038]
In "wstr_to_utf8buf" function, memory_buf_t 's size is a const value of 250, (wstr_size+1)*2 is less than 250, so there is no resizing of the result_size. In next WideCharToMultiByte call, this step went wrong.The last error is ERROR_INSUFFICIENT_BUFFER(122)(0x7A).
My test string is"OnPlayerStateChanged:state not changed 〈1〉叶心音的父亲遭人陷害入狱，男友不救反而出国，反而被他弟弟陆景霄救下。可她不知道就是男友陷害的父亲，而自己却已经爱上男友的弟弟！《总裁的金丝雀》,2,1", and can reproduce of this issue. 

![wstr_to_utf8buf](https://github.com/gabime/spdlog/assets/72930792/f486283b-3216-4b05-92f6-bab9920da012)

**Comment by tt4g** [comment]
PR is welcome.
