### ISSUE TITLE
Sdplog thread in synchronous mode

### ISSUE THREAD

**Issue by NahuFigueroa97** [gabime/spdlog#3039]
Hi @gabime ! great job! I have a doubt with the synchronous mode, since I understand it should not launch any thread, in fact I do not use the spdlog::init_thread_pool() function. But when I do the thread analysis in my application I see that sdplog creates a thread. What is this about? Is there a configuration to not launch that thread or is it inevitable?

**Comment by tt4g** [comment]
Even if it is a synchronous logger, calling `spdlog::flush_every()` will create a thread that executes the flush periodically.

**Comment by NahuFigueroa97** [comment]
thank you! I have a doubt as to why ASAN gave me a race condition. Maybe it was a false positive. Is it advisable to do a shutdown at the end of the program?

**Comment by tt4g** [comment]
>  Is it advisable to do a shutdown at the end of the program?

Yes. It is recommended to call `spdlog::shutdown()`.

**Comment by NahuFigueroa97** [comment]
thanks!
