### ISSUE TITLE
In class backtracer  do we rellay need  variable enabled_  be atomic？

### ISSUE THREAD

**Issue by ljgdsq** [gabime/spdlog#3040]
i found backtracer modify enabled_   in two place and after lock. so do we rellay need  variable enabled_  be atomic？

**Comment by tt4g** [comment]
This is because backtracer is used inside the logger and the logger's logging methods are thread-safe API: https://github.com/gabime/spdlog/wiki/1.1.-Thread-Safety

**Comment by ljgdsq** [comment]
> This is because backtracer is used inside the logger and the logger's logging methods are thread-safe API: https://github.com/gabime/spdlog/wiki/1.1.-Thread-Safety

@tt4g i know it. i mean enabled_ is already under lock. so it is safe control.it may be normal variable ?

**Comment by tt4g** [comment]
No. The following API (`backtracer::enabled()`) is not thread-safe.

- https://github.com/gabime/spdlog/blob/ae525b75c31adaad130dd4501d37ff632ec5eade/include/spdlog/logger.h#L266-L267
- https://github.com/gabime/spdlog/blob/ae525b75c31adaad130dd4501d37ff632ec5eade/include/spdlog/details/backtracer-inl.h#L41
