### ISSUE TITLE
flush policy

### ISSUE THREAD

**Issue by NahuFigueroa97** [gabime/spdlog#3045]
I have a quick question. In what cases is it necessary to use flush_every()? since it raises a thread and I don't want it for my application. I think it would be better to use flush_on(level::trace).

**Comment by NahuFigueroa97** [comment]
I read this https://github.com/gabime/spdlog/wiki/7.-Flush-policy and my doubts are: is flush_every() mandatory? Can it be replaced by flush_on and obtain the same result and performance?

**Comment by tt4g** [comment]
`flush_every()` is used when you want to write logs to disk periodically.
It should be used for applications that do not write logs very often.

Consider that it is not to be used as a reason for performance.

**Comment by tt4g** [comment]
By the way, the choice between flushing from threads by `flush_every()` and frequent flushes by `flush_on()` should depend on machine performance.
On a machine with slow disk I/O, frequent log writes to disk by `flush_on()` will slow down the throughput of the application.
In such a case, flushing to dedicated thread (`flush_every()` thread) should improve the throughput of the application.

**Comment by NahuFigueroa97** [comment]
thanks!
