### ISSUE TITLE
Lambda Expression Does Not Compile in GCC 4.8.1 Version

### ISSUE THREAD

**Issue by KaganCanSit** [gabime/spdlog#3050]
### General Info

* Hi, I recently wanted to update the spdn library I was using in my project. The version I was using was version 1.9.2. When I update the library contents and header files and start compiling, I get an error while compiling the expression containing **Lambda Expression**.

### Error Case
> In file included from ../../../common/spdlog/fmt/bundled/core.h:3321:0,
                 from ../../../common/spdlog/fmt/fmt.h:28,
                 from ../../../common/spdlog/common.h:50,
                 from ../../../common/spdlog/spdlog.h:12,
                 from ../../../common/log/Log.cpp:22:
../../../common/spdlog/fmt/bundled/format.h: In static member function 'static int fmt::v9::detail::count_digits(UInt) [with int BITS = 1; UInt = __int128 unsigned]::__lambda2::_FUN(__int128 unsigned)':
../../../common/spdlog/fmt/bundled/format.h:1110:11: internal compiler error: in expand_expr_addr_expr_1, at expr.c:7628
   return [](UInt m) {
           ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://sourceforge.net/projects/mingw-w64> for instructions.

### Workaround (I'm not sure, I didn't have enough time.)
* The part determined as the error point is located in the "format.h" file. [This](https://github.com/gabime/spdlog/blob/73e2e02b42b2d52fc07b88ceb7f91cf95c5f564f/include/spdlog/fmt/bundled/format.h#L1110) When I write the part here as a general function without a lambda expression, I can compile and use it without getting this error.

`int num_digits = 0;`
`do {`
`++num_digits;`
`} while ((n >>= BITS) != 0);`
`return num_digits;`
 
### Information is provided as follows in the Install information file.
> Tested on:
> gcc 4.8.1 and above
> clang 3.5
> Visual Studio 2013

### Information about my development environment;
OS: Windows 10
IDE: Netbeans 8.1
GCC and G++ Version: 4.8.1
![spdnLogBug](https://github.com/gabime/spdlog/assets/59123356/f5c7d283-7c34-40d0-bf77-df7acbf86021)

**Am I missing something? Maybe revision differences may cause this. Or can we find a better solution?**

**Comment by tt4g** [comment]
Duplicate #2333, #2834, #2835

gcc 4.8 is not full support C++11.

**Comment by KaganCanSit** [comment]
Thanks your answer,
I've seen most of the content. I wanted to open it because the situation I experienced seemed simple compared to other compilation errors. Another thing that confused me was the statement "[gcc 4.8.1 and above](https://github.com/gabime/spdlog/blob/73e2e02b42b2d52fc07b88ceb7f91cf95c5f564f/INSTALL#L18)" in the install content. It may be good to point out in the readme description and the install file that compilation errors may be found in various revisions and minor version differences of version 4.8. I can do this when I have free time. I realize that backward compatibility is difficult and tiring. Or if you direct to me another solution, I can help in my spare time.

**Comment by tt4g** [comment]
> Another thing that confused me was the statement "[gcc 4.8.1 and above](https://github.com/gabime/spdlog/blob/73e2e02b42b2d52fc07b88ceb7f91cf95c5f564f/INSTALL#L18)" in the install content.

Thanks for noticing. Could you send me a PR to update `INSTALL.md`?

And the source code under `spdlog/fmt/bundled/` directory is copied from [fmt repository](https://github.com/fmtlib/fmt).
It is not maintained in spdlog and will not be modified here to support gcc 4.8.

**Comment by KaganCanSit** [comment]
I added informational lines and removed test information. (It was written 8 years ago and I thought it could no longer be trusted.) There are explanations in the PR.

Leave me a message if changes are desired. I'll take care of it when I'm available.

**Comment by KaganCanSit** [comment]
Hello again @tt4g @gabime,
I will run the specific tests mentioned in the [merge](https://github.com/gabime/spdlog/pull/3052) request as best I can. I'll check the GCC version and see if it compiles. I won't go into depth. It will cost too much time. Please share better findings.

Before starting testing, I see that the project is compiled with the most up-to-date content.
GCC (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

During testing, CMake 3.29 docker images were giving glibc errors because they were old. I used [3.22.2](https://github.com/Kitware/CMake/tags?after=v3.21.5). I chose it so it wouldn't be too current or too old.

GCC 4.8.4 - Source: [Docker-GCC-4.8.4](https://hub.docker.com/_/gcc/tags?page=1&name=4.8)
Result: It fails when compiling without any changes.
![image](https://github.com/gabime/spdlog/assets/59123356/7f251965-5fa1-44ca-93b2-605cc58acc23)

GCC 4.8.5 - Source: [Docker-GCC-4.8.5](https://hub.docker.com/_/gcc/tags?page=1&name=4.8)
Result: It fails when compiling without any changes.
![image](https://github.com/gabime/spdlog/assets/59123356/3782d836-7f39-4c3d-b6c6-ea05ed2c1267)

GCC 4.9 - Source: [Docker-GCC-4.9](https://hub.docker.com/_/gcc/tags?page=1&name=4.9)
Result: It fails when compiling without any changes.
![image](https://github.com/gabime/spdlog/assets/59123356/09e5b9d4-4697-4405-91b3-9998f065fa29)

Since all common errors come from put_time, I did some research.
https://stackoverflow.com/questions/14136833/stdput-time-implementation-status-in-gcc

GCC 5.1.0 - Source: [Docker-GCC-5.1.0](https://hub.docker.com/_/gcc/tags?page=1&name=5.)
Result: It fails when compiling without any changes.
![image](https://github.com/gabime/spdlog/assets/59123356/ea214a50-f442-447e-b7a6-819fc1aa1092)

GCC 5.5.0 - Source: [Docker-GCC-5.5.0](https://hub.docker.com/_/gcc/tags?page=1&name=5.)
Result: It fails when compiling without any changes.
![image](https://github.com/gabime/spdlog/assets/59123356/b9afd19d-03ad-412a-9cef-574ac7e8c203)

GCC 6.5.0 - Source: [Docker-GCC-6.5.0](https://hub.docker.com/_/gcc/tags?page=1&name=6.)
Result: It fails when compiling without any changes.
![image](https://github.com/gabime/spdlog/assets/59123356/85b79923-995a-454b-bc8a-52ce73c70cfe)


https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.200x
The Formatter structure is a structure added later. I spent a long time. Research must be done to find a definitive version.

We can argue about this. I can give it one last try. However, I think the features of the formatter used here are supported by C++17. For this, I will make one last try in version 7.

GCC 7.5.0 - Source: [Docker-GCC-6.5.0](https://hub.docker.com/_/gcc/tags?page=1&name=7.)
Result: OK
![image](https://github.com/gabime/spdlog/assets/59123356/f414ec35-d6fc-4582-8b19-ba80908cf0ae)

That's all the time I can spare right now. It is necessary to examine between 7.5.0 and 6.5.0. I guess there will be no problem in versions above 7. However, it may be necessary to switch to C++17 standard support instead of C++11 standard support. I do not have qualified information. The final decision is yours.

I would like to decide on the pull request and test part and add this pull request to the project.
See you later.

**Comment by KaganCanSit** [comment]
This information can perhaps be added to an area such as a wiki.

**Comment by gabime** [comment]
Thanks, so the conclusion is 6.5 and above?

**Comment by KaganCanSit** [comment]
> Mar 23, 2024: After testing via official [Docker GCC repositories](https://hub.docker.com/_/gcc), we recommend using GCC 7.1.0 or above to compile spdlog without requiring any modifications.
> 
> | REPOSITORY | TAG    | DOCKER IMAGE ID | CREATED      | RESULT|
> |------------|--------|-----------------|--------------|--------|
> | gcc        | 7.5.0  | 310bcd463946    | 3 years ago  | OK     |
> | gcc        | 7.1    | 855a4f4d1cd9    | 6 years ago  | OK     |
> | gcc        | 6.5.0  | 562a195e29be    | 3 years ago  | FAILS  |
> | gcc        | 5.5.0  | 37139c6da088    | 4 years ago  | FAILS  |
> | gcc        | 5.1    | 1693ea8f6b05    | 8 years ago  | FAILS  |
> | gcc        | 4.9    | 1b3de68a7ff8    | 6 years ago  | FAILS  |
> | gcc        | 4.8.5  | 4e41303e90cb    | 7 years ago  | FAILS  |
> | gcc        | 4.8.4  | 37f96d141111    | 8 years ago  | FAILS  |
> | gcc        | 4.8.3  | e049867013e3    | 9 years ago  | FAILS  |

**Comment by tt4g** [comment]
I am not sure because the error message is not complete, but this is a bug in fmt v9.1.0 that has already been fixed: fmtlib/fmt#3339

Use external fmt, not bundled fmt.

**Comment by KaganCanSit** [comment]
Thanks, I solved this similar to the opened issue. For now, we are focused on detecting the minimum gcc version after the pull request. Unless I made a mistake, the result is as in the comment above.

**Comment by KaganCanSit** [comment]
Hello @tt4g,
Today, I took the fmt library from the master tree and compiled gcc versions. I didn't get any errors. When I compiled the spdlog by updating the header files in the spdlog, I received error. It may be necessary to make adjustments after Fmt is released.

I wanted to give you information. I'm here for issues I can help with.

See you later.

Little talk here -> https://github.com/fmtlib/fmt/pull/3340#issuecomment-2037326286

I am closing the issue because I think this process will take a long time.

**Comment by tt4g** [comment]
@KaganCanSit Thank you for reporting.

Since the spdlog v1.x branch is still on fmt v9, no one else may have noticed the compile errors that occur when using the latest fmt.
If you can avoid the error by fixing spdlog, it would be helpful if you could send PR.

**Comment by KaganCanSit** [comment]
@tt4g I would like to help with this issue after the FMT version is released. 
Enjoy your work
