### ISSUE TITLE
Casting error on Clang 15 (and 17) and GCC 13

### ISSUE THREAD

**Issue by sfulham** [gabime/spdlog#3053]
Hey, I've been trying to build a project on Linux that uses spdlog (and supposedly builds fine on Windows), however I get a casting error as below:

```
candidate function template not viable: no known conversion from 'const std::format_string<unsigned int &, float &>' (aka 'const basic_format_string<char, unsigned int &, float &>') to 'format_string_t<Args...>' (aka 'basic_string_view<char>') for 1st argument
  154 |     void critical(format_string_t<Args...> fmt, Args &&...args)
```

The offending call is `logger->critical(format, std::forward<Args>(args)...);` where this is the function definition 
```
	template<typename... Args>
	void Log::PrintMessage(Log::Type type, Log::Level level, const std::format_string<Args...> format, Args&&... args)
```

`SPDLOG_USE_STD_FORMAT` is defined.

Result of `g++ -v`
```Using built-in specs.
COLLECT_GCC=g++-13
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.1.0-8ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2,rust --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-IvzKaI/gcc-13-13.1.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-IvzKaI/gcc-13-13.1.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.1.0 (Ubuntu 13.1.0-8ubuntu1~22.04)
```

Result of `clang -v`
```clang version 17.0.6 (https://github.com/llvm/llvm-project 6009708b4367171ccdbf4b5905cb6a803753fe18)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/charli/Downloads/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

Thanks in advance

**Comment by tt4g** [comment]
spdlog does not recognize that the compiler supports `std::format_string`, so it uses `std::string_view` as the `format` argument.

https://github.com/gabime/spdlog/blob/73e2e02b42b2d52fc07b88ceb7f91cf95c5f564f/include/spdlog/common.h#L145-L156

C++23 is required because `std::format_string` is a C++23 feature.
I think you have not enabled it with compiler flags.

**Comment by sfulham** [comment]
Thanks @tt4g, it seems as if, even with c++23 set, `__cpp_lib_format` is set to `202106` with libstdc++13.1 and undefined with libc++-17. I'm on PopOS 22.04 so some packages may be a little behind, but these are the latest packages I can seem to find.

**Comment by sfulham** [comment]
It seems if I manually define `__cpp_lib_format` to `202207L` with libc++-17 it works fine, however this is really not a permanent solution.

**Comment by tt4g** [comment]
`__cpp_lib_format >= 202207L` should be a prerequisite for `std::format_string` support.

See `__cpp_lib_format` section in [Feature testing - cppreference.com](https://en.cppreference.com/w/cpp/feature_test) and [P2508R1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2508r1.html).

The fact that it is `202106` means that the compiler does not support `std::format_string`, so using `std::format_string` in `Log::PrintMessage` is a mistake.

**Comment by tt4g** [comment]
> It seems if I manually define `__cpp_lib_format` to `202207L` with libc++-17 it works fine, however this is really not a permanent solution.

If so, it may be a compiler bug.
Please report it to the compiler maintainer.

**Comment by sfulham** [comment]
> > It seems if I manually define `__cpp_lib_format` to `202207L` with libc++-17 it works fine, however this is really not a permanent solution.
> 
> If so, it may be a compiler bug. Please report it to the compiler maintainer.

After some more digging, it seems it isn't a mistake/it is known to be undefined, https://libcxx.llvm.org/FeatureTestMacroTable.html

**Comment by tt4g** [comment]
spdlog cannot use the feature that the compiler does not support.
You should not use `std::format_string`.
