### ISSUE TITLE
I am fellowing Cherno Hazel Engine，and I have include spdlog.h, but spdlog seems has some problem

### ISSUE THREAD

**Issue by SavourSummer** [gabime/spdlog#3054]
>c1xx : fatal  error C1083:  “vendor\spdlog\example\jni\example.cpp”: No such file or directory
1>multisink.cpp
1>c1xx : fatal  error C1083: : “vendor\spdlog\example\multisink.cpp”: No such file or directory
1>errors.cpp
1>c1xx : fatal  error C1083: : “vendor\spdlog\tests\errors.cpp”: No such file or directory
1>file_helper.cpp
1>c1xx : fatal  error C1083: : “vendor\spdlog\tests\file_helper.cpp”: No such file or directory
1>file_log.cpp
1>c1xx : fatal  error C1083: : “vendor\spdlog\tests\file_log.cpp”: No such file or directory

**Comment by SavourSummer** [comment]
![image](https://github.com/gabime/spdlog/assets/76558384/1926c551-6cd6-48cb-9c6a-387b1e5164d2)

**Comment by SavourSummer** [comment]
![image](https://github.com/gabime/spdlog/assets/76558384/93534815-8686-4af8-bca2-dfcd476c5a20)

**Comment by SavourSummer** [comment]
Sometimes it have a  no "benchmark.h" preoblem, but i don‘t need benchmark.h"

**Comment by SavourSummer** [comment]
![image](https://github.com/gabime/spdlog/assets/76558384/9e3edcb5-a309-4a22-be0e-eb7e4e04ba07)

**Comment by sfulham** [comment]
I would suggest you discuss this in [The Cherno's discord server](https://discord.com/invite/thecherno), in the #game-engine-series channel

**Comment by SavourSummer** [comment]
> I would suggest you discuss this in [The Cherno's discord server](https://discord.com/invite/thecherno), in the #game-engine-series channel

Thanks for  your reply, but i think it is a spqlog problem. I include spqlog.h and spqlog generates a wrong in VS2022.

**Comment by tt4g** [comment]
The Hazel project seems to be importing spdlog with Premake.

https://github.com/TheCherno/Hazel/blob/1feb70572fa87fa1c4ba784a2cfeada5b4a500db/Hazelnut/premake5.lua#L16-L25

There may be a problem with the use of Premake.
Please ask in the Hazel repository.

**Comment by SavourSummer** [comment]
> The Hazel project seems to be importing spdlog with Premake.
> 
> https://github.com/TheCherno/Hazel/blob/1feb70572fa87fa1c4ba784a2cfeada5b4a500db/Hazelnut/premake5.lua#L16-L25
> 
> There may be a problem with the use of Premake. Please ask in the Hazel repository.

Thanks for your reply. I seems have found the solution which generates by VS2022 .  First Delete  code  about   example.cpp ,like "<ClCompile Include="src\Hazel\example.cpp" />"  
![image](https://github.com/gabime/spdlog/assets/76558384/53d34ec0-54a8-43c2-9fe9-5bee546b59f0)
 in bellow file
![image](https://github.com/gabime/spdlog/assets/76558384/3c35df9d-9b08-4bd0-83c6-4db6099ed1cb)
and Second Generating again program in VS2022. 
https://stackoverflow.com/questions/16422883/error-c1083-cannot-open-source-file-shouldnt-be-looking-for-the-file-at-all
