### ISSUE TITLE
spdlog for DSP

### ISSUE THREAD

**Issue by navF76** [gabime/spdlog#3055]
I was able to compile spdlog for x64, and it works as expected. But when I try to compile it (using c++ 11) for an analog devices dsp, I see an error message that indicates that the compiler could not find "atomic". I understand this is specific to the device/toolchain I'm using, but in general, are there any workarounds for this?

**Comment by tt4g** [comment]
If C++11 is not fully supported on that platform, spdlog will not compile.

**Comment by gabime** [comment]
Try using the -DSPDLOG_NO_ATOMIC_LEVELS CMake flag

**Comment by navF76** [comment]
Thanks for the suggestion, but the error is still the same. Here's the exact error message - 

**"..\..\external\spdlog\include\spdlog/details/null_mutex.h", line 6: cc2388:  catastrophic error: cannot open source file "atomic"

  #include <atomic>**

**Comment by navF76** [comment]
Thanks for the suggestion, but the error is still the same. Here's the exact error message - 

![image](https://github.com/gabime/spdlog/assets/161812406/491e57d9-f53d-4a8d-bed4-59e351908aff)

**Comment by gabime** [comment]
Try commenting out this include from the file

**Comment by navF76** [comment]
null_mutex.h seems to be required for all sinks, and atomic is used in it for using 'memory_order'. It doesn't seem like I can comment it out.

**Comment by gabime** [comment]
Then I don't see a way to overcome this without further modifications
