### ISSUE TITLE
Custom pattern for log and severity level

### ISSUE THREAD

**Issue by greatsharma** [gabime/spdlog#3057]
The default pattern is `[2024-04-01 09:30:24.522] [info]` but I want to remove the milliseconds from time. For this I removed %e from this pattern `[%Y-%m-%d %H:%M:%S. %e]`. But after this the log severity i.e., error, info etc become colorless. What should be the format so that everything remain same just milliseconds removed.

Also I want custom name for severity like debug and error are 5 chars but warning is more, so if I wanted to restrict all of them to same number of character then how I can do that?

Also we can read the spdlog severity level from env var like this `spdlog::cfg::load_env_levels();` but how I can check what is the log level using if condition. Like I wanted a specific logic to be running only if the log level is debug only.

Also how can I limit the float precision in spdlog? Like in the below log I just wanted to print upto 2 decimal places i.e., 5.81
`[2024-04-01 09:38:23.468] [debug] Menu Cam0 fps: 5.816666666666666`

**Comment by tt4g** [comment]
> But after this the log severity i.e., error, info etc become colorless. What should be the format so that everything remain same just milliseconds removed.

The default format has a color range `%^` and `%$`: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

https://github.com/gabime/spdlog/blob/8fed530bdffbe69304a330be2096c65793b722c2/include/spdlog/pattern_formatter-inl.h#L884-L890

Add a color range to the log pattern.

```diff
-[%Y-%m-%d %H:%M:%S] [%l]
+[%Y-%m-%d %H:%M:%S] [%^%l%$]
```

> Also I want custom name for severity like debug and error are 5 chars but warning is more, so if I wanted to restrict all of them to same number of character then how I can do that?

Define `SPDLOG_LEVEL_NAMES` macro:

https://github.com/gabime/spdlog/blob/8fed530bdffbe69304a330be2096c65793b722c2/include/spdlog/tweakme.h#L102-L107

> lso we can read the spdlog severity level from env var like this `spdlog::cfg::load_env_levels();` but how I can check what is the log level using if condition. Like I wanted a specific logic to be running only if the log level is debug only.

I do not know where you want to get the log level.
Call `spdlog::get_level()` if you want a global log level for spdlog.
Duplicate #1854, #1357 if it is a custom sink.

> Also how can I limit the float precision in spdlog?

The logging argument format uses [fmt library](https://github.com/fmtlib/fmt).
See fmt API: https://fmt.dev/10.1.1/syntax.html

**Comment by greatsharma** [comment]
Thanks, this worked for me.
