### ISSUE TITLE
sometimes print the log, and sometimes it don't.

### ISSUE THREAD

**Issue by li-xiangyun-z** [gabime/spdlog#3058]
I create a winmain process using js spawn and create a console with this winmain process, and reopen stderr,then call spdlog::info().
I find this to be a problem:
sometimes print the log, and sometimes it don't.

I tried different methods and found that when I run WinMain directly, the spdlog::info() can always be printed.
When I create WinMain in Spawn, I can also print the log using std::cerr.

But when you use spawn and spdlog, you can sometimes print the log to stderr, and sometimes you don't.

When I use spdlog::info to print to a file, it always saves to the file.

Hopefully someone can give a little guiding advice

**Comment by gabime** [comment]
Please provide code to reproduce the problem.

**Comment by tt4g** [comment]
I don't know what programming language API `spawn` is, but processes that are launched from another process may not have STDOUT and STDERR attached.
If the process doing the `spawn` does not have STDOUT/STDERR attached, there is no guarantee that they will work.

**Comment by li-xiangyun-z** [comment]
> I don't know what programming language API `spawn` is, but processes that are launched from another process may not have STDOUT and STDERR attached. If the process doing the `spawn` does not have STDOUT/STDERR attached, there is no guarantee that they will work.

Thank you very much, your suggestion works.

**Comment by li-xiangyun-z** [comment]
> Please provide code to reproduce the problem.

Sorry to reply now, the past three days were our holiday
