### ISSUE TITLE
Logging messages within a custom sink causes a dead lock?

### ISSUE THREAD

**Issue by WorstCodeWay** [gabime/spdlog#3064]
I'm developing a `TcpSink(server)`, I have overrided `sink_it_` which will send messages to network and works just fine.

Pushing all sinks to a logger
```c++
SpdLogger logger;
logger->sinks().push_back(console_sink);
logger->sinks().push_back(file_sink);
logger->sinks().push_back(tcp_sink); // customized TcpSink(server)
```
Overriding sink for TcpSink
``` c++
void sink_it_(const spdlog::details::log_msg &msg) override
{
  // formatted message buffer ...
  int error = send(bufer ...);  // here will give a error when connection is broken
  if(error < 0)
    logger->error("some errors");
  // ...
}
```
When there is a disconnection, `sink_it_` will break with a error, like "Connection reset by peer", that is normal. But log this error message with logger will cause a dead lock, right?

So how to prevent that situation? For my implementation, I create two loggers, one for console_sink and file_sinke, the other for tcp_sink. Then if I want to log within TcpSink, call first logger.

Is that suitable?

**Comment by gabime** [comment]
Yes, sounds ok.
