### ISSUE TITLE
set close-on-exec flag when open log file

### ISSUE THREAD

**Issue by scottzhang** [gabime/spdlog#307]
http://danwalsh.livejournal.com/53603.html

I am using spdlog on my server, which will fork something but spdlog fd passed to child. 
If we change 
details/os.h:    auto *file = fopen(filename.c_str(), "r");
to 
details/os.h:    auto *file = fopen(filename.c_str(), "re");

Extra "e", then everything fixed.

**Comment by gabime** [comment]
related #301

**Comment by gabime** [comment]
I am thinking to add a macro to control this  this in tweakme.h (with default as current behavior)

**Comment by gabime** [comment]
Fixed in 92db8115b77d2a63ceb8fa6741f5d7650c1ab299

To close on exec got to tweak,me.h and uncomment:
```c++
#define SPDLOG_PREVENT_CHILD_FD
```
