### ISSUE TITLE
Is there a plan to update the included libfmt to fix fmtlib/fmt#3540?

### ISSUE THREAD

**Issue by NouberNou** [gabime/spdlog#3070]
We do not use libfmt anywhere else in our code so we'd prefer to not use the external library, but we do use spdlog across a number of projects and it'd be nice to not have to play whack a mole with pragma warning disables.

**Comment by tt4g** [comment]
As far as I know, there are no plans to do.
See #2767

**Comment by NouberNou** [comment]
I wonder if, in that case, if the compiler version is at the level that raises this warning, automatically using `std::format` instead would be a good plan?

As of right now, spdlog doesn't work out of the box on Windows and the latest MSVC.

**Comment by tt4g** [comment]
You can use external fmt by defined CMake variable `SPDLOG_FMT_EXTERNAL`.
This allows to use a different version fmt.

Wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-use-external-fmt-library-instead-of-the-bundled

**Comment by NouberNou** [comment]
That is not really an actual solution given the current structure of the library. See the initial post, the nice thing about spdlog was that it was a one stop library, adding another dependency when its the only library that uses it (for us at least), especially when previously the included libfmt _did work_ is rather frustrating.

Additionally, none of the demos on the front README will even work for Windows users right now. It'd frankly label this library as deprecated for Windows at the moment going forward for anyone who'd suggest using it.

Either remove the included libfmt and require external libfmt or `std::format`, deprecate Windows as a supported platform and adjust the documentation, or update the included libfmt.

**Comment by tt4g** [comment]
I don't think `checked_array_iterator` is the cause of the unavailability yet, since it only gives the deprecated warning `C4996`.

If you really do not want to use external fmt, use `std::format` by CMake variable `SPDLOG_USE_STD_FORMAT`.

https://github.com/gabime/spdlog/blob/a2b4262090fd3f005c2315dcb5be2f0f1774a005/CMakeLists.txt#L90

**Comment by gabime** [comment]
I’ve tried to update the bundled fmt to 10.2.1 but encountered problems when trying to build spdlog with the -DSPDLOG_SHARED_LIB=ON in windows. See https://github.com/gabime/spdlog/commit/d8e0ad46bfc2cad56f9a6d50cebc63bddd768633 and the [ci error](https://ci.appveyor.com/project/gabime/spdlog/builds/49507264/job/j103108xf0rueaae) 

If anyone finds a fix, It would be great. We could then bundle newest fmt again.

**Comment by lalitshankarch** [comment]
For `cmake` users, setting `CMAKE_CXX_STANDARD` to 11 is a temporary fix.

**Comment by gabime** [comment]
Closed. Updated to fmt 10.2.1 in spdlog 1.14.0
