### ISSUE TITLE
Show the lower digits of numeric fields, such as thread-id

### ISSUE THREAD

**Issue by randomizedthinking** [gabime/spdlog#3074]
I would like the log-file shows the last three digits of the thread id field to save some space. The logger setting is as follows: `set_pattern("(%3!t) >> %v")`. But it would keep the higher three digits of the thread-id. To me, the lower 3-digits would be enough to distinguish threads but not the higher 3-digits.

Is there way to add an option to truncate numeric values to keep the lower components?

**Comment by tt4g** [comment]
You can use custom formatter.
See: https://github.com/gabime/spdlog/issues/2306#issuecomment-1908090502

**Comment by randomizedthinking** [comment]
Thanks, @tt4g. I will check it out...
