### ISSUE TITLE
Does the dist_sink support Factory pattern to create a new logger?

### ISSUE THREAD

**Issue by osirisQdt2810** [gabime/spdlog#3085]
In my initialization context, i have created a logger using sink `dist_sink_mt`:
 ```
         auto consoleSink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        auto rotatingFileSink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(folderName_  + "/System.txt", bit2Mb_ * size, duplicate);
        std::vector<spdlog::sink_ptr> sinks;
        sinks.push_back(consoleSink);
        sinks.push_back(rotatingFileSink);
        distSink_ = std::make_shared<spdlog::sinks::dist_sink_mt>(sinks);
        logMap_[logName_] = std::make_shared<spdlog::logger>(logName_, distSink_);
        rootLog_ = logMap_[logName_];
        rootLog_->set_pattern(pattern_);
        rootLog_->set_level(static_cast<spdlog::level::level_enum>(level));
        rootLog_->flush_on(spdlog::level::trace);
```
and in the later context in runtime, i have tried to create another logger also using this type of sink for wrapping another `rotating_file_sink`
```
logger = std::make_shared<spdlog::logger>(anotherLogName, anotherDistSink);
````
But when i using this one, like 
```
logger->debug("...");
```
The log seems to appear in the first `rotating_file_sink`. If i use factory like
``` logger = spdlog::rotating_logger_mt(...)```
The workflow works fine. But my case is i wanna create a new dist_sink with multiple sinks, so is there anyway that solve this problem? Or did i my something that make the code is not correct?

**Comment by tt4g** [comment]
I'm not sure what you are doing with your code since there is no code creating `anotherDistSink`.
Therefore, I cannot give you advice on what exactly you should do to make them behave the way you want them to.

**Comment by osirisQdt2810** [comment]
> I'm not sure what you are doing with your code since there is no code creating `anotherDistSink`. Therefore, I cannot give you advice on what exactly you should do to make them behave the way you want them to.

I missed something in my code so have a misunderstanding about `dist_sink`, but thanks for your reply.

**Comment by tt4g** [comment]
Does this mean that the problem has been solved? If so, please close this issue.
