### ISSUE TITLE
COMBINE "daily_file_sink" AND "rotating_file_sink"

### ISSUE THREAD

**Issue by Zshowstopper** [gabime/spdlog#3086]
If i want to split daily files by size ,how can i do it

**Comment by tt4g** [comment]
Duplicate #2702

There is no module supports that feature, but you can create custom sink.
See Wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by Zshowstopper** [comment]
Thank you! I will try.
