### ISSUE TITLE
How register work?

### ISSUE THREAD

**Issue by vipcxj** [gabime/spdlog#3088]
For example I want to create many many logger and bind each to a object instance.
```c++
class Object {
  std::shared_ptr<spdlog::logger> m_logger;
}
```
When the object is destroied, will the logger be unregistered?
What about all m_loggers of objects with same name?
What about all m_loggers of objects with different name?
Will spdlog::set_level (set_pattern, set_formatter, set_err_handler) effect m_loggers?

**Comment by tt4g** [comment]
You need to register and unregister loggers to the spdlog registry with `spdlog::register_logger()` and `spdlog::drop()`.
`spdlog::*` API affects all loggers registered in the registry.

`spdlog::set_level()` calls `spdlog::logger::set_level()` of the loggers registered in the registry.

spdlog identifies loggers registered in the registry by name (`spdlog::logger::name()`),
You can get it by passing the logger name to `spdlog::get()`.

> When the object is destroied, will the logger be unregistered?

No.

> What about all m_loggers of objects with same name?
> What about all m_loggers of objects with different name?

Loggers registered in the registry cannot use the same name.

> Will spdlog::set_level (set_pattern, set_formatter, set_err_handler) effect m_loggers?

Yes.

**Comment by vipcxj** [comment]
@tt4g Can I use the logger without register it? Then when the object is destroyed, will m_logger be safely destroyed?

**Comment by tt4g** [comment]
You can use the logger without registering it in the registry.
However, it is no longer under the control of spdlog, so it is not affected by the `spdlog::*` API.

`m_logger` will be safely deleted if the destructor is called by `std::shared_ptr`.
