### ISSUE TITLE
[Question] logger sink question

### ISSUE THREAD

**Issue by chenyongquan2** [gabime/spdlog#3093]
How can I configure a logger to rotate the log files daily, while also rotating them based on the file size?

To achieve this, you can use the daily_file_sink_mt and size_file_sink_mt sinks provided by spdlog, and combine them together.
 
I Have tried 
```
auto daily_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>(log_file_path, 2, 30);
auto rotating_file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(log_file_path, max_size, max_files, true); 
auto logger = std::make_shared<spdlog::logger>(name, std::initializer_list<spdlog::sink_ptr>{rotating_file_sink,daily_sink});
```
But it didn't turn out the way I expected.

**Comment by tt4g** [comment]
Duplicate #2702
