### ISSUE TITLE
[Question] Can spdlog's log level be instantly updated?

### ISSUE THREAD

**Issue by chenyongquan2** [gabime/spdlog#3099]
spdlog's load_argv_levels supports reading the log level from the LOG_LEVEL environment variable and then setting the log level. So, if the value of the LOG_LEVEL environment variable is changed during the program's runtime, can spdlog's log level be instantly updated

**Comment by gabime** [comment]
No. There is no way.

**Comment by chenyongquan2** [comment]
During the execution of the program, I modify the value of the environment variable SPDLOG_LEVEL, and I also have a thread that constantly executes ```spdlog::cfg::load_env_levels();``` Can I use the above method to change the log_level of my spdlog at runtime? Or are there other ways to dynamically adjust the output log_level value during program runtime?

In my current project, I expect to dynamically enable the output of trace-level logs only in some exceptional cases (this log printing has a very high frequency, so I hope to print it only when I need it, in order to avoid the situation of overly large logs), while in normal cases, I expect to only output info-level logs.
