### ISSUE TITLE
Compile Issue using std::atomic_int

### ISSUE THREAD

**Issue by sbrkopac** [gabime/spdlog#310]
Hi There,

Using Visual Studio Community 2013. I get the following error when attempting to compile in SPDLOG:

`lib\spdlog-0.11.0\include\spdlog/sinks/sink.h(18): error C2664: 'std::atomic_int::atomic_int(const std::atomic_int &)' : cannot convert argument 1 from 'spdlog::level::level_enum' to 'const std::atomic_int &'
1>          Reason: cannot convert from 'spdlog::level::level_enum' to 'const std::atomic_int'
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called`

Is SPDLOG no longer compatible with Visual Studio 2013?

**Comment by sbrkopac** [comment]
Putting the preprocessor definition "SPDLOG_NO_ATOMIC_LEVELS" allows me to continue the compilation. Perhaps we need an extra check for the visual studio version as well?

**Comment by gabime** [comment]
I think it was already fixed(8c67d6e05ec76a7d4f1b61167712421e06e539bc) .
Please update to latest version and try again

**Comment by sbrkopac** [comment]
Yup. That fixed it. Thank you.
