### ISSUE TITLE
MDC ignores `SPDLOG_NO_TLS`

### ISSUE THREAD

**Issue by GaryOderNichts** [gabime/spdlog#3101]
The in version 1.14.0 added Mapped Diagnostic Context (MDC) support ignores the `SPDLOG_NO_TLS` define and always creates a `thread_local` variable in `mdc::get_context`.
https://github.com/gabime/spdlog/blob/c3aed4b68373955e1cc94307683d44dca1515d2b/include/spdlog/mdc.h#L40-L43
This breaks support for systems where thread local storage isn't available.

**Comment by gabime** [comment]
So such systems can choose not to include mdc.h

**Comment by AntoineMurat** [comment]
I confirm the issue; we are also affected. While it could be mitigated with a (slow) workaround that would use the tid, I believe a reasonable hotfix would be to disable MDC entirely when `SPDLOG_NO_TLS` is set.

**Comment by gabime** [comment]
I agree. PR is welcome
