### ISSUE TITLE
linker error on ansicolor_stdout_sink on windows

### ISSUE THREAD

**Issue by yalov** [gabime/spdlog#3103]
stdout_color_sink_mt compile and run without problems:
``` cpp
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/ansicolor_sink.h>

int main(int argc, char* argv[]) {
    auto sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    //auto sink = std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>();
    spdlog::set_default_logger(std::make_shared<spdlog::logger>("sink", sink));
    spdlog::info("Welcome to spdlog!");
    return EXIT_SUCCESS;
}
```
The same code for ansicolor_stdout_sink_mt
``` cpp
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/ansicolor_sink.h>

int main(int argc, char* argv[]) {
    //auto sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    auto sink = std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>();
    spdlog::set_default_logger(std::make_shared<spdlog::logger>("sink", sink));
    spdlog::info("Welcome to spdlog!");
    return EXIT_SUCCESS;
}
```
have the linker error:

Error	LNK2019	unresolved external symbol "public: __cdecl spdlog::sinks::ansicolor_stdout_sink<struct  spdlog::details::console_mutex>::ansicolor_stdout_sink<struct spdlog::details::console_mutex>(enum spdlog::color_mode)" (??0?$ansicolor_stdout_sink@Uconsole_mutex@details@spdlog@@@sinks@spdlog@@QEAA@W4color_mode@2@@Z) referenced in function "public: __cdecl std::_Ref_count_obj2<class spdlog::sinks::ansicolor_stdout_sink<struct spdlog::details::console_mutex> >::_Ref_count_obj2<class spdlog::sinks::ansicolor_stdout_sink<struct spdlog::details::console_mutex> ><>(void)" (??$?0$$V@?$_Ref_count_obj2@V?$ansicolor_stdout_sink@Uconsole_mutex@details@spdlog@@@sinks@spdlog@@@std@@QEAA@XZ)	D:\project\out\build\x64-release\project	D:\project\out\build\x64-release\main.cpp.obj	1		

Windows, VS2022, C++17, cmake, ninja
spdlog was added as subfolder
``` cmake
// parent
add_subdirectory(spdlog)
add_subdirectory(logger-tester)
```
``` cmake
// logger-tester
target_link_libraries(logger-tester PRIVATE spdlog)
```

Any idea that could be the problem there?

**Comment by yalov** [comment]
got it, wincolor_stdout_sink for windows
``` cpp
#ifdef _WIN32
using stdout_color_sink_mt = wincolor_stdout_sink_mt;
using stdout_color_sink_st = wincolor_stdout_sink_st;
using stderr_color_sink_mt = wincolor_stderr_sink_mt;
using stderr_color_sink_st = wincolor_stderr_sink_st;
#else
using stdout_color_sink_mt = ansicolor_stdout_sink_mt;
using stdout_color_sink_st = ansicolor_stdout_sink_st;
using stderr_color_sink_mt = ansicolor_stderr_sink_mt;
using stderr_color_sink_st = ansicolor_stderr_sink_st;
#endif
```

**Comment by yalov** [comment]
Or maybe ansi_sink should work on windows?

How to make gray with the wincolor_stdout_sink ?

The typical codes  (`#define DARK_GRAY "\033[90m"`) in the message itself is working

**Comment by tt4g** [comment]
Windows did not support ANSI escape sequences until midway through Windows 10, so it is unlikely that Windows support was considered at the time ansi_color_sink was developed.

**Comment by yalov** [comment]
thanks, I will open new issue about advansed support of ANSI escape sequences miltiplatform (win10, linux)
