### ISSUE TITLE
How to print boost::program_options::options_description, that aleady have the std::ostream& operator<< overload?

### ISSUE THREAD

**Issue by yalov** [gabime/spdlog#3105]
Hello, 
can spdlog use the

```
friend BOOST_PROGRAM_OPTIONS_DECL std::ostream& operator<<(std::ostream& os, const options_description& desc);
```
straight away, without the std::ostringstream ?

``` cpp
boost::program_options::options_description options_desc("Options");
std::ostringstream oss;
oss << options_desc;
spdlog::info(oss.str());
```

**Comment by tt4g** [comment]
Since spdlog formats log arguments by fmt library, you can format the object by defining `fmt::formatter<T>`.

See WIki: https://github.com/gabime/spdlog/wiki/1.-QuickStart#log-user-defined-objects
See also fmt document: https://fmt.dev/latest/api.html#formatting-user-defined-types

Example:

```cpp

// Define `template <> struct fmt::formatter<T>` here.

T object;
spdlog::info("{}", object);
```

**Comment by yalov** [comment]
thanks, somehow I missed the `fmt::formatter` line in the QuickStart
