### ISSUE TITLE
Can't log static const class members - causes linker errors

### ISSUE THREAD

**Issue by rhd** [gabime/spdlog#311]
Hi,

I'm basically getting linker errors because of this:
https://stackoverflow.com/questions/3025997/defining-static-const-integer-members-in-class-definition

And wanted to know if there is a reasonable fix you can apply on your end to basically take a copy instead of a reference of the static const class member.

My temp fix (which makes me feel dirty) has been to do this (notice the `int()`):

```cpp
console->info("the val is {}", int(MyClass::MyVal));
```

If this has no reasonable fix, please close this issue...

Thanks!

**Comment by gabime** [comment]
Not sure how to fix this. So I will close it
