### ISSUE TITLE
Do not include fmt headers if SPDLOG_USE_STD_FORMAT is defined?

### ISSUE THREAD

**Issue by Holt59** [gabime/spdlog#3110]
The include for `spdlog/fmt/fmt.h` is currently not guarded from `SPDLOG_USE_STD_FORMAT` in `common.h`.

It would be nice to guard it so that one does not need to include the `fmt` subfolder if using the `spdlog` header-only version.

**Comment by tt4g** [comment]
The header include branch in `spdlog/fmt/fmt.h` so there is no problem you are worried about.

https://github.com/gabime/spdlog/blob/c3aed4b68373955e1cc94307683d44dca1515d2b/include/spdlog/fmt/fmt.h#L14-L30

**Comment by Holt59** [comment]
> The header include branch in the fmt library is done in `spdlog/fmt/fmt.h` so there is no problem you are worried about.
> 
> https://github.com/gabime/spdlog/blob/c3aed4b68373955e1cc94307683d44dca1515d2b/include/spdlog/fmt/fmt.h#L14-L30

Thanks, this means I at least need to ship the `fmt.sh`, but that's small enough.
