### ISSUE TITLE
ANSI escape sequences multiplatform (win10, linux)

### ISSUE THREAD

**Issue by yalov** [gabime/spdlog#3111]
Hello, It there a way to have colors set up as 

trace and debug — full line gray (GRAY = "\033[90m"), not just from `%^` to `%$`, but full line

info, warn, error, critical — full line white (normal), only the level tag is colored (default colors and a pattern se up as `%^%l%$` are ok)

**Comment by tt4g** [comment]
Related #3103

wincolor_sink is already provided that uses the old Windows color output API.
However, wincolor_sink does not use ANSI escape sequences, so you can create a custom sink if you really want to use it.

See wiki: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

stdout_color_sink and stderr_color_sink, [introduced in `README.md`](https://github.com/gabime/spdlog/blob/v1.14.1/README.md#create-stdoutstderr-logger-object), are aliases for ansicolor_sink and wincolor_sink.

https://github.com/gabime/spdlog/blob/c3aed4b68373955e1cc94307683d44dca1515d2b/include/spdlog/sinks/stdout_color_sinks.h#L14-L27

**Comment by cschreib-ibex** [comment]
Unfortunately, the ANSI color sinks are not included in the static/shared library build of spdlog on Windows. The headers are there, but the implementation is missing, so trying to use these sinks results in a linker error. Looking at the source code, they should indeed work on Windows, so perhaps they should be included unconditionally in the build? 

A workaround is to include both `ansicolor_sink.h` and `ansicolor_sink-inl.h`, but I don't know if this is advisable.

I have opened a new issue to cover this and other problems using this on Windows: https://github.com/gabime/spdlog/issues/3138.
