### ISSUE TITLE
idea behind SPDLOG_DEBUG_ON macro?

### ISSUE THREAD

**Issue by geronimo22** [gabime/spdlog#312]
sorry. rookie question - I was wondering what the idea behind SPDLOG_DEBUG_ON macro.

Is it to avoid the expensive string formatting in a logger->debug("expensive formatting { }", something) which will be discarded if the logging level is set to INFO and not DEBUG?

**Comment by gabime** [comment]
There is no cost in formatting since formatting would not happen if not needed. 
It is to avoid the cost of calling the function and the small cost of checking at runtime the log level.
