### ISSUE TITLE
[win32] no entry point found _ZN6spdlog7details7log_msgC1ENS_10source_locESt17basic_string_viewIcSt11char_traitsIcEENS_5level10level_enumES6_

### ISSUE THREAD

**Issue by basiliscos** [gabime/spdlog#3126]
Hi,

Tried to build spdlog v1.14.1 and v1.12.0 using msys2 on windows. My library build options is `-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/spdlog -DBUILD_SHARED_LIBS=on -DSPDLOG_USE_STD_FORMAT=on`

It successfully builds and installs; the example runs OK (although, it does not uses dll, as I can see). However, when I use it in my other project I get the popup with the error

![2024-07-04_11-24](https://github.com/gabime/spdlog/assets/3630048/50a45b1d-705f-4e38-b5ac-b955f82942e7)

```
_ZN6spdlog7details7log_msgC1ENS_10source_locESt17basic_string_viewIcSt11char_traitsIcEENS_5level10level_enumES6_
```

The symbol `spdlog::details::log_msg::log_msg(spdlog::source_loc, std::basic_string_view<char, std::char_traits<char> >, spdlog::level::level_enum, std::basic_string_view<char, std::char_traits<char> >)` can be found on linux `.so` (built with the same cmake options), but not on windows.

There are only the following symbols (extracted via `dumpbin`)

```
        257  100 000032E0 _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES6_
        258  101 00003220 _ZN6spdlog7details7log_msgC1ENSt6chrono10time_pointINS2_3_V212system_clockENS2_8durationIxSt5ratioILx1ELx1000000000EEEEEENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumESF_
        259  102 000033C0 _ZN6spdlog7details7log_msgC2EN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES5_
        260  103 000032E0 _ZN6spdlog7details7log_msgC2ENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES6_
        261  104 00003220 _ZN6spdlog7details7log_msgC2ENSt6chrono10time_pointINS2_3_V212system_clockENS2_8durationIxSt5ratioILx1ELx1000000000EEEEEENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumESF_
        262  105 00006370 _ZN6spdlog7details8registry10set_levelsESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_5level10level_enumESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEEPSA_

```

any ideas what I do wrong?

**Comment by tt4g** [comment]
I can't help you because I don't know how you build your projects.
How are you building a project that uses spdlog?

**Comment by basiliscos** [comment]
Ok, I'll try to make a synthetic example

**Comment by basiliscos** [comment]
I wasn't able to reproduce again, but it seems the problem was that I used ` -DBUILD_SHARED_LIBS=on` instead of officially recommended `-DSPDLOG_BUILD_SHARED=on`. I'm not sure, so, closing this.
