### ISSUE TITLE
i can't build it about Spalog, need help~

### ISSUE THREAD

**Issue by lsm1997** [gabime/spdlog#3133]
>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1511): error C4579: 'fmt::v9::detail::basic_data<void>::pow10_significands': in-class initialization for type 'const uint64_t [87]' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1544): note: 参见对正在编译的类 模板 实例化“fmt::v9::detail::basic_data<void>”的引用
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1481): error C2131: 表达式的计算结果不是常数
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1482): note: 遇到非常量(子)表达式
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1527): error C4579: 'fmt::v9::detail::basic_data<void>::pow10_exponents': in-class initialization for type 'const int16_t [87]' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1519): error C2131: 表达式的计算结果不是常数
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1520): note: 遇到非常量(子)表达式
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1534): error C4579: 'fmt::v9::detail::basic_data<void>::power_of_10_64': in-class initialization for type 'const uint64_t [20]' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1532): error C2131: 表达式的计算结果不是常数
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(1533): note: 遇到非常量(子)表达式
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format-inl.h(65): error C2666: “fmt::v9::format_to”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4202): note: 可能是“OutputIt fmt::v9::format_to<fmt::v9::appender,fmt::v9::detail::format_error_code::<lambda_f5c77d34a1f9c3bceb526e0279c56577>::()::FMT_COMPILE_STRING,const char(&)[3],0>(OutputIt,const Locale &,fmt::v9::basic_format_string<char,const char (&)[3]>,const char (&)[3])”
1>          with
1>          [
1>              OutputIt=fmt::v9::appender,
1>              Locale=fmt::v9::detail::format_error_code::<lambda_f5c77d34a1f9c3bceb526e0279c56577>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3233): note: 或  “OutputIt fmt::v9::format_to<fmt::v9::appender,fmt::v9::string_view&,const char(&)[3],0>(OutputIt,fmt::v9::basic_format_string<char,fmt::v9::string_view &,const char (&)[3]>,fmt::v9::string_view &,const char (&)[3])”
1>          with
1>          [
1>              OutputIt=fmt::v9::appender
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format-inl.h(65): note: 尝试匹配参数列表“(fmt::v9::appender, fmt::v9::detail::format_error_code::<lambda_f5c77d34a1f9c3bceb526e0279c56577>::()::FMT_COMPILE_STRING, fmt::v9::string_view, const char [3])”时
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format-inl.h(66): error C2666: “fmt::v9::format_to”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4202): note: 可能是“OutputIt fmt::v9::format_to<fmt::v9::appender,fmt::v9::detail::format_error_code::<lambda_1f350d4c323c2872800c74c8a8ba3910>::()::FMT_COMPILE_STRING,int&,0>(OutputIt,const Locale &,fmt::v9::basic_format_string<char,int &>,int &)”
1>          with
1>          [
1>              OutputIt=fmt::v9::appender,
1>              Locale=fmt::v9::detail::format_error_code::<lambda_1f350d4c323c2872800c74c8a8ba3910>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3233): note: 或  “OutputIt fmt::v9::format_to<fmt::v9::appender,const char(&)[7],int&,0>(OutputIt,fmt::v9::basic_format_string<char,const char (&)[7],int &>,const char (&)[7],int &)”
1>          with
1>          [
1>              OutputIt=fmt::v9::appender
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format-inl.h(66): note: 尝试匹配参数列表“(fmt::v9::appender, fmt::v9::detail::format_error_code::<lambda_1f350d4c323c2872800c74c8a8ba3910>::()::FMT_COMPILE_STRING, const char [7], int)”时
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format-inl.h(1154): warning C4307: “*”: 整型常量溢出
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format-inl.h(1186): warning C4307: “*”: 整型常量溢出
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format-inl.h(1207): warning C4307: “*”: 整型常量溢出
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\logger-inl.h(139): error C2666: “fmt::v9::format”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4183): note: 可能是“std::string fmt::v9::format<spdlog::logger::sink_it_::<lambda_ab18d0a347b6e73b6add0337907619b4>::()::FMT_COMPILE_STRING,const char*const &,const int&,0>(const Locale &,fmt::v9::basic_format_string<char,const char *const &,const int &>,const char *const &,const int &)”
1>          with
1>          [
1>              Locale=spdlog::logger::sink_it_::<lambda_ab18d0a347b6e73b6add0337907619b4>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3204): note: 或  “std::string fmt::v9::format<const char*,const char*const &,const int&>(fmt::v9::basic_format_string<char,const char *,const char *const &,const int &>,const char *&&,const char *const &,const int &)”
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\logger-inl.h(139): note: 尝试匹配参数列表“(spdlog::logger::sink_it_::<lambda_ab18d0a347b6e73b6add0337907619b4>::()::FMT_COMPILE_STRING, const char *, const char *const , const int)”时
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\logger-inl.h(151): error C2666: “fmt::v9::format”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4183): note: 可能是“std::string fmt::v9::format<spdlog::logger::flush_::<lambda_a6917095f9b59a90a7277929d3c24179>::()::FMT_COMPILE_STRING,const char*&,int&,0>(const Locale &,fmt::v9::basic_format_string<char,const char *&,int &>,const char *&,int &)”
1>          with
1>          [
1>              Locale=spdlog::logger::flush_::<lambda_a6917095f9b59a90a7277929d3c24179>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3204): note: 或  “std::string fmt::v9::format<const char*,const char*&,int&>(fmt::v9::basic_format_string<char,const char *,const char *&,int &>,const char *&&,const char *&,int &)”
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\logger-inl.h(151): note: 尝试匹配参数列表“(spdlog::logger::flush_::<lambda_a6917095f9b59a90a7277929d3c24179>::()::FMT_COMPILE_STRING, const char *, const char *, int)”时
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(42): error C2666: “fmt::v9::format”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4183): note: 可能是“std::string fmt::v9::format<spdlog::async_logger::sink_it_::<lambda_423ab1cb0b96661cdfa195c0dfee058d>::()::FMT_COMPILE_STRING,const char*const &,const int&,0>(const Locale &,fmt::v9::basic_format_string<char,const char *const &,const int &>,const char *const &,const int &)”
1>          with
1>          [
1>              Locale=spdlog::async_logger::sink_it_::<lambda_423ab1cb0b96661cdfa195c0dfee058d>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3204): note: 或  “std::string fmt::v9::format<const char*,const char*const &,const int&>(fmt::v9::basic_format_string<char,const char *,const char *const &,const int &>,const char *&&,const char *const &,const int &)”
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(42): note: 尝试匹配参数列表“(spdlog::async_logger::sink_it_::<lambda_423ab1cb0b96661cdfa195c0dfee058d>::()::FMT_COMPILE_STRING, const char *, const char *const , const int)”时
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(54): error C2666: “fmt::v9::format”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4183): note: 可能是“std::string fmt::v9::format<spdlog::async_logger::flush_::<lambda_9dcdb2c14246dac0c89e187c747500f5>::()::FMT_COMPILE_STRING,const char*&,int&,0>(const Locale &,fmt::v9::basic_format_string<char,const char *&,int &>,const char *&,int &)”
1>          with
1>          [
1>              Locale=spdlog::async_logger::flush_::<lambda_9dcdb2c14246dac0c89e187c747500f5>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3204): note: 或  “std::string fmt::v9::format<const char*,const char*&,int&>(fmt::v9::basic_format_string<char,const char *,const char *&,int &>,const char *&&,const char *&,int &)”
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(54): note: 尝试匹配参数列表“(spdlog::async_logger::flush_::<lambda_9dcdb2c14246dac0c89e187c747500f5>::()::FMT_COMPILE_STRING, const char *, const char *, int)”时
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(64): error C2666: “fmt::v9::format”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4183): note: 可能是“std::string fmt::v9::format<spdlog::async_logger::backend_sink_it_::<lambda_a1f9975e7b19686211047d80750a4844>::()::FMT_COMPILE_STRING,const char*const &,const int&,0>(const Locale &,fmt::v9::basic_format_string<char,const char *const &,const int &>,const char *const &,const int &)”
1>          with
1>          [
1>              Locale=spdlog::async_logger::backend_sink_it_::<lambda_a1f9975e7b19686211047d80750a4844>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3204): note: 或  “std::string fmt::v9::format<const char*,const char*const &,const int&>(fmt::v9::basic_format_string<char,const char *,const char *const &,const int &>,const char *&&,const char *const &,const int &)”
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(64): note: 尝试匹配参数列表“(spdlog::async_logger::backend_sink_it_::<lambda_a1f9975e7b19686211047d80750a4844>::()::FMT_COMPILE_STRING, const char *, const char *const , const int)”时
1>e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(76): error C2666: “fmt::v9::format”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4183): note: 可能是“std::string fmt::v9::format<spdlog::async_logger::backend_flush_::<lambda_26e86631442e79b783aa84b84fb55b9c>::()::FMT_COMPILE_STRING,const char*&,int&,0>(const Locale &,fmt::v9::basic_format_string<char,const char *&,int &>,const char *&,int &)”
1>          with
1>          [
1>              Locale=spdlog::async_logger::backend_flush_::<lambda_26e86631442e79b783aa84b84fb55b9c>::()::FMT_COMPILE_STRING
1>          ]
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\core.h(3204): note: 或  “std::string fmt::v9::format<const char*,const char*&,int&>(fmt::v9::basic_format_string<char,const char *,const char *&,int &>,const char *&&,const char *&,int &)”
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\async_logger-inl.h(76): note: 尝试匹配参数列表“(spdlog::async_logger::backend_flush_::<lambda_26e86631442e79b783aa84b84fb55b9c>::()::FMT_COMPILE_STRING, const char *, const char *, int)”时
1>E:\Documents\SVN712\test_demo_cuda11\thirdlib\spdlog/fmt/bundled/chrono.h(1555): warning C4624: “fmt::v9::detail::get_locale::<unnamed-tag>”: 未能生成析构函数，因为基类析构函数不可访问或已被删除
1>E:\Documents\SVN712\test_demo_cuda11\thirdlib\spdlog/sinks/daily_file_sink.h(36): error C2666: “fmt::v9::format”: 2 个重载有相似的转换
1>  e:\documents\svn712\test_demo_cuda11\thirdlib\spdlog\fmt\bundled\format.h(4183): note: 可能是“std::string fmt::v9::format<spdlog::sinks::daily_filename_calculator::calc_filename::<lambda_15339c707e073a48be504f739b0b88a2>::()::FMT_COMPILE_STRING,int,int,const int&,spdlog::filename_t&,0>(const Locale &,fmt::v9::basic_format_string<char,int,int,const int &,spdlog::filename_t &>,int &&,int &&,const int &,spdlog::filename_t &)”
1>          with
1>          [
1>              Locale=spdlog::sinks::daily_filename_calculator::calc_filename::<lambda_15339c707e073a48be504f739b0b88a2>::()::FMT_COMPILE_STRING
1>          ]

**Comment by tt4g** [comment]
I can't help because I don't know the source code that is causing the compilation error.
Please provide the code that is causing the error and the complete error message.
