### ISSUE TITLE
compiler error on vs2015

### ISSUE THREAD

**Issue by Xuhuajie-2021** [gabime/spdlog#3134]
#include "spdlog\spdlog.h"
When I include head file in VS2015, it turns wrong with below:

1>d:\project_master\02_user_client_tools\trunk\thirdparty\include\spdlog\fmt\bundled\format-inl.h(61): error C2666: “fmt::v10::format_to”: 2 个重载有相似的转换
1>  d:\project_master\02_user_client_tools\trunk\thirdparty\include\spdlog\fmt\bundled\format.h(4488): note: 可能是“OutputIt fmt::v10::format_to<fmt::v10::appender,fmt::v10::detail::format_error_code::<lambda_3ef0f86fc78cfb665af2aad3d9d57024>::()::FMT_COMPILE_STRING,const char(&)[3],0>(OutputIt,const Locale &,fmt::v10::basic_format_string<char,const char (&)[3]>,const char (&)[3])”
1>          with
1>          [
1>              OutputIt=fmt::v10::appender,
1>              Locale=fmt::v10::detail::format_error_code::<lambda_3ef0f86fc78cfb665af2aad3d9d57024>::()::FMT_COMPILE_STRING
1>          ]
1>  d:\project_master\02_user_client_tools\trunk\thirdparty\include\spdlog\fmt\bundled\core.h(2861): note: 或  “OutputIt fmt::v10::format_to<fmt::v10::appender,fmt::v10::string_view&,const char(&)[3],0>(OutputIt,fmt::v10::basic_format_string<char,fmt::v10::string_view &,const char (&)[3]>,fmt::v10::string_view &,const char (&)[3])”
1>          with
1>          [
1>              OutputIt=fmt::v10::appender
1>          ]

**Comment by tt4g** [comment]
Please write your issue in English so that many people can read your issue.

**Comment by tt4g** [comment]
Template materialization has failed.
It should not be caused by just including spdlog, so there must be code in your project that caused the error.
We will not be able to help you unless you submit the code that is causing the error.

**Comment by Xuhuajie-2021** [comment]
I checkout the master version, it works.
the default version '1.x' ,compiler error.
my code is here:
#include <string>
#include <iostream>

#include "spdlog\spdlog.h"

int main()
{
	
	system("pause");
}

**Comment by tt4g** [comment]
I found a report of C2666 in the fmt repository fmtlib/fmt#3469, but unfortunately MSVC2015 is no longer supported.
Please use a newer version MSVC.

**Comment by Xuhuajie-2021** [comment]
thanks for reply.
