### ISSUE TITLE
build with SPDLOG_FMT_EXTERNAL_HO error

### ISSUE THREAD

**Issue by ChrisCatCP** [gabime/spdlog#3142]
“spdlog/fmt/bundled/core.h”: No such file or directory

https://github.com/gabime/spdlog/blob/5ebfc927306fd7ce551fa22244be801cf2b9fdd9/include/spdlog/fmt/fmt.h#L14-L25

SPDLOG_FMT_EXTERNAL_HO has not been processed correctly here

**Comment by tt4g** [comment]
What do you think is incorrect?

`SPDLOG_FMT_EXTERNAL_HO` is a CMake variable, not a C++ macro.
And `SPDLOG_FMT_EXTERNAL_HO=ON` then, `include/spdlog/fmt/bundled/ ` is not installed and `fmt::fmt-header-only` is added to the linked library to use the header-only fmt library.

https://github.com/gabime/spdlog/blob/5ebfc927306fd7ce551fa22244be801cf2b9fdd9/CMakeLists.txt#L208-L228

https://github.com/gabime/spdlog/blob/5ebfc927306fd7ce551fa22244be801cf2b9fdd9/CMakeLists.txt#L322-L325

https://github.com/fmtlib/fmt/blob/10.2.1/CMakeLists.txt#L339-L340

**Comment by ChrisCatCP** [comment]
sorry,i think i made a mistake
