### ISSUE TITLE
Enums do not work.

### ISSUE THREAD

**Issue by mold-boy** [gabime/spdlog#3147]
So how do i get this to work as the user?
cout << enum works but 
spdlog::error("{}", My_ENUM} does not work

_Originally posted by @aCuria in https://github.com/gabime/spdlog/issues/150#issuecomment-1125676843_

**Comment by tt4g** [comment]
A custom formatter must be defined to format user-defined objects: https://fmt.dev/10.2.0/api.html#formatting-user-defined-types
