### ISSUE TITLE
When initializing, it prompts "simple log instance"

### ISSUE THREAD

**Issue by ma-yongliang** [gabime/spdlog#3149]
my code is as follows:

`auto logger = spdlog::rotating_logger_mt(getCurrentPid(), "C:\\ProgramData\\MyLog\\spdlog.log", 1024 * 1024 * 5, 3);`

when I call 
`logger->info("Test log.")`

it prompts "simple log instance".

**Comment by tt4g** [comment]
> it prompts "simple log instance".

Where is it printed?
If it is a console, it does not appear to be due to spdlog.
