### ISSUE TITLE
rename macros DEPRECATED

### ISSUE THREAD

**Issue by dontsovcmc** [gabime/spdlog#315]
Your macros DEPRECATED conflicts with same name macros from FTDI library (com-usb chip driver). Can you rename it?

**Comment by gabime** [comment]
Fixed in https://github.com/gabime/spdlog/commit/9eee823041f3e48904c2a0fbc26d97bb88ff3d62
Thanks for reporting.

**Comment by dontsovcmc** [comment]
Thanks a lot!
