### ISSUE TITLE
error: call to non-‘constexpr’ function ‘long int sysconf(int)’

### ISSUE THREAD

**Issue by xinyugit** [gabime/spdlog#3152]
System environment：

Linux version 6.8.0-39-generic (buildd@lcy02-amd64-112) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024

gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4) 

ERROR:

/tests/catch.hpp:9041:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 9041 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~

**Comment by tt4g** [comment]
This is Catch2 issue, please reopen in [the  Catch2 repository](https://github.com/catchorg/Catch2).

**Comment by xinyugit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xinyugit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
