### ISSUE TITLE
I found that we can use python format style:

### ISSUE THREAD

**Issue by mold-boy** [gabime/spdlog#3153]
This doesn't work in C++20.

error: call to consteval function 'fmt::basic_format_string<char, int &, double &, int &>::basic_format_string<char[69], 0>' is not a constant expression

              I found that we can use python format style:
```
SPDLOG_INFO("Test: {0:.8f}", y);
```
Output: [2019-03-08 17:28:15.921] [info] [test.cc:75] Test: 4.12345679

But is there anyway to just set precision 1 time so we no need to put "0:.8f" every time logging double?
For example:
```
spdlog::set_precision(8);
```

_Originally posted by @larvavral in https://github.com/gabime/spdlog/issues/1019#issuecomment-470882142_

**Comment by tt4g** [comment]
The logging argument format uses [the fmt library](https://github.com/fmtlib/fmt), but there was no ability to set the precision globally.

**Comment by mold-boy** [comment]
Okay, using C++20 it used std::format under the hood.
