### ISSUE TITLE
Is spdlog can support placeholders %0 %1 like {0} {1} 

### ISSUE THREAD

**Issue by xiaocai123123** [gabime/spdlog#3162]
How can spdlog support placeholders %0 %1 like {0} {1} ?
I have a log that needs to be printed like below:
spdlog::info("Welocome to spdlog %0  %1", 123, "test");
I want to print like below:
spdlog::info("Welocome to spdlog {}  {}", 123, "test");
How can i finish it?

**Comment by tt4g** [comment]
spdlog uses [fmt library](https://github.com/fmtlib/fmt) to format logging arguments, and fmt not supports `%0` style (`%` is reserved by Chrono Format Specifications: https://fmt.dev/11.0/syntax/#chrono-format-specifications).

**Comment by xiaocai123123** [comment]
> [fmt library](https://github.com/fmtlib/fmt)

thanks! U are great!
