### ISSUE TITLE
Build error on raspberry pi

### ISSUE THREAD

**Issue by MathijsV** [gabime/spdlog#317]
Error when building spdlog on a raspberry pi: "error: operator '!' has no right operand" on line 347 in details/os.h. Replacing "_GNU_SOURCE" with "defined(_GNU_SOURCE)" seems to help, though I'm not sure it's supposed to be like that.

**Comment by vitaut** [comment]
@gabime, the fmt library has an automatic detection of safe `strerror` variants in https://github.com/fmtlib/fmt/blob/master/fmt/format.cc#L121 which may help addressing this issue and #303.

**Comment by gabime** [comment]
Fixed in e12916c070caab334326aea72925c1cb903bfc97
Thanks for reporting.

**Comment by gabime** [comment]
@vitaut Thanks. I hope it is resolved now. If not, I will certainly check your ```safe_strerror``` function
