### ISSUE TITLE
Print file name, function name, and line number

### ISSUE THREAD

**Issue by hongshibao** [gabime/spdlog#318]
Can spdlog support printing related info about file name, function name, and line number for each log? The standard predefined macros ``__FILE__, __LINE__, __FUNCTION__`` may be helpful to implement this.

**Comment by hongshibao** [comment]
It seems SPDLOG_TRACE has already supported this.

**Comment by smrititripathi027** [comment]
If I am creating two loggers in same c++ file then how to print file name, line number in file becausee if I am using SPDLOG_TRACE , it is supporting to only one logger.

**Comment by tt4g** [comment]
@smrititripathi027 You can refer to the following snippet (copy from https://github.com/gabime/spdlog/issues/1032#issuecomment-475237476):

```cpp
// Enable SPDLOG_TRACE macro, see: spdlog/tweakme.h
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#define SPDLOG_DEBUG_ON
#define SPDLOG_TRACE_ON

#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>

int main(int, char**)
{
    spdlog::set_pattern("[source %s] [function %!] [line %#] %v");

    auto console = spdlog::stdout_logger_mt("console");
    spdlog::set_default_logger(console);

    SPDLOG_TRACE("global output with arg {}", 1); // [source main.cpp] [function main] [line 16] global output with arg 1
    SPDLOG_LOGGER_TRACE(console, "logger output with arg {}", 2); // [source main.cpp] [function main] [line 17] logger output with arg 2
    console->info("invoke member function"); // [source ] [function ] [line ] invoke member function

    return 0;
}
```

The `SPDLOG_TRACE` macro uses a global logger, The `SPDLOG_LOGGER_TRACE` macro uses the first argument logger.

**Comment by adlternative** [comment]
sorry, but I could not find a good way to use this feature with a normal logger object:

```cpp
#define SPDLOG_FMT_EXTERNAL
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/spdlog.h>

int main(int, char **) {

  // spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
  // spdlog::set_level(spdlog::level::trace);

  // SPDLOG_TRACE("This trace");
  // SPDLOG_DEBUG("This is debug..");
  // SPDLOG_INFO("This is info..");
  // SPDLOG_ERROR("This is error..");
  // SPDLOG_CRITICAL("This is critical..");

  auto console_logger = spdlog::stdout_color_mt("console");
  console_logger->set_pattern("[source %s] [function %!] [line %#] %v");
  console_logger->error("This is error..");
  return 0;
}
```
Its output:

```
[source ] [function ] [line ] This is error..
```

**Comment by tt4g** [comment]
@adlternative Should use logging macro.

```diff
 #include <spdlog/sinks/basic_file_sink.h>
 #include <spdlog/sinks/stdout_color_sinks.h>
 #include <spdlog/spdlog.h>

 int main(int, char **) {

   // spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
   // spdlog::set_level(spdlog::level::trace);

   // SPDLOG_TRACE("This trace");
   // SPDLOG_DEBUG("This is debug..");
   // SPDLOG_INFO("This is info..");
   // SPDLOG_ERROR("This is error..");
   // SPDLOG_CRITICAL("This is critical..");

   auto console_logger = spdlog::stdout_color_mt("console");
   console_logger->set_pattern("[source %s] [function %!] [line %#] %v");
-  console_logger->error("This is error..");
+  SPDLOG_LOGGER_ERROR(console_logger, "This is error..");
   return 0;
 }
```

Wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

**Comment by adlternative** [comment]
> @adlternative Should use logging macro.
> 
> ```diff
>  #include <spdlog/sinks/basic_file_sink.h>
>  #include <spdlog/sinks/stdout_color_sinks.h>
>  #include <spdlog/spdlog.h>
> 
>  int main(int, char **) {
> 
>    // spdlog::set_pattern("[source %s] [function %!] [line %#] %v");
>    // spdlog::set_level(spdlog::level::trace);
> 
>    // SPDLOG_TRACE("This trace");
>    // SPDLOG_DEBUG("This is debug..");
>    // SPDLOG_INFO("This is info..");
>    // SPDLOG_ERROR("This is error..");
>    // SPDLOG_CRITICAL("This is critical..");
> 
>    auto console_logger = spdlog::stdout_color_mt("console");
>    console_logger->set_pattern("[source %s] [function %!] [line %#] %v");
> -  console_logger->error("This is error..");
> +  SPDLOG_LOGGER_ERROR(console_logger, "This is error..");
>    return 0;
>  }
> ```
> 
> Wiki: https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

All right, Thanks!
