### ISSUE TITLE
did spdlog work on Windows Server ？

### ISSUE THREAD

**Issue by fzw2408** [gabime/spdlog#3186]
why my spdlog demo can‘t run  on Windows Server system ？ buy it run on my win 10 11 system very well。did somebody has the same   
problem？

**Comment by tt4g** [comment]
I don't know how you tried to run the application. Did you try to double click on the `<your_application>.exe` file and it didn't work?

**Comment by fzw2408** [comment]
yes ，just click and it can‘t out put any file and i can't see any wrong tips ，but on my develop system it work’s ok. i try it on 3 pc , 2 :windows server system[ ]. 1 win 10 /win 11[no problem]

**Comment by fzw2408** [comment]
i got it ：it must build use  /MT  not /MD 
if u use Qt pro project  just add   
QMAKE_CXXFLAGS_RELEASE += /MT
 
QMAKE_CFLAGS_RELEASE += /MT

and then it work
