### ISSUE TITLE
About asio endpoint

### ISSUE THREAD

**Issue by iGwkang** [gabime/spdlog#3187]
In spdlog `v1.30.0`, this code is supported:
```c++
asio::ip::udp::endpoint endpoint(asio::ip::make_address("127.0.0.1"), 8080);
SPDLOG_INFO("{}", endpoint);
```

When I upgraded to `v1.40.1`, the compilation reported an error.
> [build] /spdlog-src/include/spdlog/fmt/bundled/core.h:1600:63: error: implicit instantiation of undefined template 'fmt::detail::type_is_unformattable_for<asio::ip::basic_endpoint<asio::ip::udp>, char>'
[build]  1600 |     type_is_unformattable_for<T, typename Context::char_type> _;
[build]       |                                                               ^
[build] /spdlog-src/include/spdlog/fmt/bundled/core.h:1842:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, asio::ip::basic_endpoint<asio::ip::udp>, 0>' requested here
[build]  1842 |         data_{detail::make_arg<is_packed, Context>(args)...} {
[build]       |                       ^
[build] /spdlog-src/include/spdlog/fmt/bundled/core.h:1860:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, asio::ip::basic_endpoint<asio::ip::udp>>::format_arg_store<asio::ip::basic_endpoint<asio::ip::udp>>' requested here
[build]  1860 |   return {args...};
[build]       |          ^
[build] /spdlog-src/include/spdlog/logger.h:328:59: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, asio::ip::basic_endpoint<asio::ip::udp>>' requested here
[build]   328 |             fmt::vformat_to(fmt::appender(buf), fmt, fmt::make_format_args(args...));
[build]       |                                                           ^
[build] /spdlog-src/include/spdlog/logger.h:80:9: note: in instantiation of function template specialization 'spdlog::logger::log_<asio::ip::basic_endpoint<asio::ip::udp> &>' requested here
[build]    80 |         log_(loc, lvl, details::to_string_view(fmt), std::forward<Args>(args)...);
[build]       |         ^
[build] /workspaces/udp_forward/test.cpp:7:1: note: in instantiation of function template specialization 'spdlog::logger::log<asio::ip::basic_endpoint<asio::ip::udp> &>' requested here
[build]     7 | SPDLOG_INFO("{}", endpoint);
[build]       | ^
[build] /spdlog-src/include/spdlog/spdlog.h:315:30: note: expanded from macro 'SPDLOG_INFO'
[build]   315 |     #define SPDLOG_INFO(...) SPDLOG_LOGGER_INFO(spdlog::default_logger_raw(), __VA_ARGS__)
[build]       |                              ^
[build] /spdlog-src/include/spdlog/spdlog.h:314:9: note: expanded from macro 'SPDLOG_LOGGER_INFO'
[build]   314 |         SPDLOG_LOGGER_CALL(logger, spdlog::level::info, __VA_ARGS__)
[build]       |         ^
[build] /spdlog-src/include/spdlog/spdlog.h:288:19: note: expanded from macro 'SPDLOG_LOGGER_CALL'
[build]   288 |         (logger)->log(spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, level, __VA_ARGS__)
[build]       |                   ^
[build] /spdlog-src/include/spdlog/fmt/bundled/core.h:1578:45: note: template is declared here
[build]  1578 | template <typename T, typename Char> struct type_is_unformattable_for;
[build]       |                                             ^
[build] /spdlog-src/include/spdlog/fmt/bundled/core.h:1604:7: error: static assertion failed due to requirement 'formattable': Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https:/fmt.dev/latest/api.html#udt
[build]  1604 |       formattable,
[build]       |       ^~~~~~~~~~~
[build] 2 errors generated.

I want to know why this is happening?

**Comment by tt4g** [comment]
It is difficult to guess the cause because we do not know the version before the upgrade.
I expect this is probably due to the fact that starting with fmt version 10, `fmt::formatter<T>` (inherits `fmt::ostream_formatter`) must be defined for formatting by `operator<<(std::ostream&, const T&)`.
Bundled fmt is now version 10, this is a change from ~~[1.12.0](https://github.com/gabime/spdlog/releases/tag/v1.12.0).~~ (Edit: [1.14.0](https://github.com/gabime/spdlog/releases/tag/v1.14.0))

See: https://github.com/gabime/spdlog/issues/3097#issuecomment-2132446276

**Comment by iGwkang** [comment]
But this code is supported in [1.30.0](https://github.com/gabime/spdlog/releases/tag/v1.13.0)
I did not use independent fmtlib, but directly introduced spdlog through the header file.
If fmt version 10 has been updated in 1.12.0, then 1.13.0 should not support the above code.

**Comment by tt4g** [comment]
Oh, sorry, the link to the release page is wrong.
The bundled fmt version 10 is from spdlog [1.14.0](https://github.com/gabime/spdlog/releases/tag/v1.14.0).

> Updated bundled fmt to version 10.2.1.

**Comment by iGwkang** [comment]
Thank you, I know! In fmt version 10.2.1, do I have to show the declaration custom type?

**Comment by tt4g** [comment]
Yes.  You must define a specialization of `fmt::formatter<T>`.

**Comment by iGwkang** [comment]
Ok, thank you! Then I'll use version 1.30.0, because I have many custom types. I don't quite understand why the new version of fmt should be changed like this. Is it to deal with any problems?

**Comment by tt4g** [comment]
I'm not the maintainer of fmt, so I don't know the detailed reason. you can ask in the [fmt repository](https://github.com/fmtlib/fmt).

**Comment by iGwkang** [comment]
Ok, thank you very much!

**Comment by iGwkang** [comment]
https://github.com/fmtlib/fmt/releases/tag/9.0.0
> Disabled automatic std::ostream insertion operator (operator<<) discovery when fmt/ostream.h is included to prevent ODR violations. You can get the old behavior by defining FMT_DEPRECATED_OSTREAM but this will be removed in the next major release. Use fmt::streamed or fmt::ostream_formatter to enable formatting via std::ostream instead.
