### ISSUE TITLE
log level of messages of the dup_filter_sink

### ISSUE THREAD

**Issue by yalov** [gabime/spdlog#3188]
Hello, as of now I have:

```
[2024-09-15_13:58:06.955] [65.178] [TRCE] message
[2024-09-15_13:58:07.040] [65.262] [INFO] Skipped 1 duplicate messages..
```

The message that is duplicated is at the TRACE level, but the "duplication message" is at the INFO level.
Is this expected?
Is there a configuration to make the "duplication message" use the same level as the message being duplicated (which may vary)?

**Comment by tt4g** [comment]
> Is there a configuration to make the "duplication message" use the same level as the message being duplicated (which may vary)?

This feature is not supported.

Skip messages are notified at the log level configured in the constructor.

https://github.com/gabime/spdlog/blob/ffd5aa41d687ec1d9b2d6ff48ca1c816f7c7f0c5/include/spdlog/sinks/dup_filter_sink.h#L43-L46

Also there is one problem if you are achieving the behavior you expect.
dup_filter_sink detects duplicate log messages, but does not check the log level.
If dup_filter_sink skips the same message with different log levels, what should the log level of message “Skipped N duplicate message.” be?

Note, I am not the author of dup_filter_sink.

**Comment by yalov** [comment]
> If dup_filter_sink skips the same message with different log levels, what should the log level of message “Skipped N duplicate message.” be?

The maximum log level of the skipped messages, so the "Skipped N duplicate" message will not be skipped, and will not have the higher log level than the skipped messages themselves.

**Comment by tt4g** [comment]
I know what the desired behavior is.
However, if the log level that generates dup_filter_sink log message “Skipped N duplicate.” is changed dynamically, the behavior will change.
This would be an undesirable change for users who have been discarding “Skipped N duplicate.” messages by setting the trace level of dup_filter_sink.

spdlog allows you to define custom sinks, so create your own dup_filter_sink that behaves the way you want: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by yalov** [comment]
ok, I will to that.
