### ISSUE TITLE
September is the only month abbreviated with four letters

### ISSUE THREAD

**Issue by eronconi** [gabime/spdlog#3194]
Hello all,

I've noticed that month abbreviations hardcoded in `include/spdlog/pattern_formatter-inl.h` use three letters for all months except September, which is abbreviated with `Sept`.

This makes logs misaligned when the month changes to/from September, and makes logs misaligned to other logs created with *nix tools/sprintf which uses three letter abbreviations for all months.

Is there a particular reason for this? Thanks!

**Comment by tt4g** [comment]
The `%b` flag is defined only as “Abbreviated month name” and there is no requirement for three characters, so both `Sep` and `Sept` are correct.

https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags

>  | %b | Abbreviated month name | "Aug" |

Use the `%3!b` flag if you want to align to 3 letters: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#aligning

**Comment by eronconi** [comment]
Thanks for the suggestion, I didn't thought to use alignment feature to truncate the name. It works great.

However, while there are no requirements on "Abbreviated month name", I still find quite odd to have that exception.

**Comment by gabime** [comment]
https://web.library.yale.edu/cataloging/months#:~:text=sept.%2Fset.,nov.
