### ISSUE TITLE
How to customize the file name numbering of spdlog log rotation?  

### ISSUE THREAD

**Issue by pikalin1997** [gabime/spdlog#3204]
I am using the log rotation function of spdlog. I found that the file names of the log rotation files are only the original files that are supplemented by an increasing number. However, when files are named in this format, the log sorting is out of order when I view the log files in linux. Logs are not displayed in the order I expected, as follows:

test.10.log
test.1.log
test.2.log
test.log

I expect the following order:
test.1.log
test.2.log
...
test.10.log
test.log

The solution I have considered is that for the numeric number of the transferred file, 0 is added under the premise of a certain width, as follows:
test.001.log
test.002.log
...
test.010.log
test.log

Does spdlog support this format of transfer file number definition or similar functions?

**Comment by tt4g** [comment]
That feature is not supported.
You can implement a custom sink: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink
