### ISSUE TITLE
Per-class logger with shared sinks

### ISSUE THREAD

**Issue by Jesseeee** [gabime/spdlog#3206]
Hi,

I recently started with spdlog so apologies if I seem to have missed something.

I'm trying to replace our current logging system which allows per-class(cpp file) naming of log output and registers this and also allows setting the log level for each registered log level.

This is essentially what spdlog also allows with everything available, what I would like to achieve is having a sort of "global default" where I can pick which sinks get attached to every created logger by default and have a sort of way to create a per-class logger based on it's class name or some defined variable, this is something we must have as due to the size of our code bases it would otherwise not allow fine-grained enough control over the log output.

Is there some framework available where one could easily sort of "automate" creation of such loggers and have them all send to the same sinks?

I really like what spdlog has to offer, and having the capability to somewhat "manage" all the loggers more globally with default sinks/logger creation would be amazing, but as it stands right now unless I've missed something it seems I'd have to create some framework on top of this to make it work the way I envision.

I've looked in this issue https://github.com/gabime/spdlog/issues/630 and this comes quite close to the per-class I envision, where I'd also like to not necessarily have this as a member variable or require specific instantiation

I'd be willing to look into adding this into spdlog itself if there is interest in this and would fit into the purpose of the library

**Comment by tt4g** [comment]
spdlog does not provide such features.
Logger management methods vary from application to application, so developers must develop their own management methods.

**Comment by gabime** [comment]
logger->clone(new_logger_name) is the closest to what you want. Create a logger with the sinks (and set it as default logger if needed), then clone it  throughout your code.

**Comment by Jesseeee** [comment]
> logger->clone(new_logger_name) is the closest to what you want. Create a logger with the sinks (and set it as default logger if needed), then clone it throughout your code.

Fair enough, I've been able to whip up something that very much resembles what I'm looking for and the clone did help for that, so I'll just maintain this as a small separate piece, thanks for the help!
