### ISSUE TITLE
ThreadSanitizer reports many race conditions and double lock issues

### ISSUE THREAD

**Issue by teoring** [gabime/spdlog#3209]
OS: Ubuntu 22.04
compiler: gcc v11.4.0
spdlog tested 1.1.9 and 1.14.1 ( tried the latest version )
tsan: 12.3.0-1ubuntu1~22.04

I did see this issue https://github.com/gabime/spdlog/pull/2588 and thought it might be related since I also observe traces concerning mpmc_blocking_queue::dequeue_for. But then I tried the latest available version of spdlog ( 1.14.1 ) and observed same warnings. Is it related to gcc version or am I doing something wrong?

My application:

`   
    spdlog::init_thread_pool( 6000, 1 );

    std::vector<spdlog::sink_ptr> sinksToUse = {
        std::make_shared<spdlog::sinks::rotating_file_sink_mt>( "current.log", 2000000, 1 ),
        std::make_shared<spdlog::sinks::stdout_color_sink_mt>()
    };

    auto tp = std::make_shared<spdlog::details::thread_pool>( 6000, 1 );
    auto loggerPtr = std::make_shared<spdlog::async_logger>( "tsan", sinksToUse.begin(), sinksToUse.end(),
            spdlog::thread_pool(), spdlog::async_overflow_policy::block );

    loggerPtr->set_pattern( "[%Y-%m-%d T%H:%M:%S.%f%z] [%n] [%^%l%$] %v" );
    loggerPtr->info( "just a log" );
    spdlog::shutdown();`
    
Attaching tsan warnings as a file as they are too many.
 
[tsan.log](https://github.com/user-attachments/files/17305331/tsan.log)

**Comment by tt4g** [comment]
Since you are using `spdlog::async_overflow_policy::block`, it is an expected result that the message queue of the async logger is doubly locked.

**Comment by teoring** [comment]
Ok, I understand these are expected? Does it pose a real problem for the application like possibility of the dead lock of race conditions?

**Comment by tt4g** [comment]
It is not a deadlock because it is only reported when the lock is challenged while other threads are locked.

**Comment by teoring** [comment]
Ok and data races are due to the same issue described in https://github.com/gabime/spdlog/pull/2588?

If the answer is yes, lets close this ticket.

**Comment by tt4g** [comment]
The ThreadSanitizer message “double lock of a mutex” does not appear to be related to #2588.
It appears to be a false positive for `std::condition_variable`: google/sanitizers#1259

**Comment by teoring** [comment]
Ok, thanks for checking.
