### ISSUE TITLE
Error even when using const char*

### ISSUE THREAD

**Issue by WeleSS2** [gabime/spdlog#3215]
This is first library where i can't even use const char* as string...

```
    const char* tt = "test {}";

    spdlog::debug(tt, std::source_location::current().file_name());
```
Is throwing a nice error 
![image](https://github.com/user-attachments/assets/7ed51d9b-e397-4cfa-9cc9-affd8d9375da)

NOthing in docs of fmt work, any way to solve it or i just need to abandon fmt and spd?

**Comment by tt4g** [comment]
Use `fmt::runtime()` to avoid compile-time-check: https://fmt.dev/11.0/api/#compile-time-checks

```diff
     const char* tt = "test {}";

-    spdlog::debug(tt, std::source_location::current().file_name());
+    spdlog::debug(fmt::runtime(tt), std::source_location::current().file_name());
```

**Comment by WeleSS2** [comment]
Finally working solution! Thanks a lot tt4g! You can close this issue, i was sitting over it nearly 2 weeks and wanted to abandon spd and fmt.

**Comment by tt4g** [comment]
Please please close this issue.
I can't close this issue because I'm not the maintainer of this repository.
