### ISSUE TITLE
Single logger for console and file

### ISSUE THREAD

**Issue by Zonciu** [gabime/spdlog#323]
I'm trying to use a single logger to output trace logs and debug logs to console, and output other logs to the log file at the same time. Is it possible to be achieved? Or I should use two logger to divide console log and file log?

**Comment by gabime** [comment]
Yes, it can be achieved with a logger with 2 sinks(file sink +console sink).
Each sink can have different log level.

**Comment by Zonciu** [comment]
I used it like this:
```
    spdlog::sink_ptr sink_file = std::make_shared<spdlog::sinks::daily_file_sink_mt>("log", "txt", 0, 0);
    spdlog::sink_ptr sink_console = std::make_shared<spdlog::sinks::stdout_sink_mt>();
    sink_console->set_level(spdlog::level::trace);
    std::shared_ptr<spdlog::logger> logger = spdlog::create("logger", { sink_file, sink_console });
    logger->trace("Log test");
    logger->debug("Log test");
    logger->info("Log test");
    logger->warn("Log test");
```
But the console and log file output the same content, the console doesn't show the trace and debug level contents.
![image](https://cloud.githubusercontent.com/assets/10374056/20643370/eb6d7dae-b45b-11e6-83fb-5caca90841b0.png)

**Comment by gabime** [comment]
you should also set the logger level to trace
```c++
logger->set_level(spdlog::level::trace);
```

**Comment by gabime** [comment]
Also, I recommend trying the color console sink(stdout_color_mt)

**Comment by Zonciu** [comment]
Oh, a logger require a common log level, sink‘s log level is after that. Thank you.
