### ISSUE TITLE
[v1.12.0] Compile Warning

### ISSUE THREAD

**Issue by MINGJING-WU** [gabime/spdlog#3234]
In version 1.12.0, We notice the compile warning in this file **[include/spdlog/fmt/bundled/format.h:2509]**

The warning is shown below:
**warning: comparing floating point with == or != is unsafe [-Wfloat-equal]**

Detail Code is shown below:
**return !detail::isnan(value) && value != inf && value != -inf;**

I would like to know your team will consider resolving this compilation alert? Alternatively, your team may consider not introducing this fmt repository in the future? In which version will it be resolved?

**Comment by tt4g** [comment]
All files under directory `include/spdlog/fmt/bundled` are copied from the [fmt repository](https://github.com/fmtlib/fmt).
Please report them in the fmt repository.

**Comment by MINGJING-WU** [comment]
已经接收，我会尽量快点看的，谢谢

**Comment by MINGJING-WU** [comment]
已经接收，我会尽量快点看的，谢谢
