### ISSUE TITLE
Several Simple Improvements to Tweaks

### ISSUE THREAD

**Issue by batduder** [gabime/spdlog#324]
I am a big fan of spdlog.  A few simple improvements would make it even better:

- Add a tweak for log level case -> log level tags in the output are in lower case.  I would prefer upper case.
- Add a tweak for log level tag length match -> I would prefer all log level strings to be same length so that log text lines up better in the output
- Add a tweak for setting file extension -> for rotating files the hard coded extension is ".txt".  I would prefer ".log"
- Would be nice if level filter was set globally in a global XML file or config file rather than from code.  This is needed for systems where many processes/apps use spdlog and we want the filter to be controlled from one place for all apps
- Add an "always" level at the highest level.  Sometimes in production code when filter is set to "error" there are still information items we would want to see in the log.  An "always" level would permit this.

- Any plans to add a socket appender?

**Comment by Razzeee** [comment]
Cool would also be a fixed lenth for thread id
