### ISSUE TITLE
msvc_sink throws on invalid utf-8

### ISSUE THREAD

**Issue by captainurist** [gabime/spdlog#3241]
This is what `msvc_sink` is doing:
```cpp
    #if defined(SPDLOG_WCHAR_TO_UTF8_SUPPORT)
        wmemory_buf_t wformatted;
        details::os::utf8_to_wstrbuf(string_view_t(formatted.data(), formatted.size()), wformatted);
        OutputDebugStringW(wformatted.data());
    #else
        OutputDebugStringA(formatted.data());
    #endif
```

Then in `utf8_to_wstrbuf` we have:
```cpp
    int result_size =
        ::MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, str.data(), str_size, NULL, 0);
```

`MB_ERR_INVALID_CHARS` causes the function to fail on invalid characters, and then `utf8_to_wstrbuf` throws.

We've run into this when trying to output game data that wasn't utf-8 encoded, had to roll out our own implementation of `msvc_sink` (https://github.com/OpenEnroth/OpenEnroth/pull/1825).

My feel here is that logging should work at best effort basis and should not throw unless absolutely necessary (as exception can lead to `std::terminate`). Log calls can be buried somewhere deep in error handling code, and the usual expectation there is that logging calls don't throw.

In this particular case writing out text that's a bit garbled is perfectly OK.

**Comment by gabime** [comment]
Loggers never throw. The sinks might throw but loggers catch everything, so I am not sure what is the problem

**Comment by captainurist** [comment]
Ah OK. Then please disregard my comments on safety.

What do you think about just logging the text that's a bit garbled in this case instead of throwing?

**Comment by gabime** [comment]
I don't think it's a good idea. Might lead to undefined behavior.

**Comment by captainurist** [comment]
There is no UB involved, `MultiByteToWideChar` w/o `MB_ERR_INVALID_CHARS` will just replace invalid code points with `U+FFFD` (�), or drop them if we're talking older Windows versions.

The change is safe, the only concern there is about the difference in behavior. The options are:
1. Throw, potentially causing other loggers in the enclosing `dist_sink` not to run, and write an error to `stderr`.
2. Write out text with �s to msvc debug console.

My opinion is that the latter option is strictly better. What am I missing?

**Comment by gabime** [comment]
I agree. PR is welcome. Could you also add a simple test for this ?

**Comment by captainurist** [comment]
Sure, will do a PR with a test. Thanks!
