### ISSUE TITLE
"Unicode support requires compiling with /utf-8" error while thats enabled in vs 2019

### ISSUE THREAD

**Issue by jorisstudios** [gabime/spdlog#3251]
its enabled here: C/C++ > Command line > Aditional options.
the f is wrong?
![Schermafbeelding 2024-11-11 080005](https://github.com/user-attachments/assets/662bba33-2692-40e6-8a43-a803eb3d4fea)
![Schermafbeelding 2024-11-11 080025](https://github.com/user-attachments/assets/a8da73e7-865b-4374-896d-ea5644ced3c3)

**Comment by tt4g** [comment]
`include/spdlog/fmt/bundled/base.h` is copied from the [fmt repository](https://github.com/fmtlib/fmt).
Please reopen this issue in the fmt repository.

**Comment by tnnnnt** [comment]
useful

**Comment by 0x94494944** [comment]
I've added `#define FMT_UNICODE 0` for the time being but it's annoying because I have indeed but my character set to unicode

**Comment by KLL535** [comment]
same error 
I'm not even the author of the code, but a user, I don't know where to add this #define FMT_UNICODE 0

**Comment by tt4g** [comment]
@KLL535 It is certain to define macros in the compile options.

**Comment by zaphodikus** [comment]
> #define FMT_UNICODE 0

I believe, that adding it before pulling in when compiling in "header-files" only mode will do the good stuff
#define FMT_UNICODE 0
#include <spdlog/spdlog.h>

I added the path to the "...spdlog\include" folder into my project includes as a hard-coded path but if you grabbed spdlog into a child folder called spdlog, then you just need to add "spdlog\include;" without quotes into your includes... as far I can figure that works. It's not as fast to compile header-only, but so far not a biggie.

**Comment by ntninja** [comment]
You can enable source UTF-8 support in the .vcxproj file, by adding:

```xml
<AdditionalOptions>/utf-8</AdditionalOptions> 
```

… inside each `<ClCompile>` block. (This revelation was powered by Kagi Assist… 😕)
