### ISSUE TITLE
speedlog 1.15.0 (and probably at least some older verions as well) don't compile with an old external  libfmt

### ISSUE THREAD

**Issue by Lord-Kamina** [gabime/spdlog#3252]
Trying to fix my CI.  I am supporting still some old linux distros that have a version of Spdlog that is too old for my needs.
To get around that, I decided to use CMake `FetchContent` as a fallback for such cases., downloading a recent release (currently using 1.15.0)

However, I'm noticing the follow errors, if trying to use the libfmt-dev available in the distro, in this case libfmt8.

```shell
In file included from /github_actions_build/build/game/spdlog-src-src/include/spdlog/details/log_msg.h:6,
                 from /github_actions_build/build/game/spdlog-src-src/include/spdlog/sinks/sink.h:6,
                 from /github_actions_build/build/game/spdlog-src-src/include/spdlog/sinks/ansicolor_sink.h:11,
                 from /github_actions_build/game/log.hh:25,
                 from /github_actions_build/game/json.cc:2:
/github_actions_build/build/game/spdlog-src-src/include/spdlog/common.h:181:30: error: 'format_string' in namespace 'fmt' does not name a template type
  181 | using format_string_t = fmt::format_string<Args...>;
      |                              ^~~~~~~~~~~~~
/github_actions_build/build/game/spdlog-src-src/include/spdlog/common.h:190:33: error: 'basic_runtime' in namespace 'fmt' does not name a template type
  190 | using fmt_runtime_string = fmt::basic_runtime<Char>;
      |                                 ^~~~~~~~~~~~~
/github_actions_build/build/game/spdlog-src-src/include/spdlog/common.h:200:66: error: 'fmt_runtime_string' was not declared in this scope
  200 |                                  std::is_same<remove_cvref_t<T>, fmt_runtime_string<Char>>::value> {
```

Is there any way to fix it without using the bundled fmt? And, if I use the bundled fmt, is that library exposed in turn to the projects that might be trying to use spdlog?
My app uses libfmt already, so I want to both spdlog and the app itself to use the same version, if possible.

**Comment by tt4g** [comment]
Since `basic_runtime` is defined in fmt v8 (https://github.com/fmtlib/fmt/blob/8.0.0/include/fmt/core.h#L2829), the following code should work:

https://github.com/gabime/spdlog/blob/51a0deca2c825f1d4461655a18bb37d6df76646d/include/spdlog/common.h#L186-L191

And this code has existed since before v.1.15.0.  
Are you really using fmt v8?

**Comment by Lord-Kamina** [comment]
It appears that I was, in fact, NOT using libfmt8 but rather libfmt 7 *facepalm*
Do you know if it's possible to link my top project against the fmt bundled in spdlog?

**Comment by tt4g** [comment]
A compilation error means that fmt version 8 and version 7 are not API compatible.
You will have to use an older version of spdlog.
