### ISSUE TITLE
Is it necessary to call spdlog::shutdown on Windows?

### ISSUE THREAD

**Issue by zhaowq32** [gabime/spdlog#3256]
#2572 
#2406 
#1809 
If necessary, should it be added to the readme?

**Comment by tt4g** [comment]
The notes are already in the Wiki.

* https://github.com/gabime/spdlog/wiki/0.-FAQ#asynchronous-logging-hangs-on-application-exit-under-windows
* https://github.com/gabime/spdlog/wiki/6.-Asynchronous-logging#windows-issues
* https://github.com/gabime/spdlog/wiki/7.-Flush-policy#manual-flush

**Comment by zhaowq32** [comment]
I need to use spdlog in the destructor of a global variable. Is it possible to extend the life cycle of the registry?

**Comment by tt4g** [comment]
Not recommended: #2113
The behavior of destroying variables after a call to the `main()` function is out of spdlog's control.
