### ISSUE TITLE
Using spdlog with fmtlib 536cabd562831816450ce3f9e57d4da0777ffa9b gives me compile errors

### ISSUE THREAD

**Issue by Vertexwahn** [gabime/spdlog#3258]
I try to use fmtlib with commit hash `536cabd562831816450ce3f9e57d4da0777ffa9b` (from Nov 15, 2024)  when building spdlog (with commit hash `51a0deca2c825f1d4461655a18bb37d6df76646d` from Nov 9, 2024) (I set the define `SPDLOG_FMT_EXTERNAL`)

I get the following compile error:

```
In file included from external/spdlog~/include/spdlog/spdlog.h:12,
                 from ./core/logging.hpp:44,
                 from core/platform.cpp:37:
external/spdlog~/include/spdlog/common.h:369:54: error: 'template<class T, class ... Args> fmt::v11::basic_string_view<Char> spdlog::details::to_string_view' redeclared as different kind of entity
  369 | inline fmt::basic_string_view<T> to_string_view(fmt::basic_format_string<T, Args...> fmt) {
```

If I use fmt version 11.0.2 everything compiles without errors.

**Comment by tt4g** [comment]
Unreleased fmt is not supported yet. If the same error occurs after release, it will be fixed.

**Comment by Vertexwahn** [comment]
Close this for now.

**Comment by WitherVictor** [comment]
I recently encountered a bug caused by [macro conflict](https://github.com/fmtlib/fmt/pull/4186) from fmt with cpprest. It has been fixed by [this commit](https://github.com/fmtlib/fmt/commit/761d35f7632a1dada0be8e6e9d18a3ba16644f00) in fmt. Since without new release from fmt and unreleased fmt is not supported, is there any way to fix that ?

**Comment by gabime** [comment]
You can try to use the fixed fmt with “cmake -DSPDLOG_EXTERNAL=ON” when building spdlog

**Comment by WitherVictor** [comment]
> You can try to use the fixed fmt with “cmake -DSPDLOG_EXTERNAL=ON” when building spdlog

Sadly it's not working. Avoiding use `U` macro in cpprestsdk by `add_definitions(-D_TURN_OFF_PLATFORM_STRING)` in `CMakeLists.txt`  is a workaround for me. Thanks for your help.
