### ISSUE TITLE
log is not written to file with daily file sink

### ISSUE THREAD

**Issue by BTNC** [gabime/spdlog#326]
Hi,

I tried following code to write to both file and console in visual studio 2015 update 3:
```c++
spdlog::sink_ptr sink_file = std::make_shared<spdlog::sinks::daily_file_sink_st>("D:\\log\\app", "txt", 6, 0);
spdlog::sink_ptr sink_console = std::make_shared<spdlog::sinks::stdout_sink_st>();
log = spdlog::create("app", { sink_file, sink_console });
log->set_level(spdlog::level::trace);
sink_console->set_level(spdlog::level::warn);
log->critical("logger is initialized");
```
The console shows `[2016-11-29 23:09:13.063] [app] [critical] logger is initialized`
A file with name `app_2016-11-29_23-09.txt` under directory `D:\log\app` is created, however the file is empty.

I might miss some key points in the code. Any suggestion is appreciated.

Thanks,

**Comment by gabime** [comment]
Seems that it not flushed yet. Try calling ```log->flush()``` to see it immediatly.
You can also use ```log->flush_on(level)``` for automatic flushing.

**Comment by BTNC** [comment]
Thanks!
I tried `log->flush_on(level)` and see logs in file. I overlooked the 'Flush policy' section in the wiki.
