### ISSUE TITLE
spdlog 1.15.0 not completely published to conan-center

### ISSUE THREAD

**Issue by aoh83** [gabime/spdlog#3262]
according to [this](https://conan.io/center/recipes/spdlog) conan 1.15.0 is published to conan. 

however installing conan via: 

    conan install --requires='spdlog/[*] # installs 1.14.1
    conan install --requires='spdlog/[1.15.0]' # fails

**Comment by gabime** [comment]
Please open an issue to Conan. It is not part of this repo.
