### ISSUE TITLE
1.15.0 build error on vs2017

### ISSUE THREAD

**Issue by 346536971** [gabime/spdlog#3264]
build a win32 project (MBCS Mode), error happen :
"
static_assert(!FMT_UNICODE || use_utf8(),
              "Unicode support requires compiling with /utf-8");
"
why ? the FMT support windows?

**Comment by tt4g** [comment]
fmt questions must be asked in the fmt repository to be answered by the fmt maintainer.
You should move this issue to fmt.

**Comment by tt4g** [comment]
At least the ` /utf-8` option is missing: https://github.com/fmtlib/fmt/issues/4221#issuecomment-2448640358

**Comment by gabime** [comment]
If you consume spdlog using cmake, the flag should have been already [added](https://github.com/gabime/spdlog/blob/43dcb3982d1cffcf34a8b126cd12ee07b8eaa2d9/CMakeLists.txt#L276)  for you. How do you use spdlog?

**Comment by stanirya** [comment]
I had the same issue before on 1.14.1, try this workaround:

```
add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
```

**Comment by 346536971** [comment]
> If you consume spdlog using cmake, the flag should have been already [added](https://github.com/gabime/spdlog/blob/43dcb3982d1cffcf34a8b126cd12ee07b8eaa2d9/CMakeLists.txt#L276) for you. How do you use spdlog?
build only include
