### ISSUE TITLE
Adding spdlog-devel to CMake documentation

### ISSUE THREAD

**Issue by benlodz** [gabime/spdlog#3272]
Going based off the example here, my CMakeLists.txt file looks like this:

```
cmake_minimum_required(VERSION 3.30)

project(Gameboy VERSION 1.0
                DESCRIPTION "A Test"
                LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)

include_directories(deps/spdlog)
find_package(spdlog REQUIRED)

add_executable(example_target src/main.cpp)

target_link_libraries(example_target PRIVATE spdlog::spdlog_header_only)
```
I added spdlog as a git submodule to the directory deps. When I ran cmake build this was my output:
```
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.
```
I found the solution here: [https://stackoverflow.com/a/74686095/20739375](url). I'm running Fedora so I just installed spdlog-devel and like magic it works. 

I think it might be worth adding in the documentation that you have that dependency installed in order to use it in your project.That's why I'm opening up this issue. I'm still learning how to use CMake so I'm not sure if this is a standard practice and I shouldn't be making this assumption. Thank you!

**Comment by tt4g** [comment]
Please replace `include_directories()` with `add_subdirectory()`.
