### ISSUE TITLE
Program crushed (somthing wrong with std::mutex) when using MSVC Version 17.11.6 ,but it work right in MSVC Version 17.10.5

### ISSUE THREAD

**Issue by AuroraLime** [gabime/spdlog#3278]
Hello,my program excutes a very simple code `spdlog::info("Welcome to info spdlog!");`,  but it crashed.
![image](https://github.com/user-attachments/assets/a9e5b683-78b5-489e-9697-21204a136d24)
 This problem occurs in MSVC Version 17.11.6. Then I retried in another computer which installs MSVC Version 17.10.5 and it works right.
![image](https://github.com/user-attachments/assets/0a2b64f5-b78f-4c0d-b397-54ef5a3028a7)
Thanks for watching.
There are some info about the environment that occurs problem
- Visual Studio with Cmake
- Qt 6.7.3
- C++20
- MSVC Version 17.11.6
- Using a include version of spdlog
- windows11

**Comment by gabime** [comment]
This is known issue with the newer versions of msvc #3212 and #3145 (and https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio). Try to install the latest version of Microsoft Visual C++ Redistributable and reboot.

**Comment by AuroraLime** [comment]
Thanks，it works right under the latest version of VCTools(Version 14.42.34433).
