### ISSUE TITLE
Log file open mode after log rotation

### ISSUE THREAD

**Issue by ddarkarchon** [gabime/spdlog#328]
I want to understand the behavior of log file reopen in rotating_file_sink after rotation.
Currently it always reopen the file with truncate flag set to true, so I can't clear log file from command line (truncate -s0 logfile.txt), even though it's possible before the rotation.

Is this the desired behavior?
I think log file can always be opened using "ab" mode, and if truncation is desired, we can first delete the existing file.

**Comment by gabime** [comment]
I am not sure I understand why fopen with truncate flag prevents your command line to succeed..

**Comment by ddarkarchon** [comment]
The command line succeeds, but when the file is opened in "wb" mode, the result is that the file is filled with '\0', but the file size stays the same (and keeps growing when new log entries are written).
Basically what I want is log clear operation, after which the file size should be 0.

**Comment by gabime** [comment]
> when the file is opened in "wb" mode, the result is that the file is filled with '\0', but the file size stays the same

This doesn't sound right. fopen(.., "wb") actually truncates the file. try it

**Comment by ddarkarchon** [comment]
I meant that when the file is opened with "wb", the result of running "truncate -s0 logfile.txt" is log file filled with '\0' bytes, and the file size staying the same.
Sorry for explaining myself poorly.

This is what happens:
1) The application starts. The log file is opened using "ab" and thus log entries are appended. This is what I want :)
2. Before the log file is rotated, I can run "truncate -s0 logfile.txt" or "echo -n >logfile.txt" to clear this log file. The file size is truncated to zero and then new log entries are written. The file starts growing again.
3. But if the log file is rotated, after rotate function renames the files, it opens new log file using "wb".
After this, I can no longer truncate the log file to 0 size using the aforementioned commands.

**Comment by gabime** [comment]
Maybe the rotating log is not what you need. There is a contradiction here: on the one hand the rotating sink keeps files under certain size, on the other hand you want only the X last lines.

Looks that creating a specialized sink is the way to go. 
This sink would not rotate but instead keep only the last N lines in the file

Something like:

```c++
template<class Mutex>
class maxlines_file_sink : public spdlog::sinks::base_sink < Mutex >
{
public:
	explicit maxlines_file_sink(const filename_t &filename, max_lines) :
             _max_lines(max_lines), _truncate_interval(max_lines*2)
	{
		_file_helper.open(filename, true);
	}
	void flush() override
	{
		_file_helper.flush();
	}	

protected:
	void _sink_it(const details::log_msg& msg) override
	{
		_file_helper.write(msg);
		if (--_truncate_interval <=0 )
		{
			_file_helper.close();
			// Remove somehow first lines from this file using code or just using the shell)
			//..
			// Reopen without truncating
			_file_helper.reopen(false);
                      _truncate_interval = _max_lines * 2;

		}
	}
private:
	details::file_helper _file_helper;
	int _max_lines;
	int _truncate_interval; // truncate every X calls since it is expensive
        
};

typedef maxlines_file_sink<std::mutex> maxlines_file_sink_mt;
typedef maxlines_file_sink<spdlog::details::null_mutex> maxlines_file_sink_st;
```

**Comment by ddarkarchon** [comment]
The rotating log is what I want. It does exactly what I need from it.
But some people like a clean log file before running each test, so their workflow is:
1) Run the application
2) Clear log, run test, analyze logs
3) Repeat 2 until all tests are done

This is the change I've done:

```C++
void open(const filename_t& fname, bool truncate = false)
{
    close();

    if (truncate)
        details::os::remove(fname);

    _filename = fname;
    for (int tries = 0; tries < open_tries; ++tries)
    {
        if (!os::fopen_s(&_fd, fname, SPDLOG_FILENAME_T("ab")))
            return;

        std::this_thread::sleep_for(std::chrono::milliseconds(open_interval));
    }

    throw spdlog_ex("Failed opening file " + os::filename_to_str(_filename) + " for writing", errno);
}
```

**Comment by gabime** [comment]
Ok, i am glad you found a solution for your problem

**Comment by ddarkarchon** [comment]
I thought you might want to merge this fix into the codebase.
Or should I open a pull request?

**Comment by gabime** [comment]
No need yet. If there is a big demand I will add it
