### ISSUE TITLE
c++20 std::format

### ISSUE THREAD

**Issue by koubaa** [gabime/spdlog#3282]
Hello,

I am using a c++ 20 compiler. I think it would be neat if spdlog gave me an option (maybe through preprocessor) to use the builtin std::format instead of fmt. As great as the fmt library is, having fewer dependencies is nice.

**Comment by matteodelseppia** [comment]
Just generate with:` cmake -Bbuild -DSPDLOG_USE_STD_FORMAT=ON -DSPDLOG_BUILD_EXAMPLE=OFF`. I think the example is breaking compilation when activating std::format.

**Comment by koubaa** [comment]
@matteodelseppia I'm using the header-only variant. I didn't see that option - at least it's reassuring that this is in scope
