### ISSUE TITLE
question on backward compatibility

### ISSUE THREAD

**Issue by jcar87** [gabime/spdlog#3283]
Hi there!

I'm one of the maintainers of Conan Center - where we have a recipe for spdlog that is actively maintained https://conan.io/center/recipes/spdlog?version=1.15.0

I can see that spdlog is also a dependency of another ~18 libraries or so, and each tends to express the dependency for a single, specific version. Conan will typically raise an error (version conflict) when solving a dependency graph if the required versions don't match.

We are slowly moving towards letting recipes express dependencies with version ranges, similar to how it is typically done in [Python](https://peps.python.org/pep-0440/#version-specifiers) or rust (https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html) -

I was wondering if we could move toward having recipes express a dependency on spdlog such as `>=1.10.0` or `>=1.10.0 <2` - and if there are backwards compatibility guarantees (both in terms of source compatibility, and ABI compatibility, e.g. if spdlog is used in compiled mode). Some libraries (e.g. opencv, qt, zlib, ..) tend to have some strong compatibility guarantees, but I appreciate it is not easy to maintain in all scenarios.

Thanks!

**Comment by gabime** [comment]
We make an effort to maintain API compatibility (and, to a lesser extent, ABI compatibility), but it is **important to note that this is  not guaranteed**. If you plan to implement such recipes, I strongly recommend testing them rigorously.

**Comment by jcar87** [comment]
Thanks so much for the response - we'll try to figure out what the best way to proceed is in Conan Center, thanks!
