### ISSUE TITLE
fatal error: 'spdlog/fmt/bundled/core.h' file not found when building with emscripten and SPDLOG_FMT_EXTERNAL

### ISSUE THREAD

**Issue by db-tech** [gabime/spdlog#3286]
I am building spdlog with emscripten and want to use an external version fmt. So I used the option -DSPDLOG_FMT_EXTERNAL=ON as well as -Dfmt_DIR=/dir/to/fmt

This works and everything builds just fine.

In my cmake project I use it like this:
```
set(spdlog_DIR "/dir/to/spdlog")
...
find_package(spdlog CONFIG REQUIRED)
...
target_link_libraries(mygame PUBLIC spdlog::spdlog)

```
When I try to build this i get those errors:

```
include/spdlog/fmt/fmt.h:24:14: fatal error: 'spdlog/fmt/bundled/core.h' file not found
   24 |     #include <spdlog/fmt/bundled/core.h>
```

in fmt.h, SPDLOG_FMT_EXTERNAL seems not to be defined ?
I this definition not inherited from spdlog::spdlog ?

**Comment by tt4g** [comment]
The `spdlog_DIR` must be the root directory of spdlog installed by CMake.
Do you have spdlog installed there?

If the installed directory has the directory structure that CMake expects, it will find the macro definitions when spdlog is built in the CMake configuration file that exists there and automatically set them for the application.

**Comment by db-tech** [comment]
Hm, I don't think that is true. I always used the path to the cmake config file, which is in the directory <spdlog_install>/lib/cmake/spdlog/

When I do it like this, all my libs get found from cmake.

the cmake dokumentation states:

```
Config mode search attempts to locate a configuration file provided by the package to be found. A cache entry called <PackageName>_DIR is created to hold the directory containing the file.
....
 If <PackageName>_DIR has been set to a directory not containing a configuration file CMake will ignore it and search from scratch.
```

**Comment by tt4g** [comment]
<PackageName>_DIR` is the path where CMake will look for the library. However, it is not an error if no `*.cmake` file is found here
In any case, check the build log to see if `spdlog.so` is retrieved from `spdlog_DIR`.
If it is retrieved from `spdlog_DIR` but the `SPDLOG_FMT_EXTERNAL` macro is not defined, it is a CMake bug and should be reported to CMake..

**Comment by db-tech** [comment]
Appreciate your help, thanks.

As far as I know, _DIR is the path  cmake will look for the config file.
Although, setting sdplog_DIR will not throw an error, i did set REQUIRED in find_package:
`find_package(spdlog CONFIG REQUIRED)`

This is why i get this error when sdplog_DIR is not set.
```
CMake Error at cmake/emscripten/FindExternals.cmake:16 (find_package):
  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.
```

But yeah, this could also be a problem with cmake. I will investigate further.
Thanks anyway !

**Comment by db-tech** [comment]
Ok, this was absolutely my fault. I added spdlog::spdlog to the wrong target... 
I am so sorry for wasting your time.
