### ISSUE TITLE
The log cannot output line numbers

### ISSUE THREAD

**Issue by WbAccounts** [gabime/spdlog#3288]
I want to customize the log format, but I can't output the line numbers no matter what
```
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"

int main () {
    auto console = spdlog::stdout_color_mt("console");
    console->set_level(spdlog::level::level_enum::debug);
    spdlog::flush_every(std::chrono::seconds(1));
    spdlog::set_pattern("[%Y:%m:%d %X:%e %#] [line: %# ] [thread:%t] [%^%l%$] %v");

    console->info("this is info");
    console->debug("this is debug");
    console->warn("this is warn");
    console->error("this is error");
    console->critical("this is critical");
    return 0;
}
```

**Comment by tt4g** [comment]
See FAQ: https://github.com/gabime/spdlog/wiki/0.-FAQ#source-information-do-not-appear-when-using-custom-format

**Comment by WbAccounts** [comment]
If it is necessary to use macros to define the log level in order to output line numbers, it means that I cannot flexibly change the log level and must recompile to output debug logs. Is this not very user-friendly for debugging programs

**Comment by tt4g** [comment]
The purpose of the logging macro is to allow the removal of unnecessary logging statements at compile time: https://github.com/gabime/spdlog/wiki/0.-FAQ#how-to-remove-all-debug-statements-at-compile-time-

The `SPDLOG_ACTIVE_LEVEL` macro specifies the level of logging macros to keep after compilation, does not change the run-time logging level.

If you do not plan to remove the logging statement at compile time, simply define it as `#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE`.
