### ISSUE TITLE
Compile error with CeontOS 7 - g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

### ISSUE THREAD

**Issue by dujingning** [gabime/spdlog#3294]
`[ 90%] Building CXX object example/CMakeFiles/example.dir/example.cpp.o
cd /opt/spdlog/spdlog-1.15.0/build/example && /usr/bin/c++ -DSPDLOG_COMPILED_LIB -I/opt/spdlog/spdlog-1.15.0/include -O3 -DNDEBUG -std=c++11 -MD -MT example/CMakeFiles/example.dir/example.cpp.o -MF CMakeFiles/example.dir/example.cpp.o.d -o CMakeFiles/example.dir/example.cpp.o -c /opt/spdlog/spdlog-1.15.0/example/example.cpp
In file included from /opt/spdlog/spdlog-1.15.0/example/example.cpp:131:0:
/opt/spdlog/spdlog-1.15.0/include/spdlog/sinks/daily_file_sink.h: In static member function ‘static spdlog::filename_t spdlog::sinks::daily_filename_format_calculator::calc_filename(const filename_t&, const tm&)’:
/opt/spdlog/spdlog-1.15.0/include/spdlog/sinks/daily_file_sink.h:56:19: error: ‘put_time’ is not a member of ‘std’
         stream << std::put_time(&now_tm, file_path.c_str());
                   ^
/opt/spdlog/spdlog-1.15.0/example/example.cpp: At global scope:
/opt/spdlog/spdlog-1.15.0/example/example.cpp:274:13: error: specialization of ‘template<class T, class Char, class Enable> struct fmt::v11::formatter’ in different namespace [-fpermissive]
 struct fmt::formatter<my_type> : fmt::formatter<std::string> {
             ^
In file included from /opt/spdlog/spdlog-1.15.0/include/spdlog/fmt/bundled/format.h:41:0,
                 from /opt/spdlog/spdlog-1.15.0/include/spdlog/fmt/bundled/core.h:5,
                 from /opt/spdlog/spdlog-1.15.0/include/spdlog/fmt/fmt.h:24,
                 from /opt/spdlog/spdlog-1.15.0/include/spdlog/common.h:50,
                 from /opt/spdlog/spdlog-1.15.0/include/spdlog/spdlog.h:12,
                 from /opt/spdlog/spdlog-1.15.0/example/example.cpp:31:
/opt/spdlog/spdlog-1.15.0/include/spdlog/fmt/bundled/base.h:1141:8: error:   from definition of ‘template<class T, class Char, class Enable> struct fmt::v11::formatter’ [-fpermissive]
 struct formatter {
        ^
make[2]: *** [example/CMakeFiles/example.dir/example.cpp.o] Error 1
make[2]: Leaving directory `/opt/spdlog/spdlog-1.15.0/build'
make[1]: *** [example/CMakeFiles/example.dir/all] Error 2
make[1]: Leaving directory `/opt/spdlog/spdlog-1.15.0/build'
make: *** [all] Error 2
-bash-4.2#`

**Comment by dujingning** [comment]
[Version 1.15.0](https://github.com/gabime/spdlog/releases/tag/v1.15.0)

**Comment by tt4g** [comment]
Duplicate #2666 #2834

See also: https://stackoverflow.com/a/36970437

GCC 4.8.x does not support complete C++11.
