### ISSUE TITLE
[feature request] Ask for customized log filename format

### ISSUE THREAD

**Issue by dentiny** [gabime/spdlog#3295]
Context, [ray](https://github.com/ray-project/ray/tree/00163c69bb448b5cfd56685b082b26d7cddb609d) has its own log filename logic here to handle concurrently running processes and create unique logging filename: https://github.com/ray-project/ray/blob/00163c69bb448b5cfd56685b082b26d7cddb609d/python/ray/_private/node.py#L828-L830, which unfortunately it perfectly conflicts with spdlog's rotation filename formatting.
So if we enable spglog log rotation and unique filename features at the same time, we cannot tell whether the new file created is from which process.

For the current implementation, spdlog doesn't allow users to customize `calc_filename` function.
https://github.com/gabime/spdlog/blob/24dde318fe034f0c7e809daa5a6e81dc85e1155a/include/spdlog/sinks/rotating_file_sink-inl.h#L52-L64

My feature request and proposal is to allow applications to customize the logging filename format function via a function pointer, or any callable. The callable could set via constructor, or via a function similar to `RotationHandle::SetRotationFnameFormat`.

Example code change:
```
rotating_file_sink(
    filename_t base_filename,
    std::size_t max_size,
    std::size_t max_files,
    bool rotate_on_open,
    const file_event_handlers &event_handlers,
    std::function<std::string(basename, index, extension)>);
```
or 
```
void rotating_file_sink::OverrideRotationLogFilename(std::function<std::string(basename, index, extension)>);
```

Alternatives considered:
- I understand users could always write their customized sink to achieve whatever they want, but here the only thing I ask for is the filename decision function, having a whole class to maintain seems an overkill.

It's similar to previous feature request:
- https://github.com/gabime/spdlog/issues/2612
- https://github.com/gabime/spdlog/issues/2491

If you think the proposal makes sense to you, I'm more than happy to help with the implementation.

**Comment by tt4g** [comment]
I think there is a restriction that the filenames must be generated from the index in order to rotate the log files, which prevents customization of `calc_filename`.
If you have an idea to work around that problem, please send a PR.

**Comment by dentiny** [comment]
@tt4g I made a PR https://github.com/gabime/spdlog/pull/3296, let me know if you have any comments / feedbacks :)
