### ISSUE TITLE
How to resolve the issue of spdlog-related programs crashing

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [gabime/spdlog#3297]
**I installed spdlog using vcpkg, and my code editor is CLion. The program runs fine on my local machine, but when I copy the cmake-build-release folder to another computer and run the executable inside the folder, the program crashes immediately, and the logs are not printed to the file. What could be the reason for this?**
```c++
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

int main() {
    spdlog::set_default_logger(spdlog::basic_logger_mt("file_logger", "logs/my_log.txt"));
    spdlog::set_level(spdlog::level::info);
    spdlog::set_pattern("[%n] [%Y-%m-%d %H:%M:%S.%e] [%l] [%t] [%s %!:%#]  %v");
    spdlog::info("spdlog init...");
    spdlog::flush_on(spdlog::level::info);
    SPDLOG_INFO("spdlog init!!!");
    SPDLOG_INFO("spdlog init!!!");
    SPDLOG_INFO("spdlog!!!");
    spdlog::default_logger()->flush();
    return 0;
}
```
```cmake
cmake_minimum_required(VERSION 3.29)
project(spdlog_t)

set(CMAKE_CXX_STANDARD 20)

add_executable(spdlog_t main.cpp)

find_package(spdlog CONFIG REQUIRED)
target_link_libraries(spdlog_t spdlog::spdlog_header_only)
```

**Comment by tt4g** [comment]
I do not have enough information to determine the cause.
I can only guess at the following causes

* If spdlog is a shared library, the `.dll` files must have been copied to another machine
* Local machine and another machine have different versions of MSVC runtime

  MSVC made a breaking change at runtime some time ago (Duplicate: #3278 #3212 #3145)
  See: https://github.com/gabime/spdlog/issues/3119#issuecomment-2218733127
  See also: https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio

**Comment by LetAmericaGreatAgain** [comment]
**Thank you, but I don't think the two reasons you mentioned are the cause. I have tried both the header-only and .dll modes, but neither worked. Other programs that I wrote on my local machine work fine on that machine. Additionally, I tested the following program, and the program crashes immediately after pressing Enter at the first input prompt. It seems that there might be some underlying issue with spdlog itself.**
**The result was that it only created the my_log.txt file, but no content was written to it.**
```c++
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

int main() {
    system("pause");
    spdlog::set_default_logger(spdlog::basic_logger_mt("file_logger", "logs/my_log.txt"));
    spdlog::set_level(spdlog::level::info);
    spdlog::set_pattern("[%n] [%Y-%m-%d %H:%M:%S.%e] [%l] [%t] [%s %!:%#]  %v");
    spdlog::info("spdlog init...");
    spdlog::flush_on(spdlog::level::info);
    SPDLOG_INFO("spdlog init!!!");
    SPDLOG_INFO("spdlog init!!!");
    SPDLOG_INFO("spdlog!!!");
    spdlog::default_logger()->flush();
    system("pause");
    return 0;
}
```

**Comment by tt4g** [comment]
It sounds like it is caused by a resource release operation after the application is exited.
Please make sure to call `spdlog::shutdown()` at the end of `main()`.

Another possible cause is simply that the application does not have file creation permissions on the another machine.
In this case, try `try`-`catch` to see the exception message and check the exit status.
