### ISSUE TITLE
Unexpected appending of "txt" at the end of a log filename

### ISSUE THREAD

**Issue by aardvarkk** [gabime/spdlog#333]
I was confused by the usage of the filename parameter for `rotating_logger_mt`. It's called `filename`, so I interpreted that as being the absolute path to the file. Instead, it seems like `.txt` is appended onto the end of whatever is provided, so I ended up getting something like `mylog.txt.txt`. Is there a reason that the extension is hardcoded to `.txt`? Why not allow the entire filename to be specified by the caller?

As a result of this behaviour, I have to implement two functions in my code: one to output the desired log filename *without* an extension (to provide to `spdlog`), and one to output the log filename *with* an extension (when I want to operate on the log file myself).

**Comment by gabime** [comment]
The intention was to try to keep the extension for the rotated files. Maybe this it is not really needed (i.e. rotated log files would be just juse named log.txt.1, log.txt.2) and maybe there is a better way to achieve this. I will happy to consider alternative ways.

A possible fix would be to ignore the extension if it is empty string

**Comment by horar** [comment]
hi @gabime , looking shortly into my /var/log - most logs just add number on the end of file i.e.
<pre>
filename.ext
filename.ext.0
filename.ext.1
filename.ext.2
</pre>
eventuelly, extra suffix is for rotated/compressed file i.e.:
<pre>
filename.ext
filename.ext.0.xz
filename.ext.1.xz
filename.ext.2.xz
</pre>

I vote for rotating file and let user use plain filename or filename with extension.

**Comment by gabime** [comment]
Yes, I think you right. It would also simplify things a little which is always good..

**Comment by horar** [comment]
I can try create a PR  (?)

**Comment by gabime** [comment]
Sure. Please do

**Comment by horar** [comment]
this is related to #324, with bullet 3
