### ISSUE TITLE
Provide an opition to compile spdlog with no cpp exception.

### ISSUE THREAD

**Issue by harrywong** [gabime/spdlog#334]
Sometimes I don't use any exception in my project to improve performance, then I can then add -fno-exception to gcc. But cuz spdlog need to compile with exceptions (although only in constructors.), so that flags still need to be added.

Can provide a define or something to make spdlog not use any c++ exceptions? Likely just use assert instead of exceptions for special need?

Thanks!

**Comment by godbyk** [comment]
You can read the discussion @gabime and I had when we implemented the existing usage pattern of exceptions at https://github.com/gabime/spdlog/pull/231. We didn't remove exceptions completely because we had some unanswered questions about doing so.

If you're more familiar with the ramifications of `-fno-exceptions`, perhaps you could weigh in on some of the questions posed in that conversation.

Thanks!

**Comment by harrywong** [comment]
I've read that discussion. What about just like what fmt does, add a option to treat all exception as `assert(false);`. It may not smell good, but if someone enable this option, then it's his responsibility to ensure to test all the code runs well. Just add one possibility.

**Comment by gabime** [comment]
Right, This doesn't smell good. 
Any trivial error, like failing to write to disk or failing to rotate would just crash the program.

**Comment by harrywong** [comment]
Now the spdlog has the error handle function, so if the error occurred in spdlog (like write to disk or failing to rotate), it will just call error handle. If user handle it right, it won’t be crashed.

Only when in the situation where fmt failed or error in opening file will crashed.

For fmt crashed, if the code is test well, it can be avoid. As for opening file, it’s not a big deal, because it always happens in the startup period.

**Comment by gabime** [comment]
Nope. spdlog throws excpetioms internally and catch them before calling the error handler
