### ISSUE TITLE
[Feature request] Trace logging to memory

### ISSUE THREAD

**Issue by MathijsV** [gabime/spdlog#337]
To track were e.g. a crash or some other weird behaviour originates, it is sometimes necessary to add a lot of log messages so that you can see later on what happened in the code. This is especially true if your program is already "in the field" and no longer in a debugging environment. However this way log files would grow large pretty quickly. However, I'm only interested in the log messages in case something weird happened (i.e., a warning or error gets logged somewhere). So, the idea:
-Leave a lot of "trace" logs in the code, that don't get logged directly to a sink, but stay in memory for a while (for example in a circular buffer of a given size)
-When a message of a higher level gets logged (e.g. warning or error), the content of the circular buffer is written to the sink.
-If the buffer is full but no error was logged, the oldest messages get overwritten, so that you always see the last "x" messages in the trace log.

**Comment by gabime** [comment]
Might be useful indeed, and it shouldn't be too complicated to implement such a sink.

One problem is that those trace messages will have some cost even if not logged, because the formatting of the format string  (the formatting of "some message {} {}, arg1,arg2) is done at call site.

**Comment by gabime** [comment]
Done. Added enable_backtrace() and dump_backtrace() to the logger.

**Comment by Delgan** [comment]
Hi @gabime.

I have one question regarding the implementation of `dump_backtrace()`. In a previous message, you state the following:

> One problem is that those trace messages will have some cost even if not logged, because the formatting of the format string (the formatting of `"some message {} {}", arg1,arg2`) is done at call site and cannot be deferred to later stage .

Can you confirm that the final implementation of `dump_backtrace()` has this problem?
Any reason not to defer the formatting by storing the logging arguments as well?

I just realized how powerful it would be to get the "trace" logs in production after a crash, via Sentry for example.
But of course, I'd like to avoid paying the performance cost of formatting when everything's is fine.

**Comment by gabime** [comment]
Yes, the fmt formatting is always dome at call site. Otherwise a deep copy need to be done to store the args so that they can be accessed asynchronously later. Note that after crash, nothing in your program is guaranteed to work, including spdlog.

**Comment by Delgan** [comment]
Thanks for the answer.

I suppose _technically_ we could imagine a helper class wrapping the arguments to defer their formatting, but as you said, it likely needs to be combined with an asynchronous sink to ensure it's processed correctly before a crash. It seems too complex to be worth the effort, too bad.
