### ISSUE TITLE
spdlog::logger and perfect forwarding

### ISSUE THREAD

**Issue by azadkuh** [gabime/spdlog#338]
just want to know if there is any technical reason behind the current implementation of `spdlog::logger`:
```cpp
class logger
{
    template <typename... Args> void 
    log(level::level_enum lvl, const char* fmt, --> const Args&... <-- args);

    template <typename... Args> void 
    trace(const char* fmt, --> const Args&... <-- args);
};
```

instead of using **perfect forwarding** api:
```cpp
class logger
{
    template <typename... Args> void 
    log(level::level_enum lvl, const char* fmt, Args&&... args);

    template <typename... Args> 
    void trace(const char* fmt, Args&&... args);
    // std::forward<Args>(args)...
};
```

**Comment by gabime** [comment]
what would the advantage in that?

**Comment by azadkuh** [comment]
*perfect forwarding* has it own pitfalls and problems as [eric niebler](http://ericniebler.com/2013/08/07/universal-references-and-the-copy-constructo/) described, but it paves the way to optimize *rvalue*s and helps copy elision to happen if the API need to **copy** the arguments. for example user can explicitly `std::move(a_big_string)` into `spdlog` instead of copying by `const &`.

**Comment by gabime** [comment]
since when ```const &``` copies anything?

**Comment by azadkuh** [comment]
a trivial use case like this:

```cpp
//--  spdlog
template<typename... Args>
void spdlog:the_api(const Args&... args) {
   deferred_call_in_worker_thread([&](...)) {
       // log them all later
   }
}

//-- user code
void user_code() {
    std::string a_big_string = ...;
    spdlog::the_api(a_big_string, make_some_other_string());
} // strings are destroyed here, so the spdlog needs to copy them for differed calls
```

**Comment by gabime** [comment]
Right. Thanks for the example.
Currently spdlog doesn't need to move or copy the args (it only use them at the call site, never in different thread) so it is not needed.

In the future, however, this certainly might change (for example defrreing the fmt formatting to the background thread in async loggers).
