### ISSUE TITLE
how to include "__FILE__" and "__FUNC__" and "__LINE__" into log formatter

### ISSUE THREAD

**Issue by neutronsharc** [gabime/spdlog#340]
Hi all,  Is there a way to include these macros into log formatter? This would be extremely useful to help locate exact location of some log output.  Thank you!

**Comment by gabime** [comment]
No.  I didn't find an easy way to implemnet this

**Comment by neutronsharc** [comment]
I added a wrapper layer atop spdlog, and use macros to prepend __FILE__ to log entries.  Now problem solved.  spdlog is really awesome. Great work gabime!

Here is my code in case anyone is interested:
https://github.com/neutronsharc/logtest/blob/master/hcdlog.h#L77

**Comment by gabime** [comment]
Thanks. I think I might add a set of macros to the API to provide this feature.

**Comment by neutronsharc** [comment]
This would be better!  Please send me a notice when you are ready.

**Comment by carun** [comment]
I am wondering if this would work after all with LTO turned on. Any thoughts?

**Comment by gabime** [comment]
why not? it just a macro

**Comment by htfy96** [comment]
[source_location](http://en.cppreference.com/w/cpp/experimental/source_location) would be a more elegant solution. 
However it is badly supported in gcc and not even implemented in clang. Hope that several years later this could be adopted as part of standard.

**Comment by mythos002** [comment]
Hi,
I was searching myself for such a solution and after a bit of playing around I came up with something like this (definition is done in spdlog.h just after the original SPDLOG_TRACE define):

`#define SPDLOG_TRACEF(logger, ...) logger->trace("[" + fmt::format(pathlast(__FILE__)) + "::" SPDLOG_STR_HELPER(__LINE__) "::" + string(__func__) + "] " + fmt::format(__VA_ARGS__))
#define SPDLOG_TRACEPF(logger, ...) logger->trace("[" + fmt::format(pathlast(__FILE__)) + "::" SPDLOG_STR_HELPER(__LINE__) "::" + string(__PRETTY_FUNCTION__) + "] " + fmt::format(__VA_ARGS__))`

I had a few problems getting `__func__` and `__VA_ARGS__` to get interpreted together, so I've been testing around and came up with the above.

As you can see I use the fmt::format function to pass several arguments preformated into the logger, so the logger itself should interpret them as normal text like the "[" , "::" and "]" stuff. Also for the `__func__` and `__PRETTY_FUNCTION__` I encapsulated them with the string() function to get a proper string output.

As for the `__FILE__` parameter I wrote a small function (`pathlast`) to return only the filename itself without the path. But thats something more of a cosmetic thing.

This seems from my testings to work like expected.

You can call something like this in your code:

`SPDLOG_TRACEF(logging_debug->logger,"Vector Entry {} Entry {}: {}", a, i, text (part2));`

And it should output the following:

[19.03.2017 00:30:13] [trace] [xml_parse.cpp::147::getElementValuesVector] Vector Entry 0 Entry 0: v1
[19.03.2017 00:30:13] [trace] [xml_parse.cpp::147::getElementValuesVector] Vector Entry 0 Entry 1: a1
[19.03.2017 00:30:13] [trace] [xml_parse.cpp::147::getElementValuesVector] Vector Entry 0 Entry 2: b1

Also with `__PRETTY_FUNCTION__` output using SPDLOG_TRACEPF:

[19.03.2017 00:54:27] [trace] [xml_parse.cpp::147::std::vector<std::vector<std::__cxx11::basic_string<char> > > XML_Parser::getElementValuesVector(tinyxml2::XMLDocument&, std::__cxx11::string)] Vector Entry 0 Entry 0: v1
[19.03.2017 00:54:27] [trace] [xml_parse.cpp::147::std::vector<std::vector<std::__cxx11::basic_string<char> > > XML_Parser::getElementValuesVector(tinyxml2::XMLDocument&, std::__cxx11::string)] Vector Entry 0 Entry 1: a1
[19.03.2017 00:54:27] [trace] [xml_parse.cpp::147::std::vector<std::vector<std::__cxx11::basic_string<char> > > XML_Parser::getElementValuesVector(tinyxml2::XMLDocument&, std::__cxx11::string)] Vector Entry 0 Entry 2: b1

As I'm not so far into the whole stuff that depend on fmt and spdlog itself, I cannot say for sure that this is a viable solution, especially if you look into performance. Also I'm not sure if the use of fmt::format in this way is a good idea, but I couldn't find another way to make `__func__` and `__VA_ARGS__` get interpreted together, without being preformated on call.

Anyway maybe this kind of snippet will help into having such an option to use in spdlog for trace or debug messages.

**Comment by xoox** [comment]
OpenCV has sophisticated trace utilities and macros. Trace macros can be used in the beginning of functions. Just add some lines like this:
```
CV_TRACE_FUNCTION();
CV_TRACE_ARG_VALUE(arg_id, arg_name, value);
```
could we learn something from it and implement  lightweight and powerful trace macros?
See OpenCV's code here:
https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/utils/trace.hpp
https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/utils/trace.private.hpp
https://github.com/opencv/opencv/blob/master/modules/core/src/trace.cpp

**Comment by gabime** [comment]
Yes, its a good idea.

**Comment by mateuszzz88** [comment]
I have proposal how to solve this issue in PR above - do you like it?

**Comment by micfan** [comment]
+1

**Comment by gabime** [comment]
> I have proposal how to solve this issue in PR above - do you like it?

Too complicated. Also could be much more efficient (see my comment in the PR)

**Comment by peergynt** [comment]
I think that it would be useful to be able to add a filename, function name and line number to a log_msg and have one or more flag(s) that the formatter can use. If I had to pick only one, the filename is probably the most important. Filename and line number could be a good compromise if you are worried about the extra bytes.

Also, you could be more flexible and not assume that these details will necessarily come from the preprocessor (i.e. decouple the capture of those attributes). For instance you could have an external interface sending logs to spdlog with its own local filename/function name. Using a "string view" approach instead of assuming a zero terminated C string might be more convenient.

**Comment by gabime** [comment]
Latest versions of spdlog support the "%@", "%s" and "%#" patterns for this .

**Comment by carun** [comment]
@gabime https://github.com/gabime/spdlog/wiki/3.-Custom-formatting doesn't contain the reference for `%@`,  `%s` and `%#`
