### ISSUE TITLE
__FILE__, __FUNCTION__, __LINE__

### ISSUE THREAD

**Issue by xinthose** [gabime/spdlog#341]
Hello.  How can I add the __FILE__, __FUNCTION__, __LINE__ preprocessor macros to every log message?  

The main advantage of Boost logging is that you can predefine your own logging macros like so:
```
#define INFO  BOOST_LOG_SEV(my_logger::get(), boost::log::trivial::info) << __FILE__ << "(" << __FUNCTION__ << ":" << __LINE__ << ") >> "
#define WARNING  BOOST_LOG_SEV(my_logger::get(), boost::log::trivial::warning) << __FILE__ << "(" << __FUNCTION__ << ":" << __LINE__ << ") >> "
```
and use it like this: `INFO << "my message";`

**Comment by gabime** [comment]
Currently it only supporterd with trace messages: 

```c++
#define SPDLOG_TRACE_ON
SPDLOG_TRACE(logger, "some message {}", 123);
```

**Comment by xinthose** [comment]
Thank you.  I can't get it to print.  Does it work with spdlog::get?

My calling function
```
	auto log = spdlog::get("log");	
	SPDLOG_TRACE(log, "Enabled only #ifdef SPDLOG_TRACE_ON..{} ,{}", 1, 3.23);
```
Logging setup
```
		spdlog::set_async_mode(8192);	// pre-allocated logging slots, must be power of 2
		spdlog::set_level(spdlog::level::trace);		
		
		// 2. create sinks
		sinks.push_back(std::make_shared <spdlog::sinks::stdout_sink_st>());
		sinks.push_back(std::make_shared <spdlog::sinks::daily_file_sink_st>(log_file_name_1, "txt", log_rotate_hour, log_rotate_min));		
		
		// 3. create logger
		log.reset();
		log = std::make_shared <spdlog::logger>("log", begin(sinks), end(sinks));
		// Formatting options: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting
		log->set_pattern("%C-%M-%d|%T.%f|%t|%l: %v");
		
		// 4. make logger global
		spdlog::register_logger(log);
```
I have the trace define set too.

**Comment by gabime** [comment]
Trycalling  log.flush() to see it immediately.

Also ```set_asyc_mode``` has no effect in your example since it manually creates sync loggers.

**Comment by xinthose** [comment]
You mean `log->flush();`?  It did not work.  I am attaching my code so you can recreate the issue if you like.  
[spdlog.zip](https://github.com/gabime/spdlog/files/678081/spdlog.zip)

**Comment by gabime** [comment]
I see the problem. In logging.h you need to define the SPDLOG_TRACE_ON bevore including spdlog.h

**Comment by xinthose** [comment]
I just tried that, and it's set in `tweakme.h` too, but the problem persists (no trace or debug messages).  Could it be a problem with using a class constructor?

**Comment by gabime** [comment]
You need to ``` log->set_level(trace)``` (because the logger is created directly, no thru spdlog).
I hope this will fix it

**Comment by xinthose** [comment]
Thank you.  Now I get the following messages:
```
16-30-31|21:30:12.991542|5347|trace: [src/main.cpp line #19] Enabled only #ifdef SPDLOG_TRACE_ON..1 ,3.23
16-30-31|21:30:12.991567|5347|debug: Enabled only #ifdef SPDLOG_DEBUG_ON.. 1 ,3.23
```
I do have the defines set before the include just like you said in `logging.hpp`
