### ISSUE TITLE
Support logging thread name on Linux

### ISSUE THREAD

**Issue by carun** [gabime/spdlog#342]
On Linux, it is possible to name a thread using `prctl`. It would be convenient to support logging the thread name. It will be very helpful in debugging.

```
#include <sys/prctl.h>
...
char thrName[16] = {0};
::prctl(PR_GET_NAME, thrName, 0, 0, 0);
std::cout << thrName << std::endl;
```

**Comment by DrLynix** [comment]
Side-note: Microsoft has implemented proper thread names recently (not talking about the debugging exception hack) with [SetThreadDescription](https://docs.microsoft.com/fr-fr/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription). It would be nice to support it as well.
