### ISSUE TITLE
write error and critical logs to stderr

### ISSUE THREAD

**Issue by Tmplt** [gabime/spdlog#345]
In a project I work on I use spdlog to report errors to the user. To match the behavior of other cli-programs, I want that output written to `stderr`. Could `level::{err,critical}` logging be changed to write to `stderr`, or could a define perhaps be exposed in `tweakme.h`?

Cheers.

**Comment by gabime** [comment]
You can add an additional stderr sink with its level to level::error.
This way your logger would have 2 sinks with different levels.

**Comment by Tmplt** [comment]
The wiki seems to lack the level-setting part, unless I missed it completely. Could you show how this would be done?

**Comment by gabime** [comment]
Just call set_level(..) on any sink:
```c++
sink->set_level(spdlog::level::err);
```

**Comment by Tmplt** [comment]
Ah, thanks.

I've come thus far:
```cpp
auto setup_logger()
{
    std::vector<spdlog::sink_ptr> sinks;

    auto stdout_sink = spdlog::sinks::stdout_sink_mt::instance();

    auto stderr_sink = spdlog::sinks::stderr_sink_mt::instance();
    auto color_stderr_sink = std::make_shared<spdlog::sinks::ansicolor_sink>(stderr_sink);
    color_stderr_sink->set_level(spdlog::level::err);

    sinks.push_back(stdout_sink);
    sinks.push_back(color_stderr_sink);

    auto logger = std::make_shared<spdlog::logger>("main", std::begin(sinks), std::end(sinks));
    logger->set_pattern("%l: %v");

    return logger;
}
```

As wanted, error logs are now printed to `stderr`, but they are also printed to `stdout`. Can I assign `stdout_sink` to print everything except for error and critical logs, which `color_stderr_sink` handles?

**Comment by Tmplt** [comment]
To answer my own questions:

`logger->set_level(spdlog::level::info);` does affect both sinks.

And I gather from [`details/logger_impl.h`](https://github.com/gabime/spdlog/blob/master/include/spdlog/details/logger_impl.h#L64) that it is not possible to assign a singular level or range of levels to a sink: `stdout_sink` prints `err`-logs since `level::err`>`level::info`.

**Comment by gabime** [comment]
Yes, you got it right, but note that if for example the logger has "info" level then debug messages won't get forwarded by the logger to the underlying sinks, regardless of their own level. 

I am not sure that ```limit_level()``` would worth the extra cost just for this rare use case though.. Maybe you could implement a custon sink that wraps those 2 sinks by forwarding the messages accoriding to the level. should be easy I think.

**Comment by Tmplt** [comment]
On 7 January 2017 10:51:25 CET, Gabi Melman <notifications@github.com> wrote:
>Yes, you got it right, but note that if for example the logger has
>"info" level then debug messages won't get forwarded by the logger to
>the underlying sinks, regardless of their own level. 
>
>I am not sure that ```limit_level()``` would worth the extra cost just
>for this rare use case though.. Maybe you could implement a custon sink
>that wraps those 2 sinks by forwarding the messages accoriding to the
>level. should be easy I think.
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabime/spdlog/issues/345#issuecomment-271073995

Alright, makes sense.

A custom sink does sound like a better idea. A singular if-statement should probably suffice. I'll see about writing and posting the solution here.

**Comment by Tmplt** [comment]
The log message level is available in `spdlog::details::log_msg`, so:

```cpp
class split_sink : public spdlog::sinks::sink {
    void log(const details::log_msg &msg) override
    {
        if (msg.level <= spdlog::level::warn)
            std::cout << msg.formatted.str();
        else
            std::cerr << msg.formatted.str();
    }

    void flush()
    {
        std::cout << std::flush;
    }
};
```
is what I came up with.
I now set the logger up with:
```cpp
auto setup_logger()
{
    auto sink = std::make_shared<split_sink>();
    auto logger = std::make_shared<spdlog::logger>("main", sink);

    logger->set_pattern("%l: %v");
    logger->set_level(spdlog::level::err); // as default

    return logger;
}
```

Thanks for your help!

**Comment by gabime** [comment]
Looks good. Dont forget protect with mutex if you need thread safety.
