### ISSUE TITLE
cyclic memory buffer logging

### ISSUE THREAD

**Issue by p0fi** [gabime/spdlog#346]
Hello,

id like to know if its somehow possible to implement something like this:

I have set the debug lvl to <info> so, naturally a lot of <debug> logs are not visible but they are written in a cyclic memory buffer. Once an <error> occurs not only the <error> and <info> messages, but also the <debug> content in the cyclic memory buffer is written to the configured sink. Like this it would be possible to set the debug lvl lower during normal operation but in error cases more information are written to the log.

I think apple implemented some kind of this in-memory logging in their new unified logging system. This would be a good improvement to the already excellent spdloging lib.

**Comment by gabime** [comment]
possible duplicate of #337

**Comment by p0fi** [comment]
Oh well sorry, that is definitely a duplicate :) sorry for that gonna close this one here better.
