### ISSUE TITLE
SPDLOG_TRACE doesn't work for me when turn on the macro

### ISSUE THREAD

**Issue by PraflyGod** [gabime/spdlog#350]
// Uncomment to enable the SPDLOG_DEBUG/SPDLOG_TRACE macros.
//
#define SPDLOG_DEBUG_ON
#define SPDLOG_TRACE_ON

**Comment by gabime** [comment]
Try  to set the log level to 'trace' for this to work

**Comment by PraflyGod** [comment]
great！ thanks a lot!
