### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by Code-ReaQtor** [gabime/spdlog#351]
How does this library respond to scalability? One example is multi-process logging (Possibly, multiple processes writing on the same file).

Thanks!

**Comment by gabime** [comment]
It doesnt support multi processes to same file.

**Comment by Code-ReaQtor** [comment]
What are the alternatives to achieve scalability using spdlog? Any recommendations?

**Comment by gabime** [comment]
Maybe different file per process?would be simplest

**Comment by Code-ReaQtor** [comment]
Thanks @gabime
