### ISSUE TITLE
How do I set up spdlog?

### ISSUE THREAD

**Issue by BoredBored** [gabime/spdlog#352]
So what I did was download the source folder & extracted it, then I just added it to my code blocks project -- but then I start getting a bunch of errors. So how do I set up this thing?

Note: My system is 64 bit ubuntu

**Comment by gabime** [comment]
what errors?

**Comment by BoredBored** [comment]
Give me a sec, I'm gonna screenshot it

**Comment by BoredBored** [comment]
Build log:
[![Screenshot from 2017-01-16 13-58-45.png](https://s24.postimg.org/tymnivwbp/Screenshot_from_2017_01_16_13_58_45.png)](https://postimg.org/image/sjl2u5v8h/)

IDE window:
[![Screenshot from 2017-01-16 14-01-35.png](https://s24.postimg.org/a9m1wi2vp/Screenshot_from_2017_01_16_14_01_35.png)](https://postimg.org/image/mbhfqnc41/)

Ya, so, whats happening?

**Comment by gabime** [comment]
what are the compiler flags?

**Comment by BoredBored** [comment]
They are
- "Have g++ follow the C++ 14 ISO language standard [-std=c++14]"
- and "Optimize fully (for speed) [-O3]"

**Comment by BoredBored** [comment]
Please help -- I don't know what to do :(

**Comment by gabime** [comment]
try to remove them from the project. threse are just header files  and should not be part of the project (make sure the compiler search path -I includes the top folder of spdlog)

**Comment by BoredBored** [comment]
Thanks :)
