### ISSUE TITLE
Rotating takes too long in rotating_file_sink

### ISSUE THREAD

**Issue by harrywong** [gabime/spdlog#356]
Previous days I met a problem in rotating_file_sink in my production system.

The application is very sensitive to the time. Sometimes I found the application went wrong. After a several times, I found that it's because I use the rotating file logger and when it's rotating, it took too long time. Because it need to rename all the logs generated before. And doing things in filesystem is really slow.

Now, the spdlog will rotate all the files to the next one. What about just create a new file. Like we have log1.txt, log2.txt. When need to rotate, just rotate and open log3.txt file, so it's no need take too long time.

**Comment by gabime** [comment]
What do you mean by "too long"? Can you please provide numbers (duration time, number of files rotated, etc)?
In any case if your app is very time sensitive, you should use the async mode.

**Comment by harrywong** [comment]
I've done some simple benchmarks. In my ubuntu, rename a simple file takes 0.8us. It means when you rename 8 files, it will take more than 6us. And badly, it's linear variety, so when you have more file, you need more time.

And I'm using the async mode, but when it come to error log, I need to flush the logger. Comes to async logger, it will spin to wait the async logger to write finished. So consider to the switch contexts, it usually take more time, aka. its O(n) complexity. So when it comes to a error log and it also need to rotate, the application goes wrong.

I think we need to provide a stable design for rotating file logger. Only create a new file with no rotaing will take constant time. I mean when we have files: `log_1.txt, log_2.txt, log_3.txt`, when it's need to rotate, just create a new file `log_4.txt`.

 What do you think?

**Comment by gabime** [comment]
```flush()``` by definition waits until *all* items in the async queue get processed and flushed to disk, so no wonder it takes time. Even without rotating it can take log time.

Anyway I have no objection to add an option to the rotation sink to prevent rotating. Maybe another boolean in the ctor to indicate if files need to be rotated or not.
