### ISSUE TITLE
%P not working?

### ISSUE THREAD

**Issue by aharonhaber** [gabime/spdlog#358]
have following in my pattern line "...process:%P,thread:%t,..."
Logs are printed as follows:
,process:%P,thread:21516,

**Comment by gabime** [comment]
which version of spdlog? please try latest version

**Comment by vasyan1337h4x0r** [comment]
@gabime Which latest version? Latest tagged release is 0.11.0 and it doesn't support %P option. Should I use the master branch? Is it ok to use an unreleased version?

**Comment by vasyan1337h4x0r** [comment]
Btw, I'm not @aharonhaber. Just stumbled upon %P not working.

**Comment by gabime** [comment]
@vasyan1337h4x0r  please try the latest from the master branch. it is a good version

**Comment by vasyan1337h4x0r** [comment]
@gabime Ok, thanks. If this version is good, why not make a release?

**Comment by gabime** [comment]
will have a release soon.

**Comment by vasyan1337h4x0r** [comment]
Great! And if we're talking about this stuff, you might consider keeping some changelog. It might be useful for your users. Anyway, thanks for your help.
