### ISSUE TITLE
Access internal streams

### ISSUE THREAD

**Issue by kaspermarstal** [gabime/spdlog#359]
Is it possible to get access to the internal streams? For example, say I am developing a library and internally use spdlog that just logs to some streams. I want the user to be able to decide where the the streams should end up (e.g. cout or a file), so the interface of my library need to expose just the streams to the user. Is this possible?

**Comment by gabime** [comment]
Maybe ostream_sink can help. It writes to a given ```std::ostream```passed to it ctor (https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/ostream_sink.h)

But note it is rather dumb sink, it just writes to the stream (e.g. no rotating etc.)

**Comment by kaspermarstal** [comment]
Thank you for your help :)
