### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by justinmcbride** [gabime/spdlog#360]
Hey,

I appreciate this great library and use it heavily through my projects. I was just wondering what kind of release timeline/schedule you're following. The latest release is currently 65 commits behind the master, and I hadn't seen any mentions of plans for the next release.

(Sorry if this isn't the right place to ask -- it's the only place I can find to ask this question)

Thank you!

**Comment by gabime** [comment]
Hi,

Thanks for the feedback. I am glad you find the lib useful.
Basically, when the are enough substantial commits (imporant bug fixes, major changes) I do a release. There is no official schedule or timeline though..

**Comment by justinmcbride** [comment]
Thanks for the response! Would it be pretty safe to merge the incremental masters into my projects then? Or would you recommend waiting until an official release?

**Comment by gabime** [comment]
It should be ok, yes..

**Comment by justinmcbride** [comment]
Thank you!
