### ISSUE TITLE
It's not header only

### ISSUE THREAD

**Issue by alexhunsley** [gabime/spdlog#361]
This project isn't header only. There are at least 2 c files in it. Fix the project description to save the time of people who are looking for header-only projects please?

**Comment by xaqq** [comment]
Which files are troubling you?

**Comment by alexhunsley** [comment]
In the bundled folder, format.cc and ostream.cc

**Comment by gabime** [comment]
Even though they are named .cc, they are treated as regular headers. They are included using regular #include by the fmt lib, and should not be compiled or used independently.
