### ISSUE TITLE
spdlog.rb now in homebrew, add to README.md?

### ISSUE THREAD

**Issue by ahundt** [gabime/spdlog#364]
I wanted to let you know I added an [spdlog formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/spdlog.rb) to [homebrew](brew.sh) and soon [linuxbrew](linuxbrew.sh), which can be installed with `brew install spdlog`. Perhaps this information is worth adding to the README.md?

**Comment by gabime** [comment]
Thats great, thanks!
Sure, tell me what to write or open a pr.

**Comment by ahundt** [comment]
done! I also made sure you have write access to the pull request in case you wanted to make additional tweaks:
https://github.com/gabime/spdlog/pull/366

**Comment by gabime** [comment]
I updated the readme. Thanks!
