### ISSUE TITLE
Log time consistency

### ISSUE THREAD

**Issue by martink173** [gabime/spdlog#365]
Hi,
I'm writing time points into my log messages, which are taken from chrono library on windows 7. After logging 60000 data points (in my case 1000 per second), the logged time points are 5ms off from the logged time of spdlog. As far as I know spdlog also takes the time from chrono. Any ideas to explain this behaviour?
Thanks

**Comment by gabime** [comment]
spdlog uses chrono::system_clock::now()

How do u take your time?

**Comment by martink173** [comment]
I use high_resolution_clock::now();

**Comment by martink173** [comment]
Basically I'm counting thread activations and log the wakeup times of my thread. My thread is woken up every 1ms which seems to work according to my own logged clock time via chrono (I'm using a delay compensation mechanism). Comparing with spdlog's clock, I noticed that the activation count no 60000 is reached +5ms according to spdlog's time.

**Comment by gabime** [comment]
just out of curiosity, could you change spdlog to high_resolution_clock(loc-_clockmis defined in common.h) and see if this fix it?

**Comment by martink173** [comment]
This change leads to compiler errors.

**Comment by martink173** [comment]
I recompiled my own application to use system_clock". Then the logged time corresponds exactly to the spdlog time. However, then I end up with millisecond precision only, I'd prefer to have microsecond precision.

**Comment by gabime** [comment]
what are the compiler errors ?

**Comment by martink173** [comment]
Output is partly german, sorry for that.

1>spdlog-master\include\spdlog/details/pattern_formatter_impl.h(641): error C2039: "to_time_t": Ist kein Element von "std::chrono::steady_clock"
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(990): note: Siehe Deklaration von "std::chrono::steady_clock"
1>spdlog-master\include\spdlog/details/pattern_formatter_impl.h(641): error C3861: "to_time_t": Bezeichner wurde nicht gefunden.
1>spdlog-master\include\spdlog/details/pattern_formatter_impl.h(647): error C3536: "tm_time": Kann nicht verwendet werden, bevor es initialisiert wurde.
1>spdlog-master\include\spdlog/details/pattern_formatter_impl.h(647): error C2664: "void spdlog::details::flag_formatter::format(spdlog::details::log_msg &,const tm &)" : Konvertierung von Argument 2 von "int" in "const tm &" nicht möglich
1>spdlog-master\include\spdlog/details/pattern_formatter_impl.h(647): note: Ursache: Konvertierung von "int" in "const tm" nicht möglich
1>spdlog-master\include\spdlog/details/pattern_formatter_impl.h(647): note: Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig

**Comment by gabime** [comment]
Works perfectly fine with `high_resoultion_clock` .Seems that stead_clock does not support to time_t  (https://connect.microsoft.com/VisualStudio/feedback/details/1355735/breaking-change-in-vs-2015-chrono-steady-clock-time-point-not-longer-convertible-to-system-clock-time-point)
