### ISSUE TITLE
daily_logger_mt, one day in one file

### ISSUE THREAD

**Issue by uralbash** [gabime/spdlog#368]
How to make so that every time you restart the program the log was written to a single file rather than creating a new with HH-MM on the end.

**Comment by gabime** [comment]
You can provide own  "FileNameCalc" tempate parameter to the sink to modify the filename scheme. 
Please refer to the [default implementation](https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/file_sinks.h#L166) as an example.

**Comment by uralbash** [comment]
Thanks it works!
```cpp
typedef spdlog::sinks::daily_file_sink<std::mutex, spdlog::sinks::dateonly_daily_file_name_calculator> dateonly_daily_file_sink_mt;

m_logger = spdlog::create<dateonly_daily_file_sink_mt>("logger", "log", "txt", 0, 0);
```
