### ISSUE TITLE
Use environment variable to control log level?

### ISSUE THREAD

**Issue by jbreitbart** [gabime/spdlog#369]
I am wondering if it is possible to control the log level via an environment variables, e.g. debug logs are not shown be default but only when I set an environment variable. Or is this something that should be done by the application using spdlog.

Sorry, I could not find an answer to that question in the wiki and searching for environment in the GitHub repo didn't turn up anything useful.

**Comment by gabime** [comment]
It should be done by the application.
 It would need to detect that the env variable has changed and call ```spdlog::set_level(..)```

**Comment by jbreitbart** [comment]
Ok, thanks!

**Comment by little-big-h** [comment]
Should this be pointed out in the readme? Right now it says "Support for loading log levels from argv or from environment var.
" as a feature. I feel this raises the expectation of more support than "implement it yourself!".

**Comment by gabime** [comment]
There is such support. You are looking on an old thread before it was implemented.

**Comment by little-big-h** [comment]
Ah, fantastic! Maybe it would be worth pointing out how to use it in the readme or the wiki.

**Comment by little-big-h** [comment]
okay, found it -- I was grepping the readme for "environment", not "env"
