### ISSUE TITLE
Not sure how to create the kind of log that I need

### ISSUE THREAD

**Issue by ruipacheco** [gabime/spdlog#371]
I've read the Wiki but am a bit confused on how to achieve what I need.

I want to use spdlog in a library. I'd like it to be as fast as possible. This way I assume it needs to be async. I also want to have a logger per class that I create but have all the loggers write to the same sink. If I want an async logger does it also have to be multithreaded? How can I define a sink and make it accessible to all my loggers?

**Comment by gabime** [comment]
It can be achieved by creating the async loggers manually:
```c++
auto sink = std::make_shared<some_sink_mt>(..);
size_t qsize = 8192;
auto logger1 = new spdlog::async_logger("logger_name", sink, qsize)
auto logger2 = new spdlog::async_logger("logger2", sink, qsize);
```
This will create 2 async loggers. Each with his own dedicated worker thread.

**Comment by ruipacheco** [comment]
So I can store the sink in a static variable shared across the whole project and then create the loggers as I need them? Or should I create a sink every time I create a logger?

**Comment by gabime** [comment]
It must be the same sink object, but why store static variable? Just create a shared_ptr<sink> and pass it around. 

A different approach would be to create the first logger with the sink and then access its sink from anywhere using ```spdlog::get(..)```:
```c++

auto sink = std::make_shared<some_sink_mt>(..);
size_t qsize = 8192;
auto logger1 = std::make_shared<spdlog::async_logger>("logger1", sink, qsize)
spdlog::register_logger(logger1)
...
...
auto existing_sink = spdlog::get("logger1")->sinks[0];
auto logger2 = std::make_shared<spdlog::async_logger>("logger2", existing_sink , qsize)
```
To initialize the other loggers

**Comment by ruipacheco** [comment]
Thanks!

**Comment by ruipacheco** [comment]
One more question, is there a way to know how many loggers have been registered?

**Comment by gabime** [comment]
Unfortunately not in direct way. But maybe you could use apply_all()

```c++
int counter;
spdlog:apply_all([&](std::shared_ptr<spdlog::logger> l){counter ++ });
```

**Comment by ruipacheco** [comment]
Sorry, my question was not clear: I need to know if any loggers were registered so I can either get the sink of the first logger or register a logger.

**Comment by gabime** [comment]
I see, try using the apply_all for this. it calls your func for each registered logger

**Comment by ruipacheco** [comment]
There doesn't seem to be a way to get the sink from a logger. Looking at logger.h I can only see setters, not getters or public properties. 

Copying the line `auto existing_sink = spdlog::get("logger1")->sinks[0];` into my editor returns the error `no member name 'sinks' in 'spdlog::logger'.

I'm using v0.11.0 with Clang on the latest OSX.

**Comment by gabime** [comment]
try latest version from the main branch

**Comment by ruipacheco** [comment]
This worked, thanks!

Can I ask you to review the method I created to see if it matches the semantics of the library?

```
std::shared_ptr<spdlog::logger> logger(const string name, const string path) {
      std::shared_ptr<spdlog::logger> logger;
      if (name == "Connection") {
        const std::shared_ptr<spdlog::sinks::daily_file_sink_mt> daily_sink =
            std::make_shared<spdlog::sinks::daily_file_sink_mt>(path, "log", 23, 59);
        logger = std::make_shared<spdlog::async_logger>(name, daily_sink, 8192);
        spdlog::register_logger(logger);
      } else {
        logger = spdlog::get(name);
        if (logger == nullptr) {
          auto existing_sink = spdlog::get(name)->sinks()[0];
          logger = std::make_shared<spdlog::async_logger>(name, existing_sink, 8192);
        }
      }
      return logger;
    }
```

Basically I know that "Connection" will always be the first logger to be created so I use that name to signal the creation of the sink and the first logger. Then whenever I call the method with a different name I check if that logger exists and if not I create it with the sink of the first logger.

The purpose, as I explained, is to have one logger per class all of them writing to the same file/sink.

**Comment by gabime** [comment]
You forgot to register the non "Connection" logger.
I would always check of logger==null to be on the safe side 
(also, you need to mutex protect this function if multiple would use this function

Here is a fixed version:

```c++
std::shared_ptr<spdlog::logger> logger(const std::string &name, const std::string &base_path)
{
	auto logger = spdlog::get(name);

	if (logger != nullptr)  //already existing
		return logger;
	
	if (name == "Connection") {
		auto daily_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>(base_path, 23, 59);
		logger = std::make_shared<spdlog::async_logger>(name, daily_sink, 8192);
	}
	else {
		auto daily_sink = spdlog::get("Connection")->sinks()[0];
		logger = std::make_shared<spdlog::async_logger>(name, daily_sink, 8192);
	}
	
	spdlog::register_logger(logger);
	return logger;
}
```

**Comment by ruipacheco** [comment]
This is great, thanks!

**Comment by ruipacheco** [comment]
Right, new question: the solution you gave me is great but I'm still checking out master every time I checkout my project. Do you know if you'll have a release soon? If not I'd like to stick to a specific commit so I'm not constantly pulling new code.

I'm talking about a commit where `auto daily_sink = spdlog::get("Connection")->sinks()[0];` is stable.

**Comment by gabime** [comment]
I hope to release today version 0.12.0.
