### ISSUE TITLE
Wiki - typo

### ISSUE THREAD

**Issue by Sphinxila** [gabime/spdlog#372]
In the wiki at chapter 7 "Flush policy" you have a typo.
Set the flush_interval_ms in the set_async**h**_mode(..).
Not very important, if you find some time you can fix it.

Kind regards
Sphinx

**Comment by gabime** [comment]
Thanks. the wiki is public for everyone to edit and fix..

**Comment by Sphinxila** [comment]
Thanks for the tip, sorry for the usless issue.

**Comment by gabime** [comment]
@Sphinxila 👍
