### ISSUE TITLE
Does spdlog have a feature that can indent scoped log msg ?

### ISSUE THREAD

**Issue by Kiddinglife** [gabime/spdlog#374]
xxx
...xxx
......xxx
......xxx
...xxx
xxx

**Comment by gabime** [comment]
No, no such feature

**Comment by Kiddinglife** [comment]
can you tell me where I can start to extend and add such feature (which file whcih method ) ? 
thanks.

**Comment by ab-g** [comment]
+1 for this feature! It would make it easier to read when you are dealing with complex loops and calls. For example see [Python Log Indenter](https://python-log-indenter.readthedocs.io/en/latest/) for inspiration.

**Comment by mcourteaux** [comment]
@gabime Not even considered? I like this idea. I think having a formatter symbol (like, for example, `%I` or something) to put the indent spacing, would be a convenient way to integrate this.

**Comment by gabime** [comment]
Sure. Can be considered. PRs are always welcome

**Comment by MMitsuha** [comment]
> Sure. Can be considered. PRs are always welcome

It's really a great function, please give us...
