### ISSUE TITLE
Compilation fails with Clang in windows

### ISSUE THREAD

**Issue by LuisAyuso** [gabime/spdlog#382]
Hi there, 

When compiling the library in windows using clang-cl, wincolor_sink.h  presents errors.

the line:  (can be found twice)
```
 wincolor_stdout_sink():wincolor_sink(GetStdHandle(STD_OUTPUT_HANDLE))
```
should be:
```
 wincolor_stdout_sink():wincolor_sink<Mutex>(GetStdHandle(STD_OUTPUT_HANDLE))
```

MSVC is somehow relax on this matter.

**Comment by gabime** [comment]
Thanks for reporting. Could you please issue a pull to fix it?

**Comment by Timmmm** [comment]
Looks like this was [already fixed](https://github.com/gabime/spdlog/commit/b61be7320a998e16017d77346f095fb972183085).
