### ISSUE TITLE
compile failed on xcode 8.1

### ISSUE THREAD

**Issue by pkhope** [gabime/spdlog#384]
![image](https://cloud.githubusercontent.com/assets/11334906/23830646/a6200b80-074a-11e7-865d-b665c66f26f9.png)

**Comment by gabime** [comment]
It belongs to fmtlib. 
Please open in [fmt ](https://github.com/fmtlib/fmt )repository.

**Comment by mobileben** [comment]
As an FYI, I've hit this today. I opened up an issue in fmt.

https://github.com/fmtlib/fmt/issues/501

The OP didn't really specify the case to set this up, but I am getting it when passing arguments via va_list for a wrapper function. I posted an example of what I was doing there.

If I call similar code with explicit arguments, it works fine.

**Comment by mobileben** [comment]
BTW, I am using this workaround which gets past this compilation issue.

```
        template <typename... Args>
        static void info(const char* message, Args&&... args) {
#ifdef USE_SPDLOGGER
            consoleLogger->info(message, args...);
            fileLogger->info(message, args...);
#endif /* USE_SPDLOGGER */
        }
```
