### ISSUE TITLE
C++/CLI atomic not support

### ISSUE THREAD

**Issue by gorobie** [gabime/spdlog#386]
Hello.
I'd like to use the spdlog from C++/CLI too.
but the spdlog::logger class depend on C++11 atomic.
and C++/CLI does not support C++11 atomic.
Why don't you hide the atomic variable from C++/CLI ?
Is there a plan to improve the build error?

class logger
{
    ...
    spdlog::level_t _level; // atomic
    spdlog::level_t _flush_level; // atomic
    std::atomic<time_t> _last_err_time; //atomic
}

Best regards,
Satoshi Imai

**Comment by gabime** [comment]
> Why don't you hide the atomic variable from C++/CLI ?

How would you hide it?

**Comment by gorobie** [comment]
How about this approach?
Support c++11 concurrency header files in c++/cli
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/3814789-support-c-11-concurrency-header-files-in-c-cli

**Comment by gorobie** [comment]
I've tried to make the spdlog.dll above the approach for C++/CLI (VS2013).
but static logger has crashed. It seems  std::shared_ptr does not initialize in constructor of logger and sink. 
Why is it? Is that restriction of  C++11 std::shared_ptr ?  :-)

static std::shared_ptr<spdlog::logger> s_loggder = spdlog::logger::basic_logger_mt("root",  "foo.txt");
...
s.logger->info("hello");

**Comment by gorobie** [comment]
All problem has solved.  I've made the spdlog.dll. 
I appended the Logger Factory in spdlog.dll.
so It create an spdlog instance delayed.
Thanks for GOF. :-)

**Comment by gabime** [comment]
Ok .great

**Comment by DBJDBJ** [comment]
@gorobie you need to understand the scope of the delivery of this project. After that you need to ask yourself why is that the scope?

**Comment by sk-saravana** [comment]
I am facing similar issue in terms of integrating spdlog headers into C++/CLI project. I came across this forum on discussing the same topic. how did you resolve on using <atomic> contents into Managed C++.
