### ISSUE TITLE
‘ostream_sink_mt’ is not a member of ‘spdlog::sinks’

### ISSUE THREAD

**Issue by YenZi** [gabime/spdlog#387]
When I add your example for the `ostream_sink` to my code, I get the following error compilation error : 

```
myCode.cpp: In function ‘std::ostream& operator<<(std::ostream&, const DTGC<IN_W, IN_I, OUT_W, OUT_I, A0_W, A1_W, C_W, C_I, Q, O>&)’:
myCode.cpp:88:40: error: ‘ostream_sink_mt’ is not a member of ‘spdlog::sinks’
   auto ostream_sink = std::make_shared<spdlog::sinks::ostream_sink_mt>(oss);
                                        ^~~~~~
myCode.cpp:88:40: error: ‘ostream_sink_mt’ is not a member of ‘spdlog::sinks’
```

code snippet looks like this : 

```
  std::ostringstream oss;
  auto ostream_sink = std::make_shared<spdlog::sinks::ostream_sink_mt>(oss);
  auto logger = std::make_shared<spdlog::logger>("my_logger", ostream_sink);
 ```

Other sinks work just fine.

**Comment by stervo4ka** [comment]
Do you include [ostream_sink.h](https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/ostream_sink.h)?

**Comment by YenZi** [comment]
Hey @stervo4ka thanks for that hint. That fixed it ! I just didn't know I had to include that header explicitely as I did not have to include any header for the other sinks. `stdout_sink_mt`, `ansicolor_sink` and `rotating_file_sink_mt` were compiling without any #include
