### ISSUE TITLE
Cannot attach to Visual Studio Windows Debugger?

### ISSUE THREAD

**Issue by aaron3481** [gabime/spdlog#390]
Hi all, I know I am not suppose to post this to issue but I found there is no way to ask how to attach Visual Studio Windows Debugger to spdlog

Any help?

**Comment by gabime** [comment]
what did you try?

**Comment by aaron3481** [comment]
Nah, all examples are showing how to create basic console logger, file logger, and sink logger. There are not any example show how to create a Windows debugger.

**Comment by gabime** [comment]
tey using the [msvc_sink](https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/msvc_sink.h)

**Comment by aaron3481** [comment]
thanks
