### ISSUE TITLE
compile fail on codeblocks 'localtime_s' was not declared

### ISSUE THREAD

**Issue by jiftle** [gabime/spdlog#392]
os: windows 7 x64
ide: codeblocks

## compile fail on codeblocks 'localtime_s' was not declared
codeblocks compile fail,but vs2015 compile successed.
------------------------------------------
```
||=== Build: Debug in gccTest (compiler: GNU GCC Compiler) ===|
include\spdlog\details\os.h||In function 'tm spdlog::details::os::localtime(const time_t&)':|
include\spdlog\details\os.h|84|error: 'localtime_s' was not declared in this scope|
include\spdlog\details\os.h||In function 'tm spdlog::details::os::gmtime(const time_t&)':|
include\spdlog\details\os.h|104|error: 'gmtime_s' was not declared in this scope|
include\spdlog\details\os.h||In function 'void spdlog::details::os::prevent_child_fd(FILE*)':|
include\spdlog\details\os.h|148|error: '_fileno' was not declared in this scope|
include\spdlog\details\os.h||In function 'int spdlog::details::os::fopen_s(FILE**, const filename_t&, const filename_t&)':|
include\spdlog\details\os.h|166|error: '_fsopen' was not declared in this scope|
include\spdlog\details\os.h||In function 'size_t spdlog::details::os::filesize(FILE*)':|
include\spdlog\details\os.h|224|error: '_fileno' was not declared in this scope|
include\spdlog\details\os.h||In function 'int spdlog::details::os::utc_minutes_offset(const tm&)':|
include\spdlog\details\os.h|264|error: 'DYNAMIC_TIME_ZONE_INFORMATION' was not declared in this scope|
include\spdlog\details\os.h|265|error: 'tzinfo' was not declared in this scope|
include\spdlog\details\os.h|265|error: 'GetDynamicTimeZoneInformation' was not declared in this scope|
include\spdlog\details\os.h||In function 'std::string spdlog::details::os::errno_str(int)':|
include\spdlog\details\os.h|375|error: no match for 'operator==' (operand types are 'fmt::internal::Null<>' and 'int')|
include\spdlog\details\os.h|375|note: candidate is:|
include\spdlog\details\os.h|117|note: bool spdlog::details::os::operator==(const tm&, const tm&)|
include\spdlog\details\os.h|117|note:   no known conversion for argument 1 from 'fmt::internal::Null<>' to 'const tm&'|
||=== Build failed: 9 error(s), 0 warning(s) (0 minute(s), 2 second(s)) ===|
```

**Comment by gabime** [comment]
please provide more details (mingw/cygwin and gcc versions)

**Comment by jiftle** [comment]
Code::Blocks 16.01
mingw32-gcc.exe
gcc 4.9
```
=== TDM-GCC Compiler Suite for Windows ===
---           GCC 4.9 Series           ---
***   Standard MinGW 32-bit Edition    ***
```

**Comment by Taymindis** [comment]
Is this issue fixed ? I’m still having issue while windows building

**Comment by gabime** [comment]
Work on mingw 64. If anybody knows how to fix for mingw32, please post here.

**Comment by kyle-belle** [comment]
use "
std::tm tm*
time_t t;
time(&t);
tm = ::localtime(&t)
return *tm" instead

**Comment by kyle-belle** [comment]
> 
> 
> use "
> std::tm tm*
> time_t t;
> time(&t);
> tm = ::localtime(&t)
> return *tm" instead

btw similar approach must be used for gmtime

**Comment by gabime** [comment]
@wilhelmtell Problem is that localtime is not thread safe. Thats why localtime_s is used

**Comment by kyle-belle** [comment]
could it be made thread safe by placing it in a wrapper class/function and ensure it is only called by the class/function?

**Comment by kyle-belle** [comment]
as for the missing functions "_fileno" and "_fsopen" i have no idea why they are missing. i even tried in a seperate test cpp , with __STRICT_ANSI__ #undef  and it works there so dont understand what is going on here.

**Comment by kyle-belle** [comment]
> 
> 
> as for the missing functions "_fileno" and "_fsopen" i have no idea why they are missing. i even tried in a seperate test cpp , with __STRICT_ANSI__ #undef and it works there so dont understand what is going on here.

to fix this one i simply just replaced all calls to "\_fileno(f)" to "f->_file"

**Comment by gabime** [comment]
> could it be made thread safe by placing it in a wrapper class/function and ensure it is only called by the class/function?

Not really. Any other un related thread might call localtime and ruin everything. localtime is really bad  with threads.

**Comment by kyle-belle** [comment]
> 
> 
> > could it be made thread safe by placing it in a wrapper class/function and ensure it is only called by the class/function?
> 
> Not really. Any other un related thread might call localtime and ruin everything. localtime is really bad with threads.

oh ok. but this seems to be the only way to get this to work on mingw32 so i guess if someone wants to use this simply for logging with colors and whatnot i guess this workaround could be used.

**Comment by kyle-belle** [comment]
hey, me again, if i am understanding [https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-localtime32-localtime64?view=vs-2019#remarks](this) correctly it seems the windows version (which i think is the one used by mingw32) is kinda thread safe. it says only one tm struct is used per thread.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-localtime32-localtime64?view=vs-2019#remarks

**Comment by gabime** [comment]
> which i think is the one used by mingw32

If you can verify that, a pr will be welcome ( to use _localtime32 under mingw32)

**Comment by kyle-belle** [comment]
Ok I'll try to see if i can find any sources which can confirm this or just test it myself but as far as I'm concerned mingw use msvcrt.dll for function definitions which means it will use the windows version
