### ISSUE TITLE
Restart a file each time the logger iscreated

### ISSUE THREAD

**Issue by AAraKKe** [gabime/spdlog#393]
Hi,

I am using psdlog to implement the logging system of a data anlysis software and I would like to know if there is a way of overwriting a give logfile each time a logger over that file is crated instead of write at the end of the las t time it was used. I guess there should be an easy way but cannot find it. 

The idea is that this logfile is the log of a given run and the name is always the same because it is the main nformation that the user receive from the code. Nonetheless the file should be rewritten in each run. I have now everything running but it seems that the files get updated instead of rewritten.

Sorry if this was not the place to ask for this and thanks a lot in advance!

**Comment by prilr** [comment]
I beleive `basic_logger` with `truncate` set to `true` is what you want, as seen in `include/spdlog/spdlog.h`:

`std::shared_ptr<logger> basic_logger_mt(const std::string& logger_name, const filename_t& filename, bool truncate = false);`

I haven't found anything about it in the wiki, but the functionality is there.
An example:
    `auto logger = spdlog::basic_logger_mt("trunc_logger", "log.txt", true);`

**Comment by AAraKKe** [comment]
Thanks a lot! I will give it a try.
