### ISSUE TITLE
Async sinks instead of logger

### ISSUE THREAD

**Issue by wolf1792** [gabime/spdlog#395]
Hi,
it seems the Asynchronous mode has to be set on the whole logger; it could be possible make it part of each sink?
It would be really interesting, for example, to have a logger with two sinks: the first could log important message in synchronous way, the second could log everything in asynchronous mode.

Or, there is another way to achieve this?

**Comment by gabime** [comment]
Interesting idea indeed. However implementing it would change entirly the semantics and inner working of the lib. 
You can use combination async and sync loggers to achieve something similiar.
