### ISSUE TITLE
Consider revisiting streaming pointers

### ISSUE THREAD

**Issue by kingcheez** [gabime/spdlog#40]
In ```format.h```, there are a pair of constructors that are made private to avoid the streaming of [const] volatile char *:

```
    // The following two methods are private to disallow formatting of
    // arbitrary pointers. If you want to output a pointer cast it to
    // "void *" or "const void *". In particular, this forbids formatting
    // of "[const] volatile char *" which is printed as bool by iostreams.
    // Do not implement!
    template <typename T>
    MakeValue(const T *value);
    template <typename T>
    MakeValue(T *value);
```

In all cases besides these, the user just wants to see the hex value for the pointer anyway so I think the restriction created by these private constructors is too onerous and the goal could be achieved by making private constructors that overload on ```[const] volatile char *``` unless I'm missing something totally obvious.

**Comment by gabime** [comment]
These are cppformat's lib code and I don't want to change it without good reason

**Comment by kingcheez** [comment]
Oh I see, maybe I'll file something with them. Thanks

On January 27, 2015 6:34:38 PM EST, Gabi Melman <notifications@github.com> wrote:
>These are cppformat's lib code and I don't want to change it without
>good reason
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gabime/spdlog/issues/40#issuecomment-71751876

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
