### ISSUE TITLE
detials::registry::instance() can't guarantee to make the class registry singleton in mutithread enviroment

### ISSUE THREAD

**Issue by yandaren** [gabime/spdlog#401]
In the mutithread enviroment, the function detials::registry::instance() can't guarantee the class registry initialize only once, maybe we should call the function detials::registry::instance() explicitly to initilize the spdlog enviroment in the main thread before we use any other spdlog api?

**Comment by gabime** [comment]
Thread safety of initialization of static variables is guaranteed according to the c++11 standard.

**Comment by yandaren** [comment]
ok, thanks very much!
