### ISSUE TITLE
unicode output

### ISSUE THREAD

**Issue by DBJDBJ** [gabime/spdlog#410]
I would like to output strings like these:

const static std::wstring doubles = L"║═╚";
const static std::wstring singles = L"│─└";

Should I try or should I just leave?

**Comment by gabime** [comment]
Please dont leave. I think it is related to pull #379

**Comment by DBJDBJ** [comment]
After 2+ decades as an MSVC guinea pig I think I can safely recommend to anyone not to try and use C++ Unicode on Win32 console ...  But I will gladly accept the "solution", no worries :)

**Comment by DBJDBJ** [comment]
Scope of the problem is: C++ stdlib  + Win Console + UTF-8 or UTF16 . I hope [this is not](http://dbj.org/c-windows-unicode-console-output/) branded "self plug".

**Comment by gabime** [comment]
@DBJDBJ Do you mean that apart from the console problem, the pull #379 gives what you need?

**Comment by DBJDBJ** [comment]
Honestly I was not even looking. Sorry.

**Comment by kleuter** [comment]
@gabime 
I can confirm that though the pull #379 is not really clean, it gives a good solution to Unicode output on Windows.

**Comment by gabime** [comment]
@kleuter Thanks. What do you mean by "not really clean" ?

**Comment by kleuter** [comment]
@gabime 
I explained [here](https://github.com/gabime/spdlog/pull/379#issuecomment-300459254)
