### ISSUE TITLE
Uninitialized members in async_msg caught by ubsan.

### ISSUE THREAD

**Issue by nlyan** [gabime/spdlog#411]
Hi,

I've been running our app compiled with ubsan and getting the following warning upon program termination.

`third_party/spdlog/include/spdlog/details/async_log_helper.h:75:27: runtime error: load of value 2694985328, which is not a valid value for type 'level_enum'`

I've tracked this down to a partially initialized 'terminate' async_msg object when the async_logger is shutdown.

Here:
https://github.com/gabime/spdlog/blob/2b5c3615fde7494bd030de0e6eb4d8c4de2075a1/include/spdlog/details/async_log_helper.h#L219

The incomplete constructor is here:
https://github.com/gabime/spdlog/blob/2b5c3615fde7494bd030de0e6eb4d8c4de2075a1/include/spdlog/details/async_log_helper.h#L67

**Comment by alzix** [comment]
i believe it is fixed already in
```
Author:		gabime <gmelman1@gmail.com>
Date:		1 week ago (06-May-17 15:33:12)
Commit hash:	81965bc300eebb051ec22adf5d0df7f34dc6c67c
Children:	0aeaf9e28e
Parent(s):	8d5ecc1b58

Fixed some analyzer warnings
```

**Comment by gabime** [comment]
Indeed. I will close this issue.
