### ISSUE TITLE
Compile error in eclipse on ubuntu 16.04

### ISSUE THREAD

**Issue by Kiddinglife** [gabime/spdlog#416]
```c++
network_logger()->error("GecoNetEndpoint::FindDefaultInterface: if_nameindex returned NULL ({})\n",strerror(errno));
```
this line of code works fine in windows but it reports compile error in eclipse editor on ubuntu 16.04 system. Error looks like this:
>invalidate argments
>candidates are:
>void error(const char*, const #0(...)&...);
>void error(const #0 &);

Tx.

**Comment by gabime** [comment]
which spdlog version? I think it might have been fixed in latest commits
