### ISSUE TITLE
Can you register a deb file with the debian package manager?

### ISSUE THREAD

**Issue by kssim** [gabime/spdlog#417]
Can you register a deb file with the debian package manager?
We are working on a debian8(jessie) environment, and we want to use this spdlog.
Of course, we can get the source code, but we want to use the package manager.
It's registered in ubuntu, so it's not hard to upload it to debian.
It would be nice to consider suppporting the debian environment as well.
Thank you in advance.

**Comment by gabime** [comment]
Hi, spdlog whould work fine under debian.  You are welcome to register it.

**Comment by kssim** [comment]
No, that's not the version what I want.
The version on the link is a testing version of debian.
What I want is a [stable version](https://packages.debian.org/stable/) of the debian package manager.
The test version code name on the link is "strech", and the stable version code name is "jessie".
I'd like you to review it for use in the stable version.

Thank you for your attention. :)

**Comment by gabime** [comment]
It has too old version of spdlog. You need 0.13.0

**Comment by kssim** [comment]
I did not mean the version of spdlog.
I mean the version of debian package manager that spdlog is currently uploaded to.
Debian has serveral versions(code names), such as "old stable", "stable", "testing", "unstable" and "experimental".
Currently, spdlog has been uploaded to testing(stretch) and unstable(sid) versions of debian package manger.
Debian users mainly use the stable version, but can not download spdlog through the package manager.
So what I'm asking you to do is upload the spdlog to the stable version of debian package manager.
[This](https://wiki.debian.org/DebianReleases#Current_Releases.2FRepositories) is a list of Debian's release repository.

**Comment by gabime** [comment]
Like I said, you are welcome to upload it to the stable version.

**Comment by kssim** [comment]
Oh, sorry!
I misunderstood.
I'll upload it to the stable version and let you know.
Thanks.

**Comment by kssim** [comment]
I tried to post a spdlog to the debian stable version, and found [this](https://www.debian.org/doc/manuals/developers-reference/ch05.en.html#upload-stable) document.
In summary, I can upload the spdlog, if I meet one of the following conditions:

- a truly critical functionality problem
- the package becomes uninstallable
- a released architecture lacks the package

So I'm afraid I'll not be able to upload it to the stable version.
I'll change this issue to terminate.
Thank you for your help.
