### ISSUE TITLE
Issue with clock_gettime

### ISSUE THREAD

**Issue by mfrey** [gabime/spdlog#42]
Compiling the current head of spdlog in my project throws the following error
```bash
out/g++-debug/testbed/TestbedARAClient.o: In function `spdlog::details::os::now()':
/home/mfrey/testbed/ara-sim/spdlog/include/spdlog/sinks/../details/./os.h:51: 
undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
Makefile:251: recipe for target 'out/g++-debug/testbed/TestbedDaemon' failed
make: *** [out/g++-debug/testbed/TestbedDaemon] Error 1
```
Apparently, this can be solved adding ``-lrt`` to the linker flags in the makefile. If I compile the code on my development machine (without adding the ``-lrt`` flag and using clang++) the code compiles fine nevertheless. I'm not sure if this is an issue with the fairly old Debian on the server (I'm working on)? However, I thought it might be helpful for somebody who runs into the same issue.

**Comment by gabime** [comment]
Latest commit should solve it (spdlog won't use CLOCK_REALTIME_COARSE be default)
Please try latest commit and feedback if ok

**Comment by mfrey** [comment]
It compiles fine on the server! Thanks!
