### ISSUE TITLE
per sink format pattern

### ISSUE THREAD

**Issue by alzix** [gabime/spdlog#421]
I suggest adding an option to set per sink format pattern.
Some sinks (i.e. `android_logger` and `syslog_sink`) apply their own formatting to every print by adding timestamps, severity, thread and process ids.
In case single logger connected to more than one sink, by using `dist_sink_st` it is not sufficient to set formatting pattern at a logger level, since _"native sink formatting"_ may vary.

**Comment by alzix** [comment]
I was looking in to implementing this issue by myself and come to conclusion that "native sink formatting" in case is provided is sufficient. After examining formatter flags I do not believe such a feature will be useful.
But there is still a problem with `android_sink` though. This problem can be solved the same way as you have treated `syslog_sink` - just use `msg.raw` instead of `msg.formatted` in `android_sink::log`.

What do you think?

**Comment by gabime** [comment]
Maybe, but it should be backward compatible  with current android implementation (maybe add new flag to the ctor whether to use raw or formatted or not).

**Comment by alzix** [comment]
merged

**Comment by wang-bin** [comment]
android own formating is not a solution. I want to print thread info in my log, but android log just print the thread invoking `__android_log_write()`, i.e. it's always `_worker_thread` for async logger. per sink formatting is the only solution

**Comment by alzix** [comment]
I've missed this one

**Comment by gabime** [comment]
@alzix any chance you fix it?

**Comment by alzix** [comment]
nope... but i think i can

**Comment by gabime** [comment]
please do :)

**Comment by c0nk** [comment]
I have a single logger with two sinks that writes to stderr and a log rotated file. I would to use a different format for each sink. For example, I don't want the timestamp for stderr, but I do want the timestamp in the log file. Please add per-sink format patterns.

**Comment by hoerenj** [comment]
Thank you for this wonderfully designed (and fast!) logging library!

I believe this feature can be implemented with the library as it is. Decorator pattern ;-) One can implement a custom sink that decorates any other sink, so it "sits" between the managing logger and the backend sink. It receives messages from the managing logger, applies the formatting, and forwards the formatted message to the backend sink.

**Comment by gabime** [comment]
@hoerenj Interesting idea. Might work. The cost would be that the default formatter will be called anyway even if its ouput is not needed...(and of course another virtual sink_it call).

**Comment by hoerenj** [comment]
That's right. It works already. The beauty of the decorator approach is that it can be combined with any sink. If you think it's worth adding it to the library, I would contribute the code (github beginner, though... :-))

**Comment by gabime** [comment]
What I like in this approach is that no new API is needed to support this. 
So maybe (at least until a better solution exists) it could be good solution. Please open a PR. I think it should just contain a new sink header file( which would need be included if needed by user code).

**Comment by gabime** [comment]
@alzix @hoerenj  spdlog 1.x supports format per sink.
