### ISSUE TITLE
Get non-existent logger

### ISSUE THREAD

**Issue by henryiii** [gabime/spdlog#428]
Currently, if you request a non-existent logger, you get a runtime segfault. (Xcode, Mac tested). In my case, I want a program to work even if the "initialization" portion is not available (for example, when using python bindings), so this should at least throw an error, and a reasonable default might be even better. Or log a warning...

**Comment by gabime** [comment]
When requesting non exiting logger the library should return nullptr (wrapped inside shared_ptr). The crash is probably due to trying to acess this nullptr.

**Comment by henryiii** [comment]
Okay, that's better! I'd just recommend mentioning the behavior in the docs somewhere (or somewhere more obvious, I didn't see it). Thanks!

**Comment by henryiii** [comment]
I like your picture, by the way. 👍

**Comment by gabime** [comment]
@henryiii Thanks. This is a picture my cat.
