### ISSUE TITLE
debug build sizes are quite large

### ISSUE THREAD

**Issue by jcelerier** [gabime/spdlog#429]
Just compiling the following file:  
```C++
#include <spdlog/spdlog.h>
```

g++ -g -c test.cpp

yields a 1.4 megabytes binary (1.6 MB with gcc).

Adding this: 

```C++
void fun()
{
auto logger = spdlog::stderr_logger_mt("foo");
}
```

goes up to 1.9 megabytes with gcc and 2.3 with clang.

would you have any idea on how to reduce binary size bloat a bit ?

**Comment by gabime** [comment]
-g by definition inserts debug info so isn't this expected?
