### ISSUE TITLE
async and multisink problems

### ISSUE THREAD

**Issue by parihaaraka** [gabime/spdlog#432]
Please, point errors too fix the problems in comments:
```
        spdlog::set_async_mode(1024*1024, spdlog::async_overflow_policy::block_retry, nullptr, std::chrono::seconds(2));
        // (_1_) chrono::seconds(2) does not affect the loggers (?!)!

        //auto dist_sink = make_shared<spdlog::sinks::dist_sink_mt>();
        //dist_sink->add_sink(s1 /* rotating sink */);
        //dist_sink->add_sink(s2 /*notifier*/); 
        // (_2_) unable to access notifier sink from outermost code (or not?), so we do:
        std::vector<spdlog::sink_ptr> sinks
        {
            // (_3_) buffer size again? what is the correct way with set_async_mode()?
            make_shared<spdlog::sinks::rotating_file_sink_mt>("/var/log/test/app.log", 1024*1024, 5),
            make_shared<notifier_sink>()
        };
        sys_logger = make_shared<spdlog::logger>("sys", sinks.begin(), sinks.end());
        sys_logger->set_level(spdlog::level::debug);
        spdlog::register_logger(sys_logger);    // (_4_) it does not register itself without this line (why?)!
```
thanks

**Comment by gabime** [comment]
Async flush is working afaik. Please provide more info

**Comment by parihaaraka** [comment]
The 'sys' logger above does not flush every 2 seconds. I have to do it manually with my own timer.

**Comment by gabime** [comment]
This is because it are creating a synchronous logger!
You should do:
```c++
sys_logger = make_shared<spdlog::async_logger>("sys", ..)
```
or even better, use spdlog's factory methods

**Comment by parihaaraka** [comment]
Then why this synchronous logger does not write into the file untill i do flush()? What is the correct way to make multisink logger (i need to access one of the sinks (custom one) afterwards via the logger)?

**Comment by gabime** [comment]
Please refer to the [documantation ](https://github.com/gabime/spdlog/wiki/7.-Flush-policy) about flush policy in spdlog.

**Comment by parihaaraka** [comment]
Sorry, my bad. I forgot that synchronous logger is buffered too (i don't use it). Moreover i must be blind not to find all the answers in wiki :( I beg your pardon.
