### ISSUE TITLE
Question: Release Schedule

### ISSUE THREAD

**Issue by bahostetterlewis** [gabime/spdlog#439]
I checked the wiki and didn't find a release schedule.  Is there any information on when the next tagged release will be issued? I am using spdlog for a project at work but we have a policy that requires us to use official releases in production and would like to use the newly included fixes.

**Comment by gabime** [comment]
Next release is planned for next few weeks. No exact schedule exists though..

**Comment by bahostetterlewis** [comment]
ok thanks
