### ISSUE TITLE
Support the ability to filter out sensitive data

### ISSUE THREAD

**Issue by kingcheez** [gabime/spdlog#44]
I have an application that logs network calls so it is at the very lowest level. Within this trace, a password may appear, usually in some pattern like ```<password>whatever</password>```. I couldn't think of a sanctioned way to turn this into ```<password>[redacted]</password>``` so it doesn't mean there isn't one, but if there isn't, I'd like there to be!

Other logging frameworks have this. I wonder if a compiled regex would be sufficient.

**Comment by gabime** [comment]
Could you please provide an example API to support such feature ? I am not sure I understood what you meant..

**Comment by kingcheez** [comment]
So in the network traces that are logged, you might see something like this:

```
<login><username>whatever</username><password>secret</password></login>
```

At the code level, this might be logged as:

```
logger->trace(network_message)
```

So by the time it is logged, even the idea that network_message contains sensitive information is lost. To solve this problem, an API like the following could help:

```
sink->install_filter(regex_filter("<password>(.+)</password>","[redacted]"))
```
Which would replace all things matched in all lines logged that matches that pattern with [redacted].

**Comment by gabime** [comment]
Out of scope

**Comment by cmaruan** [comment]
I know this thread is old, but the code has much evolved since 2015.
So, my question would be: can this behavior be achieved? Has there any facility been added that would allow replacing/masking sensitive data like passwords, card numbers, etc based off of a regex?

**Comment by gabime** [comment]
There is no such facility, but I guess a simple custom sink can be developed for this.
