### ISSUE TITLE
Microseconds are not rounded

### ISSUE THREAD

**Issue by tamboril** [gabime/spdlog#461]
Hi.  I'm not sure whether it was the intent, but I noticed when using microsecond precision
in the format string, it does not round.  In this test, I'm actually hooking the clock_gettime() function to control the logged time; so in this case, it returned the same number when I called it and when spdlog called it.

```
[11:07:47.970473] (I) [111810] foobar 2016-01-31T17:07:47.970473845Z
```

Should it round, or just be documented as truncating?

**Comment by gabime** [comment]
Please post the code to reproduce.
I am not sure if it should round. Which behavior would be better for the typical use cases? 

Gabi

**Comment by tamboril** [comment]
If you temporarily change `spdlog::details::os::now()` to return a constant, such as `return time_point(duration(1497979724202938914))`, then set a pattern such as `::spdlog::set_pattern("[%H:%M:%S.%f] (%L) [%t] %v");` and then just log anything, you will see the issue.  That particular constant will yield: `[12:28:44.202938] (E) [124127] XXX`, but, with rounding, the microseconds should end in 939, not 938.

**Comment by gabime** [comment]
seems std::chrono truncates as the standard mandates. The question is if rounding is better.

**Comment by tamboril** [comment]
OK.  Now I see that it effectively does a `chrono::duration_cast<>`,  and that's not the same as a `chrono::round<>`.

I think it should stand as-is, after all.

Thanks for looking at it.
