### ISSUE TITLE
Readd ansicolor::set_color

### ISSUE THREAD

**Issue by cyres** [gabime/spdlog#464]
Hi,

I'd like to know if it's possible to readd set_color for the ansicolor-sink. It was removed in 98addad8887432561462a23e14595a492b75e946 and I don't see why.

For convenience I can do a pull request if you like to.

Greetings

**Comment by gabime** [comment]
Sure, go ahead, but please make sure it is thread safe by locking the  protected ```_mutex``` member.

**Comment by gabime** [comment]
Implemented by @cyres in pull #465 and merged in 9a04e372753882f909ecf5611b72484ac547f23e
