### ISSUE TITLE
how to write log file immediately

### ISSUE THREAD

**Issue by kangseung** [gabime/spdlog#466]
i use basiclog only can create log file. when main() function exit can write logs in log file.but  if program crashed before correct exit i can't get any logs.only a empty log file.T^T help me thankyou

**Comment by iamantony** [comment]
Use `logger->flush_on(spdlog::level);`

**Comment by kangseung** [comment]
thankyou.  but it dose't work.

`my_logger = spdlog::basic_logger_mt("Datarecorder", "logs/datarecorder.txt");
		my_logger->info("info");
		my_logger->error("error");
		my_logger->critical("critical");
		my_logger->trace("trace");
		my_logger->debug("debug");
		my_logger->warn("warn");
		my_logger->flush_on(spdlog::level::trace);`

this is my test code

**Comment by iamantony** [comment]
```
my_logger = spdlog::basic_logger_mt("Datarecorder", "logs/datarecorder.txt");
my_logger->flush_on(spdlog::level::trace);
my_logger->error("Holy Moly! This should work!");
```

**Comment by kangseung** [comment]
it works  thankyou . hahahahaha （ tears of joy）
