### ISSUE TITLE
thread-safe console output?

### ISSUE THREAD

**Issue by p0fi** [gabime/spdlog#47]
is spdlog meant to be thread-safe? 
I have 3 loggers in multiple threads and the output in the console looks a little messed up like this:

```
[11:52:57] [logger1] [info] some log message
[[1111::5522::5577]]  [[lwneoggseoa1k]e 2r[]n o[tiincfeo]]  ENnoO cdeaatna  Lteoa rsneMnodd
e ON
```

it should more look like

```
[11:52:58] [logger1] [info] some log message
[11:52:58] [logger2] [info] another log message
[11:52:58] [logger3] [notice] the last log message
```

**Comment by gabime** [comment]
Please provide the code that you create the loggers, but probably the problem is that you have 3 different loggers with 3 different sinks pointing to same console. You should either have single logger shared by the threads (using spdlog::get("logger_name"), recommended) or create 3 loggers with a shared sink

**Comment by p0fi** [comment]
I'm using the same code for each logger in some different classes/threads. 
I took them out of the example code.
```
auto logger1 = spdlog::stdout_logger_mt("logger1");
```
```
auto logger2 = spdlog::stdout_logger_mt("logger2");
```
```
auto logger3 = spdlog::stdout_logger_mt("logger3");
```
Sharing a single logger would mean that the name of the logger can't be different?
I use 3 loggers to get a nicer output in the console to see from where this specific log output comes from.
How do i create a shared sink?

**Comment by gabime** [comment]
```c++
 auto stdout_sink = std::make_shared<spdlog::sinks::stdout_sink_mt>();
 auto logger1 = spdlog::create("logger1", { stdout_sink });
auto logger2 = spdlog::create("logger2", { stdout_sink });
auto logger3 = spdlog::create("logger3", { stdout_sink });
```

**Comment by p0fi** [comment]
this seems to work fine!
thanks!
