### ISSUE TITLE
How to use conditional logging?

### ISSUE THREAD

**Issue by ruipacheco** [gabime/spdlog#472]
I've downloaded 0.13.0 and can't find the methods for conditional logging, despite what the homepage of the project says. I've opened the file `logger.h` but there doesn't seem to be anything there. Was the homepage updated prematurely?

**Comment by gabime** [comment]
Right. Please pull this from latest commit. The doc is indeed little bit too early

**Comment by gabime** [comment]
Not sure but I hope in a  2 or 3 weeks

**Comment by ruipacheco** [comment]
I'll wait and close this issue when I upgrade. 

Thanks!

**Comment by asit-dhal** [comment]
There is a test case for conditional logging here... https://github.com/gabime/spdlog/blob/master/tests/cond_logging.cpp

You can refer it. It's very straightforward.
