### ISSUE TITLE
Formatting in trace and debug C macros

### ISSUE THREAD

**Issue by elelel** [gabime/spdlog#476]
The trace/debug output format is hard-coded into the macro. It would be nice if that formatting would be customizable, especially when integrating the trace output to IDEs. For example, the trace macro is used to inject "line #" substring into the output, while Emacs under default configuration expects "source.cpp:line" format. To make the trace output clickable, one either has to rewrite Emacs's compile parser, or to undef the SPDLOG_TRACE macro if it is defined and redefine it from scratch. Perhaps it is possible to make this macro dependant on a formatting macro setting.
This is related to #340

**Comment by werman** [comment]
I would also like to see this feature implemented. I have integrated spdlog in a big project and it was utmost improtant to have logs clikable in visual studio output, visual studio has "file.cpp(123) : message" format to navigate to corresponding line. I have solved it by having custom ::log method but it will be nice to have a good solution available in the library.

**Comment by gabime** [comment]
>  I have solved it by having custom ::log method

Could you please share your solution here (at the least the relevant part), might be good start

**Comment by werman** [comment]
Unfortunately it's not a good solution, just was ok for us since we didn't need flexible one. From memory (I'm not near that code atm):
```
inline void spdlog::logger::log(level::level_enum lvl, const fmt::StringRef& msg_prefix, const char *msg)
{
    ...
        details::log_msg log_msg(&_name, lvl);
        log_msg.raw << msg;
        log_msg.formatted << msg_prefix;

        _sink_it(log_msg);
    ...
}
```
From the first look I like #561 idea (didn't look at its optimality) as a general solution.
Also thanks for this good library!
