### ISSUE TITLE
create console logger for android

### ISSUE THREAD

**Issue by fcoulombe** [gabime/spdlog#48]

**Comment by fcoulombe** [comment]
I think I have an implementation if you're interested in checking it out

**Comment by gabime** [comment]
Sure. Even better would be pull

**Comment by gabime** [comment]
@fcoulombe Any news on this ?

**Comment by fcoulombe** [comment]
I haven't forgotten, still busy with other things sorry.

**Comment by gabime** [comment]
Ok, I will leave this open in the meanwhile

**Comment by ruslo** [comment]
See https://github.com/gabime/spdlog/pull/130

**Comment by gabime** [comment]
Implemented in #130
