### ISSUE TITLE
Wiki page conflicts, questions, and concerns.

### ISSUE THREAD

**Issue by iaz3** [gabime/spdlog#480]
## Wiki page Asynchronous Logging vs Error Handling informational conflict

The page for Asynchronous Logging indicates that Logging will throw an error the next time it is called, if beforehand an error had occurred in the worker thread.

The Error Handling page indicates that logging will *never* throw an error as of commit 39cdd08

I'm unsure which page, if any, is in error. Is Asynchronous logging a special case, or is the page outdated? Does it have a replacement for that use case that should be listed instead?

## Wiki Page Quickstart

The example given for `Create a logger with multiple sinks` is partially invalid, in particular the line `sinks.push_back(std::make_shared<spdlog::sinks::daily_file_sink_st>("logfile", "txt", 23, 59));` has an invalid argument, `"txt"`, that presumably used to set the file extension for the log, but is no longer there.
Is there an alternative for that use case?

**Comment by gabime** [comment]
> I'm unsure which page, if any, is in error. Is Asynchronous logging a special case, or is the page outdated? 

The wiki is outdated. spdlog should never throw (except for when constructing new logger fails)

> has an invalid argument, "txt", that presumably used to set the file extension for the log..

The wiki is outdated here too.
 Fixes the wiki are most welcome

**Comment by iaz3** [comment]
I would've fix it myself, but i didnt know if alternatives to the use cases existed, which is why I asked.

For now i've fixed the outdated information, but it'd be nice to be able to list alternatives
