### ISSUE TITLE
crash signal handling feature ported from g3log 

### ISSUE THREAD

**Issue by rxdu** [gabime/spdlog#486]
I recently ported the signal handling feature from g3log (**written by KjellKod**) to spdlog, since this feature is very useful and convenient to me. Currently, only the *nix support is ported. Details could be found here: 

https://github.com/rxdu/spdlog/blob/signal/include/spdlog/details/signal_handler.h

I read previous discussions on this topic. As gabime mentioned you could always handle signals in your application and ask the logger to flush before exiting. And it's also debatable whether signal handling is the responsibility of the logger. Anyway, I like it to be included for my personal projects and I write a post here in case anyone else might be interested. 

Comments/suggestions are welcomed.

**Comment by gabime** [comment]
Interesting. So to use it one need to include this header and call ```installCrashHandler``` ?

**Comment by rxdu** [comment]
For my convenience, I just made this install function called in the constructor of logger. Then spdlog could be used without any difference.

https://github.com/rxdu/spdlog/blob/signal/include/spdlog/details/logger_impl.h#L28

That's the only place I touched the code of the original spdlog. So it shouldn't be a problem for me to merge future updates back into my fork. Maybe what you just mentioned is a better way to do this, if someone doesn't want to touch the code at all.

**Comment by gabime** [comment]
What would happen if you have several loggers, all calling 'initCrashHandler' at the same time?

**Comment by rxdu** [comment]
That's a good point and I missed it. I will fix this soon.

**Comment by rxdu** [comment]
I think this should fix the issue:
https://github.com/rxdu/spdlog/blob/signal/include/spdlog/details/logger_impl.h#L29

When I run "catch_tests", I got:
[*** LOG ERROR ***] [logger] [argument index out of range] [2017-07-31 09:38:28]
===============================================================================
All tests passed (76 assertions in 27 test cases)

Is this normal, the "LOG ERROR" line? It says all tests passed though.

**Comment by gabime** [comment]
yes thats fine. it tests exception handling

**Comment by rxdu** [comment]
Just a note: the signal handler only logs stack information and flushes loggers registered in the log registry.

**Comment by nj2901** [comment]
@rxdu can you give a sample snippet of how to use your code without touching any existing spdlog files other than including signal_handler.h in spdlog/details path
Thanks

**Comment by rxdu** [comment]
> @rxdu can you give a sample snippet of how to use your code without touching any existing spdlog files other than including signal_handler.h in spdlog/details path
> Thanks

Take a look at this:
https://github.com/rxdu/spdlog/blob/v1.2.1-signal/tests/signal/test_signal.cpp
