### ISSUE TITLE
warning for missing enumeration value in switch-case

### ISSUE THREAD

**Issue by asit-dhal** [gabime/spdlog#488]
In Ubuntu GNU 4.8.4

/home/asit/spdlog/tests/cond_logging.cpp:14:5: warning: enumeration value ‘off’ not handled in switch [-Wswitch]
     switch (logger_level)
     ^
/home/asit/spdlog/tests/cond_logging.cpp: In instantiation of ‘std::string conditional_log_varags(spdlog::level::level_enum, bool, const char*, const Arg1&, const Args& ...) [with Arg1 = int; Args = {}; std::string = std::basic_string<char>]’:
/home/asit/spdlog/tests/cond_logging.cpp:132:9:   required from here
/home/asit/spdlog/tests/cond_logging.cpp:49:5: warning: enumeration value ‘off’ not handled in switch [-Wswitch]
     switch (logger_level)

**Comment by gabime** [comment]
Fixed in pull #490 . 
Thanks @asit-dhal
