### ISSUE TITLE
support for STL containers?

### ISSUE THREAD

**Issue by p0fi** [gabime/spdlog#49]
is there, or will there be support for STL containers like vectors?

**Comment by gabime** [comment]
You mean to log containers? I dont think so.. Seems out of the scope for library..

**Comment by p0fi** [comment]
i meant to output the content of a vector<uint8_t> into to console for example

**Comment by gabime** [comment]
Out of the scope. I want to keep the library lean

**Comment by honghaoli** [comment]
Sorry to bring this up again. Just want to understand how hard it is to implement this, given the original [{fmt} library](https://github.com/fmtlib/fmt) already supports STL containers. If it's not too complicated, I can fork and implement for my own use.

**Comment by adlternative** [comment]
I think this feature will be useful...
