### ISSUE TITLE
spdlog with mintty

### ISSUE THREAD

**Issue by hxf0223** [gabime/spdlog#492]
I debug my console app with spdlog, it's very handy to use.
followed the sample, I use spdlog like this:

`auto console = spd::stdout_color_mt("console");`
`console->info("{0}: {1}", __FUNCTION__, dumpss(ss));`

it works on windows default console, but when i change to use mintty of git, there's no output.
how to let spd logged to windows console and mintty both?

**Comment by gabime** [comment]
try to use/add  ansicolor sink to your logger :

```c++
auto sink = std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>();
auto logger = make_shared<spdlog::logger>("color_logger", sink);
```

**Comment by hxf0223** [comment]
@gabime THX for sample code.

**Comment by OldWolf2** [comment]
Having the same problem as of commit 32177aa. However the suggested fix on this ticket gives error:

    main.cc:110:54: error: 'ansicolor_stdout_sink_mt' is not a member of 'spdlog::sinks'
      auto windows_sink = std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>();
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~
    main.cc:110:54: note: suggested alternative: 'wincolor_stdout_sink_mt'

Using `wincolor_stdout_sink_mt` compiles successfully but still produces no output on the Cygwin terminal. (Output does appear correctly if I launch the executable from command prompt). 

Using mingw-w64/x86_64-7.2.0-win32-seh-rt_v5-rev1 as standalone install (not the cygwin flavour of mingw-w64).

**Comment by OldWolf2** [comment]
I ahd to also do `#include "spdlog/sinks/ansicolor_sink.h"` to compile. This causes the output to display in the Cygwin terminal but with no colours still.
