### ISSUE TITLE
how to support variadic parameters in C lib

### ISSUE THREAD

**Issue by zhishupp** [gabime/spdlog#493]
I wrapped spdlog into a C lib, but it's hard to support variadic parameters.

because in spdlog there isn't C type variadic parameters interfaces, only template type which as:

`template <typename... Args> void log(level::level_enum lvl, const char* fmt, const Args&... args);`

finally, i support variadic parameters in this way:

`
void spdlog_log_msg_var_full(const char* logger_name, int log_level, const char* func, char* file, size_t line, const char* fmt, ...)
{
    char msgbuf[MSG_BUF_MAX_LEN];
    va_list args;

    va_start(args, fmt);
    vsnprintf(msgbuf, sizeof(msgbuf), fmt, args);
    va_end(args);

    std::string strmsg = msgbuf + std::string(" [{0}|{1}:{2}]");
    spdlog::get(logger_name)->log(static_cast<spdlog::level::level_enum>(log_level), strmsg.c_str(), func, extract_name(file), line);
}

`

it's so ugly, and message length is limited

so, is thers any chance to support C type variadic parameters ? 
thanks !

**Comment by Mmisiek** [comment]
I have the same issue and solution with buffer is ugly and non-efficient, va_list should be supported. Maybe by another set of functions like printf does ?
