### ISSUE TITLE
after log file deleted, it won't create again~

### ISSUE THREAD

**Issue by zhishupp** [gabime/spdlog#495]
I used rotating_logger_mt create a logger, but after i deleted the log file, it won't create again, even i call API flush, so the log file is only created when logger created ?

**Comment by iamantony** [comment]
rotating_file_sink opens a log file in constructor (see [code](https://github.com/gabime/spdlog/blob/5ed426980b366400d4854d28eac27d153bd7fbd4/include/spdlog/sinks/file_sinks.h#L76)) via file_helper. file_helper will save file descriptor of log file ([here](https://github.com/gabime/spdlog/blob/5ed426980b366400d4854d28eac27d153bd7fbd4/include/spdlog/details/file_helper.h#L54)) and use it for write operations.

If you manually delete log file during execution of your program, file descriptor in file_helper will become invalid. rotating_file_sink do not have instruments that can detect such situation, so it will still use old (now invalid) file descriptor and all write operations will send data to nowhere.

**Comment by zhishupp** [comment]
this issue can be closed now, thanks!
