### ISSUE TITLE
how should I log the message include "{ something... }"

### ISSUE THREAD

**Issue by zhishupp** [gabime/spdlog#496]
I notice that the messgae like this, can not log successfully: 
receive msg: {"command":10010,"parameter":{"logger":""}}

I have to use json as my message carrier, so there are a lot of “{ }" in the message.
how should I log the message include "{ something... }"   ?

thanks！

**Comment by gabime** [comment]
Use double braces {{ or }}

**Comment by zhishupp** [comment]
It's a little hard to do this convert before logging, it will lose some performance, and in C it more difficult to do this (string length limitation or memory alloc/free), so, it there any better way to do this? many thanks.

**Comment by zhishupp** [comment]
this issue can be closed now, thanks!
