### ISSUE TITLE
rotating_file_sink and multiple processes

### ISSUE THREAD

**Issue by iamantony** [gabime/spdlog#497]
First of all, thanks for spdlog @gabime !

rotating_file_sink_mt works well in case of multi-threaded process - all threads could share one file sink and write to the same log file (safely and quick).

But if you have several processes that want to use one rotating log file, rotating_file_sink will not help you there. All processes will have different file descriptors and none of the processes will know real size of the log file. Things will get worse when one of the processes decide to perform rotation.

We encountered such problem in our system and finally found out a solution (on linux). It is much slower than rotating_file_sink because it tracks real size of a file, but it can grant atomic writes for processes so messages from different processes will not intersect.

If the solution to such a problem is suited to the concept of spdlog, we will be happy to share our code.

**Comment by gabime** [comment]
Hi

Thanks for the feedabck 👍 

Sure, Please share your approach in supporting this.

**Comment by iamantony** [comment]
Ok, I'll make a PR
