### ISSUE TITLE
SPDLOG_WCHAR_TO_UTF8_SUPPORT compile error in clang

### ISSUE THREAD

**Issue by hestad** [gabime/spdlog#498]
Spec: Clang 3.8 and ubuntu 16.04
Error: spdlog/details/logger_impl.h:333:10: error: no member named 'wstring_convert' in namespace 'std'
    std::wstring_convert<std::codecvt_utf8<wchar_t> > conv;

sample.cpp:
```
#define SPDLOG_WCHAR_TO_UTF8_SUPPORT
#include "spdlog/spdlog.h"
int main(int argc, char *argv[]) {}
```

`#include <locale>` fixes the first error.

After this we get the compile error: expression contains unexpanded parameter pack 'args' `log(lvl, fmt, args);`
Second error:
File: logger_impl.h line 402: `log(lvl, fmt, args);` becomes `log(lvl, fmt, args...);`

**Comment by gabime** [comment]
Thanks @hestad for the fix
