### ISSUE TITLE
Usage of ansicolor_sink

### ISSUE THREAD

**Issue by ohmyarch** [gabime/spdlog#499]
The constructor parameters of class ansicolor_sink has changed, could you please write a demo to show how to use it?

**Comment by gabime** [comment]
To create the sink directly:
```c++
 auto sink = std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>();
```
Please refer to the [docs](https://github.com/gabime/spdlog/wiki/4.-Sinks).
