### ISSUE TITLE
when log file be removed, couldn't auto recreate  the log file

### ISSUE THREAD

**Issue by Jenuce** [gabime/spdlog#500]
Some time, when log file be removed, couldn't auto recreate log file.  I think we should do that.
file_helper.h, "write" function should like this:
void write(const log_msg& msg){
if (!file_exists(_filename)){
   reopen(false);
}
.......
}

**Comment by iamantony** [comment]
See issue #495

**Comment by gabime** [comment]
checking if file exists for each write would kill performance. Dont delete the log file - it is manged by spdlog
