### ISSUE TITLE
I am still confused about sync mode, anyone help me ?

### ISSUE THREAD

**Issue by zhishupp** [gabime/spdlog#508]
in sync mode, i think the log will send to file immediately, 
in async mode, the log depends on queue size, and will be kept in memory for a while.

so, why in my test, sync mode can not send log to file before i call flush ?
(actually, flush can not sent log to file immeidately too)
I am really confused about this, pls help me out, thanks!

**Comment by gabime** [comment]
Yes. Use flush_on(level) to auto flush based on level

**Comment by zhishupp** [comment]
yes, i already did  flush_on(trace),  but std::fflush can not send log to file immediately, still need a little while, why ? it's the limitation of OS ?

**Comment by zhishupp** [comment]
ok, i just did a test on win & linux,  before application crashed, all messages were correctly logged into file,
that just what I want, great ! 
thanks !
