### ISSUE TITLE
spdlog::set_pattern doesn't work on custom sink loggers if called before creating the logger

### ISSUE THREAD

**Issue by orangefour** [gabime/spdlog#511]
Static function spdlog::set_pattern does not seem to change pattern for custom sink loggers

    class MyCustomSink : public spdlog::sinks::sink {
    public:
      void log(const spdlog::details::log_msg& msg) override {
      ..
      }
      void flush() override {
      ..
      }
    };

    // doesn't work
    spdlog::set_pattern("[%L %H:%M:%S.%e] %v");
    logger = std::make_shared<spdlog::logger>("console", custom_sink);
    
    
    // works
    logger = std::make_shared<spdlog::logger>("console", custom_sink);
    logger->set_pattern("[%L %H:%M:%S.%e] %v");

**Comment by gabime** [comment]
works if using spdlogs factory to create loggers, or by registering the logger
