### ISSUE TITLE
Thread safety and [cannot switch from automatic to manual argument indexing] message

### ISSUE THREAD

**Issue by elelel** [gabime/spdlog#512]
I'm getting error message "[cannot switch from automatic to manual argument indexing" when using SPDLOG_TRACE in a multithreaded application. This happens when I use hex format patterns ( {0:x} or {0:#x} ) and never happens when I change that to {}. I suspect that it happens when a thread that starts with a call to log is notified to continue right after a thread that terminates with a call to log finishes. 
Looks like spdlog formats messages right after log invocation with fmt library, is formatting with fmt library thread safe? Fmt library's README page doesn't say a thing about thread safety and spdlog's wiki only mentions only three functions as thread unsafe and I think they are not called from inside log(...) calls.

**Comment by gabime** [comment]
Please post a code sample to reproduce.

**Comment by elelel** [comment]
I think the problem was in my code, it appears the source was in the very bug I've been trying to fix with SPDLOG_TRACE records. I replaced these calls to spdlog with plain std::cout, found my bug and can't reproduce the error with formatter anymore. The bug was related to threads coordination and move semantics of my objects. So this issue may be closed, but there's a takeaway that SPDLOG_TRACE (and perhaps log_->trace) are more problematic to use for their purposes than a plain std::cout. The trace is not forcibly flushed buy default and a trace record may not appear in the log at all in case of an error that happens between the call and the bug. If we attach default semantic attributes to each log level, perhaps that should include eager flushing policy for trace level? Another possible drawback when compared to plain std::cout is that formatting with fmt is probably not as resilient as with stdlib streams. That is not something I found proof for though.

**Comment by zhongjingjogy** [comment]
I just encountered the same issue, the code for reproducing the issue could be 
```
std;:string result_root_dir = "results";
std::string logfile = "results/logfile.csv";
spdlog::info("Creating directory <path = {}> for <logfile = {1}>", result_root_dir, logfile);
```
The problem might be: some position parameters are assigned with indexes, while the others are not.
