### ISSUE TITLE
easiest to way add file name, row number and function

### ISSUE THREAD

**Issue by yoni386** [gabime/spdlog#517]
Hello,

How to add  file name, row number and function ->  __LINE__, __FILE__ ?

Thank you

**Comment by gabime** [comment]
you can use SPDLOG_TRACE

**Comment by yoni386** [comment]
It may also fit. My idea was if verbose is set by a flag then set the general format to include it.
Is it difficult to add it by me self as done in trace?

**Comment by gabime** [comment]
It must be macro, so it wont work
