### ISSUE TITLE
Clear the file if it's not empty

### ISSUE THREAD

**Issue by Xottab-DUTY** [gabime/spdlog#520]
Now I'm just clearing the file manually on app start:
```C++
std::ofstream f(LogFile);
f << ""; // Create the file or clear it if it's not empty
f.close();
```
Should I continue use this construction or there's a built in option?

**Comment by gabime** [comment]
whic sink are you using?

**Comment by Xottab-DUTY** [comment]
simple_file_sink_mt

**Comment by gabime** [comment]
There is a boolean "truncate" param for this

**Comment by Xottab-DUTY** [comment]
Thank you!
