### ISSUE TITLE
std::mutex makes a bad performance

### ISSUE THREAD

**Issue by zhishupp** [gabime/spdlog#521]
we are using spdlog in our DNS software, here is the QPS on one CPU core:

none log:   1,200,000/s
spdlog with spdlog::details::null_mutex:   600,000/s
spdlog with std::mutex:  240,000/s

so, any way to enhance the performance ?

**Comment by gabime** [comment]
Try using async logger

**Comment by zhishupp** [comment]
yes, I set flush level as trace, i will change it and try again, thx
