### ISSUE TITLE
Add a spdlog::get() style function to retrieve sinks

### ISSUE THREAD

**Issue by Dysl3xik** [gabime/spdlog#525]
I am currently taking advantage of a previously requested feature log levels by sink #279 

Using this scheme I have a single logger that can forward messages around to all my sinks and the sinks can snag messages of variable levels. This works just fine.

I now wanted to add the ability to dynamically toggle the level of the messages going to a given sink. This way the user can turn on more verbose messages while the application is running. To do this a handle to the given sink is required, once this is obtained the level can be set quite easily.

So to enable this kind of usage in an easy manner it would be nice to have a lookup for sinks, just as you have a lookup (the get() function) for logs. Maybe this could be just another get function but inside the ::sinks namespace? or something like spdlog::getSink("MySinkName")?

I don't think this would require much change aside from adding a static/singleton lookup table similar to what you use for looking up logs. If you don't want to change any of the sink constructors or factory functions you can just require users manually register any sinks they want to have be lookupable, otherwise you could add string arguments to your factory functions to register these sinks.

If you would be interested in having this capability in the library, but do not have time to write it, I would be willing to contribute an implementation.

**Comment by gabime** [comment]
Maybe you could use the  looger->sinks() function?

**Comment by Dysl3xik** [comment]
I started on that path but it has a few issues:

If I only want to affect a single sinks level I have to iterate the sinks and find that particular one. Assuming they are all different types I could try casting them to the type of the one I want to hit, and check for null. This only works if each type of sink is unique though. In my case I have two file sinks and the only way for me to distinguish them is to compare the levels or target file path or similar. That is messy. 

FYI I use two file sinks because I have an advanced one with messages that are meaningful to me, but over the average users head, and a more simple log that is just info and above that would normally be used the users for their level of debugging. 

In this case I am turning down the log level of the console and debug file jointly so that on the fly debugging via trace can be done. Once done debugging the levels can be turned back up, however the debug log never gets set higher than debug, so it doesn't always follow the console but it can be lowered to trace. The info log file just never changes level. All of these sinks are housed in all of my loggers, which are really all clones but with names tied to my class names, this is how I detect where errors originate.

**Comment by gabime** [comment]
Well in that case, adding a global map of sinks in your code should be pretty easy.

**Comment by Dysl3xik** [comment]
Yes I have already overcome this in my own application, this was intended more as a feature request/suggestion as I thought this may be useful for other users of this library. If you do not agree you can close this bug.

P.S. it is a great library and I appreciate the work you have put into it!

**Comment by gabime** [comment]
Thanks! I will conside adding it in the future if there is demand.
