### ISSUE TITLE
i_formatter is missing in pattern_formatter_impl.h

### ISSUE THREAD

**Issue by josefschroettle** [gabime/spdlog#527]
When SPDLOG_ENABLE_MESSAGE_COUNTER is defined I get a compilation error in  pattern_formatter_impl.h line 646 (on latest master).
The details::i_formatter() is missing. Adding
#if defined(SPDLOG_ENABLE_MESSAGE_COUNTER)
// Message counter
class i_formatter SPDLOG_FINAL:public flag_formatter
{
    void format(details::log_msg& msg, const std::tm&) override
    {
        msg.formatted << msg.msg_id;
    }
};
#endif
fixed it :-)

**Comment by josefschroettle** [comment]
On second thought the line
       msg.formatted << fmt::pad(msg.msg_id, 6, '0');
looks nicer. It might be nice to add way to 'format' the patterns (width, fill).

**Comment by gabime** [comment]
Right. Could you open a PR?

**Comment by josefschroettle** [comment]
Sorry, I thought the issue would be that. I have no experience with github...

**Comment by gabime** [comment]
No proble. Will be fixed

**Comment by gabime** [comment]
Fixed in 709948ff4ab979113ba5a2de885ed68a79e3ee53.

Thanks for reporting.
