### ISSUE TITLE
set_pattern() thread safety issue

### ISSUE THREAD

**Issue by josefschroettle** [gabime/spdlog#528]
The second call to set_pattern() in the following code crashes with a memory  exception
`    // No decorations for separator line
    spd::set_pattern("%v");

    logger->info("----------------------------------------");

    // Customize msg format for all messages
    spd::set_pattern("%i %Y.%m.%d %H:%M:%S.%f %v"); // => Crashes
`

**Comment by josefschroettle** [comment]
It is not the second call, it is calling set_pattern() after an output.
I'm using an async logger with file rotation.

**Comment by josefschroettle** [comment]
Also adding
    logger->flush();
after logger->info("----") fixes it also. Seems to be a race condition with async logging

**Comment by gabime** [comment]
It is a known limitation. Please see ghe related section in the [docs](https://github.com/gabime/spdlog/wiki/1.1.-Thread-Safety)

**Comment by josefschroettle** [comment]
Oh, thanks. Missed the RTFM :-)
Btw. congratulations to a fine piece of code!
Josef

**Comment by gabime** [comment]
fixed in v1.x branch
