### ISSUE TITLE
Mapped Diagnostic Context

### ISSUE THREAD

**Issue by miqelm** [gabime/spdlog#532]
Have you ever thought about implementing Mapped Diagnostic Context?
It's nice way to log information based on specifier %X{key}. There is map which translates this specified to given value, if given. https://logback.qos.ch/manual/mdc.html

**Comment by gabime** [comment]
Is it something like this - #353 ?

**Comment by miqelm** [comment]
Yes, that's the same

**Comment by miqelm** [comment]
#534

**Comment by SiteshSahoo** [comment]
Can anyone please explain what is the state of this enhancement ? Also, will the enhancement is being planned for  **asynchronous loggers** as well ?

**Comment by gabime** [comment]
implemented in #2907

**Comment by cyaneous** [comment]
This would be a lot more useful if it was usable in async loggers.
