### ISSUE TITLE
Aysnc logger flush interval with multi-sink is not taking effect

### ISSUE THREAD

**Issue by littlehau979** [gabime/spdlog#537]
Hi,

Could you please take a look at the following code?
I found the flush interval is not applied.
It always flush ~8 seconds interval to file sink.

        std::shared_ptr<spdlog::logger> file_logger;
        std::vector<spdlog::sink_ptr> sinks;
        spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block_retry, nullptr, std::chrono::milliseconds(500), nullptr);
        sinks.push_back( std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>() );
        sinks.push_back( std::make_shared<spdlog::sinks::rotating_file_sink_mt>("myfilename", 1024*1024*5, 3) );
        
        file_logger = std::make_shared<spdlog::logger>("multisink", sinks.begin(), sinks.end());
        spdlog::register_logger(file_logger);
        
        while(1) {
            usleep(100000);
            file_logger->info("log message");
        }

Simple async logger without multi-sink works

        spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block_retry, nullptr, std::chrono::milliseconds(500), nullptr);
        auto file_logger = spdlog::rotating_logger_mt("file_logger", "myfilename", 1024 * 1024 * 5, 3);
        
        while(1) {
            usleep(100000);
            file_logger->info("message");
        }

Thanks

**Comment by gabime** [comment]
you need to create spdlog::async_logger when creating the file_logger

**Comment by littlehau979** [comment]
thanks.
modified to async_logger and it works well.

    std::shared_ptr<spdlog::async_logger> file_logger;
    std::vector<spdlog::sink_ptr> sinks;
    sinks.push_back( std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>() );
    sinks.push_back( std::make_shared<spdlog::sinks::rotating_file_sink_mt>("myfilename", 1024*1024*5, 3) );
    file_logger = std::make_shared<spdlog::async_logger>("multisink",
                                                         sinks.begin(),
                                                         sinks.end(),
                                                         8192,
                                                         spdlog::async_overflow_policy::block_retry,
                                                         nullptr,
                                                         std::chrono::milliseconds(500),
                                                         nullptr);
    spdlog::register_logger(file_logger);
    
    while(1) {
        usleep(100000);
        file_logger->info("log message");
    }

**Comment by naveenpinto** [comment]
with the latest spd log code below function is not present
spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block, nullptr, std::chrono::milliseconds(500), nullptr);

how can we create a rotating logger that is async and has a flush interval, some examples on this will be nice :)
