### ISSUE TITLE
spd::daily_logger_mt

### ISSUE THREAD

**Issue by songfg** [gabime/spdlog#542]
1:how can i create a spd::daily_logger that it created just one file  in th day?
  spd::daily_logger_mt("test", "logs//log", 0, 0);
 The above code will create a new file while everytime use it  

2:how can i create a spd::daily_logger that the file name is completed by  myself
  spd::daily_logger_mt("test", "logs//log", 0, 0);
 the file name is "log_2017-10-31_12-30" but i want the file name is  "log_2017-10-31"

thanks

**Comment by Subenle** [comment]
You can write your own `daily_file_name_calculator`, see `default_daily_file_name_calculator` below:
https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/file_sinks.h#L151

**Comment by songfg** [comment]
@Subenle Thank you for your answer.
And spd::daily_logger_mt don't create folder?

**Comment by Subenle** [comment]
What do you mean **spd::daily_logger_mt don't create folder ?**  

The `default_daily_file_name_calculator` set file name accurate to the minute, if you dont restart your program, there will only be ONE log file. But if you restart your program, a new log file may be created.

If you modify the file name to "log_2017-10-31", then every time you use it in the same day, it will write logs to the same file.

**Comment by songfg** [comment]
@Subenle 
嗯这个我已经改成年月日了,但是spd::daily_logger_mt("test", "logs//log", 0, 0);
第二个参数 如果logs文件夹不存在就会抛出异常,他自己是不会创建logs的文件夹的 不知道库里有没有提供创建文件夹的
