### ISSUE TITLE
Conan package for spdlog

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [gabime/spdlog#547]
Hello,
Do you know about Conan package manager? Can you add Conan package for the library and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by gabime** [comment]
spdlog does not maintain the packages for it. They are maintained externally.

**Comment by hestad** [comment]
I think it would be very valuable for conan-users if the mentioned conan-package found its way here: https://bintray.com/conan/conan-center

Because the conan-transit repo is freezed.

e.g. bincrafters are maintaining fmt: https://bintray.com/bincrafters/public-conan/fmt%3Abincrafters
