### ISSUE TITLE
Using variadic templates to log

### ISSUE THREAD

**Issue by BotellaA** [gabime/spdlog#552]
Hello,

I am thinking about using spdlog in my project. I am currently using a variadic template approach to log like:
`logger.info("message with several values: ", 12 , " and ", 54);`

It looks like you do not handle this kind of parameters. Do you think of a way to use your logger without changing the logger messages in my entire codebase?

Thank for your ideas

**Comment by gabime** [comment]
You would need to change

```c++
logger.info("message with several values: ", 12 , " and ", 54);
```
to 

```c++
logger.info("message with several values: {}{}{}", 12 , " and ", 54);
```

I don't think there is any easy workaround

**Comment by BotellaA** [comment]
Thank you for your answer.
Could this will work too?
`logger.info("{}{}{}{}", "message with several values: ", 12 , " and ", 54);`

**Comment by gabime** [comment]
Probably yes.. But looks silly :)

**Comment by BotellaA** [comment]
Sure but easier to interface with my project! ;)
