### ISSUE TITLE
'null_sink_mt' is not a member of 'spdlog::sinks'

### ISSUE THREAD

**Issue by daylanKifky** [gabime/spdlog#553]
I'm getting that error when trying to create a null_sink

```
sinksVector.push_back(make_shared<spdlog::sinks::null_sink_mt>());
```

Am I missing something? I don't see `null_sink.h` included nowhere.

**Comment by gabime** [comment]
>  I don't see null_sink.h included nowhere.
It is not included. You need to include it yourself

**Comment by daylanKifky** [comment]
ok, thank you, I now see it was written on the wiki
