### ISSUE TITLE
Windows debugging output

### ISSUE THREAD

**Issue by jpcima** [gabime/spdlog#554]
Hi. The windows debug sink can be useful out of Visual Studio and should not be limited to that IDE.
There are other tools to access the debug log, including Sysinternals Debugview, which works even in Wine.
In my opinion the support should be extended to all the Windows compilers.

I propose to do these changes:
* rename msvc_sink (windebug_sink? maybe also keep the old name for compatibility)
* check for _WIN32 instead of _MSC_VER
* rename WinBase.h to winbase.h (mingw compilation on case-sensitive fs)

**Comment by gabime** [comment]
Thanks for the suggestions. A pull request would be welcome.

> rename msvc_sink (windebug_sink? maybe also keep the old name for compatibility)

Right. better not rename but maybe add ```#typedef windebug sinkmsvc_sink;```

> check for _WIN32 instead of _MSC_VER

Agreed

> rename WinBase.h to winbase.h (mingw compilation on case-sensitive fs)

Agreed
