### ISSUE TITLE
Help needed using LPWSTR variable logging

### ISSUE THREAD

**Issue by DaveRabelink** [gabime/spdlog#557]
Hi,
I'm not a C(++) expert but can manage putting stuff together with a lot of trial&errors.

I have implemented spdlog in my project but I get compile errors when using LPWSTR variables.

Here a snipplet:

```
#define SPDLOG_WCHAR_TO_UTF8_SUPPORT
#include "spdlog/spdlog.h"

	LPWSTR sTest;
	spd::get("async_file_logger")->info(sTest);
	spd::get("async_file_logger")->info(L"This is a text");
```

Results in this error when using sTest variable.
The second line passing L"This is a text" compiles ok.

logger_impl.h(105): error C2248: 'fmt::BasicWriter<char>::operator <<': cannot access private member declared in class 'fmt::BasicWriter<char>'

What do I need to do to log the string contents of sTest variable?

**Comment by DaveRabelink** [comment]
Ah, I have found it myself.

This is the proper way and works:

`spd::get("async_file_logger")->info( L"{}", sTest );`

**Comment by gabime** [comment]
OK. Thanks for the update
