### ISSUE TITLE
Missing function implementation of log_if with variable Args

### ISSUE THREAD

**Issue by meldavis** [gabime/spdlog#558]
In logger.h, ~ line 47, it looks like the **log_if** function with variable Args is unimplemented.  

``` C++
template <typename... Args> 
void log_if(const bool flag, level::level_enum lvl, const char* fmt, const Args&... args);
```

**Comment by gabime** [comment]
I removed this feature entirely  in dcc7b347caadca6d191c40c8ae59a3320ab277ac
