### ISSUE TITLE
Is automated configuration of interest?

### ISSUE THREAD

**Issue by dsmccall** [gabime/spdlog#560]
I've made some additions to my fork of spdlog so that I can control global functions/sinks/loggers from a configuration file, and added a few macros to simplify certain logging scenarios.
I've certainly found a use for this type of functionality - I was wondering if it might be of further interest?

**Comment by gabime** [comment]
Hi,
There is already a repo for config file [here](https://github.com/guangie88/spdlog_setup). Is it similar?

**Comment by dsmccall** [comment]
Hi,
I think the functionality is quite similar - that's a great project :).  My additions are probably quite a bit simpler, and don't have any additional dependencies.

I've added some test cases [here](https://github.com/dsmccall/spdlog/blob/master/tests/auto_configuration.cpp) that show some of the functionality.  It's unfinished, but I'll be adding more to it and tidying it up over the next few days.

**Comment by tjakway** [comment]
+1 for interest
