### ISSUE TITLE
Allow making tweaks with compiler definitions, instead of just "tweakme.h"

### ISSUE THREAD

**Issue by meldavis** [gabime/spdlog#562]
If I customize "tweakme.h" for my application, my build system may later overwrite my changes when it pulls updates from the spdlog repo.   So, I instead add my tweaks as definitions in the compiler options.

The problem is that "common.h" is written to require a trailing semicolon in the definition of SPDLOG_LEVEL_NAMES;  But semicolons cannot be part of a compiler option.   If you make the following small change, it will all work.

In "common.h"
On line 84: remove the trailing semicolon
On line 86: add a trailing semicolon.

https://github.com/gabime/spdlog/blob/587b5282927b0515a9724bd1069bd2316b573b71/include/spdlog/common.h#L83-L86

**Comment by gabime** [comment]
sure. please issue a pull
