### ISSUE TITLE
VS 2017 Update 15.5: Build Error C4996

### ISSUE THREAD

**Issue by htmlboss** [gabime/spdlog#569]
With update 15.5, MSVC has drastically changed the behaviour of the std::allocator. Just wanted to give you a heads-up:

`Error	C4996	'std::allocator<char>::allocate': warning STL4010: Various members of std::allocator are deprecated in C++17. Use std::allocator_traits instead of accessing these members directly. You can define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.	...\include\spdlog\fmt\bundled\format.h	903	`

Lemme know if you need any more info.

**Comment by gabime** [comment]
Thanks i will take a look

**Comment by meldavis** [comment]
Just to give some additional info.  In spdlog specific code, the error appears at line 371 below when SPDLOG_WIDECHAR_FILENAMES is defined.  MSDN say to consider using MultiByteToWideChar() and WideCharToMultiByte() from <Windows.h> instead.

https://github.com/gabime/spdlog/blob/88fe218741d46deed401f5458dbbda6fa1c1f2f2/include/spdlog/details/os.h#L366-L373

**Comment by PooyaEimandar** [comment]
Same problem on Visual Studio 2017 update 15.7 
I couldn't build with folowing defines 
```
SPDLOG_WCHAR_TO_UTF8_SUPPORT
SPDLOG_WCHAR_FILENAMES
```
with C++17
