### ISSUE TITLE
Using spdlog with cppformat cause #include order dependency

### ISSUE THREAD

**Issue by objectx** [gabime/spdlog#57]
I've tried using `spdlog` and `cppformat` simultaneously.  But 1st do #include `spdlog/spdlog.h` cause error.

`#define FMT_HEADER_ONLY` in `spdlog` cause some functions (in the anonymous namespace) were declared twice.

**Comment by meldavis** [comment]
Workaround: To use both spdlog and cppformat in the same app, I create a header called "format.h" containing only the following line: `#include "spdlog/details/format.h"`

I include this "format.h" file when I want to bring in the `fmt:` namespace.
