### ISSUE TITLE
Getting compile-error in logger_impl.h#L255

### ISSUE THREAD

**Issue by hestad** [gabime/spdlog#571]
https://github.com/gabime/spdlog/blob/b1be7b9fea296bea1ec43ab4921f04d3f8affe00/include/spdlog/details/logger_impl.h#L255

There is an extra right curly braces. (at least for clang 5)

How come your build-server flagged this as green?

**Comment by gabime** [comment]
Because the clang tests were removed a while ago :(

**Comment by gabime** [comment]
Fixed in 88fe218741d46deed401f5458dbbda6fa1c1f2f2

Please verify it solves your problem

**Comment by hestad** [comment]
I would guess you never call #define SPDLOG_WCHAR_TO_UTF8_SUPPORT in your tests?

**Comment by hestad** [comment]
Yes, that fixes it for me.

**Comment by hestad** [comment]
Btw, since I have you here :) when do you plan to release spdlog next time?

**Comment by gabime** [comment]
Very soon. Hopefully in the next few days. Why?

**Comment by hestad** [comment]
I'm waiting for two of the wstring-fixes, but also a fmt-fix related to wstring. (ref: 
 https://github.com/fmtlib/fmt/pull/606#issuecomment-343497460 )

I have just copied the sources for now, but ideally we would get spdlog + fmt via conan.

**Comment by gabime** [comment]
Please note the the spdlog bundles only official fmt versions, not necessarily the latest fixed from the fmt repo..

**Comment by hestad** [comment]
Yeah, I guessed as much, but I also agree. I had a tiny dream that they could be co-released :)

**Comment by gabime** [comment]
Do you know when fmt plan to release? that can be arranged

**Comment by hestad** [comment]
Seems like they accepted to do a release the next few days: https://github.com/fmtlib/fmt/issues/621#issuecomment-349868682

**Comment by gabime** [comment]
Oh thats good. I will wait..
