### ISSUE TITLE
SPDLOG_FMT_EXTERNAL

### ISSUE THREAD

**Issue by VikingExplorer** [gabime/spdlog#573]
I am also using the fmt library, and I was getting an error, so I defined SPDLOG_FMT_EXTERNAL in my preprocessor settings.

This fixed the error, but left this warning:

1>C:\Dev\Couloir\3pLibs\vcpkg\installed\Win32\include\spdlog/tweakme.h(95): warning C4005: 'SPDLOG_FMT_EXTERNAL': macro redefinition (compiling source file Log.cpp)
1>C:\Dev\Couloir\3pLibs\vcpkg\installed\Win32\include\spdlog/tweakme.h(95): note: command-line arguments:  see previous definition of 'SPDLOG_FMT_EXTERNAL' (compiling source file Log.cpp)

The comments say to comment out the line causing the warning.

I just thought it was odd to have to do that.

Wouldn't this work better:

#ifndef SPDLOG_FMT_EXTERNAL
#define SPDLOG_FMT_EXTERNAL
#endif

**Comment by godbyk** [comment]
That wouldn't work because then `SPDLOG_FMT_EXTERNAL` would always be defined.

You could change the logic of `SPDLOG_FMT_EXTERNAL` everywhere to check if it's set to 0 or 1 instead of whether or not it's defined. Then the default definition (if not previously defined) could be 0 and you could override it when you compile it.

**Comment by gabime** [comment]
@VikingExplorer why are you defining it twice?

**Comment by VikingExplorer** [comment]
Unless I'm mistaken, I didn't. Without any code change, was getting an error.  Defined in pre processor, got warning.  However, I'm transitioning from a previous version to the one from vcpkg. Let me check the issue isn't on my end.  Give me an hour.

**Comment by VikingExplorer** [comment]
So, I removed SPDLOG_FMT_EXTERNAL in pre-processor settings.

I made there was no way to include anyh files from the previous version of spdlog or fmt.

Error	C1083	Cannot open include file: 'spdlog/fmt/bundled/format.h': No such file or directory	CouloirAFX-WinW	C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog\fmt\fmt.h	21	

I haven't defined it all, let alone twice.

It gets to it by this route:

1>Note: including file: C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Include\LogSink.hpp
1>Note: including file:  C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog/sinks/base_sink.h
1>Note: including file:   C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog/sinks/sink.h
1>Note: including file:    C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog/details/log_msg.h
1>Note: including file:     C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog/common.h
1>Note: including file:      C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog/details/null_mutex.h
1>Note: including file:      C:\Dev\Couloir\3pLibs\vcpkg\installed\x64\include\spdlog/fmt/fmt.h

**Comment by gabime** [comment]
yes but why is it uncommented in line 95 in the first place?

**Comment by VikingExplorer** [comment]
I thought it started out uncommented.  If that's not the case, I must have confused myself.

Sorry about all this.

**Comment by gabime** [comment]
np. thanks for reporting anyway
