### ISSUE TITLE
Release 0.16.0 date

### ISSUE THREAD

**Issue by arossert** [gabime/spdlog#574]
As I understand you are planning to release version 0.16.0 soon, do you have a date for the release (we are planning to do a release in our project and we want the latest spdlog release)?

**Comment by gabime** [comment]
No specific date but hopefully this week - I am waiting for fmt 4.0.1 - to bundle with this release.

**Comment by arossert** [comment]
Thanks, we will wait for the release.

**Comment by horar** [comment]
HI @gabime , could you please keep updated version string SPDLOG_VERSION in spdlog.h. It defines version 0.14.0

**Comment by gabime** [comment]
Sh**t, I forgot to update it. Is there a way to update a release? Or maybe i will  create a new release 0.16.1 with the proper version

**Comment by gabime** [comment]
I release new version 0.16.1
