### ISSUE TITLE
Forking a logger to create an exact duplicate w/ different name?

### ISSUE THREAD

**Issue by jadamcrain** [gabime/spdlog#576]
Is there a way to fork a logger to change or append it's name, but keep the exact same set of sinks?

I would like to just create a single logger that can be configured to have one or more sinks from a configuration file.  I want multiple components to use that same set of sinks, but I want each component to have a distinct log name. Is this possible without having to create multiple loggers all pointing to the same std::vector<>?

**Comment by gabime** [comment]
I dont think so. whats wrong with sharing the vector of sinks?

**Comment by jadamcrain** [comment]
That'll work. I can inject all my loggers at the top level during initialization, so no issue there.

The version I'm using in Ubuntu 17 via the package manager is a bit dated, so I'll upgrade to the latest that has spdlog::logger::sinks().

thanks!
