### ISSUE TITLE
example.cpp:150:49: fatal error: spdlog/fmt/ostr.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by caoyang1024** [gabime/spdlog#578]
unable to compile using command `g++ -std=c++0x -pthread` on ubuntu 16.04 LTS
with error ostr.h can't be found, but it exists.
thanks.

**Comment by pabloariasal** [comment]
Well did you set your include directories? I advice you to build using cmake as explained [here](https://github.com/gabime/spdlog/wiki/9.-CMake)
