### ISSUE TITLE
Is there an option to prevent adding EOL character to messages?

### ISSUE THREAD

**Issue by sandy081** [gabime/spdlog#579]
Hi!

We use spdlog in VS Code for logging and it is working very well and faster. 

We also wanted to use it in our Output channels which receives messages and show them as logs.These logs are in memory and now we want to use spdlog to write them into files. These can append incoming messages without inserting a new line. 

Since spdlog always inserts EOL, I wonder if there is an option to prevent this?

**Comment by gabime** [comment]
Sure, there is a way -  define the “SPDLOG_EOL” macro in tweakme.h to “”.

**Comment by sandy081** [comment]
Thanks, but I think this is a global option right? Can't we have per logger option? We would be having multiple loggers with different formatters and we want one of the loggers only to have this option.

**Comment by gabime** [comment]
No, no such option exists. sorry

**Comment by sandy081** [comment]
Thanks @gabime for the quick response.

**Comment by sandy081** [comment]
@gabime Do you think providing a way to set `eol` per logger makes sense and can be treated as a feature for spdlog?

I see `eol` is set by the default inline formatter, if the logger has a custom formatter then is it up to the formatter to set it or not?

**Comment by gabime** [comment]
eol is  decided by the formatter -  so if such option to be provided, it would as be a param to the pattern formatter constructor.
By “custom formatter”, do  you mean a custom implementation of the formatter interface?

**Comment by sandy081** [comment]
@gabime 

> eol is decided by the formatter - so if such option to be provided, it would as be a param to the pattern formatter constructor.

Agreed. It means, `eol` also has to be a param to the logger constructor.

> By “custom formatter”, do you mean a custom implementation of the formatter interface?

Yes.

**Comment by sandy081** [comment]
If you think it is a good idea to set `eol` per logger, I would be happy to submit a PR

**Comment by gabime** [comment]
Ok. Adding an option to the ctor of the formatter would be enough:
 
```c++
std::string eol(“some eol”);
spdlog::formatter f = std::make_shared<spdlog::pattern_formatter>(“%l %v”,  eol);
logger->set_formatter(f)
```

On the other hand it is would be a rarely used featue, so if you can solve your problem using simple custom formatter, it would be better. If not, please issue a pr.

**Comment by sandy081** [comment]
@gabime I have a solution for it by having a custom formatter. Thanks for the help.

**Comment by EwingKang** [comment]
Just found this discussion very useful. My thank to everyone.
However the API for both `pattern_formatter` constructor and `set_formatter()` has changed since the answer. Leave my implementatino here in case anyone wants to know.
```
auto f = std::make_unique<spdlog::pattern_formatter>("%l %v", spdlog::pattern_time_type::local, std::string(""));  // disable eol
p_nmea_logger->set_formatter( std::move(f) );
```

**Comment by slinkinone** [comment]
@EwingKang Thank you a lot for the example!
