### ISSUE TITLE
spdlog::stdout_logger_st requires pthreads

### ISSUE THREAD

**Issue by zyv** [gabime/spdlog#58]
Hi,

I'm not sure if it's a bug, or a feature, so here's the issue anyways. I've read the documentation and decided to start using spdlog in my (for now, single-threaded) project. Thus, I figured that spdlog::stdout_logger_mt won't bring me anything and spdlog::stdout_logger_st is the right choice. However, as I compiled the project, I've got a bunch of linking errors connected to pthreads. Adding -pthread or -fopenmp switch to the driver invocation fixed them.

So, the question is whether the single-threaded logger is supposed to be usable without threads at all? This is what I would have expected, and I think that it would be a fairly useful property. If not, then I beg my pardon, but it would be nice at least to have it documented.

As a corollary, is my understanding correct that if I ever go for -fopenmp, I wouldn't need threading support explicitly, as -pthread will be magically brought in by -fopenmp, or this is platform/compiler dependent?

Many thanks!

**Comment by gabime** [comment]
Spdlog uses threading stuff internally in several places in the code regardless of the logger type, so -pthread flag must be used.

About openmp - I am not sure..

**Comment by zyv** [comment]
Thanks for a very fast reply, @gabime!

In this case, I guess, I should rephrase my question: is it possible / feasible to isolate this and compile it out if no threading is required (by the application), or I should accept it, and failing that, look for another library?

Would you have any suggestions for the latter case? I was quite impressed by spdlog being simple, clean and header-only (!), while having all the basic niceties that one would expect.

**Comment by gabime** [comment]
It is probably possible by adding some #ifdefs and removing the async support..
Why is this thing is so critical for you?

**Comment by zyv** [comment]
Well, the project that I'm working on doesn't require threads (*), and for now is being statically linked. I can introduce detection of threads to the build system, and switch to dynamic linking, but because of (*) this would be hard to justify.

Additionally, we have a rather strict policy on dependencies, that is, one shouldn't pull-in anything that has to be linked, so I'm sticking to header-only libraries, if I need to go beyond STL, which why I was happy to find spdlog: it's header-only and covers the basics. The popular alternatives like glog or boost::logging require compilation...

**Comment by gabime** [comment]
In this case, spdlog is proably not suitable - It is not trivial to remove the pthread reliance.

**Comment by zyv** [comment]
Okay, I would suggest to mention that in the README then. Thanks for the feedback!
