### ISSUE TITLE
Increase level of detail of exceptions

### ISSUE THREAD

**Issue by pabloariasal** [gabime/spdlog#588]
In order to better signalize issues we should increase the level of detail of exceptions. In my case in particular I could really use a `spdlog::logger_already_exists_exception`. I can provide a PR if this seems relevant

**Comment by gabime** [comment]
Thanks,  but I try to keep this simple as possible, without too many exception types or hierarchies.

**Comment by pabloariasal** [comment]
Alright. Thank you for your answer.
