### ISSUE TITLE
Suggestion: Clang-Format and Clang-Tidy

### ISSUE THREAD

**Issue by fcharlie** [gabime/spdlog#591]
We can create a file named *`.clang-format`* under project root path. clang-format use configured style format sources code

Tool benefits can reduce code-style differences

https://github.com/llvm-mirror/llvm/blob/master/.clang-format
https://github.com/Microsoft/vcpkg/blob/master/toolsrc/.clang-format

My projects style: 

```yml
BasedOnStyle: LLVM
SortIncludes: false
```

Mybe AStyle is good tools, But Clang-format can better avoid clang-tidy warnings.

Aslo, We can use clang-tidy check code's bugs.

https://github.com/llvm-mirror/llvm/blob/master/.clang-tidy

**Comment by gabime** [comment]
astyle is good enough for me, but clang tidy might be useful. Please issue a PR
