### ISSUE TITLE
Make libfmt a compile time option

### ISSUE THREAD

**Issue by stkw0** [gabime/spdlog#592]
Could libfmt be a cmake option? This way a distro package would be able to globally avoid the bundled version without having to patch tweakme.h.

Thanks

**Comment by gabime** [comment]
Maybe.. As long as the current tweakme.h way still holds

**Comment by stkw0** [comment]
Personally, the best option will be to not bundle fmt library. I understand that some people may want to easily use this library in their projects, to accomplish this fmt is bundled inside spdlog. For this use case I don't think that the SPDLOG_FMT_EXTERNAL option on tweakme.h have much value.
Who use this library by installing it from source using cmake, they will be able to decide if they want to install the bundled fmt or not,  so I don't think that SPDLOG_FMT_EXTERNAL option have much value for this users neither. 
Also, if some vulnerability is found on fmt, the bundled version may be left vulnerable more time than it should.

**Comment by gabime** [comment]
> . For this use case I don't think that the SPDLOG_FMT_EXTERNAL option on tweakme.h have much value.

This flag is already used by numerous projects - any solution  should be backward compatible

**Comment by stkw0** [comment]
I'm currently using SPDLOG_FMT_EXTERNAL but because there are no other options. 

I agree that in general backward compatibility is a valuable thing, but adding a cmake option and at the same time maintaining the option on tweakme.h will be more confusing and hard to implement. As I don't see how to implement such a thing I will close this issue.

Thank your for your time.

**Comment by gabime** [comment]
ok. thanks for the suggestion
