### ISSUE TITLE
Conditional logging removed from version 16.*

### ISSUE THREAD

**Issue by tluqo** [gabime/spdlog#594]
Why have you removed conditional logging from version 16.*?

**Comment by gabime** [comment]
I decided it is redundant and confusing - Just a fancy way of doing if

**Comment by Jerry-Ma** [comment]
Correct me if I am wrong, but intuitively, I thought that by using SPDLOG_DEBUG_IF, we can skip the if clause when the debug message is disabled at compile time. Is that true?

**Comment by gabime** [comment]
There are 2 levels of protection when using macros. On compile time and runtime.
see  https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/spdlog.h#L314

**Comment by Jerry-Ma** [comment]
say we have the code:

`if (expensive_debug_logic()) SPDLOG_DEBUG("foo");`

compared with:

`SPDLOG_DEBUG_IF(expensive_debug_logic(), "foo")`

When we disable the debug message, the former will still call `expensive_debug_logic()` while the latter does not. I thought this is a handy feature.

**Comment by Jerry-Ma** [comment]
@gabime any comments on this?

**Comment by gabime** [comment]
I still think its just a fancy way of doing a simple ״if״

**Comment by kunaltyagi** [comment]
This feature would prevent a runtime check if removed compile-time. Currently that's no longer feasible without replicating the same logic used in spdlog.

I understand it seems like a fancy `if` but it's a bit more than that. It's also wrapping that if into a macro and preventing at least 1 operation at runtime (and potentially (most likely) an expensive function call)

**Comment by sketch34** [comment]
I would find the `_IF` macros useful. Yes it's a fancy if that gives a clean way to get rid of the runtime logic when logging is disabled. The alternative is too messy in my opinion. Here's my real world example where I wanted this today:

```
// ^_^ lovely, calm, readable
SPDLOG_DEBUG_IF(!win->empty(), "cache hit for request: {}", req.describe(desc_));
```

versus

```
// o_O more brain load than is reasonable
#if SPDLOG_ACTIVE_LEVEL <= SPDLOG_LEVEL_DEBUG
 if (!win->empty()) {
     SPDLOG_DEBUG("cache hit for request: {}", req.describe(desc_));
 }
#endif
```

It seems reasonable for a library dedicated to logging to have these extra macros.
