### ISSUE TITLE
sinks/wincolor_sink.h -Wconversion warning.

### ISSUE THREAD

**Issue by Broekman** [gabime/spdlog#595]
On line 85 in file sinks/wincolor_sink.h:
`back_color &= ~(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY);`

'back_color' is of type 'WORD' (unsigned short) whereas a bitwise complement/NOT returns an int. This results in a conversion warning with -Wconversion enabled. 

`85:20: warning: conversion to 'WORD {aka short unsigned int}' from 'int' may alter its value [-Wconversion] back_color &= ~(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY);`

Possible solution:
We know that the result of `~(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)` is always within the limits of an unsigned short so a simple cast should suffice (correct me if I'm wrong):

`back_color &= static_cast<unsigned short>(~(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY));`

**Comment by gabime** [comment]
Yes. Maybe even cast to WORD to be exact. 
It is strange I never encountered this warning..How do you complie this?

**Comment by Broekman** [comment]
Yes, a cast to WORD is the more obvious choice of course.

Currently, I'm using the following for my Windows adventures:
Build tool: MinGW-W64 (with GNU Make 4.2.1)
Compiler: GCC: 7.2.0
Compile options: -O2 -g3 -Wall -Wextra -Wconversion

**Comment by gabime** [comment]
Ok. Could you open a PR?

**Comment by Broekman** [comment]
Done.

**Comment by gabime** [comment]
Thanks.Merged
