### ISSUE TITLE
Upgrade to bundled fmt to 4.1.0

### ISSUE THREAD

**Issue by hestad** [gabime/spdlog#597]
Fmt has released 4.1.0: https://github.com/fmtlib/fmt/releases/tag/4.1.0

**Comment by candrews** [comment]
I believe it would be much better to not bundle libfmt (the fact that spdlog is falling behind libfmt releases is an example of why not bundling is the better solution): https://github.com/gabime/spdlog/issues/600

**Comment by gabime** [comment]
@hestad It will have to wait for next version.

**Comment by gabime** [comment]
Committed in 3826ac14336b7b862b48ef9182672fe572f1a47c
