### ISSUE TITLE
Is C++ -fno-exceptions completely support in spdlog ver 0.16.2?

### ISSUE THREAD

**Issue by droneboost** [gabime/spdlog#598]
Hi All,

I find several issue threads talked about it, in https://github.com/gabime/spdlog/pull/231, godbyk  seems has fix it and  gabime merged the modification, but I still can find lots of C++ keywords "try", "catch", "throw" in following files which break my build(I did set FMT_EXCEPTIONS=0 in my makefile). Who can tell me the latest status about compiling spdlog with -fno-exceptions option. Thank!

spdlog\details\async_logger_impl.h"(88,5):    try
spdlog\details\async_log_helper.h"(227,5):    try
spdlog\details\async_log_helper.h"(275,9):        try
spdlog\details\logger_impl.h"(65,5):    try
spdlog\details\logger_impl.h"(86,5):    try
spdlog\details\logger_impl.h"(102,5):    try
spdlog\details\async_logger_impl.h"(97,5):    catch (const std::exception &ex)
spdlog\details\async_log_helper.h"(232,5):    catch (...) // don't crash in destructor
spdlog\details\async_log_helper.h"(279,9):        catch (const std::exception &ex)
spdlog\details\logger_impl.h"(76,5):    catch (const std::exception &ex)
spdlog\details\logger_impl.h"(92,5):    catch (const std::exception &ex)
spdlog\details\logger_impl.h"(108,5):    catch (const std::exception &ex)

**Comment by gabime** [comment]
spdlog must have exceptions enabled.
There were talks about maybe support fno-exceptions,  but it was decided that it is not simple to support correctly.

**Comment by droneboost** [comment]
Thanks! Got it.

**Comment by gabime** [comment]
Done. See https://github.com/gabime/spdlog/issues/1152
