### ISSUE TITLE
Do not bundle libfmt

### ISSUE THREAD

**Issue by candrews** [gabime/spdlog#600]
It's not a good practice to bundle dependencies; problems with bundling include trouble keeping up to date leading to security vulnerabilities persisting when they really shouldn't as well as symbol collisions and other confusion.

https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

Can you please not bundled libfmt, and instead depend upon it?

I believe that:
* modifying the code to behave as if `SPDLOG_FMT_EXTERNAL` is always set
* modifying https://github.com/gabime/spdlog/blob/master/CMakeLists.txt to check for libfmt

would be the solution

**Comment by gabime** [comment]
This is convenient in many cases and  spdlog doesn't force it - like you noted  all that is needed is setting the SPDLOG_FMT_EXTERNAL flag. 
The package/build scripts can always set it.
