### ISSUE TITLE
Passing arbitrary data to the logger

### ISSUE THREAD

**Issue by overfl0** [gabime/spdlog#603]
Is there a way to prevent processing/formatting of the data passed to the logger? (while retaining the logger name, date, etc... as the same time)

I would like to log arbitrary data from a separate system so the data to log will always come as a single string with no additional arguments. I would like to prevent the situation where a `"{}"` string will be logged from that system and interpreted as requiring an additional argument to be passed to the logger, resulting in a format string attack.

While I could in theory always pass `"{}"` as the first argument and the string to be logged as the second one, I believe there must be a way to "just log" what I'm passing to the logger (without the formatting performance penalty).

Or maybe it is safe to pass such strings if there are no additional arguments passed to the logger?

**Comment by gabime** [comment]
If you pass a single argument to logger it will not format anything. It will log it as is
See [logger_imp](https://github.com/gabime/spdlog/blob/master/include/spdlog/details/logger_impl.h#L94)
And: [logger_imp](https://github.com/gabime/spdlog/blob/master/include/spdlog/details/logger_impl.h#115)

They are writing to the buffer as is:
```c++
  log_msg.raw << msg;
```
as opposed to doing
```c++
log_msg.raw.write(fmt, args...);
``` 
when more than one arg passed
