### ISSUE TITLE
How to output the file name in the log

### ISSUE THREAD

**Issue by Guozht** [gabime/spdlog#607]
How to output the file name in the log？

**Comment by Guozht** [comment]
Such As：
***[xxxxx.cpp] [11:02:14 +08:00] [thread 15816] Async message #16 ***
***[sdadas.cpp] [11:02:14 +08:00] [thread 15816] Async message #16 ***
***[asdasdas.cpp] [11:02:14 +08:00] [thread 15816] Async message #16 ***
***[asdasda.cpp] [11:02:14 +08:00] [thread 15816] Async message #16 ***
***[asdasdasd.cpp] [11:02:14 +08:00] [thread 15816] Async message #16 ***
***[123123.cpp] [11:02:14 +08:00] [thread 15816] Async message #16 ***

**Comment by nukes** [comment]
did you solved this problem? @Guozht
