### ISSUE TITLE
Windows: sleep_for is dependent on system clock

### ISSUE THREAD

**Issue by joaomoreno** [gabime/spdlog#609]
Hey there! 👋 

We've hit this issue in VS Code: https://github.com/Microsoft/vscode/issues/41136

Ultimately here's the problem: `std::this_thread::sleep_for` is poorly implemented in Windows and depends on the system clock. When the thread is sleeping and the system clock is changed to a previous time, the sleep takes longer than expected, apparently by as much as the system clock was changed.

The bug easily reproduces with this snippet:

```cpp
#include "stdafx.h"
#include <iostream>
#include <chrono>
#include <thread>

int main()
{
	while (true) {
		std::cout << "sleeping for 500ms" << std::endl;
		std::this_thread::sleep_for(std::chrono::milliseconds(500));
	}

    return 0;
}
```

Simply go back in time and one of the 500ms `sleep_for` calls will take much longer.

---

I found a comment in [here](https://developercommunity.visualstudio.com/content/problem/61684/stdthis-threadsleep-for-depends-on-system-time.html) which indicates that `sleep_until` doesn't have the same issue, though I don't really verify that. I tried using both `system_clock` and `steady_clock` to compute the `sleep_until` argument; the bug still happens.

Of course, using the WinAPI call `Sleep` works like a charm.

Would you accept a PR in which I replace `sleep_for` calls for `Sleep` calls in Windows?

**Comment by gabime** [comment]
Sure. I prefer it the be inplemented in the os.h file for obvoius reasons
