### ISSUE TITLE
spdlog::set_level(...) does not affect loggers created afterwards

### ISSUE THREAD

**Issue by ssams** [gabime/spdlog#61]
Changing the global log level only changes the output of already created loggers, but loggers created after changing the global level still use the default level.

Fixing it should be easy; in [registry.h](https://github.com/gabime/spdlog/blob/e9dbd4c0f987affcd7e9858034ad2de812f4e825/include/spdlog/details/registry.h) add the following line to the implementation of `set_level`:
```
_level = log_level;
```

**Comment by gabime** [comment]
Thanks. committed a fix in 3556c87a51bc89696f6230b4c6c76f88c18d5990.
Easy fix indeed :)
