### ISSUE TITLE
Q: how to format an external object?

### ISSUE THREAD

**Issue by garyo** [gabime/spdlog#612]
I have an external class (not my own), called `cv::Mat`. I'd like to format objects of that type in my spdlog logs.

I saw the message from spdlog that says I should provide an overload of `format_arg`. I'm not sure exactly how to implement that. I tried this:
```
namespace fmt
{
template <typename ArgFormatter>
void format_arg(BasicFormatter<char, ArgFormatter> &f,
                const char *&format_str, const cv::Mat &m)
{
  format_str += 2; // skip past {}, is this right?
  f.writer().write("cv::Mat({}x{},{}ch)", m.cols, m.rows, m.channels());
}
}
```
which works for me, but I don't know if this is the best way to do it. What's the right way to handle `format_str`?  An example of this style would be very useful.

(I can't use the `ostream operator<<` method because the class in question already has one which isn't appropriate for my purposes.)

**Comment by gabime** [comment]
Please try asking in the fmt lib repository.
