### ISSUE TITLE
spdlog silently skips logs (but successfully compiles) when trying to hex-format `std::string` or `char*`

### ISSUE THREAD

**Issue by blakehawkins** [gabime/spdlog#614]
There are various format strings that will raise compiler errors, like:

`{:x}` with `reinterpret_cast<int*>(&std::string[0])`
`{:x}` with `reinterpret_cast<const int*>(std::string.data())`

But there are at least a couple that will *not* raise compiler errors, but exhibit a bug wherein the log is not at all displayed, like:

`{:x}` with `std::string`
`{:x}` with `std::string.data()`

Clearly, `{:x}` is not intended for use with pointers, but a lack of compiler error makes this unclear.

**Comment by gabime** [comment]
Thanks for reporting. 
I think it should be reporetd in the [fmt lib](https://github.com/fmtlib/fmt) project that implements those features.

**Comment by vitaut** [comment]
Compile-time format string checks (http://zverovich.net/2017/11/05/compile-time-format-strings.html) have been recently added to the `std` branch of the fmt library and haven't been released yet. They'll be available in the next major release.

**Comment by blakehawkins** [comment]
@gabime as discussed in https://github.com/fmtlib/fmt/issues/670 , fmtlib should raise this as an exception. If you think spdlog is not swallowing them, then I should probably investigate. Care to comment?

**Comment by gabime** [comment]
spdlog swallows logging exceptions(including fmt’s formatting errors), and by default, prints them to stderr. 

It only throws if logger constructing fails or upon un excpected exceptions (those that do not inherit from std::exception and thus cannot be caught safely).

This behaviour can be customized using the set_error_handler(..) function.
