### ISSUE TITLE
There is no output in console for debug

### ISSUE THREAD

**Issue by definename** [gabime/spdlog#618]
Hi all,
There is my sample code:

```
#include "spdlog/spdlog.h"

int main(int argc, char* argv[])
{
    try
    {
        std::shared_ptr<spdlog::logger> console = spdlog::stdout_color_mt("console");
        console->info("Hello info spdlog");
        console->debug("Hello debug spdlog");
    }
    catch (const spdlog::spdlog_ex& e)
    {
        std::cerr << "spdlog error occurred: " << e.what() << std::endl;
    }
    catch (const std::exception& e)
    {
        std::cout << "error occurred: " << e.what() << std::endl;
    }

    return 0;
}
```
And there is my output for that sample code
![out](https://user-images.githubusercontent.com/9870947/35164150-f6dd7bea-fd51-11e7-97b1-9fc6df1754b2.jpg)

As you can see there is not debug record in console. Could you point me what I need to do to see it in console?

**Comment by gabime** [comment]
You need to set the log level to debug (“set_level(level::debug)”) to see debug messages.

**Comment by definename** [comment]
Way is log level like `debug, trace` turned off?

**Comment by godbyk** [comment]
To reduce the amount of log messages emitted. Most end users don't need to see debug- and trace-level log messages, only info and above.

**Comment by definename** [comment]
In order to turn them on we need to add `level::debug` and `level::trace` to our logger?

**Comment by definename** [comment]
Thanks.
