### ISSUE TITLE
MacOS rotating_file_sink generates file errors

### ISSUE THREAD

**Issue by kebiao** [gabime/spdlog#620]
class rotating_file_sink SPDLOG_FINAL : public base_sink < Mutex >: 

    // calc filename according to index and file extension if exists.
    // e.g. calc_filename("logs/mylog.txt, 3) => "logs/mylog.3.txt".
    static filename_t calc_filename(const filename_t& filename, std::size_t index)
    {
        std::conditional<std::is_same<filename_t::value_type, char>::value, fmt::MemoryWriter, fmt::WMemoryWriter>::type w;
        if (index)
        {
            filename_t basename, ext;
            std::tie(basename, ext) = details::file_helper::split_by_extenstion(filename);
            w.write(SPDLOG_FILENAME_T("{}.{}{}"), basename, index, ext);
        }
        else
        {
            w.write(SPDLOG_FILENAME_T("{}"), filename);
            printf("---------%s-----%s\n",filename.c_str(),w.str().c_str());
        }
        return w.str();
    }

test.cpp:

		std::vector<spdlog::sink_ptr> sinks;

		spdlog::set_async_mode(32768);

                 sinks.push_back(std::make_shared<spdlog::sinks::rotating_file_sink_mt>
                            ("logs/mylog.txt", 1 * 1024L * 1024, 1));
            
		logger_ = std::make_shared<spdlog::logger>("both", begin(sinks), end(sinks));
		spdlog::register_logger(logger_);

		logger_->set_level(spdlog::level::err);
		logger_->set_pattern("*** [%Y-%m-%d %H:%M:%S %z] [thread %t] %v");
		logger_->flush_on(spdlog::level::err);

-------------------------------------------------------------------------------------------------

kbedeMBP:bin kbe$ ./test 
---------logs/mylog.txt------nan
kbedeMBP:bin kbe$ ls
-nan	logs	test
kbedeMBP:bin kbe$ ls logs
kbedeMBP:bin kbe$

**Comment by kebiao** [comment]
Version 0.16.3

**Comment by kebiao** [comment]
Windows test is correct

**Comment by gabime** [comment]
What are the errors exactly?

**Comment by kebiao** [comment]
sinks.push_back(std::make_shared<spdlog::sinks::rotating_file_sink_mt>
                        ("logs/mylog.txt", 1 * 1024L * 1024, 1));

The result of the calc_filename function in macOS is：   “-nan“

**Comment by gabime** [comment]
Could you debug more and see what exactly causes it?

anyway you are creating a sync logger by mistake. 
The code should be:
```c++
logger_ = std::make_shared<spdlog::async_logger>(..)
```

**Comment by kebiao** [comment]
fmt::MemoryWriter w;   
         w.write(SPDLOG_FILENAME_T("{}"), filename);
         printf("---------%s-----%s\n",filename.c_str(),w.str().c_str());

================================
kbedeMBP:bin kbe$ ./test
---------logs/mylog.txt------nan

Cppformat bug?

**Comment by kebiao** [comment]
kbedeMBP:bin kbe$ more /System/Library/CoreServices/SystemVersion.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>ProductBuildVersion</key>
        <string>17C205</string>
        <key>ProductCopyright</key>
        <string>1983-2018 Apple Inc.</string>
        <key>ProductName</key>
        <string>Mac OS X</string>
        <key>ProductUserVisibleVersion</key>
        <string>10.13.2</string>
        <key>ProductVersion</key>
        <string>10.13.2</string>
</dict>
</plist>

**Comment by gabime** [comment]
Strange.. Do you define  SPDLOG_WCHAR_FILENAMES ?

**Comment by kebiao** [comment]
No definition of SPDLOG_WCHAR_FILENAMES .

**Comment by gabime** [comment]
Works fine in Mac OS 10.11.6
