### ISSUE TITLE
travis-ci unit tests

### ISSUE THREAD

**Issue by ido** [gabime/spdlog#63]
@gabime:
Would you consider writing some unit/regression tests and a `.travis.yml` file so that they run on each git push?  I had to fix a few minor bugs last time I did a `git subtree pull`.  I'd especially like to see the `bench` program run on each `git push` on travis-ci so we can easily see if a commit introduces any performance regressions.

Here is an example C++11 project `.travis.yml` file you could base yours off of, if you've never used travis-ci before, it's super straightforward to get started:
https://github.com/zaphoyd/websocketpp/blob/master/.travis.yml

I do not have time to do this myself right now or I'd submit this as a pull request.  If I have time this summer, I'll add some performance/unit tests as well, but maybe you could start with lightly modified versions of the example or bench programs that output the max message rate/sec, time to log 1,000,000 entries with each of the various logging methods (sync st file, async mt file, async st file, etc.)?  Then move on to unit tests of the public API?

If you don't have time, thanks again for taking your time to write this library in the first place. :-)

**Comment by gabime** [comment]
Why modify the output? It already provides most of needed info..

**Comment by ido** [comment]
No need to modify the output.  

Just set it up to build and run with gcc, clang, and any other compilers you want.  Don't forget to add any relevant compile/linker flags to your build matrix.  Good luck! :-)

**Comment by gnzlbg** [comment]
Here is range-v3's travis-ci script: https://github.com/ericniebler/range-v3/blob/master/.travis.yml

It is really useful to have travis ci because it tests pull-requests automatically with all the compilers you want and makes sure that at least whats tested doesn't break on any platform.

By default you get linux + clang-3.4 ... clang-3.7, and gcc 4.9, with both libc++ and libstdc++. 
You can also apply for macos build bots to test latest AppleClang + libc++.

**Comment by gnzlbg** [comment]
Setting this up takes half an hour and would have prevented issue #94 .

**Comment by gabime** [comment]
Right. I never had the time to get to it, Would really appreciate a pull

**Comment by gnzlbg** [comment]
A pull-request is coming, it would be helpful if you registered on https://travis-ci.org and enabled testing for your project :)

**Comment by gabime** [comment]
OK. Will do

**Comment by gnzlbg** [comment]
How do you choose in the examples between Debug and Release builds?

**Comment by gabime** [comment]
```make debug``` vs ```make```

**Comment by gabime** [comment]
I registered. Please tell me if you need anything else

**Comment by gnzlbg** [comment]
So i've sent you a pull-request with an sketch about how a travis configuration looks like. 
I'd appreciate if you could take a look at the configuration file, which is not nice but not too long either.

**Comment by gnzlbg** [comment]
So the travis tests in my branch seem to be running all fine. 
However, I cannot send you anymore pull-requests until you fixed up your history (you have duplicated commits and what not, and these will get triplicated if you merge any more pull-request from my branch).

I think the best thing you can do is:
- rebase -i on master and clean the history
- `push --force` and hope nobody besides me has an uptodate fork
- manually diff the stuff from my branch and apply a patch to your master

My branch is here: https://github.com/gnzlbg/spdlog/tree/travis

**Comment by gabime** [comment]
Maybe it would be easier if you just send me the travis file and I commit it to master. As far as I understand this is the only modifcation

**Comment by gabime** [comment]
Travis tests up and running fine. Thanks to @gnzlbg
