### ISSUE TITLE
___guard_check_icall_fptr was 0x1110126.

### ISSUE THREAD

**Issue by mq1n** [gabime/spdlog#633]
Exception thrown: read access violation.

___guard_check_icall_fptr was 0x1110126.

Sometimes gives this error and crashes.

I've created a simple wrapper; https://hastebin.com/putifusani.cpp Works fine but as far as I said something this problem is occurring.

Here is a example crash stack;
https://vgy.me/mptihO.png
https://vgy.me/U8cbhE.png
https://vgy.me/o344uq.png
https://vgy.me/QbM6pH.png
https://vgy.me/fTrdZj.png

**Comment by gabime** [comment]
looks related to tls.. what compiler and os versions are you using?

**Comment by mq1n** [comment]
Visual studio 2017 with v141_xp toolset and Windows 10 build 15063

**Comment by gabime** [comment]
Pleasetry to uncomment SPDLOG_DISABLE_TID_CACHING in tweakme.h - Lets try to see if it is really related to thread local storage.

**Comment by mq1n** [comment]
now it works fine

**Comment by gabime** [comment]
seems a winxp build issue only
