### ISSUE TITLE
find_package(spdlog) is not working

### ISSUE THREAD

**Issue by ezamelczyk** [gabime/spdlog#636]
I installed it with `brew install spdlog` and typed in my CMakeLists.txt `find_package(spdlog CONFIG REQUIRED)` but it doesn't find it.

I get this error message
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.13.0 -o untitled -search_paths_first -headerpad_max_install_names CMakeFiles/untitled.dir/src/main.cpp.o CMakeFiles/untitled.dir/src/Logger.cpp.o -lspdlog -lc++ -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
ld: library not found for -lspdlog
```

**Comment by ezamelczyk** [comment]
Nevermind it was a simple mistake. You can close it.

**Comment by dyanikoglu** [comment]
> Nevermind it was a simple mistake. You can close it.

Maybe also share the solution?

**Comment by ezamelczyk** [comment]
Aww jeez... Sorry for that lackluster answer. I know how frustrating it can be. Unfortunately I don't remember what was the problem anymore :c

**Comment by PiotrDabkowski** [comment]
I think `target_link_libraries(xxx spdlog)` is not needed for header-only libraries. Removing it fixes the issue. So all you need is `find_package(spdlog REQUIRED)`
