### ISSUE TITLE
Compile Instructions?

### ISSUE THREAD

**Issue by avilyn** [gabime/spdlog#639]
New to C++ development. I like the looks of this library for doing my application logging, but am not able to make it work with the existing instructions.

I've installed libspdlog-dev (1.6-1) on my Ubuntu 16.04 vm.

    #include <cstdlib>
    #include "spdlog/spdlog.h"

    namespace spd = spdlog;
    int main () {
      auto application_logger = spd::basic_logger_mt("basic_logger", "application.log");
      application_logger->info("Initializing");
      exit(0);
    }

Running `g++ main.cpp -std=c++11` gives the following error.

    main.cpp: In function ‘int main()’:
    main.cpp:6:29: error: ‘basic_logger_mt’ is not a member of ‘spd’
       auto application_logger = spd::basic_logger_mt("basic_logger", "/vargrant/logs/application.log");
                                 ^

I assume I need to specify something additional, but I don't see any documentation. Can someone point me in the right direction (or better yet, add additional documentation)?

**Comment by gabime** [comment]
The problem is that this is a very old version. Try upgrading to  a newer version
