### ISSUE TITLE
clang build fails due to `details/format.h` diagnostic pop without prior push

### ISSUE THREAD

**Issue by ido** [gabime/spdlog#64]
-Werror says:

There is an errant `#pragma clang diagnostic pop` at the end of `details/format.h` because you are missing a `clang diagnostic push` before line 105 of that file.

**Comment by vitaut** [comment]
Fixed in [C++ Format](https://github.com/cppformat/cppformat): https://github.com/cppformat/cppformat/commit/b9f4668855e7b957adf97636e73f95e526d9733d, but the fix needs to be propagated to the spdlog's copy of `format.h`. Thanks for catching this, @ido.

**Comment by gabime** [comment]
Fixed in 6fe03c778066b98193fdcf90bb7a5e34438692bc
Thanks @vitaut and @ido
