### ISSUE TITLE
Fatal error: spdlog/fmt/ostr.h

### ISSUE THREAD

**Issue by studident** [gabime/spdlog#640]
Hi,
I'm trying to build a Sailfish library using Cmake. Somehow it gives me this fatal error:

`In file included from /usr/tools/SailfishBeta-0.7.6_Linux-x86-64/bin/sailfish/src/SailfishIndexer.cpp:60:0:
/usr/tools/SailfishBeta-0.7.6_Linux-x86-64/bin/sailfish/external/install/include/rapmap/RapMapSAIndex.hpp:31:29: fatal error: spdlog/fmt/ostr.h: No such file or directory
`

Where exactly does this file or directory have to be?

Best,
Steve

**Comment by studident** [comment]
Thanks Charles,

by installing you mean copying the spdlog folder into my build tree?

**Comment by CharlesB2** [comment]
Yes, you can do this, it should work.
You can also install fmtlib and `#define SPDLOG_FMT_EXTERNAL 1` before including spdlog files.
