### ISSUE TITLE
Color log with color just on %i

### ISSUE THREAD

**Issue by psalvaggio** [gabime/spdlog#641]
I am working on converting from Boost::Log to spdlog, which has gone very well, but I'm a bit stuck on this last item. I find the log messages to be a bit tough to read with the whole line being a different color, I'd really like to be able to just confine the color to the log level that I put into my log prefix with a "%i". So far, the only way I can think to do it is look for raw message in the formatted message and then search for the various levels "info", "debug", etc. inside of the log prefix. Is there a cleaner way to do this? Doing a bunch of string searches for every log message doesn't seem like a great option.

**Comment by gabime** [comment]
It has been bothering me too lately, but I didnt find an efficient nor clean way to achieve this.

**Comment by psalvaggio** [comment]
Yeah if I settled for the whole prefix being colored, there was a 99% solution with 1 string search per message, but I think I'm just going to customize each level's colors to mitigate the readability issues. Not ideal, but I can live with it.

**Comment by psalvaggio** [comment]
Awesome! I'll be sure to try it out.

**Comment by gabime** [comment]
You can customize the colored range using the %^ (start color) and the %$(end color).

For example:
```c++
logger->set_pattern(“a colored %^date %x....%$  %v”);
```
