### ISSUE TITLE
tweakme.h is only included by spdlog.h

### ISSUE THREAD

**Issue by boimart1** [gabime/spdlog#645]
When tweakme.h is used, only Translation Units that include `<spdlog/spdlog.h>` will get the appropriate definitions.

This is a minor inconvenience for users when including bits-and-pieces of spdlog. In my case, a situation like this turned up:

```
// file_a.h
#include <spdlog/common.h>  // for spdlog::level
// SPDLOG_WCHAR_FILENAMES not defined, filename_t = std::string

// file_b.h
#include "file_a.h"
#include <spdlog/spdlog.h>
// includes tweakme: defines SPDLOG_WCHAR_FILENAMES
// includes logger -> base_sink -> sink -> log_msg -> os.h
// vendors\spdlog\0.16.3\include\spdlog\details\os.h(175) : error C2664: 'FILE *_wfsopen(const wchar_t *,const wchar_t *,int)' : cannot convert argument 1 from 'const char *' to 'const wchar_t *'
```

The user is required to write `#include <spdlog/tweakme.h>` before any other spdlog include, which isn't that big of a deal but it's still an annoyance and easy to forget.

It would make sense to either include tweakme at the beginning of common.h (I believe this is always the first include in every other file?), or include tweakme at the beginning of every single file in spdlog.

**Comment by gabime** [comment]
Agreed. Fixed in commit 051048ebd728fe8623b2970232969bd30606855c
