### ISSUE TITLE
Issue of authority

### ISSUE THREAD

**Issue by daoqiang** [gabime/spdlog#648]
My use scene is very special, spdlog default permissions can not create files and create folders。
How should I modify it
My working environment is window

**Comment by gabime** [comment]
If you dont have permissions to files - where to you want to log to?

**Comment by daoqiang** [comment]
I describe inaccuracy，You need to create a file in this way through 
CreateFile(lpFileName, dwAccess, FILE_SHARE_READ | FILE_SHARE_WRITE,
			NULL, dwCreationFlags, FILE_ATTRIBUTE_NORMAL, NULL)
The default creation file mode of Spdlog cannot be created

**Comment by gabime** [comment]
> I can't work with spdlog in DLL 

What's the error message you get (spdlog should throw)?

**Comment by daoqiang** [comment]
in initterm.cpp
extern "C" void __cdecl _initterm(_PVFV* const first, _PVFV* const last)
{
    for (_PVFV* it = first; it != last; ++it)
    {
        if (*it == nullptr)
            continue;

        (**it)();
    }
}

By debugging, I found that the program will go around this place, and if I continue to follow the F5, I will report the exception
An exception that is caused by 0x004A764F: an access conflict occurs when the 0xC0000005: reads the location 0x00000000.
