### ISSUE TITLE
replace SPDLOG_DEBUG/TRACE macro from  force_log to log

### ISSUE THREAD

**Issue by theambient** [gabime/spdlog#65]
because it is impossible to handle log level runtime otherwise.

**Comment by gabime** [comment]
Log levels can be set at runtime..
The idea is that the DEBUG/TRACE macros will always appear if SPDLOG_DEBUG_ON  is defined, no matter the actual level.

**Comment by theambient** [comment]
I understand you idea but it seems to be inconvenient, cause you specify at runtime, say, just error level, but accidentally see debug or trace log.

Also it would be nice to have such macros for all log levels forwarding log place (file, line) to actual log function.

I can prepare patch, but i need your decision on this subject.

**Comment by gabime** [comment]
Ok. Lets try those suggestions. Pull would be nice.

**Comment by gabime** [comment]
Fixed in 9603c2a20cc1f7356e9bcd250ba466a9c0842a6d
