### ISSUE TITLE
VS2017 Conformance

### ISSUE THREAD

**Issue by sraboy** [gabime/spdlog#657]
There is an issue using wide chars on VS2017 due to [improved conformance](https://blogs.msdn.microsoft.com/vcblog/2017/09/11/two-phase-name-lookup-support-comes-to-msvc/) with two-phase name lookups in templates. 

I'm not sure if there are similar issues elsewhere but in order to use `wstring` and `wchar_t` parameters, I had to add `typename` to [logger_impl.h@222](https://github.com/gabime/spdlog/blob/e8a39c894ffbb3e03328278e4be7a106a31a433e/include/spdlog/details/logger_impl.h#L222). My line now reads: `typename fmt::WMemoryWriter wWriter;`.

**Comment by cstratopoulos** [comment]
Was going to report this same issue but just saw that you had already done so!

I am going to apply the same workaround for now, but would you (or anyone else) care to weigh in on whether this might be an MSVC bug?

I receive error C7510: 
```
'WMemoryWriter': use of dependent type name must be prefixed with 'typename'
```

However as per, e.g., [here](http://en.cppreference.com/w/cpp/language/dependent_name), it seems that `WMemoryWriter` is _not_ a dependent name in this context: the only template parameter in the function is the variadic `Args...`, and `WMemoryWriter` is not a template class or template alias, hence cannot in any way depend on `Args...`.

**Comment by sraboy** [comment]
I should also mention that I'm compiling for C++17. 

Maybe it's referring to `Char`, but the error doesn't come up on `MemoryWriter` with narrow chars... haven't really dug in to see if there's a difference in the definitions. I couldn't understand what it meant about the dependent name either... took me a while to decide to just throw `typename` in there and give a try.

**Comment by sraboy** [comment]
Reading more of the article I linked in the original post, I think it matches this known issue:

> 4. Non-type dependent expressions involving local declarations aren’t analyzed correctly. The MSVC compiler currently parses the type as dependent causing an incorrect error.
