### ISSUE TITLE
I use external fmt lib,and #define SPDLOG_FMT_EXTERNAL,some error reported:

### ISSUE THREAD

**Issue by snowzjy** [gabime/spdlog#658]
I use external mft lib,and #define SPDLOG_FMT_EXTERNAL like this:

#include <fmt/format.h>
#include "fmt/time.h"
#define SPDLOG_FMT_EXTERNAL
#include "spdlog/spdlog.h"

but when compile my project,some error reported:

/home/zjy/program/spdlog/include/spdlog/sinks/../details/log_msg.h:39:10: error: ‘MemoryWriter’ in namespace ‘fmt’ does not name a type
     fmt::MemoryWriter raw;
          ^~~~~~~~~~~~
/home/zjy/program/spdlog/include/spdlog/sinks/../details/log_msg.h:40:10: error: ‘MemoryWriter’ in namespace ‘fmt’ does not name a type
     fmt::MemoryWriter formatted;
          ^~~~~~~~~~~~
/home/zjy/program/spdlog/include/spdlog/sinks/../details/pattern_formatter_impl.h: In member function ‘virtual void spdlog::details::name_formatter::format(spdlog::details::log_msg&, const tm&)’:
/home/zjy/program/spdlog/include/spdlog/sinks/../details/pattern_formatter_impl.h:38:13: error: ‘struct spdlog::details::log_msg’ has no member named ‘formatted’
         msg.formatted << *msg.logger_name;

**Comment by gabime** [comment]
Try removing the include ```#include <fmt/format.h>``` - spdlog already includes it
a

**Comment by snowzjy** [comment]
I removed the include #include <fmt/format.h>. The errors still occur

**Comment by gabime** [comment]
Try to remove also the "#include "fmt/time.h"

**Comment by snowzjy** [comment]
I changed the code like this:
//#include <fmt/format.h>
#include "fmt/time.h"
#define SPDLOG_FMT_EXTERNAL
#define FMT_HEADER_ONLY
#include "spdlog/spdlog.h"

But the errors still occur,I don't know why

**Comment by DanielChabrowski** [comment]
Download fmt-4.1.0. MemoryWriter no longer exists on master branch.

From what I see, that's the current, "master", way to write to memory_buffers:
```
fmt::basic_memory_buffer<Char> buffer;
typedef fmt::back_insert_range<fmt::internal::basic_buffer<Char>> range;
fmt::basic_writer<range> writer(buffer);
writer.write(value);
```
