### ISSUE TITLE
heap profile points to spdlog

### ISSUE THREAD

**Issue by wjackson** [gabime/spdlog#659]
Hi,

When looking at large memory usage for [Envoy](https://www.envoyproxy.io/) which uses spdlog I got this heap profile:

```
$ pprof --text envoy-bin ./sidecar_heap_profile.0226.heap
Using local file envoy-bin.
Using local file ./sidecar_heap_profile.0226.heap.
Total: 6482.4 MB
  6482.4 100.0% 100.0%   6482.4 100.0% spdlog::details::os::thread_id::tid
     0.0   0.0% 100.0%      0.0   0.0% allocate_dtv
     0.0   0.0% 100.0%      0.0   0.0% __new_exitfn
     0.0   0.0% 100.0%      0.0   0.0% __cxa_thread_atexit_impl
     0.0   0.0% 100.0%      0.0   0.0% __GI___strdup
     0.0   0.0% 100.0%      0.0   0.0% __GI___pthread_once
     0.0   0.0% 100.0%      0.8   0.0% __libc_start_main
     0.0   0.0% 100.0%   6481.2 100.0% start_thread
```

I posted about this on the Envoy users group and got the suggestion to post here too. Here's the Envoy post that has more details: https://groups.google.com/forum/#!topic/envoy-users/etHAqrDDRjE

Would appreciate any insights you might have.

**Comment by gabime** [comment]
strange.. maybe your old  platform doesnt support thread local storage well?
Please try defining SPDLOG_DISABLE_TID_CACHING before including spdlog.h (or uncmment  it in teakme.h) and see if it helps after recompiling.

**Comment by gabime** [comment]
@wjackson Any news about before I close it?

**Comment by wjackson** [comment]
I'll close. From what I can piece together so far it looks like this heap profile is misleading. I got similar behavior from an Envoy build specifically for my OS but a very different heap profile.

Thanks for the advice.
