### ISSUE TITLE
Request - daily log with rotation

### ISSUE THREAD

**Issue by kiranpradeep** [gabime/spdlog#661]
Currently daily logs cannot be rotated. Is it possible to have an option to do that?

**Comment by xann16** [comment]
Hi,

I had similar need and adjusted 'daily_file_sink' to allow log rotation (by simply deleting outdated files while creating new one - so once a day). I used 'boost/filesystem' as I had it in my project's dependencies anyway, but if there is enough need in community and support from maintainers, I'd be glad to write more native version (at least for Unix and Windows) to be added to the project.

Please contact me here or by PM/mail, if You would like my current quick changes (boost dependent), or interested in permanent contribution.

**Comment by gabime** [comment]
Implemented. Now users can pass max_files arg to the sink constructor (pass 0 to disable rotating).
