### ISSUE TITLE
lines with red background after critical logs when using stdout_sink/stderr_sink with colors

### ISSUE THREAD

**Issue by rhymerjr** [gabime/spdlog#670]
Hi!

I started using this lib a few days ago and it is really great!
I have found that there are red backgrounds in the next line after each critical logs when using in console mode!

![extra_red](https://user-images.githubusercontent.com/20098067/37966236-24b7aab8-31c8-11e8-9afc-2a96e7abd3ee.PNG)

Is it possible to prevent second red backgrounded lines after a critical message?

**Comment by gabime** [comment]
I need to fix it. Its a known bug

**Comment by rhymerjr** [comment]
Waiting for that!
Thanks for letting me know!

**Comment by gabime** [comment]
Fixed in latest commit (now you can use the %^ and %$ to mark start/end color range!
