### ISSUE TITLE
"Failed to open file" using multisink feature

### ISSUE THREAD

**Issue by Frank667** [gabime/spdlog#671]
I have the following code to initialize my logging for a dll used at systemstart:

```
std::vector<spdlog::sink_ptr> sinks;
sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_mt>());
auto traceSink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(logpath + "trace.log", 1024 * 1024, 5);
traceSink->set_level(spdlog::level::trace);
sinks.push_back(traceSink);
auto debugSink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(logpath + "debug.log", 1024 * 1024, 5);
debugSink->set_level(spdlog::level::debug);
sinks.push_back(debugSink);
auto infoSink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(logpath + "info.log", 1024 * 1024, 5);
infoSink->set_level(spdlog::level::info);
sinks.push_back(infoSink);

auto ksp_logger = std::make_shared<spdlog::logger>("ksp", sinks.begin(), sinks.end());
ksp_logger->set_level(spdlog::level::trace);
register_logger(ksp_logger);
auto handler_logger = std::make_shared<spdlog::logger>("handler", sinks.begin(), sinks.end());
handler_logger->set_level(spdlog::level::trace);
register_logger(handler_logger);
auto client_logger = std::make_shared<spdlog::logger>("client", sinks.begin(), sinks.end());
client_logger->set_level(spdlog::level::trace);
register_logger(client_logger);
```

After that I retrieve the loggers with (for example) `spdlog::get("client")` (only once per logger and store it).

Now a few lines are logged in trace.log but all of a sudden the exe calling my dll crashes. Examining the dump I found out that file_helper.h seems to be unable to open a file (unfortunately I cannot see which of the files), though it wrote things up to this point into the trace.log. All files have been created but debug.log and info.log are empty, even if there are debug and info entries in the trace.log. So I think there is something wrong with the multisink feature.

By the way: I am using the same code to initialize the logging in another dll where it seems to work without any problems.

**Comment by gabime** [comment]
> All files have been created but debug.log and info.log are empty, even if there are debug and info entries in the trace.log. So I think there is something wrong with the multisink feature.

Try lowering the flush level to see immediatly debug or trace messages (‘logger-> flush_on(spdlog::level::trace);’ - this comes on the expense of performance of course).
> By the way: I am using the same code to initialize the logging in another dll where it seems to work without any problems.

Maybe this is the problem? you create 2 sinks with same file name? Seems that the open fails brcause it is already open by other sink.

**Comment by Frank667** [comment]
Thank you for the fast reply. The flushing helped to have things written to the other logs, too.
However the crash still happens. This time without creating a dump, but the error in the eventlog looks the same. Unfortunately I cannot debug the code, as it is used by Windows LogonUI before I am logged in. :-(
Perhaps there is too much output to process in to little time? I will try to change the settings for opening the file and see if this makes a difference.

Regarding the second point: Sorry, for not being clear enough, but the other dll uses other logfiles.

**Comment by gabime** [comment]
Anyway it should not crash. The code need to surround the sinks creation with try/catch and print the error.

**Comment by Frank667** [comment]
The sinks are created and the first few lines (~90) are logged pretty well, but then the file_helper fails to open the file. To verifiy this I added the following quick&dirty hack to the file_helper:
```
std::ofstream errorLog;
errorLog.open("C:\\tmp\\spdlog_error.txt");
errorLog << "Failed opening file " + os::filename_to_str(_filename) + " for writing";
errorLog.close();
```
This tells me that the trace.log cannot be opened, though just a few milliseconds before some entries were written to exactly the same file.

**Comment by gabime** [comment]
@Frank667 How would you use CreateFile() ? with which flags?

**Comment by tuket** [comment]
I'm having the same problem
