### ISSUE TITLE
Bad access exception

### ISSUE THREAD

**Issue by grcasanova** [gabime/spdlog#672]
Hello,
I am trying to wrap spdlog in an Interface class, in order to easily switch from syslog to spdlog.
I set the class variables and functions to be static so that the Logger contains one single 
`        static std::shared_ptr<spdlog::logger> m_logger;
`
pointer to spdlog.

However, whenever logging, a thread Bad Access Exception is thrown. Is it something related to concurrent access/mutexes?
```

void Logger::init()
    {        
        try
        {
            // Set the logger as rotating and asyncronous
            m_logger = spd::rotating_logger_mt(DEFAULT_LOG_NAME, LOGFILE_PATH, MAX_LOGFILE_SIZE, LOGFILES_N);
            spd::set_pattern("*** [%H:%M:%S %z] [thread %t] %v ***");

            // Full queue policy: Discard the message and never block
            spd::set_async_mode(QUEUE_SIZE, spd::async_overflow_policy::discard_log_msg);
            
            // Set custom error handler
            spd::set_error_handler([](const std::string& msg) {
                throw std::runtime_error(msg);
            });
            
            // Initialisation was successful
            m_initialised = true;
        }
        catch (const spd::spdlog_ex& ex)
        {
            m_initialised = false;
        }
    }

void Logger::critical(const char *msg)
    {
        if(!m_initialised) { return; }
        
        m_logger->error(msg);
    }
```

**Comment by gabime** [comment]
Hi, 

I am not sure why the crash, but you must call “set_async_mode” *before* creating any loggers. 

Also, throwing in the error handler is  bad idea in async mode - the exception would be thrown from the worker thread without any way to catch.

**Comment by grcasanova** [comment]
Yes, apparently it was the custom error handler causing the issue.

Do you have any self-test to check wether files are created or not? Because I don't see any file created, but logs are reported correctly when switching to console view?
Thank you

**Comment by gabime** [comment]
The recommended way is to catch the exception around logger constructing. If no exception thrown then the file was created ok.
