### ISSUE TITLE
Is it possible to send additional parameters to sinks? 

### ISSUE THREAD

**Issue by mersadk** [gabime/spdlog#673]
I'm creating custom sink that will send logs to Graylog. I would like to pass object with current program state to logger, so that it can be sent to Graylog as custom fields and not as part of a message. 
Is that possible with spdlog?

**Comment by Oleg26Dev** [comment]
Great idea!
Are you going to make this sink public?

**Comment by mersadk** [comment]
@Oleg26Dev Yes, I'll try to find time in next few days to upload it to GitHub.

**Comment by Oleg26Dev** [comment]
Ok, thnx, waiting.

**Comment by lion10243** [comment]
@mersadk @Oleg26Dev  perhaps this might be of interest on this point, I have a branch of spdlog with a feature allowing a map of key-val custom fields types to be logged with every message, which we are already using in our production code.

**Comment by lion10243** [comment]
@mersadk You'll need the code from master branch here: https://github.com/lion10243/spdlog
The spdlog::get()->log() methods take as first argument an attributes_type map. Real world example:

spdlog::attributes_type ma {
        {"search_id", q->api_search_id()},
        {"uuid", q->uuid()},
        //{"shop", q->shop_name()},
        {"market", q->market().Name},
        {"partner", q->partner().Name},
    };
    spdlog::get("shop")->info(ma, fmt, args...);

Then inside the logging sink you can access the attribute values and do someting with them:

auto iter = msg.attrs.find("market");
if (iter != msg.attrs.end()) {
    jrec["market"] = spdlog::attrval::get<std::string>( iter->second );
}

We use FluentD/Td-Agent and Kibana, and the log attributes are used by the sink to write extra json data fields alongside the log message, log severity level etc.

**Comment by PuneetPatwari** [comment]
Hi @gabime , are you going to support custom attributes in addition to the defaults? It will be really powerful feature in your already powerful library.

**Comment by gabime** [comment]
@PuneetPatwari Not sure yet.
