### ISSUE TITLE
Add sink to logger on the fly

### ISSUE THREAD

**Issue by arnonshp** [gabime/spdlog#674]
Hi,

I have a use case where logging is usually done to the screen however a user may choose to add logging to a file. So the original logger is instantiated with only one sink (to screen). I need to add another sink later on which will dump to file. Is there a way to add a sink to a logger after it has been created? 
If not, I thought of adding a file sink in advance and turn it off, and then turn it on only when the user chooses to dump to file. However, the file name is given to the sink on its creation and I couldn't find a way to change it on the fly. 
So I'd be fine with either of those 2 options:
1. Adding a sink on the fly, after the logger is created.
2. Change the file name of a file sink, after the sink is created.

Is there a way to do any of the above? Or those would be new enhancements?

Thanks,
arnoshp

**Comment by godbyk** [comment]
There's not currently a method for adding a sink after the logger has been constructed, but I don't see any reason why one couldn't be added.

**Comment by gabime** [comment]
The reason there is now such way is that thread safety cannot be achieved without surrounding the sinks vector with mutex in each access (i.e on each log call) - a price I thought was too high for this feature.

spdlog  could provide  a non thread safe way though.. And document that it is should not be used concurrently..

**Comment by arnonshp** [comment]
A non-thread safe way will be fine for my use case as I do not expect sinks to be added while the logger is actively logging messages.

**Comment by rhd** [comment]
Does [dist_sink.h](https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/dist_sink.h) cover this usecase?

**Comment by Xottab-DUTY** [comment]
> Does dist_sink.h cover this usecase?

Probably yes, but you need to store the pointer for it somewhere.

Another way is to use const_cast for sinks vector
![image](https://user-images.githubusercontent.com/2989212/42565436-dbbe2fdc-851c-11e8-8296-6ca8b203fef0.png)

**Comment by Broekman** [comment]
Simply adding a push_back(sink_ptr) function in logger.h/logger_impl.h should do the trick if you only use it during initialization. Correct me if I'm wrong. Been using this in a multithreaded environment for a while now and did not run into any problems.

**Comment by Xottab-DUTY** [comment]
@gabime was this fixed? Or what method do you recommend to use?

**Comment by Broekman** [comment]
@Xottab-DUTY, as of version 1.1.0 there is a function returning a  non-const reference to the sinks vector, allowing you to manually push back sinks. I'm not sure if it's wise to use this in a multi-threaded environment but as long as you only use it during initialization, it should be fine.

```
inline std::vector<spdlog::sink_ptr> &spdlog::logger::sinks()
{
    return sinks_;
}
```

**Comment by Xottab-DUTY** [comment]
@Broekman, ah, that's cool. Thank you =)

**Comment by gabime** [comment]
@Xottab-DUTY If you need to add sinks while other threads are already using the logger concurrently, dist_sink can be used.
