### ISSUE TITLE
log4j, log4net format ?

### ISSUE THREAD

**Issue by Oleg26Dev** [gabime/spdlog#676]
Is it possible to implement formatting like log4j, log4net?

**Comment by gabime** [comment]
what do you mean?

**Comment by Oleg26Dev** [comment]
I mean for example: I have .NET app uses log4net and I use some third party utilities to view log files or logs sent to network. These utilities know the log4j/log4net format. And I have asked: is it possible to use a formatter (which?) which can create records in log4j/log4net format?

**Comment by gabime** [comment]
Please refer to the docs about formatting. (set_pattern('..'))

**Comment by RolandMuenker** [comment]
I create a custom sink to send the messages via UDP.
I want to use the Log2Console tool for viewing the received UDP messages. The Log2Console viewer supports the log4J / log4net format. What is the proper format string for the method set_pattern?
