### ISSUE TITLE
Filename of currently active Logfile when rotating logs ?

### ISSUE THREAD

**Issue by mythos002** [gabime/spdlog#678]
Hi,

I have a question related to the time based log rotator. Is there some variable or function where I can read out the current active name of the Logfile from within the spdlog class, cause currently I'm forced to look at the filesystem itself which makes it a little bit awkward.

Would be nice if someone could give me a hint on this.

Thanks.

Greets,

Tommy

**Comment by gabime** [comment]
No, no direct way to get this. Sorry.

**Comment by mythos002** [comment]
Hi Gabi,

since you calculate the filename on rotation, wouldn't it be a good idea to have a simple string variable on the logger itself that holds that calculated name in it and gets rewritten on rotation with the new name ?

I mean you could than just ask the information after initialization with something like this:

auto l = spdlog::get("logger1");
std::string fname = l->filename;

This would be really helpful even for other purposes than mine.

**Comment by mythos002** [comment]
Ok,

I guess I would need to change stuff on the sink for this.

Since I currently don't have the time to take a look for this I'll stick with my external filesystem change function for the moment.

Thx anyways for the hint.
