### ISSUE TITLE
Error when building anything with spdlog

### ISSUE THREAD

**Issue by bmofa** [gabime/spdlog#682]
When trying to log anything with spdlog I get a ton of errors, even when all I'm doing is initializing the logger, without even doing anything.

```
1>------ Build started: Project: Silverware, Configuration: Debug Win32 ------
1>MySourceFile.cpp
1>format.obj : error LNK2005: "public: virtual __thiscall fmt::FormatError::~FormatError(void)" (??1FormatError@fmt@@UAE@XZ) already defined in MySourceFile.obj
1>format.obj : error LNK2005: "private: struct fmt::internal::Arg __thiscall fmt::internal::FormatterBase::do_get_arg(unsigned int,char const * &)" (?do_get_arg@FormatterBase@internal@fmt@@AAE?AUArg@23@IAAPBD@Z) already defined in MySourceFile.obj
1>format.obj : error LNK2005: "void __cdecl fmt::internal::report_unknown_type(char,char const *)" (?report_unknown_type@internal@fmt@@YAXDPBD@Z) already defined in MySourceFile.obj
1>C:\Users\bmoFA\source\repos\Silverware\Debug\MyProject.exe : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "MyProject.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I've spent a ton of time debugging this and looking at stuff and have come to the conclusion that I have no idea what's going on and I am either experiencing the rarest bug in the world or I'm just really dumb, most likely that latter.

Any help would be appreciated.

**Comment by Oleg26Dev** [comment]
What is your source code?

**Comment by bmofa** [comment]
Don't know what I did, but I fixed it :+1:

**Comment by spongebobcarre** [comment]
I've got the same problem, what did you do ?

**Comment by gabime** [comment]
Does your code include fmt.h directly? Try to define SPDLOG_FMT_EXTERNAL or include it only after spdlog.h was included.

**Comment by bmofa** [comment]
@spongebobcarre I don't have the actual code I was using anymore. But to solve it, I just re-setup spdlog and did some restructuring of what I was working on and it solved itself, no idea why or how but it did.

**Comment by code667** [comment]
I got the same issue,  #define SPDLOG_FMT_EXTERNAL  doesn't work.

I am using catch2 test framework.
There are multiple testcase, each testcase may include spdlog.h

**Comment by code667** [comment]
put #define SPDLOG_FMT_EXTERNAL on the top of the header file solve  the issue:

```
#ifndef XXX_H_
#define XXX_H_

#define SPDLOG_FMT_EXTERNAL
#include a.h
#include b.h
....
....
#include "spdlog/spdlog.h"
#include "spdlog/fmt/ostr.h"

```
