### ISSUE TITLE
each inclusion of spdlog/spdlog.h adds 6 seconds of compilation time

### ISSUE THREAD

**Issue by k-brac** [gabime/spdlog#685]
Everytime I include spdlog/spdlog.h in one of my .cpp file the time needed to compile my project takes 6 more seconds (in debug) even if I don't use it (just include)

I am using Visual studio 2017 15.6.6

**Comment by gabime** [comment]
hang on, I am working on new major release that improves it (among many other changes)

**Comment by k-brac** [comment]
Good to know!
I hope I'll be able to close this issue then!

**Comment by deblauwetom** [comment]
That would be awesome indeed

**Comment by abdes** [comment]
When is the new release coming?

**Comment by adioanca** [comment]
Hi,
We'd like to use spdlog in every file that we have, that's hundreds of files.
Compilation takes 6s for every file.
I've tried precompiled headers, and I've got this:
--------
adi@nodes:~/Logging$ ls include/ -l
[...]
-rw-rw-r-- 1 adi adi       219 oct 23 19:24 spdlog-precompiled.h
-rw-r--r-- 1 adi adi 129678128 oct 23 19:24 spdlog-precompiled.h.gch
adi@nodes:~/Logging$ cat include/spdlog-precompiled.h
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/sinks/stdout_sinks.h"
#include "spdlog/sinks/sqlite_sink.h"
#include "spdlog/sinks/zmq_sink.h"
#include "spdlog/sinks/dist_sink.h"
adi@nodes:~/Logging$ 
--------
Makefile:
spdlog-precompiled: include/spdlog-precompiled.h
	$(CXX) $(CXX_FLAGS) $(CXX_RELEASE_FLAGS) $(CXXFLAGS) include/spdlog-precompiled.h 
--------

That's 120+MB for spdlog-precompiled.h.gch, of course it takes a lot of time.

Does anyone know of a solution to speed this up, other than wrapping everything in a class(.o bject) and #include spdlog-stuff.h only once in a project?

Thank you,
Adi.

**Comment by Mazrog** [comment]
Hi,
Any updates on this ?

Thanks

**Comment by gabime** [comment]
Yes. Please try the static-lib branch.  It implements a statically compiled lib of spdlog(cmake -DSPDLOG_STATIC_LIB=ON), which should reduce the compile time significantly

**Comment by k-brac** [comment]
I confirm that the build time is now constant. But with this version my project went from 42s to 50s in debug with visual studio 2016 update 1...

**Comment by gabime** [comment]
> I confirm that the build time is now constant

What do you mean?
