### ISSUE TITLE
Document loggers with multiple sinks

### ISSUE THREAD

**Issue by gnzlbg** [gabime/spdlog#69]
E.g. I would like to have a file logger, but that at compile-time/run-time would also display the output to the screen. I can achieve this by wrapping two loggers. But I could also do this by having a single logger with 2 sinks and setting the level to the console sink to `on`/`off` (i.e. having a different level per sink in the logger with multiple sinks).  

I think wrapping two different loggers is better, but without documentation about loggers with multiple sinks it is hard to know what is the best way to achieve what I want to do.

**Comment by gabime** [comment]
Multiple sinks is the intended use for such cases. That's reason for this feature in the first place..

**Comment by gnzlbg** [comment]
So it is possible to set the output level on a per sink basis (besides on a per logger basis)?

**Comment by gnzlbg** [comment]
I've been trying to set a different level per sink in a logger with multiple sinks (console, and file) without success, neither the sink nor the logger interface seem to have a way to achieve this.

**Comment by gabime** [comment]
Levels can only be set per logger, not per sink. So the solution would be to use 2 loggers instead of 2 sinks..

**Comment by gnzlbg** [comment]
> I think wrapping two different loggers is better, but without documentation about loggers with multiple sinks it is hard to know what is the best way to achieve what I want to do.

That is what I'm using, thanks for the clarification.

**Comment by gabime** [comment]
Sure. Any comments, suggestions or issues are welcome. I don't see them as "issue spam"

**Comment by gabime** [comment]
I added [wiki](https://github.com/gabime/spdlog/wiki) docs for this. Please improve if you want
