### ISSUE TITLE
#pragma once and relative-includes breaking on some compilers

### ISSUE THREAD

**Issue by abrownsword** [gabime/spdlog#692]
I'm switching one of my machines to use Clang 7.0 and have run into an issue where duplicate symbols are being reported -- from the same include file!  It appears this is happening because some of the library's internal includes are done via relative paths (../file.h) rather than relying on the include search paths and this confuses #pragma once.  I don't see this on earlier versions of Clang nor Apple's currently Xcode version.

I can see several approaches to fix this:  switch to preprocessor-based include guards, don't use relative includes, or move to a build mechanism not entirely header-based.

**Comment by gabime** [comment]
strange.. maybe its just a bug in clang 7.0?

**Comment by jhasse** [comment]
I've never had any problems with `#pragma once` and relative includes. Are you sure the files aren't duplicated? Do you know how these errors could be reproduced?

**Comment by abrownsword** [comment]
Sorry, I just tried to restore my repro case and its not happening anymore.  My project has moved forward quite a bit including switching to libc++ and c++17, so something must have fixed the problem.  May as well close the issue and come back to it if it surfaces again.

**Comment by gabime** [comment]
Thanks for updating. fwiw the new v1.x branch (to be released soon) has all includes normalized without relative paths.
