### ISSUE TITLE
Windows: Symbol visiblity of registry_t class.

### ISSUE THREAD

**Issue by xaqq** [gabime/spdlog#693]
Hello,

I've been using spdlog for a while and I recently had to port a project from Linux to Windows.
I've encountered various crashes that I believe come from a symbol visibility issue.

The project does the following:
  +  A shared library has a functions "init_loggers()" that create various loggers using the
      `spdlog::stdout_color_mt("root");` functions and similar.
  + A main program that links with my shared library, call `init_loggers` then (attempt to) use the loggers.

It turns out that the program will crash when using the logger after a `spdlog::get_logger()` call.

spdlog being header only, and `registry_t` class using a singleton, my program is most likely violating the One Definition Rule because both my shared library and the main program seems to get their own
definition of the `registry_t::get_instance()` function (and its internal `static registry_t instance` object). I think this then causes UB and therefore crash.

The issue seems to be fixable by using the classic BLABLA_API macro. Something like

```
#ifdef SPDLOG_EXPORTS
#define SPDLOG_API __declspec(dllexport)
#else
#define SPDLOG_API __declspec(dllimport)
#endif
```

Using the `SPDLOG_API` macro on the declaration of the `registry_t` class will fix the issue if I also compile my my shared library with `-DSPDLOG_EXPORTS=1`.

I would be interested in knowing if other people faced related issue. I'd also like feedback about the fix, especially if there are other place in the library that may need to explicitly export symbols.

Thank you,

**Comment by gabime** [comment]
This is very important and a FAQ.. Any solution or help will be greatly appreciated. 

Note that any soltution  need to support both linux(gcc and  clang) and windows msvc.

**Comment by gabime** [comment]
@xaqq I think that using the compiled version of spdlog will resolve this issue too. Could you confirm?
