### ISSUE TITLE
Feature request: Log filtering of repeated lines

### ISSUE THREAD

**Issue by polesapart** [gabime/spdlog#696]
There's a feature I'd love to have, even if it has limited usability: replacing repeated identical log lines by  recording the repeat attempts (a la linux syslog), for instance: smbd: message repeated 69 times: [ pam_unix(samba:session): session closed for user nobody]

**Comment by gabime** [comment]
Implemented using a special filter sink.

Usage example:
```c++
#include "spdlog/sinks/dup_filter_sink.h"
int main() {
    auto dup_filter = std::make_shared<dup_filter_sink_st>(std::chrono::seconds(5));
    dup_filter->add_sink(std::make_shared<stdout_color_sink_mt>());
    spdlog::logger l("logger", dup_filter);
    l.info("Hello");
    l.info("Hello");
    l.info("Hello");
    l.info("Different Hello");
}
```
 Will produce:
       [2019-06-25 17:50:56.511] [logger] [info] Hello
       [2019-06-25 17:50:56.512] [logger] [info] Skipped 3 duplicate messages..
       [2019-06-25 17:50:56.512] [logger] [info] Different Hello
