### ISSUE TITLE
Request to add move constructor to spdlog::logger

### ISSUE THREAD

**Issue by chrahunt** [gabime/spdlog#697]
This would enable the following uses:

1. Defining a singleton `spdlog::logger` with some local function
2. Defining a class with an `spdlog::logger` member with initialization delegated to another function

e.g.

```cpp
// Use case 1
namespace logging
{

spdlog::logger & instance()
{
    static auto make_logger = []()
    {
        spdlog::logger  logger;
        // ...
        return logger;
    };
    static spdlog::logger inst = make_logger();
    return inst;
}

}

// Use case 2
class Widget
{
public:
    Widget()
    : logger_( make_logger() )
    {}

private:
    static spdlog::logger make_logger();
    spdlog::logger logger_;
};
```

**Comment by gabime** [comment]
A workaround would be to use a (shared/unique) pointer in order to pass the logger around.

**Comment by chiumichael** [comment]
Unless I'm mistaken, shared/unique ptrs will heap-allocate. Any particular reason against providing a move constructor?

**Comment by gabime** [comment]
No. Nothing against it in particular. Didnt have the time to implement it.

**Comment by gabime** [comment]
Move ctor is now implemented.

**Comment by chiumichael** [comment]
Greatly appreciated. Thanks for the update!

**Comment by gabime** [comment]
@chiumichael  You're welcome. There is still a missing ```operator==(logger &&)``` definition. Will be added soon.

**Comment by Col-blimp** [comment]
its positive she is
________________________________
