### ISSUE TITLE
How to locate error log line in my source？

### ISSUE THREAD

**Issue by hbhuyt** [gabime/spdlog#699]
I used spdlog in my c++ project recent.
but got error like this:

[*** LOG ERROR ***] [tdx_quote] [cannot switch from automatic to manual argument indexing] [2018-05-02 10:55:47]

but how can I find the error line in my source？

**Comment by vitaut** [comment]
The error means that you try to use both manual and automatic indexing when referring to arguments in your format strings, e.g. "{} {1}". You should either use all manual "{0} {1}" or all automatic "{} {}".
