### ISSUE TITLE
Please provide a one-header include

### ISSUE THREAD

**Issue by FelixBer** [gabime/spdlog#701]
Like catch does for example.

**Comment by jhasse** [comment]
Why?

**Comment by JesApp** [comment]
Because figuring out what to include where is a hassle.

Would there be any disadvantages to it? I'm not a C++ expert but I can't see anything other than possibly somewhat longer compile times.

**Comment by gabime** [comment]
you need to include only spdlog.h

**Comment by JesApp** [comment]
Oh, I see. It's only the null sink that needs the extra include, not all sinks.

Alright, nevermind. :)
