### ISSUE TITLE
flush is too slow

### ISSUE THREAD

**Issue by alexeiz** [gabime/spdlog#703]
I use asynchronous logging and on certain critical events I flush all logs with:

```cpp
spdlog::apply_all([](auto const & log) { log->flush(); });
```

With about 10 loggers, this operation takes from 1 to 2 seconds.  Is there a reason it's so slow?  I'd expect `log->flush()` to take a millisecond but not like 0.1 second.

**Comment by gabime** [comment]
Its a known issue. this is because flush waits for the queue to get empty before returning.

**Comment by gabime** [comment]
Fixed in latest commit
