### ISSUE TITLE
Is it possible to set the log level of a file sink to only output one level?

### ISSUE THREAD

**Issue by Andy608** [gabime/spdlog#704]
Right now in my code, I have six files that I want six sinks respectively to log to. One file for each level in spdlog. When I set each sink's level, it currently is only setting the minimum log level for the sink. Is there a way to set a sink to only allow one specific level?

**Comment by gabime** [comment]
There is no such way in the API

**Comment by Andy608** [comment]
Thanks for your response. I ended up creating a custom sink that overrides the should_log function to achieve my desired result.

**Comment by TimboKZ** [comment]
For anyone looking for a solution in the future, solution Andy mentions can be found here: https://github.com/Andy608/andrick-engine/blob/dc3183d0c8b26ed854c73cd17da502ca6ea761fe/andrick-sdk/andrick-sdk/andrick-sdk/andrick/logger/AndrickSinks.h#L76-L88

**Comment by nmoreaud** [comment]
should_log is not virtual, I don't think this works in the general case.

**Comment by tt4g** [comment]
We can do it with own custom sink (proxy-pattern).

See this issue: https://github.com/gabime/spdlog/issues/1357#issuecomment-565477775
