### ISSUE TITLE
critical output taints blank space at end of following line when scrolling

### ISSUE THREAD

**Issue by lambdafu** [gabime/spdlog#705]
I tested the example from the front page, and it gave some weird output when scrolling in the terminal. To reproduce, I used "clear" to clear the screen, then run the test program, and it gave proper output until the bottom of the terminal window, when the problem starts to be visible.  Here is a screenshot (in gnome-terminal, same result for xterm) on Linux:
![spdlog](https://user-images.githubusercontent.com/1138455/40332415-59867e74-5d54-11e8-8a15-bb7c25f6c9ad.png)
The code is straight from the front page:

```
  namespace spd = spdlog;
  auto console = spd::stdout_color_mt("console");
  console->info("Welcome to spdlog!");
  console->error("Some error message with arg{}..", 1);

  // Formatting examples
  console->warn("Easy padding in numbers like {:08d}", 12);
  console->critical(
      "Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
  console->info("Support for floats {:03.2f}", 1.23456);
  console->info("Positional args are {1} {0}..", "too", "supported");
  console->info("{:<30}", "left aligned");
```

**Comment by gabime** [comment]
Please try latest version 0.17.0 - should be better.

**Comment by lambdafu** [comment]
Yep, can confirm! Thanks a lot. 0.17.0 also fixes the %^...%$ issue I was just going to report :champagne:
