### ISSUE TITLE
Some using questions

### ISSUE THREAD

**Issue by NickYang1988** [gabime/spdlog#707]
Hi, thanks for offering this excellent logging library.

I try to replace easylogging++ by spdlog in my framework, but when I test spdlog, I have some questions below,

1. My spdlog partten is `spdlog::set_pattern("*** [%Y%m%d %H:%M:%S.%z] [thread %t] %v ***");`, but thread id patten %t is invalid, my log is 
```
[2018-05-22 19:37:07.303] [1] [warning] warn
[2018-05-22 19:37:07.304] [1] [info] info
[2018-05-22 19:37:07.304] [1] [error] error
[2018-05-22 19:37:07.305] [1] [critical] critical
```

2. I try to combine rotating strategy with `rotating_sink` and `daily_sink`, but throw an exception to me, the file has already existed. Actually I want to combine rotating with size and hour, if size up to my setting size, then rotated, if hour is changed, then rotated, for now I cannot find how to do, I find issue #222, it seems to add `hourly_file_sink_mt`, but this PR is not merged into master, so I'm not sure if it is OK.

3. After I check output log files, I find extra `[1]`, how could I remove this in file, my code is blow
```cpp
bool Example1Module::Init()
{
    spdlog::set_pattern("*** [%Y%m%d %H:%M:%S.%z] [thread %t] %v ***");
    spdlog::set_async_mode(1024 * 8);
    std::vector<spdlog::sink_ptr> sinks_vec;
    //auto rotating_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(pPluginManager->AppName() + ".log", 209715200, 1000);
    auto daily_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>(pPluginManager->AppName() + ".log", 0, 0);
#if ARK_PLATFORM == PLATFORM_WIN
    auto color_sink = std::make_shared<spdlog::sinks::wincolor_stdout_sink_mt>();
#else
    auto color_sink = std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>();
#endif

    //sinks_vec.push_back(rotating_sink);
    sinks_vec.push_back(daily_sink);
    sinks_vec.push_back(color_sink);

    auto combined_logger = std::make_shared<spdlog::logger>("1", std::begin(sinks_vec), std::end(sinks_vec));
    spdlog::register_logger(combined_logger);

    combined_logger->debug("debug");
    combined_logger->warn("warn");
    combined_logger->info("info");
    combined_logger->error("error");
    combined_logger->critical("critical");
    combined_logger->trace("trace");

    spdlog::drop_all();

    return true;
}
```

Looking forward your reply, thanks.

**Comment by gabime** [comment]
1. If you create loggers directly with make_shared, you need to set the pattern directly using
```logger->set_pattern(..)```

2. Maybe try [step_file_sink](https://github.com/gabime/spdlog/blob/master/include/spdlog/contrib/sinks/step_file_sink.h) - It closes the log on file each interval and if the file size exceeds a given size.

**Comment by NickYang1988** [comment]
Thanks for your reply, I resolved the question, I'm trying to commit a new sink(*rotating with size and hour*).
