### ISSUE TITLE
logger->flush_on()

### ISSUE THREAD

**Issue by ElioDream** [gabime/spdlog#711]
Hi,
I read the wiki and the flush policy, but flush_on isn't a member function anymore. Or isn't yet ? The package available for Ubuntu 16.04 is the 1.6-1.
Was it replaced ?
Thanks in advance !
Elio

**Comment by gabime** [comment]
In which spdlog version?

**Comment by ElioDream** [comment]
Installed the 1.6-1 with synaptic packet manager. Should I install from source ?

**Comment by gabime** [comment]
Yes. you have old version

**Comment by ElioDream** [comment]
Ok, thanks ! :-)
