### ISSUE TITLE
Fix for supporting AIX 6.1

### ISSUE THREAD

**Issue by JamesReynolds** [gabime/spdlog#714]
AIX 6.1 also lacks the `tm_gmtoff` field so the code needs to be adjusted for _AIX as well as _sun/sun.

With this done, all tests (except exception raising tests, but that is an AIX gcc issue) pass under AIX 6.1 / gcc 6.3.

**Comment by JamesReynolds** [comment]
@gabime I've retested and all tests pass. Do you want to add AIX support to the README.md as well? We're testing this at the moment so we could wait until we've gone a bit further?

**Comment by gabime** [comment]
@JamesReynolds If you fill it works, I will add it now.
