### ISSUE TITLE
`stdout_sink_mt` does not log to Visual Studio 2015's output window

### ISSUE THREAD

**Issue by paulhoux** [gabime/spdlog#716]
Hi,

it could be that I am doing something wrong, but logging to a `stdout_sink_mt` does not produce messages in Visual Studio 2015's Output window (with "Show output from" set to "Debug" and the following filters are enabled/checked: "Program Exit Messages","Thread Exit Messages","Program Output").

I am simultaneously logging to 2 sinks, one of which is a `rotating_file_sink_mt` which seems to work fine. Here's the setup code:
```
    std::vector<spdlog::sink_ptr> sinks;
    sinks.push_back( spdlog::sinks::stdout_sink_mt::instance() );
    sinks.back()->set_level( spdlog::level::trace );
    sinks.push_back( std::make_shared<spdlog::sinks::rotating_file_sink_mt>( ( findPath( "logs" ) / "log.txt" ).string(), 2 * 1024 * 1024, 3 ) );
    sinks.back()->set_level( spdlog::level::info );
    mLogger = std::make_shared<spdlog::logger>( "logger", std::begin( sinks ), std::end( sinks ) );
    mLogger->flush_on( spdlog::level::err );
    spdlog::register_logger( mLogger );
```

I also tried to create a `stdout` logger directly as in the sample code, but then, too, no messages were logged to the Output window. 

Could you tell me what I am doing wrong? How can I log to both the Output window and a file?

**Comment by paulhoux** [comment]
Additional information: when stepping into `stdout_sink`'s `fwrite` function, `__acrt_iob_func(1)` returns a nullptr:

![2018-05-30_133918](https://user-images.githubusercontent.com/304908/40718056-eb0236c0-640e-11e8-9e4f-2cc8580da6a1.png)

**Comment by paulhoux** [comment]
OK, sorry for the confusion. It seems logging to `stdout` does not produce output in Visual Studio anyway, so it's not an issue of spdlog. The proper way to output to Visual Studio's Output window is to use `OutputDebugString` and one way to do this is to write a wrapper that acts like a `std::ostream`. I could then use a `spdlog::ostream_sink_mt`.

The framework I am using, Cinder (http://libcinder.org) provides this wrapper as a `cinder::msw::dostream` (defined in [cinder/msw/OutputDebugStringStream.h](https://github.com/cinder/Cinder/blob/master/include/cinder/msw/OutputDebugStringStream.h)) in case anyone is interested in an implementation.

**Comment by gabime** [comment]
Please note that spdlog already provides a sink to OutputDebugString - [msvc_sink.h](https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/msvc_sink.h)
