### ISSUE TITLE
Compile failure on sparc Solaris 9

### ISSUE THREAD

**Issue by JamesReynolds** [gabime/spdlog#717]
Compile fails on Solaris 9 as Solaris 9 does not have `strerror_r`:
```
[solaris_sparc] /home/jenkins/build/workspace/Fractions_XPlatform@2/3rdparty/spdlog_1fcc89/include/spdlog/details/os.h:430:36: error: no matching function for call to ‘errno_to_string(char [256], fmt::internal::Null<>&)’
[solaris_sparc]      return errno_to_string(buf, err);              // use overloading to select correct stringify function
```
this is technically a failure in `fmt` for not falling back to a thread-unsafe version on systems where there is no thread-safe version perhaps?

However, this can be fixed in `spdlog` by adding an inline overload for `::Null<>` - will submit a PR soon.

**Comment by gabime** [comment]
Well in this case maybe this function should removed entirly from os.h and replace the code to use   fmt’s version directly (only single place  - in common.h so should be easy)
