### ISSUE TITLE
Add builtin stdlog logger.

### ISSUE THREAD

**Issue by meldavis** [gabime/spdlog#72]
Add a built-in logger to `std::clog` to match the `stderr` and `stdout`loggers.

**Comment by gabime** [comment]
There is already support for this - the stdout_sink and stderr_sink sinks

**Comment by meldavis** [comment]
Okay. But just to clarify:  c++ has 3 separate and distinct standard output streams:

std::cout => file descriptor 1,  (buffered to stdout)
std::cerr => file descriptor 2,   (unbuffered to stderr)
std::clog => file descriptor 3    (buffered to stderr)

What I typically do is send routine output intended for the user to see to std::cout, error messages meant for the user to std::cerr and logging/trace messages to std::clog. 

This allows me, through redirection, to see the log in the console, blended with the user-intended messages,  or redirect the log/trace messages to a separate file. 

`myapp.exe`
or
`myapp.exe --trace 3>myapp.log `  
or 
`myapp.exe --trace 2>myapp.err 3>myapp.log`

It just seems that a library intended for logging, would have built-in support for the std::clog output stream.  

But, you've made a great library, and it's easy enough to extend.  Thanks!

**Comment by gabime** [comment]
Right. Would be easy to add the missing clog_sink (just copy paste from stdout_sink). If you do it please open pull request
