### ISSUE TITLE
Memory leak of spdlog lib

### ISSUE THREAD

**Issue by xiangjan** [gabime/spdlog#721]
I have some project use your lib.
But, I found some memory leak in the lib.
I just creat new win32 console project in visual studio. 
I just inclued your library in the header. and then run.
it's dump some memory leak.

the code is like blow.

#include "stdafx.h"
#include "spdlog/spdlog.h"
//CTLog	gTLog;
#define DEBUG_MERROY 1
#if DEBUG_MERROY
#define _CRTDBG_MAP_ALLOC  
#include <stdlib.h>  
#include <crtdbg.h>  
#endif
int main()
{
	_CrtDumpMemoryLeaks();
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
    return 0;
}

The dumped leak is like blow
Dumping objects ->
{209} normal block at 0x00DA27C0, 8 bytes long.
 Data: < H      > 14 48 15 00 00 00 00 00 
{208} normal block at 0x00DA2718, 8 bytes long.
 Data: < G      > F8 47 15 00 00 00 00 00 
{207} normal block at 0x00DA2638, 8 bytes long.
 Data: < G      > DC 47 15 00 00 00 00 00 
{206} normal block at 0x00DA2408, 8 bytes long.
 Data: < G      > C0 47 15 00 00 00 00 00 
{205} normal block at 0x00DA2360, 8 bytes long.
 Data: < G      > A4 47 15 00 00 00 00 00 
{204} normal block at 0x00DA2328, 8 bytes long.
 Data: < G      > 88 47 15 00 00 00 00 00 
{203} normal block at 0x00DA2600, 8 bytes long.
 Data: <lG      > 6C 47 15 00 00 00 00 00 
{202} normal block at 0x00DA1630, 8 bytes long.
 Data: <PG      > 50 47 15 00 00 00 00 00 
{201} normal block at 0x00DA1668, 8 bytes long.
 Data: <4G      > 34 47 15 00 00 00 00 00 
{200} normal block at 0x00DA15F8, 8 bytes long.
 Data: < G      > 18 47 15 00 00 00 00 00 
{199} normal block at 0x00DA1748, 8 bytes long.
 Data: < F      > FC 46 15 00 00 00 00 00 
{198} normal block at 0x00DA1C88, 8 bytes long.
 Data: < F      > E0 46 15 00 00 00 00 00 
{197} normal block at 0x00DA17B8, 8 bytes long.
 Data: < F      > C4 46 15 00 00 00 00 00 
{196} normal block at 0x00DA1940, 8 bytes long.
 Data: < F      > A8 46 15 00 00 00 00 00 
{195} normal block at 0x00DA1908, 8 bytes long.
 Data: < F      > 8C 46 15 00 00 00 00 00 
{194} normal block at 0x00DA1BA8, 8 bytes long.
 Data: <pF      > 70 46 15 00 00 00 00 00 
{193} normal block at 0x00DA1828, 8 bytes long.
 Data: <TF      > 54 46 15 00 00 00 00 00 
{192} normal block at 0x00DA1BE0, 8 bytes long.
 Data: <8F      > 38 46 15 00 00 00 00 00 
{191} normal block at 0x00DA1710, 8 bytes long.
 Data: < F      > 1C 46 15 00 00 00 00 00 
{190} normal block at 0x00DA1B38, 8 bytes long.
 Data: < F      > 00 46 15 00 00 00 00 00 
{189} normal block at 0x00DA1AC8, 8 bytes long.
 Data: < E      > E4 45 15 00 00 00 00 00 
{188} normal block at 0x00DA1C50, 8 bytes long.
 Data: < E      > C8 45 15 00 00 00 00 00 
{187} normal block at 0x00DA1C18, 8 bytes long.
 Data: < E      > AC 45 15 00 00 00 00 00 
{186} normal block at 0x00DA1780, 8 bytes long.
 Data: < E      > 90 45 15 00 00 00 00 00 
{185} normal block at 0x00DA17F0, 8 bytes long.
 Data: <pE      > 70 45 15 00 00 00 00 00 
{184} normal block at 0x00DA1898, 8 bytes long.
 Data: <TE      > 54 45 15 00 00 00 00 00 
{183} normal block at 0x00DA1A90, 8 bytes long.
 Data: <8E      > 38 45 15 00 00 00 00 00 
{182} normal block at 0x00DA1B00, 8 bytes long.
 Data: < E      > 1C 45 15 00 00 00 00 00 
{181} normal block at 0x00DA1A58, 8 bytes long.
 Data: < E      > 00 45 15 00 00 00 00 00 
{180} normal block at 0x00DA1860, 8 bytes long.
 Data: < D      > E4 44 15 00 00 00 00 00 
{179} normal block at 0x00DA19B0, 8 bytes long.
 Data: < D      > C8 44 15 00 00 00 00 00 
{178} normal block at 0x00DA16D8, 8 bytes long.
 Data: < D      > A8 44 15 00 00 00 00 00 
{177} normal block at 0x00DA18D0, 8 bytes long.
 Data: < D      > 8C 44 15 00 00 00 00 00 
{176} normal block at 0x00DA1B70, 8 bytes long.
 Data: <pD      > 70 44 15 00 00 00 00 00 
{175} normal block at 0x00DA1A20, 8 bytes long.
 Data: <TD      > 54 44 15 00 00 00 00 00 
{174} normal block at 0x00DA1978, 8 bytes long.
 Data: <8D      > 38 44 15 00 00 00 00 00 
{173} normal block at 0x00DA19E8, 8 bytes long.
 Data: < D      > 1C 44 15 00 00 00 00 00 
{172} normal block at 0x00DA15C0, 8 bytes long.
 Data: < D      > 00 44 15 00 00 00 00 00 
Object dump complete.

I found this in my big project. this is just sample code of memory leak.

Hope you to solve this problem for eveyone.

**Comment by gabime** [comment]
Probably due to the static registry object and not real leak. (see https://stackoverflow.com/a/5266164)

Anyway, shouldn't the line 
```_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);``` be before ```_CrtDumpMemoryLeaks();``` ?
