### ISSUE TITLE
spdlog_ex can throw exception

### ISSUE THREAD

**Issue by elnormous** [gabime/spdlog#724]
You should not store std::string in the spdlog_ex class, because the std::move in the constructor can throw an exception and also rethrowing the spdlog_ex exception will try to copy the _msg which can also throw an exception. I suggest simply inheriting from the std::runtime_error.

**Comment by gabime** [comment]
Agreed. Thanks for noticing.

**Comment by gabime** [comment]
Solved in v1.x branch
