### ISSUE TITLE
Including fmt and spdlog in a project

### ISSUE THREAD

**Issue by spacemoose** [gabime/spdlog#728]
I have a project which uses libfmt and spdlog.  I recently changed from using libfmt from a package (on fedora) to libfmt as a submodule of the project.  When I did so, I discovered two things:  

1.  In the meantime fmt has moved from release 4 to release 5.
2.  spdlog has some 4.x fmt bundled in its source code.

These caused a conflict, since fmt no longer has a MemoryWriter class.

Well, I 'fixed' the short term problem, but I'm concerned.  I only discovered the overlap because of the incompatible interfaces between the major versions.  I  imagine that subtle bugs might arise when such overlapping definitions occur but are not detected at compile time.  

In my library I've added libfmt as a submodule to the project, which I find unsatisfactory:  now there are at least two copies of libfmt in my source tree, and if the library user has installed libfmt using a package, they will have three, and they may have to take care that the right version is being compiled or linked against.  So my users will face the same problem that I faced just now.

So it seems to me that we have the same problem.  What do you think, do you also find this disturbing?  If so, maybe we could cultivate a solution together.

Here's what I thought might work in my project, which has 3 github dependencies (fmt, spdlog and Catch2):
    1.  have the user clone my project, which has the other dependencies as submodules.
    2.  CMake looks if the system provides a compatible version of each required library.  If it's found, it uses that.  If not, it runs git submodule udpate and uses the submoduled code.

Does that seem like a good approach?  Do you have a better idea, see problems with the approach, or have suggestions for improvement?  Finally, would you be interested in a PR in that dirction?

**Comment by gabime** [comment]
Hi @spacemoose 

There is a option for spdlog to use external fmt (define SPDLOG_FMT_EXTERNAL before including spdlog.h).

Also, please note that spdlog is being actively ported to fmt 5 and will be released as spdlog v1.0  soon. stay tuned

**Comment by daixtrose** [comment]
Any update wrt fmt 5?

**Comment by tt4g** [comment]
@daixtrose spdlog 1.8.0 and above are bundled fmt  version 7.0.3.

https://github.com/gabime/spdlog/releases/tag/v1.8.0:

> Upgraded bundled fmt to version 7.0.3.
