### ISSUE TITLE
custom time source

### ISSUE THREAD

**Issue by mateuszzz88** [gabime/spdlog#730]
This is feature request.
I would like to be able to set time source different than std::chrono::system_clock to be used by spdlog. 

I am willing to develop it in near future. I would welcome any comments how to do it so that PR would be accepted into upstream (API to use, etc)

My usecase:
Our program is distributed across many computers that do not have synchronized system(OS) time. Our program has its own time synchronization and knows the offset from system time to real time. I want logs to be indexed by real time (provided by object provided by me) and not std::chrono::sytem_clock()::now()

How I think I would do this:
If in tweakme.h has define CUSTOM_TIME_SOURCE, then its value is a class that will be used. common.h: log_clock then uses this class. 
PRO: time source is set globally at compile time, so there shouldn't be performance penalty
CON: when used, tweakme must include user-provided header from outside spdlog. Ugly, but i can live with it.

So, would you consider such enhancement? Does implementation seem reasonable?

**Comment by gabime** [comment]
> I would like to be able to set time source different than std::chrono::system_clock to be used by spdlog.

Please note this won't affect file sinks time calculations (spdlog calls ```system_clock::now()``` to decide when to close files and which name to give them, it doesn't use log_clock for this(maybe it should i'm not sure).

This is very specific requirement. Maybe on first stage just replace the ```using log_clock=..``` in common.h to whatever needed. 
If this requirement become more popular, I will add the CUSTOM_TIME_SOURCE option to the tweakme.h file.

**Comment by dawagner** [comment]
@gabime : I'm also interested in such a feature for usage under simulated time. A typedef wouldn't 100% cut it for me because I'm using a runtime switch to use simulated time or system time.

I'll try using a custom flag formatter that prints the simulated time as a workaround until then.

Thanks for spdlog, by the way :)

**Comment by kyle-basis** [comment]
Giving a +1 here as well - I will fork spdlog for now, but this would be very useful.

**Comment by TomerW** [comment]
+1, also needs this, 
I am using an embedded system that reads it's time from Firmware and does not relay on systemtime.

Moreover, i have a simulation that runs the code in a virtual environment where the time is completly different then systemtime.

I'll use the suggested workaround for now but would love such a feature to exist.
