### ISSUE TITLE
Example code doesn't work on Visual Studio 12

### ISSUE THREAD

**Issue by guestinvite** [gabime/spdlog#736]
Hello,
Trying to build a very simple example
`
#include <iostream>
#include <spdlog\spdlog.h>

int main()
{
	std::cout << "Hello!" << std::endl;
   auto console = spdlog::stdout_color_mt("console");
   console->info("Welcome!");
	return 0;
}
`

on Windows/Visual Studio 12, gave me first **C2610 errors**:

> Error	1	error C2610: 'spdlog::details::async_log_helper::async_msg::async_msg(spdlog::details::async_log_helper::async_msg &&)' : is not a special member function which can be defaulted	c:\work\logging\spdtry\dev\include\spdlog\details\async_log_helper.h	66	1	dev

Without surprise, deleting this faulty code then gave me LNK2019 errors:
`
Error	1	error LNK2019: unresolved external symbol "public: __cdecl spdlog::details::async_log_helper::async_msg::async_msg(struct spdlog::details::async_log_helper::async_msg &&)" (??0async_msg@async_log_helper@details@spdlog@@QEAA@$$QEAU0123@@Z) referenced in function "public: void __cdecl std::allocator<struct spdlog::details::async_log_helper::async_msg>::construct<struct spdlog::details::async_log_helper::async_msg,struct spdlog::details::async_log_helper::async_msg>(struct spdlog::details::async_log_helper::async_msg *,struct spdlog::details::async_log_helper::async_msg &&)" (??$construct@Uasync_msg@async_log_helper@details@spdlog@@U1234@@?$allocator@Uasync_msg@async_log_helper@details@spdlog@@@std@@QEAAXPEAUasync_msg@async_log_helper@details@spdlog@@$$QEAU2345@@Z)	C:\WORK\Logging\SpdTry\build\main.obj	dev
`

**Comment by gabime** [comment]
try newer version of vs. It is not supported for vs 2012

**Comment by guestinvite** [comment]
Thank you for your quick reply!
Howhever this solution is problematic, because my enterprise still use VS 12. Do you think it is easy to adapt the code to manually add these two constructors?

**Comment by gabime** [comment]
No sure. Give it a try.

**Comment by guestinvite** [comment]
So I tried, and here the main modifications (async_log_helper.h:66)
`#ifndef _has_no_default_move
        async_msg(async_msg &&other) = default;
        async_msg &operator=(async_msg &&other) = default;
#else
#include <utility>
        async_msg(async_msg &&other)
           : level(other.level)
           , thread_id(other.thread_id)
           , msg_type(other.msg_type)
           , msg_id(other.msg_id)
        {  
        }
        async_msg &operator=(async_msg &&other)
        {
           return *std::move(&other);
        }
#endif`

==> Result?
1) Basic examples work, at least this give a hello world feel of your lib.
2) But, the last part of the examples seems buggy: when lauching from command-line, the program hangs until a Ctrl-C kill; and when stepping with Visual Studio, an exception is raised, because program repeatedly fails to open a file.
3) The test suite fails.

Any ideas please?

**Comment by sixten-hilborn** [comment]
@gabime defaulted move doesn't work in VS2013 (a.k.a. VS12) so I think this should be re-opened:

    ...\spdlog\details\../details/async_log_helper.h(67): error C2610: 'spdlog::details::async_log_helper::async_msg::async_msg(spdlog::details::async_log_helper::async_msg &&)' : is not a special member function which can be defaulted
    ...\spdlog\details\../details/async_log_helper.h(68): error C2610: 'spdlog::details::async_log_helper::async_msg &spdlog::details::async_log_helper::async_msg::operator =(spdlog::details::async_log_helper::async_msg &&)' : is not a special member function which can be defaulted

Changing the code like this works:

    #if defined(_MSC_VER) && _MSC_VER <= 1800
        async_msg(async_msg &&other) SPDLOG_NOEXCEPT
            : level(other.level)
            , time(other.time)
            , thread_id(other.thread_id)
            , txt(move(other.txt))
            , msg_type(other.msg_type)
            , msg_id(other.msg_id)
        {
        }

        async_msg &operator=(async_msg &&other) SPDLOG_NOEXCEPT
        {
            level = other.level;
            time = other.time;
            thread_id = other.thread_id;
            txt = move(other.txt);
            msg_type = other.msg_type;
            msg_id = other.msg_id;
            return *this;
        }
    #else
        async_msg(async_msg &&other) = default;
        async_msg &operator=(async_msg &&other) = default;
    #endif

**Comment by gabime** [comment]
Thanks @sixten-hilborn 

I will update the branch with your suggested fix

**Comment by gabime** [comment]
Fixed in branch v1.x
