### ISSUE TITLE
How to view the real-time log file text?

### ISSUE THREAD

**Issue by kisanman** [gabime/spdlog#737]
Below text is not any issues just question.

first of all, I appreciate the distributors of this spdlog prj.
I'm using it on Ubuntu and rotating_logger_mt() is my major logger.
When I make a process run and try to see the log text, I usually use "tail -f spdlog.log" command.
But, During the process is running, I can't see any log text the the 'tail' command.
And After finishing the process, I can see all log text finally.

Is there any way to check the log text real-time by 'tail -f' or another tool??

Thank you

**Comment by gabime** [comment]
Maybe try setting the flush level to lower level:
e.g.
```c++
logger->flush_on(spdlog::level::debug);
```
This comes with the cost of performance of course.
