### ISSUE TITLE
help wanted - Integrate spdlog for QNX OS

### ISSUE THREAD

**Issue by Murugaiyan** [gabime/spdlog#738]
Hi, 
The spdlog document mentioned the supported os. I'm trying to integrate spdlog for QNX 6.6 OS. The qnx internally uses gcc compiler version gcc 4.7.3 which supports c++11 standards. 

I got compilation error  when I compiled with the following compiler options 
-O3 -Wshadow -Wextra -pedantic -vv  -std=c++11 

Compilation Error: 
---------------------
'strftime' is not a member of 'std'

After analyse the compilation error triggered from time.h from the folder spdlog fmt/bundled/time.h
Since the spdlog is working for linux version, I tried for QNX 6.6 which uses gcc compiler internally. Would like to know if I'm missing anything ?

Could you help me out to fix this problem ? Thanks

**Comment by Murugaiyan** [comment]
Full log of compilation error for qnx 6.6
---------------------------------------------------
F:\workspace\spdlog\logger>make
make -j 1 -Cx86 -fMakefile
make[1]: Entering directory `F:/workspace/spdlog/logger/x86'
make -j 1 -Co -fMakefile
make[2]: Entering directory `F:/workspace/spdlog/logger/x86/o'
C:/qnx660/host/win32/x86/usr/bin/qcc -Vgcc_ntox86 -c -Wc,-Wall  -Os -Wshadow -Wextra -pedantic -O3 -vv -std=c++11          -DNDEBUG    -I. -IF:/workspace/spdlog/logger/x86/o -IF:/workspace/spdlog/logger/x86 -IF:/workspace/spdlog/logger -IF:/spdlog-master/include -IF:/spdlog-master/include/spdlog -IF:/spdlog-master/include/spdlog/contrib -IF:/spdlog-master/include/spdlog/contrib/sinks -IF:/spdlog-master/include/spdlog/details -IF:/spdlog-master/include/spdlog/fmt -IF:/spdlog-master/include/spdlog/fmt/bundled -IF:/spdlog-master/include/spdlog/sinks -IC:/qnx660/target/qnx6/usr/include     -DBUILDENV_qss   F:/workspace/spdlog/logger/example.cpp
cc: looking for gcc_ntox86 in C:/qnx660/host/win32/x86/etc/qcc/gcc/4.7.3/gcc_ntox86++.conf
cc: looking for gcc_ntox86 in C:/qnx660/host/win32/x86/etc/qcc/gcc/4.7.3/gcc_ntox86.conf
C:/qnx660/host/win32/x86/usr/lib/gcc/i486-pc-nto-qnx6.6.0/4.7.3/cc1plus -Os -O3 -DNDEBUG -I. -IF:/workspace/spdlog/logger/x86/o -IF:/workspace/spdlog/logger/x86 -IF:/workspace/spdlog/logger -IF:/spdlog-master/include -IF:/spdlog-master/include/spdlog -IF:/spdlog-master/include/spdlog/contrib -IF:/spdlog-master/include/spdlog/contrib/sinks -IF:/spdlog-master/include/spdlog/details -IF:/spdlog-master/include/spdlog/fmt -IF:/spdlog-master/include/spdlog/fmt/bundled -IF:/spdlog-master/include/spdlog/sinks -IC:/qnx660/target/qnx6/usr/include -DBUILDENV_qss -quiet -fstack-protector-strong -march=i486 -nostdinc -nostdinc++ -std=gnu++11 -D__QNX__ -D__QNXNTO__ -D__GNUC__=4 -D__GNUC_MINOR__=7 -D__GNUC_PATCHLEVEL__=3 -D__NO_INLINE__ -D__DEPRECATED -D__EXCEPTIONS -D__unix__ -D__unix -D__ELF__ -D__X86__ -D__i386__ -march=i486 -D__LITTLEENDIAN__ -Wall -Wshadow -Wextra -pedantic -std=c++11 -isystem C:/qnx660/target/qnx6/usr/include -isystem C:/qnx660/host/win32/x86/usr/lib/gcc/i486-pc-nto-qnx6.6.0/4.7.3/include -isystem C:/qnx660/target/qnx6/usr/include/cpp/c -isystem C:/qnx660/target/qnx6/usr/include/cpp F:/workspace/spdlog/logger/example.cpp -dumpbase F:/workspace/spdlog/logger/example.cpp -o C:\Users\Murugan\AppData\Local\Temp\2qccpYo0jb\example.s
In file included from C:/qnx660/target/qnx6/usr/include/cpp/xlocale:8:0,
                 from C:/qnx660/target/qnx6/usr/include/cpp/xiosbase:4,
                 from C:/qnx660/target/qnx6/usr/include/cpp/streambuf:4,
                 from C:/qnx660/target/qnx6/usr/include/cpp/xlocnum:8,
                 from C:/qnx660/target/qnx6/usr/include/cpp/ios:4,
                 from C:/qnx660/target/qnx6/usr/include/cpp/ostream:4,
                 from C:/qnx660/target/qnx6/usr/include/cpp/istream:4,
                 from C:/qnx660/target/qnx6/usr/include/cpp/iterator:4,
                 from C:/qnx660/target/qnx6/usr/include/cpp/string:4,
                 from F:/spdlog-master/include/spdlog/fmt/bundled/format.h:40,
                 from F:/spdlog-master/include/spdlog/fmt/bundled/time.h:13,
                 from C:/qnx660/target/qnx6/usr/include/cpp/chrono:7,
                 from F:/spdlog-master/include/spdlog/common.h:13,
                 from F:/spdlog-master/include/spdlog/spdlog.h:10,
                 from F:/workspace/spdlog/logger/example.cpp:13:
C:/qnx660/target/qnx6/usr/include/cpp/xlocinfo: In function 'std::size_t std::_Strftime(char*, std::size_t, const char*, const std::tm*, void*)':
C:/qnx660/target/qnx6/usr/include/cpp/xlocinfo:164:10: error: 'strftime' is not a member of 'std'
In file included from C:/qnx660/target/qnx6/usr/include/cpp/chrono:7:0,
                 from F:/spdlog-master/include/spdlog/common.h:13,
                 from F:/spdlog-master/include/spdlog/spdlog.h:10,
                 from F:/workspace/spdlog/logger/example.cpp:13:
F:/spdlog-master/include/spdlog/fmt/bundled/time.h: In function 'void fmt::format_arg(fmt::BasicFormatter<char, ArgFormatter>&, const char*&, const std::tm&)':
F:/spdlog-master/include/spdlog/fmt/bundled/time.h:41:29: error: 'strftime' is not a member of 'std'
F:/spdlog-master/include/spdlog/fmt/bundled/time.h: At global scope:
F:/spdlog-master/include/spdlog/fmt/bundled/time.h:81:31: error: 'fmt::localtime' declared as an 'inline' variable
F:/spdlog-master/include/spdlog/fmt/bundled/time.h:81:31: error: variable 'std::tm fmt::localtime' has initializer but incomplete type
F:/spdlog-master/include/spdlog/fmt/bundled/time.h:81:26: error: 'time_t' is not a member of 'std'
F:/spdlog-master/include/spdlog/fmt/bundled/time.h:82:1: error: expected ',' or ';' before '{' token
In file included from C:/qnx660/target/qnx6/usr/include/sched.h:50:0,
                 from C:/qnx660/target/qnx6/usr/include/pthread.h:49,
                 from C:/qnx660/target/qnx6/usr/include/cpp/Dinkum/threads/xthrcommon.h:61,
                 from C:/qnx660/target/qnx6/usr/include/cpp/Dinkum/threads/xtimec.h:4,
                 from C:/qnx660/target/qnx6/usr/include/cpp/chrono:8,
                 from F:/spdlog-master/include/spdlog/common.h:13,
                 from F:/spdlog-master/include/spdlog/spdlog.h:10,
                 from F:/workspace/spdlog/logger/example.cpp:13:
C:/qnx660/target/qnx6/usr/include/_pack64.h:32:24: error: expected '}' before end of line
C:/qnx660/target/qnx6/usr/include/_pack64.h:32:24: error: expected declaration before end of line
cc: C:/qnx660/host/win32/x86/usr/lib/gcc/i486-pc-nto-qnx6.6.0/4.7.3/cc1plus caught signal 1
cc: unlinking example.o
cc: unlinking C:\Users\Murugan\AppData\Local\Temp\2qccpYo0jb\example.s
cc: removing  C:\Users\Murugan\AppData\Local\Temp\2qccpYo0jb
make[2]: *** [example.o] Error 1
make[2]: Leaving directory `F:/workspace/spdlog/logger/x86/o'
make[1]: *** [all] Error 2
make[1]: Leaving directory `F:/workspace/spdlog/logger/x86'
make: *** [all] Error 2

F:\workspace\spdlog\logger>

**Comment by gabime** [comment]
Seems this originates from fmt libray. Please open an issue in its repo (https://github.com/fmtlib/fmt).

**Comment by Murugaiyan** [comment]
Hi Gabime,
This is the reply I got from Vituat from fmt library contributor.
 
----------------------------------------------
The problem is that fmt/bundled is passed as an include directory which makes bundled time.h (which is normally included as fmt/time.h in stock fmt) be included instead of the system's time.h. spdlog's include directories might need some adjustments.
