### ISSUE TITLE
0.16.3 -> 0.17 broke wincolor

### ISSUE THREAD

**Issue by NickeZ** [gabime/spdlog#739]
I'm using windows 10 and ms vs 2017. I don't get color output anymore in the dev console when using wincolor_stderr_sink_mt or wincolor_stdout_sink_mt.

Do I have to change anything when upgrading from 0.16.3 to 0.17?

git bisect gives me: d040ab93ea4e372998048c8b270aaffd6e5ce663 

```
$ git bisect good
d040ab93ea4e372998048c8b270aaffd6e5ce663 is the first bad commit
commit d040ab93ea4e372998048c8b270aaffd6e5ce663
Author: gabime <gmelman1@gmail.com>
Date:   Fri Apr 6 03:04:18 2018 +0300

    wincolor color formatting support

:040000 040000 b342157f00af567d638d9ffe6efa91d6bf1f3013 77a4959bab8ac61684c76ddb5bd3b196bb5424d0 M      example
:040000 040000 e3741ff536a8c4d8e807760fd52bee5efb63392f f83afaa560648aadadb266475dd1de58d9002b52 M      include
```

Can I provide any other information?

**Comment by gabime** [comment]
Try surrounding the part of the log you want to color with   %^ and %$ in the format string.

**Comment by NickeZ** [comment]
I had totally forgot that I used a custom formatter. It works like a charm. Sorry for the noise...
