### ISSUE TITLE
Compile Errors on Mac OSX Yosemite

### ISSUE THREAD

**Issue by lzuwei** [gabime/spdlog#74]
When compiling on mac against clang LLVM 3.5, I have the following compilation error,

```
spdlog/include/spdlog/sinks/../details/./os.h:188:12: error: cannot initialize return object of type 'size_t' (aka 'unsigned long') with an rvalue of type 'pthread_t' (aka '_opaque_pthread_t *')
    return pthread_self();
```

if you look at the file `os.h`, under the function:

```
inline size_t thread_id()
{

#ifdef SPDLOG_NO_THREAD_ID
    return 0;
#else

#ifdef _WIN32
    return ::GetCurrentThreadId();
#elif __linux__
    return  syscall(SYS_gettid);
#else
    return pthread_self();
#endif
#endif //SPDLOG_NO_THREAD_ID
}
```
spdlog attempts to return the `struct pthread_t` which resolves to a pointer of type `_opaque_pthread_t *` of the current thread as the thread id however there is no implicit conversion for this to `size_t`. A workaround is to cast the pointer to `size_t`.

**Comment by gabime** [comment]
Would something like 
```return static_cast<size_t>(pthread_self());``` work?

I don't have OSX here to try myself. 
Also could you verify that indeed  ```return  syscall(SYS_gettid);``` is not supported ?```

**Comment by lzuwei** [comment]
Hi gabime,
Thanks for the replies,

`syscall(SYS_gettid)` is not supported on OSX,

`return static_cast<size_t>(pthread_self());` fails because the types are different between `_opaque_pthread_t*` and `size_t`, only `reinterpret_cast<size_t>(pthread_self())` will work in this case which will cast the pointer address to type `size_t`

**Comment by gabime** [comment]
Fixed in b715378ff55eb40664d215e9264407b0310ec763 :
Under OSX, spdlog will use the standard c++11 ```std::hash<std::thread::id>()(std::this_thread::get_id())```

Please feeback if it works for you..

**Comment by lzuwei** [comment]
Hi Gabime,

As far as I have tested, no issues with Mac OSX using `std::hash<std::thread::id>()(std::this_thread::get_id())`

Thank you for the fixes.

Regards,
Zuwei

**Comment by gabime** [comment]
Would be interesting to see if there are performance issues using this method under OSX.
