### ISSUE TITLE
Can spd logger print file name function and line number using formater

### ISSUE THREAD

**Issue by naveenpinto** [gabime/spdlog#743]
Can spd logger print file name function and line number using formater

**Comment by Clocktown** [comment]
While you can't do this directly in the pattern you use for your logger or sinks, you can write a simple macro or insert `__FILE__` and `__LINE__` yourselves. I use this:

```cpp
#define LOG_LINE(logger, lvl, msg, ...)                                                     \
    (logger)                                                                                                \
            ->log(spdlog::level::level_enum::lvl, "[{}, Line {}] " msg, __FILE__, __LINE__, __VA_ARGS__)

#define LOG_LINE_INDEXED(logger, lvl, msg, ...)                                             \
    (logger)                                                                                                        \
            ->log(spdlog::level::level_enum::lvl,                                                     \
                  "[{0}, Line {1}] " msg,                                                                       \
                  __FILE__,                                                                                          \
                  __LINE__,                                                                                         \
                  __VA_ARGS__)
```

**Comment by MacroGu** [comment]
hi, I copy these code and compile under ubuntu, but cause an error:
`/home/macro/workspace/githubMacro/MGServer/server/./header/defines.h:22:103: error: expected primary-expression before ¡®)¡¯ token
            ->log(spdlog::level::level_enum::lvl, "[{}, Line {}] " msg, __FILE__, __LINE__, __VA_ARGS__)
                                                                                                       ^
/home/macro/workspace/githubMacro/MGServer/server/source/AcceptServer.cpp:211:2: note: in expansion of macro ¡®LOG_LINE¡¯
  LOG_LINE(ServerLog::GetInstance().GetInstance().GetRotatingLogger(),warn, "1234");
  ^~~~~~~~
make[2]: *** [server/CMakeFiles/server.dir/build.make:154: server/CMakeFiles/server.dir/source/AcceptServer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: server/CMakeFiles/server.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by tt4g** [comment]
@MacroGu Now spdlog can log line number using macro: `SPDLOG_TRACE`, `SPDLOG_DEBUG` ...

see: https://github.com/gabime/spdlog/issues/1032#issuecomment-475237476

**Comment by smrititripathi027** [comment]
If I am creating two loggers in same c++ file then how to print file name, line number in file becausee if I am using SPDLOG_TRACE , it is supporting to only one logger.
