### ISSUE TITLE
what is the use of const Arg1 &arg1 in info function

### ISSUE THREAD

**Issue by naveenpinto** [gabime/spdlog#747]
i would like to know what is the use of const Arg1 &arg1 cant we only have const const Args &... args
inline void spdlog::logger::info(const char *fmt, const Arg1 &arg1, const Args &... args)

**Comment by gabime** [comment]
@naveenpinto Indeed. No good reason for this. It's a leftover from older code. Will be fixed in v1.x branch

**Comment by gabime** [comment]
Fixed in 4f1ce9189f6ef4b1b96fe017c56c24c5513f8514

**Comment by naveenpinto** [comment]
@gabime have you also fixed it for other log levels?
will i get this fix if i pull the latest code???

**Comment by gabime** [comment]
yes.In branch v1.x
