### ISSUE TITLE
line number, function name and file name

### ISSUE THREAD

**Issue by naveenpinto** [gabime/spdlog#749]
Hi 
  cant we have this in SPD logger printing the line number, function name and file name, for now i have to implement this in my own code. It will be really useful for users to have these parameters in the spd implementation itself.

Regards
Naveen

**Comment by gabime** [comment]
you can use SPDLOG_TRACE for this

**Comment by blackball** [comment]
I have the very need. Would like to know why it's not implemented by default. Thanks.

**Comment by smrititripathi027** [comment]
If I am creating two loggers in same c++ file then how to print file name, line number in file becausee if I am using SPDLOG_TRACE , it is supporting to only one logger.
