### ISSUE TITLE
what is the off logging type mean, please can anyone explain?

### ISSUE THREAD

**Issue by naveenpinto** [gabime/spdlog#750]
what is the off logging type mean, please can anyone explain?

**Comment by gabime** [comment]
Messages with this log level will never be logged

**Comment by naveenpinto** [comment]
Then there is no use of this log level, is it needed, can't it be removed???

**Comment by Chartas** [comment]
No, it can also be used to set the log level. This results in NO messages being logged which is really useful to turn off logging.

**Comment by naveenpinto** [comment]
Ok got it, thanks
