### ISSUE TITLE
Do not use mutexes in single-threaded mode

### ISSUE THREAD

**Issue by fmoessbauer** [gabime/spdlog#751]
In some scenarios applications cannot use mutexes or create threads. This especially holds for embedded systems.

Is it possible to use spdlog in a mode that does neither create threads or use locks? Even the single-threaded sink uses at least one of these.

**Comment by gabime** [comment]
which single threaded sink use it?

**Comment by gabime** [comment]
I dont know of a mutex in it.. shich spdlog version?

**Comment by fmoessbauer** [comment]
Latest Master. I'll have a closer look at the code and report back. Thanks for your quick  response.

**Comment by gabime** [comment]
I recommend using the better v1.x branch.

**Comment by gabime** [comment]
you can avoid it by not using the factory funcs at all, and just create the loggers directly.

**Comment by fmoessbauer** [comment]
Ok, doing it like that works:

```cpp
auto sink = std::make_shared<spdlog::sinks::stdout_color_sink_st>();
auto new_logger = std::make_shared<spdlog::logger>("console", std::move(sink));
```
Thanks for your assistance.
