### ISSUE TITLE
The spdlog project compile problem

### ISSUE THREAD

**Issue by jirotao** [gabime/spdlog#754]
I used Visual Studio 2013 to compile example project was faild and Visual Studio 2017  compile success . what caused it ?

**Comment by gabime** [comment]
It was fixed in the v1.x branch. Please try

**Comment by jirotao** [comment]
<img width="937" alt="_20180718140754" src="https://user-images.githubusercontent.com/30790340/42863961-5d70a774-8a97-11e8-9d7b-a678274587f3.png">

you can see what reason compile faild

**Comment by gabime** [comment]
I cannot reproduce this. Works in my vs 2013.
