### ISSUE TITLE
msvc_sink.h has erroneous override or wrong signature

### ISSUE THREAD

**Issue by garyo** [gabime/spdlog#755]
In msvc_sink.h (v1.x branch) there is this code:
```
...
class msvc_sink : public base_sink<Mutex>
{
...
    void sink_it_(const details::log_msg &, const fmt::memory_buffer &formatted) override
```
But the Visual Studio compiler complains that that does not override any base class methods. It appears to be right, since the base class defines `sink_it_` differently:
```
    virtual void sink_it_(const details::log_msg &msg) = 0;
```

`msvc_sink.h` seems to be the only sink with that second arg.

**Comment by gabime** [comment]
Right. Thanks for reporting.

**Comment by gabime** [comment]
Fixed.
