### ISSUE TITLE
Question: stdout/stderr loggers synchronization

### ISSUE THREAD

**Issue by oblitum** [gabime/spdlog#76]
By walking the code-base I've checked that differently named console loggers like `spd::stdout_logger_mt("A")`, `spd::stdout_logger_mt("B")`, `..`. seem to create a `stdout_sink_mt` for each. Each will be protected by independent `std::mutex`s right? So,

- Is it expected for these default multi-threaded stdout loggers not to be synchronized?
- If so, isn't this worth to be explicitly documented?

I ask this because if this is the behaviour that has been implemented, it's quite likely that a user will not expect that by having multiple named multi-threaded stdout loggers they won't be in sync solely because of their name.

**Comment by gabime** [comment]
Right. It should be made clear in the docs.
The user can use same stdout logger by using spdlog::get("A") to solve this.
Thanks for reporting.

**Comment by oblitum** [comment]
@gabime not sure what you meant by solving it using `spdlog::get(`A`)`. Can the user rename it to start logging using a different name? Although I don't think this is a good usage to achieve that. If you doesn't mean that, then I don't see what benefit for the problem.

Also, initially, what I think that's the more expected, at last it's what I was expecting initially (I'm even using another synk that I've implemented that ends up doing this) is that differently named logger of the same type share a single lock.

This because, my first impression was that by using a mt stdout class, I would be being protecting in any case regarding writing to the stdout, not regarding the object instance. Anyway, you should ponder what makes more sense.

**Comment by oblitum** [comment]
updated comment.

**Comment by gabime** [comment]
I think maybe to change this function (stdout_logger_mt) to always use same static instance of the "stdout_sink_mt" 

We'll see..

**Comment by oblitum** [comment]
I think you may hit the issue I'm facing now personally. Trying to provide a simple setup header only lib while having to have a static instance of something. For a C++ header only library it seems infeasible since anything static must have a definition and it can't be in a header...

**Comment by gabime** [comment]
Actually it works if you declare a static variable inside an inline class function. This is how the global registry static instance works in spdlog and i haven't seen any issues(yet)

**Comment by oblitum** [comment]
@gabime this is exactly what I was thinking now, since you already have a registry. Is there a name for this technic/pattern/idiom?

It could be listed at http://en.wikibooks.org/wiki/More_C%2B%2B_Idioms =)

**Comment by oblitum** [comment]
@gabime Particularly it's the first time I'm seeing a way out to have a header only library with something static declared.

**Comment by gabime** [comment]
http://stackoverflow.com/a/11711082

**Comment by oblitum** [comment]
Thanks for the link.

**Comment by oblitum** [comment]
@gabime I guess you may already know it, but just in case, it's not necessary to involve a class/struct for this. Free inline functions support static variables that can be used to return state so... it's the simplest case I guess.

**Comment by gabime** [comment]
Right. This is a nice trick

**Comment by oblitum** [comment]
@gabime Yeah, the only problem is when the intent of creating a simple header only setup strucks out when the need for using the lib in, for example, both inside a executable, as well as in a shared library. Since the executable depends on the shared library, but both logging facility, even using same header, won't be sharing registry or anything.

**Comment by gabime** [comment]
Maybe, I didn't try this setup. I am not sure what would happen.

**Comment by oblitum** [comment]
@gabime as each executable (shared library and application) are compiled separately, both should have a working and independent spdlog, both will be compiled with their own registry, etc.

**Comment by oblitum** [comment]
@gabime they won't be in sync except if properly orchestrated.

**Comment by oblitum** [comment]
by the way, this may be a good item for FAQ or README, that it isn't best suited for use by independently compiled binaries that depend/load one another since it's header only.

**Comment by gabime** [comment]
Fixed in 2a0d00929cb6795bdf2c7a81ae7d5ec55bbb3662

Now ```stdout``` loggers all share same sink.
Please confirm it solved your problem

**Comment by oblitum** [comment]
Will do asap.

**Comment by oblitum** [comment]
To tell the truth. I'm assuming it's ok the same way I've assumed it wasn't. I've solely verified the problem analysing the code and not by finding issues through tests. So I assume it's theoretically fine.

**Comment by gabime** [comment]
Ok. Thanks for this
