### ISSUE TITLE
UTF-8 output on Windows?

### ISSUE THREAD

**Issue by YukinoHayakawa** [gabime/spdlog#762]
wincolor_sink uses WriteConsoleA to write output, which AFAIK can't handle UTF-8. Should we convert the buffer to UTF-16 and use WriteConsoleW instead?

**Comment by gabime** [comment]
Maybe.. spdlog never tried to deal with  wchars in the windows console.

**Comment by YukinoHayakawa** [comment]
I'm thinking of of whether this change will break existing code. Maybe add another sink implement (like wincolor_utf8_sink) would be better?

**Comment by gabime** [comment]
There is already an optional  ```SPDLOG_WCHAR_TO_UTF8_SUPPORT``` macro.
So maybe a workaround would be:
```c++
#ifdef SPDLOG_WCHAR_TO_UTF8_SUPPORT
WriteConsoleW(..)
#else
WriteConsoleA(..)
#endif

**Comment by YukinoHayakawa** [comment]
I'm afraid they are not dealing with exactly the same thing. I already have UTF-8 `char`-based strings as params & format string. I only hope they can reach the terminal without being treated badly.

**Comment by gabime** [comment]
Yes but still, WriteConsoleW should be used instead.

**Comment by YukinoHayakawa** [comment]
Yes.

**Comment by polesapart** [comment]
WriteConsoleA can be used to handle utf8 just fine. In fact, if your application doesn't use wide strings at all and you decide to use WriteConsoleW, you'd first need to copy-convert all your console-targeted strings to widechar, which can have a huge performance hit, specially if it involves allocation/deallocation.

What you'd need to do to pass utf-8 to WriteConsoleA is set windows console to expect it, before using it.

There are three aspects to consider: 

- Text  that your application will pass to console (windows has to expect it in utf-8),
- How console will try to render it (you need a windows font that has enough glyphs for most of utf8), and: 
- How the rest of your application will handle that (if you have writers to console, other than spdlog).

Something like the following will deal with the first two issues, and I'll leave the third as an exercise to the reader as it fall out of our context:
```
SetConsoleOutputCP(CP_UTF8);
CONSOLE_FONT_INFOEX cfi;
  cfi.cbSize = sizeof cfi;
  cfi.nFont = 0;
  cfi.dwFontSize.X = 0;
  cfi.dwFontSize.Y = 14;
  cfi.FontFamily = FF_DONTCARE;
  cfi.FontWeight = FW_NORMAL;
  wcscpy_s(cfi.FaceName, LF_FACESIZE, L"Lucida Console");
  if (SetCurrentConsoleFontEx(GetStdHandle(STD_OUTPUT_HANDLE), FALSE, &cfi) == 0) {
    // handle error
  }
```

**Comment by YukinoHayakawa** [comment]
@polesapart AFAIK the -A functions are wrappers that convert strings from current code page to UTF-16 and call the corresponding -W functions. Doesn't this means that the conversion happens anyway? Or am I getting anything wrong?

**Comment by polesapart** [comment]
Actually, you're right - as a rule, winnt backends are traditionally UCS-2 (a somewhat poor UTF-16 subset with some (very) slow pace evolving to UTF-16 compliance) and anything other than that have a conversion layer. 

I'm not sure if console output would be any sort of exception, but we can assume not.

That said, you still have to consider whether or not it makes sense for your application to do the conversion by itself. If you interface with windows api only rarely I don't see the point, i.e. you can assume the windows layer will do it as good as you would (except where it's buggy, i.e. the filesystem naming can bite, there are APIs with two code pages involved, etc.). 

On the other hand if you do most of your string-related work in utf-16, then there's no question, just go for the "W" api . 

There were days where UTF8 support in windows was somewhere between nonexistent or poor and buggy, but that's changing.You may take a read at http://utf8everywhere.org/ if you're interested in some followups.

**Comment by YukinoHayakawa** [comment]
Thank you for your detailed explanation. I actually have read the website before (that's part of the reason that I use UTF-8 in my project). I currently aren't gonna do any benchmark on the issue. If I noticed any performance issue due to the conversion, I'll update in another comment.

**Comment by gabime** [comment]
@polesapart Yes. Can confirm. it worked for me just by adding 
```c++
SetConsoleOutputCP(CP_UTF8);
```
somewhere once before using:
```c++
#pragma execution_character_set( "utf-8" )
#include "spdlog/sinks/stdout_color_sinks.h"
int main()
{
	SetConsoleOutputCP(CP_UTF8);
	auto c = spdlog::stdout_color_mt("cons");

	SetConsoleOutputCP(CP_UTF8);	
	c->info("Testing unicode -- English -- Ελληνικά -- Español param = {}", "Русский");
}
```

I guess ```SetCurrentConsoleFontEx()``` might be also needed sometimes as you noted..

**Comment by polesapart** [comment]
@gabime Good  to know. Perhaps recent windows editions have better default fonts - or they have more glyphs. When I first tried it was back in windows 7 days and that code is there since then.

**Comment by YukinoHayakawa** [comment]
If we come to use SetConsoleOutputCP for UTF-8 output maybe we can add a flag for it? If it is a good idea I can send a pull request later. But there still left a problem that whether SetConsoleOutputCP affect the programs running after the one using spdlog in the same console.  If so the end user might be surprised that the code page is changed. Or we have to revert the change made using SetConsoleOutputCP before exit.

**Comment by gabime** [comment]
I am not sure it is good idea. This is too much specific need, and can be easily fixed in the client code.
