### ISSUE TITLE
Doesn't compile on with SPDLOG_WCHAR_TO_UTF8_SUPPORT

### ISSUE THREAD

**Issue by kleuter** [gabime/spdlog#763]
Hi, just updated to the latest version and it doesn't compile on VC2013 (though it's declared).

```cpp
std::wstring s;
spdlog::get("async_file_logger")->info(L"This is a text {}", s);
```

[compile.log](https://github.com/gabime/spdlog/files/2216185/compile.log)

**Comment by gabime** [comment]
Seems like an fmt library issue. Please open a ticket in its repo (https://github.com/fmtlib/fmt)

**Comment by gabime** [comment]
spdlog has only limited support for wchars: only the log message can be wchar - not the args unfortunatly.

This works:
```c++
#define SPDLOG_WCHAR_TO_UTF8_SUPPORT
#include "spdlog.h"
..
logger->info(L"This is a text {}", "HELLO");
```

but this not:
```c++
logger->info(L"This is a text {}", L"HELLO");
```

**Comment by kleuter** [comment]
Thanks for the answer. May I create a feature request then?

**Comment by gabime** [comment]
Sure..

**Comment by gabime** [comment]
Moved to feature request #764
