### ISSUE TITLE
Missing #include

### ISSUE THREAD

**Issue by en-em** [gabime/spdlog#765]
periodic_worker.h needs to #include <thread>. Otherwise the minimal example

        #include <spdlog/spdlog.h>

fails to compile with g++.

    In file included from ...src/spdlog/include/spdlog/details/registry.h:14:0,
                 from ...src/spdlog/include/spdlog/spdlog.h:11,
                 from test.cpp:3:
    ...src/spdlog/include/spdlog/details/periodic_worker.h:71:10: error: ‘thread’ in namespace ‘std’ does not name a type
         std::thread flusher_thread_;
              ^~~~~~
    
Edit: g++ 5.4 and 7.1

**Comment by gabime** [comment]
Fixed in 9d497d5afdfc48e40789750dd2270f37a4a508e7

Thanks for reporting.
