### ISSUE TITLE
Consider upgrade path for v1.x

### ISSUE THREAD

**Issue by arthur-tacca** [gabime/spdlog#767]
I am working on an application that uses spdlog and I am struggling to keep it working due to the API changes in the v1.x branch. There are a lot of dependencies for this applications and there are two ways developers can get them:

 * On Linux, my application's dependencies can all be found in Ubuntu 18.04's apt repositories, including the slightly old but perfectly acceptable spdlog 0.16.3. 
 * On Windows, we use vcpkg, which usually uses the most up to date release, and currently includes a slightly out of date revision from the v1.x branch.

The code to create a logger and a file sink is very simple and yet still suffers from three incompatible APIs:

    // 0.16.3
    #include <spdlog/spdlog.h>   // automatically includes <spdlog/sinks/file_sinks.h>
    using file_sink_st = spdlog::sinks::simple_file_sink_st;
    
    // vcpkg v1.x branch
    #include <spdlog/sinks/simple_file_sink.h>
    using file_sink_mt = spdlog::sinks::simple_file_sink_mt;
    
    // current v1.x branch
    #include <spdlog/sinks/basic_file_sink.h>
    using file_sink_mt = spdlog::sinks::basic_file_sink_mt;

I couldn't come up with one code base that worked with different versions of spdlog, so I tried writing different versions of the code, guarded by preprocessor directives. We instantiate the logger and sinks in a single .cpp file so this is not too painful.

    #if defined(SPDLOG_0_16_3)
    #include <spdlog/sinks/file_sinks.h>
    using file_sink_st = spdlog::sinks::simple_file_sink_st;
    #elif defined(SPDLOG_OLD_1x)
    // ... etc. ...

That is only from the file sink part of the logging code. I haven't even started on the bit of code that instantiates a logger (either an async one or a sync one depending on an application setting), which also seems to have changed API ("'async_logger': is not a member of 'spdlog'" – maybe I just need another `#include`). The stderr sink also seems to have a problem ("'formatted': is not a member of 'spdlog::details::log_msg'").

Problems with this:

 * There is no version macro in spdlog, except `SPDLOG_VERSION` which is a string so can't be used in `#if` statements (and because the includes depend on the version it really does need to be done at the pre-processor level rather than with `constexpr if` statements).
 * The only source of information I could find to produce a version macro is the version number exported with the CMake config. For 0.16.3 this is "0.16.3" (great!) but for the vcpkg 1.x revision it is also "0.16.3"! For the current 1.x branch this is "1.0.0", which is good because at least it is different from 0.16.x, but bad because it is likely to collide with the final release version of 1.0.

Some suggestions:

 * Ideally, make code that used public interfaces from 0.16.x work without modification in the final version of 1.x. E.g. add `using simple_file_sink_st = basic_file_sink_mt` or even rename that class back (the difference in meaning between "simple" and "basic" is extremely subtle compared to the impact of breaking code).
 * (Very similar to previous point.) Mandate a change to client code that will allow the same code to compile with old and new versions e.g. previously `#include <spdlog/sinks/file_sinks.h>` was not necessary but wouldn't hurt; in 1.x you could put a compatibility header there that includes the correct other headers and has any typedefs.
 * Consider adding a numeric version `#define` to simplify the process of writing code that works with different version of spdlog.

Thanks!

**Comment by gabime** [comment]
@arthur-tacca Thanks for the feedback.

Indeed, the latest and greatest v1.x has undergone lots of changes. The API changed a bit, but hopefully for good reasons and will stabilize very soon.
Why do you try to support 3 versions at once ? Just choose one version. I recommend the v1.x (official release very soon).

> There is no version macro in spdlog, except SPDLOG_VERSION which is a string so can't be used in #if statements..

Agreed, I will change it be be a more useful numeric ( major * 10000 + minor * 100 + patch):
```c++
#define SPDLOG_VER_MAJOR 1
#define SPDLOG_VER_MINOR 0
#define SPDLOG_VER_PATCH 0

#define SPDLOG_VERSION (SPDLOG_VER_PATCH*10000 + SPDLOG_VER_PATCH*100 + SPDLOG_VER_PATCH)
```

**Comment by arthur-tacca** [comment]
> Why do you try to support 3 versions at once ?

I don't really need 3 different versions, I just was just venting frustration after spending a bit of time on the problem, sorry :-) Mostly I wanted to demonstrate the effects of API changes so that you consider them during upgrades, although I am sure you already do.

For now, and in future, I am likely to support at most 2 versions at once: the most recent release version in vcpkg (soon 1.x presumably) and the version in the most recent Ubuntu LTS (currently 0.16). The change to a numeric scheme will make that a lot easier, so thank you for doing that (for 0.16 vs 1.0 I will just check `#ifndef SPDLOG_VERSION_MAJOR`; after that I'll actually use the numerical value). I will close this issue accordingly.
