### ISSUE TITLE
does SPD log have api to have logs with file size 

### ISSUE THREAD

**Issue by naveenpinto** [gabime/spdlog#768]
Hi 
  does SPD log have log file size? that is we have a log file written as logfile_001.log when 100mb is written then it writes to logfile_002.log and so on, after a 99 it comes back are rewrites logfile_001.log
can something like this be done with log file api's.

Regards
naveen

**Comment by gabime** [comment]
```c++
// Create a file rotating logger with 100mb size max and 99 rotated files
auto rotating_logger = spdlog::rotating_logger_mt("some_logger_name", "logs/rotating.txt", 1048576 * 100, 99);

```

**Comment by naveenpinto** [comment]
Hi Gabime, this is for rotating file logger, i want a async file logger to have this concept, how can i do this, i see async file logger dont have these examples, is there a best way to do this for async file logger to have this?

**Comment by gabime** [comment]
Please refer to the docs

**Comment by naveenpinto** [comment]
can we create a async rotating logger??? as shown below

spdlog::rotating_logger_mt<spdlog::async_factory>(mLoggerName, sFname, 1048576 * 100, 99);

**Comment by naveenpinto** [comment]
this is the statement i am using
auto mSpdLogger = spdlog::rotating_logger_mt<spdlog::async_factory>("test", "logger.log" , 1048576 * 100, 99);

**Comment by naveenpinto** [comment]
with the latest spd log code below function is not present
spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block, nullptr, std::chrono::milliseconds(500), nullptr);

how can we create a rotating logger that is async and has a flush interval, some examples on this will be nice :)

**Comment by gabime** [comment]
Ther are examples in the wiki docs and in examples/example.cpp

**Comment by naveenpinto** [comment]
![image](https://user-images.githubusercontent.com/10204541/43895350-a3917870-9bf2-11e8-9dde-4ae030dfcf76.png)

i get this error when i build the solution of example.sln, is there a way to solve this i am using VS 2015

**Comment by naveenpinto** [comment]
by changing the build tools i was able to compile, but the expected a file name error stands.
