### ISSUE TITLE
Invalid application of sizeof to incomplete type spdlog::details::thread_pool

### ISSUE THREAD

**Issue by wbthomason** [gabime/spdlog#769]
Using the current commit (7d38e2b), I've started receiving the above error in code that used to compile. From the log, the error occurs at https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/details/registry.h#L81. I first noticed this error on commit ce5c1c2, though unfortunately I'm not sure what the last working commit was (I know it was sometime after cdbf2e3?)

The simplest program that reproduces this behavior is:

```c++
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"

int main(void) {
  auto log = spdlog::stdout_color_mt("test");

  log->info("Hello!");
  return 0;
}
```

I'm happy to provide whatever details, etc. help with debugging! Thanks!

**Comment by wbthomason** [comment]
(Note that the bug is displayed in the above sample whether `stdout_color_mt` or `stdout_color_st` is used)

**Comment by gabime** [comment]
Hi,
Which compiler version are you using?

**Comment by wbthomason** [comment]
gcc 8.1.1, on Arch Linux.

**Comment by gabime** [comment]
Theres a missing include..

**Comment by gabime** [comment]
Fixed. Thanks for reporting!

**Comment by wbthomason** [comment]
Thanks!
