### ISSUE TITLE
Support for PID?

### ISSUE THREAD

**Issue by oblitum** [gabime/spdlog#77]
Currently the library supports thread ids but not PID. I think that even thought it's a repetitive information, it may be useful for later querying stored logs by PID. I'm asking since I see some other libraries support this, and I believe this is one of the reasons.

**Comment by gabime** [comment]
Sure. Good idea

**Comment by barboteur** [comment]
Hello.
We are also looking for this enhancement because it is the better way to distinguish logs from different processes which uses multithreading.
Thanks.

**Comment by gzliudan** [comment]
I need this feather also.

**Comment by gzliudan** [comment]
append PID to logger name can get this feather

**Comment by dsbaby** [comment]
I need this feather also.    and  how to append PID to logger name ???

**Comment by gabime** [comment]
Implemented in latest release. Use %P in the format string
