### ISSUE TITLE
Fatal error C1001 when compiling 

### ISSUE THREAD

**Issue by jonathansty** [gabime/spdlog#770]
I'm trying to include spdlog in a home project. But I keep getting following compile error:

`1>g:\personal\garage-game\garage-engine\engine\thirdparty\common\spdlog\spdlog\details\logger_impl.h(55): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'msc1.cpp', line 1516)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information (compiling source file ..\..\Garage-Engine\Engine\Source\Engine\Core\ConfigFile.cpp)
1>g:\personal\garage-game\garage-engine\engine\thirdparty\common\spdlog\spdlog\details\logger_impl.h(116): note: see reference to function template instantiation 'void spdlog::logger::log<const _Elem*>(spdlog::level::level_enum,const char *,const _Elem *const &)' being compiled
1>        with
1>        [
1>            _Elem=char
1>        ] (compiling source file ..\..\Garage-Engine\Engine\Source\Engine\Core\ConfigFile.cpp)
1>g:\personal\garage-game\garage-engine\engine\source\engine\core\configfile.cpp(23): note: see reference to function template instantiation 'void spdlog::logger::info<const _Elem*>(const char *,const _Elem *const &)' being compiled
1>        with
1>        [
1>            _Elem=char
1>        ]
1>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\CL.exe'
1>    Please choose the Technical Support command on the Visual C++
1>    Help menu, or open the Technical Support help file for more information`

This happens for every instantiation of a spdlog::logger::log using info or warn. I'm running vs2017.

Any ideas?

**Comment by gabime** [comment]
Thanks for reporting. 
Please provide spdlog version and some code to reproduce.

**Comment by jonathansty** [comment]
Hmmm, I might have made a slight mistake the first time getting the include files. Seems that now using the latest release it's working. I might have accidentally got the code  directly from the repo. Now I can't reproduce the same compiling issue I've had before...

**Comment by gabime** [comment]
Right, but it should work streight out of the spdlog repo.. If thats not the case, let me know please.

**Comment by jonathansty** [comment]
It's all working on latest now with vs2017. I suspect I just did something wrong with copying over the includes.

**Comment by kai-heine** [comment]
I'm getting the same error message and found a way to reproduce it. I'm using VS 2017 15.7.6 and spdlog v1.0.0.
The error happens when passing additional arguments to `spdlog::logger::log()` and compiling with `/std:c++17` or `/std:c++latest`. Here's a minimal example:
```c++
#include <spdlog/sinks/stdout_color_sinks.h>

int main()
{
    auto logger = spdlog::stdout_color_mt("test");
    logger->info("{}", 1);
}
```
This compiles when switching to `/std:c++14`. It also compiles when commenting out the call to `fmt::format_to(log_msg.raw, fmt, args...);` in line 64 of `spdlog/details/logger_impl.h`.
Seems to be a compiler bug.
