### ISSUE TITLE
MingGW under DevC++: Memory Leak on windows when multi threading - async logging

### ISSUE THREAD

**Issue by Taymindis** [gabime/spdlog#771]
```cpp
#include <iostream>

#define SPDLOG_FMT_PRINTF 1
#define MAX_THREAD 24

/*https://github.com/gabime/spdlog*/
#include "spdlog/spdlog.h"

static std::shared_ptr<spdlog::logger> file_logger = 0;
void async_logging();
void init_logger_in_instance();

int i;
BOOL running = TRUE;

void init_logger_in_instance() {
    fprintf(stderr, "%s\n", "init logging");
    size_t q_size = 8196; // queue size must be power of 2
    spdlog::set_async_mode(q_size, spdlog::async_overflow_policy::discard_log_msg, nullptr, std::chrono::milliseconds{10}/*flush interval*/, nullptr);
	file_logger = spdlog::rotating_logger_st("async_file_logger", "lasync_log", 1024 * 1024, 5);
    
}

unsigned __stdcall
async_logging(void *arg) {
	int z = 10000;
	int argint =*(int*) arg;
	while(z-- > 0) {
	    file_logger->info("%d - %s", argint, "Dummy log" );
    }
	return 0;
}

int main(int, char* []) {
	HANDLE threads[MAX_THREAD];	
	init_logger_in_instance();
    try {
    	for(i=0;i<MAX_THREAD;i++) {
			 unsigned tid;
    		 threads[i] = (HANDLE)_beginthreadex(NULL, 0, async_logging, &i, 0, &tid);
		    if (threads[i] == 0) {
		      fprintf(stderr, "Error while creating the thread: %s\r\n", strerror(errno) );
		    }
		}
		
		for(i =0 ; i< MAX_THREAD;i++) {
			WaitForSingleObject(threads[i], INFINITE);
		}	
    }
    catch (const spdlog::spdlog_ex& ex) {
        std::cout << "Log initialization failed: " << ex.what() << std::endl;
    }
    spdlog::drop_all();
}
```

Attached leak-report for details (Ran by Drmemory)
[leak-reports.txt](https://github.com/gabime/spdlog/files/2238071/leak-reports.txt)

**Comment by gabime** [comment]
Seems like false positive. Do you actually see memeory leak if you run it in a loop?

**Comment by gabime** [comment]
which spdlog version?

**Comment by Taymindis** [comment]
0.17.0 latest release

**Comment by gabime** [comment]
I just tried it in VS2017. Run this example in infinite loop. No memory leaks detected.

**Comment by Taymindis** [comment]
I’m using dev c++ to build the program. And using drmemory to check the error. How do you check the memory leak from vs2017?

**Comment by gabime** [comment]
I just followed your steps - run in an infinite loop for log time and observed the task manager.Does you dev++ uses mingw? which version?

**Comment by Taymindis** [comment]
this is my gcc/g++ version

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/4.9.2/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-4.9.2/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --disable-multilib --with-tune=generic --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib
Thread model: posix
gcc version 4.9.2 (GCC)

**Comment by Taymindis** [comment]
how can i show you in video？ i will make one minute clip to you

**Comment by Taymindis** [comment]
You manage to replicate the issue in MingW?

**Comment by gabime** [comment]
I didn't try. Buy I understand that dev c++ uses mingw, right?

**Comment by Taymindis** [comment]
Have tried to build with VS2017, no more memory leak

**Comment by gabime** [comment]
Tried on v1.x branch. Could not reproduce on mingw 64 bits.
