### ISSUE TITLE
Is there a way to reduced increased binary sizes caused by spdlog?

### ISSUE THREAD

**Issue by ossama-othman** [gabime/spdlog#774]
I noticed that some of my object file sizes increased significantly when I introduced logging through spdlog.   Comparing the sizes of simple "Hello World" programs compiled on my 64 bit Linux box with g++ 7.3, I get the following:

### Iostream Case
```c++
#include <iostream>

int main(int, char* [])
{
    std::cout << "Hello world!\n";
}
```
The sizes of the object file and linked program are:
```sh
$ g++ -O2 -save-temps=obj -o foo foo.cpp
$ size foo.o foo         
   text    data     bss     dec     hex filename
    164       8       1     173      ad foo.o
   2033     648     280    2961     b91 foo

```
### Spdlog Case
With spdlog the binary file sizes increase significantly:
```c++
#include <spdlog/spdlog.h>

int main(int, char* [])
{
    auto console = spdlog::stdout_color_mt("console");
    console->set_pattern("%v");
    console->info("Hello world!");
}
```
```sh
$ g++ -O2 -save-temps=obj -o bar bar.cpp -lpthread
$ size bar.o bar
   text    data     bss     dec     hex filename
  75183    4473    1521   81177   13d19 bar.o
  99498    5744    1616  106858   1a16a bar
```
Spdlog has been great for my use case, so I'm really hoping to be able to reduce the increase in binary sizes incurred by using it.  Is there a way to mitigate the large binary size increase?

Thanks for any help you can provide!

_Note: This question is similar to #429, but non-debug binary sizes are shown in my case._

**Comment by gabime** [comment]
Try using v1.x branch. It should reduce it because spdlog.h will include much less, and your code would need to include only the sinks it needs (see the examples).

**Comment by ossama-othman** [comment]
No luck.  The size actually increased with v1.x.  Adding the necessary sink header to the spdlog based "Hello World!" program I posted above so that I can use v1.x branch like so:

```diff
--- bar.cpp.orig        2018-08-03 10:50:29.605192756 -0700
+++ bar.cpp     2018-08-03 10:47:48.839780337 -0700
@@ -1,4 +1,5 @@
 #include <spdlog/spdlog.h>
+#include <spdlog/sinks/stdout_color_sinks.h>
 
 int main(int, char* [])
 {
```
results in an increase from the spdlog 0.16.3 based binary sizes I posted earlier.  Compiling the spdlog based code like so:

```sh
$ g++ -I/home/ossama/MaRC/spdlog/include -O2 -save-temps=obj -o bar bar.cpp -lpthread
```

results in the following sizes:

### spdlog 0.16.3 (via `libspdlog-dev` package on Ubuntu 18.04)
```
 text    data     bss     dec     hex filename
75183    4473    1521   81177   13d19 bar.o
99498    5744    1616  106858   1a16a bar
```

### spdlog v1.x (cloned from your GitHub repository)
```sh
   text    data     bss     dec     hex filename
 126716    4209     321  131246   200ae bar.o
 150158    5432     408  155998   2615e bar
```
`Data` and `bss` binary sections improved relative to 0.16.3, but the `text` section of the binaries increased by about 51% for the linked binary `bar`.

**Comment by gabime** [comment]
If the size is so important maybe try to strip it?

**Comment by ossama-othman** [comment]
Stripping the binaries won't change the size results I posted since the [size(1)](https://linux.die.net/man/1/size) command gives binary section sizes, not file sizes.  The same is true if debugging symbols are in the file, too.

```sh
$ ls -gG bar
-rwxrwxr-x 1 226824 Aug  3 11:06 bar
$ strip bar
$ ls -gG bar
-rwxrwxr-x 1 162448 Aug  3 12:51 bar
$ size bar
   text    data     bss     dec     hex filename
 150158    5432     408  155998   2615e bar
```
The section sizes were unaffected by stripping the binary, as expected.

I'll just limit my use of spdlog to debug logging for now, and try to restructure general logging to inclusion of spdlog headers to a few files to minimize the increase in footprint.

Thanks again!

**Comment by gabime** [comment]
Ok. Thanks for the feedback and good luck.

**Comment by ossama-othman** [comment]
Thanks!   It was my pleasure.  I look forward to your upcoming changes.  Spdlog is a great library.
