### ISSUE TITLE
{fmt} version is not 5.0

### ISSUE THREAD

**Issue by gabyx** [gabime/spdlog#775]
Would you mind making `master`  compatible with the latest 5.1 version?

Because I would like to use fmt as an external library.  I' ve seen you have a header `fmt.h` where a macro decides if the internal bundled version is used or not. So far, I cannot use it, because its not 5.1

 Maybe it would be good if the bundled version has different include guards, such that an other external version used in a project (`#include <fmt/format.h>`) does not get in its way, but then we have to wrap the namespace `fmt` of the bundled version also in `spdlog` (or to simply replace it with `spdlog_fmt` to make it work and clean...

Thanks for you help :-)
Would that be a PR for you?

**Comment by gabime** [comment]
Please use tne v1.x. branch. It uses fmt 5.1 and is production ready.

**Comment by gabyx** [comment]
Perfect, do you also have another ReadMe on this branch which reflects the build status by travis for this branch? or is it still master  :-)

**Comment by gabime** [comment]
It builds v1.x
