### ISSUE TITLE
Easy way to share sinks between loggers?

### ISSUE THREAD

**Issue by DavidNemeskey** [gabime/spdlog#776]
Is there a way to easily share sinks between loggers? In my use-case, I create a "root" logger, and then make copies of it with different names for all sub-systems. The problem is that the only way I found for this is something like
```C++
std::shared_ptr<spdlog::logger> get_logger(std::string name) {
    root = spdlog::get("root");
    ...
    auto &registry_inst = spdlog::details::registry::instance();
    std::lock_guard<std::recursive_mutex>(registry_inst.tp_mutex());
    auto tp = registry_inst.get_thread_pool();
    auto sinks = root->sinks();
    std::shared_ptr<spdlog::logger> logger(new spdlog::async_logger(name, sinks.begin(), sinks.end(), tp));
    spdlog::details::registry::instance().register_and_init(logger);
    logger->set_level(root->level());
    return logger;
}
```

As you can see, the snippet above basically repeats the code from `spdlog::create_async`. It would be great if there was an "official" way of doing this, such as a `logger::clone(std::string new_name)` method.

**Comment by gabime** [comment]
Would be shorter  just to construct the async logger with the needed sinks, and then call spdlog::register_logger(..). No need to mess with the thread pool, etc.

**Comment by gabime** [comment]
> how do I construct the logger without the thread pool stuff?

simpler version(no need to lock on tp_mutex if you dont intend to modify it concrently):
```c++
..
auto tp = spdlog::thread_pool();
shared_ptr<spdlog::logger> logger(new spdlog::async_logger(name, sinks.begin(), sinks.end(), tp));
```
