### ISSUE TITLE
register_and_init() sets level to info

### ISSUE THREAD

**Issue by DavidNemeskey** [gabime/spdlog#777]
In my previous issue (#776), I found that if I switch the two lines of code:
```C++
spdlog::details::registry::instance().register_and_init(logger);
logger->set_level(root->level());
```
, i.e. to
```C++
logger->set_level(root->level());
spdlog::details::registry::instance().register_and_init(logger);
```
, then `logger` will have a `info` as its log level. Since `logger` also sets the level to `info` in its constructor, I see no reason why `register_and_init` should do it again, potentially overriding the user.

**Comment by gabime** [comment]
As its name impies and init the logger with default values. Use spdlog::register(..) to avoid this.

**Comment by DavidNemeskey** [comment]
Right, I missed that function (you meant `register_logger(...)`, right?). In my defense, it's not use anywhere in the examples. But of course, it explains the behavior that perplexed me.

**Comment by gabime** [comment]
> (you meant register_logger(...), right?)

Right
