### ISSUE TITLE
compiler wraning: no new line at end of file

### ISSUE THREAD

**Issue by baishuai** [gabime/spdlog#778]
spdlog is really an awesome log library. 

but there no new line in some source files, and it leads to compiler warnings.

**Comment by gabime** [comment]
where exactly?

**Comment by baishuai** [comment]
`fmt_helper.h`
`circular_q.h`
`thread_pool.h`

I used spdlog in an iOS project.

These three files have end of line, but xcode still give warnings.

after a add other new line at end of these three files, the warnings didn't show again.

**Comment by gabime** [comment]
please send a PR with the fix
