### ISSUE TITLE
syslog_logger is not a member of spdlog

### ISSUE THREAD

**Issue by rajesh-p** [gabime/spdlog#779]
I wanted to use spdlog to log into syslog. So, I tired using following line to create syslogger

`spdlog::syslog_logger("syslog", "syslog-example")` 

I also included syslog/sinks/syslog_sink.h and spdlog/spdlog.h

So, at time of compiling project I got following error

`syslog_logger` is not a member of spdlog`

I used following steps to install spdlog locally

1. git clone https://github.com/gabime/spdlog.git && \
   			     cd spdlog && \
   			     cmake -H. -B_builds -DCMAKE_BUILD_TYPE=Release && \
   			     cmake --build _builds --target install

**Comment by gabime** [comment]
use “syslog_logger_mt” (or _st)

**Comment by rajesh-p** [comment]
Thanks a lot, it worked for me.
