### ISSUE TITLE
Logger does not write to file even after `flush()`, until you end the program

### ISSUE THREAD

**Issue by patrikhuber** [gabime/spdlog#780]
Hi!

I've got more or less the following code:
```
auto logger = spdlog::basic_logger_mt("mylogger", "mylogger.log.txt");
logger->flush_on(spdlog::level::err);
try
{
	my_class = std::make_unique<my_class>(my_class::load("my_class.bin"));
} catch (const std::runtime_error& e)
{
	logger->error("std::runtime_error while loading: {}", e.what());
	logger->flush();
	throw;
}
```

However, this code does not write to the log file until I exit the program/exit debugging. So for example I would set a breakpoint on the line with the `throw;`, after the `flush()`, and it does not flush and write to the file (actually I would expect it to even flush without the `flush()` since I specified `logger->flush_on(spdlog::level::err);`). It only writes to the log file once I press Shift+F5 to stop the debugging. This makes the whole logging-thing sort-of useless to me, so I am sure I must be missing something? I read through the whole wiki-docs and couldn't really find anything related.

**Comment by gabime** [comment]
This is strange indeed. Which version of spdlog and compiler are you using?

**Comment by patrikhuber** [comment]
Thanks for the quick reply!
I did "git submodule add ...spdlog..." around a week ago, so I was at whatever branch/commit this results in (your default branch is `v1.x` now so I am not sure what branch this resulted in, master or `v1.x`). I switched/updated to the latest commit from the `v1.x` branch now - it shows it only updated by 10 commits, so I maybe already was on `v1.x`:

```
Submodule spdlog 986af6e..8179b26:
  > Update file_log.cpp
  > Update README.md
  > small fix to example.sln
  > Fixed async_bench
  > clang format
  > delay the release mutex in the async queue only for mingw
  > Added async_bench
  > Fix deadlock issue with mingw in async logger
  > Merge pull request #773 from slapenko/v1.x
  > Update README.md
```

I think the behaviour changed slightly now - `logger->error("...")` now seems to write to the log right away in one build configuration but it still doesn't in the other.
If this is not expected behaviour, then I think this might be related with the fact that I'm using this inside an Unreal Engine 4 (4.20.1) project. It is all compiling within Visual Studio and the MSVC compiler (I'm using VS 15.7.6 with its latest v14.14 toolset), but UE has its own build system and uses its own set of compiler flags, build configurations and everything (and it uses `/std:c++14` mode). It's an incredible pain in the ass.

Whereas before I pulled these latest commits, it wouldn't write to the log in all build configurations, it now seems to write to the log right away in the "DebugGame" configuration, but not in the "DebugGame Editor" configuration. Unreal Engine's documentation of all this is incredibly bad but one difference that I could make out is that in the "DebugGame" configuration, exceptions are disabled, while in the latter configuration, they're enabled.

But I kind of think that in principle neither disabled/enabled exceptions nor different compiler flags should cause spdlog to not flush the log when instructed to do so, so it's all a mystery to me. It's also reproducible and consistent, and not random or anything.

**Comment by gabime** [comment]
> in the "DebugGame" configuration, exceptions are disabled, while in the latter configuration, they're enabled.

If exceptions are disabled, while using a lib that usec exceptions, then all bets are off .. who knows whats the implications of this mix..

**Comment by patrikhuber** [comment]
Well interestingly, as I wrote, in the DebugGame configuration, it actually works now and the log seems to get written right away. The case that doesn't work is where supposedly exceptions are enabled in both the UE project as well as the lib.

> If exceptions are disabled, while using a lib that use exceptions, then all bets are off .. who knows whats the implications of this mix..

I think this is actually supported, you just need to make sure that the lib catches all exceptions internally, and no exceptions are thrown or leaked out of the lib.

**Comment by gabime** [comment]
Maybe try to debug and step in the code to see whats going on?

**Comment by patrikhuber** [comment]
Ok, I just did - all looks fine, the sink calls the code to write the message, it then goes into the right `if` branch to flush, gets to `flush_()` here https://github.com/gabime/spdlog/blob/85a2bf1c176cff55f3781a809387b8d2c65725b8/include/spdlog/sinks/base_sink.h#L42
(which looks like it calls `ucrtbase.dll!fflush()`, no more debug information at this point) - so all looks good, except that the log file doesn't update at that point (until I completely end the debugging).
Is this another peculiarity of the Unreal Engine? This thing is driving me crazy.

In the DebugGame configuration, the log updates right away as soon as it returns from `ucrtbase.dll!fflush()`.

Anyway... I think it pretty much looks like spdlog is doing what it should, and this is a weird thing that the Unreal Engine is causing. Not the first time...
So I think we can close this, unless you have some ingenious idea! :-)

**Comment by gabime** [comment]
ok. thanks for the update

**Comment by aisnote** [comment]
I meet this issue on VS2017. the code is from example:
mRotatingLogger = spdlog::rotating_logger_mt("lomoagent", "lomoagent.log", 1048576 * 5, 3);

mRotatingLogger->info(strMsg);

seems it will not write the log to file right away till end of the program. any ideas?

**Comment by tapika** [comment]
I have noticed exactly the same error. 
I've harvested docs and spdlog source codes, but did not get any clue why it would not work.
Using vs2017, 64bit compilation environment.

One thing I've noticed that in documentation there exists separate "c" flag, which apparently somehow reflects 
to fflush behavior. But when tried even with that flag - flush still did not work.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=msvc-160

**Comment by tapika** [comment]
But handle is opened with _wfsopen, and file_helper::flush() is called for each message, so it's not a bug of spdlog, but maybe windows port or windows platform.

**Comment by aiyolo** [comment]
so what's the solution for this issue?

**Comment by tapika** [comment]
Maybe raise ticket in here: https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+fopen

There are similar issues as well, maybe they can fix it.

Sorry for not raising this issue by myself, back then did not have a knowledge that posix issues can be still resolved via github ticket.
