### ISSUE TITLE
i get this error when i include the spd logger in my main program

### ISSUE THREAD

**Issue by naveenpinto** [gabime/spdlog#781]
i get this error when i include the spd logger in may main program

Severity	Code	Description	Project	File	Line
Error (active)		expected a file name	GExport	c:\Users\JNP014\Documents\Visual Studio 2015\Projects\staticlogger\staticlogger\spdlog\fmt\bundled\core.h	183

It points to this code 

// libc++ supports string_view in pre-c++17.
#if (FMT_HAS_INCLUDE(<string_view>) && (__cplusplus > 201402L || defined(_LIBCPP_VERSION))) ||                                             \
    (defined(_MSVC_LANG) && _MSVC_LANG > 201402L && _MSC_VER >= 1910)
#include <string_view>
#define FMT_USE_STD_STRING_VIEW
#elif (FMT_HAS_INCLUDE(<experimental / string_view>) && __cplusplus >= 201402L)
#include <experimental/string_view>
#define FMT_USE_EXPERIMENTAL_STRING_VIEW
#endif

has anyone encountered this????

**Comment by gajanak** [comment]
Perhaps this helps you: (I don't use msvc)
__has_include ( < filename > )  Syntax need c++17.  Perhaps the check should be rotated for pre-c++17 support of string_view.  ;)

**Comment by naveenpinto** [comment]
HI 
  i am not very clear on what exact code change that needs to be done to remove this error, can you please elaborate.

i am still seeing these error on VS C++ 2015

![image](https://user-images.githubusercontent.com/10204541/44573055-3d9ce380-a7a3-11e8-9d58-7c3606ab4578.png)

**Comment by naveenpinto** [comment]
@gabime i have logged this issue on fmtlib, hope i get a fix, but some one should have encountered it using spdlog.

https://github.com/fmtlib/fmt/issues/842

**Comment by naveenpinto** [comment]
@gabime i do get this error even with the examples solution bundled in spdlog with visual studio 2015, this is a concern for us to use spd log in production, i have raised a bug on fmtlib.
