### ISSUE TITLE
error: use of undeclared identifier 'fmt_helper'; did you mean 'details::fmt_helper' in android_sink.h

### ISSUE THREAD

**Issue by rajesh-p** [gabime/spdlog#785]
I am getting above error while using android_sink with ndk. There are two more error, use of undeclared identifier 'formatter_' did you mean 'formatted'.

member reference type 'fmt::memory_buffer' is not pointer \

**Comment by rajesh-p** [comment]
android_sink.h:46:13 fmt_helper::append_buf(msg.raw, formatted);
android_sink.h:50:13: error: use of undeclared identifier 'formatter_'; did you mean 'formatted'?
android_sink.h:50:23: error: member reference type 'fmt::memory_buffer' (aka 'basic_memory_buffer<char>') is not a pointer; did you mean to use '.'?

**Comment by rajesh-p** [comment]
Found solution, 
For line 46, add details::fmt_helper::append_buf(msg.raw, formatted);
for line 50, replace line with sink::formatter_->format(msg, formatted);

**Comment by gabime** [comment]
Thanks for reporting and finding a solution. 
A PR would be appreciated.

**Comment by rajesh-p** [comment]
Yes, will do that.

**Comment by gabime** [comment]
Fixed in #786. Thanks @rajesh-p
