### ISSUE TITLE
set_pattern not consistent

### ISSUE THREAD

**Issue by jade2k11598** [gabime/spdlog#788]
I've picked up the latest version (1.0.0) and I've setup my speed log with a specified pattern.  This logger is a singleton and writes to two sinks (console and file).  I'll have multiple loggers that will uniquely identify the various modules using this singleton logger.

Initially I had set the pattern from the two sinks, so that all logs to file and console were consistent in format:  
```
        auto file_sink =
            std::make_shared<spdlog::sinks::rotating_file_sink_mt>("/tmp/MyTest.log", 10240, 10);
        file_sink->set_pattern(m_log_pattern);
        auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        console_sink->set_pattern(m_log_pattern);
```
where m_log_pattern is std::string that is set to ```m_log_pattern("%^%Y-%m-%d-%X.%f %L T%t %n %v%$")```
But that never worked.  So instead of setting the pattern via sinks, I set the pattern for every logger and _most of the time_ this worked.  There seems to be this race condition at startup:
```
2018-08-10-14:28:10.570978 I T016310 IOService This thread started
2018-08-10-14:28:10.571005 I T016311 IOService This thread started
2018-08-10-14:28:10.571036 I T016312 IOService This thread started
[2018-08-10 14:28:10.571] [IOService] [info] This thread started
2018-08-10-14:28:10.571358 I T016308 main Press [return] to exit

```
The first 3 logs is correctly formatted by the specified pattern, but the 4th one doesn't (it seems to be the default patterned used).  The first 4 logs is the results of executing the same line of code (just different threads), which is referencing this singleton logger (my singleton is the Meyer's Singleton using modern C++).

Is there something wrong I'm doing?  This behavior is intermittent.

Ideally I"d prefer to just set the pattern using the sinks for all loggers, but I never got that to work.  I did notice that the problem _seems_ to go away if I set the pattern not only with each loggers but the sinks as well.  It's hard for me to tell if the problem completely goes away doing it this way because it seems to be an intermittent behavior.

I'm guessing that one shouldn't have to set the pattern on all sinks _and_ loggers just to get a consistent pattern for all loggers going into the various sinks ...

OK, I just ran more test and setting the pattern on the sinks and the loggers does not make this problem go away.

**Comment by gabime** [comment]
I took a look at the example. ```registry_inst.register_and_init(logger)``` in line 37 is your problem. As its name implies, “register_and_init” also initiates the logger with a default values. You should use “spdlog::register_logger(logger)” instead. Also, try not to use the details::registry - it is an internal class, and the public API should be sufficient for all your needs.

**Comment by jade2k11598** [comment]
That's solved it!  That appeared to not just fix setting the pattern at one place (just the sinks and not just all loggers), but it looks like it also fixed the intermittent behavior!  At least I can't seem to reproduce that problem anymore with now calling ```spdlog::register_logger```.

Thanks!  Sorry for wasting your time!

**Comment by gabime** [comment]
np, and good luck.

**Comment by jade2k11598** [comment]
One more question.  Does the set_level, also behave like the set_pattern?  Because I also want to formalize all the loggers to the same log level.  So now, I have simplified my logger ctor to have the 2 sinks set the pattern as well as the set_level:
```
    MyLogger()
        :m_log_pattern("%^%Y-%m-%d-%X.%f %L T%t %n %v%$"),
         m_tp(),
         m_sinks(),
         m_logger()
    {
        // 2^12 = 4096 2^13=8192 2^15=32768 2^16=65536 2^20=1048576 2^21=2097152
        size_t queue_size = std::pow(2, 20);
        
        // Need to create thread pool
        auto &registry_inst = spdlog::details::registry::instance();        
        m_tp = std::make_shared<spdlog::details::thread_pool>(queue_size, 1);

        auto file_sink =
            std::make_shared<spdlog::sinks::rotating_file_sink_mt>("/tmp/MyTest.log", 10240, 10);
        file_sink->set_pattern(m_log_pattern);
        file_sink->set_level(spdlog::level::trace);
        
        auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        console_sink->set_pattern(m_log_pattern);
        console_sink->set_level(spdlog::level::trace);
        
        m_sinks.push_back(file_sink);
        m_sinks.push_back(console_sink);
        m_logger = RegisterLogger("main");        
    }
```
And that RegisterLogger function is now simplified to this:
```
   spdlog_logger RegisterLogger(const char *name)
    {
        auto logger = std::make_shared<spdlog::async_logger>(name, m_sinks.begin(),
                                                             m_sinks.end(), m_tp);
            
        // logger->set_level(spdlog::level::trace);
        spdlog::register_logger(logger);
        return logger;
    }
```
where I have commented out the logger setting the log level.  But it looks like that will only log levels info and above to file and console, if done that way.

If instead I set the log level for each logger, (uncomment that one line in ```RegisterLogger```), then I can see all the log levels in the file and console ....

**Comment by gabime** [comment]
logger ps and sinks can have different levels, so it makes sense.
