### ISSUE TITLE
CMake targeting - fatal error during compilation

### ISSUE THREAD

**Issue by inglor** [gabime/spdlog#790]
I'm trying to use the spdlog and i follow the instructions on the README but project fails to compile.

You can check the very simple project at https://github.com/inglor/test-spdlog using the example.cpp

The error during compilation is
```
In file included from /home/inglor/workspace/test-spdlog/main.cpp:5:
/home/inglor/workspace/test-spdlog/spdlog/spdlog.h:13:10: fatal error: spdlog/version.h: No such file or directory
 #include "spdlog/version.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

It used to be the case that before v1.0.0 it was referencing the includes with relative paths - but it's not the case now.

**Comment by gabime** [comment]
maybe try to add to the cmake  
```
add_library(spdlog INTERFACE)
target_include_directories(spdlog INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}")
```

**Comment by inglor** [comment]
@gabime No, no luck with that.

**Comment by xorz57** [comment]
This didn't work for me.
