### ISSUE TITLE
Support creation of async logger with multiple sinks

### ISSUE THREAD

**Issue by lfrlucas** [gabime/spdlog#794]
Hi,
I want to create an async logger with multiple sinks. While the wiki shows a manual procedure to combine multiple sinks for a sync logger, there is no example for async loggers. 
Is there any limitation preventing the use of multiple sinks on an async logger?
If not, the solution is simply to reimplement the create method of async_factory_impl struct using the  async_logger constructor that receives a list of sinks?
Thanks.

**Comment by lfrlucas** [comment]
Excellent answer. Thank you.

**Comment by gajanak** [comment]
It is important that in this way register_logger is called, and if factory is used register_and_init is used ?
I'm searching the reason, that if i create a async logger with mutliple syncs... 
SPDLOG_NO_NAME  is not used anymore ... ?

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@gabime This works. Thank you.
