### ISSUE TITLE
Question: changing log level at runtime

### ISSUE THREAD

**Issue by fabiomargarido** [gabime/spdlog#80]
Hi.

Sorry if this is a dumb question, but it isn't immediately obvious from the documentation and the code how to change the log level at runtime.

Is it possible, and if it is, how do I do it?

Thanks

**Comment by gabime** [comment]
Sure either ```spdlog::set_level(...);``` for global level
or ```logger->set_level(...);``` for specific logger

**Comment by fabiomargarido** [comment]
I meant changing the active log level of a running binary, like you would for example with log4cplus by changing the configuration file, which is automatically reloaded.

**Comment by gabime** [comment]
There is no config file for spdlog. 
So the user should implement whatever mechanism it wants and call set_level(..) to change at runtime

**Comment by fabiomargarido** [comment]
Yeah, the config file was just an example. One other way I've seen this done is to cycle the active level upon reception of SIGUSR1, but I'm not sure how to achieve this in a portable way.

It would still be nice to have support for this kind of feature in the library, if you want to analyze running production code.

**Comment by gabime** [comment]
Yes. Very useful indeed..
I think config file reloading is the way to go for this

**Comment by fabiomargarido** [comment]
Sorry to bother, but if this is related to a feature that would be interesting to have, wouldn't it make more sense to tag this issue 'enhancement' or 'wishlist' and keep it open for reference?

**Comment by gabime** [comment]
Agreed

**Comment by BYugandhar** [comment]
I am also facing same issue

**Comment by fabiomargarido** [comment]
To whom it might interest: I ended up using served (https://github.com/datasift/served) to build a REST API which I could then consume from anywhere to interact with the running binary log configuration, since there is (or at least there was a year ago) no built-in way of doing it using only spdlog.

**Comment by facontidavide** [comment]
My two cents.
It is hard to have a one-fit-all solution that can be merged into spdlog, since any user might want to use a different Inter Process Communication or transport mechanism to set this from the "outside".

REST API, Linux pipes, ROS, ZeroMQ... any RPC or messaging system will do.
It would be very confusing (and opinionated) to add one of these to spdlog.

**Comment by PuneetPatwari** [comment]
Looking for same functionality where log levels can be changed at runtime without re-compiling the code.

**Comment by smohanty92** [comment]
ANY Update on this?

I'm trying `void handle_sigusr2(int signum) {
	SPDLOG_WARN("SIGUSR2 received, toggling log level");
	spdlog::set_level(spdlog::level::trace);
}`

but it's not updating at runtime
