### ISSUE TITLE
fmt::v5::format_error at executable loading

### ISSUE THREAD

**Issue by BotellaA** [gabime/spdlog#802]
Great v1 release but I get an exception at library or executable loading that I did not have before. Here is a snippet:
```
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"

namespace
{
    struct test
    {
            test()
            {
                spdlog::stdout_color_mt( "console" )->info( "test" );
            }
    } instance;
}

int main()
{
    return 0;
}
```
Here is the error message:
```
terminate called after throwing an instance of 'fmt::v5::format_error'
  what():  argument index out of range
Abandon (core dumped)
```
Thanks for your help!

**Comment by BotellaA** [comment]
What would you recommand to log something at loading? Do you know why it was working before v1?

**Comment by gabime** [comment]
> Do you know why it was working before v1?

 
I am not sure. Too many changes. why not just log at start of main()?

**Comment by BotellaA** [comment]
My goal is to log at library loading where each library would be a plugin of a larger app. Having an automatic logging at library loading is the easiest way I found.

**Comment by dsalnikov** [comment]
@BotellaA, @gabime, Am I right that spdlog relies on static initialization? 
So it can't be used safely in case we want to use it in static class?

**Comment by BotellaA** [comment]
It can be used in a static class. Here is my logger ([h](https://github.com/Geode-solutions/OpenGeode/blob/master/include/geode/basic/logger.h)/[cpp](https://github.com/Geode-solutions/OpenGeode/blob/master/src/geode/basic/logger.cpp))
