### ISSUE TITLE
error: macro "index" requires 2 arguments, but only 1 given          , index(0)

### ISSUE THREAD

**Issue by yRezaei** [gabime/spdlog#805]
In ubuntu 18.4, with the C++17 standard. Just by including "spdlog/sinks/basic_file_sink.h" file, I got the following error:
..../spdlog/fmt/bundled/format.h:2330:18: error: macro "index" requires 2 arguments, but only 1 given
         , index(0)
                  ^
..../spdlog/fmt/bundled/format.h:2335:22: error: macro "index" requires 2 arguments, but only 1 given
         , index(index)

any idea?

**Comment by gabime** [comment]
Pleas post small example to reproduce.

**Comment by yRezaei** [comment]
The code that I have is too big and I am not allowed to show it. But, I just noticed that the error only happening in this big project and not in a simple program. Probably I have something somewhere in my code which "spdlog" doesn't like it. I will check it out and put the issue here.
