### ISSUE TITLE
Incompatible with nvcc

### ISSUE THREAD

**Issue by Kur0x** [gabime/spdlog#807]
`
include/spdlog/details/pattern_formatter.h:357:66: error: expected primary-expression before ‘const’
     log_clock::time_point last_update_{std::chrono::seconds(0)};
`
can not compile with nvcc

**Comment by amanbora** [comment]
@gabime could you please share some more info about the issue, I would like to contribute to this bug.

**Comment by gabime** [comment]
@amanbora  Thanks. I didnt have time to look into it and see why it doesn't dompile.

**Comment by lahwaacz** [comment]
I've been able to compile the [tests](https://github.com/gabime/spdlog/tree/v1.x/tests) with nvcc 10.0 just fine. nvcc 9 would probably work too, but nvcc 8 and older are very buggy when it comes to C++11 conformance (it often fails to compile a valid C++11 host code, not just device code).

**Comment by gabime** [comment]
@lahwaacz Thanks great. Thanks. I will close this issue then,

**Comment by jwmelto** [comment]
Is it better to re-open this or write a new issue?
With **nvcc** 12.1, simply including `<spdlog/spdlog.h>` results in this error:

```
/opt/foss/include/spdlog/fmt/bundled/format.h(4163): error: a literal operator template must have a template parameter list equivalent to "<char ...>"
  template <detail_exported::fixed_string Str> constexpr auto operator""_a() {
                                                              ^
```

Maybe when GCC finally supports `std::format` this will go away?

(I should probably note this was built against tag **v1.11.0**)

**Comment by tt4g** [comment]
@jwmelto `include/spdlog/fmt/bundled/format.h` copied from [fmt repository](https://github.com/fmtlib/fmt).
Please open a issue in fmt project,
