### ISSUE TITLE
Increment the name of an existing logger

### ISSUE THREAD

**Issue by zippy84** [gabime/spdlog#808]
I'm planning to use spdlog in https://github.com/zippy84/vtkbool and I have a question about an existing logger. This is the code within my constructor:

```cpp
try {
    spd::set_level(spd::level::debug);
    logger = spd::basic_logger_st("logger", "logs/vtkbool.log", true);
    logger->set_pattern("[%l] %v");
} catch (...) {
    logger = spdlog::create<spdlog::sinks::null_sink_st>("logger");
}
```

In a second instance of my class spdlog throws

```
terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  logger with name 'logger' already exists
```

Is there a **simple** way to append a number to the name of the logger, if the logger already exists?

**Comment by gabime** [comment]
You can use spdlog::get(“loggername”). It will return nullptr if it doesn't exist.

**Comment by LeKristapino** [comment]
I have a similair issue, but with all the guards. When I compile it on my host computer, the app works just fine, but when being compiled in a docker container, it shows the error 
>terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  logger with name 'logger' already exists

I use vcpkg to install spdlog and have checked that both -host computer and docker container use the same version - 1.8.5

Relevant code here..

```cpp
inline void setup() {
    //create vector of spdlog sinks
    std::vector<spdlog::sink_ptr> sinks;
    //create a sink for terminal output and log output
    sinks.push_back(std::make_shared<spdlog::sinks::stdout_color_sink_mt>());
    sinks.push_back(std::make_shared<spdlog::sinks::daily_file_sink_mt>("log/logger", 0, 0, false, 10));

    //combine sinks, register new, combined sink and make it default logger
    std::shared_ptr<spdlog::logger> combined_logger = std::make_shared<spdlog::logger>("logger", begin(sinks), end(sinks));
    spdlog::register_logger(combined_logger);
    //set log level and formatting pattern

    //"trace", "debug", "info", "warning", "error", "critical", "off"
    combined_logger->set_level(spdlog::level::from_str("debug"));
    combined_logger->flush_on(spdlog::level::level_enum::trace);
    combined_logger->set_pattern("%^ %-10D | %-2H:%-2M:%-2S | %-8l |%$ [%t] %-64v");
  }

  inline auto logger() {
    if(!spdlog::get("logger")) {
        setup();
        return spdlog::get("logger");
    } else {
        return spdlog::get("logger");
    }
  }

  template <typename FormatString, typename... Args>
  inline void trace(const FormatString &fmt, Args &&...args)
  {
    logger()->trace(fmt, std::forward<Args>(args)...);
  }

....
```

**Comment by gabime** [comment]
This might be a race condition if several threads call `logger()` at same time.

**Comment by LeKristapino** [comment]
As I understand the object does not appear in multiple threads. That's the reason why I had to make it this way - to get the same logger config to work on all the threads in the app. but it works fine in host compiled program so I'm confused what the difference might be

**Comment by gabime** [comment]
Not sure what you mean. If the are multiple threads this is probably the issue. Just try to surround body of your logger() function with a lock and see if this solves this.

**Comment by LeKristapino** [comment]
@gabime 

this version seems to work. Is it better to do a mutex or this?
```cpp
 inline auto logger() {
    if(!spdlog::get("logger")) {
      try {
        setup();
      } catch (const std::exception & e) {
          return spdlog::get("logger");
      }
        return spdlog::get("logger");
    } else {
        return spdlog::get("logger");
    }
  }
```

**Comment by gabime** [comment]
This doesn't look good. Go for the mutex.

**Comment by LeKristapino** [comment]
I'm having troubles implementing mutex the way I've designed the logger. But now I'm focusing on how to get the exact same version of spdlog through vcpkg on both - host computer and docker container. Because this seems to be an issue that is happening on one compiled version, but does not happen on the other. My guess is that those are actually 2 different spdlog versions used, even though in CONTORL They both show the same version, but different ABIs

host computer:
```
Package: spdlog
Version: 1.8.5
Depends: fmt, vcpkg-cmake, vcpkg-cmake-config
Architecture: x64-linux
Multi-Arch: same
Abi: 64f56e3efc3c6c0ac5ebe4923d92948a720cf10d
Description: Very fast, header only, C++ logging library
Type: Port
```

Docker container
```
Package: spdlog
Version: 1.8.5
Port-Version: 3
Depends: fmt, vcpkg-cmake, vcpkg-cmake-config
Architecture: x64-linux
Multi-Arch: same
Abi: 76a9ace1a4814b1fe081901ab01187fd2ad493c7867f45bab84d86663c414dc0
Description: Very fast, header only, C++ logging library
Type: Port

```
