### ISSUE TITLE
error C2440: “<function-style-cast>”: 无法从“initializer-list”转换为“fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::buffer>>::double_writer

### ISSUE THREAD

**Issue by Guozht** [gabime/spdlog#809]
2	error C2440: “<function-style-cast>”: 无法从“initializer-list”转换为“fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::buffer>>::double_writer”	e:\commhelper\include\spdlog\fmt\bundled\format.h	3594	1
3errorC2780: “voidfmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::buffer>>::write_padded(size_t,const fmt::v5::align_spec &,F)”: 应输入 3 个参数，却提供了 2 个	e:\commhelper\include\spdlog\fmt\bundled\format.h	3594	1
4	error C2440: “<function-style-cast>”: 无法从“initializer-list”转换为“fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::wbuffer>>::double_writer”	e:\commhelper\include\spdlog\fmt\bundled\format.h	3594	1
..................................
10	IntelliSense:  namespace "fmt::internal" 没有成员 "dummy_int"	e:\CommHelper\Include\spdlog\fmt\bundled\format.h	425	37	
.......................................
16	IntelliSense:  namespace "fmt::fmt" 没有成员 "string_view"	e:\CommHelper\Include\spdlog\fmt\bundled\format.h	2950	78	
..................................

**Comment by Guozht** [comment]
code:simple project
compiler version:Visual Studio 2013 - Windows XP( v120_xp) or Visual Studio 2013 (v120)

**Comment by Guozht** [comment]
@gabime

**Comment by Guozht** [comment]
Microsoft Visual Studio Ultimate 2013  12.0.21005.1 REL

Visual C++ 2013   06181-004-0451047-02908
Microsoft Visual C++ 2013

**Comment by gabime** [comment]
Sorry. Cannot reproduce. Compiles fine
