### ISSUE TITLE
Doesn't compile on OS X under gcc-4.9

### ISSUE THREAD

**Issue by banks** [gabime/spdlog#81]
This is actually a cppformat bug that has been fixed in their head. See https://github.com/cppformat/cppformat/issues/124

Please consider updating to the upstreams head or if that is problematic for some reason at least include the simple patch on that issue in the vendored code in spdlog.

Currently I'm needing to maintain that patch on spdlog myself for this.

**Comment by gabime** [comment]
Thanks for reporting.

**Comment by gabime** [comment]
Fixed (hopefully) by updating format.h and format.cc to latest versions
