### ISSUE TITLE
Question about flushing

### ISSUE THREAD

**Issue by jade2k11598** [gabime/spdlog#810]
Hi, 
I'm using spdlog v1.0.0.  I have several loggers setup for a given sink (using rotating file with async logging).  After initialization of these loggers, I set it to flush on log levels of error or more severe.  

Now I'm setting up my signal handlers, that for severe signals, I log an error which should flush all my loggers automatically.  But I'm also confused that sinks can be flushed too.  What's the difference between flushing loggers and flushing sinks?  Do I need to also flush my sink if I'm expecting the application going down (as in the case of receiving a severe signal or shutting down)?

**Comment by gabime** [comment]
You only need to call flush on the loggers. The logger is calling the flush() on the sinks. 
If you. exit() the app, you need to call flush, or use flush_on to auto flush when error meesage is written.
