### ISSUE TITLE
fmt::v5::format_error

### ISSUE THREAD

**Issue by XYZ-bear** [gabime/spdlog#811]
hello:
in linux i got this error "fmt::v5::format_error",when use this code:
static auto file_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>("daily.txt", 2, 30);
but it work fine in windows.....

**Comment by gabime** [comment]
Please provide code sample to reproduce

**Comment by gabime** [comment]
I think it is  because you statically create global objects. Problematic in cpp regarding initializatiom order.
Try creating in main.
spdlog provides spdlog::register_logger(logger), spdlog::get(logger_name) to help access loggers from different places.

**Comment by XYZ-bear** [comment]
ok,thanks,it work

**Comment by Peter9606** [comment]
> I think it is because you statically create global objects. Problematic in cpp regarding initializatiom order.
> Try creating in main.
> spdlog provides spdlog::register_logger(logger), spdlog::get(logger_name) to help access loggers from different places.

What if in a library for example .so ? A .so library which provides just some APIs and even doesn't have a main API entrance, if I want use spdlog in such a library, the first comes to my mind would be using a global spdlog instance. Does that work ?

**Comment by tt4g** [comment]
@Peter9606 spdlog has a global registry by default.
If you need to use spdlog in shared library, see wiki: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

You should also know the difference between global variables and static variables: https://stackoverflow.com/questions/19373061/what-happens-to-global-and-static-variables-in-a-shared-library-when-it-is-dynam

**Comment by Peter9606** [comment]
@tt4g  Thanks for your reply.

> @Peter9606 spdlog has a global registry by default.
> If you need to use spdlog in shared library, see wiki: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs
> 
I saw that page, but it is also said that spdlog::get is not a cheap function call and we should avoid using it frequently. But in my case, I can't control how often the client calls the APIs in my library. So I designed to first create and register a spdlog::logger as a global variable, then reference it every time the client calls.
Is there any suggestion?

**Comment by tt4g** [comment]
One of the solutions: use static variable in function (c++11 or above required).
Initialization is delayed for static variables declared in functions until they are evaluated.

Example:

Shared library source:

```cpp
#include "spdlog/spdlog.h"
#include <memory>

spdlog::logger* get_logger()
{
    // is initialized when this line is evaluated.
    static std::shared_ptr<spdlog::logger> logger = (omit)

    return logger.get();
}
```

main source:

```cpp
#include "spdlog/spdlog.h"

int main()
{
    spdlog::logger* logger = get_logger();

    logger->info("Hello, World!");

    return 0;
}
```

Please see the this link for details: https://stackoverflow.com/questions/246564/what-is-the-lifetime-of-a-static-variable-in-a-c-function

**Comment by Peter9606** [comment]
@tt4g  Thank you very much ! Your solution works for me!

I still don't know why my original solution which has only slight difference between yours.

Shared library source:
```

#include "spdlog/spdlog.h"
#include <memory>

shared_ptr<spdlog::logger> get_logger()
{
    // is initialized when this line is evaluated.
    static std::shared_ptr<spdlog::logger> logger = (omit)

    return logger;
}
```
main source:

```
#include "spdlog/spdlog.h"

int main()
{
    shared_ptr<spdlog::logger> logger = get_logger();

    logger->info("Hello, World!");

    return 0;
}
```

My solution always get crushed
