### ISSUE TITLE
#include statments should all be relative from the main `spdlog.h` include

### ISSUE THREAD

**Issue by aaron-michaux** [gabime/spdlog#816]
The include statements in `spdlog.h` should be relative, so:

```
#include "spdlog/common.h"
#include "spdlog/details/registry.h"
#include "spdlog/logger.h"
#include "spdlog/version.h"
```

becomes

```
#include "common.h"
#include "details/registry.h"
#include "logger.h"
#include "version.h"
```

And so forth through the project. This should marginally increase the compile time, and also means that the `spdlog` folder doesn't have to be on the include path of the compiler.

**Comment by gabime** [comment]
Thats debatable. The are pro/cons for each approach (e.g 
https://stackoverflow.com/questions/597318/what-are-the-benefits-of-a-relative-path-such-as-include-header-h-for-a-hea)
