### ISSUE TITLE
not open file

### ISSUE THREAD

**Issue by jeckdz** [gabime/spdlog#818]
I use this spdlog in a new project , but it can not open this logs/rotating .I find this '_fsopen' function return 2 for me in this project. but I don't know why. can you help me ?

**Comment by gabime** [comment]
Please show the exception message

**Comment by jeckdz** [comment]
oh my god,I just tried to consult you, but I didn't expect your timely reply. Thank you.Figure 1 shows the crash,I find '_fsopen' this func get failed and throw spdlog_ex,the errno is show '2' in this error .i don't kow why that it sucessd in the example but it failed in my project.of course,I changed the function, allowed him to support the log into the latest file but the changes in exemple, no [problem.
Duplicate of 
![error](https://user-images.githubusercontent.com/42936747/45017296-d52eeb80-b059-11e8-8c30-36bae53081a4.PNG)
[spdlog.zip](https://github.com/gabime/spdlog/files/2347641/spdlog.zip)

#

**Comment by jeckdz** [comment]
yes, I have this "logs" folder, but where I need to expexts it. I don't find it in the exemple project .
![logs](https://user-images.githubusercontent.com/42936747/45020028-6bfea680-b060-11e8-82d8-0bb173d35180.PNG)
