### ISSUE TITLE
Qt Creator's application output does not print from spdlog logger

### ISSUE THREAD

**Issue by mgansi** [gabime/spdlog#828]
I have working logging in Visual studio project using spdlog. But the same project in Qt creator, does not prints the spdlog logging. But the std::cout still works and prints to Qt creator's application output window.

```
auto console = spdlog::stdout_color_mt("console");
console->info("Welcome to spdlog!");
console->error("Some error message with arg: {}", 1);
```

**Comment by DanielChabrowski** [comment]
https://i.imgur.com/6TbLWME.png

Works fine for me, at least on xubuntu.

**Comment by mgansi** [comment]
I am running it on Windows. Could the issue be specific to windows?

**Comment by mgansi** [comment]
Yes, it does not work with stdout_sink_mt  too.

**Comment by gabime** [comment]
Does it work if excuted from the cmd instead?

**Comment by DanielChabrowski** [comment]
Got some interesting results.

code:
https://gist.github.com/DanielChabrowski/93b55b361ac5065b76103efb65fd7d3f

cmd
https://i.imgur.com/h6DxT3G.png

qtcreator
https://i.imgur.com/OgINfG9.png

**Comment by gabime** [comment]
Interesting indeed.. Maybe related to 
https://stackoverflow.com/q/29005357/192001 ?

**Comment by mgansi** [comment]
Yes, the application output does not output the spdlogs. But, I manage to output to terminal by following steps.

1.     Go to Projects, then choose Run configuration for selected kit
2.     In run settings, check the "Run in terminal" option
3.     Next, add console to CONFIG in Project pro file
4.     Clean the project
5.     Build and run.
