### ISSUE TITLE
'f' uses undefined struct 'fmt::v5::formatter<T,char,void>'

### ISSUE THREAD

**Issue by wtom76** [gabime/spdlog#829]
Hi. At first, thank you so much for spdlog. It's awsome at most =)
The problem for me: may be I don't have enough mastery in argument-dependent lookup, but
`'f' uses undefined struct 'fmt::v5::formatter<T,char,void>` compilation error is most frequent and annoying issue when using custom writers. Some times it is so hard to figure out where to place operator overload `std::ostream& operator << (std::ostream& out, ...` to get compiler to find it for particular type.
For my own types 'friend' works fine, but for foreign types, declared deep inside many levels of namespaces and other types...
For instance what about `boost::msm::back::state_machine<MyNamespace::MySmType>::InitEvent`? Where should I place operator << overload to do `{ return out << "InitEvent"; }` if log will be used in even other namespace?

Thanks

**Comment by gabime** [comment]
Please try to use the current recommended way by fmt lib(
http://fmtlib.net/dev/api.html#formatting-user-defined-types)
