### ISSUE TITLE
Change a logger's sinks

### ISSUE THREAD

**Issue by fabiomargarido** [gabime/spdlog#83]
Hi there.

Is there any way to change the list of sinks associated with a given logger? I was doing that by simply calling ```spdlog::create(loggerName, { new_sink_1, new_sink_2 })``` with the name of an already existing logger, but this throws since 256c64d72f3c943b16173e59b73615b62f3c1e22.

Thanks.

**Comment by fabiomargarido** [comment]
Looking at the changes in that commit, it seems what I was doing was probably not working as I expected... :)

But maybe it would still be interesting to be able to add or remove sinks to a logger.

**Comment by gabime** [comment]
There is no way changing list of sinks for an existing logger object.
It worked before for you because you actually created a new logger object with the same name.

But since then the lib throws when creating a new logger with same name.

**Comment by jcelerier** [comment]
> There is no way changing list of sinks for an existing logger object.

Is there a deep reason for this ? For instance if a library wants to provide to the applications that uses it access to the logger that it logs to, how should it be done ?

**Comment by gabime** [comment]
The main reason is to avoid locking.otherwise threads will be able to change it.

**Comment by jcelerier** [comment]
but isn't there the same problem for `set_formatter`, `set_pattern` etc... ? While on x86(_64), pointer writes are atomic (and still, only if aligned, but I think that they should be in spdlog), it's not necessarily the case on other platforms (like MIPS if I remember correctly).

**Comment by gabime** [comment]
No. formatter is shated_ptr and hence thread safe.

**Comment by jcelerier** [comment]
I don't think that's how `shared_ptr` thread-safety works; the only part that is guaranteed to be safe is that if you have two distinct `shared_ptr` variables both pointing to the same object, then you can reassign each shared_ptr variable in different threads without needing mutexes. However here one would change the same variable, which is not thread-safe. You would need [std::atomic_shared_ptr](http://en.cppreference.com/w/cpp/experimental/atomic_shared_ptr) to protect against accesses to the same variable.

**Comment by gabime** [comment]
Hmm... good point. Please open an issue (or even better open a pull :)
I am not sure it worth the cost of protecting though. After all, who needs to modify the format of a  logger concurrently from differnt threads?.. Maybe documenting clearly would be enough..

**Comment by gabime** [comment]
I added a [wiki page](https://github.com/gabime/spdlog/wiki/1.1.-Thread-Safety ) to document it. I hope it is clear enough.
