### ISSUE TITLE
spdlog::set_pattern not working for logger with manually created sinks

### ISSUE THREAD

**Issue by berhoeckner** [gabime/spdlog#832]
I try to manually create sinks and a logger and set a pattern.
It seems as if setting a pattern to the logger does not work.
The logger is registered, and i try to set the pattern globally and on the logger itself. 
See the example below:
```
#include <spdlog/logger.h>
#include <spdlog/sinks/dist_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/spdlog.h>

int main() {
    auto ds = std::make_shared<spdlog::sinks::dist_sink_mt>();
    ds->set_pattern("*** meh %v ***");

    auto s = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    s->set_pattern("*** MEH %v ***");

    ds->add_sink(s);

    auto logger = std::make_shared<spdlog::logger>("console", ds);

    spdlog::register_logger(logger);
    logger->info("info");

    spdlog::set_pattern("*** foo %v ***");
    logger->info("info");

    logger->set_pattern("*** BAR %v ***");
    spdlog::get("console")->info("info");
}
```

I would expect to get something like
```
*** MEH info ***
*** foo info ***
*** BAR info ***
```

but i get 
```
*** MEH info ***
*** MEH info ***
*** MEH info ***
```

Maybe someone has a pointer to what i'm doing wrong?

**Comment by peergynt** [comment]
I think that the reason why you are not getting the output you expect is because dist_sink does not override its children formatter/pattern when set_formatter/set_pattern is called.

Some pointers:
- you don't need to use dist_sink if you have a single sink
- you could modify the sink pattern directly
- if you want to use multiple sink, you could use the logger constructor that takes multiple sinks, I think your example would work as expected then

**Comment by berhoeckner** [comment]
>I think that the reason why you are not getting the output you expect is because dist_sink does not override its children formatter/pattern when set_formatter/set_pattern is called.

Makes somehow sense, if one wants the same messages but with different patterns in different sinks.

> * you don't need to use dist_sink if you have a single sink

I plan to have a log file as well with the same log messages as on the console.

> * you could modify the sink pattern directly

you mean via the logger? something along (```logger->sinks()[0]->set_pattern( ... )```?

> * if you want to use multiple sink, you could use the logger constructor that takes multiple sinks, I think your example would work as expected then

i'll look into this if this is feasible for the actual code

Thanks for the help!

**Comment by gabime** [comment]
I would avoid dist_sink in your case. Just pass the list of sinks to the ctor of the logger. Thats the recommende spdlog usage.

**Comment by gabime** [comment]
The main usecase is the ability to dynamically change the list of sinks in a thread safe way.
