### ISSUE TITLE
Adding support for numeric log levels?

### ISSUE THREAD

**Issue by emmenlau** [gabime/spdlog#834]
Thanks a lot for the very great library and for the great work!

I have a humble request that I could not yet find in the issues (only related topic #400). We use a numeric log verbosity instead of levels, where lower numbers indicate higher priority. Think of `console->log(0, "Message")` as `console->fatal("Message")`, `console->log(2, "Message")` as `console->warn("Message")` and so on. Compared to fixed levels, this allows for two benefits:
 - arbitrary log levels and granularity are possible, esp. for internal builds with ultra-high granularity, and
 - at very high verbosities beyond `trace`, the program may include additional debug information that otherwise may be too costly to produce.

It is certainly a personal preference, but something I would love to see in spdlog. I think it may be fairly easy to add for me, but I hesitant to maintain a custom fork. Would you consider such a PR for inclusion? Are other people interested in this?

**Comment by gabime** [comment]
Hi,

Thanks for the feedback!

spdlog loggers already support half of what you need (passing level on the call):
```c++
logger -> log(level::info, "hello {}", "world");
```

Regarding custom log levels, how would one add new log levels and their long/short names ? Could you provide an example ?

**Comment by emmenlau** [comment]
Dear @gabime thanks for the quick reply! I have seen this functionality. This is really half of what I need, thanks!

Now my idea would be to add
```
console->set_level(10); // Show only messages with level <= 10
logger -> log(0, "super important message"); // 0 will always display at all log levels
logger -> log(2, "quite important message"); // 2 will be displayed at log level 10
logger -> log(17, "very unimportant message"); // 17 will not be displayed at log level 10
```

**Comment by gabime** [comment]
Right, but please note that spdlog requires a level name(short and normal, e.g “infol/“I”) for each level. The are defined in common.h

**Comment by gabime** [comment]
It can be any c string.

**Comment by emmenlau** [comment]
Great! This solves the problem for me. Here is what I did:

- First reverse the order of current levels:
```
enum level_enum
{
    off = -1,
    critical = 0,
    err = 1,
    warn = 2,
    info = 3,
    debug = 4,
    trace = 5
};
```

- Change the `SPDLOG_LEVEL_NAMES`, `to_c_str`, `to_short_c_str`, `from_str` accordingly
- Change the methods `should_flush_()` and `should_log()` to reverse the integer value

In my eyes this makes it slightly easier to add new logger levels of **lower** impotance, because the list (or lists) can just be extended at the end.

Thanks a lot for your help, this is great!

**Comment by gabime** [comment]
I am glad it worked out. enjoy the logs :)

**Comment by miketsts** [comment]
Hi, any chance to see the customer levels in the library one day? As I understand, OP just uses his private modified fork of the library?

**Comment by gabime** [comment]
While the idea is good, the problem is that reversing level numbers would  break backward compatibility.

Maybe instead we could you negative numbers for user defined levels, but it needs further investigation..

**Comment by miketsts** [comment]
For starters, I see that enum would not play well with negative members.
Also, indexing of `short_level_names` and `level_string_views` arrays with negative indices would require at least shifting the indices by a some constant. Which becomes a number of custom levels allowed.

In addition, I've tried to modify `tests/test_misc.cpp` to test for new level support, before I try any change in the code (TDD style) - the most of the tests return successful. Maybe I'm not familiar enough with the CATCH library, but apparently, no limit checks are done when accessing the above arrays.

I can continue investigating if you still think this direction can bring results... 

Another question. Considering that spdlog is header only library, and the current levels are enum constants, why do you think it will be a problem to changing the enum constants' values? The single issue I can think about is that people may define their own aliases to the defined enum levels. And may compare between them - but I can't think about the purpose of such comparison.

**Comment by ecepep** [comment]
I also wanted to have more levels/numeric level. To hack the level enum, I just created my own levels, used the macro for renaming the levels, and I `static_cast<spdlog::level::level_enum>(lvl)` any time I wish to use spdlog.

I think it works fine so far at the exception that [when `static_cast<underlying>`]:
- MYLevel::OFF != spdlog::off;
- MYLevel::NLEVELS > spdlog::n_levels.

Issues occurs in:
- The console colored sink won't assign the proper color. Unfortunately the arrays `ansicolor_sink::colors_` & `wincolor_sink::colors_` are fixed size so using `set_color()` has limited effect.
- `logger::should_flush_()` returns false `if (msg.level == level::off)`. This is the reason, I reassigned the value for MyLevel::Critical to 7 [=spdlog::level::off +1] because, I want critical to flush!
- Some default value are being assigned level::off. Which correspond now to "nothing" in MYLevel. (among others: default flush level).

I haven't seen any other use of level::off which may be a bother.
Support for numeric log level probably just takes to have `spdlog::level::off` being the max value of the underlying type and removing `n_levels` and replacing arrays by vectors [or pointers to array].

```
enum MYLevel
{
	TRACE = 0,
	DEBUG = 1,
	EVENT = 2,
	INFO = 3,
	WARN = 4,
	ERR = 5,
	CRITICAL = 7, /// \warning CRITICAL cannot be same as spdlog::level::off because of: logger::should_flush_(const details::log_msg &msg)
	OFF = 8,
	NLEVELS = 9
};

#define MY_LEVEL_NAME_TRACE spdlog::string_view_t("TRACE", 5)
#define MY_LEVEL_NAME_DEBUG spdlog::string_view_t("DEBUG", 5)
#define MY_LEVEL_NAME_EVENT spdlog::string_view_t("EVENT", 5)
#define MY_LEVEL_NAME_INFO spdlog::string_view_t("INFO", 4)
#define MY_LEVEL_NAME_WARNING spdlog::string_view_t("WARNING", 7)
#define MY_LEVEL_NAME_ERROR spdlog::string_view_t("ERROR", 5)
#define MY_SPDLOG_OFF spdlog::string_view_t("SPDLOG_OFF", 10) // "MYLevel = 6 doesn't exist, but correspond to spdlog::level::off
#define MY_LEVEL_NAME_CRITICAL spdlog::string_view_t("CRITICAL", 8)
#define MY_LEVEL_NAME_OFF spdlog::string_view_t("OFF", 3)

#ifdef SPDLOG_LEVEL_NAMES
static_assert(false, "SPDLOG_LEVEL_NAMES is already defined.");
#endif

#define SPDLOG_LEVEL_NAMES                                                                                            \
	{                                                                                                                 \
		MY_LEVEL_NAME_TRACE, MY_LEVEL_NAME_DEBUG, MY_LEVEL_NAME_EVENT, MY_LEVEL_NAME_INFO,                            \
			MY_LEVEL_NAME_WARNING, MY_LEVEL_NAME_ERROR, MY_SPDLOG_OFF, MY_LEVEL_NAME_CRITICAL, MY_LEVEL_NAME_OFF					  \
	}

#define SPDLOG_SHORT_LEVEL_NAMES                    \
	{                                               \
		"T", "D", "E", "I", "W", "R", "o", "C", "O"		\
	}
```
``` 
#include <spdlog/sinks/stdout_color_sinks.h> 
static_assert(std::is_same_v<std::underlying_type<MYLevel>::type, std::underlying_type<spdlog::level::level_enum>::type>, "MYLevel and spdlog::level::level_enum don't have the same underlying type. Dangerous cast.");

inline std::shared_ptr<spdlog::sinks::stdout_color_sink_mt> getHackedStdOutColorSink()
{
	static_assert(static_cast<typename std::underlying_type<MYLevel>::type>(MYLevel::OFF) <= static_cast<typename std::underlying_type<spdlog::level::level_enum>::type>(spdlog::level::n_levels),
		"wincolor_sink::colors_ is an array of fixed size: n_levels. We cannot assign colors beyond the array size"); /// WONT COMPILE with MYLevel::CRITICAL = 7 aka NLEVELS = 9
	


	auto hacked = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
	hacked->set_color(static_cast<spdlog::level::level_enum>(MYLevel::TRACE), FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE);		// white
	hacked->set_color(static_cast<spdlog::level::level_enum>(MYLevel::DEBUG), FOREGROUND_GREEN | FOREGROUND_BLUE);							// cyan
	hacked->set_color(static_cast<spdlog::level::level_enum>(MYLevel::EVENT), FOREGROUND_GREEN);											// green
	hacked->set_color(static_cast<spdlog::level::level_enum>(MYLevel::INFO), FOREGROUND_BLUE);												// blue
	hacked->set_color(static_cast<spdlog::level::level_enum>(MYLevel::WARN), FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);	// intense yellow
	hacked->set_color(static_cast<spdlog::level::level_enum>(MYLevel::ERR), FOREGROUND_RED | FOREGROUND_INTENSITY);						// intense red
	hacked->set_color(static_cast<spdlog::level::level_enum>(MYLevel::CRITICAL), BACKGROUND_RED | FOREGROUND_RED | 
		FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY);																				// intense white on red background
	return hacked;
}
```
