### ISSUE TITLE
coverity issue on rotating_file

### ISSUE THREAD

**Issue by rafiw** [gabime/spdlog#835]
https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/rotating_file_sink.h#L104
there is no error check if remove fails!
you can change to
`if (details::os::remove(target) !=0 || details::os::rename(src, target) != 0)`
or add a different exception if remove fails.

**Comment by gabime** [comment]
Not critical at all, but you are right. Please open a PR.
