### ISSUE TITLE
global spdlog::set_pattern() does not work

### ISSUE THREAD

**Issue by jeremy-bitbridge** [gabime/spdlog#838]
Setting pattern globally like this doesn't work:
 spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%n] [%l] %v");

**Comment by gabime** [comment]
Please provide full sample to reproduce, and the error message

**Comment by jeremy-bitbridge** [comment]
Here is my application with `#define SPDLOG_NO_NAME`

I log 
`[2018-09-17 12:38:01.891] [info] UP AND RUNNING`

```
#include "spdlog/sinks/daily_file_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/spdlog.h"
#include <memory>

using namespace std;

void main() {
    std::vector<spdlog::sink_ptr> sinks;
    sinks.push_back(
        std::make_shared<spdlog::sinks::stdout_color_sink_st>());

    // Create a daily logger - a new file is created every day on 1am
    sinks.push_back(
        std::make_shared<spdlog::sinks::daily_file_sink_st>("daily.log", 1, 0));

    std::string logger_name = "multi_sink";
    auto _log = std::make_unique<spdlog::logger>(logger_name, sinks.begin(), sinks.end());
    // _log->set_pattern("%H:%M:%S.%e [%l] %v");
    spdlog::set_pattern("%H:%M:%S.%e [%l] %v");
    _log->info("UP AND RUNNING");
}
```
If I use the logger specific format:
`_log->set_pattern("%H:%M:%S.%e [%l] %v");`

instead of the global
`spdlog::set_pattern("%H:%M:%S.%e [%l] %v");`

I get the `12:45:32.308 [info] UP AND RUNNING` as expected

**Comment by gabime** [comment]
The global pattern takes effect on all registerd loggets. If you create a logger directly (without using spdlog’s factory funcs as in the example), you need to call spdlog::register_logger(_log) to let the global functions know about it.


> One other quirk is that if I set the pattern on the logger then the stdout_color_sink_st no longer is in color.

You need to wrap colored part in you pattern with ^ and %$ .

**Comment by jeremy-bitbridge** [comment]
Beautiful! Thanks. I would say that wasn't the most intuitive from the docs but I really appreciate the quick support. I'm now even more confident in pushing this to my team as the goto logger for our code base.
