### ISSUE TITLE
instance’ is not a member of ‘spdlog::sinks::stdout_sink_mt

### ISSUE THREAD

**Issue by BruceWashington13** [gabime/spdlog#839]
@gabime  hi, i am having some errors in spdlog

error: ‘instance’ is not a member of ‘spdlog::sinks::stdout_sink_mt {aka ### ```
```
spdlog::sinks::stdout_sink<spdlog::details::console_stdout, spdlog::details::console_mutex>}’
   auto stdout_sink=spdlog::sinks::stdout_sink_mt::instance();
```
                                                   ^~~~~~~

and

 error: ‘set_async_mode’ is not a member of ‘spdlog’
 `spdlog::set_async_mode(16 /*q_size*/, spdlog::async_overflow_policy::discard_log_msg); /`/ sz must be pow of 2

error: ‘discard_log_msg’ is not a member of ‘spdlog::async_overflow_policy’
`spdlog::set_async_mode(16 /*q_size*/, spdlog::async_overflow_policy::discard_log_msg);` // sz must be pow of 2

**Comment by gabime** [comment]
looks like annold version. please use the v1.x branch

**Comment by BruceWashington13** [comment]
@gabime 

  auto stdout_sink=spdlog::sinks::stdout_sink_mt::instance();
                                                        ^~~~~~~~
/home/lab04/Music/Hyperflow-20180620/src/main.cpp:88:16: error: ‘set_async_mode’ is not a member of ‘spdlog’
        spdlog::set_async_mode(16 /*q_size*/, spdlog::async_overflow_policy::discard_log_msg); // sz must be pow of 2
                ^~~~~~~~~~~~~~
/home/lab04/Music/Hyperflow-20180620/src/main.cpp:88:77: error: ‘discard_log_msg’ is not a member of ‘spdlog::async_overflow_policy’
        spdlog::set_async_mode(16 /*q_size*/, spdlog::async_overflow_policy::discard_log_msg); // sz must be pow of 2
                                                                             ^~~~~~~~~~~~~~~

still same error after using latest version

**Comment by BruceWashington13** [comment]
@gabime 
```

	std::vector<spdlog::sink_ptr> sinks;
	auto stdout_sink=spdlog::sinks::stdout_sink_mt::instance();
	sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_mt>())				sinks.push_back(std::make_shared<spdlog::sinks::rotating_file_sink_st>(log_file_path, "log", 1024 * 1024, 5,false));
	spdlog::set_async_mode(16 /*q_size*/, spdlog::async_overflow_policy::discard_log_msg); 
```

this is my code

**Comment by gabime** [comment]
There is no “set_async_mode” in ver 1.x. but  main.cpp use it.

**Comment by BruceWashington13** [comment]
@gabime  
then how to fiix this one
`auto stdout_sink=spdlog::sinks::stdout_sink_mt::instance();`

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@gabime still have this problem when I try to use multi sinks async log with colorful console:

```
    std::shared_ptr<spdlog::logger> logger = nullptr;
    std::vector<spdlog::sink_ptr> sinks;

    auto stdout_sink = spdlog::sinks::stdout_sink_mt::instance();
    auto color_sink = std::make_shared<spdlog::sinks::ansicolor_sink>(stdout_sink);
    sinks.push_back(color_sink);
    const std::string logDest = format("log/%s.txt", scope.c_str());
```

has any body solved this ?

**Comment by gabime** [comment]
What problem exactly?

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@gabime by checking headers, I replaced the above codes with:

```
    /*
    auto stdout_sink = spdlog::sinks::stdout_sink_mt::instance();
    auto color_sink = std::make_shared<spdlog::sinks::ansicolor_sink>(stdout_sink);
     */
    auto color_sink = std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>();
```

In the header file (installed by ubuntu apt), `spdlog::sinks::stdout_sink_mt::instance` the method has not been added to the class.
