### ISSUE TITLE
vector subscript out of range

### ISSUE THREAD

**Issue by kshitizvadera** [gabime/spdlog#841]
https://github.com/gabime/spdlog/blob/b6b9d835c588c35227410a9830e7a4586f90777a/include/spdlog/details/registry.h#L65
throwing _DEBUG_ERROR("vector subscript out of range");

**Comment by kshitizvadera** [comment]
loggers_.size() is zero.

**Comment by gabime** [comment]
Please post code to reproduce

**Comment by kshitizvadera** [comment]
No worries this is related to order of object initialization and destruction issue. spdlog lib is fine here.
Thanks
