### ISSUE TITLE
set_pattern will lose color of log level with stdout_color_sink_mt/st.

### ISSUE THREAD

**Issue by jefferylush** [gabime/spdlog#843]
spdlog v1.1.0, Create stdout_color_sink, the log level color is work.
But after set_pattern, the color of log level will lose.
logger->set_pattern("[%Y-%m-%d %T.%e] [Pid:%P] [%l] %v", spdlog::pattern_time_type::utc);
I check the code of spdlog-1.1.0/include/spdlog/details/pattern_formatter.h
don't set msg.color_range_start of level_formatter,short_level_formatter.
add these code, will fixed this bug.
// log level appender
class level_formatter : public flag_formatter
{
    void format(const details::log_msg &msg, const std::tm &, fmt::memory_buffer &dest) override
    {
        `msg.color_range_start = dest.size();`
        fmt_helper::append_c_str(level::to_c_str(msg.level), dest);
       ` msg.color_range_end = dest.size();`
    }
};

// short log level appender
class short_level_formatter : public flag_formatter
{
    void format(const details::log_msg &msg, const std::tm &, fmt::memory_buffer &dest) override
    {
        `msg.color_range_start = dest.size();`
        fmt_helper::append_c_str(level::to_short_c_str(msg.level), dest);
        `msg.color_range_end = dest.size();`
    }
};

**Comment by gabime** [comment]
You need to wrap the colored part in you pattern with ^ and %$ .
