### ISSUE TITLE
memory_buffer, store_ is never deallocated

### ISSUE THREAD

**Issue by liuliushimonkey** [gabime/spdlog#845]
I have noticed that in basic_memory_buffer, the private field T store_[SIZE] is never deallocated. After call to grow, the real data holder, ptr_, is reallocated, but the store_ keeps intact as the initial array. And it seems to me that the only usage of store_ is to initialize the ptr_ in the constructor. Once we grow, the data in store_ is obselete and unallocated. If we have a lot of basic_memory_buffer, we risk of a memory leak, especially if we instantiate basic_memory_buffer with large customized size.

**Comment by gabime** [comment]
It is consant sized array. It is released automatically when the memory_buffer is destructed. It allows avoiding allocating memory dynamically when the message is less than 500 bytes.
