### ISSUE TITLE
Can't build with SPDLOG_ENABLE_MESSAGE_COUNTER.

### ISSUE THREAD

**Issue by Bak-Jin-Hyeong** [gabime/spdlog#849]
Since commit a06d32ae1930793db64cfdd3564723292f75a21c, can't build with SPDLOG_ENABLE_MESSAGE_COUNTER.

I think `details::log_msg::msg_id` should be mutable.
Otherwise, `logger::sink_it_` should not use const reference parameter.

**Comment by gabime** [comment]
Fixed in c5011181bb0f77fd73cac4bf0b6c9fe20eccedde
Thanks for reporting

**Comment by Bak-Jin-Hyeong** [comment]
Thank you very much for your quick fix.

**Comment by gabime** [comment]
Fixed again in 3611237
