### ISSUE TITLE
'GetDynamicTimeZoneInformation' was not declared in this scope

### ISSUE THREAD

**Issue by DJuego** [gabime/spdlog#85]
Another compiler error with mingw-builds (i686-4.9.2-release-win32-sjlj-rt_v4-rev2) [WIN32]

..\..\inc/spdlog/sinks/../details/./os.h: In function 'int spdlog::details::os::utc_minutes_offset(const tm&)':
..\..\inc/spdlog/sinks/../details/./os.h:167:52: error: 'GetDynamicTimeZoneInformation' was not declared in this scope
     auto rv = GetDynamicTimeZoneInformation(&tzinfo);

I can "solve" it with:

File timezoneapi.h: [mingw32\i686-w64-mingw32\include\timezoneapi.h]
```cpp
-#if _WIN32_WINNT >= 0x0600
  WINBASEAPI DWORD WINAPI GetDynamicTimeZoneInformation (PDYNAMIC_TIME_ZONE_INFORMATION pTimeZoneInformation);
-#endif
```

**Comment by gabime** [comment]
No need to add anything to timezoneapi.h

It compiles fine if you add ``` -D_WIN32_WINNT=0x600``` to the compiler flags (see Makefile.mingw in the example folder)
