### ISSUE TITLE
build error with wchar_t

### ISSUE THREAD

**Issue by bbc1246** [gabime/spdlog#852]
I have..
 
      VS2017  15.8.4
      spdlog latest branch 1.x
     
The code is..

	std::wstring str = L"abc";
	auto console = spdlog::stdout_color_mt("console");
	console->info("Welcome to spdlog! {}", str.c_str());

Error is..

Error (active)	E1775	'= delete' can only appear on the first declaration of a function	spdlog\fmt\bundled\core.h	1236	

Error	C2825	'fmt::v5::internal::get_type<Context,Arg>::value_type': must be a class or namespace when followed by '::'	
spdlog\fmt\bundled\core.h	973	

Error	C2510	'value_type': left of '::' must be a class/struct/union	
spdlog\fmt\bundled\core.h	973	

Error	C2440	'initializing': cannot convert from 'fmt::v5::format_spec_tag' to 'const fmt::v5::internal::type'	
spdlog\fmt\bundled\core.h	973	

Error	C2131	expression did not evaluate to a constant	
spdlog\fmt\bundled\core.h	1038	

is it VS2017 bug? or none support wchar_t?

**Comment by gabime** [comment]
Fixed in 8b42b7d269f3397b04e9e4c8f236c4b922de410b
