### ISSUE TITLE
Rotating file sink uses incorrect filenames

### ISSUE THREAD

**Issue by rigtorp** [gabime/spdlog#855]
Recently upgraded to latest spdlog and ran into several issues due to new naming scheme for rotating file sink.

Previous naming scheme was `filename.log` for newest file and `filename.log.[1-9]+` for rotated files. New scheme is `filename.[1-9]+.log` for rotated logs. This new naming scheme has several issues:

- Different from common [logrotate](https://linux.die.net/man/8/logrotate) scheme
- Breaks common usecase of searching recent logs: `grep XXX *.log`. With new scheme this also searches old logs
- Breaks rsyslog forwarding to log server. New naming scheme causes old logs to be re-imported as "filename.[1-9]+" log source. 

Please revert to old behaviour. I am happy to submit a PR if you agree.

**Comment by gabime** [comment]
This is pretty old change(3c4a2bf5317219c685667fee65273e68bb4410a5 almost 2 years), and users are happy with it (me included), so I can’t just change it and break compitability.

What can be done is maybe provide a lambda option  (sink->set_filename_fun(..)) that returns a filename, or maybe, like in [daily_file_sink](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/sinks/daily_file_sink.h) have a template option for custom filename calculator.

**Comment by rigtorp** [comment]
Probably easiest solution is for me to maintain custom sink.

Thanks for all the great work on spdlog
