### ISSUE TITLE
Getting a specific logger from sinks

### ISSUE THREAD

**Issue by devhandle** [gabime/spdlog#857]
**Question**

This is probably a noob question but I've tried googling and couldn't find a solution. I've created a logger which outputs to both console and file. The problem is that occasionally I'd like to output to console only. I have configured my logger below but I can't find a way to just get the console logger. I realise I can get access to the sinks but how do I get access to the console logger? 

`auto& sinks = spdlog::get("Logger")->sinks()[0];`

Configuring the logger 

```
  void configureLogging(const std::string &loggerName, const std::string &logFilename)
    {
        // configure logging (colour console and rotating file)
        std::vector<spdlog::sink_ptr> sinks;
        sinks.push_back(std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>());
        sinks.push_back(std::make_shared<spdlog::sinks::rotating_file_sink_mt>("test.log", 5 * 1024 * 1024, 5));
     
        auto combined_logger = std::make_shared<spdlog::logger>(loggerName.c_str(), begin(sinks), end(sinks));
        //register for global accessibility
        spdlog::register_logger(combined_logger);
    }
```

Any help appreciataed.

**Comment by gabime** [comment]
The closest I can think of is creating another console logger, and call it occasionally. Logger is just a wrapper to sinks anyway.

**Comment by devhandle** [comment]
Thanks for the response. I'll go ahead and create another console logger - it's just a shame I can't use the existing logger. I guess it's not a major issue.
