### ISSUE TITLE
Default logger in registry

### ISSUE THREAD

**Issue by otristan** [gabime/spdlog#858]
Unless I am missing this feature in the doc, it looks like there is no way to get/set a default logger that could be used in apps where there is one single logger and don't want to define a global name.

Something like spdlog::get_default() and spdlog::set_default()

This would allows to have something similar to Boost Log and BOOST_LOG_TRIVIAL

Thanks !

**Comment by gabime** [comment]
Right., you are not missing anything. No default logger exists.

**Comment by otristan** [comment]
Is this something that make sense to be added ?

**Comment by gabime** [comment]
Not sure whats the added value.

**Comment by otristan** [comment]
Love the new syntax.

Thanks a lot !
