### ISSUE TITLE
Library versioning?

### ISSUE THREAD

**Issue by mattklein123** [gabime/spdlog#86]
Hi,

Library looks pretty interesting and am considering using it in a project. Are you thinking about starting to tag versions at some point soon? I would prefer to be able to import at specific versions vs. master if possible.

(This isn't really an issue per say but I figured I would ask here)

Thanks,
Matt

**Comment by gabime** [comment]
Sure, At some point versioning will be applied - when the API stabilizes a bit..not sure when though..

**Comment by dkopecek** [comment]
I'm also a bit interested in this topic. I've packaged your project for Fedora ([pkgdb link](https://admin.fedoraproject.org/pkgdb/package/spdlog/), [package review link](https://bugzilla.redhat.com/1210753)) because I use it in my project which I'd like to have there and Fedora has strict library bundling rules -- i.e. you can't bundle anything unless it's really necessary.

If are going to do tagged releases at some point in the future, then I'm looking forward to it, because that will simplify the decision when to update the package in Fedora.

**Comment by mattklein123** [comment]
Out of curiosity, do you foresee breaking changes coming soon? Is there any reason not to put a version on what is there right now? It seems fairly complete (for what it does currently).

**Comment by gabime** [comment]
There probably will be breaking changes.. There is always room for improvment..

**Comment by gabime** [comment]
@dkopecek thanks for the packaging! 

Btw, I would be happy to get some feedback on the lib (strong/weak points etc.)

**Comment by gregoire-astruc** [comment]
Hi,

I just had a glance at this project and I'm very likely to use it in a couple projects.

Regarding versioning, I'd strongly recommend following the [SemVer](http://semver.org) approach: it would enable you to start versioning right now, even if you feel you're still in alpha/beta stage.

API might break now or even in the future and this scheme gives you the chance to inform clients about it.

Hope that helps.

**Comment by gabime** [comment]
Thanks for the feedback. I will take a look at SemVer approach..

**Comment by memsharded** [comment]
I know this is an old issue, but I also think that tagging at some points would be beneficial. I have created a spdlog package for conan: https://www.conan.io/source/spdlog/0.1/memsharded/testing, and used the latest commit, named it 0.1. I can do a "master" version getting the latest commit, but for package management and reproducibility, I think is better to fix the package to one commit. 

So it would be great if you could tag your project at some points, it doesn't really require to follow semver, or be really special releases. It is just an easy name for consumers to handle reproducibility without having to resort to ugly sha1 commit hashes. Thank you, and thanks for such a great project.

**Comment by barboteur** [comment]
Hello, I would also appreciate that you put a first tag on your library. You should start with a tag named 0.x.y if it is not the final product.

**Comment by gabime** [comment]
First official library version just released (0.9.0)

**Comment by memsharded** [comment]
Great, thank you!

Just created package for 0.9.0 in conan: https://www.conan.io/source/spdlog/0.9.0/memsharded/stable
The github repo: https://github.com/memsharded/conan-spdlog. As it is header only, the package recipe is very simple, if you want to have a look: https://github.com/memsharded/conan-spdlog/blob/master/conanfile.py

Thanks again, this helps for package maintenance.

**Comment by gabime** [comment]
@memsharded :+1:

**Comment by memsharded** [comment]
Package for 0.10.0 available in conan: https://www.conan.io/source/spdlog/0.10.0/memsharded/stable

Very cool that you were able to remove the exceptions! I think this will further increase adoption.

There are badges for packages just in case you want to reference them somewhere: https://github.com/memsharded/conan-spdlog.

**Comment by p0fi** [comment]
Hello,

i'd like to know how it is possible to know the installed version of the lib. Is there any method i can call witch will return a version number?

**Comment by gabime** [comment]
No, no such method exists.

**Comment by p0fi** [comment]
I think this might be useful to add if you have version numbers?

**Comment by gabime** [comment]
Maybe a ```#define SPDLOG_VERSION someversion```...

**Comment by p0fi** [comment]
I guess that would do the job also, just not easy to find out which actual version of the lib is getting used in a project. I would be glad if this finds the way into the lib. Great work by the way! :)

**Comment by chausner** [comment]
@gabime Could you please confirm whether the library officially adheres to semantic versioning or not (breaking changes -> bump major version, non-breaking changes -> bump minor version, non-breaking bug fixes -> bump patch version)?

**Comment by gabime** [comment]
It tries to adhere to semver, yes
