### ISSUE TITLE
logging to a remote server like node JS

### ISSUE THREAD

**Issue by naveenpinto** [gabime/spdlog#863]
Hi 
   this is second time i am asking this question, do you have any examples on writing to a remote server, example a node JS server.

Regards
Naveen

**Comment by vvhh2002** [comment]
hi, you can write a sub class of base_sink with a callback  of NodeJS js function.

**Comment by naveenpinto** [comment]
Hi @vvhh2002 thanks a lot, do you have any example implementation of the same????
