### ISSUE TITLE
Does it work ok in forked process?

### ISSUE THREAD

**Issue by dawei101** [gabime/spdlog#865]

**Comment by gabime** [comment]
If you mean that all processes write to same log file, then no. Each process should write to its own logfile

**Comment by jiudianren** [comment]
if before fork  i  creat a logger with a filesink  ,and then fork . 
at fork ,will fater pid and son pid both use the same logger  write to the same filesink ok?
 thanks for your answer

**Comment by tt4g** [comment]
@jiudianren spdlog does not support writing log to the same file.
See #937
