### ISSUE TITLE
Control fluch policy by no. of log lines written?

### ISSUE THREAD

**Issue by alexsuo** [gabime/spdlog#869]
Hi,

Firstly thank you all. Great lib for high performance logging :) I am using spdlog while I found sometimes the logger produces no output when program is not actively writing to log file. After some googling I found https://github.com/gabime/spdlog/issues/82 and https://github.com/gabime/spdlog/wiki/7.-Flush-policy (btw the latter page is out of date). 

It seems my major option is to use spdlog::flush_every(std::chrono::seconds). However if the system isn't actively producing log lines this is a waste of system resource. I don't want to flush every line either which is also slow and a waste even when the logger is in async mode. 

My main questions are

1. Is there anyway I can tell spdlog to flush every X lines logged? Is it a sensible flushing policy?
2. What's the default behavior for flushing? Does it have anything to do with the pool size (e.g. flush when 1/2 of the pool used)? If so, is it recommended to change the pool size to control flushing behavior (which seems bundle the 2 features together but if that's the solution)?

Thanks
Alex

**Comment by gabime** [comment]
Hi,
Thanks for the feedback!

> Is there anyway I can tell spdlog to flush every X lines logged? Is it a sensible flushing policy?

No.

> What's the default behavior for flushing? 

The default is to let glibc to flush whenever it sees fit (i.e. spdlog never call flush() in the default log settings). Anyway, there is no relation to pool size.

I recommend using ```spdlog::flush_every(std::chrono::seconds)``` - It does exactly what you need.  
It does costs an extra thread (single thread - no matter how many loggers), but I believe the cost is small -the thread just sleeps most of the time. If you worry about it just define big interval, say 5, or 10 seconds.

**Comment by alexsuo** [comment]
Thanks for the rapid feedback :) 1 more follow up.

> I recommend using `spdlog::flush_every(std::chrono::seconds)` - It does exactly what you need.
> It does costs an extra thread (single thread - no matter how many loggers), but I believe the cost is small -the thread just sleeps most of the time. If you worry about it just define big interval, say 5, or 10 seconds.

In the above case, after the timed thread trigger a flush, 

1. I believe since its one timer thread for all the loggers, the timed thread simply notify the loggers to do flushing in its own thread from the thread pool (i.e. the task is not done in the timer thread)?

2. Meanwhile, as long as the log buffer/queue isn't full, doing a flushing shouldn't have any impact for new log item to be produced; thus won't block any log producing threads (i.e. application threads)?

Thanks in advance.

P.S. nice cat. 
Alex

**Comment by gabime** [comment]
1. Right - in asynchronous  loggers. In sync loggers, it is done in the timed thread.
2. Right - in asynchronous  loggers. The ```sink::flush()``` operation itself is protected by mutex, so in synchronous loggers any concurrent log call will block until flush finishes.

**Comment by alexsuo** [comment]
Thanks Gabi. In that case I think the design is good and performance is adequate. I would do some CPU affinity to ensure performance in my application. (I am just a bit lazy to read through all code) Consider this as closed :)

Have a nice day!
Alex
