### ISSUE TITLE
replace unordered_map with map in registry 

### ISSUE THREAD

**Issue by divaykin** [gabime/spdlog#87]
@gabime I believe on small number of entries map works a lot faster vs unordered_map. the main reason is necessity to build a hash code (out of string).

maybe even better would be to be able to define it in tweakme?

I can make a patch if you like.

**Comment by gabime** [comment]
This is interesting..
I always thought lookup time of un ordered map is faster..
Do you have any numbers or measurments?

**Comment by divaykin** [comment]
See gist https://gist.github.com/divaykin/bb7253412b8519a8c1ca

For small number of keys basically it's faster to simply go through entire array and do compare.

```
map takes 57.2173ns on average
umap takes 61.7916ns on average
vec takes 32.5011ns on average
vec2 takes 32.4735ns on average
AAAAAAAAAAAAAA / AAAAAAAAAAAAAA / AAAAAAAAAAAAAA / AAAAAAAAAAAAAA
RUN FINISHED; exit value 0; real time: 1s; user: 0ms; system: 730ms
```

**Comment by divaykin** [comment]
If we use `int` as a key instead of string we can save few nanos https://gist.github.com/divaykin/c051f7133caa122e9d1e

```
map takes 2.2279ns on average
umap takes 1.3549ns on average
vec takes 1.6258ns on average
vec2 takes 1.6711ns on average
AAAAAAAAAAAAAA / AAAAAAAAAAAAAA / AAAAAAAAAAAAAA / AAAAAAAAAAAAAA
RUN FINISHED; exit value 0; real time: 70ms; user: 0ms; system: 30ms
```

**Comment by gabime** [comment]
Thanks. Which compiler did you use?

Seems that the differences between umap and map (4 ns) doesnt worth the trouble, but the vector and int are significant...

**Comment by divaykin** [comment]
It's GCC 4.9. Lets do then lookup of logger by int

**Comment by gabime** [comment]
I agree, but we need to figure out  how not to break the current API and still keep things simple..

I could add a template param to the involved functions but it will complicate the API significantly..

**Comment by gabime** [comment]
On the other hand, giving the user an option to use vector<string> instead of map<string> in the tweakme.h won't break the API and will gain about 30ns..

**Comment by divaykin** [comment]
How about two versions of ::get() - by name & by integer id? And two maps?

**Comment by gabime** [comment]
But then there would also be two versions for each logger factory function. for example:

```spdlog::simple_file_logger_mt(int id, string name);```
and also the regular
```spdlog::simple_file_logger_mt(string name,..);```

**Comment by divaykin** [comment]
A bit cumbersome indeed. In tweakme we can try define instead of template maybe

**Comment by rpopescu** [comment]
Gabi,

Can't you just assign numeric IDs to the loggers internally, and return the value from the factory?
Then, if not ignored, the return value can be used to speed up the lookups.

**Comment by gabime** [comment]
@rpopescu Thats an interesting idea. But now the factory would need to return ic  (in addition to the pointer) which means major api change for little  gain..

**Comment by gregoire-astruc** [comment]
If I may, this should not be a primary concern: besides the search, you have a mutex and a shared pointer which has synchronization to do on its own.

Moreover, according to the wiki and some good sense, you *should* hold onto the smart pointer you got from the registry shouldn't you?

**Comment by rpopescu** [comment]
That's a very sensible comment. I agree - now having actually used the library - that lookup performance doesn't seem particularly relevant.
