### ISSUE TITLE
Feature request: Capture source line and filename

### ISSUE THREAD

**Issue by mattgodbolt** [gabime/spdlog#871]
This is probably a portability nightmare...but... with `std::experimental::source_location` (see [here](https://github.com/gabime/spdlog/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+color)) there's a possibility of capturing the log location without resorting to macro trickery.

It would be _amazing_ to be able to capture the log caller's location and have it available for the formatter.

**Comment by gabime** [comment]
> This is probably a portability nightmare

I agree:) Do you know which compilers support it already? Can't find it in https://en.cppreference.com/w/cpp/compiler_support

**Comment by mattgodbolt** [comment]
Based on testing it's only GCC 7 and above. I have a home-grown MACRO-based "solution" for my logging needs but it unfortunately doesn't work all that well with spdlog as it stands. I'd love to be able to extend the internal log object with at least placeholders which I could populate with my macros, and then use later on.

**Comment by peergynt** [comment]
@gabime the added `source_loc` looks really promising!

Would you consider adding an optional filename length field or making it a string_view maybe?
I have a case where the filename does not come from the preprocessor but from an external source and it is not guaranteed to be a zero terminated string.

**Comment by gabime** [comment]
ok, lets replace with string view. It would also more efficient for the pattern formatter.

**Comment by gabime** [comment]
@mattgodbolt Impemented in version 1.3.0 (see 
https://github.com/gabime/spdlog/releases for details)
