### ISSUE TITLE
Make_unique doesn't work when using multi sink

### ISSUE THREAD

**Issue by liron-tiledmedia** [gabime/spdlog#875]
when declaring:
std::unique_ptr<spdlog::logger> mf_logger;

and then trying:
logger = std::make_unique<spdlog::logger>("Main_logger", { shared_sink_console, shared_sink_file});
I get the error: 'std::make_unique': function does not take 2 arguments.

It seems as if make_unique can not see the multi sink ctor. (it does work if i change this line to only have 1 sink without init_list)

**Comment by gabime** [comment]
Try using ```spdlog::sinks_init_list{..}```:
```c++
std::make_unique<spdlog::logger>("Main_logger", spdlog::sinks_init_list{ shared_sink_console, shared_sink_file});
```

**Comment by liron-tiledmedia** [comment]
Work like a charm, many thanks.
