### ISSUE TITLE
How to set color for the given level whatever the OS?

### ISSUE THREAD

**Issue by LeMoussel** [gabime/spdlog#879]
I want to change color for the given level.  It seems that this is possible with  `set_color`. 
 `set_color` is define in 

- ansicolor_sink.h :  [void set_color(level::level_enum color_level, const std::string &color)](https://github.com/gabime/spdlog/blob/226d5a1d36ff310a0bd0f30a73a9421d02156483/include/spdlog/sinks/ansicolor_sink.h#L56)
- wincolor_sink.h : [void set_color(level::level_enum level, WORD color)](https://github.com/gabime/spdlog/blob/226d5a1d36ff310a0bd0f30a73a9421d02156483/include/spdlog/sinks/wincolor_sink.h#L62)

I define console color logger like this

> auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();

but how to use `set_color` for this skin whatever the OS (Win/Linux)?

> console_sink->set_color(spdlog::level::info, ????);

**Comment by gabime** [comment]
You can try
```c++
auto color_sink = static_cast<spdlog::sinks::stdout_color_sink_mt*>(console->sinks()[0].get());
color_sink->set_color(...);
```

**Comment by LeMoussel** [comment]
it doesn't work. I do this 
```
auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
auto color_sink = static_cast<spdlog::sinks::stdout_color_sink_mt*>(console_sink->sinks()[0].get());
```

Under Win this compiles but under Unix I have the error:

> error: ‘using element_type = class spdlog::sinks::ansicolor_sink<spdlog::details::console_stdout, spdlog::details::console_mutex> {aka class spdlog::sinks::ansicolor_sink<spdlog::details::console_stdout, spdlog::details::console_mutex>}’ has no member named ‘sinks’; did you mean ‘sink’?
>      auto color_sink = static_cast<spdlog::sinks::stdout_color_sink_mt*>(console_sink->sinks()[0].get());

**Comment by MrChampion** [comment]
```
auto console_out = spdlog::stdout_color_mt("console_out");	
auto console_sink = dynamic_cast<spdlog::sinks::stdout_color_sink_mt *>(console_out->sinks().back().get());
console_sink->set_color(spdlog::level::info, "\033[37m");
```
I'm doing that in Linux (GCC-4.8), dunno if it helps in your case.

**Comment by LeMoussel** [comment]
It's OK for Linux
But with Win, I got this error:

> error C2664: 'void spdlog::sinks::wincolor_sink<spdlog::details::console_stdout,spdlog::details::console_mutex>::set_color(spdlog::level::level_enum,WORD)': cannot convert argument 2 from 'const char [6]' to 'WORD'

The solution is to do:
```
#if defined _MSC_VER
    console_sink->set_color(spdlog::level::info, "FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE");
#else
    console_sink->set_color(spdlog::level::info, "\033[37m");
#endif
```
