### ISSUE TITLE
Can't compile with toolset Visual Studio 2013 (windows xp v120)

### ISSUE THREAD

**Issue by Zeno82** [gabime/spdlog#894]
Hi,

I get compiler error C2440 on line 2182
p = parse_arg_id(p, end, id_adapter<Handler, Char>{handler});
 in fmt/bundled/format.h:
< function-style-cast > : cannot convert from 'initializer-list' to 'fmt::v5::internal::id_adapter<Handler,Char>'

I'm compiling Spdlog v. 1.2.1
Visual studio 2017 v 15.8.4
Platform Toolset: Visual Studio 2013 - Windows XP (v120_xp)
Thanks

**Comment by gabime** [comment]
Please provide the code to reproduce.

**Comment by gabime** [comment]
Ok, I've changed the title accordingly

**Comment by gabime** [comment]
I can't reproduce. Compiles fine on my environment (vs2017 + windows xp v120).
Maybe you need to update the tool set or something of the sort?

**Comment by MrRoLiG** [comment]
> I can't reproduce. Compiles fine on my environment (vs2017 + windows xp v120).
> Maybe you need to update the tool set or something of the sort?
> 
> I am using 2013 Update 5 (_MSC_FULL_VER = 180040629)

I tied the same project at two different computers...
it works fine at the computer with the toolset Visual Studio 2013 (v120/v120_xp) and Visual Studio 2017 (v141).
but not works at the computer which only installed the toolset Visual Studio 2013 (v120/v120_xp).
