### ISSUE TITLE
Variable aruments list va_list not accepted as parameter to logging.

### ISSUE THREAD

**Issue by Mmisiek** [gabime/spdlog#895]
When I try to pass va_list to log function I am getting compilation error:

error: calling a private constructor of class 'fmt::internal::MakeValue<fmt::BasicFormatter<char, fmt::ArgFormatter<char> > >'
    Value result = MakeValue<Formatter>(value);

**Comment by gabime** [comment]
spdlog doesnt support bis I tihnk, but pleas provide the source to reproduce.
