### ISSUE TITLE
Clarify blocking behavior in docs

### ISSUE THREAD

**Issue by cgorshing** [gabime/spdlog#896]
In the docs is the following:

> When trying to log a message and the queue is full, the caller will block (default behavior) **if the until a slot becomes available** (default), or overrun oldest message immediately in the queue with the new one (if the logger was constructed with async_overflow_policy==overrun_oldest).

Does the "if the" need to be removed or was there something left out on this paragraph?

**Comment by gabime** [comment]
Fixed. thanks for noticing.
