### ISSUE TITLE
escaping special characters (e.g. newlines) in log messages

### ISSUE THREAD

**Issue by drnedm** [gabime/spdlog#900]
Hi there,

I am using spdlog in an application where my program receives string messages from other processes through fifos. If I want to log the received messages, control characters like \n, \t etc. mess up the log file by being interpreted and leading to e.g. additional blank lines in the file.

Example:
```
char buffer[100];
/* receive string into buffer, e.g. "do nothing\n" */
log->info("something");
log->info("something else");
log->debug("message was: \"{}\"", buffer);
log->info("something");
```

--> log file:
```
[2111-01-01 01:01:01.111] [test] [info] something
[2111-01-01 01:01:01.112] [test] [info] something else
[2111-01-01 01:01:01.113] [test] [debug] message was: "do nothing
"
[2111-01-01 01:01:01.114] [test] [info] something
```

Is there already a way to achieve escaping (such that the log would read
`message was: "do nothing\n"`
) the log messages already in spdlog, or if not, how would I go about implementing this?

The original message buffer cannot be changed for logging.

Cheers,
D

**Comment by gabime** [comment]
> Is there already a way to achieve escaping (such that the log would read
message was: "do nothing\n

No, you will need to escape before passing to spdlog.

**Comment by drnedm** [comment]
OK, thanks for your reply. 
But escaping beforehand would mean that I would either have to manually check for the current log level of spdlog, or always escape even if the message would not be logged at all. 
Is it possible to do this in a custom formatter or something? Such that spdlog's logic to figure out, if a message is to be logged at all or not, does not have to be duplicated?

Cheers,
D

**Comment by gabime** [comment]
Sure, you can have your own custom formatter by implementing the formatter [interface](
https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/formatter.h) and provide it to the logger using  set_formatter(..).

**Comment by nareddyt** [comment]
Is there any example code of a custom formatter to solve this issue? I'm assuming this is still not built-in functionality, right?
