### ISSUE TITLE
[MSVC] vcpkg : compile error for isnan&_isnan 

### ISSUE THREAD

**Issue by jeanga** [gabime/spdlog#901]
When compiling with vcpkg's x86-windows or x64-windows I get: 
f:\vcpkg\installed\x64-windows\include\fmt\format.h(288): error C2084: function 'fmt::v5::internal::dummy_int fmt::v5::internal::_isnan(...)' already has a body

Commenting the line solves the issue with no (apparent) consequences...

**Comment by gabime** [comment]
I suggest you open this issue in vcpkg repo instead.
