### ISSUE TITLE
ODR violation when using spdlog and fmt without -DSPDLOG_FMT_EXTERNAL

### ISSUE THREAD

**Issue by Quincunx271** [gabime/spdlog#904]
I spent the last few days tracking down a segfault that turned out to be an ODR violation because I was using spdlog and fmt without defining `SPDLOG_FMT_EXTERNAL`. I understand that this is documented, but it's still easy to run into this problem, and ODR violations are some of the worst bugs to debug.

In particular, I'm using the conan-spdlog package, which actually adds this flag if you use the conan `cmake` generator, but I was using `cmake_paths`, which uses this repository's `spdlogConfig.cmake`.

Is there something we can do to make this situation harder to fall into?

----

If we add an option to the cmake project which exports the `SPDLOG_FMT_EXTERNAL`, that would work (conan-spdlog could set that option):

```cmake
option(SPDLOG_FMT_EXTERNAL ...)

# ...

target_compile_definitions(spdlog
  INTERFACE
    $<$<BOOL:${SPDLOG_FMT_EXTERNAL}>:SPDLOG_FMT_EXTERNAL>
)
```

----

If we move the bundled fmt to a different namespace, that would also work, but it would be a breaking change. However, if the bundled fmt was in `namespace fmt { inline namespace spdlog { inline namespace v5 {`, that should work, because it would catch the ODR violation at link time. That might be possible by hijacking `FMT_BEGIN_NAMESPACE` and `FMT_END_NAMESPACE`.

**Comment by gabime** [comment]
I am not expert in conan, and not sure how to make it harder to fall in to, but it seems reasonable that coma. would install spdlog without the bundled fm. y deafult.. This is the way it is done by other pakacge managers like vcpkg.
