### ISSUE TITLE
How to safely create thread-safe loggers?

### ISSUE THREAD

**Issue by dmjones** [gabime/spdlog#905]
I have a class that may be constructed several times within an application and used from multiple threads.

Ideally, each class instance would call `_logger = spdlog::get("some_logger");` in the constructor (as advised in [the wiki](https://github.com/gabime/spdlog/wiki/2.-Creating-loggers). However, the first  instance would presumably get an empty shared pointer, since the logger doesn't exist yet.

Is there an idiomatic spdlog way to solve this issue? My concern is thread safety, because several threads could try and create this logger at the same time, resulting in errors from the registry.

I can add my own synchronisation with some kind of log-creation mutex, but I wondered if I'm overlooking something in the spdlog library?

**Comment by gabime** [comment]
Mutex seems good  way to do it safely, or maybe create the logger at main, before constructing any of those objects, so they can just assume the logger already exists.
