### ISSUE TITLE
No console outputs with stdout console sink

### ISSUE THREAD

**Issue by inspire1989** [gabime/spdlog#909]
Hi,

I'm using spdlog together with the ROS framework (http://www.ros.org/). That means I disabled ROS logging as far as possible and instead I just want to use spdlog. 

Until now I had spdlog 0.13.0 and it worked like charm! But since I updated to spdlog 1.2.1 all console outputs with the spdlog::stdout_color_st/mt logger sinks disappeared. The result in the console is: nothing. 

The spdlog::stderr_color_st/mt sinks are still working by the way.

Is there something that could prevent the std output stream from showing any data? I don't know what the ROS framework does in the background but as I said: with an older spdlog version it worked. Maybe there is a setting so I can get back the old stdout logging mechanism? 

Thanks in advance!
inspire

**Comment by gabime** [comment]
plaese show the code
