### ISSUE TITLE
async logger periodic flush

### ISSUE THREAD

**Issue by divaykin** [gabime/spdlog#91]
@gabime what do you think of periodical flush (on timer basis) in async worker? what's the best API to configure it?

**Comment by gabime** [comment]
why only on the async logger?

**Comment by divaykin** [comment]
because async has already a worker thread unlike normal loggers

**Comment by divaykin** [comment]
somewhere here https://github.com/gabime/spdlog/blob/master/include/spdlog/details/async_log_helper.h#L284 is a good place to do a flush. the only question is - what's the best way to set timespan length (X milliseconds)? with tweakme or yet another parameter of async logger?

**Comment by gabime** [comment]
Probably in the ctor..
And the code would reside in the ```async_log_helper::process_next_msg(..)``` function (in the empty queue section - there is no sense calling flush if there are messages in the queue which would trigger the flush operation anyway)

**Comment by divaykin** [comment]
done

**Comment by gabime** [comment]
Thanks @divaykin 

Does it work well ? Or is it confusing (the fact that it flushes only when empty queue)?

**Comment by divaykin** [comment]
@gabime seems fine, I use it only during debugging to see logs clearly right after the write
