### ISSUE TITLE
Wiki on printing custom classes through spdlog

### ISSUE THREAD

**Issue by jartu** [gabime/spdlog#910]
I have a hard time finding what exactly one has to do to simply print out one's own class using spdlog. 

For instance: 
My Logger.h class:
`
const std::shared_ptr<spdlog::logger> &log = spdlog::stdout_color_mt("console");
log->warn("My class: {}", my_class_instance);
`
gives me just a _/usr/local/include/spdlog/fmt/bundled/core.h:661:60: error: ‘fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>::formatter_type<Strategy>::type f’ has incomplete type_

It would be great to add this to the wiki which - as far as I can see - is still completely empty.

**Comment by gabime** [comment]
The example in the frontpage contains info about it (
https://github.com/gabime/spdlog#user-defined-types)

**Comment by jartu** [comment]
Oh, sorry, I missed that one. Thanks. Closing the issue.

**Comment by JoelWillLiveForever** [comment]
It's not working :(
