### ISSUE TITLE
Question: can I have a header for a log?

### ISSUE THREAD

**Issue by amno1** [gabime/spdlog#920]
I would like to use spdlog in a bit unusual manner: I need a rotating csv file writer. So I figured out I could simply use spdlog and dump my data as custom format into a rotating file log, eazy-peazy. But there seems to be a gotcha :-(: I need to dump column names in first row when a new file is created. Is there some way to do this with spdlog or do I have to go all custom route? Is there some kind "on new file" point where I can hack my header dumping code? I was looking around a bit, but I didn't found any suitable place yet :-). Any hint?

**Comment by gabime** [comment]
No such support yet. I suggest just copy/paste the rotating sink to a customized "csv_rotating_sink".

**Comment by amno1** [comment]
Thank you. I'll try that route.
