### ISSUE TITLE
[Feature request] Make default logging pattern tweakable (in tweakme.h?)

### ISSUE THREAD

**Issue by Stolij** [gabime/spdlog#922]
Adding an option to tweak the default logging pattern of Spdlog would be a very useful feature in my opinion. 

Maybe something like this?
```C++
///////////////////////////////////////////////////////////////////////////////
// Uncomment to modify the default Spdlog logging pattern
//
// #define SPDLOG_DEFAULT_PATTERN "[%Y-%m-%d %H:%M:%S.%e] [%n] [%l] %v"
///////////////////////////////////////////////////////////////////////////////
```

**Comment by gabime** [comment]
why?

**Comment by Stolij** [comment]
I thought it'd be a useful feature to be able to change the default pattern, instead of calling 'set_pattern' at the 'Main()' of every project.

Might just be my personal preference though.

**Comment by gabime** [comment]
If there is strong demand I will reconsider..In the meanime I close it.

**Comment by sonorhcnysa** [comment]
I too would like to set a custom format that will be applied to loggers/sinks that will be created in the future.  `spdlog::set_pattern(...)` appears to set the custom format only for sinks of loggers that already exist.
I think I would prefer a method rather than using a preprocessor definition.

**Comment by jfdoolster** [comment]
with multiple loggers used in my project, it is a little annoying to have to call `logger->set_pattern(fmt)` with the same `fmt` each time. it would be nice if there was a way to tweak `SPDLOG_DEFAULT_PATTERN` (using @Stolij syntax) at the start and then not worrying about it each time a new logger is created.
