### ISSUE TITLE
Question: Periodic flush

### ISSUE THREAD

**Issue by advaitraut** [gabime/spdlog#923]
Hi 
How to flush log messages periodically ?
Will the code such as `spdlog::flush_every(std::chrono::seconds(5))` apply 5 seconds periodic flush to all loggers ?
How to set attach flush interval with specific logger or with specific sink ?

**Comment by gabime** [comment]
> Will the code such as spdlog::flush_every(std::chrono::seconds(5)) apply 5 seconds periodic flush to all loggers ?

Yes

> How to set attach flush interval with specific logger or with specific sink ?

There is no such feature. You can try to use the [periodic_worker](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/details/periodic_worker.h) class to achieve it.
