### ISSUE TITLE
create/find loggers with same source

### ISSUE THREAD

**Issue by FerasOd** [gabime/spdlog#925]
I'm trying  to build a method where i can check if i can find a logger with the source that i have and if i didn't find it i want to create a logger with this source ,
if you could add an example of how to do it i will be thankful ,
for now that's what I'm trying to do :-

spdlog::logger *gSpdlogLogger = NULL;
Logger *LogManager::GetLogger(std::string source)
{
  if (spdlog::get(source) == NULL) {
       gSpdlogLogger = new spdlog::logger(source, { file_sink });
       spdlog::create<spdlog::sinks::basic_file_sink_mt>(source);
      ..... some code that does not concern  spdlog....
  }else{
       gSpdlogLogger = spdlog::get(source); 
       //i never get the same address of the pointer that was created previously 
       ..... some code that does not concern  spdlog....
  }
return gLogger;
}

**Comment by gabime** [comment]
You can use spdlog::create:
```c++
std::shared_ptr<spdlog::logger>gSpdlogLogger;
gSpdlogLogger = spdlog::get(source);
if (gSpdlogLogger == nullptr) {
   gSpdlogLogger = spdlog::create<spdlog::sinks::basic_file_sink_mt>(source, "log.txt");
}
```
