### ISSUE TITLE
Inclusion of CTest in CMakeLists.txt File Should be Guarded

### ISSUE THREAD

**Issue by dpacbach** [gabime/spdlog#927]
In the top-level CMakeLists.txt file we have:

include(CTest)

However, issuing this will automatically enable testing (and set BUILD_TESTING=ON) which we don't always want e.g. if we are using this repo as a git submodule in a parent project.

So I guess the request is, can we please only include CTest conditionally if SPDLOG_MASTER_PROJECT is ON (or maybe more correctly, if SPDLOG_BUILD_TESTING=ON)?

**Comment by gabime** [comment]
Sounds reasonable. Please open a pr

**Comment by dpacbach** [comment]
Will send one shortly; for additional justification, just wanted to point out an example of a popular project (from Google) that does this too:

https://github.com/abseil/abseil-cpp/blob/master/CMakeLists.txt#L81

In Abseil's CMakeLists.txt as you can see they include CTest only conditionally when test-building is requested.
