### ISSUE TITLE
How to support LOG << val1 << val2 << val3 << endl style

### ISSUE THREAD

**Issue by chengm349** [gabime/spdlog#938]
LOG could be a macro similar to SPDLOG_INFO for example

**Comment by gabime** [comment]
Support for streams was removed long time ago.

**Comment by chengm349** [comment]
I feel no simple/direct support. May I use fmt::memory_buffer to append int/char/double etc easily first.? then pass this buffered content to spdlog functions.

**Comment by chengm349** [comment]
>           Support for streams was removed long time ago.
sounds no similar requirement?

**Comment by chengm349** [comment]
>           if you insist on steams, you  can use std::ostringstream and pass the result to the logger.

ostingstream is slow. that's the issue.

**Comment by chengm349** [comment]
> > ```
> >       Support for streams was removed long time ago.
> > ```
> 
> sounds no similar requirement?

any there are ton of legacy code using stream way. I am doing replacement now. We can't change all lines,

**Comment by gabime** [comment]
ok. good luck.
