### ISSUE TITLE
Did something changed in `simple_file_sink` ?

### ISSUE THREAD

**Issue by gnzlbg** [gabime/spdlog#94]
Hi the latest commits break my builds with the following error:

```bash
error: field type 'spdlog::sinks::simple_file_sink<spdlog::details::null_mutex>' 
is an abstract class

...

spdlog/include/spdlog/sinks/../details/../sinks/sink.h:38:18: 
note: unimplemented pure virtual method 'flush' in 'simple_file_sink'
    virtual void flush() = 0;
                 ^
```

when doing:

`std::make_shared<spdlog::sinks::simple_file_sink_st>(name + ".log", false);`

If `spdlog::sinks::simple_file_sink_st` is deprecated maybe it could be better to mark it with an attribute containing how to fix it and maybe the reason: `[[deprecated("reason + how to fix it")]]`.

**Comment by gabime** [comment]
This is a bug relating to latest commit that added flush feature.. 
Thanks for reporting. will be fixed soon
