### ISSUE TITLE
Avoid formatting in the binary output

### ISSUE THREAD

**Issue by larytet** [gabime/spdlog#942]
We do not have to output constant format strings at all in the binary format. There are two possibilities

* Collect the constant strings (format strings) in the compilation phase, create a table of all format strings, use constexpr hash of the filename and source line as a key in the table. When decompressing the binary stream look for the format strings in the table or in the source code itself. Example https://github.com/larytet/emcpp/blob/master/src/Log.h#L98
* Cache the format string using the address of the string as a key. The idea is that linker places constant strings in one place - .text section of the executable. If the address is not belonging to the .text hashtable which uses the format string hash will do.  Example (Go): https://github.com/larytet/binlog 

In the first approach application does not analyse the format strings. In the first approach format strings will not be part of the executable file (the .text section of the ELF is going to be smaller). 

In the second approach the application analyses every format string once, keeps all required for output to the binary stream information. 

In both approaches the application outputs only variadic arguments.

Both approaches limit the application to use immutable format strings, and, for the best performance, constant strings. The upside is x2-x4 performance gain and a smaller log.

**Comment by gabime** [comment]
> We do not have to output constant format strings at all in the binary forma

No sure I understand what is  the binary format.
What is the use case ? sending log data to a different process ?

**Comment by larytet** [comment]
When logging binary data I have two objectives

* Less log data, smaller log files, less I/O load
* Faster processing

I can keep log in the binary format (encoded) and "decode" the log on demand.
