### ISSUE TITLE
Detele spdlog text file after each hour

### ISSUE THREAD

**Issue by dakiwaki** [gabime/spdlog#943]
I am using this code. My speed log_file which is output.txt file get larger and larger. I want to delet my log after each hour so that it creates a new log_file. Any idea how to achieve this ? 

 log::init() {
    /// Set up multisink logger instance ///
    std::vector<spd::sink_ptr> sinks;
    sinks.emplace_back(std::make_shared<spd::sinks::ansicolor_stdout_sink_mt>());
    sinks.emplace_back(std::make_shared<spd::sinks::simple_file_sink_mt>(log_file));
    handle = spd::create(logger_name, sinks.begin(), sinks.end());
}

**Comment by gabime** [comment]
you should use rotating sink
