### ISSUE TITLE
Template stream operator not working

### ISSUE THREAD

**Issue by gruo** [gabime/spdlog#944]
When I declare the stream operator for all my custom classes of a namespace like this

    template <class T>
    auto operator<<(std::ostream &os, const T &t) noexcept -> decltype(t.print(os), os) {
        t.print(os);
        return os;
    }

the compiler puts an error like 
`static_assert failed due to requirement 'no_formatter_error<Container>::value' "don't know how to format the type, include fmt/ostream.h if it provides an operator<< that should be used" [clang-diagnostic-error]`

although I included `#include "spdlog/fmt/ostr.h"` as specified in the documentation. If I implement the output stream operator in the target class all works fine (but it clashes with the template method). Is this solution compatible? I would like to not implement the operator on every class.

(Note that the above snippet is not added to the classes header but the libraries one. Streaming an object works flawlessly.)

**Comment by gabime** [comment]
> (Note that the above snippet is not added to the classes header but the libraries one. Streaming an object works flawlessly.)

What do you mean?

**Comment by gruo** [comment]
Small example (out of my head):

In file `b.h`:

    #include "lib.h"
    
    namespace A {
    class B {
        void print(std::ostream &os) {
            os << "this is class B" << '\n';
        }
    };
    }

In file `lib.h`:

    namespace A {
    template <class T>
    auto operator<<(std::ostream &os, const T &t) noexcept -> decltype(t.print(os), os) {
        t.print(os);
        return os;
    }
    }

And a `main.cpp`:

    #include "b.h"
    
    int main() {
        B b;
        std::cout << b;
        
        return 0;
    }

This is the overall working structure without some stdlib includes. Hope this helps clearify the topic.

**Comment by gabime** [comment]
I am not sure. Please refer to the fmt docs about it (http://fmtlib.net/latest/api.html#custom-formatting-of-built-in-types)
