### ISSUE TITLE
missing overflow policy discard_log_msg

### ISSUE THREAD

**Issue by 7starsea** [gabime/spdlog#946]
In the newer v1.x branch, we only have two queue policy: block and overrun_oldest.
I am missing the policy discard_log_msg, I think from the point of message, overrun_oldest policy is equivalent discard_log_msg, since there are always some message lost. However, discard_log_msg policy maybe faster then overrun_oldest policy? ( I am not sure).

Thanks.
Aimin

**Comment by gabime** [comment]
It's not equivalent - ```overrun_oldest``` policy overrides oldest message with the new one, while ```discard_log_msg``` was discarding the new message instead of oldest one.
