### ISSUE TITLE
Create classic logger pointer instead of std::shared_ptr<spdlog::logger>

### ISSUE THREAD

**Issue by Xydez** [gabime/spdlog#951]
Hey! I just wondered how I would go about creating a classic `spdlog::logger*` instead of a `std::shared_ptr<spdlog::logger>`, and more importantly how I would use this in combination with the sinks. Is this a feature that already exists, or is `std::shared:ptr` a requirement? I need a pointer because I'm creating a wrapper class and don't want to include the `<memory>` header. Thanks for any help!

**Comment by gabime** [comment]
They must be shared ptrs

**Comment by Xydez** [comment]
How would I then create a multithreaded stdout color logger? Mind giving an example?

**Comment by gabime** [comment]
please see the docs (https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#creating-loggers-manually)

**Comment by Xydez** [comment]
Do I have to create a shared_ptr of the sink to create the logger? Any way to avoid this? The wiki is a little unclear.

**Comment by gabime** [comment]
no, you can pass it later using the sinks() function
