### ISSUE TITLE
Default thread pool does not appear to exist

### ISSUE THREAD

**Issue by spiderkeys** [gabime/spdlog#952]
Reading through the wiki section on Async Loggers, the wording makes it sound as if there should exist a thread pool created with default settings:
> by default, spdlog create a global thread pool with queue size of 8192 and 1 worker thread which to serve all async loggers.

However, when trying to create a logger in the following manner, without having first called init_thread_pool(), I get:
> [*** LOG ERROR ***] [2018-12-31 23:47:51] [example] async log: thread pool doesn't exist anymore

My code which produces this error:
```c++
auto path = boost::filesystem::path( m_dir ) / boost::filesystem::path( m_name );

// Create multiple sinks
std::vector<spdlog::sink_ptr> sinks;

auto rotating_file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>( path.string(), maxLogSizeBytes, maxLogCount );
rotating_file_sink->set_level(spdlog::level::info);

auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
stdout_sink->set_level(spdlog::level::info);

sinks.push_back( rotating_file_sink );
sinks.push_back( stdout_sink );

m_logger = std::make_shared<spdlog::async_logger>( m_name, std::begin( sinks ), std::end( sinks ), spdlog::thread_pool(), spdlog::async_overflow_policy::overrun_oldest );

m_logger->flush_on( spdlog::level::err ); 

spdlog::register_logger( m_logger );
```
Presumably, this is because the call to spdlog::thread_pool()
```c++
// get the global thread pool.
inline std::shared_ptr<spdlog::details::thread_pool> thread_pool()
{
    return details::registry::instance().get_tp();
}
```
ends up returning a null shared_ptr, as the tp_ member of the registry class is only created in one of two ways, 1) you explicitly call init_thread_pool(), or 2) you create the async logger using the async_create factory methods. When creating a standalone sink, as in my code, the init code that the async factory method uses is not employed.

Perhaps this is by design? Would it be possible to create the default thread pool in the constructor of the registry class?

**Comment by gabime** [comment]
The wiki could be more clear. One need to call init_thread_pool  before trying to use the global pool.
Please note that you can create your own instance of thread-pool and pass it to the ctor. There is no requirement to use the global one.
