### ISSUE TITLE
user's callback for rotating logger

### ISSUE THREAD

**Issue by kiryazovi** [gabime/spdlog#954]
This is referencing:
https://github.com/gabime/spdlog/issues/155

Hi,

Are you still interested with adding a callback for rotating logger?

I have a use case where I need:

Log compression.
And writing header and footer messages when compressing.

I saw in the thread that there was a pull request.
https://github.com/gabime/spdlog/pull/489
But its development  seems to be discontinued.

I am ok to take the pull request and continue development on it so that both sides are happy with the idea.

**Comment by gabime** [comment]
Ok, lets give it another shot.

**Comment by kiryazovi** [comment]
Hello, 

After a brief discussion with people from my team,
I'd like to give you a heads up as to how the change would look:
I'm thinking of adding three callbacks:
One for doing something before rotating (the users might want to do something with the files the moment they are opened.) - in our case we'd like to add a Header message.
One for doing something after rotating files (the moment a file handle is released) - in our case we'd like compressing and adding a Footer Message.
One for adding any functionality when the files are not touched. An example is scanning for file indexes.

I'd also like to make it so the user is not obligated to use the callback functionality.

Please if you disagree or have other vision of this write back, so we can reach a solution helpful for both of us.

Thanks.

**Comment by gabime** [comment]
> One for adding any functionality when the files are not touched. An example is scanning for file indexes.

When would it be called ?

**Comment by kiryazovi** [comment]
Sorry for late reply.
So after some thought, we found a better solution that should have an even lighter impact:
One callback which substitutes the rotate() call.
The point is that that way we are giving power to the user to do however he/she pleases with the rotate.
And that way we won't change the way that the current rotating logger works.
I will show you a diff suggestion hopefully next week as we are running local tests to check if this solution is best.
