### ISSUE TITLE
Pattern string width formatting for log level doesn't seem to work

### ISSUE THREAD

**Issue by btmcg** [gabime/spdlog#957]
When following the wiki, and setting the pattern as follows:
`logger->set_pattern("%Y-%m-%d %H:%M:%S.%f %-8l [%n] %v");`
I get the following:
`2019-01-11 07:30:56.657157 %-8l [main] on_connect: TCP connection successful`

By removing the width argument of `-8`, the log level is again printed
`2019-01-11 07:25:20.106566 info [main] on_connect: TCP connection successful`

**Comment by gabime** [comment]
You need to use the latest version from the trunk for this.

**Comment by btmcg** [comment]
Hmm... I'm seeing the same results with v1.3.0.
