### ISSUE TITLE
depending on the order of inclusion

### ISSUE THREAD

**Issue by gocarlos** [gabime/spdlog#959]
Right now spdlog depends on the order of inclusion: 

previously (v0.17) we could add 
```cpp
#include "spdlog/spdlog.h"
```
and we could use 
```cpp
auto logger = spdlog::stdout_color_mt(name);
```

now (v1.3.0) it seems like that we also have to include 
```cpp
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/spdlog.h"
```
now this breaks the compilation with the error 
```txt
#error "spdlog.h must be included before this file."
```
one has to rearrange the order of the includes... which is againts the google style guide(which a lot of people use with clang-format)

One solution for that could be to check the existence of the header as now and include it if not done already... 

ref: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Comment by gabime** [comment]
Fixed. Thanks.
