### ISSUE TITLE
Logging variables

### ISSUE THREAD

**Issue by codingbug123** [gabime/spdlog#964]
I'm probably just doing something wrong, but I can't find what it is. When I try to log a variable using this code:

	spdlog::info("Support for floats {:03.2f}", 1.23456);

I get this error: 2>c:\users\predator\source\repos\hazel\hazel\vendor\spdlog\include\spdlog\details\logger_impl.h(71): fatal error C1001: An internal error has occurred in the compiler.

I include "spdlog/spdlog.h"

However if I comment out part of the code everything works just fine, so if I do either of these:

	spdlog::info("Support for floats {:03.2f}");
	spdlog::info(1.23456);

everything works just fine. Any help would be much appreciated.

**Comment by gabime** [comment]
https://stackoverflow.com/questions/7076494/fatal-error-c1001-an-internal-error-has-occurred-in-the-compiler

There are some advices there to fix it.
