### ISSUE TITLE
SIGSEGV after spdlog::get("my_logger")

### ISSUE THREAD

**Issue by gusev-vitaliy** [gabime/spdlog#965]
spd::get(const std::string &name) interface should raise exception when logger with *name* does not exist.
Instead, spdlog::get() returns nullptr and ALL examples in spdlog's papers are done without any protection:

   // Return an existing logger or nullptr if a logger with such name doesn't                                                                             
  // exist.                                                                                                                                              
  // example: spdlog::get("my_logger")->info("hello {}", "world");

This successfully introduces SIGSEGV in spdlog::logger::should_log()

Segmentation fault can not be handled right, but exception can. Check on nullptr is not usable or should be added to ALL examples.

**Comment by gabime** [comment]
This is by design. Sometimes a user just want to check if such logger exists before creating it. 
About the the examples, they dont check because there is no reason for it. If your know that your code created the logger just few lines before, there is no point for checking.
