### ISSUE TITLE
Getting filename sink is pointed to

### ISSUE THREAD

**Issue by markniebur** [gabime/spdlog#968]
Hello, I am trying to share the same file sink between multiple loggers, but I would like to use the sink pointers that are held by a given logger instead of maintaining a list of my own.  I know I can iterate the vector of sinks in a logger, but cannot find out what the filename it is using because it's private.  Can that detail be exposed in the API?  I'm happy to submit a PR to do it if it's something desirable.

**Comment by gabime** [comment]
Which specific file sink type? there are several types of file sinks. 
Maybe its better to expose the filename in all of them for sake of completness.

**Comment by markniebur** [comment]
I was using the basic file sink, with something like the daily rotating sink, I suppose you may want to know both, the base file name and the current open file name.  The same method name should be shared for the file sinks, my guess would be that it would be for the file name passed in to the constructor, and an additional method to return the calculated file name.

**Comment by gabime** [comment]
The file_helper member already has ```const filename_t &filename() const```. All that is needed is to expose in the sinks.

**Comment by markniebur** [comment]
In the case of the rotating sinks, I can think of use-cases where you'd want to know both, the current file name and the base file name.

**Comment by markniebur** [comment]
In the case that you are trying to retrieve the sink pointer from a logger, getting the whole filename instead of the base filename would make the comparison more difficult than necessary.
In the case that you are trying to identify the file a given sink is writing to, it would be useful to have the actual filename.
