### ISSUE TITLE
spdlog not printing message if SPDLOG_NO_THREAD_ID is defined

### ISSUE THREAD

**Issue by stkw0** [gabime/spdlog#970]
If SPDLOG_NO_THREAD_ID is defined then messages are not show.

For a test case example/example.cpp can be used. I tested it under Linux with GCC 8.

This error happens only with version 1.3.0.

**Comment by scribam** [comment]
Fixed in branch `v1.x`, see #969

**Comment by stkw0** [comment]
Oh, I see, thanks.
