### ISSUE TITLE
Does %# and %s in custom formatting really work?

### ISSUE THREAD

**Issue by Guptajakala** [gabime/spdlog#972]
It is mentioned here:
https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

But when I use it, 

```
spdlog::set_pattern("%^[%H:%M:%S.%e][%s:%#]%$ %v");
spdlog::info("hello!");  
```
It does not show file name and line number:
`[20:12:36.574][%s:%#]  hello!`

**Comment by gabime** [comment]
you must use the macros for this (e.g. SPDLOG_INFO(..))

**Comment by Guptajakala** [comment]
@gabime Here is my implementation using SPDLOG_TRACE, it still does not work. 
```
auto console = spdlog::stderr_color_mt("console");
console->set_level(spdlog::level::trace);
console->set_pattern("%^[%H:%M:%S.%e][%s:%#] %v%$");
SPDLOG_TRACE(console,"Welcome!");
```

**Comment by Guptajakala** [comment]
@gabime never mind, I found the problem. I dont need to set pattern in that case.
