### ISSUE TITLE
Custom formatter to use my own timestamp

### ISSUE THREAD

**Issue by devhandle** [gabime/spdlog#974]
**QUESTION**

I would like spdlog to use my own generated timestamp. I believe the correct way to do this is using a custom formatter - i.e. inherit from _formatter_ class. 

I was unable to find an example on how to do this. 

Is it possible for me to use my own timestamp? If so, does anyone have an example piece of code which does this?

Thanks in advance.

**Comment by gabime** [comment]
You can try to replace the spldog::log_clock in 
https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/common.h with your own imlementation.

**Comment by gabime** [comment]
If you really want custom formatter, you neec to implement the formatter interface (
https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/formatter.h)

**Comment by devhandle** [comment]
I tried to use a custom formatter by copying the `pattern_formatter` and modifying it slightly  (I've added a new flag to `handle_flag_` ) but calling set_pattern reinstates the `pattern_formatter` and my custom formatter is never called. Am I doing something wrong or is this a bug?


```
inline void spdlog::logger::set_pattern(std::string pattern, pattern_time_type time_type)
{
    auto new_formatter = details::make_unique<spdlog::**pattern_formatter**>(std::move(pattern), time_type);
    set_formatter(std::move(new_formatter));
}
```
