### ISSUE TITLE
SPDLOG_FMT_PRINTF removed from v1.x branch

### ISSUE THREAD

**Issue by devhandle** [gabime/spdlog#976]
**QUESTION**

I was working against the master branch but noticed it's not up to date. Since switching to the v1.x branch I've noticed that _SPDLOG_FMT_PRINTF_ has been removed. Has printf support been removed altogether?  There isn't an associated merge request with the commit which removed this macro.

Thanks in advance.

**Comment by gabime** [comment]
yes, it was removed fron the v1.x branch long time ago.
