### ISSUE TITLE
dist_sink mutex may not be "safe"

### ISSUE THREAD

**Issue by jveber** [gabime/spdlog#979]
in "disk_sink.h"

    void add_sink(std::shared_ptr<sink> sink)
    {
        std::lock_guard<Mutex> lock(base_sink<Mutex>::mutex_);
        sinks_.push_back(sink);
    }

    void remove_sink(std::shared_ptr<sink> sink)
    {
        std::lock_guard<Mutex> lock(base_sink<Mutex>::mutex_);
        sinks_.erase(std::remove(sinks_.begin(), sinks_.end(), sink), sinks_.end());
    }

both are locked with mutex but:

    void sink_it_(const details::log_msg &msg) override
    {

        for (auto &sink : sinks_)
        {
            if (sink->should_log(msg.level))
            {
                sink->log(msg);
            }
        }
    }

    void flush_() override
    {
        for (auto &sink : sinks_)
        {
            sink->flush();
        }
    }

are not. 

Noone can guarantee that the vector sinks_ wont change during sink_it() and flush() by using add_sink() or remove_sink() from another thread. This might cause nasty random crashes of the program that use dist_sink_mt and that changes sinks in runtime.

I understand that mutex in sink_it() would slow down the method a bit, but it is also pissible to use multi-sink logger for those who need faster sink_it().

I'd advise you to either add mutex before cycle in snik_it() and flush() or introduce some kind of dynamic lock-free container insted of vector for sinks_ for mt version. Also there is a way to drop the mt version of disk_sink,

**Comment by gabime** [comment]
Right. Thanks for noticing. 
```dist_sink``` should indeed be completely thread safe.

**Comment by gabime** [comment]
I totally forgot that it actually inherits from  ```base_sink<Mutex>``` so it is safe (the logger calls ```base_sink_::sink_it``` which locks and calls ```dist_sinks::sink_it(..)```)
