### ISSUE TITLE
Use of deprecated function call (result_of)

### ISSUE THREAD

**Issue by ITNano** [gabime/spdlog#983]
This is just a minor issue but I thought I ought to mention it anyway. The core.h file contains calls to the deprecated function result_of. result_of has been deprecated based on [these reasons](https://en.cppreference.com/w/cpp/types/result_of#Notes) and should not be used. std::invoke_result is the preferred method instead.

```
... spdlog/fmt/bundled/core.h:215:25: error: 'result_of<fmt::v5::internal::precision_checker<fmt::v5::internal::error_handler> (int)>' is deprecated: warning STL4014: std::result_of and std::result_of_t are deprecated in C++17. They are superseded by std::invoke_result and std::invoke_result_t. You can define _SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning. [clang-diagnostic-deprecated-declarations]
  typedef typename std::result_of<
```

**Comment by DanielChabrowski** [comment]
It should be reported to fmt repository instead. It looks like they still use it on master branch.

**Comment by ITNano** [comment]
Thanks for your fast reply. I close this issue and open it in the fmt repo instead.
