### ISSUE TITLE
windows: rotating_file_sink: failed renaming

### ISSUE THREAD

**Issue by htonus** [gabime/spdlog#987]
Hello! 
Created logger by:
`spd::rotating_logger_mt<spd::async_factory>("MyLogger", "log\\mylog.txt", 5000, 1);`

In some time always get following error:
`[*** LOG ERROR ***] [2019-02-05 00:11:32] [MyLogger] rotating_file_sink: failed renaming logs\mylog.txt to logs\mylog.1.txt: Permission denied`

The file itself has all permissions required for the action.

**Comment by gabime** [comment]
Do you have antivirus turned on? I saw this happening under windows with AV.

**Comment by gabime** [comment]
as a workaround try to increase the 5000to something bigger. e.g. to 1024*500

**Comment by htonus** [comment]
That was 2M when first happened and takes too long to re-produce. So the size was reduced to speed up the issue to happen.

**Comment by htonus** [comment]
Tried to add my app to exclusions and disabled AV totally - doesn't solve the issue.

**Comment by gabime** [comment]
And the setup vbox host with win10 guest? spdlog compiled with msvc?

**Comment by htonus** [comment]
I compile my app in VS2017CE, Windows 1809, Build 17763.253. Hosting OS. But the issue happens with app in VM, will try to reproduce on hosting system.

**Comment by gabime** [comment]
spdlobeg v1.3?

**Comment by htonus** [comment]
```
c:\work\c++\vcpkg>vcpkg.exe list
fmt:x64-windows                                    5.3.0            Formatting library for C++. It can be used as a ...
fmt:x86-windows                                    5.3.0            Formatting library for C++. It can be used as a ...
openssl-windows:x64-windows                        1.0.2q           OpenSSL is an open source project that provides ...
openssl-windows:x86-windows                        1.0.2q           OpenSSL is an open source project that provides ...
openssl:x64-windows                                0                OpenSSL is an open source project that provides ...
openssl:x86-windows                                0                OpenSSL is an open source project that provides ...
spdlog:x64-windows                                 1.3.1            Very fast, header only, C++ logging library
spdlog:x86-windows                                 1.3.1            Very fast, header only, C++ logging library
```

**Comment by gabime** [comment]
Can't reproduce

**Comment by artemyv** [comment]
I can describe one of the scenarios where it happend for me. I'm using log from service. So log file is created as system. But some function use user impersonation. So this parts write to log as user. If the rotation is happening while such function tries to write to log rotate function will fail to rename file.

**Comment by Cleroth** [comment]
Had this problem too. Using Process Hacker I was able to determine the handle was being opened and staying open by a third-party library I'm using (Live++).

**Comment by mb10-hub** [comment]
What third party library are you using?

**Comment by Cleroth** [comment]
Live++, as I said.
