### ISSUE TITLE
Windows Event Log Support

### ISSUE THREAD

**Issue by sinainnet** [gabime/spdlog#989]
Hi,

I'm curious to know if there is any implementation of sink in SPDLOG based on Windows event log. I will be grateful if anyone let me know.

Thanks

**Comment by howar6hill** [comment]
@gabime Is this feature still needed? If yes, I want to help on this.

**Comment by gabime** [comment]
Its nice to have. Thanks !

**Comment by TheQwertiest** [comment]
Shouldn't this be fixed by #1418 ?

**Comment by gabime** [comment]
Right. Closing..

**Comment by gabime** [comment]
Fixed in #1418
