### ISSUE TITLE
Losing data during file rollover

### ISSUE THREAD

**Issue by rayz55** [gabime/spdlog#991]
I have a CLI test app compiled with Visual Studio 17 Community Edition. Compile and execution are on Windows 10 with i7 CPU. In main(), I create a shared  file sink, rotating between 2 files of size 5000. Then I start a separate thread which opens another instance using the same log file sink. Both threads write a short string to the log file each 500ms. When I examine the two files after the app ends, about 20 seconds of data is missing.

`
#include "spdlog/spdlog.h"
#include "spdlog/sinks/rotating_file_sink.h"

static shared_ptr<spdlog::logger> mainlog;

main()
{
    auto sharedFileSink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("test", 5000, 2);
    // all log file entries produced by main() will be tagged with "main".
    // each subsystem will log to the same file, but with different tags.
    mainlog = std::make_shared<spdlog::logger>("main", sharedFileSink);

    // create subsystem threads; share cfg info, log file.
    Subsystem   PnP(CfgInfo, "PnP", sharedFileSink, PnPSendQue, PnPRecvQue);

    size_t  loop_cnt = 0;
    while (!quitting)
    {
    // send message to PnP thread and wait here for response (details omitted)
    mainlog->info("Servo Status {}, State {}, cnt={}", pData->ServoStatus, pData->SubState, loop_cnt++);
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
    }
`
The PnP thread gets an instance of the log, then waits for the message from main().
`
PnP_main()
{
    // get handle to log file created in main
    logger = std::make_shared<spdlog::logger>("PnP", log_file_sink);

    while (!quitting)
    {
    // wait for message from main and respond (details omitted)
    logger->debug("PnP state #{}", m_state);
    }
}
`
If I let this run for a minute or so, I get files "test.log" (newest) and "test.2.log" (oldest)
The last few lines of test.2.log are:
2019-02-07 09:37:03.224 main     [I] Servo Status 0, State 0, cnt=60
2019-02-07 09:37:03.716 PnP      [D] PnP state #1
2019-02-07 09:37:03.719 main     [I] Servo Status 0, State 1, cnt=61
2019-02-07 09:37:04.217 PnP      [D] PnP state #2
2019-02-07 09:37:04.225 main     [I] Servo Status 0, State 2, cnt=62
2019-02-07 09:37:04.718 PnP      [D] PnP state #3
The first lines of test.log are:
2019-02-07 09:37:25.260 main     [I] Servo Status 0, State 4, cnt=104
2019-02-07 09:37:25.759 PnP      [D] PnP state #0
2019-02-07 09:37:25.761 main     [I] Servo Status 0, State 0, cnt=105
2019-02-07 09:37:26.260 PnP      [D] PnP state #1
2019-02-07 09:37:26.267 main     [I] Servo Status 0, State 1, cnt=106
2019-02-07 09:37:26.761 PnP      [D] PnP state #2

I can't figure out where the missing 20 seconds of data went.

**Comment by gabime** [comment]
Please provide a reproducible example. It's hard to understand what's going on from your example.

**Comment by rayz55** [comment]
My apologies! When I ran the tests for a couple minutes then closed the app, my file management utility showed only test.log and test.2.log. After working on other things for an hour then coming back to this, it now also shows test.1.log, which contains the missing data.
Sorry to waste your time and thanks for a great utility!

**Comment by gabime** [comment]
Good. Thanks for the update.
