### ISSUE TITLE
Wiki "2. Creating loggers" refers to non-existant spdlog::sinks::simple_file_sink_mt

### ISSUE THREAD

**Issue by tambry** [gabime/spdlog#995]
In particular [the last section](https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#creating-multiple-file-loggers-with-the-same-output-file) contains the following code:
```c++
auto sharedFileSink = std::make_shared<spdlog::sinks::simple_file_sink_mt>("fileName.txt");
```

However, `spdlog::sinks::simple_file_sink_mt` doesn't seem to exists anywhere.

**Comment by gabime** [comment]
Fixed. Thanks @tambry
