### ISSUE TITLE
Build error moving from an old version (0.13.0 -> 1.3.1)

### ISSUE THREAD

**Issue by wolf1792** [gabime/spdlog#997]
Hi,
i was trying to update the library version in my project.
I was using the version 0.13.0 and everything was fine,
so i was wondering if i'm missing something cause switching to new version 1.3.1 results in these compile errors:

`1>.\include\spdlog\fmt\bundled\format.h(1708): error C2059: syntax error: 'constant'`
`1>.\include\spdlog\fmt\bundled\format.h(1727): note: see reference to class template instantiation 'fmt::v5::internal::arg_ref<Char>' being compiled`
`1>.\include\spdlog\fmt\bundled\format.h(1708): error C3805: 'constant': unexpected token, expected either '}' or a ','`

I already did the necessesaries updates to the code adding the right include and using new factories
(	
`auto std_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>("name");`
instead of 
`auto std_sink = std::make_shared<spdlog::sinks::simple_file_sink_mt>("name");`
ecc...
)

A basic example compiles just fine, of course.

What else can i check in my code?

Thank you for your help.

**Comment by gabime** [comment]
please provide the code sample

**Comment by wolf1792** [comment]
Sorry, found it, but this kind of compile error are everything but clear.
There was a 
`#define INDEX 1`
somewhere else that was conflicting with the enum 
`enum Kind { NONE, INDEX, NAME };`
Close.
